= Other Setup

. https://git-scm.com/downloads[Download and install git].
. Setup your user name and email.
+
[source,bash]
----
git config --global user.name "John Smith"
git config --global user.email "john@example.com"
----
. Setup your default text editor.
+
[source,bash]
----
git config --global core.editor vim
----
+
[IMPORTANT]
====
At this stage, if you were to commit to a project, there would be no way to tell if you are _really_ John Smith. In fact, you could be anybody claiming to be John Smith. In the same way that online document signing applications allow you to verify you are _you_, you can create a GPG key, upload it to GitHub, and automatically _sign_ your commits so creators _know_ it comes from you. To do so, continue on.
====
+
. Install https://brew.sh/[Homebrew].
. Install `gpg2` by running: `brew install gpg2`.
. Install gpgtools from https://gpgtools.org/[GPGTools].
+
. Open a terminal and type the following.
+
[source,bash]
----
gpg --full-generate-key --expert
----
+
. Select `ECC (sign only)` in the first prompt, and `Curve 25519` for the second. Choose how many years you'd like your key to be valid for, and enter the information as you are prompted.
+
[NOTE]
====
It is recommended to _not_ use a passphrase if you want to have your commits automatically signed when using GitHub Desktop. Otherwise, you will need to run the following in a terminal before you can commit to the project.

[source,bash]
----
export GPG_TTY=$(tty)
----
====
+
. When complete, you can print the public key by running the following.
+
[source,bash]
----
gpg --export -a "John Smith"
----
+
[IMPORTANT]
====
Make sure your replace "John Smith" with the user name you provided when creating the key.
====
+
. Copy the public key to your clipboard, navigate to https://github.com, and sign in. Click on your profile in the upper right-hand corner of the screen and navigate to btn:[Settings]. On the left-hand menu, click btn:[SSH and GPG keys] and then btn:[New GPG key]. Paste your public key in the provided text area and click btn:[Add GPG key].
+
. Lastly, in order to sign commits using the newly created key, open up a text editor and modify `$HOME/.gitconfig` to use your key. 
+
[source,toml]
----
[user]
    name = John Smith
    email = john@example.com
    signingkey = ABCDEFGHIJKLMNOP
[gpg]
    program = /usr/local/bin/gpg (or other path to `gpg` executable)
[commit]
    gpgsign = true
----
+
[TIP]
====
To get your signing key, run the following.

[source,bash]
----
gpg --list-secret-keys --keyid-format=long
----

Your signing key is the 16 character value following `ed25519/` on the `sec` line.
====
