= Data

Data comes in so many different formats, and each format has its own set of rules and tooling surrounding it. Here, we've curated a list of formats that we think every data scientist should have at least a cursory exposure to. 

Do you have another data format that you think should be included? Please feel free to xref:book:ROOT:how-to-contribute.adoc[make a contribution]. See a mistake? Please https://github.com/TheDataMine/the-examples-book/issues[open an issue] and we will get to it as soon as possible.

* xref:data-formats/html.adoc[HTML]
* xref:data-formats/xml.adoc[XML]
* xref:data-formats/json.adoc[json]
* xref:data-formats/csv.adoc[csv]
* xref:data-formats/yaml.adoc[yaml]
* xref:data-formats/toml.adoc[toml]
* xref:data-formats/parquet.adoc[parquet]
* xref:data-formats/feather.adoc[feather]
* xref:data-formats/vcf.adoc[VCF]
* xref:data-formats/las.adoc[LAS]
* xref:data-formats/stl.adoc[STL]
* xref:data-formats/messagepack.adoc[MessagePack]
* xref:data-formats/protobuf.adoc[Protobuf]
