= TDM 10200: Project 14 -- Spring 2026

**Motivation:** We covered a _lot_ this semester! From basic paradigms of `Python` as a language, to concepts about working with data, we hope that you have had the opportunity to learn a lot, and to improve your data science skills. For our final project of the semester, we want to provide you with the opportunity to give us your feedback on how we connected different concepts, built up skills, and incorporated real-world data throughout the semester, along with showcasing the skills you learned throughout the past 13 projects!

**Context:** This last project asks students to reflect on your work from the semester.

**Scope:** Python, Data Science

.Learning Objectives:
****
- Reflect on the semester's content as a whole
- Offer your thoughts on how the class could be improved in the future
****

Please use the regular project template to submit your feedback in Gradescope, as usual.

[[ai-note]]
[IMPORTANT]
====
If AI is used in any cases, such as for debugging, research, etc., we now require that you submit a link to the entire chat history. For example, if you used ChatGPT, there is an “Share” option in the conversation sidebar. Click on “Create Link” and please add the shareable link as a part of your citation.

The project template in the Examples Book now has a “Link to AI Chat History” section; please have this included in all your projects. If you did not use any AI tools, you may write “None”.

We allow using AI for learning purposes; however, all submitted materials (code, comments, and explanations) must all be your own work and in your own words. No content or ideas should be directly applied or copy pasted to your projects. Please refer to https://the-examples-book.com/projects/spring2026/syllabus#guidance-on-generative-ai[GenAI page] in the example book. Failing to follow these guidelines is considered as academic dishonesty.
====

== Questions

=== Question 1 (2 pts)

We would appreciate a short reflection (1-2 paragraphs) on the positive aspects of your experience in The Data Mine.

.Deliverables
====
What have you found most valuable about The Data Mine? You may consider topics such as:

- technical content (DS concepts, tools, methodologies)
- hands-on/project-based learning
- teamwork and learning community
- preparation for internships or careers
- development of best practices

Please share specific examples when possible.
====

=== Question 2 (2 pts)

We welcome your feedback on how The Data Mine experience could be improved.

.Deliverables
====
What changes would you suggest for The Data Mine? You may consider areas such as:

- course structure or organization
- technical content and tools
- project design or expectations
- workload and pacing
- alignment with your major, the College of Science curriculum, or the Data Science Certificate

Both constructive and critical feedback are encouraged. Please share specific suggestions or examples when possible.
====

=== Question 3 (2 pts)

How does The Data Mine fill some gaps in your Purdue experience?  In what ways would you miss The Data Mine if it was not available?

Please reflect on how your Purdue experience would differ with and without The Data Mine.

.Deliverables
====
Please contrast your Purdue experience with-and-without The Data Mine, in other words, help us understand what gaps that The Data Mine fills in your Purdue curriculum.  This will help us to better understand how The Data Mine fits into your learning and professional development.  

What would you miss the most, if The Data Mine had not been available?
====

=== Question 4 (2 pts)

Any additional feedback for the faculty or staff?

.Deliverables
====
If you have additional feedback and insights for the Purdue faculty, staff, and administration, we would really appreciate your insights.  All feedback is welcome!
====

=== Question 5 (2 pts)

Please identify 3 skills or topics related to the Python language or data science (in general) that you wish we had covered in our projects. For each, please provide an example that illustrates your interests, and the reason that you think they would be beneficial.

.Deliverables
====
- A markdown cell containing 3 skills/topics that you think we should have covered in the projects, and an example of why you believe these topics or skills could be relevant and beneficial to students going through the course.
====

=== OPTIONAL but encouraged:

Please connect with Dr Ward on LinkedIn:  https://www.linkedin.com/in/mdw333/

and also please follow our Data Mine LinkedIn page:  https://www.linkedin.com/company/purduedatamine/

and join our Data Mine alumni page:  https://www.linkedin.com/groups/14550101/

**Find us, @purduedatamine, on Instagram, Twitter and Facebook!!**

== Submitting your Work

If there are any final thoughts you have on the course as a whole, be it logistics, technical difficulties, or nuances of course structuring and content that we haven't yet given you the opportunity to voice, now is the time. We truly welcome your feedback! Feel free to add as much discussion as necessary to your project, letting us know how we succeeded, where we failed, and what we can do to make this experience better for all our students and partners in 2025 and beyond.

We hope you enjoyed the class!

.Items to submit
====
- firstname_lastname_project14.ipynb
====

[WARNING]
====
It is necessary to document your work, with comments about each solution.  All of your work needs to be your own work, with citations to any source that you used.  Please make sure that your work is your own work, and that any outside sources (people, internet pages, generative AI, etc.) are cited properly in the project template.

You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not.

**Please** take the time to double check your work. See xref:ROOT:submissions.adoc[submission page] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====


