= Web Scraping

Web scraping is the automated retrieval of data from web pages. Web scraping is one of the foundational tools of our modern web; for instance, Google was originally a web scraping system on steroids (typically called crawlers) designed to scrape the entire web. While today Google has grown beyond just its crawler system, web scraping is still incredibly important to retrieving data in an automated way for many organizations, not just Google.

== Common Applications

Many industries utilize web scraping to keep track of market changes, product prices, etc. For instance:

- Retail: scraping product prices from a competitors website to automatically keep track of their prices
- Marketing/Advertising/Communication: companies like https://syften.com[Syften] monitor web communications using scraping systems and use that to help companies find customers talking about their products (or, their competitors products)
- Social Media: one of the biggest targets for scraping, because public sentiment can be analyzed here (see https://the-examples-book.com/starter-guides/data-science/data-analysis/nlp/sentiment-analysis[Sentiment Analysis])

== Resources

All resources are chosen by Data Mine staff to be of decent quality, and most if not all content is free. 

=== TDM Seminar Scraping Projects



=== Videos

https://www.youtube.com/watch?v=QhD015WUMxE[Beginners Guide To Web Scraping with Python]

https://www.youtube.com/watch?v=Ct8Gxo8StBU[What is Web Scraping and What is it Used For? (Parsehub)]

https://www.youtube.com/watch?v=8dTpNajxaH0[Scraping Data From a Real Website using Python]

=== Books

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99170207991101081[Python Web Scraping Cookbook (2018)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99170208361901081[R Web Scraping Quick Start Guide (2018)]

=== Articles

https://methods-sagepub-com.ezproxy.lib.purdue.edu/foundations/web-scraping[Web Scraping (2020)]