= WSDS Notes

== Data Sets

Chinook is a SQLite database of digital media store data comes from Kaggle:

https://www.kaggle.com/datasets/ranasabrii/chinook

== Description of the Data

The data represents a digital media store with tables for artists, albums, media tracks, invoices and customers. The updated version of the chinook data is available here (it was slightly updated in 2022):

https://github.com/lerocha/chinook-database/tree/master/ChinookDatabase/DataSources

It has an interesting name. Let’s check the reason behind it on the webpage: "The name of this sample database was based on the Northwind database. Chinooks are winds in the interior West of North America, where the Canadian Prairies and Great Plains meet various mountain ranges. Chinooks are most prevalent over southern Alberta in Canada. Chinook is a good name choice for a database that intents to be an alternative to Northwind."*

The data is located at: /anvil/projects/tdm/data/chinook/chinook.db

To run SQL queries in a Jupyter Lab notebook, first run the following in a cell at the top of your notebook to establish a connection with the database.

[source,ipython]
----
%sql sqlite:////anvil/projects/tdm/data/movies_and_tv/imdb.db
----

* Source: https://github.com/lerocha/chinook-database/blob/master/README.md (Accessed at 10/09/2025)

Note: The Northwind database is a sample dataset originally developed by Microsoft and has served as the foundation for tutorials across many of their database products for decades.

