= WSDS Notes

== Data Sets

Chinook is a SQLite database of digital media store data comes from Kaggle:

https://www.kaggle.com/datasets/ranasabrii/chinook

== Description of the Data

The data represents a digital media store with tables for artists, albums, media tracks, invoices and customers. The updated version of the chinook data is available here (it was slightly updated in 2022):

https://github.com/lerocha/chinook-database/tree/master/ChinookDatabase/DataSources

It has an interesting name. Let’s check the reason behind it on the webpage: "The name of this sample database was based on the Northwind database. Chinooks are winds in the interior West of North America, where the Canadian Prairies and Great Plains meet various mountain ranges. Chinooks are most prevalent over southern Alberta in Canada. Chinook is a good name choice for a database that intents to be an alternative to Northwind."*

The data is located at: /anvil/projects/tdm/data/chinook/chinook.db

To run SQL queries in a Jupyter Lab notebook, first copy the chinook database to your local storage in anvil so that you are able to modify it:

=== Database Setup
[source,python]
----
import sqlite3

# Load the Chinook database
read_only_chinook = sqlite3.connect('/anvil/projects/tdm/data/chinook/chinook.sqlite')
local_chinook = sqlite3.connect('./chinook.sqlite')

read_only_chinook.backup(local_chinook)
read_only_chinook.close()
local_chinook.close()
----

Before diving deeper into the code, let’s take a moment to talk about Structured Query Language (SQL) — the standard language for managing and manipulating relational databases. SQL enables users to efficiently create, read, update, and delete data. It is widely used across applications, from small projects to large-scale industry systems. For data analysts, data scientists, and software developers, understanding SQL is essential for working effectively with databases.

However, for this 
* Source: https://github.com/lerocha/chinook-database/blob/master/README.md (Accessed at 10/09/2025)

Note: The Northwind database is a sample dataset originally developed by Microsoft and has served as the foundation for tutorials across many of their database products for decades.

