= Shells

Unix has a variety of shells.  The book https://learning.oreilly.com/library/view/unix-power-tools/0596003307/[Unix Power Tools]
gives a helpful https://learning.oreilly.com/library/view/unix-power-tools/0596003307/ch01.html#upt3-CHP-1-SECT-6[overview of the types of available shells].

Users type commands in the terminal, and the shell processes the commands.  The shell is the key way that the user can interact with the files and the operating system.

When you are using a terminal in Unix, you can usually tell, just by looking at the prompt, what type of shell you are using:

* `$` is the prompt for the Bourne shell (`sh`)
* `%` is the prompt for the C shell (`csh`)
* `>` is the prompt for the T shell (`tcsh`)
* xref:unix/bash-overview.adoc[bash shell]

When using the terminal in Unix, the mouse will not help you, and that's a good thing!  Dr Ward points out that it is much more efficient to keep your hands on the keyboard, and learn many shortcuts and also efficient methods that Unix provides for data analysis.

When a user is confined to using a mouse and a system of drop-down menus, there are only a handful of functions available to the user.  In the very first section of the https://learning.oreilly.com/library/view/unix-power-tools/0596003307/ch01.html#upt3-CHP-1-SECT-1[Unix Power Tools] book, the authors point out that using the wide variety of tools available in Unix allows the user to be really versatile.

Unix tools also allow users to perform tasks in a reproducible and efficient way, with short short sequences of tools in a pipeline.  A comparable program, written in a programming language, would often take hundreds of lines of code.



