= Corporate Partners

Welcome to the resource book for The Data Mine Corporate Partners. 


Watch this video about The Data Mine that was created by Purdue's Marketing and Communication team. It has over 119,000 views! 


++++
<iframe  class="video" width="560" height="315" src="https://www.youtube.com/embed/R_kqpIMyhR4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

We have partnerships with the following companies (and more!): 

[format=csv, cols="1,1,1,1"]
|===

American First Finance
ATOM 
Bayer Crop Sciences
Beck's Hybrids 
CAT Digital
CDC
CLA 
Corteva 
Delta Faucet
DORIS
Elanco
Ford
FSSA
Gro Master 
Halderman
Helmer Scientific 
IU Health
Jobvite
John Deere 
Lockheed Martin 
Makusafe
Merck 
Military Family Research Institute at Purdue
Minecraft
MISO
Mursix
Nuvve
Pebblst
Plane English 
Purdue Athletics 
Purdue Co-rec
Raytheon 
Renzoe Box
Republic Airways 
Sandia National Lab
Telemetry Sports 
TMap
UPS
USAA
USDA Forest Service 
Viasat
Wabash  
Webee 
.
|===

This video features our partnership with link:https://www.beckshybrids.com/[Beck's Hybrids]. 

++++
<iframe class="video" width="560" height="315" src="https://www.youtube.com/embed/dXferJvntko" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

We have two videos that feature our partnership with link:https://www.cummins.com/[Cummins]. 

++++
<iframe class="video" width="560" height="315" src="https://www.youtube.com/embed/LTax4AE9zIE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++



++++
<iframe class="video" width="560" height="315" src="https://www.youtube.com/embed/JabJjMzD6D0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++