= R
:page-aliases: introduction.adoc

[quote, , www.r-project.org]
____
R is a language and environment for statistical computing and graphics. It is a GNU project which is similar to the S language and environment which was developed at Bell Laboratories (formerly AT&T, now Lucent Technologies) by John Chambers and colleagues. R can be considered as a different implementation of S. There are some important differences, but much code written for S runs unaltered under R.
____

R is a highly powerful tool for statistical computing, graphics, and programming. As a free, open-source, and continually evolving software, it is widely recognized as a strong competitor among statistical and data science packages. 

[quote, , www.r-project.org]
____
R is available as Free Software under the terms of the link:http://www.gnu.org/[Free Software Foundation]’s link:https://www.r-project.org/COPYING[GNU General Public License] in source code form. It compiles and runs on a wide variety of UNIX platforms and similar systems (including FreeBSD and Linux), Windows and MacOS.
____

Resources on the web: 

* The main resource is the R project site: <http://www.r-project.org>
* For quick R Manuals: <https://cran.r-project.org/manuals.html>
* Blogs about R is highly broad and powerful. Try R-bloggers: <http://www.r-bloggers.com/>
* Questions/Answers in programming: <https://stackoverflow.com/>
* Cheat sheets can be helpful resources for a quick look in R. See the following example including summary information for RStudio: <https://rstudio.github.io/cheatsheets/rstudio-ide.pdf> 
* Working with a team requires version control. If version control is not familiar to you, the following link would be a great start: <https://happygitwithr.com>

====
R project site contains an extensive bibliography of books related to R: <http://www.r-project.org/doc/bib/R-books.html>
====

Here are some (tentative) topics covered in R section:

* xref:reading-and-writing-data.adoc[Reading and Writing Data]
* xref:variables.adoc[Variables]
* xref:logical-operators.adoc[Logical Operators]
* xref:lists-and-vectors.adoc[Lists and Vectors]
* xref:data-frames.adoc[Data Frames]
* xref:control-flow.adoc[Control Flow]
* xref:writing-functions.adoc[Functions]
* xref:r-base-functions.adoc[R Base Functions]
* xref:apply-functions.adoc[Apply Functions]
* xref:plotting.adoc[Plotting]
