= R `base` functions

== table

`table` is a function used to build a contingency table, which is a table that shows counts for categorical data, from one or more categories. `prop.table` is a function that accepts `table` output, returning proportions of the counts.

=== Examples

==== In the DeathRecords data file, create a table of the values in the Race column and how many times that each Race value occurs.

.Click to see solution
[%collapsible]
====
[source,R]
----
deathDF <- read.csv("/anvil/projects/tdm/data/death_records/DeathRecords.csv")
table(deathDF$Race)
----

----
      1       2       3       4       5       6       7      18      28      38 
2241510  309504   18031   13297    8159     700   11074    6778    4711     623 
     48      58      68      78 
   4913     316    8737    2818 
----
====

== subset
`subset`  is a function that helps you take subsets of data. By default, `subset` removes NA rows.

NOTE: `subset` does not perform any operation that can't be accomplished by indexing.

=== Examples

==== In the DeathRecords data file, show the head of the subset of data for which Sex=='F'.

.Click to see solution
[%collapsible]
====
[source,R]
----
deathDF <- read.csv("/anvil/projects/tdm/data/death_records/DeathRecords.csv")

femaleSubset <- subset(deathDF, Sex == 'F')

head(femaleSubset)
----

----
Id	ResidentStatus	Education1989Revision	Education2003Revision	EducationReportingFlag	MonthOfDeath	Sex	AgeType Age	AgeSubstitutionFlag	...	CauseRecode39	NumberOfEntityAxisConditions	NumberOfRecordAxisConditions	Race	BridgedRaceFlag	RaceImputationFlag	RaceRecode3	RaceRecode5	HispanicOrigin	HispanicOriginRaceRecode
	<int>	<int>	<int>	<int>	<int>	<int>	<chr>	<int>	<int>	<int>	...	<int>	<int>	<int>	<int>	<int>	<int>	<int>	<int>	<int>	<int>
3	3	1	0	7	1	1	F	1	75	0	...	28	2	2	1	0	0	1	1	100	6
6	6	1	0	5	1	1	F	1	93	0	...	37	5	5	1	0	0	1	1	100	6
9	9	1	0	3	1	1	F	1	86	0	...	37	1	1	1	0	0	1	1	100	6
11	11	1	0	3	1	1	F	1	79	0	...	22	2	2	1	0	0	1	1	100	6
13	13	1	0	4	1	1	F	1	85	0	...	22	5	5	1	0	0	1	1	100	6
14	14	1	0	3	1	1	F	1	84	0	...	8	2	2	1	0	0	1	1	100	6
----
====

==== In the DeathRecords data file, show the head of the subset of data for which  Sex=='F' & Age!=999.

.Click to see solution
[%collapsible]
====
[source,R]
----
deathDF <- read.csv("/anvil/projects/tdm/data/death_records/DeathRecords.csv")

validFemaleSubset <- subset(deathDF, Sex == 'F' & Age != 999)

head(validFemaleSubset)
----

----
Id	ResidentStatus	Education1989Revision	Education2003Revision	EducationReportingFlag	MonthOfDeath	Sex	AgeType	Age	AgeSubstitutionFlag	...	CauseRecode39	NumberOfEntityAxisConditions	NumberOfRecordAxisConditions	Race	BridgedRaceFlag	RaceImputationFlag	RaceRecode3	RaceRecode5	HispanicOrigin	HispanicOriginRaceRecode
	<int>	<int>	<int>	<int>	<int>	<int>	<chr>	<int>	<int>	<int>	...	<int>	<int>	<int>	<int>	<int>	<int>	<int>	<int>	<int>	<int>
3	3	1	0	7	1	1	F	1	75	0	...	28	2	2	1	0	0	1	1	100	6
6	6	1	0	5	1	1	F	1	93	0	...	37	5	5	1	0	0	1	1	100	6
9	9	1	0	3	1	1	F	1	86	0	...	37	1	1	1	0	0	1	1	100	6
11	11	1	0	3	1	1	F	1	79	0	...	22	2	2	1	0	0	1	1	100	6
13	13	1	0	4	1	1	F	1	85	0	...	22	5	5	1	0	0	1	1	100	6
14	14	1	0	3	1	1	F	1	84	0	...	8	2	2	1	0	0	1	1	100	6
----
====
