= R `base` functions


== subset
`subset`  is a function that helps you take subsets of data. By default, `subset` removes NA rows.

NOTE: `subset` does not perform any operation that can't be accomplished by indexing.

=== Examples

==== Using the yellow_tripdata_2015-11.csv file, make a new data frame called thanksgivingdayDF by using the subset function, with the option grepl("2015-11-26", tpep_pickup_datetime) to extract the rows of the data from Thanksgiving day. Your new data frame should have 242393 rows and 19 columns.

.Click to see solution
[%collapsible]
====
[source,R]
----
myDF <- fread("/anvil/projects/tdm/data/taxi/yellow/yellow_tripdata_2015-11.csv", tz="")

thanksgivingDF <- subset(myDF, grepl("2015-11-26", tpep_pickup_datetime))
dim(thanksgivingDF)
----
----
    242393
    19
----
====

==== Using the yellow_tripdata_2015-11.csv file, make a new data frame called finalDF from the data frame thanksgivingdayDF (from the previous example), using the subset function with the condition (mytimes > paradestart) & (mytimes < paradeend). Your data frame finalDF should have 28704 rows.

====
[source,R]
----
paradestart <- strptime("2015-11-26 09:00:00", format="%Y-%m-%d  %H:%M:%S", tz="EST")

paradeend <- strptime("2015-11-26 12:00:00", format="%Y-%m-%d  %H:%M:%S", tz="EST")
----
====

.Click to see solution
[%collapsible]
====
[source,R]
----
paradestart <- strptime("2015-11-26 09:00:00", format="%Y-%m-%d  %H:%M:%S", tz="EST")
paradeend <- strptime("2015-11-26 12:00:00", format="%Y-%m-%d  %H:%M:%S", tz="EST")

times <- strptime(thanksgivingDF$tpep_pickup_datetime, format="%Y-%m-%d  %H:%M:%S", tz="")

finalDF <- subset(thanksgivingDF, (times > paradestart) & (times < paradeend))
dim(finalDF)
----
----
    28704
    19
----
====