= R `base` functions

== Overview

The following is a curated list of useful, "must-know" functions built into the R `base` package that is shipped with R. This is by no means an exhaustive list. Do you have another function that you think should be included here? Please feel free to xref:book:ROOT:how-to-contribute.adoc[make a contribution]. See a mistake? Please https://github.com/TheDataMine/the-examples-book/issues[open an issue] and we will get to it as soon as possible.

In R, you can easily read about the details of a given function by typing `?` followed by the function name. For example, to see documentation for the `merge` function, simply run the following command in R.

[source,r]
----
?merge
----

Typically, this is the best first-step to understanding what a function does, and how to use it. With that being said, the documentation can be inconsistent, so we will do our best to provide you with some cursory information about important functions, as well as provide tangible examples on how to use them.

== Datasets
* xref:r-base-iris.adoc[Iris]
* xref:r-base-airport.adoc[Airports]
* xref:r-base-icecream.adoc[Ice Cream]
* xref:r-base-olympics.adoc[Olympics]
* xref:r-base-election.adoc[Election]
* xref:r-base-deathrecord.adoc[Death Records]
* xref:r-base-beer.adoc[Beer]
* xref:r-base-grocery.adoc[Grocery]
* xref:r-base-iowaliquor.adoc[Iowa Liquor]
* xref:r-base-movies.adoc[Movies and TV]
* xref:r-base-craigslist.adoc[Craigslist]

== Object introspection

* xref:ncol.adoc[ncol]
* xref:nrow.adoc[nrow]
* xref:dim.adoc[dim]
* xref:str.adoc[str]
* xref:head.adoc[head]
* xref:tail.adoc[tail]
* xref:unique.adoc[unique]

== Numeric functions

* xref:mean.adoc[mean]
* xref:median.adoc[median]
* xref:var.adoc[var]
* xref:sd.adoc[sd]
* xref:abs.adoc[abs]
* xref:sum.adoc[sum]
* xref:min.adoc[min]
* xref:max.adoc[max]
* xref:length.adoc[length]
* xref:table-and-prop-table.adoc[table & prop.table]

== Data manipulation & indexing

* xref:rep.adoc[rep]
* xref:seq.adoc[seq]
* xref:which.adoc[which]
* xref:r-grep.adoc[grep]
* xref:sort.adoc[sort]
* xref:order.adoc[order]
* xref:paste-and-paste0.adoc[paste & paste0]
* xref:cut.adoc[cut]
* xref:split.adoc[split]
* xref:subset.adoc[subset]
* xref:merge.adoc[merge]


== Resources

https://stat.ethz.ch/R-manual/R-devel/library/base/html/00Index.html[R `base` functions]

An exhaustive list of the functions in the `base` library.