= Plotting in R with `graphics`

== Introduction

The `graphics` package is included with the language, meaning you won't need to import anything at the beginning of your file. It includes a ton of useful, variably-complex plots to use on your journey of data visualization.

=== Examples

==== Plot of the table of Age values for the subset of the DeathRecords data file for which Sex=='F'.

.Click to see solution
[%collapsible]
====
[source,R]
----
deathDF <- read.csv("/anvil/projects/tdm/data/death_records/DeathRecords.csv")
femaleSubset <- subset(deathDF, Sex == 'F')

ageTable <- table(femaleSubset$Age)
plot(ageTable, main = "Age Distribution of Females", xlab = "Age", ylab = "Frequency")
----

====

==== Plot of the table of Age values for the subset of the DeathRecords data file for which Sex=='F' & Age!=999.

.Click to see solution
[%collapsible]
====
[source,R]
----
validFemaleSubset <- subset(deathDF, Sex == 'F' & Age != 999)

validAgeTable <- table(validFemaleSubset$Age)

plot(validAgeTable, main = "Age Distribution of Females (w/o 999)", xlab = "Age", ylab = "Frequency")
----

====

==== Plot of the table of Age values for people with Filipino race, also with Age not equal to 999.

You can see what races the data from the Race column represents, by looking at page 15 of the pdf source file: www.cdc.gov/nchs/data/dvs/Record_Layout_2014.pdf

.Click to see solution
[%collapsible]
====
[source,R]
----
plot(table(deathDF$Age[(deathDF$Race == 7) & (deathDF$Age != 999)]))
----

====