= Additional Tools

In addition to the wonderful resources in this section, there are many others located in The Examples Book. Below are some of the sections you could find useful on your project.

Navigate to: xref:data-science-theory-appendix::introduction.adoc[Introduction to Data Science]

Navigate to: xref:data-science-book-list-appendix::introduction.adoc[Supplementary Data Science Reading List]

Navigate to: xref:prodigy-appendix::introduction.adoc[Prodigy Annotation]

Navigate to: xref:geospatial-appendix::basic_postgis.adoc[Geospatial Analytics]

Navigate to: xref:data-visualization-appendix::introduction.adoc[Data Visualization]

Navigate to: xref:matlab-appendix::introduction.adoc[MATLAB]

Navigate to: xref:optimization-techniques-appendix::introduction.adoc[Optimization]

//test 11: xref:students:fall2022/locations.adoc[maybe now?]




To find more resources in the appendices and resources on Data Types, UNIX, SQL, R, Python, Git, and past project please navigate to the home page of The Examples Book and search through the appendices and left hand search bar. 