= Lab Planning 

As the TA, you get to design your labs to drive your project. This is valuable time to complete work, collaborate, and hold discussions with the entire team each sprint. 

How do you plan a lab for students? 

== Before Lab
1. Identify goal(s) of the lab.
    a. Clearly state what you want to accomplish using SMART goals. What goals can you move from the product backlog to the current sprint?
2. Plan the activities and sequence. Specific plans will vary by your project. Below is an example.
    a. Daily Stand-Up (low-stress). Students will answer three questions. What did I do yesterday? What will I do today? Finally, do I have any blockers? 
    b. Discussion on what tasks need to be worked on. Share the goals from step 1. and complete any demonstrations if needed. 
    c. Work time.
    d. Allow discussion between the team. 

3. Create a realistic timeline. Lab is only 2 hours.
4. Plan for a lab closure such as a conclusion of work completed and assignments or a group discussion.

== During Lab
1. Icebreaker, if applicable.
2. Attendance.
3. Lab time!
4. Remember to ask for questions before dismissing the team. "What questions do y'all have?"

== After Lab
1. Reflect on what worked well and why. What could you have done differently?

Repeat the process each week using reflection and collecting feedback to improve your labs.

Remember, you are the leader. 