= Team Report

Another responsibility as a TA in The Data Mine is writing Team Reports. These reports are a set of questions that are answered by TAs and serve as a written retrospective of the team. TAs will provide honest feedback on their team's progress and submit the report to The Data Mine staff for review. The Data Mine staff then reads the reports and offers any guidance and assistance that was requested or perceived. 

== Sample Team Report Questions
The questions found on Team Reports are:author:

1. Did you have both of your team meetings this week? If not, please explain. If yes, a simple “yes” will suffice. 

2. What did your team do well this week, and why do you think it went well?

3. What did your team struggle with this week, and what would help that go better next week?

4. Who are your team’s superstars (and why)?

5. Who struggled this week, and how do you plan to reach out to them?

6. Did you update the attendance spreadsheet in Box for this week? A simple “yes” is sufficient. This is mainly a reminder question. 

7. How is the mentoring from your Corporate Partner Mentor? Do they respond to questions? Are they clear with their expectations?

8. Is there anything new Data Mine staff can do to help support you or your team? Anything else we should know? 

== FAQs
*How often do TAs write and submit sprint reports?*

TAs submit team reports every two weeks. TAs will alternate grading xref:rythms_grading.adoc[sprint reports] and writing team reports. 

*Are the team reports required?*

Yes, they are required. These reports are the primary source of updates for The Data Mine staff.

*How long does it take to write a team report on average?*

Team reports are not difficult to write or very time consuming. It will usually take TAs no longer than 30 to 45 minutes to complete their team report.

