= Introduction to Data Science

Data science is a popular topic that is growing rapidly in both interest and complexity. Rather than diving right into technical details our goal is to help build skills that allow readers to think through data science problems. 

Breaking down and understanding these problems are critical to building a good foundation for a successful data science project. 

== What is Data Science

There are many definitions for a data science problem. Many different groups debate the specific definition, but to our team data science and analytics is the focus on using data and scientific thinking to solve a problem. 

As with any discipline this has many layers. These layers can be both technical (modeling algorithms) or conceptual (ethics in data science). It's important to learn both to be a successful data practitioner. 

== What is Data

Breaking it down ever further we can think about what constitutes data. The awesome and amazing thing about data science is that data is everywhere. Anything from the weather to the type of cereal you had for breakfast, or how many steps you took to work is valuable data. 

Think about your day-to-day life. What data would you be interested in? 

* How long did you sleep? 
* How much have you eaten? 
* What topic did you learn about that you found most interesting? 

These are all data points! 

== How is it Used

Data science is everywhere. From the products and shows you're recommended to the route home and your online order of groceries it all uses data science. 

If you want a fun challenge, try to think of a discipline that doesn't use data science and then look-up `that term` + data science on the internet. I bet you'll be surprised. 

== Why is it Important

Because data science is everywhere it's also used in almost everything. When a practice becomes that pervasive it's important to ensure that people who use it understand it and use it ethically. 

These can be difficult challenges in a world driven by profit and tight deadlines. Learning how to work with data well and in the right way are continuing journeys for any data science practitioners (our team included).