= The Examples Book
:page-aliases: introduction.adoc
:description: Supplementary material for solving projects assigned in Purdue University's The Data Mine.
:sectanchors:
:url-repo: https://github.com/TheDataMine/the-examples-book


== Overview

++++
<iframe  class="video" width="560" height="315" src="https://www.youtube.com/embed/R_kqpIMyhR4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

xref:ROOT:tdm-intro-transcript.adoc[Data Mine Introduction Video Transcript]

Welcome to The All New Examples Book! This book contains a collection of information and examples that can be used to reinforce topics learned in https://datamine.purdue.edu[The Data Mine] seminar at https://purdue.edu[Purdue University]. The Examples Book is open to anyone. Even if you aren't a student at Purdue we hope you find helpful content here.

[TIP]
====
Where to go for specific topics:

* Learning R, Python, or SQL. `Tools` might be helpful.
* Want more info on The Data Mine, corporate partners projects, or student course materials? Check out `Corporate Partners`.
* Looking for projects/exercises to build your skills? Read through the `Course Links`.
* Did you find a mistake in the Book? Would you like to add your own content? Do you have a frequently asked question (FAQ)? `Helpful Links` is the place for you.
====

== Core Topics
xref:crp:ROOT:index.adoc[[.custom_button]#Corporate Partners#]
xref:tools:ROOT:index.adoc[[.custom_button]#Tools#]
xref:projects:ROOT:index.adoc[[.custom_button]#Seminar Projects#]

== Course Links
xref:projects:fall2025:10100/projects.adoc[[.custom_button]#TDM 101-102#]
xref:projects:fall2025:20100/projects.adoc[[.custom_button]#TDM 201-202#]
xref:projects:fall2025:30100/projects.adoc[[.custom_button]#TDM 301-302#]
xref:projects:fall2025:40100/projects.adoc[[.custom_button]#TDM 401-402#]
xref:projects:fall2025:syllabus.adoc[[.custom_button]#Syllabus#]
xref:projects:fall2025:office_hours.adoc[[.custom_button]#Office Hours#]

== Grant Awarded Programs
xref:crp:ndmn:index.adoc[[.custom_button]#NDMN#]

== Workshops and Trainings
xref:workshops:wsds/index.adoc[[.custom_button]#WSDS#]

== Helpful Links
xref:ROOT:faqs.adoc[[.custom_button]#FAQs#]
xref:ROOT:how-to-contribute.adoc[[.custom_button]#How to Contribute#]
xref:ROOT:contributors.adoc[[.custom_button]#Contributors#]