= Salesforce

== Leads versus Contacts

Both leads and contacts are individual people.

A "lead" is a person who has not (yet) agreed to be involved in a partnership with The Data Mine.

A "contact" is a person who has agreed to be involved in a current (or previous) partnership with The Data Mine.

Leads are converted to contacts when they agree to be involved in a partnership with The Data Mine.

[NOTE]
====
Once a lead is converted to a contact, it cannot be converted back to a lead again.
====

== Partnerships versus Projects

A "partnership" is a company or university (or other similar type of organization).  Whether the partner has agree to work with The Data Mine or not, it is OK to enter the information about all partnerships (past, present, potential, etc.)  Partnerships can be classified by their type, including "Prospect" (which means that they have not yet agreed to work with The Data Mine) or "Partner" (which means that they are a past or present partner, or have agreed to be a partner in the very near future).

A "project" describes an opportunity that The Data Mine will execute with one or more of its partners, typically during a 9-month credit-bearing, experiential project, but could also be during a sponsored research project.

== Setting up a New Lead

[NOTE]
====
Please, before setting up a new lead or a new contact, it is recommended for you to (first) jump down to the "Setting up a New Partner" section first, if the person's company or university has not (yet) been entered there.  That way, for instance, we can be certain to name things consistently.  The name of the partner will even automatically populate for contacts (although not for leads).
====

[IMPORTANT]
====
"When updating existing accounts or contacts during lead conversion, the values of mapped lead fields don’t overwrite the values of the mapped account and contact fields."

https://help.salesforce.com/s/articleView?id=sales.leads_notes.htm&type=5
====

[TIP]
====
This page describes how a lead's values are converted to contacts, accounts ("partnerships" in The Data Mine language), and opportunities ("projects" in The Data Mine language):

https://help.salesforce.com/s/articleView?id=sales.lead_conversion_mapping.htm&type=5
====

Information about the fields for a lead:

[cols="1,1"]
|===
|Lead Field |What This Field Does

|Name, which includes: Salutation, First Name, Middle Name, Last Name, Suffix
|The person's name

|Title
|The person's title at their job

|Email
|The person's work email address

|Personal Email
|The person's third-party email address

|Personal LinkedIn
|The person's LinkedIn page

|Address
|The person's mailing address

|Phone
|The person's telephone number

|Personal Website
|The person's individual webpage

|Company
|The partner company's name (or university's name)

|Lead Owner
|Data Mine team member who is the person's primary point of contact

|Lead Source
|The way that The Data Mine first met the person

|Lead Status
|Status on the path for this person to become a contact who said yes

|Do Not Call
|Indicates that this person should not be called at the present time

|Email Opt Out
|Indicates that this person should not be emailed at the present time

|Rating
|Further clarification on the person's status: cold, warm, hot

|Description
|Provides additional information about the person
|=== 

== What Happens When a Lead is Converted to a Contact

The lead fields that get converted to contact fields:

[cols="1,1"]
|===
|Lead Field |Contact Field

|Name
|Name

|Title
|Title

|Email
|Email

|Personal Email
|Personal Email

|Personal LinkedIn
|Personal LinkedIn

|Address
|Mailing Address

|Phone
|Phone

|Personal Website
|Personal Website

|Company
|Account Name

|Lead Owner
|Contact Owner

|Lead Source
|Lead Source

|Lead Status
|This field disappears upon conversion to a contact

|Do Not Call
|Do Not Call (or maybe This field isn't updated for leads converted to existing contacts; need to check this)

|Email Opt Out
|Email Opt Out (or maybe This field isn't updated for leads converted to existing contacts; need to check this)

|Rating
|This field disappears upon conversion to a contact

|Description
|Description
|=== 

The lead fields that get converted to partner fields; these should already be filled in by The Data Mine team member who created the partner (if it did not exist) before creating the lead.

[cols="1,1"]
|===
|Lead Field |Partner Field

|Company
|Account Name

|Address
|Billing Address

|Phone
|Phone

|Lead Owner
|Account Owner

|Lead Source
|Account Source

|Rating
|Rating
|=== 

== Setting up a New Contact

[NOTE]
====
(As noted above:)

Please, before setting up a new lead or a new contact, it is recommended for you to (first) jump down to the "Setting up a New Partner" section first, if the person's company or university has not (yet) been entered there.  That way, for instance, we can be certain to name things consistently.  The name of the partner will even automatically populate for contacts (although not for leads).
====

Information about the fields for a contact:

[cols="1,1"]
|===
|Contact Field |What This Field Does

|Name, which includes: Salutation, First Name, Middle Name, Last Name, Suffix
|The person's name

|Title
|The person's title at their job

|Email
|The person's work email address

|Personal Email
|The person's third-party email address

|Personal LinkedIn
|The person's LinkedIn page

|Mailing Address
|The person's mailing address

|Phone
|The person's telephone number

|Personal Website
|The person's individual webpage

|Birthdate
|The person's birthdate

|Asst. Phone
|The phone number of the person's assistant

|Home Phone
|The person's home phone number

|Other Address
|An alternative address for the person

|Other Phone
|An alternative phone number for the person

|Account Name
|The partner company's name (or university's name)

|Department
|The department where the person works

|Reports To
|The name of the person's supervisor

|Assistant
|The name of the person's assistant

|Contact Owner
|Data Mine team member who is the person's primary point of contact

|Lead Source
|The way that The Data Mine first met the person

|Do Not Call
|Indicates that this person should not be called at the present time

|Email Opt Out
|Indicates that this person should not be emailed at the present time

|Description
|Provides additional information about the person
|=== 

Note: We did not (yet) include the "Last stay-in-touch request date" or the "Last stay-in-touch save date"

