= Sprint Planning

Deciding what tasks need to be done is a crucial first step towards a successful sprint. To start, product owners and scrum masters take the responsibility for the delivery and upkeep of the product backlog. The product backlog is a prioritized list of tasks for the development team to accomplish. The product backlog clearly lays out stakeholder and customer expectations such that the development team can satisfy these needs. Because this system creates a transparent set of tasks to be completed, the development team can take ownership of specific tasks for each sprint. During the sprint planning ceremony, development team members create a plan of action based on the product backlog and move tasks from the product backlog to the sprint backlog. The *sprint backlog* is the same as the product backlog, but rather than it being a list of tasks for the entire project, it is a prioritized list for only the upcoming sprint. 

Once tasks are decided on for the upcoming sprint, the next step of sprint planning will be to plan *how* these tasks will get done. The scrum team will examine how each of the selected tasks fit together and create a plan of completion. When using a management software, notes and specific sub-tasks can be noted directly on the task, allowing everyone on the team to see written thoughts. 

Lastly, the team needs to decide *who* will take ownership of each of the tasks. Choosing tasks based on each other’s strengths is important. The development team will discuss who is best fit to take on certain tasks and will label who takes ownership of each task in the sprint backlog.  

== Sprint Planning in The Data Mine

Sprint planning should take place at the start of every sprint. Realistically, planning meetings will occur at the first team meeting following the end of sprint. TAs are responsible for creating and maintaining the product backlog by working with their team’s corporate partner mentor to ensure they project is moving with correct pace and direction.  

During the sprint planning meeting, an open discussion is held between the corporate partner mentors, TAs, and development team. Each development team member will take ownership of tasks from the product backlog to complete the coming sprint. Each event that is chosen will then be moved to sprint backlog. 

[TIP]
====
Pairing members of the development team together to take co-ownership of tasks helps productivity and allows for team mentorships to form.
====