= Sprint Reviews

The second to last ceremony of a sprint is called a *sprint review*. These meetings are meant to discuss, demonstrate, and celebrate the team’s work from the sprint. Development team members will discuss, present, and showcase their work and seek approval for completion of their tasks from the product owner. 

It is during the sprint review that product owners or other development team members can give demonstrations and receive feedback on their work with the main goal being to decide if tasks are completed or should be rolled over into the next sprint. 

== Sprint Reviews in The Data Mine

In The Data Mine, sprint reviews should occur once every sprint during a meeting time with the team’s corporate partner mentor in attendance. Team members will go around and informally demonstrate their work through live demos, documentations, or presentations. This meeting is where the corporate partner mentor can clearly see the work being done by the team and can give feedback to the team. It is crucial for the team to be prepared for these meetings on a sprint-by-sprint basis because it is direct representation of the work being accomplished. Feedback from the corporate partner mentor should be annotated and applied towards the next sprint.