= Corporate Partner TA Playbook
:page-aliases: introduction.adoc

TAs hold a large part in the success of a corporate partner team and in a student’s experience within The Data Mine. The TAs primary responsibilities include engaging with students and CRP mentors, leading projects, and being a resource for their team. 

== Welcome to The Data Mine Corporate Partners!

All course content lives within The Corporate Partners appendix of The Example Book (the pages you are reading right now). 

Teaching Assistants (TAs) will use Gradescope to submit their reports and success factors for their time sheets. Students will also continue to use link:https://www.gradescope.com/[Gradescope] as the submission portal for retrospective sprint reports and professional developments. The method of submission will be specified for each assignment under the corresponding sprint page. 

== TA Info, Training, & Resources

The following nodes of this branch are a resource for a TAs to become acclimated with The Data Mine and learn of the strategies that welcome success to their corporate partnership projects.

To get started:

1. Review the TA xref:trainingModules/introduction_trainings.adoc[training], completing respective Gradescope quizes.

2. Checkout xref:fall2025/sprint1.adoc[Sprint #1] to review the content for the first two weeks.

3. Explore additional xref:trainingModules/ta_training_resources.adoc[resources].

We look forward to working with you this semester! 
