= Corporate Partner TA Playbook

== Welcome to The Data Mine Corporate Partners!

All course content lives within The Corporate Partners appendix of The Example Book (the pages you are reading right now). We have migrated away from hosting our content in Brightspace to make our content publicly accessible as we expand. 

However, we still have a link:https://purdue.brightspace.com/[Brightspace] page for the purposes of grading. All Purdue courses are required to post grades in Brightspace. Students will also continue to use link:https://www.gradescope.com/[Gradescope] as the submission portal for sprint reports. The method of submission will be specified for each assignment under the corresponding sprint page. 

== TA Responsibility Overview

TAs hold a large part in the success of a corporate partner team and in a student’s experience within The Data Mine. The TAs primary responsibilities include engaging with students and CRP mentors, leading projects, and being a resource for their team. 

The following nodes of this branch are a resource for a TAs to become acclimated with The Data Mine and learn of the strategies that welcome success to their corporate partnership projects.

To get started:

1. Confirm your xref:trainingModules/introduction_trainings.adoc[training] is complete.

2. Click on xref:fall2022/sprint1.adoc[Sprint #1] to review the content for the first two weeks.

3. Explore the xref:resources/introduction_resources.adoc[resources] branch to view templates, guides, and learn tips from staff and past TAs.

We look forward to working with you this semester! 
