= Corporate Partner TA Playbook

== Welcome to The Data Mine Corporate Partners Fall 2022 semester!

All course content lives within The Corporate Partners appendix of The Example Book (the pages you are reading right now). We have migrated away from hosting our content in Brightspace to make our content publicly accessible as we expand. 

However, we still have a link:https://purdue.brightspace.com/[Brightspace] page for the purposes of grading. All Purdue courses are required to post grades in Brightspace. Students will also continue to use link:https://www.gradescope.com/[Gradescope] as the submission portal for sprint reports. The method of submission will be specified for each assignment under the corresponding sprint page. 

== TA Responsibility Overview

TAs hold a large part in the success of a corporate partner team and in a student’s experience within The Data Mine. The TAs primary responsibilities include engaging with students and CRP mentors, leading projects, and being a resource for their team. 

The following nodes of this branch are a resource for a TAs to become acclimated with The Data Mine and learn of the strategies that welcome success to their corporate partnership projects.

To get started:

//1. Review the xref:fall2022/syllabus.adoc[fall 2022 syllabus].

1. Confirm your xref:trainingModules.adoc[training] is complete.

2. Confirm your xref:student/fall2022/locations.adoc[meeting time and location]. The MS Teams meeting link for your SYNC ONLINE class were emailed out in mid-August and again on the first day of term. If you do not have this meeting link, please email us at datamine@purdue.edu and specify what team you are on. 

3. Click on xref:fall2022/sprint1.adoc[Sprint #1] to review the content for the first two weeks.

We look forward to working with you this semester! 
