= TA NDA Process

== NDA Guide Step-by-Step
1. On the Teams channel for your project, click on the Files tab at the top.
2. There will be two folders and a document uploaded here:
    * Orange folder - Student Consent
        ** Folder: “Saved Signed Student Consent”
        ** Document: Data Mine Consent to Disclose and Store
    * Green folder - Student NDA
        ** Folder: “Saved Signed Student NDA”
        ** Document: Project NDA
3. Follow the instructions below to complete the NDA process:
    * Each student on the roster and the TA for the project must sign and save both the student consent and NDA documents in the correct folders in Teams.
    * This process can be completed during class time if needed.
    * The TA must check the roster (team members in Teams) daily for any new additions.
        ** **Important**: The Teams roster will contain your mentor(s).  Make sure you know who they are as they do not have to sign an NDA.
        ** The Teams roster will also include include two Non-Person accounts: one that posts to outlook (abcd123.groups.purdue.edu@amer.teams.ms) and the owner (datamine-teams).  Do not modify these accounts for the channel to work correctly.
    * Contact or speak with any newly added students to ensure they are aware of the forms and the urgency in signing them.
    * Any student unwilling to save their forms in the Teams folder must:
        ** Email datamine@purdue.edu
        ** Notify the TA so we can ensure all students on the project have completed the process.
    * TAs are not to give any legal advice on signing the forms.
    * If a student chooses not to sign the NDA, contact datamine@purdue.edu immediately.
4. Finalizing the NDA process:
    * No students should be added to the project after September 2nd.
    * On September 3rd, verify that all members of the Teams channel have signed and saved:
        ** Student Consent forms in “Saved Signed Student Consent”
        ** Student NDA forms in “Saved Signed Student NDA”
    * Check the actual forms for any errors or missing information.
    * If any corrections are needed, contact the student right away to meet the deadline.
    * Notify the mentor when all NDAs are available to download from the Teams channel - **no later than September 5th**.
    * Mentors do not need the Consent Forms; these are for internal use only.
    * Do not delete or modify any files or instructions - only sign them. Leave everything in the Files tab for the entire academic year.

