= Meeting Notes

TAs are encouraged to record meeting notes (or meeting minutes) for every team meeting and lab. These notes should be a written as summary of the meeting and distributed to the team for review. 

These notes will help keep track of progress throughout the semester as well as offer a summary of events for anyone who is absent from a team meeting. 

== Sample Meeting Notes
Below is a sample of meeting notes. This sample is brief but outlines what a meeting might look like in summary. TAs are encouraged to put more detail into these meeting notes in order to give a thorough overview of meetings.  

1. Introduction
* Welcome conversation
* Ice breaker
2. Sprint Planning 
* Data Engineering Team
** Executable 1
** Executable 2
** Executable 3
* Data Visualization Team
** Executable 1
** Executable 2
** Executable 3
* Data Science Team
** Executable 1
** Executable 2
** Executable 3
3. Question and Answer 
4. Free Time to work
5. To Do for next meeting
* Task 1
* Task 2

== FAQs
*How often should meeting minutes be written?*

Meeting Minutes should be written for every team meeting and lab. 

*How should meeting minutes be distributed?*

Meeting minutes can be distributed through slack or email. It is also valuable to save all meeting minutes in a shared document. 

*Who will get value out of the meeting minutes?*

Any team member looking to find a summary of the meeting will find meeting notes valuable. These notes will help refresh memories or keep absent team members up to date. 

*How soon after a meeting should TAs send meeting notes?*

Sending out meeting notes as soon as possible is ideal. However, distributing the notes no longer than a day after the meeting is crucial.  