= Symposium Presentation Activities

Symposium activities are designed to help simulate the presenter-audience dynamic that students can expect to navigate during the symposium. This activities are fun and engaging, while also helping students develop important presentation skills that will serve them well during the symposium. Encourage students to be creative and have fun with these exercises!

● **Forget the Fillers** +
● **Enthusiasm is Contagious!** 

---

== Forget the Fillers

This activity helps students limit interruptions in their presentation, which conveys a higher level of understanding and confidence in their project to a listening audience.

1. Have students work in pairs or small groups to simulate a presenter-audience dynamic
2. Give the presenting student 30 seconds (using a timer) to practice talking the audience through their project (Symposium Pitch)
3. Have at least one audience member count the number of times the presenter uses a filler word (“uh,” “like,” “um,” “you know”)
4. Allow the presenting student to do a 30 second timed practice run a few times in a row. The presenting student should try to use fewer and fewer filler words with each run-through.
5. Repeat this fun challenge for each member of the group!

---

== Enthusiasm is Contagious!

This activity helps students give their audience the impression that they are devoted to their projects and conveys the importance/urgency of their research.

1. Have students work in pairs or small groups to simulate a presenter-audience dynamic
2. Have presenting student decide on something random to present on that they are totally indifferent about (e.g., a kitchen utensil, office supplies, etc).
3. Presenting student should channel their enthusiasm by honing in on strategies for emphasis (voice, tone, body language) to engage the audience in their chosen topic.
4. Repeat this fun challenge for each member of the group

---


These resources are provided by OWL in Indianapolis. +
Web: http://owl.english.purdue.edu/ +
Email: indy.owl@purdue.edu
