= FAQ

== Logistics

=== NDA’s
Data Mine staff is working with you on these! There is a legal process a company must complete to create an NDA. This can take some time. As soon as there is an NDA, we share it with your team. Each team with NDAs needs ALL students and TA’s to sign. Stragglers can cause additional delays, so encourage all students to be present at the initial signing. 

=== Getting Data Late
What do you do while waiting for data?
 * Create mock data sets
 * Create, reuse, or run skill labs to build student skill sets and create skeleton functions
 * Expand domain knowledge via research or discussions with mentors
Different teams may have different challenges to receive and work with their data. It is encouraged to be transparent with your students about this process. Depending on the timeline, we also encourage you to speak with your mentor and Data Mine staff if necessary.

=== More staff check-ins at lab
We hear you. We have a rotating schedule for staff to check in. 
If you feel you are not receiving enough support or have lots of questions, feel free to set a meeting with one of our staff members to ask questions. You can also message staff members and tag them using the @ symbol in your team MS teams chat. 
We do not know you need help unless you tell us. Working together is a two way street.  

=== Setting expectations with your mentor(s)
This continues to build off of not being able to read minds and the “two way street.”
Schedule a meeting with your mentor. Gather feedback from your students. Be honest with your mentor about your interpretation of the situation. Express your thoughts on limitations and areas your team can excel. Refocus the scope where your team will be challenged and successful. Advocate for your students while remembering the scope. 
Ask for guidance on how to overcome obstacles or provide feedback about needed support. 
Work together to find a solution. 

=== Who can I reach out to TA for support?
 * Your friendly Head TA
 * Make use of the CRP TA MS Teams chat
 * Contact other TAs with simialar projects

=== Secure documentation
Meet with your mentor to work out specifics of this. Options can include keeping your documentation in a secure, approved location for de-identifying data like the company’s GitHub

=== How to Schedule Mentor Meeting
How do I schedule a meeting with my mentor to complete the mid-semester feedback?
Please reach out to your mentor(s) through your typical communication (MS Teams, email, phone, etc.). You can set a meeting for whenever works before the deadline. 

=== Student Engagement
What do we do about students that are active sometimes but disengaged at other times?
I recommend having a 1-1 with the student. It may be because of their schedule or factors you can not control. Meeting with them will allow you to understand them as well as reset expectations about engagement in the class. 

=== Students Needing to Join Virtually
How should we handle students that need to participate online?
If a student needs to join virtually for one week this is fine. We prefer they attend in person, but understand that ‘life happens.’ They will need to keep their camera on and actively participate. Joining virtually should not become a habit though. 



== Students

=== Participation
This is part of a student's grade and a required part of the course. If a student continuously does not participate, we recommend meeting with them one on one to discuss expectations. 

=== Students not showing up
If a student misses a meeting or lab, their attendance should be recorded in the attendance/participation section of the Sprint report. You should also send them an email to make sure they are ok. If they miss more than two meetings consecutively, please email them and copy Data Mine staff on the email. We may need to escalate the situation. 
Attendance is required per Purdue Policy.
 	
=== Maximum effort is still not getting project work complete. 
This can be difficult. One approach is sitting the entire team down in a lab and resetting expectations for contribution, collaboration, and participation. This may not be an easy conversation, but may be necessary to move the team forward. 

=== Not all students are on the same skill level
How to navigate new technology?
Create, reuse, or run skill labs to build student skill sets and create skeleton functions. Previous TA’s have found this very helpful. If you are not sure how to create these labs, feel free to use projects from the Example Book from previous semesters. :)
Feel free to reach out to our Data Science Team! They’re fantastic and have a ton of expertise. 

=== Balance giving students support vs. providing them the answer
This is a real challenge that many TA’s struggle with. There is no right answer here, but here are a couple tips:
 * Break the problem down into steps 
 * Prompt the student with questions to encourage thinking
 * Ask leading questions
 * Provide hints such as directing them to specific functions

=== How to keep everyone on the same page?
Previous TA’s have found weekly emails very successful to set expectations, summarize the previous week, share announcements, and send reminders. “Daily” stand-up sessions are also very helpful to update the entire team on progress.

=== Online student belonging
 * Greet them when they enter the call (can help confirm mircophone settings too)
 * Use the students’ names
 * Prompt the student’s online. This lets them know they have the floor and it is their turn to speak. 
 * Similarly, allow them the floor and provide them a time to share their thoughts.
 * Provide them with specific roles or leadership positions of subteams

=== Splitting into subteams
Splitting into subteams has been a very successful way to complete work and keep students engaged. When forming or shuffling teams keep the following in mind:
 * What is the student interested in?
 * Where will the student have the most impact?
 * Will the student be challenged? 
 * What is the best role for the student to take on?

=== Social Events
Are there any Data Mine support social events with the team?
Yes! We host a few events throughout the semester typically around network building. Most recently there was a movie day at Hillenbrand.