= TA Training Module 4: Diversity In Data Science

== What is the current status of diversity in data science?

*Purdue Undergraduate Demographics (Fall 2019)*

- *Gender*:  Male 57%, Female 43%

- *Race/ethnicity*:  White 63%, International 14%, Asian 9%, Hispanic/Latinx 6%, Black or African American 3%, 2 or more races 4%, Unknown 2% 

- *Residency*:  IN resident 52%, Out-of-state US resident 35%, International 14%

*The Data Mine Demographics*

- *Gender*:  Male 65%, Female 35%

- *Race/ethnicity*:  White 47%, Asian 41%, Hispanic/Latino(a) 5%, Black or African American 3%, 2 or more races 5%

- *Residency*:  IN resident 31%, Out-of-state US resident 51%, International 18%

- *Year in school*:  Continuing 51%, New 49%

=== Data Mine student college of major (Fall 2019)

[cols="1,1,1"]
|===
|College | # | % of Total

|Science
|315
|49.30%

|Engineering
|125
|19.56%

|Health and Human Sciences
|50
|7.82%

|Management
|47
|7.36%

|Polytechnic
|31
|4.85%

|Liberal Arts
|30
|4.69%

|Exploratory Studies
|17
|2.66%

|Agriculture
|13
|2.03%

|Pharmacy
|10
|1.56%

|Temporary
|1
|0.16%

|*Total*
|*639*
|*100%*
|===

=== Data Science Professional Demographics

- Big Data is largely an all-white boys’ club. 

- Google’s workforce, according to its own internal audit, is 70 percent male, 61 percent white. Facebook isn’t much different. 

- Barely 18 percent of computer science degrees go to women. 

- Women make up 11 percent of math faculty. 

- Nearly half of the women who graduate with engineering degrees never enter the profession, or leave soon after. 

- https://www.washingtonpost.com/local/women-flocking-to-statistics-the-new-hot-high-tech-field-of-data-science/2014/12/19/f3e2e486-62ed-11e4-9fdc-d43b053ecb4d_story.html?noredirect=on&utm_term=.695b6e0f193b


== Why is it so important to increase diversity and inclusion in data science?

=== How Diversity Makes Us Smarter

- Decades of research by organizational scientists, psychologists, sociologists, economists and demographers show that socially diverse groups (that is, those with a diversity of race, ethnicity, gender and sexual orientation) are more innovative than homogeneous groups.
- It seems obvious that a group of people with diverse individual expertise would be better than a homogeneous group at solving complex, non-routine problems. It is less obvious that social diversity should work in the same way—yet the science shows that it does.
- This is not only because people with different backgrounds bring new information. Simply interacting with individuals who are different forces group members to prepare better, to anticipate alternative viewpoints and to expect that reaching consensus will take effort.
- Phillips, K.W. (2014, October 1). How Diversity Makes Us Smarter: Being around people who are different from us makes us more creative, more diligent and harder-working. https://www.scientificamerican.com/article/how-diversity-makes-us-smarter/ 

=== Why Does Data Science Need Diversity?

- Diversity enables better representation of the broader population.

- Diversity improves the products and services we create.

- Diversity helps counteract algorithmic violence (the ways that algorithms or automated decision-making systems inflict harm by preventing people from meeting their needs).

- https://www.informationweek.com/big-data/big-data-analytics/why-data-scientists-should-make-a-commitment-to-diversity/a/d-id/1333403

=== Data Science Needs Different Perspectives

- “We like to have this idea that the data is the ultimate truth, but it really comes down to how you ask questions and the evidence you are looking for to support the question you have or to deny it.  

- “Remember that data is just a representation of something that happened. A lot of times it tells a portion of the story but not the full story…Any time you bring in someone who brings a different perspective and different experience, you will only add to being able to solve problems…

- “There should be a conscious awareness to make sure you go after building a diverse team…It’s so easy to hire people in our own circle, and those people usually are most like us.  That’s where awareness needs to be.” - Sadie St. Lawrence, Founder and Executive Director of the non-profit Women in Data

- https://www.dataversity.net/building-future-women-data/

== How can the Data Science community be inclusive to people with disabilities?

== What is a Disabilty?

- Disability is not a simple concept with a small number of possible values. It has many dimensions, varies in intensity and impact, and often changes over time. 

- The World Health Organization estimates that 15 percent of people worldwide have some form of impairment that can lead to disability. Almost all of us will experience sensory, physical or cognitive disability in our lives.

- As defined by the United Nations Convention on the Rights of People with Disabilities, disability “results from the interaction between persons with impairments and attitudinal and environmental barriers that hinders their full and effective participation in society.”

- In other words, a disability is mainly a problem if the person is not able to participate fully in society.  We have the power to reduce those barriers.

- https://venturebeat.com/2018/12/03/how-to-tackle-ai-bias-for-people-with-disabilities/

=== Types of Disabilities

- Mobility
- Hearing
- Vision
- Processing information
- Language
- Attention span
- Emotional (including anxiety, depression, or need for personal space)

=== Important Deaf Cultural Notes

- When working with a deaf student, it is considered very rude for a hearing person to “make up” new signs.  

- If a deaf student is working with a sign language interpreter, make eye contact with the student, not the interpreter, when the interpreter speaks the words out loud.  Your conversation is with the student, not the interpreter.

=== Tips for working with people who are blind

- DO identify yourself when initiating a conversation and use the person’s name when talking to them.
- DON’T censor your language to avoid using words like “look.”
- DO describe the layout of large rooms, including how the furniture is arranged.
- DON’T be afraid to ask questions.  It’s better than making assumptions.
- DO give a verbal indication when you leave a conversation or a room.
- DON’T speak to or touch a guide dog.  They are working.
- DO provide electronic copies of materials in advance.
- DON’T use highly stylized typefaces.  Stick to sans-serif fonts like Arial or Calibri.
- DO add alternative text tags to graphics.
- https://www.perkins.org/stories/nine-essential-tips-for-working-with-people-who-are-blind
https://www.dhs.wisconsin.gov/blind/adjustment/dos-donts.htm  

== Why we need people with disabilities in data science

- To ensure AI-based systems are treating people with disabilities fairly, it is essential to include them in the development process. Developers must take the time to consider who the outliers might be, and who might be impacted by the solutions they are developing. 

- The best path ahead is to seek out the affected stakeholders and work with them towards a fair and equitable system. 

- If we can identify and remove bias against people with disabilities from our technologies, we will be taking an important step towards creating a society that respects and upholds the human rights of us all.

- https://venturebeat.com/2018/12/03/how-to-tackle-ai-bias-for-people-with-disabilities/ 

== Example of a data science corporate diversity and inclusion mission statement

- One of Mathematica’s core values is a deep commitment to diversity and inclusion. Building a welcoming and supportive culture that draws on the individual strengths of our employees from different ethnic backgrounds, cultures, abilities, and experiences is key to our success. Our research is more robust because it is informed by a variety of diverse perspectives, and our mission to improve societal well-being is strengthened by a greater understanding of issues and challenges facing the populations we serve. 

- Mathematica’s ongoing commitment to diversity and inclusion is woven into our everyday actions, policies, and practices. We are dedicated to maintaining a work environment in which everyone is treated with respect and dignity. We continually strive to foster a professional and collegial atmosphere that promotes equal employment opportunities and values the contributions of each staff member. 

== Diversity in The Data Mine

=== Impact

- This is the perfect place to make a real difference in the diversity of the data science community.
- We will be reaching over 600 students a year who will go out to work in data science-related careers.
- We have the opportunity to turn a lot of people on to data science if we do our jobs well.
- But we also have the opportunity to turn a lot of people off to data science we don’t pay attention to the culture of The Data Mine.
Let’s be thoughtful!

=== You are an ambassador

- It is an important part of your job as a T.A. to create a welcoming and diverse data science community here in The Data Mine.
- There is not one right type of person or one right way of approaching a problem in data science.
- We can all learn from each other.
- We all bring strengths and insights.
- You will be learning from your students, too.

=== The Data Mine is a home for everyone 
- People of all genders and sexualities.
- People of all races and ethnicity.
- People from throughout the country and around the world.
- People who might have accommodations for accessibility.
- People from all colleges and major programs.
- People of all ages and student classifications. 
- People with different academic and professional goals.
- People with previous data science experience or none at all.
- People who are confident or nervous.

Everybody is WELCOME and NEEDED in data science.  

== First Impressions video
++++
<iframe  class="video" width="560" height="315" src="https://www.youtube.com/watch?v=9rdHHkUomzw&t=122s&ab_channel=PurdueUniversityDiversity" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++