= TDM 10100: Python Project 7 -- 2024

**Motivation:** Functions are the backbone of code. Whether you have a goal of building a complex internet server, designing and creating your own videogame, or analyzing enormous swaths of data instantly, you will need to have a strong working knowledge of functions to do it. Functions enable you to write more readable code, apply custom-made operations in novel ways, and overall are a necessity as a data scientist. In this project, we'll begin to explore the differences between functions and methods in Python, and start to write our own as well!

**Context:** Again, we'll be building off of all the previous projects here. A strong ability to work with lists and dataframes, analyze documentation and learn from it, and iterate through large amounts of data using a variety of approaches will set you up for success in this project

**Scope:** Functions, objects, methods, Python

.Learning Objectives:
****
- Learn what a function is
- Learn the difference between a function and a method
- Learn about a few common, high-utility functions in Python
- Design and write your first functions
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about project submissions xref:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset(s):

- /anvil/projects/tdm/data/flights/1987.csv
- /anvil/projects/tdm/data/beer/reviews.csv

[IMPORTANT]
====
This project will be working with some larger datasets, so please be sure to reserve 3 cores when starting your Jupyter session. If you are getting a "kernel died" message when you attempt to run your code, feel free to increase it to 4 cores. If your kernel is still dying, please reach out to someone on the TDM team for assistance. You should not reserve more than 4 cores for this project.
====

== Questions

=== Question 1 (2 pts)

Let's begin by discussing functions. While we've already used numerous functions throughout this semester, we have not yet taken the time to explore what is going on behind the scenes. A function is, at its most basic, some code that takes input data, and returns output data. We often refer to the input data as 'parameters' or 'arguments' and the output data 'return values' or simply 'outputs'. The usefulness of functions comes from their reusability. If we need to do the same action at different points in the code, we can define a function that performs that action and use it repeatedly to make our code cleaner and more readable.

Functions are first **defined**: their name, the number of arguments and the name of each argument, the code that is performed each time the function is called, and what values are returned are defined in this part of the code. Then, when we want to use a function, we **call** it by writing its name along with any arguments we want to give it.

Let's look at a brief example below, demonstrating how a function is defined, the inputs it takes, and the value it returns. Please copy this into your Jupyter notebook and experiment with it to really get a feel for how things work before attempting to complete this question. Pay special attention to the comments dissecting each part of the code in detail if you are still having trouble understanding the program flow

[source, python]
----
# Nothing in between the equals signs gets run until
#   the function is called!!
# =====================================================
# define a function called foo, that takes two
#   arguments: bar and buzz
def foo(bar, buzz):

    # use the first argument, bar, in a print statement
    print(f"Hello {bar}, how are you?")

    # return an output of buzz times 10
    return buzz * 10
# =====================================================

# call the function with our own arguments, and
#   store the output to funcOut1
funcOut1 = foo("Jackson", 20)
print(funcOut1)

# we can also pass in defined variables as arguments,
#   like so:
var1 = "Jimbob"
var2 = 13
funcOut2 = foo(var1, var2)
print(funcOut2)
----

For this question, we want you to define your own function called `is_leap()` that takes one variable, called `year`, as input, and returns `True` if `year` is a leap year and `False` if year is not a leap year. (Hint: You should already have the code to do this in project 2, you just have to turn it into a function!!)

[NOTE]
====
Here are some test cases for you to use to double-check that your code is working as expected.
- 1896, 2000, 2004, 2008, and 2024 are all leap years
- 1700, 1900, and 2010 are all not leap years
====

.Deliverables
====
- A function, `is_leap()`, that returns a boolean dictating whether or not a function is a leap year or not
====

=== Question 2 (2 pts)

Awesome. We now know in a real sense what a function is, how to define it, and how to use it in our code. Let's keep building on this by reading in some data and learning how we can apply functions to dataframes all at once!

[IMPORTANT]
====
If you missed the note at the top of the project, I will reiterate here once more: you will very likely need to use at least 3 cores for this project. If you get a "kernel died" message, try using 3-4 cores instead of 2. If your kernel is still dying at 4 cores, please reach out to someone on the TDM team for assistance.
====

First off, read the "/anvil/projects/tdm/data/flights/1987.csv" data into a new dataframe called `flights_1987`. Print the head of the dataset.

You should notice a column called "DayOfWeek". Write a function called `dayNamer()` that, given a number for day of the week, returns the name of that day. Run it on at least 3 different rows of the data to verify that it works. (Hint: DayOfWeek depicts Monday as 1, Tuesday as 2, and so on.)

[NOTE]
====
The first 5 days in the data, in order, are Friday, Saturday, Thursday, Friday, Saturday. You can use this to test your function.
====

You can use the below code to test your function:

[source, python] 
----
for index, i in enumerate(flights_1987["DayOfWeek"]):
    print(f"Day {index + 1}: {dayNamer(i)}")
    if index == 4:
        break
----

.Deliverables
====
- a function called `dayNamer` that takes as input a number for the day of the week and returns as output a string that is the name of the day.
====

=== Question 3 (2 pts)

Great, we now have a function that converts a day number into a day name. Let's use this function to create a new column, "day_name", in our Pandas dataframe. However, there is a caveat: this is a **LOT** of data. If you try and iterate through it all with a for loop, your kernel will 
very likely die (or at the least run very slowly). 

Introducing: the https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html[`.apply()`] method. `.apply()` will allow us to apply a function to every row (or column, if you so choose) in a dataframe in a vectorized and efficient manner. Take a look at the below example, where I use this method to create a new column in our data using a nonsensical function I've written (very similar to what you have to do for this question).

[source, python]
----
def scaler(year):
    return year * 1000

flights_1987["nonsense_years"] = flights_1987["Year"].apply(scaler)
flights_1987.head()
----

[NOTE]
====
You can check your work here by printing the head of your dataframe and making sure the first 5 days match as expected in the previous question.
====

.Deliverables
====
- A new column, "day_name" in the dataframe, generated using your `dayNamer()` function and `apply()`, that is the names of each day corresponding to the pre-existing 'DayOfWeek' column
====

=== Question 4 (2 pts)

Now that we've got a good grasp on functions, let's discuss a small distinction we haven't yet covered. You likely noticed mention of `methods` several times throughout this course, oftentimes in association with things like `.head()` or even more recently `.apply()`. 

In a simple sense, methods are very similar to functions. They even look similar in how they are called and defined. While we won't be covering Object Oriented Programming in TDM 101, and thus won't be covering methods in detail, its important to understand some basics.

A method, similar to a function, is a reusable chunk of code. However, it is tied to an _object_, which is a tough concept to describe. Let's consider an example. If I define an object that is a "Basketball", methods are actions that I can perform with/on that object. For example, I might have methods like `.deflate()` or `.inflate()` or `.bounce()` to use with my basketball. If I have an instance of a "Basketball" object named "my_basketball", for example, I could call use my methods by running code like `my_basketball.inflate()` or `my_basketball.bounce()`.

One good example of this in code we've worked with is `.head()`. `.head()` is a method that works on a "dataframe" object and returns the first 5 rows of the data. Another example is the `.apply()` method that we used in the last question, which applies the function you provide as an argument to each row of the dataframe object that it is called on.

In this question, we want you to explore some new methods that we can use with Pandas dataframes. First, use `.value_counts()` to get a count of how many times each day occurs in the data (using the 'day_name' column you made in the last question). Then, use `len()` and division to figure out what percentage of the days in our data are each day of the week. Your final result should contain printed output with what proportion (or percentage) of our data occurred on each day of the week. Do not use any looping to solve this problem, as it will be both significantly slower and defeat the purpose of using `.value_counts()` and `len()`.

Finally, in a markdown cell, describe whether `.value_counts()` and `len()` are methods or functions. Justify your answer.

[NOTE]
====
We've now used https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html[`.value_counts()`] and https://www.w3schools.com/python/ref_func_len.asp[`len()`] in multiple projects, but feel free to refer back to their docs pages if necessary.
====

.Deliverables
====
- The proportion of each day in our dataset, printed out.
- A markdown cell identifying which of `.value_counts()` and `len()` was a function and which was a method.
====

=== Question 5 (2 pts)

For this last question, we'll start getting into the more complex functions that we'll be spending lots of time on in the next few projects. The function you will write for this question is as follows:

- called `prop_dict_maker()`
- Takes two arguments, a dataframe and a column
- Returns a dictionary of the proportions of each value in that column

If you're struggling with where to start, try and approach this problem like so:

. First, write some code to do this on a specific dataframe and column of your choice (Hint: We did this in the last problem!)
. Next, wrap that code in a function definition, and replace the dataframe and column you chose with your function arguments as needed.
. Finally, be sure that you are returning a dictionary as expected, and test your function a few times with known results.

Finally, run the following code:

[source, python]
----
# import our library
import pandas as pd

# read in some beer review data
beer_reviews = pd.read_csv("/anvil/projects/tdm/data/beer/reviews.csv")

# get a dictionary of user proportions
top_users = prop_dict_maker(beer_reviews, "username")

# print the top 5 users in the data
print(sorted(top_users, key=top_users.get, reverse=True)[:5])
----

Which should have an output like this if you did everything correctly:

`['Sammy', 'kylehay2004', 'acurtis', 'StonedTrippin', 'jaydoc']`

.Deliverables
====
- The `prop_dict_maker()` function as described above
- The results of running the provided testing code using your `prop_dict_maker()` function
====

== Submitting your Work

Congratulations, you've finished your first in-depth project on functions in Python! Going forward, you should be getting quite comfortable in writing your own functions to analyze data, perform calculations, and otherwise simplify repetitive tasks in your code. You should also be able to differentiate between methods and functions, and understand what notation you should use when calling something based on whether it is a function or a method.

In the next project, we'll finish up our exploration of functions in Python, and begin exploring visualizing data and analyzing it to create good summary statistics and graphics.

.Items to submit
====
- firstname_lastname_project7.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/current-projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====