= Tableau

Tableau is a Salesforce product that is used to create charts, graphs, dashboards and other visual mediums from data while at the same time integrating data sources and streamlining the data visualization process in general. It's drag and drop format is relatively easier to learn, while at the same time providing a very detailed functionality. 

== Common Applications

Tableau is used especially by data/business analysts of all kinds. Its relative accessibility means just about every industry will find people who use it, and its ease of integration makes it a common choice for small to medium sized businesses.

== Getting a License

https://guides.lib.purdue.edu/c.php?g=699997&p=4965839[Purdue students can get their license here]. For non-Purdue students, check your university ("<my university> tableau" should come up with the instructions to get the license) or go to https://www.tableau.com/blog/tableau-students-free-access-tableau-desktop#:~:text=Tableau%20Desktop%20is%20free%20for,out%20how%20to%20get%20started.[the Tableau for Students page from Tableau.com for other options.]

== Code Project: Learn Directly From Tableau

https://www.tableau.com/learn/training[The Tableau training videos are a great start to learning Tableau!]

== Resources

All resources are chosen by Data Mine staff to be of decent quality, and most if not all content is free. 

=== Books

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99170207974401081[Tableau Desktop Cookbook by Lorna Brown (O’Reilly, 2021)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99170208495101081[Innovative Tableau by Ryan Sleeper (O’Reilly, 2020)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma9917020768400108[Practical Tableau by Ryan Sleeper (O’Reilly, 2018)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/ufs51j/alma99170208187501081[Communicating Data with Tableau by Ben Jones (O’Reilly, 2014)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99170207767001081[Tableau Strategies by Ann Jackson and Luke Stanke (O’Reilly, 2021)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99170208450001081[Tableau Prep: Up & Running by Carl Allchin (O’Reilly, 2020)]

=== Articles

https://mavenanalytics.io/blog/how-to-learn-tableau-a-guide-for-beginners[How To Learn Tableau: A Guide For Beginners]

https://www.tableau.com/why-tableau/what-is-tableau[What is Tableau? (From The Makers of Tableau)]

https://medium.com/@niitwork0921/what-is-tableau-da98ce1526bd[What is Tableau? (Medium article)]

=== Free Courses    

https://www.simplilearn.com/tutorials/tableau-tutorial/tableau-charts[Simplilearn]