= Nagish

Welcome to the student resource section for the _Nagish_ corporate partnership project. + 
This is a "living" book that is continuously being updated. If you have any feedback, please write to datamine@purdue.edu

== Expectations
For this spring semester starting on Monday, February 6th, you're expected to: +

* attend 50-minute mentor meeting on Tuesdays at 12:30 PM Eastern Time. + 
* attend 2-hour lab on Mondays at 4:30 PM Eastern Time.
* submit a seminar project weekly due Friday at 11:59 PM PST on Gradescope.
* submit a sprint report bi-weekly due Wednesday at 11:59 PM PST on Gradescope.
* complete evaluation. (more information coming soon)

== Adding The Data Mine to your Resume
Please see the https://the-examples-book.com/crp/students/professional_development[Professional Development] section to learn how to add The Data Mine to your resume.

== Questions? Need Help?
* Check The Examples Book for course schedule with due dates
* Ask The Data Mine Staff
** Naomi and Kali are your go-to resource for questions specific to DEAF PODS
** Send us an email at datamine-help@purdue.edu for questions related to grades and techincal help [https://the-examples-book.com/crp/students/ds_team_support[see this page on asking for techincal help]]

== Schedule
[%header,format=csv,stripes=even,%autowidth.stretch]
|===      
Assignment,Due date (at 11:59 PST), Submission Location
Pre Survey, February 22, TBD
Seminar TDM 102 Project 1: https://the-examples-book.com/projects/current-projects/10200-2023-project01[Introduction to Python: part I],February 17,https://www.gradescope.com/[Gradescope] 
Corporate Partners Sprint Report 1, February 22,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 2: https://the-examples-book.com/projects/current-projects/10200-2023-project02[Introduction to Python: part II],February 24,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 3: https://the-examples-book.com/projects/current-projects/10200-2023-project03[Introduction to Python: part III],March 3,https://www.gradescope.com/[Gradescope] 
Corporate Partners Sprint Report 2, March 8,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 4: https://the-examples-book.com/projects/current-projects/10200-2023-project04[Scientific computing & pandas: part I],March 10,https://www.gradescope.com/[Gradescope] 
Mid Survey, March 10, TBD
Seminar TDM 102 Project 5: https://the-examples-book.com/projects/current-projects/10200-2023-project05[Functions: part I],March 24,https://www.gradescope.com/[Gradescope] 
Corporate Partners Sprint Report 3, March 29,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 6: https://the-examples-book.com/projects/current-projects/10200-2023-project06[Functions: part II],March 31,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 7: https://the-examples-book.com/projects/current-projects/10200-2023-project07[Scientific computing & pandas: part II],April 7,https://www.gradescope.com/[Gradescope] 
Corporate Partners Sprint Report 4, April 12,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 8: https://the-examples-book.com/projects/current-projects/10200-2023-project08[Scientific computing & pandas: part III],April 14,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 9: https://the-examples-book.com/projects/current-projects/10200-2023-project09[Scientific computing & pandas: part IV],April 21, https://www.gradescope.com/[Gradescope] 
Corporate Partners Sprint Report 5, April 26,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 10: https://the-examples-book.com/projects/current-projects/10200-2023-project10[Importing and using packages],April 28,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 11: https://the-examples-book.com/projects/current-projects/10200-2023-project11[Classes/dunder & attributes methods/etc: part I],May 5,https://www.gradescope.com/[Gradescope] 
Post Survey, May 5, TBD
|===
