= Mark Daniel Ward

https://datamine.purdue.edu[The Data Mine] +
Purdue University +
101 Foundry Drive +
West Lafayette, IN 47906 +
mailto:mdw@purdue.edu[mdw@purdue.edu] +
mailto:datamine@purdue.edu[datamine@purdue.edu] +
phone: (765)496-9563 +
VRS: (765)248-6858

== STAT/MA 41600 Probability Archive from the STAT-LLC (2014-2018)

2014 link:{attachmentsdir}/41600/2014/midtermexam1.pdf[Midterm Exam 1] and link:{attachmentsdir}/41600/2014/midtermexam1answers.pdf[Midterm Exam 1 answers] +
2014 link:{attachmentsdir}/41600/2014/midtermexam2.pdf[Midterm Exam 2] and link:{attachmentsdir}/41600/2014/midtermexam2answers.pdf[Midterm Exam 2 answers] +
 +
2015 link:{attachmentsdir}/41600/2015/midtermexam1.pdf[Midterm Exam 1] and link:{attachmentsdir}/41600/2015/midtermexam1answers.pdf[Midterm Exam 1 answers] +
2015 link:{attachmentsdir}/41600/2015/midtermexam2.pdf[Midterm Exam 2] and link:{attachmentsdir}/41600/2015/midtermexam2answers.pdf[Midterm Exam 2 answers] +
 +
2016 link:{attachmentsdir}/41600/2016/midtermexam1.pdf[Midterm Exam 1] and link:{attachmentsdir}/41600/2016/midtermexam1answers.pdf[Midterm Exam 1 answers] +
2016 link:{attachmentsdir}/41600/2016/midtermexam2.pdf[Midterm Exam 2] and link:{attachmentsdir}/41600/2016/midtermexam2answers.pdf[Midterm Exam 2 answers] +
 +
2017 link:{attachmentsdir}/41600/2017/midtermexam1.pdf[Midterm Exam 1] and link:{attachmentsdir}/41600/2017/midtermexam1answers.pdf[Midterm Exam 1 answers] +
2017 link:{attachmentsdir}/41600/2017/midtermexam2.pdf[Midterm Exam 2] and link:{attachmentsdir}/41600/2017/midtermexam2answers.pdf[Midterm Exam 2 answers] +
 +
2018 link:{attachmentsdir}/41600/2018/midtermexam1.pdf[Midterm Exam 1] and link:{attachmentsdir}/41600/2018/midtermexam1answers.pdf[Midterm Exam 1 answers] +
2018 link:{attachmentsdir}/41600/2018/midtermexam2.pdf[Midterm Exam 2] and link:{attachmentsdir}/41600/2018/midtermexam2answers.pdf[Midterm Exam 2 answers] +

== link:41600/day1.html[Outcomes, Events, and Sample Spaces]

== link:41600/day2.html[Probability]

== link:41600/day3.html[Independent Events]

== link:41600/day4.html[Conditional Probability]

== link:41600/day5.html[Bayes' Theorem]

== link:41600/day7.html[Random Variables; Discrete Versus Continuous]

== link:41600/day8.html[Probability Mass Functions and CDFs]

== link:41600/day9.html[Joint Distributions; Independence and Conditioning]

== link:41600/day10.html[Expected Values of Discrete Random Variables]

== link:41600/day11.html[Expected Values of Sums of Random Variables]

== link:41600/day12.html[Expected Values of Functions of Random Variables; Variance]

== link:41600/day15.html[Bernoulli Random Variables; Binomial Random Variables]

== link:41600/day16.html[Geometric Random Variables]

== link:41600/day17.html[Negative Binomial Random Variables]

== link:41600/day18.html[Poisson Random Variables]

== link:41600/day19.html[Hypergeometric Random Variables]

== link:41600/day22.html[Discrete Uniform Random Variables; and Counting]

== link:41600/day24.html[Continuous Random Variables]

== link:41600/day25.html[Jointly Distributed Continuous Random Variables]

== link:41600/day26.html[Independent Continuous Random Variables]


This material is based upon work supported by the National Science Foundation under Grant Numbers 0939370, 1140489, 1246818.  Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the National Science Foundation.
