= Mark Daniel Ward

https://datamine.purdue.edu[The Data Mine] +
Purdue University +
101 Foundry Drive +
West Lafayette, IN 47906 +
mailto:mdw@purdue.edu[mdw@purdue.edu] +
mailto:datamine@purdue.edu[datamine@purdue.edu] +
phone: (765)496-9563 +
VRS: (765)248-6858

== STAT/MA 41600 Probability

This is Dr Ward's problem archive from the STAT-LLC (2014-2018) +
 +
2014 link:{attachmentsdir}/41600/2014/midtermexam1.pdf[Midterm Exam 1] and link:{attachmentsdir}/41600/2014/midtermexam1answers.pdf[Midterm Exam 1 answers] +
2014 link:{attachmentsdir}/41600/2014/midtermexam2.pdf[Midterm Exam 2] and link:{attachmentsdir}/41600/2014/midtermexam2answers.pdf[Midterm Exam 2 answers] +
 +
2015 link:{attachmentsdir}/41600/2015/midtermexam1.pdf[Midterm Exam 1] and link:{attachmentsdir}/41600/2015/midtermexam1answers.pdf[Midterm Exam 1 answers] +
2015 link:{attachmentsdir}/41600/2015/midtermexam2.pdf[Midterm Exam 2] and link:{attachmentsdir}/41600/2015/midtermexam2answers.pdf[Midterm Exam 2 answers] +
 +
2016 link:{attachmentsdir}/41600/2016/midtermexam1.pdf[Midterm Exam 1] and link:{attachmentsdir}/41600/2016/midtermexam1answers.pdf[Midterm Exam 1 answers] +
2016 link:{attachmentsdir}/41600/2016/midtermexam2.pdf[Midterm Exam 2] and link:{attachmentsdir}/41600/2016/midtermexam2answers.pdf[Midterm Exam 2 answers] +
 +
2017 link:{attachmentsdir}/41600/2017/midtermexam1.pdf[Midterm Exam 1] and link:{attachmentsdir}/41600/2017/midtermexam1answers.pdf[Midterm Exam 1 answers] +
2017 link:{attachmentsdir}/41600/2017/midtermexam2.pdf[Midterm Exam 2] and link:{attachmentsdir}/41600/2017/midtermexam2answers.pdf[Midterm Exam 2 answers] +
 +
2018 link:{attachmentsdir}/41600/2018/midtermexam1.pdf[Midterm Exam 1] and link:{attachmentsdir}/41600/2018/midtermexam1answers.pdf[Midterm Exam 1 answers] +
2018 link:{attachmentsdir}/41600/2018/midtermexam2.pdf[Midterm Exam 2] and link:{attachmentsdir}/41600/2018/midtermexam2answers.pdf[Midterm Exam 2 answers] +

== Outline of Topics

=== Outcomes, Events, and Sample Spaces

1.1 definitions (link:{attachmentsdir}/41600/notes/prob0101.pdf[pdf] / https://mediaspace.itap.purdue.edu/media/prob0101.mp4/1_sta6spse[video]) +
1.2 dice example (link:{attachmentsdir}/41600/notes/prob0102.pdf[pdf] / https://mediaspace.itap.purdue.edu/media/prob0102.mp4/1_mkeizzzi[video]) +
1.3 coin flip example (link:{attachmentsdir}/41600/notes/prob0103.pdf[pdf] / https://mediaspace.itap.purdue.edu/media/prob0103.mp4/1_kba0ls1o[video]) +
1.4 DeMorgan's First Law (link:{attachmentsdir}/41600/notes/prob0104.pdf[pdf] / https://mediaspace.itap.purdue.edu/media/prob0104.mp4/1_xw2wpbki[video]) +
1.5 DeMorgan's Second Law (link:{attachmentsdir}/41600/notes/prob0105.pdf[pdf] / https://mediaspace.itap.purdue.edu/media/prob0105.mp4/1_ntyycvng[video]) +
1.6 how many events (link:{attachmentsdir}/41600/notes/prob0106.pdf[pdf] / https://mediaspace.itap.purdue.edu/media/prob0106.mp4/1_gh4gy9hr[video]) +
1.7 sample spaces (link:{attachmentsdir}/41600/notes/prob0107.pdf[pdf] / https://mediaspace.itap.purdue.edu/media/prob0107.mp4/1_jz88d2ui[video]) +
 +
link:{attachmentsdir}/41600/practice/practiceset01.pdf[Practice Problems] and link:{attachmentsdir}/41600/practice/practiceset01answers.pdf[Practice Solutions] +
 +
2014 link:{attachmentsdir}/41600/2014/inclassset01.pdf[In-Class Problem Set] and link:{attachmentsdir}/41600/2014/inclassset01answers.pdf[In-Class Problem Set Solutions] +
2015 link:{attachmentsdir}/41600/2015/inclassset01.pdf[In-Class Problem Set] and link:{attachmentsdir}/41600/2015/inclassset01answers.pdf[In-Class Problem Set Solutions] +
2016 link:{attachmentsdir}/41600/2016/inclassset01.pdf[In-Class Problem Set] and link:{attachmentsdir}/41600/2016/inclassset01answers.pdf[In-Class Problem Set Solutions] +
2017 link:{attachmentsdir}/41600/2017/inclassset01.pdf[In-Class Problem Set] and link:{attachmentsdir}/41600/2017/inclassset01answers.pdf[In-Class Problem Set Solutions] +
2018 link:{attachmentsdir}/41600/2018/inclassset01.pdf[In-Class Problem Set] and link:{attachmentsdir}/41600/2018/inclassset01answers.pdf[In-Class Problem Set Solutions] +

=== Probability

2.1 probability rules (link:{attachmentsdir}/41600/notes/prob0201.pdf[pdf] / https://mediaspace.itap.purdue.edu/media/prob0201.mp4/1_pnluh27w[video]) +
2.2 probability of empty set (link:{attachmentsdir}/41600/notes/prob0202.pdf[pdf] / https://mediaspace.itap.purdue.edu/media/prob0202.mp4/1_gvn9c4ox[video]) +
2.3 union of finitely many events (link:{attachmentsdir}/41600/notes/prob0203.pdf[pdf] / https://mediaspace.itap.purdue.edu/media/prob0203.mp4/1_zjtqfzw2[video]) +
2.4 equally likely outcomes (link:{attachmentsdir}/41600/notes/prob0204.pdf[pdf] / https://mediaspace.itap.purdue.edu/media/prob0204.mp4/1_xmvluvej[video]) +
2.5 more equally likely outcomes (link:{attachmentsdir}/41600/notes/prob0205.pdf[pdf] / https://mediaspace.itap.purdue.edu/media/prob0205.mp4/1_47va4953[video]) +
2.6 examples (link:{attachmentsdir}/41600/notes/prob0206.pdf[pdf] / https://mediaspace.itap.purdue.edu/media/prob0206.mp4/1_axbmq2ac[video]) +
2.7 setminus and partition (link:{attachmentsdir}/41600/notes/prob0207.pdf[pdf] / https://mediaspace.itap.purdue.edu/media/prob0207.mp4/1_msvsenjh[video]) +
2.8 inclusion/exclusion (link:{attachmentsdir}/41600/notes/prob0208.pdf[pdf1] / link:{attachmentsdir}/41600/notes/prob0208.pdf[pdf2] / https://mediaspace.itap.purdue.edu/media/prob0208.mp4/1_ofetfx5z[video]) +
 +
link:{attachmentsdir}/41600/practice/practiceset02.pdf[Practice Problems] and link:{attachmentsdir}/41600/practice/practiceset02answers.pdf[Practice Solutions] +
 +
2014 link:{attachmentsdir}/41600/2014/inclassset02.pdf[In-Class Problem Set] and link:{attachmentsdir}/41600/2014/inclassset02answers.pdf[In-Class Problem Set Solutions] +
2015 link:{attachmentsdir}/41600/2015/inclassset02.pdf[In-Class Problem Set] and link:{attachmentsdir}/41600/2015/inclassset02answers.pdf[In-Class Problem Set Solutions] +
2016 link:{attachmentsdir}/41600/2016/inclassset02.pdf[In-Class Problem Set] and link:{attachmentsdir}/41600/2016/inclassset02answers.pdf[In-Class Problem Set Solutions] +
2017 link:{attachmentsdir}/41600/2017/inclassset02.pdf[In-Class Problem Set] and link:{attachmentsdir}/41600/2017/inclassset02answers.pdf[In-Class Problem Set Solutions] +
2018 link:{attachmentsdir}/41600/2018/inclassset02.pdf[In-Class Problem Set] and link:{attachmentsdir}/41600/2018/inclassset02answers.pdf[In-Class Problem Set Solutions] +

