= Catalyst

In 1794, Elizabeth Fulhame introduced and analyzed the concept of catalysis, in her book _An Essay on Combustion, with a View to a New Art of Dying and Painting, wherein the Phlogistic and Antiphlogistic Hypotheses are Proved Erroneous_.

.The Oxford English Dictionary provides an early description of the usage of the word *catalytic*, in 1836:
[quote,translation of J. J. Berzelius,Edinburgh New Philosophical Journal vol. 21 227]
"Many substances..possess the power of exercising upon compound bodies an influence essentially distinct from chemical affinity, an influence which consists in the production of a displacement, and a new arrangement of their elements, without their directly and necessarily participating in it... In defining it a new power..I shall designate it..the _catalytic power_ of bodies; and the decomposition it produces I shall call _catalysis_."

The Data Mine enables students to learn data science tools and methodologies at an early point in their career, before they enter the workforce.  They also learn domain-specific skills first-hand from their mentors in industry.  As a result, The Data Mine is a catalyst for change:  The students are making a significant impact even before they have graduated and joined the workforce.

== Prioritizing the Needs of Others

We owe our philosophy for The Data Mine's modus operandi to Dr. E. Daniel "Dan" Hirleman and Dr. David "Dave" McKinnis, and implemented at the earliest stages by Ms. Margaret "Maggie" Betz.  Dan had the early idea that companies might be willing to negotiate new contracts with Purdue University.  The companies would explain their most pressing data science needs to students, and the students would actively work to provides solutions to meet the companies' needs.  In this way, the companies would proactive accomplish cutting-edge work in the data sciences, and the students would enable the design of new algorithms, applications, environments, methodologies, and tools.  These partnerships would result in a tremendous return on investment for the companies, and would enable students to have a much deeper understand of the applications of data science in the workforce.  Dave provided brilliant guidance about the business model.  Essentially, paraphrasing his advice, he told encouraged us: "Never worry about the money: If the students have a great experience, and the companies have a great experience, the money will come naturally."  Wow, Dave was right!  Maggie developed these ideas into a mature, systematic model of engagement between students and their industry mentors.  As a result, The Data Mine has enabled numerous new and ongoing partnerships between universities and Corporate Partners all over the world.

== Origins

The first written description of The Data Mine, from a recruiting email draft on November 17, 2017, to Haley Cutler and Jonathan Manz:

"I am pleased to mention a new opportunity that might interest you.  We are starting a new Living-Learning Community for 2018-19 called "The Data Mine".  We have an inclusive approach that enables students from any data-driven discipline to make it "mine".  Indeed, students from any college on campus can apply.  Each student will participate in a 1 credit seminar for data-driven professional development, including a mix of training and guest speakers.  By learning and living with other students in Hillenbrand, we will foster a welcoming environment for all students who want to work in data-driven careers of all kinds.  We will also attempt (although we cannot guarantee) to find research experiences on campus for students who want to be involved in data-driven projects."

In fall 2018, The Data Mine seminar was launched.  It consisted of a 1-credit data science seminar, led by Mark Daniel Ward, and also a partnership with Viasat, in which one small team of students worked on a research project with Mark Rapo and Gideon Shalev.

Ellen Gundlach joined The Data Mine as Managing Director in May 2019, and The Data Mine launched a wide variety of academic learning communities for students at Purdue University.  Eric Zinn, in his role as Vice President for Student Corporate Experience Development at Purdue Research Foundation, helped to foster the concept of working with a handful of companies during academic year 2019-20.  Kevin Amstutz joined in October 2019 as Instruction Specialist.  In December 2019, Maggie Betz joined The Data Mine as Corporate Partners Senior Manager.

== Academic Programs

We should go through the old Data Mine website datamine.purdue.edu
and make sure that we are not forgetting any programs.

* Actuarial Science
** Jeff Beckley, Shane Leib, Jianxi Su
** STAT 17000, STAT 41600, STAT 41700, STAT 47301, STAT 49000
* Agriculture
** Jeff Holland
** AGR 29000 and ENTM 24200
* Biology
** Michael Gribskov, Andrea Kasinski
** BIOL 19500, 29500, 39500, and BIOL 23100 for Biology majors who do not (yet) have this course
* Chemistry
** Beatriz Cisneros, Jonathan Reinstra-Kiracofe, Christine Schertz, Paul Wenthold
** CHM 12500, CHM 19400
* Computational Investigative Living Systems
** Sri Iyer-Biswas and Rudro Biswas
** PHYS 39000
* Critical Data Studies
** Faithe Day, Bethany McGowan, Kendall Roark, Danielle N. Walker, Jason Ware, Lindsay Weinberg, and Laura Zanotti
** HONR 39900, ILS 23000, ILS 49500, and ILS 59500
* Data and Society
** see also Philosophy and Political Science
** PHIL 20800 and POL 22900
* Data Visualization
** Vetria Byrd
** CGT 27000, CGT 27001, and CGT 29000
* Digital Gaming and Culture
** Samantha Blackmon
** ENGL 20300, ENGL 28000
* EAPS
** Alexander Gluhovsky, Matthew Huber, and Robin Tanamachi
** EAPS 19100 and EAPS 22700
* HDFS
** Sharon Christ
** HDFS 39000, PUBH 49000
* Institutional Assessment
** Steve Beaudoin, Natasha Harris, Kendal S. Kosta-Mikel, Yukiko Maeda, David Nelson, Arman Sabbaghi
** HONR 49900 and STAT 19000
* Krannert
** Mohammad Rahman and Roy Dejoie
** MGMT 28800 and MGMT 29000
* Nursing
** Qinglan (Priscilla) Ding, Sandra J. (Sandi) Gilpin, Laura Moffat
** NUR 10800, NUR 21801
* Pharmacy
** Amy Childress, Tony Hazbun, Tonglei Li, and JJ Sadler
** GS 29501, GS 39501, and PHRM 49500
* Philosophy
** Michael Flierl, Matthew Kroll, Stephanie Lynn Parrish, Chris Yeomans
** PHIL 12000, POL 30000, SCLA 10100, PHIL 20800
* Political Science
** Jay McCann and Eric Waltenburg
** POL 10100, POL 30000, PHIL 20800, SCLA 10200(15342)
* Physics
** Andy Jung, Rafael Lang, Mia Liu, Danny Milisavljevic
** PHYS 32300, PHYS 32400, and PHYS 39000
* Psychology
** Gregory Francis, Jill Gulker, Jeff Karpicke, Peter Urcuioli
** PSY 12000, PSY 39200
* RCHE
** Po-Ching Delaurentis, Paul Griffin, Lingsong Zhang
** STAT 29000
* Statistics
** Bruce Craig, Alan Friedman, Andy Hirsch, Chuanhai Liu, Vinayak Rao, Michelle Redmond
** STAT 10100, STAT 19000, and STAT 49000
* VIP
** Jan Allebach, Yung-Hsiang Lu, Cyndi Lynch, Nichole Ramirez, Carla Zoltowski
** ECE 17920, ECE 27900, ECE 37900, ECE 47900, ENGR 29600, ENGR 39600, ENGR 49600


== State of The Data Mine

At the time of writing, The Data Mine has 24 employees, more than 1500 undergraduate and graduate students, and more than 80 partnerships with companies and universities... and we are still at the beginning.  In its sixth year of operation, The Data Mine is self-funded and brings millions of dollars of revenue to the university.  

== Art of the Possible




==

Team Members:

Mark Daniel Ward

* Director of The Data Mine, August 2018-September 2023
* Executive Director of The Data Mine, September 2023-present

Ellen Gundlach

* Managing Director of The Data Mine, May 2019-June 2021

Kevin Amstutz

* Instruction Specialist, October 21, 2019-July 2022
* Senior Data Science Instruction Specialist, July 2022-April 2023
* Senior Data Scientist, June 2020-present

Margaret "Maggie" Betz

* Corporate Partners Senior Manager, December 16, 2019-March 2021
* Corporate Partnerships Managing Director, March 2021-present

Justin Gould

* Senior Data Scientist, December 2020-September 2021

Heather Goodwin

* Corporate Partners Senior Manager, July 2021-April 2022

Sarah Rodenbeck

* Senior Data Scientist, July 2021-September 2021

David "Dave" Kotterman

* Managing Director, August 2021-February 2022

David Glass

* Senior Data Scientist, August 2, 2021-June 2022
* Managing Director for Data Science, June 2022-present

Nicole Finley

* Operations Manager, August 2021-April 2022

Rebecca Sharples

* Managing Director of Academic Programs and Outreach, August 2021-October 2023

Kalika "Kali" Lacy

* Associate Research Analyst, October 11, 2021-present

Jamie Baker

* Senior Administrative Assistant, October 2021-May 2022

Naomi Mersinger

* ASL Interpreter and Strategic Initiatives Coordinator, November 15, 2021-present

Shuennhau Chang

* Corporate Partners Senior Manager, January 2022-October 2022

Kimberly "Kim" Rechkemmer

* Senior Program Administration Specialist, April 25, 2022-present

Katherine "Katie" Sanders

* Operations Manager, May 23, 2022-present

Nicholas "Nick" or "Rosey" Rosenorn

* Corporate Partners Technical Specialist, June 1, 2022-March 22, 2024

Jessica Jud

* Senior Manager of Expansion Operations, August 29, 2022-present

Nicholas "Lenny" Lenfestey

* Corporate Partners Technical Specialist, October 17, 2022-present

Emily L Hoeing

* Corporate Partners Advisor, December 5, 2022-present

Elizabeth "Betsy" Satchell

* Senior Administrative Assistant, January 23, 2023-present

Kimie "Kimmie" Casale

* ASL Instructor, March 6, 2023-present

Douglas "Doug" Crabill

* Senior Data Scientist, April 17, 2023-present

Lauren Terese Dalder

* Corporate Partners Advisor, April 19, 2023-present

Cai Shun Chen

* Corporate Partners Technical Specialist, May 15, 2023-present

Joshua "Josh" Winchester

* Data Science Technical Specialist, July 10, 2023-present

Ning "Cindy" Zhou

* Senior Data Science Instructional Specialist, July 17, 2023-present

Gloria Lenfestey

* Research Development Administrator, July 31, 2023-present

Elizabett "Betsy" Hillery

* Principal Business Development Administrator, July 2023-present

Stacey Dunderman

* Lead Program Administration Specialist, August 14, 2023-present

Donald Barnes

* Guest Relations Administrator, August 28, 2023-present

