= Mark Daniel Ward

https://datamine.purdue.edu[The Data Mine] +
Purdue University +
101 Foundry Drive +
West Lafayette, IN 47906 +
mailto:mdw@purdue.edu[mdw@purdue.edu] +
mailto:datamine@purdue.edu[datamine@purdue.edu] +
phone: (765)496-9563 +
VRS: (765)248-6858

== Current Position

I am a Professor of Statistics and (by courtesy) of Agricultural & Biological Engineering, Computer Science, Mathematics, and Public Health at Purdue University. My research is in probabilistic, combinatorial, and analytic techniques for the analysis of algorithms and data structures.  I am also interested in data science, science of information, game theory, and large-scale computation. I currently serve as Executive Director of https://datamine.purdue.edu[The Data Mine].

== Visiting Faculty Positions

École Polytechnique, Palaiseau, France +
Invited Professor in the Algorithms and Models for Integrative Biology team, November-December 2015 +
 +
The George Washington University, Washington, DC +
(sabbatical) Adjunct Professor in the Department of Statistics, September 2013-May 2014 +
 +
University of Maryland, College Park, MD +
(sabbatical) Visiting Professor in the Department of Mathematics, July 2013-June 2014 +
 +
Université de Paris 13, Villetaneuse, France +
Invited Professor at the Laboratoire Informatique de Paris Nord (LIPN), February-March 2012 +
 +
University of Pennsylvania +
(postdoc) Lecturer in Mathematics, 2005-2007


== Education

Purdue University +
Ph.D., Mathematics with Specialization in Computational Science, May 2005 +
Dissertation: Analysis of the Multiplicity Matching Parameter in Suffix Trees +
Advisor: Wojciech Szpankowski +
 +
University of Wisconsin-Madison +
M.S., Applied Mathematical Sciences, May 2003 +
Thesis: Analysis of a Randomized Selection Algorithm +
 +
Denison University +
B.S., Mathematics and Computer Science, summa cum laude, May 1999 +
Senior Honors Project: Mathematical Foundations for Performance Analysis +


== Contracts and Corporate Partnerships

The Data Mine coordinates contracts for corporate partnerships with AbbVie, Aerospace Corporation, Allison Transmission, AstraZeneca, ATOM, BASF, Bayer, Beck's Hybrids, Blue Wave AI, Boeing, CAS, Caterpillar, CDC, Center for C-SPAN Scholarship and Education, Cisco, Co-Alliance, Cook Medical, Cummins, deaffriendly, Debaterly, DORIS, Elanco, Eli Lilly, Finish Line, FSSA, Howmet Aerospace, HUMN Capital, Indiana Crop Improvement Association, Indiana Soybean Alliance, Ingenii, Innivee Strategies, Inogen, John Deere, Knudsen Institute, Lockheed Martin Company, Merck, Microsoft, Military Family Research Institute, MISO, Molecular Stethoscope, Nagish, Nationwide, No Limit Living, Pacific Life, Pacific Northwest National Laboratory, Procter & Gamble (P&G), Pro Football Focus, Purdue Athletics, Purdue Student Life, Raytheon, Renzoe Box, Sandia, Stratolaunch, Tesla, Thermo Fisher, USAA, USDA US Forest Service, V2X, Viasat, Wabash, Webee, Wikimedia, Yamaha. +
 +

== Grants

National Science Foundation OAC-#2118329: HDR Institute: Geospatial Understanding through an Integrative Discovery Environment (2021-2026) +
 +
National Institute of Food and Agriculture: Data Science and Analytics for Precision Livestock Systems (2021-2026) +
 +
National Science Foundation DMS-#2123321: HDR DSC: National Data Mine Network (2021-2024) +
 +
Lilly Endowment: Charting the Future for Indiana's Colleges and Universities: The Indiana Data Mine (2021-2025) +
 +
National Institute of Food and Agriculture: Computational Skills Development for Next Generation Agriscience Professionals for Sustaining Data Driven Agriculture (2020-2023) +
 +
National Science Foundation OAC-#2005632: Category I: Anvil---A National Composable Advanced Computational Resource for the Future of Science and Engineering (2020-2022) +
 +
Inspiring Actuarial Education through Learning Communities and Research Experiences; from the Society of Actuaries (2019-2021) +
 +
National Institute of Food and Agriculture: Experiential Learning with Data Tools for Digital Agriscience and FACT (2019-2023) +
 +
Foundation for Food and Agriculture Research: An Open Source Framework and Community for Sharing Data and Algorithms (2018-2022) +
 +
National Science Foundation DMS-#1600382: Lake Michigan Workshop on Combinatorics and Graph Theory (2016) +
 +
National Science Foundation DMS-#1560332: REU Site: Diverse Undergraduate Research Experiences in Statistics (2016-2018) +
 +
National Science Foundation DMS-#1246818: MCTP: Sophomore Transitions: Bridges into a Statistics Major and Big Data Research Experiences via Learning Communities (2013-2018) +
 +
National Science Foundation CCF-#0939370: Science and Technology Centers: Integrative Partnerships Program: Emerging Frontiers of Science of Information (2010-2024) +
 +
National Science Foundation DUE-#1140489/#1140519: Collaborative Research: Science of Information: Bringing Many Disciplines Together (2012-2014) +
 +
Army Research Office: Stochastic Control of Multi-scale Networks (2008-2014) +
 +
National Science Foundation DMS-#0603821: Asymptotic Enumeration, Reinforcement, and Effective Limit Theory (2006-2009)

== Honors

Pillar of CERIAS Award to The Purdue Data Mine, Dr. Mark Daniel Ward, Director, 2023 +
Learning Community Academic Connection Award, 2022-2023 +
College of Science Diversity Award, 2022-2023 +
Learning Community Student Impact Award, 2019-2020 +
Focus Award, 2019 +
Mu Sigma Rho William D. Warde Statistics Education Award, 2016 +
Statistics Advising Award, 2015-2016 +
Voted as the Most Outstanding Faculty in the Favorite Faculty program, 2015-2016 +
Fellow of the Purdue University Teaching Academy, 2015-present +
College of Science Undergraduate Advising Award, 2015-2016 +
College of Science Team Award, 2014-2015 +
Excellence in Research Award (for $1 million or larger external grants) 2011, 2012, 2013, 2015 +
College of Science Graduate Student Mentoring Award, 2012-2013 +
College of Science Team Award, 2011-2012 +
Junior Oberwolfach Fellow at the Mathematisches Forschungsinstitut Oberwolfach (MFO) in Germany, April 2011 +
College of Science Interdisciplinary Award, 2010-2011 +
Purdue University Teaching for Tomorrow Award, 2010-2011 +
Purdue University's Mortar Board Chapter Citation Award, 2009-2010 +
College of Science Faculty Award for Outstanding Contributions to Undergraduate Teaching by an Assistant Professor, 2009-2010 +
College of Science Undergraduate Advising Award, 2009-2010 +
Department of Statistics Outstanding Assistant Professor Teaching Award, 2008-2009 +
Top Ten Outstanding Teacher in College of Science, 2007-2008 +
Good Teaching Award (Penn) in Math 104, Spring 2007 +
Good Teaching Award (Penn) in Math 104 and Math 580, Fall 2006 +
Good Teaching Award (Penn) in Math 104, Spring 2006 +
Good Teaching Award (Penn) in Math 104 and Math 432, Fall 2005 +
Actuarial Science Program Scholarship (Purdue), Fall 2004 +
Excellence in Teaching Award (Purdue), Spring 2004 +
GAANN Fellowship in Computational Science and Engineering (Purdue), 2002-2005 +
Frederick N. Andrews Fellowship in Mathematics (Purdue), 2001-2002 +
GAANN Fellowship in Mathematics and Computation in Engineering (Wisconsin), 1999-2001 +
Phi Beta Kappa, elected in 1999 +
Sigma Xi +
Faculty Scholarship for Achievement (full tuition at Denison), 1995-1999 +
Anderson Science Scholarship (full tuition at Denison, 1 of 2 selected), 1995-1999

== Publications

[%reversed]
. Asymptotic Analysis of Combinatorial Transformations of Polylogarithms, by Ricardo Gómez-Aíza and Mark Daniel Ward, 12 pages, submitted for publication.
. The Data Mine Model for Accessible Partnerships in Data Science, by Maggie Betz, Rebecca Sharples, and Mark Daniel Ward, WIREs Computational Statistics, Volume 16, Issue 1, 17 pages, January/February 2024.
. A Unified Treatment of Families of Partition Functions, by Lida Ahmadi, Ricardo Gómez-Aíza, and Mark Daniel Ward, La Matematica, Volume 3, 1257-1296, 2024.
. The Number of Distinct Adjacent Pairs in Geometrically Distributed Words: A Probabilistic and Combinatorial Analysis, by Guy Louchard, Werner Schachinger, and Mark Daniel Ward, Discrete Mathematics and Theoretical Computer Science, Volume 25, Issue 2, paper #3 (46 pages), 2023.
. Developing Students from All Backgrounds in Data Science for the Government, by Rebecca Sharples and Mark Daniel Ward. Chapter 7 in Liebowitz, Jay (Ed.), Pivoting Government Through Digital Transformation (pp. 95-108). Taylor and Francis, 2023.
. Undergraduate Data Science, by Rachel Saidi, Rebecca Sharples, and Mark Daniel Ward, Chapter 15 in the book "Using Data-Centric Methods to Teach Introductory Statistics", Edited by Donna LaLonde and Deirdre Longacher Smeltzer, Mathematical Association of America, MAA Notes Volume 99, pages 125-132 (2024).
. A Mixed-Methods Approach to Understand University Students' Perceived Impact of Returning to Class During COVID-19 on Their Mental and General Health, by Qinglan Ding, Mark Daniel Ward, Nancy Edwards, Emily Anna Wu, Susan Kersey, and Marjorie Funk, PLOS ONE 18(1): e0279813, 21 pages (2023).
. Characterizing the Identity Formation and Sense of Belonging of the Students Enrolled in a Data Science Learning Community, by Aparajita Jaiswal, Alejandra Magana, and Mark Daniel Ward, Education Sciences, Volume 12, Issue 10, 16 pages (2022).
. "Mine" the Gap: Connecting Curriculum, Courses, and Community, by J. W. Manz, M. D. Ward, and E. Gundlach. In J. E. Eidum and L. Lomicka, editors, Faculty Factor: Developing Faculty Engagement with Living Learning Communities, chapter 8. Center for Engaged Learning at Elon University, 2022. Also contains vignette "The Impact of Experiential Learning" by Tim Knight.
. Student Experiences within a Data Science Learning Community: A Communities of Practice Perspective, by Aparajita Jaiswal, Alejandra Magana, Joseph A. Lyon, Ellen Gundlach, and Mark D. Ward, Learning Communities Research and Practice, Volume 9, Issue 1 (2021).
. Evaluating Student Experiences in a Residential Learning Community: A Situated Learning Perspective, by Aparajita Jaiswal, Joseph A. Lyon, Viranga Perera, Alejandra J. Magana, Ellen Gundlach, Mark D. Ward, accepted for publication in the American Society for Engineering Education (ASEE) Annual Conference (2021).
. Characterizing the psychosocial effects of participating on a year-long residential research-oriented learning community, by Alejandra J. Magana, Aparajita Jaiswal, Aasakiran Madamanchi, Loran C. Parker, Ellen Gundlach, Mark D. Ward, Volume 42, pages 2850–2867, (2023).
. The number of distinct adjacent pairs ingeometrically distributed words, by Margaret Archibald, Aubrey Blecher, Charlotte Brennan, Arnold Knopfmacher, Stephan Wagner, Mark Daniel Ward, 18 pages, Discrete Mathematics and Theoretical Computer Science, Volume 22, no. 4, paper 10, 2021.
. Research Experiences in the Statistics Living Learning Community, by Maggie Betz, Peter Boyd, Emily Damone, Christina DeSantiago, Kent Gauen, Katie Lothrop, Mikaela Meyer, Kristen Mori, Ashley Peterson, Mark Daniel Ward, 12 pages, Chapter 6 of the book "Expanding Undergraduate Research in Mathematics: Making UR More Inclusive." edited by Michael Dorff, Jan Rychtář, and Dewey Taylor (MAA Notes, Volume 94), MAA Press, 2023.
. The Data Mine: Enabling Data Science Across the Curriculum, by E. Gundlach and M. D. Ward, Journal of Statistics and Data Science Education, Volume 29 (2021), supplement, S74-S82.
. The Periodicity of Nim-Sequences in Two-Element Subtraction Games, by B. Benesh, J. Carter, D. Crabill, D. Coleman, J. Good, M. Smith, J. Travis, and M. D. Ward, INTEGERS: Electronic Journal of Combinatorial Number Theory, Volume 20 (2020), 6 pages (link:{attachmentsdir}/paper044.pdf[pdf]).
. The Next Wave: We Will All Be Data Scientists, by M. Betz, E. Gundlach, E. Hillery, J. Rickus, and M. D. Ward, Statistical Analysis and Data Mining, volume 13 (2020), 544-547 (link:{attachmentsdir}/paper043.pdf[pdf]).
. Asymptotic Analysis of the kth Subword Complexity, by L. Ahmadi and M. D. Ward, Entropy, Volume 22, Issue 2 (2020), 34 pages (link:{attachmentsdir}/paper042.pdf[pdf]).
. Fostering Undergraduate Data Science, by F. Gokalp Yavuz and M. D. Ward, The American Statistician, volume 74 (2020), 8-16 (link:{attachmentsdir}/paper041.pdf[pdf]).
. Purdue University: Statistics Living Learning Community, by L. C. Parker and M. D. Ward, Aligning Institutional Support for Student Success: Case Studies of Sophomore-Year Initiatives, National Resource Center for The First-Year Experience & Students in Transition, University of South Carolina, edited by Tracy Skipper, September 2019 (link:{attachmentsdir}/paper040.pdf[pdf]).
. Undergraduate Data Science and Diversity at Purdue University, by E. Hillery, M. D. Ward, J. Rickus, A. Younts, P. Smith, and E. Adams, PEARC '19: Proceedings of the Practice and Experience in Advanced Research Computing on Rise of the Machines, July 2019, Article No. 88 (link:{attachmentsdir}/paper039.pdf[pdf]).
. The Characterization of Tenable Pólya Urns, by A. Davidson and M. D. Ward, Statistics and Probability Letters, volume 135 (2018), 38-43 (link:{attachmentsdir}/paper038.pdf[pdf]).
. Asymptotic Analysis of Sums of Powers of Multinomial Coefficients: A Saddle Point Approach, by G. Louchard and M. D. Ward, INTEGERS: Electronic Journal of Combinatorial Number Theory, volume 17 (2017), paper A47 (27 pages) (link:{attachmentsdir}/paper037.pdf[pdf]).
. Building Bridges: The Role of an Undergraduate Mentor, by M. D. Ward, invited submission for The American Statistician, volume 71 (2017), 30-33 (link:{attachmentsdir}/paper036.pdf[pdf]).
. On the Variety of Shapes in Digital Trees, by J. Gaither, H. Mahmoud, and M. D. Ward, Journal of Theoretical Probability, volume 30 (2017), 1225-1254 (link:{attachmentsdir}/paper035.pdf[pdf]).
. Variance of the Internal Profile in Suffix Trees, by J. Gaither and M. D. Ward, Proceedings of the 27th International Conference on Probabilistic, Combinatorial and Asymptotic Methods for the Analysis of Algorithms, 12 pages (2016) (link:{attachmentsdir}/paper034.pdf[pdf]).
. On the Asymptotic Probability of Forbidden Motifs on the Fringe of Recursive Trees, by M. Gopaladesikan, S. Wagner, and M. D. Ward, Experimental Mathematics, volume 25 (2016), 237-245 (link:{attachmentsdir}/paper033.pdf[pdf]).
. Data Science in the Statistics Curricula: Preparing Students to "Think with Data," by J. Hardin, R. Hoerl, N. J. Horton, D. Nolan, B. Baumer, O. Hall-Holt, P. Murrell, R. Peng, P. Roback, D. Temple Lang, and M. D. Ward, The American Statistician, volume 69 (2015), 343-353 (link:{attachmentsdir}/paper032.pdf[pdf]).
. Learning Communities and the Undergraduate Statistics Curriculum (A Response to "Mere Renovation Is Too Little Too Late" by George Cobb), by M. D. Ward, The American Statistician, volume 69 (2015), online supplement (link:{attachmentsdir}/paper031.pdf[pdf]).
. The Truncated Geometric Election Algorithm : Duration of the Election, by G. Louchard and M. D. Ward, Statistics and Probability Letters, volume 101 (2015), 40-48 (link:{attachmentsdir}/paper030.pdf[pdf]).
. Asymptotic Properties of Protected Nodes in Random Recursive Trees, by H. Mahmoud and M. D. Ward, Journal of Applied Probability, volume 52 (2015), 290-297 (link:{attachmentsdir}/paper029.pdf[pdf]).
. Resolution of T. Ward's Question and the Israel-Finch Conjecture. Precise Analysis of an Integer Sequence Arising in Dynamics, by J. Gaither, G. Louchard, S. Wagner, and M. D. Ward, Combinatorics, Probability, & Computing, volume 24 (2015), 195-215 (link:{attachmentsdir}/paper028.pdf[pdf]).
. On Kotzig's Nim, by X. L. Tan and M. D. Ward, INTEGERS: The Electronic Journal of Combinatorial Number Theory, volume 14 (2014), paper G6 (27 pages) (link:{attachmentsdir}/paper027.pdf[pdf]).
. On a Leader Election Algorithm: Truncated Geometric Case Study, by R. Kalpathy and M. D. Ward, Statistics and Probability Letters, volume 87 (2014), 40-47 (link:{attachmentsdir}/paper026.pdf[pdf]).
. Asymptotic Joint Normality of Counts of Uncorrelated Motifs in Recursive Trees by M. Gopaladesikan, H. M. Mahmoud, and M. D. Ward, Methodology and Computing in Applied Probability, volume 16 (2014), 863-884 (link:{attachmentsdir}/paper025.pdf[pdf]).
. Building Random Trees from Blocks, by M. Gopaladesikan, H. M. Mahmoud, and M. D. Ward, Probability in the Engineering and Informational Sciences, volume 28 (2014), 67-81 (link:{attachmentsdir}/paper024.pdf[pdf]).
. The Variance of the Number of 2-Protected Nodes in a Trie, by J. Gaither and M. D. Ward, The Tenth Workshop on Analytic Algorithmics and Combinatorics (2013), 43-51 (link:{attachmentsdir}/paper023.pdf[pdf]).
. Analytic Methods for Select Sets, by J. Gaither and M. D. Ward, Probability in the Engineering and Informational Sciences, volume 26 (2012), 561-568 (link:{attachmentsdir}/paper022.pdf[pdf]).
. Asymptotic Distribution of Two-Protected Nodes in Random Binary Search Trees, by H. M. Mahmoud and M. D. Ward, Applied Mathematics Letters, volume 25 (2012), 2218-2222 (link:{attachmentsdir}/paper021.pdf[pdf]).
. Partitions with Distinct Multiplicities of Parts: On An "Unsolved Problem" Posed By Herbert Wilf, by J. A. Fill, S. Janson, and M. D. Ward, Electronic Journal of Combinatorics, volume 19(2), article P18, 2012 (link:{attachmentsdir}/paper020.pdf[pdf]).
. On the Number of 2-Protected Nodes in Tries and Suffix Trees, by J. Gaither, Y. Homma, M. Sellke, and M. D. Ward, Discrete Mathematics and Theoretical Computer Science, volume AQ (2012), 381-398 (link:{attachmentsdir}/paper019.pdf[pdf]).
. Asymptotic Analysis of the Nörlund and Stirling Polynomials, by M. D. Ward, Applicable Analysis and Discrete Mathematics, volume 6 (2012), 95-105 (link:{attachmentsdir}/paper018.pdf[pdf]).
. Number of survivors in the presence of a demon, by G. Louchard, H. Prodinger, and M. D. Ward, Periodica Mathematica Hungarica, volume 64 (2012), 101-117 (link:{attachmentsdir}/paper017.pdf[pdf]).
. Towards the variance of the profile of suffix trees, by P. Nicodeme and M. D. Ward, Report of the Mini-Workshop on Random Trees, Information and Algorithms, from Mathematisches Forschungsinstitut Oberwolfach, Report 23/2011, pages 1269-1272 (link:{attachmentsdir}/paper016.pdf[pdf]).
. Asymptotic properties of a leader election algorithm, by R. Kalpathy, H. M. Mahmoud, and M. D. Ward, Journal of Applied Probability, volume 48 (2011), 569-575 (link:{attachmentsdir}/paper015.pdf[pdf]).
. Asymptotic rational approximation to Pi: Solution of an "Unsolved Problem" posed by Herbert Wilf, by M. D. Ward, Discrete Mathematics and Theoretical Computer Science, volume AM (2010), 591-602 (link:{attachmentsdir}/paper014.pdf[pdf]).
. Inverse auctions: Injecting unique minima into random sets, by F. T. Bruss, G. Louchard, and M. D. Ward, ACM Transactions on Algorithms, volume 6, Article 21, December 2009, 19 pages (link:{attachmentsdir}/paper013.pdf[pdf]). (See the link:{attachmentsdir}/paper013full.pdf[previous version] for full details before we did significant editing/trimming for publication.)
. On the shape of the fringe of various types of random trees, by M. Drmota, B. Gittenberger, A. Panholzer, H. Prodinger, and M. D. Ward, Mathematical Methods in the Applied Sciences, volume 32 (2009), 1207-1245 (link:{attachmentsdir}/paper012.pdf[pdf]).
. Exploring data compression via binary trees, by M. D. Ward, Resources for Teaching Discrete Mathematics, MAA Notes volume 74 (Mathematical Association of America, 2009), 143-150 (link:{attachmentsdir}/paper011.pdf[pdf]).
. Average-case analysis of cousins in m-ary tries, by H. M. Mahmoud and M. D. Ward, Journal of Applied Probability, volume 45 (2008), 888-900 (link:{attachmentsdir}/paper010.pdf[pdf]).
. On correlation polynomials and subword complexity, by I. Gheorghiciuc and M. D. Ward, Discrete Mathematics and Theoretical Computer Science, volume AH (2007), 1-18 (link:{attachmentsdir}/paper009.pdf[pdf]).
. Error resilient LZ'77 data compression: algorithms, analysis, and experiments, by S. Lonardi, W. Szpankowski, and M. D. Ward, IEEE Transactions on Information Theory, volume 53, May 2007, 1799-1813 (link:{attachmentsdir}/paper008.pdf[pdf]).
. The average profile of suffix trees, by M. D. Ward, The Fourth Workshop on Analytic Algorithmics and Combinatorics (2007), 183-193 (link:{attachmentsdir}/paper007.pdf[pdf]).
. Exploring the average values of Boolean functions via asymptotics and experimentation, by R. Pemantle and M. D. Ward, The Third Workshop on Analytic Algorithmics and Combinatorics (2006), 253-262 (link:{attachmentsdir}/paper006.pdf[pdf]).
. Analysis of the multiplicity matching parameter in suffix trees, by M. D. Ward and W. Szpankowski, Discrete Mathematics and Theoretical Computer Science, volume AD (2005), 307-322 (link:{attachmentsdir}/paper005.pdf[pdf]).
. Analysis of the average depth in a suffix tree under a Markov model, by J. Fayolle and M. D. Ward, Discrete Mathematics and Theoretical Computer Science, volume AD (2005), 95-104 (link:{attachmentsdir}/paper004.pdf[pdf]).
. The number of distinct values of some multiplicity in sequences of geometrically distributed random variables, by G. Louchard, H. Prodinger, and M. D. Ward, Discrete Mathematics and Theoretical Computer Science, volume AD (2005), 231-256 (link:{attachmentsdir}/paper003.pdf[pdf]).
. Error resilient LZ'77 scheme and its analysis, by S. Lonardi, W. Szpankowski, and M. D. Ward, Proceedings of the 2004 IEEE International Symposium on Information Theory (2004), 56 (link:{attachmentsdir}/paper002.pdf[pdf]).
. Analysis of a randomized selection algorithm motivated by the LZ'77 scheme, by M. D. Ward and W. Szpankowski, The First Workshop on Analytic Algorithmics and Combinatorics (2004), 153-160 (link:{attachmentsdir}/paper001.pdf[pdf]).

== Professional Membership

American Mathematical Society (AMS) (Lifetime Membership) +
 +
American Statistical Association (ASA), ASA Fellow (also member of the Central Indiana Chapter) +
 +
Association for Women in Mathematics +
 +
Bernoulli Society (Lifetime Membership) +
 +
Institute of Mathematical Statistics (IMS) (Lifetime Membership) +
 +
International Statistical Institute (ISI) (Elected Member; Lifetime Membership) +
 +
Mathematical Association of America (MAA) (Lifetime Membership) +
 +
National Association of Mathematicians (NAM) (Lifetime Membership) +
 +
National Association of the Deaf (NAD) +
 +
National Black Deaf Advocates (also member of the Indiana Chapter) +
 +
Society for Advancement of Chicanos and Native Americans in Science (SACNAS) (Lifetime Membership) +



