= Spring 2026 Office Hours Schedule

[IMPORTANT]
====
Office hours before 5 PM on weekdays (Monday through Friday) will be offered both in-person in the lobby of Hillenbrand Hall, and also virtually.

Office hours on Sundays (all day) and also on weekdays after 5 PM will be held exclusively virtually.

Office Hours Zoom Link: https://purdue-edu.zoom.us/j/97199764245?pwd=bTMbApvj5ajczPimat5TbakdVEDaeK.1

Checklist for the Zoom Link:

* When joining office hours, please include your Data Mine level in front of your name. For example, if you are in TDM 102, your name should be entered as "102 - [Your First Name] [Your Last Name]".

* After joining the Zoom call, please stay in the main room until a TA invites you to a specific breakout room.

* We will continue to follow the office hours schedule as posted on the Examples Book. Link is coming soon!
====

[NOTE]
====
The below calendars represent regularly occurring office hours. Please check your class' Piazza page to view the latest information about any upcoming changes or cancellations for office hours prior to attending.

Our Piazza links are:
 
TDM 10200: https://piazza.com/purdue/fall2025/tdm1010010200202526/home

TDM 20200: https://piazza.com/purdue/fall2025/tdm2010020200202526/home 

TDM 30200: https://piazza.com/purdue/fall2025/tdm3010030200202526/home

TDM 40200: https://piazza.com/purdue/fall2025/tdm4010040200202526/home 

====

== TDM 10200 Office Hours:

[cols="1,1,1,1,1,1,1", options="header"]
[.small]
|===
| Time | Sunday | Monday | Tuesday | Wednesday | Thursday | Friday


|===


== TDM 20200 Office Hours:

[cols="1,1,1,1,1,1,1", options="header"]
[.small]
|===
| Time | Sunday | Monday | Tuesday | Wednesday | Thursday | Friday


|===


== TDM 30200 and 40200 Office Hours:

[cols="1,1,1,1,1,1,1", options="header"]
[.small]
|===
| Time | Sunday | Monday | Tuesday | Wednesday | Thursday | Friday


|===


== Indianapolis Office Hours (all levels):

All sessions of seminar and office hours will occur in ET 219 (The Data Mine suite). 

TA: Bozidar Perovic (bperovic@purdue.edu)

[cols="1,1,1,1,1,1,1", options="header"]
[.small]
|===
| Time | Sunday | Monday | Tuesday | Wednesday | Thursday | Friday



|===

