== Purdue Policies & Resources

=== Class Behavior

You are expected to behave in a way that promotes a welcoming, inclusive, productive learning environment.  You need to be prepared for your individual and group work each week, and you need to include everybody in your group in any discussions.  Respond promptly to all communications and show up for any appointments that are scheduled.  If your group is having trouble working well together, try hard to talk through the difficulties--this is an important skill to have for future professional experiences.  If you are still having difficulties, ask The Data Mine staff to meet with your group.


*Purdue's Copyrighted Materials Policy:*

Among the materials that may be protected by copyright law are the lectures, notes, and other material presented in class or as part of the course. Always assume the materials presented by an instructor are protected by copyright unless the instructor has stated otherwise. Students enrolled in, and authorized visitors to, Purdue University courses are permitted to take notes, which they may use for individual/group study or for other non-commercial purposes reasonably arising from enrollment in the course or the University generally.
Notes taken in class are, however, generally considered to be "derivative works" of the instructor's presentations and materials, and they are thus subject to the instructor's copyright in such presentations and materials. No individual is permitted to sell or otherwise barter notes, either to other students or to any commercial concern, for a course without the express written permission of the course instructor. To obtain permission to sell or barter notes, the individual wishing to sell or barter the notes must be registered in the course or must be an approved visitor to the class. Course instructors may choose to grant or not grant such permission at their own discretion, and may require a review of the notes prior to their being sold or bartered. If they do grant such permission, they may revoke it at any time, if they so choose.

=== Nondiscrimination Statement
Purdue University and The Data Mine are committed to maintaining a community that recognizes and values the inherent worth and dignity of every person; fosters tolerance, sensitivity, understanding, and mutual respect among its members; and encourages each individual to strive to reach his or her potential. For details, see Purdue’s  link:https://www.purdue.edu/purdue/ea_eou_statement.php[nondiscrimination policy.]

=== Students with Disabilities
Purdue University strives to make learning experiences as accessible as possible. If you anticipate or experience physical or academic barriers based on disability, you are welcome to let me know so that we can discuss options. You are also encouraged to contact the Disability Resource Center at: link:mailto:drc@purdue.edu[drc@purdue.edu] or by phone: 765-494-1247.

If you have been certified by the Office of the Dean of Students as someone needing a course adaptation or accommodation because of a disability OR if you need special arrangements in case the building must be evacuated, please contact The Data Mine staff during the first week of classes.  We are happy to help you.

=== Mental Health Resources

* *If you find yourself beginning to feel some stress, anxiety and/or feeling slightly overwhelmed,* try link:https://purdue.welltrack.com/[WellTrack]. Sign in and find information and tools at your fingertips, available to you at any time.
* *If you need support and information about options and resources*, please contact or see the link:https://www.purdue.edu/odos/[Office of the Dean of Students]. Call 765-494-1747. Hours of operation are M-F, 8 am- 5 pm.
* *If you find yourself struggling to find a healthy balance between academics, social life, stress*, etc. sign up for free one-on-one virtual or in-person sessions with a link:https://www.purdue.edu/recwell/fitness-wellness/wellness/one-on-one-coaching/wellness-coaching.php[Purdue Wellness Coach at RecWell]. Student coaches can help you navigate through barriers and challenges toward your goals throughout the semester. Sign up is completely free and can be done on BoilerConnect. If you have any questions, please contact Purdue Wellness at evans240@purdue.edu.
* *If you're struggling and need mental health services:* Purdue University is committed to advancing the mental health and well-being of its students. If you or someone you know is feeling overwhelmed, depressed, and/or in need of mental health support, services are available. For help, such individuals should contact link:https://www.purdue.edu/caps/[Counseling and Psychological Services (CAPS)] at 765-494-6995 during and after hours, on weekends and holidays, or by going to the CAPS office of the second floor of the Purdue University Student Health Center (PUSH) during business hours.

=== Violent Behavior Policy

Purdue University is committed to providing a safe and secure campus environment for members of the university community. Purdue strives to create an educational environment for students and a work environment for employees that promote educational and career goals. Violent Behavior impedes such goals. Therefore, Violent Behavior is prohibited in or on any University Facility or while participating in any university activity. See the link:https://www.purdue.edu/policies/facilities-safety/iva3.html[University's full violent behavior policy] for more detail.

=== Basic Needs Security Resources

Any student who faces challenges securing their food or housing and believes this may affect their performance in the course is urged to contact the Dean of Students for support. There is no appointment needed and Student Support Services is available to serve students from 8:00 - 5:00, Monday through Friday. The link:https://www.purdue.edu/vpsl/leadership/About/ACE_Campus_Pantry.html[ACE Campus Food Pantry] is open to the entire Purdue community).

Considering the significant disruptions caused by the current global crisis as it related to COVID-19, students may submit requests for emergency assistance from the link:https://www.purdue.edu/odos/resources/critical-need-fund.html[Critical Needs Fund].

=== Course Evaluation

During the last two weeks of the semester, you will be provided with an opportunity to give anonymous feedback on this course and your instructor. Purdue uses an online course evaluation system. You will receive an official email from evaluation administrators with a link to the online evaluation site. You will have up to 10 days to complete this evaluation. Your participation is an integral part of this course, and your feedback is vital to improving education at Purdue University. I strongly urge you to participate in the evaluation system.

You may email feedback to us anytime at link:mailto:datamine-help@purdue.edu[datamine-help@purdue.edu]. We take feedback from our students seriously, as we want to create the best learning experience for you!

=== General Classroom Guidance Regarding Protect Purdue

Any student who has substantial reason to believe that another person is threatening the safety of others by not complying with Protect Purdue protocols is encouraged to report the behavior to and discuss the next steps with their instructor. Students also have the option of reporting the behavior to the link:https://purdue.edu/odos/osrr/[Office of the Student Rights and Responsibilities]. See also link:https://catalog.purdue.edu/content.php?catoid=7&navoid=2852#purdue-university-bill-of-student-rights[Purdue University Bill of Student Rights] and the Violent Behavior Policy under University Resources in Brightspace.

=== Campus Emergencies

In the event of a major campus emergency, course requirements, deadlines and grading percentages are subject to changes that may be necessitated by a revised semester calendar or other circumstances. Here are ways to get information about changes in this course:

* Brightspace or by e-mail from Data Mine staff.
* General information about a campus emergency can be found on the Purdue website: xref:www.purdue.edu[].


=== Illness and other student emergencies

Students with *extended* illnesses should contact their instructor as soon as possible so that arrangements can be made for keeping up with the course. Extended absences/illnesses/emergencies should also go through the Office of the Dean of Students.

*Official Purdue University links to Resources and Guidelines:*

=== University Policies and Statements

- link:https://www.purdue.edu/odos/osrr/academic-integrity/index.html[Academic Integrity]
- link:https://www.purdue.edu/purdue/ea_eou_statement.php[Nondiscrimination Policy Statement]
- link:https://www.purdue.edu/advocacy/students/absences.html[Class Absences]
- link:https://catalog.purdue.edu/content.php?catoid=15&navoid=18634#classes[Attendance]
- link:https://www.purdue.edu/policies/ethics/iiia1.html[Amourous Relationships]
- link:https://www.purdue.edu/ehps/emergency-preparedness/[Emergency Preparedness]
- link:https://www.purdue.edu/policies/facilities-safety/iva3.html[Violent Behavior]
- link:https://www.purdue.edu/policies/academic-research-affairs/ia3.html[Use of Copyrighted Materials]

=== Student Support and Resources

- link:https://www.purdue.edu/asc/resources/get-engaged.html[Engage In Your Learning]
- link:https://www.purdue.edu/policies/information-technology/s5.html[Purdue's Web Accessibility Policy]
- link:https://www.d2l.com/accessibility/standards/[Accessibility Standard in Brightspace]

=== Disclaimer
This syllabus is subject to change. Changes will be made by an announcement in Brightspace and the corresponding course content will be updated.
