= Chatbots

Chatbots are applications that communicate in human languages. These applications vary from simple hardcoded textual responses to voice activated, neural network systems that dynamically respond to a situation and learn from the speakers (think Alexa). 

== Common Applications

Chatbots are very common nowadays. From customer support systems, to front end recommender systems, websites and more, chatbots are also one technology that has found a use case in nearly every industry. Some of the most common industries that use chatbots include:
- Retail
- Banking
- Customer Service
- Travel

== A Brief History

The Turing Test, presented in 1950, claimed that a machine would have intelligent behavior if, when asked a series of questions, it could respond like a human would. This amounts to a chatbot. In the 1960's, a chatbot called ELIZA seemed to meet this standard; although no one doubted that it was not conscious. Since then, we all can imagine the various chatbots that have found their way into our daily lives, from automated customer service systems, to simple self service phone agents, to Alexa, or even games. 

== Resources

All resources are chosen by Data Mine staff to be of decent quality, and most if not all content is free. 

=== Videos

https://www.youtube.com/watch?v=dvOnYLDg8_Y&list=PLQVvvaa0QuDdc2k5dwtDTyT9aCja0on8j[Creating a Chatbot with Deep Learning, Python and Tensorflow]

https://www.youtube.com/watch?v=o9-ObGgfpEk[What is a Chatbot? (IBM, ~10 minutes)]

https://www.youtube.com/watch?v=1lwddP0KUEg[Intelligent AI Chatbot in Python (~35 minutes)]

https://www.youtube.com/watch?v=c_gXrw1RoKo[Build your own chatbot using Python | Python Tutorial for Beginners in 2022 (Great Learning, ~1 hour)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99170476157001081[Building Intelligent Chatbots Using AWS (2019)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99170475084401081[Building Chatbots Using Google Dialogflow (2019)]

=== Books

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99169492106401081[Building chatbots with Python using natural language processing and machine learning (2019)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_proquest_journals_1818658254[The return of the chatbots (2016)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_askewsholts_vlebooks_9783030042998[Developing Enterprise Chatbots: Learning Linguistic Structures (2019)]

=== Articles

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_doaj_primary_oai_doaj_org_article_a4a77aac8cc844c98f259227899d7659[Building a Chatbot System to Analyze Opinions of English Comments (2023)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_arxiv_primary_2001_00100[Building chatbots from large scale domain-specific knowledge bases: challenges and opportunities (2019)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_arxiv_primary_1710_00689[Building Chatbots from Forum Data: Model Selection Using Question Answering Metrics (2017)]
