= NLTK (Natural Language Toolkit)

[quote, NLTK website]
"NLTK is a leading platform for building Python programs to work with human language data. It provides easy-to-use interfaces to over 50 corpora and lexical resources such as WordNet, along with a suite of text processing libraries for classification, tokenization, stemming, tagging, parsing, and semantic reasoning, wrappers for industrial-strength NLP libraries, and an active discussion forum."

NLTK is a free library that helps a wide variety of tasks in NLP, from tokenizing, to integrating large corpora, to displaying parsing trees and much more.

== Code Examples

The https://www.nltk.org/howto.html[NLTK website] has numerous detailed demonstrations of all its functions. 

== Resources

All resources are chosen by Data Mine staff to be of decent quality, and most if not all content is free. 

=== Videos

https://www.youtube.com/watch?v=WYge0KZBhe0[Introduction to NLTK]

=== Books

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99170205424701081[Natural Language Processing With Python (2009)]

=== Articles

https://www.nltk.org/howto/tokenize.html[The NLTK Website]

=== Free Courses    

https://www.youtube.com/watch?v=LQQbW3Pve5U&list=PLS1QulWo1RIZDws-_0Bfw5FZFmQJWtMl1[Python NLTK Tutorial]

https://www.youtube.com/watch?v=FLZvOKSCkxY&list=PLQVvvaa0QuDf2JswnfiGkliBInZnIC4HL[NLP with Python and NLTK]

https://www.youtube.com/watch?v=IqPWZL5f-7g&list=PLcTXcpndN-Sl9eYrKM6jtcOTgC52EJnqH[NLTK Text Processing]