= Protein Sequence Embedding

In the https://the-examples-book.com/starter-guides/data-science/data-analysis/nlp/word-embeddings[Word Embeddings Starter Guide page] you learned how embeddings can be used to capture the relationships between words. But how do we use embeddings to capture the relationship between... proteins? One way to think of this is that biology speaks in a language too, such as with genetic changes over long periods of time. Protein sequence embedding is a way to infer the biological properties of protein sequences using machine learning, and at the same time predict potential new protein sequences while optimising for specific biological properties.

== Common Applications

It is incredibly useful for healthcare and/or pharmeceutical drug discovery in particular, or any industry that encounters biological data. This is a field that intersects with biology (bioinformatics and/or biochemistry), data science, and healthcare.

== Resources

All resources are chosen by Data Mine staff to be of decent quality, and most if not all content is free. 

=== Videos

https://www.youtube.com/watch?v=RoboNOx-5oM[Protein Sequence Classification using BERT, Transformers, and Natural Language Processing (AWS, ~30 minutes)]

https://www.youtube.com/watch?v=JgczCetF1W0[Machine Learning For Proteins (Harvard, ~45 minutes)]

https://www.youtube.com/watch?v=p1qcA9ZoYDQ[An Introduction to Protein Sequencing (BioXLD, ~12 minutes)]

=== Books

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_askewsholts_vlebooks_9781119792659[Bioinformatics and Medical Applications: Big Data Using Deep Learning Algorithms (2022)]

=== Articles

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_doaj_primary_oai_doaj_org_article_6e2769a28be74d83a8cfe48876d9c323[Survey of Protein Sequence Embedding Models (Intl Journal of Molecular Sciences, 2023, Vol 24)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_proquest_miscellaneous_2766065658[Tree visualizations of protein sequence embedding space enable improved functional clustering of diverse protein superfamilies (Briefings in Bioinformatics, 2023, Vol.24 (1))]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_proquest_miscellaneous_2485517309[Sequence representation approaches for sequence-based protein prediction tasks that use deep learning (Briefings in functional genomics, 2021, Vol.20 (1), p.61-73)]