= Sentiment Analysis Using NLP

Sentiment analysis is the technique of using analyzing language to understand affective states or subjective responses; that is, to study what people feel about a given subject. This could include audio or text, but typically this is used for text. Your sentiment and emotional reactions are constantly being studied every time you like, subscribe, downvote, respond with an emoji, etc. 

== Common Applications

Industries that use sentiment analysis commonly include:
- Customer Service
- Marketing/Digital Marketing
- Tech Companies
- Advertising 

== Resources

All resources are chosen by Data Mine staff to be of decent quality, and most if not all content is free. 

=== Videos

https://www.youtube.com/watch?v=QpzMWQvxXWk[Python Sentiment Analysis Project with NLTK and 🤗 Transformers. Classify Amazon Reviews!!]

https://www.youtube.com/watch?v=Ao4-ZIPOGJI[Sentiment Analysis in 10 Minutes]

https://www.youtube.com/watch?v=uPKnSq6TaAk[Twitter Sentiment Analysis by Python]

https://www.youtube.com/watch?v=G6TbcyFxrms[Sentiment Analysis of Amazon Reviews]

=== Books

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_igpublishing_primary_PACKT0000479[Python social media analytics: analyze and visualize data from twitter, youtube, github, and more]]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99169705157801081[Learn about dictionary-based sentiment analysis in Python with data from the Economic News Article Tone dataset (2016)]

=== Articles

https://aws.amazon.com/what-is/sentiment-analysis/[What is Sentiment Analysis? (AWS)]

https://towardsdatascience.com/sentiment-analysis-concept-analysis-and-applications-6c94d6f58c17[Sentiment Analysis: Concept, Analysis and Applications (Towards Data Science)]

https://huggingface.co/blog/sentiment-analysis-python[Getting Started With Sentiment Analysis in Python (Hugging Face)]
