# Unix {#unix}

## Getting started {#unix-getting-started}

## Standard utilities {#unix-utilities}

### `man` {#man}

#### `tldr` {#tldr}

### ~ & . & .. {#dots}

### `cat` {#cat}

`cat` stands for concatenate and print files. It is an extremely useful tool that prints the entire contents of a file by default. This is especially useful when we want to quickly check to see what is inside of a file. It can be used as a tool to output the contents of a file and immediately pipe the contents to another tool for some sort of analysis if the other tool doesn't natively support reading the contents from the file.

A similar, but alternative UNIX command that incrementally shows the contents of the file is called `less`. `less` starts at the top of the file and scrolls through the rest of the file as the user pages down.

### `head` {#head}

`head` is a simple utility that displays the first _n_ lines of a file, or input.

#### How do I show the first 5 lines of a file called `input.txt`?
<details>
    <summary>Click here for solution</summary>
```{bash, eval=F}
head -n5 input.txt
```

Alternatively:
```{bash, eval=F}
cat input.txt | head -n5
```

</details>

### `ls` {#ls}

### `cp` {#cp}

### `mv` {#mv}

### `pwd` {#pwd}

### `touch` {#touch}

### `uniq` {#uniq}

`uniq` reads the lines of a specified input file and compares each adjacent line and returns each unique line. Repeated lines in the input will not be detected if they are not adjacent. What this means is you must sort prior to using `uniq` if you want to ensure you have no duplicates.

### `wc` {#wc}

You can think of `wc` as standing for "word count". `wc` displays the number of lines, words, and bytes from the input file.

#### How do I count the number of lines of an input file called `input.txt`?
<details>
    <summary>Click here for solution</summary>
```{bash, eval=F}
wc -l input.txt
```
</details>

#### How do I count the number of characters of an input file called `input.txt`?
<details>
    <summary>Click here for solution</summary>
```{bash, eval=F}
wc -m input.txt
```
</details>

#### How do I count the number of words of an input file called `input.txt`?
<details>
    <summary>Click here for solution</summary>
```{bash, eval=F}
wc -w input.txt
```
</details>

### `ssh` {#ssh}

#### `mosh` {#mosh}

### `scp` {#scp}

### `cut` {#cut}

`cut` is a tool to cut out parts of a line based on position/character/delimiter/etc and directing the output to stdout. It is particularly useful to get a certain column of data.

#### How do I get the first column of a csv file called 'office.csv`?

<details>
    <summary>Click here for solution</summary>
```{bash, eval=F}
cut -d, -f1 office.csv
```
</details>

#### How do I get the first and third column of a csv file called 'office.csv`?

<details>
    <summary>Click here for solution</summary>
```{bash, eval=F}
cut -d, -f1,3 office.csv
```
</details>

#### How do I get the first and third column of a file with columns separated by the "|" character?

<details>
    <summary>Click here for solution</summary>
```{bash, eval=F}
cut -d '|' -f1,3 office.csv
```
</details>

### `awk` {#awk}

### `sed` {#sed}

### `grep` {#grep}

It is very simple to get started searching for patterns in files using `grep`.

#### How do I search for lines with the word "Exact" in the file located `/home/john/report.txt`?
<details>
    <summary>Click here for solution</summary>
```{bash, eval=F}
grep Exact /home/john/report.txt

# or

grep "Exact" "/home/john/report.txt"
```
</details>

#### How do I search for lines with the word "Exact" or "exact" in the file located `/home/john/report.txt`?
<details>
    <summary>Click here for solution</summary>
```{bash, eval=F}
# The -i option means that the text we are searching for is 
# not case-sensitive. So the following lines will match
# lines that contain "Exact" or "exact" or "ExAcT".
grep -i Exact /home/john/report.txt

# or

grep -i "Exact" "/home/john/report.txt"
```
</details>

#### How do I search for lines with a string containing multiple words, like "how do I"?
<details>
    <summary>Click here for solution</summary>
```{bash, eval=F}
# The -i option means that the text we are searching for is 
# not case-sensitive. So the following lines will match
# lines that contain "Exact" or "exact" or "ExAcT".

# By adding quotes, we are able to search for the entire
# string "how do i". Without the quotes this would only 
# search for "how".
grep -i "how do i" /home/john/report.txt
```
</details>

#### How do I search for lines with the word "Exact" or "exact" in the files in the folder and all sub-folders located `/home/john/`?

<details>
    <summary>Click here for solution</summary>
```{bash, eval=F}
# The -R option means to search recursively in the folder
# /home/john. A recursive search means that it will search 
# all folders and sub-folders starting with /home/john.
grep -Ri Exact /home/john
```
</details>

#### How do I search for the lines that don't contain the words "Exact" or "exact" in the folder and all sub-folders located `/home/john/`?

<details>
    <summary>Click here for solution</summary>
```{bash, eval=F}
# The -v option means to search for an inverted match.
# In this case it means search for all lines of text
# where the word "exact" is not found.
grep -Rvi Exact /home/john
```
</details>

#### How do I search for lines where one or more of the words "first" or "second" appears in the current folder and all sub-folders?

<details>
    <summary>Click here for solution</summary>
```{bash, eval=F}
# The "|" character in grep is the logical OR operator.
# If we do not escape the "|" character with a preceding
# "\" grep searches for the literal string "first|second"
# instead of "first" OR "second".
grep -Ri "first\|second" .
```
</details>

#### How do I search for lines that begin with the word "Exact" (case insensitive) in the folder and all sub-folders located in the current directory?
<details>
    <summary>Click here for solution</summary>
The "^" is called an anchor and indicates the start of a line.
    
```{bash, eval=F}
grep -Ri "^Exact" .
```
</details>

#### How do I search for lines that end with the word "Exact" (case insensitive) in the files in the current folder and all sub-folders?
<details>
    <summary>Click here for solution</summary>
The "$" is called an anchor and indicates the end of a line.

```{bash, eval=F}
grep -Ri "Exact$" .
```
</details>

#### How do I search for lines that contain only the word "Exact" (case insensitive) in the files in the current folder and all sub-folders?
<details>
    <summary>Click here for solution</summary>
```{bash, eval=F}
grep -Ri "^Exact$" .
```
</details>

#### How do I search for strings or sub-strings where the first character could be anything, but the next two characters are "at"? For example: "cat", "bat", "hat", "rat", "pat", "mat", etc.
<details>
    <summary>Click here for solution</summary>
The "." is a wildcard, meaning it matches any character (including spaces).

```{bash, eval=F}
grep -Ri ".at" .
```
</details>

#### How do I search for zero or one of, zero or more of, one or more of, exactly _n_ of a certain character using grep and regular expressions?
<details>
    <summary>Click here for solution</summary>
"*" stands for 0+ of the previous character.
"+" stands for 1+ of the previous character.
"?" stands for 0 or 1 of the previous character.
"{n}" stands for exactly n of the previous character.

```{bash, eval=F}
# Matches any lines with text like "cat", "bat", "hat", "rat", "pat", "mat", etc.
# Does NOT match "at", but does match " at". The "." indicates a single character.
grep -i ".at" .
```

```{bash, eval=F}
# Matches any lines with text like "cat", "bat", "hat", "rat", "pat", "mat", etc.
# Matches "at" as well as " at". The "." followed by the "?" means 
# 0 or 1 of any character.
grep -i ".?at" .
```

```{bash, eval=F}
# Matches any lines with any amount of text followed by "at".
grep -i ".*at" .
```

```{bash, eval=F}
# Only matches words that end in "at": "bat", "cat", "spat", "at". Does not match "spatula".
grep -i ".*at$" .
```

```{bash, eval=F}
# Matches lines that contain consecutive "e"'s.
grep -i ".*e{2}.*" .
```

```{bash, eval=F}
# Matches any line. 0+ of the previous character, which in this case is the wildcard "."
# that represents any character. So 0+ of any character.
grep -i ".*"
```

</details>


#### Resources {#grep-resources}

**[Regex Tester](https://regex101.com/)**

https://regex101.com/ is an excellent tool that helps you quickly test and better understand writing regular expressions. It allows you to test four different "flavors" or regular expressions: PCRE (PHP), ECMAScript (JavaScript), Python, and Golang. regex101 also provides a [library](https://regex101.com/library?orderBy=MOST_POINTS) of useful, pre-made regular expressions.

**[Lookahead and Lookbehinds](https://www.regular-expressions.info/lookaround.html)**

This is an excellent resource to better understand positive and negative lookahead and lookbehind operations using `grep`.

#### `ripgrep` {#rg}

### `find` {#find}

#### `fd` {#fd}

### `top` {#top}

### `less` & `more` {#less-and-more}

### `sort` {#sort}

### `git` {#git-ref-01}

See [here](#git).

## Piping & Redirection {#piping-and-redirection}

Redirection is the act of writing standard input (stdin) or standard output (stdout) or standard error (stderr) somewhere else. stdin, stdout, and stderr all have numeric representations of 0, 1, & 2 respectively. 

### Redirection 

#### Examples

For the following examples we use the example file `redirection.txt`. The contents of which are:

```{bash, eval=T}
cat redirection.txt
```

##### How do I redirect text from a command like `ls` to a file like `redirection.txt`, completely overwriting any text already within `redirection.txt`?
<details>
    <summary>Click here for solution</summary>
```{bash, eval=T}
# Save the stdout from the ls command to redirection.txt
ls > redirection.txt
```

```{bash, eval=T}
# The new contents of redirection.txt
head redirection.txt 
```
```{bash, eval=TRUE, include=FALSE}
# Reset redirection.txt
echo "This is a simple file with some text.
It has a couple of lines of text.
Here is some more." > redirection.txt
```

</details>

##### How do I redirect text from a command like `ls` to a file like `redirection.txt`, without overwriting any text, but rather appending the text to the end of the file?
<details>
    <summary>Click here for solution</summary>
```{bash, eval=T}
# Append the stdout from the ls command to the end of redirection.txt
ls >> redirection.txt
```

```{bash, eval=T}
head redirection.txt
```

```{bash, eval=TRUE, include=FALSE}
# Reset redirection.txt
echo "This is a simple file with some text.
It has a couple of lines of text.
Here is some more." > redirection.txt
```

</details>

##### How can I redirect text from a file to be used as stdin for another program or command?
<details>
    <summary>Click here for solution</summary>
```{bash, eval=T}
# Let's count the number of words in redirection.txt
wc -w < redirection.txt
```
</details>

##### How can I use multiple redirects in a single line?
<details>
    <summary>Click here for solution</summary>
```{bash, eval=T}
# Here we count the number of words in redirection.txt and then 
# save that value to value.txt.
wc -w < redirection.txt > value.txt
```

```{bash, eval=T}
head value.txt
```

</details>

### Piping 

Piping is the act of taking the output of one or more commands and making the output the input of another command. This is accomplished using the "|" character.

#### Examples

For the following examples we use the example file `piping.txt`. The contents of which are:

```{bash, eval=T}
cat piping.txt
```

##### How can I use the output from a `grep` command to another command?
<details>
    <summary>Click here for solution</summary>
```{bash, eval=T}
grep -i "p\{2\}" piping.txt | wc -w
```
</details>

##### How can I chain multiple commands together?
<details>
    <summary>Click here for solution</summary>
```{bash, eval=F}
# Get the third column of piping.txt and 
# get all lines that end in "s" and sort 
# the words in reverse order, and append
# to a file called food.txt.
cut -d, -f3 piping.txt | grep -i ".*s$" | sort -r > food.txt
```
</details>


### Resources {#piping-and-redirection-resources}

**[Intro to I/O Redirection](https://www.digitalocean.com/community/tutorials/an-introduction-to-linux-i-o-redirection)**

A quick introduction to stdin, stdout, stderr, redirection, and piping.

## Emacs {#emacs}

## Nano {#nano}

## Vim {#vim}

## Writing scripts {#writing-scripts}
