# R {#r}

## Getting started {#getting-started-with-r}

How to install R (windows/mac/linux)
How to install RStudio
How to connect to RStudio Server on Scholar
How to get help (?, help(), get function itself)

## Variables {#r-variables}

## Logical operators {#r-logical-operators}

## Lists & Vectors {#r-lists-and-vectors}

## Basic R functions {#r-basic-functions}

## Data.frames {#r-data-frames}

## Reading & Writing data {#r-reading-and-writing-data}

## Control flow {#r-control-flow}

## Apply functions {#r-apply-functions}

### `apply` {#r-apply}

### `sapply` {#r-sapply}

### `lapply` {#r-lapply}

### `tapply` {#r-tapply}

## Writing functions {#r-writing-functions}

## Plotting {#r-plotting}

### `ggplot` {#r-ggplot}

### `ggmap` {#r-ggmap}

## RMarkdown {#r-rmarkdown}

To install RMarkdown simply run the following:

```r
install.packages("rmarkdown")
```

Projects in [The Data Mine](https://datamine.purdue.edu) are all written in RMarkdown. You can download the RMarkdown file by clicking on the link at the top of each project page. Each file should end in the ".Rmd" which is the file extension commonly associated with RMarkdown files.

You can find an exemplary RMarkdown file here:

https://raw.githubusercontent.com/TheDataMine/the-examples-book/master/files/rmarkdown.Rmd

If you open this file in RStudio, and click on the "Knit" button in the upper left hand corner of IDE, you will get the resulting HTML file. Open this file in the web browser of your choice and compare and contrast the syntax in the `rmarkdown.Rmd` file and resulting output. Play around with the file, make modifications, and re-knit to gain a better understanding of the syntax. Note that similar input/output examples are shown in the [RMarkdown Cheatsheet](https://rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf).

### Resources {#r-markdown-resources}

**[RMarkdown Cheatsheet](https://rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf):**

An excellent quick reference for RMarkdown syntax.

**[RMarkdown Reference](https://rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf):**

A thorough reference manual showing markdown input and expected output. Gives descriptions of the various chunk options, as well as output options.

**[RStudio RMarkdown Lessons](https://rmarkdown.rstudio.com/lesson-1.html):**

A set of lessons detailing the ins and outs of RMarkdown.

**[Markdown Tutorial](https://www.markdowntutorial.com/):**

RMarkdown uses Markdown syntax for its text. This is a good, interactive tutorial to learn the basics of Markdown. This tutorial is available in multiple languages.

**[RMarkdown Gallery](https://rmarkdown.rstudio.com/gallery.html):**

This gallery highlights a variety of reproducible and interactive RMarkdown documents. An excellent resource to see the power of RMarkdown.

**[RMarkdown Chapter](https://r4ds.had.co.nz/r-markdown.html):**

This is a chapter from Hadley Wickham's excellent [_R for Data Science_](https://r4ds.had.co.nz/) book that details important parts of RMarkdown.

**[RMarkdown in RStudio](https://rmarkdown.rstudio.com/articles_intro.html):**

This is a nice article that introduces RMarkdown, and guides the user through creating their own interactive document using RMarkdown in RStudio.

**[Reproducible Research](https://andrewbtran.github.io/NICAR/2017/reproducibility-rmarkdown/rmarkdown.html#reproducible_research):**

This is another good resource that introduces RMarkdown. Plenty of helpful pictures and screenshots.

## Tidyverse {#r-tidyverse}

## data.table {#r-datatable}

## SQL in R {#r-sql}

## Scraping {#r-scraping}

## `shiny` {#r-shiny}

### Rendering images {#r-shiny-render-images}


