---
output:
  pdf_document: default
  html_document: default
---
# FAQs {#faqs}

## How do I connect to Scholar from off-campus?

There are a variety of ways to connect to Scholar from off-campus. You can [use the ThinLinc web client](#connecting-with-thinlinc-webclient), or [setup a VPN connection to Purdue's VPN, and connect using the ThinLinc client application](#connecting-with-thinlinc-client). If you just want to use Jupyter notebooks, you can [use JupyterHub](#jupyterhub). If you just want to use RStudio, you can [use RStudio Server](#rstudio-server).

## Is there an advantage to using the ThinLinc client rather than the ThinLinc web client?

Yes. Although it is marginally more difficult to connect with, the ThinLinc client allows the user to copy and paste directly from their native operating system. So for example, if you have an RStudio session opened on your MacBook, you can directly copy and paste code onto Scholar using the ThinLinc client. You are unable to do this via the ThinLinc web client.
  
## GitHub Classroom is not working -- can't authorize the account.

This is usually a browser issue. GitHub Classroom does not work well with Microsoft Edge or Internet Explorer. Try [Firefox](https://www.mozilla.org/en-US/firefox/new/) or Safari or [Chrome](https://www.google.com/chrome/).

## In Scholar, my font size looks weird or my cursor is offset.

In scholar, navigate to `Tools > Global Options > Appearance`, and select the "Monospace" font, and click the "Apply" button.

## How do I make the ThinLinc window bigger without going to the dreaded "full screen" mode?

See [here](https://home.cc.umanitoba.ca/~psgendb/local/public_html/remote/desktop/thinlinc/thinlinc.local.html).

## I'm unable to type into the terminal in RStudio.

Try opening a new terminal, try clearing the terminal buffer, or interrupting the current terminal. All these options come from a menu that will pop up when you hit the small down arrow next to the words "Terminal 1" (it might be another number depending on how many terminals are open) which is on the left side right above the terminal in RStudio.

## I'm unable to connect to RStudio Server.

Try closing it, clearing your cookies, and using the original link:  https://rstudio.scholar.racac.purdue.edu/, or for ease of scrolling, try https://desktop.scholar.rcac.purdue.edu, and open up RStudio from within the ThinLinc web client.

## RStudio initialization error. {#rstudio-init-error}

1. Navigate to https://desktop.scholar.rcac.purdue.edu/ and login using your Purdue Career Account credentials.
2. Open a terminal (*not* RStudio, but rather, a terminal).
3. Run the following commands, one at a time. Be sure to replace *yourusername* with your actual Purdue alias. These commands connect you to the various Scholar frontends and kill all of the processes running under your username.

```bash
ssh scholar-fe00;
killall -9 -u yourusername;

ssh scholar-fe01;
killall -9 -u yourusername;

ssh scholar-fe02;
killall -9 -u yourusername;

ssh scholar-fe03;
killall -9 -u yourusername;

ssh scholar-fe04;
killall -9 -u yourusername;

ssh scholar-fe05;
killall -9 -u yourusername;

ssh scholar-fe06;
killall -9 -u yourusername;
```

During one of these 7 processes (from 00 to 06) you will get logged out of Scholar. When this happens, repeat steps **(1)** and **(2)** and continue to execute remaining commands. Once you have killed your processes on all 7 machines, there should no longer be any lingering processes that prevent you from logging in.

## RStudio crashes when loading a package.

Follow the directions under [rstudio initialization error](#rstudio-init-error).

## RStudio license expired.

If you are getting this message on a Saturday night, this is due to the Scholar frontends rebooting. Orphan processes are cleaned up and memory reclaimed. This process can cause a disruption in the communication that RStudio needs to do. This disruption is interpreted as a licensing issue. Simply wait and try again the next day.

## RStudio is taking a long time to open. {#rstudio-long-time-to-open}

It is possible that you saved a large `.RData` file the last time that you closed RStudio. (It is OK to avoid saving the .RData file, for this reason.) If you did save your `.RData` file, and you want to remove it now, you can do the following:

1. Close RStudio. 
2. Open the File Manager (it is located in the dock, and looks like a filing cabinet). 
3. Select your home directory (Dr. Ward's is called "mdw", for instance).
4. You need to see the "hidden files", which you can do by pressing Control-H or by choosing View / Show Hidden Files in the menu at the top of the File Manager window.
5. Drag your `.RData` file to the Trash.
6. Click on the Trash and then choose File / Empty Trash from the File Manager window, and then click "Empty Trash" to confirm that you want to empty the Trash.

## How can you run a line of R code in RStudio without clicking the "Run" button?

1. Click anywhere on the line (you do not need to highlight the line, and you do not need to click at the start or end of the line; anywhere on the line is ok).
2. Type the "Control" and "Return" keys together to run that line.

## My R session freezes.

1. Log out of Scholar. 
2. Log back into Scholar using the [ThinLinc client](#connecting-with-thinlinc-client).

**Before entering your password in ThinLinc, be sure to click on the "End Existing Session" option in the ThinLinc window (to the left of where you type your password). This will resent your Scholar session.**

## White screen issue when loading RStudio.

1. [Log in to Scholar](#connecting-to-scholar).
2. Open a terminal (click the black box at the bottom of the screen). 
3. Run the following commands:

```bash
# Note: You can use -fe01, -fe02, ..., -fe06 instead of -fe00.
# Until you find one that works.
ssh -Y scholar-fe00
module load rstudio
rstudio
```

4. When Scholar is reset, load RStudio by opening a terminal and running the following commands:

```bash
ml gcc
ml rstudio
rstudio
```

## Scholar is slow. {#scholar-is-slow}

**Possibility one:**

Most of the files we use in this class would require dozens of seconds to load using `read.csv()` in R.

Here is another trick to save you some time in data import:

1. Read only the first, say, 10000 rows of data (see instructions below), and complete your code using the smaller dataset. The code works for the subset of data should also work for the complete data. **This output is not your final answer!**
2. Once you complete the code, read in the entire dataset, and run the code to RStudio. You may even close the ThinLinc after submitting the code as long as you do not close your RStudio window. Closing RStudio will stop your code from running. It is also highly recommended to save your code prior to running it.
3. Some time (e.g., a few hours) later, you can come back and check your output. Scholar is a computing facility that is always on, and thus you can leave it do the work.

How do you read the first 10000 rows then? For example, we usually use the following line of code to read all of the election data:

```r
myDF <- read.csv('/class/datamine/data/election/itcont2020.txt')
```
	  
Now, with an additional parameter `nrows`, you can decide how many rows to read:

```r
myDF_short <- read.csv('/class/datamine/data/election/itcont2020.txt', nrows = 10000)
```

**Possibility two:**

You could be close to using 100% of your quota on scholar. 

1. Log into Scholar using [the ThinLinc client](#connecting-with-thinlinc-client).
2. Open a terminal, and run the following command: `myquota`.  

**Important note:** It will ask for your Purdue password (but won’t show it to you as you type). If your quota is at or near 100%, you will need to delete some of your files on Scholar. A healthy server needs < 80% full.

## There are no menus in Scholar.

Although this is a less common problem, it can happen if you accidentally selected ''one empty panel'' when you first logged into Scholar. To fix this, do as follows:

1. Open a terminal by clicking on the `Home` icon -- it looks like a house --. This will open a window in the `File Manager`. Then, choose from the menu in `File Manager` window: `File > Open Terminal Here`.
2. Run **exactly** the following command in the terminal:
```bash
cp  /etc/xdg/xfce4/panel/default.xml ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
```
3. Log out of Scholar. As this can be hard without menus, run in the terminal:
```bash
killall -9 -u [PUT USERNAME HERE]
```
**Example:** Dr. Ward would type:
```bash
killall -9 -u mdw
```

Running the command above will kill your session. When youd log back in, the menu system will work properly.

## Firefox in Scholar won't open because multiple instances running.

**The easy fix:**

1. Open your `File Browser` in Scholar. 
2. Choose the Option `View > Show Hidden Files`.
3. Inside your home directory, throw away the directory `.mozilla`. 

Now your Firefox should load.

**More complicated fix *(if the easy fix doesn't work)*:**

1. Open a terminal, and run the following commands:

```bash
cd ~/.mozilla/firefox
rm profiles.ini
```
Alternatively, you can run `rm -rf ./mozilla.`

**Important note:** *Make sure that you don't leave a space after the period. The period needs to be directly next to the slash.*

2. Log out of Scholar.  
3. Log back into Scholar using [the ThinLinc client](#connecting-with-thinlinc-client). When logging in, after you type your password in ThinLinc, but before you press the "Connect" button, make sure that you check the box "End Existing Session".

## How to transfer files between your computer and Scholar.

**Solution 1: email**

Attach the files in an e-mail to yourself. To do so inside Scholar, use the browser to log on to your e-mail client (located in the dock and the icon looks like a blue-and-green picture of the globe).

**Solution 2: use `scp`**

*To send a file from your computer to Scholar:*

1. Open a terminal.
2. Go to the directory where you have the file you want to transfer using the command with updated directory location `/directory/with/file/to/send`

```bash
cd /directory/with/file/to/send
```

3. Run the following command with the corresponding `filename`, `username`, and `where/to/put/filename` directory

```bash
scp filename username@scholar.rcac.purdue.edu:/where/to/put/filename
```

**Example:** Dr. Ward wants to transfer the file titled `my_file.txt` to a folder in his main directory called `my_folder`, he would run:

```bash
scp my_file.txt mdw@scholar.rcac.purdue.edu:/my_folder/my_file.txt
```

*To send a file from Scholar to your computer:* 

1. Open a terminal.
2. Run the following command with the corresponding `file/to/send/filename`, `username`, and `where/to/put/filename` directory:

```bash
scp username@scholar.rcac.purdue.edu:/file/to/send/filename /where/to/put
```

**Example:** If Dr. Ward wants to transfer the file titled `my_file.txt` located in a folder named `my_folder_in_scholar` to a folder in his personal computer called `my_folder` in his main directory, he would run:

```bash
scp mdw@scholar.rcac.purdue.edu:/my_folder/my_file.txt /my_folder/my_file.txt 
```

## ThinLinc app says you can't create any more sessions.

You will need to close any other sessions that you are running and start a new one. To do so, click on a little box under the password, over on the left-hand side, which says "End existing session".

## How to install ThinLinc on my computer.

See [here](#connecting-with-thinlinc-client).

## Forgot my password or password not working with ThinLinc.

First, ensure you are typing it correctly by typing it somewhere you can see, and copying and pasting the password back into ThinLinc. Remember that Scholar wants your Career Account credentials, not the Boiler Key.

If you are using the app version of ThinLinc, try using the [web version](#connecting-with-thinlinc-webclient) or [Jupyter](#jupyterhub). 

If the steps above do not work, you need to change your Career Account password. To do so:

1. [Go to Secure Purdue](https://www.purdue.edu/securepurdue/).
2. Click on the option "Change your password".  
3. After logging in, search for the link "Change Password" that "Allows you to change your Purdue Career Account password".

## Jupyter Notebook download error with IE.

Please note that Internet Explorer is **not** a recommended browser. If still want to use Explorer, make sure you download the notebook as "All Files" (or something similar). That is, we need to allow the browser to save in its natural format, and not to convert the notebook when it downloads the file.

## Jupyter Notebook kernel dying.

- Make sure you are using the R 3.6 (Scholar) kernel.

- Make sure you are using https://notebook.scholar.rcac.purdue.edu and not https://notebook.brown.rcac.purdue.edu.  (Use Scholar instead of Brown.)

- Try clicking `Kernel > Shutdown`, and then reconnect the kernel.

- If one particular Jupyter Notebook template gives you this error, then create a new R 3.6 (Scholar) file.

- Try re-running the code from an earlier project that you had set up and working using Jupyter Notebooks.

- One student needed to re-run the setup command one time in the terminal:

`source /class/datamine/data/examples/setup.sh`

- You could be close to using 100% of your quota on scholar. 

1. Log into Scholar using [the ThinLinc client](#connecting-with-thinlinc-client).
2. Open a terminal, and run the following command: `myquota`.  

**Important note:** It will ask for your Purdue password (but won’t show it to you as you type). If your quota is at or near 100%, you will need to delete some of your files on Scholar. A healthy server needs < 80% full, aim for that.

## Python kernel not working, Jupyter Notebook won't save.

1. Navigate to https://notebook.scholar.rcac.purdue.edu/, and login.
2. Click on the "Running" tab and shutdown all running kernels.
3. Log into Scholar using [the ThinLinc client](#connecting-with-thinlinc-client).
4. Open a terminal, and run the following commands: 

```bash
pip uninstall tornado(
/class/datamine/data/examples/setup2.sh
```

5. Go back to https://notebook.scholar.rcac.purdue.edu/, click on "Control Panel" in the upper right hand corner.
6. Click the "Stop My Server" button, followed by the green "My Server" button.

## Installing `my_package` for Python

Do **not** install packages in Scholar using:

`pip install my_package` 

or 

`pip install my_package --user`


We've tried to provide you with a ready-made kernel with every package you would want or need. If you need a newer version of some package, or need a package not available in the kernel, please send us a message indicating what you need. Depending on the situation we may point you to [create your own kernel]().

## Displaying multiple images after a single Jupyter Notebook Python code cell.

Sometimes it may be convenient to have several images displayed after a single Jupyter cell. For example, if you want to have side-by-side images or graphs for comparison. The following code allows you to place figures side-by-side or in a grid.

Note you will need the included import statement at the very top of the notebook.

```python
import matplotlib.pyplot as plt

number_of_plots = 2
fig, axs = plt.subplots(number_of_plots)
fig.suptitle('Vertically stacked subplots', fontsize=12)
axs[0].plot(x, y)
axs[1].imshow(img)
plt.show()

number_of_plots = 3
fig, axs = plt.subplots(1,number_of_plots)
fig.suptitle('Horizontally stacked subplots', fontsize=12)
axs[0].plot(x, y)
axs[1].imshow(img)
axs[2].imshow(img2)
plt.show()

number_of_plots_vertical = 2
number_of_plots_horizontal = 2

# 2 x 2 = 4 total plots
fig, axs = plt.subplots(number_of_plots_vertical,number_of_plots_horizontal)
fig.suptitle('Grid of subplots', fontsize=12)
axs[0][0].plot(x, y) # top left
axs[0][1].imshow(img) # top right
axs[1][0].imshow(img2) # bottom left
axs[1][1].plot(a, b) # bottom right
plt.show()
```

## RMarkdown “Error: option error has NULL value” when knitting".

This error message occurs when using the RStudio available on Scholar via ThinLinc, and running a code chunk in RMarkdown by clicking the green "play" button (Run Current Chunk). Do *not* click on the green triangle "play" button. Instead, knit the entire document, using the "knit" button that looks like a ball of yarn with a knitting needle on it.  

## How do you create an RMarkdown file?

Any text file with the `.Rmd` file extension can be opened and knitted into a PDF (or other format). If you'd like to create an RMarkdown file in RStudio, you can do so.

1. Open an RStudio session.
2. Click on `File > New File > RMarkdown...`.
3. You may put R code into the R blocks (the grey sections of the document), and put any comments into the white sections in between.

[This](https://rmarkdown.rstudio.com/lesson-1.html) is an excellent guide to RMarkdown, and [this](https://rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf) is a cheatsheet to get you up and running quickly.

## Problems building an RMarkdown document on Scholar.

If you are having problems building an RMarkdown document on Scholar, try the following:

- Dump the previously loaded modules. 

1. Open up a terminal.
2. Run the following commands:

```bash
module purge
ml gcc
ml rstudio
rstudio
```

This will purge (remove) previously loaded modules.

- Remove your `R` directory:

1. Open up a terminal.
2. Run the following commands:

```bash
cd ~
rm -rf R
```

This will force the removal of your R directory. It will remove your old R libraries. They will reload the newest versions if you install them again, and as you use them. 

This is recommended, especially at the start of the academic year.

If your R is taking a long time to open, see [here](#rstudio-long-time-to-open).

## How can I use SQL in RMarkdown?

When you use SQL in RMarkdown you can highlight the code in code chunks just like R by writing "sql" instead of "r" in the brackets:

```asis
```{sql, eval=FALSE}
SELECT * FROM table;
```
```

You will notice that all the SQL code chunks provided in the template have the option `eval=F`. The option `eval=F` or `eval=FALSE` means the SQL statements would be shown in your knitted document, but without being executed. 

To actually _run_ SQL inside RMarkdown see [here]().

You can read about the different languages that can be displayed in RMarkdown here:
https://bookdown.org/yihui/rmarkdown/language-engines.html.

## Copy/paste from terminal inside RStudio to RMarkdown.

If you're using the terminal inside the Scholar RStudio at https://rstudio.scholar.rcac.purdue.edu, right clicking won't work. A trick that does work (and often works in other situations as well) is the keyboard shortcut ctrl-insert for copy and shift-insert for paste. 
Alternatively, use the Edit/Copy from the menu in the terminal.

## How do I render an image in a `shiny` app?

There are a variety of ways to render an image in an RShiny app. See [here](#r-shiny-render-images).

## The package `my_package` is not found.

The package might not be installed. Try running:

```r
install.packages("ggmap")
```

Note that if you have already run this on ThinLinc, there is no need to do it again. 

Another possibility is that the library is not loaded, try running:

```r
library(ggmap)
```

## Problems installing `ggmap`.

Two possible fixes:

1. Open a terminal and run:

```bash
rm -rf ~/R
```

After that, re-open RStudio and re-install `ggmap`:

```r
install.packages("ggmap")

# Don't forget to load the package as well
library(ggmap)
```

2. Open a terminal and run:

```bash
module load gcc/5.2.0
```

After that, restart all RStudio processes.


