= Final Presentation - Fall 2025

[IMPORTANT]
====
Final presentations must be kept **CONFIDENTIAL** to team/company! The presentations cannot be publicly shared.  
====

Your final presentation will be completed as a group during your last regularly scheduled 50-minute team meeting the week of December 8 - December 12, 2025.

A draft of your presentation is due on Wednesday, November 19, 2025.

This final presentation is worth 10% of your grade and will help you prepare for The Data Mine Corporate Partner Symposium in April 2026.

The presentation will be ~35 minutes long with 10-15 minutes for questions/discussion.

== *Guidelines* 

The Data Mine Corporate Partners Final Presentations will showcase the hard work of students this semester and their goals for spring 2026. It will help everybody get on the same page and make sure all team members have a thorough understanding of the work. Knowing how to *do* something and knowing how to *explain* something are two different skills, and it is important to be skilled at both.
 
**Research for fall should NOT stop at this draft. Continue working on your research and you may continue to update the slides up until the day of your presentation **

=== *When*
The final presentation will occur during your last 50-minute team meeting of the semester, during the week of Monday, December 8 - Friday, December 12, 2025.

=== *Expectations* 

* **Each student must contribute to the presentation in some capacity. **  
* Not every student needs to speak during the presentation, but if you don't speak during the presentation, consider answering a question during Q&A. 
* For example, here are some suggested roles students can fill (not required to be broken up this way):
    - Student 1: introduction
    - Student 2: summary
    - Student 3: formatting 
    - Student 4: script/notes for the presentation
    - Students 5-10: talk and give the presentation
    - Students 11-14: answer questions after the presentation 

=== *Design*

•	The presentation should look professional. You are encouraged to use a branded template from your Corporate Partner or a Purdue template. A Purdue template is available for xref:attachment$Purdue-branded-powerpoint-template-reduced.pptx[download here].

=== *Content* 
*Introduction/Background/Motivation (~10%)*

- Include a slide with team profile (picture with name and major of each student)
- Introduce the project and provide a brief background (there will be colleagues at the presentation that will likely not be familiar with your project)

*Fall 2025 work (~45%)* 

- Summarize your work this semester. Do not go too deep into the nitty gritty details (you should not have screenshots or pasted code in your presentation). 
- Feel free to include a demo (outside of a PowerPoint) if this is relevant to your team.

*Spring 2026 goals (~40%)* 

- Include your plan for spring 2026. Be strategic and discuss what you plan to accomplish by when and how you define a “success”. 

*Summary (~5%)* 

- Include a slide of references and acknowledgements. Thank your mentors and any faculty members.
- Summarize your presentation briefly and open the floor to discussion and questions

=== *Preparation* 

To create an outline for your presentation, we will be using ideas from Professional Development #5. 

Your team will use the Transformation Matrix to create an outline for your presentation. Individually, you will fill out this matrix in Gradescope for Professional Development Assignment #5. Then, as a team, you will fill this matrix in lab, to create your presentation outline.  

Additionally, your team will use concepts from Data Storytelling to explain your project. Similarly, you will complete this assignment individually in Professional Development Assignment #5 and then as a team in the following lab. It is important you integrate these concepts into your outline.    

*Other Tips*
Additional tips on written and verbal communication on the tips page xref:fall2022/final_presentation_tips.adoc[Final Presentation Tips]

- The percentages in parenthesis are approximations of how much you should spend talking about each section. It is important to be strategically planning for your spring 2026 goals which is why ~40% of the presentation should be prospective. 
- Make sure to make your slides interesting – include pictures/figures/screenshots. 
- Limit text when possible. 
- Be aware of your audience. Ask your Corporate Partner Mentor who will be coming to the presentation. Some may have technical experience whereas others have business domain experience.  
- The presentation does not have to hide company protected material because these presentations will only be given to internal colleagues to the companies. These presentations will *not* be shared publicly like the posters in the spring semester. 
- Plan out who will be speaking for each section, how much time each team member will have to speak, and how to transition between speakers smoothly. 
- Practice! Practice! Practice! This is your final presentation of the semester. Make sure to practice and prepare. 

=== *Length* 

- The team meeting is 50 minutes. 
- Your presentation should be 30-40 minutes with 10-15 minutes for questions and discussion. 
    - You should prepare a few questions to get the Q&A started if no guests have questions right away. Practice answering questions that you think may come up. Take turns answering them too. 
- Make sure to leave time for a demonstration *if* you are including one. This does not apply to all groups. 

== *Grading* 

The final presentation is worth 10% of your fall grade (per the syllabus). The final presentation and deliverable grades will be determined in collaboration with The Data Mine staff and Corporate Partner Mentors. 

[cols="4,2,1"]
|===

2+|*Final Presentation*
>|15%

|Drafts (practice presentation, draft deliverables)
^| 5%
|

|Final Deliverables & Presentation
^| 10%
|

|===

== *Draft* 

A draft of your presentation is due *Wednesday, November 5, 2025*. The reason your draft is due this early is to allow The Data Mine staff and Corporate Partners Mentors to review the material and provide feedback. 

Each TA will submit the draft link on behalf of the team. The presentation should be created and shared in PowerPoint online. 

Your draft should include all slides that you plan to include. 60%+ of slides should be complete, but some may be “placeholders” and have outlines or notes if you are still working on your fall research.

**Research for fall should *NOT* stop at this draft. Continue working on your research and you may continue to update the slides up until the day of your presentation **

== *Deliverables* 
 
- [Draft Version] PowerPoint Presentation 
- [Final Version] One PowerPoint presentation
    * If you have multiple sub-teams, you should still have 1 presentation overall. 
- [Optional, dependent on team] Interactive demonstrations (as appropriate) like R Shiny, Tableau, mobile app
- [All students] Participation at the presentation 


== *Due Dates*

- DRAFT presentation due by 11:59 PM ET on Wednesday, November 19, 2025 (your TA will submit this)
- FINAL version of presentation due by Friday, December 5, 2024 by 11:59 PM ET

xref:fall2025/schedule.adoc[View the fall 2025 course schedule here with all due dates.]

== *Rubric* 

[%header,format=csv]
|===
Category, Needs Improvement, Acceptable, Exceeds Expectation
Introduction/background/motivation, Team provides very limited detail on their goals or vision for the project., "Team provides some detail about why they are doing the work, but the overall vision is unclear.", Team provides an easy to understand and thorough overview of their project goals and overall vision. 

Fall 2025 Research (what and *how*), "Team provides little detail on the significant milestones and achievements. Overview is limited to high level explanations and significant detail is needed.", "Project milestones and successes are clear, but the detail is limited. Student contributions are covered but more depth may be needed.", "Team provides detailed information on the challenges, successes, and learnings from the first semester. Student contributions to the project are easy to understand."

Spring 2026 Research (what and *how*), "Team does not have a well-defined future vision or steps on how to complete the work.", "Team provides an outline of future work but may not have as much detail as to how they plan to accomplish the milestones.", "Team provides clear outline of future goals and how they relate to both the overall vision and the current semester’s work."

Summary, "The team’s overview was difficult to understand and didn’t show a path forward for the coming semester.", "Team provides an overview of the semester’s work and goals but may leave out a few details. Some of the review may be too technical for most audiences.", "Team provides an easy to understand and concise overview of the semester’s work and the student’s learnings. Topics are easy to understand with any level of technical expertise."

References and Acknowledgements,The team did not list any additional contributions or support for the project. (And it’s known that it was supported by other parties.),The team listed contributors on a “Thank You” slide. ,The team was sure to call out anyone who helped support the team or contribute to the project. 

Figures,Lots of extra visualizations that don’t seem to be related to the subject at all. Doesn’t reference or tie the figures to the narrative of the presentation. ,Visualizations are good but may not always be related directly to the topic. Some are a bit confusing to interpret. ,Visualizations are effective and help to drive the story and user understanding clearly. 

Layout and design,"The presentation is poorly designed and confusing. Topics are hard to follow, and the work doesn’t appear professional. ","The presentation is professionally done and easy to understand. Some slides may need improvement, but the majority are clean and concise. ","Presentation is clean, concise, and effective. It’s easy to read and understand quickly and in a virtual environment. "

Speakers,The students seem unsure of the deliverables and can’t provide additional detail when asked. ,The students know their topics well and can speak to the deliverables. May be a little light on technical detail when applicable. ,The students are well prepared both on the topic and for user questions. They also provide technical detail and background where appropriate. 
Q&A / Discussion,The team isn’t engaged in questions and doesn’t interact when asked. ,The team is engaged and ready to answer most questions. They may have to follow up on a few of the more technical items. ,The team is engaged and provides clear professional answers to any questions. 

Overall,"The team was unprepared, uninvolved, and disorganized. The presentation was hard to understand and didn’t have a vision for the next steps.",The presentation was clean and easy to understand but had some room for improvement. The team spoke well but had some variation in the strength of the content. ,"The presentation was thorough, professional, and easy to understand. The team did a good job with interactions, and everyone was prepared and involved. "


|===

== *Questions?* 

- Ask your TA 
- Email us anytime at datamine-help@purdue.edu  