= Welcome to The Data Mine Corporate Partners Fall 2025 semester!
:page-aliases: fall2025/introduction.adoc

All course content lives within The Corporate Partners appendix of The Example Book (the pages you are reading right now).

However, we still have a link:https://purdue.brightspace.com/[Brightspace] page for the purposes of grading. All Purdue courses are required to post grades in Brightspace. Students will also use link:https://www.gradescope.com/[Gradescope] as the submission portal for assignments.


To get started this semester:

1. Watch this link:https://youtu.be/xEDCqtK7I-c?si=bfPsa51bqAjpA6BM["first day of class" video].

2. Review the xref:fall2025/syllabus.adoc[fall 2025 syllabus].

3. Review the xref:fall2025/schedule.adoc[fall 2025 course schedule] for due dates and important dates.

4. Confirm your xref:fall2025/locations.adoc[meeting time and location]. _This should match the time listed on your official Purdue schedule._ The MS Teams meeting link for your SYNC ONLINE class will be sent a few days before August 25. If you do not have this meeting link, please email us at datamine-help@purdue.edu and specify what team you are on.

5. Click on xref:fall2025/sprint0.adoc[Sprint #0] to review the content for the first week.

We look forward to working with you this semester!

== Experiencing The Data Mine Video
Check out this video featuring students in The Data Mine!

++++
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/2hYY20OGjpg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++
