= Sprint #4

[IMPORTANT]
====
The fall 2025 content is currently being revised. Please check back soon for updates. 
====

== Sprint Dates
_Monday, 10/7 and Tuesday, 10/8: October Break – No Classes_

_Thursday, 10/10 and Friday 10/11: All labs and meetings as usual. No changes to classes on Wednesday, Thursday and Friday after fall break._


[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 10/3
|Mon 9/30

|*Sprint End Date*
|Wed 10/16
|Sun 10/13

|*Due Date*
2+| Wed 10/16 by 11:59 PM ET

|===


== Sprint Tasks

=== &#10003; Professional Development 

During this sprint, we will review the importance of Documentation, learn about multiple Time Management skills and hear about initiative and follow through.

IMPORTANT: Please note that the Sprint #4 Professional Development deadline has been extended until Wednesday, October 16, 2024 at 11:59 PM ET. It was previously due October 9, but we extended the deadline because of link:https://catalog.purdue.edu/preview_program.php?catoid=16&poid=27599[Fall Break] on Monday, October 7 and Tuesday, October 8.

++++
<html>
<head>
<meta name="viewport"  content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}

.accordion:after {
  content: '\002B';
  color: #777;
  font-weight: bold;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2212";
}

.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>

<button class="accordion">Documentation Guide</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, October 16, 2024 at 11:59 PM ET. Late work will not be accepted.
		</p>
<br>
	</div>
	<div>
		<p><b>What: </b>Read this article about <a href="https://www.atlassian.com/work-management/knowledge-sharing/documentation/importance-of-documentation">The Importance of Documentation</a> and write a reflection in "Sprint 4: Professional Development".</p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 4: Professional Development".</p>
<br>
  </div>
  <div>
		<p><b>Why: </b>Documentation is essential in both The Data Mine and the real world. While it might not be the most exciting part of your job, it is one of the most valuable. Therefore, it is important to get practice early on. </p>
<br>
  </div>
</div>

<button class="accordion">Time Management</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, October 16, 2024 at 11:59 PM ET. Late work will not be accepted. 
		</p>
<br>
	</div>
	<div>
		<p><b>What: </b>You have the option to read about or watch the videos about the following 3 Time Management Techniques. Then, answer the reflection question in Gradescope. 
<br> 
        1. Time Blocking: Watch this <a href = "https://www.youtube.com/watch?v=FLxt4Sbpud4&list=PLf5PUa_bu9_EMG2R3ZhecODo1mFLD3rZr&index=3" target="_blank" rel="noopener noreferrer">Video</a> or read this <a href = "https://todoist.com/productivity-methods/time-blocking">Article</a>. 
<br>
        2. The Pomodoro Method: Watch this <a href = "https://www.youtube.com/watch?v=z1BvrkPF2LE&list=PLf5PUa_bu9_EMG2R3ZhecODo1mFLD3rZr&index=5" target="_blank" rel="noopener noreferrer">Video</a> or read this <a href = "https://todoist.com/productivity-methods/pomodoro-technique">Article</a>.  
<br>
        3. Eat the Frog: Watch this <a href = "https://www.youtube.com/watch?v=ntSraUH4Rlo&list=PLf5PUa_bu9_EMG2R3ZhecODo1mFLD3rZr&index=6" target="_blank" rel="noopener noreferrer">Video</a> or read this <a href = "https://todoist.com/productivity-methods/eat-the-frog">Article</a>. </p> 
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 4: Professional Development".</a></p>
<br>
  </div>
  <div>
		<p><b>Why: </b> Learning about different time management techniques and effectively incorporating them into you everyday routine helps you optimize your productivity, reduce stress, and achieve a better work-life balance. By understanding various techniques, you can find the methods that work best for your personal and professional needs.
        </p>
<br>
  </div>
</div>
<button class="accordion">Initiative and Follow Through </button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, October 16, 2024 at 11:59 PM ET. Late work will not be accepted.</p>
<br>
	</div>
	<div>
		<p><b>What: </b>Watch the following video on <a href="https://www.youtube.com/watch?v=hn9so1zVfR0" target="_blank" rel="noopener noreferrer">Taking Action</a> and complete the reflection questions in Gradescope.</p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 4: Professional Development".</p>
<br>
  </div>
  <div>
		<p><b>Why: </b> Often times, people miss out on opportunities simply because they are afraid to take the first step. We hope this video shows you the impact of taking charge of what you want and inspires you to do so not only in Corporate Partners, but in your everyday lives. </p>
<br>
  </div>
</div>

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

</body>
</html>
++++

=== &#10003;Sprint #4 Report 

*When:* Due Wednesday, October 16, 2024 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in Sprint #4 Retro Report. 

*Where:* link:https://www.gradescope.com/[Gradescope] 
