= Sprint #0

[IMPORTANT]
====
The fall 2025 content is currently being revised. Please check back soon for updates. 
====

== Intro Video

In the Corporate Partners course, we don't have a first class with all 800+ students together in one space because teams start meeting immediately. Instead, we recorded a 10-minute video of the information we would share on the first class. 

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/xEDCqtK7I-c?si=XKlVlsKsBBXjRTxD" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
++++



== Sprint Dates
In the Agile methodology, a sprint is a block of time used for the development of a product, these are 2-weeks each in the case of The Data Mine. This first week "Sprint #0" we've provided a few onboarding assignments and a little bit of background information before you jump into your first sprint with your company.

> Monday August 25, 2025 - Friday August 29, 2025

== Sprint Tasks

NOTE: The first sprint has a lot of tasks to help aide with onboarding. In future sprints, plan to spend more time working on your project.

=== &#10003; Anvil Access

_*Do not submit this more than once. You only need to create *one* account that you will use for Seminar and Corporate Partners. If you already filled this out for Seminar (TDM 101, 201, 301, 401, 501), do not do it again.*_ 

*When:* By the first day of class

*What:* Create an ACCESS account so you can login to Anvil. Do not do this again if you already set it up for Seminar. 

*Where:* Find instructions to link:https://the-examples-book.com/setup[create an ACCESS account to utilize Anvil here.] Don't forget the last step of submitting your username to the Qualtrics survey (at the bottom of the instructions page). 

=== &#10003; Download MS Teams

The Data Mine uses MS Teams as one of our primary communication tools. You will need to download MS Teams to your computer. Your team SHOULD NOT use any other form of communication (e.g., Slack, Discord, etc.) unless approved by The Data Mine staff and your mentor. 

*When:* By the first day of class

*What:*  Review this page xref:fall2025/MS_Teams.adoc[about MS Teams in The Data Mine]. Download MS Teams Desktop App to your computer (and phone if you would like).

*Where:* Download via the link above. 

=== &#10003; Syllabus Quiz

While all teams will work on different projects, and mentors will provide a project charter, the syllabus includes information that every Data Mine Corporate Partner student needs to know. 

*Released:* The assignment will open with the start of school on Monday, August 25, 2025.

*When:* Due Wednesday, September 3, 2025 at 11:59 PM ET. Late work will not be accepted.

*What:* Review the xref:fall2025/syllabus.adoc[fall 2025 syllabus page] and xref:fall2025/schedule.adoc[fall 2025 course schedule]. Take the quiz up to 3 times before the due date and your highest score will be taken. You may have the syllabus open while you take the quiz. _Please note there is a separate syllabus quiz for the 1-credit seminar class (TDM 101, 201, 301, 401, 501)._

*Where:* Take the quiz on link:https://www.gradescope.com/[Gradescope] 


=== &#10003; Project Management Training 

The Data Mine Corporate Partners will implement Agile methods into our project management. Agile is very popular in industry and the majority of our Corporate Partners use it. Now is the best time to practice it while you are a student.

During your first or second lab session, you will be using Legos to learn the Agile approach to project management. Your TA will be facilitating this Lego lab. We encourage you to review this link:https://thisiszone.medium.com/using-lego-to-show-the-advantages-of-an-agile-approach-to-software-development-3eda6e5c2114[article]. 

*Released:* The assignment will open with the start of school on Monday, August 25, 2025.

*When:* Due Wednesday, September 3, 2025 at 11:59 PM ET. Late work will not be accepted.

*What:* Complete the link:https://the-examples-book.com/crp/projectmanagement/intro[Project Management Training], participate in the Lego lab activity, and take the quiz. 

*Where:* Take the quiz on link:https://www.gradescope.com/[Gradescope] titled "Sprint 0: Project Management Quiz"

=== &#10003; Professional Development 

The Data Mine Corporate Partners program is a professional development program. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

With the exception of sprint 0, each sprint you will complete a few professional development related tasks. These are completed in link:https://www.gradescope.com/[Gradescope] and may contain multiple topics each assignment.


=== &#10003; Sprint #0 Report

*Released:* The assignment will open with the start of school on Monday, August 25, 2025.

*When:* Due Wednesday, September 3, 2025 at 11:59 PM ET. Late work will not be accepted.

*What:* Answer the questions in the Sprint #1 Report. 

*Where:* Submit the report on link:https://purdue.ca1.qualtrics.com/jfe/form/SV_0SSqJoHqqq2sdjU[Qualtrics (click here)]. The first report is submitted in Qualtrics to collect data for required grant assessments. _You will receive an email confirmation of your responses upon submitting the form. If you do not get an email, we did not receive your response._

*Why:* The Data Mine uses these surveys for grants and other applications, please answer truthfully and write responses to the best of you ability.

=== &#10003; Meet The Team Presentation 

Create a PowerPoint slide containing your headshot, major, graduation year, and your hobbies/interests. This will be presented during your mentor meeting during the second week.

=== &#10003; Team Introduction Survey 

Your TA, in partnership with your Corporate Partner Mentors, will create a team introduction survey to get to know more about your interests, experiences, and goals for your time at The Data Mine. 

*When:* Per your TA's guidance. Each team is unique

*What:* Complete the survey provided to you by your TA. 

*Where:* Please ask your TA about the survey link. This background survey is specific to each team and created in partnership with your TA and Corporate Partner Mentor(s). This is not a graded assignment. 