= Sprint #6

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 11/2
|Mon 10/30

|*Sprint End Date*
|Wed 11/15
|Sun 11/12

|*Due Date*
2+| Wed 11/15 by 11:59 PM ET

|===

== To Do

&#10003; See the xref:fall2023/schedule.adoc[Fall Schedule] for timesheet and report deadlines.

&#10003; Complete Time Sheet

* Timesheet #11 due Sunday 11/5 at 11:59 PM EST.
* Timesheet #12 due Sunday 11/12 at 11:59 PM EST.

&#10003; Grade Sprint #5 & Team Report #5 on Gradescope by Wednesday 11/8 at 11:59PM EST.

&#10003; Attend Monthly Meeting #2, All TA are required to attend 1 session on Wed 11/1:

* 9:00 - 10:00 AM ET at DLR 134
* 2:30 - 3:30 PM ET at DLR 134
* 3:30 - 4:30 PM ET at DLR 134

== Sprint Schedule

=== Team Meeting #1 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.

* Ensure students are assigned tasks to work on before meeting again in the next lab.


=== Lab Section #1 (1 hour and 50 Minutes):

* There will not be a professional development discussion this week. Instead, use this extra time to work on your Final Presentation Draft and Project objectives. See below for more information on the Final Presentation.

=== Team Meeting #2 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles,roadblocks or barriers that they experienced while completing this weeks task?
** What do they plan on committing to completing by next mentor meeting?
* Time for questions from students to mentor.

* Ensure students are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #2 (1 hour and 50 Minutes):


* There will not be a professional development discussion this week. Instead, use this extra time to work on your Final Presentation Draft and Project objectives. See below for more information on the Final Presentation.

== Final Presentation

To recap the semester, your team will present on project progress and future goals. Please review the following Guidelines for the Final Presentation: xref:fall2023/final_presentation.adoc[Final Fall Presentation Details]. During this sprint, your team should complete a first draft of your presentation and continuing working on this presentation until the final week of term when you will present to your CRP mentors and the Data Mine staff.

*When:* First Draft due Wednesday, November 15, 2023 at 11:59 PM ET. Late work will not be accepted. Final Draft due Friday, December 1, 2023 at 11:59 PM ET. Late work will not be accepted. *TAs will submit on behalf of the whole team*

*What:* 

&#10003; The team started the Final Fall Presentation (2 weeks till due date).

&#10003; Assigned speaking parts for the Final Fall Presentation. This even includes back-up speakers! 

&#10003; xref:fall2023/final_presentation.adoc[Final Fall Presentation Details]

&#10003; Turned in the team *Final Presentation draft* materials by 11:59 PM ET on Wednesday, 11/15/2023. *TAs will submit on behalf of the whole team*

*Where:* link:https://www.gradescope.com/[Gradescope]