= Sprint #1

== Sprint Dates
All sprints will have the same due dates, but the sprint start and end dates are slightly shifted depending on when a team has their lab (2 hours) and lecture (50 minutes). This is so that sprints always start with a lec and follow the format lec-lab-lec-lab.

You can find a xref:fall2023/schedule.adoc#sprint-schedule[visual of the sprint schedule here]. More details will be covered in the agile training below. 

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|*Mon 8/21
|Mon 8/21

|*Sprint End Date*
|Wed 9/6
|Sun 9/3

|*Due Date*
2+| Wed 9/6 by 11:59 PM ET

|===

_*Please note that sprint 1 starts on August 21, the first day of fall 2023 semester, for both schedules. Once we are in a regular sprint schedule, you will see the lab then meeting schedule shift to starting on Thursdays._

== To Do

&#10003; Prepared an icebreaker for the first lab. xref:trainingModules/ta_training_module3_4_warmups.adoc[TA Created Warm-Ups].

&#10003; Planned my first lab! I remembered an introduction, agile explanation, and reminders about the syllabus/quizzes and NDAs (if your company has provided them already).

&#10003; Sent reminders to students about the syllabus/quizzes in BrightSpace and NDAs that need to be signed

&#10003; Sent reminders to students to complete NDAs

&#10003; See the xref:fall2023/schedule.adoc[Fall Schedule] for timesheet and report deadlines.

== The Data Mine Video
Check out the new Data Mine Video and share it with your friends!

++++
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/2hYY20OGjpg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++