= Sprint #2

== Intro Video

*Insert Video Here*

== Sprint Dates
All sprints will have the same due dates, but the sprint start and end dates are slightly shifted depending on when a team has their lab (2 hours) and lecture (50 minutes). This is so that sprints always start with a lec and follow the format lec-lab-lec-lab.

You can find a xref:fall2023/schedule.adoc#sprint-schedule[visual of the sprint schedule here]. More details will be covered in the agile training below. 

_Monday, 9/4:  Labor Day (no Corporate Partner meetings/classes)_

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 9/7
|Tues 9/5

|*Sprint End Date*
|Wed 9/20
|Sun 9/17

|*Due Date*
2+| Wed 9/20 by 11:59 PM ET

|===


== Sprint Schedule

=== Team Meeting #1 (50 minutes):

* Greet students and mentor as they join the Team Meeting & take attendance of students present.
* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles,roadblocks or barriers that they experienced while completing this weeks task?
** What do they plan on committing to completing by next mentor meeting?
* Time for questions from students to mentor.
* Before the end of the meeting, assign background readings and prepwork that students should prepare before the next lab
** This can include content from the charter or other materials you have found helpful in your preparation for the project
** Please also consider starter guides that are relevant to your project

=== Lab Section #1 (1 hour and 50 Minutes):

* Begin lab by doing an Agile review with students and assist students in setting up https://the-examples-book.com/starter-guides/tools-and-standards/git/github-anvil[Github on Anvil]
** Use this powerpoint to facilitate the discussion: xref:attachment$agile_reflection.pptx[Agile Reflection Guide]
* Use the remainder of the time to review relative, supplementary content for your project including:
** Starter Guides 
** Background Readings
** Sprint Tasks for students: xref:students:fall2023/sprint2.adoc[Sprint 2 Tasks]


=== Team Meeting #2 (50 minutes):

* Greet students and mentor as they join the Team Meeting & take attendance of students present.
* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles,roadblocks or barriers that they experienced while completing this weeks task?
** What do they plan on committing to completing by next mentor meeting?
* Time for questions from students to mentor.
* Before the end of the meeting, assign background readings and prepwork that students should prepare before the next lab
** This can include content from the charter or other materials you have found helpful in your preparation for the project
** Please also consider starter guides that are relevant to your project


=== Lab Section #2 (1 hour and 50 Minutes):

* Begin lab with this sprint's professional development topic of RACI Matrix and discuss with your team whether you will be using this tool for your project.
** Use this powerpoint to facilitate the discussion: xref:attachment$RACI.pptx[RACI Guide]
** *ACTION ITEM*: Review xref:raci_guide.adoc[RACI Guide] for more information on RACI Matrix.
* Use the remainder of the time to review relative, supplementary content for your project including:
** Starter Guides 
** Background Readings
** Sprint Tasks for students: xref:students:fall2023/sprint2.adoc[Sprint 2 Tasks]