= TDM 20100: Project 2 -- Manipulating the Filesystem

**Motivation:** In the previous project we took a minute to get re-familiarized with working on Anvil before diving straight into the CLI, learning how to move around the filesystem. Now that we know how to move around, we are ready to learn how to manipulate the filesystem. By learning to create, destroy, and move files and directories, along with some basic commands to begin to analyze files, we will be well on our way to performing some primitive forms of data analysis using nothing but the terminal!

**Context:** The ability to use `cd`, `pwd`, and `ls` to orient yourself in the filesystem, along with a basic understanding of `man` pages, will make this project drastically easier on you.

**Scope:** Anvil, Jupyter Labs, CLI, Bash, GNU, filesystem manipulation

.Learning Objectives:
****
- Learn how to create and destroy files from the CLI
- Learn how to create and destroy directories from the CLI
- Learn how to move files and directories around the filesystem
- Learn about basic file analysis commands
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about project submissions xref:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset(s):

- Ipsum lorem

== Questions

=== Question 1 (2 pts)

To start, let's establish a convention that will make your work on these next few projects _much_ easier. Any time that we can, we should keep all of our work in one place: the `$SCRATCH` directory. Not only will this help you keep track of everything, but it will also make sure that you don't accidentally delete any of your projects by mistake (assuming you keep your projects in your `$HOME` directory, as many do). So just remember to start your code cells off with `cd $SCRATCH` whenever appropriate, and never be afraid to `pwd` a whole bunch to be sure that you're in the right place.

Let's talk about creating and removing files. As you'll see with many things in the terminal, there are a lot of different routes to accomplishing the same task.

.Deliverables
====
- Ipsum lorem
====

=== Question 2 (2 pts)

Ipsum lorem dolor sit amet, consectetur adipiscing elit

.Deliverables
====
- Ipsum lorem
====

=== Question 3 (2 pts)

Ipsum lorem dolor sit amet, consectetur adipiscing elit

.Deliverables
====
- Ipsum lorem
====

=== Question 4 (2 pts)

Ipsum lorem dolor sit amet, consectetur adipiscing elit

.Deliverables
====
- Ipsum lorem
====

=== Question 5 (2 pts)

Ipsum lorem dolor sit amet, consectetur adipiscing elit

.Deliverables
====
- Ipsum lorem
====

== Submitting your Work

This is where we're going to say how to submit your work. Probably a bit of copypasta.

.Items to submit
====
- Ipsum lorem
- Ipsum lorem
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====