= 201 Project 05 - Groupby 

In this project, we will groupby function in pandas library 

== Project Objectives

- Use the `groupby` function to group the data
- Calculate Summary Statistics
- Aggregate Multiple Statistic
- Visualize the Data  

== Dataset

. `/anvil/projects/tdm/data/Iris.csv`   

== Reading And Resources
. https://www.shanelynn.ie/summarising-aggregation-and-grouping-data-in-python-pandas/[Python Groupby]
. https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html[groupby]

== Questions 

[NOTE]
====
We will use the Iris dataset. You can use the pandas library to read
the dataset.
[source,python]
----
import pandas as pd
 
my_df = pd.read_csv('/anvil/projects/tdm/data/Iris.csv')
----

We will drop 'ID' column from the dataframe since we do not need this column

my_df = my_df.drop(columns=['Id'])

====

=== Question 1 (2 points )

.. Please display the first 6 rows of the dataset

.. Please use 'info()' to get dataset basic information 
 

.. Please use 'describe()` to get statistics information and explain the meaning
 
print(my_df.describe())

=== Question 2 (2 points):  

[NOTE]
====
pandas `groupby` function can be used to group data based on values at dataset column(s). 

For example, we can use following statement to group the data by the "Species" column:

[source,python]
----
group_by_species = my_df.groupby('Species')

# Display 10 records for each grouped data
for name, group in group_by_species:
    print(name)
    print(group.head(10))
----
`mean`,`median` and `std` can be used to calculate summary statistics for each group like calculate the mean for each group
[source,python]
----
mean_stats = group_by_species.mean()
print("Mean Statistics:")
print(mean_stats)
----
====
.. Please calculate the `median` for different iris groups
.. Please calculate the standard deviation for different iris group
 
[NOTE]
==== 
`agg` function can be used to calculate multiple statistics at once like 

[source,python]
length_agg = group_by_species.agg({'SpepalLengthCm':['mean', 'median', 'std']})
====

=== Question 3 (2 points)

.. Please use `agg` to get `mean` and `max` of sepal's width ('SepalWidthCm' column) for each group
.. Please use `agg` to get `median` and `std` of petal's  length ('PetalLengthCm' column) for each group


=== Question 4 (2 points)

.. Please calculate and display the count of each species in the dataset using the `groupby` function.

[TIP]
====
`size` function will be useful to count the amount for each group
====


[NOTE]
====
you can visualize the grouped data using `matplotlib`. For example

[source,python]
----
import matplotlib.pyplot as plt
# Plot the mean sepal length  
mean_stats['SepalLengthCm'].plot(kind='bar', title='Mean Sepal Length')
plt.xlabel('Species')
plt.ylabel('Mean Sepal Length')
plt.show()
----
====
=== Question 4 (2 points)
.. Please plot the standard deviation of petal width ('PetalWidthCm' column) for each species
  

Project 04 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project04.ipynb` 
* Python file with code and comments for the assignment
    ** `firstname-lastname-project04.py`
* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double-check that your submission is complete and contains all of your code and output before submitting. If you have a spotty internet connection, it is recommended to download your submission after submitting it to ensure what you _think_ you submitted is what you _actually_ submitted.

In addition, please review our xref:projects:submissions.adoc[submission guidelines] before submitting your project.
====

 