 
= 201 Project 02: Exploratory Data Analysis of NOAA Weather Data

In this project, we continue to explore NOAA weather data to understand its main characteristics

== Objectives

* Load and preprocess NOAA weather data
* Calculate summary statistics and identify trends over time
* Create additional features that may benefit future models
* Visualize the data to better understand its structure and trends

== Dataset

The dataset used from NOAA which contains daily weather observations for various stations. You may get more information for it from `readme` file

- `/anvil/projects/tdm/data/noaa/2010.csv`
- `/anvil/projects/tdm/data/noaa/readme-by_year.txt`

== Questions

=== Question 1 (1 point)
 
[NOTE]
====
We will use pandas library to load file data

[source,python]
----
import pandas as pd
file_path = '/anvil/projects/tdm/data/noaa/2010.csv'
----
====
.. Please refer to readme file: readme-by_year.txt and create a list for column titles named "column_names"

- Answer
column_names = [
    'ID', 'DATE', 'ELEMENT', 'VALUE', 'M-FLAG', 
    'Q-FLAG', 'S-FLAG', 'OBS-TIME'
]

.. Please load the dataset of 2010.csv to a DataFrame named my_df with column_names as column titles

Answer 

my_df = pd.read_csv(file_path, header=None, names=column_names)

== Question 2 

.. Please display the my_df's first few rows 

Answer

print(my_df.head())

.. Please display the column titles 

Answer

print(my_df.columns)

.. Please use `describe()` to show the file information 

Answer 

print(my_df.describe())

.. Please use `shape` to display the shape of the dataframe

Answer

print(my_df.shape)

.. Please use `info()` to display the dataframe info

Answer

print(my_df.info())

== Question 3 (2 points)

[NOTE]
====
The `to_datetime()` is a function provided by pandas library to convert data to datetime format. This function can parse dates in various formats and convert them into datetime objects, making it easier to perform operations like sorting, filtering, and plotting based on dates.
====
.. Please us `to_datetime()` Convert column 'DATE' to datetime format 

Answer 

my_df['DATE'] = pd.to_datetime(my_df['DATE'], format='%Y%m%d')

== Question 4 (2 points)

[NOTE]
====
We can plot values over time to understand trends. You will need to make sure that the date column is in datetime format. Then, you can use plotting libraries such as `Matplotlib` to create a line plot, like for "TMAX" values

[source,python]
----
TMAX_df = my_df[my_df['ELEMENT'] == 'TMAX'].sort_values(by='DATE')
 
plt.figure(figsize=(14, 8))
plt.plot(TMAX_df['DATE'], TMAX_df['VALUE'], label='TMAX')
plt.xlabel('Date')
plt.ylabel('Temperature')
plt.title('Max Temperature Trends Over Time')
plt.legend()
plt.show()
----
====

.. Please Plot TAVG values over time to identify trends

Answer

TAVG_df = my_df[my_df['ELEMENT'] == 'TAVG'].sort_values(by='DATE')

plt.figure(figsize=(14, 8))
plt.plot(TAVG_df['DATE'], TAVG_df['VALUE'], label='TAVG')
plt.xlabel('Date')
plt.ylabel('Temperature')
plt.title('Average Temperature Trends Over Time')
plt.legend()
plt.show()

== Question 5 (2 points)

[NOTE]
====
You can also plot two distribution values, such as TMAX and TMIN, you need to filter the DataFrame for these elements separately first. Then use Matplotlib to create line plots or histograms to visualize the distribution of these values, like
[source,python]
----
TMAX_df = my_df[my_df['ELEMENT'] == 'TMAX']
TMIN_df = my_df[my_df['ELEMENT'] == 'TMIN']

# Plot histograms for TMAX and TMIN values
plt.figure(figsize=(14, 8))

# Histogram for TMAX
plt.hist(TMAX_df['VALUE'], bins=30, alpha=0.5, label='TMAX')

# Histogram for TMIN
plt.hist(TMIN_df['VALUE'], bins=30, alpha=0.5, label='TMIN')

plt.xlabel('Temperature')
plt.ylabel('Frequency')
plt.title('Distribution of Maximum and Minimum Temperatures')
plt.legend()
plt.show()

----
 
====

.. Please visualize the distributions of `TAVG`and `TMIN` values with histogram plot(2 points)

 
 

Project 02 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project02.ipynb` 
* Python file with code and comments for the assignment
    ** `firstname-lastname-project02.py`
* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.

In addition, please review our xref:projects:current-projects:submissions.adoc[submission guidelines] before submitting your project.
====

 