 
= 201 Project 02 - Exploratory Data Analysis of NOAA Weather Data

In this project, we continue to explore NOAA weather data to understand its main characteristics, identify trends over time, visualize the data in different ways

== Project Objectives

* Load and pre-process NOAA weather data
* Calculate summary statistics and identify trends over time
* Create additional features that may benefit future models
* Visualize the data to better understand its structure and trends

== Dataset

The dataset used from NOAA which contains daily weather observations for various stations. You may get more information for it from `readme` file.

- `/anvil/projects/tdm/data/noaa/2010.csv`
- `/anvil/projects/tdm/data/noaa/readme-by_year.txt`

== Questions

=== Question 1 (2 points)
 
[NOTE]
====
let us the pandas library to load the data from the file like,

[source,python]
----
import pandas as pd
file_path = '/anvil/projects/tdm/data/noaa/2010.csv'
----
====
.. First, use the readme file: `/anvil/projects/tdm/data/noaa/readme-by_year.txt` to create a list of column titles named "column_names"

[TIP]
====
You may use the following to create a list for columns: 'ID', 'DATE', 'ELEMENT', 'VALUE', 'M-FLAG', 
    'Q-FLAG', 'S-FLAG', 'OBS-TIME'
====

.. Next, load the dataset of 2010.csv into a DataFrame named my_df,using column_names to add in the column titles. (HINT: https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html[`pd.read_csv()`] can help you with this!)


=== Question 2 (2 pts)

.. Please display the my_df's first 10 rows 
.. Please display the column titles 
.. Please use `describe()` to show the file information 
.. Please use `shape` to display the shape of the dataframe
.. Please use `info()` to display the dataframe info


=== Question 3 (2 points)

[NOTE]
====
The `to_datetime()` is a pandas function to convert data to a specialized datetime format. It can parse dates in various formats and convert them into datetime objects, making it easier to perform operations like sorting, filtering, and plotting based on dates.
====
.. Please use `to_datetime()` to convert column 'DATE' to datetime format 

[TIP]
====
You can get more `to_datetime` information https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html[here]
====

=== Question 4 (2 points)

[NOTE]
====
We can visualize values over time to understand trends. You will need to make sure that the date column is in datetime format. Then, you could use `Matplotlib` to create a line plot for "TMAX" values like so,

[source,python]
----
TMAX_df = my_df[my_df['ELEMENT'] == 'TMAX'].sort_values(by='DATE')
 
plt.figure(figsize=(14, 8))
plt.plot(TMAX_df['DATE'], TMAX_df['VALUE'], label='TMAX')
plt.xlabel('Date')
plt.ylabel('Temperature')
plt.title('Max Temperature Trends Over Time')
plt.legend()
plt.show()
----
====

.. Please create a line plot for 'TAVG' values over time to identify trends


=== Question 5 (2 points)

[NOTE]
====
You can also plot more than one value at once for easy comparison, such as TMAX and TMIN. You need to filter the DataFrame for these elements separately first and _then_ use Matplotlib to create line plots or histograms to visualize the distribution of these values, like so:

[source,python]
----
TMAX_df = my_df[my_df['ELEMENT'] == 'TMAX']
TMIN_df = my_df[my_df['ELEMENT'] == 'TMIN']

# Plot histograms for TMAX and TMIN values
plt.figure(figsize=(14, 8))

# Histogram for TMAX
plt.hist(TMAX_df['VALUE'], bins=30, alpha=0.5, label='TMAX')

# Histogram for TMIN
plt.hist(TMIN_df['VALUE'], bins=30, alpha=0.5, label='TMIN')

plt.xlabel('Temperature')
plt.ylabel('Frequency')
plt.title('Distribution of Maximum and Minimum Temperatures')
plt.legend()
plt.show()

----
====

.. Please visualize the distributions of `TAVG` and `TMIN` values with a histogram plot


Project 02 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project02.ipynb` 
* Python file with code and comments for the assignment
    ** `firstname-lastname-project02.py`
* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.

In addition, please review our xref:projects:current-projects:submissions.adoc[submission guidelines] before submitting your project.
====

 