= TDM 20100: Project 2 -- Manipulating the Filesystem

**Motivation:** In the previous project we took a minute to get re-familiarized with working on Anvil before diving straight into the CLI, learning how to move around the filesystem. Now that we know how to move around, we are ready to learn how to manipulate the filesystem. By learning to create, destroy, and move files and directories, along with some basic commands to begin to analyze files, we will be well on our way to performing some primitive forms of data analysis using nothing but the terminal!

**Context:** The ability to use `cd`, `pwd`, and `ls` to orient yourself in the filesystem, along with a basic understanding of `man` pages, will make this project drastically easier on you.

**Scope:** Anvil, Jupyter Labs, CLI, Bash, GNU, filesystem manipulation

.Learning Objectives:
****
- Learn how to create and destroy files from the CLI
- Learn how to create and destroy directories from the CLI
- Learn how to move files and directories around the filesystem
- Learn about basic file analysis commands
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about project submissions xref:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset(s):

- `/anvil/projects/tdm/data/*` (we will use many datasets, in brief)

== Questions

=== Question 1 (2 pts)

To start, let's establish a convention that will make your work on these next few projects _much_ easier. Any time that we can, we should keep all of our work in one place: the `$SCRATCH` directory. Not only will this help you keep track of everything, but it will also make sure that you don't accidentally delete any of your projects by mistake (assuming you keep your projects in your `$HOME` directory, as many do). So just remember to start your code cells off with `cd $SCRATCH` whenever appropriate, and never be afraid to `pwd` a whole bunch to be sure that you're in the right place.

Let's talk about creating and removing files. As you'll see with many things in the terminal there are a lot of different ways to accomplish the same task.

First off, the creation of files. While our more Bash-savvy students may say "Just open your favorite text editor and it'll make a new file for you!", we are going to refrain from discussing CLI text-editors like Vim and Nano, as their applications would not be very directly helpful for this class. Instead, we'll discuss the `touch` command. Creating a file is as easy as using `touch filename` to create a new file called `filename` in your current working directory (the one printed by `pwd`). However, it is often best practice to make sure that your file has the proper extension (like `.txt`, `.xdocx`, `.pdf`, and more!) in order to ensure the computer knows how to open your file.

Deletion of files is similarly easy using the `rm` command, where `rm filename` will delete a given file. Both `touch` and `rm` have their fair share of optional arguments, which you can examine in detail by viewing their respective man pages (using `man touch`, for example). Be sure to exercise _great_ caution when using `rm`, as this isn't like dropping a file into the recycling bin on your desktop. When you `rm` a file, it is gone. Permanently. End of discussion (...mostly). Do _not_ use `rm` before being sure that you're okay with deleting what you're deleting, and be sure you understand any arguments you may be using.

[IMPORTANT]
====
For an added degree of caution, you can use `rm -i` to be prompted before the final removal of a file. This is a good safeguard when just starting out with `rm`
====

Thirdly, let's discuss putting content into files. While once again this can be done with text editors, this course will not focus on the manual population of file contents and will instead deal with processing and managing data using tools. By-hand manipulation of real-world data is, after-all, completely impractical!

Try running the following code, which creates a file named `start.txt` in your scratch directory, adds the text "The meaning of life is the number 42." to the file, `echo`s the contents of the file to the console, and then removes the file.

[source, python]
----
%%bash
cd $SCRATCH

touch starter.txt # create the file starter.txt
echo "The meaning of life is the number 42." > starter.txt # add contents to starter.txt
echo " -------------------------- " # spacer
cat starter.txt # print contents of file
rm starter.txt
----

For this question, we want you to write code that creates a new file called `greeting.txt` in your scratch directory, fills in the file with the text "Hello World!", prints the contents of the file, and then removes the file. Feel free to do this all in one cell, or spread among multiple cells if you prefer. Feel free to refer to the above example code for a _very_ big headstart into this question.

.Deliverables
====
- Bash to create, populate, then delete `greeting.txt` as specified
====

=== Question 2 (2 pts)

Next let's discuss creating directories. After all, computers have a _lot_ of files. We would be limited in a lot of ways if we stored everything in one place.

Creating directories can be done using `mkdir`. For example, `mkdir fakefolder` would create a new directory called `fakefolder`. By using `rmdir`, we can easily remove directories.

Run the below example step-by-step, examining the outputs of each step.

[source, python]
----
%%bash
cd $SCRATCH

# Step 1 - Show the directory doesn't exist
ls -l

# Step 2 - Create the directory, and show it exists
mkdir fakefolder
ls -l

# Step 3 - Delete the directory, and show it no longer exists
rmdir fakefolder
ls -l
----

Next, let's take a look at a more complex example. While `rmdir` is capable of deleting empty directories, it struggles with directories that still have contents we also want to delete. Run the below example, and observe the resulting error:

[source, python]
----
%%bash
cd $SCRATCH
mkdir fakefolder
touch fakefolder/fakefile
rmdir fakefolder
----

For directories with contents, we'll have to refer back to trusty old `rm`. Passing the recursive flag, `-r`, to `rm` will cause it to delete a directory and all its contents. With that knowledge in mind, take another few seconds to recognize the amount of damage one could accidentally due with misuse of these commands. Once you've reflected on the possible consequences of using `rm` without caution, try and complete the below activities.

. Create a directory called `emptycase` in the scratch directory
. Remove `emptycase` and then list the contents of `$SCRATCH`
. Create a directory called `fullcase` in the scratch directory
. Create a new file, `contents.txt`, within `fullcase`
. List the contents of `$SCRATCH`, then list the contents of `fullcase`
. Remove `fullcase` using the recursive argument to `rm`
. List the contents of `$SCRATCH`


.Deliverables
====
- Commands to complete the above 7 steps
====

=== Question 3 (2 pts)

In this question, we'll take a look at _moving_ and _copying_ files. Again, there are many ways of accomplishing this, with `mv` and `cp` being some of the more common ones. Let's briefly discuss both.

- http://man.he.net/?topic=mv&section=all[`mv`] can be used to move or rename files and directories
- http://man.he.net/?topic=cp&section=all[`cp`] can be used to copy files and directories to other locations

Below are a few example snippets of each. Take a look and feel free to run them on your own, as understanding each of these separately will better enable you to tackle the tasks at the end of the question. Be sure to run each snippet in order to ensure they run correctly.

[source, Python]
----
%%bash
cd $SCRATCH

# set-up for other examples
mkdir dir1
touch dir1/file2

mkdir dir2
touch dir2/file1
touch dir2/file3

# prints results
echo dir1: 
ls -l dir1
echo
echo dir2:
ls -l dir2
----

[source, Python]
----
%%bash
cd $SCRATCH

# copy file2 from dir1 to dir2, then delete the dir1 version
cp dir1/file2 dir2/file2
rm dir1/file2

# prints results
echo dir1: 
ls -l dir1
echo
echo dir2:
ls -l dir2
----

[source, Python]
----
%%bash
cd $SCRATCH

# move files 1 and 2 from dir2 to dir1
# note that * is another way of saying 'all files' here
mv dir2/* dir1/

# rename dir2 to dir3
mv dir2 dir3

# prints results
echo dir1: 
ls -l dir1
echo
echo dir3:
ls -l dir3
----

Using the above code snippets as a guide, for this question we want you to:

. Create two new directories in `$SCRATCH`, `directoryA` and `directoryB`
. Create a new file called `fileA` in `directoryB`, and a matching `fileB` in `directoryA`
. Make the contents of `fileA`, `This is file A!` 
. Make the contents of `fileB`, `This is file C!`
. Move `fileA` to `directoryA` and `fileB` to `directoryB`
. Rename `directoryB` to `directoryC` and `fileB` to `fileC`
. Use `ls -l` on both directories to show your final results.

.Deliverables
====
- Bash code to perform the above instructions
====

=== Question 4 (2 pts)

With the creation, deletion, and movement of files handled, let's now get into some basic tools for analyzing files. We'll start with printing the first few lines using https://explainshell.com/explain/1/head[`head`], the last few lines using https://explainshell.com/explain?cmd=tail[`tail`], and the total contents of a file using https://explainshell.com/explain?cmd=cat[`cat`].

`head` can be used to print the first 5 lines of a file (when it isn't told to print more or less). By using the `-n` flag, we can tell it to print an exact number of lines as well. `tail` can be thought of as the exact same as `head`, but starting from the ending of the file and moving backwards. For example, `head` will get the first 5 lines of a file by default while `tail` will get the last 5 lines. See below for a concrete example.

[source, python]
----
%%bash
# prints the first 5 lines of USvideos.csv
head /anvil/projects/tdm/data/youtube/USvideos.csv

# prints the last 5 lines of USvideos.csv
tail /anvil/projects/tdm/data/youtube/USvideos.csv

# print the first 2 lines of destinations.csv
head -n 2 /anvil/projects/tdm/data/expedia/destinations.csv
# equivalently (notice the spacing around -n2):
head -n2 /anvil/projects/tdm/data/expedia/destinations.csv

# print the last line of destinations.csv
tail -n 1 /anvil/projects/tdm/data/expedia/destinations.csv
----

[NOTE]
====
Observe that often, the first line of a data file contains the titles of the columns in the data
====

Additionally (although not as often), we will want to view the contents of a file in whole. For this, `cat` is perfect. Try running the below code, and observe it's effects:

[source, python]
----
%%bash

# prints all the contents of the file readme-by_year.txt
cat /anvil/projects/tdm/data/noaa/readme-by_year.txt
----

For this question, we want you to do the following:

. print the first 3 lines of `/anvil/projects/tdm/data/election/itcont1986.txt`
. print the last 2 lines of `/anvil/projects/tdm/data/craigslist/vehicles_clean.txt`
. print the contents of `/anvil/projects/tdm/data/noaa/status-by_year.txt`

.Deliverables
====
- The file contents requested above, and the commands to get them
====

=== Question 5 (2 pts)

With these basic tools to look at the contents of a file covered, let's talk about two commands useful to discover more about the _size_ and _structure_ of our file: `wc` and `du`.

`wc`, which stands for _word count_, is actually capable of much more than simply counting the words in a file! Take a look at some of the below examples, along with https://explainshell.com/explain/1/wc[this man page], for some ideas about the power of `wc`.

[source, python]
----
%%bash

# prints newline, then word, then byte counts for 2012.csv
wc /anvil/projects/tdm/data/stackoverflow/processed/2012.csv

# prints just word count for 2012.csv
wc -w /anvil/projects/tdm/data/stackoverflow/processed/2012.csv

# prints just byte count for 2012.csv
wc -c /anvil/projects/tdm/data/stackoverflow/processed/2012.csv
----

Where `wc` examines the number of lines, bytes, or characters _within_ a file, `du` (which stands for disk usage) measures the total disc space occupied by files and directories. Again, review https://explainshell.com/explain/1/du[the man page for `du`] and the below examples, and then move onto the tasks for the final set of tasks for this project.

[source, python]
----
%%bash

# print the number of bytes that all of the processed directory is taking up
du -b /anvil/projects/tdm/data/stackoverflow/processed

# prints the number of kilobytes that the processed directory is taking up
du --block-size=KB /anvil/projects/tdm/data/stackoverflow/processed

# prints the number of kilobytes that each file in the processed directory is taking up
du --block-size=KB -a /anvil/projects/tdm/data/stackoverflow/processed
----

. How many lines are there in `/anvil/projects/tdm/data/beer/beerfile1.csv`? (Hint: `wc -l`)
. What is the length of the longest line in `/anvil/projects/tdm/data/beer/beerfile1.csv`? (Hint: `wc` has another argument to do this!)
. What is the size of the `/anvil/projects/tdm/data/beer/` directory in megabytes?
. What is the size of each individual file in `/anvil/projects/tdm/data/beer/`, in megabytes?

[NOTE]
====
If you're struggling with some of these tasks, _please_ refer back to the man pages or the https://explainshell.com[explainshell] page for a given command for some _strong_ hints on where to go next. 
====

.Deliverables
====
- The sizes requested above, and the commands used to produce these sizes
====

== Submitting your Work

Congratulations! With this project complete, you're now familiar with all of the basics of the command line! With these tools in your belt, you can now explore, analyze, and manipulate a large part of Anvil at your whims! Please don't use your newfound powers for evil though...

In the next project, we'll be building on these more primal analysis tools by introducing some more complex commands that allow us to perform specific search-and-return processes on data. From there, the sky is the limit, and we will be ready to dive into one of the most useful and important concepts in all of code: *pipelines*

.Items to submit
====
- firstname-lastname-project2.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====