= 201 Project 05 - Groupby 

In this project, we will use the `groupby` function in the pandas library. 

== Project Objectives

- Use the `groupby` function to group the data.
- Calculate summary statistics.
- Aggregate multiple statistics.
- Visualize the data.

== Dataset

- `/anvil/projects/tdm/data/Iris.csv`   

== Reading And Resources

- https://www.shanelynn.ie/summarising-aggregation-and-grouping-data-in-python-pandas/[Python Groupby]
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html[groupby]

== Questions 

=== Question 1 (2 points)

We will first load the Iris dataset. You can drop the `Id` column as we do not use this column in this project.

[source,python]
----
import pandas as pd

my_df = pd.read_csv('/anvil/projects/tdm/data/Iris.csv')
my_df = my_df.drop(columns=['Id'])
----

.. Please display the first 6 rows of the dataset.
.. Please use `info()` to get basic information about the dataset.
.. Please use `describe()` to get statistical information and explain the meaning.

=== Question 2 (2 points)

The pandas `groupby` function can be used to group data based on values in dataset column(s). 

The following is an example to group the data by the "Species" column:

[source,python]
----
group_by_species = my_df.groupby('Species')
----

`mean`, `median`, and `std` can be used to calculate summary statistics for each group. The following is an example to calculate the mean for each group:

[source,python]
----
mean_stats = group_by_species.mean()
print("Mean Statistics:")
print(mean_stats)
----

.. Please calculate the `median` for different iris groups.
.. Please calculate the standard deviation for different iris groups.

=== Question 3 (2 points)

The `agg` function can be used to calculate multiple statistics at once. The following is an example:

[source,python]
----
length_agg = group_by_species.agg({'SepalLengthCm':['mean', 'median', 'std']})
----

.. Very similar to the example, please use `agg` to get `mean` and `max` of sepal width ('SepalWidthCm' column) for each group.
.. Please use `agg` to get `median` and `std` of petal length ('PetalLengthCm' column) for each group.

=== Question 4 (2 points)
 
`apply` can be used to filter the data. Like if we only want to have data for 'PetalLengthCm' that is 3.0 and larger, we can define a function, then, use this function to filter the DataFrame  

[source,python]
----
def sepal_width(length):
    return length >= 3.0

filtered_sepal = my_df[my_df['SepalWidthCm'].apply(sepal_width)]
 
----

.. Similar to the example code, please filter the data with only PetalLengthCm is greater then 5.0



=== Question 5 (2 points)

You can visualize the grouped data using `matplotlib`. For example:

[source,python]
----
import matplotlib.pyplot as plt

# Plot the mean sepal length  
mean_stats['SepalLengthCm'].plot(kind='bar', title='Mean Sepal Length')
plt.xlabel('Species')
plt.ylabel('Mean Sepal Length')
plt.show()
----

.. Similar to the example, please plot the standard deviation of petal width ('PetalWidthCm' column) for each species.

Project 05 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments, and output for the assignment.
    ** `firstname-lastname-project05.ipynb` 
* Submit files through Gradescope.
====

[WARNING]
====
_Please_ make sure to double-check that your submission is complete and contains all of your code and output before submitting. If you have a spotty internet connection, it is recommended to download your submission after submitting it to ensure what you _think_ you submitted is what you _actually_ submitted.

In addition, please review our https://the-examples-book.com/projects/submissions[submission guidelines] before submitting your project.
====
 