= 201 Project 01 - Data Wrangling with GNU Command Line Utilities

== Project Objectives

- Learn basic command line operations for handling CSV files
- Prepare raw data for further analysis by resolving formatting inconsistencies, missing values 

== Reading and Resources

- https://www.gnu.org/software/coreutils/manual/coreutils.html[GNU Coreutils Documentation]
- https://www.gnu.org/software/gawk/manual/gawk.html[GNU Awk User's Guide]

== Dataset

- /anvil/projects/tdm/data/noaa/2010.csv

== Questions  

=== Question 1 (2 points) 

Read the following documentation on the `ls`, `head` and `tail` commands:

- https://www.gnu.org/software/coreutils/manual/coreutils.html#head-invocation[head]
- https://www.gnu.org/software/coreutils/manual/coreutils.html#tail-invocation[tail]
- https://www.gnu.org/software/coreutils/manual/coreutils.html#ls-invocation[ls]

[NOTE]
====

To get basic file information and view specific rows, the following commands are useful:

- `ls` to list file details, replace the file_name with the file you want to check such as /anvil/projects/tdm/data/noaa/2010.csv to get file information

[source,bash]
ls -lh file_name

- `head` to display the first few lines for a file, like  

[source,bash]
head -n 20  file_name

- `tail` to display the last few lines for a file, like   

[source,bash]
tail -n 20  file_name

====

.. Use the `ls -lh ` command to view file '2010.csv' information and explain the output.
.. Use the `head`,`tail` and pipe commands to display first 10 lines of the 2010.csv file and content from the 33rd line.

[TIP]
====

A pipeline or simple as pipe (`|` ) is used to pass the output of one command to the input of another command. Like in the following example get first 20 lines of the file 2010.csv then use it as input to the next command `tail` to get the last line of them 

[source,bash]
head -n 20 2010.csv | tail -n 1

====

=== Question 2 (2 points)

https://www.gnu.org/software/gawk/manual/gawk.html[GNU Awk User's Guide] may be helpful to learn to use `awk` command 

[NOTE]
====
- You can use `wc` to analyze file such as to count the total number of records

[source, bash]
wc -l filename

- You can use `awk` to manipulate data and generate data information like to get and print out the number of fields in the current record 

[source,bash]
awk -F, '{print NF}'
 
====

.. Please use `wc`, `awk` and pipeline to count how many records are in 2010.csv that with an ELEMENT of "TAVG" (column 3)
 
[TIP]
====
The following is a example to filter a file to only have 3rd column is "TMAX" and save the output to a file 

[source,bash]
awk -F, '$3=="TMAX"' 2010.csv > 'filter_TMAX.txt'

 
====

=== Question 3 (2 points) 

[NOTE]
====
- You can use `>` to save data to a file like

[source,bash]
awk -F, 'condition' filename > filteredfilename

- You can use '||'  as 'or'
====

.. Select a value for the `column 3` from `TMAX`, `TMIN`, or `TAVG`, use `awk` command to compare and save filtered data to a file named "2010_filtered.csv"  

 
=== Question 4 (2 points)

[NOTE]
====
You can extract unique values by using combination of commands like `sort`,`uniq` etc
- `sort` can be used to sort lines of text files alphabetically

[source,bash]
sort filename

- `uniq` can be used to remove adjacent duplicated lines

[source,bash]
uniq filename

====

.. Use `awk`, `sort`, `uniq` and pipeline to get the unique stations which is column 1 in the file, and save the output to a file named 'stations_output.txt' 

[TIP]
====
You can get column n's content by using

[source,bash]
awk -F, {print $n} filename
====

=== Question 5 (2 points) 

[NOTE]
====
- `awk` action block can also include selection or repetition structures, for example if we have a file named surplus.txt contains following data:

[cols="3,2" ]
|===
|table| 20
|printer|100
|bike|10
|printer|60
|bike|30
|===


We want to reduce each printer by 5, we can do

[source,bash]
awk -F, '{if ($1== 'printer') $2=$2-5;print}' surplus.txt

We can change the first column to upper case by doing following loop

[source,bash]
awk -F, '{for (i=1;i<=NF;i++) $i=toupper($i);print}' surplus.txt 

====

.. Please convert the temperature values in column 4 to regular decimal point values by dividing each by 10 if column 3 is  `TMAX`, `TMIN`, or `TAVG` and save to a file column3.txt 



Project 01 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project01.ipynb` 
* Python file with code and comments for the assignment
    ** `firstname-lastname-project01.py`
* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.

In addition, please review our xref:projects:current-projects:submissions.adoc[submission guidelines] before submitting your project.
====