= TDM 20100: Project 6 -- Awk Everything! 1

**Motivation:** As you've seen so far, `bash` has a wide variety of commands that enable us to do different things, and we can use pipes to connect those commands and perform whole loads of data processing in one big step. However, conciseness _is_ a virtue. In this project we'll start learning about `awk`, the bash multi-tool capable of performing the work of tons of commands all by itself. By the end of the next few weeks, you'll be able to do entire pipelines worth of work in just one `awk`!

**Context:** This project will relate `awk` concepts back to previously learned commands, and at the very least a basic knowledge of filesystem navigation and regex will be needed.

**Scope:** `awk`, data processing, Bash, GNU, CLI

.Learning Objectives:
****
- Learn the general structure of a call to `awk`
- Construct your first basic `awk`
- Use `awk` to print common file information
- Use `awk` to print specific parts of files
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about project submissions xref:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset(s):

- Ipsum lorem
- Ipsum lorem

== Questions

=== Question 1 (2 pts)

Ipsum lorem dolor sit amet, consectetur adipiscing elit

.Deliverables
====
- Ipsum lorem
====

=== Question 2 (2 pts)

Ipsum lorem dolor sit amet, consectetur adipiscing elit

.Deliverables
====
- Ipsum lorem
====

=== Question 3 (2 pts)

Ipsum lorem dolor sit amet, consectetur adipiscing elit

.Deliverables
====
- Ipsum lorem
====

=== Question 4 (2 pts)

Ipsum lorem dolor sit amet, consectetur adipiscing elit

.Deliverables
====
- Ipsum lorem
====

=== Question 5 (2 pts)

Ipsum lorem dolor sit amet, consectetur adipiscing elit

.Deliverables
====
- Ipsum lorem
====

== Submitting your Work

This is where we're going to say how to submit your work. Probably a bit of copypasta.

.Items to submit
====
- Ipsum lorem
- Ipsum lorem
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====