= TDM 20100: Project 4 -- Pattern matching in pipelines

**Motivation:**  We have begun to learn how to build pipelines in bash.  Now we will integrate pattern matching into bash pipelines.

**Context:** Pattern matching, used as part of a pipeline, is a very powerful technique.

**Scope:** Pipelines and pattern matching in Bash

.Learning Objectives:
****
- Learn about using pattern matching in bash pipelines.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about project submissions xref:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset(s):

- `/anvil/projects/tdm/data/flights/subset/` (airplane data)
- `/anvil/projects/tdm/data/election` (election data)
- `/anvil/projects/tdm/data/8451/The_Complete_Journey_2_Master/5000_transactions.csv` (grocery store data)

== Questions

=== Question 1 (2 pts)

In Project 1, question 4, we learned how to find lines of the file that contain the pattern "IND" (these are the flights that have origin or destination at the Indianapolis airport).

In Project 3, question 1, we extracted all of the origin and destination airports, using one pipeline of bash commands.

Revisit Project 3, question 1, but this time, use `grep IND` early in your bash pipeline, so that your results only show flights that either have origin or destination at Indianapolis.  The goal is to show the 10 most popular flight paths to-or-from Indianapolis (during the years 1987 to 2008), and the number of times that airplanes flew on each of these flight paths.

[HINT]
====
You want the top 10 most popular flight paths that are either to Indianapolis or from Indianapolis.  The top 2 most popular flight paths that are either to Indianapolis or from Indianapolis (which should be the last two lines of your ten lines of output) are:

[source, bash]
----
  76554 ORD,IND
  77720 IND,ORD
----

In this question, you will find all 10 such flight paths.  Besides ORD (which is Chicago O'Hare), the other popular flight paths include these airports: ATL,DFW,DTW,MSP,STL.
====

.Deliverables
====
- Show the 10 most popular flight paths to-or-from Indianapolis (during the years 1987 to 2008), and the number of times that airplanes flew on each of these flight paths.  (We already gave you 2 of these 10 in the hint!)
====

=== Question 2 (2 pts)

In the previous project, from this file:

`/anvil/projects/tdm/data/8451/The_Complete_Journey_2_Master/5000_transactions.csv`

we discovered how many times that each of the `STORE_R` values appear in the file, using the following commands in bash:

[source, bash]
----
`cut -d, -f7` (to extract the `STORE_R` values from this file)
`sort` (to get all of the same `STORE_R` values next to each other in the file)
`uniq -c` (to discover how many times that each `STORE_R` value occurs)
`sort -n` (to numerically sort the number of times that the `STORE_R` values occur)
----

Now we can do all of this together, in one long line:

[source, bash]
----
cut -d, -f7 /anvil/projects/tdm/data/8451/The_Complete_Journey_2_Master/5000_transactions.csv | sort | uniq -c | sort -n
----

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_8vxzttjy&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++

.Deliverables
====
- List the number of times that each of the `STORE_R` values appear in the file.
====

=== Question 3 (2 pts)

Using a pipeline to discover the 10 states in which the largest number of donations have been made (and the number of donations from each of these states), using the data stored in:

`/anvil/projects/tdm/data/election/itcont*.txt`

[HINT]
====
The data can be extracted from the 10th field of the files.  The symbol "|" is the delimiter.  So the cut command should look like:  `cut -d'|' -f10`
====


.Deliverables
====
- The 10 states in which the largest number of donations have been made (and the number of donations from each of these states)
====

=== Question 4 (2 pts)

Modify your solution to Question 3 so that you extract both the city and the state (simultaneously) for each donation.  In this way, you can discover the 10 city-and-state pairs in which the largest number of donations have been made (and the number of donations from each of these city-and-state pairs).

.Deliverables
====
- The 10 city-and-state pairs in which the largest number of donations have been made (and the number of donations from each of these city-and-state pairs).
====

=== Question 5 (2 pts)

Return to the analysis of the airline data.  Modify your solution to Question 1 so that, *instead of* extracting the Origin and Destination airports, this time you can extract three columns: the year, month, and day of the flights.  In this way, you can discover the 10 most popular days to fly from 1987 to 2008, i.e., the 10 dates on which the most flights occurred (and the number of flights on each of those 10 dates).

.Deliverables
====
- The 10 dates on which the most flights occurred (and the number of flights on each of those 10 dates).
====

== Submitting your Work

You now have some experience using pattern matching inside pipelines of bash commands!  Your skills from one project to the next are growing!  Please refer back to previous projects, and ask questions anytime that you need advice or help!

.Items to submit
====
- firstname-lastname-project4.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, comments (in markdown or with hashtags), and code output, even though it may not. **Please** take the time to double check your work. See xref:submissions.adoc[the instructions on how to double check your submission].

You **will not** receive full credit if your `.ipynb` file submitted in Gradescope does not **show** all of the information you expect it to, including the output for each question result (i.e., the results of running your code), and also comments about your work on each question. Please ask a TA if you need help with this.  Please do not wait until Friday afternoon or evening to complete and submit your work.
====
