= TDM 20100: Project 8 -- SQL

**Motivation:** Starting with this project, we will learn about databases, which allow you to write queries about data.

**Context:** We will focus on SQLite.  Once you understand how to make queries in SQLite, you will have a strong foundation that can be used to learn other database resources, such as MySQL.

**Scope:** SQLite queries that do not need `JOIN`

.Learning Objectives:
****
- We will learn how to make SQLite queries on one table at a time (without using the `JOIN`)
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about project submissions xref:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset:

- `/anvil/projects/tdm/data/lahman/lahman.db` (Lahman baseball database)

Our page in The Examples Book about SQL (in general) is given here:  https://the-examples-book.com/tools/SQL/

[IMPORTANT]
====
Before you begin the project, try the examples from the Lahman baseball database found on this webpage of The Examples Book:  https://the-examples-book.com/tools/SQL/lahman-examples-no-joins  All of these examples are (relatively) simple and do not need to `JOIN` two tables.  They just rely on one table of the database at a time.
====

== Questions

Using the `seminar` kernel, if you run this line in a cell by itself:

`%sql sqlite:////anvil/projects/tdm/data/lahman/lahman.db`

Then you can make SQL queries in subsequent cells in Jupyter Lab, like this, for example:

[source,bash]
----
%%sql
SELECT * FROM Pitching LIMIT 5;
----

[WARNING]
====
It is really important to include `LIMIT 5` or something similar, for instance, `LIMIT 20`, so that you do not try to print all of the results from a SQL table in your Jupyter Lab notebook.
====

The list of all of the tables in this database are:

[source,bash]
----
AllstarFull
Appearances
AwardsManagers
AwardsPlayers
AwardsShareManagers
AwardsSharePlayers
Batting
Battingnew
BattingNEW
BattingPost
CollegePlaying
Fielding
FieldingOF
FieldingOFsplit
FieldingPost
HallOfFame
HomeGames
Managers
ManagersHalf
Parks
ParksNEW
People
PeopleNEW
Pitching
PitchingPost
Salaries
Schools
SchoolsNEW
SeriesPost
Teams
TeamsFranchises
TeamsHalf
----



=== Question 1 (2 pts)

a. From the `Teams` table, print the row corresponding to the 2023 data for the team with `name = 'Chicago Cubs'`.  Your output will be just one row, showing the Cubs overall information for 2023.

b. From the `Batting` table, print the 48 rows corresponding to the 2023 data for the players from the team with `teamID = 'CHN'` (this is the Chicago Cubs `teamID`).

[TIP]
====
For both 1a and 1b, since we only want to see the 2023 results, you need to use `yearID = 2023` as a condition in your query.
====


.Deliverables
====
- Print the 2023 summary data from the `Teams` table for the team with `name = 'Chicago Cubs'` (just one row of output).

- Print the 48 rows of table from the `Batting` table for the 2023 Chicago Cubs players.
====


=== Question 2 (2 pts)

Back in Project 6, Question 2, we added all of the donation dollar amounts from the 1980 election data:

`/anvil/projects/tdm/data/election/itcont1980.txt`

Now, instead, let's add the donation dollar amounts in each state:  Grouping the transaction amounts according to the state, add the donation dollar amounts for each state.  For your output, on each line, print the dollar amount and the state, and sort the output in numerical order.  It is OK to just print the tail of the result, so that you will print 10 lines of output.

[NOTE]
====
The bottom 4 lines are given below.
====

[source, bash]
----
17916669 
18673301 NY
24085171 CA
24472610 TX
----

[NOTE]
====
The line 17916669 without a state corresponds to the sum of the donation amounts where the state was blank!
====

.Deliverables
====
- Print the 10 largest total dollar amounts of donations, and the analogous states where those donations were made.  (The 4th largest one is a blank state and that is OK.)
====



=== Question 3 (2 pts)

In this *sample* file of beer reviews `/anvil/projects/tdm/data/beer/reviews_sample.csv`

Consider the mean beer scores on each date.

Find the three dates on which the mean score is a 5.

[NOTE]
====
This week, we are using only the sample file: `/anvil/projects/tdm/data/beer/reviews_sample.csv`

You *DO NOT* need to use the (much larger) file from last week:  `/anvil/projects/tdm/data/beer/reviews.csv`
====

[NOTE]
====
A mean `score` of "5" is a perfect score, so you can add up the scores on each date, and the number of reviews on each date, and print the ratio of the sum of scores and the number of reviews, and then sort the results numerically, and print only the tail.
====

[NOTE]
====
The date is in the 3rd field and the score is the last field on each line, i.e., the score is stored in `$NF`.
====

.Deliverables
====
- In the reviews sample file, show the three dates on which the mean `score` is a 5.
====


=== Question 4 (2 pts)

Consider the data in the file `/anvil/projects/tdm/data/8451/The_Complete_Journey_2_Master/5000_transactions.csv`

Solve the same question from Project 6, Question 4, again, but this time use associative arrays.  By using associative arrays, you can solve this question with just 1 line of awk.  You should just use awk one time (not 4 times).  By using associative arrays, you can add the total amounts of the values in the `SPEND` column, grouping the values according to the `STORE_R` column, and print the results for all 4 regions using awk just one time.


.Deliverables
====
- Print the sum of the `SPEND` column values corresponding to each of the four store regions.  Use `awk` only one time (by using associative arrays).
====


=== Question 5 (2 pts)

Find the average `DepDelay` from each `Origin` airport in 1990, i.e., using the data in the file `/anvil/projects/tdm/data/flights/subset/1990.csv`

You *do not need* to print the output for all of the `Origin` airports.  Instead, it is OK to include:

`grep 'EWR\|JFK\|LGA'`

at the end of your pipeline, so that you are only displaying the average departure delays for the three huge `Origin` airports in New York City.

.Deliverables
====
- Print the average departure delays for the three biggest airports located in New York City, namely, the average departure delay from EWR, the average departure delay from JFK, and the average departure delay from LGA.
====


== Submitting your Work

Please let us know (anytime!) if you need help as you are learning about associative arrays in awk.



.Items to submit
====
- firstname-lastname-project7.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, comments (in markdown or with hashtags), and code output, even though it may not. **Please** take the time to double check your work. See xref:submissions.adoc[the instructions on how to double check your submission].

You **will not** receive full credit if your `.ipynb` file submitted in Gradescope does not **show** all of the information you expect it to, including the output for each question result (i.e., the results of running your code), and also comments about your work on each question. Please ask a TA if you need help with this.  Please do not wait until Friday afternoon or evening to complete and submit your work.
====

