= 201 Project 04: Handling Outliers and Missing Values

In this project, we will understand the concept of how to identify and handle outliers and missing values.

== Project Objectives

- Identify and handle outliers in a dataset
- Impute missing values in a dataset

== Dataset

- `/anvil/projects/tdm/data/house_prices/train.csv` (referred to as train.csv in the file)

== Questions

[NOTE]
====

Outliers are values that are significantly different from other values, which can cause inaccurate results for data analysis.

`Z-score` method and the `Interquartile Range (IQR)` method are two common methods for detecting outliers.

We will use some examples to demonstrate the concepts as follows:

[source,python]
----
import pandas as pd

example_outliers = {
    'Index': range(1, 11),
    'Value': [10, 12, 11, 13, 100, 12, 11, 10, 12, 110]
}

my_df = pd.DataFrame(example_outliers).to_csv('outliers.csv', index=False)
----

[source,python]
----
example_missing = {
    'Index': range(1, 11),
    'Value': [10, 12, 11, None, 13, 12, None, 10, 12, 11]
}

my_df_2 = pd.DataFrame(example_missing)
my_df_2.to_csv('missing.csv', index=False)
----

`Z-score` describes the relation to the mean values, measured in terms of standard deviations from the mean. 

The following is the meaning of `Z-score` values:
- 0: a value is the same as the mean score
- 1: a value that is one standard deviation from the mean

Example of using Z-score:

[source,python]
----
from scipy import stats
import numpy as np

z_scores = stats.zscore(my_df['Value'])
abs_z_scores = np.abs(z_scores)
outliers = my_df[abs_z_scores > 3]
print("Outliers detected:\n", outliers)
----
====

=== Question 1 (2 points)

.. Please use your own words to explain the example codes above.
.. Please identify outliers in the 'SalePrice' column using `Z-score`.

The following example code uses the Interquartile Range (IQR) method:

[source,python]
----
# 25% of the Value column
Q1 = my_df['Value'].quantile(0.25)

# 75% of the Value column
Q3 = my_df['Value'].quantile(0.75)
# difference
IQR = Q3 - Q1
# boundaries if beyond are outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# replaces values 
my_df['Value'] = my_df['Value'].clip(lower_bound, upper_bound)
----

=== Question 2 (2 points)

.. Please replace outliers in the 'SalePrice' column of the train.csv file using the IQR method.

The following code is used to find out how many missing values are present:

[source,python]
----
missing_v = my_df_2.isnull().sum()
print("Missing values in each column:\n", missing_v)
----

=== Question 3 (2 points)

.. Please identify how many columns have missing values in the train.csv file.

Imputation means to replace the missing data with some specified values, like the following code to replace with the mean value:

[source,python]
----
my_df_2['Value'].fillna(my_df_2['Value'].mean(), inplace=True)
----

=== Question 4 (2 points)

.. Please replace missing values in the 'LotFrontage' column in train.csv using the `mean` value.

Missing data can significantly impact the results of model training. 


=== Question 5 (2 points)

.. Explain the importance of handling missing values in a dataset. Provide an example to support your statement


Project 04 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments, and output for the assignment
    ** `firstname-lastname-project04.ipynb` 

* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double-check that your submission is complete and contains all of your code and output before submitting. If you have a spotty internet connection, it is recommended to download your submission after submitting it to ensure what you _think_ you submitted is what you _actually_ submitted.

In addition, please review our https://the-examples-book.com/projects/submissions[submission guidelines] before submitting your project.
====
