= Technical Tutorials
:page-aliases: introduction.adoc


Welcome to Technical Tutorials, hosted by Jacqui Kane(tjkane@purdue.edu)

Use these tutorials to skill-up before an interview, or as a basis to build your own awesome applications! 
++++
- xref:attachment$1-crud_ejs-tutorial1.pdf[Build A Purdue Pete Scheduled Meetings Reminder Application With Node.js, EJS]
++++

++++
<html>
<h2>Purdue Pete's Meetings Reminder App (Node.js, EJS)</h2>
<p>
Node.js is a cross-platform, open-source JavaScript runtime environment that can run on multiple operating systems, like Windows and macOS. EJS is a templating engine. What's a templateing engine? Software that supports injecting data into HTML, and supporting the dynamic generation of HTML content.
</p>
<p>
In this tutorial, you will see how the EJS templating engine is brought into your Node.js 
application to create dynamic page content, and modularize the code base. You will be 
creating a simple application that shows a list of reminders. That list is rendered using EJS, 
to selectively display items in  a list, and pass values dynamically to the display.
</p>

</html>
++++



++++
<iframe id="reading" style="border:1px solid #666CCC" title="PDF in an i-Frame" src="_attachments/ReactCaseStudy_Interactive_Components.pdf" frameborder="1" scrolling="auto" height="1100" width="850" ></iframe>

++++



