= Technical Tutorials
:page-aliases: introduction.adoc


Welcome to Technical Tutorials, hosted by Jacqui Kane(tjkane@purdue.edu)

Use these tutorials to skill-up before an interview, or as a basis to build your own awesome applications! 


++++
<html>
<h2>Purdue Pete's Meetings Reminder App (Node.js, EJS)</h2>
<p>
Node.js is a cross-platform, open-source JavaScript runtime environment that can run on multiple operating systems, like Windows and macOS. EJS is a templating engine. What's a templateing engine? Software that supports injecting data into HTML, and supporting the dynamic generation of HTML content.
</p>
<p>
In this tutorial, you will see how the EJS templating engine is brought into your Node.js 
application to create dynamic page content, and modularize the code base. You will be 
creating a simple application that shows a list of reminders. That list is rendered using EJS, 
to selectively display items in  a list, and pass values dynamically to the display.
</p>
<a href="../attachments/1-crud_ejs-tutorial1.pdf">Purdue Pete's Meetings App</a>
</html>
++++


++++
<html>
<h2>Purdue Pete's Meetings Reminder App++ (Node.js, EJS.SQLite), Persisting Meeting Data</h2>
<p>
Purdue Pete needs to persist the meeting data, with the help of a database!
</p>
<p>
In the last Node/Express/EJS tutorial, you used dummy data from an array, to represent Purdue Pete's meetings. This data is not persisted, if these were real meetings, you would expect them to come from a central source, like a database. In this tutorial, you will 
-	add support for a relational database, which is the one with tables! We will use SQLite and SQLite3, to build the code base we need for the database connection and query. Remember, a query is how we get data back from a database.
-	apply more Bootstrap styling

</p>
<a href="../attachments/2-crud_ejsTutorialPlusSQL2.pdf">Purdue Pete's Meetings App</a>
</html>
++++


++++
<iframe id="reading" style="border:1px solid #666CCC" title="PDF in an i-Frame" src="_attachments/ReactCaseStudy_Interactive_Components.pdf" frameborder="1" scrolling="auto" height="1100" width="850" ></iframe>

++++
++++
- xref:attachment$1-crud_ejs-tutorial1.pdf[Build A Purdue Pete Scheduled Meetings Reminder Application With Node.js, EJS]
++++





