= Technical Tutorials
:page-aliases: introduction.adoc


Welcome to Technical Tutorials, hosted by Jacqui Kane(tjkane@purdue.edu)

Use these tutorials to skill-up before an interview, or as a basis to build your own awesome applications! 


++++
<html>
<h2>Purdue Pete's Meetings Reminder App (Node.js, EJS), #1 of 3</h2>
<p>
Node.js is a cross-platform, open-source JavaScript runtime environment that can run on multiple operating systems, like Windows and macOS. EJS is a templating engine. What's a templateing engine? Software that supports injecting data into HTML, and supporting the dynamic generation of HTML content.
</p>
<p>
In this tutorial, you will see how the EJS templating engine is brought into your Node.js 
application to create dynamic page content, and modularize the code base. You will be 
creating a simple application that shows a list of reminders. That list is rendered using EJS, 
to selectively display items in  a list, and pass values dynamically to the display.
</p>
<a href="../attachments/1-crud_ejs-tutorial1.pdf">Purdue Pete's Meetings App</a>
</html>
++++


++++
<html>
<h2>Purdue Pete's Meetings Reminder App++ (Node.js, EJS, SQLite), Persisting Meeting Data, #2 of 3</h2>
<p>
Purdue Pete needs to persist the meeting data, with the help of a database!
</p>
<p>
In the last Node/Express/EJS tutorial, you used dummy data from an array, to represent Purdue Pete's meetings. This data is not persisted, if these were real meetings, you would expect them to come from a central source, like a database. In this tutorial, you will 
-	add support for a relational database, which is the one with tables! We will use SQLite and SQLite3, to build the code base we need for the database connection and query. Remember, a query is how we get data back from a database.
-	apply more Bootstrap styling

</p>
<a href="../attachments/2-crud_ejsTutorialPlusSQL2.pdf">Hanging On To The Meetings Data, Purdue Pete's Meetings App With SQLite</a>
</html>
++++


++++
<html>
<h2>Oh CRUD! Purdue Pete's Meetings Reminder App++ (Node.js, EJS, SQLite), Persisting And Manipulating Meeting Data, #3 of 3</h2>
<p>
Purdue Pete can create a new meeting, but what if he decides to cancel the odd meeting, maybe update a time, review some details? There is a special term for this - CRUD, Create, Read, Update, Delete ... meetings from the Meetings Database.
</p>
<p>
In your CRUD project, you are building tutorial 3 on top of tutorial 2, which was built on tutorial 1. Just in case you are starting a new project each time, make sure that you are using the correct imports and middleware to support the HTTP requests and the route handler request and response objects. 

</p>
<p>
A company typically has a requirement to list products and to manage inventory, and that could be services as well as tangible items like coffee or clothing. Business applications revolve around representing and manipulating this data. Can you think of any business that does not concern itself with managing data?
Data represents the company’s offerings, the reason that the business is in operation. Businesses are dynamic - new products or services are added, existing products or services might be removed or modified.
You have an application that reads data from a database, but this data has been seeded by the application – it does not represent a product or service that has been added, because the ability to extend product inventory has not been implemented. You do not have the ability to delete or remove an item that is no longer a part of the business offering. You cannot update an item to reflect new considerations.
In your job as a software developer, you may be tasked with the creation of a CRUD application. A CRUD application is a key building block for software engineers, and concerns data management. 
CRUD is an acronym for
<ul>
<li>Create – the process of adding a product or service</li>
<li>Read – getting the details about a product or service</li>
<li>Update – modifying the details of a product or service</li>
<li>Delete – removing a product or service from the company’s offerings</li>
</ul>

So far, you have the Read covered. Now let’s tackle the other 3!

</p>
<a href="../attachments/3-crud_ejs-CreateUpdate-Delete3.pdf">Hanging On To The Meetings Data, Purdue Pete's Meetings App With SQLite</a>
</html>
++++


++++
<iframe id="reading" style="border:1px solid #666CCC" title="PDF in an i-Frame" src="_attachments/ReactCaseStudy_Interactive_Components.pdf" frameborder="1" scrolling="auto" height="1100" width="850" ></iframe>

++++
++++
- xref:attachment$1-crud_ejs-tutorial1.pdf[Build A Purdue Pete Scheduled Meetings Reminder Application With Node.js, EJS]
++++





