
== Online Meeting “Net-etiquette"

Even before the world widely moved online due to COVID-19, The Data Mine Corporate Partners students met with their Corporate Partner Mentors online via Microsoft Teams because most Corporate Partner Mentors do not live or work near Purdue. For example, Viasat is in California; Sandia is in New Mexico; Microsoft is in Washington 

Your weekly 50-minute meeting with your Corporate Partner Mentor meeting will occur online via Zoom/MS Teams/WebEx (unless your mentor is located on campus – we will notify you if this is the case). 

To create a welcoming online meeting environment, we are proposing the following internet etiquette, or “net-etiquette”. 

•	Call into the meeting at least two minutes early so the meeting can begin promptly. If your meeting is schedule for 3:00 PM, make sure you log in by 2:58 PM. 
•	Always check the time zone of the meeting to the time zone you are in. Meetings will always be scheduled for Eastern Time, which is the time zone Purdue is in. 
•	Turn your web camera on. It is very challenging to gauge body language when you cannot see others. For example, you cannot tell if your teammates are nodding in agreement or confused if you cannot see them. 
•	You should be *actively* attending the meetings: pay attention and stay engaged in the call. Do not be doing other homework or playing on your phone during these calls. 
•	Keep your hands in camera view so that others can see you are engaged and not doing other work. 
•	Find a quiet place to conduct the call. 
•	Mute yourself unless you are speaking. Even if you think you are in a quiet space, there may be background noise that is disruptive to others. 
•	Feel welcome to type your comments or questions into the chat if you feel more comfortable. 
•	If you will be sharing content, make sure it is pulled up on your computer and ready to share. 
    - Tip: if you’re planning to demo new content it can be helpful to create a recording in advance. Live demos can often run into issues. 
•	If this is the first time that you will be using the calling software, please make sure to install all required software well before the first meeting. For example, you may need to install Microsoft Teams.
•	Test your audio connection. The Microsoft Teams app or laptop microphone not working does not excuse you from participating.
•	You can download the Microsoft Teams app on your mobile phone if needed. 
•	Do not dominate any discussion. Give other students the opportunity to join in the discussion.
•	Do not use offensive language. Present ideas appropriately.
•	Always pay attention when the mentors and other students are speaking.  You should not do email or other tasks during your team meeting.  By focusing on the meeting, you will be more engaged, you will have more fun, and you will be better able to support your teammates and perform your own work as well.  There is plenty of time to be distracted on the internet when you are not in your team meeting.  Give it your best effort and support your team!
