= Sprint #1: August 23 - September 5, 2021 

== About The Data Mine 

Click on the xref:introduction.adoc[Introduction] page to learn more about The Data Mine and Corporate Partners. 

== Where do I go for class?

STAT 190/290/390 The Data Mine & STAT 598 Data Science in Industry is a 3 credit hour class. You will meet for ~3 hours per week as your "class time". It is also expected that you spend 5-7 hours per week on this course outside of your class time. Total hours on this course is ~8-10 hours per week. 

*50 minute lecture*

This team meeting will occur *online via MS Teams* unless you are notified that your mentor is on campus and will meet you in person. You will receive a calendar invite before the first day of term with the meeting link. If you do not have the invite, email datamine@purdue.edu to request the invite be forwarded to you. 

*1 hr 50 minute lab*

This student meeting will occur *in person* in Burton D. Morgan Center for Entrepreneurship (MRGN) located at 1201 W. State St., West Lafayette, IN 47906

*document missing* 

Click on this document to find your meeting times and locations, including the specific room in MRGN for your lab. If you need the Microsoft Teams link for your online meeting, please email datamine@purdue.edu with "Meeting link needed" as the subject. 

*Map*

*map missing*
Click on this campus map to see where Morgan (MRGN) is located. The address is 1201 W. State St., West Lafayette, IN 47906. It is located on the southwest corner of State St. and Jischke Dr. 


Click on this document to find your meeting times and locations, including the specific room in MRGN for your lab. If you need the Microsoft Teams link for your online meeting, please email datamine@purdue.edu with "Meeting link needed" as the subject. 


== Syllabus Quiz 

While all teams will work on different projects and many mentors will provide a project syllabus, the below syllabus includes information that all Data Mine Corporate Partner students need to know. Please read the syllabus and then take the quiz. You may have the syllabus open while you take the quiz. 

If you need to refer to the syllabus, please refer to the syllabus in this book (as opposed to looking at a downloaded copy). The syllabus below will always be the most up to date. The last update timestamp is located in the bottom footer.

Click on xref:syllabus_fall2021.adoc[Syllabus] on the left bar to view the syllabus. 

Login to link:https://purdue.brightspace.com/[Brightspace] to take the syllabus quiz. You make take the quiz up to 3 times and your highest score will count. 

== Agile Training 
Click on xref:agile-training.adoc[Agile Training] on the left bar to view the Agile resources. 

During your first lab session (or second week if your mentor is visiting the first week), you will be using Lego's to learn the Agile approach to project management. The Data Mine data scientists and your TA will be facilitating this Lego lab. 

We encourage you to review this link:https://thisiszone.medium.com/using-lego-to-show-the-advantages-of-an-agile-approach-to-software-development-3eda6e5c2114[article]. 

The Data Mine Corporate Partners will implement Agile methods into our project management. Agile is very popular in industry and the majority of our Corporate Partners use it. Now is the best time to practice it while you are a student. 


== Sprint #1 Report 


*When:* Due Sunday, Spetember 5 at 11:59 PM ET. Late work will not be accepted. 

*What:* Download this file and answer the questions in complete sentences. 

*Where:* submit to link:https://www.gradescope.com/[Gradescope] as a *PDF* file. It is important to upload your document as a PDF. You will be deducted points if you submit any other file than a PDF.

