= CSV

== Overview
CSV stands for "comma-separated values". CSV files is one of the most common ways that tabular data is stored and shared, and you may have even interacted with a CSV file before.

Here is an example of a CSV file. True to its name, the value are separated by commas.

[source]
----
age, weight, height
20, 165, 70
----

Note that the first row and the second row of the file have the same number of lines. This is not always the case. However, data that is represented in a tabular format will typically have this property.

== CSV Files and `R`/`Python`
There will by times where you might want to analyze data stored in a CSV file using a tool such as `R`. Luckily, it is easy to load data in this format into an `data.frame.` This can be done using the following command:

[source]
----
my_data <- read.csv("my_file.csv")
----

After a `data.frame` has been manipulated, it is a good idea to ensure those changes are saved by writing the object to disk. Using `R`, this is easy!

[source]
----
# Changes were made to the `my_data` data.frame, and the new data.frame is called `my_new_data`.
write.csv(my_new_data, "my_new_path.csv")
----

In Python, the `pandas` module can be used to read the data into a `pandas DataFrame` object.

[source]
----
import pandas as pd

my_data = pd.read_csv("my_file.csv")
----

When you want to write a `pandas DataFrame` to a CSV file, it can be done so in the following way:

[source]
----
# Changes were made to the `my_data` DataFrame, and the new DataFrame is called `my_new_data`.
my_new_data.to_csv("my_new_file.csv")
----


== Pros and Cons
Data is represented and shared in CSV format for a number of reasons. First, it is very easy for a user to open the file and gain an understanding of what is going on. CSV files open natively in many applications such as Excel, Google Sheets and even if Jupyter. Along with ease of viewing, many applications support data import and export of CSV files. For these reasons and many more, data represented in CSV format is very very common.

Despite the benefits that CSV files offer, there are some shortcomings. One such short coming is storage size. CSV files are uncompressed (compared to their compressed counterparts such as `.pickle` and `.parquet` files). This means that a CSV file containing the same information as a `.pickle` file takes up more disk space. As a result, it may take longer to read-from and write-to CSV files.

== Summary
When working with data, it is common to use CSV files in a variety of ways. This file type is comfortable for many, and could be considerd industry defacto even for non-technical data consumers. As you step into the world of data science, be ready to consume, manipulate and produce CSV files regularly, BUT also be open to trying other, more efficient manners of storing information.
