= XML

== Overview

[IMPORTANT]
====
It is _highly_ recommended to read the xref:html.adoc[HTML] section before reading this section. HTML and XML have a few similar concepts and terms that will make this section easier to understand.
====

XML stands for Extensible Markup Language. XML and HTML appear and sound very similar but have different goals. Whereas HTML was designed to **display** data, XML was designed to **store** data.

Like HTML, XML still has **start tags**, **content**, and **end tags**, however, rather than using a finite set of "legal" or "official" tags, XML tags are defined and created by the user. What does this mean? It means the following is perfectly legal XML.

[source,xml]
----
<exam>
  <question>
    <text>What is red?</text>
    <solution>A color.</solution>
    <points>2</points>
  </question>
  <question>
    <text>What is a square?</text>
    <solution>A shape.</solution>
    <points>1</points>
  </question>
</exam>
----

Rather than opening that content in a web browser and expecting it to **display** data, we would instead write custom software to send, receive, store, display, or do _something_ with the data.

== XPath expressions

XPath Expressions are expressions created to programmatically select https://www.w3schools.com/xml/dom_nodes.asp[nodes or node-sets] from an XML document.

The following table (from https://www.w3schools.com/xml/xpath_syntax.asp[w3schools]) shows some of the most useful expressions that can be used to select nodes programmatically.

[%header,format=csv,stripes=even]
|===
include::example$expressions.csv[]
|===

=== Predicates

A predicate is a way to filter a node-set by evaluating the expression contained within a set of square brackets `[]`. For example, let's say you wanted to get all of the questions that have points > 1. Doing this using predicates is easy.

[source,xml]
----
<exam>
  <question>
    <text>What is red?</text>
    <solution>A color.</solution>
    <points>2</points>
  </question>
  <question>
    <text>What is a square?</text>
    <solution>A shape.</solution>
    <points>1</points>
  </question>
</exam>
----

The XPath expression to fetch the questions that are worth more than 1 point is the following.

[source,xml]
----
//question[points > 1]
----


=== Operators

In order to make comparisons, we need operators. The following is a list of XPath operators from https://www.w3schools.com/xml/xpath_operators.asp[here].

[%header,format=dsv,stripes=even,separator=;]
|===
include::example$operators.csv[]
|===


=== Functions

XPath functions are an easy way to filter data with more control. You can find a list of functions https://developer.mozilla.org/en-US/docs/Web/XPath/Functions[here]. Of particular use are the `contains` and `translate` functions. `contains` allows you to see if the first argument string contains the second argument string. It is particularly useful to see if a class or attribute contains some substring. `translate` allows you to, among other things, change the case (whether the text is capitalized or not) of some text prior to using the `contains` function.


=== Examples

[NOTE]
====
While the following examples are useful, to see examples using XPath expressions in R or Python, please check out the following links.

* xref:book:r:xpath-expressions.adoc[XPath expressions in R]
* xref:book:python:xpath-expressions.adoc[XPath expressions in Python]
====

The following are examples using the following XML document. You can use https://extendsclass.com/xpath-tester.html[this tool] to test your XPath expressions.

[source,xml]
----
<html>
    <head>
        <title>My Title</title>
    </head>
    <body>
        <div>
            <div class="abc123 sktoe-sldjkt dkjfg3-dlgsk">
                <div class="glkjr-slkd dkgj-0 dklfgj-00">
                    <a class="slkdg43lk dlks" href="https://example.com/123456">
                    </a>
                </div>
            </div>
            <div>
                <div class="ldskfg4">
                    <span class="slktjoe" aria-label="123 comments, 43 Retweets, 4000 likes">Love it.</span>
                </div>
            </div>
            <div data-amount="12">13</div>
        </div>
        <div>
            <div class="abc123 sktoe-sls dkjfg-dlgsk">
                <div class="glkj-slkd dkgj-0 dklfj-00">
                    <a class="slkd3lk dls" href="https://example.com/123456">
                    </a>
                </div>
            </div>
            <div>
                <div class="ldg4">
                    <span class="sktjoe" aria-label="1000 comments, 455 Retweets, 40000 likes">Love it.</span>
                </div>
            </div>
            <div data-amount="122">133</div>
        </div>
    </body>
</html>
----

==== Write an XPath expression to get the "title" element.

.Solution
====
[source, xml]
----
//title
----
====

==== Write an XPath expression to get the content of the "title" element.

.Solution
====
[source, xml]
----
//title/text
----
====

==== Write an XPath expression to get every "div" element in the document.

.Solution
====
[source, xml]
----
//div
----
====

==== Write an XPath expression to get every "div" element in the document with the "class" attribute having a value of "ldskfg4".

.Solution
====
[source, xml]
----
//div[@class="ldskfg4"]
----
====

==== Write an XPath expression to get every "div" element where the string "abc123" is in the "class" attribute's value (as a substring).

.Solution
====
[source, xml]
----
//div[contains(@class, 'abc123')]
----
====

==== Write an XPath expression to get every "div" element with an "aria-label" attribute.

.Solution
====
[source, xml]
----
//div[@aria-label]
----
====

== GPX

== Resources

https://www.w3schools.com/xml/xml_xpath.asp[XPath Tutorial]

A w3schools tutorial on XPath expressions. A nice 1 page summary.

https://gist.github.com/LeCoupa/8c305ec8c713aad07b14[XPath Expression Cheatsheet]

A simple, but very thorough cheatsheet to recall XPath expressions.

https://extendsclass.com/xpath-tester.html[XPath Tester]

A great, online tool for testing XPath expressions.