= TDM 32100: Project 16 - NOAA Monthly Climate Data Part 2

== Project Objectives

In this project, you'll explore and model monthly climate trends in Indianapolis using an Augmented Regressive model and SARIMAX, a type of ARIMA model that can handle both seasonal patterns. 

.Learning Objectives
****
- Understand the structure and purpose of time series data in climate forecasting.
- Visualize long-term patterns and identify trends and seasonality in temperature data.
- Test for stationarity using the Augmented Dickey-Fuller test and interpret results.
- Apply differencing to transform non-stationary series into stationary ones.
- Train a SARIMAX model using both endogenous and exogenous variables.
- Evaluate model performance using Mean Absolute Error (MAE) on train and test sets.
- Generate and interpret future forecasts using the trained model.
- Communicate findings through visualizations and a well-documented workflow.
****

== Dataset
- `/anvil/projects/tdm/data/noaa_timeseries2/monthly_avg_df_NOAA.csv`


== Questions

=== Question 1 (2 points)

.Deliverables
====
- 
====

=== Question 2 (2 points)

.Deliverables
====
- 
====

=== Question 3 (2 points)

.Deliverables
====
- 
====

=== Question 4 (2 points)

.Deliverables
====
- 
====

=== Question 5 (2 points)


.Deliverables
====
- 
====

== Submitting your Work

Once you have completed the questions, save your Jupyter notebook. You can then download the notebook and submit it to Gradescope.

.Items to submit
====
- firstname_lastname_project1.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====