= How to contribute

== AsciiDoc

This book is written using https://asciidoc.org/[AsciiDoc]. AsciiDoc is an open and powerful format for writing notes, text documents, books, etc. It is easy to write technical documentation in AsciiDoc, and quickly convert the text to various mediums like websites, ebooks, pdfs, etc.

Below are a variety of AsciiDoc examples from https://powerman.name/doc/asciidoc[powerman]. To see how content is rendered, compare https://raw.githubusercontent.com/TheDataMine/the-examples-book/staging/content/modules/ROOT/pages/how-to-contribute.adoc[the adoc file for this page], to it's output below.

== Headers

== Level 1
Text.

=== Level 2
Text.

==== Level 3
Text.

===== Level 4
Text.

====== Level 5
Text.

======= Level 6
Text.

== Paragraphs

.Optional Title

Usual
paragraph.

.Optional Title

	Literal paragraph.
		Must be indented

.Optional Title

[source,python]
list = ['first', 'second', 'third',]

Not code in the next paragraph.

.Optional Title
[NOTE]
This is an example of a single-paragraph note.

[TIP]
This is a tip.

[IMPORTANT]
This is important.

[WARNING]
This is a warning.

[CAUTION]
This is a caution note.

== Blocks

.Optional Title
----
*Listing* Block

Use for code of file listings
----

.Optional Title
[source,python]
----
# Source code block

# Use for chunks of code
import pandas as pd

myDF = pd.read_csv("myFile.csv")
----

.Optional Title
****
*Sidebar Block*

Use for sidebar notes.
****

.Optional Title
====
*Example* Block

Use for examples

The default caption "Example:" can be changed using [caption="Custom: "] before the example block.
====

.Optional Title
[NOTE]
====
*Note* Block

Use for multi-paragraph notes.
====

////
*Comment* Block

Use for comments that do not appear.
////

++++
*Passthrough* Block

<p>
Use for backend specific markup like:

<table border="1">
	<tr>
		<td>1</td>
		<td>2</td>
	</tr>
</table>

</p>
++++

.Optional Title
....
*Literal* Block

Use when literal paragraph (indented) like
	1. First
	2. Second

is incorrectly processed as list.
....

.Optional Title
[quote, cite author, cite source]
____
*Quote* Block

Use to cite somebody.
____

== Text

forced +
line break

*bold text*

_italic text_

+monospaced text+

``doubel quoted''

`single quoted'

text^super^

text~sub~

A command: `echo "some command"`

+monospaced and *bold*+

`passthrough *bold*`

Directory paths: '/class/datamine/data', '/class/datamine/apps'

[red]#color text red#

[blue]#color text blue#

[yellow-background]#highlight text yellow#

[green-background]#highlight text green#

[red yellow-background]#highlight red text yellow#

[big]#large text#

[red yellow-background]*highlight red, bolded text yellow*

[red yellow-background]_highlight red, italicized text yellow_

Modify single characters: n__o__**r**++m++[red]##a##[blue yellow-background]**l**

// Comment -- invisible

Special symbols: (C) (R) (TM) -- ... -> <- => <= &#182;

Escape characters:
\_italic_, +++_italic_+++, t\__e__st, +++t__e__st+++, +++<b>bold</b>+++, $$<b>normal</b>$$, \&#182;, \`not single quoted', \``not double quoted''

== Links

[[custom-anchor-link-01]]
Text for the custom anchor link `custom-anchor-link-01`.

anchor:custom-anchor-link-02[]
Text for the custom anchor link `custom-anchor-link-02`.

<<custom-anchor-link-01>>

<<custom-anchor-link-01, My Anchor Link 1>>

xref:custom-anchor-link-02[]

xref:custom-anchor-link-02[My Anchor Link 2]

https://google.com[Link to Google]

== Images

== Lists

== Tables
