= 300/400 Seminar Homework Submission Steps

All of the homeworks are in a Jupyter notebook and contain the instructions and links to materials needed to be successful for that homework. Each week we will release a folder that contains the notebook (as well as supplementary data or images). The general process to retrieve and work on homeworks is:

0. Copy the Helper Notebook
1. Copy the Homework
2. Do the Homework
3. Submit to Gradescope

== 0. Copy the Helper Notebook (Do This Once)

We've provided a notebook with the scripts needed to copy the homeworks on Anvil. You will only need to do this once, at the beginning of the semester. Run the command below in a terminal on Anvil.

[source,bash]
----
cp -r /anvil/projects/tdm/seminar/helper.ipynb $HOME/seminar/
----

== 1. Copy The Homework

Each week, open the helper notebook and go to the respective week and run that cell to retrieve that weeks homework materials. **You can run it as many times as you like, but realize that it may overwrite any progress you've made on notebooks it overwrites- be careful!!**

== 2. Finish the Homework

From here, you can begin working on the homework by opening it up at the file explorer window in Jupyter Lab (inside the folder titled `seminar`).

== 3. Submit to Gradescope

Go to Gradescope and submit the code like usual - the rules at https://the-examples-book.com/projects/current-projects/submissions apply!

Part of these rules include uploading both the homework with answers in a .ipynb, as well as (for these homeworks) the corresponding Python code in a .py script. You can manually strip the Python code from the notebook and upload that; alternatively there is a way to convert a .ipynb file directly to a .py for upload, but you will have to do it on your local machine (not on Anvil). See here for details: https://the-examples-book.com/starter-guides/tools-and-standards/jupyter#i-want-to-steal-all-the-code-from-the-notebook-without-the-data-mines-comments