= Spring 2022 Announcements 


*Check this page frequently for announcements about the course. Announcements will also be emailed out to students*


== (April 13) Symposium Preparation

 
To prepare for the symposium that is ONE WEEK FROM TODAY, please review the section xref:symposium.adoc#information-to-know-for-the-day-of-the-symposium-wednesday-april-20-2022[“Information to know for the day of the symposium”].
 
All students are expected to actively participate in their team’s Zoom room for at least 1 hour from 2:30 – 4:30 PM on Wednesday, April 20, 2022. Ideally, we'd love for you to participate for the full two hours if your schedule allows.
 
If you have a University conflict (class or TA duties) during the full two hour session, please view this xref:symposium.adoc#alternative-assignment-for-symposium-attendance[alternative assignment].

== (March 7) Symposium reminders
 
We are halfway through the spring 2022 semester, only 13 days away from the first day of spring, and less than a week away from spring break! Here are a few updates. 
 
*Symposium*

* Poster and video drafts due Sunday, March 13
* Where should we submit the drafts? 
** Students do not need to officially submit anything for the draft. Only the TA will make 1 submission per team. 
* All details regarding the poster and symposium are xref:symposium.adoc[listed here]. *Please review this page as it contains lots of helpful information!*
* We strongly encourage creativity on the posters and videos! Please do not feel tied to the poster template we sent out or a standard PowerPoint recorded video. Review the posters and videos from last year. The link:https://datamine.purdue.edu/symposium/merck/2021.html[video from Merck Biometrics team] last year was very creative and unique. We also encourage demonstrations of interactive apps you have developed.  
* What can we include on our poster?
** Remember, many projects are under NDA. The posters and videos will be shared *publicly*. Discuss with your Corporate Partner Mentors what parts of the projects are allowed to be shared publicly. This is an important conversation because it will help you navigate future conversations about your project including interviews and grad school applications. 
* #1 tip for a successful poster? Reduce text and focus on images. The poster is not a large paper! 
* #1 tip for a success video? Think of your video as the movie trailer, not the movie. It does not need to include all of your work from this academic year. 
* A Purdue branded PowerPoint template link:https://the-examples-book.com/crp/_attachments/Purdue-branded-powerpoint-template-reduced.pptx[is listed here in the book] if you would like to use this for the video. 
 
*Sprint #5*

Sprint #5 is a week longer due to spring break. It will end on March 27. However, the poster and video drafts are due in the middle of the sprint by Sunday, March 13 before you leave for spring break. See above for details. 

Have a good week and stay safe over spring break! 

== (February 28) A few reminders....

A few reminders to start off your 8th week of spring semester: 

1. Sprint report #4 is due this Sunday, March 6. 
2. Start working on your Symposium poster and video. Drafts are due March 13. https://the-examples-book.com/crp/symposium
3. Apply to be a student in The Data Mine for next year fall 2022 - spring 2023 (if you have not applied already) https://datamine.purdue.edu/apply/
4. Apply to be a paid TA for Seminar or Corporate Partners for next year https://purdue.ca1.qualtrics.com/jfe/form/SV_1YBgySxIEmGkJWm
Have a great week! 
 

== (February 2) Inclement Weather Procedures for The Data Mine

We want to make you aware of our plans *if* Purdue calls for an inclement weather day.

Team meetings will continue as normal since these are already scheduled for online. No changes needed. 
Labs will continue as scheduled with an *online* format only. Students should use the same MS Teams meeting link for lab as previously sent out for the 50-minute team meetings. The link will still work even if it is a different day. 
Should there be inclement weather, Data Mine students are still expected to attend team meetings and labs in an *online* format. 

Please let us know if you have any questions. We will keep you posted via email with any additional updates. Stay safe and warm!

== (January 11) COVID-19 Protocols

https://protect.purdue.edu/protect-purdue-health-center/quarantine-isolation-resources/

These protocols were recently updated, and we want to make sure you are aware of them. Please review these updated protocols for quarantine and isolation before attending any in-person classes. 

YOU SHOULD NOT BE ATTENDING IN-PERSON CLASS IF YOU HAVE *ANY* SYMPTOMS, EVEN IF YOU TEST NEGATIVE. 

You can call Protect Purdue Health Center for any questions about your specific situation. 


== (January 10) Lab locations & Meeting Times

All teams have in-person labs (1 hour 50 minutes) regardless of what your registration says on UniTime. 

Lab locations are either in MRGN or HILL. The complete list of times and locations are available in the xref:spring2022/locations.adoc[Team Meeting Locations] page.

== (January 3) Welcome to The Data Mine Corporate Partners!

Hello, and welcome to The Data Mine Corporate Partners! (STAT 190/290/390 The Data Mine & STAT 598 Data Science in Industry).

To get started, please click on "Sprint #1" on the left hand column. It includes the syllabus, where to go for your class time, and your first assignments. 

If you have questions, please email datamine@purdue.edu and include "Corporate Partners question: [your team name]" in the subject line to help you get the fastest response. 

We look forward to working with you this semester! 