= GitHub Desktop

Microsoft's GitHub is a popular platform for `git` repository hosting and provides a myriad of related developer tools. https://desktop.github.com/[GitHub Desktop] is a graphical user interface for `git`-related work. While it is specifically designed to be used with GitHub, it is possible to use with some other providers. For simplicity, when anything version control related is mentioned in this book, guidance will be demonstrated primarily using GitHub Desktop in combination with GitHub. 

== Terminology

It is very common to mix `git` terminology with terminology that is platform-specific. The following are very common terminologies that are important to understand. These are terms that are specific to the platforms (GitHub, GitLab, etc.), and aren't part of `git`.

=== Issue

https://docs.github.com/en/github/getting-started-with-github/quickstart/github-glossary#issue[The GitHub glossary] does an excellent job describing what an issue is. 

[quote, , https://docs.github.com/en/github/getting-started-with-github/quickstart/github-glossary#issue[GitHub glossary]]
____
Issues are suggested improvements, tasks or questions related to the repository. Issues can be created by anyone (for public repositories), and are moderated by repository collaborators. Each issue contains its own discussion thread. You can also categorize an issue with labels and assign it to someone.
____

Issues are an excellent and central way to organize tasks for a project.

=== Pull Request


=== Release

== Resources