= Mapping Projects to Learning Outcomes, and Assessment of Learning Outcomes

Project 1 -- Introduction to High Performance Computing

Project 2 -- Assessing Online Data and Scraping Data from the Web

Project 3 -- Introduction to Large Language Models

Project 4 -- Retrieval-Augmented Generation (RAG) with LLMs

Project 5 -- Fine Tuning Large Language Models

Project 6 -- Introduction to Agent-Based Modeling

Project 7 -- Building a Single-Agent Model

Project 8 -- Introduction to AI Tools for Image Processing

Project 9 -- Using AI to Implement Image Processing

Project 10 -- Introduction to Containerization and APIs

Project 11 -- Container Builds and API Connectivity

Project 12 -- Introduction to Streaming Databases

Project 13 -- Implementing Streaming Databases with Spark SQL

Project 14 -- Reflections and Summative Assessment



SOCIO-EMOTIONAL LEARNING
Emotional Regulation
ER5	Students will manage emotions effectively to foster healthy relationships and achieve goals.

Social Skills
SS2	Students will identify developmental norms, identify general social skills that apply to various situations, and identify expectations in various social situations.
SS3	Students will behave in a socially acceptable way relative to the situation, people involved, and timing.
SS4	Students will initiate conversations appropriately, sustain conversations or interaction appropriately, demonstrate active listening, close a conversation or end an interaction appropriately, interpret non-verbal cues appropriately, and communicate information effectively when making a presentation.
SS5	Students will shift behavior and language relative to the situation, people involved, and timing.
SS6	Students will identify the problem(s), identify strategies for resolving the conflict, select a strategy appropriate to the situation and relationship, implement the appropriate strategy, and enlist support when needed.
SS7	Students will demonstrate the ability to see a situation from a view other than own, empathize with a view other than own, and alter actions toward a person, situation, or idea in response to another point of view.
SS8	Students will identify different levels of intimacy with others, identify how different relationships require different levels and types of sharing, and recognize and establish boundaries based on different types of relationships.
SS9	Students will work and communicate with a partner to accomplish a task, work and communicate with several other people to complete a task, use compromise to advance larger goals, and divide tasks fairly and effectively, taking into account individual strengths, weaknesses, and availability.

Self-Care
SC2	Students will set goals that are: specific, measurable, action-oriented, realistic, and timely and review progress towards goals by evaluating and revising.

Executive Function
EF1	Students will transition between activities or situations, move freely between aspects of a problem, or think flexibly around problem solving.
EF2	Students will begin an activity, begin generating ideas.
EF4	Students will develop appropriate sequence of steps to carry out a task or action, implement appropriate sequence of steps to carry out a task or action, manage time effectively, and maintain a system for holding and retrieving information – applying memory strengths or compensatory strategies.  
EF5	Students will recognize impulsive behavior, control impulses and behavior, and modulate behavior based on time and context.
EF6	Students will accurately label strengths and weaknesses, identify impact of personal behavior on self and others, label when things break down, and recognize need for problem solving.

EXPERIENTIAL EDUCATION
Authenticity and Purposeful Application
APA1: Students will engage in purposeful application of their learning through collaborative projects based on real-world contexts.
APA2: Students will build awareness of their own learning needs and will intentionally strive to move beyond their comfort zone.

Responsible Decision-Making
RDM2	Students will demonstrate agency and personal choice through their engagement in activities.
RDM3	Students will evaluate and reflect on their decision-making process.

Critical Reflection
CR1	Students will name and challenge assumptions.
CR2	Students will evaluate the outcomes of their decisions and actions and apply these learnings to future endeavors.
CR3	Students will embrace challenge and failure to build resiliency and a growth mindset.

Self and Social Awareness
SASA2	Students will examine their strengths, areas of growth, biases, and positionality and how they impact the group.
SASA3	Students will practice strategies that promote empathy, respect, empowerment, and relationship-building.
SASA4	Students will value and engage the variety of opinion and identity within groups.

BELONGING AND COMMUNITY
Perspectives
P1	Students will express comfort with people who are both similar to and different from them and engage respectfully with all people.

TECHNOLOGY, RESEARCH, INFORMATION, AND MEDIA LITERACIES
Empowered Learner
EL1	Students will articulate and set personal learning goals, develop strategies leveraging technology to achieve them, and reflect on the learning process itself to improve learning outcomes.
EL4	Students will understand the fundamental concepts of technology operations, demonstrate the ability to choose, use, and troubleshoot current technologies, and be able to transfer their knowledge to explore emerging technologies.

Digital Citizen
DC1	Students will cultivate and manage their digital identity and reputation and will be aware of the permanence of their actions in the digital world. 
DC2	Students will engage in positive, safe, legal, and ethical behavior when using technology, including social interactions online or when using networked devices. 
DC3	 Students will demonstrate an understanding of and respect for the rights and obligations of using and sharing intellectual property.
DC4	Students will manage their personal data to maintain digital privacy and security and are aware of data-collection technology used to track their navigation online.

Knowledge Constructor
KC2	Students will evaluate the accuracy, perspective, credibility, and relevance of information, media, data, or other resources.
KC4	Students will build knowledge by actively exploring real-world issues and problems, developing ideas and theories, and pursuing answers and solutions.

Computational Thinker
CT1	Students will formulate problem definitions suited for technology-assisted methods such as data analysis, abstract models, and algorithmic thinking in exploring and finding solutions.
CT2	Students will collect data or identify relevant data sets, use digital tools to analyze them, and represent data in various ways to facilitate problem-solving and decision-making. 
CT3	Students will break problems into component parts, extract key information, and develop descriptive models to understand complex systems or facilitate problem-solving.

Creative Communicator
CC1	Students will choose the appropriate platforms and tools for meeting the desired objectives of their creation or communication.
CC3	Students will communicate complex ideas clearly and effectively by creating or using a variety of digital objects such as visualizations, models, or simulations.
CC4	Students will publish or present content that customizes the message and medium for their intended audiences.

Global Collaborator
GC2	Students will use collaborative technologies to work with others, including peers, experts, or community members, to examine issues and problems from multiple viewpoints.
GC3	Students will contribute constructively to project teams, assuming various roles and responsibilities to work effectively toward a common goal.
GC4	Students will explore local and global issues and use collaborative technologies to work with others to investigate solutions.




. *Identify a line of inquiry that requires information, including formulating questions and determining the scope of the investigation.* In each of the 14 weekly projects, the scope is described at a high level at the very top of the project. Students are expected to tie their analysis on the individual weekly questions back to the stated scope. As an example of the stated scope in a project: Understanding how to use Pandas and be able to develop functions allows for a systematic approach to analyzing data. In this project, students will already be familiar with Pandas but will not (yet) know at the outset how to "develop functions" and take a "systematic approach" to solving the questions. Students are expected to comment on each question about how their "line of inquiry" and "formulation of the question" ties back to the stated scope of the project. As the seminar progresses past the first few weeks, and the students are being asked to tackle more complex problems, they need to identify which Python, SQL, R, and UNIX tools to use, and which statements and queries to run (this is "formulating the questions"), in order to get to analyze the data, derive the results, and summary the results in writing and visualizations ("determining the scope of the investigation").
. *Locate information using effective search strategies and relevant information sources.* The Data Mine seminar progresses by increasing the complexity of the problems. The students are being asked to solve complex problems using data science tools. Students need to "locate information" within technical documentation, API documentation, online manuals, online discussions such as Stack Overflow, etc. Within these online resources, they need to determine the "relevant information sources" and apply these sources to solve the data analysis problem at hand. They need to understand the context, motivation, technical notation, nomenclature of the tools, etc. We enable students to practice this skill on every weekly project during the semester, and we provide additional resources, such as Piazza (an online discussion platform to interact with peers, teaching assistants, and the instructor), office hours throughout the week, and attending in-person or virtual seminar, for interaction directly with the instructor.
. *Evaluate the credibility of information. The students work together this objective in several ways.* They need evaluate and analyze the "credibility of information" and data from a wide array of resources, e.g., from the federal government, from Kaggle, from online repositories and archives, etc. Each project during the semester focuses attention on a large data repository, and the students need to understand the credible data, the missing data, the inaccurate data, the data that are outliers, etc. Some of the projects for students involve data cleansing efforts, data imputation, data standardization, etc. Students also need to validate, verify, determine any missing data, understand variables, correlation, contextual information, and produce models and data visualizations from the data under consideration.
. *Synthesize and organize information from different sources in order to communicate.* This is a key aspect of The Data Mine. In many of the student projects, they need to assimilate geospatial data, categorical and numerical data, textual data, and visualizations, in order to have a comprehensive data analysis of a system or a model. The students can use help from Piazza, office hours, the videos from the instructor and seminar live sessions to synthesize and organize the information they are learning about, in each project. The students often need to also understand many different types of tools and aspects of data analysis, sometimes in the same project, e.g., APIs, data dictionaries, functions, concepts from software engineering such as scoping, encapsulation, containerization, and concepts from spatial and temporal analysis. Synthesizing many "different sources" to derive and "communicate" the analysis is a key aspect of the projects.
. *Attribute original ideas of others through proper citing, referencing, paraphrasing, summarizing, and quoting.* In every project, students need to use "citations to sources" (online and written), "referencing" forums and blogs where their cutting-edge concepts are "documented", proper methods of "quotation" and "citation", documentation of any teamwork, etc. The students have a template for their project submissions in which they are required to provide the proper citation of any sources, collaborations, reference materials, etc., in each and every project that they submit every week.
. *Recognize relevant cultural and other contextual factors when using information.* Students weekly project include data and information on data about (all types of genders), political data, geospatial questions, online forums and rating schema, textual data, information about books, music, online repositories, etc. Students need to understand not only the data analysis but also the "context" in which the data is provided, the data sources, the potential usage of the analysis and its "cultural" implications, etc. Students also complete professional development, attending several professional development and outside-the-classroom events each semester. The meet with alumni, business professionals, data practitioners, data engineers, managers, scientists from national labs, etc. They attend events about the "culture related to data science", and "multicultural events". Students are required to respond in writing to every such event, and their writing is graded and incorporated into the grades for the course.
. *Observe ethical and legal guidelines and requirements for the use of published, confidential, and/or proprietary information.* Students complete an academic integrity quiz at the beginning of each semester that sets the stage of these "ethical and legal guidelines and requirements". They have documentation about proper data handling and data management techniques. They learn about the context of data usage, including (for instance) copyrights, the difference between open source and proprietary data, different types of software licenses, the need for confidentiality with Corporate Partners projects, etc.

== Assessment of Foundational Learning Outcome (FLO) = Information Literacy

Note: Please review the current university catalog for The Data Mine (TDM) course approvals for meeting a Foundational Learning Outcome

. *Assessment method for this course.* Students are assigned a weekly project that usually includes a data set and then questions about the data set that engage the student in experiential learning. Each week, these projects are graded by teaching assistants based on solutions provided.
. *Identify a line of inquiry that requires information, including formulating questions and determining the scope of the investigation.* Students are assigned a weekly project that usually includes a data set and then questions about the data set that engage the student in experiential learning. Each week, these projects are graded by teaching assistants based on solutions provided. Students identify which R and Python statements and queries to run (this is formulating the questions), in order to get to the results they think they are looking for (determining the scope of the investigation).
. *Locate information using effective search strategies and relevant information sources.* Students are assigned a weekly project that usually includes a data set and then questions about the data set that engage the student in experiential learning. Each week, these projects are graded by teaching assistants based on solutions provided. The students are being asked to solve complex problems using data science tools. They need to figure out what they are looking to figure out, and to do that they need to figure out what to ask.
. *Evaluate the credibility of information. Students are assigned a weekly project that usually includes a data set and then questions about the data set that engage the student in experiential learning.* Each week, these projects are graded by teaching assistants based on solutions provided. Some of the projects that students complete in the course involve data cleansing efforts including validation, verification, missing data, and modeling and students must evaluate the credibility as they move through the project.
. *Synthesize and organize information from different sources in order to communicate.* Students are assigned a weekly project that usually includes a data set and then questions about the data set that engage the student in experiential learning. Each week, these projects are graded by teaching assistants based on solutions provided. Information on how to complete the projects is learned through many sources and student utilize an experiential learning model.
. *Attribute original ideas of others through proper citing, referencing, paraphrasing, summarizing, and quoting.* Students are assigned a weekly project that usually includes a data set and then questions about the data set that engage the student in experiential learning. Each week, these projects are graded by teaching assistants based on solutions provided set and then questions about the data set that engage the student in experiential learning. At the beginning of each project there is a question regarding citations for the project.
. *Recognize relevant cultural and other contextual factors when using information.* Students are assigned a weekly project that usually includes a data set and then questions about the data set that engage the student in experiential learning. Each week, these projects are graded by teaching assistants based on solutions provided. For professional development event assessment – students are required to attend three approved events and then write a guided summary of the event.
. *Observe ethical and legal guidelines and requirements for the use of published, confidential, and/or proprietary information.* Students complete an academic integrity quiz at the beginning of each semester, and they are also graded on their proper documentation and usage of data throughout the semester, on every weekly project.

