= Summer 2026 Syllabus - TDM 19000

== Course Information 

[%header,format=csv,stripes=even]
|===
Course Number and Title, CRN
TDM 19000 - Data Analysis and Applications, 11781
|===

*Course credit hours:* 
2 credit hours

*Prerequisites:*
TDM 19000 is an introductory course, with introduction to data science tools and methodologies.  Students will learn about large language models, agent-based (agentic) models, image processing, containers, APIs, etc.

=== Course Web Pages

- link:https://the-examples-book.com/projects/summer2026/syllabus[*Syllabus*] - All information will be posted within these pages!
- link:https://www.gradescope.com/[*Gradescope*] - All solutions to questions will be submitted on Gradescope
- link:https://purdue.brightspace.com/[*Brightspace*] - Grades will be posted in Brightspace.
- link:https://ondemand.anvil.rcac.purdue.edu/[*Jupyter Lab via the On Demand Gateway on Anvil*]
- link:https://notebook.anvilcloud.rcac.purdue.edu/[*Jupyter Lab via the Notebook Portal on Anvil*]

=== Meeting Times 
There are three course meetings per week, on Mondays, Tuesdays, and Wednesdays, from 2:15 PM to 4:50 PM, all hosted online at https://purdue-edu.zoom.us/my/mdward/ (on Zoom).  All the information you need to work on the questions each week will be provided online during class, and also in the notes online.  We encourage you to get a head start on the questions in between classes.  It is helpful to ask questions and get help from Dr. Ward, the T.A.s, and your classmates in several ways, e.g., onsite in class, in Piazza, in office hours, etc.  The T.A.s will have many daytime and evening office hours throughout the week.

=== Course Description

The Data Mine is a supportive environment for students in any major and from any background who want to learn data science tools and methodologies. Students will have hands-on experience with computational tools for representing, extracting, manipulating, interpreting, transforming, and visualizing data, especially big data sets, and in effectively communicating insights about data. Topics include: large language models, agent-based (agentic) models, image processing, containers, APIs, etc.

=== Learning Outcomes

By the end of the course, you will be able to:

. Utilize data science tools and methods in research opportunities and in professional development opportunities.
. Understand how language models, generative AI, agentic models, image processing, etc., are used in data-driven applications.
. Devise and implement the most appropriate data-driven strategy, in order to answer research questions.

=== Mapping and Assessment of Foundational Learning Outcomes (FLO) = Information Literacy

Please see the separate page for the section on Foundational Learning Outcomes:

https://the-examples-book.com/projects/summer2026/flo

=== Mapping and Assessment of College of Science Learning Outcomes:

Please see the separate page for the section on Foundational Learning Outcomes:

https://the-examples-book.com/projects/summer2026/cos

=== Required Materials

* A laptop so that you can easily work with others. Having audio/video capabilities is useful.
* Access to these websites:
- link:https://the-examples-book.com/projects/summer2026/syllabus[*Syllabus*] - All information will be posted within these pages!
- link:https://www.gradescope.com/[*Gradescope*] - All solutions to questions will be submitted on Gradescope
- link:https://purdue.brightspace.com/[*Brightspace*] - Grades will be posted in Brightspace.
- link:https://ondemand.anvil.rcac.purdue.edu/[*Jupyter Lab via the On Demand Gateway on Anvil*]
- link:https://notebook.anvilcloud.rcac.purdue.edu/[*Jupyter Lab via the Notebook Portal on Anvil*]
* Good internet connection.

=== Guidance on Generative AI

[TIP]
====
*AI tools may be used for:* 

* Code debugging or optimization suggestions 

* Rewording or summarizing your own writing 

* Practicing concepts (e.g., asking AI to quiz you)

*AI tools CANNOT be used for:* 

* Submitting AI-generated responses as your own, without meaningful modification. Students need to provide explanations of their work, using full English sentences that the student wrote herself/himself. 

* Using AI to generate entire reports, essays, or coding solutions, with minimal personal input. 
====

[IMPORTANT]
====
*Disclosure Requirement for Students*

The usage of generative AI must *always be documented.* This is similar to the need to document books, papers, notes from other people, online sources, electronic resources, Stack Exchange / Stack Overflow, any websites, etc. It is necessary to document any source of any information that you use anytime!

If you use AI tools, you must include an explanation about where you used the AI tools in your work (e.g., you must provide such an explanation in your submission template) describing: 

* Which tool was used 
* What it was used for 
* How the output was modified.
====

As the world of machine learning, deep learning, and AI continues to evolve, we wanted to offer some guidance on The Data Mine's perspective for generative AI tools.

New emergent technologies can be incredibly valuable tools. However, at the same time, it is important to keep perspective on how and when we utilize these new systems.

When using Generative AI on a Data Mine solutions:

* Always question the response that the tool provides.

** It is OK to ask different applications for suggestions, e.g., about common algorithms, or good starting points for problem solutions. However, it is vital to understand factors like where the solutions fit, how they perform, and how to measure their performance.

** It is OK for a tool to recommend an algorithm for research. It is unacceptable to assume that the algorithm is the only correct answer and to not be able to explain why it was chosen. ("Generative AI told me" will not be accepted.)

** It is also occasionally possible that the tool will make up an answer, and you do not want to get stuck presenting false information.

* If you are ever unsure about if a tool can be used, ask your instructor BEFORE you use it.

** We want to use new tools and adapt to the new environments, but our number 1 priority is to provide a safe, secure, and ethical data environment. We want to ensure that students' academic work is not at risk.

* When using generative AI for code it is very important to understand the fundamental code's functionality.

** While generative AI can easily write (for instance) if/else functions or for loops, if you do not understand how they work, you will have a much harder time when it comes to writing documentation or highly specific code functions.

** Generative AI is great to help with ideas, but should not be used without thought.

As with any new technologies, the world of generative AI is changing quickly. We encourage open discussion and welcome any feedback to The Data Mine concerning these technologies.

[IMPORTANT]
====
*Ethical Considerations*

* Before submitting your work, you must critically evaluate AI-generated content for accuracy, bias, and fairness.

* Please keep in mind that AI should support learning, not replace it.

* Carefully keep in mind that AI-assisted work is still your responsibility.

* The usage of Generative AI needs to be documented.

https://www.purdue.edu/odos/osrr/honor-pledge/about.html[The Purdue Honor Pledge] is "As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue."
====

=== Attendance Policy 

When conflicts or absences can be anticipated, such as for many University-sponsored activities and religious observations, the student should inform the instructor of the situation as far in advance as possible. 

For unanticipated or emergency absences when advance notification to the instructor is not possible, the student should contact the instructor as soon as possible by email or phone. When the student is unable to make direct contact with the instructor and is unable to leave word with the instructor's department because of circumstances beyond the student's control, and in cases falling under excused absence regulations, the student or the student's representative should contact or go to the Office of the Dean of Students website to complete appropriate forms for instructor notification. Under academic regulations, excused absences may be granted for cases of grief/bereavement, military service, jury duty, parenting leave, and medical excuse. For details, see the link: https://catalog.purdue.edu/content.php?catoid=19&navoid=25412#a-attendance[Academic Regulations & Student Conduct] of the University Catalog website. 

== How to succeed in this course

If you would like to be a successful Data Mine student:

* Start on the daily questions promptly, so that you have plenty of time to get help from your classmates, TAs, and Data Mine staff. Don't wait until the due date to start!
* Be excited to challenge yourself and learn impressive new skills. Don't get discouraged if something is difficult. You are here because you want to learn, not because you already know everything!
* Remember that Data Mine staff and TAs are excited to work with you! Take advantage of us as resources.
* Network! Get to know your classmates, even if you don't see them in an actual classroom. You are all part of The Data Mine because you share interests and goals.
* Use "The Examples Book" with lots of explanations and examples to get you started. Google, Stack Overflow, etc. are all great, but "The Examples Book" has been carefully put together to be the most useful to you. https://the-examples-book.com[the-examples-book.com]
* Expect to spend time daily on the questions assigned in class. Some might take less time, and occasionally some might take more.
* If you get behind or feel overwhelmed about this course or anything else, please talk to us!
* Stay on top of deadlines. Announcements and news will be given every day in class, so please come to class.
* Read your emails!


== Information about the Instructors 

=== The Data Mine Staff

[%header,format=csv]
|===
Name, Title
Shared email we all read, datamine-help@purdue.edu
Katie Sanders, Operations Director
Dr. Fulya Gökalp Yavuz, Director of Data Science
Dr. Mark Daniel Ward, Faculty Director
|===

=== Communication Guidance

* For questions about how to do the homework, talk to Dr. Ward in class, visit office hours, and ask questions on Piazza.
* For general Data Mine questions, please write to: datamine@purdue.edu
* For regrade requests, use Gradescope's regrade feature within Brightspace. Regrades should be
requested within 1 week of the grade being posted.


== Assignments and Grades

=== Course Schedule & Due Dates

See the schedule and later parts of the syllabus for more details, but here is an overview of how the course works:

Generally, every week you will have questions discussed in class, to be answered by the start of the following week, i.e., by the following Monday.  The questions from the last week are due on the last Friday of the semester.

We suggest trying to do as many daily questions as possible, so that you can keep up with the material. The questions are much less stressful if they aren't done at the last minute.  It is also possible that the high performance computing systems will be busy, if you wait until the last night, causing unexpected behavior and long wait times. Try to start your solutions early, to leave yourself time to ask questions.

=== Solutions to Questions 

* Each weekly set of solutions is worth 25 percent of the course grade.
* There will be 4 collections of questions available over the four-week course.
* No late work will be accepted, even if you are having technical difficulties, so do not work at the last minute.
* There are many opportunities to get help throughout the week. We are here for you! Ask questions!
* Follow the instructions for how to submit your solutions properly through Gradescope in Brightspace.
* It is ok to get help from others or online, although it is important to document this help in the comment sections of your submissions. You need to say who helped you and how they helped you.
* Each week, new questions will be posted daily.  The questions from each week will be due on the following Monday.
* If you need to request a regrade on any part of your submission, use the regrade request feature inside Gradescope. The regrade request needs to be submitted within one week of the grade being posted (we send an announcement about this).

=== Late Work Policy 

We generally do NOT accept late work. 

=== Grade Distribution

[cols="4,1"]
|===

|Week 1 Solutions |25% 
|Week 2 Solutions |25% 
|Week 3 Solutions |25% 
|Week 4 Solutions |25% 
|*Total* |*100%*

|===


=== Grading Scale

In this class grades reflect your achievement throughout the semester in the various course components listed above. Your grades will be maintained in Brightspace. This course will follow the 90-80-70-60 grading scale for A range, B range, C range, D range, and F range cut-offs. If you earn a 90.000 in the class, for example, that is A range, which could include A-, or A, or A+, given at the instructor's discretion between these cut-offs.

* A range [A-, A, A+]: 100.000% - 90.000%
* B range [B-, B, B+]: 89.999% - 80.000%
* C range [C-, C, C+]: 79.999% - 70.000%
* D range [D-, D, D+]: 69.999% - 60.000%
* F range: 59.999% - 0.000%


=== Academic Integrity 

Academic integrity is one of the highest values that Purdue University holds. Individuals are encouraged to alert university officials to potential breaches of this value by either link:mailto:integrity@purdue.edu[emailing] integrity@purdue.edu or by calling 765-494-8778. While information may be submitted anonymously, the more information that is submitted provides the greatest opportunity for the university to investigate the concern.

In TDM 19000, we encourage students to work together. However, there is a difference between good collaboration and academic misconduct. We expect you to read over this list, and you will be held responsible for violating these rules. We are serious about protecting the hard-working students in this course. We want a grade for The Data Mine seminar to have value for everyone and to represent what you truly know. We may punish both the student who cheats and the student who allows or enables another student to cheat. Punishment could include receiving a 0 on a submission, receiving an F for the course, and incidents of academic misconduct reported to the Office of The Dean of Students.

*Good Collaboration:*

* First try the questions  yourself, on your own.
* After trying the questions yourself, then get together with a small group of other students who have also tried the questions themselves to discuss ideas for how to do the more difficult problems. Document in the comments section any suggestions you took from your classmates or your TA.
* Finish the solutions on your own so that what you turn in truly represents your own understanding of the material.
* Look up potential solutions for how to do part of the solutions online, but document in the comments section where you found the information.
* If the assignment involves writing a long, worded explanation, you may proofread somebody's completed written work and allow them to proofread your work. Do this only after you have both completed your own assignments.

*Academic Misconduct:*

* Divide up the problems among a group. (You do #1, I'll do #2, and he'll do #3: then we'll share our work to get the assignment done more quickly.)
* Attend a group work session without having first worked all of the problems yourself.
* Allowing your partners to do all of the work while you copy answers down, or allowing an unprepared partner to copy your answers.
* Letting another student copy your work or doing the work for them.
* Sharing files or typing on somebody else's computer or in their computing account.
* Getting help from a classmate or a TA without documenting that help in the comments section.
* Looking up a potential solution online without documenting that help in the comments section.
* Reading someone else's answers before you have completed your work.
* Have a tutor or TA work though all (or some) of your problems for you.
* Uploading, downloading, or using old course materials from Course Hero, Chegg, or similar sites.
* Using the same outside event reflection (or parts of it) more than once. Using an outside event reflection from a previous semester.
* Using somebody else's outside event reflection rather than attending the event yourself.


The link:https://www.purdue.edu/odos/osrr/honor-pledge/about.html[Purdue Honor Pledge] "As a boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together - we are Purdue"  

Please refer to the link:https://www.purdue.edu/odos/osrr/academic-integrity/index.html[student guide for academic integrity] for more details.

Incidents of academic misconduct in this course will be addressed by the course instructor and referred to the Office of Student Rights and Responsibilities (OSRR) for review at the university level. Any violation of course policies as it relates to academic integrity will result minimally in a failing or zero grade for that assignment, and at the instructor's discretion may result in a failing grade for the course. In addition, all incidents of academic misconduct will be forwarded to OSRR, where university penalties, including removal from the university, may be considered. 

=== xref:syllabus_purdue_policies.adoc[Purdue Policies & Resources]

=== Disclaimer 
This syllabus is subject to small changes.  All questions and feedback are always welcome!
