= NDMN Gallaudet 10100: R Project 10 -- 2022

**Motivation:** 

**Context:** 

**Scope:** 

.Learning Objectives
****
- 
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- `/anvil/projects/tdm/data`

== Questions

=== Question 1



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 2



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 3



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 4



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 5



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:book:projects:submissions.adoc[submission guidelines] before submitting your project.
====