= Fall 2025 Office Hours Schedule

[IMPORTANT]
====
Office hours before 5 PM on weekdays (Monday through Friday) will be offered both in-person in the lobby of Hillenbrand Hall, and also virtually.

Office hours on Sundays (all day) and also on weekdays after 5 PM will be held exclusively virtually.

Office Hours Zoom Link: https://purdue-edu.zoom.us/s/97774213087

Checklist for the Zoom Link:

* When joining office hours, please include your Data Mine level in front of your name. For example, if you are in TDM 102, your name should be entered as "102 - [Your First Name] [Your Last Name]".

* After joining the Zoom call, please stay in the main room until a TA invites you to a specific breakout room.

* We will continue to follow the office hours schedule as posted on the Examples Book. Link is coming soon!
====

[NOTE]
====
The below calendars represent regularly occurring office hours. Please check your class' Piazza page to view the latest information about any upcoming changes or cancellations for office hours prior to attending.

Our Piazza links are:
 
TDM 10100: https://piazza.com/purdue/fall2025/tdm1010010200202526/home

TDM 20100: https://piazza.com/purdue/fall2025/tdm2010020200202526/home 

TDM 30100: https://piazza.com/purdue/fall2025/tdm3010030200202526/home

TDM 40100: https://piazza.com/purdue/fall2025/tdm4010040200202526/home 

====

== TDM 10100 Office Hours:

Link is coming soon!
https://purdue0-my.sharepoint.com/:x:/g/personal/hanse186_purdue_edu/EWMIAcyp8sFEqE1F9u1A-0wB74g6caSAPYj9ENtJrRodBw?e=J85uA4&ovuser=4130bd39-7c53-419c-b1e5-8758d6d63f21%2Cfgokalp%40purdue.edu&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI1MC8yNTA3MzExNzQxMCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D

== TDM 20100 Office Hours:

Link is coming soon!

== TDM 30100 and 40100 Office Hours:

Link is coming soon!

