---
title: "STAT 29000 Project 2"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Topics:  Introduction to Mapping in Scholar

Motivation:  In many applications of data science, in many disciplines, mapping plays a key role.  In STAT 19000, you already learned how to make maps in R.  They are relatively simple to create.  Indeed, maps were one of the first concepts in data visualization that you learned.

Context:  After remindering ourselves how to build maps in R, we will be able to make maps of anywhere in the world that Google Maps are available.  We will also have control over the zoom factor, and we will be able to add points to the maps, according to the latitude and longitude for points of interest.  Last year, we borrowed Dr Ward's Google Maps API Key, but this year we will also learn how to create our own Google Maps API Key.

Scope:  You already know that R can be used as the glue that stitchs together many other data science tools.  At the moment, R has approximately 15,000 packages, which are used in every conceivable discipline and area of study.  The list of packages is constantly growing.  The packages are also becoming more advanced and more stable, so that working in R makes the entire ecosystem of data analysis available to everyone.
These packages are available to download and use, at no cost.  <https://cran.r-project.org/web/packages/> 

## Question 1: Building a Map of AirBnB Listings in Los Angeles

Recall how to make a map in R.  We use the AirBnB listings from Los Angeles as an example.
Try the following *inside* the Scholar environment.

1a.  Open the Terminal in Scholar.

1b.  Open RStudio by typing the following in the terminal:

ml gcc

ml rstudio

rstudio

1c.  Open the following R file:  `/class/datamine/data/examples/LAmaps.R`

1d.  Save this file in your home directory on Scholar.

1e.  Run the commands in R and display the map of AirBnB listings in Los Angeles.

Hint 1:  Recall that you can run each command in RStudio by typing Control-Enter (also called Control-Return)

Hint 2:  If the font in your RStudio application looks strange, read the section about how to fix this, in the computer FAQ on The Data Mine website <https://datamine.purdue.edu/computing-faq.html>

## Question 2: Getting Your Own Google Maps API Key

2a.  First load this URL:

<https://google.secure.force.com/GCPEDU?cid=SX1tU%2Fw1ZbMTo0VdyFTNzwBCEeeh5KQ7xk5%2Bi273beHLpPDcHt9bEzC3lEfguSWJ>

or, if we run out of licenses there, use this link:

<https://google.secure.force.com/GCPEDU?cid=GHTlKXA9WVqT7vBf5tRDglTU4InEPt0ivXWMJ40OnTbIlRC0jWgm%2BcQ%2FLqvf2qIo>

2b.  Then follow the instructions here, to get your own Google Maps API Key.

<https://datamine.purdue.edu/information/project2getAPIkey.pdf>


## Question 3: Creating Your Own Function to Make Maps

You ONLY need to submit your answers to Question 3a, 3b, 3c for this project.  You submit it at this URL: <https://classroom.github.com/a/gD77-KhL> using the instructions found in the GitHub Classroom instructions folder on Blackboard.

3a.  Modify the code from `/class/datamine/data/examples/LAmaps.R` to build your own function that produces a map.  When using this function, you do not need to include the ggmap installation or the command to load ggmap.  You can assume that the person using your function has already installed and loaded this package.

The function should be able to be called like this:
`mymapfunction(mylon,mylat,mycenter,myzoom)`
Your function should use your own Google Maps API Key.

3b.  Run your function with the Los Angeles data, as follows:

`myDF <- read.csv("/class/datamine/data/airbnb/united-states/ca/los-angeles/2019-07-08/visualisations/listings.csv")`
`mymapfunction(myDF$longitude,myDF$latitude,"Los Angeles",9)`

3c. Now run your function to make a map using the data about AirBnB locations in London

`myDF <- read.csv("/class/datamine/data/airbnb/united-kingdom/england/london/2019-07-10/visualisations/listings.csv")`
`mymapfunction(myDF$longitude,myDF$latitude,"London",10)`



