= ArcGIS

This section is intended to be a starting place for users to learn more about https://www.arcgis.com/index.html[ArcGIS] as a Geospatial Information Systems (GIS) platform. 

For students at Purdue University there is an https://www.rcac.purdue.edu/downloads/geospatial/arcgis[ESRI ArcGIS student page]. The page outlines the steps required for students to setup access to the applications free of charge. 

For students outside of Purdue ESRI has setup an https://storymaps.arcgis.com/stories/60856ecea6654bfc86d754d1eacd99fe[ArcGIS Pro for student use] process that allows an educational license for the application. 

[IMPORTANT]
====
The ArcGIS and ESRI tools don't currently have a Mac or Linux version. Meaning they will only run on a Windows computer. 

If you are running these applications as part of a Data Mine project, please reach out to datamine-help@purdue.edu for steps to run the applications on Purdue's resources. 
====

== ArcGIS Training

After your account setup is complete, ESRI offers comprehensive training courses focused on ArcGIS topics. 

The trainings can be accessed via https://www.esri.com/training/[ESRI's training portal.]

[TIP]
====
If you're a student at Purdue and you need to log-in to ESRI for anything select "Your ArcGIS organization's URL" and then enter `purdueuniversity.maps.arcgis.com` in the information box. 

This will utilize your Purdue credentials to authenticate and should give you access with no additional charge. 
====

=== ArcGIS Courses

* The https://www.esri.com/training/catalog/5d9cd7de5edc347a71611ccc/gis-basics/[GIS Basics] course is beneficial for those who have never worked in GIS.
* ESRI does have many more courses focused on specific topics if there are research items that the team would like to learn more about. 

== Publishing ArcGIS Findings

It's always important to think about how you will https://pro.arcgis.com/en/pro-app/latest/help/sharing/overview/share-with-arcgis-pro.htm[share information via ArcGIS.] Often, other users may be required to have a license to access map layers or dashboards created via ArcGIS. 

These licenses are almost always paid for non-student users. The Data Mine does not pay for software licenses that are included as part of a project or research. 

[TIP]
====
The training from ESRI will leverage both ArcGIS Pro and ArcGIS Online. 

ArcGIS Pro should have all the capabilities of ArcGIS Online and more. 

However, the specific steps may be slightly different between the two applications. 
====