= deaffriendly

Welcome to the student resource section for the _deaffriendly_ corporate partnership project. + 
This is a "living" book that is continuously being updated. If you have any feedback, please write to datamine@purdue.edu

== Expectations
For this spring semester starting on Monday, February 6th, you're expected to: +

* attend 50-minute mentor meeting on Tuesdays at 2:30 PM Eastern Time. + 
* attend 2-hour lab on Thursdays either at 12 PM or 4 PM Eastern Time.
* submit a mini project weekly due Friday at 11:59 PM PST on Gradescope.
* submit a sprint report bi-weekly due Wednesday at 11:59 PM PST on Gradescope.
* complete evaluation. (more information coming soon)

== Adding The Data Mine to your Resume
Please see the https://the-examples-book.com/crp/students/professional_development[Professional Development] section to learn how to add The Data Mine to your resume.

== Questions? Need Help?
* Check The Examples Book for course schedule with due dates
* Ask The Data Mine Staff
** Naomi and Kali are your go-to resource for questions specific to DEAF PODS
** Send us an email at datamine-help@purdue.edu for questions related to grades and techincal help [https://the-examples-book.com/crp/students/ds_team_support[see this page on asking for techincal help]]

== Schedule
[%header,format=csv,stripes=even,%autowidth.stretch]
|===      
Assignment,Due date (at 11:59 PST), Submission Location
Pre Survey, February 22, TBD
Mini Project 1: https://the-examples-book.com/projects/current-projects/10200-2023-project01[Learn how to use Anvil],February 17,https://www.gradescope.com/[Gradescope] 
Corporate Partners Sprint Report 1, February 22,https://www.gradescope.com/[Gradescope] 
Mini Project 2: [Coming Soon],February 24,https://www.gradescope.com/[Gradescope] 
Mini Project 3: [Coming Soon],March 3,https://www.gradescope.com/[Gradescope] 
Corporate Partners Sprint Report 2, March 8, https://www.gradescope.com/[Gradescope] 
Mini Project 4: [Coming Soon],March 10,https://www.gradescope.com/[Gradescope] 
Mid Survey, March 10, TBD
Mini Project 5: [Coming Soon],March 24,https://www.gradescope.com/[Gradescope] 
Corporate Partners Sprint Report 3, March 29,https://www.gradescope.com/[Gradescope] 
Mini Project 6: [Coming Soon],March 31,https://www.gradescope.com/[Gradescope] 
Mini Project 7: [Coming Soon],April 7,https://www.gradescope.com/[Gradescope] 
Corporate Partners Sprint Report 4, April 12,https://www.gradescope.com/[Gradescope] 
Mini Project 8: [Coming Soon],April 14,https://www.gradescope.com/[Gradescope] 
Mini Project 9: [Coming Soon],April 21,https://www.gradescope.com/[Gradescope] 
Corporate Partners Sprint Report 5, April 26,https://www.gradescope.com/[Gradescope] 
Mini Project 10: [Coming Soon],April 28,https://www.gradescope.com/[Gradescope] 
Mini Project 11: [Coming Soon],May 5,https://www.gradescope.com/[Gradescope] 
Post Survey, May 5, TBD
|===
