= Schedule

Note: This schedule is still tentative. 

[%header,format=csv,stripes=even,%autowidth.stretch]
|===      
Assignment,Due date (at 11:59 Eastern Time), Submission Location
Pre Survey, TBD, TBD
Corporate Partners Sprint Report 1, February 22,https://www.gradescope.com/[Gradescope]
Mini Project 1: https://the-examples-book.com/projects/current-projects/10200-2023-project01[Learn how to use Anvil],February 24,https://www.gradescope.com/[Gradescope] 
Mini Project 2: xref:MP2-s2023.adoc[Look at Cragislist Vehicles],March 3,https://www.gradescope.com/[Gradescope] 
Corporate Partners Sprint Report 2, March 8, https://www.gradescope.com/[Gradescope] 
Mini Project 3: xref:MP3-s2023.adoc[Learn how to data explore],March 10,https://www.gradescope.com/[Gradescope] 
Complete your RCR Training course (_An email consisting of training information should be sent to your Purdue email_),March 24,Email your completion report to rcrtraining@purdue.edu and datamine@purdue.edu
Corporate Partners Sprint Report 3, March 29,https://www.gradescope.com/[Gradescope] 
Mini Project 5: https://the-examples-book.com/projects/current-projects/10200-2023-project10[Data Visualization],March 31,https://www.gradescope.com/[Gradescope] 
Mini Project 6: https://the-examples-book.com/projects/current-projects/10200-2023-project11[Merging Datasets],April 7,https://www.gradescope.com/[Gradescope] 
Corporate Partners Sprint Report 4, April 12,https://www.gradescope.com/[Gradescope] 
Mini Project 7: xref:MP7-s2023.adoc[Web scraping],April 14,https://www.gradescope.com/[Gradescope] 
Mini Project 8: https://the-examples-book.com/projects/current-projects/10200-2023-project13[Working with Text in Python],April 21,https://www.gradescope.com/[Gradescope]
Draft of the Poster: https://the-examples-book.com/deaf-pods/intro/poster-guidance[See the guidelines here],April 21,Leave it in your MS Teams group
Corporate Partners Sprint Report 5, April 26,https://www.gradescope.com/[Gradescope] 
Mini Project 9: [Coming Soon],April 28,https://www.gradescope.com/[Gradescope]
Final verison of the Poster,May 3,Leave it in your MS Teams group
Spring Report #6/Exist Survey,May 5, https://www.gradescope.com/[Gradescope]
|===
