= deaffriendly: Mini Project 2 -- Spring 2023

**Motivation:** In this project, we are going to learn how to work with a dataset in Python. Some popular open-source packages in Python are `python` and `numpy` which we will use for this project. `pandas` is used for data manipulation and data analysis. `numpy` is used for scientific computing in arrays.

This project will look at the vehicle dataset webscraped from Craigslist.

**Context:** ...

**Scope:** Python, Jupyter Lab, Anvil

.Learning objectives
****
- Read and learn about dataframe structures
- Check for data types and learn about the behaviors of True/False
- Use various functions to learn more about the data (e.g., unique, value_counts, etc.)
- Create a subset of the dataset
****

Make sure to read about and use the template found https://the-examples-book.com/projects/current-projects/templates[here]. Also make sure to read the important information about projects submissions https://the-examples-book.com/projects/current-projects/submissions[here].

== Dataset

The following questions will use the dataset found in Anvil:

`/class/datamine/data/craigslist/vehicles.csv`

== Questions

=== Question 1: Warm up
In the previous project, you successfully read in a data file in `pandas`. Let's do again with `/anvil/projects/tdm/data/craigslist/vehicles.csv`

[IMPORTANT]
====
Before you launch your Jupyter Lab session, make sure to select *2* cores.
====

Recall the previous project, answer those following questions:

- How many rows and columns are in the dataset?
- What are the columns in the dataset?
- Use `head()` and `tail()` to print the first and last five lines in the dataset.

.Items to submit
====
- Python code used to answer the questions above
- The outputs/answers
====

=== Question 2: Data types

Let `myDF` stand for my dataframe variable that read in the `vehicles` file. It's OK if your variable is different from mine. It's just a name of the variable.

Data comes in different shapes and forms. It's important to know what types of data you're working with.

Please visit the https://the-examples-book.com/programming-languages/python/variables#overview[page] for more information about common data types you'll see in Python. 


[source,python]
----
# This will check the data type of the `price` column
type(myDF['price'])
# It will return: pandas.core.series.Series
# This means the `price` column is just a series or a list of items in pandas.

# What if you check the data type of one item in the `price` column
# Feel free to swap "0" for a different number, this indicates the row number in the column
type(myDF['price'][0])
# It will return: numpy.int64
# This means the item in the `price` column is an int value (or a [whole] number)
----

==== Challenge: What data type are the items inside the `id` column?

.Items to submit
====
- Python code used to answer the question above
- The output/answer
====

=== Question 3: We want free vehicles

It's tad annoying that I cannot see a whole row in my Jupyter notebook. If you print the head of your dataframe, you will see that your output doesn't show all the columns in the dataset.

To view all the columns in your output, you can run this line of code in your cell:

[source,python]
----
pd.set_option('display.max_columns', None)
----

When you print the head of your dataframe again, you'll be able to see all the columns!

Looking at the head of `myDF`, I wonder how many vehicles are "free" in the dataset. In other words, how many times does "0" appear in the `price` column.

To answer the question above, we can use a comparison operator (==) which will compare two variables and then return either `True` or `False`. +
For example, `4==5` will return `False`. `1==1` will return `True`.

[source,python]
----
# This will compare every item in the `price` column with `0`
myDF['price'] == 0
# When you run this in your cell, you'll see a list of `True` and `False`
----

Now, from the mathematical perspective, `True` has an equivalent value of 1 and `False` has an equivalent value of 0. +
For example, if you run `True + True` in your cell, it will return `2`. If you run `True + False + False`, it will return `1`.

With that in mind, we can add up the output we got from the comparison operator code above to find the number of "free" vehicles!

[source,python]
----
# We can use sum() function to add up all the numbers in a list.
sum(myDF['price'] == 0)
# This will return 30701 free vehicles.
----

==== Challenge: How many vehicles are listed for less than $5000 (not equal to $5000)? How many vehicles are listed for less than $5000 but not free?

.Items to submit
====
- Python code used to answer the questions above
- The output/answer
====

=== Question 4: Value Frequency

Looking at the head of `myDF` again, I'm quite curious about the data in the `fuel` column. I'm wondering how many kinds of fuel in the dataset. To answer that question, I can use `unique()` which is a Python function that will return an array of all unique values found in the column.

[source,python]
----
# We can use unique() to find unique different kinds of fuel
myDF['fuel'].unique()
# This will return an array consisting of gas, other, diesel, nan, hybrid, electric
----

I'm curious about how many manufacturers there are in the dataset. I can do the similar process I just did for fuel.
[source,python]
----
myDF['manufacturer'].unique()
# It will return an array consisting of all different vehicle manufacturers
----

Now, I have a follow-up question about fuel. I wonder how many vehicles have gas for fuel, how many for diesel, how many for hybrid, etc. +
To answer that question, I can use 'value_counts()' which will return the total occurrences for each unique value in a column.

[source,python]
----
myDF['fuel'].value_counts()
# This will return the total vehicles for each fuel type in the order of largest to smallest
----

==== Challenge: Which manufacturer appears the most in the dataset?

.Items to submit
====
- Python code used to answer the questions above
- The output/answer
====

=== Question 5: Region and Age
Using the `unique()` function we just learned about, I wanted to find different regions in the dataset. 
[source,python]
----
myDF['region'].unique()
# This will return an array consisting of all unique regions appeared in the dataset. It's long!
----

I just learned that there's a region consisting of my name! `kalispell` sounds like an incredible place for myself being Kali to live in! +
I'm in a wrong career - I should be a ruler in `kalispell`.

Now, I'm only interested in all vehicles in the kalispell region. +
Filtering out uninteresting data consists of couple steps. Bear with me. +
Please feel free to pause and look around the data at any point of this process.

[source,python]
----
# Recall that the comparison operator (==) we learned in a previous question
# This will return a list of True and False
myDF['region'] == 'kalispell'
----

[source,python]
----
# Let's assign the output above to a variable
list_tf = myDF['region'] == 'kalispell'
----
[source,python]
----
# What happens here is that myDF will delete all rows that have the same position of False, only keeping the rows that have the same position of True
myDF[list_tf]
----

[source,python]
----
# let's assign the output above to a variable
kalispell_DF = myDF[list_tf]
----

[source,python]
----
# Print the top five lines
kalispell_DF.head()
# Note that the row numbers are different (e.g., not starting at 0)
----

[source,python]
----
# If you run this line, it will throw you an error because of the index number
kalispell_DF['id'][0]
----

[source,python]
----
# We can reset the index numbers using reset_index()
# drop=True means you don't want to keep the original index numbers, feel free to remove if you want to keep the old index numbers
kalispell_DF.reset_index(drop=True)
# The output have index numbers starting at 0
----

[source,python]
----
# Assign the output above to the same variable name as I want the output above
kalispell_DF = kalispell_DF.reset_index(drop=True)
----

[source,python]
----
# Print the top five lines
kalispell_DF.head()
----

You did it! You just filtered out all the data that are not in the kalispell region! + 

Looking at the 'year' column, I want to know what year is the lowest and what year is the highest in that column. To find the answers, we can use `max` and `min` functions from the `numpy` library.

[source,python]
----
import numpy as np

# Find the highest year listed in the column
print(np.max(kalispell_DF['year']))

# Find the highest year listed in the column
print(np.min(kalispell_DF['year']))
----

Now, I'm interested in learning more about the oldest vehicle and the newest vehicle in the dataset. I can filter out the data to find those specific information.

Let's start with the newest vehicle:
[source,python]
----
# Assign the max year value to a variable
max_year = np.max(kalispell_DF['year'])

# Check if every value in the year column is equal to the max year value
# Only keeps the row(s) if True
kalispell_DF[kalispell_DF['year'] == max_year]
----

Now, for the oldest vehicle:
[source,python]
----
# Assign the min year value to a variable
min_year = np.min(kalispell_DF['year'])

# Check if every value in the year column is equal to the min year value
# Only keeps the row(s) if True
kalispell_DF[kalispell_DF['year'] == min_year]
----

The outputs should show that the newest vehicle and the oldest vehicle in the kalispell region listed on Craigslist were, respectfully, Subaru Outback Limited XT and Ford T-bucket.

==== Challenge: Choose a region you're interested in looking at. Despite how cool it is, you cannot select kalispell, sorry! What are the manufacturer and model of the oldest and newest cars in that region?

.Items to submit
====
- Python code used to answer the question above
- The output/answer
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our https://the-examples-book.com/projects/current-projects/submissions[submission guidelines] before submitting your project.
====