= deaffriendly: Mini Project 3 -- Spring 2023

**Motivation:** In this project, we are going to learn how to work with a dataset in Python. Some popular open-source packages in Python are `python` and `numpy` which we will use for this project. `pandas` is used for data manipulation and data analysis. `numpy` is used for scientific computing in arrays.

This project will look at the review dataset webscraped from Amazon.

**Scope:** Python, Jupyter Lab, Anvil

.Learning objectives
****
- Learn how to get the overview look of the dataset (size, columns, value_counts, etc)
- Create subsets and filter specific data points
****

Make sure to read about and use the template found https://the-examples-book.com/projects/current-projects/templates[here]. Also make sure to read the important information about projects submissions https://the-examples-book.com/projects/current-projects/submissions[here].

== Dataset

The following questions will use the dataset found in Anvil:

`/anvil/projects/tdm/data/amazon/amazon_fine_food_reviews.csv`

== Questions

=== Question 1: Warm up
Let's read in `/anvil/projects/tdm/data/amazon/amazon_fine_food_reviews.csv` in `pandas`.

Recall the previous project, answer those following questions:

- How many rows and columns are in the dataset?
- What are the columns in the dataset?

.Items to submit
====
- Python code used to answer the questions above
- The outputs/answers
====

=== Question 2: Value Frequency

Let `myDF` stand for my dataframe variable that read in the `amazon_fine_food_reviews.csv` file. It's OK if your variable is different from mine. It's just a name of the variable.

Recall the function `value_counts` you learned in the previous project. This function calculates the total occurrences for each unique value in a column

==== Challenge: Use the `value_counts` function to find the top five most-reviewed `ProductId` and the top five `UserId` with most reviews.

.Items to submit
====
- Python code used to answer the questions above
- The output/answer
====

=== Question 3: Products with at least 100 reviews

Recall that `True` has an equivalent value of `1` and `False` has an equivalent value of `0`.

=== Challenge: Use the `sum` functon to find the number of `ProductId` that has more than 100 review (not equal to 100 review)

.Items to submit
====
- Python code used to answer the question above
- The output/answer
====

=== Question 4: 
Suppose I'm interested in looking at `ProductId == B006HYLW32`

Let's make a subset from the dataset consisting data only about that particular product.
[source,python]
----
# Filter to keep all data points with ProductId being B006N3I0DM
# Assign this smaller dataset to a variable named mySubset
# Reset the index number back to 0
mySubset = myDF[myDF['ProductId']=='B006HYLW32'].reset_index(drop=True)
# Print the top five lines of mySubset
mySubset.head()
----

I'm wondering if this product has multiple reviews from a same user. +
We can check using `value_counts` function
[source,python]
----
# Check the frequency values for each unqiue UserId
mySubset['UserId'].value_counts()
# Output: Looks like there are some users who did couple reviews on the same product
----

My follow-up question: How many users with multiple reviews on this product?
[source,python]
----
# I'll check every value to see if it's greater than 1
# Then sum the total list of True/False
sum(mySubset['UserId'].value_counts() > 1)
# Output: Five users
----

Now, I'm interested in looking at `UserId == A2TCY4Q5S0NO5Z` to see what this user has to say about this product.
[source,python]
----
# Filter to keep all data points with UserId being A2TCY4Q5S0NO5Z
mySubset[mySubset['UserId'] == "A2TCY4Q5S0NO5Z"]
----

Output (my observation): +
The UserId, `A2TCY4Q5S0NO5Z`, wrote two reviews on the same product. The user is `Mira L. Shanks "F.R.O.G.` and they rated this product `5` for both reviews. Even though the time format is in weird format, I can see that the reviews were written on different times.

Let's print the written text of the reviews themselves.
[source,python]
----
# Note that I didn't reset the index number to 0, so I need to carefully write down the correct index numbers

# print the first review
print(mySubset[mySubset['UserId'] == "A2TCY4Q5S0NO5Z"]['Text'][54])
# print the new line
print("\n") #new line, equivalent to your keyboard's 'return/enter'
# print the second review
print(mySubset[mySubset['UserId'] == "A2TCY4Q5S0NO5Z"]['Text'][398])
----

My observation of the output is that the user really loved the snack product and ordered the same product at least twice. +


Let's look at reviews written by the UserId, `A3UNPDOS40TSF1`.
[source,python]
----
# Following the similiar procedure we did for UserId == "A2TCY4Q5S0NO5Z"

# Filter to keep all data points with UserId being A3UNPDOS40TSF1
mySubset[mySubset['UserId'] == "A3UNPDOS40TSF1"]
----

My observation of the output is that the user has `Hoolia` as their profile name. Hoolia originally rated this snack product `5` but then, the second review, Hoolia rated the same product `3`.

Now, I'm curious about the possible reasoning behind the downvote of the product. 

[source,python]
----
# Note that I didn't reset the index number to 0, so I need to carefully write down the correct index numbers

# print the first review
print(mySubset[mySubset['UserId'] == "A3UNPDOS40TSF1"]['Text'][45])
# print the new line
print("\n") #new line, equivalent to your keyboard's 'return/enter'
# print the second review
print(mySubset[mySubset['UserId'] == "A3UNPDOS40TSF1"]['Text'][404])
----

The output of the written reviews on the same product by Hoolia indicated that the second product was a different flavor and Hoolia wasn't a fan of the Sour Cream and Onion flavored pack. The first review mentioned the BBQ flavor. Hoolia ordered a bulk of the chips, and I wonder if the whole bulk was in BBQ flavor or a variety of flavors?

Now looking at the `summary` column of the both reviews, it seems like Hoolia ordered the bulk in BBQ flavor and then decided to try a different flavor which ended up meh.

This is just an example of data exploration. Be curious. A question leads another question. 

==== Challenge: Go and explore the dataset and share couple (3-4) interestings findings you have learned from the datset.

.Items to submit
====
- Python code used for your data exploration
- List of interesting observations you have about this dataset
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our https://the-examples-book.com/projects/current-projects/submissions[submission guidelines] before submitting your project.
====