= The National Data Mine Network (NDMN)
:description: Main introduction page for NDMN Page
:sectanchors:
:url-repo: https://github.com/TheDataMine/the-examples-book

== Overview

// REPLACE THIS with topical photos from Jessica
// ++++
// <iframe  class="video" width="560" height="315" src="https://www.youtube.com/embed/R_kqpIMyhR4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
// ++++

// xref:book:ROOT:tdm-intro-transcript.adoc[Data Mine Introduction Video Transcript]

Welcome! The link:https://www.amstat.org/[American Statistical Assocation] in collaboration with link:https://datamine.purdue.edu/[The Data Mine at Purdue University] is proud to support this $1.5 million National Science Foundation grant. This website is The Examples Book, a collection of information and examples that can be used to reinforce topics learned in https://datamine.purdue.edu[The Data Mine] seminar. The Examples Book is open to anyone. Even if you aren't a student in The Data Mine we hope you find helpful content here.

[TIP]
====
Where to go for specific topics:

* Working on modeling, analysis, or visualization? Check out `Data Science`.
* Need to know about containers, high performance computing (HPC), or other operations-related topics? Check out `Data Engineering`. 
* Learning R, Python, or SQL. `Programming Languages` might be helpful. 
* Want more info on The Data Mine, corporate partners projects, or student course materials? Check out `Corporate Partners`.
* Looking for projects/exercises to build your skills? Read through the `Course Links`.
* Did you find a mistake in the Book? Would you like to add your own content? Do you have a frequently asked question (FAQ)? `Helpful Links` is the place for you. 
====

== Core Topics

xref:data-science:intro-to-ds:introduction.adoc[[.custom_button]#Data Science#]
xref:data-engineering:intro-to-data-engineering:introduction.adoc[[.custom_button]#Data Engineering#]
xref:programming-languages:ROOT:introduction.adoc[[.custom_button]#Programming Languages#]
xref:crp:ROOT:introduction.adoc[[.custom_button]#Corporate Partners#]

== Course Links

xref:projects:current-projects:10100-2022-projects.adoc[[.custom_button]#TDM 101-102#]
//xref:projects:current-projects:20100-2022-projects.adoc[[.custom_button]#TDM 201-202#]
//xref:projects:current-projects:30100-2022-projects.adoc[[.custom_button]#TDM 301-302#]
//xref:projects:current-projects:40100-2022-projects.adoc[[.custom_button]#TDM 401-402#]
//xref:projects:project-archive:introduction.adoc[[.custom_button]#Projects Archive#]

== Grant Awarded Programs
xref:ndmn:intro:introduction.adoc[[.custom_button]#NDMN#]
xref:deaf-pods:intro:introduction.adoc[[.custom_button]#DEAF PODS#]


== Workshops and Trainings

xref:workshops:intro-workshop:introduction.adoc[[.custom_button]#Workshops#]
xref:think-summer:ROOT:introduction.adoc[[.custom_button]#Think Summer#]

== Helpful Links

xref:book:FAQs:faqs.adoc[[.custom_button]#FAQ#]
xref:book:ROOT:how-to-contribute.adoc[[.custom_button]#How to Contribute#]
xref:book:contributors:contributors.adoc[[.custom_button]#Contributors#]

== Details about the National Data Mine Network:
- This program will provide $4500 in monthly research stipends plus $500 towards conference travel to 100 students (per year) at Minority Serving Institutions
- Students will be able to work on data science projects throughout the 9-month academic year (August through April) and will have access to data science training, materials, and high-performance computing from Purdue University
- In addition to learning data science skills, the students will be able to work on projects with a research mentor or with a mentor from industry through our Data Mine Corporate Partners Projects – we currently have 70+ Corporate Partners projects this year and plan to expand for the upcoming academic year
- Students chosen to participate in the grant activities will receive their research stipends directly from the American Statistical Association.  (Faculty participation in this grant is completely free for those at MSIs.)
 
== Criteria for eligible students include:
- Need to be a U.S. citizen, U.S. national, or permanent resident of the U.S.
- Have undergraduate status at any Minority Serving Institution, including Historically Black Colleges and Universities, Hispanic Serving Institutions, Tribal Colleges, and Universities, or also colleges serving Blind or Deaf learners. 

A list of many MSIs is given here: https://www2.ed.gov/about/offices/list/ocr/edlite-minorityinst.html  (but please inquire if there is any doubt about such classifications or eligibility)
 
== Role of faculty members:
- Onsite, to help provide mentoring for the students -- Such faculty do not need to have data science experience to mentor a team but should have an interest in working closely with students on a data science project
- Participating faculty will have access to a rich collection of resources and faculty development opportunities
  
All questions are welcome! For questions about this opportunity, please reply to:  ndmn@lists.purdue.edu 


== Apply

Applications for Academic Year 2023-2024 is open now! Please apply using this https://purdue.ca1.qualtrics.com/jfe/form/SV_8HyNFGUrvzZjH9Q[link].