
[IMPORTANT]
====
This page is under construction. Please contact us at datamine@purdue.edu for any questions.
====

= The National Data Mine Network (NDMN)

Welcome! The link:https://www.amstat.org/[American Statistical Assocation] in collaboration with link:https://datamine.purdue.edu/[The Data Mine at Purdue University] is proud to support this $1.5 million National Science Foundation grant. 
 
== Details about the National Data Mine Network:
- This program will provide $4500 in monthly research stipends plus $500 towards conference travel to 100 students (per year) at Minority Serving Institutions
- Students will be able to work on data science projects throughout the 9-month academic year (August through April) and will have access to data science training, materials, and high-performance computing from Purdue University
- In addition to learning data science skills, the students will be able to work on projects with a research mentor or with a mentor from industry through our Data Mine Corporate Partners Projects – we currently have 70+ Corporate Partners projects this year and plan to expand for the upcoming academic year
- Students chosen to participate in the grant activities will receive their research stipends directly from the American Statistical Association.  (Faculty participation in this grant is completely free for those at MSIs.)
 
== Criteria for eligible students include:
- Need to be a U.S. citizen, U.S. national, or permanent resident of the U.S.
- Have undergraduate status at any Minority Serving Institution, including Historically Black Colleges and Universities, Hispanic Serving Institutions, Tribal Colleges, and Universities, or also colleges serving Blind or Deaf learners. 

A list of many MSIs is given here: https://www2.ed.gov/about/offices/list/ocr/edlite-minorityinst.html  (but please inquire if there is any doubt about such classifications or eligibility)
 
== Role of faculty members:
- Onsite, to help provide mentoring for the students -- Such faculty do not need to have data science experience to mentor a team but should have an interest in working closely with students on a data science project
- Participating faculty will have access to a rich collection of resources and faculty development opportunities
  
All questions are welcome! For questions about this opportunity, please reply to:  ndmn@lists.purdue.edu 


== Apply

Applications for Academic Year 2023-2024 is open now! Please apply using this https://purdue.ca1.qualtrics.com/jfe/form/SV_8HyNFGUrvzZjH9Q[link].
