= The Starter Guides

The Starter Guides are handcrafted by Data Mine staff to help you deal with data. Here you will find a brief synopsis on all the major data related topics and tools, as well as some less common ones; books, articles, videos and more to learn more about the topic from; as well as free code samples demonstrating technical topics usually in the form of Notebooks and/or containers. 

== Table of Contents

=== Data Science
* https://the-examples-book.com/starter-guides/data-science/data-modeling/introduction[The Data Modeling Process, including general principles, a step by step guide, and how to choose a data modeling technique]
* https://the-examples-book.com/starter-guides/data-science/data-analysis/introduction-data-analysis-techniques[Data Analysis (techniques to help you make sense of data, such as Time Series, NLP, Neural Networks, Computer Vision, etc)]
* https://the-examples-book.com/starter-guides/data-science/data-visualization/introduction-data-visualization[Data Visualization, such as with Tableau, PowerBI, Python or R]
* https://the-examples-book.com/starter-guides/data-science/gather-data/introduction-gather-data[Gathering Data, such as using web scraping and lists of free data sources]

=== Data Engineering
* https://the-examples-book.com/starter-guides/data-engineering/containers/intro-to-containers[Containers (such as with Kubernetes, PySpark)]
* https://the-examples-book.com/starter-guides/data-engineering/databases/introduction-databases[Databases/SQL (such as with SQLite)]
* https://the-examples-book.com/starter-guides/data-engineering/slurm/introduction-slurm[SLURM]

=== Programming Languages For Data Professionals
* Python
* R
* SQL
* Perl

=== Tools, Standards & More
* xref:starter-guides:tools-and-standards:jupyter.adoc[Jupyter Notebook/Lab]
* xref:starter-guides:tools-and-standards:data-science-ethics.adoc[Data Ethics]
* http://the-examples-book.com/starter-guides/tools-and-standards/bookshelf[The Bookshelf]
* https://the-examples-book.com/starter-guides/tools-and-standards/data-formats/introduction-data-formats[Data Formats]
* https://the-examples-book.com/starter-guides/tools-and-standards/matlab/introduction-matlab[Matlab]
* https://the-examples-book.com/starter-guides/tools-and-standards/git/introduction-git[Git]
* https://the-examples-book.com/starter-guides/tools-and-standards/unix/introduction-unix[Unix]

=== Anvil
* https://the-examples-book.com/starter-guides/anvil/introduction[Anvil]
* http://the-examples-book.com/starter-guides/anvil/access-setup[Anvil ACCESS Setup]
* https://the-examples-book.com/starter-guides/tools-and-standards/git/github-anvil[GitHub on Anvil]
* https://the-examples-book.com/starter-guides/anvil/anvil-getting-started[Getting Started With Anvil]

== How to Use 

The Starter Guides are meant to be use-it-when-you-need-it, so if you know what topic you are looking for, dig right in! Otherwise, this page can help you get started.

If you are brand new to dealing with data, start with https://the-examples-book.com/starter-guides/data-science/data-modeling/introduction[learning about the data modeling process]. If you need to gather your own dataset, https://the-examples-book.com/starter-guides/data-science/gather-data/introduction-gather-data[web scraping or searching for a dataset is the next step]. Once you have data, you might need to https://the-examples-book.com/starter-guides/data-science/data-analysis/introduction-data-analysis-techniques[select and perform an analysis technique]. https://the-examples-book.com/starter-guides/data-science/data-visualization/introduction-data-visualization[Data visualization] is used throughout the entire process, whether in EDA or visualizing your results.

For projects with a data engineering focus, check out our https://the-examples-book.com/starter-guides/data-engineering/containers/intro-to-containers[Containers], https://the-examples-book.com/starter-guides/data-engineering/databases/introduction-databases[SQL], or https://the-examples-book.com/starter-guides/data-engineering/slurm/introduction-slurm[SLURM] guides.

=== Data Engineering Vs. Data Science: What's the Difference?

If you are relatively new to dealing with data, refer to the table below to get a feel for the difference between data engineering and data science.

[cols="3,3,3"]
|===
|Discipline |Data Engineering | Data Science

|Languages Used
|Any; General Purpose Languages Most Common, like Python, Java, C++
| Python, R

|What They Do With Data
|"Move Data Around"; Collect, Organize, Set Up Databases; Set up Cloud Systems
| "Make Sense of Data"; Analyze, Train Models, Make Visualizations

|Common Backgrounds
|Computer Science, IT
|Math, Statistics, Computer Science

|Common Tools
| Hadoop, NoSQL, Spark, Postgresql, Kubernetes, Docker
| MapReduce, Keras, PyTorch, Plotting Packages like GGPlot, JAX 

|===

WARNING: While there are debates about whether data science is data engineering and vice versa, or whether they even belong on the same guide together, they are both dependent on each other in some form or fashion, and so we included both as separate categories. For some organizations, people do both! For others, they have multiple departments that share all of those responsibilities; still others draw a much starker line between the two than we have here. One thing is clear: dealing with data always depends on who you deal with, and the jury is still out on the right way to categorize these skills. Nonetheless they overlap in many areas.

TIP: Data professionals of all stripes should know a mix of data engineering and data science to be successful at their jobs. 

=== I Don't See The Topic I Am Looking For

Try the search bar in the top right corner of the Examples Book; it searches across our entire site.