= Sprint #2

== Intro Video

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/ia6H9c0Ap2I?si=xUbeNZejSRKFtHFu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
++++

== Sprint Dates
All sprints will have the same due dates, but the sprint start and end dates are slightly shifted depending on when a team has their lab (2 hours) and lecture (50 minutes). This is so that sprints always start with a lecture (lec) and follow the format lec-lab-lec-lab.

You can find a xref:fall2024/schedule.adoc#sprint-schedule[visual of the sprint schedule here].

*_Monday, 9/2:  Labor Day (no Corporate Partner meetings/classes)_*

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 9/5
|Mon 9/2

|*Sprint End Date*
|Wed 9/18
|Sun 9/15

|*Due Date*
2+| Wed 9/18 by 11:59 PM ET

|===

== To Do

&#10003; Complete Time Sheet

* Timesheet #3 due Sunday 9/8 at 11:59 PM EST.

* Timesheet #4 due Sunday 9/15 at 11:59 PM EST.

&#10003; Grade Sprint #1 & Team Report #1 & Professional Development #1 on Gradescope by Wednesday 9/11 at 11:59PM EST.

== Sprint Schedule

=== Team Meeting #1 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
** Questions related to the company. (Internship, Full-Time Opportunities, and etc.)
* Ensure students are assigned tasks to work on before meeting again in the next lab.


=== Lab Section #1 (1 hour and 50 Minutes):

* Begin lab by doing an Agile review Kahoot with students and a sprint retrospective of sprint #1. Followed by a daily stand-up and sprint planning for sprint #2.
** Use this PowerPoint to facilitate the discussion: xref:attachment$agile_reflection.pptx[Agile Reflection Guide]
* **Team Contract** - Collaborate with your team to create your Team Contract by following the provided outline. This contract will establish your team's expectations for the year. Facilitate this process as an open discussion, encouraging all members to provide input. You will submit this contract in Gradescope at the end of the sprint.  
* Assist students in setting up https://the-examples-book.com/starter-guides/tools-and-standards/git/github-anvil[Github on Anvil]
** *ACTION ITEM*: Review https://the-examples-book.com/starter-guides/tools-and-standards/git/github-anvil[Github on Anvil]
* Use the remainder of the time to work on your project.

=== Team Meeting #2 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles,roadblocks or barriers that they experienced while completing this weeks task?
** What do they plan on committing to completing by next mentor meeting?
* Time for questions from students to mentor.

* Ensure students are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #2 (1 hour and 50 Minutes):

* Begin lab with this sprint's professional development topic of RACI Matrix and discuss with your team whether you will be using this tool for your project.
** Use this PowerPoint to facilitate the discussion: xref:attachment$RACI.pptx[RACI Guide Powerpoint]
** *ACTION ITEM*: Review https://the-examples-book.com/crp/students/raci_guide[RACI Guide] for more information on RACI Matrix.
* Use the remainder of the time to work on your project.

* Sprint Tasks for students: xref:students:fall2024/sprint2.adoc[Sprint 2 Tasks]