= Sprint #4

== Intro Video

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/8kzhUzJHZk4?si=DqQUVDAlCFDyV0Gq" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
++++

== Sprint Dates
_Monday, 10/07 and Tuesday, 10/8: Fall Break – No Classes_

_Thursday, 10/10 and Friday 10/11: All labs and meetings as usual. No changes on Wednesday, Thursday and Friday._


[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 10/3
|Mon 9/30

|*Sprint End Date*
|Wed 10/16
|Sun 10/13

|*Due Date*
2+| Wed 10/16 by 11:59 PM ET

|===

== To Do

&#10003; Set-up a meeting with your mentor to complete mid-semester feedback. Mid-Semester Evals are due October 23. You can begin this assignment during this sprint with your mentor. Please make them aware and share the rubric with them early so they may begin preparing. link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module5_4_mentor_feedback[Mentor and TA Feedback Guide]

&#10003; Complete TA and Student 1:1's. When you complete this task is flexible during Sprint 4. Please find time with each team member to check in with them individually.  link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module4_9_check_ins[Semester Check-Ins with Students]

&#10003; Review Sprint Tasks for students: xref:students:fall2024/sprint4.adoc[Sprint 4 Tasks]. Watch the video on 'The Secret to Giving Great Feedback' and implement strategies in 1:1s with students. 

&#10003; Complete Team Report #3 by Wednesday, October 11 on link:https://www.gradescope.com/[Gradescope]

&#10003; See the xref:fall2023/schedule.adoc[Fall Schedule] for timesheet and report deadlines.

== Sprint Schedule

=== Team Meeting #1 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
* Ensure students are assigned tasks to work on before meeting again in the next lab.


=== Lab Section #1 (1 hour and 50 Minutes): For groups with only 1 lab during this sprint, conduct the resiliency professional development activity. 

* Begin lab by facilitating a discussion on the professional development topic of resiliency. Followed by a daily stand-up and sprint planning for sprint #4.
** Use this PowerPoint to facilitate the discussion: xref:attachment$resiliency.pptx[Resiliency]
** *ACTION ITEM*: Carefully review the  PowerPoint before lab. This will aid in your preparedness to facilitate a productive and thoughtful discussion. Reflect on the images and be ready to participate in the student group discussion if students are slow to warm up. 
* Use the remainder of the time to work on your project.

=== Team Meeting #2 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles,roadblocks or barriers that they experienced while completing this weeks task?
** What do they plan on committing to completing by next mentor meeting?
* Time for questions from students to mentor.

* Ensure students are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #2 (1 hour and 50 Minutes):

* Begin lab by facilitating a discussion on the professional development topic of problem solving.
** Use this PowerPoint to facilitate the discussion: xref:attachment$ProblemSolving_Sp4_2.pptx[Problem Solving and Decision Making]
** *ACTION ITEM*: Carefully review the  PowerPoint before lab. This will aid in your preparedness to facilitate a productive and thoughtful discussion. Reflect on the questions and be ready to participate in the student group discussion if students are slow to warm up. 
* Use the remainder of the time to work on your project.

* Sprint Tasks for students: xref:students:fall2024/sprint4.adoc[Sprint 4 Tasks]