= Sprint #7

== Sprint Dates
_Wednesday, 11/23 – Friday, 11/25: Thanksgiving break – No Classes_

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 11/14
|Mon 11/11

|*Sprint End Date*
|Sun 12/1
|Sun 12/1

|*Due Date*
2+| Wed 12/4 by 11:59 PM ET

|===

Final Fall Presentations: December 2, 2024 - December 6, 2024
* To recap the semester, your team will present on project progress and future goals. Please review the following Guidelines for the Final Presentation: Final Fall Presentation Details. During this sprint, your team should complete a first draft of your presentation and continue working on this presentation until the final week of term when you will present to your CRP mentors and the Data Mine staff. 

== To Do 

&#10003; See the xref:fall2024/schedule.adoc[Fall Schedule] for timesheet and report deadlines.

&#10003; Grade Sprint #6 & Complete Team Report #6 on link:https://www.gradescope.com/[Gradescope] by Wednesday 11/27 at 11:59PM EST.

&#10003; Final Semester Feedback completed with mentor

* *What:* Meet with the corporate partner mentor to discuss individual student's work and engagement in the project.
* *When:* Due Wednesday, December 4 at 11:59 PM EST

**Please share the link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module5_4_mentor_feedback[Mentor and TA Feedback Guide] with your mentor ahead of time so they may prepare. 

&#10003; Complete project charter review with student team.

&#10003;Complete the Corporate Partners Mid-year Final Survey individually. 

* *Where:* Follow the Qualtrics link to complete and submit the final report. You do not need to submit anything in Gradescope.
link:https://purdue.ca1.qualtrics.com/jfe/form/SV_5pSI5u5fhLfLjb8[Qualtrics Survey] 

* *When:* Due Wednesday, December 4, 2024 at 11:59 PM ET. Late work will not be accepted. 

&#10003; Review Sprint Tasks for students: xref:students:fall2024/sprint7.adoc[Sprint 7 Tasks]. 

&#10003; Complete Team Report #7 by Sunday, December 8 at 11:59 EST on link:https://www.gradescope.com/[Gradescope]

== Sprint Schedule

=== Team Meeting #1 (50 minutes): 

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
* Ensure students are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #1 (1 hour and 50 Minutes): 

* Final preparation for Final Fall Presentations. Data Mine Staff will grade draft presentations and provide feedback on presentations during lab time. Please review Data Mine Staff feedback on presentation with the team. Then, work with the student team to make necessary changes to your team's presentation.
* Review the Project Charter with your team and provide updates/edits in RED. KEEP all the original descriptions, but each section must be reviewed, and edits should be provided in RED. Ensure your team updates the Fall objectives and purpose, Spring objectives and purpose, as well as the timeline. If a section does not need to be edited, please indicate that the charter is accurate. 

=== Team Meeting #2 (50 minutes):

* Final Fall Presentation! Unless otherwise scheduled with your mentor or liaison, your presentation will given during this meeting time.  

=== Lab Section #2 (1 hour and 50 Minutes):

* Review the Project Charter with your team and provide updates/edits in RED. KEEP all the original descriptions, but each section must be reviewed, and edits should be provided in RED. Ensure your team updates the Fall objectives and purpose, Spring objectives and purpose, as well as the timeline. If a section does not need to be edited, please indicate that the charter is accurate. 

*When*: Due Friday, December 6 at 11:59pm EST.  

*Where*: Upload Project Charter with revisions to link:https://www.gradescope.com/[Gradescope]
PDF is the preferred format, but .docx and .pptx are also acceptable. 