= Spring 2025 Office Hours Schedule

[IMPORTANT]
====
Office hours before 5 PM on weekdays (Monday through Friday) will be offered both in-person in the lobby of Hillenbrand Hall, and also virtually.

Office hours on Sundays (all day) and also on weekdays after 5 PM will be held exclusively virtually.

Office Hours Zoom Link: https://purdue-edu.zoom.us/s/97774213087

Checklist for the Zoom Link:

* When joining office hours, please include your Data Mine level in front of your name. For example, if you are in TDM 102, your name should be entered as "102 - [Your First Name] [Your Last Name]".

* After joining the Zoom call, please stay in the main room until a TA invites you to a specific breakout room.

* We will continue to follow the office hours schedule as posted on the Examples Book. (https://the-examples-book.com/projects/spring2025/office_hours)
====

[NOTE]
====
The below calendars represent regularly occurring office hours. Please check your class' Piazza page to view the latest information about any upcoming changes or cancellations for office hours prior to attending.

Our Piazza links are:
 
TDM 10200: https://piazza.com/purdue/fall2024/tdm1010010200202425

TDM 20200: https://piazza.com/purdue/fall2024/tdm2010020200202425

TDM 30200: https://piazza.com/purdue/fall2024/tdm3010030200202425

TDM 40200: https://piazza.com/purdue/fall2024/tdm4010040200202425

====

== TDM 10200 Office Hours:

https://the-examples-book.com/projects/spring2025/office_hours_10200[Click here for TDM 10200 Office Hours]

== TDM 20200 Office Hours:

https://the-examples-book.com/projects/spring2025/office_hours_20200[Click here for TDM 20200 Office Hours]

== TDM 30200 and 40200 Office Hours:

https://the-examples-book.com/projects/spring2025/office_hours_30200_40200[Click here for TDM 30200 and 40200 Office Hours]

