= 401 Project 10 - Regression: Perceptrons

== Project Objectives

In this project, we will be learning about perceptrons and how they can be used for regression. We will be using the Boston Housing dataset as it has many different potential features and target variables.

.Learning Objectives
****
- 
****

== Supplemental Reading and Resources

== Dataset

- `/anvil/projects/tdm/data/boston_housing/boston.csv`

== Questions

=== Question 1 (2 points)

A perceptron is a simple model that can be used for regression. These perceptrons can be combined together to create neural networks. In this project, we will be creating a perceptron from scratch.

To start, let's load in the Bostong Housing dataset with the below code:
[source,python]
----
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
df = pd.read_csv('/anvil/projects/tdm/data/boston_housing/boston.csv')

X = df.drop(columns=['MEDV', 'CRIM'])
y = df[['MEDV', 'CRIM']]

scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=7)
----

Now, we can begin discussing what a perceptron is. A perceptron is a simple model 

.Deliverables
====
- 
====

=== Question 2 (2 points)

.Deliverables
====
- 
====

=== Question 3 (2 points)

.Deliverables
====
- 
====

=== Question 4 (2 points)

.Deliverables
====
- 
====

=== Question 5 (2 points)

.Deliverables
====
- 
====

=== Question 6 (2 points)

.Deliverables
====
- 
====

== Submitting your Work

.Items to submit
====
- firstname_lastname_project10.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====