= TDM 40100

== Important links

xref:fall2024/logistics/office_hours_401.adoc[[.custom_button]#Office Hours#]
xref:fall2024/logistics/401_TAs.adoc[[.custom_button]#TA List#]
xref:fall2024/logistics/syllabus.adoc[[.custom_button]#Syllabus#]
https://piazza.com/purdue/fall2023/tdm40100/home[[.custom_button]#Piazza Homepage#]
https://piazza.com/purdue/fall2023/tdm40100[[.custom_button]#Piazza Sign-up#]

== Assignment Schedule

[NOTE]
====
Only the best 10 of 14 projects will count towards your grade.
====

[CAUTION]
====
Topics are subject to change. While this is a rough sketch of the project topics, we may adjust the topics as the semester progresses.
====

|===
| Assignment | Release Date | Due Date
| Syllabus Quiz | 19-08-2024 | 30-08-2024
| Academic Integrity Quiz | 19-08-2024 | 30-08-2024
| Project 1 -  | 19-08-2024 | 30-08-2024
| Project 2 - | 22-08-2024 | 30-08-2024
| Project 3 -  | 29-08-2024 | 06-09-2024
| Project 4 -  | 05-09-2024 | 13-09-2024
| Outside Event 1 | 19-08-2024 | 13-09-2024 
| Project 5 -  | 12-09-2024 | 20-09-2024
| Project 6 -  | 19-09-2024 | 27-09-2024
| Project 7 -  | 26-09-2024 | 04-10-2024
| Outside Event 2 | 19-08-2024 | 04-10-2024
| Project 8 -  | 03-10-2024 | 18-10-2024
| Project 9 -  | 17-10-2024 | 25-10-2024
| Project 10 -  | 24-10-2024 | 01-11-2024
| Project 11 -  | 31-10-2024 | 08-11-2024
| Outside Event 3 | 19-08-2024 | 08-11-2024
| Project 12 -  | 07-11-2024 | 15-11-2024
| Project 13 -  | 14-11-2024 | 22-11-2024
| Project 14 -  | 21-11-2024 | 06-12-2024
|===

[WARNING]
====
Projects are **released on Thursdays**, and are due 1 week and 1 day later on the following **Friday, by 11:59pm**. Late work is **not** accepted. We give partial credit for work you have completed -- **always** submit the work you have completed before the due date. If you do _not_ submit the work you were able to get done, we will _not_ be able to give you credit for the work you were able to complete.

// **Always** double check that the work that you submitted was uploaded properly. See xref:current-projects:submissions.adoc[here] for more information.

Each week, we will announce in Piazza that a project is officially released. Some projects, or parts of projects may be released in advance of the official release date. **Work on projects ahead of time at your own risk.**  These projects are subject to change until the official release announcement in Piazza.
====