= TDM 10100: Project 5 -- Fall 2022
Tapply and DataFrames

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_ttsk2n6t?wid=_983291"></iframe>
++++

**Motivation:** `R` differs from other programming languages that _typically_  work best using vectorized functions and the _apply_ suite instead of using loops. 

.Insider Knowledge
[%collapsible]
====
Apply Functions: are an alternative to loops. You can use *`apply()`* and its varients (i.e. mapply(), sapply(), lapply(), vapply(), rapply(), and tapply()...) to manuiplate peices of data from data.frames, lists, arrays, matrices in a repetative way. The *`apply()`* functions allow for flexiabilty in crossing data in multiple ways that a loop does not.
====

**Context:** We will focus in this project on efficient ways of processing data in `R`.

**Scope:** r, data.frames, recycling, factors, if/else, for loops, apply suite

.Learning Objectives
****
- Demonstrate the ability to use the `tapply` function.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s) in anvil:

/anvil/projects/tdm/data/election/escaped2020sample.txt

.Helpful Hint
[%collapsible]
====
A txt and csv file both sore information in plain text. *csv* files are _always_ separated by commas. In *txt* files the fields can be separated with commas, semicolons, or tab. 


To read in a txt file as a csv we simply add sep="|" (see code below)
[source,r]
----
 myDF <- read.csv("/anvil/projects/tdm/data/election/escaped2020sample.txt", sep="|")
----
====

== Questions

=== ONE

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_t2adfk4u?wid=_983291"></iframe>
++++

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_undlfl0o?wid=_983291"></iframe>
++++

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_db31nrf8?wid=_983291"></iframe>
++++

Read the dataset `escaped2020sample.txt` into a data.frame called `myDF`. The dataset contains contribution information for the 2020 election year.

The dataset has a column named `TRANSACTION_DT` which is set up in the `[month].[day].[year]` format. 
We want to organize the dates in chronological order. 

When working with dates, it is important to use tools specifically for this purpose (rather than using string manipulation, for example). We've provided you with the code below. The provided code uses the `lubridate` package, an excellent package which hides away many common issues that occur when working with dates. Feel free to check out https://raw.githubusercontent.com/rstudio/cheatsheets/master/lubridate.pdf[the official cheatsheet] in case you'd like to learn more about the package.

[source,r]
----
library(lubridate, warn.conflicts = FALSE)
----

[loweralpha]
.. Use the `mdy` function (from the `lubridate` library) on the column `TRANSACTION_DT`, to create a new column named `newdates`.
.. Using `tapply`, add the values in the `TRANSACTION_AMT` column, according to the values in the `newdate` column.
.. Plot the dates on the x-axis and the information we found in part b on the y-axis.

.Helpful Hint
[%collapsible]
====
*tapply()* helps us to compute statistical measures such as mean, median, minimum, maximum, sum, etc... for data that is split into groups. *tapply()* is most helpful when we need to break up a vector into groups, and compute a function on each of the groups.
====

[WARNING]
====
If your `tapply` in Question 1b hates you (e.g., it will absolutely not finish the `tapply`, even after a few minutes), then the fix described below will likely help.  Please note that, after you run this fix, you need to reset your memory back to 5000 MB at time 4:16 in the video.

You do not need to run this "fix" unless you have a cell like this, which should be running, but you are "stuck" on it:
====

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_m37n59j2?wid=_983291"></iframe>
++++

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== TWO

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_cg7vwni6?wid=_983291"></iframe>
++++

The plot that we just created in question one shows us that the majority of the data collected is found in the years 2018-2020.  So we will focus on the year 2019.

[loweralpha]
.. Create a new dataframe that only contains data for the dates in the range 01/01/2019-05/15/2019
.. Plot the new dataframe 
.. What do you notice about the data?

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- Answer to the questions above
====

=== THREE

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_uwajsx7z?wid=_983291"></iframe>
++++

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_wu96qqja?wid=_983291"></iframe>
++++

Lets look at the donations by city and state

[loweralpha]
.. Find the sum of the total donations contributed in each state.
.. Create a new column that pastes together the city and state.
.. Find the total donation amount for each city/state location.  In the output do you notice anything suspicious in the result? How do you think that occurred?

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- Answers to the questions above.
====

=== FOUR

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_5335wwv1?wid=_983291"></iframe>
++++

Lets take a look who is donating 

[loweralpha]
.. Find the type of data that is in the `NAME` columm
.. Split up the names in the `NAME` column, to extract the first names of the donors.  (This will not be perfect, but it is our first attempt.)
.. How much money is donated (altogether) by people named `Mary`?

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- Answer to the questions above
====

=== FIVE

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_dpsjs2t3?wid=_983291"></iframe>
++++

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_9bq3bc73?wid=_983291"></iframe>
++++

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_psgbfiqe?wid=_983291"></iframe>
++++

Employment status

[loweralpha]
.. Using a `barplot` or `dotchart`, show the total amount of donations made by `EMPLOYED` vs `NOT EMPLOYED` individuals
.. What is the category of occupation that donates the most money?
.. Plot something that you find interesting about the employment and/or occupation columns

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- 1-2 sentences explaining what is was you chose to plot and why
- Answering to the questions above
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
