= TDM 10100: Project 13 -- 2022

**Motivation:** This semester we took a deep dive into `R` and it's packages. Lets take a second to pat ourselves on the back for surviving a long semester and review what we have learned! 

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- /anvil/projects/tdm/data/beer/beers.csv

== Questions

=== ONE

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_hjlpsvtu&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++

Read in the dataset and into a data.frame called `beer`
[loweralpha]
. What is the file size, how many rows, columns and type of data?
. What is the average score for a `stout`? (consider a stout any named beer from the column `name` with the word `stout` in it)
. How many `Pale Ale's` are on this list? (consider a stout any named beer from the column `name` with the word `pale` and `ale` in it)


.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== TWO

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_stltxfhx?wid=_983291"></iframe>
++++

. Plot or Graph all the beers that are available in the summer and their ratings.

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== THREE

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_uwvx1gze?wid=_983291"></iframe>
++++

. Create a plot of the average rating of beer by country.

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== FOUR

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_4fzvjp6k?wid=_983291"></iframe>
++++

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_5rnyo1ie?wid=_983291"></iframe>
++++

. Do `limited` runs of beer have a greater median rating than all others?
(consider limited to be any beer that has the word `Limited` in the `availability` column) 

. Use the `unique` function to investigate the availability column. Why are there different labels that are technically the same?

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
