= Amazon

== Source

The Amazon fine food reviews are available to download here:

https://www.kaggle.com/datasets/snap/amazon-fine-food-reviews

The Million Song Dataset is the original source of the music and tracks data; it is available here:

http://millionsongdataset.com/

== Description of the Data

Three data sets:

`amazon_fine_food_reviews.csv` and `amazon_fine_food_reviews.sqlite` contain reviews from Amazon about food products

`music.txt` contains reviews from Amazon about music

`tracks.csv` and `tracks.db` contain metadata about music tracks available from Amazon

== Transformations to the original data source

The file `amazon_fine_food_reviews.csv` is created from `Reviews.csv` (the original source file) by using R to remove the commas (not replacing them with spaces) that are internal to any of the 10 columns.  The file `amazon_fine_food_reviews.sqlite` is downloaded from the source and not transformed.

We believe that we built the music and tracks files using these steps:

https://tech.marksblogg.com/importing-data-from-s3-into-redshift.html





