= Bay Area Bike Share

== Source

The data is available in two times ranges.

The data from August 2013 to August 2015 is available here:
https://www.kaggle.com/datasets/benhamner/sf-bay-area-bike-share
and the metadata is available here:
https://www.kaggle.com/datasets/benhamner/sf-bay-area-bike-share/discussion/23165
This data is available in the `archive.zip` file too.

The data from 2017 to 2023 is available here:
https://s3.amazonaws.com/baywheels-data/index.html

== Description of the Data

Data about bicycle rides in the bay at San Francisco.
Most recently downloaded in July 2023.

== Transformations to the original data source

The data from 2017 to 2023 is available by running:

wget https://s3.amazonaws.com/baywheels-data/202012-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202101-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202102-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202103-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202104-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202105-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202106-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202107-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202108-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202109-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202110-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202111-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202112-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202201-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202202-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202203-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202204-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202205-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202206-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202207-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202208-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202209-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202210-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202211-baywheeels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202212-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202301-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202302-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202303-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202304-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202305-baywheels-tripdata.csv.zip
wget https://s3.amazonaws.com/baywheels-data/202306-baywheels-tripdata.csv.zip

and then we can unzip the files by running:
ls *.zip | awk '{print "unzip "$0}' | bash

and then throw away the zip files by running:
rm *.zip

and throw away the Mac folder:
rm -rf __MACOSX

