= chinook

== Source

Chinook is a SQLite database of digital media store data comes from Kaggle:

https://www.kaggle.com/datasets/ranasabrii/chinook

== Description of the Data

The data represents a digital media store with tables for artists, albums, media tracks, invoices and customers. The updated version of the chinook data is available here (it was slightly updated in 2022):

https://github.com/lerocha/chinook-database/tree/master/ChinookDatabase/DataSources

It has an interesting name. Let’s check the reason behind it on the webpage: "The name of this sample database was based on the Northwind database. Chinooks are winds in the interior West of North America, where the Canadian Prairies and Great Plains meet various mountain ranges. Chinooks are most prevalent over southern Alberta in Canada. Chinook is a good name choice for a database that intents to be an alternative to Northwind."*

== Transformations to the original data source

In June 2020, Kevin downloaded the `chinook.db` and `chinook.sql` versions of the data to Anvil.

In July 2023, Mark downloaded the new versions, which are only very slightly updated:

`Chinook_Sqlite.sql`

`Chinook_Sqlite.sqlite`

* Source: https://github.com/lerocha/chinook-database/blob/master/README.md (Accessed at 10/09/2025)

Note: The Northwind database is a sample dataset originally developed by Microsoft and has served as the foundation for tutorials across many of their database products for decades.