= Consumer Complaints

== Source

The consumer complaints data is available from the federal government:

https://www.consumerfinance.gov/data-research/consumer-complaints/#download-the-data

== Description of the Data

The data set contains information about consumer complaints and the responses from companies.

The downloaded data set has two versions:

`complaints.csv` and `complaints.json`

In July 2023, Mark added a transformed version called `processed.csv` in which each line has 18 fields (see below).

== Transformations to the original data source

Kevin originally downloaded this data set in June 2021.  He created three transformations of the original data set:

`processed.csv`

`processed.feather`

`processed.parquet`

Kevin removed all commas from the data set.  For instance, if a consumer complaint had commas in the text data, he removed them.  That way, every line contained 19 fields (a line number and the original 18 fields).

In July 2023, Mark downloaded the updated consumer complaint data.  Mark transformed the `complaints.csv` into a file called `processed.csv` using R by: removing all commas; replacing each "\\n\\n" with "\\n"; and then replacing "\\n" with " ".  In particular, Mark did not add a line number, so Mark's version of `processed.csv` has only the original 18 fields per line, and no added line numbers.

Mark did not (yet) make a `feather` or `parquet` version of the data set.




