= Disney

== Source

Disney World data is provided by:

https://touringplans.com/walt-disney-world/crowd-calendar#DataSets

The data was most recently updated by `touringplans.com` in December 2021.

== Description of the Data

This data has descriptions of posted waiting times and actual waiting times for rides at Disney World.

In addition to information about 52 rides (with 1 `csv` file per ride), there is a

Data Dictionary: `touringplans_data_dictionary.xlsx`

Metadata: `metadata.csv`

and Facts: `entities.csv`


== Transformations to the original data source

Kevin created a `total.parquet` file in March 2023, containing the data from all entries.

To download the data, we can run:

wget https://cdn.touringplans.com/datasets/touringplans_data_dictionary.xlsx

wget https://cdn.touringplans.com/datasets/metadata.csv

wget https://cdn.touringplans.com/datasets/entities.csv

wget https://cdn.touringplans.com/datasets/pirate_s_adventure.csv

wget https://cdn.touringplans.com/datasets/ariel_s_grotto.csv

wget https://cdn.touringplans.com/datasets/astro_orbiter.csv

wget https://cdn.touringplans.com/datasets/barnstormer.csv

wget https://cdn.touringplans.com/datasets/big_thunder_mtn.csv

wget https://cdn.touringplans.com/datasets/buzz_lightyear.csv

wget https://cdn.touringplans.com/datasets/carousel_of_progress.csv

wget https://cdn.touringplans.com/datasets/casey_jr_splash.csv

wget https://cdn.touringplans.com/datasets/country_bears.csv

wget https://cdn.touringplans.com/datasets/dumbo.csv

wget https://cdn.touringplans.com/datasets/ench_tales_w__belle.csv

wget https://cdn.touringplans.com/datasets/hall_of_presidents.csv

wget https://cdn.touringplans.com/datasets/haunted_mansion.csv

wget https://cdn.touringplans.com/datasets/it_s_a_small_world.csv

wget https://cdn.touringplans.com/datasets/jungle_cruise.csv

wget https://cdn.touringplans.com/datasets/liberty_sq_riverboat.csv

wget https://cdn.touringplans.com/datasets/mad_tea_party.csv

wget https://cdn.touringplans.com/datasets/magic_carpets.csv

wget https://cdn.touringplans.com/datasets/main_st_vehicles.csv

wget https://cdn.touringplans.com/datasets/town_sq_mickey.csv

wget https://cdn.touringplans.com/datasets/town_sq_tink.csv

wget https://cdn.touringplans.com/datasets/philharmagic.csv

wget https://cdn.touringplans.com/datasets/laugh_floor.csv

wget https://cdn.touringplans.com/datasets/peoplemover.csv

wget https://cdn.touringplans.com/datasets/pete_s__goofy_donald.csv

wget https://cdn.touringplans.com/datasets/pete_s__minnie_daisy.csv

wget https://cdn.touringplans.com/datasets/peter_pan_s_flight.csv

wget https://cdn.touringplans.com/datasets/pirates_of_caribbean.csv

wget https://cdn.touringplans.com/datasets/regal_carrousel.csv

wget https://cdn.touringplans.com/datasets/princess_hall__cinderella_elena.csv

wget https://cdn.touringplans.com/datasets/princess_hall__rapunzel_tiana.csv

wget https://cdn.touringplans.com/datasets/7_dwarfs_train.csv

wget https://cdn.touringplans.com/datasets/sorcerers_of_the_mk.csv

wget https://cdn.touringplans.com/datasets/space_mountain.csv

wget https://cdn.touringplans.com/datasets/splash_mountain.csv

wget https://cdn.touringplans.com/datasets/swiss_family_tree.csv

wget https://cdn.touringplans.com/datasets/winnie_the_pooh.csv

wget https://cdn.touringplans.com/datasets/tom_sawyer_island.csv

wget https://cdn.touringplans.com/datasets/tom_land_speedway.csv

wget https://cdn.touringplans.com/datasets/under_the_sea.csv

wget https://cdn.touringplans.com/datasets/enchanted_tiki_rm.csv

wget https://cdn.touringplans.com/datasets/soarin.csv

wget https://cdn.touringplans.com/datasets/spaceship_earth.csv

wget https://cdn.touringplans.com/datasets/alien_saucers.csv

wget https://cdn.touringplans.com/datasets/rock_n_rollercoaster.csv

wget https://cdn.touringplans.com/datasets/slinky_dog.csv

wget https://cdn.touringplans.com/datasets/toy_story_mania.csv

wget https://cdn.touringplans.com/datasets/flight_of_passage.csv

wget https://cdn.touringplans.com/datasets/dinosaur.csv

wget https://cdn.touringplans.com/datasets/expedition_everest.csv

wget https://cdn.touringplans.com/datasets/kilimanjaro_safaris.csv

wget https://cdn.touringplans.com/datasets/navi_river.csv



