= election

== Source

The data about campaign donations at the federal level is downloadable from:

https://www.fec.gov/data/browse-data/?tab=bulk-data

under the section on "Contributions by individuals"

== Description of the Data

The names, addresses, and amounts of money donations by individuals is given, during each 2-year election campaign cycle.

There is also one file called `escaped2020sample.txt` (see below).

== Transformations to the original data source

The file `escaped2020sample.txt` contains a fraction of the data from the `itcont2020.txt` file, with the data fields surrounded by double quotes.

To download the original data sources, we run:

wget https://www.fec.gov/files/bulk-downloads/1980/indiv80.zip

wget https://www.fec.gov/files/bulk-downloads/1982/indiv82.zip

wget https://www.fec.gov/files/bulk-downloads/1984/indiv84.zip

wget https://www.fec.gov/files/bulk-downloads/1986/indiv86.zip

wget https://www.fec.gov/files/bulk-downloads/1988/indiv88.zip

wget https://www.fec.gov/files/bulk-downloads/1990/indiv90.zip

wget https://www.fec.gov/files/bulk-downloads/1992/indiv92.zip

wget https://www.fec.gov/files/bulk-downloads/1994/indiv94.zip

wget https://www.fec.gov/files/bulk-downloads/1996/indiv96.zip

wget https://www.fec.gov/files/bulk-downloads/1998/indiv98.zip

wget https://www.fec.gov/files/bulk-downloads/2000/indiv00.zip

wget https://www.fec.gov/files/bulk-downloads/2002/indiv02.zip

wget https://www.fec.gov/files/bulk-downloads/2004/indiv04.zip

wget https://www.fec.gov/files/bulk-downloads/2006/indiv06.zip

wget https://www.fec.gov/files/bulk-downloads/2008/indiv08.zip

wget https://www.fec.gov/files/bulk-downloads/2010/indiv10.zip

wget https://www.fec.gov/files/bulk-downloads/2012/indiv12.zip

wget https://www.fec.gov/files/bulk-downloads/2014/indiv14.zip

wget https://www.fec.gov/files/bulk-downloads/2016/indiv16.zip

wget https://www.fec.gov/files/bulk-downloads/2018/indiv18.zip

wget https://www.fec.gov/files/bulk-downloads/2020/indiv20.zip

wget https://www.fec.gov/files/bulk-downloads/2022/indiv22.zip

wget https://www.fec.gov/files/bulk-downloads/2024/indiv24.zip

unzip indiv80.zip

mv itcont.txt itcont80.txt

unzip indiv82.zip

mv itcont.txt itcont82.txt

unzip indiv84.zip

mv itcont.txt itcont84.txt

unzip indiv86.zip

mv itcont.txt itcont86.txt

unzip indiv88.zip

mv itcont.txt itcont88.txt

unzip indiv90.zip

mv itcont.txt itcont90.txt

unzip indiv92.zip

mv itcont.txt itcont92.txt

unzip indiv94.zip

mv itcont.txt itcont94.txt

unzip indiv96.zip

mv itcont.txt itcont96.txt

unzip indiv98.zip

mv itcont.txt itcont98.txt

unzip indiv00.zip

mv itcont.txt itcont00.txt

unzip indiv02.zip

mv itcont.txt itcont02.txt

unzip indiv04.zip

mv itcont.txt itcont04.txt

unzip indiv06.zip

mv itcont.txt itcont06.txt

unzip indiv08.zip

mv itcont.txt itcont08.txt

unzip indiv10.zip

mv itcont.txt itcont10.txt

unzip indiv12.zip

mv itcont.txt itcont12.txt

unzip indiv14.zip

mv itcont.txt itcont14.txt

unzip indiv16.zip

mv itcont.txt itcont16.txt

unzip indiv18.zip

mv itcont.txt itcont18.txt

unzip indiv20.zip

mv itcont.txt itcont20.txt

unzip indiv22.zip

mv itcont.txt itcont22.txt

unzip indiv24.zip

mv itcont.txt itcont24.txt

rm *.zip

rm -rf by_date

