= Iowa liquor sales

== Source

The state of Iowa provides data about liquor sales, available here for download:

https://data.iowa.gov/Sales-Distribution/Iowa-Liquor-Sales/m3tr-qhgy

The direct download link is:

https://data.iowa.gov/api/views/m3tr-qhgy/rows.csv?accessType=DOWNLOAD

Kaggle provided earlier versions of this data set:

https://www.kaggle.com/datasets/residentmario/iowa-liquor-sales

== Description of the Data

The original data set is `iowa_liquor_sales.csv`.

Each row of the data set corresponds to an alcohol purchase at a store in Iowa.  Information is given about the type of alcohol purchased, the amount, the cost, the location of the store, etc.

== Transformations to the original data source

Mark created a version called `iowa_liquor_sales_cleaner.txt` from the original data set by importing the data into R using `fread`, and changing the name of "CNS IMPORTS; FOUR SEASONS TRADING; CNS WINE & SPIRITS" to be (instead) "CNS IMPORTS, FOUR SEASONS TRADING, CNS WINE & SPIRITS", and then exporting the data into a csv file using a semicolor `;` as the delimiter.


