= TIGER/Line Shapefiles Dataset Description

== Source
The dataset is from https://catalog.data.gov/dataset/tiger-line-shapefile-2021-nation-u-s-states-and-equivalent-entities/resource/2c2a9b10-39cd-4a6a-98fc-bf9d55c3b281?inner_span=True[catalog data gov].

== Description of the Data
TIGER (Topologically Integrated Geographic Encoding and Referencing system)/Line Shapefiles is provided by the US Census Bureau, providing geospatial data on legal state and natioanl boundaries, as well as geographical attributes such as roads/transportation and bodies of water. 

Following is the 2021 TIGER Technical Documentation: https://www2.census.gov/geo/pdfs/maps-data/data/tiger/tgrshp2021/TGRSHP2021_TechDoc.pdf

TIGER has multiple data products, and the TIGER/Line Shapefiles is the most comprehensive dataset, consisting of shapefiles and database files. Each record represents geographical entities (for example, a state) and the dataset covers all US states and equivalent entities: 50 states, District of Columbia, Puerto Rico, territories. 
