= NDMN Meeting Times

== ATOM - Small Molecule Data Driven Modeling for Drug Discovery
=== *Lecture Time:*  Monday: 12:30 - 13:20pm ET
=== *Lab Time:* Friday: 12:30 - 14:20pm ET
https://projects.the-examples-book.com/projects/small-molecule-data-driven-modelling-for-drug-discover-ndmn/[Click here for the project description]


== BASF - Market Models
=== *Lecture Time:*  Tuesday: 11:30 - 12:20pm ET
=== *Lab Time:* Thursday: 10:30 - 12:20pm ET
https://projects.the-examples-book.com/projects/basf-market-models/[Click here for the project description]


== Center for C-SPAN Scholarship and Education - Analysis of Rhetoric on Capitol Hill
=== *Lecture Time:*  Tuesday: 12:30 - 13:20pm ET
=== *Lab Time:* Thursday: 11:30 - 13:20pm ET
https://projects.the-examples-book.com/projects/analysis-of-rhetoric-on-capitol-hill/[Click here for the project description]


== Elanco - Knowledge Graphs Biomedical Discovery
=== *Lecture Time:*  Monday: 15:30 - 16:20pm ET
=== *Lab Time:* Friday: 15:30 - 17:20pm ET
https://projects.the-examples-book.com/projects/knowledge-graphs-biomedical-discovery/[Click here for the project description]


== FSSA - Predicting Medical Outcomes 
=== *Lecture Time:*  Monday: 10:30 - 11:20pm ET
=== *Lab Time:* Friday: 9:30 - 11:20pm ET
https://projects.the-examples-book.com/projects/predicting-medical-outcomes-ndmn/[Click here for the project description]


== Molecular Stethoscope - Translational Data Science
=== *Lecture Time:*  Friday: 15:30 - 16:20pm ET
=== *Lab Time:* Monday: 15:30 - 17:20pm ET
https://projects.the-examples-book.com/projects/translational-data-science/[Click here for the project description]


== Renzoe Box - Renzoe Quiz
=== *Lecture Time:*  Tuesday: 15:30 - 16:20pm ET
=== *Lab Time:* Thursday: 15:30 - 17:20pm ET
https://projects.the-examples-book.com/projects/renzoe-quiz/[Click here for the project description]


== Stratolaunch - Marketing Analytics
=== *Lecture Time:*  Friday: 15:30 - 16:20pm ET
=== *Lab Time:* Monday: 15:30 - 17:20pm ET
https://projects.the-examples-book.com/projects/marketing-analytics/[Click here for the project description]


== USAA - Determining Customer Intent
=== *Lecture Time:*  Friday: 13:30 - 14:20pm ET
=== *Lab Time:* Monday: 12:30 - 14:20pm ET
https://projects.the-examples-book.com/projects/determining-customer-intent/[Click here for the project description]


== V2X - ChatBot vs NLP Classification
=== *Lecture Time:*  Thursday: 12:30 - 1:20pm ET
=== *Lab Time:* Tuesday: 12:30 - 2:20pm ET
https://projects.the-examples-book.com/projects/chatbot-vs-nlp-classification/[Click here for the project description]
