= SQL
:page-aliases: introduction.adoc

SQL (Structure Query Language) is a language used to manage data in a relational database management system (RDBMS). Popular RDBMS's include names like: Postgresql, Oracle, MySQL, SQLite, MariaDB, and Microsoft SQL Server. SQL enables the user to write queries that quickly create, read, update, delete, and summarize data. 

Standard SQL can be used with any of the mentioned RDBMS's without change. With that being said, the way the RDBMS's function can vary. For example, Postgresql has clients and servers, whereas SQLite is a single program. Additionally, most RDBMS's have extensions that add supplementary, non-standard features, and each can have slight https://www.datacamp.com/community/blog/sql-differences[syntax differences].

* xref:index.adoc[SQL]
* xref:sql-books.adoc[SQL books]
* xref:terminology.adoc[Terminology]
* xref:queries.adoc[Queries]
* xref:baseball-examples.adoc[SQL Baseball examples]
* xref:chinook-examples.adoc[SQL Chinook examples]
* xref:stat-llc-sql-examples.adoc[SQL examples from the STAT-LLC]
* xref:aliasing.adoc[Aliasing]
* xref:aggregate-functions.adoc[Aggregate functions]
* xref:joins.adoc[Joins]

== Resources

https://www.w3schools.com/sql/[W3Schools SQL Introduction]

A speedy overview and reference to get started with SQL.

== Downloads

It is possible to http://dev.mysql.com/downloads/[download MySQL Community Server] or http://www.sqlite.org/download.html[download SQLite] at no charge.

== Documentation

The http://www.mysql.com/[MySQL webpage] provides http://dev.mysql.com/doc/[extensive documentation].

SQLite is another popular database engine. The http://www.sqlite.org/[SQLite webpage] provides a https://www.sqlite.org/about.html[succinct description] of the SQLite database engine. It also provides a webpage of http://www.sqlite.org/docs.html[more documentation].

