= STAT-LLC 2018 SQL Exercises

== Project 7

Question 1.

What percent of batters are lefties?  Switchhitters?

Question 2.

Which team has hit the most home runs altogether?

Question 3.

Find the player who had the largest number of doubles in one season.

Question 4.

During which years was Jackie Robinson active in baseball?  Check your solution by comparing the results from the SQL database with a resource online.

Question 5.

Find the statistics for how many home runs that Ernie Banks hit with a year-by-year breakdown, while he was playing for the Chicago Cubs.  FYI, Ernie Banks was awarded the Presidential Medal of Freedom in 2013, for his contribution to sports.

Question 6.

Make a dotchart of the number of home runs hit by Derek Jeter each year.

Question 7.

Find the first and last names of all the players who attended Purdue University.

Question 8.

Find the first and last names of all the players who attended college anywhere in Indiana.

Question 9.

Find all teams that won 105 or more games in a season. List the year, the team's full name, the number of wins in that season, and the first and last name of the manager for the team.

Question 10.

Find all players who stole 100 or more bases. For each such player, list the player's first name, last name, the number of bases stolen, and the year.

Question 11.

For each pitcher who had 20 or more wins, list the player's first name, last name, number of wins, and the relevant year.

Question 12.

Consider the total number of saves by pitchers during their entire careers. A few pitchers had 300 or more saves during their careers. Make a list of all such pitchers. For each such pitcher, give his first name, last name, and the total number of saves that the pitcher had during his career.

Question 13.

Same question as 12, but instead of finding pitchers with 300 or more saves, find pitchers with 2000 or more strikeouts during their careers.

Question 14.

Plot how many players were born in each state.

Question 15.

a.  Which manager's teams have had the most home runs overall?

b.  Which manager's teams have had the most stolen bases overall?



== Project 8

Question 2.

a.  Use the master table from the SQL database to find the number of baseball players born in each state.

b.  Use the (built-in) state.abb to extract the results from the 50 US States (only).

Question 4.

Use the "pairs" function or another function of your choice to make a figure that compares the total number of baseball players born in each state.

