= STAT-LLC Fall 2016 STAT 29000 Projects

== Project 1

Use the data set from the http://stat-computing.org/dataexpo/2009/[Data Expo 2009]

to answer the following questions.

A description of the data is given http://stat-computing.org/dataexpo/2009/the-data.html[here]

All of the data is already downloaded for you on the llc server here:

`/data/public/dataexpo2009/`

Please save your solutions in a file named, for instance, if you are group 3:

`/proj/gpproj16/p01g3/p01g3.txt`

Question 1.

1.  How many distinct airport codes appear:

a.  In the origin column?

b.  In the destination column?

c.  Altogether?

Question 2.

a.  Use cut (it is always OK to use other commands in tandem, if needed) to find how many flights arrive or depart from IND.  Hint: You might need more than 1 line of code for this problem.  It might be helpful to try your code on individual years before you try it on the entire data set.

b.  For a much faster solution, use grep to see how many flights arrive or depart from IND.

Question 3.

How many tailnums have the following kids of errors:

a.  Equal to NA?

b.  Equal to 0?

c.  Equal to 000000?

d.  The phrase NKNO is part of the tailnum?

e.  The tailnum is blank, i.e., consisting only of zero or more whitespace characters but no other content?

Question 4.

Which 10 planes took the most flights overall?

Question 5.

a.  How many airplane flights did the airplane with tailnum N528 make altogether?

b.  What was the largest number of flights that this airplane ever made during a single day?

c.  How many flights did this airplane make on November 3, 1995?

Question 6.

How many flights has each airline had (as an Origin) from each airport?  E.g., give a list of all pairs of (Origin) airports and airlines, with the associated counts.  Please sort from the highest count to the lowest count.  This question should give you some insight about which airports are hubs for which airlines.

Question 7.

How many airplane flights occur per year?

== Project 2

Please refer to Chapters 1, 2, 3 of
this book on `sed` and `awk` (we only cover `awk`)

http://proquestcombo.safaribooksonline.com.ezproxy.lib.purdue.edu/1565922255

or to the http://www.gnu.org/software/gawk/manual/[awk manual] itself:

Question 1.

a.  How many users are on the llc machine?

b.  If we restrict ourselves to users whose home directory resides
        in the /home filesystem, how many users does llc have?

Question 2.

Considering the first names of people on the llc machine, which first names appear 3 or more times?

Question 3.

Print a list of all origin-to-destination airplane routes (from the Data Expo 2009) that are 2500 miles or longer.

Question 4.

How many miles has United flown altogether?

Question 5.

How many flights have a departure delay of 15 minutes or longer, but an arrival delay of 5 minutes or less?

Question 6.

This question asks about the individual campaign contributions, as reported on the FEC website:

http://www.fec.gov/finance/disclosure/ftpdet.shtml

Scroll down to the table for 2015-2016 Data Files if you want to see this data.

There is some information about the data here:

http://www.fec.gov/finance/disclosure/metadata/DataDictionaryContributionsbyIndividuals.shtml

The data for "Contributions by Individuals" was downloaded from September 4, 2016.

This data is stored on the llc machine in the directory `/data/public/election2016/itcont.txt`

`CMTE_ID` (in Column 1) shows the committee that receives the donation.

`TRANSACTION_AMT` (in Column 15) shows the transaction amount.

a. How much money has been donated by individuals to Hillary Clinton's committee `"HILLARY FOR AMERICA"`, `C00575795`?

b. How much money has been donated by individuals to Donald Trump's committee `"DONALD J. TRUMP FOR PRESIDENT, INC."`, `C00580100`?

c. Who received the most separate donations: Clinton, Sanders, or Trump?  The committee number for Sanders is `C00577130`.

Question 7.

a.  In which state were donations given most frequently?

b.  What was the total amount of donations given, from donors in that state?

Question 8.

a.  Which campaign did students most frequently give money to, i.e., which was the most popular in terms of the number of donations? (not the dollar amount)

A person can be classified as a student, for the purpose of this problem, if STUDENT appears as part of their job title.

b.  Which campaign was second most popular with the students? (Hint: This is not explicitly Clinton, Sanders, or Trump!)

c.  Which campaign was third most popular with the students?

Question 9.

a.  In which state do most homemakers live?

b.  How much money (dollar amount) was donated altogether by homemakers?

Question 10.

10.  Consider the data files in `/data/public/subtraction` which have the form x followed by some number(s) followed by `t16384.txt`

How many bytes are stored altogether in these files?
Hint:  Do not use `wc`.  That would take way too long.

Bonus question:  Considering the files from question 10, how many occurrences are there of the character 0? 1? 2? ... 9?

(This question is not required but might be fun to try.)


== Project 3

Question 1.

This question asks about the individual campaign contributions, as reported on the FEC website:

http://www.fec.gov/finance/disclosure/ftpdet.shtml

Scroll down to the table for 2015-2016 Data Files if you want to see this data. There is some information about the data here:

http://www.fec.gov/finance/disclosure/metadata/DataDictionaryContributionsbyIndividuals.shtml

The data for "Contributions by Individuals" was downloaded from September 4, 2016.

This data is stored on the llc machine in the directory `/data/public/election2016/itcont.txt`

On which day of the election season were the average donations (by dollar amount) the largest?

Question 2.

a. On which 10 days of the campaign were the largest number of donations made?

b. On which 10 days of the campaign were the largest dollar amounts of donations made?

Question 3.

a. How many donations were made by people who declared themselves to be Purdue employees?

b. How many of those donations came from Purdue employees who live in West Lafayette?

c. Among all Purdue donations from 3a, which campaign account received the largest number of donations?

Question 4.

Consider (only) the residents of Lafayette and West Lafayette.  What is the size of an average donation from such people?

Question 5.

a. Which 10 professions made the largest numbers of donations?  (Do not worry about the dollar amount of the donations.)

b. Which 10 professions had the largest total dollar amount of donations?

Question 6.

Find the total dollar amount of contributions, grouped according to each of the following individual zip codes: 47901, 47902, 47903, 47904, 47905, 47906, 47907, 47909, 47996.  If a zip code is listed as a 9-digit zip, then you need to (first) trim it down to a 5-digit zip code.  Hint: strtrim might be helpful for this purpose.

Question 7.

a. Find the top 15 cities in Indiana according to the total amount of money donated.

b. Find the top 15 cities in the USA, according to the total amount of money donated.

Question 8.

a. On which day of the election season did Hillary Clinton receive the largest amount of money?

b. On which day of the election season did Donald Trump receive the largest amount of money?

You may use the campaign numbers from the last project, namely:

`"HILLARY FOR AMERICA"`, `C00575795`

and

`"DONALD J. TRUMP FOR PRESIDENT, INC."`, `C00580100`

Question 9.

a.  Paste together (using the paste command) into a new vector the following information about each donor: the Name, City, State, and Zip_Code.

Then answer the following questions, using the vector from 9a to identify the donors in a (hopefully) unique way.

b.  Which donor donated the most times to Clinton's campaign?

c.  Which donor donated the most times to Trump's campaign?

d.  How many people have chosen to donate to both of the campaigns, i.e., they donated money to both Clinton and Trump?


== Project 4

Project 4 is a mini-project:

Take the project 3 discussion and code, and embed it into an RMarkdown document.

Please write English sentences to explain how your code from project 3 works. It is worthwhile to discuss your solutions with the other students in your group, to make sure that you all agree on the code itself, and on the explanations.

For your submission, submit 4 files.

For example, for group 1, please submit:

`p04g1.Rmd`   (an RMarkdown file)
`p04g1.docx`  (a Word file)
`p04g1.pdf`   (an Adobe Acrobat pdf file)
`p04g1.html`  (an html file)


== Project 5

Use the following function to extract data from the database of the NSF Center for Coastal Margin Observation & Prediction

[source,r]
----
library("ncdf4")

myfunction <- function( mystation, mylength, mymonth, myyear ) {
  
  mystring <- paste("http://amb6400b.stccmop.org:8080/thredds/dodsC/preliminary_data/", sprintf("saturn%02d", mystation),"/", sprintf("saturn%02d", mystation), ".", mylength , ".A.CT/", myyear, sprintf("%02d",mymonth), ".nc", sep="")
  
  mync <- nc_open(mystring)
  
  tempDF <- as.data.frame( lapply(1:mync$nvars, function(j) {ncvar_get(mync, mync$var[[j]])} ))
  
  names(tempDF) <- sapply(1:mync$nvars, function(j) mync$var[[j]]$name)
  
  tempDF$time <- ncvar_get(mync, "time")
  tempDF$length <- mylength
  tempDF$year <- myyear
  tempDF$month <- mymonth
  tempDF$days <- as.POSIXlt(tempDF$time, tz="PST8PDT", origin = "1970-01-01")$mday
  
  nc_close(mync)    
  return(tempDF)    
}
----

Question 1.

This question asks about the individual campaign contributions, as reported on the FEC website:

a. Create a vector corresponding to the 84 months from Nov 2009 through Oct 2016, and create a second vector containing the corresponding years.

b. Use these vectors in the context of an mapply function, to obtain the 84 months of data about the water temperature, salinity, and electrical conductivity at the SATURN03 station at the depth 2.4m. The result should be a list that contains 84 data.frames.

c. Use the sapply function to verify that all 84 data.frames have the variable names in the same order.

d. Use the do.call function to rbind these 84 data.frames into one data.frame called bigDF24. Check that the resulting data.frame has a little more than 7 million observations.

e. Repeat the steps above, to gather the data about these same 3 variables from depth 8.2m into one data.frame called bigDF82 (which will have a little less than 6 million observations).

Question 2.

a. Restricting attention to the 2.4m data, what is the longest time period for which no data is available, i.e., what is the longest time period in which no data is collected?

b. On which day does that biggest gap occur?

Question 3.

a. Find the daily mean values for water_temperature at depth 2.4m.

b. Plot the resulting daily mean values for water_temperature at depth 2.4m.

c. Re-consider 3a and 3b for water_electrical_conductivity, and then also for water_salinity.

Question 4.

a. Decide what constitutes a false reading, i.e., data that is probably an outlier. What are your criteria for having a false reading?

b. How many false readings occur at depth 2.4m? Please break your responses down to a month-by-month tally, for each variable.

Question 5.

The goal of this question is to scrape the Hot 100 chart from Billboard. This chart is posted every Saturday. The first chart is here:

http://www.billboard.com/charts/hot-100/1958-08-09

and the most current chart is here:

http://www.billboard.com/charts/hot-100/2016-10-08

Use the system and either the wget or curl command, inside R, to scrape all of these charts (in XML format) into the <strong>scratch</strong> folder for your team.

Hint: It might be helpful to use the sapply and paste commands, as well as the `seq.Date` help page. After you have scraped all of the charts in XML format, then zip the results into one file, so that you can use them during a later project.

It is NOT NECESSARY to extract the titles and artists for the songs in the database. Just download the 3000+ webpages from the web (each one in XML), and we'll come back later to this data, to scrape the titles and artists, and do some analysis. For now, we just want to download the data files.

Question 6.

Consider the New York City taxi data located at:

http://www.nyc.gov/html/tlc/html/about/trip_record_data.shtml

Here is a data dictionary:

http://www.nyc.gov/html/tlc/downloads/pdf/data_dictionary_trip_records_yellow.pdf

Use the system and either the wget or curl command, inside R, to scrape all of the yellow taxi cab data (in CSV format) into the *scratch* folder for your team. You can scrape these directly using bash if you prefer (in fact, that is probably recommended), but make sure that the code that you use to scrape them is succinct, and if you make bash calls, please use the system command in R to make them.

Question 7.

You may want to cut the data in various ways in bash (again using the system command in R), before answering the following questions:

a. On which day did the most taxi cab rides occur? If a ride goes past midnight, use the start of the ride for the date of the ride.

b. For each day, determine the distribution of the number of passengers. Your output should allow you to answer questions like the following: On January 1, 2016, how many rides had 1 passenger? 2 passengers? 3 passengers? Etc.?

Question 8.

a. For each day, determine the average distance of a taxi cab ride.

b. For each day, determine the average number of passengers.

Question 9.

a. On which type of day (Sun, Mon, …, Sat) is the average distance of a ride the longest?

b. On which type of day (Sun, Mon, …, Sat) is the average number of passengers in a car the largest?

Question 10.

Put the resulting answers from this entire project into an RMarkdown file.


== Project 6


During Project 5, question 5, you scraped the data from all of the BillBoard charts. In this project, you can have freedom to explore questions about the data.
To scrape the information from the first Hot 100 chart, you can use XPath. First it is necessary to install XPath.

[source,r]
----
install.packages("XML",repos="http://cran.us.r-project.org")
library("XML")
----

Then it is necessary to parse the XML source.

`mydoc <- htmlParse("/Users/mdw/1958-08-09")`

Now you are able to make queries about the XML content in a page. For instance,

[source,r]
----
mysongs <- xpathSApply(mydoc, "//*/div[@class='chart-row__title']/h2[@class='chart-row__song']", xmlValue)
mysongs
  [1] "Poor Little Fool"                                        
  [2] "Patricia"                                                
  [3] "Splish Splash"                                           
  [4] "Hard Headed Woman"                                       
  [5] "When"                                                    
  [6] "Rebel-'Rouser"                                           
  [7] "Yakety Yak"                                              
  [8] "My True Love"                                            
  [9] "Willie And The Hand Jive"                                
 [10] "Fever"                                                   
 [11] "Ginger Bread"                                            
 [12] "Just A Dream"                                            
 [13] "Left Right Out Of Your Heart (Hi Lee Hi Lo Hi Lup Up Up)"
 [14] "If Dreams Came True"                                     
 [15] "For Your Precious Love"                                  
 [16] "One Summer Night"                                        
 [17] "Endless Sleep"                                           
 [18] "Little Star"                                             
 [19] "Everybody Loves A Lover"                                 
 [20] "Do You Want To Dance"                                    
 [21] "Guess Things Happen That Way"                            
 [22] "A Certain Smile"                                         
 [23] "Western Movies"                                          
 [24] "The Purple People Eater"                                 
 [25] "What Am I Living For"                                    
 [26] "Born Too Late"                                           
 [27] "Think It Over"                                           
 [28] "Secretly"                                                
 [29] "Enchanted Island"                                        
 [30] "Angel Baby"                                              
 [31] "Chantilly Lace"                                          
 [32] "Blue Blue Day"                                           
 [33] "The Freeze"                                              
 [34] "Don't Ask Me Why"                                        
 [35] "Rock-in Robin"                                           
 [36] "No Chemise, Please"                                      
 [37] "Moon Talk"                                               
 [38] "Somebody Touched Me"                                     
 [39] "That's How Much I Love You"                              
 [40] "Crazy Eyes For You"                                      
 [41] "Early In The Morning"                                    
 [42] "You Cheated"                                             
 [43] "Come What May"                                           
 [44] "Jennie Lee"                                              
 [45] "Kathy-O"                                                 
 [46] "(It's Been A Long Time) Pretty Baby"                     
 [47] "I Wonder Why"                                            
 [48] "Return To Me"                                            
 [49] "All I Have To Do Is Dream"                               
 [50] "By The Light Of The Silvery Moon"                        
 [51] "Baubles, Bangles And Beads"                              
 [52] "Early In The Morning"                                    
 [53] "Come Closer To Me (Acercate Mas)"                        
 [54] "Nel Blu Dipinto Di Blu (Volare)"                         
 [55] "Let's Go Steady For The Summer"                          
 [56] "Leroy"                                                   
 [57] "You Need Hands"                                          
 [58] "Fool's Paradise"                                         
 [59] "Young And Warm And Wonderful"                            
 [60] "Over And Over"                                           
 [61] "Itchy Twitchy Feeling"                                   
 [62] "For Your Love"                                           
 [63] "High School Confidential"                                
 [64] "Padre"                                                   
 [65] "You're Making A Mistake"                                 
 [66] "Delicious!"                                              
 [67] "Big Man"                                                 
 [68] "Volare (Nel Blu Dipinto Di Blu)"                         
 [69] "Op"                                                      
 [70] "Don't Go Home"                                           
 [71] "Got A Match?"                                            
 [72] "Stupid Cupid"                                            
 [73] "Hey Girl - Hey Boy"                                      
 [74] "Gotta Have Rain"                                         
 [75] "Win Your Love For Me"                                    
 [76] "Midnight"                                                
 [77] "Happy Years"                                             
 [78] "Betty Lou Got A New Pair Of Shoes"                       
 [79] "The Bird On My Head"                                     
 [80] "Johnny B. Goode"                                         
 [81] "Beautiful Delilah"                                       
 [82] "Blip Blop"                                               
 [83] "Try The Impossible"                                      
 [84] "Summertime Blues"                                        
 [85] "Got A Match?"                                            
 [86] "To Be Loved"                                             
 [87] "Jealousy"                                                
 [88] "Just Like In The Movies"                                 
 [89] "Blue Boy"                                                
 [90] "Stay"                                                    
 [91] "The Purple People Eater Meets The Witch Doctor"          
 [92] "Bird Dog"                                                
 [93] "Are You Really Mine"                                     
 [94] "She Was Only Seventeen (He Was One Year More)"           
 [95] "Little Mary"                                             
 [96] "Over And Over"                                           
 [97] "I Believe In You"                                        
 [98] "Little Serenade"                                         
 [99] "I'll Get By (As Long As I Have You)"                     
[100] "Judy"</code>
----

or like this

[source,r]
----
myartists <- xpathSApply(mydoc, "//*/div[@class='chart-row__title']/h3[@class='chart-row__artist']|//*/div[@class='chart-row__title']/a[@class='chart-row__artist']", xmlValue)
myartists
  [1] "\n                                Ricky Nelson\n                            "                               
  [2] "\n                                Perez Prado And His Orchestra\n                            "              
  [3] "\n                                Bobby Darin\n                            "                                
  [4] "\n                                Elvis Presley With The Jordanaires\n                            "         
  [5] "\n                                Kalin Twins\n                            "                                
  [6] "\n                                Duane Eddy His Twangy Guitar And The Rebels\n                            "
  [7] "\n                                The Coasters\n                            "                               
  [8] "\n                                Jack Scott\n                            "                                 
  [9] "\n                                The Johnny Otis Show\n                            "                       
 [10] "\n                                Peggy Lee\n                            "                                  
 [11] "\n                                Frankie Avalon\n                            "                             
 [12] "\n                                Jimmy Clanton And His Rockets\n                            "              
 [13] "\n                                Patti Page\n                            "                                 
 [14] "\n                                Pat Boone\n                            "                                  
 [15] "\n                                Jerry Butler and The Impressions\n                            "           
 [16] "\n                                The Danleers\n                            "                               
 [17] "\n                                Jody Reynolds\n                            "                              
 [18] "\n                                The Elegants\n                            "                               
 [19] "\n                                Doris Day\n                            "                                  
 [20] "\n                                Bobby Freeman\n                            "                              
 [21] "\n                                Johnny Cash And The Tennessee Two\n                            "          
 [22] "\n                                Johnny Mathis\n                            "                              
 [23] "\n                                The Olympics\n                            "                               
 [24] "\n                                Sheb Wooley\n                            "                                
 [25] "\n                                Chuck Willis\n                            "                               
 [26] "\n                                Poni-Tails\n                            "                                 
 [27] "\n                                The Crickets\n                            "                               
 [28] "\n                                Jimmie Rodgers\n                            "                             
 [29] "\n                                The Four Lads\n                            "                              
 [30] "\n                                Dean Martin\n                            "                                
 [31] "\n                                Big Bopper\n                            "                                 
 [32] "\n                                Don Gibson\n                            "                                 
 [33] "\n                                Tony And Joe\n                            "                               
 [34] "\n                                Elvis Presley With The Jordanaires\n                            "         
 [35] "\n                                Bobby Day\n                            "                                  
 [36] "\n                                Gerry Granahan\n                            "                             
 [37] "\n                                Perry Como\n                            "                                 
 [38] "\n                                Buddy Knox with the Rhythm Orchids\n                            "         
 [39] "\n                                Pat Boone\n                            "                                  
 [40] "\n                                Bobby Hamilton\n                            "                             
 [41] "\n                                Buddy Holly\n                            "                                
 [42] "\n                                The Slades\n                            "                                 
 [43] "\n                                Clyde McPhatter\n                            "                            
 [44] "\n                                Jan &amp; Arnie\n                            "                                
 [45] "\n                                The Diamonds\n                            "                               
 [46] "\n                                Gino &amp; Gina\n                            "                                
 [47] "\n                                Dion &amp; The Belmonts\n                            "                        
 [48] "\n                                Dean Martin\n                            "                                
 [49] "\n                                The Everly Brothers\n                            "                        
 [50] "\n                                Jimmy Bowen with the Rhythm Orchids\n                            "        
 [51] "\n                                The Kirby Stone Four\n                            "                       
 [52] "\n                                The Rinky-Dinks\n                            "                            
 [53] "\n                                Nat King Cole\n                            "                              
 [54] "\n                                Domenico Modugno\n                            "                           
 [55] "\n                                The Three G's\n                            "                              
 [56] "\n                                Jack Scott\n                            "                                 
 [57] "\n                                Eydie Gorme\n                            "                                
 [58] "\n                                The Crickets\n                            "                               
 [59] "\n                                Tony Bennett\n                            "                               
 [60] "\n                                Bobby Day\n                            "                                  
 [61] "\n                                Bobby Hendricks\n                            "                            
 [62] "\n                                Ed Townsend\n                            "                                
 [63] "\n                                Jerry Lee Lewis And His Pumping Piano\n                            "      
 [64] "\n                                Toni Arden\n                            "                                 
 [65] "\n                                The Platters\n                            "                               
 [66] "\n                                Jim Backus &amp; Friend\n                            "                        
 [67] "\n                                The Four Preps\n                            "                             
 [68] "\n                                Dean Martin\n                            "                                
 [69] "\n                                The Honeycones\n                            "                             
 [70] "\n                                The Playmates\n                            "                              
 [71] "\n                                Frank Gallup\n                            "                               
 [72] "\n                                Connie Francis\n                            "                             
 [73] "\n                                Oscar McLollie and Jeanette Baker\n                            "          
 [74] "\n                                Eydie Gorme\n                            "                                
 [75] "\n                                Sam Cooke\n                            "                                  
 [76] "\n                                Paul Anka\n                            "                                  
 [77] "\n                                The Diamonds\n                            "                               
 [78] "\n                                Bobby Freeman\n                            "                              
 [79] "\n                                David Seville\n                            "                              
 [80] "\n                                Chuck Berry\n                            "                                
 [81] "\n                                Chuck Berry\n                            "                                
 [82] "\n                                Bill Doggett\n                            "                               
 [83] "\n                                Lee Andrews And The Hearts\n                            "                 
 [84] "\n                                Eddie Cochran\n                            "                              
 [85] "\n                                The Daddy-O's\n                            "                              
 [86] "\n                                Jackie Wilson\n                            "                              
 [87] "\n                                Kitty Wells\n                            "                                
 [88] "\n                                The Upbeats\n                            "                                
 [89] "\n                                Jim Reeves\n                            "                                 
 [90] "\n                                The Ames Brothers\n                            "                          
 [91] "\n                                Joe South\n                            "                                  
 [92] "\n                                The Everly Brothers\n                            "                        
 [93] "\n                                Jimmie Rodgers\n                            "                             
 [94] "\n                                Marty Robbins\n                            "                              
 [95] "\n                                Fats Domino\n                            "                                
 [96] "\n                                Thurston Harris\n                            "                            
 [97] "\n                                Robert &amp; Johnny\n                            "                            
 [98] "\n                                The Ames Brothers\n                            "                          
 [99] "\n                                Billy Williams\n                            "                             
[100] "\n                                Frankie Vaughan\n                            "
myartists <- sub("^\\s+", "", myartists)
myartists <- sub("\\s+$", "", myartists)
myartists
  [1] "Ricky Nelson"                               
  [2] "Perez Prado And His Orchestra"              
  [3] "Bobby Darin"                                
  [4] "Elvis Presley With The Jordanaires"         
  [5] "Kalin Twins"                                
  [6] "Duane Eddy His Twangy Guitar And The Rebels"
  [7] "The Coasters"                               
  [8] "Jack Scott"                                 
  [9] "The Johnny Otis Show"                       
 [10] "Peggy Lee"                                  
 [11] "Frankie Avalon"                             
 [12] "Jimmy Clanton And His Rockets"              
 [13] "Patti Page"                                 
 [14] "Pat Boone"                                  
 [15] "Jerry Butler and The Impressions"           
 [16] "The Danleers"                               
 [17] "Jody Reynolds"                              
 [18] "The Elegants"                               
 [19] "Doris Day"                                  
 [20] "Bobby Freeman"                              
 [21] "Johnny Cash And The Tennessee Two"          
 [22] "Johnny Mathis"                              
 [23] "The Olympics"                               
 [24] "Sheb Wooley"                                
 [25] "Chuck Willis"                               
 [26] "Poni-Tails"                                 
 [27] "The Crickets"                               
 [28] "Jimmie Rodgers"                             
 [29] "The Four Lads"                              
 [30] "Dean Martin"                                
 [31] "Big Bopper"                                 
 [32] "Don Gibson"                                 
 [33] "Tony And Joe"                               
 [34] "Elvis Presley With The Jordanaires"         
 [35] "Bobby Day"                                  
 [36] "Gerry Granahan"                             
 [37] "Perry Como"                                 
 [38] "Buddy Knox with the Rhythm Orchids"         
 [39] "Pat Boone"                                  
 [40] "Bobby Hamilton"                             
 [41] "Buddy Holly"                                
 [42] "The Slades"                                 
 [43] "Clyde McPhatter"                            
 [44] "Jan &amp; Arnie"                                
 [45] "The Diamonds"                               
 [46] "Gino &amp; Gina"                                
 [47] "Dion &amp; The Belmonts"                        
 [48] "Dean Martin"                                
 [49] "The Everly Brothers"                        
 [50] "Jimmy Bowen with the Rhythm Orchids"        
 [51] "The Kirby Stone Four"                       
 [52] "The Rinky-Dinks"                            
 [53] "Nat King Cole"                              
 [54] "Domenico Modugno"                           
 [55] "The Three G's"                              
 [56] "Jack Scott"                                 
 [57] "Eydie Gorme"                                
 [58] "The Crickets"                               
 [59] "Tony Bennett"                               
 [60] "Bobby Day"                                  
 [61] "Bobby Hendricks"                            
 [62] "Ed Townsend"                                
 [63] "Jerry Lee Lewis And His Pumping Piano"      
 [64] "Toni Arden"                                 
 [65] "The Platters"                               
 [66] "Jim Backus &amp; Friend"                        
 [67] "The Four Preps"                             
 [68] "Dean Martin"                                
 [69] "The Honeycones"                             
 [70] "The Playmates"                              
 [71] "Frank Gallup"                               
 [72] "Connie Francis"                             
 [73] "Oscar McLollie and Jeanette Baker"          
 [74] "Eydie Gorme"                                
 [75] "Sam Cooke"                                  
 [76] "Paul Anka"                                  
 [77] "The Diamonds"                               
 [78] "Bobby Freeman"                              
 [79] "David Seville"                              
 [80] "Chuck Berry"                                
 [81] "Chuck Berry"                                
 [82] "Bill Doggett"                               
 [83] "Lee Andrews And The Hearts"                 
 [84] "Eddie Cochran"                              
 [85] "The Daddy-O's"                              
 [86] "Jackie Wilson"                              
 [87] "Kitty Wells"                                
 [88] "The Upbeats"                                
 [89] "Jim Reeves"                                 
 [90] "The Ames Brothers"                          
 [91] "Joe South"                                  
 [92] "The Everly Brothers"                        
 [93] "Jimmie Rodgers"                             
 [94] "Marty Robbins"                              
 [95] "Fats Domino"                                
 [96] "Thurston Harris"                            
 [97] "Robert &amp; Johnny"                            
 [98] "The Ames Brothers"                          
 [99] "Billy Williams"                             
[100] "Frankie Vaughan"</code>
----

Did it work?

[source,r]
----
length(mysongs)
[1] 100
length(myartists)
[1] 100
----


Question 1.

a. Write a function that takes one date as input, and it extracts the song titles for that week.

b. Use the sapply and the unlist function to get a vector of all of the song titles for all of the weeks.

c. Write a function that takes one date as input, and it extracts the artists for that week.

d. Use the sapply and the unlist function to get a vector of all of the artists for all of the weeks.

Hint: It might be helpful to use:

`mydates <- seq(as.Date("1958-08-09"), as.Date("2016-10-08"), by = "week")`

Question 2.

Take your data from Question 1 and build a `data.frame` with four columns: the artists, the songs, the weeks, and the rank within the week. You will need to build another function to extract the positions.

Questions 3-10.

Ask 8 questions about the Billboard data, and answer each question, using the data.frame that you have built. It would be nice to make some visualizations about the data, for some of your questions. Have fun!


== Project 7

Question 1.

Find out how many games that each baseball team won in 2015. Your result should have 30 rows.

Question 2.

Find the years in which the Chicago Cubs won at least 95 games. Your result should have 7 rows.

Question 3.

Find the statistics for how many home runs that Ernie Banks hit with a year-by-year breakdown, while he was playing for the Chicago Cubs. FYI, Ernie Banks was awarded the Presidential Medal of Freedom in 2013,  for his contribution to sports. Your result should have 19 rows.

Question 4.

Identify each player who hit 40 or more home runs during a year, while they were playing with the Chicago Cubs. Your result should have 18 rows, and some players achieved such an accomplishment several times (and will therefore appear in the list multiple times).

Question 5.

Have there been any Chicago Cubs players to get 100 or more runs in a single season? Find all such Cubs players who had such an achievement since 2000.

Question 6.

Find, for each year since 1960, how many Chicago Cubs players there were in each year.  Your result should have 56 rows.

Question 7.

Find the player who had the largest number of doubles in one season.

Hint for questions 8, 9, 10:

You might need/want to use `HAVING` near the end of your query on each question.

Question 8.

Find the teams and years in which a team won at least 105 games that year. Your result should have 18 rows. Notice that some players achieved this feat during more than 1 season.

Question 9.

Find the breakdown of players who had 500 or more home runs during their lifetime.  Your result should have 26 rows.

Question 10.

Just like we adjusted the data type and the indexing for some of the batting, master, and teams tables, please go ahead and adjust the data types and indexing in the pitching table as follows:

[source,sql]
----
alter table pitching modify playerID varchar(20);
alter table pitching modify teamID varchar(20);
----

We should also build an index for each of these fields, as follows:

[source,sql]
----
alter table pitching add index pitching_playerID(playerID);
alter table pitching add index pitching_teamID(teamID);
----

Now find the pitchers who have made at least 3000 strikeouts during their career. Your result should have 16 rows.


== Project 8

Question 1.

Make several plots that compare the abilities of the Boston Red Sox batters and the New York Yankees batters.  It is worthwhile to consider several of their batting characteristics, i.e., do not just consider hits or home runs.  Can you make a convincing argument (using one or more plots) that one or the other of them is usually the stronger team, say, within our lifetimes?

Question 2.

Is a player's number of hits correlated with his number of home runs?  Make some plots to argue for or against such a correlation.

Question 3.

Triples are rare in baseball.  Have they become more or less likely over the years?  Be sure to properly normalize whatever kind of justification you use.  For instance, it would not be reasonable to just compare the number of triples overall, because there are more teams playing baseball now, as compared to twenty years ago.  Use at least one visualization to support your argument.

Question 4.

Pitchers are judged by various criteria, e.g., their E.R.A., their number of strikeouts, etc.  The standards of what makes a "good" player have changed over the years; this can be seen as the trends in some pitching attributes have changed over the years.  Identify one such pitching attribute that has gradually changed over the years, and use a visualization to describe the way(s) in which this attribute has changed.

Question 5.

Pick a fixed year in baseball (you can choose the year) and use some visualizations to describe which teams are the strongest in both batting and pitching (i.e., teams that are simultaneously good in both batting and pitching).  Use one or more plots to support your opinion about which teams are the strongest in that fixed year.

Question 6.

The Chicago Cubs won the World Series this year.  Have they been improving during the last five years (2011-2015), leading up to this year?  Make a case for or against this argument, and use at least one visualization to justify your argument.


== Project 9

Something went very, very unexpected in the Presidential Election 2016.

Spend this week finding 6 visualizations of the election data (either before or after the election).  Find things that the visualizations do well, and find things that they do poorly. I.e., make some critiques, as a team, of the visualizations.

I suggest that you first consider some of the bad ways of depicting data seen in this article:

http://www.jstor.org.ezproxy.lib.purdue.edu/stable/2683253

I'm also attaching some scans (in two attached pdf files) from two books that might be helpful.  I just picked out some of the most relevant pages.  One of the books discusses some issues with color, but both books are actually printed in black and white (it is strange, I know).

You can submit your writeup in whatever way looks most professional to you.  Be critical of what you see and what you say about the visualizations that you find!

The due date for Project 9 is Friday, November 18, but you will probably be able to finish it before that, and move onwards to Project 10.


== Project 10

Summarize what you have learned in the course, as follows:

Please find some data on the web that you are interested in (as a group; this will take some initial discussion and agreement).

Scrape data for this project from the web in XML format, and then parse the data using XML tools, and finally design 6 questions about the data, and answer all 6 of your questions.

Since we are focusing on large data, I would like you to (please) have at least 2 million pieces of data in the set that you scrape.  You are certainly welcome to have more than 2 million pieces of data.

You can handle this, I know it for sure!  (For comparison, the airline data set had about 120 million pieces of data.)

I would also request (please) that, once you identify your website with your 2 million (or more) pieces of data, you run your project idea by me.  OK?

Once you have identified your website, and you run your project idea by me, I will ask you to scrape the data from the web, and parse it.  Then you should design 6 or more interesting questions about the data, and answer each of the 6 questions.

At the end, your group will submit the following to me:

The code for scraping the data from the web, and the code for parsing the data, and the 6 questions you designed about the data, and the answers to the 6 questions.

The due date for Project 10 is the end of the final week of classes, i.e., by the end of the day on Friday, December 9.  (We don't have a final exam, of course.)  I just want you to be done with this project before the final exams start, so that it doesn't get in the way of your exams.

If you have any questions, please let me know.  Enjoy! 

