# DEAF PODS

**D**eveloping **E**xpereiential **A**ccessible **F**ramework for **P**artnerships and **O**pportunities in **D**ata **S**cience (for the deaf community). 

[IMPORTANT]
====
Do you want to join a DEAF PODS project? 

Be sure to fill out the https://purdue.ca1.qualtrics.com/jfe/form/SV_3NLrTMxi5IsWzZQ[application]!

Please note, the students must:

- Identify as deaf or hard of hearing. 
- Be an undergraduate student. 
- Be a United States citizen. 
====

[TIP]
====
If you don't meet the requirements and are still interested, please reach out to mailto:datamine@purdue.edu[datamine@purdue.edu]. We are happy to discuss different options for participation. 
====

## The Data Mine
https://datamine.purdue.edu/[The Data Mine] is a data science focused experiential learning project here at Purdue University. We accept students of all undergraduate years and majors, and pair them with corporations. 

Using industry data, The Data Mine encourages collaborative learning amongst our students and to help devise solutions for whatever project or question the industry partner presents.

We intend to utilize this framework and build an experience that will enable a similar environment that allows Deaf students gain data science knowledge and tools to immerse deaf and hard of hearing students in a world of education, research, engagement, and 
collaboration.

## NSF Award

- https://beta.nsf.gov/news/nsf-accelerates-use-inspired-solutions-persons[NSF Public Announcement]
- https://www.nsf.gov/awardsearch/showAward?AWD_ID=2235473&HistoricalAwards=false[NSF Abstract]

## Gallaudet Workshop

- xref:ROOT:templates.adoc[Templates]
- xref:ROOT:submissions.adoc[Submissions]
- xref:ROOT:ndmn-gallaudet-projects-r.adoc[R Projects]
- xref:ROOT:ndmn-gallaudet-projects-python.adoc[Python Projects]