= Trees

Tree based methods are a well known modeling technique that are used for both regression and classification. The general idea is that we segment the feature space into individual subspaces. The rules for segmenting the data into their respective subspaces is summarized by the tree, and is why tree methods are sometimes called *decision tree* methods. Tree methods have numerous different approaches, such as bagging, boosting and random forests. 

== Common Applications

=== Common Problem Types

- Regression
- Classification
- Rules-based segmentation
- Problems where interpretability is critical

== A Brief History

Tree based methods were first published in the early 1960's, and have since exploded into a remarkable diversity of techniques and approaches that was aided by the growth of free software and cheaper hardware to implement computations that were challenging to do by hand, but relatively easier for computers. They found themselves sometimes enhancing traditional models such as least squares and logistic regression. If you are interested in a technical overview of the various approaches and a more in depth history, see https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_proquest_miscellaneous_1770355778[(2014, Loh)].

== Resources

All resources are chosen by Data Mine staff to be of decent quality, and most if not all content is free. 

=== Websites

https://online.stat.psu.edu/stat508/lesson/11[Tree-based Methods (Penn State)]

https://sdcastillo.github.io/PA-R-Study-Manual/tree-based-models.html[Tree-based models (Exam PA Study Guide)]

https://hastie.su.domains/MOOC-Slides/trees.pdf[Tree-based Methods (Stanford)]

=== Videos

https://www.youtube.com/watch?v=_L39rN6gz7Y[Decision and Classification Trees, Clearly Explained!!! (StatQuest with Josh Starmer, ~18 minutes)]

https://www.youtube.com/watch?v=ZVR2Way4nwQ[Decision Tree Classification Clearly Explained! (Normalized Nerd, ~10 minutes)]

https://www.youtube.com/watch?v=v6VJ2RO66Ag[Random Forest Algorithm Clearly Explained (Normalized Nerd, ~8 minutes)]

https://www.youtube.com/watch?v=QNnayf--_yk[Statistical Learning: 8.1 Tree based methods (Stanford Online, ~14 minutes)]

https://www.youtube.com/watch?v=uARj54stZxU[Regression Decision Trees (IQmates, ~18 minutes)]

=== Books

Also known as the "machine learning bible", see Chapter 8 for tree based methods.

https://www.statlearning.com[Introduction to Statistical Learning]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99170403319101081[Tree-based Methods for Statistical Learning in R]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_hal_primary_oai_HAL_hal_03066152v1[Random Forests with R]

=== Articles

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_pubmedcentral_primary_oai_pubmedcentral_nih_gov_7425836[Tree-based Machine Learning Methods for Survey Research (2019)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_proquest_journals_2774942518[Tree-based Machine Learning Methods for Modeling and Forecasting Mortality (2022)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_doaj_primary_oai_doaj_org_article_f89e5c8f0960487aa5fecfceb1405a66[Modelling Soil Temperature by Tree-Based Machine Learning Methods in Different Climatic Regions of China (2022)]