= Data

Data comes in so many different formats, and each format has its own set of rules and tooling surrounding it. Here, we've curated a list of formats that we think every data scientist should have at least a cursory exposure to. 

Do you have another data format that you think should be included? Please feel free to xref:ROOT:ROOT:how-to-contribute.adoc[make a contribution]. See a mistake? Please https://github.com/TheDataMine/the-examples-book/issues[open an issue] and we will get to it as soon as possible.

// dead-link: xref:data-formats/html.adoc[HTML]
* HTML
// dead-link: xref:data-formats/xml.adoc[XML]
* XML
// dead-link: xref:data-formats/json.adoc[json]
* json
// dead-link: xref:data-formats/csv.adoc[csv]
* csv
// dead-link: xref:data-formats/yaml.adoc[yaml]
* yaml
// dead-link: xref:data-formats/toml.adoc[toml]
* toml
// dead-link: xref:data-formats/parquet.adoc[parquet]
* parquet
// dead-link: xref:data-formats/feather.adoc[feather]
* feather
// dead-link: xref:data-formats/vcf.adoc[VCF]
* VCF
// dead-link: xref:data-formats/las.adoc[LAS]
* LAS
// dead-link: xref:data-formats/stl.adoc[STL]
* STL
// dead-link: xref:data-formats/messagepack.adoc[MessagePack]
* MessagePack
// dead-link: xref:data-formats/protobuf.adoc[Protobuf]
* Protobuf
