= Convolutional Neural Networks

A Convolutional Neural Network (CNN) is a feedforward neural network that utilizes filters to select which features are relevant during learning and which are not. CNN's were designed to resolve problems with the xref:data-modeling/general-principles/curse-of-dimensionality.adoc[Curse of Dimensionality] that traditional fully connected neural networks faced by using filters to perform feature engineering, thus reducing the dimensions. While there are many implementations of CNN's, they always have a convolutional filter (kernel) layer, and often have regularization built into them as well. They have seen extensive use in industry with regards to image and video or for computer vision problems.

== Common Applications

=== Common Problem Types

- Healthcare (Image Analysis)
- Tech (Search, Recommender Systems, Video Processing)
- Computer Vision Problems
- Financial Time Series

== Code Examples

NOTE: All of the code examples are written in Python, unless otherwise noted.

=== Containers

TIP: These are code examples in the form of Jupyter notebooks running in a container that come with all the data, libraries, and code you'll need to run it. https://the-examples-book.com/starter-guides/data-engineering/containers/using-data-mine-containers[Click here to learn why you should be using containers, along with how to do so.]

TIP: Quickstart: https://docs.docker.com/get-docker/[Download Docker], then run the commands below in a terminal. 

==== Computer Vision Image Toolkit

An introductory notebook showing how to implement many different types of image processing. Towards the end of this notebook there is an example of different kinds of filters, along with a demonstration of how convolution kernels work.

[source,bash]
----
#pull container, only needs to be run once
docker pull ghcr.io/thedatamine/starter-guides:cv-image-toolkit

#run container
docker run -p 8888:8888 -it ghcr.io/thedatamine/starter-guides:cv-image-toolkit
----

==== Convolutional Neural Networks, Anomaly Identification, and Reading TFRecords

Here we explore using Convolutional Neural Networks (CNN's) to classify images of concrete by their anomaly status (that is, whether they have a crack or not). Our data is supplied in the form of TFRecords, so we look at how to read those in for training and testing.

[source,bash]
----
#pull container, only needs to be run once
docker pull ghcr.io/thedatamine/starter-guides:cnn-anomaly-reading-tfrecords

#run container
docker run -p 8888:8888 -it ghcr.io/thedatamine/starter-guides:cnn-anomaly-reading-tfrecords
----

Need help implementing any of this code? Feel free to reach out to mailto:datamine-help@purdue.edu[datamine-help@purdue.edu] and we can help!

== Resources

All resources are chosen by Data Mine staff to be of decent quality, and most if not all content is free. 

=== Websites

https://www.ibm.com/topics/convolutional-neural-networks[What are convolutional neural networks? (IBM)]

https://towardsdatascience.com/convolutional-neural-networks-explained-9cc5188c4939[Convolutional Neural Networks, Explained (Towards Data Science)]

https://cs231n.github.io/convolutional-networks/[CS231n Convolutional Neural Networks for Visual Recognition (Stanford)]

=== Videos

https://www.youtube.com/watch?v=KuXjwB4LzSA[But what is a convolution? (~23 minutes, 3Blue1Brown)]

https://www.youtube.com/watch?v=YRhxdVk_sIs[Convolutional Neural Networks (CNNs) explained (~8 minutes, deeplizard)]

https://www.youtube.com/watch?v=QzY57FaENXg[What are Convolutional Neural Networks (CNNs)? (~6 minutes, IBM)]

https://www.youtube.com/watch?v=HGwBXDKFk9I[Neural Networks Part 8: Image Classification with Convolutional Neural Networks (CNNs) (~15 minutes, StatQuest With Josh Starmer)]

=== Books

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99170470677301081[Convolutional neural networks for medical applications (2023)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99170208257001081[Practical Convolutional Neural Networks (2018)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99170398516601081[Convolutional neural networks for medical image processing applications (2023)]

=== Articles

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99169913545401081[Arctic Vegetation Mapping Using Unsupervised Training Datasets and Convolutional Neural Networks (2019)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_gale_infotrac_563162782[LIDAR–camera fusion for road detection using fully convolutional neural networks (2019)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_pubmed_primary_29356229[Brain tumor segmentation in multi‐spectral MRI using convolutional neural networks (CNN) (2018)]