= Spring 2022 Announcements for Corporate Partner Mentors 


*Announcements will be emailed out to mentors and also logged here.*

== (January 25) Week 3 Updates

We hope you’ve had a great start to the spring 2022 semester in The Data Mine. My goal is to provide regular updates this semester, so here are 5 things to know for at the end of week #3 (middle of sprint #2).
 
1. Symposium Update
+
--
The Data Mine Symposium will now be conducted in a *virtual setting only* on Wednesday, April 20, 2022. We have had two successful online symposiums in 2020 and 2021, and we look forward to interacting with you and our students online. The schedule for Wednesday, April 20 is to be determined. We will be cancelling the in-person symposium on April 12. We hope to have an in-person Symposium next year in 2023.
 
The students will create one poster and one video per project to present at the symposium. Their first draft is due March 13. Since these posters and videos will be shared publicly, we will have you and your company legal team review and approve the content before posting. We encourage you to work closely on these presentations. As a reminder, all course content is posted here: https://the-examples-book.com/crp/spring2022
--
+

2. Fall 2022 – Spring 2023
+
--
We are planning for fall 2022 already. The students register for fall courses in March, so we will start working with you to determine projects for next year. Project descriptions should be submitted by March 15. If you signed the 5 year sponsor acknowledgment last year, we will be sending you an addendum to specify year 2 details.
More details regarding fall 2022 – spring 2023 planning will be coming to you soon.
--
+

3. Job opening in The Data Mine
+
--
We are searching for a Corporate Partners Technical Specialist to join our team. We would greatly appreciate you sharing this link with any interested colleagues: https://careers.purdue.edu/job/West-Lafayette-Corporate-Partners-Technical-Specialist-IN-47906/812893500/
--
+

4. Guest talk
+
--
We welcome you to give a talk this spring in The Data Mine. We frequently host guest speakers (online or in-person) for all students in The Data Mine to attend. Topics range from technical talks to company overviews to career advice. If you are interested, please let us know and we will coordinate a date that works into your schedule.
--
+

5. Writing in Data-Driven Workplaces Survey
+
--
The Purdue English Department is conducting a study on writing in data-driven workplaces.

The survey is intended to collect information on the writing and communication skills most important for students entering data-driven workplaces. The data from this survey will help us better prepare Purdue students for future employment at your workplace. Our goal is to develop materials in Purdue’s Professional Writing courses that can help students improve those skills, along with stand-alone online modules or workshops for Data Mine students. 
 
Here is the link to the survey: https://purdue.ca1.qualtrics.com/jfe/form/SV_9mgipJEWt9h4G9M
 
The survey is anonymous, and all information will be confidential. Your participation is completely voluntary and done without compensation or inducement. The survey should take approximately 15 minutes of your time, and you may stop at any point.
 
This study, “Writing in Data-Driven Workplaces,” has been approved by the Institutional Review Board at Purdue University (IRB-2021-1400). If you have any questions about what is stated above or on any other aspect of this research, please email: Jennifer Bay, jbay@purdue.edu. Our Institutional Research Board (IRB) may also be contacted at (765) 494-5942, or at the Human Research Protection Program, YONG 10th Floor, Rm 1032, 155 Grant Street, West Lafayette, IN 47906-2114.  Thank you for your time and willingness to participate in this survey.
--
+


== (January 7) Updates for Spring 2022

We hope you enjoyed the holiday break and are off to a great year! Spring 2022 semester at Purdue starts on *Monday, January 10* so we have some updates to share. 

*50-minute Team Meetings start MONDAY!*

Team meetings will begin next week starting on Monday, January 10. The schedule of meeting times is listed here: https://the-examples-book.com/crp/spring2022_locations 
Corporate Partner Mentors attend the 50-minute “lec” time listed. You should have received a recurring calendar invite in December with the meeting time and MS Teams link for the 50-minute mentor meetings. If you do not have this invite, please contact us. The majority of meeting times did not change between fall to spring. 

*Symposium*

Save the date for our 2021-2022 Symposium on Tuesday, April 12, 2022. The Data Mine Symposium showcases the research of our students throughout the academic year via a poster session. The Symposium is currently scheduled for in-person, but we are closely monitoring Purdue policy for any changes. 

*Fall 2022 – Spring 2023 Planning*

It’s not too early to start planning ahead for your project(s) next fall. Students register for their fall 2022 courses in March. We are requesting the brief project descriptions be submitted by February 15. We look forward to meeting with you soon to discuss your plans for next academic year. 

*News Updates*

The American Statistical Association in collaboration with The Data Mine was recently awarded a National Science Foundation grant to support Minority Serving Institutions in The National Data Mine Network:  https://www.purdue.edu/newsroom/releases/2021/Q4/purdues-data-mine-is-making-data-science-accessible-for-all.html 

You can follow along with updates on our LinkedIn page: https://www.linkedin.com/company/datamine-purdue/ 

*Course content*


The Examples Book has been the source of our 1 credit seminar content for the past 2 years. Now, Corporate Partners has an appendix in The Examples Book. We have migrated all of our content away from Brightspace (student-facing only) and into The Examples Book (public and accessible to all). We aspire to be more transparent between The Data Mine and our partner companies and universities, as well as making content and resources readily available for our students. You will see that we have a blank section in the book for Corporate Partner Mentors. We are still developing this content, but you are always welcome to contribute too! The Examples Book is a living document and always under construction. 

*Corporate Partners spring 2022 page for students: https://the-examples-book.com/crp/spring2022
*Home page for The Examples Book: http://the-examples-book.com/ 

*Visiting Campus*

Current Purdue policy still allows for guests to visit campus. If you would like to plan a visit to campus, please let us know. We also have a guest suite in Hillenbrand for overnight stays that is free to guests when visiting campus to meet with students. 

*Staff Updates*

Our team is continuing to grow! We have 14 staff members now. In addition to staff members listed here (https://datamine.purdue.edu/about/welcome.html), we recently welcomed Corporate Partners Senior Manager, Shuennhau Chang, and two new limited-term lecturers. 

We also have a current opening for a Corporate Partners Technical Specialist (https://careers.purdue.edu/job/West-Lafayette-Corporate-Partners-Technical-Specialist-IN-47906/812893500/) on our team if you have interested colleagues. 

We look forward to working with you this semester! 


