== Mentor Responsibility Overview
Each corporate partner provides at least one mentor on their corporate partner team. The mentor is responsible for guiding the students through the project by providing the data, assigning deliverables and providing feedback. Mentors also help students to develop communication and presentation skills that they will use in their future careers. 

Although a corporate partner can have more than one mentor, we suggest there be a primary mentor for consistency.

== Bringing Industry Culture to The Data Mine
Corporate partner mentors get to engage with the students on their team on a weekly basis. Mentors demonstrate appropriate business culture behaviors while working on the project, and get to observe the students as they develop and refine their business skills along with their technical skills. Students become aware that their engagement with their mentor should be intentional and will help them develop their networking skills. 

=== Engagement Level from Mentors
Mentors meet with their teams each week for 50 minutes during an online meeting. During those meetings, mentors engage with the students by providing feedback on the work from the most recent sprint, and on any deliverables that were due. Mentors also provide advice on how to proceed with specific areas of the project. Access to talented students is an additional advantage for the corporate partners; mentors can develop a pipeline of students for internship and full time job opportunities within the company.

== Mentor Palooza


== Agile
* Two week sprints.
* Example Two Week Sprint
** Week 1 
*** Lec: Sprint Planning with corporate 
*** Lab: Standup and working meeting
partner mentor(s)
** Week 2 
*** Lec: Sprint Review with corporate partner mentor
*** Lab: Standup, sprint retrospective, and working meeting



== Collaboration with TAs
TAs communicate the most with corporate partner mentors. Mentors know they can provide feedback, make suggestions or changes and assign deliverables through discussions with their TA and know that the TA will relay the information on to the team. This streamlined structure allows the mentor to focus on the project without having to communicate with several members of the team at once. 
