= Fall 2023 Announcements 

_Check this page frequently for announcements about the course. Announcements will also be emailed out to students._

== (August 30) The Data Mine is a welcoming learning environment

To anyone feeling nervous about your first week in The Data Mine, one of our TAs shared this. I hope this eases your mind that this is a learning environment and we are here to support you. Please know that you are always welcome to ask questions to The Data Mine staff, your TA, your Corporate Partner mentor, or your peers. We hope you have a phenomenal year learning in The Data Mine. 

> To anyone who feels nervous, I want to stress that this program is, by definition, a learning community. Last year my team had both PhD students and freshmen who had never taken a coding class in their life, and we created a space for everyone to learn, grow, and excel. We have worked very hard to ensure that people from all backgrounds and levels of experience are welcome. I promise if you put in genuine effort, you will have the resources you need to succeed.

== (August 21) Welcome to The Data Mine Corporate Partners!

Hello, and welcome to The Data Mine Corporate Partners! (TDM 111/211/311/411/511).

To get started, please click on xref:fall2023/introduction.adoc[Fall 2023 Introduction] on the left hand column. 

If you have questions, please check the xref:questions.adoc[questions page] before emailing our team. 

We look forward to working with you this academic year! 
