= Sprint #3

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 9/21
|Mon 9/18

|*Sprint End Date*
|Wed 10/4
|Sun 10/1

|*Due Date*
2+| Wed 10/4 by 11:59 PM ET

|===


== Sprint Tasks

[IMPORTANT]
====
This page is still being updated with sprint tasks. It will be finalized by the start of sprint so check back soon. 
====

=== &#10003; Professional Development 

==== Time Management

Tasks: 

* Watch video link:https://www.youtube.com/watch?v=tT89OZ7TNwc[Einshower Matrix]
* Review link:https://hbr.org/2018/12/how-timeboxing-works-and-why-it-will-make-you-more-productive[Time Boxing article] 

Knowledge Check: Screenshot your calendar (day or week) after implementing time boxing. Prioritize and identify urgent and important activities.

==== Self Awareness - Dealing with Change

Tasks: 

*  Listen to https://podcasts.apple.com/us/podcast/ted-talks-daily/id160904630?i=1000622303808[Podcast: Why change is so scary - and how to unlock it's potential]
*  Review Strategies for Continuous Learning Article below

++++
<iframe id="reading" style="border:1px solid #666CCC" title="PDF in an i-Frame" src="_attachments/Strategies_for_Becoming_a_Continuous_Learner.pdf" frameborder="1" scrolling="auto" height="1100" width="850" ></iframe>
++++


Knowledge Check: Complete a short reflection via GradeScope. 

*  Describe a significant change in your personal life, your academic life, or your public life that required you to respond by learning, adapting, and/or adjusting your knowledge, skills, and/or abilities.
*  Describe what you had to learn in order to respond to the change. 
*  Remember, continuous learning is not limited to taking a new and challenging class or enrolling at an institution to get a degree. This could be completing an assignment that required researching about a topic you were unfamiliar with, this could be attending an extra-curricular workshop where you learned something new or gained perspective about a topic, this could even be Googling something because you were curious about x topic. 


=== &#10003; Sprint #3 Report 

*When:* Due Wednesday, October 4, 2023 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in Sprint #3 Report. 

*Where:* link:https://www.gradescope.com/[Gradescope] 
