= Sprint #4

== Sprint Dates
_Monday, 10/9 and Tuesday, 10/10: October Break – No Classes_

_Thursday, 10/12 and Friday 10/13: All labs and meetings as usual. No changes on Wednesday, Thursday and Friday._


[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 10/5
|Mon 10/2

|*Sprint End Date*
|Wed 10/18
|Sun 10/15

|*Due Date*
2+| Wed 10/18 by 11:59 PM ET

|===


== Sprint Tasks

=== &#10003; Professional Development 

++++
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}

.accordion:after {
  content: '\002B';
  color: #777;
  font-weight: bold;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2212";
}

.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>
<button class="accordion">Ethics in Data Science</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, October 18, 2023 at 11:59 PM ET. Late work will not be accepted.
		</p>
	</div>
	<div>
		<p><b>What: </b>Watch this video <a href="https://www.youtube.com/watch?v=mA4gypAiRYU">Data Science Ethics in 6 minutes</a> and complete a short reflection in Gradescope</p>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training in <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 4: Professional Development".</a></p>
  </div>
</div>
<button class="accordion">Communication Strategies: Giving Feedback </button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, October 18, 2023 at 11:59 PM ET. Late work will not be accepted. 
		</p>
	</div>
	<div>
		<p><b>What: </b> Watch <a href="https://www.youtube.com/watch?v=wtl5UrrgU8c"> The Secret to Giving Great Feedback </a> and complete a short quiz on Gradescope.</a> </p>

	</div>
	<div>
		<p><b>Where: </b> Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 4: Professional Development".</a></p>
  </div>
</div>

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

</body>
</html>
++++

=== &#10003;Sprint #4 Report 

*When:* Due Wednesday, October 18, 2023 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in Sprint #4 Retro Report. 

*Where:* link:https://www.gradescope.com/[Gradescope] 
