= Sprint #2

== Sprint Dates

*_Monday, 9/4:  Labor Day (no Corporate Partner meetings/classes)_*

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 9/7
|Tues 9/5

|*Sprint End Date*
|Wed 9/20
|Sun 9/17

|*Due Date*
2+| Wed 9/20 by 11:59 PM ET

|===

== Sprint Tasks

=== &#10003; Github on Anvil (Setting up ssh keys)

As soon as possible, https://the-examples-book.com/starter-guides/tools-and-standards/git/github-anvil[Set up ssh key on Github for Anvil]. ssh key are the way for github to verify that you are who you say you are. This will allow you to push and pull code from your team's repository and collaborate with your team members on github.

=== &#10003; Starter Guides

Use these starter guides to up-skill during the first couple of sprints. You will be using these tools throughout the semester on your semester!

*When:* When you are ready to upskill!

*What:* Review the following xref:starter-guides:ROOT:introduction.adoc[Starter Guides] - there is nothing to submit for this item.

*Where:* xref:starter-guides:ROOT:introduction.adoc[Starter Guides]

=== &#10003; Professional Development 

The Data Mine Corporate Partners program is a professional development program. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

In each sprint you will complete a few professional development-related tasks. During this sprint, we will focus on creating an elevator pitch, updating resume/CV or practicing for interviews, and professional attire.

++++
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}

.accordion:after {
  content: '\002B';
  color: #777;
  font-weight: bold;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2212";
}

.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>
<button class="accordion">How to read scientific papers</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, September 20, 2023 at 11:59 PM ET. Late work will not be accepted.
		</p>
	</div>
	<div>
		<p><b>What: </b>Review <a href="https://the-examples-book.com/crp/students/reading_scientific_papers">How to read Scientific Paper</a> and complete "How to read scientific papers" section in "Sprint 2: Professional Development" .You may have the article open while you take the quiz. </a> </p>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 2: Professional Development".</a></p>
  </div>
</div>
<button class="accordion">Create a Elevator Pitch</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, September 20, 2023 at 11:59 PM ET. Late work will not be accepted. 
		</p>
	</div>
	<div>
		<p><b>What: </b>Review <a href="https://the-examples-book.com/crp/students/elevator_pitch">Elevator Pitch Guide.</a> and submit your elevator pitch in "Sprint 2: Professional Development".</p>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 2: Professional Development".</a></p>
  </div>
</div>
<button class="accordion">Update Resume/CV or Complete Mock Interview</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, September 20, 2023 at 11:59 PM ET. Late work will not be accepted.
		</p>
	</div>
	<div>
		<p><b>What: </b>Review <a href="https://the-examples-book.com/crp/students/resume_cv_interview">Update Resume/CV or Complete Mock Interview Assignment</a> and write a reflection in "Sprint 2: Professional Development".</p>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 2: Professional Development".</p>
  </div>
</div>
<button class="accordion">Professional Attire</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, September 20, 2023 at 11:59 PM ET. Late work will not be accepted.</p>
		</p>
	</div>
	<div>
		<p><b>What: </b>Review <a href="https://the-examples-book.com/crp/students/professional_attire_guide">Professional Attire Guidelines</a> and submit a photo of your business attire on "Sprint 2: Professional Development".</p>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 2: Professional Development".</p>
  </div>
</div>

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

</body>
</html>
++++

=== &#10003; Sprint #2 Report 

*When:* Due Wednesday, September 20, 2023 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in the Sprint #2 Report accessed on Gradescope. You will write your answers directly in the Gradescope assignment. 

*Where:* link:https://www.gradescope.com/[Gradescope] 


