= Sprint #2

== Sprint Dates

_Monday, 9/4:  Labor Day (no Corporate Partner meetings/classes)_

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 9/7
|Tues 9/5

|*Sprint End Date*
|Wed 9/20
|Sun 9/17

|*Due Date*
2+| Wed 9/20 by 11:59 PM ET

|===

== Sprint Tasks & Professional Development

This week sprint task will be focus on setting up ssh keys on github to allow for collaboration between team members. ssh key are the way for github to verify that you are who you say you are. This will allow you to push and pull code from your team's repository. Additionally, you will learn how to extract key information from scientific papers during this sprint.

With campus career fairs right around the corner. This sprint professional development will focus on networking, resume, and professional interviews.

Please visit https://www.cco.purdue.edu/Calendar/[CCO Calendar] to find campus opportunities.

=== &#10003; Github on Anvil (Setting up ssh keys)

As soon as possible, https://the-examples-book.com/starter-guides/tools-and-standards/git/github-anvil[Set up Github on Anvil].

=== &#10003; How to read scientific papers

Please see xref:reading_scientific_papers.adoc[How to read Scientific Paper] for assignment details.

Knowledge Check: Quiz on Gradescope.

=== &#10003; Create a Elevator Pitch

A strong elevator pitch can differentiate you from your peers and make strong first impression to employers/co-workers. Create a 30-second elevator.

Please see xref:elevator_pitch.adoc[Elevator Pitch] for assignment details.

Knowledge Check: Create a 30-second elevator.

=== &#10003; Update Resume/CV or Complete Mock Interview

Having a clear,concise, and updated CV/resume is imperative in the job/internship search. Please create or update your existing CV or Resume. You can also choose to complete a mock interview.

Please see xref:resume_cv_interview.adoc[Update Resume/CV or Complete Mock Interview] for assignment detail.

Knowledge Check: Update CV or Resume or complete a mock interview

[NOTE]
====
According to estimates by the U.S. Equal Employment Opportunity Commission, "as many as 83 percent of employers and up to 99 percent of Fortune 500 companies now use some form of automated tool to screen or rank candidates for hire" https://www.eeoc.gov/meetings/meeting-january-31-2023-navigating-employment-discrimination-ai-and-automated-systems-new/transcript[eeoc.gov]
====

=== &#10003; Dress for Success

Please see xref:professional_attire_guide.adoc[Professional Attire Guide] for assignment detail.

Knowledge Check: Upload photo of your professional attire to Gradescope.

=== &#10003; Sprint #2 Report 

*When:* Due Wednesday, September 20, 2023 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in the Sprint #2 Report accessed on Gradescope. You will write your answers directly in the Gradescope assignment. 

*Where:* link:https://www.gradescope.com/[Gradescope] 

