= Sprint #4

== Sprint Dates
_Monday, 10/9 and Tuesday, 10/10: October Break – No Classes_

_Thursday, 10/12 and Friday 10/13: All labs and meetings as usual. No changes on Wednesday, Thursday and Friday._


[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 10/5
|Mon 10/2

|*Sprint End Date*
|Wed 10/18
|Sun 10/15

|*Due Date*
2+| Wed 10/18 by 11:59 PM ET

|===


== Sprint Tasks

[IMPORTANT]
====
This page is still being updated with sprint tasks. It will be finalized by the start of sprint so check back soon. 
====

=== &#10003; Professional Development 

==== Ethics in Data Science

Tasks: 

* Watch video link:https://www.youtube.com/watch?v=mA4gypAiRYU[Data Science Ethics in 6 minutes]

Knowledge Check: Complete a short reflection via link:https://www.gradescope.com/[GradeScope].

* What is one key takeaway from the video on data science ethics that will be important for your project team to remember? Think about the impacts of the project outcomes and products your team is creating or will create... could the end users or customers of the products experience unintended risks or adverse outcomes? 

==== Communication Strategies: Giving Feedback 

Tasks: 

*  Watch Video link:https://www.youtube.com/watch?v=wtl5UrrgU8c[The Secret to Giving Great Feedback]

Knowledge Check: Complete a short quiz via link:https://www.gradescope.com/[GradeScope]. 

=== &#10003;Sprint #4 Report 

*When:* Due Wednesday, October 18, 2023 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in Sprint #4 Retro Report. 

*Where:* link:https://www.gradescope.com/[Gradescope] 
