= Sprint #1

== Sprint Dates
_All sprints will have the same due dates_, but the sprint start and end dates are slightly shifted depending on when a team has their lab (2 hours) and lecture (50 minutes). This is so that sprints always start with a lec and follow the format lec-lab-lec-lab.

You can find a xref:agile:ceremonies.adoc#sprint-schedule[visual of the sprint schedule in the Agile Training Ceremonies page]. More details will be covered in the agile training below. 


[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|*Mon 8/21 
|Mon 8/21 

|*Sprint End Date*
|Wed 9/6
|Sun 9/3

|*Due Date*
2+| Wed 9/6 by 11:59 PM ET

|===

_*Please note that sprint 1 starts on August 21, the first day of fall 2023 semester, for both schedules. Once we are in a regular sprint schedule, you will see the lab then meeting schedule shift to starting on Thursdays._

== Sprint Tasks

=== &#10003; Anvil Access

As soon as possible, link:https://the-examples-book.com/starter-guides/data-engineering/rcac/access-setup[please create an ACCESS account to access Anvil]. Students in the 1 credit hour seminar TDM 101/201/301/401/501 have to do this too. You only need to create *one* account that you will use for seminar and Corporate Partners. _*Do not submit this more than once.*_ 

=== &#10003; Syllabus Quiz

While all teams will work on different projects and mentors will provide a project charter, the syllabus includes information that every Data Mine Corporate Partner student needs to know. 

*When:* Due Wednesday, September 6, 2023 at 11:59 PM ET. Late work will not be accepted.  

*What:* Review the xref:fall2023/syllabus.adoc[fall 2023 syllabus page] and xref:fall2023/schedule.adoc[fall 2023 course schedule]. Take the quiz up to 3 times and your highest score will be taken. You may have the syllabus open while you take the quiz.

*Where:* Take the quiz on link:https://www.gradescope.com/[Gradescope] 

_Please note there is a separate syllabus quiz for the 1 credit seminar class (TDM 101, 201, 301, 401, 501)._


=== &#10003; Agile Training 

The Data Mine Corporate Partners will implement Agile methods into our project management. Agile is very popular in industry and the majority of our Corporate Partners use it. Now is the best time to practice it while you are a student. 

During your first or second lab session, you will be using Legos to learn the Agile approach to project management. Your TA will be facilitating this Lego lab. We encourage you to review this link:https://thisiszone.medium.com/using-lego-to-show-the-advantages-of-an-agile-approach-to-software-development-3eda6e5c2114[article]. 

*When:* Due Wednesday, September 6, 2023 at 11:59 PM ET. Late work will not be accepted. 

*What:* Complete the xref:agile-training.adoc[Agile in The Data Mine Training], participant in the Lego lab activity, and take the quiz. 

*Where:* Take the quiz on link:https://www.gradescope.com/[Gradescope] 

=== &#10003; The Data Mine Pre-Assessment 

The Data Mine Corporate Partners wants to proactively collect your feedback on The Data Mine experience. To assist with this, we are asking all students to complete a pre-assessment at the beginning of the semester. Later in the school year, you will complete a mid-year and final assessment.

*When:* Due Wednesday, September 6, 2023 at 11:59 PM ET. This assignment is required 

*What:* Complete the Pre-Assessment survey.

*Where:* Take the quiz on link:https://www.gradescope.com/[Gradescope] 

=== &#10003; Professional Development 

The Data Mine Corporate Partners program is a professional development program. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

Each sprint you will complete a few professional development related tasks. To begin, let's review confidentiality, netiquette, and email communication.

++++
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}

.accordion:after {
  content: '\002B';
  color: #777;
  font-weight: bold;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2212";
}

.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>

<button class="accordion">Confidentiality</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, September 6, 2023 at 11:59 PM ET. Late work will not be accepted.
		</p>
	</div>
	<div>
		<p><b>What: </b>Complete Purdue's <a href="https://www.eventreg.purdue.edu/WebCert/CourseListing.aspx?master_id=5398&master_version=1&course_area=CERT&course_number=340&course_subtitle=00">Data Classification and Handling Training</a>.<b> If you believe that data was incorrectly handled or shared, please notify datamine@purdue.edu immediately.</b></p>
	</div>
	<div>
		<p><b>Where: </b>Upload a screenshot confirming your completion of the training to <a href="https://www.gradescope.com/">Gradescope</a></p>
  </div>
</div>
<button class="accordion">Virtual Meeting Expectations</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, September 6, 2023 at 11:59 PM ET. Late work will not be accepted.
		</p>
	</div>
	<div>
		<p><b>What: </b>Watch this short video on <a href="https://youtu.be/HYUVXQfaVp0">Virtual Meeting Etiquette</a> (8 minutes).</p>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training here: <a href="https://www.gradescope.com/">Gradescope</a></p>
  </div>
</div>
<button class="accordion">Email Communication</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, September 6, 2023 at 11:59 PM ET. Late work will not be accepted.
		</p>
	</div>
	<div>
		<p><b>What: </b>Read the following article on <a href="https://sparkmailapp.com/formal-email-template">How to Write a Formal Email</a> (5 minutes).</p>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training here: <a href="https://www.gradescope.com/">Gradescope</a></p>
  </div>
</div>

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

</body>
</html>
++++

=== &#10003; Sprint #1 Report 

*When:* Due Wednesday, September 6, 2023 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in the Sprint #1 Retro Report accessed on Gradescope. You will write your answers directly in the Gradescope assignment. 

*Where:* link:https://www.gradescope.com/[Gradescope] 