= Fall Wrap-Up

== Week 16

Monday, 12/5 – Friday 12/9: Final team presentations during your regularly scheduled 50-minute team meeting.

=== General Tasks
&#10003; Optional: I hosted office hours.

&#10003; I attended the required number of meetings for being a TA. 

&#10003; I sent out meeting notes to the team with any announcements, thank yous to my team for their hard work this fall, assignments, and plan for after break.

&#10003; Finished my time sheet and turned it in.

&#10003; Entered my hours into link:https://one.purdue.edu[SuccessFactor]. 

&#10003; Finished my weekly report and turned it in.
 
=== Grading 
&#10003; Grading Sprint Report #7 due on GradeScope by 11:59 PM ET on Sunday, 12/11

=== Special Tasks
&#10003; Final Presentation!

&#10003; I took attendance at the Final Fall Presentation.

&#10003; Started planning for after break.

== Week 17
Final Exam Week - no meetings in Corporate Partners

== Week 18 
Tuesday, 12/20: Fall 2022 (student) grades are submitted to Registrar’s Office by 5 PM ET