= TA Fall 2022 Schedule
Here you will find a link to the student schedule as well as a schedule designed for TAs. 

Each Corporate Partner mentor will have their own schedules and due dates, but here is the schedule for the general due dates assignments to be submitted to The Data Mine staff: 

Due dates are listed in *BOLD*. Other dates are important notes.
If you will be late for a deadline due to illness or other unforeseen circumstances, please email the Head TA to make sure it will not count against you.

You can find guides how to complete Team Reports, Time Sheets, Labs, Grading, Check-Ins, and Feedback in the expectations and resource branches.  

// [IMPORTANT]
// ====
// *CONTENT STILL UNDER CONSTRUCTION FOR FALL 2022!!!!*

// The dates in this document are not completely finalized at this time. 

// ====

Navigate to xref:students:fall2022/schedule.adoc[Fall 2022 Student Schedule] to view student deadlines.

TA Gathering Expectations:

1. Attend at least one TA gathering a month.
2. Attend one low-ropes course to get to know your colleges. 
3. Stop by for a 15-20 minute check-in with The Data Mine staff each week. This can be right after your lab if staff is available. 
4. Meet your deadlines. 


++++
<iframe width = "800" height = "400" title="Student Schedule" scrolling="yes"
src="https://docs.google.com/spreadsheets/d/e/2PACX-1vROThOUhbjMNgmk7jBCUN_9isuX9bQsbm_LQxQoHNqqRaVbqJv4oBHf10hGKmWGqWBjG900Gj2lwH2x/pubhtml?widget=true&amp;headers=false" & wdDownloadButton="True"></iframe>
++++

Make your own copy of the guide by navigating to the link:https://docs.google.com/spreadsheets/d/1t_qkmAo_S1u_rGhZhEZ-AMKwU4AZcFcGjyfQkYK8ots/edit?usp=sharing[TA Assignment Schedule]. 

[Disclaimer]
----
If any changes are made, they will appear here. They will not appear in copies.
----