= Sprint #7

== Week 13

Monday, 11/14: Start of Sprint #7 (sprint is 3 weeks due to Thanksgiving break)

=== General Tasks

&#10003; Planned lab! 

&#10003; Completed attendance for lab.

&#10003; Took notes at lab.

&#10003; Discussed with my mentor what to cover at the meeting.

&#10003; Completed attendance for the meeting.

&#10003; Took notes at the meeting. 

&#10003; Optional: I hosted office hours.

&#10003; I attended the required number of meetings for being a TA. 

&#10003; I sent out meeting notes to the team with any announcements, assignments, and plan for the next week.

&#10003; Finished my time sheet and turned it in.

&#10003; Entered my hours into link:https://one.purdue.edu[SuccessFactor]. 

&#10003; Finished my weekly report and turned it in.

=== Grading

&#10003; Graded Sprint Report #6 due on GradeScope by 11:59 PM ET Sunday, 11/20

=== Special Tasks

Data Mine Staff returns feedback on presentations during your lab time. Reviewed Data Mine Staff feedback on presentation with the team. Made necessary changes to our presentation.

&#10003; Set-up a meeting with my mentor to complete final semester feedback, due (12/1).

xref:resources/mentor_feedback.adoc[How to Provide Feedback]


== Week 14
Wednesday, 11/23 – Friday, 11/25: Thanksgiving break – No Classes

=== General Tasks
&#10003; Planned lab! 

&#10003; Completed attendance for lab.

&#10003; Took notes at lab.

&#10003; Discussed with my mentor what to cover at the meeting.

&#10003; Completed attendance for the meeting.

&#10003; Took notes at the meeting. 

&#10003; Optional: I hosted office hours.

&#10003; I attended the required number of meetings for being a TA. 

&#10003; I sent out meeting notes to the team with any announcements, assignments, and plan for the next week.

&#10003; Finished my time sheet and turned it in.

&#10003; Entered my hours into link:https://one.purdue.edu[SuccessFactor]. 

&#10003; Finished my weekly report and turned it in.

=== Special Tasks
&#10003; Set-up a meeting with my mentor to complete final semester feedback, due next Thursday (12/1)!

xref:resources/mentor_feedback.adoc[How to Provide Feedback]

== Week 15

=== General Tasks
&#10003; Planned lab! Practice for the final presentation. Begin to discuss plans for after break (document). Tie any loose ends for Fall including thorough documentation of Fall work.

&#10003; Completed third required semester check-in with students (can be completed in Week 14 if needed).

&#10003; Completed attendance for lab.

&#10003; Took notes at lab.

&#10003; Discussed with my mentor what to cover at the meeting.

&#10003; Completed attendance for the meeting.

&#10003; Took notes at the meeting. 

&#10003; Optional: I hosted office hours.

&#10003; I attended the required number of meetings for being a TA. 

&#10003; I sent out meeting notes to the team with any announcements, assignments, and plan for the next week.

&#10003; Finished my time sheet and turned it in.

&#10003; Entered my hours into link:https://one.purdue.edu[SuccessFactor]. 


&#10003; Finished my weekly report and turned it in.

=== Special Tasks 
Final Presentation Practice Sessions and Revisions during your lab time.

&#10003; Completed final student feedback due 11:59 PM ET *Thursday*, 12/1