= Sprint #7

== Week 13

Monday, 11/14: Start of Sprint #7 (sprint is 3 weeks due to Thanksgiving break)

Data Mine Staff returns feedback on presentations during your lab time

&#10003; Planned lab! 

&#10003; Reviewed Data Mine Staff feedback on presentation with the team.

&#10003; Completed attendance for lab.

&#10003; Took notes at lab.

&#10003; Discussed with my mentor what to cover at the meeting.

&#10003; Completed attendance for the meeting.

&#10003; Took notes at the meeting. 

&#10003; Optional: I hosted office hours.

&#10003; I attended the required number of meetings for being a TA. 

&#10003; I sent out meeting notes to the team with any announcements, assignments, and plan for the next week.

&#10003; Finished my time sheet and turned it in.

&#10003; Entered my hours into SuccessFactor. 

&#10003; Finished my weekly report and turned it in.

&#10003; Graded Sprint Report #6 due on GradeScope by 11:59 PM ET Sunday, 11/20

== Week 14
Wednesday, 11/23 – Friday, 11/25: Thanksgiving break – No Classes

&#10003; Planned lab! 

&#10003; Completed attendance for lab.

&#10003; Took notes at lab.

&#10003; Discussed with my mentor what to cover at the meeting.

&#10003; Completed attendance for the meeting.

&#10003; Took notes at the meeting. 

&#10003; Optional: I hosted office hours.

&#10003; I attended the required number of meetings for being a TA. 

&#10003; I sent out meeting notes to the team with any announcements, assignments, and plan for the next week.

&#10003; Finished my time sheet and turned it in.

&#10003; Entered my hours into SuccessFactor. 

&#10003; Finished my weekly report and turned it in.

== Week 15

Final Presentation Practice Sessions and Revisions during your lab time.

&#10003; Planned lab! 

&#10003; Completed attendance for lab.

&#10003; Took notes at lab.

&#10003; Discussed with my mentor what to cover at the meeting.

&#10003; Completed attendance for the meeting.

&#10003; Took notes at the meeting. 

&#10003; Optional: I hosted office hours.

&#10003; I attended the required number of meetings for being a TA. 

&#10003; I sent out meeting notes to the team with any announcements, assignments, and plan for the next week.

&#10003; Finished my time sheet and turned it in.

&#10003; Entered my hours into SuccessFactor. 

&#10003; Finished my weekly report and turned it in.