= Sprint #3

== Week 5

=== General Tasks
&#10003; Planned lab! 



&#10003; Completed attendance for lab.

&#10003; Took notes at lab.

&#10003; Discussed with my mentor what to cover at the meeting.

&#10003; Completed attendance for the meeting.

&#10003; Took notes at the meeting. 

&#10003; Optional: I hosted office hours.

&#10003; I attended the required number of meetings for being a TA. 

&#10003; I sent out meeting notes to the team with any announcements, assignments, and plan for the next week.

&#10003; Finished my time sheet and turned it in.

&#10003; Entered my hours into link:https://one.purdue.edu[SuccessFactor]. 


&#10003; Finished my weekly report and turned it in.

=== Grading
&#10003; Graded Sprint Report #2 due on GradeScope by 11:59 PM ET Sunday, 9/25

=== Special Tasks
&#10003; Completed first required semester check-in with students during lab.

xref:expectations/check_ins.adoc[Expectations for Check-Ins]

== Week 6

=== General Tasks
&#10003; Planned lab! 

&#10003; Completed attendance for lab.

&#10003; Took notes at lab.

&#10003; Discussed with my mentor what to cover at the meeting. 

&#10003; Completed attendance for the meeting.

&#10003; Took notes at the meeting. 

xref:expectations/meeting_notes.adoc[Meeting Notes Expectation Reminder]

&#10003; Optional: I hosted office hours.

&#10003; I attended the required number of meetings for being a TA. 

&#10003; I sent out meeting notes to the team with any announcements, assignments, and plan for the next week.

&#10003; Finished my time sheet and turned it in.

&#10003; Entered my hours into link:https://one.purdue.edu[SuccessFactor]. 


&#10003; Finished my weekly report and turned it in.