= Sprint #6

== Sprint Dates
If you have your lab earlier in the week than your meeting, then you follow the "lab-meeting" sprint schedule (Wednesday Cycle).

* Monday lab and Friday meeting
* Tuesday lab and Thursday meeting

Sprint 6 Dates: November 2, 2022 - November 16, 2022

If you have your meeting earlier in the week than your lab, then you follow the "meeting-lab" sprint schedule (Sunday Cycle).

* Monday meeting and Friday lab
* Tuesday meeting and Thursday lab

Sprint 6 Dates: October 30, 2022 - November 13, 2022

== To Do

&#10003; The team started the Final Fall Presentation (2 weeks till due date).

&#10003; Assigned speaking parts for the Final Fall Presentation. This even includes back-up speakers! 

xref:fall2022/final_presentation.adoc[Final Fall Presentation Details]

&#10003; Turned in the team *Final Presentation draft* materials by 11:59 PM ET on Sunday, 11/13

xref:fall2022/final_presentation.adoc[Final Fall Presentation Details]

&#10003; See the xref:fall2022/schedule.adoc[Fall Schedule] for timesheet and report deadlines.