= Sprint #4


== Week 7

=== General Tasks
&#10003; Planned lab! 

&#10003; Completed attendance for lab.

&#10003; Took notes at lab.

&#10003; Discussed with my mentor what to cover at the meeting. 

&#10003; Completed attendance for the meeting.

&#10003; Took notes at the meeting. 

&#10003; Optional: I hosted office hours.

&#10003; I attended the required number of meetings for being a TA. 

&#10003; I sent out meeting notes to the team with any announcements, assignments, and plan for the next week.

&#10003; Finished my time sheet and turned it in.

&#10003; Entered my hours into link:https://one.purdue.edu[SuccessFactor]. 


&#10003; Finished my weekly report and turned it in.

=== Grading
&#10003; Graded Sprint Report #3 due on GradeScope by 11:59 PM ET Sunday, 10/9

== Week 8
Monday, 10/10 & Tuesday, 10/11: Fall Break - No Classes

=== General Tasks
&#10003; Planned lab! 

&#10003; Completed attendance for lab.

&#10003; Took notes at lab.

&#10003; Discussed with my mentor what to cover at the meeting.

&#10003; Completed attendance for the meeting.

&#10003; Took notes at the meeting. 

&#10003; Optional: I hosted office hours.

&#10003; I attended the required number of meetings for being a TA. 

&#10003; I sent out meeting notes to the team with any announcements, assignments, and plan for the next week.

&#10003; Finished my time sheet and turned it in.

&#10003; Entered my hours into link:https://one.purdue.edu[SuccessFactor]. 


&#10003; Finished my weekly report and turned it in.

=== Special Tasks
&#10003; Set-up a meeting with my mentor to complete mid-semester feedback.

xref:resources/mentor_feedback.adoc[How to Provide Feedback]