= Sprint #5


== Week 9

&#10003; Planned lab! 

&#10003; Completed attendance for lab.

&#10003; Took notes at lab.

&#10003; Discussed with my mentor what to cover at the meeting.

&#10003; Completed attendance for the meeting.

&#10003; Took notes at the meeting. 

&#10003; Optional: I hosted office hours.

&#10003; I attended the required number of meetings for being a TA. 

&#10003; I sent out meeting notes to the team with any announcements, assignments, and plan for the next week.

&#10003; Finished my time sheet and turned it in.

&#10003; Entered my hours into SuccessFactor. 

&#10003; Finished my weekly report and turned it in.

&#10003; Graded Sprint Report #4 due on GradeScope by 11:59 PM ET Sunday, 10/23

== Week 10


&#10003; Planned lab! 

&#10003; Completed attendance for lab.

&#10003; Took notes at lab.

&#10003; Discussed with my mentor what to cover at the meeting.

&#10003; Completed attendance for the meeting.

&#10003; Took notes at the meeting. 

&#10003; Optional: I hosted office hours.

&#10003; I attended the required number of meetings for being a TA. 

&#10003; I sent out meeting notes to the team with any announcements, assignments, and plan for the next week.

&#10003; Finished my time sheet and turned it in.

&#10003; Entered my hours into SuccessFactor. 

&#10003; Finished my weekly report and turned it in.