= git

* xref:introduction-git.adoc[Introduction (this page)]
* xref:github-desktop.adoc[GitHub Desktop]
* xref:workflows.adoc[Workflows]
* xref:github-anvil.adoc[Setup git on Anvil] <- do this once
* xref:git-cli.adoc[git CLI on Anvil] <- do this repeatedly when editing and pushing code
* xref:terminology.adoc[Terminology]

== What is `git`?

`git` is a powerful version control software written by Linus Torvalds, the inventor of the Linux kernel. `git` has a reputation for being complicated and confusing. While there may be some truth to this, `git` is used extensively in industry, and is relied upon by many of the applications being developed today.

While there are certainly advantages to understanding `git` in detail, it is unnecessary for many projects. It is possible to get the "gist" of `git` by learning some basic terminology, workflows, and how `git` fits into a regular data science or software project. For this book, this is our goal. We want to provide you with the smallest amount of information that allows you to incorporate `git` into your project, or helps you feel comfortable using `git` in an already established project. If you want to take a deeper dive into `git`, check out the <<resources, resources section>> below.

== git vs. GitHub

While `git` may be largely synonymous with GitHub, they are distinct _things_. `git` is a piece of software running on your computer -- your **local** system. You can use `git` without using GitHub (or another host like GitLab). `git` works just like other familiar programs like `grep` or `sed`. Like `grep` or `sed`, you can read about the commands and options by reading the `man` (short for manual) pages.

[source, bash]
----
man git
----

https://github.com[Microsoft's GitHub], however, is a software development and version control platform, hosted online. `git` is a complicated tool, and platforms like GitHub aim to make using `git` as pain-free as possible. It is free and easy to create a GitHub account. Other competing platforms include: https://gitlab.com[GitLab], https://sr.ht/[sourcehut], https://gitea.io[Gitea], and https://bitbucket.org[Bitbucket]. Each platform has their advantages and disadvantages, but all largely serve the same purpose.

== Resources

https://docs.github.com/en/github/getting-started-with-github/quickstart/github-glossary[GitHub Glossary]

A glossary with common `git` and GitHub-related terminology.

https://learngitbranching.js.org/[Learn Git Branching]

An interactive in-browser game to help learn about `git` and `git` branching.

=== Books

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99170207244401081[Learn Git in a Month of Lunches (2015)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99170207203301081[Building Tools With Github (2016)]

https://gitforteams.com[Git For Teams (2016)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99170340889501081[Version Control With Git, 3rd Edition (2022)]
