= Basics Of Data Visualization  
Doc Writer <shah833@purdue.edu>
:reproducible:
:listing-caption: Listing
:source-highlighter: rouge
:toc:
// Uncomment next line to add a title page (or set doctype to book)
//:title-page:
// Uncomment next line to set page size (default is A4)
//:pdf-page-size: Letter

An example of a basic https://asciidoc.org[AsciiDoc] document prepared by {author}.

== Introduction

Data visualization refers to the graphical representation of information and data. It helps to understand, analyze and communicate complex data in a clear and effective manner. Some popular tools for data visualization include

[square]
* Matplotlib: a plotting library for the Python programming language
* ggplot2: a data visualization package for the R programming language
* D3.js: a JavaScript library for creating dynamic and interactive data visualizations in web browsers
* Tableau: a commercial data visualization and business intelligence software
* Power BI: a business analytics service by Microsoft that provides interactive visualizations and business intelligence capabilities with an interface easy to use for end users to create their own reports and dashboards

== Categories in Data Visualization

=== Relationships

[square]
* Scatterplot: Demonstrate the relationship between two variables, independent variable x, and dependent variable y
* Bubble Chart: Demonstrate the relationship between three variables, x, y, and bubble size

=== Comparisons
[square]
*	Bar Chart: Used for comparing two different variables, example
*	Line Chart: For comparing the median and average values over some independent variable. Comparisons are also used for showing the trend of the data

=== Distributions
[square]
*	Histogram: To showcase the distribution of the data, to know the mean and standard deviation of the data
*	Box Plot: Used to show the maximum, minimum value, median, and lower quartile and upper quartile. And it depicts outliers in the plot too.

=== Compositions
[square]
*	Pie Chart: Composition of different categories in a 'pie'
*	Stacked Bar Chart: Stack different compositions in a bar chart
*	Stacked Area Chart: Stack different compositions in an area fashion

== Process of data visualization

[square]
* Acquiring data: collecting data from various sources such as databases, spreadsheets, or APIs
* Cleaning and transforming data: preparing the data for visualization by cleaning, transforming and aggregating it
* Choosing the right type of visualization: selecting the best visualization technique based on the type and nature of data
* Creating the visualization: using tools and software to create the actual visualization
* Interpreting the visualization: analyzing the visualization to derive insights and draw conclusions

== Misinterpreting of data visualization

== Conclusion

That's all, folks!
