= TDM 40200

All of the homeworks are in a Jupyter notebook and contain the instructions and links to materials needed to be successful for that homework. Each week we will release a folder that contains the notebook (as well as supplementary data or images). The general process to retrieve and work on homeworks is:

0. Make a Seminar directory and get the Fetch Homework notebook (Do This Once)
1. Use the fetch_homework Notebook to Retrieve Homework
2. Finish the Homework
3. Submit to Gradescope

== 0. Make a Seminar directory and get the Fetch Homework notebook (Do This Once)

Run the following in a terminal on Anvil:

[source,bash]
----
mkdir $HOME/seminar/
cp /anvil/projects/tdm/seminar/tdm_40200/fetch_homework.ipynb $HOME/seminar/
----

== 1. Use the fetch_homework Notebook to Retrieve Homework

Each week you can open this notebook, go to the corresponding week, and run the bash command to retrieve the notebook.

== 2. Finish the Homework

Once fetched, the homework will appear in your home directory (in the `seminar` folder). There are 5 points total each week; some questions are worth more than 1 point, but at most you will have 5 questions.

== 3. Submit to Gradescope

Go to Gradescope and submit the code like usual, following the rules at https://the-examples-book.com/projects/current-projects/submissions apply!