= College of Science Learning Outcomes

== Mapping and Assessment for Foundational Learning Outcome

=== Project 1. Introduction to High Performance Computing

Using High Performance Computing environments for the first time requires students to think about the computational process in abstract ways, i.e., about the computing environment, resources, constraints, memory allocations, scheduling, abstraction and algorithmic concepts, etc.  We will not only enable the students to utilize HPC environments for the first time, but we will ask the students critical questions about these environments, shared usage, resources, allocations, etc.

(CT1) Students will formulate problem definitions suited for technology-assisted methods such as data analysis, abstract models, and algorithmic thinking in exploring and finding solutions.

=== Project 2. Assessment of Online Data and Scraping Data from the Web

Assessing online repositories and systematically scraping data from the internet involves numerous layers of planning, not only for the digital tools needed to achieve web scraping, but also for strategies about respecting copyright laws, documentation, bandwidth limitations, authorship and consent for sharing digital media, conflict resolution, digital security, etc.  In additional to having students learn about digital scraping tools, we will integrate questions about digital privacy, security, copying, and authorship, so that when students scrape data from the internet, they are more likely to do it in ethical ways.

(CT2) Students will collect data or identify relevant data sets, use digital tools to analyze them, and represent data in various ways to facilitate problem-solving and decision-making. 

(DC1) Students will cultivate and manage their digital identity and reputation and will be aware of the permanence of their actions in the digital world. 

(KC4) Students will build knowledge by actively exploring real-world issues and problems, developing ideas and theories, and pursuing answers and solutions.

(SS6) Students will identify the problem(s), identify strategies for resolving the conflict, select a strategy appropriate to the situation and relationship, implement the appropriate strategy, and enlist support when needed.

=== Project 3. Introduction to Large Language Models

We will ask students to think critically about the pro's and con's of LLMs, including their limitations, their tuning, characteristics of the models, and the degree to which various models will perform strongly or poorly.  We will ask students to explain their decision-making process while working through the various types of LLMs.

(CC1) Students will choose the appropriate platforms and tools for meeting the desired objectives of their creation or communication.

(RDM3) Students will evaluate and reflect on their decision-making process.

=== Project 4. Creating Large Language Models

While creating language models, although students are familiar with using generative AI, this will (likely) be their first time creating their own LLMs.  We will encourage students to work through the challenges inherent in customizing and tailoring LLMs, in learning about threads and cores and computational requirements.  Students will need to feel comfortable being uncomfortable with the behind-the-scenes concepts about creating LLMs, likely for the first time.

(APA2) Students will build awareness of their own learning needs and will intentionally strive to move beyond their comfort zone.

(DC4) Students will manage their personal data to maintain digital privacy and security and are aware of data-collection technology used to track their navigation online.

=== Project 5. Fine Tuning Large Language Models

While fine-tuning their language models, students will reflect on the strengths and weaknesses of the language models that they are turning.  We will ask students to (also) characterizing the strengths and weaknesses of language models that their peers are tuning.  We believe that, in this way, students have an excellent opportunity to critically examine their own work and the work of their peers, especially as it relates to their problem solving work on the fine tuning of language models.

(CC4) Students will publish or present content that customizes the message and medium for their intended audiences.

(EF6) Students will accurately label strengths and weaknesses, identify impact of personal behavior on self and others, label when things break down, and recognize need for problem solving.

=== Project 6. Understanding Agent-Based Models

As they are learning about what is feasible for an agent-based model to accomplish, students will generate ideas about "the art of the possible" about what single-agent models can accomplish.  Students will brainstorm, will share ideas with classmates, with the TAs, and with the instructor, and will being preparing for the subsequence project, in which they implement and deploy a single-agent model.

(EF2) Students will begin an activity, begin generating ideas.

(P1) Students will express comfort with people who are both similar to and different from them and engage respectfully with all people.

(RDM2) Students will demonstrate agency and personal choice through their engagement in activities.

=== Project 7. Creating a Single-Agent Model

Students will have some freedom about choosing the type of single-agent model to implement in this project and in the previous project.  Students will be encouraged to balance their technical skills (to date) with what is achievable and realistic for a single-agent model to perform.

(SC2) Students will set goals that are: specific, measurable, action-oriented, realistic, and timely and review progress towards goals by evaluating and revising.

(SS7) Students will demonstrate the ability to see a situation from a view other than own, empathize with a view other than own, and alter actions toward a person, situation, or idea in response to another point of view.

=== Project 8. Introduction to AI Tools for Image Processing

As students learn about the ways that AI tools can be used for image processing and image analysis, we will also ask the students to reflect on the ways that such visualizations are clear and effective.  We will ask the students to consider issues about authorship, ethics, documentation of image manipulation, copying, sources of images, etc.

(CC3) Students will communicate complex ideas clearly and effectively by creating or using a variety of digital objects such as visualizations, models, or simulations.

(KC2) Students will evaluate the accuracy, perspective, credibility, and relevance of information, media, data, or other resources.

(SS3) Students will behave in a socially acceptable way relative to the situation, people involved, and timing.

(SS5) Students will shift behavior and language relative to the situation, people involved, and timing.

=== Project 9. Using AI to Implement Image Processing

Students will be asked to describe the ethical and practical challenges that arise in image processing, e.g., with authorship, copying, online fake images, impersonate, etc.  Students will communication about assumptions and will articulate their understanding about learned best practices related to image processing.

(CR1) Students will name and challenge assumptions.

(DC2) Students will engage in positive, safe, legal, and ethical behavior when using technology, including social interactions online or when using networked devices. 

(EL4) Students will understand the fundamental concepts of technology operations, demonstrate the ability to choose, use, and troubleshoot current technologies, and be able to transfer their knowledge to explore emerging technologies.

(SS4) Students will initiate conversations appropriately, sustain conversations or interaction appropriately, demonstrate active listening, close a conversation or end an interaction appropriately, interpret non-verbal cues appropriately, and communicate information effectively when making a presentation.

(SS9) Students will work and communicate with a partner to accomplish a task, work and communicate with several other people to complete a task, use compromise to advance larger goals, and divide tasks fairly and effectively, taking into account individual strengths, weaknesses, and availability.

=== Project 10. Introduction to Containerization and APIs

APIs are usually used in such a way that computing tools can be integrated into digital workflows.  We will ask students to reflect on the ways that APIs are utilized in their digital life, e.g., to connect digital tools that they may (otherwise) take for granted.  We will ask the students to set goals about understanding and reflecting on the usage and integration of APIs throughout their digital lives, especially the ways that APIs allow for a multiplicative usage of digital tools by students as they leverage technology.

(DC3)  Students will demonstrate an understanding of and respect for the rights and obligations of using and sharing intellectual property.

(EL1) Students will articulate and set personal learning goals, develop strategies leveraging technology to achieve them, and reflect on the learning process itself to improve learning outcomes.

=== Project 11. Container Builds and API Connectivity

During the container build project, we will encourage students to work together to understand the aspects of container builds.  This will include holistic thinking about the tools, data, workflows, structure, etc., inherent in a container.  Because a container build requires comprehensive building stages, flexible thinking, planning, and (usually) frequent rounds of revision, we believe that this project will be an excellent team-oriented project.  In particular, we will encourage students to think about internal container design and also the external connectivity with a container via APIs.

(CR3) Students will embrace challenge and failure to build resiliency and a growth mindset.

(EF1) Students will transition between activities or situations, move freely between aspects of a problem, or think flexibly around problem solving.

(EF4) Students will develop appropriate sequence of steps to carry out a task or action, implement appropriate sequence of steps to carry out a task or action, manage time effectively, and maintain a system for holding and retrieving information – applying memory strengths or compensatory strategies.  

=== Project 12. Introduction to Streaming Databases

As the students learn about streaming databases (likely for the first time), they will need to learn not only about structured data, but also about synchronization, descriptive data models, categories of data, primary versus foreign keys, and complexity of streaming systems, in which the databases are growing and changing even as the users are making queries in time-sensitive applications.

(CT3) Students will break problems into component parts, extract key information, and develop descriptive models to understand complex systems or facilitate problem-solving.

(GC4) Students will explore local and global issues and use collaborative technologies to work with others to investigate solutions.

=== Project 13. Implementing Streaming Databases with Spark SQL

Streaming databases (in Spark SQL and other technologies) are now pervasive, in ever-changing scenarios and workflows.  Students will need to consider all aspects of streaming database integration and workflows.  This will include collaborative thinking about databases involving the usage of numerous stakeholders, e.g., the data owners, consumers, applications, workflow managements, etc.

(APA1) Students will engage in purposeful application of their learning through collaborative projects based on real-world contexts.

(GC3) Students will contribute constructively to project teams, assuming various roles and responsibilities to work effectively toward a common goal.

(SASA2) Students will examine their strengths, areas of growth, biases, and positionality and how they impact the group.

=== Project 14. Reflections and Summative Assessment

Students will be asked to reflect on the challenges and benefits from working with others, in collaborative scientific environments with modern digital tools.  They will reflect on the ways that people skills and technology skills are intertwined and mutually dependent.

(CR2) Students will evaluate the outcomes of their decisions and actions and apply these learnings to future endeavors.

(GC2) Students will use collaborative technologies to work with others, including peers, experts, or community members, to examine issues and problems from multiple viewpoints.

(SASA3) Students will practice strategies that promote empathy, respect, empowerment, and relationship-building.

(SASA4) Students will value and engage the variety of opinion and identity within groups.

