= Fall 2026 Office Hours Schedule

[IMPORTANT]
====
Office hours before 5 PM on weekdays (Monday through Friday) will be offered both in-person in the lobby of Hillenbrand Hall, and also virtually.

Office hours on Sundays (all day) and also on weekdays after 5 PM will be held exclusively virtually.

Office Hours Teams Link: will be updated soon!

Checklist for the Teams Link:

* When joining office hours, please include your Data Mine level in front of your name. For example, if you are in TDM 10100, your name should be entered as "TDM 10100 - [Your First Name] [Your Last Name]".

* After joining the Teams call, please unmute your mic to make sure a TA knows you have joined the meeting.

* We will continue to follow the office hours schedule as posted on the Examples Book. Link to the TA Office Hours is coming soon!
====

[NOTE]
====
The below calendars represent regularly occurring office hours. Please check your class' Piazza page to view the latest information about any upcoming changes or cancellations for office hours prior to attending.

Our Piazza links are:
 
TDM 10100: https://piazza.com/purdue/fall2026/tdm10100

====

== TDM 10100 Office Hours:

[cols="1,1,1,1,1,1,1", options="header"]
[.small]
|===
| Time | Sunday | Monday | Tuesday | Wednesday | Thursday | Friday

| 8:30 - 9:00 AM | | Seminar Session 1: Dr. Ward |  | Seminar Session 3: Dr. Ward |  | Seminar Session 5: Dr. Ward
| 9:00 - 9:30 AM | | Seminar Session 1: Dr. Ward |  | Seminar Session 3: Dr. Ward |  | Seminar Session 5: Dr. Ward
| 9:30 - 10:00 AM |  | Seminar Session 2: Dr. Ward |  | Seminar Session 4: Dr. Ward | | Seminar Session 6: Dr. Ward
| 10:00 - 10:30 AM | | Seminar Session 2: Dr. Ward |  | Seminar Session 4: Dr. Ward | | Seminar Session 6: Dr. Ward
| 10:30 - 11:00 AM | | | | | | 
| 11:00 - 11:30 AM | | | | | | 
| 11:30 - 12:00 PM | | | | | | 
| 12:00 - 12:30 PM | | | | | | 
| 12:30 - 1:00 PM | | | | | | 
| 1:00 - 1:30 PM | | | | | | 
| 1:30 - 2:00 PM | | | | | | 
| 2:00 - 2:30 PM | | | | | | 
| 2:30 - 3:00 PM | | | | | | 
| 3:00 - 3:30 PM | | | | | | 
| 3:30 - 4:00 PM | | | | | | 
| 4:00 - 4:30 PM | | | | | | 
| 4:30 - 5:00 PM | Dr. Ward office hours | | | | | 
| 5:00 - 5:30 PM | Dr. Ward office hours | | | | | 
| 5:30 - 6:00 PM | | | | | | 
| 6:00 - 6:30 PM | | | | | | 
| 6:30 - 7:00 PM | | | | | | 
| 7:00 - 7:30 PM | | | | | | 
| 7:30 - 8:00 PM | | | | | | 
| 8:00 - 8:30 PM | | | | | | 
| 8:30 - 9:00 PM | | | | | | 
| 9:00 - 9:30 PM | | | | | | 
| 9:30 - 10:00 PM | | | | | | 
| 10:00 - 10:30 PM | | | | | | 
| 10:30 - 11:00 PM | | | | | | 
|===



