= Seminar TA Training

== Welcome to The Data Mine Seminar Course!

Course content lives within The Projects appendix of The Example Book (the pages you are reading right now). We have migrated away from hosting our content in Brightspace to make our content publicly accessible as we expand. 

Teaching Assistants (TAs) will use Gradescope to submit their training. Students will also continue to use link:https://www.gradescope.com/[Gradescope] as the submission portal for retrospective sprint reports. The method of submission will be specified for each assignment under the corresponding sprint page. 

== TA Responsibility Overview

TAs are a key part of success to The Data Mine. Your constant support in seminars, grading, office hours, and more keep the course running smoothly. 

== Training:

=== Module 1
Navigate to link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module1[Training Module 1], complete the reading and quiz in Gradescope. 

=== Module 2
Navigate to link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module2[Training Module 2], complete the reading and quiz in Gradescope. 
    
COMPLETE your FERPA TRAINING and submit proof in Gradescope. You can not work as a TA without a FERPA certification!

=== Module 3.1
Navigate to link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module3_1_diversity[Training Module 3.1], complete the reading and quiz in Gradescope.


=== Office Hours 
TAs will choose their office hour times and will be expected to hold their scheduled office hours consistently.
Please see the list of required office hours to know how many hours you're required to hold. 

Use link:https://docs.google.com/spreadsheets/d/1tw9qbXD9_2dtOB6AYYUxfHfp-Aow5NB-8tVZk3e4MLI/edit?usp=sharing[this link] to select your office hour time and add your Webex link to the spreadsheet. 
https://docs.google.com/spreadsheets/d/1tw9qbXD9_2dtOB6AYYUxfHfp-Aow5NB-8tVZk3e4MLI/edit?usp=sharing

==== Set up your Office Hours.
Use your personal Webex room to hold your office hours. Go to https://purdue.webex.com/ and log in with your Purdue credentials. You do not need to schedule a meeting for your office hours, just list your personal Webex room. For example, First_name Last_name personal Webex room is: https://purdue.webex.com/join/Last_name/.

For the first 3 weeks of the semester, we need a few T.A.s (at least one for 19000 and one for 29000) in each of the seminar times and in the hour after each seminar. We definitely need lots of help on Thursday and Friday. Evenings are much appreciated because we have students all over the world who will need help. Friday evenings are prime time, and we may permit more than one TA working at a time then.

Please keep track of how many students come to each of your office hours during the first 3 weeks of the semester. We will reshuffle a bit based on popular times after the first 3 weeks.

=== Grading
TAs will be grading student submissions through Gradescope. 
Below are example videos by Gradescope. 

[NOTE]
====
All information in these videos is for example purposes only. They are not Data Mine students or assignments. 
====

Student View: Viewing Feedback and Requesting Regrades
++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/TOHCkI12mh0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

Managing Regrade Requests
++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/jpre3UxF1i0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

Grading a Simple Question
[NOTE]
====
If rubric items are already set in an assignment, please, do NOT change them.
Do NOT delete rubric items as it will alter all other submissions with that item selected.
====
++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/12ySmTBH3pY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

Grading Even Faster with Short Cuts
++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/VMM16gdREfg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

=== Additional Quizzes and Requirements

1. Complete the Syllabus and Academic Integrity Quizzes in Gradescope.  
2. Join Piazza
3. Confirm you're a part of the TA Teams Group Chat. 

Please send any questions to your head TA, Seminar TA group chat, or email datamine-help@purdue.edu. 
We look forward to working with you this semester! 