= Schedule

Note: This schedule is still tentative. 

[%header,format=csv,stripes=even,%autowidth.stretch]
|===      
Assignment,Due date (at 11:59 Eastern Time), Submission Location
Pre Survey, TBD, TBD
Seminar TDM 102 Project 1: https://the-examples-book.com/projects/current-projects/10200-2023-project01[Introduction to Python: part I],February 17,https://www.gradescope.com/[Gradescope] 
Research Check-In Report 1, February 22,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 2: https://the-examples-book.com/projects/current-projects/10200-2023-project02[Introduction to Python: part II],February 24,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 3: https://the-examples-book.com/projects/current-projects/10200-2023-project03[Introduction to Python: part III],March 3,https://www.gradescope.com/[Gradescope] 
Research Check-In Report 2, March 8,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 4: https://the-examples-book.com/projects/current-projects/10200-2023-project04[Scientific computing & pandas: part I],March 10,https://www.gradescope.com/[Gradescope] 
Mid Survey, TBD, TBD
Seminar TDM 102 Project 5: https://the-examples-book.com/projects/current-projects/10200-2023-project05[Functions: part I],March 24,https://www.gradescope.com/[Gradescope] 
Research Check-In Report 3, March 29,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 6: https://the-examples-book.com/projects/current-projects/10200-2023-project06[Functions: part II],March 31,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 7: https://the-examples-book.com/projects/current-projects/10200-2023-project07[Scientific computing & pandas: part II],April 7,https://www.gradescope.com/[Gradescope] 
Research Check-In Report 4, April 12,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 8: https://the-examples-book.com/projects/current-projects/10200-2023-project08[Scientific computing & pandas: part III],April 14,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 9: https://the-examples-book.com/projects/current-projects/10200-2023-project09[Scientific computing & pandas: part IV],April 21,https://www.gradescope.com/[Gradescope] 
Research Check-In Report 5, April 26,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 10: https://the-examples-book.com/projects/current-projects/10200-2023-project10[Importing and using packages],April 28,https://www.gradescope.com/[Gradescope] 
Seminar TDM 102 Project 11: https://the-examples-book.com/projects/current-projects/10200-2023-project11[Classes/dunder & attributes methods/etc: part I],May 5,https://www.gradescope.com/[Gradescope] 
Post Survey, TBD, TBD
|===