= Supplementary Data Science Reading List
Objective:

Data Science has revolutionized industry and has fostered technological advancements that are enabling true "big data" data collection—also enabling analysis techniques like ML that would not have been possible previously. At universities across the world, new research institutes, degree programs, classes, and faculty positions have been created to prepare students for the myriad of Data Science career opportunities in industry. In the real world, we have seen the importance of data and data literacy through the COVID-19 pandemic—with a great emphasis on interpreting metrics, graphs, statistical methods, and more. Companies—both small and large—are investing heavily in data-driven organizations.

However, to be competitive in the field, you need to be more than just technically proficient; understanding real-world applications of Data Science is equally as important. The books listed below were chosen to provide exposure to prudent topics related to Data Science and professionalism: digital ethics, statistical reasoning, time/organizational management, and more.

* Deep Work: Rules for Focused Success in a Distracted World _by Cal Newport_
** Genre: Productivity
** Abridged Content:
*** https://knowledge.wharton.upenn.edu/article/deep-work-the-secret-to-achieving-peak-productivity
*** https://www.youtube.com/watch?v=y3Umo_jd5AA

* Weapons of Math Destruction: How Big Data Increases Inequality and Threatens Democracy  _by Cathy O’Neil_
** Genre: Digital Ethics
** Abridged Content:
*** https://www.npr.org/2016/09/12/493654950/weapons-of-math-destruction-outlines-dangers-of-relying-on-data-analytics
*** https://youtu.be/TQHs8SA1qpk

* The Signal And The Noise: Why So Many Predictions Fail – But Some Don’t _by Nate Silver_
** Genre: Statistics
** Abridged Content:
*** https://www.npr.org/2012/10/10/162594751/signal-and-noise-prediction-as-art-and-science

* Quiet: The Power of Introverts in a World That Can't Stop Talking _by Susan Cain_
** Genre: Psychology
** Abridged Content:
*** https://medium.com/12minapp/quiet-the-power-of-introverts-book-summary-bb213ddd9b6d
*** https://youtu.be/AzlCIS072_Y

* The Black Box Society _by Frank Pasquale_
** Genre: Digital Ethics
** Abridged Content:
*** https://blogs.lse.ac.uk/medialse/2016/02/05/bittersweet-mysteries-of-machine-learning-a-provocation/
*** https://www.youtube.com/watch?v=7_7ffmjOQfo

* How Not to be Wrong: The Power of Mathematical Thinking _by Jordan Ellenberg_
** Genre: Math and Statistics
** Abridged Content:
*** https://www.youtube.com/watch?v=isTNnwk5SqE
*** https://cs.nyu.edu/~davise/papers/Ellenberg.pdf


