= Sprint #3


[IMPORTANT]
====
 *CONTENT STILL UNDER CONSTRUCTION FOR SPRING 2025!!!!*
====

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 2/8
|Mon 2/5

|*Sprint End Date*
|Wed 2/21
|Sun 2/18

|*Due Date*
2+| Wed 2/21 by 11:59 PM ET

|===

== Sprint Tasks

=== &#10003; Professional Development 

The Data Mine Corporate Partners program is a professional development program. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

In each sprint, you will complete one https://www.gradescope.com/[Gradescope Quiz] on this sprint's professional development topics.

++++
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}

.accordion:after {
  content: '\002B';
  color: #777;
  font-weight: bold;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2212";
}

.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>
<button class="accordion">Data Security</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, February 21, 2024 at 11:59 PM ET. Late work will not be accepted.	</p>
<br>
	</div>
	<div>
		<p><b>What: </b><a href="https://the-examples-book.com/crp/students/datasecurity">Read about data security in The Data Mine</a> and take the quiz in Gradescope.</b></p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 3: Professional Development".</p>
<br>
  	</div>
	<div>
<p><b>Why: </b> The Data Mine Corporate Partners students work with proprietary data from many companies. Students need to learn how to securely work with data. </p>
<br>
  </div>
</div>
<button class="accordion">3-Minute Thesis</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, February 21, 2024 at 11:59 PM ET. Late work will not be accepted.
		</p>
<br>
	</div>
	<div>
		<p><b>What: </b><a href="https://the-examples-book.com/crp/students/three_minute_thesis">Learn about the 3 minute thesis </a> and submit a practice 3 minute thesis on Gradescope.</b></p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 4: Professional Development".</p>
<br>
  	</div>
	<div>
		<p><b>Why: </b>In preparation for The Data Mine Symposium, we are having students practice giving a 3-minute thesis. There will be many attendees from different companies and backgrounds during the symposium. Being able to give a 3-minute thesis about your Data Mine project to a non-technical audience is an important skill to learn for The Data Mine Symposium.  </p>
<br>
  </div>
</div>

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

</body>
</html>
++++

=== &#10003; Sprint #3 Report 

*When:* Due Wednesday, Febuary 21, 2024 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in the Sprint #3 Report accessed on Gradescope. You can draft your answers in a separate document then you will write your answers directly in the Gradescope assignment. 

*Where:* link:https://www.gradescope.com/[Gradescope] 
