= Spring 2025 Syllabus - The Data Mine Corporate Partners



== Course Information   
 
[%header,format=csv]
|===
Course Number and Title, CRN
TDM 11200 – Corporate Partners II, link:https://selfservice.mypurdue.purdue.edu/prod/BZWSLCSR.P_Prep_Search?term_in=202520&crn_in=11039[CRNs vary]
TDM 21200 – Corporate Partners IV, link:https://selfservice.mypurdue.purdue.edu/prod/BZWSLCSR.P_Prep_Search?term_in=202520&crn_in=11031[CRNs vary]
TDM 31200 – Corporate Partners VI, link:https://selfservice.mypurdue.purdue.edu/prod/BZWSLCSR.P_Prep_Search?term_in=202520&crn_in=11032[CRNs vary] 
TDM 41200 – Corporate Partners VIII, link:https://selfservice.mypurdue.purdue.edu/prod/BZWSLCSR.P_Prep_Search?term_in=202520&crn_in=11037[CRNs vary]
TDM 51200 – Corporate Partners, link:https://selfservice.mypurdue.purdue.edu/prod/BZWSLCSR.P_Prep_Search?term_in=202520&crn_in=18594[CRNs vary] 

|===

*Meeting times:* Two times per week (50 minutes LEC + 1 hour 50 minutes LAB), dependent on your assigned Corporate Partner Team. The team meeting times are listed on your registered course schedule. 

*Course credit hours:* 3 credits

*Prerequisites:*

* *Undergraduate students:* To be enrolled concurrently in TDM 10200, 20200, 30200, or 40200 The Data Mine II or IV or VI or VIII (1 credit seminar).

* *Graduate students:* Application required. No other prerequisites.

== Course Site
All course material will be posted here in the xref:spring2025/index.adoc[Corporate Partners section of The Examples Book]. 

Grades can be viewed in link:https://purdue.brightspace.com/[Brightspace] and assignments will be submitted through link:https://www.gradescope.com/[Gradescope]. 

== Course Schedule & Due Dates

Due dates are listed in the xref:spring2025/schedule.adoc[Spring 2025 Student Course Schedule]

== Information about the Instructors 

=== The Data Mine Staff

Check out our link:https://datamine.purdue.edu/about/welcome.html[staff welcome page] to see the team that supports The Data Mine


=== Email Policy

The Data Mine Team uses a shared email which functions as a ticketing system. Using a shared email helps the team manage the influx of questions, better distribute questions across the team, and send out faster responses. 

*Send your questions to datamine-help@purdue.edu* 

* Please use your official @purdue.edu email address to communicate with us. 
* If you have not received a response within 1 business day (Mon-Fri), please resend the email. 
* When emailing us, *please place your Corporate Partner team in the subject line of the email* (e.g., Merck Biometrics Team – Symposium Poster Question). This will help us respond to your emails quickly.

Use this table to send your questions to the most appropriate email. If you're not sure who to ask, navigate to the link:https://the-examples-book.com/crp/students/spring2025/questions[Questions] page for more details. 

[%header,format=csv]
|===
Who should you email?, Types of Questions/Topics
"<<Corporate Partner TAs, Your CRP TA>>", "Weekly tasks, catching up on a missed meeting, general team questions"
datamine-help@purdue.edu, "General Data Mine/Corporate Partners, grades, technical project or topic questions"
Your CRP Mentor, (Check with your TA first) Project specific questions

|===



=== Corporate Partner Mentors
Your Corporate Partner Mentor(s) are employees of the company you are working with. You will meet once a week with them online (unless the company is in West Lafayette, IN or visiting Purdue for a meeting). Please treat all communication with them in a *professional* manner – they are like your supervisor during an internship. They also act as a product owner and can help to answer questions or find resources for any product specific questions that you have during the project.

=== Corporate Partner TAs
Our Corporate Partner TAs will serve as peer mentors and team leaders for each of our projects. Nearly all of our CRP TAs have been in The Data Mine Corporate Partners program in past years and many are returning to the same project. The CRP TAs will lead the weekly student meeting (lab – 2 hours) when you are not meeting with the Corporate Partner Mentor(s). _Your CRP TA should also be the first person to go to when you have a technical question or questions about your project._

//link here to google sheet with tas
//team, ta name, ta email

++++
<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vRFXsEtFhiYRFLutMLzaf1Zx6rrvP26nAwrUk6HFtBS0XrV2xcN1W4lXjQAKoEa_XB7w3ESdhROcAr0/pubhtml?widget=true&amp;headers=false"></iframe>
++++


=== Data Scientists 

The data scientists employed by The Data Mine are here to help students with the technical topics and concepts that they will encounter during their projects. The data scientist team has a varied background in topics such as natural language processing (NLP), geospatial information systems (GIS), high performance computing, and machine learning.

If you have a question for a member of the Data Science team, please email datamine-help@purdue.edu and your question will be answered by a member of the Data Science Team. If our doors are open, you can drop by and ask for help. They will bring in other members of the team as needed. They are here to help so don’t be worried when asking questions!

When scheduling a meeting with a data scientist keep in mind that they are designed to be collaborative. The team wants to see any solutions that you’ve attempted and where you may be getting stuck. Also, for more complicated questions it helps to give some advance notice of the topics over email. We aren’t experts in all of data science and some research may be required. 

== Course Description
Students in The Data Mine Corporate Partners Learning Community will work in interdisciplinary teams with Corporate Partner Mentors on a variety of data-driven projects.  They will analyze real data related to questions that the Corporate Partner proposes.  Most projects will last for a full academic year (late August through late April), with multiple reports and presentations given more frequently.  The mentor is expected to meet with the students weekly by Microsoft Teams, or (more rarely) in person. Students are expected to actively participate in these meetings and in all individual and group work.  The goal of the course is to help students build impactful industry related skills in data science, visualization, and data engineering. The Data Mine staff also has data scientists who can assist students with technical questions focused on the skills being built and the research conducted. Students can work on real-world industry facing issues that have a high value add for the corporate partner. 

== Learning Outcomes
By the end of this course, you will be able to:

1. Discover and apply data science tools to manage data sets from Corporate Partners through researching, cleaning, processing, analyzing, and visualizing data. 
2. Apply Agile project management methodology to plan task ownership and decision making, collaborate with scrum teams to accomplish the increment during 2-week sprints, review the product backlog, and reflect on areas of success and improvement.  
3. Engage with peers to identify and overcome complex challenges in the data sciences. 
4. Effectively communicate findings of technical research through detailed documentation and team presentations. 
5. Discover professional development opportunities in order to prepare for your career.

== Logistics 

=== Office Hours

The Data Mine staff offer office hours by request. Please email datamine-help@purdue.edu if you need to request a meeting. Students are always welcome to stop by staff offices Monday - Friday. West Lafayette staff are located in link:https://convergence.discoveryparkdistrict.com/[Convergence] at 101 Foundry Dr., West Lafayette, IN 47906.  Indianapolis students can find The Data Mine suite located in ET219 at 799 W. Michigan St., Indianapolis, IN 46202.

=== Weekly Class/Team Meeting Times

TDM 111/211/311/411/511 The Data Mine Corporate Partners is a 3 credit hour class. You will meet for about 3 hours per week as your class time. It is also expected that you spend 5-7 hours per week on this course outside of your class time. Total hours on this course are approximately 8-10 hours per week.

*Team Meeting - 50 minutes*

The weekly 50-minute Team Meeting is listed on your academic schedule as "LEC", however, there will be no "lecturing" during this meeting. All students, the team TA, and the industry mentor(s) attend this meeting to share updates and discuss next steps. Check out the xref:spring2025/locations.adoc[Locations] page to learn *when* and *where* this meeting is held for your team. 


*Student Lab - 1 hour 50 minutes* 

The weekly 1 hour 50 minute Student Lab is listed on your academic schedule as "LAB". This dedicated work time, led by your team TA, enables you to collaborate with your peers and work in sub-teams. The industry mentor(s) generally do not attend this meeting each week. Sometimes this time block is used for offsite visits to the company. Check out the xref:spring2025/locations.adoc[Locations] page to learn *when* and *where* this lab is held for your team. 

=== Required Materials

*	A laptop that can be used for working on the project, group meetings, and presentations
*	Microsoft Suite Products (remember that link:https://it.purdue.edu/services/microsoft-office-365.php[Microsoft Office is free for all students])
    ** MS Teams installed and logged into your Purdue account (You will be invited to join your Corporate Partner MS Team)
*	link:https://purdue.brightspace.com/d2l/login[Brightspace] and link:https://www.gradescope.com/[Gradescope] course pages
*	Access to link:https://the-examples-book.com/starter-guides/anvil/access-setup[User Account (ACCESS) Setup]


== Assignments and Grades

=== Late Policy 
We do NOT accept late work, unless there are extenuating circumstances.  

Extenuating circumstances do NOT include:

- Having exams near or on the due date 
- Working on other course projects on or near the due date
- Being sick for a few days on or near the due date
- Traveling for any reason
- Forgetting the due date
- Having technical difficulties (wifi, computer, etc)

It is better to submit a partially done report than nothing at all. Partial credit can be earned for work turned in on time. The electronic submission systems also do not allow for late work. 

=== Grade Expectations 
This is a research-type, project-based course, so the majority of your grade for the semester will be determined holistically based on work with Corporate Partners in addition to reports and other assignments per the schedule.  Students will receive their own individual grade, but the success of the group will be a component of that individual grade. 

It is very important to check your @purdue.edu email, Brightspace, Gradescope, and The Examples Book pages frequently! Please review the schedule. More details for each assignment will be available in The Examples Book. 

*Due dates are listed in the xref:spring2025/schedule.adoc[semester schedule] with assignments to be completed on link:https://www.gradescope.com/[Gradescope].*

You will need to complete the tasks detailed on each sprint page. The first sprint is covered here:  xref:spring2025/sprint1.adoc[Sprint 1]. Additional tasks specific to your project will be discussed with your CRP Mentor, TA, and team. 

Near the end of the semester, we will host the Corporate Partners Symposium to showcase the work you have done throughout the year to corporate partner mentors and guests. All Corporate Partner students will be required to attend the symposium presentation to present their work. More details will be forthcoming and posted in The Examples Book.  

The Data Mine does not conduct an exam during the final exam period. Therefore, Corporate Partner Courses are not required to follow the Quiet Period in the link:https://catalog.purdue.edu/content.php?catoid=15&navoid=18634#academic-calendar[Academic Calendar].


=== Grade Breakdown

[cols="4,2,1"]
|===

2+|*Agile 2-week Sprints*
>|70%
3+|_Seven 2-week sprints. Click on the pages for each sprint for specific assignments._

|xref:../spring2025/sprint1.adoc[Sprint 1]
^| 10%
|

|xref:../spring2025/sprint2.adoc[Sprint 2]
^| 10%
|

|xref:../spring2025/sprint3.adoc[Sprint 3]
^| 10%
|

|xref:../spring2025/sprint4.adoc[Sprint 4]
^| 10%
|

|xref:../spring2025/sprint5.adoc[Sprint 5]
^| 10%
|

|xref:../spring2025/sprint6.adoc[Sprint 6]
^| 10%
|

|xref:../spring2025/sprint7.adoc[Sprint 7]
^| 10%
|


2+|*Corporate Partners Mentor and TA Evaluation*
>|15%

|Mid-Semester Evaluation 
^| 5%
|

|Final Evaluation (cumulative of entire spring 2025 semester)
^| 10%
|

2+|*Symposium*
>|15%

|Drafts (poster, video script)
^| 3%
|

|Final Poster, Final Video & Presentation at Symposium on April 30, 2025
^| 12%
|


2+|*TOTAL*
>|*100%*


|===

This course will follow the 90-80-70-60 grading scale for A, B, C, D cut-offs.  If you earn a 90.000 in the class, for example, that is a solid A.  +/- grades will be given at the instructor’s discretion below these cut-offs.  If you earn an 89.11 in the class, for example, this may be an A- or a B depending on the course grade distribution at the end of the semester. 

* A: 100.000% – 90.000%
* B: 89.999% – 80.000%
* C: 79.999% – 70.000%
* D: 69.999% – 60.000%
* F: 59.999% – 0.000%

== Project Management and Agile
xref:projectmanagement:intro.adoc[Click here to view the Project Management Training and Resources]


The Data Mine will be applying Agile project management to all of our Corporate Partner projects. Most of our Corporate Partners use Agile methods at their workplace. Agile allows complex projects to be broken down into small manageable tasks that can be assigned to individuals or teams. Agile also has built-in processes that help to enable team communication and collaboration. 

Many corporations utilize Agile in environments from software development to data science. While the specifics of each Agile practice may vary by corporation it is beneficial to understand the high-level architecture of the Agile practices and how they can be beneficial in a team development environment. Agile implementation specifics may differ by team. However, each team will be working toward the same goals focused on the breakdown and accomplishment of work tasks and the constant open collaboration between team members. 

To become more familiar with Agile methodologies you will complete online training and interactive team training focused on Agile. You will also take a quiz on applying Agile to The Data Mine. Since The Data Mine Corporate Partners is a learning environment (and not your typical 8 AM - 5 PM workplace), we have modified some of the practice to best suit the student schedule. 

The MS Teams Planner (or other Agile software) application will also be available to teams for task tracking. The Data Mine staff will provide resources on the use of MS Teams Planner and how it related to the Agile concepts in the materials above. The tool that the team utilizes for Agile task tracking can be determined on a project-by-project basis between the students and the Corporate Partner Mentor or TA. 


== Course Policies

=== Sponsored Student Class Project Notice 

This course permits you, the student to participate in a class project that has been sponsored by a third party other than the University. The University encourages and supports your participation in this practical learning experience. Although your course requirements may include a practical learning project, you are not required to participate in a project that is sponsored by an outside third party. Prior to your participation in a project sponsored by an outside third party, we would like you to carefully consider that your participation (i) may require you to assign your intellectual property (IP) rights to any intellectual property for which a student would retain ownership under the University’s Policy I.A.1 on Intellectual Property and/or (ii) may require you sign a non-disclosure (confidentiality) agreement with the sponsor. If you sign an agreement regarding intellectual property rights or a non-disclosure agreement, you may incur personal liability (with respect to a breach of a non- disclosure agreement) or you may lose economic benefits associated with your ownership of intellectual property (with respect to a license or assignment of intellectual property). You are encouraged to retain independent legal counsel for advice on these types of agreements. In addition, if you choose not to sign a non-disclosure or intellectual property rights agreement, you may be reassigned to a different project or you may not be able to participate in The Data Mine Corporate Partners. 

=== Confidentiality of The Data Mine Corporate Partner Projects 

It is important to note that you are working on real-world problems that your Corporate Partner is trying to solve. These projects weren't created as busywork to keep you occupied for 9 months; you have the opportunity to make a real impact with your Corporate Partner. Past work from Data Mine students has been put into production code! 

With that being said, *the work you do and the data you have access to must be kept fully confidential!* Nearly all Corporate Partner students will be required to sign an NDA and/or IP agreement with the company. Even if you do not have to sign an NDA for your project, please keep the project details private. While each NDA will have unique terms, some basics include:

*	Do not move or copy the data from the original storage. Never email data, text it to your teammates, copy it to MS Teams, or put it in Google drive (or any other cloud storage system). For example, if the data lives on Anvil, do not move it off Anvil and _do not move it to a different folder._ including your home directory. 
*	Do not share any screenshots of the data or any findings (graphs, pictures, etc.) from the project with those who are not on your team. 
*	You cannot share things you learn from the data with anyone who is not working on the project. This includes your roommate, your parents, and your best friend. 
*	Do not disclose project specifics to anyone, including:
    **	In an interview for an internship or job
    **	On your LinkedIn profile
    **	Your family/friends/roommate/boyfriend/girlfriend/professor 
*	Do not discuss the details of projects when you are in a public space. You should find a private place to join the weekly online team meetings. Also, be careful working on the project in a public space when others could walk by and see your screen. 
*	If you ever have questions about what you *can* talk about, always ask your Corporate Partner Mentor first. 
If you’re ever in doubt about what to share it’s often best to not share initially and check with your corporate partner. They can help clarify any confusion.



=== Guidance on Generative AI

[IMPORTANT]
====
Use of generative AI tools needs to be approved by your company mentor *prior* to being used in the project. 

Work with your TA to check for approval and document it with The Data Mine. 
====

As the world of machine learning, deep learning, and AI continues to evolve we wanted to offer some guidance on The Data Mine’s perspective for generative AI tools, such as ChatGPT.

New emergent technologies can be incredibly valuable tools. However, at the same time it’s
important to keep perspective on how and when we utilize these new systems.

When using ChatGPT (or other generative AI) on a Data Mine project:

* Never share a company’s code, data, information, or any other proprietary property
with the tool.
** While not all tools incorporate user input into their training, it’s a very common
practice and can lead to breaches in the NDA agreements.
* Always question the response that the tool provides.
** It’s OK to ask different apps for suggestions on things like common algorithms or
good starting points for problem solutions. However, it’s VITAL to understand
factors like where the solutions fit, how they perform, and how to measure their
performance.
** It’s OK for a tool to recommend an algorithm for research. It’s unacceptable to
assume that the algorithm is the only correct answer and to not be able to
explain why it was chosen. (ChatGPT told me won’t be accepted.)
** It’s also occasionally possible that the tool will make up an answer, and you don’t
want to get stuck presenting false information.
* If you’re ever unsure about if a tool can be used, ask your mentor and The Data Mine
BEFORE you use it.
** We want to use new tools and adapt to the new environments, but our number
1 priority is to provide a safe and secure data environment. We can’t do anything
that puts that at risk.
* When using generative AI for code it’s very important to understand the fundamental
code’s functionality.
** While generative AI can easily write if/else functions or for loops, if you don’t
understand how they work you will have a much harder time when it comes to
writing a novel or highly specific code function.
** Generative AI is great to help with ideas, but shouldn’t be used with no thought.

As with any new technologies, the world of generative AI is changing quickly. We encourage open discussion and welcome any feedback to The Data Mine concerning these technologies.

==== Data Mine Approval Process

. The TA should reach out to the company project mentor and get written approval for the use of generative AI tools in the project. 
. The approval email should then be forwarded to datamine@purdue.edu for documentation.
** The email subject line should read `Generative AI Approval - <team name>`. With the "team name" replace with your group's name. 

=== Attendance Policy 

This course follows link:https://catalog.purdue.edu/content.php?catoid=16&navoid=19719#a-attendance[Purdue University Academic Regulations regarding class attendance], *which states that students are expected to be present for every meeting of the classes in which they are enrolled.* For the purposes of this course, being “present” means attending all face-to-face meetings and all online meetings, unless you are ill or need to be absent for reasons excused by University regulations: grief/bereavement, military service, jury duty, parenting leave or emergent medical care. Attendance will be taken at the beginning of each class and lateness will be noted. 

*Regardless if your absence is planned or unplanned, excused or unexcused, please notify your TA as soon as possible and work with them to catch up on missed information and work.*

==== Dropped Absences 

All students will get to drop one missed LAB (1 hr 50 min) and one missed LEC (50 min) per semester. The missed class will still show up on your sprint report when graded by your TA, but The Data Mine staff will add in the drops at the end of the semester.

==== Excused Absences

The link:https://www.purdue.edu/advocacy/students/absences.html[Office of the Dean of Students] is able to verify and provide notifications for absences that meet the criteria of the excused absence policies established by University Senate.

The University Senate recognizes the following as types of absences that must be excused:

• Grief Absence Policy for Students
• Jury Duty Policy for Students
• Medical Excused Absence Policy for Students
• Military Absence Policy for Students
• Parenting Leave Policy for Students- Facilitated by the Office of Institutional Equity

Students needing an absence notification sent for one of the above-listed excused absence policies should link:https://www.purdue.edu/advocacy/students/absences.html[complete the corresponding request form]. 

==== Unexcused Absences

*What if the absence does not meet the criteria of one of the excused absence policies? (link:https://www.purdue.edu/advocacy/faculty/fs_class_absences.html[link])*

_Absences outside of those covered by the University's excused class absence policies are at the discretion of the individual course instructors. Students should work with their instructors directly to discuss their absence and the opportunity to complete missed coursework. The Office of the Dean of Students cannot verify or provide notification for an absence outside of the excused class absence policies._

*What should you do if it does not meet the criteria for an excused absence?* 

1.	Do not come to class if you are feeling ill, but DO email/message your TA immediately. They do not need details about your symptoms; simply let them know you are feeling ill and cannot come to class. If it is an emergency situation, please follow the University regulations on emergent medical care (see above).
2.	Unless it falls under the University excused absence regulations (see above), *any work due should be submitted on time*.

Most absences not excused by ODOS will not be excused by The Data Mine. However, if you believe you have an extenuating circumstance, please notify us at datamine-help@purdue.edu. 

//When conflicts or absences can be anticipated, such as for many University-sponsored activities and religious observations, the student should inform the instructor of the situation as far in advance as possible. 

//For unanticipated or emergency absences when advance notification to the instructor is not possible, the student should contact the instructor or TA as soon as possible by email or phone. When the student is unable to make direct contact with the instructor and is unable to leave word with the instructor’s department because of circumstances beyond the student’s control, and in cases falling under excused absence regulations, the student or the student’s representative should contact or go to the Office of the Dean of Students website to complete appropriate forms for instructor notification. Under academic regulations, excused absences may be granted for cases of grief/bereavement, military service, jury duty, parenting leave, and medical excuse. For details, see the link:https://catalog.purdue.edu/content.php?catoid=13&navoid=15965#a-attendance[Academic Regulations & Student Conduct section] of the University Catalog website. 



=== Class Behavior

You are expected to behave in a way that promotes a welcoming, inclusive, productive learning environment.  You need to be prepared for your individual and group work each week, and you need to include everybody in your group in any discussions.  Respond promptly to all communications and show up for any appointments that are scheduled.  If your group is having trouble working well together, try hard to talk through the difficulties—this is an important skill to have for future professional experiences.  If you are still having difficulties, ask The Data Mine staff to meet with your group. Visit the xref:student_code_of_conduct.adoc[Student Code of Conduct] page to understand expectations on “Net-etiquette,” dress-code, in-person meetings, meal etiquette, work expectations, networking expectations, written communication, and time management.

== Adding The Data Mine to your Resume
Please see the xref:datamine_resume_LinkedIn.adoc[Professional Development] section to learn how to add The Data Mine to your resume.
 
== Disclaimer 
This syllabus is subject to change. Changes will be made by an announcement via email and the corresponding course content will be updated. 



== xref:spring2025/syllabus_purdue_policies.adoc[Purdue Policies & Resources]

* xref:spring2025/syllabus_purdue_policies.adoc#Academic-Integrity[Academic Integrity]
* xref:spring2025/syllabus_purdue_policies.adoc#Nondiscrimination-Statement[Nondiscrimination Statement]
* xref:spring2025/syllabus_purdue_policies.adoc#Students-with-Disabilities[Students with Disabilities]
* xref:spring2025/syllabus_purdue_policies.adoc#Mental-Health-Resources[Mental Health Resources]
* xref:spring2025/syllabus_purdue_policies.adoc#Violent-Behavior-Policy[Violent Behavior Policy] 
* xref:spring2025/syllabus_purdue_policies.adoc#Inclusion-Statement[Inclusion Statement]
* xref:spring2025/syllabus_purdue_policies.adoc#Basic-Needs-Security-Resources[Basic Needs Security Resources] 
* xref:spring2025/syllabus_purdue_policies.adoc#Course-Evaluation[Course Evaluation]
* xref:spring2025/syllabus_purdue_policies.adoc#Campus-Emergencies[Campus Emergencies]
* xref:spring2025/syllabus_purdue_policies.adoc#Illness-and-other-student-emergencies[Absences, Illness, and other student emergencies]
