= TDM 20100: Project 6 -- Awk Everything! 1

**Motivation:** As you've seen so far, `bash` has a wide variety of commands that enable us to do different things, and we can use pipes to connect those commands and perform whole loads of data processing in one big step. However, conciseness _is_ a virtue. In this project we'll start learning about `awk`, the bash multi-tool capable of performing the work of tons of commands all by itself. By the end of the next few weeks, you'll be able to do entire pipelines worth of work in just one `awk`!

**Context:** This project will relate `awk` concepts back to previously learned commands, and at the very least a basic knowledge of filesystem navigation and regex will be needed.

**Scope:** `awk`, data processing, Bash, GNU, CLI

.Learning Objectives:
****
- Learn the general structure of a call to `awk`
- Construct your first basic `awk`
- Use `awk` to print common file information
- Use `awk` to print specific parts of files and accomplish multiple commands worth of work at once
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about project submissions xref:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset(s):

- `/anvil/projects/tdm/data/iowa_liquor_sales/iowa_liquor_sales_cleaner.txt`

== Questions

=== Question 1 (2 pts)

To begin learning about `awk`, its important to conceptualize the two fundamental units that `awk` operates on: _records_ and _fields_. 

In the context of 101-102 concepts, you can think of a _record_ as one row of data in a file that is "tidy". Alternatively, a record can be thought of as one instance of the things we are tracking in our data. For example, in the YouTube data we've previously used a record corresponds to a single video.

A _field_ can be thought of as a singular aspect or detail corresponding to a single record. For example, in the YouTube data there are fields like `comment_count`, `publish_time`, `title`, and `channel_name`.

Use `head` to print the first 3 lines of the `/anvil/projects/tdm/data/iowa_liquor_sales/iowa_liquor_sales_cleaner.txt` file. What are the names of the different _fields_ for this data?

Using `wc`, figure out how many records exist in this data. You can consider that data 'tidy' (meaning each line is a complete record). Remember that the first line is column headers and thus doesn't count as its own record.

.Deliverables
====
- The names of the fields for the Iowa liquor sales data
- The number of records in the Iowa liquor sales data
====

=== Question 2 (2 pts)

As a multi-purpose tool for pattern-matching and processing, `awk` needs to have the ability to structure complex processing and pattern-matching logic in a readable, concise way.

The general structure of a call to `awk` is as follows:

[source, bash]
----
# general structure of a call to awk
awk [FLAGS] '(pattern) {action}' INPUTFILE
----

We'll continue to elaborate on this throughout the rest of the project, but for now you can think of `[FLAGS]` as the typical command line flags you've been using with different functions already so far. `(pattern)` is the pattern that must be matched in order to perform `{action}`. Multiple patterns and actions can be included in each call to `awk`, as long as they reside between the two single-quotes in the call. Finally, a path to the desired input file must be provided at the end of the statement.

In addition to basic structure, `awk` has a lot of special syntax to make things easier/shorter to write. https://man7.org/linux/man-pages/man1/awk.1p.html[The manpages] are always a good place to start, but we'll also walk you through the basics in the following few questions.

First, try running the below code and observing its output:

[source, bash]
----
cd /anvil/projects/tdm/data/iowa_liquor_sales
awk -F ';' '{print $1"   |   "$5"   |   "$6} NR==5{exit}' iowa_liquor_sales_cleaner.txt
----

There's a lot here, so let's break it down more simply (Remember: https://explainshell.com/[explainshell.com] is a great resource for understanding terminal commands!). 

First, we call `awk` and then use `-F ";"` to specify that the separator for different fields is a semicolon and not whitespace (the default field delimiter for `awk`). 

For our first _action_ block, we don't provide any condition, meaning that `awk` will perform the stuff in the first braces on every record/line of our file. In this case, we tell it `'{print $1"   |   "$5"   |   "$6}'`, which as you likely could tell prints the first, fifth, and sixth field for each record. It also adds "   |   " between each record for readability. 

We then add another condition-command pair, this time with the condition `NR==5` where NR stand for _number of records_. When the number of records we have processed reaches 5 (the fifth line of the file in this case), we perform the action `{exit}`, which ends our `awk` program.

Using the above code as a guide, write a similar `awk` statement that prints the 2nd, 4th, and 21st fields for the first 10 records of our file. If done correctly, your output should resemble the below text.

[source, txt]
----
Date, Store Name, Bottles Sold
08/16/2012, CVS PHARMACY #8443 / CEDAR RAPIDS, 3
09/10/2014, SMOKIN' JOE'S #6 TOBACCO AND LIQUOR, 12
04/10/2013, HY-VEE FOOD STORE / MOUNT PLEASANT, 2
08/30/2012, AFAL FOOD & LIQUOR / DES MOINES, 3
01/26/2015, HY-VEE FOOD STORE #5 / CEDAR RAPIDS, 4
07/19/2012, SAM'S MAINSTREET MARKET / SOLON, 12
11/20/2013, BIG G FOOD STORE, 6
10/23/2013, DECORAH MART, 12
05/02/2012, ECON-O-MART / COLUMBUS JUNCTION, 3
----

.Deliverables
====
- The first, second, and twenty-first fields for the first 10 records in our data
====

=== Question 3 (2 pts)

Show BEGIN and END usage, have them do an example of each

.Deliverables
====
- Ipsum lorem
====

=== Question 4 (2 pts)

Show compound usage of BEGIN, END, and potentially also during to put together a full command, then have students slightly modify

.Deliverables
====
- Ipsum lorem
====

=== Question 5 (2 pts)

Demonstrate basic conditionals in awk, then apply

.Deliverables
====
- Ipsum lorem
====

== Submitting your Work

This is where we're going to say how to submit your work. Probably a bit of copypasta.

.Items to submit
====
- firstname-lastname-project6.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====