= NDMN Attendance Policy

NDMN students are expected to be present for every Corporate Partner Meeting as they are receiving a monthly stipend from the NSF to participate.  Attendance is reported to the NSF to ensure students are meeting the requirements outlined in the program.  Multiple absences (excused or unexcused) will be reported to and reviewed by The Data Mine team to determine if the student can remain in the program. 


For the purposes of this course, being “present” means attending all online meetings with camera on and actively participating. 


The following are types of absences that will be considered excused:

• Grief/Bereavement 
• Jury Duty
• Medical Excused Absence or Emergent Medical Care 
• Military Absence 
• Parenting Leave 

NOTE:  If you are feeling ill, please email/message your TA immediately. They do not need details about your symptoms; simply let them know you are feeling ill and cannot come to your meeting. 

*Regardless if your absence is planned or unplanned, excused or unexcused, please notify your TA as soon as possible and work with them to catch up on missed information and work.*

==== Dropped Absences 

NEW: Students will get to drop one missed LAB (1 hr 50 min) and one missed LEC (50 min) per semester. The missed class will still show up on your sprint report when graded by your TA, but The Data Mine staff will add in the drops at the end of the semester.

==== Unexcused Absences
What if the absence does not meet the criteria of one of the excused absence types above?

Absences outside of those excused class absences  are at the discretion of the TA and Mentor. Students should work with their TA directly to discuss their absence and the opportunity to complete missed coursework. Should there be any concerns, please email: datamine@purdue.edu
