= Apply Functions

== Abstract

In R, we might encounter situations where we need to iterate over several (or all) of the elements in a data frame. With languages like Python or Java, for-loops and while-loops are indispensable when dealing with iteration, but in R, we have the *apply functions*, which offer a faster, more concise way of _applying_ a function to a data set.

[NOTE]
====
There's a great https://ademos.people.uic.edu/Chapter4.html[online encyclopedia on R] that inspired and informed many examples for this page. Check them out!
====

{sp}+

=== `apply`

The basic apply function takes an array/matrix, a `MARGIN` parameter for the desired dimension, and the function you want to apply.

Our test matrix will be 5x5, where the numbers 1-25 will populate each column sequentially:

[source,R]
----
cubed5 <- matrix(c(1:5, 6:10, 11:15, 16:20, 21:25), nrow = 5, ncol = 5)
cubed5
----

----
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    6   11   16   21
[2,]    2    7   12   17   22
[3,]    3    8   13   18   23
[4,]    4    9   14   19   24
[5,]    5   10   15   20   25
----

Ultimately, that's all there is to `apply`. One important note is that `apply` will *not* work for vectors -- we discuss vector

[source,R]
----

----

----

----