= Apply Functions

== Abstract

In R, we might encounter situations where we need to iterate over several (or all) of the elements in a data frame. With languages like Python or Java, for-loops and while-loops are indispensable when dealing with iteration, but in R, we have the *apply functions*, which offer a faster, more concise way of _applying_ a function to a data set.

[NOTE]
====
There's a great https://ademos.people.uic.edu/Chapter4.html[online encyclopedia on R] that inspired and informed many examples for this page. Check them out!
====

{sp}+

=== `apply`

The basic apply function takes an array/matrix, a `MARGIN` parameter for the desired dimension, and the function you want to apply.

Our test matrix will be 5x5, where the numbers 1-25 will populate each column sequentially:

[source,R]
----
cubed5 <- matrix(c(1:5, 6:10, 11:15, 16:20, 21:25), nrow = 5, ncol = 5)
cubed5
----

----
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    6   11   16   21
[2,]    2    7   12   17   22
[3,]    3    8   13   18   23
[4,]    4    9   14   19   24
[5,]    5   10   15   20   25
----

* insert examples for `apply` here

Ultimately, that's all there is to `apply`. One important note is that `apply` will *not* work for vectors -- we discuss vector `apply` functions in a moment.

[source,R]
----
squares <- c(1, 4, 9, 16, 25)
apply(squares, 1, function(x) x ^ 0.5)
----

----
`Error in apply(squares, 1, function(x) x^0.5) :
  dim(X) must have a positive length`
----

{sp}+

=== `lapply & sapply`

`lapply` applies a function to each element of a list, then returns a list that's been altered by the function. Since there is only one dimension in a list, the `MARGIN` parameter does not apply. Let's use `sum` on the `squares` vector from before:

[source,R]
----
lapply(squares, sum)
----

----
[[1]]
[1] 1

[[2]]
[1] 4

[[3]]
[1] 9

[[4]]
[1] 16

[[5]]
[1] 25
----

This is obviously not what we wanted -- the problem here is that vectors and lists are not the same thing and `lapply` treats every element in the vector like its own list. Casting `squares` to a list will fix the issue:

[source,R]
----
lapply(list(squares), sum)
----

----
[[1]]
[1] 55
----

=== `tapply`