= data.frames

== Abstract
Data.frames are one of the primary data structures used very frequently when working in R. Data.frames are tabular data structures, consisting of named columns of equal size, where each column has a single type.

You can create a data.frame easily. Vectors are used to fill the columns as follows:

=== Bracket Subsetting/Indexing

==== Data Frame Creation
====
[source,r]
----
df <- data.frame(cat_1=c(1,2,3), cat_2=c(9,8,7), 
                 ok=c(T, T, F), other=c("first", "second", "third"))

head(df)
----

----
   cat_1 cat_2    ok  other
 1     1     9  TRUE  first
 2     2     8  TRUE second
 3     3     7 FALSE  third
----
====

The different columns of a data frame can be disparate in type, the only requirement is that values column-wide have the same type. In this case, `cat_1` and `cat_2` contain integers, `ok` contains booleans, and `other` contains Strings.

Regular indexing rules apply to R data frames. Pay close attention to the commas in the following examples:

==== Indexing Rows Numerically
====
[source,r]
----
# Numeric indexing on rows:
df[1:2,]
----

----
   cat_1 cat_2   ok  other
 1     1     9 TRUE  first
 2     2     8 TRUE second
----
====

This method uses the indices of the rows, which are independent of the row names. We can update the names of the rows and subsequently index those as well, if row names are appropriate for the situation.

==== Row Naming & Indexing on Row Names
====
[source,r]
----
row.names(df) <- c("row1", "row2", "row3")
df[c("row1", "row3"),]
----

----
      cat_1  cat_2    ok  other
 row1     1      9  TRUE  first
 row3     3      7 FALSE  third
----
====

[TIP]
====
Though the row names replace the numerical indices in the output, we can still index using either. This same logic applies to columns, which also have intrinsic indices and are required to be named in order to be created.
====

So far we've indexed in two ways, and their differences merit explanation:

. `:` selects indices based on the given sequence. In R, this process is *inclusive*, meaning that `1:4` will select the first, second, third, _and_ fourth entries.
. `c()` defines a https://the-examples-book.com/book/r/lists-and-vectors[vector], as explained in the Lists & Vectors page, and indexing on vectors will select all rows/columns shared between the vector and data frame.

Indexing can also be done logically using a vector of Boolean values:

==== Logical Indexing
====
[source,r]
----
# selection is True for the first line, 
# False for the second, and True for the third

df[c(T,F,T),]
----

----
   cat_1 cat_2    ok other
 1     1     9  TRUE first
 3     3     7 FALSE third
----
====

For all of the above examples, there was at least one comma -- anything before the comma defines row selection, and anything after the comma defines column selection. If you leave out the comma, R will default to column selection.

==== Column-Default Indexing
====
[source,r]
----
df[c("cat_1", "ok")]
----

----
      cat_1    ok
 row1     1  TRUE
 row2     2  TRUE
 row3     3 FALSE
----
====

This is equivalent to leaving a blank space before the comma:

==== Indexing Column-Specific
====
[source,r]
----
df[, c(1,3)]
----

----
      cat_1    ok
 row1     1  TRUE
 row2     2  TRUE
 row3     3 FALSE
----
====

We can apply sequence-indexing and logical indexing to columns in the same way. You'll find that indexing rows and indexing columns is a nearly identical process that is easy to get hold of. We can combine any of the previous methods to index rows and columns simultaneously.

==== Putting It All Together
====
[source,r]
----
df[1:2, c(1,3)]
----

----
      cat_1   ok
 row1     1 TRUE
 row2     2 TRUE
----

[source,r]
----
df[c(T,F,T), c(T, F, F, F)]
----

----
 [1] 1 3
----
====

=== $ Subsetting/Indexing

A key feature of R is the `$` operator on data.frames, which is the more common indexing method for R.

==== $ Column Indexing
====
[source,r]
----
df$cat_1
----

----
 [1] 1 2 3
----
====

[NOTE]
====
You can extend this to index for row as well using `df$column_name[]`.

It's good to keep in mind that `$` lists column and then row, while just `df[ , ]` indexing requires row, then column.
====

==== Selecting Values from a Column
====
[source,r]
----
df$cat_1[c(F,T,F)]
----

----
[1] 2
----
====


=== Examples

==== *How can I get the first 2 rows of a data.frame named `df`?*

.Solution
====
[source,r]
----
df <- data.frame(cat_1=c(1,2,3), cat_2=c(9,8,7), 
                 ok=c(T, T, F), other=c("first", "second", "third"))
df[1:2,]
----

----
   cat_1 cat_2   ok  other
 1     1     9 TRUE  first
 2     2     8 TRUE second
----
====


==== *How can I get the first 2 columns of a data.frame named `df`?*

.Solution
====
[source,r]
----
df[,1:2]
----

----
   cat_1 cat_2
 1     1     9
 2     2     8
 3     3     7
----
====


==== *How can I get the rows where values in the column named `cat_1` are greater than 2?*

.Solution
====
[source,r]
----
# first example, using $
df[df$cat_1 > 2,]
----

----
   cat_1 cat_2    ok other
 3     3     7 FALSE third
----

[source,r]
----
# second example, using []
df[df[, c("cat_1")] > 2,]
----

----
   cat_1 cat_2    ok other
 3     3     7 FALSE third
----
====

==== *How can I get the rows where values in the column named `cat_1` are greater than 2 _and_ the values in the column named `cat_2` are less than 9?*

.Solution
====
[source,r]
----
df[df$cat_1 > 2 & df$cat_2 < 9,]
----

----
   cat_1 cat_2    ok other
 3     3     7 FALSE third
----
====


==== *How can I get the rows where values in the column named `cat_1` are greater than 2 _or_ the values in the column named cat`_2 are less than 9?*

.Solution
====
[source,r]
----
df[df$cat_1 > 2 | df$cat_2 < 9,]
----

----
   cat_1 cat_2    ok  other
 2     2     8  TRUE second
 3     3     7 FALSE  third
----
====


==== *How do I sample n rows randomly from a data.frame called `df`?*

.Solution
====
[source,r]
----
df[sample(nrow(df), n),]
----
You could also use the `sample_n` function from the package `dplyr`:
[source,r]
----
sample_n(df, n)
----
====


==== *How can I get only columns whose names start with "cat_"?*

.Solution
====
[source,r]
----
df <- data.frame(cat_1=c(1,2,3), cat_2=c(9,8,7), 
                 ok=c(T, T, F), other=c("first", "second", "third"))
df[, grep("^cat_", names(df))]
----

----
   cat_1 cat_2
 1     1     9
 2     2     8
 3     3     7
----
====
