= R

[quote, , www.r-project.org]
____
R is a language and environment for statistical computing and graphics. It is a GNU project which is similar to the S language and environment which was developed at Bell Laboratories (formerly AT&T, now Lucent Technologies) by John Chambers and colleagues. R can be considered as a different implementation of S. There are some important differences, but much code written for S runs unaltered under R.
____

R is a programming language commonly used by data scientists and statisticians for analysis and to create visualizations. R is frequently compared with other languages like Python, Matlab, and Julia. Like with most programming languages, there are tradeoffs when using R. While in many ways Python is easier to learn and work with than R, and more commonly used in industry, R has an extensive suite of statistical and graphic libraries used by many. In addition, the `ggplot2` package is still one of the best tools for creating both simple and advanced visualizations, rapidly -- regardless of the programming language.

* xref:variables.adoc[Variables]
* xref:logical-operators.adoc[Logical Operators]
* xref:lists-and-vectors.adoc[Lists and Vectors]
* xref:data.frames.adoc[Data Frames]
* xref:reading-and-writing-data.adoc[Reading and Writing Data]
* xref:control-flow.adoc[Control Flow]
* xref:writing-functions.adoc[Writing Functions]
* xref:r-base-functions.adoc[R Base Functions]
* xref:apply-functions.adoc[Apply Functions]
* xref:plotting.adoc[Plotting]

== Resources
