= Lists and Vectors

== Overview

=== Vectors

Vectors are one of the most important data structures in R. Vectors contain values that are _all_ the same type. The following are some examples of vectors.

[source,r]
----
# a logical vector
logical_vector <- c(F, T, TRUE, FALSE)
typeof(logical_vector)
----

----
'logical'
----

[CAUTION]
====
Be careful! The code above _could_ fail. Remember, `T` and `F` are global variables with an initial value of `TRUE` and `FALSE`. If someone were to run the following code _before_ running the code above, R would coerce every element in the vector to the _most-specific_ type, which is a character, now.

[source,r]
----
T <- "I'm a string, now"
logical_vector <- c(F, T, TRUE, FALSE)
logical_vector
----

----
[1] "FALSE" "I\'m a string, now" "TRUE" "FALSE"
----
====

[source,r]
----
# a double vector
double_vector <- c(1, 2, 3, 4)
typeof(nvec)
----

----
'double'
----

[source,r]
----
# a character vector
character_vector <- c("a", "b", "c", "d")
typeof(character_vector)
----

----
'character'
----

As mentioned before, as soon as you try and mix and match types, elements are coerced to the _least-specific_ type. For example, the following code will coerce all elements in the vector to a character.

[source,r]
----
typeof(c(0, 1, 2))
----

----
'double'
----

[source,r]
----
typeof(c(0, 1, 2, "ok"))
----

----
'character'
----

=== Lists

Lists are vectors that can contain any class of data. For example, the following produces a list with various types of elements.

[source,r]
----
my_list <- list(TRUE, 1, 2, "OK", c(1,2,3))
typeof(my_list)
----

----
'list'
----

You may be thinking, "well it looks like everything will be coerced to some other type, right? Nope. The elements of a list keep their underlying storage type.

[source,r]
----
typeof(my_list[[1]])
typeof(my_list[[2]])
typeof(my_list[[5]])
----

----
'logical'
'double'
'double'
----

== Indexing

=== Examples

== Recycling

=== Examples