= Variables

== Overview

== character

== numeric

== integer

== logical

== complex

== factors

A factor is R's way of representing a categorical variable. There are elements in a factor (just like there are elements in a vector), but they are constrained to only be chosen from a specific set of values, called "levels". They are useful when a vector has only a few different values it could be, like "Male" or "Female" and "A", "B", or "C".

=== Examples

==== How do I test whether or not a vector is a factor?

.Solution
====
[source, r]
----
test_factor <- factor("Male")
is.factor(test_factor)
----

----
[1] TRUE
----

[source,r]
----
test_factor_vec <- factor(c("Male", "Female", "Female"))
is.factor(test_factor_vec)
----

----
[1] TRUE
----
====

==== How do I convert a vector of strings to a factor?

.Solution
====
[source, r]
----
vec <- c("Male", "Female", "Female")
vec <- factor(vec)
----
====

==== How do I get the unique values a factor could hold, also known as its _levels_?

.Solution
====
[source, r]
----
vec <- factor(c("Male", "Female", "Female"))
levels(vec)
----

----
[1] "Female" "Male"
----
====

==== How can I rename the levels of a factor?

.Solution
====
[source, r]
----
vec <- factor(c("Male", "Female", "Female"))
levels(vec)
----

----
[1] "Female" "Male"
----

[source,r]
----
levels(vec) <- c("F", "M")
vec
----

----
[1] M F F
Levels: F M
----

[source,r]
----
# be careful! Order matters, this is wrong:
vec <- factor(c("Male", "Female", "Female"))
levels(vec)
----

----
[1] "Female" "Male"
----

[source,r]
----
# here we incorrectly rename "Female"'s to "M" instead of "F"
levels(vec) <- c("M", "F")
vec
----

----
[1] F M M
Levels: M F
----
====

==== How can I find the number of levels of a factor?

.Solution
====
[source, r]
----
vec <- factor(c("Male", "Female", "Female"))
nlevels(vec)
----

----
[1] 2
----
====

== Dates

== `NA` & `NaN` & `NULL`

`NA`::

`NA` stands for not available. In general, this represents a missing value or a lack of data. _Technically_, `NA` is a logical value. You can test this with the following code.

[source,r]
----
class(NA)
----

`NaN`::
`NaN` stands for not a number. This is a special value that is used to indicate that there is a result, it just cannot be represented as a number (for example the result of 0/0). _Technically_, `NaN` is a numeric value. You can test this with the following code.

[source,r]
----
class(NaN)
----

`NULL`::

If you have an understanding of `NULL` from other programming languages, you can carry it over to R. Otherwise, it is safe to think of `NULL` as something that is neither `TRUE` nor `FALSE`. _Technically_, `NULL` is its own thing. It is not a logical value, numeric value, etc. `NULL` is commonly used to represent an empty object or something that exists but isn't really defined. When trying to distinguish between `NA` and `NULL`, think of `NA` as a missing value, and `NULL` as an undefined value.

=== Examples

==== How do I tell if a value is `NA`?

.Solution
====
[source, r]
----
# test if a value is NA.
value <- NA
is.na(value)
----

----
[1] TRUE
----

[source,r]
----
# does is.nan return TRUE for NA?
is.nan(value)
----

----
[1] FALSE
----
====

==== How do I tell if a value is `NaN`?

.Solution
====
[source, r]
----
# test if a value is NaN.
value <- NaN
is.nan(value)
----

----
[1] TRUE
----

[source,r]
----
value <- 0/0
is.nan(value)
----

----
[1] TRUE
----

[source,r]
----
# does is.na return TRUE for NaN?
is.na(value)
----

----
[1] TRUE
----
====

==== How do I tell if a value is `NULL`?

.Solution
====
[source, r]
----
# test if a value is NULL.
value <- NULL
is.null(value)
----

----
[1] TRUE
----

[source,r]
----
class(value)
----

----
[1] "NULL"
----

[source,r]
----
# does is.na return TRUE for NULL?
is.na(value)
----

----
logical(0) # no
----
====

== Resources

https://swcarpentry.github.io/r-novice-inflammation/13-supp-data-structures/[SWCarpentry Data Types and Structures]

A good overview of the various data types in R.

https://www.r-bloggers.com/2010/04/r-na-vs-null/[R-Bloggers, NA vs. NULL]

A good writeup on the differences between `NA` and `NULL`.