= Variables

== Overview

== character

== numeric

== integer

== logical

== complex

== factors

== Dates

== `NA` & `NaN` & `NULL`

`NA`::

`NA` stands for not available. In general, this represents a missing value or a lack of data. _Technically_, `NA` is a logical value. You can test this with the following code.

[source,r]
----
class(NA)
----

`NaN`::
`NaN` stands for not a number. This is a special value that is used to indicate that there is a result, it just cannot be represented as a number (for example the result of 0/0). _Technically_, `NaN` is a numeric value. You can test this with the following code.

[source,r]
----
class(NaN)
----

`NULL`::

If you have an understanding of `NULL` from other programming languages, you can carry it over to R. Otherwise, it is safe to think of `NULL` as something that is neither `TRUE` nor `FALSE`. _Technically_, `NULL` is its own thing. It is not a logical value, numeric value, etc. `NULL` is commonly used to represent an empty object or something that exists but isn't really defined. When trying to distinguish between `NA` and `NULL`, think of `NA` as a missing value, and `NULL` as an undefined value.

=== Examples

==== How do I tell if a value is `NA`?

.Solution
====
[source, r]
----
# test if a value is NA.
value <- NA
is.na(value)
----

----
[1] TRUE
----

[source,r]
----
# does is.nan return TRUE for NA?
is.nan(value)
----

----
[1] FALSE
----
====

==== How do I tell if a value is `NaN`?

.Solution
====
[source, r]
----
# test if a value is NaN.
value <- NaN
is.nan(value)
----

----
[1] TRUE
----

[source,r]
----
value <- 0/0
is.nan(value)
----

----
[1] TRUE
----

[source,r]
----
# does is.na return TRUE for NaN?
is.na(value)
----

----
[1] TRUE
----
====

==== How do I tell if a value is `NULL`?

.Solution
====
[source, r]
----
# test if a value is NULL.
value <- NULL
is.null(value)
----

----
[1] TRUE
----

[source,r]
----
class(value)
----

----
[1] "NULL"
----

[source,r]
----
# does is.na return TRUE for NULL?
is.na(value)
----

----
logical(0) # no
----
====

== Resources

https://swcarpentry.github.io/r-novice-inflammation/13-supp-data-structures/[SWCarpentry Data Types and Structures]

A good overview of the various data types in R.

https://www.r-bloggers.com/2010/04/r-na-vs-null/[R-Bloggers, NA vs. NULL]

A good writeup on the differences between `NA` and `NULL`.