= TDM 10100: Project 2 -- 2023
Introduction to R part I

The R environment is a powerful tool to perform data analysis. R's language is often compared to Python. Both languages have their advantages and disadvantages, and both are worth learning. 

In this project we will dive in head-first and learn some of the basics while solving data-driven problems.


.5 basic types of data
[%collapsible]
====
    * Values like 1.5 are called numeric values, real numbers, decimal numbers, etc.
    * Values like 7 are called integers or whole numbers.
    * Values TRUE or FALSE are called logical values or Boolean values.
    * Texts consist of sequences of words (also called strings), and words consist of sequences of characters.
    * Values such as 3 + 2ifootnote:[https://stat.ethz.ch/R-manual/R-devel/library/base/html/complex.html] are called complex numbers.  We usually do not encounter these in The Data Mine.
====



[NOTE]
====
R and Python both have their advantages and disadvantages.  A key part of learning data science methods is to understand the situations in which R is a more helpful tool to use, or Python is a more helpful tool to use.  Both of them are good for their own purposes.  In a similar way, hammers and screwdrivers and drills and many other tools are useful for construction, but they all have their own individual purposes.

In addition, there are many other languages and tools, e.g., https://julialang.org/[Julia] and https://www.rust-lang.org/[Rust] and https://go.dev/[Go] and many other languages are emerging as relatively newer languages that each have their own advantages.
====

**Context:** In the last project we set the stage for the rest of the semester. We got some familiarity with our project templates, and modified and ran some examples. 

In this project, we will continue to use R within Jupyter Lab to solve problems. Soon, you will see how powerful R is and why it is often more effective than using spreadsheets as a tool for data analysis.

**Scope:** xref:programming-languages:R:introduction.adoc[R], xref:programming-languages:R:lists-and-vectors.adoc[vectors, lists], https://rspatial.org/intr/4-indexing.html[indexing]

.Learning Objectives
****
- Be aware of the different concepts and when to apply them; such as lists, vectors, factors, and data.frames 
- Be able to explain and demonstrate: positional, named, and logical indexing.
- Read and write basic (csv) data using R.
- Identify good and bad aspects of simple plots.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- `/anvil/projects/tdm/data/flights/subset/1995.csv`

== Questions

=== Question 1
[upperalpha]
.. How many columns does this dataframe have?
.. How many rows does this dataframe have?
.. What type/s of data are in this dataframe (example: numerical values, and/or text strings, etc.)

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_z48k1y3g&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++

////
The data that we may be working with does not always come to us neat and cleanfootnote:["Raw data" vs "Clean data". Some datasets require "cleaning" such as removing duplicates, removing null values and disgarding irrelevent data].
////

It is important to get a good understanding of the dataset(s) with which you are working. This is the best first step to help solve any data-driven problems.

We are going to use the `read.csv` function to load our datasets into a dataframe.

To read data in R from a CSV file (.csv), you use the following command:

[source,r]

----
myDF <- read.csv("/anvil/projects/tdm/data/flights/subset/1995.csv")
----

[NOTE]
====
Here `myDF` is a variable - a name that references our dataframe. In practice, you should always use names that are specific, descriptive, and meaningful.
====

We want to use functions such as `head`, `tail`, `dim`, `summary`, `str`, `class`,  to get a better understanding of our dataframe. 

.Helpful Hints
[%collapsible]
====
- `head(myDF)` - Look at the head (or top) of the dataframe

- `tail(myDF)` - Look at the tail (or bottom) of the dataframe

- `class(myDF$Dest)` - Return the type of data in a column of the dataframe, for instance, in a column that stores the destination of flights (Dest)

- What do `dim`, `summary`, and `str` do?
====

.Items to submit*
====
- Code used to solve this problem.
- Output from running the code.
- The answers to sub-questions A, B, and C.
====

=== Question 2
[upperalpha]
.. What type of data is in the vector `myairports`?
.. The vector `myairports` contains all of the airports where flights departed from in 1995.  Print the first 250 of those airports. (Do not print all of the airports, because there are 5327435 such values!) How many of the first 250 flights departed from O'Hare?
.. How many flights departed from O'Hare altogether in 1995?

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_7doevmwn&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++

Let's create a new https://sudo-labs.github.io/r-data-science/vectors/[vector] called `myairports` containing all of the origin airports (i.e., the airports where the flights departed) from the column `myDF$Origin` of the data frame `myDF`. We can do this using the `$` operator. Documentation on the `$` operator can be found https://statisticsglobe.com/meaning-of-dollar-operator-in-r[here], and an example of how to use it is given below.

[source,r]
----
newVector <- myDF$ColumnName
----

.Insider Knowledge
[%collapsible]
====
A vector is a simple way to store a sequence of data.  The data can be numeric data, logical data, textual data, etc.
====
//To assist with this question, please also see the end of the video from Question 1.

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answers to sub-questions A, B, and C.
====

=== Question 3

[upperalpha]
.. How many flights departed from Indianapolis (`IND`) in 1995?  How many flights landed there?
.. Consider the flight data from row 894 the data frame.  What airport did it depart from?  Where did it arrive?
.. How many flights have a distance of less than 200 miles?

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_dna4su06&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++

There are many different ways to access data after we load it, and each has its own use cases. One of the most common ways to access data is called _indexing_. Indexing is a way of selecting or excluding specific elements in our data. This is best shown through examples, some of which can be found https://rspatial.org/intr/4-indexing.html[here].

.Insider Knowledge
[%collapsible]
====
Accessing data can be done in many ways, one of those ways is called **_indexing_**. Typically we use brackets **[ ]** when indexing. By doing this we can select or even exclude specific elements. For example we can select a specific column and a certian range within the column. Some examples of symbols to help us select elements include: +
     * < less than +
     * > greater than +
     * <= less than or equal to +
     * >= greater than or equal to +
     * == is equal +
     * != is not equal +
It is also important to note that indexing in R begins at 1. (This means that the first row of the dataframe will be numbered starting at 1.)
====

.Helpful Hint
[%collapsible]
====
Many programming languages, such as https://www.python.org/[Python] and https://www.learn-c.org/[C], are called "zero-indexed". This means that they begin counting from '0' instead of '1'. Because R is not zero-indexed, we can count like humans normally do. However, this is a good thing to keep in mind going forward.
====

.Helpful Examples
[%collapsible]
====
[source,r]
----
# find data by their indices
myDF$Distance[row_index_start:row_index_end,] 

# creates a new vector with the specific info
mynewvector <- myDF$putcolumnnamehere

# all of the data from row 3
myDF[3,]

# all of the data in all of the rows, with columns between myfirstcolumn and mylastcolumn
myDF[,myfirstcolumn:mylastcolumn] 


# the first 250 values from column 17
head(myDF[,17], n=250)

# puts all variables that are less than 6 from the dataframe
longdistances = myDF$Distance[myDF$Distance > 2000]
----
====

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answers to questions A, B, and C.
====

=== Question 4
[upperalpha]
.. Rank the airline companies (in the column `myDF$UniqueCarrier`) according to their popularity, (i.e. according to the number of flights on each airline).
.. Now find the ten airplanes that had the most flights in 1995.  List them in order, from most popular to least popular.  Do you notice anything unusual about the results?

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_5ypy9ra5&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++

Oftentimes we will be dealing with enormous quantities of data, and it just isn't feasible to try and look at the data point-by-point in order to summarize the entire dataframe. When we find ourselves in a situation like this, the `table()` function is here to save the day! 

Take a look at https://www.geeksforgeeks.org/create-table-from-dataframe-in-r/[this link] for some examples of how to use the `table()` function in R. Once you have a good understanding of how it works, try and answer the three sub-questions below using the `table()` function. You may need to use some other basic R functions as well.

.Insider Knowledge
[%collapsible]
====
It is useful to use functions in R and see how they behave, and then to take a function of the result, and take a function of that result, etc.  For instance, it is common to summarize a vector in a table, and then sort the results, and then take the first few largest or smallest values. This is known as "nesting" functions, and is common throughout programming.

====

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answers to sub-questions A and B.
====

=== Question 5
[upperalpha]
.. Using the R built-in function `hist()`, create a histogram of flight distances.
.. Write 2-3 sentences detailing any patterns you see in your plot and what those patterns tell you about the distance of flights in this dataset.

**VIDEO IS GOING TO GO HERE**

Graphs are a very important tool in analyzing data. By visualizing our data in any of a number of ways, we can discover patterns that may not be as readily apparent by simply looking at tables. As such, they are a vital skill in all data scientists' skillset. 

In this question, we would like you to get comfortable with plotting in R. There are a number of built in tools for basic plotting in this language, but we will focus on histograms here. Using the `Distance` column of our dataframe, create a histogram of the distribution of distances for our data. Then, write a few sentences describing your plot, any patterns you see, and what the distribution as a whole looks like.

.Helpful Hint
[%collapsible]
====
https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/hist[Documentation on R histograms] may help you understand how to answer this question.
====

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- Answer to sub-question B.
====


[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====