= TDM 10100: Project 2 -- 2022

**Motivation:** The R environment is a powerful tool to perform data analysis. R is a tool that is often compared to Python. Both have their advantages and disadvantages, and both are worth learning. In this project we will dive in head first and learn some of the basics while solving data-driven problems.

[NOTE]
====
R and Python both have their advantages and disadvantages. There still exist domains and problems where R is better than Python, and where Python is better than R. In addition, https://julialang.org/[Julia] is another language in this domain that is quickly gaining popularity for its speed and Python-like ease of use.
====

**Context:** In the last project we set the stage for the rest of the semester. We got some familiarity with our project templates, and modified and ran some R code. In this project, we will continue to use R within Jupyter Lab to solve problems. Soon, you will see how powerful R is and why it is often a more effective tool to use than a tool like spreadsheets.

**Scope:** r, vectors, indexing, recycling

.Learning Objectives
****
- List the differences between lists, vectors, factors, and data.frames, and when to use each.
- Explain and demonstrate: positional, named, and logical indexing.
- Read and write basic (csv) data using R.
- Identify good and bad aspects of simple plots.
- Explain what "recycling" is in R and predict behavior of provided statements.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- `/anvil/projects/tdm/data`

== Questions

=== Question 1



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 2



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 3



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 4



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 5



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====