= TDM 10100: Project 11 -- 2022
Application 

**Motivation:** Selecting the right tools, understanding a problem and knowing what is available to support you takes practice. +
So far this semester we have learned multiple tools to use in `R` to help solve a problem. This project will be an opportunity for you to choose the tools and decide how to solve the problem presented. 

We will also be looking at `Time Series` data. This is a way to study the change of one or more variables through time. Data visualizations help greatly in looking at Time Series data. 


Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

"/anvil/projects/tdm/data/zillow/County_time_series.csv"

== Questions

=== ONE

Read in the dataset "/anvil/projects/tdm/data/zillow/County_time_series.csv" into a data.frame named `county`
[loweralpha]
.. Convert the `Date` column to month, date, year format. 
.. How many years are in the data.frame in total?

.. Create a lineplot that shows the column `MedianListingPricePerSqft_3Bedroom` average price per year *AND* `MedianListingPricePerSqft_1Bedroom` average price per year. 

.. Create a lineplot that shows the average value per year of `MedianListingPricePerSqft_3Bedroom` *AND* shows the average value per year of `MedianListingPricePerSqft_1Bedroom`. 
.. Write one to two sentences on what you notice in the graph

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== TWO
[loweralpha]

.. What is the median of the top tier homes per year? Write a sentence or two about anything that may seem interesting about this data.
.. What is the median of the bottom tier homes in 2014?
.. What is the median of the middle tier homes in 2010?


[loweralpha]


.Helpful Hint
[%collapsible]
====
You can use either `tapply` OR the `aggregate` function for this
====

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

.. What is the average value per year of the median prices of top tier homes? Write a sentence or two about anything that may seem interesting about this data.
.. What is the average value of the median of bottom tier homes in 2014?
.. What is the average value of the median of middle tier homes in 2010?


Can you create a graph that shows all three columns (bottom tier, middle tier, and top tier) in comparison by year? 

.Helpful Hint
[%collapsible]
====
You can use the library ggplot2 for this

You can use either `tapply` OR the `aggregate` function for this
====

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== THREE

Looking at the data, is there something that you find interesting? 
Create 3 new graphs and explain what you see and why you chose that specific type of plot.

Can you create a graph that shows the average per year of each of the three columns (bottom tier, middle tier, and top tier), so that you can easily compare these variables?

.Helpful Hint
[%collapsible]
====
You can use the library ggplot2 for this
====


.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====


Looking at the data, is there something that you find interesting? 
Create 3 new graphs and explain what you see and why you chose that specific type of plot.


.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====



[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
