= TDM 10100: Project 10 -- 2023
Creating functions and using `tapply` and `sapply`

**Motivation:**  As we have learned, functions are foundational to more complex programs and behaviors. +
There is an entire programming paradigm based on functions called https://en.wikipedia.org/wiki/Functional_programming[functional programming].

**Context:** 
We will apply functions to entire vectors of data using `tapply` and `sapply`. We learned how to create functions, and now the next step we will take is to use it on a series of data. 

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The project will use the following dataset(s):

* `/anvil/projects/tdm/data/restaurant/orders.csv`
* `/anvil/projects/tdm/data/restaurant/vendors.csv`

[NOTE]
====
read.csv() function automatically delineates by a comma`,` +
You can use other delimiters by using adding the `sep` argument +
i.e. `read.csv(...sep=';')` +
====


== Questions

=== Question 1 (1 pt)
[loweralpha]
.. Please load the datasets into data frames named `orders` and `vendors`
.. Please look at both data frames and find out what are dimensions of the data frames: How many columns and rows for each data frame 

=== Question 2 ( 1 pt)

[NOTE]
====
* Simply put `grep` helps us to find a word within a string. In R `grep` is vectorized and can be applied to an entire vector of strings. We will use it to find the restaurants that provides `Fries` in the data frame `vendors`. You may get more information from https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/grep [grep: Pattern Matching and Replacement]
* Syntax
[source,r]
grep(pattern, x, ignore.case = FALSE, perl = FALSE, value = FALSE,
     fixed = FALSE, useBytes = FALSE, invert = FALSE)

====

[loweralpha]
.. Please create a new variable named r_w_fries. This variable should store the output from a grep function that looks for the word "Fries" in the vendors’s vendor_tag_name column 
.. Display the output of the previous grep function 

=== Questions 3 (2 pts)
[NOTE]
====
* Now look into how to use `grepl` function https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/grep [grepl]
* Syntax
[source,r]
grepl(pattern, x, ignore.case = FALSE, perl = FALSE,
      fixed = FALSE, useBytes = FALSE)
====
[loweralpha]
.. Please use `grepl` function to get all records in `vendors` that provide fries and list the result
.. Please find out total number of restaurants from previous question

[NOTE]
====
You may find some useful information on regular expression for extraction used by `grep/grepl` here https://bookdown.org/rdpeng/rprogdatascience/regular-expressions.html [Regex]
====

[NOTE]
====
Just an FYI refresh: +

* `<-` is an assignment operator, it assigns values to a variable

* Functions *must* be called using the round brackets aka parenthesis *`()`* 

* Square brackets *`[]`*, are also called `extraction operators` as they are used to help extract specific elements from a vector or matrix. 
====

=== Question 4 (2 pts)

.. Please write a command to find out the column in `vendors` data frame that contains delivery_charge information, you may find out that column does not have empty value so in the following questions you may not have to consider null value
.. The delivery_charge column in the vendors data frame has two different values: 0 and 0.7. List how many restaurants have free delivery (0) and how many are not-free (0.7)
.. Please find out the proportions (% of total values) for free delivery and not-free delivery vendors in the data frame 

[TIP]
====
* `names` and `which` function will be useful to find the data frame's column information 
* The `table()` function can be used to quickly create frequency tables 
* The `prop.table()` function can calculate the value of each cell in a table as a proportion of all values.
====

=== Question 5 (2 pts)

[NOTE]
====
* The `tapply` function can be used to apply some function to a vector that has been grouped by another vector. You may get more information from https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/tapply[tapply] `
* Syntax 
[source,r]
`tapply(x, INDEX, FUNCTION)`

* The `sapply` function takes a list, vector, or data frame as input and gives output in the form of an array or matrix object.It is useful for operations on list objects and returns a list object of same length of original set. You may get more information from https://www.geeksforgeeks.org/applying-a-function-over-an-object-in-r-programming-sapply-function/ [sapply]
====
.. Please use `tapply` to find the percentages of different group of vendors, grouped by vendor_category_id in vendors data frame ( `2` , `3` )  that provide free delivery vs non-free delivery

.. Please use `sapply()` to find the percentages of different group of vendors, (grouped by `vendor_category_id` in `vendors` data frame, as category `2` or category `3` )  that provide free delivery vs non-free delivery
 
[TIP]
====
* You may use a user defined function with `tapply`, For example:
[source,r]
function(x){prop.table(table(x))}
* You can modify this function as needed
====

Project 10 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project10.ipynb` 

* Submit files through Gradescope
====

 
[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
