= TDM 10100: Project 4 -- Fall 2023
Introduction to R part III


Many data science tools including xref:programming-languges:R:introduction[R] have powerful ways to index data.

[NOTE]
====
R typically has operations that are vectorized and there is little to no need to write loops. + 
R typically also uses indexing instead of using an if statement.

* Sequential statements (one after another) i.e. + 
1. print line 45 + 
2. print line 15 +

**if/else statements**
 create an order of direction based on a logical condition. +

if statement example:
[source,r]
----
x <- 7
if (x > 0){
print ("Positive number")
}
----
else statement example:
[source,r]
----
x <- -10
if(x >= 0){
print("Non-negative number")
} else {
print("Negative number")
}
----
In `R`, we can classify many numbers all at once:
[source,r]
----
x <- c(-10,3,1,-6,19,-3,12,-1)
mysigns <- rep("Non-negative number", times=8)
mysigns[x < 0] <- "Negative number"
mysigns
----

====
**Context:** As we continue to become more familiar with `R` this project will help reinforce the many ways of indexing data in `R`. 

**Scope:** R, data.frames, indexing. 

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].


Using the *seminar-r* kernel 
Lets first see all of the files that are in the `craigslist` folder 
[source,r]
----
list.files("/anvil/projects/tdm/data/craigslist")
----

[NOTE]

====
Remember: +

* If we want to see the file size (aka how large) of the CSV. 
[source,r]
----
file.info("/anvil/projects/tdm/data/craigslist/vehicles.csv")$size
----

* You can also use 'file.info' to see other information about the file. 
====

After looking at several of the files we will go ahead and read in the data frame on the Vehicles
[source,r]
----
myDF <- read.csv("/anvil/projects/tdm/data/craigslist/vehicles.csv", stringsAsFactors = TRUE)
----

It is so important that, each time we look at data, we start by becoming familiar with the data. +
In past projects we have looked at the head/tail along with the structure and the dimensions of the data. We want to continue this practice.

This dataset has 25 columns, and we are unable to see it all without adjusting the width.  We can do this by
[source,r]
----
options(repr.matrix.max.cols=25, repr.matrix.max.rows=200)
----
and we also remember (from the previous project) that we can set the output in `R` to look more natural this way:
[source,r]
----
options(jupyter.rich_display = F)
----


[TIP]
====
- Use 'head' to look at the first 6 rows  
[source,r]
 head(myDF) 
- Use 'tail' to look at the last 6 rows  
[source, r]
 tail(myDF) 
- Use `str` to check structure  
[source, r]
 str(myDF) 
- Use `dim` to check dimensions  
[source, r]
 dim(myDF) 

To sort and order a single vector you can use this code:
[source,r]
----
head(myDF$year[order(myDF$year)])
----
You can also use the `sort` function, by default it sorts in ascending order, if want the order in descending, use 'secreasing' argument
[source,r]
head(sort(myDF$year, decreasing = TRUE))
====

_**vectorization**_

Most of R's functions are vectorized, which means that the function will be applied to all elements of a vector, without needing to loop through the elements one at a time. The most common way to access individual elements is by using the `[]` symbol for indexing. 

[NOTE]
====
[source,r]
----
cut(myvector, breaks = c(10,50,200) , labels = c(a,b,c))

breaks value specified the range of myvector divided into the following intervals:
- (-∞, 10)
- [10, 50)
- [50, 200)
- [200, ∞)

labels valuse will be assigned 
- Values less than 10: Will be given an NA label   
- Values in the range [10, 50): Will be labeled as "a".
- Values in the range [50, 200): Will be labeled as "b".
- Values 200 and above: Will be labeled as "c".
----
====

== Questions

=== Question 1 (1.5 pts)
[upperalpha]
.. How many unique states are there in total? Name 5 of the different states that are included in this dataset.
.. How many cars's price is equal or higher than $2000 ?
.. What is the average price of the vehicles in the dataset?


=== Question 2 (1.5 pts)
[upperalpha]
.. Create a new column `mileage_category` in your data.frame that categorize the vehicle's mileage into different buckets 
... "Low": [0, 50000)
... "Moderate": [50000, 100000)
... "High": [100000, 150000)
... "Very High": [150000, Inf)
.. Use _table_ to list cars in the different mileage_categories

.. Create a new column called `has_VIN` that flag if the listing Vehicle has a VIN provided

[NOTE]
====
Remember to consider _empty_ values and or `NA` values 

====

=== Question 3 (1.5 pts)
[upperalpha]
.. Using the table() function, and the column myDF$has_VIN, identify how many vehicles have VIN and how many are not .
.. Using the `cut` function and appropriate `breaks`, create a new column called `new_mileage_category`.  Verify that this column is identical to the previously created `mileage_category` column, created in question Question 2.
.. Create a new column`description_length_category` to categorize listings based on the length of their descriptions
... "Very Short": [0, 50)
... "Short": [50, 100)
... "Medium": [100, 200)
...  "Long": [200, 500)
... "Very Long": [500, Inf)

[TIP]

You may count number of characters by nchar() function
[source,r]
    mynchar(as.character(myDF$description))


=== Question 4 (1.5 pts)

**Preparing for Mapping**
//[arabic]
[upperalpha]
.. Extract all of the data for texas into a data.frame called myTx
.. Identify the most popular state from myDF, and extract all of the data from that state into a data.frame called popularState.
.. Create a third data.frame with the data from a state of your choice




=== Question 5 (2 pts)

**Mapping**
[upperalpha]
.. Using the R package `leaflet`, make 3 maps of the USA, namely, one map for the data in each of the `data.frames` from question FOUR.




=== Submitting your Work
Well done, you've finished Project 4! Make sure that all of the below files are included in your submission, and feel free to come to seminar, post on Piazza, or visit some office hours if you have any further questions.

Project 4 Assignment Checklist
====
- Code used to solve quesiton 1 to 5
- Output from running th code
- Copy thes code and outputs to a new Python File and a new R File respectively
    * `firstname-lastname-project04.ipynb`.
    * `firstname-lastname-project04.R`.
- submit files through gradescope
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output, when in fact it does not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/current-projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or it does not render properly in gradescope. Please ask a TA if you need help with this.
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
