= TDM 10100: Project 13 -- 2023

**Motivation:** This semester we took a deep dive into `R` and it's packages. Lets take a second to pat ourselves on the back for surviving a long semester and review what we have learned! 

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The project will use the following dataset:

* `/anvil/projects/tdm/data/icecream/combined/products.csv`

== Questions

=== Questions 1 ( 2 pts)

Read in the dataset and into a data.frame called `orders`
[loweralpha]
.. What is the file size, how many rows, columns and type of data?
.. How many ice creams do not contain "MILK"? and what is the average rating for them?
.. Please find out average rating for ice creams contain "MILK"

[TIP]
====
"invert" parameter of the grep function will be useful
====

 
=== Question 2 (2 pts)
 
.. What is the average rating for ice cream contains "PEANUTS"?  

.. Plot or Graph all the ice creams that contain "PEANUTS" using "key" and their ratings.

[TIP]
====
- You may use ggplot, below is some sample code, edit if needed and/or you may create your owns. 

[source,r]
library(ggplot2)
...
# get keys and ratings for the ice cream that contain "PEANUTS"
pnDF<-data.frame(keys,ratings)
ggplot(pnDF,aes(x=keys,y=ratings))+ geom_dotplot(binaxis = 'y',stackdir = 'center',dotsize=0.5)+theme(axis.text.x=element_text(angle=90,hjust = 1))+labs(title="PEANUTS!!!",x ="Key",y="Rating")

====

=== Question 3 (2 pts)

 
.. Create a plot of the average rating of icecream by "brand"

[TIP]
====
- dotchart may be useful. Below is some sample code, edit if needed and/or you may create your owns.
[source,r]
...
# use tapply to get average ratings
dotchart(sort(average_ratings,decreasing = TRUE))
====

=== Question 4 (2 pts)

.. Use the `unique` function to investigate the name column. and display the the brand with flavor count. The output will be like

.output

    brand flavor_count
bj  bj          57
....

Project 13 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project13.ipynb` 
* R code and comments for the assignment
    ** `firstname-lastname-project13.R`.

* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
