= TDM 10100: Project 10 -- 2022

**Motivation:**  As we have learned functions are foundational to more complex programs and behaviors. +
There is an entire programming paradigm based on functions called https://en.wikipedia.org/wiki/Functional_programming[functional programming].

**Context:** 
We will apply functions to entire vectors of data using `sapply`. We learned how to create functions, and now the next step we will take is to use it on a series of data. `sapply` is one of the best ways to do this in `R`. 

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

* /anvil/projects/tdm/data/okcupid/filtered/users.csv
* /anvil/projects/tdm/data/okcupid/filtered/questions.csv

.Helpful Hint
[%collapsible]
====
read.csv() function automatically delineates by a comma`,` +
You can use other delimiters by using adding the `sep` argument +
i.e. read.csv(...sep=';') +

Use the readlines(...,n=x) function to see the first x number of rows to identify what the character that you will use in the `sep` argument.  
====


== Questions

=== ONE
We want to go ahead and load the datasets into data.frames named `users` and `questions`. Take a look at both data.frames and identify what is apart of each of them. What information is in each datatset and how they are related.


.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
-1 or 2 sentances on the datasets.
====

=== Question 2



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 3



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 4



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 5



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:book:projects:submissions.adoc[submission guidelines] before submitting your project.
====