= TDM 10100: Project 3 -- Fall 2022
Inroduction to R part II

In xref:programming-languges:R:introduction[R] a *data frame* is the primary data structure. It is important to understand how to insert, retrieve, and update data in a *data frames*. 

.Insider Knowlege 
[%collapsible]
====
A *data frame* is a table or a 2D array. Each column containes values or a variable.  Each row contains one set of values for each column. 
====
**Context:** In the previous project we ran our first R code. Learned about accessing data within vectors. +
In this project we will continue to reinforce what we've already learned and introduce a new, flexible data structure called `data.frame`s.

**Scope:** r, data.frames, recycling, factors

.Learning Objectives
****
- Explain what "recycling" is in R and predict behavior of provided statements.
- Explain and demonstrate how R handles missing data: NA, NaN, NULL, etc.
- Demonstrate the ability to use the following functions to solve data-driven problem(s): mean, var, table, cut, paste, rep, seq, sort, order,  length, unique, etc.
- Read and write basic (csv) data.
- Explain and demonstrate: positional, named, and logical indexing.
- List the differences between lists, vectors, factors, and data.frames, and when to use each.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].


Using the *f2022-s2023-r* kernel 
Lets first see all of the files that are in the Disney folder 
[source,r]
----
list.files(path = "/anvil/projects/tdm/data/disney", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)
----

After looking at several of the files we will go ahead and read in the data frame on the 7 Dwarfs Train.
[source,r]
----
myDF <- read.csv("/anvil/projects/tdm/data/disney/7_dwarfs_train.csv", stringsAsFactors = TRUE)
----

If we want to see the file size (aka how large) of the CSV. 
[source,r]
----
file.info("/anvil/projects/tdm/data/disney/7_dwarfs_train.csv")$size
----
You can also use 'file.info' to see other information about the file. 

.Insider Knowledge
[%collapsible]
====
*size*- double: File size in bytes. +
isdir- logical: Is the file a directory? +
*mode*- integer of class "octmode". The file permissions, printed in octal, for example 644. +
*mtime, ctime, atime*- integer of class "POSIXct": file modification, ‘last status change’ and last access times. +
*uid*- integer: the user ID of the file's owner. +
*gid*- integer: the group ID of the file's group. +
*uname*- character: uid interpreted as a user name.
grname +
character: gid interpreted as a group name. Unknown user and group names will be NA. 
====

=== ONE

Familiarizing yourself with the data. 

.Helpful Hint
[%collapsible]
====
You can look at the first 6 rows (`head`) and the last 6 rows (`tail`). The structure (`str`) and/or the dimentions (`dim`) of the dataset. +

*"SACTMIN"* is the actual minuites that a person waited in line +
*"SPOSTMIN"* is the time above the ride estimating the wait time. (Any value that is -999 means that the ride was not in service) +
*"datetime"* is the date and time the information was recorded +
*"date"* is the date of the event 
====

In the last project we learned about how to look at the data.frame. Based on that, write 1-2 sentences describing the dataset (how many rows, how many columns, the type of data, etc.) and what it holds. Use the head command to look at the first 21 rows.


.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- 1-2 sentences explaining the dataset.
====

=== TWO

Now that we have a better understanding of content and structure of our data. We are diving a bit deeper and making connections within the data.

[loweralpha]
.. If we are looking at the column *"SPOSTMIN"* what do you notice about the increments of time?
.. How many different wait time options do you see?
.. How many NA values do you see in *"SACTMIN"*. 
.. Create a new data frame with the name `newDF` that has all NA values removed in the *"SACTMIN"* colummn.

.Insider Knowledge
[%collapsible]
====
`na.omit` and `na.exclude` returns objects with the ovservations removed if they contain any missing values. As well as performs calculations by considering the NA values but does not include them in the calculation. +
`na.rm` first [.underline]#removes the NA values and then# does the calculation. +
`na.pass` returns the object unchanged 
====

.Helpful Hint
[%collapsible]
====
Use the code below 
[source,r]
----
table(myDF['SPOSTMIN'])
----
====

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answer to the 3 questions above.
====
=== THREE

[loweralpha]
.. On Christmas day what was the average wait time? 
.. On July 26th what was the average wait time and was there a difference between summer and the holiday? 
.. For which date is there the most entries in the data set?

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answer to the 3 questions above.
====

==== FOUR
Recyling in R  +

.Insider Knowledge
[%collapsible]
====
Recycling happens in R automatically.When you are teempting to preform operations like addition, subtraction on two vectors of unequal length. +
The shorter vector will be repeated as long as the operation is completeing on the longer vector. 
====

[loweralpha]
.. Find the lengths of the column *"SACTMIN"* in the `myDF` and `newDF`.
.. Create a new vector called `myhours` by adding together *"SACTMIN"* columns from `myDF` and `newDF` each divided by 60  What is the length of that `myhours`?
.. What happened in row 7636?



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answers to the 3 questions above.
====


==== FIVE
Indexing and Expanding dataframes in R 

[source,r]
----
library(lubridate, warn.conflicts = FALSE)
myDF$weekday <- wday(myDF$datetime, label=TRUE)
----

[loweralpha]
.. What day of the week in 'myDF' has the longest wait times?
.. Make a boxplot and a dotchart of 'myDF' which one conveys the infomation better and why?
.. We created a new column in 'myDF' that shows the weekdays, add another column in 'myDF' that shows the month. 


.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answers to the 3 quetsions above.
====





[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
====