= TDM 10100: Project 4 -- Fall 2022
Inroduction to R part III

All programing languages including xref:programming-languges:R:introduction[R]. have an order and pathway by which the flow of the actions are determined. This is called control flow. +
Simply put control flow is simply the order in which we want our instructions to be executed. We can set things to happen `*_if_*` a specific condition has been met. +
We can also preform an operation several times by using loops.  

.Insider Knowlege 
[%collapsible]
====
R typically has operations that are vectorized and there is little to no need to write loops. + 
R typically also uses indexing heavily instead of using an if statment.

* Sequential statments (one after another) i.e. + 
1. print line 45 + 
2. print line 15 +

**if/else statments**
 create an order of direction based on a logical condition. +

if statment example:
[source,r]
----
x <- 7
if (x > 0){
print ("Positive number")
}
----
else statment example:
[source,r]
----
x <- -10
if(x > 0){
print("Non-negative number")
} else {
print("Negative number")
}
----

There are mutliple types/condidtions of if/else statments such as +
* nested if/else statments
* else/if statments 
* to join two or more conditions into a single `if` statement you can use logical operators. +

**loops**- `R` provides three basic loops +
* for- can ve used to execute a group of statments repeatedly +
* while- evaluates an expression or a function while a condition is *TRUE* +
* repeat- repeats the same expression or a function until its "broken" due to a condition

====
**Context:** As we continue to become more familiar with `R` this project will introduce and help practice the concept of control flow, while continuing to reinforce concepts from the previous projects. 

**Scope:** r, data.frames, recycling, factors, if/else statments, and for loops. 

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].


Using the *f2022-s2023-r* kernel 
Lets first see all of the files that are in the CraigsList folder 
[source,r]
----
list.files(path = "/anvil/projects/tdm/data/craigslist", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)
----

After looking at several of the files we will go ahead and read in the data frame on the Vehicles
[source,r]
----
myDF <- read.csv("/anvil/projects/tdm/data/craigslist/vehicles.csv", stringsAsFactors = TRUE)
----

.Helpful Hints
[%collapsible]
====
Remember: +

* If we want to see the file size (aka how large) of the CSV. 
[source,r]
----
file.info("/anvil/projects/tdm/data/craigslist/vehicles.csv")$size
----

* You can also use 'file.info' to see other information about the file. 
====

=== ONE

It is so important that each time we look at data we start by becoming familiar with the data. +
In past projects we have looked at the head/tail along with the structure and the dimentions of the data. We want to continue this practice.

This dataset has 25 columns and we are unable to see it all without adusting the width, we can do this by
[source,r]
----
options(repr.matrix.max.cols=25, repr.matrix.max.rows=200)
----


.Helpful Hint
[%collapsible]
====
You can look at the first 6 rows (`head`) and the last 6 rows (`tail`). The structure (`str`) and/or the dimentions (`dim`) of the dataset. 
====

[loweralpha]
.. How many unique regions are there in total? Name 5 of the the different regions that are included in this dataset.
.. Create a new vector called `year`, then a new vector called 'newer' how many cars are manufactured in 2011 or newer?
.. Put `year` into chronological order, what is the oldest model available, the newest? 

.Helpful Hint
[%collapsible]
====
To sort and order a single vector you can use this code:
[source,r]
----
myDF[order(myDF)]
----
====
.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- Answers to the 3 questions above.
====

=== TWO
**if statements and for loops** +

_**if statments**_

An `*if*` statement is a decision making statement it is used to decide if a certian statement or several statments will be executed i.e. if A is `TRUE` then the statement is executed. If A is `FALSE` then nothing happens. +

.Helpful Hint
[%collapsible]
====
any() will return TRUE if _any_ element of the vector is TRUE
all() will return TRUE if _all_ of the elemnts of the vector are TRUE
====

[loweralpha]
.. Create a new column in your data.frame that is labeled `like_new` which indicates if the vehicle for sale has been labled as like new
.. Now we can use if/else statements to help catagorize the column `price`
... "cheap": cars under $1,500
... "average": cars between $1,501 and $3,000
... "expensive": cars over $3,001
.. How many cars are "expensive"?


.Helpful Hint
[%collapsible]
====
Remember to consider any 0 values and or `NA` values 

Using the  tideyverse package in R may help
[source,r]
----
library(tidyverse, warn.conflicts = FALSE)
----
====

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answer to the questions above.
====

=== THREE
_**vectoriztion**_

Most of R's functions are vectorized meaning that the function will be applied to all elements of a vector without needing to loop and apply to one element at a time. The most common way to access individual elements is thru the `[]` symbol. 

[loweralpha]
.. Using the `table()` function take a look at myDF$like_new
.. Now using the `cut()` function create the same catagories as in question TWO 
.. What is main difference between using a if statment vs vectoriation?

.Helpful Hint
[%collapsible]
====
[source,r]
----
cut(data.frame$columnname, breaks = c(1,2,3) , labels = c(a,b,c))
----
====


.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answer to the questions above.
====

==== FOUR
**Mapping**

.Insider Knowledge
[%collapsible]
====

====

[loweralpha]
.. 



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answers to the 3 questions above.
====






[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
====