= TDM 10100: Project 6 -- Fall 2023
Tapply, Tapply, Tapply

**Motivation:** We want to have fun and get used to the function `tapply`


Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].
 
== Dataset(s)

The following questions will use the following dataset(s):

- `/anvil/projects/tdm/data/olympics/athlete_events.csv`
- `/anvil/projects/tdm/data/death_records/DeathRecords.csv`

== Questions

=== Question 1 (1.5 pts)

(We do not need the tapply function for Question 1)

For this question, you will use a data frame read from the dataset `/anvil/projects/tdm/data/olympics/athlete_events.csv`, read the dataset into a data frame called `myDF`

[source, r]

myDF <- read.csv("/anvil/projects/tdm/data/olympics/athlete_events.csv", stringsAsFactors=TRUE )

[loweralpha]
.. Use `table` function to list all Games with occurrences in this data frame 
.. Use `table` function to list all countries participating in the Olympics in year 1980 (output should exclude country that did not have any athlete attended) 
.. Create a new subset data frame for athlete that attended olympic more than one time, make sure to include all records for the athletes from the original data frame 

[source, r]
athleteGamesDF <- myDF[duplicated(myDF$ID) | duplicated(myDF$ID, fromLast = TRUE)]

[TIP]
====
* use `duplicate` to identify duplicated elements, for example:
[source, r]
vec <- c(1, 2, 3, 2, 4, 3)
duplicated(vec)
duplicated(vec, fromLast = TRUE)

FALSE FALSE FALSE TRUE FALSE TRUE
FALSE TRUE TRUE FALSE FALSE FALSE

* please notice how to use an argument `fromLast`  to check from backward  
====


=== Question 2 (1.5 pts)

[loweralpha]
.. What is the average age of participants from different country?
.. What is Maximum Height by Sport? list top 5 of Height
.. Sort the outputs from previous questions for average age and maximum height in ascending and descending order respectively, display the first 5 outputs 

 
=== Question 3 (1 pt)

For this question, you will use a data frame read from dataset `/anvil/projects/tdm/data/death_records/DeathRecords.csv` 
[source, r]
myDF <- read.csv("/anvil/projects/tdm/data/death_records/DeathRecords.csv", stringsAsFactors = TRUE)

Review the data frame structure by str() function 
[source, r]
str(myDF)

[loweralpha]
.. What is the number of observations(rows) for this dataframe?
.. Change the column "MonthOfDeath" from numbers to months
.. How many people died in total on each month? Please display the numbers from January to December

[TIP]
====
You may factorize the month names with a specified level order:
[source, r]
month_order <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
myDF$MonthOfDeath <- factor(myDF$MonthOfDeath, levels = month_order)
====

=== Question 4 (2 pts)

[loweralpha]
.. What is the average age group by race at death? Use `race` column that has integer value and sort output in descending order
.. What is the average age group by race for females at death? and for males? 
 

=== Question 5 ( 2 pts)

[loweralpha]
.. Using the two data sets create two separate graphs or plots on the data that you find interesting (one graph or plot for each of the two data sets in this project).  Write 1-2 sentences on each one and why you found it interesting/what you noticed in the dataset. 

Project 06 Assignment Checklist
====
* Jupyter Lab notebook with your code and comments for the assignment
    ** `firstname-lastname-project06.ipynb`.

* Submit files through Gradescope
====
[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
