= TDM 10100: Project 2 -- 2023
Introduction to R part I

The R environment is a powerful tool to perform data analysis. R's language is often compared to Python. Both languages have their advantages and disadvantages, and both are worth learning. 

In this project we will dive in head-first and learn some of the basics while solving data-driven problems.


.5 basic types of data
[%collapsible]
====
    * Values like 1.5 are called numeric values, real numbers, decimal numbers, etc.
    * Values like 7 are called integers or whole numbers.
    * Values TRUE or FALSE are called logical values or Boolean values.
    * Texts consist of sequences of words (also called strings), and words consist of sequences of characters.
    * Values such as 3 + 2ifootnote:[https://stat.ethz.ch/R-manual/R-devel/library/base/html/complex.html] are called complex numbers.  We usually do not encounter these in The Data Mine.
====



[NOTE]
====
R and Python both have their advantages and disadvantages.  A key part of learning data science methods is to understand the situations in which R is a more helpful tool to use, or Python is a more helpful tool to use.  Both of them are good for their own purposes.  In a similar way, hammers and screwdrivers and drills and many other tools are useful for construction, but they all have their own individual purposes.

In addition, there are many other languages and tools, e.g., https://julialang.org/[Julia] and https://www.rust-lang.org/[Rust] and https://go.dev/[Go] and many other languages are emerging as relatively newer languages that each have their own advantages.
====

**Context:** In the last project we set the stage for the rest of the semester. We got some familiarity with our project templates, and modified and ran some examples. 

In this project, we will continue to use R within Jupyter Lab to solve problems. Soon, you will see how powerful R is and why it is often more effective than using spreadsheets as a tool for data analysis.

**Scope:** xref:programming-languages:R:introduction.adoc[R], xref:programming-languages:R:lists-and-vectors.adoc[vectors, lists], https://rspatial.org/intr/4-indexing.html[indexing]

.Learning Objectives
****
- Be aware of the different concepts and when to apply them; such as lists, vectors, factors, and data.frames 
- Be able to explain and demonstrate: positional, named, and logical indexing.
- Read and write basic (csv) data using R.
- Identify good and bad aspects of simple plots.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- `/anvil/projects/tdm/data/flights/subset/1995.csv`

== Questions

== Question 1
////
The data that we may be working with does not always come to us neat and cleanfootnote:["Raw data" vs "Clean data". Some datasets require "cleaning" such as removing duplicates, removing null values and disgarding irrelevent data].
////

It is important to get a good understanding of the dataset(s) with which you are working. This is the best first step to help solve any data-driven problems.

We are going to use the `read.csv` function to load our datasets into a dataframe.

To read data in R from a CSV file (.csv), you use the following command:

[source,r]

----
myDF <- read.csv("/anvil/projects/tdm/data/flights/subset/1995.csv")
----

////
----
myDF <- read.csv("/anvil/projects/tdm/data/flights/subset/1995.csv")

OR SHOULD WE GO WITH -

myDF <- read.csv("/anvil/projects/tdm/data/flights/subset/1995.csv", stringsAsFactors = TRUE) 

???
----
////

[NOTE]
====
Here `myDF` is a variable - a name that references our dataframe. In practice, you should always use names that are specific, descriptive, and meaningful.
====

////
.Dataset vs Dataframe
[%collapsible]
====
A *Dataset* is a distributed collection of data. Datasets can be thought of as one or more observations of one or more variables. For most datasets, each row is an observation and each column is a variable.

[NOTE]
====
There may be some datasets do not follow that convention.
====

A *Dataframe* is a Dataset organized into named columns. It is conceptually equivalent to a table in a relational database but with richer optimizations under the hood. A dataframe allows you use the tools of R to get insights about the data.
====
////


We want to use functions such as `head`, `tail`, `dim`, `summary`, `str`, `class`,  to get a better understanding of our dataframe. 

.Helpful Hints
[%collapsible]
====
- `head(myDF)` - Look at the head (or top) of the dataframe

- `tail(myDF)` - Look at the tail (or bottom) of the dataframe

- `class(myDF$Dest)` - Return the type of data in a column of the dataframe, for instance, in a column that stores the destination of flights (Dest)

- What do `dim`, `summary`, and `str` do?
====

*Answer the following questions:*

[loweralpha]
.. How many columns does this dataframe have?
.. How many rows does this dataframe have?
.. What type/s of data are in this dataframe (example: numerical values, and/or text strings, etc.)


.Items to submit*
====
- Code used to solve this problem.
- Output from running the code.
- The answers to the three questions above
====

== Question 2
Let's can create a new https://sudo-labs.github.io/r-data-science/vectors/[vector] containing all of the origin airports (i.e., the airports where the flights departed) from the column `myDF$Origin` of the data frame `myDF`. We can do this using the `$` operator. Documentation on the `$` operator can be found https://statisticsglobe.com/meaning-of-dollar-operator-in-r[here], and an example of how to use it is given below.

[source,r]
----
newVector <- myDF$ColumnName
----

////
[source,r]
----
# takes the selected information from the dataframe and puts it into a new vector called `myairports` 
myairports <- myDF$Origin
----
////

.Insider Knowledge
[%collapsible]
====
A vector is a simple way to store a sequence of data.  The data can be numeric data, logical data, textual data, etc.
====
//To assist with this question, please also see the end of the video from Question 1.

*Answer the following questions:*

[loweralpha]
.. What type of data is in the vector `myairports`?
.. The vector `myairports` contains all of the airports where flights departed from in 1995.  Print the first 250 of those airports. (Do not print all of the airports, because there are 5327435 such values!) How many of the first 250 flights departed from O'Hare?
.. How many flights departed from O'Hare altogether in 1995?


.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answers to the 3 questions above.
====

== Question 3
There are many different ways to access data after we load it, and each has its own use cases. One of the most common ways to access data is called _indexing_. Indexing is a way of selecting or excluding specific elements in our data. This is best shown through examples, some of which can be found https://rspatial.org/intr/4-indexing.html[here].

.Insider Knowledge
[%collapsible]
====
Accessing data can be done in many ways, one of those ways is called **_indexing_**. Typically we use brackets **[ ]** when indexing. By doing this we can select or even exclude specific elements. For example we can select a specific column and a certian range within the column. Some examples of symbols to help us select elements include: +
     * < less than +
     * > greater than +
     * <= less than or equal to +
     * >= greater than or equal to +
     * == is equal +
     * != is not equal +
It is also important to note that indexing in R begins at 1. (This means that the first row of the dataframe will be numbered starting at 1.)
====

.Helpful Hint
[%collapsible]
====
Many programming languages, such as https://www.python.org/[Python] and https://www.learn-c.org/[C], are called "zero-indexed". This means that they begin counting from '0' instead of '1'. Because R is not zero-indexed, we can count like humans normally do. However, this is a good thing to keep in mind going forward.
====

.Helpful Examples
[%collapsible]
====
[source,r]
----
# find data by their indices
myDF$Distance[row_index_start:row_index_end,] 

# creates a new vector with the specific info
mynewvector <- myDF$putcolumnnamehere

# all of the data from row 3
myDF[3,]

# all of the data in all of the rows, with columns between myfirstcolumn and mylastcolumn
myDF[,myfirstcolumn:mylastcolumn] 


# the first 250 values from column 17
head(myDF[,17], n=250)

# puts all variables that are less than 6 from the dataframe
longdistances = myDF$Distance[myDF$Distance > 2000]
----
====

[loweralpha]
.. How many flights departed from Indianapolis (`IND`) in 1995?  How many flights landed there?
.. Consider the flight data from row 894 the data frame.  What airport did it depart from?  Where did it arrive?
.. How many flights have a distance of less than 200 miles?


.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answers to the 3 questions above.
====

== Question 4
Oftentimes we will be dealing with enormous quantities of data, and it just isn't feasible to try and look at the data point-by-point in order to summarize the entire dataframe. When we find ourselves in a situation like this, the `table()` function is here to save the day! 

Take a look at https://www.geeksforgeeks.org/create-table-from-dataframe-in-r/[this link] for some examples of how to use the `table()` function in R. Once you have a good understanding of how it works, try and answer the three sub-questions below using the `table()` function. You may need to use some other basic R functions as well.

.Insider Knowledge
[%collapsible]
====
It is useful to use functions in R and see how they behave, and then to take a function of the result, and take a function of that result, etc.  For instance, it is common to summarize a vector in a table, and then sort the results, and then take the first few largest or smallest values. This is known as "nesting" functions, and is common throughout programming.

////
Remember also that R is a case-sensitive language.
[source,r]
----
table(myDF$Origin)   # summarizes how many flights departed from each airport
sort(table(myDF$Origin))   # sorts those results in numeric order
tail(sort(table(myDF$Origin)),n=10)  # finds the 10 most popular airports, according to the number of flights that departed from each airport.
----
////

====
[loweralpha]
.. Rank the airline companies (in the column `myDF$UniqueCarrier`) according to their popularity, (i.e. according to the number of flights on each airline).
.. Which are the three most popular airlines from 1995?
.. Now find the ten airplanes that had the most flights in 1995.  List them in order, from most popular to least popular.  Do you notice anything unusual about the results?

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answers to the 3 questions above.
====

== Question 5
Graphs are a very important tool in analyzing data. By visualizing our data in any of a number of ways, we can discover patterns that may not be as readily apparent by simply looking at tables. As such, they are a vital skill in all data scientists' skillset. 

In this question, we would like you to get comfortable with plotting in R. There are a number of built in tools for basic plotting in this language, including scatterplots, bar charts, histograms, and more! Do some research into a few basic types of plots in R and use your newfound knowledge to answer the below sub-questions.

.Helpful Hint
[%collapsible]
====
https://www.w3schools.com/r/r_graph_plot.asp[This website] has pages on several basic plotting functions in R that may help you complete the question.
====

////
.Insider Knowledge
[%collapsible]
====
A dot plot, also known as a dot chart, is similar to a bar chart or a scatter plot. In R, the categories are displayed along the vertical axis and the corresponding values are displayed according to the horizontal axis. +

We can assign groups a color to help differentiate while plotting a dot chart +

We can also plot a column that we find interesting as well to take a look at what the data might show us.
For example if we wanted to see if there was a difference in days of the week and number of flights, we would use `hist`.
[source,r]
----
mydays<- myDF$DayOfWeek
hist(mydays)
----

====


.Helpful Hints
[%collapsible]
====
[source,r]
----
mycities <- tail(sort(table(myDF$Origin)),n=10)
dotchart(mycities, pch = 21, bg = "green", pt.cex = 1.5)
----
====
////

[loweralpha]
.. Based on your exploration into this data so far, think of a question you have that a plot would answer well. Use one of the native R plots (without importing libraries) to create a plot to answer your question. Before making the plot, think about how many data points wil be displayed. If you try to display millions of dots, you might cause your Jupyter Lab session to freeze or crash. It is useful to think ahead and to consider how your plot might look before you accidentally try to display millions of dots.
.. In a few sentences, explain why you chose the plot you did. Describe any patterns you see in your plot and how those patterns answer the question you put forth in part (a). If you don't see any patterns or your question is left unanswered, put forth a possible explanation as to why that may be happening and what you could change about your approach to improve it.


.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The plot or dotchart and your commentary about what you created and what you observed.
====


[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====