= TDM 10100: Project 6 -- Fall 2023
Tapply, Tapply, Tapply

**Motivation:** We want to have fun and get used to the function `tapply`


Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].
 
== Dataset(s)

The following questions will use the following dataset(s):

- `/anvil/projects/tdm/data/olympics/athlete_events.csv`
- `/anvil/projects/tdm/data/death_records/DeathRecords.csv`

== Questions

=== Question 1 (1.5 pts)

(We do not need the tapply function for Question 1)

For this question, please read the dataset

`/anvil/projects/tdm/data/olympics/athlete_events.csv`

into a data frame called `myDF` as follows:

[source, r]

myDF <- read.csv("/anvil/projects/tdm/data/olympics/athlete_events.csv", stringsAsFactors=TRUE )

[loweralpha]
.. Use the `table` function to list all Games with occurrences in this data frame 
.. Use the `table` function to list all countries participating in the Olympics during the year 1980.  (The output should exclude all countries that did not have any athletes in 1980.)
.. Use the `subset` function to create a new data frame containing data related to athletes that attended the Olympics more than one time.  (Use the original data frame `myDF` as a starting point; in other words, do not restrict yourself to the year 1980.  Problems 1a and 1b and 1c are independent of each other.)

[source, r]
athleteGamesDF <- myDF[duplicated(myDF$ID) | duplicated(myDF$ID, fromLast = TRUE)]

[TIP]
====
* use `duplicate` to identify duplicated elements, for example, with this vector:
[source, r]
vec <- c(2, 5, 1, 1, 5, 5, 6, 6, 1, 6, 3, 4)

If we run this `duplicated` command:

[source, r]
duplicated(vec)

Then we get this output:

[source, r]
FALSE FALSE FALSE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE FALSE

====


=== Question 2 (1.5 pts)

[loweralpha]
.. What is the average age of participants from different country?
.. What is Maximum Height by Sport? list top 5 of Height
.. Sort the outputs from previous questions for average age and maximum height in ascending and descending order respectively, display the first 5 outputs 

 
=== Question 3 (1 pt)

For this question, you will use a data frame read from dataset `/anvil/projects/tdm/data/death_records/DeathRecords.csv` 
[source, r]
myDF <- read.csv("/anvil/projects/tdm/data/death_records/DeathRecords.csv", stringsAsFactors = TRUE)

Review the data frame structure by str() function 
[source, r]
str(myDF)

[loweralpha]
.. What is the number of observations(rows) for this dataframe?
.. Change the column "MonthOfDeath" from numbers to months
.. How many people died in total on each month? Please display the numbers from January to December

[TIP]
====
You may factorize the month names with a specified level order:
[source, r]
month_order <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
myDF$MonthOfDeath <- factor(myDF$MonthOfDeath, levels = month_order)
====

=== Question 4 (2 pts)

[loweralpha]
.. What is the average age group by race at death? Use `race` column that has integer value and sort output in descending order
.. What is the average age group by race for females at death? and for males? 
 

=== Question 5 ( 2 pts)

[loweralpha]
.. Using the two data sets create two separate graphs or plots on the data that you find interesting (one graph or plot for each of the two data sets in this project).  Write 1-2 sentences on each one and why you found it interesting/what you noticed in the dataset. 

Project 06 Assignment Checklist
====
* Jupyter Lab notebook with your code and comments for the assignment
    ** `firstname-lastname-project06.ipynb`.

* Submit files through Gradescope
====
[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
