= TDM 10100: Project 6 -- Fall 2022
Tapply, Tapply, Tapply

**Motivation:** We want to have fun and get used to the function `tapply`


Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].
 
== Dataset(s)

The following questions will use the following dataset(s):

- `/anvil/projects/tdm/data/olympics/athlete_events.csv`
- `/anvil/projects/tdm/data/death_records/DeathRecords.csv`

== Questions

=== ONE

Read the dataset `/anvil/projects/tdm/data/olympics/athlete_events.csv`, into a data.frame called `eventsDF`. 

[loweralpha]
.. What are the years included in this data.frame?
.. What are the different countries particpating in the Olympics?
.. How many times is each country represented?


.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- Answers to the code above.
====

=== TWO

[loweralpha]
.. What is the average height of particpants from each country?
.. What is the most common age of athletes from each country?
.. What is the sum of the weight of all participants from each country?

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- Answers to the code above
====

=== THREE
Read the dataset `/anvil/projects/tdm/data/death_records/DeathRecords.csv` into a data.frame called 'deathrecordsDF'

[loweralpha]
.. What are the column names in this dataframe?
.. Change the column "DayOfWeekOfDeath" from numbers to weekdays
.. How many people died in total on each day of the week?

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- Answers to the questions above
====

=== FOUR

[loweralpha]
.. What is the average age of Males vs Females at death?
.. What the sum of married, divoriced, widowed, single Males?
.. What is the number of deaths by year?
.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- Answers to the question above
====

=== FIVE

[loweralpha]
.. Using the two data sets create two separate graphs or plots on the data that you find interesting and write 1-2 sentences on each one and why you found it interesting/what you noticed in the dataset. 

Read about https://plato.stanford.edu/entries/paradox-simpson/[Simpsons Paradox], would you be able to find a Simpson's Paradox in either or both of these datasets?

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====


[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
====
