= TDM 10100: Project 3 -- Fall 2022
Inroduction to R part II

**Motivation:** `data.frames` are the primary data structure you will work with when using R. It is important to understand how to insert, retrieve, and update data in a `data.frame`. 

**Context:** In Project 2 we ran our first R code, learned about vectors and indexing, and explored some basic functions in R. In this project, we will continue to enforce what we've already learned and learn more about how dataframes, formally called `data.frame`, work in R.

**Scope:** r, data.frames, recycling, factors

.Learning Objectives
****
- Explain what "recycling" is in R and predict behavior of provided statements.
- Explain and demonstrate how R handles missing data: NA, NaN, NULL, etc.
- Demonstrate the ability to use the following functions to solve data-driven problem(s): mean, var, table, cut, paste, rep, seq, sort, order,  length, unique, etc.
- Read and write basic (csv) data.
- Explain and demonstrate: positional, named, and logical indexing.
- List the differences between lists, vectors, factors, and data.frames, and when to use each.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- `/anvil/projects/tdm/data/craigslist/vehicles.csv`

== Setting Up
First, let's take a look at all of the data available to students. In order to do this, we are going to use a new function as listed below to list all of the files in the craigslist folder.

Let's run the below command using the *seminar-r* kernel to view all the files in the folder.

[source,r]
----
list.files("/anvil/projects/tdm/data/craigslist")
----

As you can see, we have two different files worth of information from Craigslist.
For this project, we are interested in looking at the `vehicles.csv` file

Before we read in the data, we should check the size of the file to get an idea of how big it is. This is important because if the file is too large, we may need more cores for our project or else our core will 'die'.

We can check the size of our file (in bytes) using the following command.
[source,r]
----
file.info("/anvil/projects/tdm/data/craigslist/vehicles.csv")$size
----

[TIP]
====
You can also use `file.info` to see other information about the file. 

*size*- double: File size in bytes. +
isdir- logical: Is the file a directory? +
*mode*- integer of class "octmode". The file permissions, printed in octal, for example 644. +
*mtime, ctime, atime*- integer of class "POSIXct": file modification, ‘last status change’ and last access times. +
*uid*- integer: the user ID of the file's owner. +
*gid*- integer: the group ID of the file's group. +
*uname*- character: uid interpreted as a user name. +
*grname* - character: gid interpreted as a group name. +
(Unknown user and group names will be NA.)
====

Now that we have made sure our file isn't too big (1.44 GB), let's read it into a dataframe the same way that we have done in the previous two projects, and get started with our questions
[source,r]
----
myDF <- read.csv("/anvil/projects/tdm/data/craigslist/vehicles.csv")
----

== Questions

=== Question 1 (1 pt)
[upperalpha]
.. How many rows and columns does our dataframe have?
.. What type/s of data are in this dataframe (example: numerical values, and/or text strings, etc.)
.. 1-2 sentences describing what our data contains as a whole.

As we stressed in Project 2, familiarizing yourself with the data you are going to work with is an extremely important first step. For this question, we want to figure out how many rows and columns are in our data along with what the types of data in our dataframe are. The hint below contains all of the functions that we need to solve this problem, but we also covered these functions in detail in Project 2, so feel free to reference it if you want more information.

When answering sub-question C., consider talking about where the data appears to be taken from, what the data contains, and any important details that immediately stand out to you about the data.

[TIP]
====
The `head()`, `dim()`, and `str()` functions could be helpful in answering this question.
====

.Items to submit
====
- The number of rows and columns in our dataframe, in a markdown cell.
- The types of data in our dataframe, in a markdown cell.
- 1-2 sentences summarizing our data.
====

=== Question 2 (1 pt)
[upperalpha]
.. Print the number of NA or NULL values in the *'year'* column of `myDF`, and the percentage of the total number of rows in `myDF` that this represents.
.. Create a new dataframe with only the rows in myDF that have a defined year (non NA or NULL values), and print the head.
.. Create a new dataframe with only the rows in myDF that *are* missing data in the *'year'* column, and print the head.

Now that we have a better understanding of the general structure and contents of our data, lets focus on some specific patterns in our data that may make analysis more challenging.

Often, one of these patterns is missing data. This can come in many forms, such as NULL, NA, or simply a blank space in one of our dataframes cells. When performing data analysis, it is important to consider missing data and decide how to handle it appropriately.

In this question, we will look at filtering out rows with missing data. The `R` function `na.omit()` will remove rows with missing data from what is passed into it as an argument. As an example, if we wanted to create a new dataframe with all of the rows that have missing data in the `price` column removed, we could do the following:

[source,r]
----
newDF <- na.omit(myDF$price)
----

Let's also determine how much missing data we are omitting, so that we have an idea of how much of the data we are left working with after applying this method of handling missing data. This can be done on the `price` column, for example, like so:

[source,r]
----
sum(is.na(myDF$price))
----

Now that we have a better understanding of content and structure of our data, and we have begun to deal with missing data, we can continue our analyses in the next few questions.

[NOTE]
====
`na.omit` and `na.exclude` returns objects with the observations removed if they contain any missing values. As well as performs calculations by considering the NA values but does not include them in the calculation. +
`na.rm` first [.underline]#removes the NA values and then# does the calculation. +
`na.pass` returns the object unchanged +
It is also possible to use the `subset` function and the `is.na` function.
====

.Items to submit
====
- The number of NA or NULL values in the `year` column of `myDF` and the percentage of the total number of rows in `myDF` that this represents, in a markdown cell.
- A dataframe of only the rows in myDF that have a defined year (non NA or NULL values), and the head of that dataframe.
- A dataframe of only the rows in myDF that are missing year data, and the head of that dataframe.
====

=== Question 3 (2 pts)
[IMPORTANT]
====
Use the `myDF` data.frame for this question.
====

[upperalpha]
.. Print the average price of a vehicle by year for the last 20 years.
.. Calculate the percentage of data that is NA in our price and year columns.
.. Find which year of vehicle appears most frequently in our table, and how frequently it occurs.


[TIP]
====
Using the `aggregate` function is one possible way to solve this problem. An example of finding the mean price for each type of car is shown here:

[source,r]
----
aggregate(price ~ type, data = myDF, FUN = mean)
----
====

[TIP]
====
Finding the most frequent vallue in our data can be done using `table`, which we have talked about previously, in conjunction with the `which.max` function. An example of finding the most frequent type of car is shown here:

[source,r]
----
which.max(table(myDF$type))
----
====

.Items to submit
====
- The average price of each year of vehicle for the last 20 years, in a markdown cell.
- The percent of NA data in our two columns of interest.
- The most frequent year in our data, and how frequently it occured.
====

==== Question 4 (2 pts)
[upperalpha]
.. Create a new vector called `noNAprices` that contains all of the prices from `myDF` that are not NA.
.. Create a new vector called `halfprice` that contains the first half of the prices from `noNAprices`. (it should be half the length of `noNAprices`)
.. Find the difference between the lengths of `myDF$price` and `noNAprices`.
.. Create a new vector called `myprices` by adding together the two vectors we just created. What is the length of that new vector `myhours`?
.. What happened in row 213441? Why?

So far, we have been using functions without really thinking about the operations they are performing, and a lot of special magic has been going on under the hood to make everything work. For example, in the last question when we asked you to compute averages by year, it is possible that the "year" column and the "price" column are different lengths. 

In this case, R automatically performs an action called _recycling_. When you are attempting to perform operations like addition, subtraction, or others on two vectors of unequal length, the shorter vector will be repeated as long as the operation is completing on the longer vector. 

[TIP]
====
Creating a vector that is half of another vector is simple, and you have already learned how to do it. Consider this: if we know the length of a vector, and we can index into it, how can we use that information to create a new vector that is half the length of the original vector?
====


.Items to submit
====
- Three new vectors, `noNAprices`, `halfprice`, and `myprices`, as described above.
- The difference between the lengths of `myDF$price` and `noNAprices`.
- A sentence or two describing what happened in row 213441, and why. (Hint: _recycling_)
====


==== Question 5 (2 pts)
.. In question 3, we found the average price of vehicles by year. Choose at least two different plot types in R and create two plots of average vehicle price by year.
.. Write 3-5 sentences detailing any patterns present in the data along with your personal observations. (i.e. shape, outliers, etc.)

[NOTE]
====
Remember, all plots should have a title and appropriate axis labels. Axes should also be scaled appropriately. If a plot is incoherent, you quite possibly will lose points.
====

.Items to submit
====
- 2 different plots of average price of vehicle by year.
- A 3-5 sentence explanation of any patterns present in the data along with your personal observations.
====

=== Submitting your Work
Nice work, you've finished Project 3! Make sure that all of the below files are included in your submission, and feel free to come to seminar, post on Piazza, or visit some office hours if you have any further questions.

.Items to submit
====
- `firstname-lastname-project01.ipynb`.
- `firstname-lastname-project01.R`.
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output, when in fact it does not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/current-projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or it does not render properly in gradescope. Please ask a TA if you need help with this.
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====