= TDM 10100: Project 4 -- Fall 2023
Introduction to R part III


Many data science tools including xref:programming-languges:R:introduction[R] have powerful ways to index data.

[NOTE]
====
R typically has operations that are vectorized and there is little to no need to write loops. + 
R typically also uses indexing instead of using an if statement.

* Sequential statements (one after another) i.e. + 
1. print line 45 + 
2. print line 15 +

**if/else statements**
 create an order of direction based on a logical condition. +

if statement example:
[source,r]
----
x <- 7
if (x > 0){
print ("Positive number")
}
----
else statement example:
[source,r]
----
x <- -10
if(x >= 0){
print("Non-negative number")
} else {
print("Negative number")
}
----
In `R`, we can classify many numbers all at once:
[source,r]
----
x <- c(-10,3,1,-6,19,-3,12,-1)
mysigns <- rep("Non-negative number", times=8)
mysigns[x < 0] <- "Negative number"
mysigns
----

====
**Context:** As we continue to become more familiar with `R` this project will help reinforce the many ways of indexing data in `R`. 

**Scope:** R, data.frames, indexing. 

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].


Using the *seminar-r* kernel 
Lets first see all of the files that are in the `craigslist` folder 
[source,r]
----
list.files("/anvil/projects/tdm/data/craigslist")
----

After looking at several of the files we will go ahead and read in the data frame on the Vehicles
[source,r]
----
myDF <- read.csv("/anvil/projects/tdm/data/craigslist/vehicles.csv", stringsAsFactors = TRUE)
----

[NOTE]

====
Remember: +

* If we want to see the file size (aka how large) of the CSV. 
[source,r]
----
file.info("/anvil/projects/tdm/data/craigslist/vehicles.csv")$size
----

* You can also use 'file.info' to see other information about the file. 
====

== Questions

=== Question 1 (1.5 pts)
[upperalpha]
.. How many unique states are there in total? Name 5 of the different states that are included in this dataset.
.. How many cars's price is equal or higher than $ 2000 ?
.. In what year was the oldest model manufactured? In what year was the most recent model manufactured? In which year were the most cars manufactured?

[NOTE]
====
You can look at the first 6 rows (`head`), the last 6 rows (`tail`), the structure (`str`), and/or the dimensions (`dim`) of the dataset. 
====

[NOTE]
====
To sort and order a single vector you can use this code:
[source,r]
----
head(myDF$year[order(myDF$year)])
----
You can also use the `sort` function, as demonstrated in earlier projects.
====

It is so important that, each time we look at data, we start by becoming familiar with the data. +
In past projects we have looked at the head/tail along with the structure and the dimensions of the data. We want to continue this practice.

This dataset has 25 columns, and we are unable to see it all without adjusting the width.  We can do this by
[source,r]
----
options(repr.matrix.max.cols=25, repr.matrix.max.rows=200)
----
and we also remember (from the previous project) that we can set the output in `R` to look more natural this way:
[source,r]
----
options(jupyter.rich_display = F)
----

=== Question 2 (1.5 pts)
[upperalpha]
.. Create a new column in your data.frame that is labeled fairflag which indicates if the vehicle for sale's condition has been labeled as fair. In other words, the column fairflag should be TRUE if the vehicle on that row is fair, and FALSE otherwise.
.. Create a new column called `pricecategory` that is
... `cheap` for vehicles less than or equal to $2,000
... `average` for vehicles strictly more than $2,000 but less than or equal to $12,000
... `expensive` for vehicles strictly more than $12,000
.. How many cars are there in each of these three `pricecategories` ?

[NOTE]
====
Remember to consider any 0 values and or `NA` values 

====

=== Question 3 (1.5 pts)
[upperalpha]
.. Using the table() function, and the column myDF$fairflag, identify how many vehicles are in fair condition and how many vehicles are not in fair condition.
.. Now using the `cut` function and appropriate `breaks`, create a new column called `newpricecategory`.  Verify that this column is identical to the previously created `pricecategory` column, created in question TWO.
.. Make another column called `odometerage`, which has values `new` or `middle age` or `old`, according to whether the odometer is (respectively): less than or equal to 50000; strictly greater than 50000 and less than or equal to 100000; or strictly greater than 100000.  How many cars are in each of these categories?

_**vectorization**_

Most of R's functions are vectorized, which means that the function will be applied to all elements of a vector, without needing to loop through the elements one at a time. The most common way to access individual elements is by using the `[]` symbol for indexing. 

[NOTE]
====
[source,r]
----
cut(myvector, breaks = c(10,50,200) , labels = c(a,b,c))
----
====


=== Question 4 (1.5 pts)
[arabic]
.. Extract all of the data for texas into a data.frame called myTx
.. Identify the most popular state from myDF, and extract all of the data from that state into a data.frame called popularState.
.. Create a third data.frame with the data from a state of your choice
**Preparing for Mapping**

**Preparing for Mapping**


=== Question 5 (2 pts)
[upperalpha]
.. Using the R package `leaflet`, make 3 maps of the USA, namely, one map for the data in each of the `data.frames` from question FOUR.

**Mapping**


=== Submitting your Work
Well done, you've finished Project 4! Make sure that all of the below files are included in your submission, and feel free to come to seminar, post on Piazza, or visit some office hours if you have any further questions.

Project 4 Assignment Checklist
====
- Code used to solve quesiton 1 to 5
- Output from running th code
- Copy thes code and outputs to a new Python File and a new R File respectively
    * `firstname-lastname-project04.ipynb`.
    * `firstname-lastname-project04.R`.
- submit files through gradescope
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output, when in fact it does not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/current-projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or it does not render properly in gradescope. Please ask a TA if you need help with this.
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
