= TDM 10100: Project 8 -- 2022

**Motivation:** Functions are an important part of writing effecient code. +
Functions allow us to repeat and reuse code. If you find you using a set of coding steps over and over, a function may be a good way to reduce your lines of code!

**Context:** We've been learning about and using functions these last few weeks. +
To learn how to write your own functions we need to learn some of the terminology and components.  

**Scope:** r, functions

.Learning Objectives
****
- Gain proficiency using split, merge, and subset.
- Demonstrate the ability to use the following functions to solve data-driven problem(s): mean, var, table, cut, paste, rep, seq, sort, order, length, unique, etc.
- Read and write basic (csv) data.
- Comprehend what a function is, and the components of a function in R.
****

== Dataset(s)

We will use the same dataset(s) as last week:
/anvil/projects/tdm/data/movies_and_tv/titles.csv
/anvil/projects/tdm/data/movies_and_tv/episodes.csv
/anvil/projects/tdm/data/movies_and_tv/people.csv
/anvil/projects/tdm/data/movies_and_tv/ratings.csv


.Helpful Hints
[%collapsible]
====
`fread`- is a fast and efficient way to read in data.

[source,r]
----
library(data.table)

titles <- data.frame(fread("/anvil/projects/tdm/data/movies_and_tv/titles.csv"))
episodes <- data.frame(fread("/anvil/projects/tdm/data/movies_and_tv/episodes.csv"))
people <- data.frame(fread("/anvil/projects/tdm/data/movies_and_tv/people.csv"))
ratings <- data.frame(fread("/anvil/projects/tdm/data/movies_and_tv/ratings.csv"))
----
====


== Questions

Writing our own function to make a repetitive operation easier by turning it into a single command. +

Take care to name the function somthing concise but meaningful so that others can understand what the function can be understood by other users. +

Functions can also be called formal arguments. 

.Insider Knowledge
[%collapsible]
====
A function is an object that contains multiple interrelated statments put together in a predefined order when called(run). +

Functions can be built-in or created by the user (user-defined). +

.Some examples of built in functions are: 

* min(), max(), mean(), median()
* print()
* head()

====

.Helpful Hints
[%collapsible]
====
Syntax of a function
[source, R]
----
what_you_name_the_function <- function (parameters) {
  statement(s) that are executed when the function runs
}
----
====

=== ONE
To gain a better insight into our data lets make two simple plots
- A grouped bar chart 
- A line plot 
What information are you gaining from either of these graphs?

=== TWO
For practice, now that you have a basic understanding of how to make a function, we will use that knowlege in our dataset(s)

Here are pieces of a function we will use on this dataset; put them in the correct order +

* results <- merge(ratings, titles, by.x = "title_id", by.y = "title_id")
* {}
* function(titles_df, ratings_df,ratings_of_at_least)
* return(results)
* results <- results[results$type == "movie" & results$rating >= ratings_of_at_least,]
* find_movie_with_at_least_rating <-

=== THREE
Take the above function and add comments explaining what the function does at each step



=== FOUR
Now that you know what the function does go ahead and create a new vector named `my_selection` and use the function to find all ratings that are at least 5.0 or higher. 
How many movies in total are there that is above that limit?
Change the limits in the function from at least to lower than 5.0
How many movies in total are there that fall under 5.0


=== FIVE
Pick a genre 
Now create a function that finds the movie that has the most votes per genre



Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].



[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:book:projects:submissions.adoc[submission guidelines] before submitting your project.
====