= TDM 10100: Project 7 -- 2023

**Motivation:** A couple of bread-and-butter functions that are a part of the base R are: `subset`, and `merge`. `subset` provides a more natural way to filter and select data from a data.frame. `merge` brings the principals of combining data that SQL uses, to R.

**Context:** We've been getting comfortable working with data in within the R environment. Now we are going to expand our tool set with these useful functions, all the while gaining experience and practice wrangling data!

**Scope:** r, subset, merge, tapply

.Learning Objectives
****
- Gain proficiency using split, merge, and subset.
- Demonstrate the ability to use the following functions to solve data-driven problem(s): mean, var, table, cut, paste, rep, seq, sort, order, length, unique, etc.
- Read and write basic (csv) data.
- Explain and demonstrate: positional, named, and logical indexing.
- Demonstrate how to use tapply to solve data-driven problems.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- `/anvil/projects/tdm/data/icecream/combined/products.csv` 
- `/anvil/projects/tdm/data/icecream/combined`
- `/anvil/projects/tdm/data/movies_and_tv/titles.csv``
- `/anvil/projects/tdm/data/movies_and_tv/episodes.csv`
- `/anvil/projects/tdm/data/movies_and_tv/ratings.csv`
== Questions

[IMPORTANT]
====
Please select 6000 memory when launching Jupyter for this project.
====

Data can come in a lot of different formats and from a lot of different locations. It is not uncommon to have one or more files that need to be combined together before analysis is performed. `merge` is a popular function in most data wrangling libraries. It is extremely similar and essentially equivalent to a `JOIN` in SQL.

[NOTE]
====
Read the data in using the following code. `fread` is a _very_ fast and efficient way to read in data.

[source,r]
----
library(data.table)

products <- fread("/anvil/projects/tdm/data/icecream/combined/products.csv")
reviews <- fread("/anvil/projects/tdm/data/icecream/combined/reviews.csv")
titles <- data.frame(fread("/anvil/projects/tdm/data/movies_and_tv/titles.csv"))
episodes <- data.frame(fread("/anvil/projects/tdm/data/movies_and_tv/episodes.csv"))
ratings <- data.frame(fread("/anvil/projects/tdm/data/movies_and_tv/ratings.csv"))

====
=== Question 1 (1 pt)

We will use "products" data.frame for this question
[loweralpha]
.. What are all the different ingredients in the first record of `products`?
.. Look at the `rating` column and the `ingredients` column. Please find out the distribution of ratings for the ice cream which ingredients include "GUAR GUM", display the result in descending order


=== Question 2 (1 pt)
We will use "products" and "reviews" data.frame for this question
[loweralpha]

.. Use the `brand` and `key` columns from both the `products` data.frame and `reviews` data.frame to merge the two data frames.

We want to end up with a new data.frame that contains the product details and their associated reviews. Use the `merge` function to accomplish this.


[TIP]
====
* The `merge` function in `R` allows two data frames to be combined by common columns. This function allows the user to combine data similar to the way `SQL` would using `JOIN`s. https://www.codeproject.com/articles/33052/visual-representation-of-sql-joins[Visual representation of SQL Joins] 
* This is also a really great https://www.datasciencemadesimple.com/join-in-r-merge-in-r/[explanation of merge in `R`].
====
=== Question 3 (3 pts)

We will use "episodes", "titles" and "ratings" data.frame for questions 3 - 5
[loweralpha]
.. Use `merge` (a few times) to create a new data.frame that contains at least the following information for **only** the show called "The Green Archer". "The Green Archer" (the show itself) has a `title_id` of tt0032557. Each episode of The Green Archer, has its own `title_id` which contains the information for the specific episode as well.

- The `primary_title` of the **episode** -- call it `episode_title`.
- The `primary_title` of the **show itself** -- call it `show_title`.
- The `rating` of the show itself -- call it `show_rating`.
- The `rating` of the episode -- call it `episode_rating`.

[TIP]
====
Start by getting a subset of the `episodes` table that contains only information for the show The Green Archer. That way, we aren't working with as much data.
====

Show the top 5 rows of your final data.frame that contain the top 5 rated episodes.

=== Question 4 (1 pt)

[loweralpha]
.. Use regular old indexing to find all episodes of "The Green Archer" with an `episode_rating` less than 8 and `season_number` of exactly 1.

.. Repeat the process, but this time use the `subset` function instead.


=== Question 5 (2 pts)

`subset` is a sometimes useful function that allows you to index data.frame's in a less verbose manner. Read https://the-examples-book.com/programming-languages/R/subset[this]. 

While it maybe appears to be a clean way to subset data, I'd suggest avoiding it over explicit long-form indexing. Read http://adv-r.had.co.nz/Computing-on-the-language.html[this fantastic article by Dr. Hadley Wickham on non-standard evaluation]. Take for example, the following (a bit contrived) example using the dataframe we got in question (3).

[source,r]
----
season_number = 6
subset(result_r, episode_rating < 8 & season_number == season_number)
----
[loweralpha]
.. Read that provided article and do your best to explain _why_ `subset` gets a different result than our example that uses regular indexing.

Project 07 Assignment Checklist
====
* Jupyter Lab notebook with your code,comments and output for the assignment
    ** `firstname-lastname-project07.ipynb`.

* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
