= TDM 10100: Project 13 -- 2023

**Motivation:** This semester we took a deep dive into `R` and it's packages. Lets take a second to pat ourselves on the back for surviving a long semester and review what we have learned! 

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- /anvil/projects/tdm/data/beer/beers.csv

== Questions

=== Question 1 (2 pts)

Read in the dataset and into a data.frame called `beer`
[loweralpha]
. What is the file size, how many rows, columns and type of data?
. What is the average score for a `stout`? (consider a stout any named beer from the column `name` with the word `stout` in it)
. How many `Pale Ale's` are on this list? (consider a stout any named beer from the column `name` with the word `pale` and `ale` in it)



=== Question 2 (2 pts)

. Plot or Graph all the beers that are available in the summer and their ratings.
 

=== Question 3 (2 pts)

. Create a plot of the average rating of beer by country.

 

=== Question 4 (2 pts)

. Do `limited` runs of beer have a greater median rating than all others?
(consider limited to be any beer that has the word `Limited` in the `availablity` column) 

. Use the `unique` function to investigate the availablity column. Why are there different labels that are technically the same?


Project 12 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project12.ipynb` 
* R code and comments for the assignment
    ** `firstname-lastname-project12.R`.
* Submit files through Gradescope
====
[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
