= TDM 10100: Project 8 -- 2023

**Motivation:** Functions are an important part of writing efficient code. +
Functions allow us to repeat and reuse code. If you find you using a set of coding steps over and over, a function may be a good way to reduce your lines of code!

**Context:** We've been learning about and using functions these last few weeks. +
To learn how to write your own functions we need to learn some of the terminology and components.  

**Scope:** r, functions

.Learning Objectives
****
- Gain proficiency using split, merge, and subset.
- Demonstrate the ability to use the following functions to solve data-driven problem(s): mean, var, table, cut, paste, rep, seq, sort, order, length, unique, etc.
- Read and write basic (csv) data.
- Comprehend what a function is, and the components of a function in R.
****

== Dataset(s)

We will use the same dataset(s) as last week:

- `/anvil/projects/tdm/data/icecream/combined/products.csv`
- `/anvil/projects/tdm/data/icecream/combined/reviews.csv` 


[IMPORTANT]
====
Please choose 3 cores when launching Jupyter for this project.
====

[NOTE]
====
`fread`- is a fast and efficient way to read in data.

[source,r]
----
library(data.table)

products <- fread("/anvil/projects/tdm/data/icecream/combined/products.csv")
reviews <- fread("/anvil/projects/tdm/data/icecream/combined/reviews.csv") 
----
====
[WARNING]
====
Please remember to run the `library(data.table)` line, before you use the `fread` function.  Otherwise, you will get an error in a pink box in JupyterLab like this:

Error in fread: could not find function "fread"
====

== Questions

Writing our own function to make a repetitive operation easier by turning it into a single command. +

Take care to name the function something concise but meaningful so that others can understand what the function can be understood by other users. +

Function parameters can also be called formal arguments. 

[NOTE]
====
A function is an object that contains multiple interrelated statements put together in a predefined order when called(run). +

Functions can be built-in or created by the user (user-defined). +

.Some examples of built in functions are: 

* min(), max(), mean(), median()
* print()
* head()


Syntax of a function
[source, R]
----
what_you_name_the_function <- function (parameters) {
  statement(s) that are executed when the function runs
  the last line of the function is the returned value
}
----
====

=== Question 1 (2 pts)

[loweralpha]

To gain a better insight into our data, let's make two simple plots,the following are two examples. You can create your own plots.   
.. In project 07, you have found out the different ingredients for the first record in `products data frame. We may get all ingredients from the datasets and find top 10 most frequently used ingredients in `products`,to create a bar chart for the distribution 

.. A line plot to visualize the distribution of reviews by their star ratings 
.. What information are you gaining from these graphs?
[TIP]
====
`table` can be useful to get the distribution
This is a good website for bar plot examples  https://www.statmethods.net/graphs/bar.html
This is a good website for line plot examples http://www.sthda.com/english/wiki/line-plots-r-base-graphs[see an example here]
====

=== Question 2 (2 pts)
 
For practice, now that you have a basic understanding of how to make a function, we will use that knowledge, applied to our dataset.

Here are pieces of a function we will use on this dataset; products, reviews and products' rating put them in the correct order +
[source,r]
* merge_results <- merge(products_df, reviews_df, by="key")
* }
* function(products_df, reviews_df, rating)
* return(products_reviews_results)
* {
* products_reviews_results <- merge_results[merge_results$rating >= rating, ]
* products_reviews_by_rating <-


=== Question 3 (1 pt)
 

Take the above function and add comments explaining what the function does at each step.

 

=== Question 4 (1 pt)

[source,r]
----
my_selection <- products_reviews_by_rating(products, reviews, 4.5)
----

Using the code above answer these questions.

[loweralpha]
.. How many products in total are there that have product's rating at least 4.5
.. Are there any common ingredients in the products with ratings greater than 4.5? list 5 top most frequently used ingredients

[TIP]
====
The function merged two data sets products and reviews,both of them have `ingredients` column, use `ingredients` column from products by `ingredients.x`
====
=== Questions 5 (2 pts)

Now create a function that takes a ingredients as the input(s) and finds either
[loweralpha]
.. the products that contain the ingredient  
.. the product(s) that contain the ingredient and have the highest product's rating

(You just need to create the function for one of them  )

Project 08 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project08.ipynb`

* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
