= TDM 10100: Project 3 -- Fall 2022
Inroduction to R part II

**Motivation:** `data.frames` are the primary data structure you will work with when using R. It is important to understand how to insert, retrieve, and update data in a `data.frame`. 

**Context:** In Project 2 we ran our first R code, learned about vectors and indexing, and explored some basic functions in R. In this project, we will continue to enforce what we've already learned and learn more about how dataframes, formally called `data.frame`, work in R.

**Scope:** r, data.frames, recycling, factors

.Learning Objectives
****
- Explain what "recycling" is in R and predict behavior of provided statements.
- Explain and demonstrate how R handles missing data: NA, NaN, NULL, etc.
- Demonstrate the ability to use the following functions to solve data-driven problem(s): mean, var, table, cut, paste, rep, seq, sort, order,  length, unique, etc.
- Read and write basic (csv) data.
- Explain and demonstrate: positional, named, and logical indexing.
- List the differences between lists, vectors, factors, and data.frames, and when to use each.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- `/anvil/projects/tdm/data/flights/subset/1995.csv`

== Setting Up
First, let's take a look at all of the data available to students. In order to do this, we are going to use a new function as listed below to list all of the files in the craigslist folder.

Let's run the below command using the *seminar-r* kernel to view all the files in the folder.

[source,r]
----
list.files("/anvil/projects/tdm/data/craigslist/vehicles.csv")
----

As you can see, we have quite a few different files worth of information from Craigslist.
For this project, we are interested in looking at the `vehicles.csv` file

Before we read in the data, we should check the size of the file to get an idea of how big it is. This is important because if the file is too large, we may need more cores for our project or else our core will die.

We can check the size of our file (in bytes) using the following command.
[source,r]
----
file.info("/anvil/projects/tdm/data/disney/7_dwarfs_train.csv")$size
----
[TIP]
====
You can also use `file.info` to see other information about the file. 

*size*- double: File size in bytes. +
isdir- logical: Is the file a directory? +
*mode*- integer of class "octmode". The file permissions, printed in octal, for example 644. +
*mtime, ctime, atime*- integer of class "POSIXct": file modification, ‘last status change’ and last access times. +
*uid*- integer: the user ID of the file's owner. +
*gid*- integer: the group ID of the file's group. +
*uname*- character: uid interpreted as a user name. +
*grname* - character: gid interpreted as a group name. +
(Unknown user and group names will be NA.)
====

Now that we have made sure our file isn't too big (1.24 GB), let's read it into a dataframe the same way that we have done in the previous two projects, and get started with our questions
[source,r]
----
myDF <- read.csv("/anvil/projects/tdm/data/craigslist/vehicles.csv")
----

== Questions

=== Question 1 (1 pt)
[upperalpha]
.. How many rows and columns does our dataframe have? (0.5 pts) 
.. What type/s of data are in this dataframe (example: numerical values, and/or text strings, etc.) (0.5 pts)
.. 1-2 sentences describing what our data contains as a whole.

As we stressed in Project 2, familiarizing yourself with the data you are going to work with is an extremely important first step. For this question, we want to figure out how many rows and columns are in our data along with what the types of data in our dataframe are. The hint below contains all of the functions that we need to solve this problem, but we also covered these functions in detail in Project 2, so feel free to reference it if you want more information.

When answering sub-question C., consider talking about where the data appears to be taken from, what the 

[TIP]
====
The `head()`, `dim()`, and `str()` functions could be helpful in answering this question.
====

.Items to submit
====
- The number of rows and columns in our dataframe, in a markdown cell.
- The types of data in our dataframe, in a markdown cell.
- 1-2 sentences summarizing our data.
====

=== Question 2 ( pt)
[upperalpha]
.. subquestion1
.. subquestion2
.. subquestion3










Now that we have a better understanding of content and structure of our data. We are diving a bit deeper and making connections within the data.

[loweralpha]
.. If we are looking at the column *"SPOSTMIN"* what do you notice about the increments of time?  I.e., is there anything special about the types of values that appear? How many different wait time options do you see in *"SPOSTMIN"*?
.. How many `NA` values do you see in *"SPOSTMIN"*?
.. Create a new data frame with the name `newDF` in which the *"SPOSTMIN"* column has all `NA` values removed.  In other words, select the rows of `myDF` for which *"SPOSTMIN"* is not `NA` and call the resulting `data.frame` by the name `newDF`.

.Insider Knowledge
[%collapsible]
====
`na.omit` and `na.exclude` returns objects with the observations removed if they contain any missing values. As well as performs calculations by considering the NA values but does not include them in the calculation. +
`na.rm` first [.underline]#removes the NA values and then# does the calculation. +
`na.pass` returns the object unchanged +
It is also possible to use the `subset` function and the `is.na` function.
====

.Helpful Hint
[%collapsible]
====
Use the code below 
[source,r]
----
table(myDF$SPOSTMIN)
----
====

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answer to the 3 questions above.
====
=== Question 3 (pt)

Use the `myDF` data.frame for this question.
[loweralpha]
.. On Christmas day, what was the average wait time? On July 26th, what was the average wait time?
.. Is there a difference between the wait times in the summer and the holidays? 
.. On which date do the most entries occur in the data set?

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answer to the 3 questions above.
====

==== Question 4 ( pt)

Recycling in R  +

.Insider Knowledge
[%collapsible]
====
Recycling happens in R automatically.  When you are attempting to preform operations like addition, subtraction on two vectors of unequal length. +
The shorter vector will be repeated as long as the operation is completing on the longer vector. 
====

[loweralpha]
.. Find the lengths of the column *"SPOSTMIN"* in the `myDF` and `newDF`.
.. Create a new vector called `myhours` by adding together *"SPOSTMIN"* columns from `myDF` and `newDF` with each divided by 60.  What is the length of that new vector `myhours`?
.. What happened in row 313997?  Why?



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answers to the 3 questions above.
====


==== Question 5 ( pt)

Indexing and Expanding dataframes in R 

[source,r]
----
library(lubridate)
myDF$weekday <- wday(myDF$datetime, label=TRUE)
----

[loweralpha]
.. Consider the average wait times.  What day of the week in `myDF` has the longest average wait times?
.. Make a plot and a dotchart that illustrate the data for the average wait times.   Which one conveys the information better and why?
.. We created a new column in `myDF` that shows the weekdays.  Do the same thing for part (a) and (b) again, but this time using the months instead of the days of the week.


.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answers to the 3 questions above.
====

=== Submitting your Work
Congratulations, you've finished Project 2! Make sure that all of the below files are included in your submission, and feel free to come to seminar, post on Piazza, or visit some office hours if you have any further questions.

.Items to submit
====
- `firstname-lastname-project01.ipynb`.
- `firstname-lastname-project01.R`.
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output, when in fact it does not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/current-projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or it does not render properly in gradescope. Please ask a TA if you need help with this.
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====