= TDM 10200: Project 1 -- 2024

**Motivation:** In this project we are going to jump head first into The Data Mine. We will load datasets into our environment, and introduce some core programming concepts like variables, vectors, types, etc. As we will be "living" primarily in an IDE called Jupyter Lab, we will take some time to learn how to connect to it, configure it, and run code.

**Context:** This is our first project this spring semester. We will get situated, configure the environment we will be using throughout our time with The Data Mine, and jump straight into working with data!

**Scope:** Python, Jupyter Lab, Anvil

.Learning Objectives
****
- Learn how to run Python code in Jupyter Lab on Anvil.
- Read and write basic (csv) data using Python.
****

== Readings and Resources

[NOTE]
====
Login to Anvil 
* Navigate and login to https://ondemand.anvil.rcac.purdue.edu using your ACCESS credentials (and Duo). 
* You may refer to https://the-examples-book.com/starter-guides/anvil/introduction [Anvil Introduction] and https://the-examples-book.com/starter-guides/anvil/access-setup [Access Setup]to find out how to Login to Anvil
====

[NOTE]
====
In the upper right-hand corner of your notebook, you will see the current kernel for the notebook, `seminar`. If you click on this name you will have the option to swap kernels out -- no need to do this yet, but it is good to know!

There are different data types in Python, some of the built in types include: 
* Integer (int)
* Float (float)
* string (str)
* types can include list, tuple, range
* Mapping data type (dict)
* Boolean type (bool)

Numeric

. int - holds signed integers of non-limited length.
. long- holds long integers(exists in Python 2.x, deprecated in Python 3.x).
. float- holds floating precision numbers and it is accurate up to 15 decimal places.
. complex- holds complex numbers.

String - a sequence of characters, generally strings are represented by single or double-quotes

Lists- ordered sequence of data written using square brackets *[]* and commas *(,)*. 

Tuple- similar to a list but immutable. Data is written using a parenthesis *()* and commas *(,)*. 

Dictionary is an unordered sequence of data of key-value pair(two pieces of data that have a set of associated values, two related data elements). 
====


== Dataset(s)

The following questions will use the following dataset(s):

- `/anvil/projects/tdm/data/forest/ENTIRE_COUNTY.csv`


== Questions

=== Question 1 (2 points)
 
[loweralpha]

.. In the first cell,  format as markdown cell and input your name and the course number. Inside the second cell comment out "print Hello World!", then place the Python code on the next line and run the cell. 

[TIP]
====
[source,python]
----
print("Hello World!")
----
====
 
=== Question 2 (2 points)

.. Create a variable named `num1` and assign the a integer number from user input, create a variable named `num2` and assign a integer number from user input. then print sum of num1 and num2 like follow, replace[result] with your result

.output
Sum of num1 and num2 is [result]

=== Question 3 (2 points)

.. Declare a list named fruits and assign 5 fruits to it

[TIP]
====
You may refer to https://the-examples-book.com/programming-languages/python/lists [this] Example Book python lists introduction
====

=== Question 4 (2 points)

.. Use template to create your project 1

[TIP]
====
This year, the first step to starting any project should be to download and/or copy our project template (which can also be found on Anvil at `/anvil/projects/tdm/etc/project_template.ipynb`). 

Open the project template and save it into your home directory, in a new notebook named `firstname-lastname-project01.ipynb`. 

Fill out the project template, replacing the default text with your own information, and transferring all work you've done up until this point into your new notebook. If a category is not applicable to you (for example, if you did _not_ work on this project with someone else), put N/A. 
====

=== Question 5 (2 points)

.. Read "/anvil/projects/tdm/data/forest/ENTIRE_COUNTY.csv" dataset in Python and assign it to a variable named forest
.. Use different methods to display the dateset information
... info, shape, size, column, len

[TIP]
====
[source,python]
----
import pandas as pd
forest = pd.read_csv("/anvil/projects/tdm/data/forest/ENTIRE_COUNTY.csv")
 
----
====

[IMPORTANT]
====
Submit your completed project 1: one Jupyter notebook and one Python script file

Let's pretend we are now done with the project. We've written some code, maybe added some markdown cells to explain what we did, and we are ready to submit our assignment. For this course, we will turn in a variety of files, depending on the project.

We will always require a Jupyter Notebook file. Jupyter Notebook files end in `.ipynb`. This is our "source of truth" and what the graders will turn to first when grading. 
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output, when in fact it does not.  

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or it does not render properly in gradescope. Please ask a TA if you need help with this.
====
[NOTE]
====
A `.ipynb` file is generated by first running every cell in the notebook, and then clicking the "Download" button from menu:File[Download].

In addition to the `.ipynb`, if a project uses Python code., you will need to also submit a Python script. A Python script is just a text file with the extension `.py`.

Let's practice.  take the Python code from this project and copy and paste it into a text file with the `.py` extension. Call it `firstname-lastname-project01.py`. Download your `.ipynb` file -- making sure that the output from all of your code is present and in the notebook (the `.ipynb` file will also be referred to as "your notebook" or "Jupyter notebook").

Once complete, submit your notebook,and Python script.
====

Project 01 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project01.ipynb`.
* Python file for the assignment
    ** `firstname-lastname-project01.py`.

* Submit files through Gradescope
====
 
[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
