= TDM 10200: Project 11 -- Spring 2024


**Motivation:** Learning classes in Python

**Scope:** Object Oriented Python

**Scope:** Python, pandas, NumPy 

== Reading and Resources

- Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here]
- https://the-examples-book.com/programming-languages/python/classes[python classes]
- https://www.programiz.com/python-programming/class[python objects and classes] 

== Dataset

`/anvil/projects/tdm/data/flights/2014.csv`

[WARNING]
====
You need to use 2 cores for your Jupyter Lab session for Project 10 this week.
====

[TIP]
====
You can use `pd.set_option('display.max_columns', None)` if you want to see all of the columns in a very wide data frame.
====

== Questions

=== Question 1(2 points)

[loweralpha]

.. Create a class "Transport" : Represents a single flight, with attributes as flight number, origin, destination, departure, and arrival times.

=== Question 2(2 points)

.. Create a sub class "FlightTransport" : Inherit attribute from "Transport" an airline, with attributes as the airline's name, IATA code, and a list of flights operated by the airline.

=== Question 3(2 points)

.. Create a sub class "CommercialFlight": Inherit from 'FlightTransport' 
=== Question 4(2 points)

.. Create a sub class "CharterFlight" : Inherit from 'FlightTransport' 

=== Question 5(2 points) 
.. Create instances and demonstrate usage.  

Project 11 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project11.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project11.py`

* Submit files through Gradescope
==== 
 
[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
