= TDM 10200: Project 7 -- 2024

**Motivation:** Pandas is a powerful tool to manipulate and analysis data in Python. We can use Pandas to extract information about one or more variables on data frames, sometimes we can group the data according to one variable and summarizing another variable within each of those groups.

**Context:**  Understanding how to use Pandas and be able to develope functions allows for a systematic approach to analyzing data.
**Scope:** Pandas and functions

== Reading and Resources

- Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].
- https://the-examples-book.com/programming-languages/python/writing-functions[Python Functions]
- https://the-examples-book.com/programming-languages/python/pandas-series[pandas Series]
- https://www.w3schools.com/python/python_lambda.asp[Python Lambda]
- https://the-examples-book.com/programming-languages/python/pandas-aggregate-functions[pandas aggregation functions]

== Datasets

/anvil/projects/tdm/data/noaa

== Questions

=== Question 1 (2 points)
 
[loweralpha]

.. US records start with 'US' in the first field, create a function to get a dictionary with years and count of how many US records pairs in the dataset
.. Run the function for dataset 1950.csv
.. Run the function for datasets from 1950 to 1953

[TIP]
====
- The following sample code can be used to get US records
[source,bash]
----
[source,python]
us_records = df[df['id'].str.startswith('US')]
----
- shape may be useful to get information

====


=== Question 2 (2 points)

.. Modify the function from question 1 to include the sort statement and return the sorted dictionary in descending order, define and use a Python lambda function as the keyword argument for "key"  in the sorted function
+
[TIP]
====
- Refer to https://www.w3schools.com/python/python_lambda.asp[Python Lambda]
====
.. Run the function for dataset 1950.csv
.. Run the function for dataset from 1950 to 1953


=== Question 3(2 points)
 
.. Write a function to calculate total number of snowfall days ("SNOW" as element_code) records in the given datasets in US
+
[TIP]
====
- 'value' will need to be great than 0
====
.. Write a function to calculate total snow amount in the given datasets in US
.. Run the functions for dataset 1950
.. Run the functions for datasets 1950- 1953

=== Question 4(2 points)

.. Update the function from question 3a to group the snowfall days by station id 
.. Update the function to return just the station with maximum snowfall days station for specified dataset(s) 
.. Run the function to find out which station has the most days of snowfall for year 1950 and how many? How about for year 1950 to 1954?

=== Question 5(2 points)
.. Create a function to find out the station that has maximum total yearly snowfall amount(s) for specified dataset(s)
.. Create a function to find out the station and month that has maximum monthly snowfall amount(s) for specified dataset(s)
.. Run the functions for dataset 1950. Which station has the most snowfall yearly amount for dataset 1950?
.. Run the functions for dataset 1950 to 1953. Which station at which month has the most monthly snowfall amount during these years?

[TIP]
====
- The following statement is the sample to get month information
[source,python]
df['date']=pd.to_datetime(df['date'],format ='%Y%m%d')
df['month'] = df['date'].dt.month
====
 
 

Project 07 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project07.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project07.py`

* Submit files through Gradescope
==== 


[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====

