= TDM 10200: Project 7 -- 2023

**Motivation:** Pandas allows us to work with data frames.  The actions that we perform on data frames will sometimes remind us of similar actions that we have performed on data frames during the previous semester with R.  For instance, we often want to extract information about one or more variables, sometimes grouping the data according to one variable and summarizing another variable within each of those groups.

**Context:**  Unifying our understanding of Pandas and the ability to develop functions will allow us to systematically analyze data.

**Scope:** Pandas and functions

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

/anvil/projects/tdm/data/flights/subset/


== Questions

=== ONE

Make sure to have 2 cores when you start your Jupyter Lab session.

For convenience, we will help you quickly get all of the data for all of the flights that depart or arrive at Indianapolis airport, as follows.  Make a new cell in JupyterLab that has exactly this content (please copy and paste for accuracy):

[source,bash]
----
%%bash
head -n1 /anvil/projects/tdm/data/flights/subset/1987.csv >~/INDflights.csv
grep -h ",IND," /anvil/projects/tdm/data/flights/subset/*.csv >>~/INDflights.csv
----

We want to use Pandas to read in the data frame, and it will have a lot of columns.  So we set Pandas to display an unlimited number of columns.

[source,python]
----
import pandas as pd
pd.set_option('display.max_columns', None)
----

Afterwards, in a separate cell in JupyterLab, you can read in your data to a Pandas data frame like this:

[source,python]
----
myDF = pd.read_csv('~/INDflights.csv')
----

Now your data frame called `myDF` will contain all of the data for the flights (from October 1987 to April 2008) that depart or arrive at Indianapolis airport, which has 3-letter code `IND`.

These files correspond to the years 1987 through 2008.  Your data frame should contain all of the data for all of the flights with `IND` as the `Origin` or `Dest` airport.

[loweralpha]
.. How many flights are there altogether in `myDF`?  You can check this using `myDF.shape`.
.. How many of the flights are departing from `IND`?  (I.e., the `Origin` airport is `IND`.)
.. How many of the flights are arriving to `IND`?  (I.e., the `Dest` airport is `IND`.)


.Items to submit
====
- Code used to answer the question. 
- Result of code.
====



=== TWO

[loweralpha]
.. For flights departing from 'IND', what are the 10 most popular destination airports?
.. For flights arriving to 'IND', what are the 10 most popular origin airports?

.Items to submit
====
- Code used to answer the question. 
- Result of code.
====


=== THREE


[loweralpha]
.. Use plotly to make plots for the data in 2a
.. Use plotly to make plots for the data in 2b

.Items to submit
====
- Code used to answer the question. 
- Result of code.
====





=== FOUR


Consider flights departing from "IND".  If we group by the airline (UniqueCarrier), and take an average of the departure delays, what are the average departure delays for each of these three airlines: `AA`, `DL`, and `UA`?

.Items to submit
====
- Code used to answer the question. 
- Result of code.
====



=== FIVE

Wrap your work from Question 1 and 2a into a function that accepts an `Origin` airport (as the departing airport), and outputs the 10 most popular destination airports.

Test your function on several airports, e.g., test it on each of these three airports (one at a time) `IND`, `ORD`, `CVG`, to make sure that the output from the function makes sense.


.Items to submit
====
- Code used to answer the question. 
- Result of code.
====



[NOTE]
====
TA applications for The Data Mine are currently being accepted. Please visit us https://purdue.ca1.qualtrics.com/jfe/form/SV_08IIpwh19umLvbE[here] to apply!
====


[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====