= TDM 10200: Project 4 -- 2024

**Motivation:** In the last project, we began exploring control flow, including if statements and for loops. In this project, we will delve deeper into the concept of loops. There are three main types of loops we'll focus on: for loops, while loops, and nested loops.


**Context:**  We will continue to work on some basic data types and go thru some similar control flow concepts  

**Scope:** loops, basic data structures such as tuples, lists, loops, dict


== Dataset

/anvil/projects/tdm/data/noaa/2022.csv

== Readings and Resources
[NOTE]
====
- Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

- Please review the following Examples Book Contents  
    - https://the-examples-book.com/programming-languages/python/dictionaries [Python dictionaries]
    - https://the-examples-book.com/programming-languages/python/tuples [Python tuples]
    - https://the-examples-book.com/programming-languages/python/lists [Python lists]
    - https://the-examples-book.com/programming-languages/python/pandas-dataframes [Python pandas DataFrames] 
    - https://the-examples-book.com/programming-languages/python/matplotlib [matplotlib]
==== 


== Questions

=== Question 1 (2 points)

[loweralpha]

.. Create a dictionary named "Veg_colors" to contain 5 vegetables and their colors. Include "Eggplant" and "Celery" in the dictionary  
.. Now add the two more Veg-color to the dictionary 
.. Remove "Eggplant" and "Celery" from the dictionary  

 
=== Question 2 (2 points)


.. Use a while loop to print a series of odd numbers between 100 to 200

.. Put the sentence "Data Mining is so fun!!!" in a variable called 'dm'.   Print everything in the string *EXCEPT* the letter *!* 

.. Use a while loop to print each letter in the string except empty space. like 'here comes the letter: D !!!'


=== Question 3 (2 points)


[loweralpha]
.. Save the song "Old MacDonald Had a Farm" to a list and use a for loop with the ""enumerate()" function to print out each line of the song, including the line number. You may just print 4 sentences
.. Use a for loop with "range()" function to count down from 10 to 1

[NOTE]
====
- You may refer to the following Lyrics 
Old MacDonald had a farm, E-I-E-I-O,", 
"And on his farm he had a cow, E-I-E-I-O,", 
"With a moo-moo here and a moo-moo there,", 
"Here a moo, there a moo, everywhere a moo-moo."]
====
 
=== Question 4 (2 points)

.. Read in the dataset for file "2022.csv", add columns name by the list ["id","date","element_code","value","mflag","qflag","sflag","obstime"]  

.. From the dataset, create a dictionary to hold key:value pairs for the first 10 records 

=== Question 5(2 points)

.. You have used both while and for loop on this project. Please describe the scenarios of your preference with your own 2 examples using the dataset for each loop 

Project 04 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project04.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project04.py`

* Submit files through Gradescope
==== 

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====