= TDM 10200: Project 8 -- 2024

**Motivation:** We will continue to introduce functions and continue with visualization


**Context:**  Write functions with visualization

**Scope:** python, functions, pandas, matplotlib, Parquet columnar storage file format

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Examples Book Content

Please review the following Examples Book Contents  
- https://the-examples-book.com/programming-languages/python/writing-functions [Python Functions]
- https://the-examples-book.com/programming-languages/python/dictionaries [Python dictionaries]
- https://the-examples-book.com/programming-languages/python/tuples [Python tuples]
- https://the-examples-book.com/programming-languages/python/lists [Python lists]
- https://the-examples-book.com/programming-languages/python/pandas-dataframes [Python pandas DataFrames] 
- https://the-examples-book.com/programming-languages/python/matplotlib [matplotlib]

== Datasets

/anvil/projects/tdm/data/whin/weather.parquet


== Questions 

[TIP]
====
We want to load *only* two `pandas` data frames to use in this project. We will not be working with the other data frames.
Don't forget to import pandas!
[source, python]
----
weather = pd.read_parquet("/anvil/projects/tdm/data/whin/weather.parquet") 

----
====

=== Question 1 (2 points)

.. Writing a function called `get_weather_data` with the `station_id` and specific date as arguments. Function should include all type hints (https://www.pythontutorial.net/python-basics/python-type-hints/[type hints])
This new function should return a pandas DataFrame with the information in the `weather` DataFrame for that `station_id` at the date. 
        ``

=== Question 2 (2 points)


Next, we need to write a function called `calculate_avg_wind_speed` that accepts the `station_id` and returns the average number of wind_speed for group by station_id

Doing this we can use the `groupby()` function.  This is one of the most powerful functions for (more easily) working with data frames in python.


 

=== Question 3 (2 points)

.. write a function called `visualize_wind`. It needs to accept a list of station_id and a date as arguments.  It should make a line plot that shows the average wind speed
 

=== Question 4 (2 points)

.. write a function `visualize_wind_station` with argument of station id and range of date. It should make a line plot that shows the average wind speed in the date range for the station. 

Project 08 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project08.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project08.py`

* Submit files through Gradescope
==== 

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====