= TDM 10200: Project 9 -- Spring 2023


**Motivation:** Working in pandas can be fun! Learning how to wrangle data and clean up data in pandas is a helpful tool to have in your tool belt!  

**Context:** Now that we are feeling more comfortable with building functions and using pandas we want to continue to build skills and use pandas to solve data driven problems.

**Scope:** python, pandas, numpy

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)
When launching Juypter Notebook on Anvil you will need to use 2 cores. 

The following questions will use the following dataset(s):

'/anvil/projects/tdm/data/disney/total.parquet'


.Helpful Hints
[%collapsible]
====
[source,python]
----
import pandas as pd
disney = pd.read_parquet('/anvil/projects/tdm/data/disney/total.parquet')
----
====



.Insider Knowledge
[%collapsible]
====
It is helpful to use a `Parquet` file when we need efficient storage. If we tried to read in all the .csv files in the disney folder the kernel would crash. In short a `Parquet` file allows for high performance data compression and encoding schemes to deal with large amounts of complex data. The format is a column- oriented file format while .csv's tend to be row-oriented. +
You can read more about what row vs column oriented databases are https://dataschool.com/data-modeling-101/row-vs-column-oriented-databases/[here]. 
====

=== ONE
Luckily this data is being read in as already cleaned data. It also has been recently updated and has a lot more information. Which means more data from more rides. 


[loweralpha]
.. Since there is a lot of new ride data, lets print the name of each ride. 
.. How many rows of data are there for each ride?
.. What is different about the information that you receive if you use the groupby() vs value.count(). Which will lead me to the information asked by question 1b? 
.. Go ahead and import the numpy package see if you can find the frequency of JUST the ride named 'hall_of_presidents' from the column 'ride_name'. Under *Helpful Hint* there are two different ways to do that, but can you come up with a third?

.Helpful Hint
[%collapsible]
====
[source,python]
----
import numpy as np
disney[disney.ride_name == 'hall_of_presidents'].shape[0]
#OR
import numpy as np 
(disney['ride_name']=='hall_of_presidents').sum()
----
====

.Insider Knowledge
[%collapsible]
====
* Note that before it gives you all the unique values in the column `ride_name` it tells you that it is an array. An array is a ordered collection of elements where every value is the same data type. 
====

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- Answer to questions a,b,c,d
====

=== TWO
Create a new function that results in showing for each ride the first year the data was collected and the most recent year the data was collected.

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== THREE
Notice that the dataset has two columns `SPOSTMIN' or 'SACTMIN`. Each row has either a value for `SPOSTMIN' or 'SACTMIN` but not both. 

[loweralpha]
.. How many total rows of data do we have?
.. How many non-null rows for `SPOSTMIN`
.. How many non-null rows for `SACTMIN`
.. Combine columns `SPOSTMIN' and 'SACTMIN` to create a new variable named newcolumn
.. How many fewer rows are in the variable newcolumn?


.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- Answer to questions a,b,c,d,e
====

=== FOUR
[loweralpha]
.. Find the date that each ride was most frequently checked 
.. Find the max and min time for `SACTMIN` for each ride
.. Find the max and min time `SPOSTMIN' for each ride
.. What was the most commonly closed ride? (note that the value -999 indicates the attraction was closed)
.. Find the average time `SPOSTMIN' for each ride 
.. Find the average `SACTMIN' time for each ride

.Helpful Hint
[%collapsible]
====
You will need to replace the values -.999 with a null value so that you can calculate the average `SPOSTMIN` and `SACTMIN'. 
====

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
-Answer to questions a-f
====


[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
