= TDM 10200: Project 7 -- 2023

**Motivation:** Pandas allows us to work with data frames.  The actions that we perform on data frames will sometimes remind us of similar actions that we have performed on data frames during the previous semester with R.  For instance, we often want to extract information about one or more variables, sometimes grouping the data according to one variable and summarizing another variable within each of those groups.

**Context:**  Unifying our understanding of Pandas and the ability to develop functions will allow us to systematically analyze data.

**Scope:** Pandas and functions

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

/anvil/projects/tdm/data/flights/subset/


== Questions

=== ONE

Create a new data frame called `myDF` that contains all of the data for Indianapolis from the `csv` files from the directory:

`/anvil/projects/tdm/data/flights/subset`

These files correspond to the years 1987 through 2008.  Your data frame should contain all of the data for all of the flights with `IND` as the `Origin` or '`est` airport.

.Items to submit
====
- Code used to answer the question. 
- Result of code.
====



=== TWO


[loweralpha]
.. Write a loop that prints the number of vehicles from `chicago` as the `region` in each of the years 2016, 2017, 2018.
(I.e., you should have 3 lines of output.)
.. Now write a double-loop that prints the number of vehicles from each `region` in the list `[chicago, indianapolis, cincinnati]` in each of the years 2016, 2017, 2018.
(I.e., you should have 9 lines of output.)

.Items to submit
====
- Code used to answer the question. 
- Result of code.
====


=== THREE


[loweralpha]
.. Write a function with two arguments: a list of regions, and a list of years.  The function should print a listing that shows the number of vehicles from each of those regions in each of those years.
(I.e., it will print one line of output for each region during each year.)
.. Use your new function to re-create the answer to question 2b.
.. Test your function on some lists of regions and lists of years of your choice.

.Items to submit
====
- Code used to answer the question. 
- Result of code.
====





=== FOUR

Use the function from Question 3a in Project 5.


[loweralpha]
.. Write a loop that prints the number of flights that depart from `IND` as the `Origin` airport in each of the years 1988, 1989, 1990.
(I.e., you should have 3 lines of output.)
.. Now write a double-loop that prints the number of flights that depart from each of the airports `IND`, `ORD`, `CVG` as the `Origin` airport in each of the years 1988, 1989, 1990.
(I.e., you should have 9 lines of output.)


[TIP]
====
For this question, you should not read the full data frame all at once, but instead, you should just a few lines at a time, using the `chunksize = 10000` and the `iterrows` like in the videos.
====

.Items to submit
====
- Code used to answer the question. 
- Result of code.
====



=== FIVE

Extend your function from Question 3 as follows:

[loweralpha]
.. Write a function with two arguments: a list of `Origin` airports, and a list of years.
The function should print a listing that shows the number of flights departing from each of those `Origin` airports in each of those years.
(I.e., it will have one line of output for each `Origin` airport during each year.)
.. Use your new function to re-create the answer to question 4b.
.. Test your function on some lists of `Origin` airports and lists of years of your choice.

[TIP]
====
Again, for this question, you should not read the full data frame all at once, but instead, you should just a few lines at a time, using the `chunksize = 10000` and the `iterrows` like in the videos.
====

.Items to submit
====
- Code used to answer the question. 
- Result of code.
====



[NOTE]
====
TA applications for The Data Mine are currently being accepted. Please visit us https://purdue.ca1.qualtrics.com/jfe/form/SV_08IIpwh19umLvbE[here] to apply!
====


[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====