= TDM 10200: Project 7 -- 2023

**Motivation:** Pandas allows us to work with data frames.  The actions that we perform on data frames will sometimes remind us of similar actions that we have performed on data frames during the previous semester with R.  For instance, we often want to extract information about one or more variables, sometimes grouping the data according to one variable and summarizing another variable within each of those groups.

**Context:**  Unifying our understanding of Pandas and the ability to develop functions will allow us to systematically analyze data.

**Scope:** Pandas and functions

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

/anvil/projects/tdm/data/flights/subset/


== Questions

UNDER CONSTRUCTION!!!  Dr Ward is making Project 7 shorter.  The revised Project 7 will be posted on Sunday morning.


[NOTE]
====
TA applications for The Data Mine are currently being accepted. Please visit us https://purdue.ca1.qualtrics.com/jfe/form/SV_08IIpwh19umLvbE[here] to apply!
====


[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====