= TDM 10200: Project 2 -- 2023

**Motivation:** In this project we are going to jump head first into The Data Mine. We will load datasets into  environment, and introduce some core programming concepts like variables, vectors, types, etc. As we will be "living" primarily in an IDE called Jupyter Lab, we will take some time to learn how to connect to it, configure it, and run code.

**Context:** This is our second project and we will continue to introduce some basic data types and go thru some similar control flow concepts like we did in `R`. 

**Scope:** tuples, lists, if statments, opening files

.Learning Objectives
****
- List the differences between lists & tuples and when to use each.
- Gain familiarity with string methods, list methods, and tuple methods.
- Demonstrate the ability to read and write data of various formats using various packages.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- /anvil/projects/tdm/data/death_records/DeathRecords.csv 

== Questions

=== ONE

`pandas` is an integral tool for various data science tasks in Python. You can read a quick intro [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html).

Lets first learn how to create a simple dataframe 
If we have a store that we only sell hats that are blue and white and shoes that are red and purple. +
Imagine its a Saturday and we wanted to keep track of our customer's purchase. 
Our first sale is a red shoe and a blue hat. Second sale is a purple shoe and a blue hat. Third is a red shoe and a blue hat, fourth is a purple shoe and a white hat, fifth is a red shoe and a white hat, the sixth and seventh sale are red shoes and blue hats. 

So it looks a bit like this:
[source, python]
----
data = {
    'shoes':['red','purple','red','purple', 'red', 'red', 'red'],
    'hats': ['blue', 'blue', 'blue', 'white', 'white', 'blue', 'blue']
}
----

[loweralpha]
.. Create a data set named 'data'
.. take the data you created and make a dataframe named 'store'

.Insider Knowledge
[%collapsible]
====
`Pandas` is a great way to get aquainted with your data. Using `pandas` to clean, transform and analyze it. `Pandas` allows you to extract data from a CSV (comma- seprated values) file. 

The two main components of pandas are the `series` and `DataFrame`. A `series` is essential a column and a `DataFrame` is a table makde up of a collection of `series`. 
====


=== TWO

For this dataframe that we want to actually have customer names as our index instead of numbers. 

[loweralpha]
.. Change the numbers 0-6 to customers Jay, Mary, Bill, Chris, Martha, Karen, Rob

.Helpful Hint 
[%collapsible]
====
[source, python]
----
store = pd.DataFrame(data, index=['Jay', 'Mary', 'Bill', 'Chris', 'Martha','Karen', 'Rob'])

store
----
====



.Insider Knowledge 
[%collapsible]
====
Notice that the indexing for our dataframe starts at 0. In `python` and other programming languages the indexing starts at 0. Whereas our previous semester in `R` the indexing began at 1. This is an important fact to remember. 
====

.Items to submit
====
- Code used to answer the question. 
- Result of code.
====


=== THREE

Open a new notebook in using the f2022-2023 kernel
We want to go ahead and read in the dataset /anvil/projects/tdm/data/death_records/DeathRecords.csv  into a `pandas` DataFrame called `myDF`. +

[loweralpha]
.. Find the information for the 11th row in the dataframe
.. Find the last five rows of the data frame
.. Find how many rows and columns there are in the entire dataframe
.. Print just the column names 

.Helpful Hints
====
[source,python]
----
.head()
.tail()
.shape()
----
====

.Items to submit
====
- Results of the questions A-C
====

=== FOUR

Lets look for specific information in our dataframe so we can become a bit more familiar with what it contains. 

[loweralpha]
----
.. How many people over the age of 52 are on this list?
.. How many males vs how many females
.. How many females that are over the age of 70 on this list?
----

.Items to submit
====
- Answers to questions A-C
====

=== FIVE

Now that we have a bit of familiarity with the data, lets introduce another common `python` package called 'matplotlib'
Let create a graphic using this package.
[loweralpha]
----
.. Create a graphic that summarizes some of the data from our dataset!
.. Use `pandas` and your investigative skills to look thru the data and find an interesting fact! 
----
.Helpful Hint
====
[source,python]
----
import matplotlib.pyplot as plt
----
====

.Insider Knowledge
====
*Matplotlib* is a data visualization and plotting library for`Python`. Its an easy way to generate visual data plots. 
[WARNING]
====

You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output, when in fact it does not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/current-projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or it does not render properly in gradescope. Please ask a TA if you need help with this.
====

A `.ipynb` file is generated by first running every cell in the notebook, and then clicking the "Download" button from menu:File[Download].

In addition to the `.ipynb`, if a project uses Python code., you will need to also submit a Python script. A Python script is just a text file with the extension `.py`.

Let's practice.  take the Python code from this project and copy and paste it into a text file with the `.py` extension. Call it `firstname-lastname-project01.py`. Download your `.ipynb` file -- making sure that the output from all of your code is present and in the notebook (the `.ipynb` file will also be referred to as "your notebook" or "Jupyter notebook").

Once complete, submit your notebook,and Python script.

.Items to submit
====
- `firstname-lastname-project01.py`.
- `firstname-lastname-project01.ipynb`.
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====