= TDM 10200: Project 8 -- 2024

**Motivation:** We will continue to introduce functions and visualization

**Context:**  Write functions with visualizations

**Scope:** python, functions, pandas, matplotlib, Parquet columnar storage file format


== Reading and Resources

- Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].
- https://the-examples-book.com/programming-languages/python/writing-functions[Python Functions]
- https://the-examples-book.com/programming-languages/python/pandas-series[pandas Series]
- https://the-examples-book.com/programming-languages/python/pandas-aggregate-functions[pandas aggregation functions]


== Datasets

`/anvil/projects/tdm/data/whin/weather.parquet`

== Questions 
 

=== Question 1 (2 points)

Read the file into a DataFrame called `myDF`.

.. Convert the 'observation_time' column to into a `datetime` type.
.. Create 3 new columns for the `year`, `month` and `day`, based on the column `observation_time`.
.. For a given `station_id`, calculate the average month-and-year-pair temperatures (from the column `temperature`) for that `station_id`.  Try this for a few different `station_id` values.
.. Now write a function called `get_avg_temp` that takes one `station_id` as input and returns the average month-and-year-pair temperatures (associated with that specific `station_id`).  Make sure that the results of your function match with your work from question 1c.

=== Question 2 (2 points)

For this function, be sure to `import matplotlib.pyplot`.

We will use the function from question 1d to make some line plots.

.. For a given `station_id`, create a line plot, with one line for each year.  Try this for a few different `station_id` values.
.. Now wrap your work from question 2a into a function that takes a `station_id` as input, and creates a line plot, with one line for each year (for the average month-and-year-pair temperatures from that `station_id`).

=== Question 3 (2 points)

.. Revisit the function from question 1d, to find the maximum temperature (instead of the average temperature) in each month-and-year-pair.  As before, you should test this for several examples before you build the function, and then make sure your function matches your examples.
.. Revisit the function from question 2b, to create a bar plot (instead of a line plot) and to use the maximum temperature in each month-and-year-pair (instead of the average temperature).
 

=== Question 4 (2 points)

.. Now let us get the wind speed data for station ID 1 for the year 2020, use 'wind_speed_mph' column
.. Visualize the distribution of wind speeds for each month for station ID 1 in the year 2020 using a box plot.
..  Write a function that takes a file path and a station_id as inputs, returns a DataFrame of 2020 wind speed data for the specified station, and visualizes the information with a box plot. 
 

=== Question 5 (2 points)

.. Explore the dateset and find something interesting like in wind speed, pressure or soil temperature and do some analysis, then visualize the information with different plots
.. Wrap the step to create a function and test with a station

Project 08 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project08.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project08.py`

* Submit files through Gradescope
==== 

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
