= TDM 10200: Project 11 -- Spring 2024


**Motivation:** Learning classes in Python

**Scope:** Object Oriented Python

**Scope:** Python, python class, pandas

== Reading and Resources

- Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here]
- https://the-examples-book.com/programming-languages/python/classes[python classes]
- https://www.programiz.com/python-programming/class[python objects and classes] 
- https://docs.python.org/3/library/datetime.html[python datetime]

== Dataset

`/anvil/projects/tdm/data/flights/2014.csv`

[WARNING]
====
You need to use 2 cores for your Jupyter Lab session for Project 11 this week.
====

[TIP]
====
You can use `pd.set_option('display.max_columns', None)` if you want to see all of the columns in a very wide data frame.
====

== Questions

=== Question 1 (2 points)

[loweralpha]

.. Create a class named "Flight" , it contains attributes for flight number, origin airport ID, destination airport ID, departure time, arrival time, departure delay, and arrival delay
.. Add a  get_arrdelay() to the class to get the delay time

=== Question 2 ( 2 points)

.. Create a DataFrame named "myDF", get data from provided dataset for only following columns and 100 rows, explore the dataset and provide the data type while read the data
.. Load data from myDF to the Flight class instances, you should have a list of 100 Flight instances 

[source,python]
----
columns_to_read = [
    'DepDelay', 'ArrDelay', 'Flight_Number_Reporting_Airline','Distance', 
    'CarrierDelay', 'WeatherDelay', 
    'DepTime', 'ArrTime', 'OriginAirportID' ,
    'DestAirportID' , 'AirTime'
]
----

 
=== Question 3 ( 2 points)

.. Create a dictionary variable named "delays_dest" as an empty dictionary
.. Use a for loop to assign values to "delays_dest" from flight objects 
.. Calculate the average arrival delay time for each station and save the result to a dictionary named "average_delays"

=== Question 4(2 points)

.. Create a function called "arr_avg_delays" based on the steps from Question 3, it has input as Flight objects and output a dictionary of average arrival delays for each destination
.. Run the function using 100 Flight instances from Question 2 as input

=== Question 5(2 points) 

.. Update the class `Flight` to add a method name it "get_depDelay()" to the class
.. Create a function called dep_avg_delays, take Flight objects of the updated class as input, calculate average departure delays for each station an return the delays information
.. Run the function for the 100 new Flight objects
 

Project 11 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project11.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project11.py`

* Submit files through Gradescope
==== 
 
[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
