= TDM 10200: Project 9 -- Spring 2024


**Motivation:** Working in pandas can be fun! Learning how to wrangle data and clean up data in pandas is a helpful tool to have in your tool belt!  

**Context:** Now that we are feeling more comfortable with building functions and using pandas we want to continue to build skills and use pandas to solve data driven problems.

**Scope:** python, pandas, numpy



== Reading and Resources

- Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].
- https://the-examples-book.com/programming-languages/python/pandas-dataframes[Python pandas DataFrames] 
- https://the-examples-book.com/programming-languages/python/matplotlib[matplotlib]
-  https://dataschool.com/data-modeling-101/row-vs-column-oriented-databases/[rows vs column oriented databases]. 


== Datasets

/anvil/projects/tdm/data/whin/weather.parquet

== Questions 

=== Question 1 ( 2 points )

 
[loweralpha]
 
.. Use pandas to read the file and use the following attributes or methods to describe the data frame
... .shape
... .dtypes
... .info()
... .describe()

[TIP]
====
- since the dataset format is parquet, read_parquet() may be used
====

=== Question 2 ( 2 points)


.. Use method value_counts() to get numbers of records for each station
.. Use method groupby() to get numbers of records for each station 
.. Describe if you notice any difference between 2 methods
 
 

Create a new function that accepts a r name as an argument, and prints two things: (1) the first year the data for that ride was collected, and (2) the most recent year that the data for that ride was collected.

  

=== Question 3 (2 points)
.. Use .isnull().sum() to find out how many null records in the columns soil_moisture_1 to soil_moisture_4?
.. Combine column "latitude" and "longitude" to create a new column "location" for each station. You may refer 
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.combine_first.html [combine_first function 

=== Question 4 ( 2 points)

 .. create a function to calculation average heat index by the following formula for the station and date specified
 HI = 0.5*(T+61.0+((T-68.0)*1.2 )+(R*0.094))


=== Question 5 ( 2 points)

Project 09 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project09.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project09.py`

* Submit files through Gradescope
==== 

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
