= TDM 10200: Project 6 -- 2024
**Motivation:** Once we have some data analysis working in Python, we often want to wrap it into a function.  Dr Ward usually tests anything that he wrote (usually 5 times), to make sure it works, before wrapping it into a function.  Once we are sure our analysis works, if we wrap it into a function, it can usually be easier to use.


**Context:**  Functions also help us to put our work into bite-size pieces that are easier to understand.  The basic idea is similar to functions from R or from other languages and tools. 

**Scope:** functions
 
== Reading and Resources

- Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

- https://the-examples-book.com/programming-languages/python/writing-functions[Python Functions]

- https://realpython.com/sort-python-dictionary[sorting a dictionary in Python]
 

== Datasets
/anvil/projects/tdm/data/election/

== Questions

=== Question 1 (2 points)

Functions should have simple inputs and should create helpful outputs.  That way, a person can use the function to get good things done, without having to remember the details.  For the election data, it is hard to remember where the files are located, and what the column names should be, etc.  This question will create a useful function that only requires the user to start with 1 year as input, and it returns a dataframe as the output.  That dataframe contains all of the election data for that year.

[loweralpha]
.. First (without a function!)\ start with a variable called `myyear`.  It can be an election year, and it helps if you try this with a few of the early 1980's elections years, so that they data is not-too-big.  For instance, try `myyear` with each of the years 1980, 1984, and 1988 (one at a time, not a list).  Once you set the value of `myyear`, then make a variable for the path to the data from that year, for instance, `/anvil/projects/tdm/data/election/itcont1984.txt`
.. Read in the data from the year stored in `myyear`.  Please note that the data does not have column headers built-in, so you need to add the column headers, as in the "tip" below.  Please also note that the elements in the data set has `|` between the data elements, not commas (this is why the file name ends in `.txt` not `.csv` in this case).  So you need to use the parameter `delimiter='|'` in your `read_csv` function.  It might also help to use the parameter `dtype=str`.
.. Look at the head of the data set, after you read it in.  Does it look correct?  Does everything make sense?  Try this for each of the years, 1980, then 1984, then 1988, one at a time, storing each of these values into the variable `myyear` and then read in the data for that year, and checking the head of the data.  This is good practice for making sure that your work is designed properly.
.. Now that you are sure that your work is OK, make a function called `read_election_year` that takes one parameter called `myyear` asa the input, and returns the a data frame that contains the data from that election year.  Make sure to document your function with a docstring to explain how it works.
+
[TIP]
====
- You may refer to the following title list for the dataset, you may need to update it for some datasets as needed
[source, python]
t_list=["CMTE_ID","AMNDT_IND","RPT_TP","TRANSACTION_PGI","IMAGE_NUM","TRANSACTION_TP","NAME","CITY","STATE","ZIP_CODE","EMPLOYER","OCCUPATION","TRANSACTION_DT","TRANSACTION_AMT","OTHER_ID","TRAN_ID","FILE_NUM","MEMO_CD","MEMO_TEXT","SUB_ID"]
====

==== Question 2 (2 points)

.. Create a function to calculate the unique committees numbers for different years. Display the year and committees. Use function from 1b as helper function 
.. Run the function for year 2004 to 2010

==== Question 3 (2 points)

.. Create a function to find the top 5 states by total amount of "TRANSACTION_AMT" for specified dataset(s) 
.. Run the function for dataset for year 1984 "itcont1984.txt"
.. Run the function for datasets from 2008 to 2014

[TIP]
====
- Pay attention to the type of data in the `TRANSACTION_AMT` column.  You might need to convert this column to decimal numbers before making calculations.
- You may use the `sorted()` function to sort the dictionary items that contain the `state` and `total transaction amount` pairs.
- Refer to https://realpython.com/sort-python-dictionary[Python sorted function]. You may need to define a helper function inside the main function, and pass it to `sorted()` as a callback function. The following is an example to get a tuple extracted from dictionary as a `(state, amount)` pair.  You may modify this example to fit your approach.

[source,python]
----
def get_trans_amt(state_amt_tuple):
    return state_amt_tuple[1]
----
====
 
=== Question 4 (2 points)

.. Create a function to find out what are top 5 employers by total transaction amount for specified datasets?
.. Run the function for the 1984 dataset.
.. Run the function for the datasets from 1990 to 1994.

=== Question 5 (2 points)

.. Create one of your own function using the dataset under the folder, use at least two of following: packing/unpacking(list), helper function and/or callback function

Project 06 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project06.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project06.py`

* Submit files through Gradescope
==== 


[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
==== 