= TDM 10200: Project 13 -- Spring 2024


**Motivation:** Use pandas to understand data through statistics and visualizations and communicate results. Visualize data and drawing conclusions from data and communicate base on the results. 

**Scope:** python, pandas, numpy, matplotlib

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

/anvil/projects/tdm/data/amazon
 
== Questions 

=== Question 1 (2 pts)


[loweralpha]
This question will compare the time you use to do a mean calculation use python regular operation, pandas and numpy. Read in the twoReviews.csv from previous project. Calculate the average scores for all products
.. Calculate using regular python operation, wha tis the result and how long it takes?
.. Use numpy to calculate what is the result and how long it takes?
.. Use pandas to calculate what is the result and how long it takes?


 

=== Question 2 (2 points)
.. use pandas groupby to find out how many review counts for each product
.. use pandas groupby to find out the number of reviews for each year

  
=== Question 3 (2 points)

.. what is the total helpful numerator for the whole dataframe (total of column helpfulnessnumerator)
.. what is the total number helpful denominator for  the whole dataframe ?


=== FOUR
.. Visualize with a bar chart to show average scores for each product
.. Visualize with a scatter plot to explore the relationship between HelpfulnessNumerator vs HelpfulnessDenominator, what do you find?

Project 13 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project13.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project13.py`

* Submit files through Gradescope
==== 
[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
