= TDM 10200: Project 9 -- Spring 2024


**Motivation:** Working with pandas can be fun! Learning how to manipulate and clean up data in pandas is a helpful tool to have in your tool belt! Dive into pandas to transform and analyze data, equipping you with key data science skills.

**Context:** Hopefully, most students are feeling pretty comfortable now, with building functions and using pandas. In this project, we will continue working with pandas. We want to get better at analyzing big datasets and solving problems with data. 

**Scope:** python, pandas 

== Reading and Resources

- Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here]
- https://www.digitalocean.com/community/tutorials/pandas-dropna-drop-null-na-values-from-dataframe[pandas drop Null from DataFrame]

== Dataset

`/anvil/projects/tdm/data/whin/weather.csv`
 

[WARNING]
====
You need to use 2 cores for your Jupyter Lab session for Project 9 this week.
====

[TIP]
====
You can use `pd.read_parquet` to read in a `parquet` file (very similarly to how you use `pd.read_csv` to read in a `csv` file!)

You can use `pd.set_option('display.max_columns', None)` if you want to see all of the columns in a very wide data frame.
====



== Questions 

=== Question 1 (2 points)

 
[loweralpha]
 
.. Use pandas to read the file and use the following attributes or methods to describe the data frame
... .head()
... .shape
... .dtypes
... .info()
... .describe()

=== Question 2 (2 points)

.. Use method `value_counts()` to get numbers of records for each station
.. Use method `groupby()` to get numbers of records for each station 
.. Explain the difference between using the two methods
 

=== Question 3 (2 points)

.. Find out how many null records exist in `myDF` for each column
+
[TIP]
====
- `isnull()` is useful to find null records
====
.. Count total number of nulls across `myDF`
+
[TIP]
====
- sum() is useful
====
.. Drop rows with any null values across `myDF`, saved the output to a new DataFrame `myDF_cleaned`. display the total count of non-null records in the new DataFrame
+
[TIP]
====
- `dropna()` is useful
====


=== Question 4 (2 points)

.. Drop all null values for column `temperature`
.. Combine column "latitude" and "longitude" into a new column "location" with '_' in between
+
[TIP]
====
- You may refer to https://www.statology.org/pandas-combine-two-columns/[combine columns]
- The data type need to be string for the location
====

.. Find the average temperature group by the `location` column

[TIP]
====
- Due to memory limitation, you may need to use a loop to process the file in chunks 
- Drop only rows has null value at `temperature` column
====

=== Question 5 (2 points)
.. Let us create a function for Question 4, it will drop records with null value at `temperature` column, creates a `location` column, and calculate average temperature group by location and returns the Series of average temperature by location.  

[TIP]
====
- Due to memory limitation, you may need to use a loop to process the file in chunks 
- Drop only rows has null value at `temperature` column
====

Project 09 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project09.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project09.py`

* Submit files through Gradescope
==== 

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
