= TDM 10200: Project 12 -- Spring 2024


**Motivation:** Data analysis with Panda and numpy 

**Scope:** python, pandas, numpy, apply, lambda, explode

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

'/anvil/projects/tdm/data/amazon


=== Question 1 (2 points)

[loweralpha]
.. Using apply() and lambda function to rename the column names 
... From "HelpfulnessNumerator" to "helpNum"
... from "HelpfulnessDenominator"to "helpDen"


=== Question 2 (2 points)

 
.. Create a new data frame "review_mean" that contain the mean rate in the combined data frame for each product

=== Question 3 (2 points)

.. Use query or indexing to see what products have the highest rate
 

=== Question 4 (2 points)
.. Explore the explode() method, use explode() to extract a appropriate column from data frame to a list

Project 12 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project12.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project12.py`

* Submit files through Gradescope
==== 
 
[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
