= TDM 10200: Project 13 -- Spring 2024


**Motivation:** Use pandas to understand data through statistics and visualizations and communicate results. Visualize data and drawing conclusions from data and communicate base on the results. 

**Scope:** python, pandas, 

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

/anvil/projects/tdm/data/amazon
 
== Questions 

=== Question 1 (2 pts)


[loweralpha]
.. Use python to do calcuation for mean for the combined dataframe two_dfs, how long it takes?
.. Use numpy to do the same calcuation. How long it takes?
.. Use numpy to do the median and standard deviation score for the whole dataframe


 

=== Question 2 (2 points)
.. use pandas groupby to find out how many review counts for each product
.. use pandas groupby to find out the number of reviews for each year

  
=== Question 3 (2 points)

.. what is the total helpful numerator for the whole dataframe (total of column helpfulnessnumerator)
.. what is the total number helpful denominator for  the whole dataframe ?


=== FOUR
.. Visualize with a bar plot for scores
.. Visualize with a scatter plot for viewers

Project 13 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project13.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project13.py`

* Submit files through Gradescope
==== 
[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
