= TDM 10200: Project 12 -- Spring 2024


**Motivation:** Data analysis with Panda and numpy 

**Scope:** python, pandas, numpy, apply, lambda, pandas query

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

'/anvil/projects/tdm/data/amazon


=== Question 1 (2 points)

[loweralpha]
.. Read in the twoReviews.csv from last project and name it two_dfs. Using rename(),and dictionary to rename the column names. You may refer to rename [here] dictionary [here ]
... From "HelpfulnessNumerator" to "HelpfulnessNum"
... From "HelpfulnessDenominator"to "HelpfulnessDen"


=== Question 2 (2 points)
.. Use rename() and lambda function to rename the column names to all lowercase and remove "fulness" from the two columns. You may refer to apply [here] lambda function [here ]
... From "HelpfulnessNum" to "helpfulNum"
... From "HelpfulnessDen" to "helpfulDen"
 


=== Question 3 (2 points)

.. Use apply() and lambda function to create a new data field "text_len" that contains the text length for each review
 average score for for each product
.. Use apply and lambda function to create a new data field "help_ratio" that contains help_ratio calculated from helpnum and helpden
.. create a new dataframe the only contains help_ration greater than 0.8 and less than 0.9. How many records you get?




=== Question 4 (2 points)
.. Create a year field to only contain year from new_time field 
.. Use pandas query to select only year 2012 from two_dfs and assign to df_2012, then drop the column 'year'
.. Use pandas query to select only score less than 3 from df_2012 and assign to df_2012_3u
Project 12 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project12.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project12.py`

* Submit files through Gradescope
==== 
 
[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
