= TDM 10200: Project 3 -- 2023

**Motivation:** Learning about Big Data. When working with large data sets, its important to know how we can use loops to find our information a bit at a time. 
We will need to *set our cores to 4* for this when we spin up Juypter Notebook. This will require more space for us to handle processing this dataset. If we do not adjust the cores then our kernel will crash every time we try to run a cell. 


**Scope:** Python, If statements, for loops, 

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

/anvil/projects/tdm/data/flights

== Questions

=== ONE
First lets go ahead and see what files are in this dataset 

[source, python]
----
ls /anvil/projects/tdm/data/flights
----
This allows you to see all of the files that are in this dataset.
We are going to focus on years *1987-2008*

[loweralpha]
.. list the most recent year that is in this dataset
.. what would the path be to access just one file in this data set
.. Go ahead and import the library pandas as pd. AND Object-oriented filesystem paths we will refrence named pathlib go ahead and import Path

.Helpful Hints
[%collapsible]
====
[source, python]
----
/anvil/projects/tdm/data/flights/2003.csv

import pandas as pd
from pathlib import Path
----
====

.Items to submit
====
- Code used to answer the question. 
====



=== TWO
[source, python]
----
files = [Path(f'/anvil/projects/tdm/data/flights/subset/{year}.csv') for year in range(1987,2009)]
files
----
This code using list comprehension creates a list of file paths ranging from the years of 1987-2008
*`files`* will now contain strings of file paths for *all* the csv files. 

Lets test out the first file to see if we can find the column names
[loweralpha]
.. How many columns are there?
.. List the first 5 columns 

.Helpful Hints
[%collapsible]
====
#reads the first file into a df called `eightseven`
eightyseven = pd.read_csv(files[0])
#looks for column names from the df
column_names = eightyseven.columns
print(column_names)
====

.Items to submit
====
- Code used to answer the question. 
- Result of code.
====


=== THREE

Lets look at the column `Origin` 

[loweralpha]
.. print out the unique elements of the column 
.. find the number of times that 'IND' shows up in that column


.Helpful Hint
====
[source,python]
----
eightyseven['Origin'].value_counts()['IND']
----
====

.Items to submit
====
- Code used to answer the question.
- Result of the code
====

=== FOUR

Lets do something similar for 1988, 1989, 1990, naming them eightyeight, eightynine, ninety.

[loweralpha]
----
.. How many times does 'IND' show up in `eightyeight`
.. How many times does 'IND' show up in `eightynine`
.. How many times does 'IND' show up in `ninety`
----

.Items to submit
====
- Code used to answer questions
- Result of the code
====

=== FIVE

Knowing that we can find how many times the value 'IND' shows up in 'Origin' we could do this for each of the years and add them up to find the total that Indiana was the origin flight taken from years 1987-2008. But that is a lot of work!! We can shorten the tedious work of keeping track and adding by using a for loop to go thru all of the subset files and total the number of times 'IND' shows up in the 'Origins' column. 

We could use this code 
[source, python]
----
count = 0
for file in files:
    df = pd.read_csv(file)
    count += len(df[df['Origin'] == 'IND'])

print(count)
----
*BUT* before you go ahead and copy and paste, this code will take ALL of the files and read them into memory, this is destined to crash the kernel even if we upped the cores to 4. 

this means we have to think of another way to do it. 

We have to use `for loops` which is a way to iterate to check for certain conditions and repeatedly execute them. This is very helpful when you come across situations that you will need to use a specific code over and over again but you don't want to write the same line of code multiple times. 

We need to consider a way that will allow us to go thru the files line by line and read them but then not commit them to memory so we can go thru all lines of code and still keep track of how many of a specific value we have. 

[source,python]
----
total_count = 0
for file in files:
    for df in pd.read_csv(file, chunksize=10000):
        for index, row in df.iterrows():
            if row['Origin'] == 'IND':
                total_count += 1

print(total_count)
----

You will note that doing the  above code DOES produce the correct answer BUT it take a very long time to run 
is there a shorter way to run this code? 

.Helpful Hint
====
[source, python]
----
origin_ind = 0
for file in files:
    with open(file,'r') as f:
        for line in f:
            if line.split(",")[16] == 'IND':
                origin_ind += 1
print(origin_ind)
----
====



You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output, when in fact it does not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/current-projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or it does not render properly in gradescope. Please ask a TA if you need help with this.
====

A `.ipynb` file is generated by first running every cell in the notebook, and then clicking the "Download" button from menu:File[Download].

In addition to the `.ipynb`, if a project uses Python code., you will need to also submit a Python script. A Python script is just a text file with the extension `.py`.

Let's practice.  take the Python code from this project and copy and paste it into a text file with the `.py` extension. Call it `firstname-lastname-project01.py`. Download your `.ipynb` file -- making sure that the output from all of your code is present and in the notebook (the `.ipynb` file will also be referred to as "your notebook" or "Jupyter notebook").

Once complete, submit your notebook,and Python script.

.Items to submit
====
- `firstname-lastname-project01.py`.
- `firstname-lastname-project01.ipynb`.
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====