= TDM 10200: Project 4 -- 2024

**Motivation:** In the last project, we began exploring control flow, including if statements and for loops. In this project, we will delve deeper into the concept of loops. There are three main types of loops we'll focus on: for loops, while loops, and nested loops.


**Context:**  We will continue to work on some basic data types and go thru some similar control flow concepts  

**Scope:** loops, basic data structures such as tuples, lists, loops, dict


== Dataset

/anvil/projects/tdm/data/noaa/2022.csv

== Readings and Resources
[NOTE]
====
- Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

- Please review the following Examples Book Contents  
    - https://the-examples-book.com/programming-languages/python/dictionaries [Python dictionaries]
    - https://the-examples-book.com/programming-languages/python/tuples [Python tuples]
    - https://the-examples-book.com/programming-languages/python/lists [Python lists]
    - https://the-examples-book.com/programming-languages/python/pandas-dataframes [Python pandas DataFrames] 
    - https://the-examples-book.com/programming-languages/python/matplotlib [matplotlib]
==== 


== Questions

=== Question 1 (2 points)

[loweralpha]

.. Create a dictionary of capitals for the 10 states includes two states of "Indiana" and "Illinoi", call it `capitals`
.. Now add the two more capitals to it so it contains 12 state capitals
.. Delete the two states "Indiana" and illinois from the dictionary  

 
=== Question 2 (2 points)


.. Use a while loop to print a series of numbers from 0 to 200, counting by 10's

.. Put the phrase "Old McDonald had a farm e-i-e-i-o" into a string and call it `words`.   Print everything in the string *EXCEPT* the letter *a* 

.. Now take `words` and replace each occurrence of the symbol *-* with an asterisk ***


=== Question 3 (2 points)


[loweralpha]
.. Create a `for` loop 
.. Now add in the `enumerate()` function to your `for` loop.
.. Create a 'for' loop with the `range()` function
[Warning]
====
Notice that the indexing for our dataframe starts at 0. In `Python` and other programming languages, the indexing starts at 0. In contrast, during our previous semester, working in `R`, the indexing began at 1. This is an important fact to remember. 
====
 
=== Question 4 (2 points)

.. read in the dataset for file "2022.csv" and name it "weather"
+
[TIP]
====
[source, python]
----
import pandas as pd

weather = pd.read_csv("/anvil/projects/tdm/data/noaa/2022.csv",names = ["id","date","element_code","value","mflag","qflag","sflag","obstime"]))
----
====
.. From the dataset `weather` create a dictionary called `mydict` that contains key:value pairs for the first 10 records from the dataset weather

=== Question 5(2 points)


Project 04 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project04.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project04.py`

* Submit files through Gradescope
==== 

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====