= TDM 10200: Project 2 -- 2023

**Motivation:** In this project we are going to jump head first into The Data Mine. We will load datasets into  environment, and introduce some core programming concepts like variables, vectors, types, etc. As we will be "living" primarily in an IDE called Jupyter Lab, we will take some time to learn how to connect to it, configure it, and run code.

**Context:** This is our second project and we will continue to introduce some basic data types and go thru some similar control flow concepts like we did in `R`. 

**Scope:** tuples, lists, if statments, opening files

.Learning Objectives
****
- List the differences between lists & tuples and when to use each.
- Gain familiarity with string methods, list methods, and tuple methods.
- Demonstrate the ability to read and write data of various formats using various packages.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- /anvil/projects/tdm/data/death_records/DeathRecords.csv 

== Questions

=== ONE
`pandas` is an integral tool for various data science tasks in Python. You can read a quick intro [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html).

Lets first learn how to create a simple dataframe 
If we have a store that we only sell hats that are blue and white and shoes that are red and purple we will need to know what our customers are purchasing to keep inventory. 

[loweralpha]
.. 

.Insider Knowledge
[%collapsible]
====
`Pandas` is a great way to get aquainted with your data. Using `pandas` to clean, transform and analyze it. `Pandas` allows you to extract data from a CSV (comma- seprated values) file. 

The two main components of pandas are the `series` and `DataFrame`. A `series` is essential a column and a `DataFrame` is a table makde up of a collection of `series`. 
====


=== TWO
Open a new notebook in using the f2022-2023 kernel
We want to go ahead and read in the dataset /anvil/projects/tdm/data/death_records/DeathRecords.csv  into a `pandas` DataFrame called `myDF`. +

[loweralpha]
.. Find the information for the 11th row in the dataframe
.. Find the last five rows of the data frame
.. Find how many rows and columns there are in the entire dataframe

.Helpful Hint 
[%collapsible]
====
[source,python]
----
.head()
.tail()
.shape()
----
====


.Items to submit
====
- Result of code.
====


.Insider Knowledge
[%collapsible]
====
Numeric

. int - holds signed integers of non-limited length.
. long- holds long integers(exists in Python 2.x, deprecated in Python 3.x).
. float- holds floating precision numbers and it is accurate up to 15 decimal places.
. complex- holds complex numbers.

String - a sequence of characters, generally strings are represented by single or double-quotes

Lists- ordered sequence of data written using square brackets *[]* and commas *(,)*. 

Tuple- similar to a list but immutable. Data is written using a parenthesis *()* and commas *(,)*. 

Dictionary is an unordered sequence of data of key-value pair(two pieces of data that have a set of associated values, two related data elements). 
====
We are going to create a variable, we are assigning the numbers 1,2,3 to a variable called my_list. 

[source,python]
----
my_list = [1, 2, 3]
print(f'My list is: {my_list}')
----

We are going to practice assigning variable and doing some simple requests in Python

.One
.. create a variable named `x` and assign the number 6 to it 
.. create a variable named `y` and assign the number 8 to it 
.. create a variable named `z` and assign `x * y` to it 
.. now print `z`

.Two
.. assign `x,z,y` the same value of "peanutbutter" all in one line

.Three
.. assign the ingredients of a club sandwich to the variable `club_sandwich`

.Helpful Hint
[%collapsible]
====
To learn more about how to run various types of code using this kernel, see https://the-examples-book.com/projects/current-projects/templates[our template page].
====

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== THREE

This year, the first step to starting any project should be to download and/or copy https://the-examples-book.com/projects/current-projects/_attachments/project_template.ipynb[our project template] (which can also be found on Anvil at `/anvil/projects/tdm/etc/project_template.ipynb`). 

Open the project template and save it into your home directory, in a new notebook named `firstname-lastname-project01.ipynb`. 

Fill out the project template, replacing the default text with your own information, and transferring all work you've done up until this point into your new notebook. If a category is not applicable to you (for example, if you did _not_ work on this project with someone else), put N/A. 

.Items to submit
====
- How many of each types of cells are there in the default template?
====

=== FOUR
We are going to open up this ("/anvil/projects/tdm/data/disney/flight_of_passage.csv") dataset in Python. 

[source,python]
----
import pandas as pd
disney= read_csv("/anvil/projects/tdm/data/disney/flight_of_passage.csv")
disney
----

Using the Pandas library we are able to see This allows us to see how many rows and columns are in this dataset. Pandas is a data analysis library that is one of the most commonly used in Python. 


.Items to submit
====
- How many rows are in this data set?
- How many columns are in this dataset?
- Use the `heads()` and `tails()` to look at the beginning and end of the data. 
====

=== FIVE

Let's pretend we are now done with the project. We've written some code, maybe added some markdown cells to explain what we did, and we are ready to submit our assignment. For this course, we will turn in a variety of files, depending on the project.

We will always require a Jupyter Notebook file. Jupyter Notebook files end in `.ipynb`. This is our "source of truth" and what the graders will turn to first when grading. 

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output, when in fact it does not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/current-projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or it does not render properly in gradescope. Please ask a TA if you need help with this.
====

A `.ipynb` file is generated by first running every cell in the notebook, and then clicking the "Download" button from menu:File[Download].

In addition to the `.ipynb`, if a project uses Python code., you will need to also submit a Python script. A Python script is just a text file with the extension `.py`.

Let's practice.  take the Python code from this project and copy and paste it into a text file with the `.py` extension. Call it `firstname-lastname-project01.py`. Download your `.ipynb` file -- making sure that the output from all of your code is present and in the notebook (the `.ipynb` file will also be referred to as "your notebook" or "Jupyter notebook").

Once complete, submit your notebook,and Python script.

.Items to submit
====
- `firstname-lastname-project01.py`.
- `firstname-lastname-project01.ipynb`.
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====