= TDM 10200: Project 3 -- 2024

**Motivation:** Learning about Big Data. When working with large data sets, it is important to know how we can use control flow to find our information, a little bit at a time, without reading in all of the files at once. Control flow is the order that your code runs
 

**Scope:** Python, Control Flow, if statements, for loops

== Dataset(s)

/anvil/projects/tdm/data/noaa

== Readings and Resources

[NOTE]
====

- Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].
- Please review https://the-examples-book.com/programming-languages/python/control-flow[this] Examples Book content about Control Flow
====

== Questions

=== Question 1 (2 pts) 

[loweralpha]

.. Explore the files at the provided data set folder. Find out how many years include in the data set. Briefly describe a file's content
.. Import the library `pandas` as `pd`, and import `Path` from `pathlib`
.. Create a list named "files", to hold "Path" objects from "1980.csv" to "1983.csv" in the data set folder using "list comprehension". You may refer to the following sample code that created list with a for loop. Modify it to use "List comprehensions"  
+
[TIP]
====
- Following is the sample code that will return a "Path" object for file 1750.csv
[source,python]
Path("/anvil/projects/tdm/data/noaa/1750.csv")

- You may use a for loop to create a list of Path objects like
[source,python]
files=[]
for year in range (1980, 1983):
    file= Path(f'/anvil/projects/tdm/data/noaa/{year}.csv')
    files.append(file)
print(files)
====

=== Question 2 (2 pts)

[loweralpha]

.. Calculate how many records in file "1980.csv"
+
[TIP]
====
The following is the sample code to calculate records in one sample file object named "file"
[source, python]
with open(file,"r") as f:
    count =0
    for line in f:
        count+=1
print(f'There are {count} records in the {file}')

Output will be like (if for "1980.csv")

There are 33923709 records in the /anvil/projects/tdm/data/noaa/1980.csv
====
.. Calculate how many records in total for the files from "1980.csv" to "1983.csv" that "files" list contains

[TIP]
====
- You may use a for loop to iterate files object like
[source,python]
for file in files:
...# body of the for loop
====


=== Question 3 (2 pts)
.. Run the following statement to read in the first file of files object to a DataFrame  Display the column names for the sample_df
[source,python]
----
sample_df = pd.read.csv(files[0])
----
.. You may notice the output of question a does not look right, since the file does not have column titles. Modify the statement to add "header=None" argument and recreate the sample_df. What is the column names now?

.. Now let us add column titles for each column starts from first column as "id","date","element_code","value","mflag","qflag","sflag","obstime" respectively while read a file to a DataFrame. Use a list of DataFrames named "file_DFs" to hold 3 DataFrames from "1980.csv" to "1983.csv" that files contains. Refer to the following sample code for reading in the first file, add a for loop above it to read in 3 files
.. Display the data from the first five rows.
[TIP]
====
#reads one file "1980.csv" into a df called "file_df"

[source,python]
file_df = pd.read_csv(files[0],names = ["id","date","element_code","value","mflag","qflag","sflag","obstime"])
#looks for column names from the df
column_names = sampleDF.columns
print(column_names)

- You may use a list of DataFrame name
====

=== Question 4 (2 pts)

Let's look at the column `element_code` 

[loweralpha]
.. Print out the unique elements of this column.
.. Find the number of times that `AWDR` occurs in the `element_code` column.

[TIP]
====
[source,python]
----
sampleDF['element_code'].value_counts()['AWDR']
----
====
 

=== Question 5 (2 pts)

.. Find the number of times that AWDR` occurs in the `element_code` column from year 1910 to year 2020

Instead of using 
[source, python]
----
count = 0
for file in files:
    df = pd.read_csv(file)
    count += len(df[df['element_code'] == 'AWDR'])

print(count)
----
 
[source,python]
----
total_count = 0
for file in files:
    for df in pd.read_csv(file, chunksize=10000):
        for index, row in df.iterrows():
            if row['Origin'] == 'IND':
                total_count += 1

print(total_count)
----

Using
 
[TIP]
====
[source, python]
----
ind = 0
for file in files:
    with open(file,'r') as f:
        for line in f:
            if line.split(",")[16] == 'AWDR':
                ind += 1
print(origin_ind)
----
====
Project 03 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project03.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project03.py`

* Submit files through Gradescope
==== 

 

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
