= TDM 10200: Project 5 -- 2023

**Motivation:** Once we have some data analysis working in Python, we often want to wrap it into a function.  Dr Ward usually tests anything that he wrote (usually 5 times), to make sure it works, before wrapping it into a function.  Once we are sure our analysis works, if we wrap it into a function, it can usually be easier to use.


**Context:**  Functions also help us to put our work into bite-size pieces that are easier to understand.  The basic idea is similar to functions from R or from other languages and tools. 

**Scope:** functions

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

-/anvil/projects/tdm/data/craigslist/vehicles.csv

-/anvil/projects/tdm/data/flights/subset/

-/anvil/projects/tdm/data/death_records/DeathRecords.csv

[TIP]
====
I would _highly_ recommend taking the time to read through the entire article https://realpython.com/defining-your-own-python-function/[here]. It is a very detailed article going through all the things you can do with functions in Python. The section on https://realpython.com/defining-your-own-python-function/#argument-tuple-packing[tuple packing] and https://realpython.com/defining-your-own-python-function/#argument-tuple-unpacking[tuple unpacking] may be particularly useful to you!
====

[TIP]
====
https://realpython.com/defining-your-own-python-function/#default-parameters[This] section will review default parameters.
====

== Questions

=== ONE

Read in the dataset from Project 4

-/anvil/projects/tdm/data/craigslist/vehicles.csv

and name it `cars`.

[loweralpha]
.. Write a function called `mycarcount` that takes two parameters: `cars` as a data frame, and `year` as an integer, and outputs the number of cars from that `year`.
.. Run the function for each of the years from Project 4, Question 4, namely, for the years 2011, 1989, 1997.  Make sure that your answers agree with the results from that earlier project.


.Items to submit
====
- Code used to answer the question. 
- Result of code.
====



=== TWO


[loweralpha]
.. Run the function from question 1 for each year in the data set.  (Be sure to only run it once per year, not once per row!)
.. Now make sure that the results agree, if you compare with the `value_counts()` from the `year` column.



.Items to submit
====
- Code used to answer the question. 
- Result of code.
====



=== THREE

Use the csv data sets from this directory (the same as from Project 3):

-/anvil/projects/tdm/data/flights/subset/


[loweralpha]
.. Write a function that takes two parameters: `myorigin` as a string with three characters, and `year` as an integer, and outputs the number of flights that depart during that year, from the `Origin` airport indicated in `myorigin`.
.. Test your function for a few years and airports of your choice.
.. Run the function for each of the years from 1987 to 2008, checking how many flights depart from `IND` in each year.  Make sure that you use the method from the end of Project 3, Question 5


.Helpful Hint
[%collapsible]
====
[source,python]
----
total_count = 0
for df in pd.read_csv(putthefilenamehere, chunksize=10000):
    for index, row in df.iterrows():
        if row['Origin'] == myorigin:
            total_count += 1
----


.Items to submit
====
- Code used to answer the question. 
- Result of code.
====



=== FOUR

Extend your function from Question 3 as follows:

[loweralpha]
.. Modify your function so that it takes three parameters: `myorigin` and `mydest` as strings that each have three characters, and `year` as an integer, and outputs the number of flights that depart during that year, from the `Origin` airport indicated in `myorigin`, and arrive at the `Dest` airport indicated in `mydest`.
.. Test your function for a few years and pairs of airports of your choice.
.. Run the function for each of the years from 1987 to 2008, checking how many flights depart from `IND` and arrive at `ORD` in each year.


.Items to submit
====
- Code used to answer the question. 
- Result of code.
====


=== FIVE


Use the csv data set for the DeathRecords from Project 2:

-/anvil/projects/tdm/data/death_records/DeathRecords.csv


[loweralpha]
.. Write a function that takes three parameters: `Sex` (which will be `Female` or `Male`) and a `startingyear` and an `endingyear`, and outputs the number of people with the indicated `Sex` that are born between the `startingyear` and `endingyear` (inclusive).
.. Test your function for a few example inputs.


.Items to submit
====
- Code used to answer the question
- Result of the code 
====




[NOTE]
====
TA applications for The Data Mine are currently being accepted.Please visit us https://purdue.ca1.qualtrics.com/jfe/form/SV_08IIpwh19umLvbE[here] to apply!
====


[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====