= TDM 10200: Project 10 -- Spring 2024

**Motivation:** NumPy is the foundation that Pandas is built on. Mastering NumPy's numerical operations will enrich your understanding for numerical operations and data analysis.

**Context:** Hopeful you have found yourself understand well on Python foundation and pandas introductions. In this project we will delve into NumPy, enhancing your skill set for high performance computing without direct use pandas.

**Scope:** Python, pandas, NumPy 

== Reading and Resources

- Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here]
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html[Pandas read_csv]
- https://numpy.org/devdocs/user/index.html[NumPy user guide]
- https://numpy.org/devdocs/reference/index.html[Numpy reference]

== Dataset

`/anvil/projects/tdm/data/flights/2014.csv`

[WARNING]
====
You need to use 2 cores for your Jupyter Lab session for Project 10 this week.
====

[TIP]
====
You can use `pd.set_option('display.max_columns', None)` if you want to see all of the columns in a very wide data frame.
====

== Questions

=== Question 1 (2 points)

[loweralpha]
.. The dataset is 2.5 G. For this project, we will only need the following columns, so let us create a DataFrame with only those columns with corresponding data types.

[source,python]
----
cols = [
    'DepDelay', 'ArrDelay', 'Distance', 
    'CarrierDelay', 'WeatherDelay', 
    'DepTime', 'ArrTime', 'Diverted', 'AirTime'
]

col_types = {
    'DepDelay': 'float64', 
    'ArrDelay': 'float64', 
    'Distance': 'float64', 
    'CarrierDelay': 'float64', 
    'WeatherDelay': 'float64', 
    'DepTime': 'float64', 
    'ArrTime': 'float64', 
    'Diverted': 'int64', 
    'AirTime': 'float64'
}
----
[TIP]
====
- You may refer to https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html[pandas.read_csv] to know more about read only specific columns
====

=== Question 2 (2 points)
.. Use `to_numpy()` to create a numpy array called `mydelays`, containing the information from the column `DepDelay`.
.. Display the array's shape and data type.
.. Use `nan_to_num()` to replace all null values in the array to 0.
.. It can be helpful to know how to manipulate the values in an array!  Find the average time in `mydelays` by taking the numpy `mean()` of this array.  Afterwards, add 15 minutes to all of the departure delay times stored in `mydelays`.  Finally, use the numpy `mean()` method again, to calculate and display the average of the updated values in `mydelays`.  How do these two averages compare?

[NOTE]
====
- The output should look something like this:

.output
----
The average Departure Delay before adding 15 minutes is: .......

The average Departure Delay after adding 15 minutes is: .......
----
====

=== Question 3 (2 points)

.. Create a numpy array for column `ArrDelay`
.. Replace all null value to 0
.. Calculate and display the maximum arrival delay and min arrival delay

[NOTE]
====
- Sample output result like

.output
----
Max Arrival Delay: 2444.0 minutes 
Min Arrival Delay: -112.0 minutes
----
====


=== Question 4 ( 2 points)

Now let us compare the time we need to do calculation by pandas vs. numpy, solve the following 2 questions with pandas methods only

.. Create a array named "delayed_flights" to hold flights with either "departure delay > 60 minutes or arrival delay > 60 minutes"
.. Calculate the average distance for these flights
.. how long does the program take to get the average?

[TIP]
====
- You may import time() library to calculate the time spent like
[source,python]
----
import time
start_time = time.time()
#your program here
....
end_time = time.time()
print(f"Used time is {start_time - end_time}")
----
====

=== Question 5 (2 points)

Please using `numpy` methods to Calculate the average distance for question 4 

.. Create numpy arrays for `DepDelay`, `ArrDelay` and `Distance` separately.
.. Create a boolean array the hold the condition that 'departure delay > 60 minutes or arrival delay > 60 minutes'
.. Use the condition from 5b to filter the numpy array for `Distance` to get only Distances that satisfy the condition 
.. Use numpy `mean()` to calculate the average distance for those flights
.. How long does the program take to get the average?
.. Please state your understanding of pandas vs. numpy from Question 4 and 5


Project 10 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project10.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project10.py`

* Submit files through Gradescope
==== 
 
[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====


  