= TDM 10200: Project 5 -- 2024

**Motivation:** Once we have some data analysis working in Python, we often want to wrap it into a function. Dr Ward usually tests anything that he wrote (usually 5 times), to make sure it works, before wrapping it into a function.  Once we are sure our analysis works, if we wrap it into a function, it can usually be easier to use.


**Context:**  Functions also help us to put our work into bite-size pieces that are easier to understand.  The basic idea is similar to functions from R or from other languages and tools. 

**Scope:** functions

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Datasets

/anvil/projects/tdm/data/noaa/{year}.csv

== Reading and Resources

- Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].
- https://the-examples-book.com/programming-languages/python/writing-functions[Python Functions]
- https://www.fec.gov/campaign-finance-data/contributions-individuals-file-description/[Contributions by individuals file description] 

[NOTE]
====
- Please note the data set used in the examples book for https://the-examples-book.com/programming-languages/python/writing-functions[Python Functions] does not contain headers. You may refer to - https://www.fec.gov/campaign-finance-data/contributions-individuals-file-description/[Contributions by individuals file description] to find out how to determine the column descriptions.
====

== Questions

=== Question 1 (2 points)

[loweralpha]

.. Write a function called "avg_aggreg_temp" that takes 5 parameters: the file path as string , column_title_list as list for column titles, start date as integer, end date as integer, temperature element code as string which default value is "TAVG"; outputs a float number of average temperature  
.. Run the function for data set 2018.csv with date range 20180101 to 20180115

[NOTE]
====
- Dataset does not include column tile, so column_title_list=["id","date","element_code","value","mflag","qflag","sflag","obstime"]
- Dataset is about 2.2 GB, so use chunksize argument to read in data, set chunksize = 10000
- data type for "value" column is integer. So the start_date and end_date are integers as yyyymmdd
- You will need to include docstring for the function definition
====
  

=== Question 2 (2 points)
 
.. Create a function to display the list of years annual average trend for a specified element code
.. Run the function for year 1880 to 1883

[TIP]
====
- Create a files list to hold the file names for 1880.csv to 1883.csv, like following, you may need to modify sample codes to fit it into your program
[source,python]
files = [f'/{year}.csv' for year in range(1880,1884)]
- Include column titles ["id","date","element_code","value","mflag","qflag","sflag","obstime"]
====
 
=== Question 3(2 points)

.. Create a function to display the years' month average trend for a specified element code
.. Run the function for year 1880 to 1883 and months are January, May, and October 
 

=== Question 4 (2 points)

.. Create a function to find out the year with most "qflags" that user specified
.. Run the function for year 1880 to 1883, and "qflgs" value as "T"


=== Question 5 (2 points)

.. Explore the dataset files at the folder of "noaa", create one your own function that you feel interested. Make sure have docstring include in the function definition. 
.. Run your function and explain the output that if it meets the expectation.


Project 05 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project05.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project05.py`

* Submit files through Gradescope
==== 


[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====