= TDM 10200: Project 6 -- 2024
**Motivation:** Once we have some data analysis working in Python, we often want to wrap it into a function.  Dr Ward usually tests anything that he wrote (usually 5 times), to make sure it works, before wrapping it into a function.  Once we are sure our analysis works, if we wrap it into a function, it can usually be easier to use.


**Context:**  Functions also help us to put our work into bite-size pieces that are easier to understand.  The basic idea is similar to functions from R or from other languages and tools. 

**Scope:** functions

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Examples Book Content

Please review the following Examples Book Contents  
- https://the-examples-book.com/programming-languages/python/writing-functions [Python Functions]
- https://the-examples-book.com/programming-languages/python/dictionaries [Python dictionaries]
- https://the-examples-book.com/programming-languages/python/tuples [Python tuples]
- https://the-examples-book.com/programming-languages/python/lists [Python lists]
- https://the-examples-book.com/programming-languages/python/pandas-dataframes [Python pandas DataFrames] 
- https://the-examples-book.com/programming-languages/python/matplotlib [matplotlib]

== Datasets

/anvil/projects/tdm/data/noaa

[NOTE]
====
You can read https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/readme.txt[here] about what the data means.

. 11 character station ID
. 8 character date in YYYYMMDD format
. 4 character element code (you can see the element codes https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/readme.txt[here] in section III)
. value of the data (varies based on the element code)
. 1 character M-flag (10 possible values, see section III https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/readme.txt[here])
. 1 character Q-flag (14 possible values, see section III https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/readme.txt[here])
. 1 character S-flag (30 possible values, see section III https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/readme.txt[here])
. 4 character observation time (HHMM) (0700 = 7:00 AM) -- may be blank
====
 

== Questions

=== Question 1 (2 points)

 

[loweralpha]
.. Modify your "averageTemp" as save as "averageTemp_years" function from Project 5, so that it takes a list of years' weather data as a parameter, and prints the average of temperature for selected date range from each year in your list.
.. Now test your `averageTemp_years` function on the list of years `[2011, 1989, 1997]`. 



=== Question 2 (2 points)

[loweralpha]
.. Write a loop that prints the total precipitations for year 2014 to 2022 
.. Now write a double-loop that prints the 5 stations total precipitations for year 2014 to 2022 

=== Question 3 (2 points)

[loweralpha]
.. Write a function with two arguments: a list of locations/stations, and a list of years.  The function should print a listing that shows the total precipitations from each of those locations in each of those years.
 .. Use your new function to re-create the answer to question 2b.
.. Test your function on some lists of locations and lists of years of your choice.

 

=== Question 4 ( 2 points)


[loweralpha]Write a loop that prints the total snowfall (element_code as 'SNOW') for the winter months (December, January, February) of each year from 2015 to 2020.
(I.e., you should have 6 lines of output.)
 
.. Write a function "snowfall_years" with two arguments: a list of locations/stations, and a list of years to calculate the total snowfall (element_code as 'SNOW') for  each year listed  
.. Test your function on some lists of locations and lists of years of your choice.
[TIP]
====
Again, for this question, you should not read the full data frame all at once, but instead, you should just a few lines at a time, using the `chunksize = 10000` and the `iterrows` like in the videos.
====

Project 05 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project05.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project05.py`

* Submit files through Gradescope
==== 


[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====