= TDM 20100: Project 5 -- 2023

**Motivation:** `awk` is a programming language designed for text processing. It can be a quick and efficient way to quickly parse through and process textual data. While Python and R definitely have their place in the data science world, it can be extremely satisfying to perform an operation extremely quickly using something like `awk`. 

**Context:** This is the first of three projects where we introduce `awk`. `awk` is a powerful tool that can be used to perform a variety of the tasks that we've previously used other UNIX utilities for. After this project, we will continue to utilize all of the utilities, and bash scripts, to perform tasks in a repeatable manner.

**Scope:** awk, UNIX utilities

.Learning Objectives
****
- Use awk to process and manipulate textual data.
- Use piping and redirection within the terminal to pass around data between utilities.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- `/anvil/projects/tdm/data/stackoverflow/unprocessed/2011.csv`

- `/anvil/projects/tdm/data/iowa_liquor_sales/iowa_liquor_sales_cleaner.txt`

[NOTE]
====
While the UNIX tools we've used up to this point are very useful, `awk` enables many new capabilities, and can even replace major functionality of other tools.

`awk` is a text-processing tool in Unix, it scans and processes text based on patterns. `awk` is a versatile tool, ideally for tasks such as columnar data manipulation, pattern scanning, field-based calculations, and file formatting tasks, all performed efficiently from the command line.

Here is an example to use `awk` to print the header line of file `/anvil/projects/tdm/data/stackoverflow/unprocessed/2011.csv`

[source,bash]
awk 'NR==1 {print}' filename.txtx


* `NR==1`: only for the first line.
* `{print}`: action when the condition is true. It prints the entire line.


In a previous question, we asked you to use commands `head`, `tr` and `wc` to find out how many times does the character 'A' appear in the first 10 lines of the file /anvil/projects/tdm/data/stackoverflow/unprocessed/2011.csv. We can use `awk` to  perform the same operation 
[source,bash]
awk 'NR<=10 {a+=gsub(/A/,"")} END {print a}' /anvil/projects/tdm/data/stackoverflow/unprocessed/2011.csv

* `NR<=10`: limits to the first 10 lines.
* `numberofA+=gsub(/A/,"")`: using `gsub` function in `awk` to replace 'A' with a empty value,then add that 1 to a variable to count how many 'A's encountered
* `END {print a}`: at end,prints the final count of 'A'.
====

== Questions

=== Question 1 (1 pt)
[upperalpha]
.. How many times does the word 'WHISKIES' appear in the last 5 lines of the file?

[TIP]
* use tail to get the last 5 lines of the file
[source,bash]
tail -n 5 filename.txt
* use `\<` and `\>` word boundary markers to enclose the word to search, so it will not part of another word

=== Question 2 (1 pt)

[upperalpha]

.. In a previous question, we used `sort` in combination with `uniq` to find  which 5 items have the highest 'state bottle retail' price from the file /anvil/projects/tdm/data/iowa_liquor_sales/iowa_liquor_sales_cleaner.txt
Now please just use `awk` to find which 5 items have the highest 'state bottle retail' price from the file 

[TIP]
====
* Sorting an array by values in `awk` can be confusing. Check out https://stackoverflow.com/questions/5342782/sort-associative-array-with-awk[this excellent stackoverflow post] to see a couple of ways to do this. "Edit 2" is the easiest one to follow.

* You can pipe output to the `column` unix command to get neatly formatted output! 

[source,bash]
----
man column
----
====


=== Question 3
[upperalpha]
.. Please compute the total volume (in liters) of `VODKA 80 PROOF` sold in the file iowa_liquor_sales_cleaner.txt. Do this using _only_ `awk` to sum the volume of this specific category. 

[TIP]
====
`gsub` is a powerful awk utility that allows you to replace a string with another string. For example, you could replace all `,`'s in field 23 with nothing by:

----
gsub(/,/, "", $23)
----
====

[NOTE]
====
The `gsub` operation happens in-place. In a nutshell, what this means is that the original field, `$23` is replaced with the result of the `gsub` operation (which removes the commas).
====
 

=== Question 4

Please compute the total volume (in liters) of `VODKA 80 PROOF` sold _by county_. Do this using _only_ `awk`. Format your output so it looks like the following.

.output
----
FRANKLIN: 33536.88 Liters
GRUNDY: 32453.35 Liters
DICKINSON: 275542.34 Liters
O'BRIEN: 73413.50 Liters
CHEROKEE: 44019.56 Liters
RINGGOLD: 9068.05 Liters
----

Notice anything odd about the result? Look carefully at the dataset and suggest an alternative method that would clean up the issue.

[TIP]
====
You can see the issue in our tiny sample of output.
====


=== Question 5 (2 pts)

[upperalpha]
.. `awk` is extremely powerful, and this liquor dataset is pretty interesting! We haven't covered everything `awk` (and we won't). Look at the dataset and ask yourself an interesting question about the data. Use `awk` to solve your problem (or, at least, get you closer to answering the question). Explore various stackoverflow questions about `awk` and `awk` guides online. Try to incorporate an `awk` function you haven't used, or a `awk` trick you haven't seen. While this last part is not required, it is highly encouraged and can be a fun way to learn something new.

[NOTE]
====
You do not need to limit yourself to _just_ use `awk`, but try to do as much using just `awk` as you are able.
====

Project 05 Assignment Checklist
====
* Jupyter Lab notebook with your code and comments for the assignment
    ** `firstname-lastname-project05.ipynb`.
* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====