= TDM 20100: Project 11 -- 2023

**Motivation:** Databases are (usually) comprised of many tables. It is imperative that we learn how to combine data from multiple tables using queries. To do so we perform "joins"! In this project we will explore learn about and practice using joins on our  database, as it has many tables where the benefit of joins is obvious.

**Context:** We've introduced a variety of SQL commands that let you filter and extract information from a database in an systematic way. In this project we will introduce joins, a powerful method to combine data from different tables.

**Scope:** SQL, sqlite, joins

.Learning Objectives
****
- Briefly explain the differences between left and inner join and demonstrate the ability to use the join statements to solve a data-driven problem.
- Perform grouping and aggregate data using group by and the following functions: COUNT, MAX, SUM, AVG, LIKE, HAVING.
- Showcase the ability to filter, alias, and write subqueries.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)


For this project, we will be using the `lahman` sqlite database. This database contains the data in the directory  

- `/anvil/projects/tdm/data/lahman`

You may get some more `lahman` database information from this youtube video http://youtube.com/watch?v=tS_-oTbsDzs
[2023 SABR Analytics:Sean Lahman, "introduction to Baseball Databases"]

To run SQL queries in a Jupyter Lab notebook, first run the following in a cell at the top of your notebook to establish a connection with the database.

[source,python]
----
%sql sqlite:////anvil/projects/tdm/data/lahman/lahman.db
----

For every following cell where you want to run a SQL query, prepend `%%sql` to the top of the cell -- just like we do for R or bash cells.

== Questions

=== Question 1 (2 pts)

In the previous project, you already understand how to get data from single table.   

Now that we are learning about _joins_, we have the ability to make much more interesting queries!
[NOTE]
====
You may get more information on joins here
====
[NOTE]
====
Table `batting` contains a field H (hits) and a field AB (at-bats), we can calculate the batting average(BA) by the formula 

AVG = H/AB

A higher batting average is an indicator to show a batter's ability to produce offensively. 

You may get more batting average information from wikipedia

====

.. Please find the bottom 10 players with lowest batting average for year 2022. Use batting table inner join people table to get players first name, last name. The output will contain playerID, player first name, player last name and battingAverage   


=== Question 2 (2 pts)
[NOTE]
====
When considering batting average, pitchers often have a significantly lower bating average for they are not trained hitters. To focuse on regular batters, pitchers need to be excluded.
.. Use `appearances` table to find out the players who are pitchers for year 2022
G_p>0
.. Write a query that exclude those pitcher from the question 1 query for the year 2022

=== Question 3 (2 points)
 
In the question 2, instead of subquery, we can use left join to accomplish the task

.. Modify your query from question (2) to use left join to get the 10 players with lowest batting 
Average 

     
=== Question 4 (2 pts)


.. Write another query to find out what is the average batting average for all players ( exclude pitchers) in year 2022 

Project 11 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project11.ipynb` 
* Submit files through Gradescope
====



[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====

