= TDM 20100: Project 9 -- 2023

**Motivation:** Although SQL syntax may still feel unnatural and foreign, with more practice it will start to make more sense. The ability to read and write SQL queries is a "bread-and-butter" skill for anyone working with data.

**Context:** We are in the second of a series of projects that focus on learning the basics of SQL. In this project, we will continue to harden our understanding of SQL syntax, and introduce common SQL functions like `AVG`, `COUNT`, and `MAX`.

**Scope:** SQL, sqlite

.Learning Objectives
****
- Describe basic database concepts like: RDBMs, tables, fields, query, clause,etc.
- Basic clauses: select, order by, limit, desc, asc, count, where, from,group by etc.
- Utilize SQL functions like max, avg, sum, count, cast,round etc. 
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

For this project, we will be using the `lahman` sqlite database. This database contains the data in the directory  

- `/anvil/projects/tdm/data/lahman`

You may get some more `lahman` database information from this youtube video http://youtube.com/watch?v=tS_-oTbsDzs
[2023 SABR Analytics:Sean Lahman, "introduction to Baseball Databases"]

To run SQL queries in a Jupyter Lab notebook, first run the following in a cell at the top of your notebook to establish a connection with the database.

[source,ipython]
----
%sql sqlite:////anvil/projects/tdm/data/lahman/lahman.db
----

For every following cell where you want to run a SQL query, prepend `%%sql` to the top of the cell -- just like we do for R or bash cells.

== Questions

[NOTE]
In previous projects, we used `awk` to parse through and summarize data. While `awk` is extremely convenient and can work well, but SQL is even better.

[IMPORTANT]
====
Make sure all queries limit output to only 100 rows. You may refer to https://www.sqlitetutorial.net/sqlite-limit/  [SQLite-Limit Syntax]
If you want the headers to be more descriptive, you can use aliases.You may refer to https://www.tutorialspoint.com/sqlite/sqlite_alias_syntax.htm [SQLite-aliases Syntax]

====
 
=== Question 1 (2 pts)

.. Write a query to find out who won the 2022 World Baseball Series from table `seriespost`?
.. For this champion team, please find out the home runs (hr) rate and runs batted in (rbi) rate in year 2022 from table `batting`. Round the rates to 2 decimals. You may get rates by 
   * hr_rate = sum of home runs / sum of hits 
   * rbi_rate = sum of runs batted in / sum of hits

[TIP]
====
Use the `sum` aggregate function to calculate the totals, and division to figure out the percentages(rates).
`cast`is useful to convert integer to real number to do calculation, e.g.
[source, sql]
select cast (HR AS REAL) from batting
.. Try to do calculation without `cast`, what do you get?
`round` is useful to round a decimal.
====

=== Question 2 (2 pts)

.. For the champion team from question 1, please write a query that counts the number of RBI for each athlete in team at year 2022 using `batting` table, display output in ascending order
.. Run the query again and display the output in descending order, 
.. Which athlete has the highest RBI from previous question? Please provide the player's playerID along with first name and last name from `people` table

[TIP]
====
* Use `group by` to group for each athlete
* Use `order by` to sort the output 
====


=== Question 3 (2 pts)

.. Write a query that gets the how many times the athlete from question 2 attended All Star Games
.. Write a query to find out who is the athlete that attended most times of All Star Games in the data set


=== Question 4 (1 pt)

.. Write a query that gets the average `salary` for each athlete in the database. Display in descending order Limit output in 100 rows. 

=== Question 5 (1 pt)

Now create your own query to describe the information you are interested, use at least one of aggregation functions such as `min`, `max`, `count` or `sum`. Be sure to use `group by` and display in order with `order by`
 
Project 09 Assignment Checklist
====
* Jupyter notebook with your code, comments and output for questions 1 to 5
    ** `firstname-lastname-project09.ipynb`
* Submit files through Gradescope
====


[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====

