= TDM 20100: Project 7 -- 2023
:page-mathjax: true

**Motivation:** `awk` is a programming language designed for text processing. It can be a quick and efficient way to quickly parse through and process textual data. While Python and R definitely have their place in the data science world, it can be extremely satisfying to perform an operation extremely quickly using something like `awk`.

**Context:** This is the third of three projects where we introduce `awk`. `awk` is a powerful tool that can be used to perform a variety of the tasks that we've previously used other UNIX utilities for. After this project, we will continue to utilize all of the utilities, and bash scripts, to perform tasks in a repeatable manner.

**Scope:** awk, awk arrays, UNIX utilities

.Learning Objectives
****
- Use awk arrays to efficiently store sets of data
- Use awk and functions to process and manipulate data.
- Use piping and redirection within the terminal to pass around data between utilities.
****
Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)
- `/anvil/projects/tdm/data/iowa_liquor_sales/iowa_liquor_sales_cleaner.txt`
- `/anvil/projects/tdm/data/election/escaped2020sample.txt`
- `/anvil/projects/tdm/data/flights/1990.csv`

[NOTE]
====
In `awk`, arrays are associative, meaning you can store data with key-value pairs. This makes it very efficient to manage data, especially for large files.  We can manage to index our data in easier ways than in other programming languages.
Awk arrays are versatile and powerful tools: you can index them using strings and numbers.
====

=== Question 1 ( 2 pts)
[loweralpha]
In Project 05's Question 2, you were asked to use the dataset `iowa_liquor_sales_cleaner.txt` to find out which Store Name had the most purchases, and once got store name, calculated the total cost from this store. Now let us using `awk arrays` to list top 10 stores' purchases and total costs 

.. List number of purchases for top 10 stores   (not the largest total cost, but the largest number of purchases; please consider each line to be 1 purchase)
.. List the total cost of all purchases from top 10 stores   

=== Question 2 (2 pts)

[loweralpha]

.. Let us look at dataset `escaped2020sample.txt`. It contains columns of STATE (column 10), CITY( column 9) and TRANSACTION_AMT (column 15). Please calculate the total transaction amounts for each city from this dataset and list top 10 cities with total transaction amounts. Please use awk array for this question.

[TIP]
====
* Use `gsub` to remove `"` for data fields if needed
* Since there have some cities share same city names but in different state, need to combine state and city to differentiate them
====

[NOTE]
====
* In `awk`, arrays can also be passed to functions as arguments, it makes data operations or processing based on the associative nature of these arrays very efficient.
====

=== Question 3 ( 2 pts)

[loweralpha]
.. Now let us take a look at the dataset `1990.csv`. You may have noticed that the "FlightDate" column (6th column) contains with dates formatted as "1990-01-31".Please write an awk command to extract the year, month from this column and then reformat them as "01/1990". Make sure to use the functions `split` and `gsub` in your solution
 
[TIP] 
====
Start with first 10 lines to verify output, then to manipulate with all data, use `cat`  
====

=== Question 4 (2 pts)

[loweralpha]
.. Use `awk` to create a new dataset from `1990.csv` called `1990_flight_info.csv`, the new dataset will include the following columns, flight_month(MM/YYYY) same as you created in question 3, delay total should sum in minutes

.columns
----
flight_month;departure_delay_total;arrive_delay_total;distance_total 
----

[TIP] 
====
Use `>` to _redirect_. You can output from the `awk` command to a new file with this operator. If you were to replace `>` by `>>` it would _append_ instead of _replace_. In other words, if you use a single `>` it will first erase the output file before adding the results of the `awk` command to the file. If you use `>>`, it will append the results
====

[NOTE] 
====
Make sure to submit the file `1990_flight_info.csv` when you upload your files to Gradescope.
====

Project 07 Assignment Checklist
====
* Jupyter notebook with your code, comments and output for questions 1 to 4
    ** `firstname-lastname-project07.ipynb`.
* A `.sh` text file with all of your `bash` code and comments written inside of it
    ** bash code and comments used to solve questions 1 through 5
* The output file from question 4, called:  1990_flight_info.csv
* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                   
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====