= TDM 20200: Project 4 -- 2024

**Motivation:** Being able to analyze and create good visualizations is a skill that is invaluable in many fields. It can be pretty fun too! In this project, we are going to dive into plotting using "plotly" of Python version, a very popular open source graphing library that can interact graphs online.

**Context:** Create good visualizations about the flight data using "plotly". In the next project, we will continue to learn about and become comfortable using `plotly`.

**Scope:** Python, visualizations, plotly

.Learning Objectives
****
- Demonstrate the ability to create basic graphs with default settings.
- Demonstrate the ability to modify axes labels and titles.
- Demonstrate the ability to customize a plot (color, shape/linetype). 
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- "/anvil/projects/tdm/data/zillow/Metro_time_series.csv"


== Readings and Resources

[NOTE]
====
- Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].
- You may refer to https://plot.ly/python[plot introduction]
- Read plotly express functions on https://plotly.com/python/plotly-express/[this] page. 
- https://plotly.com/python/axes/
====

== Questions

=== Question 1 (2 points)
[loweralpha]
.. Read in the data and called it "df", create a sub DataFrame from "2010 to 2015"
.. Plot a line chart to show the overall housing inventory through years. Make sure your plot has labels for the x axis, y axis, and overall plot.

[TIP]
====
.. Please use 'fig.show(renderer="jpg")' for all of your plots to show the plots user friendly
.. You will need to use 'fig.update_xaxes' or 'fig.update_layout' to make your x axis labels in tone. Refer to "Set axis label rotation and font" on https://plotly.com/python/axes/[this page].
====


=== Question 2(2 points)
.. Use a bar chart to visualize the top 5 regions with the highest inventory of homes. 
.. Use a bar chart to visualize the the top 5 regions with the oldest inventory of homes
=== Question 3(2 points)

.. Use a box plot to visualize the the top 5 regions with the oldest inventory of homes
.. Use a box plot to visualize the the top 5 regions with the youngest inventory of homes

=== Question 4(2 points)

.. Use scatter plot to visualize the regions that have the highest median percentage of price reduction for all homes


=== Question 5 (2 points)

.. Now that you've been exploring data visualization with different kind of plots. Please state the situations when you use those different types of plots. 

Project 04 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project04.ipynb` 
* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.

In addition, please review our xref:projects:current-projects:submissions.adoc[submission guidelines] before submitting your project.
====