= TDM 20200: Project 1 -- 2024


**Motivation:** Understand website basic knowledge such as HTML/XML, CSS, Javascript; Python basic knowledge warm up and basic Beautiful Soup Concepts

**Context:** In this project we will use warm up with website and python basic concepts and start practicing web scraping with beautifulSoup 

**Scope:** HTML, CSS, python, BeautifulSoup

.Learning objectives
****
- Review web, python basic concepts  
- Understand web scraping basic concepts 
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].
 

== Questions

[IMPORTANT]
====
It would be well worth your time to:

. Read the https://the-examples-book.com/starter-guides/data-formats/html[HTML  
. Finally, take the time to work through https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html[`pandas` 10 minute intro].
====

=== Question 1 (2 points) 


.. Review the source code for datamine example book webpage, please list the webpage itmes a basic webpage with HTML, to include following items for each the following elements
...3 headings ;3 Paragraph; 2 lists;1 image; 3links;

=== Question 2 (2 points)
.. Create a .css file with following selector
... element selector(s);class selector(s);id selector(s);attribute selector(s);universal selector
.. Update the html page with the CSS file, assign class and attribute to tags

=== Question 3(2 points)
.. import BeautifulSoup, and find the following items in your own html file 
.. find all links and use a loop to print each of links  
.. find all tags with one attributes and print the elements
.. find one class inside the webpage and and print out the item related to the class

=== Question 4 (2 points)

.. Create a empty CSV file.Parsing your HTML file with Beautifulsoup for the purdue sports website
... Get the a head element as "title" and following paragraph(s) as description(s) and save the contents to the csv file 




Project 01 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project01.ipynb`.
* Python file with code and comments for the assignment
    ** `firstname-lastname-project01.py`

* Submit files through Gradescope
==== 


[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.

In addition, please review our xref:projects:current-projects:submissions.adoc[submission guidelines] before submitting your project.
====