= TDM 20200: Project 11 -- 2024
 
**Motivation:** Machine learning and AI are huge buzzwords in industry, in this project, we will continue to know more TensorFlow features    

**Context:** The purpose of these projects is to give you exposure to machine learning tools, some basic functionality, conceptual workflow to create and use a model without needing any special math or statistics background

**Scope:** Python,tensorflow, scikit-learn,numpy

== Dataset

`/anvil/projects/tdm/data/flights/2019.csv`

== Readings and Resources

[NOTE]
====
- Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html[Pandas read_csv]
- https://scikit-learn.org/stable/documentation.html[scikit-learn documentation]
- https://scikit-learn.org/stable/tutorial/index.html[scikit-learn tutorial]
- https://www.tensorflow.org/tutorials[tensorflow tutorial]
- https://www.youtube.com/tensorflow[youtube for tensorflow]
- https://joblib.readthedocs.io/en/latest/why.html[joblib dump() load()]
- https://proclusacademy.com/blog/explainer/regression-metrics-you-must-know/[metrics]
====

[WARNING]
====
You need to use 2 cores for your Jupyter Lab session for Project 11 this week.
====
[TIP]
====
You can use `pd.set_option('display.max_columns', None)` if you want to see all of the columns in a very wide data frame.
====

== Questions

=== Question 1 (2 points)

[loweralpha]

In the previous project you created a tensorflow model with limited data. Since it would need large data in order to create a meaningful tensorflow model, your model may not work well but we can just learn how we can create, and use the model and how to check the performance power of the model. 
.. Now update your program so it can save the `scaler' and created `model',  set nrows = 100000 (read in 100000 rows data from training dataset "2014.csv")

[NOTE]
====
-  You may import `dump` from `joblib` library to save files
-  You may refer to https://joblib.readthedocs.io/en/latest/why.html[joblib document]
====


=== Question 2 (2 points)

 
.. Use joblib load to load the model and use it to predict 10000 rows arrival delays for dataset of "2019.csv" 
.. Save the predicted arrival array and name it "predictions_100k"
.. Save the 10000 rows real arrival Delay array as "predictions_100k"
[NOTE]
====
- You may refer to https://joblib.readthedocs.io/en/latest/why.html[joblib document]
====
 
 
=== Question 3 (2 points)


.. Now let us change the nrows = 500000 and redo the question 1
.. Use the model to do prediction 10000 rows data and named predicted arrival delay array "predictions_500k"   
.. Save the 10000 rows real arrival Delay array as "predictions_500k"
 
=== Question 4 ( 2 points)

.. Calculate 3 metrics mae, mse, rmse for the two models  performance by the following example function, you may need to update or use your own function. Your outputs may similar to the following example output


[source,python]
----
def pre_act_analysis(predictions, actuals):
    mae = np.mean(np.abs(predictions - actuals))
    mse = np.mean((predictions - actuals) ** 2)
    rmse = np.sqrt(mse)
    return mae, mse, rmse
----

.output

List 1 - MAE: 46.673773999568716, MSE: 12943.643871909986, RMSE: 113.7701361162497
List 2 - MAE: 54.503407120307486, MSE: 12905.609543586266, RMSE: 113.60285887065636


[NOTE]
====
- You may refer to https://proclusacademy.com/blog/explainer/regression-metrics-you-must-know/[here] to find more information about the metrics
- You may need to use numpy arrays
====

=== Question 5 ( 2 points)

.. Based on the results from previous questions, please describe your thoughts and the way(s) you think to improve the models 

Project 11 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and outputs for the assignment
    ** `firstname-lastname-project11.ipynb` 
* Python file with code and comments for the assignment
    ** `firstname-lastname-project11.py`
 
* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.

In addition, please review our xref:projects:current-projects:submissions.adoc[submission guidelines] before submitting your project.
====