= TDM 30200: Project 8 -- 2023
:page-mathjax: true

**Motivation:** Machine learning and AI are huge buzzwords in industry, in next two project we wil introduce `tensorflow` library, a popular library used to build and use complex models. If available, they can take advantage of GPUs to speed up parallelize code by a hundred or even thousand fold.

**Context:** The purpose of these projects is to give you exposure to AI tools, some basic functionality, and to show _why_ they are useful, without needing any special math or statistics background.  

**Scope:** Python, tensorflow

== Dataset

`/anvil/projects/tdm/data/flights/2014.csv`

== Readings and Resources

[NOTE]
====
- Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].
- 
====

[WARNING]
====
You need to use 2 cores for your Jupyter Lab session for Project 9 this week.
====
[TIP]
====
You can use `pd.set_option('display.max_columns', None)` if you want to see all of the columns in a very wide data frame.
====


== Questions

=== Question 1 (2 points)
[loweralpha]

.. Load and Prepare Data- Write a TensorFlow code snippet to load the dataset into a TensorFlow 'Dataset' object, splitting it into training and testing sets. Considering the appropriate preprocessing for both numerical and categorical variables 
 

=== Question 2 (2 points)


.. Build a Simple Neural Network using Keras to predict arrival delay 'ArrDelay' from available features, include at least one hidden layer
 

=== Question 3 ( 2 points)


.. Show how to compile the model created in Question 4. specifying an appropriate loss function, optimizer and metrics for a regression problem

=== Question 4 ( 2 points)


.. Training with GPU - Demonstrate how to ensure that TensorFlow trains the model using a GPU, including the necessary code to verify that TensorFlow is indeed utilizing the GPU

=== Question 5 (2 points)


.. Evaluate the Model- Write the code to evaluate the model's performance on the test set. Discuss what metrics would be appropriate for assessing the performance of a model predicting flight delays and how to interpret these metrics. 

Project 10 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and outputs for the assignment
    ** `firstname-lastname-project10.ipynb` 
* Python file with code and comments for the assignment
    ** `firstname-lastname-project10.py`
 
* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.

In addition, please review our xref:projects:current-projects:submissions.adoc[submission guidelines] before submitting your project.
====