= TDM 20200: Project 02 -- 2024

**Motivation:** Web scraping is the process of taking content off of the internet. Typically this goes hand-in-hand with parsing or processing the data. In general, scraping data from websites has always been a popular topic in The Data Mine. We will use the website of "books.toscrape.com" to practice scraping skills

**Context:** In the previous project we gently introduced XML and xpath parse a XML document. In this project, we will introduce web scraping, learn some basic web scraping skills using BeautifulSoup

**Scope:** Python, web scraping, BeautifulSoup

.Learning Objectives
****
- Understand webpage structures
- Use BeautifulSoup to scrape data from web pages
****

== Readings and Resources

[NOTE]
====
- Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].
- https://www.dataquest.io/blog/tutorial-an-introduction-to-python-requests-library/[This] link will provide you more information about python requests library
- https://www.crummy.com/software/BeautifulSoup/bs4/doc/[This] link will provide you more information about BeautifulSoap
====

== Questions

=== Question 1 (2 points)
 
[loweralpha]
.. Please use BeautifulSoup to get and display the website's HTML source code ("https://books.toscrape.com")
.. Review the code you got and find out what is the title for the webpage?

[TIP]
====
You may refer to the following to import libraries, modify the code to fit into yours
[source,python]
import requests
from bs4 import BeautifulSoup
...# define url
response = requests.get(url)
soup = BeautifulSoup(response.content,'html.parser')
====
 
=== Question 2 (2 points)
 
.. Please use BeautifulSoup library to get and display all categories' names from the homepage of the website

[TIP]
====
- Review the page source code, find "categories" located at the sidebar under a div tag with class is "nav-list" The BeautifulSoup "select" method is useful to get category, like this:

[source,python]
soup.select('.nav-list li a')
====


=== Question 3 (2 points)

.. Now instead of only getting name of categories, get the all category links from the homepage as well
+
[TIP]
====
- Review the homepage source code, explore where is the category links locate, You may use "find" to get the "div" section

[source,python]
soup.find('div',class = 'side_categories')

- Under "div" section, the links can be found in the "a" tag. You may use "find_all" to get all category links
[source,python]
find_all('a')

- You may refer to the following code to exclude "books" from the category list since it is not part of the category 
# Assume "link" hold a category link information

[source,python]
link.get('href').startswith("catalogue/category/books/")
 
- Output will look like

----
Category: Travel,link: catalogue/category/books/travel_2/index.html
Category: Mystery,link: catalogue/category/books/mystery_3/index.html
....
----
====

.. Update the code from question a to get the category of "Romance" link only, and create the url for "Romance" category based on this link 

[TIP]
====
- Output will be like 
----
romance_url is http://books/toscrape.com/catalogue/category/books/romance_8/index.html
----
====

=== Question 4 (2 points)

.. Use the "Romance" link from Question 3 to get the webpage source code for Romance category web page
.. Display all book titles in the first page of the romance category 


 
=== Question 5 (2 pts)

.. Please get the next page link from Romance category web page using BeautifulSoup and create a url for next page of Romance category web page
+
[TIP]
====
You may need to manipulate and combine basic url of Romance category web page (http://books/toscrape.com/catalogue/category/books/romance_8/index.html) with relative hyperlink you get for next page. The following is sample code for your reference

[source,python]
----
# need to remove last part from basic url
url= "http://books/toscrape.com/catalogue/category/books/romance_8/index.html"
url=url.rsplit('/',1)[0]
# Assume you get next hyperlink ""category/page-2.html" as next,need to only keep last part 
next_link = next.split("/")[-1]
#Combine
next_url=url+"/"+next_link
----
====
.. List all books from the second page of the "Romance" category  



Project 02 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project02.ipynb` 
* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.

In addition, please review our xref:projects:current-projects:submissions.adoc[submission guidelines] before submitting your project.
====