= TDM 30100: Project 13 -- 2023

**Motivation:** Containers are everywhere and a very popular method of packaging an application with all of the requisite dependencies. This project we will learn some basics of containerization in a virtual environment using Alpine Linus

**Context:** This is a first of a series of projects focused on containers. The end goal of this series is to solidify the concept of a container, and enable you to "containerize" the application you've spent the semester building. You will even get the opportunity to deploy your containerized application!

**Scope:** Python, containers, UNIX

.Learning Objectives
****
- Improve your mental model of what a container is and why it is useful.
- Use UNIX tools to effectively create a container.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Questions

=== Question 1 (1 pt)
[loweralpha]

.. Logon to anvil and use a bash command to find an available port you may use later. Just need to list 1 available port number 
 
[TIP]
====
- You may use the following code to find port from range 1025 to 65535, please edit if needed or run you own code
- You may use a loop to do it for you instead of manually try one by one
[source, bash]
if timeout 2 bash -c ">&/dev/tcp/127.0.0.1/1025" 2>/dev/null; then
    echo "Port used"
else
    echo "Port available"
====

=== Question 2 (2 pts)

.. Launch a virtual machine (VM) on Anvil with Docker pre-installed. Submit the output of job id and process id after you start a virtual machine like
.output
[1] 3152048
.. List the docker version inside the virtual machine

[NOTE]
====
The most popular containerization tool at the time of writing is likely Docker. We will Launch a virtual machine on Anvil with Docker pre-installed

First thing is first. Open up a terminal on Anvil. You may do it from within Jupyter Lab, run the following code to ensure that SLURM environment variables don't alter or effect our SLURM job 

[source,bash]
----
for i in $(env | awk -F= '/SLURM/ {print $1}'); do unset $i; done;
----

Next, let's make a copy of a pre-made operating system image. This image has Alpine Linux and a few basic tools installed, including: nano, vim, emacs, and Docker. 

[source,bash]
----
cp /anvil/projects/tdm/apps/qemu/images/builder.qcow2 $SCRATCH
----

Next, we want to acquire enough resources (CPU and memory) to not have to worry about something not working. To do this we will use SLURM to launch a job with 4 cores and about 8GB of memory.

[source,bash]
----
salloc -A cis220051 -p shared -n 4 -c 1 -t 04:00:00
----

Next, we need to make `qemu` available to our shell. Open a terminal and run the following code

[source,bash]
----
module load qemu
# check the module loaded
module list
----

Next, let's launch our virtual machine with about 8GB of memory and 4 cores. Replace the "[port]" with port number you got from question 1

[source,bash]
----
qemu-system-x86_64 -vnc none,ipv4 -hda $SCRATCH/builder.qcow2 -m 8G -smp 4 -enable-kvm -net nic -net user,hostfwd=tcp::[port]-:22 &
----

[IMPORTANT]
====
- [port] need to be replaced
====

Next, its time to connect to our virtual machine. We will use `ssh` to do this.

[source,bash]
----
ssh -p [port] tdm@localhost -o StrictHostKeyChecking=no
----

If the command fails, try waiting a minute and rerunning the command -- it may take a minute for the virtual machine to boot up.

When prompted for a password, enter `purdue`. Your username is `tdm` and password is `purdue`.

Finally, now that you have a shell in your virtual machine, you can do anything you want! You have superuser permissions within your virtual machine! 
For this question, submit a screenshot showing the output of `hostname` from within your virtual machine!

====

[TIP]
====
- You may get your docker version with 
[source, python]
docker --version
====

=== Question 3 (2 pts)

.. Exploring the virtual machine File System. Navigate the Alpine Linux file system and list the contents of the root directory.
.. List all running processes in the system 
.. Display network configuration and test network connectivity.
[TIP]
====
- You may refer to the following sample code or create your own ones
# list all root files
[source, bash] 
ls /
# system running processes
[source, bash]
ps aux
# network interface configuration
[source,bash]
ifconfig
# reachability to purdue.edu
[source, bash]
ping -c 4 purdue.edu

====

=== Question 4 (1 pts)

.. Installing a new package 'htop' using the Alpine package manager (apk).

[TIP]
====
- some sample codes

[source, bash]
#ensure you're installing the latest version of htop.
sudo apk update

# use apk to install
[source, bash]
sudo apk add htop
# run to ensure it works
[source, bash]
htop

====

=== Question 4 (2 pts)
.. Write and execute a simple shell script

[source, bash]
echo 'echo Hello Your name , You are the Best!!!' > hello.sh
chmod +x hello.sh
./hello.sh
 

Project 13 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments and output for the assignment
    ** `firstname-lastname-project13.ipynb` 
* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.

In addition, please review our xref:projects:current-projects:submissions.adoc[submission guidelines] before submitting your project.
====