= TDM 30100: Project 4 -- 2023

**Motivation:** Documentation is one of the most critical parts of a project. https://notion.so[There] https://guides.github.com/features/issues/[are] https://confluence.atlassian.com/alldoc/atlassian-documentation-32243719.html[so] https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis[many] https://www.gitbook.com/[tools] https://readthedocs.org/[that] https://bit.ai/[are] https://clickhelp.com[specifically] https://www.doxygen.nl/index.html[designed] https://www.sphinx-doc.org/en/master/[to] https://docs.python.org/3/library/pydoc.html[help] https://pdoc.dev[document] https://github.com/twisted/pydoctor[a] https://swagger.io/[project], and each have their own set of pros and cons. Depending on the scope and scale of the project, different tools will be more or less appropriate. For documenting Python code, however, you can't go wrong with tools like https://www.sphinx-doc.org/en/master/[Sphinx], or https://pdoc.dev[pdoc].

**Context:** This is the second project in a 2-project series where we explore thoroughly documenting Python code, while solving data-driven problems.

**Scope:** Python, documentation

.Learning Objectives
****
- Use Sphinx to document a set of Python code.
- Use pdoc to document a set of Python code.
- Write and use code that serializes and deserializes data.
- Learn the pros and cons of various serialization formats.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- `/anvil/projects/tdm/data/apple/health/watch_dump.xml`


=== Question 4 (1 pt)
.. Add autodoc configuration to your `conf.py` file, regenerate your documentation, and take a picture of the resulting webpage.

The `pdoc` package was specifically designed to generate documentation for Python modules using the docstrings _in_ the module. As you may have noticed, this is not "native" to Sphinx. 

Sphinx has https://www.sphinx-doc.org/en/master/usage/extensions/index.html[extensions]. One such extension is the https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html[autodoc] extension. This extension provides the same sort of functionality that `pdoc` provides natively.

To use this extension, modify the `conf.py` file in the `docs/source` folder. 

[source,python]
----
# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc'
]
----

Next, update your `index.rst` file so autodoc knows which modules to extract data from.

[source,rst]
----
.. project3 documentation master file, created by
   sphinx-quickstart on Wed Sep  1 09:38:12 2021.
   You can adapt this file completely to your liking, but it should at least
   contain the root `toctree` directive.

Welcome to project3's documentation!
====================================

.. automodule:: firstname_lastname_project03
    :members:

.. toctree::
   :maxdepth: 2
   :caption: Contents:

   README

Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
----

In a new `bash` cell in your notebook, regenerate your documentation. Check out the resulting `index.html` page, and click on the links. Not too bad!

.Items to submit
====
- Screenshot labeled "question03_results". Make sure you https://the-examples-book.com/projects/current-projects/templates#including-an-image-in-your-notebook[include your screenshot correctly].
- OR a PDF created by exporting the webpage.
====

=== Question 5 (2 pts)
.. Import the appropriate extensions so that Sphinx recognizes Google_style docstrings.
.. Create a new function, `graph_avg_heart_rate`, that graphs the average heart rate for all dates in our watch data.
.. Regenerate your documentation, and take a picture of the resulting webpage.

Okay, while the documentation looks pretty good, clearly, Sphinx does _not_ recognize Google style docstrings. As you may have guessed, there is an extension for that.

Add the `napoleon` extension to your `conf.py` file.

[source,python]
----
# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon'
]
----

Next, we would like you to write a new function called `graph_average_heart_rate` that graphs the average heart rate for all dates in our watch data. The type of graph your function generates is up to you, but it should be a meaningful and well-labeled graphic that demonstrates something about the data (i.e. shape, outliers, etc.). Make sure to include a Google style docstring for your function.

[TIP]
====
When writing more complicated functions, think about the steps they need to do. For example, our function needs to do the following:

for each date in our data: +
- get the records for that date +
- get the average heart rate for that date +
- add the average heart rate to a list of averages +

Then, finally, graph the list of averages.

I think simply by looking at this pseudocode in combination with the functions you wrote for previous questions, you should be able to get a good idea of how to structure and write this function.
====

In a new `bash` cell in your notebook, regenerate your documentation. Check out the resulting `index.html` page, and click on the links. Much better! Take a final screenshot of your `index.html` page, and include it in this question's submission section

.Items to submit
====
- function `graph_avg_heart_rate` with a Google style docstring.
- Regenerated final documentation to recognize Google style docstrings.
- Screenshot labeled "question05_results". Make sure you https://the-examples-book.com/projects/current-projects/templates#including-an-image-in-your-notebook[include your screenshot correctly].
====

// ==== Question 6 (1 pts)

.Items to submit
====
For this project, please submit the following files:

- The `.ipynb` file with:
  - all functions throughout the project, demonstrated to be working as excpected.
  - every different bash command used to call Sphinx at least once
  - screenshots whenever we asked for them in a question
  - An `.html` file with your newest set of documention.
====


[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====