= TDM 30100: Project 8 -- 2023

**Motivation:** Images are everywhere, and images are data! We will take some time to dig more into working with images as data in this series of projects.

**Context:** In the previous projects, we worked with images and implemented image Histogram Equalization, with some pretty cool results! In this project, we will continue to work with images key features, introduce YCbCr color space, and perform enhancing the image's visual quality by histogram equalization technique with colors

**Scope:** Python, images, openCV, Histogram equalization, YCbCr, image digital fingerprint

.Learning Objectives
****
- - Process images using `numpy`, `matplotlib`, and `openCV`.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- `/anvil/projects/tdm/data/images/ballpit.jpg`

[NOTE] 
====
As in our previous projects, by default, a image is read in as a `RGB` image, where each pixel is represented as a value between 0 and 255, R represents "red", G represents "green", and B represents "blue". While it is natural for display with RGB, image with `YCbCr` format has advantages in many image processing, compression situations etc.

`YCbCr` is a color space used in image processing. Y stands for "Luminance", Cb stands for "Chrominance Blue", Cr stands for "Chrominance red". You may get more information for `YCbCr` from https://en.wikipedia.org/wiki/YCbCr[YCbCr] 

`YCbCr` can be derived from the RGB color space. There are several Python libraries can be used to do the conversion, in this project we will use cv2 from OpenCV
[source, python]
import cv2
rgb_img=cv2.imread(('/anvil/projects/tdm/data/images/ballpit.jpg'))
ycbcr_img = cv2.cvtColor(img,cv2.COLOR_BGR2YCrCb)
====

== Questions

=== Question 1 (2 pts)

[loweralpha]
.. Please split `/anvil/projects/tdm/data/images/ballpit.jpg` into its `YCbCr`components and display them

 
[TIP]
====
To display the YCbCr Y component, you will need to set the Cb and Cr components to 127. To display the Cb component, you will need to set the Cr and Y components to 127, etc.  
====
 
[NOTE] 
====
The human eye is more sensitive to luminance than to color. As you can tell from the previous question, the Y component captures the luminance, and contains the majority of the image detail that is so important to our vision. The other Cb and Cr components are essentially just color components, and our eyes aren't as sensitive to changes in those components.
Luminance shows the brightness of an image. An RGB image can be converted to a YCbCr image. The histogram equalization then can apply to the luminance without impacting the color channels (Cb and Cr channels), which, if histogram equalization directly applies to an RGB image, it may cause image artifacts issues. "Artifacts issues" refers to unwanted distortion in an image.
Let's process some images in the following questions to makes this explicitly clear
====

=== Question 2 (2 pts)

[loweralpha]
.. Please write a function named `equal_hist_rgb` to do Histogram Equalization directly to an image with RGB format. The parameter will be an image. The returns will be a Histogram Equalized colored image. Run the function with input `ballpit.jpg`. Show the output Histogram Equalized colored image.


=== Question 3 (2 pts)
[loweralpha]
 
.. Please write a function named `equal_hist_YCrCb` that applies Histogram Equalization to an image, so that first the image will be converted from RGB format to YCrCb format, then apply Histogram Equalization. The parameter will be an image. The returns will be a Histogram Equalized colored image. Run the function with image `ballpit.jpg`. Show the output Histogram Equalized colored image.

[TIP]
====
We can read a 3-chanel RGB image by both `openCV cv2` and `matplotlib.image`. However, please do notice the output for cv2 is in BGR order but for matplotlib.image is in RGB order.

`cv2.split()` will be useful to split the image to 3 channels
`cv2.equalizeHist()` will be useful to do histogram equalization. 
`cv2.merge()` will be useful to combine all channels back to an equalized image

====
=== Question 4 (2 pts)

[loweralpha]
.. Please plot the original image of `ballpit.jpg`, output images of it from question 2 and question 3 as a combined chart.  What is your conclusion?

  
Project 08 Assignment Checklist
====
* Jupyter Lab notebook with your codes, comments and outputs for the assignment
    ** `firstname-lastname-project08.ipynb`.
 
* Submit files through Gradescope
====
[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
