= TDM 30200

All of the projects are in a Jupyter notebook and contain the instructions and links to materials needed to be successful for that project. Each week we will release a folder that contains the notebook (as well as supplementary data or images). The general process to retrieve and work on each project is:

0. Make a Seminar directory and get the fetch_projects_30200 notebook (Do This Once)
1. Use the fetch_projects Notebook to Retrieve Project Each Week
2. Finish the Project
3. Submit to Gradescope

== 0. Make a Seminar directory and get the Fetch Project notebook (Do This Once)

Run the following in a terminal on Anvil:

[source,bash]
----
mkdir $HOME/seminar/tdm_30200/
cp /anvil/projects/tdm/seminar/tdm_30200/fetch_projects_30200.ipynb $HOME/seminar/
----

== 1. Use the fetch_projects_30200 Notebook to Retrieve Project Each Week

Each week you can open this notebook, go to the corresponding week, and run the bash command to retrieve the notebook.

== 2. Finish the Project

Once fetched, the project will appear in your home directory (in the `seminar` folder).

== 3. Submit to Gradescope

Go to Gradescope and submit the code like usual (see https://the-examples-book.com/projects/current-projects/submissions).