= TDM 30200

== Project links

[NOTE]
====
Only the best 10 of 14 projects will count towards your grade.
====

[CAUTION]
====
Topics are subject to change. While this is a rough sketch of the project topics, we may adjust the topics as the semester progresses.
====

[%header,format=csv,stripes=even,%autowidth.stretch]
|===      
include::current-projects:example$30200-2023-projects.csv[]
|===

[WARNING]
====
Projects are **released on Thursdays**, and are due 1 week and 1 day later on the following **Friday, by 11:55pm**. Late work is **not** accepted. We give partial credit for work you have completed -- **always** submit the work you have completed before the due date. If you do _not_ submit the work you were able to get done, we will _not_ be able to give you credit for the work you were able to complete.

**Always** double check that the work that you submitted was uploaded properly. See xref:current-projects:submissions.adoc[here] for more information.

Each week, we will announce in Piazza that a project is officially released. Some projects, or parts of projects may be released in advance of the official release date. **Work on projects ahead of time at your own risk.**  These projects are subject to change until the official release announcement in Piazza.
====

== Piazza

[NOTE]
====
Piazza links remain the same from Fall 2022 to Spring 2023. 
====

=== Sign up

https://piazza.com/purdue/fall2022/tdm30100[https://piazza.com/purdue/fall2022/tdm30100]

=== Link

https://piazza.com/purdue/fall2022/tdm30100/home[https://piazza.com/purdue/fall2022/tdm30100/home]

== Syllabus

Navigate to the xref:spring2023/syllabus.adoc[syllabus].
