= TDM 40100: Project 3 -- 2023

**Motivation:** The ability to use SQL to query data in a relational database is an extremely useful skill. What is even more useful is the ability to build a `sqlite3` database, design a schema, insert data, create indexes, etc. This series of projects is focused around SQL, `sqlite3`, with the opportunity to use other skills you've built throughout the previous years.

**Context:** In TDM 20100 you had the opportunity to learn some basics of SQL, and likely worked (at least partially) with `sqlite3` -- a powerful database engine. In this project (and following projects), we will branch into SQL and `sqlite3`-specific topics and techniques that you haven't yet had exposure to in The Data Mine.

**Scope:** `sqlite3`, lmod, SQL
 
.Learning Objectives
****
- Create your own `sqlite3` database file.
- Analyze a large dataset and formulate `CREATE TABLE` statements designed to store the data.
- Run one or more queries to test out the end result.
- Demonstrate the ability to normalize a series of database tables.
- Wrangle and insert data into database.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- `/anvil/projects/tdm/data/goodreads/datadownloadsAugust2023/goodreads_book_authors.json`
- `/anvil/projects/tdm/data/goodreads/datadownloadsAugust2023/goodreads_book_series.json`
- `/anvil/projects/tdm/data/goodreads/datadownloadsAugust2023/goodreads_books.json`
- `/anvil/projects/tdm/data/goodreads/datadownloadsAugust2023/goodreads_reviews_dedup.json`

== Questions

If for whatever reason you didn't do the previous project, please run the following code in a Jupyter notebook to craete a `sqlite3` database called `my.db` in your `$HOME` directory (this is the code you wrote in the previous project, so you can skip this if you already did it). Feel free to move it into a subdirectory if you would like.

In case you skipped the previous project, let's all get on the same page. You run the following code in a Jupyter notebook to create a `sqlite3` database called `my.db` in your `$HOME` directory.

[source,ipython]
----
%%bash

rm $HOME/my.db
sqlite3 $HOME/my.db "CREATE TABLE reviews (
	user_id TEXT, 
	book_id INTEGER,
	review_id TEXT,
	rating INTEGER,
	review_text TEXT,
    date_added TEXT,
    date_updated TEXT,
    read_at TEXT,
    started_at TEXT,
    n_votes INTEGER,
    n_comments INTEGER
);"

sqlite3 $HOME/my.db "CREATE TABLE books (
	isbn TEXT,
    text_reviews_count INTEGER,
    country_code TEXT,
    language_code TEXT,
    asin TEXT,
    is_ebook INTEGER,
    average_rating REAL,
    kindle_asin TEXT,
    description TEXT,
    format TEXT,
    link TEXT,
    publisher TEXT,
    num_pages INTEGER,
    publication_day INTEGER,
    isbn13 TEXT,
    publication_month INTEGER,
    edition_information TEXT,
    publication_year INTEGER,
    url TEXT,
    image_url TEXT,
    book_id TEXT,
    ratings_count INTEGER,
    work_id TEXT,
    title TEXT,
    title_without_series TEXT
);"

sqlite3 $HOME/my.db "CREATE TABLE authors (
	average_rating REAL,
    author_id INTEGER,
    text_reviews_count INTEGER,
    name TEXT,
    ratings_count INTEGER
);"

sqlite3 $HOME/my.db "CREATE TABLE series (
	numbered INTEGER,
    note TEXT,
    description TEXT,
    title TEXT,
    series_works_count INTEGER,
    series_id INTEGER,
    primary_work_count INTEGER
);"
----

[source,ipython]
----
%sql sqlite:////home/x-myalias/my.db
----

[source,ipython]
----
%%sql

SELECT * FROM reviews limit 5;
----

[source,ipython]
----
%%sql

SELECT * FROM books limit 5;
----

[source,ipython]
----
%%sql

SELECT * FROM authors limit 5;
----

[source,ipython]
----
%%sql

SELECT * FROM series limit 5;
----

[source,ipython]
----
%%bash

rm -rf $HOME/goodreads_samples
mkdir $HOME/goodreads_samples
cp /anvil/projects/tdm/data/goodreads/datadownloadsAugust2023/goodreads_book_authors.json $HOME/goodreads_samples/
cp /anvil/projects/tdm/data/goodreads/datadownloadsAugust2023/goodreads_book_series.json $HOME/goodreads_samples/
shuf -n 25600 /anvil/projects/tdm/data/goodreads/datadownloadsAugust2023/goodreads_books.json > $HOME/goodreads_samples/goodreads_books.json
shuf -n 94200 /anvil/projects/tdm/data/goodreads/datadownloadsAugust2023/goodreads_reviews_dedup.json > $HOME/goodreads_samples/goodreads_reviews_dedup.json
----

=== Question 1 (1 pt)
[upperalpha]
.. Rename the `image_url` column from the `books` table to `book_cover`.
.. Show via a Before/After query that the column was renamed successfully.

In the last project, we created a whole bunch of tables and columns to store our data. As of yet, however, they are still quite empty. Before we start populating them with data, we should always double check our field names and make sure they are as concise and descriptive as possible. As you will likely see in the future, tables with data in them are much more tricky to modify than empty tables.

Before we start, let's get a quick look at `books` by running the below command to show all the current column names in our table.

[source,ipython]
----
%%sql
SELECT * FROM books LIMIT 0;
----

[TIP]
====
If running the above code gives you an error relating to 'DATABASE_URL variable not set', make sure you are running the line of code that establishes a connection to your database first. This snippet is provided above, and is succinctly equivalent to `%sql sqlite:////filepath/to/database/my.db`.
====

First, let's rename the `image_url` column from the `books` table. This name doesn't tell us what the image even has to do with. Instead, let's name the column `book_cover`, which tells us that this column contains all the image URLs for the covers of the books.

Remember, there is a wealth of online resources related to SQL that you can use to help you solve this problem. However, if you are having trouble figuring out where to start, the SQL `RENAME` command will be a good direction to start moving in.

After renaming our column, let's verify our change by again querying all the columns in `books`.

.Items to submit
====
- Code to rename the column `image_url` to `book_cover`.
- Before and After query to show successful rename.
====

=== Question 2
[upperalpha]
.. basfjksakhkfd
.. ajkfhadkksjfhkdsfh

Check out a line of the `goodreads_books.json` data:

[source,ipython]
----
%%bash

head -n 1 $HOME/goodreads_samples/goodreads_books.json
----

[TIP]
====
Don't have a `goodreads_samples` directory? Run the last snippet of code above Question 1 (it starts with `rm -rf`) to create it. This directory is covered in more detail in the previous project, so it would be a good idea (although not strictly necessary) to reread that project before continuing.
====

Recall that in the previous project, we just ignored the following fields from the `books` table: `series`, `similar_books`, `popular_shelves`, and `authors`. We did this because those fields are more complicated to deal with.

Read https://docs.microsoft.com/en-us/office/troubleshoot/access/database-normalization-description[this] article on database normalization from Microsoft. We are going to do our best to _normalize_ our tables with these previously ignored fields taken into consideration. Write 2-3 sentences in a markdown cell on the differences between 1st, 2nd, and 3rd normal forms, and the importance of normalizing our database.

To elaborate on the provided reading material, let's briefly discuss primary and foreign keys. 

A 'primary key' can be thought of as a unique piece of information that all of the data in that row is tied to. For example, if I have an `employees` table with salary information, names, emails, phone numbers, and employee ids, the primary key would likely be the `employee_id` as it is unique to each employee. 

A 'foreign key' is a piece of information that is a primary key in another table. For example, if I have a `departments` table with department names and department ids, the primary key for that table, `department_id` could be used as a foreign key in the `employees` table in order to indicate what department an employee is in. 

Let's begin getting into 1st form by setting some practical naming conventions. Note that these are not critical by any stretch, but can help remove some guesswork when navigating a database with many tables and ids.

Remember, we created 4 tables:
- `reviews`
- `books`
- `authors`
- `series`

Go through each of these tables and make the following changes:
. Every table's primary key should be named `id`, unless it is a composite key (more on these later). For example, instead of `book_id` in the `books` table, it would make sense to call that column `id` because `book` is implied from the table name.
. Every table's foreign key should reference the `id` column of the foreign table and be named "foreign_table_name_id". For example, if we had a foreign key in the `books` table that referenced an author in the `authors` table, we should name that column `author_id`.
. Keep table names plural, when possible -- for example, not the `book` table, but the `books` table.
. Link tables or junction tables should be named by the two tables which you are trying to represent the many-to-many relationship for. (We will go over this one specifically when needed, no worries)

Make the appropriate changes to the following `CREATE TABLE` statements that reflect these conventions as much as possible (for now).

[source,ipython]
----
%%bash

rm $HOME/my.db
sqlite3 $HOME/my.db "CREATE TABLE reviews (
	user_id TEXT, 
	book_id INTEGER,
	review_id TEXT,
	rating INTEGER,
	review_text TEXT,
    date_added TEXT,
    date_updated TEXT,
    read_at TEXT,
    started_at TEXT,
    n_votes INTEGER,
    n_comments INTEGER
);"

sqlite3 $HOME/my.db "CREATE TABLE books (
	isbn TEXT,
    text_reviews_count INTEGER,
    country_code TEXT,
    language_code TEXT,
    asin TEXT,
    is_ebook INTEGER,
    average_rating REAL,
    kindle_asin TEXT,
    description TEXT,
    format TEXT,
    link TEXT,
    publisher TEXT,
    num_pages INTEGER,
    publication_day INTEGER,
    isbn13 TEXT,
    publication_month INTEGER,
    edition_information TEXT,
    publication_year INTEGER,
    url TEXT,
    image_url TEXT,
    book_id TEXT,
    ratings_count INTEGER,
    work_id TEXT,
    title TEXT,
    title_without_series TEXT
);"

sqlite3 $HOME/my.db "CREATE TABLE authors (
	average_rating REAL,
    author_id INTEGER,
    text_reviews_count INTEGER,
    name TEXT,
    ratings_count INTEGER
);"

sqlite3 $HOME/my.db "CREATE TABLE series (
	numbered INTEGER,
    note TEXT,
    description TEXT,
    title TEXT,
    series_works_count INTEGER,
    series_id INTEGER,
    primary_work_count INTEGER
);"
----

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 3

A book can have many authors, and an author can have many books. This is an example of a many-to-many relationship. 

We already have a `books` table and an `authors` table. Create a _junction_ or _link_ table that effectively _normalizes_ the `authors` **field** in the `books` table. Call this new table `books_authors` (see point 4 above -- this is the naming convention we want).

Make sure to include your `CREATE TABLE` statement in your notebook.

[TIP]
====
There should be 4 columns in the `authors_books` table. A primary key field, two foreign key fields, and a regular data field that is a part of the original `authors` field data in the `books` table.
====

[IMPORTANT]
====
Make sure to properly apply the https://www.sqlitetutorial.net/sqlite-primary-key/[primary key] and https://www.sqlitetutorial.net/sqlite-foreign-key/[foreign key] keywords.
====

Write a SQL query to find every book by author with id 12345. It doesn't have to be perfect syntax, as long as the logic is correct. In addition, it won't be runnable, that is okay.

[TIP]
====
You will need to use _joins_ and our junction table to perform this query.
====

Copy, paste, and update your `bash` cell with the `CREATE TABLE` statements to implement these changes. In a markdown cell, write out your SQL query.

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 4

Assume that a series can have many books and a book can be a part of many series. Perform the same operations as the previous problem (except for the query).

What columns does the `books_series` table have?

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 5

The remaining two fields that need to be dealt with are `similar_books` and `popular_shelves`. Choose _at least_ one of the two and do your best to come up with a good solution for the way we store the data. We will give hints for both below.

For this question, please copy, paste, and update the `bash` cell with the `CREATE TABLE` statements. In addition, please include a markdown cell with a detailed explanation of _why_ you chose your solution, and provide at least 1 example of a query that _should_ work for your solution (like before, we are looking for logic, not syntax).

**similar_books:**

[TIP]
====
It is okay to have a link table that links rows from the same table!
====

[TIP]
====
There are always many ways to do the same thing. In our examples, we used link tables with their own `id` (primary key) in addition to multiple foreign keys. This provides the flexibility of later being able to add more fields to the link table, where it may even become useful all by itself.

There is, however, a _technically_ better solution for a table that is simply a link table and nothing more. This would be where you have 2 columns, both foreign keys, and you create a _composite_ primary key, or a primary key that is represented by the unique combination of both foreign keys. This ensures that links are only ever represented once. Feel free to experiment with this if you want!
====

**popular_shelves:**

[TIP]
====
You can create as many tables as you need.
====

[TIP]
====
After a bit of thinking, this one may not be too different than what you've already accomplished.
====

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
