= TDM 40100: Project 7 -- 20223
:page-mathjax: true

**Motivation:** Images are everywhere, and images are data! We will take some time to dig more into working with images as data in this series of projects.

**Context:** In the previous project, we learned to manipulate image's basic factors by methods from openCV `cv2` module. In this project, we will understand key image features, detect color dominance, assess contrast, and perform enhancing the image's visual quality by histogram equalization technique

**Scope:** Python, images, openCV, skimage

.Learning Objectives
****
- Process images using `numpy`, `skimage`, and `openCV`. 
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- `/anvil/projects/tdm/data/images/ballpit.jpg`
 

== Questions

=== Question 1 (2 pt)

[loweralpha]

.. Let's work with our `ballpit.jpg` again. In project 06, we split the image into its color channels (red, green and blue). With outputs for its color channels, please find out the average values of intensity for each channel
.. Display the average values for each channel with a bar chart. Briefly explain what is your finding from the bar chart

[NOTE]
====
* The average pixel values for the 3 channels can show the whole brightness of the image, reveal which color dominant the image, as well as image temperature - warm (reddish), cool(blueish)
* The average values of intensity of an image is calculated by summing up the intensity values of all pixels and dividing by the total number of pixels. Intensity is the value of a pixel. For grayscaled image, it has value from Black to white; for color image in RGB, each pixel has 3 intensity values for R,G and B respectively.  
====
[TIP]
====
* Average value can be calculated using numpy `mean()`
==== 

=== Question 2 ( 2 pts)

.. In project 06, you created a red mask for red pixels and applied the red mask to the original image. Please create another 2 masks for green and blue channels 
.. Please identify how many pixels in the image are red, green and blue respectively and visualize the amount of pixels for 3 channels using a combined Histograms. Briefly explain what is your finding from the diagrams

[NOTE]
====
* The summaries for each channel state the number of pixels for each color. So if `blue` has largest number, we can say blue is the dominant color of the image
* To define lower and upper bounds for 3 colors depends on your personal judgement. You may need to adjust those thresholds value according to the different images and different purpose of your task
====
[TIP]
====
`numpy sum()` can be used to summarize pixels
====


=== Question 3 ( 2 pts)

[loweralpha]
..write a method called `equal_histogram`
... The method will accomplish a way to enhance image area that is too dark or light
... Arguments is the grayscaled image such as grayscaled "ballpit.jpg"
... return will be a histogram equalized image of "ballpit.jpg"

.. Run the method with grayscaled "ballpit.jpg" as input. Visualize the output aligning with the original grayscaled "ballpit.jpg" using Histogram

[NOTE]
====
====
    
=== Question 4 (2 pts)

[loweralpha]
.. process one of your favorite photo with function `equal_histogram`.  Write 1-2 sentences about your input and output, make sure to show the results of your image.

Feel free to use `/anvil/projects/tdm/data/images/coke.jpg` -- the results are pretty neat!
 
Project 07 Assignment Checklist
====
* Jupyter Lab notebook with your codes, comments and outputs for the assignment
    ** `firstname-lastname-project07.ipynb`.
 
* Submit files through Gradescope
====
[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
