= TDM 40100: Project 14 -- Fall 2023

**Motivation:** We covered a _lot_ this year! When dealing with data driven projects, it is crucial to thoroughly explore the data, and answer different questions to get a feel for it. There are always different ways one can go about this. Proper preparation prevents poor performance. As this is our final project for the semester, its primary purpose is survey based. You will answer a few questions mostly by revisiting the projects you have completed.

**Context:** We are on the last project where we will revisit our previous work to consolidate our learning and insights. This reflection also help us to set our expectations for the upcoming semester
**Scope:** R, Jupyter Lab, Anvil


Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Questions


=== Question 1 (1 pt)

.. Reflect on your experience working with different datasets, which one did you feel most enjoyable and why? Discuss how this dataset's feature influenced your analysis and visualization strategies. Illustrate your explanation with an example from one question you worked using the dataset.

=== Question 2 (1 pt)

.. Reflect on your experience working with different commands, functions, modules and packages, which one is your favorite and why do you enjoy learning about it? Please provide an example from one question you worked using it. 


=== Question 3 (1 pt)

.. Reflect on data visualization questions you have done, which one you feel most appealing and what specific package did you use to create it? Please provide an example from one question you completed. You may refer to the question, and screenshot your graph.

=== Question 4 (2 pts)

.. While working on the data statistic and testing, what steps did you take to ensure the results right? Please illustrate your approach using an example from one problem you addressed. 

=== Question 5 (1 pt)

.. Reflect on the projects you completed, which questions did you feel most confusing, and how could they be made clearer? Please use a specific question to illustrate your points 

=== Question 6 (2 pts)

.. Please identify 3 skills or topics related to data science you want to learn. For each, please provide an example that illustrates your interests and the reason you think they would be beneficial.  


Project 14 Assignment Checklist
====
* Jupyter Lab notebook with your answers and examples. You may just use markdown formate for all questions.
    ** `firstname-lastname-project14.ipynb` 
* Submit files through Gradescope
====

WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.

In addition, please review our xref:projects:current-projects:submissions.adoc[submission guidelines] before submitting your project.
====