= TDM Course Overview

This page provides a high-level overview of the TDM 100, 200, 300, and 400 level courses. Together, these courses make up The Data Mine's seminar offering for students. 

[IMPORTANT]
====
The Data Mine is always incorporating new feedback and changing our offerings to fit student's needs. 

As part of that, the focus of the courses below may change in the future.
====

== TDM 101/102

The 100 level courses serve as an introduction to two of the core coding language in analytics, Python and R. Students will learn about the basic implementation of the coding languages as well as how to apply them to core skills in analytics and data science. 

The course serves as a great introduction to coding languages and core data analytics topics. 

== TDM 201/202

Building on the coding skills learned in the 100 level courses, the 200 level takes Python and R and discusses how they are used in a high-performance computing (HPC) environment. Students will leverage their core coding skills to learn about topics like code optimization, web scraping, and utilizing GPUs. 

This course is great to build experience working in Python and R in a research environment. 

== TDM 301/302

TDM 300 allows students to take a deeper dive into a specific type of predictive model. The Data Mine is starting with a deep dive into neural nets, but we plan to build out other modeling topics in the future. 

The 300-level course is a great opportunity for students to spend an extended amount of time taking a deep dive into a specific technique. 

== TDM 401/402

The Data Mine's highest current course offering, TDM 400 is an extension of the 300-level course with additional questions focused on understanding and applying the technique of focus. 

TDM 400 is an opportunity for advanced students to drive their own research into the application of predictive algorithms.