= Queries

== Overview

An SQL query is any statement that returns rows or records. Typically, a query will start with the `SELECT` or `SELECT DISTINCT` keywords. For example, the following is a simple SQL query.

[source, sql]
----
SELECT * FROM employees WHERE years_of_service > 5;
----

In this example:

* `SELECT` is a statement keyword. 
* `*` is an identifier or selector that means "select all columns".
* `FROM` is a clause that tells the engine from where (which table) we are selecting all of the columns.
* `employees` is an identifier that specifies the "employees" table in the database.
* `WHERE` is an optional clause that specifies under what conditions the engine is to return a record or row.
* `years_of_service` is an identifier that specifies a specific column called "years_of_service" in the "employees" table.
* `>` is an operator that compares two values, and returns TRUE or FALSE.
* `5` is an integer.
* Collectively, `years_of_service > 5` is a xref:terminology.adoc[predicate]#predicate.

Ultimately, this query will return all columns from all rows from the "employees" table where the "years_of_service" column has a value greater than 5. 

=== Examples

==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], display the first 10 ballparks in the `ballparks` table.

.Solution
====
[source, sql]
----
SELECT * FROM parks LIMIT 10;
----

[%header,format=csv]
|===
include::example$result01.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], make a list of the names of all of the inactive teams in baseball history.

.Solution
====
[source, sql]
----
SELECT franchName FROM teamsfranchises WHERE active=='N' LIMIT 10;
----

[%header,format=csv]
|===
include::example$result02.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], find the player with the most runs batted in (RBI's) in a season, using 2 queries. In the first query, find the `playerID` of the player with the most RBI's. In the second query find the player's name in the `people` table.

.Solution
====
[source, sql]
----
-- Find the playerID
SELECT playerID FROM batting WHERE RBI==191;

-- Display the name
SELECT nameFirst, nameLast FROM people WHERE playerID=='wilsoha01';
----

[%header,format=csv]
|===
include::example$result03.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], find out who was the manager of the 1976 "Big Red Machine" (CIN)? Answer this question using 2 queries.

.Solution
====
The "Big Red Machine" was a famous nickname for the dominant Cincinnati Reds of the early 1970s. Many of its team members are Hall of Famers, including their manager, Sparky Anderson.

[source, sql]
----
SELECT playerID FROM managers WHERE yearID==1976 AND teamID=='CIN';

SELECT nameFirst, nameLast FROM people WHERE playerID=='andersp01';
----

[%header,format=csv]
|===
include::example$result04.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], make a list of the `teamID`'s that were managed by Tony LaRussa. Answer this question using 2 queries.

.Solution
====
Tony LaRussa is very well known for being a manager that was involved in baseball for a very long time. He won the World Series with the St. Louis Cardinals and the Oakland Athletics.

[source, sql]
----
SELECT playerID FROM people WHERE nameLast=='LaRussa' AND nameFirst=='Tony';

SELECT DISTINCT teamID FROM managers WHERE playerID=='larusto01';
----

[%header,format=csv]
|===
include::example$result05.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], figure out what Cecil Fielder's salary was in 1987. Display the `teamID` with the salary.

.Solution
====
[source, sql]
----
SELECT playerID FROM people WHERE nameFirst=='Cecil' AND nameLast=='Fielder';

SELECT teamID, salary FROM salaries WHERE playerID=='fieldce01' AND yearID==1987;
----

[%header,format=csv]
|===
include::example$result06.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], make a list of all the teams who've lost a world series (WS) since 1990. Put the list in ascending order by `yearID`.

.Solution
====
[source, sql]
----
SELECT
	teamIDloser,
	yearID
FROM
	seriespost
WHERE
	yearID >= 1990
	AND round == 'WS'
ORDER BY
	yearID ASC
LIMIT 10;
----

[%header,format=csv]
|===
include::example$result07.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], find out what Cal Ripken, Jr.'s height and weight was. Did he bat right or left-handed? When did he play his final game? Find all of this information out in a single query.

.Solution
====
[source, sql]
----
SELECT
	height,
	weight,
	bats,
	finalgame
FROM
	people
WHERE
	nameFirst == 'Cal'
	AND nameLast == 'Ripken'
	AND deathState IS NULL;
----

[%header,format=csv]
|===
include::example$result08.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], select all of the `playerID`'s and `yearID`'s of the players who were inducted into the hall of fame and voted in by the veterans committee between 1990 and 2000. Put the list in descending order.

.Solution
====
The veterans committee in the Hall of Fame voting process place players in the hall of fame that are forgotten by the writers, fans, etc. This is a way for players to recognize who they think were the greatest players of all time, or are skipped over for a variety of reasons. This is one reason why there is a lot of scrutiny in the process for how players are selected to the baseball hall of fame.

[source, sql]
----
SELECT
	playerID,
	yearID
FROM
	halloffame
WHERE
	votedBy == 'Veterans'
	AND inducted == 'Y'
	AND yearID BETWEEN 1990 AND 2000
ORDER BY
	yearID DESC
LIMIT 10; 
----

[%header,format=csv]
|===
include::example$result09.csv[]
|===
====

=== Resources