= Queries

== Overview

An SQL query is any statement that returns rows or records. Typically, a query will start with the `SELECT` or `SELECT DISTINCT` keywords. For example, the following is a simple SQL query.

[source, sql]
----
SELECT * FROM employees WHERE years_of_service > 5;
----

In this example:

* `SELECT` is a statement keyword. 
* `*` is an identifier or selector that means "select all columns".
* `FROM` is a clause that tells the engine from where (which table) we are selecting all of the columns.
* `employees` is an identifier that specifies the "employees" table in the database.
* `WHERE` is an optional clause that specifies under what conditions the engine is to return a record or row.
* `years_of_service` is an identifier that specifies a specific column called "years_of_service" in the "employees" table.
* `>` is an operator that compares two values, and returns TRUE or FALSE.
* `5` is an integer.
* Collectively, `years_of_service > 5` is a xref:terminology.adoc#predicate[predicate].

Ultimately, this query will return all columns from all rows from the "employees" table where the "years_of_service" column has a value greater than 5. 

=== Examples

==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], display the first 10 ballparks in the `ballparks` table.

.Solution
====
[source, sql]
----
SELECT * FROM parks LIMIT 10;
----

[%header,format=csv]
|===
include::example$result01.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], make a list of the names of all of the inactive teams in baseball history.

.Solution
====
[source, sql]
----
SELECT franchName FROM teamsfranchises WHERE active=='N' LIMIT 10;
----

[%header,format=csv]
|===
include::example$result02.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], find the player with the most runs batted in (RBI's) in a season, using 2 queries. In the first query, find the `playerID` of the player with the most RBI's. In the second query find the player's name in the `people` table.

.Solution
====
[source, sql]
----
-- Find the playerID
SELECT playerID FROM batting WHERE RBI==191;

-- Display the name
SELECT
	nameFirst,
	nameLast
FROM
	people
WHERE
	playerID == 'wilsoha01';
----

[%header,format=csv]
|===
include::example$result03.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], find out who was the manager of the 1976 "Big Red Machine" (CIN)? Answer this question using 2 queries.

.Solution
====
The "Big Red Machine" was a famous nickname for the dominant Cincinnati Reds of the early 1970s. Many of its team members are Hall of Famers, including their manager, Sparky Anderson.

[source, sql]
----
SELECT
	playerID
FROM
	managers
WHERE
	yearID == 1976
	AND teamID == 'CIN';

SELECT
	nameFirst,
	nameLast
FROM
	people
WHERE
	playerID == 'andersp01';
----

[%header,format=csv]
|===
include::example$result04.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], make a list of the `teamID`'s that were managed by Tony LaRussa. Answer this question using 2 queries.

.Solution
====
Tony LaRussa is very well known for being a manager that was involved in baseball for a very long time. He won the World Series with the St. Louis Cardinals and the Oakland Athletics.

[source, sql]
----
SELECT
	playerID
FROM
	people
WHERE
	nameLast == 'LaRussa'
	AND nameFirst == 'Tony';

SELECT DISTINCT
	teamID
FROM
	managers
WHERE
	playerID == 'larusto01';
----

[%header,format=csv]
|===
include::example$result05.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], figure out what Cecil Fielder's salary was in 1987. Display the `teamID` with the salary.

.Solution
====
[source, sql]
----
SELECT
	playerID
FROM
	people
WHERE
	nameFirst == 'Cecil'
	AND nameLast == 'Fielder';

SELECT
	teamID,
	salary
FROM
	salaries
WHERE
	playerID == 'fieldce01'
	AND yearID == 1987;
----

[%header,format=csv]
|===
include::example$result06.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], make a list of all the teams who've lost a world series (WS) since 1990. Put the list in ascending order by `yearID`.

.Solution
====
[source, sql]
----
SELECT
	teamIDloser,
	yearID
FROM
	seriespost
WHERE
	yearID >= 1990
	AND round == 'WS'
ORDER BY
	yearID ASC
LIMIT 10;
----

[%header,format=csv]
|===
include::example$result07.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], find out what Cal Ripken, Jr.'s height and weight was. Did he bat right or left-handed? When did he play his final game? Find all of this information out in a single query.

.Solution
====
[source, sql]
----
SELECT
	height,
	weight,
	bats,
	finalgame
FROM
	people
WHERE
	nameFirst == 'Cal'
	AND nameLast == 'Ripken'
	AND deathState IS NULL;
----

[%header,format=csv]
|===
include::example$result08.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], select all of the `playerID`'s and `yearID`'s of the players who were inducted into the hall of fame and voted in by the veterans committee between 1990 and 2000. Put the list in descending order.

.Solution
====
The veterans committee in the Hall of Fame voting process place players in the hall of fame that are forgotten by the writers, fans, etc. This is a way for players to recognize who they think were the greatest players of all time, or are skipped over for a variety of reasons. This is one reason why there is a lot of scrutiny in the process for how players are selected to the baseball hall of fame.

[source, sql]
----
SELECT
	playerID,
	yearID
FROM
	halloffame
WHERE
	votedBy == 'Veterans'
	AND inducted == 'Y'
	AND yearID BETWEEN 1990 AND 2000
ORDER BY
	yearID DESC
LIMIT 10; 
----

[%header,format=csv]
|===
include::example$result09.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], get a list of attendance by season for the Toronto Blue Jays (TOR). What season had the highest attendance?

.Solution
====
The Toronto Blue Jays were the 1993 season's World Series champion. This means that, yes, a non-USA team has won the World Series for baseball!

[source, sql]
----
SELECT
	yearkey,
	attendance
FROM
	homegames
WHERE
	teamkey == 'TOR'
ORDER BY
	attendance DESC
LIMIT 10;
----

[%header,format=csv]
|===
include::example$result10.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], figure out how many different leagues have represented Major League Baseball over time.

.Solution
====
Major League Baseball has had several leagues that have been represented in its history. There are only two current leagues: National League and the American League.

[source, sql]
----
SELECT DISTINCT league FROM leagues;
----

[%header,format=csv]
|===
include::example$result11.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], find the teams that have won the world series.

.Solution
====
[source, sql]
----
SELECT teamID, yearID FROM teams WHERE WSWin=='Y' LIMIT 10;
----

[%header,format=csv]
|===
include::example$result12.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], list the top 10 season win totals for teams. Include the `yearID` and the `teamID`.

.Solution
====
[source, sql]
----
SELECT teamID, yearID, W FROM teams ORDER BY W DESC LIMIT 10;
----

[%header,format=csv]
|===
include::example$result13.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], list the pitchers with their `teamID`, wins (`W`), and losses (`L`) that threw complete games (`CG`) in the 1995 season. Include the number of complete games as well.

.Solution
====
[source, sql]
----
SELECT
	playerID,
	teamID,
	W,
	L,
	CG
FROM
	pitching
WHERE
	CG > 0
	AND yearID == 1995
ORDER BY
	W DESC
LIMIT 10;
----

[%header,format=csv]
|===
include::example$result14.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], get a printout of the hits (`H`), and home runs (`HR`) for Ichiro Suzuki's career. Answer this question using 2 queries. In the first query, find his `playerID`. In the second query, list the `teamID`, `yearID`, hits (`H`), and home runs (`HR`).

.Solution
====
Ichiro Suzuki is regarded as one of the greatest hitters of all time because of his prowess in both American and Japanese professional baseball.

[source, sql]
----
SELECT
	playerID
FROM
	people
WHERE
	nameFirst == 'Ichiro'
	AND nameLast == 'Suzuki';

SELECT
	teamID,
	yearID,
	H,
	HR
FROM
	batting
WHERE
	playerID == 'suzukic01';
----

[%header,format=csv]
|===
include::example$result15.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], figure out how many walks (`BB`) and strikeouts (`SO`) Mariano Rivera had in the playoffs. Which year did he give up the most post-season walks? Answer this question using 2 queries.

.Solution
====
More men have walked on the moon than have scored a run on Mariano Rivera in a playoff game. Mariano Rivera made the hall of fame in 2019.

[source, sql]
----
SELECT
	playerID
FROM
	people
WHERE
	nameFirst == 'Mariano'
	AND nameLast == 'Rivera';

SELECT
	yearID,
	teamID,
	BB,
	SO
FROM
	pitchingpost
WHERE
	playerID == 'riverma01'
ORDER BY
	BB DESC;
----

[%header,format=csv]
|===
include::example$result16.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], find the pitcher with the most strikeouts (`SO`), and the batter that struck out the most in the 2014 season. Get the first and last name of the pitcher and the batter. Use 3 queries to figure this out.

.Solution
====
Corey Kluber is a two-time AL Cy Young winner. He is well known for his two-seam fastball that is difficult to hit.

[source, sql]
----
SELECT
	playerID,
	SO
FROM
	pitching
WHERE
	yearID == 2014
ORDER BY
	SO DESC
LIMIT (10);

SELECT
	playerID,
	SO
FROM
	batting
WHERE
	yearID == 2014
ORDER BY
	SO DESC
LIMIT (10);

SELECT
	nameFirst,
	nameLast
FROM
	people
WHERE
	playerID == "klubeco01"
	OR playerID == "howarry01";
----

[%header,format=csv]
|===
include::example$result17.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], figure out how many teams Bartolo Colon pitched for.

.Solution
====
Bartolo Colon is a well-known journeyman pitcher in baseball. He has pitched with a lot of teams, but it wasn't until he played for the New York Mets when he needed to come to the plate. He had a weird batting stance that is funny to watch. He even https://www.youtube.com/watch?v=OVFsq9FQBlc[hit a home run] one season!

[source, sql]
----
SELECT
	playerID
FROM
	people
WHERE
	nameFirst == 'Bartolo'
	AND nameLast == 'Colon';

SELECT COUNT(DISTINCT teamID) FROM pitching WHERE playerID == 'colonba01';
----

[%header,format=csv]
|===
include::example$result18.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], figure out how many times Trevor Bauer came to bat (`AB`) in 2016. How many hits did he get? Use 2 queries to answer this question.

.Solution
====
Trevor Bauer is much more known for his pitching than he is known for hitting. This is common for pitchers, as many are not very good at hitting.

[source, sql]
----
SELECT
	playerID
FROM
	people
WHERE
	nameFirst == "Trevor"
	AND nameLast == "Bauer";

SELECT
	AB,
	H
FROM
	batting
WHERE
	playerID == "bauertr01"
	AND yearID == "2016";
----

[%header,format=csv]
|===
include::example$result19.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], compare Mike Trout and Giancarlo Stanton by season. Who hit more RBI's in a season? Who has been caught stealing (`CS`) most in a season? Use 3 queries to answer these questions.

.Solution
====
Mike Trout and Giancarlo Stanton are considered two of the of the best hitters in Major League Baseball for very different reasons. Trout is an all-around player known for being indispensible, where Stanton is known as a power hitter.

[source, sql]
----
SELECT
	playerID,
	nameFirst,
	nameLast
FROM
	people
WHERE (nameFirst == 'Giancarlo'
	AND nameLast == 'Stanton')
	OR(nameFirst == 'Mike'
		AND nameLast == 'Trout');

SELECT
	playerID,
	yearID,
	teamID,
	RBI,
	CS
FROM
	batting
WHERE
	playerID == 'stantmi03'
	OR playerID == 'troutmi01'
ORDER BY
	RBI DESC
LIMIT 1;
----

[%header,format=csv]
|===
include::example$result20.csv[]
|===

[source, sql]
----
SELECT
	playerID,
	yearID,
	teamID,
	RBI,
	CS
FROM
	batting
WHERE
	playerID == 'stantmi03'
	OR playerID == 'troutmi01'
ORDER BY
	CS DESC
LIMIT 1;
----

[%header,format=csv]
|===
include::example$result21.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], make a list of players who walked (`BB`) more than they struck out (`SO`) between 1980 and 1985. Of these players, who walked the most? Use the `BETWEEN` clause in your queries. Use multiple queries.

.Solution
====
[source, sql]
----
SELECT
	playerID,
	yearID,
	teamID,
	BB,
	SO
FROM
	batting
WHERE
	BB > SO
LIMIT 10;
----

[%header,format=csv]
|===
include::example$result22.csv[]
|===

[source, sql]
----
SELECT nameFirst, nameLast FROM people WHERE playerID=='randowi01';
----

[%header,format=csv]
|===
include::example$result23.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], figure out how many different National League (`lgID == 'NL') catchers (`C`) won the gold glove between 1990 and 2000.

.Solution
====
[source, sql]
----
SELECT DISTINCT
	playerID
FROM
	awardsplayers
WHERE
	awardID == 'Gold Glove'
	AND notes == 'C'
	AND lgID == 'NL'
	AND yearID BETWEEN 1990 AND 2000;
----

[%header,format=csv]
|===
include::example$result36.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], figure out how many different 3rd basemen played for the Seattle Mariners between 2000 and 2005. Who had the most errors?

.Solution
====
[source, sql]
----
SELECT DISTINCT
	playerID,
	yearID,
	E
FROM
	fielding
WHERE
	yearID BETWEEN 2000 AND 2005
	AND teamID == 'SEA'
	AND POS == '3B'
ORDER BY
	E DESC
LIMIT 10;
----

[%header,format=csv]
|===
include::example$result37.csv[]
|===

[source, sql]
----
SELECT
	nameFirst,
	nameLast
FROM
	people
WHERE
	playerID == 'camermi01';
----

[%header,format=csv]
|===
include::example$result38.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], figure out what seasons Craig Biggio played catcher. Craig Biggio was known for playing second base, however, did not _always_ play second base. Solve this problem using 2 queries.

.Solution
====
[source, sql]
----
SELECT
	playerID
FROM
	people
WHERE
	nameFirst == 'Craig'
	AND nameLast == 'Biggio';
----

[%header,format=csv]
|===
include::example$result39.csv[]
|===

[source, sql]
----
SELECT
	teamID,
	yearID,
	POS
FROM
	fielding
WHERE
	playerID == 'biggicr01'
	AND POS == 'C';
----

[%header,format=csv]
|===
include::example$result40.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], find the teams representing the National League, that have won the world series. Desplay the list with the `yearID` and the `teamID` in ascending order.

.Solution
====
[source, sql]
----
SELECT
	teamID,
	yearID
FROM
	teams
WHERE
	WSWin == 'Y'
	AND lgID == 'NL'
ORDER BY
	yearID ASC
LIMIT 10;
----

[%header,format=csv]
|===
include::example$result41.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], list the pitchers that threw at least one complete game (`CG`) in the 1995 season. Please include the wins and losses of the top 10 pitchers. Use the `playerID` of the pitcher who threw the most complete games to find out the name of the pitcher that had the most complete games.

.Solution
====
[source, sql]
----
SELECT
	playerID,
	W,
	L,
	CG
FROM
	pitching
WHERE
	CG > 0
	AND yearID == 1995
ORDER BY
	CG DESC
LIMIT 10;
----

[%header,format=csv]
|===
include::example$result42.csv[]
|===

[source, sql]
----
SELECT
	nameFirst,
	nameLast
FROM
	people
WHERE
	playerID == 'maddugr01';
----

[%header,format=csv]
|===
include::example$result43.csv[]
|===
====


==== Who was the most recent player manager?

.Solution
====
[source, sql]
----
SELECT
	playerID,
	yearID
FROM
	managers
WHERE
	plyrMgr == 'Y'
ORDER BY
	yearID DESC
LIMIT 10;
----

[%header,format=csv]
|===
include::example$result44.csv[]
|===

[source, sql]
----
SELECT
	nameFirst,
	nameLast
FROM
	people
WHERE
	playerID == 'rosepe01';
----

[%header,format=csv]
|===
include::example$result45.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], get the at-bats, homeruns, stolen bases for Roberto Clements by year in ascending order.

.Solution
====
[source, sql]
----
SELECT
	playerID
FROM
	people
WHERE
	nameFirst == 'Roberto'
	AND nameLast == 'Clemente';
----

[%header,format=csv]
|===
include::example$result46.csv[]
|===

[source, sql]
----
SELECT
	yearID,
	AB,
	HR,
	SB
FROM
	battingpost
WHERE
	playerID == 'clemero01'
ORDER BY
	yearID ASC;
----

[%header,format=csv]
|===
include::example$result47.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], get a list of distinct world series winners during the years where Tom Lasorda managed the Los Angeles Dodgers (LAN). First, find the years Tom Lasorda was the manager of LAN, and then find the distinct teams that won a world series in that time frame.

.Solution
====
[source, sql]
----
SELECT
	playerID
FROM
	people
WHERE
	nameFirst == 'Tom'
	AND nameLast == 'Lasorda';
----

[%header,format=csv]
|===
include::example$result48.csv[]
|===

[source, sql]
----
SELECT
	yearID
FROM
	managers
WHERE
	playerID == 'lasorto01'
LIMIT 10;
----

[%header,format=csv]
|===
include::example$result49.csv[]
|===

[source,sql]
----
SELECT DISTINCT
	teamID
FROM
	teams
WHERE
	WSWin == 'Y'
	AND yearID BETWEEN 1976 AND 1996;
----

[%header,format=csv]
|===
include::example$result50.csv[]
|===
====


==== Using the SQLite lahman database https://www.datadepot.rcac.purdue.edu/datamine/data/lahman/lahman.db[here], figure out which teams Kenny Lofton stole more than 20 bases from in a single season. Limit results to seasons after the year 2000.

.Solution
====
[source, sql]
----
SELECT
	playerID
FROM
	people
WHERE
	nameFirst == 'Kenny'
	AND nameLast == 'Lofton';
----

[%header,format=csv]
|===
include::example$result51.csv[]
|===

[source, sql]
----
SELECT
	teamID,
	yearID,
	SB
FROM
	batting
WHERE
	playerID == 'loftoke01'
	AND SB > 20
	AND yearID > 2000;
----

[%header,format=csv]
|===
include::example$result52.csv[]
|===
====

=== Resources