= 1. Basics of Querying

== Concepts

=== Identifiers

Identifiers are names of database objects, like tables, columns, etc.

=== Statements

Statements are text sent to a database engine. Typically, statements begin with one of the following keywords, and end in a semi-colon.

`SELECT`, `SELECT DISTINCT`, `SELECT INTO`, `INSERT INTO`, `UPDATE`, `DELETE`

=== Queries

A query is any statement that returns rows. That means, typically, statements that start with the the following keywords.

`SELECT`, `SELECT DISTINCT`

=== Aliasing

Aliasing is the process of giving a table or a table column a temporary name. Aliases are commonly used to either make the query easier to write, or more readable. An example of using table aliases to make a query shorter would be the following.



== Demo

[Warning]
====
Fulya  **Add Aliasing examples below https://the-examples-book.com/tools/sql/aliasing**
====

For today's practices, please select the `seminar` kernel. To run SQL queries in a JupyterLab notebook, first run the following in a cell at the top of your notebook to establish a connection with the database:

[source, sql]
----
%sql sqlite:////anvil/projects/tdm/data/movies_and_tv/imdb.db
----

[TIP]
====
In sqlite, you can show the tables using the following query:

[source, sql]
----
.tables
----

Unfortunately, sqlite-specific functions can't be run in a JupyterLab cell like that. Instead, we need to use a different query as follows:

[source, sql]
----
SELECT tbl_name FROM sqlite_master WHERE type='table';
----
====

See first five lines of `people` table and `titles`:

[source, sql]
----
SELECT * FROM people LIMIT 5;

SELECT * FROM titles LIMIT 5;
----

It is a good idea to run this query on each table in the dataset to identify the common keys that can be used to connect the tables in SQL. It is also helpful to limit the number of rows you display (`LIMIT`), viewing an entire table at once is not practical. 

[TIP]
====
In SQL and certain other languages like bash or batch, the asterisk (*) acts as a wildcard that represents "everything". For instance, the command `SELECT * FROM table` retrieves all columns from the table named table, regardless of their names, data types, or values. This feature is convenient when you want to extract every piece of data from a table without listing each column one by one.
====


Now, let's check how many records are in the people table:

[source, sql]
----
SELECT COUNT(*) FROM people;
----

As you can see, there are more than 11 million records, so displaying the full table would not be feasible.

Let’s take a closer look at the titles table by running the following query:

[source, sql]
----
SELECT * FROM titles LIMIT 5;
----

As you can see, each row includes a `title_id` that corresponds to the title of a movie, TV show, or another type of media. But what exactly is this `title_id`? Take a look at the following link:

https://www.imdb.com/title/tt0111161

== Practice on your own 

[Warning]
====
Maggie still needs to add content. 
====
