= Sprint #4

[IMPORTANT]
====
The fall 2025 content is currently being revised. Please check back soon for updates. 
====


== Intro Video

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/8kzhUzJHZk4?si=DqQUVDAlCFDyV0Gq" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
++++

== Sprint Dates
_Monday, 10/13 and Tuesday, 10/14: October Break – No Classes_

_Thursday, 10/16 and Friday 10/17: All labs and meetings as usual. No changes on Wednesday, Thursday and Friday._


== Sprint Dates

[cols="<.^1,^.^1"]
|===

|*Sprint Start Date*
|Mon 10/13

|*Sprint End Date*
|Fri 10/24

|===

== To Do

&#10003; Complete Time Sheet

* Timesheet #8 due Sunday 10/19 at 11:59 PM EST.

* Timesheet #9 due Sunday 10/26 at 11:59 PM EST.

&#10003; Grade Professional Development #3 & Team Report #3 on Gradescope by Wednesday 10/15 at 11:59PM EST.

&#10003; Grade Sprint Report #3 on Gradescope by Wednesday 10/22 at 11:59PM EST.

&#10003; Set-up a meeting with your mentor to complete mid-semester feedback. Mid-Semester Evaluations are due October 29. You can begin this assignment during this sprint with your mentor. Please share the rubric with them early so they may begin preparing. link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module5_4_mentor_feedback[Mentor and TA Feedback Guide]

&#10003; Complete TA and Student 1:1's. When you complete this task is flexible during Sprint 4. Please find time with each team member to check in with them individually.  link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module4_9_check_ins[Semester Check-Ins with Students]

** Watch the video on link:https://www.youtube.com/watch?v=YLBDkz0TwLM&t=69s[The Secret to Giving Great Feedback] and implement strategies in 1:1s with students. 

&#10003; See the xref:fall2025/schedule.adoc[Fall Schedule] for timesheet and report deadlines.

== Sprint Schedule

=== Team Meeting #1 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
* Ensure students are assigned tasks to work on before meeting again in the next lab.


=== Lab Section #1 (1 hour and 50 Minutes): 

* Begin lab by spending 10-15 minutes on your choice of the 3 following activities

1. **Ice Breaker** - Please refer to the TA MS Teams chanel for more ideas 

2. **Reviewing Professional Development Topics** - In Sprint #3, students learned about mock interviews, conflict resolution and documentation.  Refer to the assignments xref:students:fall2025/sprint3.adoc[here] and facilitate a conversation about their main takeaways or feedback on the assignments.

3. **Discuss upcoming Team Meeting** - With your team, spend time to figure out how you want to present your findings to your mentor for this week. For example, you could create a slide that highlights key points and blockers you're facing, prepare a demo, or anything else that seems suitable.   

* Complete a Sprint Retrospective of Sprint #3 by discussing the following questions with your team. 
1. What worked well during Sprint #3?

2. What didn't work well during Sprint #3? 

3. How can we improve Sprint #4? 

4. What are some questions you have regarding Sprint #3? 

* Next, have students answer the following questions in their daily stand-ups.

1. What have you been working on since the last meetings? 

2. What are you currently working on? 

3. Are there any blockers preventing you from doing your work? 

* Use the remainder of the time to work on your project.

=== Team Meeting #2 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles,roadblocks or barriers that they experienced while completing this weeks task?
** What do they plan on committing to completing by next mentor meeting?
* Time for questions from students to mentor.

* Ensure students are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #2 (1 hour and 50 Minutes):

* Begin lab by spending 10-15 minutes on your choice of the 3 following activities

1. **Ice Breaker** - Please refer to the TA MS Teams chanel for more ideas 

2. **Reviewing Professional Development Topics** - In Sprint #3, students learned about mock interviews, conflict resolution and documentation.  Refer to the assignments xref:students:fall2025/sprint3.adoc[here] and facilitate a conversation about their main takeaways or feedback on the assignments.

3. **Discuss upcoming Team Meeting** - With your team, spend time to figure out how you want to present your findings to your mentor for this week. For example, you could create a slide that highlights key points and blockers you're facing, prepare a demo, or anything else that seems suitable.   

* Next, have students answer the following questions in their daily stand-ups.

1. What have you been working on since the last meetings? 

2. What are you currently working on? 

3. Are there any blockers preventing you from doing your work? 

* Use the remainder of the time to work on your project.

* Sprint Tasks for students: xref:students:fall2025/sprint4.adoc[Sprint 4 Tasks]