= Sprint #2

[IMPORTANT]
====
The fall 2025 content is currently being revised. Please check back soon for updates. 
====


== Intro Video

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/ia6H9c0Ap2I?si=xUbeNZejSRKFtHFu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
++++

== Sprint Dates

You can find a xref:fall2025/schedule.adoc#sprint-schedule[visual of the sprint schedule here].

[cols="<.^1,^.^1"]
|===

|*Sprint Start Date*
|Mon 9/15

|*Sprint End Date*
|Fri 9/26

|===

== To Do

&#10003; Complete Time Sheet

* Timesheet #4 due Sunday 09/21 at 11:59 PM EST.

* Timesheet #5 due Sunday 9/28 at 11:59 PM EST.

&#10003; Complete Team Report #1 & grade Professional Development #1 on Gradescope by Wednesday 09/17 at 11:59PM EST.

&#10003; Attend Monthly Meeting #1, all TAs are required to attend 1 session on Wednesday 09/24. [Room TBD]

&#10003; Grade Sprint Report #1 on Gradescope by Wednesday 09/24 at 11:59PM EST.

&#10003; Before **Lab #1** prepare to facilitate a conversation about your Team Contract following the instructions linked xref:TAs:team_contract.adoc[here]. 

&#10003; Submit your Team Contract in Gradescope by Friday 9/26 11:59 PM EST. Ensure each section has been discussed and signed virtually by all of your team members.

== Sprint Schedule

=== Team Meeting #1 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles,roadblocks or barriers that they experienced while completing this weeks task?
** What do they plan on committing to completing by next mentor meeting?
* Time for questions from students to mentor.


=== Lab Section #1 (1 hour and 50 Minutes):

* Start with an Ice Breaker followed by a daily stand-up. 
* **Team Contract** - Collaborate with your team to create your Team Contract by following the provided outline xref:TAs:team_contract.adoc[here]. 
** This contract will establish your team's expectations for the year. Facilitate this process as an open discussion, encouraging all members to provide input. 
** Whatever isn't finished in this Lab, must be complete in the next Lab. You will submit this contract in Gradescope at the end of the sprint.  
* Use the remainder of the time to work on your project.
 
=== Team Meeting #2 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles,roadblocks or barriers that they experienced while completing this weeks task?
** What do they plan on committing to completing by next mentor meeting?
* Time for questions from students to mentor.
* Make sure students are prepared to present results of work that they have done(e.g. pre-run models, screenshots or a summary slide)

* Ensure students are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #2 (1 hour and 50 Minutes):

* Begin lab by spending 10-15 minutes on your choice of the 3 following activities

1. **Ice Breaker** - Please refer to the TA MS Teams chanel for more ideas 

2. **Reviewing Professional Development Topics** - In Sprint #1, students learned about Resumes, Mock Interviews, Email communications, Netiquette. Refer to the assignments xref:students:fall2025/sprint1.adoc[here] and facilitate a conversation about their main takeaways or feedback on the assignments.

3. **Discuss upcoming Team Meeting** - With your team, spend time to figure out how you want to present your findings to your mentor for this week. For example, you could create a slide that highlights key points and blockers you're facing, prepare a demo, or anything else that seems suitable.   

* Next, share one of this sprint's professional development topic of : https://the-examples-book.com/crp/students/elevator_pitch[Elevator Pitches].
** *ACTION ITEM*: Watch the video on this page https://the-examples-book.com/crp/students/elevator_pitch[Elevator Pitches] and facilitate a roundtable of elevator pitches.

* Next, have students answer the following questions in their daily stand-ups.

1. What have you been working on since the last meetings? 

2. What are you currently working on? 

3. Are there any blockers preventing you from doing your work? 

* Use the remainder of the time to work on your project.

* Sprint Tasks for students: xref:students:fall2025/sprint2.adoc[Sprint 2 Tasks]