= Sprint #6


== Sprint Dates

[cols="<.^1,^.^1"]
|===

|*Sprint Start Date*
|Mon 11/10

|*Sprint End Date*
|Fri 11/21

|===

== To Do

&#10003; Complete Time Sheet

* Timesheet #12 due Sunday 11/16 at 11:59 PM EST.

* Timesheet #13 due Sunday 11/23 at 11:59 PM EST.

&#10003; Grade Professional Development #5 & Team Report #5 on Gradescope by Wednesday 11/12 at 11:59PM EST.

&#10003; Grade Sprint Report #5 on Gradescope by Wednesday 11/19 at 11:59PM EST.

&#10003; Attend Monthly Meeting #3, All TA are required to attend 1 session on Wed 11/19. [Room TBD]

&#10003; Complete final fall presentation draft materials and submit on Gradescope by Wednesday 11/19 at 11:59 PM EST.

&#10003; Finalize a list of audience members for the final presentation and share with your team. 

== Sprint Schedule

=== Team Meeting #1 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.

* Ensure students are assigned tasks to work on before meeting again in the next lab.


=== Lab Section #1 (1 hour and 50 Minutes):

* Begin lab with an ice breaker. Please refer to the TA MS Teams chanel for more ideas 

* **Reviewing Professional Development Topics** - In Sprint #4, students learned about Data Storytelling, Addressing Different Audience and How to Give a Strong Presentation.  Refer to the assignments xref:students:fall2025/sprint4.adoc[here].
** Facilitate a conversation about their main takeaways or feedback on the assignments.
** Discuss how they can apply these skills in their upcoming Final Fall Presentation.

* Complete a Sprint Retrospective of Sprint #5 by discussing the following questions with your team. 
1. What worked well during Sprint #5?

2. What didn't work well during Sprint #5? 

3. How can we improve Sprint #6? 

4. What are some questions you have regarding Sprint #5? 

* Next, have students answer the following questions in their daily stand-ups.

1. What have you been working on since the last meetings? 

2. What are you currently working on? 

3. Are there any blockers preventing you from doing your work? 

* Using the transformation matrix and story roadmap created in the last lab, begin drafting your final presentation. 

=== Team Meeting #2 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles,roadblocks or barriers that they experienced while completing this weeks task?
** What do they plan on committing to completing by next mentor meeting?
* Time for questions from students to mentor.

* Ensure students are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #2 (1 hour and 50 Minutes):

* Begin lab with an ice breaker. Please refer to the TA MS Teams chanel for more ideas 

* Next, have students answer the following questions in their daily stand-ups.

1. What have you been working on since the last meetings? 

2. What are you currently working on? 

3. Are there any blockers preventing you from doing your work? 

* Complete the draft of your final presentation. 

== Final Fall Presentation

To recap the semester, your team will present on project progress and future goals. Please review the following Guidelines for the Final Presentation: xref:fall2025/final_presentation.adoc[Final Fall Presentation Details]. During this sprint, your team should complete a first draft of your presentation and continuing working on this presentation until the final week of term when you will present to your CRP mentors and the Data Mine staff.

*When:* Draft due Wednesday, November 19, 2025 at 11:59 PM ET. Late work will not be accepted. Final Materials due Friday, December 5th, 2025 at 11:59 PM ET. Late work will not be accepted. *TAs will submit on behalf of the whole team*

*What:* 

&#10003; The team started the Final Fall Presentation (2 weeks till due date).

&#10003; Assigned speaking parts for the Final Fall Presentation. This even includes back-up speakers! 

&#10003; xref:fall2025/final_presentation.adoc[Final Fall Presentation Details]

&#10003; Turned in the team *Final Fall Presentation draft* materials by 11:59 PM ET on Wednesday, 11/19/2025. *TAs will submit on behalf of the whole team*

*Where:* link:https://www.gradescope.com/[Gradescope]