= Sprint #7

// Sprint-specific 
:sprint: 7
:previous-sprint: 6
:start-date: Nov 24 
:end-date: Dec 12, 2025

// Tasks with due dates 
:timesheet8-due: #14: Sun, Nov 30, 2025 @ 11:59 PM ET
//:timesheet9-due: #13: Sun, Nov 23, 2025 @ 11:59 PM ET
:pd-due: Wed, Dec 3, 2025 @ 11:59 PM ET
:report-due: Wed, Dec 10, 2025 @ 11:59 PM ET
:teamreport-due: Wed, Dec 10, 2025 @ 11:59 PM ET
:indy-tm-meeting2: Tue, Dec 2, 2025 @ 08:00 AM ET
//:wl-tm-meeting: Tue, Nov 19, 2025 (Session 1 of 3)
//:final-presentation-draft: Wed, Nov 19, 2025 @ 11:59 PM ET
:final-presentation: Fri, Dec 5, 2025 @ 11:59 PM ET
:final-semester-due: Wed, Dec 10, 2025 @ 11:59 PM ET
:pd-due1: Wed, Dec 10, 2025 @ 11:59 PM ET
:survey-due: Wed, Dec 10, 2025 @ 11:59 PM ET
:project-review-due: Fri, Dec 12, 2025 @ 11:59 PM ET

// Internal resources (kept local atm, but we could think of global approach)
//General
:sessions-deck-link: link:https://[Download Sessions Deck,window=_blank]
:student-content-tasks-link: xref:students:fall2025/sprint{sprint}.adoc[Sprint {sprint} Resource,window=_blank]
:student-previous-content-tasks-link: xref:students:fall2025/sprint{previous-sprint}.adoc[Sprint {previous-sprint} Resource,window=_blank]
:meeting-agendas-link: xref:meeting_agendas.adoc[TA Resources: Meeting Agendas]
:gradescope-link: link:https://www.gradescope.com/[Gradescope,window=_blank]
:timesheet-link: link:https://hcm-us10.hr.cloud.sap/sf/timesheet[Success Factors,window=_blank]
:warm-ups-link: xref:TAs:trainingModules/ta_training_module4_3_warmups.adoc[Warm-ups,window=_blank]
:qualtrics-link: link:https://[Qualtrics]
//Sprint 4
:mentor-feedback-guide-link: link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module5_4_mentor_feedback[Mentor and TA Feedback Guide,window=_blank]
:checkins-guide-link: link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module4_9_check_ins[Semester Check-Ins with Students,window=_blank]
:checkins-video-link: link:https://www.youtube.com/watch?v=YLBDkz0TwLM&t=69s[The Secret to Giving Great Feedback,window=_blank]
//Sprint 5
:worst-presentation-ppt: xref:attachment$WorstPresentationEverStandAlone.ppt[World Worst Presentation Ever,window=_blank]
:presentation-guide: xref:TAs:fall2025/final_presentation.adoc[Final Presentation Guide,window=_blank]
//Sprint 6
:presentation-info: xref:students:fall2025/final_presentation.adoc[Final Presentation Information,window=_blank]
//sprint 7
:project-review: xref:TAs:update_project_charter.adoc[Project Charter,window=_blank]


== Sprint Timeline

> {start-date} - {end-date}

[cols="3,3,2", options="header"]
|===
| Task | Due Date | Where

| <<complete-time-sheet, ✓ Complete Time Sheet>>
| **{timesheet8-due}** + 
//**{timesheet9-due}**
| {timesheet-link}

| **Indy TAs**: ✓ Attend Indy TA Team Meeting
| **{indy-tm-meeting2}**
| In-Person; Room ET219

| <<professional-development, ✓ Grade Professional Development #{previous-sprint}>>
| **{pd-due}**
| {gradescope-link}

| <<presentation, ✓ Final Presentation>>
| **{final-presentation}**
| {gradescope-link}

| <<sprint-report, ✓ Grade Sprint Report #{previous-sprint}>>
| **{report-due}**
| {gradescope-link}

| <<complete-team-report, ✓ Complete Team Report #{previous-sprint}>>
| **{teamreport-due}**
| {gradescope-link}

| <<professional-development1, ✓ Grade Professional Development #{sprint}>>
| **{pd-due1}**
| {gradescope-link}

| <<final-semester, ✓ Final Semester Feedback with Mentor>>
| **{final-semester-due}**
| {gradescope-link}

| <<survey, ✓ Corporate Partners Mid-year Final Survey>>
| **{survey-due}**
| {qualtrics-link} - pending

| <<project-review, ✓ Project review>>
| **{project-review-due}**
| {gradescope-link}
|===

_Clicking a task name will take you to its detailed description in Sprint Details._ 

[NOTE]
.Thanksgiving break
====
_Monday, 11/24 and Tuesday, 11/25: All labs and meetings as usual. No changes on Monday and Tuesday._ +
_Wednesday, 11/26, Thursday, 11/27 and Friday 11/28: Thanksgiving break - No classes._
====

== Sprint Schedule

[TIP]
.Deck for this Sprint
====
{sessions-deck-link} +
This is your working deck for the sprint. It includes agendas and slides you can adapt — just update the marked slides before using.
====

This sprint is a bit special — it runs for three weeks and wraps up with the final presentation.

[cols="2,2,3,2", options="header"]
|===
| Session | Duration | Focus | Where

| **Team Meeting #1**
| 50 min 
| Attendance, Project Updates/Sprint Review,  Q&A
.6+| In-Person / MS Teams

| **Lab Session #1**
| 1h 50m 
| _No Class_

| **Team Meeting #2**
| 50 min 
| Attendance, Project Updates/Sprint Review,  Q&A

| **Lab Session #2**
| 1h 50m 
| Attendance, Icebreaker, Reminders, **Team Activity**

| **Team Meeting #3**
| 50 min 
| **Final Presentation Session**

| **Lab Session #3**
| 1h 50m 
| Attendance, Icebreaker, Reminders, **Team Activity**

|===

_**Note:** Icebreakers, Reminders, and the Team Activity section may vary each sprint._

---

=== Lab Sessions

- **Icebreakers** : {warm-ups-link}

- **Reminders**: {student-content-tasks-link}

- **Team Activity** +

*** **Lab Session #1:** _No Class_


*** **Lab Session #2:** +
**Professional Development:** (Optional) +
Begin lab by discussing the professional development #4 Addressing Different Audiences. Talk about the background knowledge each of your audience members has, what they want to get out of your presentation and how to adjust your presentation style to ensure you meet those expectations. Facilitating this discussion will be crucial to executing a strong final presentation. +
**Reviewing Feedback on Presentation Draft** (Required) +
Go through the feedback that Data Mine Staff members left on your presentations in Gradescope. Review this as a team and work with your team to make necessary changes to your team's presentation.
This is the last lab you have to work on final presentations, so use your time wisely!

*** **Lab Session #3:** +
**Project review** (Required) +
Spend at least 30 minutes reviewing the Project review with your team. Please refer to {project-review} assignment for more information. Whatever you do not finish in class will be the TA's responsibility to complete and submit. +
**Celebrate a Successful Semester!** (Optional) + 
Try to do something fun your last lab to celebrate a successful semester! You can bring in treats to celebrate, play fun games, or even try to coordinate something with your mentor. 

//For the full structure of meetings and labs, see the {meeting-agendas-link}.

'''

== Sprint Details


[[complete-time-sheet]]
=== ✓ Complete Time Sheet 

Timesheet {timesheet8-due} + 
Please submit through Success Factors or via Excel if you are in the credit-based TA role.

---

[[professional-development]]
=== ✓ Grade Professional Development #{previous-sprint}

Please grade the Professional Development #{previous-sprint} assignment on Gradescope. Students learned about *Proving Feedback* through Radical Candor and about the value of *Taking Initiative*.

Due: on **Gradescope by {pd-due}.**

---
[[presentation]]
=== ✓ Final Presentation 

Your team should finalize your presentation. Review the feedback provided by The Data Mine staff in Gradescope, discuss it as a team, and make any necessary updates to strengthen your presentation.

Due: on **Gradescope by {final-presentation}.** _TAs will submit on behalf of the whole team_

---

[[sprint-report]]
=== ✓ Grade Sprint Report #{previous-sprint}

The Sprint Report serves both as part of the course grading requirements and as a way to give you insight into where each team member stands in their work and how they are thinking about the project.
- **Self-Evaluation** highlights how students view their presence, contributions, and collaboration.
- **Reflections** shows how students are connecting their experiences to project practices and the program.


[IMPORTANT] 
====
**Grading**: Evaluate reports objectively based on the rubric, the evidence students provide, your observations from sessions, and the required number of sentences. Fair grading ensures accountability and consistency across the team and program.
====

Due: on **Gradescope by {report-due}**

---

[[complete-team-report]]
=== ✓ Complete Team Report #{previous-sprint}

This report captures your responsibilities as a TA (Scrum Master) and your team's progress in Sprint  {previous-sprint}. It helps you reflect on what has been completed, what still needs attention, and what's next. It also provides your liaison with the context they need to offer support.  +
**Note**: Please complete this report after grading Sprint Report #{previous-sprint} submissions.

Due: on **Gradescope by {teamreport-due}**

---

[[professional-development1]]
=== ✓ Grade Professional Development #{sprint}

Please grade the Professional Development #{sprint} assignment on Gradescope. Students *updated their ANVIL account info*, *reviewed Professional Development* from this semester, and then went on their own *ProfDev adventure* to learn a skill that will help them in their future careers.

Due: on **Gradescope by {pd-due1}.**

---

[[final-semester]]
=== ✓ Semester Feedback with Mentor

Set up a meeting with your mentor to complete your semester feedback of individual student's work and engagement in the project. Semester Evaluations are due **{final-semester-due}**. Be sure to share the rubric with your mentor early so they have time to prepare:  

** {mentor-feedback-guide-link}

Due: on **Gradescope by {final-semester-due}.**

---

[[survey]]
=== ✓ Corporate Partners Mid-Year Survey

WARNING: Qualtrics link pending.

Follow the Qualtrics link to complete and submit the mid-year survey report. There is nothing to submit in Gradescope for this task.

Due: on **Qualtrics by {survey-due}.**

---
[[project-review]]
=== ✓ Project Review

Work with your students to prepare for the next semester by organizing your team's kanban board and creating a short plan for the weeks ahead. Focus on outlining objectives and actionable steps to ensure a smooth start after the break.

Due: on **Gradescope by {project-review-due}.** _TAs will submit on behalf of the whole team_

---