= Sprint #3

[IMPORTANT]
====
The fall 2025 content is currently being revised. Please check back soon for updates. 
====


== Intro Video

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/Dt9_gUERJ1g?si=XywJb6O3Oai2wP2y" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
++++

== Sprint Dates

[cols="<.^1,^.^1"]
|===

|*Sprint Start Date*
|Mon 9/29

|*Sprint End Date*
|Fri 10/10

|===

== To Do 

&#10003; Complete Time Sheet

* Timesheet #5 due Sunday 9/28 at 11:59 PM EST.

* Timesheet #6 due Sunday 10/5 at 11:59 PM EST.

&#10003; Grade Sprint #2 & Team Report #2 by Wednesday 10/01 at 11:59PM EST.

&#10003; Grade Professional Development #3 on Gradescope by Wednesday 10/08 at 11:59PM EST.

** You will submit your Team Contract with your Team Report assignment. Ensure each section has been discussed, is complete all of your team members have virtually signed it by Wednesday 9/25 at 11:59 EST. 

&#10003; See the xref:fall2024/schedule.adoc[Fall Schedule] for timesheet and report deadlines.

== Sprint Schedule

=== Team Meeting #1 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
** Questions related to the company. (Internship, Full-Time Opportunities, and etc.)
* Ensure students are assigned tasks to work on before meeting again in the next lab.


=== Lab Section #1 (1 hour and 50 Minutes):

* Begin lab by spending 10-15 minutes on your choice of the 3 following activities

1. **Ice Breaker** - Please refer to the TA MS Teams chanel for more ideas 

2. **Reviewing Professional Development Topics** - In Sprint #2, students prepared for the Career Fairs by updating their resumes, practicing their elevator pitches and learning about the difference between Business Professional and Business Casual. Refer to the assignments xref:students:fall2024/sprint2.adoc[here] and facilitate a conversation about their main takeaways or feedback on the assignments.

3. **Discuss upcoming Team Meeting** - With your team, spend time to figure out how you want to present your findings to your mentor for this week. For example, you could create a slide that highlights key points and blockers you're facing, prepare a demo, or anything else that seems suitable.   

* Complete a Sprint Retrospective of Sprint #2 by discussing the following questions with your team. 
1. What worked well during Sprint #2?

2. What didn't work well during Sprint #2? 

3. How can we improve Sprint #3? 

4. What are some questions you have regarding Sprint #2? 

* Next, have students answer the following questions in their daily stand-ups.

1. What have you been working on since the last meetings? 

2. What are you currently working on? 

3. Are there any blockers preventing you from doing your work? 

* Use the remainder of the time to work on your project.

=== Team Meeting #2 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles,roadblocks or barriers that they experienced while completing this weeks task?
** What do they plan on committing to completing by next mentor meeting?
* Time for questions from students to mentor.

* Ensure students are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #2 (1 hour and 50 Minutes):

* Begin lab by spending 10-15 minutes on your choice of the 3 following activities

1. **Ice Breaker** - Please refer to the TA MS Teams chanel for more ideas 

2. **Reviewing Professional Development Topics** - In Sprint #2, students prepared for the Career Fairs by updating their resumes, practicing their elevator pitches and learning about the difference between Business Professional and Business Casual. Refer to the assignments xref:students:fall2024/sprint2.adoc[here] and facilitate a conversation about their main takeaways or feedback on the assignments.

3. **Discuss upcoming Team Meeting** - With your team, spend time to figure out how you want to present your findings to your mentor for this week. For example, you could create a slide that highlights key points and blockers you're facing, prepare a demo, or anything else that seems suitable.   

* Next, have students answer the following questions in their daily stand-ups.

1. What have you been working on since the last meetings? 

2. What are you currently working on? 

3. Are there any blockers preventing you from doing your work? 

* Use the remainder of the time to work on your project.

* Sprint Tasks for students: xref:students:fall2024/sprint3.adoc[Sprint 3 Tasks]