= Sprint #7

[IMPORTANT]
====
The fall 2025 content is currently being revised. Please check back soon for updates. 
====

// Sprint-specific 
:sprint: 7
:previous-sprint: 6
:start-date: Nov 24 
:end-date: Dec 12, 2025

// Tasks with due dates 
:timesheet8-due: #14: Sun, Dec 3, 2025 @ 11:59 PM ET
//:timesheet9-due: #13: Sun, Nov 23, 2025 @ 11:59 PM ET
:pd-due: Wed, Dec 3, 2025 @ 11:59 PM ET
:report-due: Wed, Dec 10, 2025 @ 11:59 PM ET
:teamreport-due: Wed, Dec 10, 2025 @ 11:59 PM ET
:indy-tm-meeting: Tue, Nov 25, 2025 @ 08:00 AM ET
:indy-tm-meeting2: Tue, Dec 2, 2025 @ 08:00 AM ET
//:wl-tm-meeting: Tue, Nov 19, 2025 (Session 1 of 3)
//:final-presentation-draft: Wed, Nov 19, 2025 @ 11:59 PM ET
:final-presentation: Fri, Dec 5, 2025 @ 11:59 PM ET
:final-semester-due: Wed, Dec 10, 2025 @ 11:59 PM ET
:pd-due1: Wed, Dec 10, 2025 @ 11:59 PM ET
:survey-due: Wed, Dec 10, 2025 @ 11:59 PM ET
:project-charter: Fri, Dec 12, 2025 @ 11:59 PM ET

// Internal resources (kept local atm, but we could think of global approach)
//General
:sessions-deck-link: link:https://[Download Sessions Deck,window=_blank]
:student-content-tasks-link: xref:students:fall2025/sprint{sprint}.adoc[Sprint {sprint} Resource,window=_blank]
:student-previous-content-tasks-link: xref:students:fall2025/sprint{previous-sprint}.adoc[Sprint {previous-sprint} Resource,window=_blank]
:meeting-agendas-link: xref:meeting_agendas.adoc[TA Resources: Meeting Agendas]
:gradescope-link: link:https://www.gradescope.com/[Gradescope,window=_blank]
:timesheet-link: link:https://hcm-us10.hr.cloud.sap/sf/timesheet[Success Factors,window=_blank]
:warm-ups-link: xref:TAs:trainingModules/ta_training_module4_3_warmups.adoc[Warm-ups,window=_blank]
:qualtrics-link: link:https://[Qualtrics]
//Sprint 4
:mentor-feedback-guide-link: link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module5_4_mentor_feedback[Mentor and TA Feedback Guide,window=_blank]
:checkins-guide-link: link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module4_9_check_ins[Semester Check-Ins with Students,window=_blank]
:checkins-video-link: link:https://www.youtube.com/watch?v=YLBDkz0TwLM&t=69s[The Secret to Giving Great Feedback,window=_blank]
//Sprint 5
:worst-presentation-ppt: xref:attachment$WorstPresentationEverStandAlone.ppt[World Worst Presentation Ever,window=_blank]
:presentation-guide: xref:TAs:fall2025/final_presentation.adoc[Final Presentation Guide,window=_blank]
//Sprint 6
:presentation-info: xref:students:fall2025/final_presentation.adoc[Final Presentation Information,window=_blank]
//sprint 7
:project-charter: xref:TAs:update_project_charter.adoc[Project Charter,window=_blank]


== Sprint Timeline

[cols="2,3,3,2", options="header"]
|===
| Sprint Duration | Task | Due Date | Where

.10+| {start-date} - {end-date}

| <<complete-time-sheet, ✓ Complete Time Sheet>>
| **{timesheet8-due}** + 
//**{timesheet9-due}**
| {timesheet-link}

| **Indy TAs**: ✓ Attend Indy TA Team Meeting
| **{indy-tm-meeting}** + 
**{indy-tm-meeting2}**
| In-Person; Room ET219

| <<professional-development, ✓ Grade Professional Development #{previous-sprint}>>
| **{pd-due}**
| {gradescope-link}

| <<sprint-report, ✓ Grade Sprint Report #{previous-sprint}>>
| **{report-due}**
| {gradescope-link}

| <<complete-team-report, ✓ Complete Team Report #{previous-sprint}>>
| **{teamreport-due}**
| {gradescope-link}

| <<professional-development1, ✓ Grade Professional Development #{sprint}>>
| **{pd-due1}**
| {gradescope-link}

| <<presentation, ✓ Final Presentation>>
| **{final-presentation}**
| {gradescope-link}

| <<final-semester, ✓ Final Semester Feedback with Mentor>>
| **{final-semester-due}**
| {gradescope-link}

| <<survey, ✓ Corporate Partners Mid-year Final Survey>>
| **{survey-due}**
| {qualtrics-link} - pending
|===

_Clicking a task name will take you to its detailed description in Sprint Details._ 

[NOTE]
.Thanksgiving break
====
_Monday, 11/24 and Tuesday, 11/25: All labs and meetings as usual. No changes on Monday and Tuesday._
_Wednesday, 11/26, Thursday, 11/27 and Friday 11/28: Thanksgiving break - No classes._
====

== Sprint Schedule

[TIP]
.Deck for this Sprint
====
{sessions-deck-link} +
This is your working deck for the sprint. It includes agendas and slides you can adapt — just update the marked slides before using.
====

This sprint is a bit special — it runs for three weeks and wraps up with the final presentation.

[cols="2,2,3,2", options="header"]
|===
| Session | Duration | Focus | Where

| **Team Meeting #1**
| 50 min 
| Attendance, Project Updates/Sprint Review,  Q&A
.6+| In-Person / MS Teams

| **Lab Session #1**
| 1h 50m 
| _No Class_

| **Team Meeting #2**
| 50 min 
| Attendance, Project Updates/Sprint Review,  Q&A

| **Lab Session #2**
| 1h 50m 
| Attendance, Icebreaker, Reminders, **Team Activity**

| **Team Meeting #3**
| 50 min 
| **Final Presentation Session**

| **Lab Session #3**
| 1h 50m 
| Attendance, Icebreaker, Reminders, **Team Activity**

|===

_**Note:** Icebreakers, Reminders, and the Team Activity section may vary each sprint._

---

=== Lab Sessions

- **Icebreakers** : {warm-ups-link}

- **Reminders**: {student-content-tasks-link}

- **Team Activity** +

*** **Lab Session #1:** _No Class_


*** **Lab Session #2:** +
**Professional Development:** (Optional) +
Begin lab by discussing the professional development #4 Addressing Different Audiences. Talk about the background knowledge each of your audience members has, what they want to get out of your presentation and how to adjust your presentation style to ensure you meet those expectations. Facilitating this discussion will be crucial to executing a strong final presentation. +
**Reviewing Feedback on Presentation Draft** (Required) +
Go through the feedback that Data Mine Staff members left on your presentations in Gradescope. Review this as a team and work with your team to make necessary changes to your team's presentation.
This is the last lab you have to work on final presentations, so use your time wisely!

*** **Lab Session #3:** +
**Project Charter** (Required) +
Spend at least 30 minutes reviewing the Project Charter with your team. Please refer to {project-charter} assignment for more information. Whatever you do not finish in class will be the TA's responsibility to complete and submit. +
**Celebrate a Successful Semester!** (Optional) + 
Try to do something fun your last lab to celebrate a successful semester! You can bring in treats to celebrate, play fun games, or even try to coordinate something with your mentor. 

//For the full structure of meetings and labs, see the {meeting-agendas-link}.

'''

== Sprint Details


[[complete-time-sheet]]
=== ✓ Complete Time Sheet 

Timesheet {timesheet8-due} + 
Please submit through Success Factors or via Excel if you are in the credit-based TA role.

---

[[professional-development]]
=== ✓ Grade Professional Development #{previous-sprint}
[WARNING]
====
update me. 
====

Please grade the Professional Development #{previous-sprint} assignment on Gradescope. 

Due: on **Gradescope by {pd-due}.**

---

[[sprint-report]]
=== ✓ Grade Sprint Report #{previous-sprint}
[WARNING]
====
update me. 
====

The Sprint Report serves both as part of the course grading requirements and as a way to give you insight into where each team member stands in their work and how they are thinking about the project....


[IMPORTANT] 
====
**Grading**: Evaluate reports objectively based on the rubric, the evidence students provide, your observations from sessions, and the required number of sentences. Fair grading ensures accountability and consistency across the team and program.
====

Due: on **Gradescope by {report-due}**

---

[[complete-team-report]]
=== ✓ Complete Team Report #{previous-sprint}

This report captures your responsibilities as a TA (Scrum Master) and your team's progress in Sprint  {previous-sprint}. It helps you reflect on what has been completed, what still needs attention, and what's next. It also provides your liaison with the context they need to offer support.  +
**Note**: Please complete this report after grading Sprint Report #{previous-sprint} submissions.

Due: on **Gradescope by {teamreport-due}**

---

[[professional-development1]]
=== ✓ Grade Professional Development #{sprint}
[WARNING]
====
update me. 
====

Please grade the Professional Development #{sprint} assignment on Gradescope. ...

Due: on **Gradescope by {pd-due1}.**

---

[[presentation]]
=== ✓ Final Presentation 

Your team should finalize your presentation. Review the feedback provided by The Data Mine staff in Gradescope, discuss it as a team, and make any necessary updates to strengthen your presentation.


Submission Details:
- **Final Version**: Due Friday, December 5, 2025 at 11:59 PM ET (Sprint 7). Late work will not be accepted.
- **Submission**: TAs will submit on behalf of the whole team

---
[[final-meeting]]
=== ✓ Semester Feedback with Mentor

Set up a meeting with your mentor to complete your semester feedback of individual student's work and engagement in the project. Semester Evaluations are due **{final-semester-due}**. Be sure to share the rubric with your mentor early so they have time to prepare:  

** {mentor-feedback-guide-link}

---
[[survey]]
=== ✓ Corporate Partners Mid-year Final Survey

Follow the Qualtrics link to complete and submit the final report. You do not need to submit anything in Gradescope. link: -- will be updated later into the semester--




---




////
Previous Version
== Sprint Dates
_Monday, 11/24 and Tuesday, 11/25: All labs and meetings as usual. No changes on Monday and Tuesday._

_Wednesday, 11/26, Thursday, 11/27 and Friday 11/28: Thanksgiving break - No classes._

[cols="<.^1,^.^1"]
|===

|*Sprint Start Date*
|Mon 11/24

|*Sprint End Date*
|Fri 12/05

|===

Final Fall Presentations: December 8, 2025 - December 12, 2025
 * To recap the semester, your team will present on project progress and future goals. Please review the following Guidelines for the Final Presentation: xref:fall2025/final_presentation.adoc[Final Fall Presentation Details]. During this sprint, your team should complete a first draft of your presentation and continue working on this presentation until the final week of term when you will present to your CRP mentors and the Data Mine staff. 

== To Do 

&#10003; Complete Time Sheet

* Timesheet #14 due Sunday 11/30 at 11:59 PM EST.

&#10003; Grade Professional Development #6 on link:https://www.gradescope.com/[Gradescope] by Wednesday 12/03 at 11:59PM EST.

&#10003; Complete the Final Fall presentation Final Upload on Gradescope by Friday 12/5 at 11:59 PM EST.

&#10003; Grade Sprint Report #6 & Complete Team Report #6 & Grade Professional Development #7 on Gradescope by Wednesday 12/10 at 11:59PM EST. Please submit Team Report #6 AFTER completing Sprint Report #6 grading.

&#10003; Final Semester Feedback completed with mentor

* *What:* Meet with the corporate partner mentor to discuss individual student's work and engagement in the project.
* *When:* Due Wednesday, December 10 at 11:59 PM EST

** Please share the link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module5_4_mentor_feedback[Mentor and TA Feedback Guide] with your mentor ahead of time so they may prepare. 

&#10003;Complete the Corporate Partners Mid-year Final Survey individually. 

* *Where:* Follow the Qualtrics link to complete and submit the final report. You do not need to submit anything in Gradescope.
link: -- will be updated later into the semester--

* *When:* Due Wednesday, December 10, 2025 at 11:59 PM ET. Late work will not be accepted. 

&#10003; Submit updated project charter on link:https://www.gradescope.com/[Gradescope] by Friday December 12th at 11:59 EST. Review xref:TAs:update_project_charter.adoc[this assignment] for more details.  

== Sprint Schedule

=== Team Meeting #1 (50 minutes): 

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
* Ensure students are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #1 (1 hour and 50 Minutes): 

* Begin lab by discussing the xref:students:fall2025/sprint4.adoc[professional development #4] _Addressing Different Audiences_. Talk about the background knowledge each of your audience members has, what they want to get out of your presentation and how to adjust your presentation style to ensure you meet those expectations. Facilitating this discussion will be crucial to executing a strong final presentation.   

* Go through the feedback that Data Mine Staff members left on your presentations in Gradescope. Review this as a team and work with your team to make necessary changes to your team's presentation.**This is the last lab you have to work on final presentations, so use your time wisely!** 

=== Team Meeting #2 (50 minutes):

* Final Fall Presentation! Unless otherwise scheduled with your mentor or liaison, your presentation will given during this meeting time.  

=== Lab Section #2 (1 hour and 50 Minutes):


* Spend at least 30 minutes reviewing the Project Charter with your team. Please refer to xref:TAs:update_project_charter.adoc[this assignment] for more information. Whatever you do not finish in class will be the TA's responsibility to complete and submit. 


* Try to do something fun your last lab to celebrate a successful semester! You can bring in treats to celebrate, play fun games, or even try to coordinate something with your mentor. 
////
