= Sprint #1


== Intro Video
++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/c5Dp0u2iu9s" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
++++

== Sprint Dates

You can find a xref:projectmanagement:ceremonies.adoc#sprint-schedule[visual of the sprint schedule in the Agile Training Ceremonies page]. More details will be covered in the agile training below.  

*Labor Day is Monday, 9/1. There will be no CRP meetings/classes that day*

[cols="<.^1,^.^1"]
|===

|*Sprint Start Date*
|Mon 9/1

|*Sprint End Date*
|Fri 9/12

|===

== To Do

&#10003; Complete Time Sheet

* Timesheet #2 due Sunday 09/07 at 11:59 PM EST.

* Timesheet #3 due Sunday 09/14 at 11:59 PM EST.

&#10003; Attend TA Orientation Session Part 2, all TA are required to attend 1 session on Wednesday 09/03 in MRGN 129.

* Attend one of the 5 session below :
 
  * 8:30 am - 9:20 am 
  * 10:30 am - 11:20 am 
  * 12:30 pm - 1:20 pm 
  * 2:30 pm - 3:20 pm 
  * 3:30 pm - 4:20 pm 

&#10003; Complete TA PreAssessment Evaluation on gradescope due Friday, 09/05 at 11:59 PM EST.

&#10003; Set up you teams Kanban board following the instructions xref:trainingModules/ta_training_module5_3_dashboard_guide.adoc[Here]

&#10003; Talk about expectations for communication, netiquette, and attendance
 
&#10003; Help your students set up the ssh key on Github for Anvil: https://the-examples-book.com/starter-guides/tools-and-standards/git/github-anvil[Set up ssh key on GitHub for Anvil]

&#10003; Meet 1:1 with mentor to discuss project next steps

&#10003; Review responses for your Team Introductions Survey and assign roles and responsibilities(make subteams as necessary)

&#10003; If you have new students on the team, help them get up to speed on tasks to do (NDA, background readings, team introduction survey, etc)

&#10003; Enure you and all your team members have finished signing NDAs. Follow the instructions in the xref:TAs:nda_ip_agreements.adoc[TA NDA Process Guide]. This should be done no later than **September 5th**

== Sprint Schedule

=== Team Meeting #1 (50 minutes):
* Deep dive into the project
** Mentors should review their project charter in more detail. This review should include:
*** Roles and Responsibilities
*** Timeline
*** Objectives
*** Data
*** Deliverables
*** Tools
*** Resources
** Remember to leave time for questions from the student team
* Before the end of the meeting, assign background readings and prepwork that students should prepare before the next lab
** This can include content from the charter or other materials you have found helpful in your preparation for the project
** Please also consider start guides that are relevant to your project

=== Lab Section #1 (1 hour and 50 Minutes):
* Begin lab with an **Ice Breaker** to help foster a familiar and comfortable environment among the students. Please refer to the TA MS Teams chanel for more ideas

* Next, facilitate the xref:trainingModules/ta_training_module5_11_survey.adoc[Student Background Experience Assessment]
** Use the data from this xref:trainingModules/ta_training_module5_11_survey.adoc[Student Background Experience Assessment] to align your team with the appropriate roles and responsibilities denoted by your project charter
* Lastly, use the remainder of the time to review relative, supplementary content for your project including:
** https://the-examples-book.com/tools/[Starter Guides]
** Background Readings
** Sprint Tasks for students: xref:students:fall2025/sprint1.adoc[Sprint 1 Tasks]

=== Team Meeting #2 (50 minutes):
* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What was one interesting thing they learned from the project/background readings? 
** Were there any roadblocks that they experienced while completing this week's task(accessing company data, tools, Github, assignments)?
** What do they plan on committing to completing by the next mentor meeting?
** Do they have any tasks/opportunities they are really interested in taking up?
* Time for questions from students to mentor.
** Questions related to the project or tools.
** Questions related to the company. (Internship, Full-Time Opportunities, and etc.)
* Ensure students are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #2 (1 hour and 50 Minutes):
* Begin lab by doing an Agile review Kahoot with students and a sprint retrospective of sprint #1. 
* Followed by a daily stand-up and sprint planning for sprint #2.
** Use this PowerPoint to facilitate the discussion: xref:attachment$agile_reflection.pptx[Agile Reflection Guide]
* Use the remainder of the time to work on your project.

== The Data Mine Video
Check out this video showcasing previous and current TAs!

++++
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/2hYY20OGjpg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++