= Sprint #3

== Sprint Dates

[cols="<.^1,^.^1"]
|===

|*Sprint Start Date*
|Mon 9/29

|*Sprint End Date*
|Fri 10/10

|===

== To Do 

&#10003; Complete Time Sheet

* Timesheet #6 due Sunday 10/5 at 11:59 PM EST.

* Timesheet #7 due Sunday 10/12 at 11:59 PM EST.

&#10003; Grade Professional Development #2 & Team Report #2 by Wednesday 10/01 at 11:59PM EST.

&#10003; Grade Professional Sprint Report #2 on Gradescope by Wednesday 10/08 at 11:59PM EST.

&#10003; Attend Monthly Meeting #1, all TAs are required to attend 1 session on Wednesday 10/01. [Room TBD]

&#10003; See the xref:fall2025/schedule.adoc[Fall Schedule] for timesheet and report deadlines.

== Sprint Schedule

=== Team Meeting #1 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
** Questions related to the company. 
* Ensure students are assigned tasks to work on before meeting again in the next lab.


=== Lab Section #1 (1 hour and 50 Minutes):

* Begin lab by spending 10-15 minutes on your choice of the 3 following activities

1. **Ice Breaker** - Please refer to the TA MS Teams chanel for more ideas 

2. **Reviewing Professional Development Topics** - In Sprint #2, students learned about Elevator Pitches, Psychological Safety, Personal Branding. Refer to the assignments xref:students:fall2025/sprint2.adoc[here] and facilitate a conversation about their main takeaways or feedback on the assignments.

3. **Discuss upcoming Team Meeting** - With your team, spend time to figure out how you want to present your findings to your mentor for this week. For example, you could create a slide that highlights key points and blockers you're facing, prepare a demo, or anything else that seems suitable.   

* Complete a Sprint Retrospective of Sprint #2 by discussing the following questions with your team. 
1. What worked well during Sprint #2?

2. What didn't work well during Sprint #2? 

3. How can we improve Sprint #3? 

4. What are some questions you have regarding Sprint #2? 

* Next, have students answer the following questions in their daily stand-ups.

1. What have you been working on since the last meetings? 

2. What are you currently working on? 

3. Are there any blockers preventing you from doing your work? 

* Use the remainder of the time to work on your project.

=== Team Meeting #2 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles,roadblocks or barriers that they experienced while completing this weeks task?
** What do they plan on committing to completing by next mentor meeting?
* Time for questions from students to mentor.

* Ensure students are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #2 (1 hour and 50 Minutes):

* Begin lab by spending 10-15 minutes on your choice of the 3 following activities

1. **Ice Breaker** - Please refer to the TA MS Teams chanel for more ideas 

2. **Discuss upcoming Team Meeting** - With your team, spend time to figure out how you want to present your findings to your mentor for this week. For example, you could create a slide that highlights key points and blockers you're facing, prepare a demo, or anything else that seems suitable.   

* Next, have students answer the following questions in their daily stand-ups.

1. What have you been working on since the last meetings? 

2. What are you currently working on? 

3. Are there any blockers preventing you from doing your work? 

* Use the remainder of the time to work on your project.

* Sprint Tasks for students: xref:students:fall2025/sprint3.adoc[Sprint 3 Tasks]