= Sprint #1

[IMPORTANT]
====
The fall 2025 content is currently being revised. Please check back soon for updates. 
====


== Intro Video
++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/c5Dp0u2iu9s" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
++++

== Sprint Dates

You can find a xref:projectmanagement:ceremonies.adoc#sprint-schedule[visual of the sprint schedule in the Agile Training Ceremonies page]. More details will be covered in the agile training below.  

*Labor Day is Monday, 9/1. There will be no CRP meetings/classes that day*

[cols="<.^1,^.^1"]
|===

|*Sprint Start Date*
|Mon 9/1

|*Sprint End Date*
|Fri 9/12

|===

== To Do

&#10003; Complete Time Sheet

* Timesheet #2 due Sunday 09/07 at 11:59 PM EST.

&#10003; Attend TA Orientation Session Part 2, all TA are required to attend 1 session on Wednesday 09/03. [Room TBD]

&#10003; Complete TA PreAssessment Evaluation on gradescope due Friday, 09/12 at 11:59 PM EST.

&#10003; Set up you teams Kanban board following the instructions xref:trainingModules/ta_training_module5_3_dashboard_guide.adoc[Here]

&#10003; Have a conversation with your mentor about the use of AI on your project. Make sure you relay this information to your team and it is clear for everyone.

&#10003; Please prepare the xref:trainingModules/ta_training_module5_11_survey.adoc[Team Introduction Survey] in Qualtrics by following the linked instructions. You will have to customize this survey. 
 
&#10003; Before **Lab #1** Review the instructions for this activity at the xref:projectmanagement:agile-lego-activity.adoc[Agile Lego Activity] page

 

== Sprint Schedule

=== Team Meeting #1 (50 minutes):

* Team Introductions
** Mentors, TAs, and Students should introduce themselves to the team
** _Cameras are required to be on for all online meetings_
*  Review Project charter
**  Company Overview
** Project Overview
* Before the end of the meeting, assign background readings and prepwork that students should prepare before the next lab
** This can include content from the charter or other materials you have found helpful in your preparation for the project


=== Lab Section #1 (1 hour and 50 Minutes):

* Begin lab with an **Ice Breaker** to get to know your students better. Please refer to the TA MS Teams chanel for more ideas  

* **NDAs & IP Agreements** (as needed)
** Some team will be required to sign NDAs and IP agreements before they can start working on their project
** A Data Mine staff member will be at your lab to help facilitate the signing of NDAs and IP agreements
* **Agile Lego Activity**
** Review the instructions for this activity at the xref:projectmanagement:agile-lego-activity.adoc[Agile Lego Activity] page
** Please use the stock cards to create name tags for all in attendance (students and TAs)
** A Data Mine staff member will be at your lab to help facilitate this activity

* **Team Introduction Survey** 
** Please provide students with the link to your Qaultrics survey. You can have students do it in class or on their own, but it should be complete by Wednesday, September 4th at 11:59pm. Please refer xref:trainingModules/ta_training_module5_11_survey.adoc[Here] for more information about how to prepare the survey. 

=== Team Meeting #2 (50 minutes):

* Deep dive into the project
** Mentors should review their project charter in more detail. This review should include:
*** Roles and Responsibilities
*** Timeline
*** Objectives
*** Data
*** Deliverables
*** Tools
*** Resources
** Remember to leave time for questions from the student team
* Before the end of the meeting, assign background readings and prepwork that students should prepare before the next lab
** This can include content from the charter or other materials you have found helpful in your preparation for the project
** Please also consider start guides that are relevant to your project


=== Lab Section #2 (1 hour and 50 Minutes):

* Begin lab with an **Ice Breaker** to help foster a familiar and comfortable environment among the students. Please refer to the TA MS Teams chanel for more ideas

* Next, share this sprint's professional development topic of Organizational Behavior
** Use this powerpoint to facilitate the discussion: xref:attachment$Organizational_Behavior.pptx[Organizational Behavior Facilitator Guide]
* Next, facilitate the xref:trainingModules/ta_training_module5_11_survey.adoc[Student Background Experience Assessment]
**  You will have to prepare this survey in Qualtrics before the lab. We encourage you to customize the questions to fit what you want to know about your team and what will be important to your project. 

** *ACTION ITEM*: There is a section under the skills category where need to customize the contents to align with topics that are significant to understand for your project. For example, if your project will involve building models, have students rank their knowledge on things like regressions, cluster analysis, decision trees, ect. 

** Use the data from this survey to align your team with the appropriate roles and responsibilities denoted by your project charter
* Lastly, use the remainder of the time to review relative, supplementary content for your project including:
** xref:starter-guides:ROOT:index.adoc[Starter Guides]
** Background Readings
** Sprint Tasks for students: xref:students:fall2024/sprint1.adoc[Sprint 1 Tasks]

== The Data Mine Video
Check out this video showcasing previous and current TAs!

++++
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/2hYY20OGjpg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++