= Sprint #7


== Sprint Dates
_Monday, 11/24 and Tuesday, 11/25: All labs and meetings as usual. No changes on Monday and Tuesday._

_Wednesday, 11/26, Thursday, 11/27 and Friday 11/28: Thanksgiving break - No classes._

[cols="<.^1,^.^1"]
|===

|*Sprint Start Date*
|Mon 11/24

|*Sprint End Date*
|Fri 12/05

|===

Final Fall Presentations: December 8, 2025 - December 12, 2025
 * To recap the semester, your team will present on project progress and future goals. Please review the following Guidelines for the Final Presentation: xref:fall2025/final_presentation.adoc[Final Fall Presentation Details]. During this sprint, your team should complete a first draft of your presentation and continue working on this presentation until the final week of term when you will present to your CRP mentors and the Data Mine staff. 

== To Do 

&#10003; Complete Time Sheet

* Timesheet #14 due Sunday 11/30 at 11:59 PM EST.

&#10003; Grade Professional Development #6 & Complete Team Report #6 on link:https://www.gradescope.com/[Gradescope] by Wednesday 12/03 at 11:59PM EST.

&#10003; Complete the Final Fall presentation Final Upload on Gradescope by Friday 12/5 at 11:59 PM EST.

&#10003; Grade Sprint Report #6 & Professional Development #7 on Gradescope by Wednesday 12/10 at 11:59PM EST.

&#10003; Final Semester Feedback completed with mentor

* *What:* Meet with the corporate partner mentor to discuss individual student's work and engagement in the project.
* *When:* Due Wednesday, December 10 at 11:59 PM EST

** Please share the link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module5_4_mentor_feedback[Mentor and TA Feedback Guide] with your mentor ahead of time so they may prepare. 

&#10003;Complete the Corporate Partners Mid-year Final Survey individually. 

* *Where:* Follow the Qualtrics link to complete and submit the final report. You do not need to submit anything in Gradescope.
link: -- will be updated later into the semester--

* *When:* Due Wednesday, December 10, 2025 at 11:59 PM ET. Late work will not be accepted. 

&#10003; Submit updated project charter on link:https://www.gradescope.com/[Gradescope] by Friday December 12th at 11:59 EST. Review xref:TAs:update_project_charter.adoc[this assignment] for more details.  

== Sprint Schedule

=== Team Meeting #1 (50 minutes): 

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
* Ensure students are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #1 (1 hour and 50 Minutes): 

* Begin lab by discussing the xref:students:fall2025/sprint4.adoc[professional development #4] _Addressing Different Audiences_. Talk about the background knowledge each of your audience members has, what they want to get out of your presentation and how to adjust your presentation style to ensure you meet those expectations. Facilitating this discussion will be crucial to executing a strong final presentation.   

* Go through the feedback that Data Mine Staff members left on your presentations in Gradescope. Review this as a team and work with your team to make necessary changes to your team's presentation.**This is the last lab you have to work on final presentations, so use your time wisely!** 

=== Team Meeting #2 (50 minutes):

* Final Fall Presentation! Unless otherwise scheduled with your mentor or liaison, your presentation will given during this meeting time.  

=== Lab Section #2 (1 hour and 50 Minutes):


* Spend at least 30 minutes reviewing the Project Charter with your team. Please refer to xref:TAs:update_project_charter.adoc[this assignment] for more information. Whatever you do not finish in class will be the TA's responsibility to complete and submit. 


* Try to do something fun your last lab to celebrate a successful semester! You can bring in treats to celebrate, play fun games, or even try to coordinate something with your mentor. 
