= Sprint #5


== Intro Video

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/13g7l3zQPq4?si=dnseCld3iCECTpJk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
++++

== Sprint Dates

[cols="<.^1,^.^1"]
|===

|*Sprint Start Date*
|Mon 10/27

|*Sprint End Date*
|Fri 11/7

|===

== To Do

&#10003; Set-up a meeting with CRP mentor to complete mid-semester student feedback by Wednesday 10/29 at 11:59 PM EST!  

&#10003; Complete Time Sheet

* Timesheet #10 due Sunday 11/02 at 11:59 PM EST.

* Timesheet #11 due Sunday 11/09 at 11:59 PM EST.

&#10003; Grade Professional Development #4 & Team Report #4 on Gradescope by Wednesday 10/29 at 11:59PM EST.

&#10003; Grade Sprint Report #4 on Gradescope by Wednesday 11/05 at 11:59PM EST.

&#10003; Attend Monthly Meeting #2, All TA are required to attend 1 session on Wed 10/29. [Room TBD]

&#10003; Complete final fall presentation draft materials and submit on Gradescope by Wednesday 11/5 at 11:59 PM EST.

&#10003; Work with your mentor to get a list of who will be attending your Final presentation. Share this with your students so they can tailor their final fall preparation to their audience.

&#10003; Refer xref:TAs:fall2025/final_presentation.adoc[here] for more information about how to prepare your team for the Final Presentation and activity in lab #2.   

== Sprint Schedule

=== Team Meeting #1 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.

* Ensure students are assigned tasks to work on before meeting again in the next lab.


=== Lab Section #1 (1 hour and 50 Minutes):
* Begin lab by completing the following activity
** Use this PowerPoint to facilitate the discussion: xref:attachment$WorstPresentationEverStandAlone.ppt[World Worst Presentation Ever]

* Complete a Sprint Retrospective of Sprint #4 by discussing the following questions with your team. 
1. What worked well during Sprint #4?

2. What didn't work well during Sprint #4? 

3. How can we improve Sprint #5? 

4. What are some questions you have regarding Sprint #4? 

* Next, have students answer the following questions in their daily stand-ups.

1. What have you been working on since the last meetings? 

2. What are you currently working on? 

3. Are there any blockers preventing you from doing your work? 

* Use the remainder of the time to work on your project.

=== Team Meeting #2 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles,roadblocks or barriers that they experienced while completing this weeks task?
** What do they plan on committing to completing by next mentor meeting?
* Time for questions from students to mentor.

* Ensure students are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #2 (1 hour and 50 Minutes):

* Begin lab with a quick ice breaker. Please refer to the TA MS Teams chanel for more ideas. There will be a lot of material to cover this lab, so don't spend too much time on this.  

* Next, have students answer the following questions in their daily stand-ups.

1. What have you been working on since the last meetings? 

2. What are you currently working on? 

3. Are there any blockers preventing you from doing your work? 

* During this lab, we will focus on preparing for the Final Presentation. Please refer xref:TAs:fall2025/final_presentation.adoc[here] for more information. 
** As a team, please complete the transformation matrix to get an outline for your final presentation. Use this outline to begin creating you final presentation. Additionally, reference the storytelling framework and incorporate a setup, conflict and resolution throughout your presentation. *You should have your transformation matrix and storytelling complete by the end of lab.* 
* Use the remaining time to work on your presentation outline or for project work.  
* Sprint Tasks for students: xref:students:fall2025/sprint5.adoc[Sprint 5 Tasks]