= <INSERT TOPIC NAME>

Brief blurb that introduces the topic in a simple way for someone who has never heard of it. Try to keep this to less than 4 sentences.

== Common Applications

=== Common Industries

- 
- 
- 
- 
- 

=== Common Problem Types

- 
- 
- 
- 
- 

== A Brief History

Give a brief synopsis on this topic.

== Code Examples

NOTE: All of the code examples are written in Python, unless otherwise noted.

=== Notebooks

TIP: Download the Notebook if you are going to upload it to Anvil to run. 

xref:attachment$PROJECT .ipynb[PROJECT Notebook]

=== Containers 

TIP: The Container and Notebook versions are the same, except the container file runs a Jupyter lab with the Notebook already in it along with all packages and data necessary to run the Notebook. (https://the-examples-book.com/starter-guides/data-engineering/containers/using-data-mine-containers)[Click here to learn when and why you should be using Containers, along with how to do so.]

[source,bash]
----
#pull container, only needs to be run once
docker pull ghcr.io/thedatamine/starter-guides:<NAME OF CONTAINER>

#run container
docker run -p 8888:8888 -it ghcr.io/thedatamine/starter-guides:<NAME OF CONTAINER>
----

Need help implementing any of this code? Feel free to reach out to mailto:datamine-help@purdue.edu[datamine-help@purdue.edu] and we can help!

== Resources

All resources are chosen by Data Mine staff to be of decent quality, and most if not all content is free. 

=== Websites



=== Videos



=== Books



=== Articles



=== Free Courses    


