= TDM 10200: Python Project 2 -- Spring 2025

**Motivation:** We get more comfortable indexing and grouping values in Python.  It is helpful to know that, when we ask for the value counts of a column in a Pandas data frame, we get the results in sorted order, without even having to sort the results ourselves!

**Context:** As a practice counting the number of data values using Python, it is helpful to pay attention to missing values.

**Scope:** Python, value counts, missing values

.Learning Objectives:
****
- Extract data in Python that meets certain conditions
- Combine values from multiple columns of a Pandas data frame
- Combine multiple conditions
- Handle missing data
****

Make sure to read about, and use the template found xref:ROOT:templates.adoc[here], and the important information about project submissions xref:ROOT:submissions.adoc[here].

== Dataset(s)

This project will use the following datasets:

- `/anvil/projects/tdm/data/olympics/athlete_events.csv`
- `/anvil/projects/tdm/data/election/itcont1980.txt`

== Questions

=== Question 1 (2 pts)

Create a Pandas data frame called `myDF` from the file of Olympics athlete events data:

`/anvil/projects/tdm/data/olympics/athlete_events.csv`

Using the methods that you learned in Project 1, Questions 3, 4, 5, find the number of times that each of the years appears (in the `Year` column in `myDF`).  As in Project 1, `value_counts()` should be helpful for this purpose.

[NOTE]
====
FYI, the results from `value_counts()` are called a `Series`.  In a `Series`, we have values (in this case, the number of times that each year appears), and also an `index` (in this case, the years are the `index`).
====

Make a plot of the number of times that each year appears.

[In the plot, you should see that the number of athletes is increasing over time, and also you should be able to see the halt in the Olympics during the two World Wars, and also you should see the 2-year rotation between summer and winter Olympics that began in the 1990s.]

.Deliverables
====
- The results of `value_counts()` showing the number of athletes participating in the Olympics during each year.
- A plot showing the number of athletes participating in the Olympics during each year.
- As *always*, be sure to document your work from Question 1 (and from all of the questions!), using some comments and insights about your work.  We will stop adding this note to document your work, but please remember, we always assume that you will *document every single question with your comments and your insights*.
====

[IMPORTANT]
====
Please remember, we always assume that you will *document every single question with your comments and your insights*.
====

=== Question 2 (2 pts)

Again studying the Olympics athletes events from the same file:

`/anvil/projects/tdm/data/olympics/athlete_events.csv`

we can practice using the `value_counts()` a little more.

Which value appears in the "NOC" column the most times?

Which value appears in the "Name" column the most times?

[NOTE]
====
When we use `value_counts()` it is helpful to know that this is called a "method" for "Series".  A "method" is like a function but it is used with a particular class.
====

.Deliverables
====
- The value that appears in the "NOC" column the most times.
- The value that appears in the "Name" column the most times.
====

=== Question 3 (2 pts)

For this question, we only pay attention to the state (not the city) for each airport.  Which state has the largest number of airports?  How many airports are located in that state?  We can extract (only) the states from each airport by writing:

[source, python]
----
myDF['state']
----

and then the `value_counts` function gives the number of airports in each state:

[source, python]
----
myDF['state'].value_counts()
----

[NOTE]
====
You do not need to make a plot of the value counts for the airports, but you are welcome to try this, if you want to!
====

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_dwczw0nl&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_d7iy8as1&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++

.Deliverables
====
- Use the `value_counts` function to find the number of airports in each state.
- Be sure to document your work from Question 3, using some comments and insights about your work.
====

=== Question 4 (2 pts)

Now load the ice cream products data set, stored here:

`/anvil/projects/tdm/data/icecream/combined/products.csv`

Using the `value_counts` function with the `brand` column from the ice cream products data set, how many rows are associated with each `brand`?  In other words, how many times does each `brand` occur in the `brand` column?

Now solve the same question with a different data set.
First load the head of the ice cream reviews data set, and then find how many times each `brand` occurs in the ice cream reviews data set:

`/anvil/projects/tdm/data/icecream/combined/reviews.csv`

How many times does each brand occur in the `reviews.csv` data set?

You work will be similar to the work from Question 3.  Be sure to document each question with comments about your work.

.Deliverables
====
- Use the `value_counts` function to find the number of times that each `brand` occurs in the ice cream products data set.
- Then use the `value_counts` function again, to find the number of times that each `brand` occurs in the ice cream reviews data set.
- Be sure to document your work from Question 4, using some comments and insights about your work.
====

=== Question 5 (2 pts)

Now we use `matplotlib` to display the `value_counts` from Question 4.  To accomplish this, we first load `matplotlib` as follows:

[source, python]
----
import matplotlib.pyplot as plt
----

Then we can save our counts into a variable, which we choose to call `mycounts` like this:

[source, python]
----
mycounts = myDF['brand'].value_counts()
----

and finally we can plot the names of the brands (which are the `index` values in `mycounts`) on the x-axis, and the values on the y-axis, as follows:

[source, python]
----
plt.bar(mycounts.index, mycounts)
----

Give this a try yourself, with BOTH of the data sets from Question 4.

In other words, make one plot that shows the number of occurrences of the `brand` in the ice cream products data set, and then make another plot that shows the number of occurrences of the `brand` in the ice cream reviews data set.

.Deliverables
====
- Make one plot that shows the number of occurrences of the `brand` in the ice cream products data set, and then make another plot that shows the number of occurrences of the `brand` in the ice cream reviews data set.
- Be sure to document your work from Question 5, using some comments and insights about your work.
====

== Submitting your Work

Please make sure that you added comments for each question, which explain your thinking about your method of solving each question.  Please also make sure that your work is your own work, and that any outside sources (people, internet pages, generating AI, etc.) are cited properly in the project template.

Congratulations! Assuming you've completed all the above questions, you've just finished your first project for TDM 10200! If you have any questions or issues regarding this project, please feel free to ask in seminar, over Piazza, or during office hours.

Prior to submitting your work, you need to put your work xref:ROOT:templates.adoc[into the project template], and re-run all of the code in your Jupyter notebook and make sure that the results of running that code is visible in your template.  Please check the xref:ROOT:submissions.adoc[detailed instructions on how to ensure that your submission is formatted correctly]. To download your completed project, you can right-click on the file in the file explorer and click 'download'.

Once you upload your submission to Gradescope, make sure that everything appears as you would expect to ensure that you don't lose any points. We hope your first project with us went well, and we look forward to continuing to learn with you on future projects!!

.Items to submit
====
- firstname_lastname_project1.ipynb
====

[WARNING]
====
It is necessary to document your work, with comments about each solution.  All of your work needs to be your own work, with citations to any source that you used.  Please make sure that your work is your own work, and that any outside sources (people, internet pages, generating AI, etc.) are cited properly in the project template.

You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not.

**Please** take the time to double check your work. See https://the-examples-book.com/projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====

