= Sprint #6

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 10/31
|Mon 10/28

|*Sprint End Date*
|Wed 11/13
|Sun 11/10

|*Due Date*
2+| Wed 11/13 by 11:59 PM ET

|===

== Sprint Tasks

=== &#10003; Final Presentation

To recap the semester, your team will present on project progress and future goals. Please review the following Guidelines for the Final Presentation: xref:fall2024/final_presentation.adoc[Final Fall Presentation Details]. During this sprint, your team should complete a first draft of your presentation and continuing working on this presentation until the final week of term when you will present to your CRP mentors and the Data Mine staff.

*When:* First Draft due Wednesday, November 13, 2024 at 11:59 PM ET. Late work will not be accepted. Final Draft due Friday, November 29, 2024 at 11:59 PM ET. Late work will not be accepted. *You're TA will submit on behalf of the whole team*

*What:* Final presentation draft - refer here for xref:fall2024/final_presentation.adoc[Final Fall Presentation Details]

*Where:* link:https://www.gradescope.com/[Gradescope] - *You're TA will submit on behalf of the whole team*


=== &#10003; Professional Development 

The Data Mine Corporate Partners program is a professional development program. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

Each sprint you will complete a few professional development-related tasks. In this sprint, we will continue to prepare you for your Final Presentation by talking about how to address different types of audiences. Additionally, we will review how to give good feedback. 

++++
<html>
<head>
<meta name="viewport"  content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}

.accordion:after {
  content: '\002B';
  color: #777;
  font-weight: bold;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2212";
}

.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>

<button class="accordion">Addressing Different Audiences</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, November 6, 2024 at 11:59 PM ET. Late work will not be accepted.
		</p>
<br>
	</div>
	<div>
		<p><b>What: </b>Read this article about <a href="https://www.quanthub.com/how-to-identify-your-audience-for-impactful-data-storytelling/"> How to Address Different Audiences</a> and complete the assignment in "Sprint 6: Professional Development".</p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 6: Professional Development".</p>
<br>
  </div>
  <div>
		<p><b>Why: </b> Your team will likely have a variety of people at your final presentations. Each will have a different amount of background knowledge about the project and will have different expectations for what they expect to get out of this project. It is important to recognize these differences and address them the best you can while presenting. </p>
<br>
  </div>
</div>

<button class="accordion">Giving Effective Feedback</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, November 6, 2024 at 11:59 PM ET. Late work will not be accepted. 
		</p>
<br>
    </div>
    <div>
		<p><b>What: </b>Watch the following video on <a href="https://www.youtube.com/watch?v=YLBDkz0TwLM&t=69s"> Giving Feedback</a> and complete the reflection questions in Gradescope.</p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 6: Professional Development".</a></p>
<br>
  </div>
  <div>
		<p><b>Why: </b> As the semester comes to a close, it is important to give constructive feedback to your TA, Mentor and The Data Mine. Your feedback will be used to improve the program for spring and future semesters, therefore, it is important you share your opinions. However, it is equally , if not, more important to learn how to share that feedback in a way that respectful and impactful. </p>
<br>
  </div>
</div>

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

</body>
</html>
++++

=== &#10003; Sprint #6 Report 

*When:* Due Wednesday, November 13, 2024 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in Sprint #6 Retro Report. 

*Where:* link:https://www.gradescope.com/[Gradescope] 