= Sprint #3

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 9/19
|Mon 9/16

|*Sprint End Date*
|Wed 10/2
|Sun 9/29

|*Due Date*
2+| Wed 10/2 by 11:59 PM ET

|===

== Sprint Tasks


=== &#10003; Professional Development 

During this sprint, we will complete Mock Interviews to prepare for upcoming interviews you may have. Additionally, we will learn how to efficiently read Scientific Papers to aid in you project research for Corporate partners.

++++
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}

.accordion:after {
  content: '\002B';
  color: #777;
  font-weight: bold;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2212";
}

.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>

<button class="accordion">Complete Mock Interview</button>
<div class="panel">
  <div>
    <p><b>When: </b>Due Wednesday, September 25, 2024 at 11:59 PM ET. Late work will not be accepted.</p>
    <br>
  </div>
  <div>
    <p><b>What: </b>Review assignment 2 of <a href="https://the-examples-book.com/crp/students/resume_cv_interview">Resume and Complete Mock Interview Assignment</a> and write a reflection in "Sprint 3: Professional Development".</p>
    <br>
  </div>
  <div>
    <p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 3: Professional Development".</p>
    <br>
  </div>
  <div>
    <p><b>Why: </b>Mock interviews are important because they provide a valuable opportunity to practice and refine your interviewing skills in a low-stakes environment. Refining these skills will prepare you to crush your interview and secure your internship or job.</p>
    <br>
  </div>
</div>

<button class="accordion">Scientific Papers</button>
<div class="panel">
  <div>
    <p><b>When: </b>Due Wednesday, September 25, 2024 at 11:59 PM ET. Late work will not be accepted.</p>
    <br>
  </div>
  <div>
    <p><b>What: </b>Watch this video about <a href="https://www.youtube.com/watch?v=Gv5ku0eoY6k?t=11" target="_blank" rel="noopener noreferrer">How to Read a Scientific Paper</a> (stop at 7:30) and then fill out the reflection questions in Gradescope. Next, using the techniques learned in the video, read this scientific paper <a href="http://mysite.science.uottawa.ca/rsmith43/Zombies.pdf">When Zombie Attack!</a> and answer the accompanying questions in Gradescope.</p>
    <br>
  </div>
  <div>
    <p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 3: Professional Development".</p>
    <br>
  </div>
  <div>
    <p><b>Why: </b>In Corporate Partners, often students spend the first few weeks of their project conducting literary analyses to get background information on their project. Learning how to read these texts efficiently and effectively will save you time and allow you to get the most out of the research.</p>
    <br>
  </div>
</div>

<button class="accordion">Implicit Biases-Schemas</button>
<div class="panel">
  <div>
    <p><b>When: </b>Due Wednesday, September 25, 2024 at 11:59 PM ET. Late work will not be accepted.</p>
    <br>
  </div>
  <div>
    <p><b>What: </b>Watch the following video <a href="https://www.youtube.com/watch?v=OQGIgohunVw&list=PLWG_vsmMJ2clEeGKVyrOIKlOYrjFnVKqa&index=2">Implicit Biases: Lesson #1 - Schemas</a> (3 minutes).</p>
    <br>
  </div>
  <div>
    <p><b>Where: </b>Complete the reflection for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 3: Professional Development".</p>
    <br>
  </div>
  <div>
    <p><b>Why: </b>Schemas are crucial for efficiently processing everyday events, but they can also lead to unconscious biases. It is essential to understand and recognize the existence of these biases and implement strategies to mitigate their negative impacts.</p>
    <br>
  </div> 
</div>

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

</body>
</html>
++++

=== &#10003; Sprint #3 Report 

*When:* Due Wednesday, October 2, 2024 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in the Sprint #3 Report accessed on Gradescope. You will write your answers directly in the Gradescope assignment.

*Where:* link:https://www.gradescope.com/[Gradescope] 
