= Sprint #3

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 9/19
|Mon 9/16

|*Sprint End Date*
|Wed 10/2
|Sun 9/29

|*Due Date*
2+| Wed 10/2 by 11:59 PM ET

|===

== Sprint Tasks


=== &#10003; Professional Development 

The Data Mine Corporate Partners program is a workforce training program that includes professional development. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

In each sprint you will complete a few professional development-related tasks. During this sprint, we will focus on time management skills and self awareness.

TO BE UPDATED

=== &#10003; Sprint #3 Report 

*When:* Due Wednesday, October 2, 2024 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in the Sprint #3 Report accessed on Gradescope. You will write your answers directly in the Gradescope assignment.

*Where:* link:https://www.gradescope.com/[Gradescope] 
