= Sprint #2

== Intro Video

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/B9CIIUJWGlc?si=fjPQqSMoaPEvEYhX" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
++++

== Sprint Dates

*_Monday, 9/2:  Labor Day (no Corporate Partner meetings/classes)_*

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 9/5
|Mon 9/2

|*Sprint End Date*
|Wed 9/18
|Sun 9/15

|*Due Date*
2+| Wed 9/18 by 11:59 PM ET

|===

== Sprint Tasks

=== &#10003; Github on Anvil (Setting up ssh keys)

As soon as possible, set up your ssh key for Github on Anvil. ssh key are the way for github to verify that you are who you say you are. This will allow you to push and pull code from your team's repository and collaborate with your team members on github.

*When:* As soon as possible!

*What:*  https://the-examples-book.com/starter-guides/tools-and-standards/git/github-anvil[Set up ssh key on Github for Anvil]. There is nothing to submit for this item.

*Where:* https://the-examples-book.com/starter-guides/tools-and-standards/git/github-anvil[Set up ssh key on Github for Anvil]

=== &#10003; Starter Guides

Use these starter guides to up-skill during the first couple of sprints. You will be using these tools throughout the semester on your semester!

*When:* When you are ready to upskill!

*What:* Review the following xref:starter-guides:ROOT:index.adoc[Starter Guides] and work with your TA to see which topics are relevant for your project - there is nothing to submit for this item.

*Where:* xref:starter-guides:ROOT:index.adoc[Starter Guides]

=== &#10003; Professional Development 

The Data Mine Corporate Partners program is a professional development program. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

In each sprint, you will complete a few professional development-related tasks. During this sprint, we will focus on skills needed for the upcoming Career Fairs, including resume updates, elevator pitches, and business attire. 

++++
<html>
<head>
<meta name="viewport"  content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}

.accordion:after {
  content: '\002B';
  color: #777;
  font-weight: bold;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2212";
}

.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>

<button class="accordion">Resume Update</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, September 11, 2024 at 11:59 PM ET. Late work will not be accepted.
		</p>
<br>
	</div>
	<div>
		<p><b>What: </b>Review assignment 1 of <a href="https://the-examples-book.com/crp/students/resume_cv_interview">Resume and Complete Mock Interview Assignment</a> and write a reflection in "Sprint 2: Professional Development".</p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 2: Professional Development".</p>
<br>
  </div>
  <div>
		<p><b>Why: </b>Updating your resume is crucial for career fairs because it ensures that your most recent accomplishments, skills, and experiences are highlighted. Presenting a polished resume at the Career Fair will help you get your dream internship/job. </p>
<br>
  </div>
</div>

<button class="accordion">Create a Elevator Pitch</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, September 11, 2024 at 11:59 PM ET. Late work will not be accepted. 
		</p>
<br>
	</div>
	<div>
		<p><b>What: </b>Review <a href="https://the-examples-book.com/crp/students/elevator_pitch">Elevator Pitch Guide.</a> and submit your elevator pitch in "Sprint 2: Professional Development".</p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 2: Professional Development".</a></p>
<br>
  </div>
  <div>
		<p><b>Why: </b> Elevator pitches are crucial for career fairs because they allow you to quickly capture the interest of potential employers, making a memorable impression in a short amount of time. A well-crafted elevator pitch can effectively communicate your skills, experiences, and career goals, setting the stage for deeper conversations and networking opportunities. </p>
<br>
  </div>
</div>
<button class="accordion">Business Attire</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, September 11, 2024 at 11:59 PM ET. Late work will not be accepted.</p>
<br>
	</div>
	<div>
		<p><b>What: </b>Read the following article on <a href="https://www.liveabout.com/business-casual-attire-2061335"> Business Professional vs. Business Casual</a> (5 minutes).</p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 2: Professional Development".</p>
<br>
  </div>
  <div>
		<p><b>Why: </b> Understanding the difference between business professional and business casual is important because it ensures you dress appropriately for various professional settings, including career fairs,interviews, networking events, and even The Symposium. Dressing correctly demonstrates respect for the occasion and shows that you understand and can adhere to workplace norms, which helps make a positive impression on your reputation and image. </p>
<br>
  </div>
</div>
<button class="accordion">Team Contract</button>
<div class="panel">
	<div>
		<p><b>When: </b>This will be completed in your first of second lab of Sprint #2. Do not worry about submission.</p>
<br>
	</div>
	<div>
		<p><b>What: </b> In lab, you will have a discussion about the topics included in the Team Contract outline. This will help establish norms and clear expectations for your team. Before lab, take a brief look at the Team Contract Outline provided to begin thinking about what is important to add for your project.</p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Refer to the assignment here (LINK). Please take a look at the outline provided.</p>
<br>
  </div>
  <div>
		<p><b>Why: </b> Creating a team contract is important because it establishes clear expectations, roles, and responsibilities for all team members from the beginning. This document promotes accountability, enhances communication, and minimizes misunderstandings by outlining agreed-upon norms and procedures. It serves as a reference point throughout the project, helping to resolve conflicts and ensuring everyone is aligned with the team's goals. </p>
<br>
  </div>
</div>
<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

</body>
</html>
++++

=== &#10003; Sprint #2 Report 

*When:* Due Wednesday, September 18, 2024 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in the Sprint #2 Report accessed on Gradescope. You will write your answers directly in the Gradescope assignment. 

*Where:* link:https://www.gradescope.com/[Gradescope] 


