= Sprint #6

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 10/31
|Mon 10/28

|*Sprint End Date*
|Wed 11/13
|Sun 11/10

|*Due Date*
2+| Wed 11/13 by 11:59 PM ET

|===

== Sprint Tasks

=== &#10003; Final Presentation

To recap the semester, your team will present on project progress and future goals. Please review the following Guidelines for the Final Presentation: xref:fall2024/final_presentation.adoc[Final Fall Presentation Details]. During this sprint, your team should complete a first draft of your presentation and continuing working on this presentation until the final week of term when you will present to your CRP mentors and the Data Mine staff.

*When:* First Draft due Wednesday, November 13, 2024 at 11:59 PM ET. Late work will not be accepted. Final Draft due Friday, November 29, 2024 at 11:59 PM ET. Late work will not be accepted. *You're TA will submit on behalf of the whole team*

*What:* Final presentation draft - refer here for xref:fall2024/final_presentation.adoc[Final Fall Presentation Details]

*Where:* link:https://www.gradescope.com/[Gradescope] - *You're TA will submit on behalf of the whole team*


=== &#10003; Professional Development 

The Data Mine Corporate Partners program is a professional development program. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

Each sprint you will complete a few professional development-related tasks. In this sprint, we will review Initiative & Following Through and Presentation Strategies.



=== &#10003; Sprint #6 Report 

*When:* Due Wednesday, November 13, 2024 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in Sprint #6 Retro Report. 

*Where:* link:https://www.gradescope.com/[Gradescope] 