= Sprint #0

// Sprint-specific 
:sprint-dates: Aug 24 - Aug 28, 2026

// Tasks with due dates 
:timesheet1-due: #1: Sun, Aug 30, 2026 @ 11:59 PM ET
:preassessment-due: Fri, Sept 4, 2026 @ 11:59 PM ET

// Resources
:gradescope-link: link:https://www.gradescope.com/[Gradescope,window=_blank]
:timesheet-link: link:https://hcm-us10.hr.cloud.sap/sf/timesheet[Success Factors,window=_blank]

== Sprint Timeline

> {sprint-dates}

*Labor Day is Monday, 9/7. There will be no CRP meetings/classes that day*

[cols="3,3,2", options="header"]
|===
| Task | Due Date | Where

| &#10003; Complete Time Sheet
| **{timesheet1-due}**
| {timesheet-link}

| &#10003; Attend TA Orientation Session Part 2
| Time TBD
| Location TBD

| &#10003; Complete TA PreAssessment Evaluation
| **{preassessment-due}**
| TA {gradescope-link}

|===

== To Prepare

&#10003; Verify you have access to your team's MS Teams Channel and the TA MS Teams Channel prior to the first day of class. Please reach out to link:mailto:datamine@purdue.edu[Data Mine Staff] if you haven't received it yet. 

&#10003; Ensure you have finished all your xref:trainingModules/introduction_trainings.adoc[TA trainings]

&#10003; Please prepare the xref:trainingModules/ta_training_module5_11_survey.adoc[Team Introduction Survey] in Qualtrics by following the linked instructions. You will have to customize this survey and set a deadline for the survey before Friday, September 4th at 11:59pm.

&#10003; Ensure you have access to your Project Charter before the first day of class. Please reach out to your liaison or mentor if you haven't received it yet.

&#10003; Schedule a meeting with your mentor to talk about the best AI scale level for your project 

&#10003; Create a PowerPoint called "Introductions" in your team's MS Teams Channel. Students will create a PowerPoint slide containing their photo, major, graduation year, and their hobbies/interests. Direct them to add their slide to this presentation. Students will present these during week 2. 

&#10003; Add your presentation slide to the Introductions PowerPoint. Use the template: xref:attachment$CRP_Intro_Template.potx[Intro Slide]

&#10003; Before **Lab #1** Review the instructions for this activity at the xref:projectmanagement:agile-lego-activity.adoc[Agile Lego Activity] page

&#10003; Attend TA Orientation Session Part 1, all TA are required to attend. Time & date TBD. 

&#10003; Make sure all your students and yourself sign the NDAs and IP Agreements (as needed) by the end of sprint #0. Follow the instructions in the xref:TAs:nda_ip_agreements.adoc[TA NDA Process Guide].

&#10003; Use the https://the-examples-book.com/tools/[Starter Guides] as an additional resource to learn and upskill across various topics.  

== Sprint Schedule

=== Team Meeting #1 (50 minutes):

* Team Introductions
** Mentors, TAs, and Students should introduce themselves to the team
** _Cameras are required to be on for all online meetings_
*  Review Project charter
**  Company Overview
** Project Overview
* Before the end of the meeting, assign background readings and prepwork that students should prepare before the next lab
** This can include content from the charter or other materials you have found helpful in your preparation for the project


=== Lab Section #1 (1 hour and 50 Minutes):

TIP: Make use of the xref:attachment$TDM_CRP_FacilitationGuide_Sprint0+1.pptx[Sprint 0+1 Facilitation Guide] to help run your Team Meetings and Labs for the first three weeks of the semester.

* Begin lab with an **Ice Breaker** to get to know your students better. Please refer to the TA MS Teams chanel for more ideas
* **NDAs & IP Agreements** (as needed)
** Some team will be required to sign NDAs and IP agreements before they can start working on their project
** Follow the instructions in the xref:TAs:nda_ip_agreements.adoc[TA NDA Process Guide].
** A Data Mine staff member or PTA will be at your lab to help facilitate the signing of NDAs and IP agreements
* **Agile Lego Activity**
** Review the instructions for this activity at the xref:projectmanagement:agile-lego-activity.adoc[Agile Lego Activity] page
** Please use the stock cards to create name tags for all in attendance (students and TAs)
** A Data Mine staff member or PTA will be at your lab to help facilitate this activity
* **Team Introduction Survey** 
** Please provide students with the link to your Qualtrics survey. You can have students do it in class or on their own, but it should be complete by Friday, September 5th at 11:59pm. Please refer xref:trainingModules/ta_training_module5_11_survey.adoc[Here] for more information about how to prepare the survey. 
** You will have to prepare this survey in Qualtrics. We encourage you to customize the questions to fit what you want to know about your team and what will be important to your project. 
** *ACTION ITEM*: There is a section under the skills category where need to customize the contents to align with topics that are significant to understand for your project. For example, if your project will involve building models, have students rank their knowledge on things like regressions, cluster analysis, decision trees, etc.