= Sprint #3

// == Intro Video

// ++++
// <iframe width="560" height="315" src="https://www.youtube.com/embed/Dt9_gUERJ1g?si=XywJb6O3Oai2wP2y" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
// ++++

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 2/13
|Mon 2/10

|*Sprint End Date*
|Wed 2/26
|Sun 2/23

|*Due Date*
2+| Wed 2/26 by 11:59 PM ET

|===

== To Do 

&#10003; Complete Time Sheet

* Timesheet #5 due Sunday 2/16 at 11:59 PM ET.

* Timesheet #6 due Sunday 2/23 at 11:59 PM ET.

&#10003; Grade Sprint #2: Professional Development by Wednesday 2/12 at 11:59PM EST.

&#10003; Grade Sprint #2: Report by Wednesday 2/19 at 11:59PM EST.

&#10003; Attend Monthly Meeting #2 on 2/26. 

&#10003; Review https://www.youtube.com/watch?v=YLBDkz0TwLM&t=69s[Radical Candor In 6 Minutes With Kim Scott] (6:30 minutes)

&#10003; Completed first required semester check-in with students during lab. Review https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module4_9_check_ins[Check-In Guide] for more information.

&#10003; Sprint Tasks for students: xref:students:spring2025/sprint3.adoc[Sprint 3 Tasks]

&#10003; See the xref:spring2025/schedule.adoc[Spring Schedule] for timesheet, grading, and report deadlines.

== Sprint Schedule

=== Team Meeting #1 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
** Questions related to the company. (Internship, Full-Time Opportunities, and etc.)
* Ensure students are assigned tasks to work on before meeting again in the next lab.


=== Lab Section #1 (1 hour and 50 Minutes):

* Start the meeting by taking attendance and having a weekly standup with your team.
** What did you work on last week?
** What are you currently working on?
** What are your blockers?
* Complete semester check-in with students. Review https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module4_9_check_ins[Check-In Guide] for more information.
* Assign sprint tasks and deadlines to team members on the Kanban board in MS Teams.
* A Data Mine staff member will stop by the lab sometime to provide support and answer any questions.

=== Team Meeting #2 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
** Questions related to the company. (Internship, Full-Time Opportunities, and etc.)
* Ensure students are assigned tasks to work on before meeting again in the next lab.
** Record tasks and deadlines on the Kanban board in MS Teams.

=== Lab Section #2 (1 hour and 50 Minutes):

* Start the meeting by taking attendance and having a daily standup with your team.

* Discuss with your team what they learned about Conflict Resolution from PD #3 and how those concepts can be applied to your team. Update the Conflict Resolution section in the Team Contract to reflect these lessons. 

* Assign sprint tasks and deadlines to team members on the Kanban board in MS Teams.
* Collaboration and work-time with team members.
* A Data Mine staff member will stop by the lab sometime to provide support and answer any questions.
