= Sprint #1

// Sprint-specific
:sprint: 8
// :previous-sprint:
:start-date: Jan 12
:end-date: Jan 23, 2026

// Tasks with due dates
:timesheet1-due: #1: Sun, Jan 18, 2026 @ 11:59 PM ET
:timesheet2-due: #2: Sun, Jan 25, 2026 @ 11:59 PM ET

// all TAs
:ferpa-syllabus-due: Sun, Jan 11, 2026 @ 11:59 PM ET

// new TAs only
:quiz-1-due: Wed, Jan14 @ 11:59 PM ET
:quiz-2-due: Wed, Jan14 @ 11:59 PM ET
:quiz-3-due: Wed, Jan14 @ 11:59 PM ET
:quiz-4-due: Wed, Jan14 @ 11:59 PM ET
:quiz-5-due: Wed, Jan14 @ 11:59 PM ET
:quiz-6-due: Wed, Jan14 @ 11:59 PM ET
:salesforce-training-due: Wed, Jan14 @ 11:59 PM ET
:wl-new-ta-orientation: Wed, Jan 14 @ TBD
:wl-tm-meeting: TBD

// Internal Resources
:gradescope-link: link:https://www.gradescope.com/[Gradescope,window=_blank]
:timesheet-link: link:https://hcm-us10.hr.cloud.sap/sf/timesheet[Success Factors,window=_blank]
:warm-ups-link: xref:TAs:trainingModules/ta_training_module4_3_warmups.adoc[Warm-ups,window=_blank]

== Sprint Timeline

[cols="2,3,3,2", options="header"]
|===
| Sprint Duration | Task | Due Date | Where

.8+| {start-date} - {end-date}

| <<complete-time-sheet, ✓ Complete Time Sheet>>
| **{timesheet1-due}** + 
**{timesheet2-due}**
| {timesheet-link}

| **ALL TAs**: <<ferpa-and-syllabus,✓ FERPA and Syllabus quiz>>
| **{ferpa-syllabus-due}**
| {gradescope-link}

| **ALL TAs**: <<team-prep,✓ Team Preparation>>
| **{ferpa-syllabus-due}**
| {gradescope-link}

| **NEW TAs ONLY**: <<new-tas-modules,✓ Complete Onboarding Tasks>>
| **{indy-tm-meeting2}**
| In-Person; Room ET219

| **NEW TAs ONLY **: <<new-ta-orientation,✓ Attend New TA Orientation>>
| **{indy-tm-meeting2}**
| In-Person; Room ET219

| **WL TAs**: ✓ Attend Monthly Meeting #1
| **{wl-tm-meeting}**
| Room TBD

| **MLK DAY**: ✓ 
| **{wl-tm-meeting}**
| Room TBD
|===

_Clicking a task name will take you to its detailed description in Sprint Details._ 


== Sprint Schedule (Returning Teams)

[cols="2,2,3,2", options="header"]
|===
| Session | Duration | Focus | Where

| **Team Meeting #1**
| 50 min 
| Attendance, Team Introductions, Project Overview, Task Assignment, Q&A 
.4+| In-Person / MS Teams

| **Lab Session #1**
| 1h 50m 
| Attendance, Icebreaker, Sprint 2026 Team Expectations + Contract, Reminders, Project Charter 

| **Team Meeting #2**
| 50 min 
| Attendance, Project Updates,  Q&A

| **Lab Session #2**
| 1h 50m 
| Attendance, Icebreaker, Reminders, Stand-ups, Retrospective, Project Work
|===

_**Note:** Icebreakers, Reminders, and the Team Activity section may vary each sprint._

---

=== Lab Sessions

- **Icebreakers** : {warm-ups-link}
- **Reminders**: //{student-content-tasks-link}







== Sprint Details

[[complete-time-sheet]]
=== ✓ Complete Time Sheet 

Timesheet {timesheet1-due} and {timesheet2-due}. Please submit through Success Factors or via Excel if you are in the credit-based TA role.

---

[[ferpa-and-syllabus]]
=== ✓ Complete FERPA Certification and Syllabus Quiz (All TAs) 

asdf

---

[[team-prep]]
=== ✓ Complete Tasks to Prepare for the Semester (All TAs)

&#10003; Complete Training and submit your FERPA.
* Submit https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module2#ferpa[FERPA] due Wednesday 1/15 at 11:59 PM ET.

&#10003; Review your team roster via Microsoft Teams by Wednesday 1/15 at 11:59 PM ET.

&#10003; Set up xref:trainingModules/ta_training_module5_3_dashboard_guide.adoc[Kanban Board in MS Teams] by Wednesday 1/15 at 11:59 PM ET.

&#10003; Before **Lab #1** prepare to facilitate a conversation about your Team Contract following the instructions linked xref:TAs:team_contract.adoc[here]. 

---

[[new-tas-modules]]
=== ✓ Complete Onboarding Tasks (New TAs Only)

asdf

---

[[new-ta-orientation]]
=== ✓ Attend TA Orientation (New TAs Only)

asdf

---














== Sprint Schedule (Returning Teams)

=== Team Meeting #1 (50 minutes):

* Team Introductions
** If your team has new mentors, TAs, or students spend some time during the first team meeting for team introductions and icebreakers.
** _Cameras are required to be on for all online meetings_
*  Review updated project charter
** Project Overview
** Project Timeline & Sprint objectives
* Weekly Deliverables
** If your team has weekly deliverables, review the deliverables for this sprint
* Task Assignment
** Before the end of the meeting, assign background readings and prep work that students should prepare before the next lab.
*** This can include content from the charter or other materials you have found helpful in your preparation for the project
** Record tasks and deadlines on the Kanban board in MS Teams.

=== Lab Section #1 (1 hour and 50 Minutes):

* Begin lab by facilitating a discussion on Spring 2025 Team expectations.
** Use this PowerPoint to facilitate the discussion: xref:attachment$Spring 2025 Team expectation.pptx[Spring 2025 Team expectations]
* Review the Spring 2025 Project Charter with your team.
* Team Contract- Collaborate with your team to review and update your Team Contract by following the provided outline xref:TAs:team_contract.adoc[here]. 
** This contract will establish your team's expectations for the year. Facilitate this process as an open discussion, encouraging all members to provide input.
** Whatever isn't finished in this Lab, must be complete in the next Lab. Students will have to reflect on this for professional development 1. 
* Assign sprint tasks and deadlines to team members on the Kanban board in MS Teams.
* A Data Mine staff member will stop by the lab sometime to provide support and answer any questions.


=== Team Meeting #2 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
** Questions related to the company. (Internship, Full-Time Opportunities, and etc.)
* Ensure students are assigned tasks to work on before meeting again in the next lab.
** Record tasks and deadlines on the Kanban board in MS Teams.

=== Lab Section #2 (1 hour and 50 Minutes):

* Start the meeting by taking attendance and having a daily standup with your team.
* Assign sprint tasks and deadlines to team members on the Kanban board in MS Teams.
* Collaboration and work-time with team members.
* A Data Mine staff member will stop by the lab sometime to provide support and answer any questions.


== Sprint Schedule (New Teams)

=== Team Meeting #1 (50 minutes):

* Team Introductions
** Mentors, TAs, and Students should introduce themselves to the team
** _Cameras are required to be on for all online meetings_
*  Review Project charter
**  Company Overview
** Project Overview
* Before the end of the meeting, assign background readings and prep work that students should prepare before the next lab
** This can include content from the charter or other materials you have found helpful in your preparation for the project


=== Lab Section #1 (1 hour and 50 Minutes):

* NDAs & IP Agreements (as needed)
** Some teams will be required to sign NDAs and IP agreements before they can start working on their project.
** The Data Mine will facilitate the signing of NDAs and IP agreements through DocuSign. Please check your email and carefully review the agreement. 
* Agile Lego Activity
** Review the instructions for this activity at the xref:projectmanagement:agile-lego-activity.adoc[Agile Lego Activity] page
** A Data Mine staff member will be at your lab to help facilitate this activity
* Team Contract- Collaborate with your team to create your Team Contract by following the provided outline xref:TAs:team_contract.adoc[here]. 
** This contract will establish your team's expectations for the year. Facilitate this process as an open discussion, encouraging all members to provide input.
** Whatever isn't finished in this Lab, must be complete in the next Lab. Students will have to reflect on this for professional development 1.  


=== Team Meeting #2 (50 minutes):

* Deep dive into the project
** Mentors should review their project charter in more detail. This review should include:
*** Roles and Responsibilities
*** Timeline
*** Objectives
*** Data
*** Deliverables
*** Tools
*** Resources
** Remember to leave time for questions from the student team
* Before the end of the meeting, assign background readings and prep work that students should prepare before the next lab
** This can include content from the charter or other materials you have found helpful in your preparation for the project
** Please also consider start guides that are relevant to your project


=== Lab Section #2 (1 hour and 50 Minutes):

* Begin lab by facilitating a discussion on Spring 2025 Team expectations.
** Use this PowerPoint to facilitate the discussion: xref:attachment$Spring 2025 Team expectation.pptx[Spring 2025 Team expectations]
* Next, facilitate the xref:trainingModules/ta_training_module5_11_survey.adoc[Student Background Experience Assessment]
** *ACTION ITEM*: you will have to prepare this survey in Qualtrics before the lab
** Use the data from this survey to align your team with the appropriate roles and responsibilities denoted by your project charter
* Review the project charter with your team.
* Assign sprint tasks and deadlines to team members on the Kanban board in MS Teams.
 
== The Data Mine Video
Check out this video showcasing previous and current TAs!

++++
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/2hYY20OGjpg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
