= Sprint #2

// == Intro Video

// ++++
// <iframe width="560" height="315" src="https://www.youtube.com/embed/ia6H9c0Ap2I?si=xUbeNZejSRKFtHFu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
// ++++

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 1/30
|Mon 1/27

|*Sprint End Date*
|Wed 2/12
|Sun 2/9

|*Due Date*
2+| Wed 2/12 by 11:59 PM ET

|===


== To Do

&#10003; Complete Time Sheet

* Timesheet #3 due Sunday 2/2 at 11:59 PM ET.

* Timesheet #4 due Sunday 2/9 at 11:59 PM ET.

&#10003; Grade Sprint #1: Professional Development by Wednesday 2/5 at 11:59PM EST.

&#10003; Grade Sprint #1: Report by Wednesday 2/5 at 11:59PM EST.

&#10003; Submit Team Report #1 on Gradescope by Wednesday 2/5 at 11:59PM EST.

&#10003; Review the https://the-examples-book.com/crp/students/spring2025/sprint2[Student Spring #2 page] and be familiar with the tasks students are assigned during this sprint.

&#10003; Review your team's Github roster. Add any new team members and remove former team members.

&#10003; Review https://www.youtube.com/watch?v=NPVTLroz2Ck&t=21s[How to Run a Virtual Meeting (BEST PRACTICES)] (5 Minutes)

&#10003; If your team completed the https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module5_11_survey[Student Background Experience Assessment], consider sharing the results with your mentors.

&#10003; Before **Lab #2** please review students feedback about the Team Contract from Professional Development Assignment #1. 

== Sprint Schedule

=== Team Meeting #1 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
** Questions related to the company. (Internship, Full-Time Opportunities, and etc.)
* Ensure students are assigned tasks to work on before meeting again in the next lab.
** Record tasks and deadlines on the Kanban board in MS Teams.

=== Lab Section #1 (1 hour and 50 Minutes):

* Start the meeting by taking attendance and having a weekly standup with your team.
** What did you work on last week?
** What are you currently working on?
** What are your blockers?
* Facilitate a discussion on virtual meeting etiquette. Here are some discussion questions to help guide the conversation:
** What makes a good virtual meeting?
** what are some things to avoid in a virtual meeting?
** What is something you can do to improve your virtual meetings?
*** ex: turning on your camera, muting yourself when you are not speaking, etc.
* Assign sprint tasks and deadlines to team members on the Kanban board in MS Teams.
* A Data Mine staff member will stop by the lab sometime to provide support and answer any questions.

=== Team Meeting #2 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
** Questions related to the company. (Internship, Full-Time Opportunities, and etc.)
* Ensure students are assigned tasks to work on before meeting again in the next lab.
** Record tasks and deadlines on the Kanban board in MS Teams.

=== Lab Section #2 (1 hour and 50 Minutes):

* Start the meeting by taking attendance and having a daily standup with your team.

* As a team, discuss updates that need to be made to the Team Contact and update them accordingly. This conversation should be based on students feedback from PD #1.

** TA's will submit updated Team Contracts in TA Report #2 on Gradescope. 

* Assign sprint tasks and deadlines to team members on the Kanban board in MS Teams.
* Collaboration and work-time with team members.
* A Data Mine staff member will stop by the lab sometime to provide support and answer any questions.

