= TDM Poster Printing

Wide format printing is available at the second floor of the Wilmeth Active Learning Center (WALC) and at the Hicks Undergraduate Library (HSSE). The Data Mine will be charged for use, so these instructions are not for personal use.

IMPORTANT: When printing, please remember that posters for the Data Mine Symposium should be 2 x 3 feet.

A single-page pdf version of these instructions (with pictures) is xref:attachment$Data Mine Wide Format Printing Instructions 2026.pdf[available here], but written out below.

. Log on to Purdue IT Windows PC using your own Career Account credentials.
. In the Windows Search bar, enter: `\\printers.itap.purdue.edu`
. Double click on either **puit-walcwideprinting** or **puit-hssewideprinting**
. Wait for the pop-up box to appear, then close it. *The printer should now be added to your list of printers.*
. Open your poster in **Adobe Acrobat**. *Please do not print from a browser or PowerPoint.* Ensure everything looks correct, then select Print.
. In the print dialogue box, select the wide format printer from the dropdown menu. Click on "Properties" at the top of the dialogue box.
. Click on the "Paper/Quality" tab, and select "Custom". In the "Custom size" pop-up box, enter the poster size **(width = 36 inches, height = 24 inches)** and enter a name (ex: `TDM Poster Size`) and click "Save".
. Click "OK" to proceed.
. Click on the "Layout/Output" tab. In the "Fit to:" option, select the document size you just created and saved from the dropdown menu.
. Click "OK" to proceed.
. Do a final review, then click "Print" to print the poster.
. Visit the **Service Desk** and let staff know that you are printing using the **Shared Account 'Data Mine' in PaperCut**. The staff will then charge the print job to The Data Mine account.
. The service desk staff will have you review the preview of the print job, and then they will send the print job to the printer.