= Sprint #5

// == Intro Video

// ++++
// <iframe width="560" height="315" src="https://www.youtube.com/embed/13g7l3zQPq4?si=dnseCld3iCECTpJk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
// ++++

== Sprint Dates

*_Monday, March 11 to Saturday March 16:  Spring Break (no Corporate Partner meetings/classes)_*

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 3/7
|Mon 3/4

|*Sprint End Date*
|Wed 3/27
|Sun 3/24

|*Due Date*
2+| Wed 3/27 by 11:59 PM ET

|===

== To Do
&#10003; Submit your symposium draft video on behalf of your team to gradescope. 

&#10003; Set-up a meeting with CRP mentor to complete mid-semester student feedback.

&#10003; Attend Monthly Meeting 3 on 3/20.

&#10003; See the xref:spring2024/schedule.adoc[Spring Schedule] for timesheet, grading, and report deadlines.

&#10003; Completed second required semester check-in with students!

== Sprint Schedule

[IMPORTANT]
====
*CONTENT STILL UNDER CONSTRUCTION FOR SPRING 2024.*
====

=== Team Meeting #1 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.

* Ensure students are assigned tasks to work on before meeting again in the next lab.


=== Lab Section #1 (1 hour and 50 Minutes):
* Begin lab by completing the activity in the facilitation guide and then complete a sprint retrospective of sprint #4. Followed by a daily stand-up and sprint planning for sprint #5.
// ** Use this PowerPoint to facilitate the discussion: xref:attachment$Initiative_Follow_Through.pptx[Initiative & Follow Through Powerpoint]
* Use the remainder of the time to work on your project.
* Prepare for your symposium final video and poster due at the end of this sprint.


=== Team Meeting #2 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles,roadblocks or barriers that they experienced while completing this weeks task?
** What do they plan on committing to completing by next mentor meeting?
* Time for questions from students to mentor.

* Ensure students are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #2 (1 hour and 50 Minutes):

* Begin lab by completing the activity in the facilitation guide
// ** Use this PowerPoint to facilitate the discussion: xref:attachment$WorstPresentationEverStandAlone.ppt[World Worst Presentation Ever]

** *ACTION ITEM*: Carefully review the  PowerPoint before lab. This will aid in your preparedness to facilitate a productive and thoughtful discussion. Reflect on the questions and be ready to participate in the student group discussion if students are slow to warm up. 
* Use the remainder of the time to work on your project.
* Prepare for your symposium final video and poster due at the end of this sprint.

* Sprint Tasks for students: xref:students:spring2024/sprint5.adoc[Sprint 5 Tasks]
