= Sprint #1

// == Intro Video
// ++++
// <iframe width="560" height="315" src="https://www.youtube.com/embed/c5Dp0u2iu9s" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
// ++++

== Sprint Dates
_All sprints will have the same due dates_, but the sprint start and end dates are slightly shifted depending on when a team has their lab (2 hours) and lecture (50 minutes). This is so that sprints always start with a lec and follow the format lec-lab-lec-lab.

You can find a xref:agile:ceremonies.adoc#sprint-schedule[visual of the sprint schedule in the Agile Training Ceremonies page]. More details will be covered in the agile training below. 

*_Monday, 1/15:  Martin Luther King Jr. Day (no Corporate Partner meetings/classes)_*

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|*Mon 1/8 
|Mon 1/8

|*Sprint End Date*
|Wed 1/24
|Sun 1/21

|*Due Date*
2+| Wed 1/24 by 11:59 PM ET

|===

_*Please note that sprint 1 starts on January 8, the first day of spring 2024 semester, for both schedules. Once we are in a regular sprint schedule, you will see the lab then meeting schedule shift to starting on Thursdays._

== To Do

&#10003; Complete Training and submit your FERPA.
* Submit FERPA due Wednesday 1/10 at 11:59 PM ET.

&#10003; Review your team rooster via Microsoft Teams by Wednesday 1/10 at 11:59 PM ET..

&#10003; Set up xref:trainingModules/ta_training_module5_3_dashboard_guide.adoc[Kanban Board in MS Teams] by Wednesday 1/10 at 11:59 PM ET.

&#10003; New TAs to attend TA Orientation on 1/10.

&#10003; Submit Initial Team Report due Wednesday 1/17 at 11:59 PM ET.

&#10003; All TAs to attend Monthly Meeting #1 on 1/17.

&#10003; Complete Time Sheet

* Timesheet #1 due Sunday 1/14 at 11:59 PM ET.

* Timesheet #2 due Sunday 1/21 at 11:59 PM ET.

== Sprint Schedule

=== Returning Teams
[IMPORTANT]
====
*CONTENT STILL UNDER CONSTRUCTION FOR SPRING 2024.*
====
==== Team Meeting #1 (50 minutes):

* Team Introductions
** If your team has new mentors, TAs, or students spend some time during the first team meeting for team introductions and icebreakers.
** _Cameras are required to be on for all online meetings_
*  Review updated project charter
** Project Overview
** Project Timeline & Sprint objectives
* Weekly Deliverables
** If your team has weekly deliverables, review the deliverables for this sprint
* Task Assignment
** Before the end of the meeting, assign background readings and prepwork that students should prepare before the next lab.
*** This can include content from the charter or other materials you have found helpful in your preparation for the project
** Record task and deadline on Kanban board in MS Teams.

==== Lab Section #1 (1 hour and 50 Minutes):

* Review the Project Charter with your team.

==== Team Meeting #2 (50 minutes):




==== Lab Section #2 (1 hour and 50 Minutes):




=== New Teams

==== Team Meeting #1 (50 minutes):

* Team Introductions
** Mentors, TAs, and Students should introduce themselves to the team
** _Cameras are required to be on for all online meetings_
*  Review Project charter
**  Company Overview
** Project Overview
* Before the end of the meeting, assign background readings and prepwork that students should prepare before the next lab
** This can include content from the charter or other materials you have found helpful in your preparation for the project


==== Lab Section #1 (1 hour and 50 Minutes):

* NDAs & IP Agreements (as needed)
** Some team will be required to sign NDAs and IP agreements before they can start working on their project
** A Data Mine staff member will be at your lab to help facilitate the signing of NDAs and IP agreements
* Agile Lego Activity
** Review the instructions for this activity at the xref:agile:agile-lego-activity.adoc[Agile Lego Activity] page
** Please use the stock cards to create name tags for all in attendance (students and TAs)
** A Data Mine staff member will be at your lab to help facilitate this activity

==== Team Meeting #2 (50 minutes):

* Deep dive into the project
** Mentors should review their project charter in more detail. This review should include:
*** Roles and Responsibilities
*** Timeline
*** Objectives
*** Data
*** Deliverables
*** Tools
*** Resources
** Remember to leave time for questions from the student team
* Before the end of the meeting, assign background readings and prepwork that students should prepare before the next lab
** This can include content from the charter or other materials you have found helpful in your preparation for the project
** Please also consider start guides that are relevant to your project


==== Lab Section #2 (1 hour and 50 Minutes):

* Begin lab with this sprint's professional development topic of Organizational Behavior
** Use this powerpoint to facilitate the discussion: xref:attachment$Organizational_Behavior.pptx[Organizational Behavior Facilitator Guide]
* Next, facilitate the xref:trainingModules/ta_training_module5_6_survey.adoc[Student Background Experience Assessment]
** *ACTION ITEM*: you will have to prepare this survey in Qualtrics before the lab
** Use the data from this survey to align your team with the appropriate roles and responsibilities denoted by your project charter
* Lastly, use the remainder of the time to review relative, supplementary content for your project including:
** xref:starter-guides:ROOT:introduction.adoc[Starter Guides]
** Background Readings
** Sprint Tasks for students: xref:students:spring2024/sprint1.adoc[Sprint 1 Tasks]

== The Data Mine Video
Check out this video showcasing previous and current TAs!

++++
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/2hYY20OGjpg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++