= Sprint #3

// == Intro Video

// ++++
// <iframe width="560" height="315" src="https://www.youtube.com/embed/Dt9_gUERJ1g?si=XywJb6O3Oai2wP2y" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
// ++++

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 2/8
|Mon 2/5

|*Sprint End Date*
|Wed 2/21
|Sun 2/18

|*Due Date*
2+| Wed 2/21 by 11:59 PM ET

|===

== To Do 

&#10003; Attend Monthly Meeting #2 on 2/21.

&#10003; Completed first required semester check-in with students during lab.

&#10003; See the xref:spring2024/schedule.adoc[Spring Schedule] for timesheet, grading, and report deadlines.

== Sprint Schedule

[IMPORTANT]
====
*CONTENT STILL UNDER CONSTRUCTION FOR SPRING 2024.*
====

=== Team Meeting #1 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
** Questions related to the company. (Internship, Full-Time Opportunities, and etc.)
* Ensure students are assigned tasks to work on before meeting again in the next lab.


=== Lab Section #1 (1 hour and 50 Minutes):

* Begin lab by facilitating a discussion on the professional development topic of effective verbal/signed communication. Followed by a daily stand-up and sprint planning for sprint #3.
// ** Use this PowerPoint to facilitate the discussion: xref:attachment$VerbalSigned Communcation.pptx[Effective Verbal/Sign Communication]
** *ACTION ITEM*: Carefully review the  PowerPoint before lab. This will aid in your preparedness to facilitate a productive and thoughtful discussion. Reflect on the questions and be ready to participate in the student group discussion if students are slow to warm up. 
* Use the remainder of the time to work on your project.

=== Team Meeting #2 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles,roadblocks or barriers that they experienced while completing this weeks task?
** What do they plan on committing to completing by next mentor meeting?
* Time for questions from students to mentor.

* Ensure students are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #2 (1 hour and 50 Minutes):

* Begin lab by facilitating a discussion on the professional development topic of listening skills.
// ** Use this PowerPoint to facilitate the discussion: xref:attachment$Listening Skills.pptx[Listening Skills]
// ** *ACTION ITEM*: Carefully review the  PowerPoint before lab and take the link:https://www.mindtools.com/ai4ff5e/how-good-are-your-listening-skills[listening quiz] yourself. This will aid in your preparedness to facilitate a productive and thoughtful discussion. Reflect on the questions and be ready to participate in the student group discussion if students are slow to warm up. 
* Use the remainder of the time to work on your project.

* Sprint Tasks for students: xref:students:spring2024/sprint3.adoc[Sprint 3 Tasks]
