= How to Prepare Your Team 

How do I prepare my team for the Symposium?

There are a couple questions you need to answer before you can properly prepare your team for the presentation.

1. Who is coming to the Symposium? Is it appropriate to show all of the work we have completed or is some of it confidential? (please discuss this with your mentor)
2. What are my expectations for student participation? Do all students need to speak? All students must have some role in the Symposium.

After you answer these questions, you can start preparing your team. You will need to determine:

* Content
* Video Recording
* Poster Preparation
    ** Tips and Common Feedback
* Speaking Roles
* Timeline

=== Content
Throughout the semester you should be taking meeting and lab notes. 
These will be very helpful for putting together your final presentation. 
In addition to meeting minutes, your team could use any professional presentation content from 
Sprint Reviews to identify important content. 

=== Poster Preparation
After your team determines the relevant content for the presentation, you will need to put it in a shareable format. 
Be creative and keep things simple.

==== Tips and Common Feedback
* *Have an elevator pitch for guests walking around.* Practice this in lab with your team.
* Make sure you meet the minimum requirements for content 
* Have *minimal words on the poster*. Use powerful visuals instead and verbally share accomplishments.
* As one of the last steps, make sure the poster is uniform (same fonts and sizes, colors, styles).

View past presentations (from Spring Symposium) on link:https://datamine.purdue.edu/symposium/welcome.html#projects[The Data Mine Website] to get ideas.

=== Speaking Roles
Now that you have a presentation, you should communicate it to your audience. 
One of the best ways to do this is to identify the number of sections and then assign speakers based on comfortability. 
It is recommended to have a back-up speaker for each section. 

The most important part of assigning speaking roles for the Symposium is making sure everyone has access to it.  
