= Anvil
:page-aliases: introduction.adoc

https://www.rcac.purdue.edu/compute/anvil[Anvil] is a great new supercomputer that was funded by the National Science Foundation. Anvil helps to expand the resources available for the NSF's https://portal.xsede.org/#/guest[Extreme Science and Engineering Discovery Environment (XSEDE)], which was ended as a funded project on August 31st, 2022. The success of XSEDE led the NSF to follow up with xref:https://access-ci.org/[ACCESS], which is now what provides us access to Anvil.

Similar to Scholar and Brown, the Anvil cluster allows The Data Mine to run our R and Python environments on world-class research computing resources. These resources give teams access to computing power and assets like GPUs. 

{sp}+

== First Time Setup

If you're logging into Anvil for the first time you'll need to create an ACCESS account and send that information to The Data Mine staff. Please follow the instructions on the https://the-examples-book.com/setup[ACCESS setup page].

If you have any issues please contact The Data Mine at datamine-help@purdue.edu. 
