== Spring Preparation

&#10003; Review content from Fall. Identify goals for the semester. Identify areas to improve for the Spring semester. 

&#10003; Met with my Corporate Mentor to discuss project expectations and communication methods. 

&#10003; (Optional, but recommended) Met with my Mentor for more planning or reviewing information

&#10003; (Optional) Met with Data Mine Staff to discuss any concerns or get my questions answered.

&#10003; Sent out a welcome back email to the team including the following: 

    * Reminding them about project meeting times
    * Reminding them about link:https://the-examples-book.com/book/introduction[The Examples Book]
    * Providing them with the best way to reach you for the semester
    * Include any updated office hours

&#10003; Prepared an icebreaker for the first lab back.

&#10003; Checked the TA schedule to identify due dates for the semester.

New TAs please refer to xref:fall2022/pre_fall_prep.adoc[Fall 2022 Pre-Fall Preparation] for additional steps.