= Sprint #1

== Sprint Dates
All sprints will have the same due dates, but the sprint start and end dates are slightly shifted depending on when a team has their lab (2 hours) and lecture (50 minutes). This is so that sprints always start with a lec and follow the format lec-lab-lec-lab.

You can find the sprint dates listed on the xref:spring2023/schedule.adoc[Spring 2023 TA Schedule]

_Monday, 1/16:  Martin Luther King Junior Day (no Corporate Partner meetings/classes)_

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|*Mon 1/9 
|Mon 1/9

|*Sprint End Date*
|Wed 1/25
|Sun 1/22

|*Student Report Due Date*
2+| Wed 1/25 by 11:59 PM ET

|===

_*Please note that sprint 1 starts on January 9, the first day of spring 2023 semester, for both schedules. Once we are in a regular sprint schedule, you will see the lab then meeting schedule shift to starting on Thursdays._

== To Do

&#10003; Prepared an icebreaker for the first lab. xref:trainingModules/ta_training_module3_4_warmups.adoc[TA Created Warm-Ups].

&#10003; Planned my first lab back from break! This can be reviewing and planning for the upcoming semester. 

&#10003; See the xref:spring2023/schedule.adoc[Spring Schedule] for timesheet and report deadlines.

== The Data Mine Video
Check out the new Data Mine Video and share it with your friends!

++++
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/2hYY20OGjpg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++
