= 1. SSH

`ssh` is a powerful tool that allows you to create a connection to a server, over a network, and exchange data. 

By default, `ssh` will provide you with a shell (for example, `bash`, `zsh`, or `fish`) running on the server.

[source,bash]
----
ssh username@anvil.rcac.purdue.edu
----

The part _before_ the "@" is your username for the _server_. The part _after_ the "@" is the _host_. The result will be the default shell of given user, on the _host_.

You can also run specific commands on the _host_ without launching an entire shell. **Run this command in the terminal in your LOCAL computer. You will need to fill in the USERNAME part with your Anvil username!**

[source,bash]
----
ssh username@anvil.rcac.purdue.edu whoami
----

This would run the `whoami` command on the _host_, `anvil.rcac.purdue.edu`, and output the value in the current shell on your _local_ machine.

== 2. Authentication

When using `ssh` to login to the _host_ system, you will be asked to enter a password. This is the password of the user, `username`, on the _host_ machine. You will be required to enter this for every `ssh` connection. 

On Anvil, it is not so simple, as there is a special gateway system that you would first need to `ssh` into, _before_ `ssh`ing into the actual Anvil system. To bypass this, you can use an alternative authentication system called public key cryptography.

Public key cryptography allows the user to bypass typing a password by exchanging a set of files. `ssh` can use these files in order to verify that you are indeed connecting from an authorized system.

To setup `ssh` keys, do the following.

. On your _local_ machine _or_ your _host_ machine, generate your key pair:

[source,bash]
----
# mac or linux
cd .ssh
ssh-keygen -a 100 -t ed25519 -f ~/.ssh/id_ed25519 

# windows
cd .ssh
ssh-keygen -t ed25519
----

. You will be prompted to enter a password. If you choose to _not_ enter a password, your resulting _private_ key will end up being the equivalent of a password. Any bad actor who gets ahold of your key will be able to enter any authorized system under your username. If you _do_ enter a password, you will be asked to enter this password every time you `ssh` into another system with a matching _public_ key in the `~/.ssh/authorized_keys` file.

. This will create two files in your `$HOME` directory: `~/.ssh/id_ed25519` and `~/.ssh/id_ed25519.pub`. Or, if you are in a Windows system: `C:\Users\username\.ssh\id_ed25519` and `C:\Users\username\.ssh\id_ed25519.pub`. The first key, `~/.ssh/id_ed25519`, is your _private_ key. The other file, `~/.ssh/id_ed25519.pub` is your _public_ key.

. The next task is to share your _public_ key with any other system you'd like to be able to `ssh` into. For example, Anvil. To share a public key, you can manually copy the contents of your _public_ key and _append_ the contents to the `~/.ssh/authorized_keys` file on the desired _host_ (in our example, Anvil).



Navigate and login to https://ondemand.anvil.rcac.purdue.edu. Click on *Clusters > Anvil Shell Access* in the top menu. 



Once presented with a shell, run the following to create the `.ssh` folder if it doesn't already exist:

[source,bash]
----
mkdir -p ~/.ssh
----

Next, you will copy the contents of your _public_ key. You will type this command still in your _local_ computer, then select the output string and copy it into **Anvil's shell**:

[source,bash]
----
# mac or linux
cat ~/.ssh/id_ed25519.pub

# windows
type C:\Users\username\.ssh\id_ed25519.pub
----

Next, navigate back to your tab `https://ondemand.anvil.rcac.purdue.edure` and turn to the top menu and click on *Files > Home Directory*.

. In the file browser, click the gear icon in the top right and enable *Show Dotfiles*.
. Open the `.ssh` folder.
. If the `authorized_keys` file does not exist, click *New File* and name it `authorized_keys`.
. Open the `authorized_keys` file and paste the full contents of your public key (copied from `cat ~/.ssh/id_ed25519.pub`) on a new line.
. Save the file.

Then, go back to the Anvil shell terminal and set the required permissions:

[source,bash]
----
chmod 700 ~/.ssh
chmod 600 ~/.ssh/authorized_keys
----

Now, on your local machine, you should be able to run the following and immediately connect:

[source,bash]
----
ssh username@anvil.rcac.purdue.edu
----

That should do it! 




Here is some more information that might come in handy:

. One neat trick, when managing many hosts, is to maintain an `ssh` config file. This is useful if you have many hosts, with different usernames, key pairs, and addresses. Take the following, for example:

[source,sshconfig]
----
Host anvil 
    Hostname anvil.rcac.purdue.edu
    User username1
    IdentityFile ~/.ssh/id_ed25519

Host pizza
    Hostname pi.zza.445.333.example.com
    User georgie
    IdentityFile ~/.ssh/id_rsa
----

This config allows you to establish a connection using `ssh` very easily:

[source,bash]
----
ssh anvil

# or

ssh pizza
----

This replaces the alternative:

[source,bash]
----
ssh username1@anvil.rcac.purdue.edu
ssh -i ~/.ssh/id_rsa georgie@pi.zza.445.333.example.com
----
