= Welcome to The Data Mine Corporate Partners Spring 2026 semester!
:page-aliases: spring2026/introduction.adoc



All course content lives within The Corporate Partners appendix of The Example Book (the pages you are reading right now). 

However, we still have a link:https://purdue.brightspace.com/[Brightspace] page for the purposes of grading. All Purdue courses are required to post grades in Brightspace. Students will also use link:https://www.gradescope.com/[Gradescope] as the submission portal for assignments.  


To get started this semester:

1. Review the xref:spring2026/syllabus.adoc[spring 2025 syllabus].

2. Review the xref:spring2026/schedule.adoc[spring 2025 course schedule] for due dates and important dates.

3. Confirm your xref:spring2026/locations.adoc[meeting time and location]. This should match the time listed on your official Purdue schedule. The MS Teams meeting link for your SYNC ONLINE class will be sent a few days before January 13. If you do not have this meeting link, please email us at datamine-help@purdue.edu and specify what team you are on. 

4. Click on xref:spring2026/sprint1.adoc[Sprint #1] to review the content for the first two weeks.

We look forward to working with you this semester! 

== Experiencing The Data Mine Video
Check out the new video featuring students in The Data Mine!

++++
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/2hYY20OGjpg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++
