= The Data Mine Corporate Partners Symposium 

[IMPORTANT]
====
 *CONTENT STILL UNDER CONSTRUCTION FOR SPRING 2025!!!!*
====

The Data Mine Corporate Partners Symposium is held annually in April. Our student teams work hard through the year on research projects in industry.  The symposium is an opportunity to have the student teams to showcase their work by creating a poster and video on their respective projects.

* link:https://datamine.purdue.edu/symposium/2023.html[2022 - 2023 posters and videos]

* link:https://datamine.purdue.edu/symposium/welcome.html[2021 - 2022 posters and videos]

* link:https://datamine.purdue.edu/symposium/welcome2021.html[2020 - 2021 posters and videos]

* link:https://datamine.purdue.edu/symposium/welcome2020.html[2019 - 2020 posters and videos]

== Symposium Preparation Checklist
[NOTE]
====
This checklist applies to all students presenting at the symposium including students at Purdue and other participating universities. 
====

&#10003; *Poster draft* due March 6th, 2024, submitted as a PDF by your TA. Review xref:students:spring2024/poster_guidelines.adoc[Poster Guidelines] for a templates, examples, and the rubric.

&#10003; *3-Minute Thesis draft* due March 6th, 2024 as an .mp4 saved in your team's general channel in MS Teams. Review xref:students:spring2024/video_guidelines.adoc[Video Guidelines] for instructions, examples, and the rubric.

&#10003; *Final poster* version due April 3th, 2024, submitted as a PDF by your TA. Review xref:students:spring2024/poster_guidelines.adoc[Poster Guidelines] for a templates, examples, and the rubric.

&#10003; *Final 3-Minute Thesis Video* version due April 3th, 2024 and uploaded to The Data Mine youtube including closed captioning. Review xref:students:spring2024/video_guidelines.adoc[Video Guidelines] for instructions on closed captioning and uploading.

&#10003; *Team attendance* schedule set for day of symposium. Review xref:students:spring2024/symposium_day_of_guidelines.adoc[Day of Symposium Guidelines] for attendance expectations.

&#10003; *Poster printed* and ready to be brought on day of symposium. Review xref:students:spring2024/poster_guidelines.adoc[Poster Guidelines] for instructions on printing your poster.

&#10003; *The Data Mine Corporate Partners Networking Night*, April 23, 2024. Come and meet with Data Mine Corporate Partners the night before the symposium in a business casual environment! xref:students:spring2024/crp_networking_event.adoc[Click here] for more information.