= Sprint #13


== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 4/3
|Mon 3/31

|*Sprint End Date*
|Wed 4/16
|Sun 4/13


|===

== Sprint Tasks

=== &#10003; Final Presentation

To recap the semester, your team will present on project progress and future goals. Please review the following Guidelines for the Final Poster: xref:spring2025/poster_guidelines.adoc[Final Poster Details]. Please review the following Guidelines for the Final Video: xref:spring2025/video_guidelines.adoc[Final Video Details].

During this sprint, your team should complete a final draft of your poster and video and continuing working on documentation and product add-ons until the final week of term when you will present at The Data Mine Symposium.

*When:*  Final Draft due Wednesday, April 9, 2025 at 11:59 PM ET. Late work will not be accepted. 

*What:* Final Poster and Video - refer here for xref:spring2025/poster_guidelines.adoc[Final Poster Details] and xref:spring2025/video_guidelines.adoc[Final Video Details].

*Where:* Your TA will submit on behalf of the team. We only need 1 submission per team. 

=== &#10003; Professional Development 

The Data Mine Corporate Partners program is a professional development program. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

Each sprint you will complete a few professional development-related tasks. 

++++
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}

.accordion:after {
  content: '\002B';
  color: #777;
  font-weight: bold;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2212";
}

.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>
<button class="accordion">Symposium Pitch</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday,  April 10, 2024 at 11:59 PM ET. Late work will not be accepted.	
		</p>
<br>
	</div>
	<div>
		<p><b>What: </b>What is your symposium pitch? Upload a video on Gradescope for your TA to review and give feedback.<a href="https://the-examples-book.com/crp/students/symposium_pitch">Review Guidelines for Symposium Pitch</a></p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 6: Professional Development".</p>
<br>
  	</div>
	<div>
		<p><b>Why: </b>In preparation for The Data Mine symposium, we want students to prepare their symposium pitch for guests at the symposium. This assignment will allow you to practice your pitch and get feedback from your TA on areas of improvement.</p>
<br>
  </div>
</div>


<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

</body>
</html>
++++



=== &#10003; Sprint #6 Report 

*Released:* The assignment will open for submissions one week before the due date starting Thursday, April 10, 2025. 

*When:* Due Wednesday, April 16, 2025 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in Sprint #6 Report. 

*Where:* Submit the report on link:https://www.gradescope.com/[Gradescope] titled "Sprint 6: Report".

