= Sprint #11
// Sprint-specific 
:sprint-no: 11
:previous-sprint-no: 10
:start-date: Feb 23 
:end-date:  Mar 6, 2026
:spring-year: 2026
:fall-year: 2025

// Tasks with due dates 
:pd-due: Wed, Mar 4, 2026 @ 11:59 PM ET
:report-due: Wed, Mar 11, 2026 @ 11:59 PM ET

//sites
:gradescope-link: link:https://www.gradescope.com/[Gradescope,window=_blank]
:syllabus: xref:spring2026/syllabus.adoc[Syllabus, window=_blank]
:schedule: xref:spring2026/schedule.adoc[Course Schedule, window=_blank]
:poster: xref:spring2025/poster_guidelines.adoc[Final Poster Details, window=_blank]
:video: xref:spring2025/video_guidelines.adoc[Final Video Details, window=_blank]


== Sprint {sprint-no} Timeline
> Sprint Duration: **{start-date} - {end-date}**

[cols="3,4,2", options="header"]
|===
| Task | Due Date | Where

| ✓ <<professional-development, Professional Development>>
| **{pd-due}** 
.2+.^| {gradescope-link}

| ✓ <<sprint-report, Sprint #{sprint-no} Report>>
.2+.^| **{report-due}**

| ✓ <<symposium, Draft Symposium Materials>>
| _TA will submit on behalf of the team_

|===

== Sprint Task
'''
[[professional-development]]
=== &#10003; [.green]#Professional Development#
During sprint {sprint-no}, ...

**When:** Professional Development Due on Gradescope by {pd-due}. Late work will not be accepted. 

.**1. Emotional Inteligence**
[%collapsible%open]
====
*Why:* 

*What*: 

====

.**2. Peer Review**
[%collapsible%open]
====
*Why:* 

*What:* 
====


---
[[sprint-report]]
=== &#10003;Sprint #{sprint-no} Report
**Why**: The Sprint Report is part of your grade and helps you reflect on your past work. It also gives you the chance to step back, recognize your impact, and track your growth as a teammate and professional.  Each section is designed to help you think about your role, your progress, and how you are applying professional skills in a real project setting.

**What**: For Sprint #{sprint-no}, your report has three parts:

- **Self-Evaluation** - evaluate your presence, contributions, and collaboration using the provided rubrics, and justify your choices.
- **Implementation Check from Professional Development**
- **Reflection** - connect your experiences from this sprint to project practices and the program.

**When:** Sprint Report #{sprint-no} Due on Gradescope by {report-due}. Late work will not be accepted. 

---

[[symposium]]
=== &#10003; Draft Symposium Materials

*Why:* The symposium poster and video allow your team to summarize your project work, highlight progress made, and outline future goals. This is an opportunity to communicate your work clearly to a broad audience at The Data Mine Symposium.

*What:* Please review the following Guidelines for the Final Poster: {poster} and for the Final Video: {video}. *During this sprint, your team should complete a draft of your poster and video* and continuing working on this until the final week of term when you will present at The Data Mine Symposium.

*Symposium Materials Due:* +
**Draft**: Due on Gradescope by {report-due}. Late work will not be accepted. +
**Final Version**: ????????. Late work will not be accepted. +
_Your TA will submit the presentation on behalf of the entire team._





////
== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 2/27
|Mon 2/24

|*Sprint End Date*
|Wed 3/12
|Sun 3/9


|===


== Sprint Tasks

=== &#10003; Draft Symposium Materials – Poster and Video

To recap the semester, your team will present on project progress and future goals. Please review the following Guidelines for the Final Poster: xref:spring2025/poster_guidelines.adoc[Final Poster Details]. Please review the following Guidelines for the Final Video: xref:spring2025/video_guidelines.adoc[Final Video Details].

During this sprint, your team should complete a first draft of your poster and video and continuing working on this until the final week of term when you will present at The Data Mine Symposium.

*When:* First Draft due Wednesday, March 12, 2025 at 11:59 PM ET. Late work will not be accepted. Final Draft due Friday, April 9, 2025 at 11:59 PM ET. Late work will not be accepted. 

*What:* Final Poster and Video Draft - refer here for xref:spring2025/poster_guidelines.adoc[Final Poster Details] and xref:spring2025/video_guidelines.adoc[Final Video Details].

*Where:* Your TA will submit on behalf of the team. We only need 1 submission per team. 

=== &#10003; Professional Development 

The Data Mine Corporate Partners program is a professional development program. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

Each sprint you will complete a few professional development-related tasks. 

The Data Mine Corporate Partners program is a professional development program. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

In preparation for The Data Mine Symposium, this sprint you will review 3-minute thesis videos and reflect on https://www.gradescope.com/[Gradescope] 

++++
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}

.accordion:after {
  content: '\002B';
  color: #777;
  font-weight: bold;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2212";
}

.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>

  <button class="accordion">3-Minute Thesis Critique</button>
  <div class="panel">
    <div>
      <p><b>When: </b>Due Wednesday, March 5, 2025 at 11:59 PM ET. Late work will not be accepted.</p><br>
    </div>
    <div>
      <p><b>What: </b> Review 3-Minute Thesis (3MT) from last year's <a href="https://datamine.purdue.edu/symposium/">Symposium</a> and reflect on items you want to mimic or change/avoid.</b></p><br>
    </div>
    <div>
      <p><b>Where: </b>Complete the reflection on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 4: Professional Development".</p><br>
      </div>
    <div>
  <p><b>Why: </b> The Data Mine Corporate Partners teams submit a 3MT video at the end of the spring semester. Being able to give a 3-minute thesis about your Data Mine project to a non-technical audience is an important skill to learn for The Data Mine Symposium.</p><br>
    </div>
  </div>

<button class="accordion">LinkedIn</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, March 5, 2024 at 11:59 PM ET. Late work will not be accepted.	
		</p><br>
	</div>
	<div>
		<p><b>What: </b><a href ="https://www.linkedin.com/pulse/10-tips-students-new-grads-linkedin-omar-garriott?utm_source=share&utm_medium=guest_desktop&utm_campaign=copy">Read this article</a> or <a href ="https://socialimpact.linkedin.com/content/dam/me/members/en-us/pdf/li_studenten_Playbook_eng.pdf">review this document</a> about how to improve your Linkedin profile. After, please take at least one tip from the article and use it to improve your profile. <br> Also add The Data Mine as experience, making sure to follow <a href="https://the-examples-book.com/crp/students/datamine_resume_LinkedIn">these guidelines<a/>. <b>Purdue or The Data Mine should be indicated as the employer</b>, as putting your company will invalidate future background checks.</p>

    <p><b>NOTE:</b> If you do not have a Linkedin profile already, please create one by following <a href ="https://www.youtube.com/watch?v=pQFuGIlZOC4"> the steps in this video </a>. Even if you have a profile already, it might be worthwhile to watch some parts of this video to make improvements.</p><br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 4: Professional Development".</p><br>
  	</div>
	<div>
		<p><b>Why: </b> Having a strong and active Linkedin presence is crucial for attracting recruiters and starting your career. Learning the best practices is important to optimize your profile and help set yourself apart from others.</p><br>
  </div>
</div>

<script>
  var acc = document.getElementsByClassName("accordion");
  var i;

  for (i = 0; i < acc.length; i++) {
    acc[i].addEventListener("click", function() {
      this.classList.toggle("active");
      var panel = this.nextElementSibling;
      if (panel.style.maxHeight) {
        panel.style.maxHeight = null;
      } else {
        panel.style.maxHeight = panel.scrollHeight + "px";
      } 
    });
  }
</script>

</body>
</html>
++++

=== &#10003;Sprint #4 Report 

*Released:* The assignment will open for submissions one week before the due date starting Thursday, March 6, 2025. 

*When:* Due Wednesday, March 12, 2025 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in Sprint #4 Report accessed on Gradescope. 

*Where:* Submit the report on link:https://www.gradescope.com/[Gradescope] titled "Sprint 4: Report".

