= Sprint #12
// Sprint-specific 
:sprint-no: 12
:previous-sprint-no: 11
:start-date: Mar 9 
:end-date:  Mar 27, 2026
:spring-year: 2026
:fall-year: 2025

// Tasks with due dates 
:pd-due: Wed, Mar 25, 2026 @ 11:59 PM ET
:report-due: Wed, Apr 1, 2026 @ 11:59 PM ET

//sites
:gradescope-link: link:https://www.gradescope.com/[Gradescope,window=_blank]
:syllabus: xref:spring2026/syllabus.adoc[Syllabus, window=_blank]
:schedule: xref:spring2026/schedule.adoc[Course Schedule, window=_blank]
:poster: xref:spring2025/poster_guidelines.adoc[Final Poster Details, window=_blank]
:video: xref:spring2025/video_guidelines.adoc[Final Video Details, window=_blank]


== Sprint {sprint-no} Timeline
> Sprint Duration: **{start-date} - {end-date}**

[cols="3,4,2", options="header"]
|===
| Task | Due Date | Where

| ✓ <<professional-development, Professional Development>>
| **{pd-due}** 
.2+.^| {gradescope-link}

| ✓ <<sprint-report, Sprint #{sprint-no} Report>>
| **{report-due}**

|===

*Note:* _Monday, March 16 to Saturday, March 21: Spring Break (no Corporate Partner meetings/classes)_

== Sprint Task
'''
[[professional-development]]
=== &#10003; [.green]#Professional Development#
During sprint {sprint-no}, ...

**When:** Professional Development Due on Gradescope by {pd-due}. Late work will not be accepted. 

.**1. Imposter Syndrome**
[%collapsible%open]
====
*Why:* 

*What*: 

====

.**2. Biases*
[%collapsible%open]
====
*Why:* 

*What:* 
====


---
[[sprint-report]]
=== &#10003;Sprint #{sprint-no} Report
**Why**: The Sprint Report is part of your grade and helps you reflect on your past work. It also gives you the chance to step back, recognize your impact, and track your growth as a teammate and professional.  Each section is designed to help you think about your role, your progress, and how you are applying professional skills in a real project setting.

**What**: For Sprint #{sprint-no}, your report has three parts:

- **Self-Evaluation** - evaluate your presence, contributions, and collaboration using the provided rubrics, and justify your choices.
- **Implementation Check from Professional Development**
- **Reflection** - connect your experiences from this sprint to project practices and the program.

**When:** Sprint Report #{sprint-no} Due on Gradescope by {report-due}. Late work will not be accepted. 

---



////
== Sprint Dates


[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

3+|*_Monday, March 17 to Saturday, March 22:  Spring Break (no Corporate Partner meetings/classes)_*

|*Sprint Start Date*
|Thurs 3/13
|Mon 3/10

|*Sprint End Date*
|Wed 4/2
|Sun 3/30


|===

== Sprint Tasks

=== &#10003; Professional Development 

The Data Mine Corporate Partners program is a professional development program. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

Each sprint you will complete a few professional development-related tasks. 

++++
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}

.accordion:after {
  content: '\002B';
  color: #777;
  font-weight: bold;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2212";
}

.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>

<button class="accordion">Documentation Guide</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, October 9, 2024 at 11:59 PM ET. Late work will not be accepted.
		</p><br>
	</div>
	<div>
		<p><b>What: </b>Read this article about <a href="https://www.atlassian.com/work-management/knowledge-sharing/documentation/importance-of-documentation">The Importance of Documentation</a> and write a reflection in "Sprint 4: Professional Development".</p><br>
	</div>
	<div>
		<p><b>Where: </b>Complete the reflection for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 4: Professional Development".</p><br>
  </div>
  <div>
		<p><b>Why: </b>Documentation is essential in both The Data Mine and the real world. While it might not be the most exciting part of your job, it is one of the most valuable. Therefore, it is important to stay up to date with it and reflect on how your team has kept up thus far. </p><br>
  </div>
</div>

<button class="accordion">Implicit Biases - Countermeasures</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, September 4, 2024 at 11:59 PM ET. Late work will not be accepted.</p><br>
	</div>
	<div>
		<p><b>What: </b>Watch the following video <a href="https://www.youtube.com/watch?v=RIOGenWu_iA&list=PLWG_vsmMJ2clEeGKVyrOIKlOYrjFnVKqa&index=7 " >Implicit Bias: Lesson #6 - Countermeasures </a> (5 minutes). </p><br>
	</div>
	<div>
		<p><b>Where: </b>Complete the reflection for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 5: Professional Development".</p><br>
  </div>
    <p><b>Why: </b> The video discusses strategies to mitigate implicit bias, emphasizing mindset, debiasing, and decoupling. Mindset involves being humble and mindful of our biases. Debiasing focuses on reshaping biases through exposure to counter-stereotypical examples. Decoupling aims to implement structures and procedures that minimize bias in decision-making. These strategies are crucial for recognizing and addressing implicit biases, which are pervasive and impact behavior. Understanding and applying these methods is essential for promoting fairness and equity in various settings. </p><br>
    </div> 
</div>

<button class="accordion">Implicit Biases - Implicit Association Test</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, September 4, 2024 at 11:59 PM ET. Late work will not be accepted.</p><br>
	</div>
	<div>
		<p><b>What: </b>Watch the following video <a href="https://www.youtube.com/watch?v=hr9xAcWv790&list=PLWG_vsmMJ2clEeGKVyrOIKlOYrjFnVKqa&index=6 " >Implicit Bias: Lesson #5 - Implicit Association Test </a> (5 minutes). If you want, you can take the IAT here <a href= "https://implicit.harvard.edu/implicit/selectatest.html" > IAT </a></p><br>
	</div>
	<div>
		<p><b>Where: </b>Complete the reflection for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 4: Professional Development".</p><br>
  </div>
    <p><b>Why: </b> The Implicit Association Test (IAT) is a widely-used tool for measuring implicit biases by assessing reaction times in sorting tasks. It reveals how quickly we associate concepts like race or gender with positive or negative attributes. The IAT demonstrates that implicit biases are pervasive and statistically significant, even though the effect sizes are small. Despite its effectiveness, the IAT has limitations, such as the potential for variability in individual responses. Understanding these biases is crucial for addressing their impact on behavior and promoting equity. </p><br>
    </div> 
</div>


<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

</body>
</html>
++++



=== &#10003; Sprint #5  Report 

*Released:* The assignment will open for submissions one week before the due date starting Thursday, March 27, 2025. 

*When:* Due Wednesday, April 2, 2025 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in Sprint #5 Report.

*Where:* Submit the report on link:https://www.gradescope.com/[Gradescope] titled "Sprint 5: Report".


