= Sprint #9

// Sprint-specific 
:sprint-no: 9
:previous-sprint-no: 8
:start-date: Jan 26  
:end-date: Feb 6, 2026
:spring-year: 2026
:fall-year: 2025

// Tasks with due dates 
:pd-due: Wed, Feb 4, 2026 @ 11:59 PM ET
:report-due: Wed, Feb 11, 2026 @ 11:59 PM ET

//sites
:gradescope-link: link:https://www.gradescope.com/[Gradescope,window=_blank]
:ms-teams: xref:spring2025/MS_Teams.adoc[MS Teams in The Data Mine, window=_blank]
:anvil: link:https://the-examples-book.com/setup[Setting Up Accounts for The Data Mine, window=_blank]
:first-class: link:https://www.youtube.com/watch?v=jE_8u1_wF-s["first day of class" video, window=_blank]
:syllabus: xref:spring2026/syllabus.adoc[Syllabus, window=_blank]
:schedule: xref:spring2026/schedule.adoc[Course Schedule, window=_blank]
:agile: link:https://the-examples-book.com/crp/projectmanagement/intro[Project Management Training, window=_blank]
:genai: link:https://www.youtube.com/watch?v=mEtAfbFr6RE[Cheating or Learning? Walking the AI tightrope in education, window=_blank]
:data-purdue: link:https://www.eventreg.purdue.edu/WebCert/CourseListing.aspx?master_id=5398&master_version=1&course_area=CERT&course_number=340&course_subtitle=00[Data Classification and Handling Training, window=_blank]
:data-no-purdue: link:https://the-examples-book.com/crp/students/_attachments/Data_Classification_and_Handling_Educational_Resources.pdf[Data Handling at Purdue, window=_blank]
:kanban: link:https://www.youtube.com/watch?v=R8dYLbJiTUE[Intro to Kanban, window=_blank]
:onlinemeetings: link:https://the-examples-book.com/crp/students/online_meeting[Online Meeting "Net-etiquette", window=_blank]

== Sprint {sprint-no} Timeline
> Sprint Duration: **{start-date} - {end-date}**

[cols="3,4,2", options="header"]
|===
| Task | Due Date | Where

| ✓ <<professional-development, Professional Development>>
| **{pd-due}** 
.2+.^| {gradescope-link}

| ✓ <<sprint-report, Sprint #{sprint-no} Report>>
| **{report-due}**

|===

== Sprint Task
'''
[[professional-development]]
=== &#10003; [.green]#Professional Development#
During sprint {sprint-no}, ...

**When:** Professional Development Due on Gradescope by {pd-due}. Late work will not be accepted. 

.**1. Poster Critique**
[%collapsible%open]
====
*Why:* 

*What*: 

====

.**2. Documentation**
[%collapsible%open]
====
*Why:* 

*What:* 
====


---
[[sprint-report]]
=== &#10003;Sprint #{sprint-no} Report
**Why**: The Sprint Report is part of your grade and helps you reflect on your past work. It also gives you the chance to step back, recognize your impact, and track your growth as a teammate and professional.  Each section is designed to help you think about your role, your progress, and how you are applying professional skills in a real project setting.

**What**: For Sprint #{sprint-no}, your report has three parts:

- **Self-Evaluation** - evaluate your presence, contributions, and collaboration using the provided rubrics, and justify your choices.
- **Implementation Check from Professional Development**
- **Reflection** - connect your experiences from this sprint to project practices and the program.

**When:** Sprint Report #{sprint-no} Due on Gradescope by {report-due}. Late work will not be accepted. 



////

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 1/30
|Mon 1/27

|*Sprint End Date*
|Wed 2/12
|Sun 2/9


|===

== Sprint Tasks


=== &#10003; Professional Development 

The Data Mine Corporate Partners program is a professional development program. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

In each sprint, you will complete one https://www.gradescope.com/[Gradescope Quiz] on this sprint's professional development topics.

++++
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}

.accordion:after {
  content: '\002B';
  color: #777;
  font-weight: bold;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2212";
}

.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>

<button class="accordion">Artificial Intelligence</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, February 5, 2025 at 11:59 PM ET. Late work will not be accepted.
		</p>
<br>
	</div>
	<div>
		<p><b>What: </b>Watch this video on <a href="https://www.youtube.com/watch?v=mEtAfbFr6RE">  Cheating or Learning? Walking the AI tightrope in education </a>. Take the 15 minutes to watch it/listen to it. Please don't ask a GenAI tool to summarize it. We want your critical thought of the video content.The goal of this video and reflection is to guide you when and how you should considering using AI (not trying to dissuade or ban it's use). Answer the reflection questions in Gradescope. </p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the reflection on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 2: Professional Development". </p>
<br>
  	</div>
	<div>
		<p><b>Why: </b> As Artificial Intelligence continues to expand in our world, understanding its business impact is crucial. This tool has many pros and cons, so it's important to have a well-rounded comprehension of its usage. </p>
<br>
  </div>
</div>

<button class="accordion">Data Handling and Security</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, February 5, 2025 at 11:59 PM ET. Late work will not be accepted.
		</p>
<br>
	</div>
	<div>
		<p><b>What: </b>Complete Purdue's <a href="https://www.eventreg.purdue.edu/WebCert/CourseListing.aspx?master_id=5398&master_version=1&course_area=CERT&course_number=340&course_subtitle=00">Data Classification and Handling Training.</a> If your certification from fall is still active, you may re-upload that document. NDMN & IDMN students (only) <a href="https://the-examples-book.com/crp/students/_attachments/Data_Classification_and_Handling_Educational_Resources.pdf"> download this file and review instead.</a> <b> If you believe that data was incorrectly handled or shared, please notify datamine@purdue.edu immediately.</b></p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 2: Professional Development".</p>
<br>
    </div>
  <div> 
        <p><b>Why: </b> This is required by for all Data Mine members, including staff, by Purdue University. </p>
<br>
    </div> 
</div>


<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

</body>
</html>
++++

=== &#10003; Sprint #2 Report 

*Released:* The assignment will open for submissions one week before the due date starting Thursday, February 6, 2025. 

*When:* Due Wednesday, February 12, 2025 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in the Sprint #2 Report accessed on Gradescope. Write your answers directly in the Gradescope assignment. 

*Where:* Submit the report on link:https://www.gradescope.com/[Gradescope] titled "Sprint 2: Report".
////



////
<button class="accordion">Conflict Resolution</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, February 5, 2025 at 11:59 PM ET. Late work will not be accepted.	</p>
<br>
	</div>
	<div>
		<p><b>What: </b>Please <a href="https://www.youtube.com/watch?v=AnIk41p9QnA">watch this video</a> about conflict resolution and reflect on its contents in Gradescope.</b></p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the reflection for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 2: Professional Development".</p>
<br>
  	</div>
	<div>
		<p><b>Why: </b> All teams experience conflict at some point. It is crucial to handle conflicts professionally and respectfully. Include these conflict resolution strategies in your Team Contracts to ensure everyone is on the same page. </p>
<br>
  </div>
</div>
////
