= Sprint #8

// Sprint-specific 
:sprint-no: 8
:previous-sprint-no: 7
:start-date: Jan 12 
:end-date: Jan 23, 2026
:spring-year: 2026
:fall-year: 2025

// Tasks with due dates 
:pd-due: Wed, Jan 21, 2026 @ 11:59 PM ET
:report-due: Wed, Jan 28, 2026 @ 11:59 PM ET

//sites
:gradescope-link: link:https://www.gradescope.com/[Gradescope,window=_blank]
:ms-teams: xref:spring2025/MS_Teams.adoc[MS Teams in The Data Mine, window=_blank]
:anvil: link:https://the-examples-book.com/setup[Setting Up Accounts for The Data Mine, window=_blank]
:first-class: link:https://www.youtube.com/watch?v=jE_8u1_wF-s["first day of class" video, window=_blank]
:syllabus: xref:spring2026/syllabus.adoc[Syllabus, window=_blank]
:schedule: xref:spring2026/schedule.adoc[Course Schedule, window=_blank]
:agile: link:https://the-examples-book.com/crp/projectmanagement/intro[Project Management Training, window=_blank]
:genai: link:https://www.youtube.com/watch?v=mEtAfbFr6RE[Cheating or Learning? Walking the AI tightrope in education, window=_blank]
:data-purdue: link:https://www.eventreg.purdue.edu/WebCert/CourseListing.aspx?master_id=5398&master_version=1&course_area=CERT&course_number=340&course_subtitle=00[Data Classification and Handling Training, window=_blank]
:data-no-purdue: link:https://the-examples-book.com/crp/students/_attachments/Data_Classification_and_Handling_Educational_Resources.pdf[Data Handling at Purdue, window=_blank]
:kanban: link:https://www.youtube.com/watch?v=R8dYLbJiTUE[Intro to Kanban, window=_blank]
:onlinemeetings: link:https://the-examples-book.com/crp/students/online_meeting[Online Meeting "Net-etiquette", window=_blank]

== Sprint {sprint-no} Timeline
> Sprint Duration: **{start-date} - {end-date}**

[cols="3,4,2", options="header"]
|===
| Task | Due Date | Where

| ✓ <<onboarding, New Students Onboarding>> +
 - First Day of Class +
 - Anvil +
 - MS Teams 
^.^| **By the first day of class**
^.^| Check details below

| ✓ <<pm, Project Management Training>> (Optional)
.3+^.^| **{pd-due}** 
.4+^.^| {gradescope-link}

| ✓ <<quiz, Syllabus Quiz>>


| ✓ <<professional-development, Professional Development>>


| ✓ <<sprint-report, Sprint #{sprint-no} Report>>
| **{report-due}**

|===

*Important Note*: _Mon, January 19, 2026 is MLK Jr. Day (No Classes)._

---

== Sprint Tasks

NOTE: The first sprint has a lot of tasks to help aide with onboarding. In future sprints, plan to spend more time working on your project.

[[onboarding]]
=== &#10003; New Students Onboarding
In the Corporate Partners course, we do not hold a single first class with all 800+ students, as teams begin meeting immediately. Instead, onboarding is completed asynchronously through required setup tasks, and a short recorded video that covers first-day information. This includes setting up Anvil (when required) and MS Teams, which are essential tools for project work and communication. 

*When:* By the first day of class

.*1. First Day of Class Video*
[%collapsible%open]
====
*Why:* You will not have a single in-person first class because teams begin meeting immediately. This video provides the key information you need to get started in the course.

*What:* Watch the recorded {first-class} video. It was recorded in Fall {fall-year}, but all information is still relevant.
====

.*2. Anvil Access*
[%collapsible%open]
====
*_Note:* If your Corporate Partner uses a different environment, no additional action is needed._

*Why:* Project work for Seminar and some Corporate Partners is conducted in Anvil. An ACCESS account ensures you can access the required computing environment when needed.

*What:* Create one ACCESS account to log in to Anvil by following the instructions at {anvil}. Do not repeat this step if you have already set it up for Seminar.

====
.*3. Download MS Teams*
[%collapsible%open]
====
*Why:* The Data Mine uses MS Teams as one of our primary communication tools. You will need to download MS Teams to your computer. Your team SHOULD NOT use any other form of communication (e.g., Slack, Discord, etc.) unless approved by The Data Mine staff and your mentor. 

*What:* Review this page about {ms-teams}. Download MS Teams Desktop App to your computer (and phone if you would like). 
====

'''

[[pm]]
=== &#10003; Project Management Training
*Why:* The Data Mine Corporate Partners program uses Agile methods for project management. Agile is widely used in industry, and many of our Corporate Partners follow this approach. This sprint provides an opportunity to review Agile concepts and how they are applied in project-based work.

*What:* Complete the {agile} and take the quiz. This quiz is optional as most students completed it in Fall {fall-year}. It is available for new students to take and is worth zero points.

**When:** Project Management Quiz Due on Gradescope by {pd-due}. (Optional)

'''

[[quiz]]
=== &#10003; Syllabus Quiz
*Why:* This quiz focuses on shared syllabus information relevant to all Data Mine Corporate Partner students, regardless of project or mentor.

*What:* Both new and returning students should review the spring {spring-year} {syllabus} and {schedule}. Then, take the quiz up to three times; your highest score will be recorded. You may keep the syllabus open while taking the quiz.

_Please note there is a separate syllabus quiz for the 1 credit seminar class (TDM 102, 202, 302, 402, 502)._

**When:** Syllabus Quiz Due on Gradescope by {pd-due}. Late work will not be accepted. 


'''
[[professional-development]]
=== &#10003; Professional Development
During sprint {sprint-no}, this professional development focuses on reviewing team expectations, thinking critically about the use of artificial intelligence, and completing required data handling training.

**When:** Professional Development Due on Gradescope by {pd-due}. Late work will not be accepted. 

.**1. Team Contract Review**
[%collapsible%open]
====
*Why:* Team Contracts are the foundation of a successful team, helping members understand expectations, establish norms, and define accountability. During a TA-facilitated discussion, teams will review their contract to identify what is working well, what may need clarification or updates, and how accountability will be enforced if expectations are not met. New students should use this opportunity to familiarize themselves with the contract and align with their team, while returning students should reflect on its effectiveness and contribute suggestions to improve clarity and usability.

*What*: After reviewing your Team Contract and participating in the TA-facilitated discussion, complete the reflection:

- Team Contract Understanding
- Accountability & Improvements

====

.**2. Artificial Intellgence**
[%collapsible%open]
====
*Why:* Generative AI tools are widely available and increasingly used in academic and professional settings. This activity is designed to help you think critically about when and how GenAI should be used as a learning support, rather than relying on it automatically.

*What:* Watch the provided video on {genai} (approximately 15 minutes). Do not use a GenAI tool to summarize the video. After watching, reflect on the questions posed and write your own thoughtful responses based on your experiences and perspectives.
====

.**3. Data Handling**
[%collapsible%open]
====
*Why:* Responsible data handling is a core expectation for Data Mine students. This certification ensures you understand best practices related to data privacy, security, and ethical use of data, which are essential for academic work and Corporate Partner projects.

*What:* Complete the required data handling training based on your student status.

- *Purdue students:* Complete Purdue’s {data-purdue}. If your certification from Fall {fall-year} is still active, you may re-upload that document. Upload a screenshot showing your name and valid dates (active through at least May 1, {spring-year}).

- *National Data Mine (NDMN & IDMN) students:* Download and review {data-no-purdue}, then upload a one-paragraph PDF reflection summarizing what you learned from the training.

_Note: If you believe that data was incorrectly handled or shared, please notify datamine@purdue.edu immediately._
====

WARNING: Regarding point 4&5 - do we want to have these included 

.**4. Kanban Board**
[%collapsible%open]
====
*Why:* Utilizing a Kanban board is essential for a team's success in The Data Mine. Returning students, reflect on how effectively you used the Kanban board during the fall semester. New students, learn to use the Kanban board effectively, as it will be crucial for tracking your projects in The Data Mine.

*What:* Watch the following video {kanban} (5 minutes) OR read this Article .
====

.**5. Meeting Expectations**
[%collapsible%open]
====
*Why:* Students in The Data Mine Corporate Partners program meet with their Corporate Partner Mentors online via Microsoft Teams every week. Conducting oneself professionally in a virtual setting is a crucial skill to develop. Returning students should reflect on their experiences from the fall {fall-year} semester, noting what went well and identifying areas for improvement. New students should familiarize themselves with the do's and don'ts of these meetings to ensure they make a positive impression

*What:* Both new and returning students should review the information and watch the video on effective participation in virtual meetings {onlinemeetings}
====

---
[[sprint-report]]
=== &#10003;Sprint #{sprint-no} Report
**Why**: The Sprint Report is part of your grade and helps you reflect on your past work. It also gives you the chance to step back, recognize your impact, and track your growth as a teammate and professional.  Each section is designed to help you think about your role, your progress, and how you are applying professional skills in a real project setting.

**What**: For Sprint #{sprint-no}, your report has three parts:

- **Self-Evaluation** - evaluate your presence, contributions, and collaboration using the provided rubrics, and justify your choices.
- **Reflection** - connect your experiences from this sprint to project practices and the program.

**When:** Sprint Report #{sprint-no} Due on Gradescope by {report-due}. Late work will not be accepted. 












////
== Intro Video

In the Corporate Partners course, we don't have a first class with all 800+ students together in one space because teams start meeting immediately. Instead, we recorded a 10-minute video of the information we would share on the first class. This video is from fall 2024, but all information is still relevant. 

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/xEDCqtK7I-c?si=XKlVlsKsBBXjRTxD" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
++++

== Sprint Dates
_All sprints will have the same due dates_, but the sprint start and end dates are slightly shifted depending on when a team has their lab (2 hours) and lecture (50 minutes). This is so that sprints always start with a lec and follow the format lec-lab-lec-lab.

You can find a xref:projectmanagement:ceremonies.adoc#sprint-schedule[visual of the sprint schedule in the Agile Training Ceremonies page]. More details will be covered in the agile training below. 


[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

3+| _Monday, 1/20:  Martin Luther King Jr. Day (no Corporate Partner meetings/classes)_

|*Sprint Start Date*
|*Mon 1/13
|Mon 1/13

|*Sprint End Date*
|Wed 1/29
|Sun 1/26

|*Due Date*
2+| Wed 1/29 by 11:59 PM ET

|===

_*Please note that sprint 1 starts on January 13, the first day of spring 2025 semester, for both schedules. Once we are in a regular sprint schedule, you will see the "(1)lab then (2)meeting" schedule shift to starting on Thursdays._


== Sprint Tasks

NOTE: The first sprint has a lot of tasks to help aide with onboarding. In future sprints, plan to spend more time working on your project.

=== &#10003; Anvil Access

_*Do not submit this more than once. You only need to create *one* account that you will use for Seminar and Corporate Partners. If you already filled this out last semester or for Seminar, do not do it again.*_ 

*When:* By the first day of class

*What:* Create an ACCESS account so you can login to Anvil. Do not do this again if you already set it up for Seminar. 

*Where:* Find instructions to link:https://the-examples-book.com/setup[create an ACCESS account to utilize Anvil here.] Don't forget the last step of submitting your username to the Qualtrics survey (at the bottom of the instructions page). 

=== &#10003; Download MS Teams

The Data Mine uses MS Teams as one of our primary communication tools. You will need to download MS Teams to your computer. Your team SHOULD NOT use any other form of communication (e.g., Slack, Discord, etc.) unless approved by The Data Mine staff and your mentor. 

*When:* By the first day of class

*What:* Review this page xref:spring2025/MS_Teams.adoc[about MS Teams in The Data Mine]. Download MS Teams Desktop App to your computer (and phone if you would like). 

*Where:* Download via the link above. 

=== &#10003; Syllabus Quiz

While all teams will work on different projects and mentors will provide a project charter, the syllabus includes information that every Data Mine Corporate Partner student needs to know. 

*When:* Due Wednesday, January 29, 2025 at 11:59 PM ET. Late work will not be accepted.  

*What:* Both new and returning students should review the xref:spring2025/syllabus.adoc[spring 2025 syllabus page] and xref:spring2025/schedule.adoc[spring 2025 course schedule]. Take the quiz up to 3 times and your highest score will be taken. You may have the syllabus open while you take the quiz. _Please note there is a separate syllabus quiz for the 1-credit seminar class (TDM 102, 202, 302, 402, 501)._

*Where:* Take the quiz on link:https://www.gradescope.com/[Gradescope] 

_Please note there is a separate syllabus quiz for the 1 credit seminar class (TDM 102, 202, 302, 402, 502)._

=== &#10003; Project Management Training 

The Data Mine Corporate Partners will implement Agile methods into our project management. Agile is very popular in industry and the majority of our Corporate Partners use it. Now is the best time to practice it while you are a student. 

During your first or second lab session, you will be using Legos to learn the Agile approach to project management. Your TA will be facilitating this Lego lab. We encourage you to review this link:https://thisiszone.medium.com/using-lego-to-show-the-advantages-of-an-agile-approach-to-software-development-3eda6e5c2114[article]. 

*When:* This quiz is _OPTIONAL_ as most students took it in fall 2024. The quiz is available for new students to take, but is worth zero points. Quiz closes Wednesday, January 29, 2025 at 11:59 PM ET. 

*What:* Complete the link:https://the-examples-book.com/crp/projectmanagement/intro[Project Management Training], participate in the Lego lab activity, and take the quiz. 

*Where:* Take the quiz on link:https://www.gradescope.com/[Gradescope] titled "Sprint 1: Project Management Quiz"

=== &#10003; Professional Development 

The Data Mine Corporate Partners program is a professional development program. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

Each sprint you will complete a few professional development related tasks. To begin, let's review confidentiality, virtual meeting expectations, email communications and implicit biases. 

Open each accordion by clicking on it. Please note the combined tasks below pertain to *one* assignment in Gradescope called `Sprint 1: Professional Development`.

// To begin, let's review confidentiality, netiquette, and email communication.

++++
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}

.accordion:after {
  content: '\002B';
  color: #777;
  font-weight: bold;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2212";
}

.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>

<button class="accordion">Virtual Meeting Expectations</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, January 29, 2025 at 11:59 PM ET. Late work will not be accepted.</p>
<br>
	</div>
	<div>
		<p><b>What: </b> Both new and returning students should <a href="https://the-examples-book.com/crp/students/online_meeting">read this information and watch the video about how to effectively participate in a virtual meeting</a>.</b></p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the reflection for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 1: Professional Development".</p>
<br>
  	</div>
	<div>
		<p><b>Why: </b> Students in The Data Mine Corporate Partners program meet with their Corporate Partner Mentors online via Microsoft Teams every week. Conducting oneself professionally in a virtual setting is a crucial skill to develop. Returning students should reflect on their experiences from the fall semester, noting what went well and identifying areas for improvement. New students should familiarize themselves with the do's and don'ts of these meetings to ensure they make a positive impression. </p>
<br>
  </div>
</div>

<button class="accordion">Kanban Board</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due January 29, 2025 at 11:59 PM ET. Late work will not be accepted.</p>
<br>
	</div>
	<div>
		<p><b>What: </b>Watch the following video <a href="https://www.youtube.com/watch?v=R8dYLbJiTUE">Intro to Kanban </a> (5 minutes) OR read this <a  href = "https://www.atlassian.com/agile/kanban#:~:text=In%20Japanese%2C%20kanban%20literally%20translates,in%20a%20highly%20visual%20manner."> Article </a>. </p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 1: Professional Development".</p>
<br>
  </div>
    <p><b>Why: </b> Utilizing a Kanban board is essential for a team's success in The Data Mine. Returning students, reflect on how effectively you used the Kanban board during the fall semester. New students, learn to use the Kanban board effectively, as it will be crucial for tracking your projects in The Data Mine. </p>
<br>
    </div> 
</div>

<button class="accordion">Team Contract Review</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, January 29, 2025 at 11:59 PM ET. Late work will not be accepted.</p>
<br>
	</div>
	<div>
		<p><b>What: </b>Please review the Team Contract your team composed during Fall Semester. IF you don't know where it is, ask your TA.</a> (5 minutes).</p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the reflection for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 1: Professional Development".</p>
<br>
  </div>
  <div>
		<p><b>Why: </b> Team Contracts are the foundation of a successful team. They help members understand expectations and establish norms. New students should familiarize themselves with this document to ensure alignment with the team. Additionally, returning students should reflect on its effectiveness and suggest improvements to enhance usability. </p>
<br>
  </div>
</div>

<button class="accordion">Implicit Biases - Real World Consequences</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, January 29, 2025 at 11:59 PM ET. Late work will not be accepted.</p>
<br>
	</div>
	<div>
		<p><b>What: </b>Watch the following video <a href="https://www.youtube.com/watch?v=8SIb97tZSpI&list=PLWG_vsmMJ2clEeGKVyrOIKlOYrjFnVKqa&index=4 " >Implicit Bias: Lesson #3 - Real World Consequences </a> (4 minutes) </p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the reflection for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 1: Professional Development".</p>
<br>
  </div>
    <p><b>Why: </b> Research over the past fifteen years has shown that implicit biases can significantly impact our decisions and behaviors, even if the effects are considered small statistically. A meta-analysis found that implicit biases are better predictors of discriminatory behavior than explicit biases which emphasizes the importance of addressing implicit biases to build equity for all. </p>
<br>
    </div> 
</div>

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

</body>
</html>
++++

=== &#10003; Sprint #1 Report 

*Released:* The assignment will open for submissions one week before the due date starting Wednesday, January 22, 2025. 

*When:* Due Wednesday, January 29, 2025 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in the Sprint #1 Report. 

*Where:* Submit the report on link:https://www.gradescope.com/[Gradescope] titled "Sprint 1: Report".
