= Sprint #10

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 2/13
|Mon 2/10

|*Sprint End Date*
|Wed 2/26
|Sun 2/23

|===

== Sprint Tasks

=== &#10003; Professional Development 

The Data Mine Corporate Partners program is a professional development program. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

In each sprint, you will complete one https://www.gradescope.com/[Gradescope Quiz] on this sprint's professional development topics.

++++
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}

.accordion:after {
  content: '\002B';
  color: #777;
  font-weight: bold;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2212";
}

.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>
  <button class="accordion">Poster Critique</button>
  <div class="panel">
    <div>
      <p><b>When: </b>Due Wednesday, February 19, 2025 at 11:59 PM ET. Late work will not be accepted.</p><br>
    </div>
    <div>
      <p><b>What: </b> Review posters from last year's <a href="https://datamine.purdue.edu/symposium/">Symposium</a> and reflect on items you want to mimic or change/avoid.</b></p><br>
    </div>
    <div>
      <p><b>Where: </b>Complete the reflection on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 3: Professional Development".</p><br>
      </div>
    <div>
  <p><b>Why: </b> The Data Mine Corporate Partners teams submit a poster at the end of the spring semester.</p><br>
    </div>
  </div>

  <button class="accordion">Implicit Biases - Explicit vs. Implicit Biases</button>
  <div class="panel">
    <div>
      <p><b>When: </b>Due Wednesday, February 19, 2025 at 11:59 PM ET. Late work will not be accepted.</p><br>
    </div>
    <div>
      <p><b>What: </b>Watch the following video <a href="https://www.youtube.com/watch?v=5S7Je6kbGDY&list=PLWG_vsmMJ2clEeGKVyrOIKlOYrjFnVKqa&index=5" >Implicit Bias: Lesson #4 - Implicit vs. Explicit Biases </a> (3 minutes)</p><br>
    </div>
    <div>
      <p><b>Where: </b>Complete the reflection for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 3: Professional Development".</p><br>
    </div>
      <p><b>Why: </b> Biases, whether explicit or implicit, significantly impact our behaviors and decisions. Explicit biases are consciously accessible and can be self-reported, though people may be unwilling to share them due to social pressures. Implicit biases, on the other hand, are unconscious and cannot be identified through introspection. Understanding both explicit and implicit biases is crucial for promoting fairness and equity, especially in professional and academic settings, where these biases can subtly yet powerfully influence outcomes. </p><br>
    </div> 
  </div>

  <script>
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
      acc[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var panel = this.nextElementSibling;
        if (panel.style.maxHeight) {
          panel.style.maxHeight = null;
        } else {
          panel.style.maxHeight = panel.scrollHeight + "px";
        } 
      });
    }
  </script>

</body>
</html>
++++

=== &#10003; Sprint #3 Report 

*Released:* The assignment will open for submissions one week before the due date starting Thursday, February 20, 2025. 

*When:* Due Wednesday, February 26, 2025 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in the Sprint #3 Report accessed on Gradescope. 

*Where:* Submit the report on link:https://www.gradescope.com/[Gradescope] titled "Sprint 3: Report".

