= Information to know for the day of the symposium:

The Data Mine will host two symposiums this year to support students in Indianapolis and West Lafayette. Students/teams will be required to present at their home location. Indianapolis teams will have the option to present in WL as well. 

== Logistics - Indianapolis

*What*: link:https://www.purdue.edu/undergrad-research/conferences/showcase/index.php[Student Innovation & Excellence Showcase]

*When*: Thursday, April 30, 2026. Two sessions: 10:30 AM to noon and 1:30 PM to 3:00 PM. 

*Where*: Campus Center - Room 450 (420 University Blvd, Indianapolis, IN 46202) 

*Who*: _Students in The Data Mine in Indianapolis are required to present at this event._ This event is open to the public so feel welcome to invite your friends. Primary attendees will be TDM students, TDM TAs, Corporate Partner Mentors, and guests. 

== Logistics - West Lafayette

*What*: link:https://datamine.purdue.edu/symposium/[The Data Mine Corporate Partners Symposium]

*When*: Wednesday, April 29, 2026, 4:00 - 6:00 PM ET _(doors open at 3:30 PM)_

*Where*: France A. Córdova Recreational Sports Center - Gyms 1, 2, & 3 (355 N Martin Jischke Dr, West Lafayette, IN 47906) Gyms 1, 2, & 3

*Who*: _Students in The Data Mine in West Lafayette are required to present at this event._ This event is open to the public so feel welcome to invite your friends. Primary attendees will be TDM students, TDM TAs, Corporate Partner Mentors, and guests. 


== Attendance

All Corporate Partner students are *required* to attend for at least 30 minutes at their poster. Only approved absences (like a scheduled class the entire session) will be excused with an alternative assignment to be posted by 5/1 morning. 

We encourage you to stay the entire time to visit the posters of your peers. 

NDMN students not attending in person should plan to do the alternative assignment or sign up for the NDMN virtual symposium.

== Poster setup 

Each team will have a table with a poster stand to display their poster. Teams only need to bring 1 copy of their poster (coordinated by the TA). 

Teams are welcome to use the remaining table space for up to 1 laptop display, but there is _no power access_ so make sure your device is charged. You cannot run electrical cords due to safety. 


== Staffing your poster
Each poster should have at least 2-3 team members present at all times. _Teams should plan 30 minute shifts in advance of the symposium and all team members are required to attend the symposium for a minimum of their 30 minute shift._

When you aren't staffing your own poster, we encourage you to visit the posters of your peers. The Data Mine students have conducted lots of exciting research. You might want to join one of these teams for next year. 

== Name tags
Name tags will be available at your poster.

== Bags
Please be mindful _to limit the number of articles you bring with you_ to reserve space. There will not be a coat or bag check available. Do NOT leave bags, coats, or other items on the floor. It is a safety hazard.  Store them neatly under your table. 

 
== Dress Code
Students should dress in business casual attire. General guidelines for business casual attire can be found link:https://www.indeed.com/career-advice/starting-new-job/guide-to-business-casual-attire[here].


== Roles
Each poster should have 2-3 team members present at all times. *Teams should plan 30 minute shifts in advance of the symposium and all team members are required to attend the symposium for a minimum of their 30 minute shift.* 

We encourage you to establish roles within your team for the in-person poster session. Please discuss with your team members to establish roles. Everyone should be actively participating in the Q&A. Here are some potential roles:

*Welcomer:* Welcomes new people as they observe your poster (if not interrupting a discussion).  If nobody is asking questions, this person can also be ready to give a short 1-2 minute “elevator pitch” about the project to motivate means for conversation. 

*Subcategory answerers/subject matter experts:*  Your team can decide who is best suited to answer certain types of questions. Decide on these categories and who should be in each one ahead of time.  Consider these to be “subject matter experts” for specialties. 

*Think of questions for your guests!*  Hopefully you will have great conversations with many guests.  Some will be Purdue faculty/staff/students.  Some will be your Corporate Partners mentors or people from their companies.  Some will be guests from other companies.  If you have answered all of their questions, it’s ok to ask them questions about themselves, too. 

* Who are they? 
* Where do they work?  
* What do they do? 
* Why are they excited about data science?  
* What do they recommend for you to do to get ready to have a career in data science?  
* Think of those extra questions for the speakers we have you write about in the Outside Event reflections.  This could be a great opportunity for you to meet some really interesting people!


== How can I prepare?

To prepare to interact with people, you might:

* Prepare a brief (maybe two- or three-sentence) overview of your research. Having that ready will help you to break the ice with viewers. Keep this quick overview general and interesting—perhaps focus on why you were interested in this research, problem, or issue (e.g., “I was curious as to why…”). 
* Practice explaining your poster. Open your poster  and have your friends stop by so you can get comfortable talking about your research. 
* Be sure to talk to the people who stop by your poster, and not to the poster! Talking at your poster or reading from your poster isn’t a great way to engage viewers. 

* Encourage people who stop by to provide feedback and/or submit their vote on the poster judging link. 

* Thank people who stop by to read your poster and talk with you.

_link:https://urca.msu.edu/posters[source]_

== Poster Map and Roster 

Below is 2025 map. A 2026 map is forthcoming. 

++++
<iframe id="sessionList" style="border:1px solid #666CCC" title="PDF in an i-Frame" src="../_attachments/2025_Table_Map.pdf" frameborder="1" scrolling="auto" height="850" width="850" ></iframe>
++++
++++
<iframe id="sessionList" style="border:1px solid #666CCC" title="PDF in an i-Frame" src="../_attachments/2025_Poster_Session_List.pdf" frameborder="1" scrolling="auto" height="1100" width="850" ></iframe>
++++


== Poster and Video Viewing after the in-person event
Posters and videos will be available link:https://datamine.purdue.edu/symposium/[on this website] on or near May 1. 

== Alternative Assignment for Symposium Attendance

This alternative assignment is only for students that have a University scheduled conflict (like a class or TA duties) during the full presentation window. If you have a different conflict, please provide approval of absence (i.e. an email or note) to your Corporate Partner Liaison. 

*When:* Due Friday, May 1, 2026 at 11:59 PM ET. Late work will not be accepted.  

*Where:* You will submit your answers directly in Gradescope.

*What:* To be posted after the symposium.  

// *What:* Download xref:attachment$spring2023-crp-alternative_symposium_assignment.docx[this file] and answer the questions in complete sentences. 

// *Where:* submit to link:https://www.gradescope.com/[Gradescope] as a *PDF* file. It is important to upload your document as a PDF. You will be deducted points if you submit any other file than a PDF.


*National Data Mine Network:* Students who were not able to be at the symposium in person, you have *two options* to receive credit for this alternative assignment:



// 1) Complete the assignment as directed with the deadline of Sunday, April 28th 

// OR

// 2) Present your team's poster in our NDMN Virtual Symposium on *Friday, April 26th from 2-4pm EST.* If you are interested in presenting, please email Jessica Jud at jljud@purdue.edu by Sunday, April 28th
