= Symposium Dinner List 

*Who:* All Data Mine students are invited to share a (free) meal after the poster session. 

*Date:* Wednesday, April 29, 2026

*Time:* See specifics for your team below. The staggered start times are to prevent congestion at the dining courts.

*Where:* See specifics for your team below

*Menus:* https://dining.purdue.edu/menus/ 

*Note:* Students with meal plans are encouraged to use their own swipes. _For those without a meal plan, please let the attendant taking swipes know that you are with The Data Mine Symposium._ They will keep a tally and charge Data Mine at the end. _You should not have to pay for anything._

*Allergies or dietary restrictions?*  If you have any allergies or dietary restrictions, please let the door checker know and the staff will be happy to help you navigate the dining court.



*Teams with a mentor visiting for dinner* 
[%header,format=csv]
|===
Time,Ford,Wiley,Windsor,Earhart,Hillenbrand
6:15 PM,General cohort students (seminar only) - Upstairs room in Ford,American Mathematical Society ,Bell Flight ,Caterpillar,ComEd
6:20 PM,FedEx,GTI Energy,IronWorkz LLC,McLain's ,Microsoft 
6:25 PM,Purdue SCALE ,Riley Children's Foundation,Rolls-Royce (Engine States),ScoutSync,TranslationalHDPM LLC
6:30 PM,V2X,World Wildlife Fund,,,

|===

*All other teams* 
[%header,format=csv]
|===

Time,Ford,Wiley,Windsor,Earhart,Hillenbrand
6:35 PM,3M ,CNH Industrial ,Frederick National Laboratory ,Molson Coors Beverage Co. ,Small Business Consulting Corporation 
6:35 PM,American Systems ,Concrete Engine ,Inari ,National Space Intelligence Center ,Stratolaunch 
6:35 PM,AstraZeneca ,Cook Medical ,John Deere ,Orion Labs LLC ,The Aerospace Corporation 
6:40 PM,BASF Corp. ,Costco ,Johnson & Johnson ,Practical AI Podcast ,U.S. Air Force 
6:40 PM,Bayer ,Crowdstrike ,Joint Cyber Center ,Prediction Guard ,U.S. SpaceCom J4 
6:40 PM,Beck's Hybrids ,Cultivate Food Rescue,Kautex Textron ,Purdue Student Life ,United States Space Force 
6:45 PM,Callaway Golf Company ,Cyberspatial ,Kimberly-Clark ,Purdue Women's Soccer ,USDA Forest Service
6:45 PM,Carnival Cruise Line ,Dow ,Knudsen Institute ,"Red Gold, Inc. ",USSF
6:45 PM,Center for C-SPAN Scholarship & Engagement ,Elanco ,L3Harris ,Rolls-Royce (Aerospace Data Synthesizer),Valbruna Slater Stainless 
6:50 PM,Central Insurance,Empire Cooler ,Low Research Lab ,RTX ,Zimmer Biomet 
6:50 PM,CityBus ,Feenix Group ,Mead Johnson Nutrition ,SDA Tap Lab ,
|===