= Dictionaries (`dicts`)

== Introduction

Dictionaries are a crucial data type used to store _key:value_ pairs. Dictionaries are https://en.wikipedia.org/wiki/Hash_table[hash maps/hash tables], which apply a hash function to the keys you insert, linking a location in code to your desired value. This makes dictionaries incredibly efficient and convenient for adding, removing, and searching for data at the expense of space. Dictionary bulk won't be a problem for our microcosmic environment of Data Mine projects, it's just a good thing to know about its structure.

The use for dictionaries (and hash maps in general) comes primarily from the connected nature of keys and values: counting occurrences of a word (`string`: `int`), saving house addresses for a zip code (`int`: `list` of `strings`), tracking a list of people with certain titles (`string`: `list` of `strings`), and so on. There will inevitably be a point where knowing how to use a dictionary will save you a lot of trouble.

{sp}+

=== Declaration

Dictionaries can be declared using `{}` or the `dict()` keyword, much like other array-like objects in Python.

[source,python]
----
dict_01 = {}  # an empty dictionary
dict_02 = dict()  # two empty dictionaries!

print(type(dict_01))
print(type(dict_02))
----

----
<class 'dict'>
<class 'dict'>
----

Declaring empty data structures is only so useful, so let's put some data in there! The ways to insert data change depend on declaration method as you'll see: 

[source,python]
----
name_dict = {"first_names": ["John", "Jill"], "last_names": ["Smith", "Johnson", "Chen"]}
id_dict = dict(names=["John Johnson", "Jill Chen"], ids=["0045265987", "0025012478"])

print(type(name_dict))
print(type(id_dict))
----

----
<class 'dict'>
<class 'dict'>
----

Note that with key-value assignment, `{}` uses ":" between the key and value, while `dict()` uses "=" to assign your value to a variable.

[CAUTION]
====
We include `dict()` declaration here, but there are a few reasons why `{}` is better. While you can use any immutable object as a key, `dict()` restricts assignment to variables cast as `strings` (in the above example, `names` and `ids` are both cast as `strings`), while `{}` allows free declaration. Though a secondary concern, `dict()` also runs slower and takes up more memory than `{}`. https://doughellmann.com/posts/the-performance-impact-of-using-dict-instead-of-in-cpython-2-7-2/[Here's an old article] on the topic if you want to know more.
====

Be careful when declaring a dictionary using `{}`, as sets are also declared using `{}` when there are no colons to indicate key:value pairs. No ":", no dictionary!

[source,python]
----
name_set = {"John", "Jill", "Ellen"}
print(type(name_set))
----

----
<class 'set'>
----

{sp}+

=== Acquisition

The two primary methods of getting data from a dictionary are the `get()` method and the square bracket method: 

[source,python]
----
things = {"fruits": ["apple", "orange", "pear"], "person": "John", "vegetables": ["carrots", "peas"]}

# If "person" is a key, they will function the same way
print(things["person"])
print(things.get("person"))
----

----
John
John
----

[source,python]
----
# If the key does not exist, like below, they will not 
# function the same way.
print(my_dict.get("height")) # Returns None when key doesn't exist
print(my_dict["height"]) # Throws a KeyError exception because the key "height" doesn't exist
----
----
None
<KeyError: 'height'>
----

Much like `dict()` vs `{}`, there are nuances that make `get()` better than `[]` in terms of value acquisition, including inherent exception handling like we demonstrated above.

{sp}+

=== Resources

There are a bunch of methods that are integral to effective dictionary manipulation -- here's a https://www.w3schools.com/python/python_ref_dictionary.asp[great introduction] to the basic methods you'll be using with dictionaries.

[cols="2*"]
|===
^|Method ^|Description

^|`clear()`
|Removes all the elements from the dictionary

^|`copy()`
|Returns a copy of the dictionary

^|`fromkeys(keys)`
|Returns a dictionary with the specified keys and value

^|`get(keyname)`
|Returns the value of the specified key

^|`items()`
|Returns a list containing a tuple for each key:value pair

^|`keys()`
|Returns a list conaining the dictionary's keys

^|`pop(keyname)`
|Removes the element with the specified key

^|`popitem()`
|Removes the last inserted key:value pair

^|`setdefault(keyname, value)`
|If the key exists, returns the value. If the key doesn't exist, inserts key with specified value.

^|`update(iterable)`
|Iterable contains key:value pairs. If key(s) exist, updates value(s). If key(s) don't exist, insert new key:value pair(s).

^|`values()`
|Returns a list of all the values in the dictionary. Returns most recent version, even if changes are made after variable assignment.

|===