=  `lxml`

== Introduction

https://lxml.de/[`lxml`] is a package used for processing XML in Python. To get started, simply import the package:

[source,python]
----
from lxml import etree
----

If you want to load XML from a string, do the following:

[source,python]
----
my_string = f"""<html>
    <head>
        <title>My Title</title>
    </head>
    <body>
        <div>
            <div class="abc123 sktoe-sldjkt dkjfg3-dlgsk">
                <div class="glkjr-slkd dkgj-0 dklfgj-00">
                    <a class="slkdg43lk dlks" href="https://example.com/123456">
                    </a>
                </div>
            </div>
            <div>
                <div class="ldskfg4">
                    <span class="slktjoe" aria-label="123 comments, 43 Retweets, 4000 likes">Love it.</span>
                </div>
            </div>
            <div data-amount="12">13</div>
        </div>
        <div>
            <div class="abc123 sktoe-sls dkjfg-dlgsk">
                <div class="glkj-slkd dkgj-0 dklfj-00">
                    <a class="slkd3lk dls" href="https://example.com/123456">
                    </a>
                </div>
            </div>
            <div>
                <div class="ldg4">
                    <span class="sktjoe" aria-label="1000 comments, 455 Retweets, 40000 likes">Love it.</span>
                </div>
            </div>
            <div data-amount="122">133</div>
        </div>
    </body>
</html>"""
tree = etree.fromstring(my_string)
----

If you don't want all of this code in your file, you can put this string into a .xml file and parse it as follows:

[source,python]
----
tree = etree.parse("example.xml")
----

Most of the time, you'll be working with .xml files that already exist and this is the common format you'll see. From there, you can use https://the-examples-book.com/book/data/xml#xpath-expressions[XPath Expressions] to parse the dataset.

[CAUTION]
====
`lxml` is largely just the facilitator for the XPath expressions you'll be writing, as those expressions will be doing the heavy lifting. Reading this page alone will _not_ magically make you a scraping professional -- read the XPath guides!
====

{sp}+

=== Examples

==== How do I load a webpage I scraped using `requests` into an `lxml` tree?

==== How do I get the name of the root node from my `lxml` tree called `tree`?

==== If the root node is named "html", how do I get the name of all nested tags?

==== How do I get the attributes of an element?

==== How do I get the div elements with attribute "data-amount"?

==== How do I get the div elements where data-amount is greater than 50?

==== How do I get the values of the span tags?


