= pytest

== Overview

While not part of the Python standard library like xref:book:python:unittest.adoc[`unittest`], `pytest` is in many ways the faster, simpler, and user-friendly alternative to `unittest`. `unittest` requires a lot of boilerplate code to set a test suite up, including a module, class, and test methods inside said class. There is a significantly larger learning curve and more concepts to understand in order to properly utilize `unittest`. 

`pytest` on the other hand, is extremely straightforward to use, and there are very few concepts that need to be understood in order to take advantage.

Let's say we have a function that accepts _n_ digits and returns the product of all of the numbers. 

.mymodule.py
[source,python]
----
import functools

def product(*numbers: float) -> float:
    return functools.reduce(lambda x, y: x*y, numbers)
----

Now, using `unittest`, we would first need to create a module as follows.

.test_mymodule.py
[source,python]
----
import unittest
import mymodule

class TestMyModule(unittest.TestCase):

    def test_product(self):
        result = mymodule.product(1, 2, 3)
        self.assertEqual(result, 6)

if __name__ == '__main__':
    unittest.main()
----

To use the `test_mymodule.py` module to actually test `mymodule.py`, we would need to run the following command.

[source,bash]
----
python -m unittest test_mymodule
----

.unittest results
----
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
----

To better visualize the difference, the equivalent functionality is much more straightforward using `pytest`.

.test_mymodule.py
[source,python]
----
import mymodule 

def test_product():
    result = mymodule.product(1, 2, 3)
    assert result==6
----

Then, to run the tests.

[source,bash]
----
python -m pytest test_mymodule.py
----

.pytest results
----
=========================================== test session starts ===========================================
platform darwin -- Python 3.9.2, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /Users/kamstut
plugins: anyio-2.2.0
collected 1 item                                                                                          

test_mymodule.py .                                                                                  [100%]

============================================ 1 passed in 0.01s ============================================
----

As you can see, `pytest` involves less boilerplate code. `pytest` is easier to use and run. The results of `pytest` are easier to read, _and_ `pytest` is faster.

== Resources

https://realpython.com/pytest-python-testing/[Effective Python Testing with Pytest]

An excellent an extensive guide to using `pytest` to test your Python code from https://realpython.com.