= STAT 29000: Project 9 -- Fall 2020

**Motivation:** Structured Query Language (SQL) is a language used for querying and manipulating data in a database. SQL can handle much larger amounts of data than R and Python can alone. SQL is incredibly powerful. In fact, https://www.cloudflare.com/[cloudflare], a billion dollar company, had much of its starting infrastructure built on top of a Postgresql database (per https://news.ycombinator.com/item?id=22878136[this thread on hackernews]). Learning SQL is _well_ worth your time!

**Context:** There are a multitude of RDBMSs (relational database management systems). Among the most popular are: MySQL, MariaDB, Postgresql, and SQLite. As we've spent much of this semester in the terminal, we will start in the terminal using SQLite. 

**Scope:** SQL, sqlite

.Learning objectives
****
- Explain the advantages and disadvantages of using a database over a tool like a spreadsheet.
- Describe basic database concepts like: rdbms, tables, indexes, fields, query, clause.
- Basic clauses: select, order by, limit, desc, asc, count, where, from, etc.
****

== Dataset

The following questions will use the dataset found in Scholar:

`/class/datamine/data/lahman/lahman.db`

This is the Lahman Baseball Database. You can find its documentation http://www.seanlahman.com/files/database/readme2017.txt[here], including the definitions of the tables and columns.

== Questions

[IMPORTANT]
====
Please make sure to **double check** that the your submission does indeed contain the files you think it does. You can do this by downloading your submission from Gradescope after uploading. If you can see all of your files and they open up properly on your computer, you should be good to go. 
====

[IMPORTANT]
====
Please make sure to look at your knit PDF *before* submitting. PDFs should be relatively short and not contain huge amounts of printed data. Remember you can use functions like `head` to print a sample of the data or output. Extremely large PDFs will be subject to lose points.
====

[IMPORTANT]
====
For this project all solutions should be done using SQL code chunks. To connect to the database, copy and paste the following before your solutions in your .Rmd
====

````markdown
```{r, include=F}`r ''`
library(RSQLite)
lahman <- dbConnect(RSQLite::SQLite(), "/class/datamine/data/lahman/lahman.db")
```
````

Each solution should then be placed in a code chunk like this:

````markdown
```{sql, connection=lahman}`r ''`
SELECT * FROM batting LIMIT 1;
```
````

If you want to use a SQLite-specific function like `.tables` (or prefer to test things in the Terminal), you will need to use the Terminal to connect to the database and run queries. To do so, you can connect to RStudio Server at https://rstudio.scholar.rcac.purdue.edu, and navigate to the terminal. In the terminal execute the command:

[source,bash]
----
sqlite3 /class/datamine/data/lahman/lahman.db
----

From there, the SQLite-specific commands will function properly. They will _not_ function properly in an SQL code chunk. To display the SQLite-specific commands in a code chunk without running the code, use a code chunk with the option `eval=F` like this:

````markdown
```{sql, connection=lahman, eval=F}`r ''`
SELECT * FROM batting LIMIT 1;
```
````

This will allow the code to be displayed without throwing an error.

=== Question 1

Connect to RStudio Server https://rstudio.scholar.rcac.purdue.edu, and navigate to the terminal and access the Lahman database. How many tables are available?

[TIP]
====
To connect to the database, do the following:
====

```{bash, eval=F}
sqlite3 /class/datamine/data/lahman/lahman.db
```

[TIP]
====
https://database.guide/2-ways-to-list-tables-in-sqlite-database/[This] is a good resource.
====

.Items to submit
====
- How many tables are available in the Lahman database?
- The sqlite3 commands used to figure out how many tables are available.
====

=== Question 2

Some people like to try to https://www.washingtonpost.com/graphics/2017/sports/how-many-mlb-parks-have-you-visited/[visit all 30 MLB ballparks] in their lifetime.  Use SQL commands to get a list of `parks` and the cities they're located in. For your final answer, limit the output to 10 records/rows.

[NOTE]
====
There may be more than 30 parks in your result, this is ok. For long results, you can limit the number of printed results using the `LIMIT` clause.
====

[TIP]
====
Make sure you take a look at the column names and get familiar with the data tables. If working from the Terminal, to see the header row as a part of each query result, run the following:

[source,SQL]
----
.headers on
----
====

.Items to submit
====
- SQL code used to solve the problem.
- The first 10 results of the query. 
====

=== Question 3

There is nothing more exciting to witness than a home run hit by a batter. It's impressive if a player hits more than 40 in a season. Find the hitters who have hit 60 or more home runs (`HR`) in a season. List their `playerID`, `yearID`, home run total, and the `teamID` they played for.

[TIP]
====
There are 8 occurrences of home runs greater than or equal to 60.
====

[TIP]
====
The `batting` table is where you should look for this question.
====

.Items to submit
====
- SQL code used to solve the problem.
- The first 10 results of the query. 
====

=== Question 4

Make a list of players born on your birth day (don't worry about the year). Display their first names, last names, and birth year. Order the list descending by their birth year.

[TIP]
====
The `people` table is where you should look for this question.
====

[NOTE]
====
Examples that utilize the relevant topics in this problem can be found xref:programming-languages:SQL:queries.adoc[here].
====

.Items to submit
====
- SQL code used to solve the problem.
- The first 10 results of the query. 
====

=== Question 5

Get the Cleveland (CLE) Pitching Roster from the 2016 season (`playerID`, `W`, `L`, `SO`). Order the pitchers by number of Strikeouts (SO) in descending order.

[TIP]
====
The `pitching` table is where you should look for this question.
====

[NOTE]
====
Examples that utilize the relevant topics in this problem can be found xref:programming-languages:SQL:queries.adoc[here].
====

.Items to submit
====
- SQL code used to solve the problem.
- The first 10 results of the query.
====

=== Question 6

Find the 10 team and year pairs that have the most number of Errors (`E`) between 1960 and 1970. Display their Win and Loss counts too. What is the name of the team that appears in 3rd place in the ranking of the team and year pairs?

[TIP]
====
The `teams` table is where you should look for this question.
====

[TIP]
====
The `BETWEEN` clause is useful here.
====

[TIP]
====
It is OK to use multiple queries to answer the question.
====

[NOTE]
====
Examples that utilize the relevant topics in this problem can be found xref:programming-languages:SQL:queries.adoc[here].
====

.Items to submit
====
- SQL code used to solve the problem.
- The first 10 results of the query.
====

=== Question 7

Find the `playerID` for Bob Lemon. What year and team was he on when he got the most wins as a pitcher (use table `pitching`)? What year and team did he win the most games as a manager (use table `managers`)?

[TIP]
====
It is OK to use multiple queries to answer the question.
====

[NOTE]
====
There was a tie among the two years in which Bob Lemon had the most wins as a pitcher.
====

[NOTE]
====
Examples that utilize the relevant topics in this problem can be found xref:programming-languages:SQL:queries.adoc[here].
====

.Items to submit
====
- SQL code used to solve the problem.
- The first 10 results of the query.
====