= Think Summer: Day 3 Notes -- 2022

Loading the R `data.table` library and loading the data from the 2005 airline data set

[source,R]
----
%%R
library(data.table)
----

[source,R]
----
%%R
myDF <- fread("/anvil/projects/tdm/data/flights/subset/2005.csv")
----

These are the first few lines of the 2005 airline data set

[source,R]
----
%%R
head(myDF)
----

There are 7 million rows and 29 columns

[source,R]
----
%%R
dim(myDF)
----

The first few flights are departing from Boston or O'Hare

[source,R]
----
%%R
head(myDF$Origin)
----

The first few flights are arriving at Boston or O'Hare

[source,R]
----
%%R
head(myDF$Dest)
----

The last few flights are departing and arriving as follows:

[source,R]
----
%%R
tail(myDF$Origin)
----

[source,R]
----
%%R
tail(myDF$Dest)
----

We can use `n=50` to get the destinations of the first 50 flights and the destinations of the last 50 flights.

[source,R]
----
%%R
head(myDF$Dest, n=50)
----

[source,R]
----
%%R
tail(myDF$Dest, n=50)
----

If we find out how many times an airplane departed from each airport, we get these counts:

[source,R]
----
%%R
head(table(myDF$Origin), n=10)
----

Now we can sort those counts, in descending order (i.e., with the largest ones given first), and display the largest such 10 counts.

[source,R]
----
%%R
head(sort(table(myDF$Origin), decreasing=T), n=10)
----

Now we can display how many flights departed from each of the 10 most popular airports.

[source,R]
----
%%R
dotchart(head(sort(table(myDF$Origin), decreasing=T), n=10))
----

We can extract the number of flights from specific airports, by looking the data up by the airports as indices.  Note that we are only selecting from the 10 most popular airports here.

[source,R]
----
%%R
head(sort(table(myDF$Origin), decreasing=T), n=10)[c("ATL","CVG","ORD")]
----

Here is another example, in which we extract the number of flights from airports which may or may not be among the most popular 10 airports.

[source,R]
----
%%R
sort(table(myDF$Origin), decreasing=T)[c("EWR","IND","JFK","ORD")]
----

We can paste together the first 300 origin airports and the first 300 destination airports.

[source,R]
----
%%R
paste(head(myDF$Origin, n=300), head(myDF$Dest, n=300), sep="-")
----

Then we can tabulate how many times each such flight path was flown.

[source,R]
----
%%R
table(paste(head(myDF$Origin, n=300), head(myDF$Dest, n=300), sep="-"))
----

Now that this works, we can remove the heads on each of those data sets.  Then we can tabulate the number of times that every flight path was used, and sort those results, and finally we can display the 6 most popular flight paths overall.

[source,R]
----
%%R
head(sort(table(paste(myDF$Origin, myDF$Dest, sep="-")), decreasing=T))
----

These are the airline carriers for the first 6 flights.

[source,R]
----
%%R
head(myDF$UniqueCarrier)
----

We can see how many flights were flown with each carrier.

[source,R]
----
%%R
sort(table(myDF$UniqueCarrier), decreasing=T)
----

The overall average departure delay, across all flights, is 8.67 minutes:

[source,R]
----
%%R
mean(myDF$DepDelay, na.rm=T)
----

We can just restrict attention to the average departure delay for flights departing from `IND` or from `JFK`.

[source,R]
----
%%R
mean(myDF$DepDelay[myDF$Origin=="IND"], na.rm=T)
----

[source,R]
----
%%R
mean(myDF$DepDelay[myDF$Origin=="JFK"], na.rm=T)
----

The first 6 department delays for flights from Boston or flights from Indianapolis are:

[source,R]
----
%%R
mean(myDF$DepDelay[myDF$Origin=="JFK"], na.rm=T)
----

[source,R]
----
%%R
head(myDF$DepDelay[myDF$Origin == "IND"])
----

Now we switch gears and load the donation data from federal election campaigns in 2000.  This data is described here:
https://www.fec.gov/campaign-finance-data/contributions-individuals-file-description/[Contributions by individuals file description]

[source,R]
----
%%R
myDF <- fread("/anvil/projects/tdm/data/election/itcont2000.txt")
----

The first several rows of election data are:

[source,R]
----
%%R
head(myDF)
----

There are 1.6 million rows and 21 columns

[source,R]
----
%%R
dim(myDF)
----

Altogether, there were 1.8 billion dollars in contributions

[source,R]
----
%%R
sum(myDF$TRANSACTION_AMT)
----

The largest number of contributions (regardless of the size of the contributions) were made by residents of `CA`, `NY`, `TX`, etc.

[source,R]
----
%%R
sort(table(myDF$STATE), decreasing=T)
----

We can paste the first 6 cities and the first 6 states together, using the `paste` function:

[source,R]
----
%%R
head(myDF$CITY)
----

[source,R]
----
%%R
head(myDF$STATE)
----

[source,R]
----
paste(head(myDF$CITY), head(myDF$STATE)
----

Then we can tabulate how many times those 6 city-state pairs occur, and sort the results, and display the head.

[source,R]
----
%%R
head(sort(table(paste(head(myDF$CITY), head(myDF$STATE))), decreasing=T))
----

Now that this works for the first 6 city-state pairs, we can do this again for the entire data set.  We see that the most donations were made from some typically large cities.  There are also a lot of donations from unknown locations.

[source,R]
----
%%R
head(sort(table(paste(myDF$CITY, myDF$STATE)), decreasing=T))
----

Here are the names of the people who made the largest number of contributions (regardless of the size of the contributions themselves)

[source,R]
----
%%R
head(sort(table(myDF$NAME), decreasing=T))
----

Now we can learn how to use the `tapply` function.

The `tapply` function takes three things, namely, some data, some groups to sort the data, and a function to run on the data.

For instance, we can take the data about the election transaction amounts, and split the data according the state where the donation was made, and sum the dollar amounts of those election donations within each state.

[source,R]
----
%%R
head(sort(tapply(myDF$TRANSACTION_AMT, myDF$STATE, sum), decreasing=T))
----

We can do something similar, now summing the amounts of the transactions in dollars, splitting the data according to the name of the donor:

[source,R]
----
%%R
head(sort(tapply(myDF$TRANSACTION_AMT, myDF$NAME, sum), decreasing=T), n=20)
----

Now we return to the airline data set from 2005:

[source,R]
----
%%R
myDF <- fread("/anvil/projects/tdm/data/flights/subset/2005.csv")
----

We can take an average of the departure delays, split according to the airline for the flights:

[source,R]
----
%%R
tapply( myDF$DepDelay, myDF$UniqueCarrier, mean, na.rm=T )
----

We can sum the distances of the flights according to the airports where the flights departed:

[source,R]
----
%%R
head(sort( tapply( myDF$Distance, myDF$Origin, sum ), decreasing=T ))
----

We can take an average of the arrival delays according to the destination where the flights landed.

[source,R]
----
%%R
head(sort( tapply( myDF$ArrDelay, myDF$Dest, mean, na.rm=T ), decreasing=T ))
----

== `LIKE` is a very powerful tool. You can read about SQLite's version of `LIKE` https://www.w3resource.com/sqlite/core-functions-like.php[here]. Use `LIKE` and/or R to get a count of how many movies (type='movie') that starts with each letter of the alphabet. Can you think of another way to do this? If so, show us, and explain what you did!

You can read more about https://www.w3resource.com/sqlite/core-functions-like.php[SQLite LIKE]

I used the `substr` function, which gets a substring from the string.  In this case, I used it to just get the first letter of the `primary_title`.

[source,sql]
----
%%sql
SELECT substr(primary_title,1,1), count(substr(primary_title,1,1)) FROM titles GROUP BY substr(primary_title,1,1) ORDER BY count(substr(primary_title,1,1)) DESC LIMIT 5;
----











Copied from previous Day 2 notes

=== Question 4

In <<question-3, question 3>>, we asked you to _kind of_ count how many unique genres there are in the database. In this question, we are going to dig in a little bit more, and use a combination of SQL and R to figure out the _actual_ number of unique genres in the database.

First, use a (slightly modified version of) the SQL query from question 3 to pull the data into an R data.frame. The result should be a data.frame with a single column named `genres` of length 2283 [CHECK THIS!]. You can access the column of a data.frame like so.

[source,r]
----
myDF <- dbGetQuery(conn, "<some query>")
genres <- myDF$genres
head(genres)
----

Our list, `genres`, contains strings with comma-separated values, which are the _actual_ genres. If you combine each of the comma-separated string values into one giant comma-separated string, you could then easily split the string into individual values. How many unique genres are there? 

[TIP]
You can use the following R functions to solve this problem: `unlist`, `strsplit`, and `unique`. 

[TIP]
====
Here is an example of splitting a string.

[source,r]
----
my_string <- "first;second;third"
result <- unlist(strsplit(my_string, ";"))
----
====

[CAUTION]
====
Before you answer the question, make sure all of the genres are _actually_ genres and not erroneous data!
====

**Relevant topics:** https://stackoverflow.com/questions/2098368/concatenate-a-vector-of-strings-character[paste]

.Items to submit
====
- All code used to solve this problem. _(3 pts)_
- A list of the unique genres. _(1 pt)_
- One sentence explaining _why_ using SQL was valuable in this instance (rather than just using R -- think speed). _(1 pt)_
====

[WARNING]
====
The following are challenge questions and are worth 0 points. If you get done early give them a try!
====

=== Question 5

In the previous question, we were able to get the number of unique genres. In this question, let's take this one step further. Use the `table` function in R to calculate how many times each genre appears in the database. 

[CAUTION]
====
You'll need to modify your query from question 3.
====

**Relevant topics:** https://thedatamine.github.io/the-examples-book/r.html#r-table[table]

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 6

In the previous question, we got a count of the number of times each genre appeared in the database. Create a dotchart illustrating this data.

[IMPORTANT]
====
Make sure to exclude the erroneous data!
====

**Relevant topics:** http://www.sthda.com/english/wiki/dot-charts-r-base-graphs[dotcharts]

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====


From 2020: Make a dotchart that shows how many movies premiered in each year since the year 2000.

Solutions from previous Day 2 notes:

== 4. Use a combination of SQL and R to figure out the actual number of unique genres in the database.

We need to run this at the start,
to load the R library for SQL, and to load the database.

[source,R]
----
%%R
library(RSQLite)
conn <- dbConnect(RSQLite::SQLite(), "/anvil/projects/tdm/data/movies_and_tv/imdb.db")
----

We focus on separating the genres into their individual genres.  Remember that they are combined, using commas, in the format that we originally have.  Here are the first few genres:

[source,R]
----
%%R
head(myDF$genres)
----

Now we split them according to the commas in each:

[source,R]
----
%%R
strsplit(head(myDF$genres), ",")
----

This will be new for many/most of you, but we can `unlist` them in R, so that they are not listed separately anymore, but instead, they are in one big vector.

[source,R]
----
%%R
unlist(strsplit(head(myDF$genres), ","))
----

and now we can use `unique` to see a list of the genres, removing any duplications:

[source,R]
----
%%R
unique(unlist(strsplit(head(myDF$genres), ",")))
----

Since this works on the `head`, we can remove the `head` now, and see the 29 such genres.  Notice that the 21st such genre is missing, i.e., it is empty, so we do not know the genres for some of the movies.  So there are 28 different genres altogether.

[source,R]
----
%%R
unique(unlist(strsplit(myDF$genres, ",")))
----

== 5. In the previous question, we were able to get the number of unique genres. In this question, let’s take this one step further. Use the `table` function in R to calculate how many times each genre appears in the database.

Instead of using the `unique` function (which gives us one copy of each entry), we can use the `table` function, to discover how many times that each genre appears.

[source,R]
----
%%R
table(unlist(strsplit(myDF$genres, ",")))
----

== 6. In the previous question, we got a count of the number of times each genre appeared in the database. Create a dotchart illustrating this data.

Instead of making a `table`, we can make a `dotchart`.

[source,R]
----
%%R
plot(table(unlist(strsplit(myDF$genres, ","))))
----

As we noted above, the last value was erroneous, so we can remove it.  A negative index will remove a value, so using -29 will remove the last value in the table.

[source,R]
----
%%R
plot(table(unlist(strsplit(myDF$genres, ",")))[-29])
----




