= Think Summer: Project 1 -- 2023

== Submission

Students need to submit the following file **by 10:00PM EST** through Gradescope inside Brightspace.

. A Jupyter notebook (a `.ipynb` file).

We've provided you with a template notebook for you to use. Please carefully read xref:summer-2023-project-template.adoc[this section] to get started.

[CAUTION]
====
When you are finished with the project, please make sure to run every cell in the notebook prior to submitting. To do this click menu:Run[Run All Cells]. Next, to export your notebook (your `.ipynb` file), click on menu:File[Download], and download your `.ipynb` file. 
====

== Questions

=== Question 1

How many people (from the people table) were born in each year?  In which year were the most people born?

.Items to submit
====
- SQL queries used to solve this problem. _(2 pts)_
- Output from running the SQL queries. _(1 pt)_
====

=== Question 2

How many episodes did the show Sopranos have?  Pick another TV show; how many episodes did this show have?

.Items to submit
====
- SQL queries used to solve this problem. _(2 pts)_
- Output from running the SQL queries. _(1 pt)_
====

=== Question 3

How many crews include George Lucas?  Pick your own favorite director, actor, or actress: How many crews include that person?

.Items to submit
====
- SQL queries used to solve this problem. _(2 pts)_
- Output from running the SQL queries. _(1 pt)_
====

=== Question 4

How many titles have 1 million or more ratings?  How many titles have 50,000 or fewer ratings?

.Items to submit
====
- SQL queries used to solve this problem. _(2 pts)_
- Output from running the SQL queries. _(1 pt)_
====

=== Question 5

In what year was the actress Gal Gadot born?  How about Mark Hamill?  How about your favorite actor or actress?

.Items to submit
====
- SQL queries used to solve this problem. _(2 pts)_
- Output from running the SQL queries. _(1 pt)_
====

