=== Question 1

How many actors have lived to be more than 115 years old? Find the names, birth years, and death years for all actors and actresses who lived more than 115 years.

[TIP]
====
Simple arithmetic can be done directly in a SQL predicate. For example, you can use the following.

[source, sql]
----
WHERE died - born > 115
----
====

[TIP]
====
Use the `people` table.
====

[CAUTION]
====
Remember **more than** 115 years implies 115 years doesn't qualify but 116 does.
====

**Relevant topics: **xref:book:SQL:introduction.adoc[SQL], xref:programming-languages:SQL:queries.adoc[queries]

.Items to submit
====
- SQL query used to solve this problem. _(1 pt)_
- Output from running the SQL query. _(0.5 pts)_
====

=== Question 2

Use the `ratings` table to discover how many films have a rating of at least 8 and at least 50000 votes.  In a separate cell, show 15 rows with this property.

**Relevant topics: **xref:programming-languages:SQL:introduction.adoc[SQL], xref:programming-languages:SQL:queries.adoc[queries]

.Items to submit
====
- SQL query used to solve this problem. _(1 pt)_
- Output from running the SQL query. _(0.5 pts)_
====

=== Question 3

In the `titles` table, the `genres` column specifies the genre of each movie. Use `COUNT` to find out how unique genres occur in the database. At this time, don't consider the fact that multiple `genres` could be listed in a single row. Any unique combination/permutation of genres should be considered a unique genre. Use the keyword `COUNT` in combination with `DISTINCT`. 

**Relevant topics:** xref:programming-languages:SQL:introduction.adoc[SQL], xref:programming-languages:SQL:queries.adoc[queries]

.Items to submit
====
- SQL query used to solve this problem. _(1 pt)_
- Output from running the SQL query. _(1 pt)_
====

=== Question 4

In <<question-3, question 3>>, we asked you to _kind of_ count how many unique genres there are in the database. In this question, we are going to dig in a little bit more, and use a combination of SQL and R to figure out the _actual_ number of unique genres in the database.

First, use a (slightly modified version of) the SQL query from question 3 to pull the data into an R data.frame. The result should be a data.frame with a single column named `genres` of length 2283 [CHECK THIS!]. You can access the column of a data.frame like so.

[source,r]
----
myDF <- dbGetQuery(conn, "<some query>")
genres <- myDF$genres
head(genres)
----

Our list, `genres`, contains strings with comma-separated values, which are the _actual_ genres. If you combine each of the comma-separated string values into one giant comma-separated string, you could then easily split the string into individual values. How many unique genres are there? 

[TIP]
You can use the following R functions to solve this problem: `unlist`, `strsplit`, and `unique`. 

[TIP]
====
Here is an example of splitting a string.

[source,r]
----
my_string <- "first;second;third"
result <- unlist(strsplit(my_string, ";"))
----
====

[CAUTION]
====
Before you answer the question, make sure all of the genres are _actually_ genres and not erroneous data!
====

**Relevant topics:** https://stackoverflow.com/questions/2098368/concatenate-a-vector-of-strings-character[paste]

.Items to submit
====
- All code used to solve this problem. _(3 pts)_
- A list of the unique genres. _(1 pt)_
- One sentence explaining _why_ using SQL was valuable in this instance (rather than just using R -- think speed). _(1 pt)_
====

[WARNING]
====
The following are challenge questions and are worth 0 points. If you get done early give them a try!
====

=== Question 5

In the previous question, we were able to get the number of unique genres. In this question, let's take this one step further. Use the `table` function in R to calculate how many times each genre appears in the database. 

[CAUTION]
====
You'll need to modify your query from question 3.
====

**Relevant topics:** https://thedatamine.github.io/the-examples-book/r.html#r-table[table]

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 6

In the previous question, we got a count of the number of times each genre appeared in the database. Create a dotchart illustrating this data.

[IMPORTANT]
====
Make sure to exclude the erroneous data!
====

**Relevant topics:** http://www.sthda.com/english/wiki/dot-charts-r-base-graphs[dotcharts]

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====


From 2020: Make a dotchart that shows how many movies premiered in each year since the year 2000.

