= Think Summer: Day 1 Notes -- 2023

== Loading the database

[source,sql]
----
%sql sqlite:////anvil/projects/tdm/data/movies_and_tv/imdb.db
----

== Extracting a few rows from the each of the 6 tables

[source,sql]
----
%%sql
SELECT * FROM titles LIMIT 5;
----

[source,sql]
----
%%sql
SELECT * FROM episodes LIMIT 5;
----

[source,sql]
----
%%sql
SELECT * FROM people LIMIT 5;
----

[source,sql]
----
%%sql
SELECT * FROM ratings LIMIT 5;
----

[source,sql]
----
%%sql
SELECT * FROM crew LIMIT 5;
----

[source,sql]
----
%%sql
SELECT * FROM akas LIMIT 5;
----

== We can see how many rows were in each table, as follows:

[source,sql]
----
%%sql
SELECT COUNT(*) FROM titles LIMIT 5;
----

[source,sql]
----
%%sql
SELECT COUNT(*) FROM episodes LIMIT 5;
----

[source,sql]
----
%%sql
SELECT COUNT(*) FROM people LIMIT 5;
----

== We can also start to investigate individual people, for instance:

[source,sql]
----
%%sql
SELECT * FROM people WHERE name = 'Ryan Reynolds' LIMIT 5;
----

[source,sql]
----
%%sql
SELECT * FROM people WHERE name = 'Hayden Christensen' LIMIT 5;
----

== Friends is one of Dr Ward's favorite shows.  We can find it here:

[source,sql]
----
%%sql
SELECT * FROM titles WHERE (primary_title = 'Friends') AND (premiered > 1992) LIMIT 5;
----

== We can investigate how many titles premiered in each year, by grouping things together according to the year that the title premiered, and by ordering the results according to the year that the title premiered.  The "desc" specifies that we want the results in descending order, i.e., with the largest result first (where "largest" means the "last year", because we are ordering by the years).

[source,sql]
----
%%sql
SELECT COUNT(*), premiered FROM titles
GROUP BY premiered ORDER BY premiered DESC LIMIT 20;
----

== The Family Guy premiered in 1999 and ended in 2022.

[source,sql]
----
%%sql
SELECT * FROM titles WHERE title_id = 'tt0182576' LIMIT 5;
----

== Tobey Maguire was born in 1975

[source,sql]
----
%%sql
SELECT * FROM people WHERE person_id = 'nm0001497' LIMIT 5;
----

== There are a total of 8064259 titles in the titles table.

[source,sql]
----
%%sql
SELECT COUNT(*) FROM titles LIMIT 5;
----

== These are the first 5 people in the people table.

[source,sql]
----
%%sql
SELECT * FROM people LIMIT 5;
----

== These are the first 5 episodes in the episodes table.

[source,sql]
----
%%sql
SELECT * FROM episodes LIMIT 5;
----

== These are the first 5 people in the crew table.

[source,sql]
----
%%sql
SELECT * FROM crew LIMIT 5;
----

== Only 3 movies have more than 2 million ratings

[source,sql]
----
%%sql
SELECT * FROM ratings WHERE votes > 2000000 LIMIT 5;
----

== Let's find how many people were born in each year (after 1850).  This is part of Question 1.

[source,sql]
----
%%sql
SELECT COUNT(*), born FROM people WHERE born > 1850 
GROUP BY born LIMIT 200;
----

== The Family Guy has 374 episodes.

[source,sql]
----
%%sql
SELECT COUNT(*) FROM episodes WHERE show_title_id = 'tt0182576' LIMIT 5;
----

== These are five of the films where George Lucas was on the crew.

[source,sql]
----
%%sql
SELECT * FROM crew WHERE person_id = 'nm0000184' LIMIT 5;
----



