== `LIKE` is a very powerful tool. You can read about SQLite's version of `LIKE` https://www.w3resource.com/sqlite/core-functions-like.php[here]. Use `LIKE` and/or R to get a count of how many movies (type='movie') that starts with each letter of the alphabet. Can you think of another way to do this? If so, show us, and explain what you did!

You can read more about https://www.w3resource.com/sqlite/core-functions-like.php[SQLite LIKE]

I used the `substr` function, which gets a substring from the string.  In this case, I used it to just get the first letter of the `primary_title`.

[source,sql]
----
%%sql
SELECT substr(primary_title,1,1), count(substr(primary_title,1,1)) FROM titles GROUP BY substr(primary_title,1,1) ORDER BY count(substr(primary_title,1,1)) DESC LIMIT 5;
----











Copied from previous Day 2 notes

=== Question 4

In <<question-3, question 3>>, we asked you to _kind of_ count how many unique genres there are in the database. In this question, we are going to dig in a little bit more, and use a combination of SQL and R to figure out the _actual_ number of unique genres in the database.

First, use a (slightly modified version of) the SQL query from question 3 to pull the data into an R data.frame. The result should be a data.frame with a single column named `genres` of length 2283 [CHECK THIS!]. You can access the column of a data.frame like so.

[source,r]
----
myDF <- dbGetQuery(conn, "<some query>")
genres <- myDF$genres
head(genres)
----

Our list, `genres`, contains strings with comma-separated values, which are the _actual_ genres. If you combine each of the comma-separated string values into one giant comma-separated string, you could then easily split the string into individual values. How many unique genres are there? 

[TIP]
You can use the following R functions to solve this problem: `unlist`, `strsplit`, and `unique`. 

[TIP]
====
Here is an example of splitting a string.

[source,r]
----
my_string <- "first;second;third"
result <- unlist(strsplit(my_string, ";"))
----
====

[CAUTION]
====
Before you answer the question, make sure all of the genres are _actually_ genres and not erroneous data!
====

**Relevant topics:** https://stackoverflow.com/questions/2098368/concatenate-a-vector-of-strings-character[paste]

.Items to submit
====
- All code used to solve this problem. _(3 pts)_
- A list of the unique genres. _(1 pt)_
- One sentence explaining _why_ using SQL was valuable in this instance (rather than just using R -- think speed). _(1 pt)_
====

[WARNING]
====
The following are challenge questions and are worth 0 points. If you get done early give them a try!
====

=== Question 5

In the previous question, we were able to get the number of unique genres. In this question, let's take this one step further. Use the `table` function in R to calculate how many times each genre appears in the database. 

[CAUTION]
====
You'll need to modify your query from question 3.
====

**Relevant topics:** https://thedatamine.github.io/the-examples-book/r.html#r-table[table]

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 6

In the previous question, we got a count of the number of times each genre appeared in the database. Create a dotchart illustrating this data.

[IMPORTANT]
====
Make sure to exclude the erroneous data!
====

**Relevant topics:** http://www.sthda.com/english/wiki/dot-charts-r-base-graphs[dotcharts]

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====


From 2020: Make a dotchart that shows how many movies premiered in each year since the year 2000.

Solutions from previous Day 2 notes:

== 4. Use a combination of SQL and R to figure out the actual number of unique genres in the database.

We need to run this at the start,
to load the R library for SQL, and to load the database.

[source,R]
----
%%R
library(RSQLite)
conn <- dbConnect(RSQLite::SQLite(), "/anvil/projects/tdm/data/movies_and_tv/imdb.db")
----

We focus on separating the genres into their individual genres.  Remember that they are combined, using commas, in the format that we originally have.  Here are the first few genres:

[source,R]
----
%%R
head(myDF$genres)
----

Now we split them according to the commas in each:

[source,R]
----
%%R
strsplit(head(myDF$genres), ",")
----

This will be new for many/most of you, but we can `unlist` them in R, so that they are not listed separately anymore, but instead, they are in one big vector.

[source,R]
----
%%R
unlist(strsplit(head(myDF$genres), ","))
----

and now we can use `unique` to see a list of the genres, removing any duplications:

[source,R]
----
%%R
unique(unlist(strsplit(head(myDF$genres), ",")))
----

Since this works on the `head`, we can remove the `head` now, and see the 29 such genres.  Notice that the 21st such genre is missing, i.e., it is empty, so we do not know the genres for some of the movies.  So there are 28 different genres altogether.

[source,R]
----
%%R
unique(unlist(strsplit(myDF$genres, ",")))
----

== 5. In the previous question, we were able to get the number of unique genres. In this question, let’s take this one step further. Use the `table` function in R to calculate how many times each genre appears in the database.

Instead of using the `unique` function (which gives us one copy of each entry), we can use the `table` function, to discover how many times that each genre appears.

[source,R]
----
%%R
table(unlist(strsplit(myDF$genres, ",")))
----

== 6. In the previous question, we got a count of the number of times each genre appeared in the database. Create a dotchart illustrating this data.

Instead of making a `table`, we can make a `dotchart`.

[source,R]
----
%%R
plot(table(unlist(strsplit(myDF$genres, ","))))
----

As we noted above, the last value was erroneous, so we can remove it.  A negative index will remove a value, so using -29 will remove the last value in the table.

[source,R]
----
%%R
plot(table(unlist(strsplit(myDF$genres, ",")))[-29])
----




