= Think Summer: Day 1 Notes -- 2023

== Loading the database

[source,sql]
----
%sql sqlite:////anvil/projects/tdm/data/movies_and_tv/imdb.db
----

== Extracting a few rows from the each of the 6 tables

[source,sql]
----
%%sql
SELECT * FROM titles LIMIT 5;
----

[source,sql]
----
%%sql
SELECT * FROM episodes LIMIT 5;
----

[source,sql]
----
%%sql
SELECT * FROM people LIMIT 5;
----

[source,sql]
----
%%sql
SELECT * FROM ratings LIMIT 5;
----

[source,sql]
----
%%sql
SELECT * FROM crew LIMIT 5;
----

[source,sql]
----
%%sql
SELECT * FROM akas LIMIT 5;
----

== We can see how many rows were in each table, as follows:

[source,sql]
----
%%sql
SELECT COUNT(*) FROM titles LIMIT 5;
----

[source,sql]
----
%%sql
SELECT COUNT(*) FROM episodes LIMIT 5;
----

[source,sql]
----
%%sql
SELECT COUNT(*) FROM people LIMIT 5;
----

== We can also start to investigate individual people, for instance:

[source,sql]
----
%%sql
SELECT * FROM people WHERE name = 'Ryan Reynolds' LIMIT 5;
----

[source,sql]
----
%%sql
SELECT * FROM people WHERE name = 'Hayden Christensen' LIMIT 5;
----

== Friends is one of Dr Ward's favorite shows.  We can find it here:

[source,sql]
----
%%sql
SELECT * FROM titles WHERE (primary_title = 'Friends') AND (premiered > 1992) LIMIT 5;
----

== We can investigate how many titles premiered in each year, by grouping things together according to the year that the title premiered, and by ordering the results according to the year that the title premiered.  The "desc" specifies that we want the results in descending order, i.e., with the largest result first (where "largest" means the "last year", because we are ordering by the years).

[source,sql]
----
%%sql
SELECT COUNT(*), premiered FROM titles
GROUP BY premiered ORDER BY premiered DESC LIMIT 20;
----

== The Family Guy premiered in 1999 and ended in 2022.

[source,sql]
----
%%sql
SELECT * FROM titles WHERE title_id = 'tt0182576' LIMIT 5;
----

== Tobey Maguire was born in 1975

[source,sql]
----
%%sql
SELECT * FROM people WHERE person_id = 'nm0001497' LIMIT 5;
----

== There are a total of 8064259 titles in the titles table.

[source,sql]
----
%%sql
SELECT COUNT(*) FROM titles LIMIT 5;
----

== These are the first 5 people in the people table.

[source,sql]
----
%%sql
SELECT * FROM people LIMIT 5;
----

== These are the first 5 episodes in the episodes table.

[source,sql]
----
%%sql
SELECT * FROM episodes LIMIT 5;
----

== These are the first 5 people in the crew table.

[source,sql]
----
%%sql
SELECT * FROM crew LIMIT 5;
----

== Only 3 movies have more than 2 million ratings

[source,sql]
----
%%sql
SELECT * FROM ratings WHERE votes > 2000000 LIMIT 5;
----

== Let's find how many people were born in each year (after 1850).  This is part of Question 1.

[source,sql]
----
%%sql
SELECT COUNT(*), born FROM people WHERE born > 1850 
GROUP BY born LIMIT 200;
----

== The Family Guy has 374 episodes.

[source,sql]
----
%%sql
SELECT COUNT(*) FROM episodes WHERE show_title_id = 'tt0182576' LIMIT 5;
----

== These are five of the films where George Lucas was on the crew.

[source,sql]
----
%%sql
SELECT * FROM crew WHERE person_id = 'nm0000184' LIMIT 5;
----

== Find and print the `title_id`, `rating`, and number of votes (`votes`) for all movies that received at least 2 million votes.
In a second query (and new cell), use the information you found in the previous query to identify the `primary_title` of these movies.

These are the movies with at least 2 million votes:

[source,sql]
----
%%sql
SELECT * FROM ratings WHERE votes >= 2000000 LIMIT 5;
----

and then we can lookup their titles:

[source,sql]
----
%%sql
SELECT * FROM titles WHERE title_id = 'tt0111161' OR title_id = 'tt0468569' OR title_id = 'tt1375666' LIMIT 5;
----

== Find the `primary_title` of every _movie_ that is over 2 hours long or that premiered after 1990. Order the result from newest premiered year to oldest, and limit the output to 15 movies. Make sure `premiered` and `runtime_minutes` are not `NULL`.  After displaying these 15 movies, run the query again in a second cell, but this time only display the number of such movies.

We just add the conditions to the query about the titles table.

[source,sql]
----
%%sql
SELECT * FROM titles WHERE (type == 'movie') AND (runtime_minutes IS NOT NULL) AND (premiered IS NOT NULL) AND ((runtime_minutes > 120) OR (premiered > 1990)) ORDER BY premiered DESC LIMIT 15;
----

Now we can find the total number of such movies, using the `COUNT`:

[source,sql]
----
%%sql
SELECT COUNT(*) FROM titles WHERE (type == 'movie') AND (runtime_minutes IS NOT NULL) AND (premiered IS NOT NULL) AND ((runtime_minutes > 120) OR (premiered > 1990)) ORDER BY premiered DESC LIMIT 15;
----

This can be a helpful time to mention the concept of https://stackoverflow.com/questions/45231487/order-of-operation-for-and-and-or-in-sql-server-queries[order of operations]

== What movie has the longest primary title? Answer this question using just SQL.

You can read more about https://www.w3resource.com/sqlite/core-functions-length.php[SQLite length]

We can use the `length` function, as follows:

[source,sql]
----
%%sql
SELECT *, length(primary_title) FROM titles ORDER BY length(primary_title) DESC LIMIT 5;
----

== What actor has the longest name? Answer this question using just SQL.

[source,sql]
----
%%sql
SELECT *, length(name) FROM people ORDER BY length(name) DESC LIMIT 5;
----

== `LIKE` is a very powerful tool. You can read about SQLite's version of `LIKE` https://www.w3resource.com/sqlite/core-functions-like.php[here]. Use `LIKE` and/or R to get a count of how many movies (type='movie') that starts with each letter of the alphabet. Can you think of another way to do this? If so, show us, and explain what you did!

You can read more about https://www.w3resource.com/sqlite/core-functions-like.php[SQLite LIKE]

I used the `substr` function, which gets a substring from the string.  In this case, I used it to just get the first letter of the `primary_title`.

[source,sql]
----
%%sql
SELECT substr(primary_title,1,1), count(substr(primary_title,1,1)) FROM titles GROUP BY substr(primary_title,1,1) ORDER BY count(substr(primary_title,1,1)) DESC LIMIT 5;
----







== We already mentioned that there are six tables in the database:  `akas`, `crew`, `episodes`, `people`, `ratings`, `titles`

Normally, when using SQLite, the easiest way to display the tables in the database is by running `.table` or `.tables`. This is SQLite-specific behavior and therefore cannot be used in our Jupyter Lab environment. Instead, to show the tables using an R cell, we can run the following.

[source, sql]
----
SELECT
    name
FROM
    sqlite_master
WHERE
    TYPE IN('table', 'view')
    AND name NOT LIKE 'sqlite_%'
ORDER BY
    1;
----

Once we learn to use R to connect to the database, if `conn` is a database connection, we can just use the `dbListTables` command, to do the same thing.

[source,r]
----
%%R
library(RSQLite)
conn <- dbConnect(RSQLite::SQLite(), "/anvil/projects/tdm/data/movies_and_tv/imdb.db")
dbListTables(conn)
----

We also have xref:programming-languages:SQL:introduction.adoc[some additional information about SQL] posted in our book pages.