= TDM 20100: Project 3 -- 2023

**Motivation:** The need to search files and datasets based on text is common during various parts of the data wrangling process.  As an example, `grep` is a powerful UNIX tool that allows you to search text using regular expressions. Regular expressions are a structured method for searching for specified patterns. Regular expressions can be very complicated.  https://blog.cloudflare.com/details-of-the-cloudflare-outage-on-july-2-2019/[(Even professionals can make critical mistakes.)]  With that being said, learning some of the basics will come in handy, regardless of the language in which you are using regular expressions.


[NOTE]
====
Regular expressions are not something you will be able to completely escape from. They exist in some way, shape, and form in all major programming languages. Even if you are less-interested in UNIX tools, you should definitely take the time to learn regular expressions.
====

**Context:** We've just begun to learn the basics of navigating a file system in UNIX using various terminal commands. Now we will go into more depth with one of the most useful command line tools, `grep`, and experiment with regular expressions using `grep`, R, and later on, Python.

**Scope:** `grep`, regular expression basics, utilizing regular expression tools in R and Python

.Learning Objectives
****
- Use `grep` to search for patterns within a dataset.
- Use `cut` to section off and slice up data from the command line.
- Use `wc` to count the number of lines of input.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the files in this directory:

- `/anvil/projects/tdm/data/consumer_complaints/`

and, in particular, several questions will focus on the data in this file:

- `/anvil/projects/tdm/data/consumer_complaints/processed.csv`


[NOTE]
====
`grep` stands for (g)lobally search for a (r)egular (e)xpression and (p)rint matching lines. As such, to best demonstrate `grep`, we will be using it with textual data.

Let's assume for a second that we _didn't_ provide you with the location of this projects dataset, and you didn't know the name of the file either. With all of that being said, you _do_ know that it is the only dataset with the text `"That's the sort of fraudy fraudulent fraud that Wells Fargo defrauds its fraud-victim customers with. Fraudulently."` in it. You may use 'grep' command to search for the dataset.  (Make sure that the single quotation mark in your quote is not a curly quote; you might have to manually re-type it.)

You can start in the `/anvil/projects/tdm/data` directory to reduce the amount of text being searched. In addition, use a wildcard (*) to reduce the directories we search to only directories that start with a `con` inside the `/anvil/projects/tdm/data` directory such as
[source,bash]
/anvil/projects/tdm/data/con*

Just know that you'd _eventually_ find the file without using the wildcard, but we don't want to waste your time.
====
[NOTE]
====
Use `man` to read about some of the options with `grep`. For example, you'll want to search _recursively_ through the entire contents of the directories starting with a `con` with option -R or -r.

[source, bash]

grep -Rin 'fraudy fraudulent fraud' /anvil/projects/tdm/data/con*

- R: This flag tells grep to search recursively, meaning it will traverse through the specified directory and all of its subdirectories, looking for the pattern in every file it encounters.
- i: This flag makes the search case-insensitive. So, "FRAUDY", "Fraudy", and "fraudy" would all match.
- n: With this flag, grep will also display the line numbers in the files where the matches are found.
- 'fraudy fraudulent fraud': This is the pattern grep is looking for. It will search for the exact phrase "fraudy fraudulent fraud" in files.
- /anvil/projects/tdm/data/con*: This is the path where grep should start its search. Specifically, it tells grep to look in the /anvil/projects/tdm/data/ directory and search in all files and directories starting with con.
====
[TIP]
====
When you search for this sentence in the file, make sure that you type the single quote in `"That's"` so that you get a regular ASCII single quote.  Otherwise, you will not find this sentence. Or, just use a unique _part_ of the sentence that will likely not exist in another file.
====

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_yj9xyllm&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++


=== Question 1 (1 pt)

[upperalpha]
.. Write a `grep` command that finds the dataset, which contains text "朝阳区" in all directories that start with `air` inside the `/anvil/projects/tdm/data` directory.  As with the example given above, you search should be case-insensitive, and your needs to display the line numbers for the location of the text.


=== Question 2 (1.5 pts)

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_zjg741ij&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++


[upperalpha]
.. Use the `head` command to print out the first line _only_ from the file `/anvil/projects/tdm/data/consumer_complaints/processed.csv`.
 
+

[TIP]
====
Using the `head` command, we can (in general) quickly print out the first _n_ lines of a file. A csv file typically has a header row to explain what data each column holds. 

[source, bash]

head -n numberoflines filename
====
//[arabic]
+
[start=b]

.. Print out first 5 lines from 3 columns, namely: `Date Received`, `Issue` and `Company response to consumer` from the file `/anvil/projects/tdm/data/consumer_complaints/processed.csv`
+
[TIP] 
====
Use the `cat` command to view all file contents, the `head` to control the row, and the `cut` command to select columns.

[source, bash]

cat filename | head -n rowNumbers | cut -d 'delimiterhere' -f field1,field2,...

====
//[arabic]
+
[start=c]
.. For the _single_ line where we heard about the `"That's the sort of fraudy fraudulent fraud"`, print out these 4 columns: `Date Received`, `Issue`, `Consumer complaint narrative`, and `Company response to consumer`.  (Make sure that the single quotation mark in your quote is not a curly quote; you might have to manually re-type it.)

[TIP]
====
Use `cat`, `head`, `tail`, and `cut` commands to isolate the 4 columns and the _single_ line
 
You can find the exact line from the file where the "fraudy fraudulent fraud" occurs, by using the `n` option from `grep`. That will tell you the line number, which can then be used with `head` and `tail` to isolate the single line.

[source, bash]

cat filename | grep 'patternhere' | cut -d 'delimiterhere' -f field1,field2,field3,field4
====


=== Question 3 (2 pts)

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_fpzaq6we&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_rnfpm1jj&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++

//[arabic]
[upperalpha]

.. From the file `/anvil/projects/tdm/data/consumer_complaints/processed.csv`, use a one line statement to create a _new_ dataset called `midwest.csv` that has the following requirments:

    * it will only contains the data for these five states: - Indiana (IN), Ohio (OH), Illinois (IL), Wisconsin (WI), and Michigan (MI)
    * it will only the contain these five columns: `Date Received`, `Issue`, `Consumer complaint narrative`, `Company response to consumer`, and `state`
+
[TIP]
====
- Be careful that you don't accidentally get lines with a word like "AGILE" in them (IL is the state code of Illinois and is present in the word "AGILE"). 
- Use '>' redirection operator to create the new file, e.g.,
[source, bash]
createthefile > midwest.csv

====
//[arabic]
[start=b]
.. Please describe how many rows of data are in the new file, and find the size of the new file in megabytes

[TIP] 
====
- Use `wc` to count rows
- Use `cut` to isolate _just_ the data we ask for. For example, _just_ print the number of rows, and _just_ print the value (in Mb) of the size of the file:

[source, bash]

cut -d 'delimiterhere' -f positionofrequestedfield
====

.output like this
----
520953
----

.output not like this
----
520953 /home/x-nzhou1/midwest.csv
----

=== Question 4 (1.5 pt)

//[arabic]
[upperalpha]
.. Use grep command to get information from the _new_ data set 'midwest.csv' to find the number of rows that contain one (or more) of the following words (the search is case-insensitive): "improper", "struggling", or "incorrect".
 

=== Question 5 (2 pts)

[upperalpha]
.. In the file `/anvil/projects/tdm/data/consumer_complaints/processed.csv`, which date appears the most in the `Date received` column?
.. In the file `/anvil/projects/tdm/data/consumer_complaints/processed.csv`, for each category of `Product`, how many times does that type product appear in the data set?

Project 03 Assignment Checklist
====
- Code used to solve question 1 to 5
- Output from running the code
- Copy the code and outputs to a new Python File  
    * `firstname-lastname-project03.ipynb`.
- Submit files through gradescope
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
                                                                                                                             
In addition, please review our xref:submissions.adoc[submission guidelines] before submitting your project.
====
