= file permissions

Each file has 9 permissions bits (either allowed not allowed):

The file owner can (or cannot) read, write, and execute the file

Users in the file's group can (or cannot) read, write, and execute the file

Other users can (or cannot) read, write, and execute the file

FIXTHIS see section 1.17 in Unix Power Tools

== Superuser / root user

Dr Ward and The Data Mine team and the students are all just regular users on Anvil.  None of us are superusers.  Itype.adocf you see (for instance, on the internet) instructions that require you to have superuser or root access, you will be unable to do this on Anvil.  (Dr Ward is unable to do such things either!)  Only our colleagues in Research Computing have superuser access.  So if you see, for instance, instructions to type `su` or `sudo` or `root` or anything like that, you will be unable to perform those commands.  You would need to ask for someone in The Data Mine to make a request on your behalf, if you need something installed, if it required superuser or root access.



