= The Examples Book
:description: Supplementary material for solving projects assigned in Purdue University's The Data Mine.
:sectanchors:
:url-repo: https://github.com/TheDataMine/the-examples-book

== Overview

Welcome to The Examples Book! This book contains a collection of information and examples that can be used to reinforce topics learned in https://datamine.purdue.edu[The Data Mine] seminar at https://purdue.edu[Purdue University]. The Examples Book is open to anyone! Even if you aren't a student at Purdue we hope you find helpful content here. 

This book is broken down into "core" topics. These topics are listed in the options below. They range from getting started with data science to information for the corporate partners who want to sponsor a project with us. 

In addition, the live version of the "core" book contains the most up-to-date slate of projects students in The Data Mine are working on. All projects from previous semesters live in the xref:projects:ROOT:introduction.adoc[Projects Archive] appendix and are open to the public.

[TIP]
====
Where to go for specific topics:

* Question about predictive models, data analysis, or visualization? Check out `Data Science`.
* Need to know more about containers or research computing? Check out `Data Engineering`. 
* Learning R or Python. `Programming Languages` might be helpful. 
* Want more info on The Data Mine, corporate partners projects, or student course resources? Check out `Corporate Partners`.
* Looking to see the projects that we use to build experience? Read through the `Course Links`.
* Have a different questions or want to add to The Examples Book? `Helpful Links` is the place for you. 
====

== Core Topics

xref:data-science:intro-to-ds:introduction.adoc[[.custom_button]#Data Science#]
xref:data-engineering:intro-to-data-engineering:introduction.adoc[[.custom_button]#Data Engineering#]
xref:crp:ROOT:introduction.adoc[[.custom_button]#Corporate Partners#]

== Course links

xref:book:projects:19000-s2022-projects.adoc[[.custom_button]#STAT 19000#]
xref:book:projects:29000-s2022-projects.adoc[[.custom_button]#STAT 29000#]
xref:book:projects:39000-s2022-projects.adoc[[.custom_button]#STAT 39000#]
xref:projects:ROOT:introduction.adoc[[.custom_button]#Projects#]

== Workshops and Trainings

xref:book:gallygoogle:introduction.adoc[[.custom_button]#Gallaudet Workshop#]
xref:think-summer:ROOT:introduction.adoc[[.custom_button]#Think Summer#]

== Helpful Links

xref:book:FAQs:faqs.adoc[[.custom_button]#FAQ#]
xref:book:ROOT:how-to-contribute.adoc[[.custom_button]#How to Contribute#]
xref:book:contributors:contributors.adoc[[.custom_button]#Contributors#]
