= The Examples Book
:description: Supplementary material for solving projects assigned in Purdue University's The Data Mine.
:sectanchors:
:url-repo: https://github.com/TheDataMine/the-examples-book

== Overview

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_i7x6tz4r?wid=_983291"></iframe>
++++

This book contains a collection of examples that students can use to reinforce topics learned in https://datamine.purdue.edu[The Data Mine] seminar at https://purdue.edu[Purdue University]. It is an excellent resource for students to learn what they need to know in order to solve The Data Mine projects.

This book is broken down into "core" topics that are covered in seminar. These topics are listed in the left-hand side menu. They include topics like Python, R, SQL, and other critical languages and tools used to solve data-driven problems. In addition, the live version of the "core" book contains the most up-to-date slate of projects students in The Data Mine are working on. All projects from previous semesters live in the xref:projects:ROOT:introduction.adoc[Projects Archive] appendix.

xref:data-science:intro-to-ds:introduction.adoc[[.custom_button]#Data Science#]
[.custom_button]#xref:crp:ROOT:introduction.adoc[Corporate Partners]#
[.custom_button]#xref:projects:ROOT:introduction.adoc[Projects Archive]#

[.custom_button]#xref:rcac:ROOT:introduction.adoc[RCAC]#
[.custom_button]#xref:k8s:ROOT:introduction.adoc[Kubernetes]#
[.custom_button]#xref:think-summer:ROOT:introduction.adoc[Think Summer]#

== Course links

The following links are useful for accessing the course materials like the syllabus, office hours schedule, videos, projects, and more.

[.custom_button]#xref:book:projects:19000-s2022-projects.adoc[STAT 19000]#
[.custom_button]#xref:book:projects:29000-s2022-projects.adoc[STAT 29000]#
[.custom_button]#xref:book:projects:39000-s2022-projects.adoc[STAT 39000]#
