= Introduction to Power BI
:toc:
:toclevels: 3


== What Is Power BI?

Power BI is Microsoft’s interactive data visualization and business intelligence platform.  

It allows you to:

* Connect to a wide range of data sources  
* Clean, transform, and model datasets  
* Build interactive dashboards and reports  
* Share visualizations with your team or organization  

Power BI is widely used across industry, making it an essential tool for data analysts, data scientists, and anyone working with dashboards.

== Power BI in The Data Mine

Students in The Data Mine frequently use Power BI to:

* Explore and clean corporate partner datasets  
* Build dashboards for presentations  
* Publish insights to a shared workspace  
* Collaborate with team members in the cloud  
* Create reproducible and visually compelling analytics outputs  

All Purdue students have access to Power BI through their Purdue credentials. If you are not a Purdue student, you can email datamine-help@purdue.edu for more information. 

== How Students Can Log In

Refer to the examples book page on login instructions here:

https://the-examples-book.com/tools/powerbi/PowerBI-Access

This page includes detailed steps.

== Logging into Power BI at the Data Mine (Tutorial)

++++
<iframe id="kaltura_player" src='https://cdnapisec.kaltura.com/p/983291/embedPlaykitJs/uiconf_id/56090002?iframeembed=true&amp;entry_id=1_lvg15iry&amp;config%5Bprovider%5D=%7B%22widgetId%22%3A%221_1uv6ttxg%22%7D&amp;config%5Bplayback%5D=%7B%22startTime%22%3A0%7D'  style="width: 860px;height: 540px;border: 0;" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" title="Getting Started with Power BI at the Data Mine"></iframe>
++++

This demo will show you how to access Power BI and connect your data to a dashboard when your data is stored in Anvil. This method is especially important for students with MacBooks, since MacBooks cannot run Power BI Desktop.



== Making Visualizations in Power BI

++++
<iframe id="kaltura_player" src='https://cdnapisec.kaltura.com/p/983291/embedPlaykitJs/uiconf_id/56090002?iframeembed=true&amp;entry_id=1_3w3nixyj&amp;config%5Bprovider%5D=%7B%22widgetId%22%3A%221_v3j2nmme%22%7D&amp;config%5Bplayback%5D=%7B%22startTime%22%3A0%7D'  style="width: 860px;height: 540px;border: 0;" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" title="Data Mine Power BI Demo CMS Data"></iframe>
++++

This demonstration will introduce you to the process of creating visualizations in Power BI using an example dataset. It provides a high-level overview of how to begin building graphics, including how to import data, create slicers, and develop basic visual elements such as bar charts and maps.

It is important to note that Power BI is a an analytical tool that cannot be fully learned in a short session. Numerous resources are available through Microsoft and other online training platforms for those who wish to learn more. Ultimately, the most effective way to learn Power BI is through hands-on practice. As you work with the tool, you will naturally discover the features you need and learn how to apply them to accomplish your analytical goals.

== Commonly Asked Questions


*“Why are we learning this method of accessing Power BI if we have a windows computer?”*

Students without MacBooks sometimes wonder why they also need to use this method. The reason is because it demonstrates how to securely import data stored in Anvil into Power BI.  Even if you do not use a MacBook, this method teaches you how to **securely load data from Anvil into Power BI**. Anvil is The Data Mine’s commonly used secure file storage environment, and many Corporate Partner projects store their datasets there. This workflow ensures that your data is imported correctly and securely into Power BI—regardless of your device or operating system.


**What if my project is not using Anvil, but we are using Power BI?**

While not every Corporate Partner project in The Data Mine uses Anvil for file storage, most projects do. If your project does not use Anvil but still requires Power BI, and you are unsure how to access or load your data, you can submit a ticket to **datamine-help@purdue.edu** for guidance.

**Do I need to launch Power BI in Anvil Desktop?**

Power BI can be accessed in multiple ways, including:

- Through the cloud (Power BI Service)
- Through the desktop application (Power BI Desktop)

Students often get confused by these different options. The key idea to remember is that your data must stay secure, and you must import it using an approved, secure method. Both methods work. 


== Working in a Shared Workspace and Collaboration

++++
<iframe id="kaltura_player" src='https://cdnapisec.kaltura.com/p/983291/embedPlaykitJs/uiconf_id/56090002?iframeembed=true&amp;entry_id=1_blaojynx&amp;config%5Bprovider%5D=%7B%22widgetId%22%3A%221_aj0l2n02%22%7D&amp;config%5Bplayback%5D=%7B%22startTime%22%3A0%7D'  style="width: 860px;height: 540px;border: 0;" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" title="Power BI Service and Power BI Workspace"></iframe>
++++


The Data Mine data science team will create a shared Power BI workspace for your group after you submit a ticket and request one. To do this, email datamine-help@purdue.edu with corporate partner project name, and the names of teammates who need access.

After your workspace has been created:
. Go to https://app.powerbi.com/ and sign in with your Purdue credentials.

. Click Workspaces on the left panel.
. Find your corporate partner’s workspace 
. Open the workspace to view dashboards, reports, datasets, and notebooks.
. Students can upload or publish dashboards directly into the shared workspace to collaborate with their teammates.
If you have questions about setting up or using a shared workspace for your project, please email datamine-help@purdue.edu.


== Helpful Tips for Students

* Save your work frequently in the desktop app (if using Power BI Desktop).  
* When collaborating in the cloud, upload your `.pbix` file to the workspace.  
* Use consistent naming conventions for pages, bookmarks, and visuals.  
* Before presentations, review whether your data is refreshed and your visuals are aligned.  
* Always verify that you are working in the correct workspace and you are not overwriting other student's changes.

== Additional Resources

* Purdue Power BI Access Guide:  
  https://the-examples-book.com/tools/powerbi/PowerBI-Access  
* Official Power BI Documentation:  
  https://learn.microsoft.com/power-bi/  
* Power BI Desktop Download (optional for windows users):  
  https://www.microsoft.com/power-bi/downloads  

