= Seminar TA Training

== Welcome to The Data Mine Seminar Course!

Course content lives within The Projects appendix of The Example Book (the pages you are reading right now). We have migrated away from hosting our content in Brightspace to make our content publicly accessible as we expand. 

Teaching Assistants (TAs) will use Gradescope to submit their training. Students will also continue to use link:https://www.gradescope.com/[Gradescope] as the submission portal for projects and outside events.  

[NOTE]
====
FERPA certifications must be submitted to Gradescope with a visible expiration date each semester. 
Training quizzes are only required in the Fall for continuing TAs.
====

== TA Responsibility Overview

TAs are a key part of success in The Data Mine. Your constant support in seminars, grading, and office hours keeps the courses running smoothly. 

Navigate to the xref:fall2022/ta_schedule.adoc[Seminar TA Fall 2022 Schedule] to find due dates for training, grading, and time sheets.

== Set Up ACCESS account
We are very excited for you to be working with us as TAs this year!
 
During this year working with us, we will be using Purdue’s Anvil computing cluster.
 
**IMPORTANT** To make sure you are ready to go on the first day please complete ALL of the steps described here; it only takes a few minutes:
https://the-examples-book.com/data-science/data-engineering/rcac/access-setup

== Training
Training is required for all TAs. You will be added to a Gradescope class to submit your training. 
All module quizzes are due in Gradescope *August 17, 2022, at 11:59 PM.* 
[IMPORTANT]
====
TAs can NOT work without their FERPA certification.
====

=== Module 1
Navigate to link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module1[Training Module 1] then complete the reading and quiz in link:https://www.gradescope.com[Gradescope]. 

=== Module 2
Navigate to link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module2[Training Module 2] then complete the reading and quiz in Gradescope. 
    
COMPLETE your FERPA TRAINING and submit proof in Gradescope. You can not work as a TA without a FERPA certification!

=== Module 3.1
Navigate to link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module3_1_diversity[Training Module 3.1] then complete the reading and quiz in Gradescope.

=== How to Get Paid
Navigate to link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module4_4_time_sheets[Training Module 4.4]. Seminar TAs will not have to complete time sheet justification, but are required to submit their hours to link:https://one.purdue.edu/launch-task/all/successfactors-employee?roles=[SuccessFactor] by *Sunday evenings at 11:59 PM.* 

=== Office Hours 
TAs will choose their office hour times and will be expected to hold their scheduled office hours consistently in person.
Please see the list of required office hours to know how many hours you're required to hold. This was sent out to the TAs.

[NOTE]
====
Attending seminar counts towards your required office hours.
====

For the first 3 weeks of the semester, we need a few T.A.s (at least one for 19000 and one for 29000) in each of the seminar times and in the hour after each seminar. We definitely need lots of help on Thursday and Friday. Evenings are much appreciated because we have students all over the world who will need help. Friday evenings are prime time, and we may permit more than one TA working at a time then.

Please keep track of how many students come to each of your office hours during the first 3 weeks of the semester. We will reshuffle a bit based on popular times after the first 3 weeks.

[NOTE]
====
**Office hours _during_ seminar:** Hillenbrand C141 -- the atrium inside the dining court +
**Office hours _outside_ of seminar, before 5:00 PM EST:** Hillenbrand Lobby C100 -- the lobby between the 2 sets of front entrances +
**Office hours _after_ 5:00 PM EST:** Online in Webex +
**Office hours on the _weekend_:** Online in Webex
====

==== Set up your Office Hours
In addition to in person office hours, you will set up a Webex to assist NDMN students. 
Use your personal Webex room to hold your office hours. Go to https://purdue.webex.com/ and log in with your Purdue credentials. You do not need to schedule a meeting for your office hours, just list your personal Webex room. For example, First_name Last_name personal Webex room is: https://purdue.webex.com/join/Last_name/.

==== Choose your time
When choosing your office hour time slot(s), please consider your own schedule and conflicts such as classes. 

Use the link sent in the Welcome Email to select your office hour time and add your Webex link to the spreadsheet. 

=== Grading
TAs will be grading student submissions through Gradescope. 
Below are example videos by Gradescope. 

[NOTE]
====
All information in these videos is for example purposes only. They are not Data Mine students or assignments. 
====

==== Student View: Viewing Feedback and Requesting Regrades
++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/TOHCkI12mh0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

==== Managing Regrade Requests
++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/jpre3UxF1i0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

==== Grading a Simple Question
[NOTE]
====
If rubric items are already set in an assignment, please, do NOT change them.
Do NOT delete rubric items as it will alter all other submissions with that item selected.
====
++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/12ySmTBH3pY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

==== Grading Even Faster with Short Cuts
++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/VMM16gdREfg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

=== Additional Quizzes and Requirements

1. Complete the Syllabus and Academic Integrity Quizzes in Gradescope.  
2. Join Piazza [*Link will be added here at a later date*]
3. Confirm you're a part of the TA Teams Group Chat. 

Please send any questions to your head TA, Seminar TA group chat, or email datamine-help@purdue.edu. 

We look forward to working with you this semester! 