= STAT 19000: Project 1 -- Fall 2020

**Motivation:** In this project we are going to jump head first into The Data Mine. We will load datasets into the R environment, and introduce some core programming concepts like variables, vectors, types, etc. As we will be "living" primarily in an IDE called RStudio, we will take some time to learn how to connect to it, configure it, and run code.

**Context:** This is our first project as a part of The Data Mine. We will get situated, configure the environment we will be using throughout our time with The Data Mine, and jump straight into working with data!

**Scope:** r, rstudio, Scholar

.Learning Objectives
****
- Use Jupyter Notebook to run Python code and create Markdown text.
- Use RStudio to run Python code and compile your final PDF.
- Gain exposure to Python control flow and reading external data.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset

The following questions will use the dataset found in Scholar:

`/class/datamine/data/open_food_facts/openfoodfacts.tsv`

== Questions

=== Question 1

Navigate to https://notebook.scholar.rcac.purdue.edu/ and sign in with your Purdue credentials (_without_ BoilerKey). This is an instance of Jupyter Notebook. The main screen will show a series of files and folders that are in your `$HOME` directory. Create a new notebook by clicking on menu:New[f2020-s2021].

Change the name of your notebook to "LASTNAME_FIRSTNAME_project01" where "LASTNAME" is your family name, and "FIRSTNAME" is your given name. Try to export your notebook (using the menu:[File] dropdown menu, choosing the option menu:[Download as]), what format options (for example, `.pdf`) are available to you?

[NOTE]
`f2020-s2021` is the name of our course notebook kernel. A notebook kernel is an engine that runs code in a notebook. ipython kernels run Python code. `f2020-s2021` is an ipython kernel that we've created for our course Python environment, which contains a variety of compatible, pre-installed packages for you to use. When you select `f2020-s2021` as your kernel, all of the packages in our course environment are automatically made available to you.

https://mediaspace.itap.purdue.edu/id/1_4g2lwx5g[Click here for video]

.Items to submit
====
- A list of export format options.
====

=== Question 2

Each "box" in a Jupyter Notebook is called a _cell_. There are two primary types of cells: code, and markdown. By default, a cell will be a code cell. Place the following Python code inside the first cell, and run the cell. What is the output?

[source,python]
----
from thedatamine import hello_datamine
hello_datamine()
----

[TIP]
You can run the code in the currently selected cell by using the GUI (the buttons), as well as by pressing kbd:[Ctrl+Enter] or kbd:[Ctrl+Return].

.Items to submit
====
- Output from running the provided code.
====

=== Question 3

Jupyter Notebooks allow you to easily pull up documentation, similar to `?function` in R. To do so, use the `help` function, like this: `help(my_function)`. What is the output from running the help function on `hello_datamine`? Can you modify the code from question (2) to print a customized message? Create a new _markdown_ cell and explain what you did to the code from question (2) to make the message customized.

[IMPORTANT]
====
Some Jupyter-only methods to do this are:

- Click on the function of interest and type `Shift+Tab` or `Shift+Tab+Tab`.
- Run `function?`, for example, `print?`.
====

[IMPORTANT]
You can also see the source code of a function in a Jupyter Notebook by typing `function??`, for example, `print??`.

.Items to submit
====
- Output from running the `help` function on `hello_datamine`.
- Modified code from question (2) that prints a customized message.
====

=== Question 4

At this point in time, you've now got the basics of running Python code in Jupyter Notebooks. There is really not a whole lot more to it. For this class, however, we will continue to create RMarkdown documents in addition to the compiled PDFs. You are welcome to use Jupyter Notebooks for personal projects or for testing things out, however, we will still require an RMarkdown file (.Rmd), PDF (generated from the RMarkdown file), and .py file (containing your python code). For example, please move your solutions from Questions 1, 2, 3 from Jupyter Notebooks over to RMarkdown (we discuss RMarkdown below). Let's learn how to run Python code chunks in RMarkdown.

Sign in to https://rstudio.scholar.rcac.purdue.edu (_with_ BoilerKey). Projects in The Data Mine should all be submitted using our template found https://raw.githubusercontent.com/TheDataMine/the-examples-book/master/files/project_template.Rmd[here] or on Scholar (`/class/datamine/apps/templates/project_template.Rmd`).

Open the project template and save it into your home directory, in a new RMarkdown file named `project01.Rmd`. Prior to running any Python code, run `datamine_py()` in the R console, just like you did at the beginning of every project from the first semester.

Code chunks are parts of the RMarkdown file that contains code. You can identify what type of code a code chunk contains by looking at the _engine_ in the curly braces "{" and "}". As you can see, it is possible to mix and match different languages just by changing the engine. Move the solutions for questions 1-3 to your `project01.Rmd`. Make sure to place all Python code in `python` code chunks. Run the `python` code chunks to ensure you get the same results as you got when running the Python code in a Jupyter Notebook.

[NOTE]
Make sure to run `datamine_py()` in the R console prior to attempting to run any Python code.

[TIP]
The end result of the `project01.Rmd` should look _similar_ to https://raw.githubusercontent.com/TheDataMine/the-examples-book/master/files/example02.Rmd[this].

https://mediaspace.itap.purdue.edu/id/1_nhkygxg9[Click here for video]

https://mediaspace.itap.purdue.edu/id/1_tdz3wmim[Click here for video]

.Items to submit
====
- `project01.Rmd` with the solutions from questions 1-3 (including any Python code in `python` code chunks).
====

=== Question 5

It is not a Data Mine project without data! [Here] are some examples of reading in data line by line using the `csv` package. How many columns are in the following dataset: `/class/datamine/data/open_food_facts/openfoodfacts.tsv`? Print the first row, the number of columns, and then exit the loop after the first iteration using the `break` keyword.

[TIP]
You can get the number of elements in a list by using the `len` method. For example: `len(my_list)`.

[TIP]
You can use the `break` keyword to exit a loop. As soon as `break` is executed, the loop is exited and the code immediately following the loop is run.

[source,python]
----
for my_row in my_csv_reader:
    print(my_row)
    break
print("Exited loop as soon as 'break' was run.")
----

[TIP]
`'\t'` represents a tab in Python.

https://mediaspace.itap.purdue.edu/id/1_ck74xlzq[Click here for video]

[IMPORTANT]
If you get a Dtype warning, feel free to just ignore it.

Relevant topics:* [for loops], [break], [print]

.Items to submit
====
- Python code used to solve this problem.
- The first row printed, and the number of columns printed.
====

=== Question 6 (optional)

Unlike in R, where many of the tools you need are built-in (`read.csv`, data.frames, etc.), in Python, you will need to rely on packages like `numpy` and `pandas` to do the bulk of your data science work.

In R it would be really easy to find the mean of the 151st column, `caffeine_100g`:

[source,r]
----
myDF <- read.csv("/class/datamine/data/open_food_facts/openfoodfacts.tsv", sep="\t", quote="")
mean(myDF$caffeine_100g, na.rm=T) # 2.075503
----

If you were to try to modify our loop from question (5) to do the same thing, you will run into a myriad of issues, just to try and get the mean of a column. Luckily, it is easy to do using `pandas`:

[source,python]
----
import pandas as pd
myDF = pd.read_csv("/class/datamine/data/open_food_facts/openfoodfacts.tsv", sep="\t")
myDF["caffeine_100g"].mean() # 2.0755028571428573
----

Take a look at some of the methods you can perform using pandas https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#computations-descriptive-stats[here]. Perform an interesting calculation in R, and replicate your work using `pandas`. Which did you prefer, Python or R?

https://mediaspace.itap.purdue.edu/id/1_ybx1iukd[Click here for video]

.Items to submit
====
- R code used to solve the problem.
- Python code used to solve the problem.
====
