= STAT 29000

== Project links

[NOTE]
====
Only the best 10 of 14 projects will count towards your grade.
====

[CAUTION]
====
Topics are subject to change. While this is a rough sketch of the project topics, we may adjust the topics as the semester progresses.
====

* xref:29000-s2022-project01.adoc[Project 1: Introduction to XML]
* xref:29000-s2022-project02.adoc[Project 2: Web scraping in Python: part I]
* xref:29000-s2022-project03.adoc[Project 3: Web scraping in Python: part II]
* xref:29000-s2022-project04.adoc[Project 4: Web scraping in Python: part III]
* xref:29000-s2022-project05.adoc[Project 5: Web scraping in Python: part IV]
* xref:29000-s2022-project06.adoc[Project 6: Plotting in Python: part I]
* xref:29000-s2022-project07.adoc[Project 7: Plotting in Python: part II]
* xref:29000-s2022-project08.adoc[Project 8: Writing Python scripts: part I]
* xref:29000-s2022-project09.adoc[Project 9: Writing Python scripts: part II]
* xref:29000-s2022-project10.adoc[Project 10: Plotting with ggplot: part I]
* xref:29000-s2022-project11.adoc[Project 11: Plotting with ggplot: part II]
* xref:29000-s2022-project12.adoc[Project 12: Tidyverse and data.table: part I]
* xref:29000-s2022-project13.adoc[Project 13: Tidyverse and data.table: part II]
* xref:29000-s2022-project14.adoc[Project 14: Tidyverse and data.table: part III]

[WARNING]
====
Projects are **released on Thursdays**, and are due 1 week and 1 day later on the following **Friday, by 11:55pm**. Late work is **not** accepted. We give partial credit for work you have completed -- **always** submit the work you have completed before the due date. If you do _not_ submit the work you were able to get done, we will _not_ be able to give you credit for the work you were able to complete.

**Always** double check that the work that you submitted was uploaded properly. After submitting your project in Gradescope, you will be able to download the project to verify that the content you submitted is what the graders will see. You will **not** get credit for or be able to re-submit your work if you accidentally uploaded the wrong project, or anything else. It is your responsibility to ensure that you are uploading the correct content.

Each week, we will announce in Piazza that a project is officially released. Some projects, or parts of projects may be released in advance of the official release date. **Work on projects ahead of time at your own risk.**  These projects are subject to change until the official release announcement in Piazza.
====

== Piazza

=== Sign up

https://piazza.com/purdue/fall2021/stat29000[https://piazza.com/purdue/fall2021/stat29000]

=== Link

https://piazza.com/purdue/fall2021/stat29000/home[https://piazza.com/purdue/fall2021/stat29000/home]

== Syllabus

See xref:book:projects:s2022-syllabus.adoc[here].
