= STAT 29000: Project 6 -- Fall 2021

== The anatomy of a bash script

**Motivation:** A bash script is a powerful tool to perform repeated tasks. RCAC uses bash scripts to automate a variety of tasks. In fact, we use bash scripts on Scholar to do things like link Python kernels to your account, fix potential isues with Firefox, etc. `awk` is a programming language designed for text processing. The combination of these tools can be really powerful and useful for a variety of quick tasks. 

**Context:** This is the first part in a series of projects that are designed to exercise skills around UNIX utilities, with a focus on writing bash scripts and `awk`. You will get the opportunity to manipulate data without leaving the terminal. At first it may seem overwhelming, however, with just a little practice you will be able to accomplish data wrangling tasks really efficiently.

**Scope:** awk, bash scripts, UNIX utilities

.Learning Objectives
****
- Use awk to process and manipulate textual data.
- Use piping and redirection within the terminal to pass around data between utilities.
- Write bash scripts to automate potential repeated tasks. 
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- `/depot/datamine/data/iowa_liquor_sales/iowa_liquor_sales_cleaner.csv`
- `/depot/datamine/data/election/*`

== Questions

=== Question 1

We now have a grip on a variety of useful tools, that are often used together using pipes and redirections. As you start to see, "one-liners" can start to become a bit unwieldy. In these cases, wrapping everything into a bash script can be a good solution.

Imagine for a minute, that you have a single file that is continually appended to by another system. Let's say this file is `/depot/datamine/data/election/itcont1990.txt`. Every so often, your manager asks you to generate a summary of the data in this file. Every time you do this, you have to dig through old notes to remember how you did this previously. Instead of constantly doing this manual process, you decide to write a script to handle this for you!

Write a bash script to generate a summary of the data in `/depot/datamine/data/election/itcont1990.txt`. The summary should include the following information, in the following format.

....
155 RECORDS READ
----------------
File: /depot/datamine/data/election/itcont1990.txt
Largest doner: ASARO, SALVATORE
Most common doner state: NY
Total donations in USD by state:
- NY: 100000
- CA: 50000
...
----------------
....

[NOTE]
====
For this question, assume that the data file will _always_ be in the same location.
====

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 2

Your manager loves your script, but wants you to modify it so it works with any file formatted the same way. A new system is being installed that saves new data into new files rather than appending to the same file.

Modify the script from question (1) to accept an argument that specifies the file to process. Test the updated script out on `/depot/datamine/data/election/itcont2000.txt`.

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 3

Modify your script once again to accept _n_ arguments, each a path to another file to generate a summary for. You should be able to run the script as follows.

[source,bash]
----
./my_script.sh /depot/datamine/data/election/itcont2000.txt /depot/datamine/data/election/itcont1990.txt
----

....
155 RECORDS READ
----------------
File: /depot/datamine/data/election/itcont1990.txt
Largest donor: ASARO, SALVATORE
Most common donor state: NY
Total donations in USD by state:
- NY: 100000
- CA: 50000
...
----------------

120 RECORDS READ
----------------
File: /depot/datamine/data/election/itcont2000.txt
Largest donor: ASARO, SALVATORE
Most common donor state: NY
Total donations in USD by state:
- NY: 100000
- CA: 50000
...
----------------
....

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 4

You are _particularly_ interested in donors from your alma mater, https://purdue.edu[Purdue University]. Modify your script from question (3) yet again. This time, add a flag, that, when present, will include the name and amount for each donor where the word "purdue" (case insensitive) is present in the `EMPLOYER` column.

[source,bash]
----
./my_script -p /depot/datamine/data/election/itcont2000.txt /depot/datamine/data/election/itcont1990.txt
----

....
155 RECORDS READ
----------------
File: /depot/datamine/data/election/itcont1990.txt
Largest donor: ASARO, SALVATORE
Most common donor state: NY
Purdue donors:
- John Smith: 500
- Alice Bob: 1000
Total donations in USD by state:
- NY: 100000
- CA: 50000
...
----------------

120 RECORDS READ
----------------
File: /depot/datamine/data/election/itcont2000.txt
Largest donor: ASARO, SALVATORE
Most common donor state: NY
Purdue donors:
- John Smith: 500
- Alice Bob: 1000
Total donations in USD by state:
- NY: 100000
- CA: 50000
...
----------------
....

[TIP]
====
https://stackoverflow.com/a/29754866[This] stackoverflow response has an excellent template using `getopt` to parse your flags. Use this as a "start".
====

[TIP]
====
You may want to comment out or delete the part of the template that limits your non-flag arguments to one.
====

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 5

Your manager liked that new feature, however, she thinks the tool would be better suited to search the `EMPLOYER` column for a specific string, and then handle this generically, rather than just handling the specific case of Purdue.

Modify your script from question (4). Accept one and only one flag `-e` or `--employer`. This flag should take a string as an argument, and then search the `EMPLOYER` column for that string. Then, the script will print out the results. Only include the top 5 doners from an employer. The following is an example if we chose to search for "ford".

[source,bash]
----
./my_script -e'ford' /depot/datamine/data/election/itcont2000.txt /depot/datamine/data/election/itcont1990.txt
----

....
155 RECORDS READ
----------------
File: /depot/datamine/data/election/itcont1990.txt
Largest donor: ASARO, SALVATORE
Most common donor state: NY
ford donors:
- John Smith: 500
- Alice Bob: 1000
Total donations in USD by state:
- NY: 100000
- CA: 50000
...
----------------

120 RECORDS READ
----------------
File: /depot/datamine/data/election/itcont2000.txt
Largest donor: ASARO, SALVATORE
Most common donor state: NY
ford donors:
- John Smith: 500
- Alice Bob: 1000
Total donations in USD by state:
- NY: 100000
- CA: 50000
...
----------------
....

Modify the script to accept a flag, `-p`, that will search the `EMPLOYER` column for a specific string, and then handle this generically.

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
====