= STAT 29000: Project 5 -- Fall 2021

**Motivation:** A bash script is a powerful tool to perform repeated tasks. RCAC uses bash scripts to automate a variety of tasks. In fact, we use bash scripts on Scholar to do things like link Python kernels to your account, fix potential issues with Firefox, etc. `awk` is a programming language designed for text processing. The combination of these tools can be really powerful and useful for a variety of quick tasks. 

**Context:** This is the first part in a series of projects that are designed to exercise skills around UNIX utilities, with a focus on writing bash scripts and `awk`. You will get the opportunity to manipulate data without leaving the terminal. At first it may seem overwhelming, however, with just a little practice you will be able to accomplish data wrangling tasks really efficiently.

**Scope:** awk, UNIX utilities, bash scripts

.Learning Objectives
****
- Use awk to process and manipulate textual data.
- Use piping and redirection within the terminal to pass around data between utilities.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

- `/depot/datamine/data/iowa_liquor_sales/iowa_liquor_sales_cleaner.csv`

== Questions

=== Question 1

While the UNIX tools we've used up to this point are very useful, `awk` enables many new capabilities, and can even replace major functionality of other tools.

In a previous question, we asked you to write a command that printed the number of columns in the dataset. Perform the same operation using `awk`.

Similarly, we've used `head` to print the header line. Use `awk` to do the same.

Similarly, we've used `wc` to count the number of lines in the dataset. Use `awk` to do the same.

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 2

In a previous question, we used `sort` in combination with `uniq` to find the stores with the most number of sales. 

Use `awk` to find the 10 stores with the most number of sales. In a previous solution, our output was minimal -- we had a count and a store number. This time, take some time to format the output nicely, _and_ use the store number to find the count (not store name).

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 3

Calculate the total number of sales (in USD) for each month, by county. Do this using any UNIX commands you have available. Then, do this using _only_ `awk`.

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 4

Use `awk` and piping to create a new dataset with the following columns, for every store, by month:

- `lat`: latitude
- `lon`: longitude
- `store_name`: store name
- `volume_sold`: total volume sold
- `sold_usd`: total amount sold in USD

Call the new dataset `sales_by_store.csv`.

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 5

Believe it or not, `awk` even supports geometric calculations like `sin` and `cos`. Write a bash script that, given a pair of latitude and pair of longitude, calculates the distance between the two points.

Use UNIX utilities to use this bash script to calculate the distance between each pair of stores provided to the script.

Pass 4 rows from your `sales_by_store.csv` dataset to the script. Output the results to a file called `my_results.csv`.

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 6 (optional, 0pts)

Use your choice of Python or R to create a beautiful graphic mapping the latitudes and longitudes of the stores. If you want to, get creative and increase the size of the points on the map based on the number of sales. Get creative!

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
====