= STAT 29000: Project 6 -- Fall 2021

**Motivation:** A bash script is a powerful tool to perform repeated tasks. RCAC uses bash scripts to automate a variety of tasks. In fact, we use bash scripts on Scholar to do things like link Python kernels to your account, fix potential issues with Firefox, etc. `awk` is a programming language designed for text processing. The combination of these tools can be really powerful and useful for a variety of quick tasks.  

**Context:** This is the second project in a series of projects focused on bash _and_ `awk`. Here, we take a deeper dive and create some more complicated awk scripts, as well as utilize the bash skills learned in previous projects.

**Scope:** bash, `awk`, bash scripts

.Learning Objectives
****
- Use awk to process and manipulate textual data.
- Use piping and redirection within the terminal to pass around data between utilities. 
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

`/depot/datamine/data/`

== Questions

=== Question 1

In project (5), we created a new dataset called `sales_by_month.csv` with the number of sales in USD, and volume of liquor sold (in liters) for each month of the year.

You may have noticed that the "Store Location" column contains latitude and longitude coordinates. That is some rich data that could be fun and useful.

Use `awk` to print out the latitude and longitude for each line in the original dataset. Output should resemble the following.

----
lat,lon
1.23,4.56
----

[TIP]
====
split and gsub will be useful `awk` functions to use for this quesiton.
====

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 2

Redo question (4) from project (5), but this time add 2 additional columns to the dataset -- `lat` and `lon`.

- 'lat': latitude
- 'lon': longitude

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 3

Believe it or not, `awk` even supports geometric calculations like `sin` and `cos`. Write a bash script that, given a pair of latitude and pair of longitude, calculates the distance between the two points.

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 4

Adapt your bash script from question (3) to accept _n_ rows from your updated `sales_by_month.csv` dataset.

For each pair of rows, calculate the distance between the two points. Behavior should resemble the following.

[source, bash]
----
./my_script.sh sales_by_month.csv 3
----

----
loc1,loc2,distance
storename1,storename2,5.5
storename1,storename3,4.5
storename2,storename2,6.5
----

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 5

Use your choice of Python or R, with our `sales_by_month.csv` to create a beautiful graphic mapping the latitudes and longitudes of the stores. If you want to, get creative and increase the size of the points on the map based on the number of sales. You could create a graphic for each month to see how sales change month-to-month. The options are limitless, get creative!

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
====