= STAT 29000: Project 6 -- Fall 2021

**Motivation:** 

**Context:** 

**Scope:** 

.Learning Objectives
****
- 
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].

== Dataset(s)

The following questions will use the following dataset(s):

`/depot/datamine/data/`

== Questions

=== Question 1



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 2



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 3



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 4



.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 5

Expand upon the previous question by adding the columns:

- 'lat': latitude
- 'lon': longitude

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====


=== Question 6

Believe it or not, `awk` even supports geometric calculations like `sin` and `cos`. Write a bash script that, given a pair of latitude and pair of longitude, calculates the distance between the two points.

Use UNIX utilities to use this bash script to calculate the distance between each pair of stores provided to the script.

Pass 4 rows from your `sales_by_store.csv` dataset to the script. Output the results to a file called `my_results.csv`.

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====

=== Question 7 (optional, 0pts)

Use your choice of Python or R to create a beautiful graphic mapping the latitudes and longitudes of the stores. If you want to, get creative and increase the size of the points on the map based on the number of sales. Get creative!

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
====


[WARNING]
====
_Please_ make sure to double check that your submission is complete, and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted, was what you _actually_ submitted.
====