= Templates

Our course project template can be found link:{attachmentsdir}/project_template.ipynb[here], or on Scholar:

`/depot/datamine/apps/templates/project_template.Rmd`

Students in STAT 19000, 29000, 39000, and 49000 are to use and modify this as a template as needed, for all project submissions. This template is a starting point for all projects.

Most of the time, this template will be used with the f2021-s2022 kernel. By default, this kernel runs Python code. To run other types of code, see below. Any format or template related questions should be asked in Piazza.

== Running `R` code using the `f2021-s2022` kernel

. First, load the `rpy2.ipython` extension.
+
[source,ipython]
----
%load_ext rpy2.ipython
----
+
. Next, to run R code, in a new cell, run the following.
+
[source,ipython]
----
%%R

my_vec <- c(1,2,3)
my_vec
----

As you can see, any cell that begins with `%%R` will run the R code in that cell. If a cell does not begin with `%%R`, it will be assumed that the code is Python code, and run accordingly.

== Running SQL queries using the `f2021-s2022` kernel

. First, load the sql extension.
+
[source,ipython]
----
%load_ext sql
----
+
. Next, you need to establish a connection with the database. If this is a sqlite database, you can use the following command.
+
[source,ipython]
----
%sql sqlite:///my_db.db
# or
%sql sqlite:////home/class/datamine/path/to/my_db.db
----
+
Otherwise, if this is a mysql database, you can use the following command.
+
[source,ipython]
----
%sql mariadb+pymysql://username:password@my_url.com/my_database
----
+
. Next, to run SQL queries, in a new cell, run the following.
+
[source,ipython]
----
%%sql

SELECT * FROM my_table;
----

As you can see, any cell that begins with `%%sql` will run the SQL query in that cell. If a cell does not begin with `%%sql`, it will be assumed that the code is Python code, and run accordingly.

== Running `bash` code using the `f2021-s2022` kernel

To run `bash` code, in a new cell, run the following.

[source,bash]
----
%%bash

ls -la
----

As you can see, any cell that begins with `%%bash` will run the `bash` code in that cell. If a cell does not begin with `%%bash`, it will be assumed that the code is Python code, and run accordingly.

[TIP]
====
Code cells that start with `%` or `%%` are sometimes referred to as magic cells. To see a list of available magics, run `%lsmagic` in a cell.
====