= Templates

Our course project template can be found link:{attachmentsdir}/project_template.ipynb[here], or on Scholar:

`/depot/datamine/apps/templates/project_template.Rmd`

Students in STAT 19000, 29000, 39000, and 49000 are to use and modify this as a template as needed, for all project submissions. This template is a starting point for all projects.

Most of the time, this template will be used with the f2021-s2022 kernel. By default, this kernel runs Python code. To run R code using this kernel, run the following in a new cell:

[source,ipython]
----
%load_ext rpy2.ipython
----

Then, to run R code, in a new cell, run:

[source,ipython]
----
%%R

my_vec <- c(1,2,3)
my_vec
----

To run SQL queries using this kernel, first, load the extension:

[source,ipython]
----
%load_ext sql
----

Next, you need to establish a connection with the database. If this is a sqlite database, you can use the following command:

[source,ipython]
----
%sql sqlite:///my_db.db
# or
%sql sqlite:////home/class/datamine/path/to/my_db.db
----

If this is a mysql database, you can use the following command:

[source,ipython]
----
%sql mariadb+pymysql://username:password@my_url.com/my_database
----

Then, to run SQL queries in a new cell, run:

[source,ipython]
----
%%sql

SELECT * FROM my_table;
----

Any format or template related questions should be asked in Piazza.