= TDM 19000: More Image Processing

The image screenshot:

/anvil/projects/tdm/data/images/seq_000014.jpg

is from a shopping mall security camera video clip. There are some people scattered throughout the scene. The camera footage is not particularly clear.  The computer will still recognize (most of) these figures as people when we go to classify the objects in the image. 

=== YOLO

Object detection is a computer vision technique in image processing that is used to identify, label, and locate specific objects from within images or videos. This method uses bounding boxes to show what items it has detected, and labels them accordingly. This is commonly done with cars, people, or animals in many different contexts. 

One of the faster approaches to perform object detection is through YOLO. We added some notes about YOLO for you here:  https://the-examples-book.com/projects/summer2026/19000/introductiontoyolo

We also want to introduce you to SAM and to masks, and use it to further our work on the image processing:  https://the-examples-book.com/projects/summer2026/19000/introductiontosam

Now that we know how to make masks, we want to make the masks systematically:  https://the-examples-book.com/projects/summer2026/19000/systematicmasks

We can also remove objects from an image, either one object at a time:

https://the-examples-book.com/projects/summer2026/19000/removingoneobject

or systematically removing multiple objects all at once:

https://the-examples-book.com/projects/summer2026/19000/removingmultipleobjects


