= TDM 19000: Running and Changing the Ollama Model

== Running the Ollama Model

Assuming that you setup a model called `llama3.2-2` at the end of the instructions for setting up Ollama:  https://the-examples-book.com/projects/summer2026/19000/settingupollama

You can now run the following in terminal window:

[source,Bash]
----
/anvil/projects/tdm/bin/ollama run llama3.2-2
----

 Now you should be able to send the LLM a test prompt in the Terminal. Enter a message to begin working with the LLM. 

Some starter ideas include:

- "Why is the sky blue?"
- "Tell me a joke about cats"
- "What is 7 * 8?"
- "What are the names of [singer's name] albums?"

The response it gives you depends on the prompt you send it, and how you have configured the model. 

The thread count is part of what determines the quality of the model's responses. 

[NOTE]
====
To exit the currently active model, type '/bye' in the message prompt.
====

== Testing the Ollama Model

One way of testing model quality is to measure how long it is running to write a response. 

Adjusting the cores will vary the speed, accuracy, and quality of your model and its responses. Currently, we are working with 2 threads. Make versions of llama3.2 that use 4 and 1 threads, respectively. 

[source,Python]
----
%%bash
cat > ~/mymodel << HERE
FROM llama3.2
# we used 2 threads before
# now test with 1, then 4
PARAMETER num_thread ___ 
HERE

# create the models from a `mymodel` file using 1 and 4 threads, respectively (run in terminal):
# fill in [thread_count] with (for instance) 1 or 2 or 4, depending on how many threads that you want to use in your test
# /anvil/projects/tdm/bin/ollama create llama3.2-[thread_count] -f ~/mymodel
----

Run this in your terminal to test how thread count (1, 2, and 4) changes the output you are recieving:

[source,Bash]
----
time /anvil/projects/tdm/bin/ollama run llama3.2-[thread count] "Explain why the sky appears blue during the day and red during sunrise and sunset. Write about 200 words."
----  

There is hopefully a very noticable time difference between running the model on 1 thread vs 2. This may be more subtle when comparing 2 cores to more (such as testing with 4 or 8 threads). The ideal number of threads tends to be around 1/2 as many cores as your server is running on - since we are using 4 cores, you should continue using 2 threads. 

