= TDM 19000: Setting Up Ollama

To begin working with Ollama, we first need to make a https://en.wikipedia.org/wiki/Symbolic_link[symbolic link] to where the Ollama files should be stored on Anvil. 

By default, Ollama will write data to the ~/.ollama location in your home directory (the tilde symbol at the upper-left-hand-side of your keyboard refers to your home directory). BUT the data should actually be stored in you `$SCRATCH/.ollama` directory.

So we need to create a symbolic link that tells Ollama to connect to and store in the scratch space. 

In a new Terminal window on Anvil, run these lines (one by one) to create an Ollama symbolic link - this only needs to be done *once* - to set up your environment: 

[source,Bash]
----
# create a new .ollama in $SCRATCH
mkdir -p $SCRATCH/.ollama;

# create a symbolic link to your personal directory
ln -s $SCRATCH/.ollama ~

# If you make a mistake during this process, you can remove the symbolic link to the .ollama directory and try again; the `rm` stands for `remove` and the `-rf` is a recursive force, i.e., throwing everything in that directory away.  Please use this with caution.  In particular, be use to NOT put a space between the tilde and the directory location.
rm -rf ~/.ollama;
----

[NOTE]
====
Without the symbolic link, Ollama would download *large* models into your personal home directory. You would very quickly hit the storage limit, and the downloads would likely fail.

With the symbolic link, large Ollama models live in scratch storage - which is meant to contain much more storage, and often temporary files.  (For comparison:  Your home directory can contain 25 GB of information, and your scratch directory can contain 100 TB of data.  In other words, your scratch directory holds 4000 times as much storage as your home directory.)

Very helpful information about symbolic links and Ollama in general on Anvil can be found in https://the-examples-book.com/tools/python/ollama_llms[the example book page on LLMs].
==== 

