4.3 Reconfigure the graph, and do some testing to see how the agent handles order cancellation requests:

[source,Python]
----
from langchain_core.messages import HumanMessage

tests = [
    {
        "title": "Cancel owner's pending order",
        "customer_name": "Tom Boeckenhauer",
        # this is Tom's pending order ID
        "order_id": "CA-2011-110422",
        "prompt": "Please cancel my order."
    },
    {
        "title": "Cancel someone else's pending order",
        "customer_name": "Tom Boeckenhauer",
        # this pending order does NOT belong to Tom
        "order_id": "CA-2014-121258",
        "prompt": "Please cancel my order."
    },
    {
        "title": "Trak someone else's shipped order",
        "customer_name": "Tom Boeckenhauer",
        # this shipped order is NOT Tom's to track
        "order_id": "CA-2013-138688",
        "prompt": "Where is my order?"
    },
]

for test in tests:
    result = graph.invoke({
        "messages": [
            HumanMessage(content=test["prompt"])
        ],
        "customer_name": test["customer_name"],
        "order_id": test["order_id"],
        "df": myDF
    })

    myDF = result["df"]

    print(f"\n{title}")

    for msg in result["messages"]:
        print(f"\n{type(msg).__title__}")
        print(msg.content)
----

4.4 In your notebook, run:

[source,Python]
----
%%bash
cat tools.py
----

[source,Python]
----
%%bash
cat state.py
----

[source,Python]
----
%%bash
cat graph.py
----

....to print the contents of these files.
====

=== What should an agent do when it cannot solve a user's request?

AI agents usually try to do anything within their knowledge to help a user get a satisfactory result. But sometimes this means they are hallucinating information that isn't 100% true, or a task that they don't actually have the capability to complete. 

Our agent knows how and when to cancel an order, how to look up the status of an order, and to verify customer ownership before sharing important information. That's all it has been trained to know. It may still try to offer up things that it can't actually do in its return messages - such as asking for an email address to confirm, offering refunds, making promises about shipping dates. 

We can attempt to help stop some of these false offers by telling the agent to escalate situations to humans if it does not actually have the capability to complete them. This tool will be called create_support_ticket. With our current system, the agent should be using this tool if the user is asking for a service beyond checking an order's status or cancelling an order. 

The prompt in this tool needs to be clear instructions that the agent *shouldn't* be able to avoid following.

[source,Python]
----
# tools.py

# create support ticket tool
@tool
def create_support_ticket(customer_name: str, issue: str) -> str:
    """Create a support ticket for issues that cannot be resolved using the other tools."""
    return f"Support ticket created for {customer_name}."

# get order status tool
@tool
def get_order_status(order_id: str) -> str:
.....
....
----

[source,Python]
----
# state.py

# no changes here!
# in this simple version, issues will come from users' messages 
# and will be passed by the LLM
----

In the `call_model()` function, we will set some base rules for this new tool. For this quesiton, it is OK to keep the support ticket very basic. 

[source,Python]
----
# graph.py

    if response.tool_calls:
        for tc in response.tool_calls:
            tool_name = tc["name"]

            ##### cancel_order
            if tool_name == "cancel_order":
            .....
            ...

            ##### get_order_status
            elif tool_name == "get_order_status":
            .......
            ....

            ##### create_support_ticket
            elif tool_name == "create_support_ticket":
                issue = tc["args"]["issue"]

                result = (
                    f"Support ticket created for {customer_name}. \nIssue: {issue}."
                )

            tool_msg = ToolMessage(
                content=result,
                tool_call_id=tc["id"]
            )
            ......
            ....
----

The prompt rules is where we have to be careful. Because we are not building out this new tool to be very specific about every single thing the agent should think to escalate to humans, there will still be a lot of errors in how the agent behaves. The following example prompt doesn't even stop the agent from asking the user about the return policy, asking for extra user details, offering refunds with policies that have not been defined, and much more. 

[source,Python]
----
# graph.py

    prompt = f"""
    You are an ecommerce support agent.

    ORDER ID: {order_id}
    CUSTOMER: {customer_name}

    Rules:
    - Ownership verification is handled by the system.
    - Do not ask customers to verify ownership.
    - Use tools when needed.
    - Tool results are final and accurate.
    - If a tool reports success, inform the customer of the successful result.
    - You only have access to the available tools
    - Never promise services you don't have tools to handle
    - If a request cannot be completed using your existing tools, you MUST call create_support_ticket
    """
----

Taking from the Superstore dataset still, test the new `create_support_ticket` tool by prompting the agent to give refunds to some of the dataset rows. 

.Deliverables
====
5.1 Create the `create_support_ticket` tool. What prompt rules are you giving the agent to ensure it doesn't hallucinate? +
5.2 Reconfigure the graph, and do some testing to see how the agent handles requests that go beyond its defined tools:

[source,Python]
----
from langchain_core.messages import HumanMessage

tests = [
    {
        "title": "Refund request",
        # rows #0 & #1
        "customer_name": "Claire Gute",
        # request refund on shipped order
        "order_id": "CA-2013-152156",
        "prompt": "I want a refund."
    },
    {
        "title": "Return request",
        # row #2
        "customer_name": "Darrin Van Huff",
        # request to return shipped order
        "order_id": "CA-2013-138688",
        "prompt": "I want to return my item."
    },
    {
        "title": "Refund request",
        # rows #9984 & #9985
        "customer_name": "Dianna Vittorini",
        # request refund on pending order
        "order_id": "CA-2012-100251",
        "prompt": "I want a refund"
    },
]

for test in tests:
    result = graph.invoke({
        "messages": [
            HumanMessage(content=test["prompt"])
        ],
        "customer_name": test["customer_name"],
        "order_id": test["order_id"],
        "df": myDF
    })

    myDF = result["df"]

    print(f"\n{test['title']}")

    for msg in result["messages"]:
        print(f"\n{type(msg).__name__}")
        print(msg.content)
----

5.3 In the output, what hallucinations are you noticing? Is the agent only responding directly to the tasks you requested? +
5.4 In your notebook, run:

[source,Python]
----
%%bash
cat tools.py
----

[source,Python]
----
%%bash
cat state.py
----

[source,Python]
----
%%bash
cat graph.py
----

....to print the contents of these files.
====

