= TDM 19000: Week 1 Questions -- Summer 2026

== Large Language Models

questions to be posted soon

== Project Objectives

Motivation:  We want to understand how large language models work.  We download and try some variants of language models using https://ollama.com/[Ollama] which has many models in its https://ollama.com/library[Library].

Context:  Working with llama3.2, which is a 2 GB model, we test several model behaviors, check timings, and learn about similarity scores.

Scope:  This is only an introduction to large language models, aimed at students with no background in the data sciences.

.Learning Objectives
****
Introduction to large language models, behaviors, timings, and similarity scores.
****  

=== Question 1

1.1 Start the Ollama server and show the process status of the model. (At the outset, it should only show `NAME    ID    SIZE...` +

1.2 In 2 to 3 sentences, explain what Ollama is, and what its main functions are. You may want to read more about Ollama on the internet. Please list any websites that you read here, or explain how you used generative AI to answer this question.  (We want you to do this for all questions, i.e., if you use any web-based resources or any generative AI or help from other people, please indicate this in your submissions.) +

1.3 In 1 to 2 sentences, explain why we need to use a symbolic link to the $SCRATCH diretory in our setup.

=== Question 2

2.1 Download the llama3.2 model to your scratch directory. +

2.2 Create a model using a custom modelfile to specify the number of threads to use. +

2.3 Explain (in 2 to 3 sentences) the purpose of using the `mymodel` file. +

2.4 Add comments to your `mymodel` file.

=== Question 3

3.1 Use `/anvil/projects/tdm/bin/ollama list` in your notebook to display the
created models. +

3.2 Compare the outputs (written response, response time) of sending a prompt to the model using 1 thread, 2 threads, and 4 threads. Please report the times for all three models. +

3.3 Explain (in 1 to 2 sentences) the differences that you noticed between the models and their responses.

=== Question 4

4.1 Use '/anvil/projects/tdm/bin/ollama list' in your notebook to list the current models. +

4.2 Try creating at least two models with new system behavior definitions. +

4.3 Explain how (in 2 to 3 sentences) your new models behave compared to the default?








== Submitting your Work

Once you have completed the questions, save your Jupyter notebook. You can then download the notebook and submit it to Gradescope.

.Items to submit
====
- firstname_lastname_week1.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====

