= STAT-LLC 2018 R Exercises



== Project 4

Use R to revisit these questions.  They can each be accomplished with 1 line of code.

Question 1.

Find all of the (origin) airports from which you can fly to 100 or more (distinct) destinations.  (Either from 2005 or from all years.)

Hint:   R has a `unique` command.

Hint 2:  `sapply(mydata, myfunction)`

can be used to apply `myfunction` to each element of `mydata`

Hint 3:  ALTERNATIVELY, it is possible to custom build functions, for example, we can get the `mean` of the `DepDelay` for each `Origin` airport this way:

`tapply(myDF$DepDelay, myDF$Origin, mean, na.rm=T)`

but we *cannot* get 3 times the mean this way:

`tapply(myDF$DepDelay, myDF$Origin, 3*mean, na.rm=T)`

we would need to build our own function:

`tapply(myDF$DepDelay, myDF$Origin, function(x) {3*mean(x, na.rm=T)})`

Question 2.

a.  Consider the election donation data:

`https://www.fec.gov/data/advanced/?tab=bulk-data`

from "Contributions by individuals" for 2017-18.  Download this data.

b.  Unzip the file (in the terminal).

c.  Use the `cat` command to concatenate all of the files into one large file (in the terminal).

d.  Read the data dictionary:

`https://www.fec.gov/campaign-finance-data/contributions-individuals-file-description/`

Hint:  When working with a file that is not comma separated, you can use the `read.delim` command, and just specify the character that separates the various pieces of data on a row.

Question 3.

a.  Which state's citizens gave the largest number of contributions?

b.  Which state's citizens gave the greatest amount of money?

Question 4.

a.  Now turn attention to the "all candidates" file for 2017-18, which contains summarized data.

b.  Download the data and unzip it.

c.  Read the data dictionary.

d.  Create a new data.frame that contains only these columns: 6-18, 26-27, 29-30

Question 5.

a.  Convert the data.frame to a matrix

b.  Sum these columns (all at once), using the apply function.

Question 6.

a.  Consider the Lahman baseball database available at:

`http://www.seanlahman.com/baseball-archive/statistics/`

Download the comma-delimited version and unzip it.

Inside the "core" folder of the unzipped file, you will find many csv files.

If you want to better understand the contents of the files, there is a helpful readme file available here:
`http://www.seanlahman.com/files/database/readme2017.txt`

b.  read the Teams.csv file into a data.frame called myDF

c.  we can break the data.frame into smaller data frames, according to the `teamID`, using this code:

`by(myDF, myDF$teamID, function(x) {plot(x$W)} )`

For each team, this will draw 1 plot of the number of wins per year.  The number of wins will be on the y-axis of the plots.

d.  For an improved version, we can add the years on the x-axis, as follows:

`by(myDF, myDF$teamID, function(x) {plot(x$year, x$W)} )`

e.  Change your working directory in R to a new folder, using the menu option:

`Session -> Set Working Directory -> Choose Directory`

We are going to make 149 new plots!

f.  After changing the directory, try this code, which makes 149 separate pdf files:

`by(myDF, myDF$teamID, function(x) {pdf(as.character(x$teamID[1])); plot(x$year, x$W); dev.off()} )`

Question 7.

Experiment with this concept yourself!  Make three more series of plots, using the baseball tables.  You are welcome to choose which kinds of series of plots you make.  Enjoy, and be creative!

Question 8.

Put the project into RMarkdown and submit when your code is polished and ready.




== Project 8

Question 1.

a.  Extract the total dollar amount of funds per state from the election data.

b.  Use the (built-in) state.abb to extract the results from the 50 US States (only).

Question 3.

a.  Extract a table that contains the total number of flights departing from each airport.

b.  Use the locations of the airports from the auxiliary airports file, available here:

http://stat-computing.org/dataexpo/2009/supplemental-data.html

to turn the results from part a into the total number of flights departing from each state.  (This will require a little thought!)

c.  Use the (built-in) `state.abb` to extract the results from the 50 US States (only).

Question 4.

Make a figure that compares each of these pairs of data, from questions 1b and 3c.  For instance, you might use the "pairs" function or another function of your choice.  The resulting plot will compare the total funds donated in each state, and the total number of flights departing from each state.

Question 6.

a.  In the election data, find the total amount of donations contributed by donors whose name contains the phrase Emma (in capital letters).  If you are unable to ensure that this is the "first name" that is OK for the purposes of the project, but you might want to (for instance) try to make your search as intelligent as possible.  There is more than one way to do so, of course.

b.  Repeat part 6a for four more girl names of your choice.

Question 7.

a.  Write a function that takes a girl name as input and extracts the total amount of donations contributed by donors who have this first name.

b.  Use the sapply function to run your function on each of the top 100 girl names that you extracted in 5c.

Question 8.

Repeat questions 6 and 7 for the top 100 boy names.

Question 9.

a.  Which girl name contributed the most, in terms of the total amount of donations?

b.  Which boy name contributed the most, in terms of the total amount of donations?





