= STAT-LLC 2017 Data Viz Exercises

== Project 5

Question 1.

Read the selection of The Elements of Graphing Data by William Cleveland, and the selection of Creating More Effective Graphs by Naomi Robbins, placed into your Project 5 folders on the scholar server.

Also read the classic article "How to Display Data Badly" by Howard Wainer:
http://www.jstor.org.ezproxy.lib.purdue.edu/stable/2683253

Question 2.

Find 6 visualizations from http://www.informationisbeautiful.net/[the Information Is Beautiful website] that do a bad job of portraying data, according to the best practices in the selections from question 1.  Write 1/3 of a page (for each such visualization) about what is done poorly.

Question 3.

Identify 3 excellent visualizations of data from the site in question 2.  Write 1/3 of a page (for each such visualization) about what is done well.

Question 4.

The Gapminder comparison of life expectancy and income per person, plotted from 1800 to 2015, is eye-catching but does not necessary follow the best practices for data visualization.  (See www.gapminder.org/tools/)  Write half a page about things that this visualization does poorly, and half a page about ways that this visualization could be re-created and re-designed, if you were to recreate this website yourself.

Question 5.

Consider the poster winner "Congestion in the Sky", from the 2009 Data Expo:

http://stat-computing.org/dataexpo/2009/posters/

Describe at least 3 significant ways that this poster could be improved.  For each of these 3 ways, write a 1/3 of a page constructive criticism, specifying what could be improved and how that aspect of the visualization could be done better.

Question 6.

Choose a different poster from the 2009 Data Expo, and construct a similar analysis to question 5, i.e., give a constructive criticism of at least 3 significant ways that this poster could be improved, with 1/3 of a page writeup for each such significant need for improvement.

Question 7.

Which of the posters in the Data Expo 2009 do you think should be the winner? Why? (It is OK if you choose the poster that actually won, or any of the other posters.) Thoroughly justify your answer, using the techniques of effective data visualization, to justify your answer, with an explanation that is at least 1 page long altogether.

Questions 8, 9, 10.

Imagine that you are going to enter the Data Expo 2009. Rather than having to organize your information into a poster, prepare 3 pages of analysis, exploring some aspects of the airline data set that are interesting to you, and which you think might be of broad interest to potential readers too. Your discussion and plots should be at least 3 pages long.

