= STAT-LLC 2016 Data Viz Exercises

== Project 9

Something went very, very unexpected in the Presidential Election 2016.

Spend this week finding 6 visualizations of the election data (either before or after the election).  Find things that the visualizations do well, and find things that they do poorly. I.e., make some critiques, as a team, of the visualizations.

I suggest that you first consider some of the bad ways of depicting data seen in this article:

http://www.jstor.org.ezproxy.lib.purdue.edu/stable/2683253

I'm also attaching some scans (in two attached pdf files) from two books that might be helpful.  I just picked out some of the most relevant pages.  One of the books discusses some issues with color, but both books are actually printed in black and white (it is strange, I know).

You can submit your writeup in whatever way looks most professional to you.  Be critical of what you see and what you say about the visualizations that you find!

The due date for Project 9 is Friday, November 18, but you will probably be able to finish it before that, and move onwards to Project 10.


