= TDM 10100: Project 1 -- Fall 2026

- Introduction to Data Analysis using Python and R in Jupyter Lab
- Project Templates for Documenting Analysis, Workflow, and Submissions
- Teamwork Stucture and Learning Community Overview

**Motivation:** Our goal in Project 1 is to help you get comfortable with aspects of The Data Mine.  We use Jupyter Lab on the Anvil computational cluster.  In this first project, it is OK to ask many questions and to explore!  (It is always OK to ask questions.)  The main goal is to get prepared to work in The Data Mine.  We are happy to have you join this experience.

**Context:** In The Data Mine, we do not require any background or prerequisites.  It is OK if this is your first time working with data.  No background is needed.  We aim to give practical examples and to always be "learning by doing."

**Scope:** Anvil, Jupyter Lab, R, Python

.Learning Objectives:
****
- Learn how to work in Jupyter Lab
- Learn how to upload and download files to/from the Anvil computing cluster
- Read data using R and Python
****

Make sure to read about, and use the template found xref:ROOT:templates.adoc[here], and the important information about project submissions xref:ROOT:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset(s):

- `/anvil/projects/tdm/data/flights/subset/airports.csv`
- `/anvil/projects/tdm/data/olympics/athlete_events.csv`

First and foremost, welcome to The Data Mine! We hope that throughout your journey with us, you learn a lot, make new friends, and develop skills that will help you with your future career. Throughout your time with The Data Mine, you will have plenty of resources available should you need help. By coming to weekly seminar, posting on the class Piazza page, and joining Dr. Ward and the TA team's office hours, you can ensure that you always have the support you need to succeed in this course.

The link to Piazza is:   https://piazza.com/purdue/fall2026/tdm10100

Dr Ward is also available on Monday, Wednesday, and Friday mornings in the Hillenbrand dining court from 8:30 AM to 10:20 AM (Eastern time zone).

[IMPORTANT]
====
If you did not (yet) set up your 2-factor authentication credentials with Duo, you can set up the credentials here: https://the-examples-book.com/setup[https://the-examples-book.com/setup] If you are still having issues with your ACCESS ID, please send an email containing as much information as possible about your issue to datamine@purdue.edu
====

Let's start off by starting up our first Jupyter session on Anvil!

Please read about Jupyter Lab here:  https://the-examples-book.com/projects/fall2026/10100/jupyterlab

We have even more information about Jupyter Lab here:  https://the-examples-book.com/projects/fall2026/10100/jupyter

[IMPORTANT]
====
The projects are usually due on *Wednesdays*.  You can see the schedule here:  https://the-examples-book.com/projects/fall2026/10100/projects  *Please do not wait until Wednesday to complete and submit your work!*
====

Download the project template, as described here:  https://the-examples-book.com/projects/templates[https://the-examples-book.com/projects/templates]

When you first open the template, you may get a pop-up asking you to select what kernel you'll be using. Select the `seminar` kernel (not the `seminar-r` kernel). If you do not get this pop-up, you can also select a kernel by clicking on the upper right part of your screen that likely says something similar to `No Kernel`, and then selecting the kernel you want to use.

We give some information about kernels here:  https://the-examples-book.com/projects/kernels

== Questions

=== Question 1 (2 pts)

For the first question in this project, let's try the first R example from the kernel page:  https://the-examples-book.com/projects/kernels

We will load the airports data set in R, using the `seminar` kernel, and will display the head of the airports data set.  The `head` is the first six lines of the data, and the names of the columns appear above the head.

[source, R]
----
%%R
myDF <- read.csv("/anvil/projects/tdm/data/flights/subset/airports.csv")
head(myDF)
----

Just try this R code using the `seminar` kernel (not the `seminar-r` kernel) and make sure that you can see the first six rows of the airports data frame.

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_shwztqo3&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++

.Deliverables
====
- Use R to show the first six rows of the airports data frame.
- Then use R again to show the first twelve rows of the airports data frame, using the `n=12` argument.
- Be sure to document your work from Question 1, using some comments and insights about your work.
====

=== Question 2 (2 pts)

Now do this again, using the `seminar-r` kernel with R, and notice that you do *NOT* need the `%%R` cell magic with the `seminar-r` kernel.  You can do all of this in the same Jupyter Lab notebook, just by changing the kernel.

[source,R]
----
myDF <- read.csv("/anvil/projects/tdm/data/flights/subset/airports.csv")
head(myDF)
----

You have now loaded the first six lines of the airports data frame in three ways (once in Question 1, and now a second and a third time in Question 2).

A Jupyter notebook is made up of `cells`, which you can edit and then `run`. There are two types of cells we'll work in for this class:

- Markdown cells. These are where your writing, titles, sections, and paragraphs will go. Double clicking a markdown cell puts it in `edit` mode, and then clicking the play button near the top of the screen runs the cell, which puts it in its formatted form. More on this in a second. For now, just recognize that most markdown looks like regular text with extra characters like `#`, `*`, and `-` to specify bolding, indentation font, size, and more! 
- Code cells. These are where you will write and run all your code! Clicking the play button will run the code in that cell, and the programming language is specified by the language or languages known by the kernel that you chose.

*For each question in The Data Mine*, please always be sure to put some comments after your cells, which describe all of the work that you are doing in the cells, as well as your thinking and insights about the results.

[NOTE]
====
Some common Jupyter notebooks shortcuts:

- Instead of clicking the `play button`, you can press ctrl+enter (or cmd+enter on Mac) to run a cell.
- If you want to run a cell and then move immediately to the next cell, you can use shift+enter. This is oftentimes more useful than ctrl+enter
- If you want to run the current cell and then immediately create a new code cell below it, you can press alt+enter (or option+enter on Mac) to do so.
- When a cell is selected (this means you clicked next to it, and it should show a blue bar to its left to signify this), pressing the `d` key twice will delete that cell.
- When a cell is selected, pressing the `a` key will create a new code cell `a`bove the currently selected cell.
- When a cell is selected, pressing the `b` key will create a new code cell `b`elow the selected cell
====

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_7a5huc9r&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_b7qgta6d&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++

.Deliverables
====
- Use R to (again) show the output with the first twelve rows of the airports data frame, this time using the `seminar-r` kernel instead of the `seminar` kernel.
- Now use R to show the first ten rows of airports that are located in Indiana.
- How many airports are located in Indiana altogether?  (Use the `dim` function, as shown in the video.)
- Be sure to document your work from Question 2, using some comments and insights about your work.
====

=== Question 3 (2 pts)

In the year 2007, count the number of flights that originate from each airport.  Which 20 airports are the most popular in this regard, i.e., in terms of having the most flights originating from those airports?

First, you need to load the `data.table` library, and then (afterwards), you can load the data for the 2007 flights, as follows:

[source, R]
----
library(data.table)
myDF <- fread("/anvil/projects/tdm/data/flights/subset/2007.csv")
----

(We needed the `data.table` library because it defines the `fread` function which is much faster and more efficient than the `read.csv` function from the previous question.  After all, we are working with more than 7 million rows of data in this question!)

You can be sure to be able to see all of the columns (up to a maximum of 50 columns) using the command:

[source, R]
----
options(repr.matrix.max.cols=50)
----

Finally, make a table, sort the results, and display the biggest 20 values, as shown in the video.

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_wmbde71i&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_6iby4zwd&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++

.Deliverables
====
- Which 20 airports are the most popular in this regard, i.e., in terms of having the most flights originating from those airports?
- Be sure to document your work from Question 3, using some comments and insights about your work.
====

=== Question 4 (2 pts)

In the Olympics data stored here:

`/anvil/projects/tdm/data/olympics/athlete_events.csv`

consider how many times that each `City` occurs in the data.  Find the top 10 most popular cities, according to how many times that they occur.  For each of these top 10 most popular cities, list the city name and the number of times that it occurred in the data set.

(The same method that you used in Question 3 should work.)

.Deliverables
====
- Find the top 10 most popular cities, according to how many times that they occur.  For each of these top 10 most popular cities, list the city name and the number of times that it occurred in the data set.
- Be sure to document your work from Question 4, using some comments and insights about your work.
====

=== Question 5 (2 pts)

For the 20 most popular airports (from Question 3), make a `dotchart` that shows how many flights originated from each of those airports in the year 2007.

Similarly, for the 10 most popular cities in the Olympics data (from Question 4), make a `dotchart` that shows how many times each city occurred in the Olympics data.

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_chf3gsi3&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++

++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_1r6wse41&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_aheik41m" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM 10100 Project 13 Question 1"></iframe>
++++

.Deliverables
====
- Make a `dotchart` that shows how many flights originated from each of the 20 most popular airports in the year 2007.
- Make a `dotchart` that shows how many times each of the 10 most popular cities occurred in the Olympics data.
- Be sure to document your work from Question 5, using some comments and insights about your work.
====

== Submitting your Work

Please make sure that you added comments for each question, which explain your thinking about your method of solving each question.  Please also make sure that your work is your own work, and that any outside sources (people, internet pages, generative AI, etc.) are cited properly in the project template.

Congratulations! Assuming you've completed all the above questions, you've just finished your first project for TDM 10100! If you have any questions or issues regarding this project, please feel free to ask in seminar, over Piazza, or during office hours.

Prior to submitting your work, you need to put your work xref:ROOT:templates.adoc[into the project template], and re-run all of the code in Jupyter Lab and make sure that the results of running that code is visible in your template.  Please check the xref:ROOT:submissions.adoc[detailed instructions on how to ensure that your submission is formatted correctly]. To download your completed project, you can right-click on the file in the file explorer and click 'download'.

Once you upload your submission to Gradescope, make sure that everything appears as you would expect to ensure that you don't lose any points. We hope your first project with us went well, and we look forward to continuing to learn with you on future projects!!

.Items to submit
====
- firstname_lastname_project1.ipynb
====

[WARNING]
====
It is necessary to document your work, with comments about each solution.  All of your work needs to be your own work, with citations to any source that you used.  Please make sure that your work is your own work, and that any outside sources (people, internet pages, generative AI, etc.) are cited properly in the project template.

You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not.

**Please** take the time to double check your work. See xref:ROOT:submissions.adoc[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====
