= TDM 10100: Project 6 -- Fall 2026

- Dates, Date-Times, Timestamps, and Libraries in Python and R for Date-Time Conversions

**Motivation:** We learn about working with dates and times, in both Python and R

**Context:** Both languages provide several types of tools for working with dates and times.

**Scope:** data frames

.Learning Objectives:
****
- Understand how to use dates and times in real-world data
****

Please use the template found xref:ROOT:templates.adoc[here], and the important information about project submissions xref:ROOT:submissions.adoc[here], when you are ready to submit your work.

== Dataset(s)

This project will use the following datasets:

- `/anvil/projects/tdm/data/craigslist/vehicles.csv`
- `/anvil/projects/tdm/data/zillow/cities_crosswalk.csv`
- `/anvil/projects/tdm/data/zillow/State_time_series.csv`
- `/anvil/projects/tdm/data/taxi/green/green_tripdata_2019-06.csv`
- `/anvil/projects/tdm/data/fars/2021/accident.csv`



[IMPORTANT]
====
In this project, *please only use 2 cores in your Jupyter Lab session*:

https://notebook.anvilcloud.rcac.purdue.edu/

(do not use 4 cores or 16 cores for this project)
====


== Questions

=== Question 1 (2 pts)

In R, if you use the `lubridate` library, there is an official Cheatsheet available from Posit (the company that makes RStudio) available here:

https://rstudio.github.io/cheatsheets/html/lubridate.html

and it is also available in pdf format:

https://rstudio.github.io/cheatsheets/lubridate.pdf

These cheat sheets are loaded with a variety of information!

Please consider our examples, which demonstrate how to use a few of these functions:

https://the-examples-book.com/projects/fall2026/10100/project6examples1

After you finish considering those examples, read the data from the ice cream reviews into an R data frame, using `fread`:

`/anvil/projects/tdm/data/icecream/combined/reviews.csv`

On which date were the most reviews written?  How many reviews were written on that date?

Make a plot that shows the number of reviews per date, for the whole data set.

Make a second plot that shows the number of reviews per date, but only for the dates in June 2018.

.Deliverables
====
- On which date were the most reviews written?
- How many reviews were written on that date?
- Make a plot that shows the number of reviews per date, for the whole data set.
- Make a second plot that shows the number of reviews per date, but only for the dates in June 2018.
- As *always*, be sure to document your work from Question 1 (and from all of the questions!), using some comments and insights about your work.  We will stop adding this note to document your work, but please remember, we always assume that you will *document every single question with your comments and your insights*.
====

=== Question 2 (2 pts)

In the Bay Area Bike Share Baywheels data from July 2025:

`/anvil/projects/tdm/data/bay_area_bike_share/baywheels/202507-baywheels-tripdata.csv`

find the average length of bicycle trips, by subtracting the `started_at` time from the `ended_at` time.

There are altogether 388168 bike rides in this data set.  Once you have calculated the average time of a bike ride, find the number of bike rides that were longer than the average length.

.Deliverables
====
- Find the average length of bicycle trips in July 2025.
- Find the number of bike rides that were longer than the average length.
====

=== Question 3 (2 pts)

Read in only the `Date received` column from the Consumer Complains data:

`/anvil/projects/tdm/data/consumer_complaints/complaints.csv`

On which date did the most complaints occur?  How many complaints occurred on that date?

Make a plot that shows the number of complaints per date, but only for the dates in February 2025.


.Deliverables
====
- On which date did the most complaints occur?
- How many complaints occurred on that date?
- Make a plot that shows the number of complaints per date, but only for the dates in February 2025.
====


=== Question 4 (2 pts)

Now switch from the `seminar-r` kernel to the `seminar` kernel, and work in Python, for questions 4 and 5.

In Python, we can read in data in csv (comma-separated-values) format, as seen in earlier projects, or we can even read in data in Parquet format (a compressed format).  For instance, consider some examples in which we learn a little about some Yellow Taxi Cab data from September 2025:

https://the-examples-book.com/projects/fall2026/10100/project5examples4

After you finish considering those examples about Yellow Taxi Cab data, we can now turn our attention to some Green Taxi Cab data, stored in csv format, from June 2019:

`/anvil/projects/tdm/data/taxi/green/green_tripdata_2019-06.csv`

Find the 7 values of `DOLocationID` that each occur 10000 or more times in the Green Taxi Cab data.

How many Green Taxi Cab rides had only 1 passenger?  How many Green Taxi Cab rides had 2 passengers?

How many Green Taxi Cab rides had a tip that was 21 dollars or greater?


.Deliverables
====
- Find the 7 values of `DOLocationID` that each occur 10000 or more times in the Green Taxi Cab data.
- How many Green Taxi Cab rides had only 1 passenger?
- How many Green Taxi Cab rides had 2 passengers?
- How many Green Taxi Cab rides had a tip that was 21 dollars or greater?
====


=== Question 5 (2 pts)

Now, read the examples about the CMS Diabetes Prescriber data:

https://the-examples-book.com/projects/fall2026/10100/project5examples5

Afterwards, consider the FARS 2021 accident data:

[source,python]
----
import pandas as pd
myDF = pd.read_csv("/anvil/projects/tdm/data/fars/2021/accident.csv", encoding="latin1")
----

(The `latin1` is used because some of the data in this data set has a slightly different encoding than usual.)

The state names are not available by default in Python, but we can make a list of them:

[source,python]
----
states = [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California",
    "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
    "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa",
    "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland",
    "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri",
    "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
    "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio",
    "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
    "South Dakota", "Tennessee", "Texas", "Utah", "Vermont",
    "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"
]
----

By studying the example we provide, find out how many rows of the FARS 2021 accident data are not from the 50 states.  What location are those (other) rows of the FARS 2021 from?

.Deliverables
====
- Find out how many rows of the FARS 2021 accident data are not from the 50 states.  What location are those (other) rows of the FARS 2021 from?
====




== Submitting your Work

Please make sure that you added comments for each question, which explain your thinking about your method of solving each question.  Please also make sure that your work is your own work, and that any outside sources (people, internet pages, generative AI, etc.) are cited properly in the project template.

Prior to submitting your work, you need to put your work xref:ROOT:templates.adoc[into the project template], and re-run all of the code in Jupyter Lab and make sure that the results of running that code is visible in your template.  Please check the xref:ROOT:submissions.adoc[detailed instructions on how to ensure that your submission is formatted correctly]. To download your completed project, you can right-click on the file in the file explorer and click 'download'.

Once you upload your submission to Gradescope, make sure that everything appears as you would expect to ensure that you don't lose any points. We hope your first project with us went well, and we look forward to continuing to learn with you on future projects!!

.Items to submit
====
- firstname_lastname_project5.ipynb
====

[WARNING]
====
It is necessary to document your work, with comments about each solution.  All of your work needs to be your own work, with citations to any source that you used.  Please make sure that your work is your own work, and that any outside sources (people, internet pages, generative AI, etc.) are cited properly in the project template.

You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not.

**Please** take the time to double check your work. See xref:ROOT:submissions.adoc[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====
