= TDM 10100: Project 8 -- Fall 2026
:page-mathjax: true

- Data Grouping, Subsets, Looping through Data using Apply (sapply/tapply/lapply) Functions, and Splitting Data

**Motivation:** R provides powerful methods for looping through data.  These methods are easy to use, once you get used to the syntax and the methodology.  

**Context:** R allows us to split data into groups, apply functions to each group, and to organize an analysis of data... often all in one line!

**Scope:** We will demonstrate the usage of looping through data in groups in R, starting with the `tapply` function as a key example.

.Learning Objectives:
****
- Practice organizing and analyzing data in R.
- Understand how R groups data and applies functions.
****

Please use the template found xref:ROOT:templates.adoc[here], and the important information about project submissions xref:ROOT:submissions.adoc[here], when you are ready to submit your work.

== Datasets
- /anvil/projects/tdm/data/grouping/vgchartz-2024.csv
- /anvil/projects/tdm/data/grouping/googleplaystore.csv
- /anvil/projects/tdm/data/election/itcont1980.txt (used in one of the example files)



[IMPORTANT]
====
In this project, *please only use 2 cores in your Jupyter Lab session*:

https://notebook.anvilcloud.rcac.purdue.edu/

(do not use 4 cores or 16 cores for this project)
====

Dr. Ward thinks about the `tapply` function this way:

- The data that you want to work with goes first in the `tapply`
- The way that the data are grouped goes second in the `tapply`
- The function that you want to apply to the data goes third in the `tapply`

For instance, `tapply(mymiles, mypeople, sum)` will add up the miles (stored in `mymiles`) but will do it one person at a time (according to `mypeople`).

As a way to know if you have the ordering of things correct, you can usually ask yourself if you could apply the function to the data itself, without grouping it, for instance, in this example, `sum(mymiles)` would be the total miles, but it would not make sense to write `sum(mypeople)` because you do not add up people.

There are numerous examples in these pages.  It should help to take a look at the examples, before you try the questions.

You can read an overview about the `tapply` function:

https://the-examples-book.com/projects/fall2026/10100/tapplyoverview

as well as an election example:

https://the-examples-book.com/projects/fall2026/10100/electionexamples

an ice cream example:

https://the-examples-book.com/projects/fall2026/10100/icecreamexample

an airport example:

https://the-examples-book.com/projects/fall2026/10100/airportexample

and the video game examples:

https://the-examples-book.com/projects/fall2026/10100/videogameexamples



== Questions

=== Question 1



.Deliverables
====
- 
- 
====

=== Question 2



.Deliverables
====
- 
- 
====


=== Question 3


.Deliverables
====
- 
- 
====

=== Question 4


.Deliverables
====
- 
- 
====


=== Question 5



.Deliverables
====
- 
- 
====




== Submitting your Work

Once you have completed the questions, save your Jupyter notebook. You can then download the notebook and submit it to Gradescope.

.Items to submit
====
- firstname_lastname_project8.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====
