= Salesforce

== Leads versus Contacts

Both leads and contacts are individual people.

A "lead" is a person who has not (yet) agreed to be involved in a partnership with The Data Mine.

A "contact" is a person who has agreed to be involved in a current (or previous) partnership with The Data Mine.

Leads are converted to contacts when they agree to be involved in a partnership with The Data Mine.

[NOTE]
====
Once a lead is converted to a contact, it cannot be converted back to a lead again.
====

We have a full page about each of these topics, to dive deeper:

* xref:salesforce:ROOT:leads.adoc[Leads]

* xref:salesforce:ROOT:contacts.adoc[Contacts]

* xref:salesforce:ROOT:leadtocontact.adoc[Converting a Lead to a Contact]




== Partnerships versus Projects

A "partnership" is a company or university (or other similar type of organization).  Whether the partner has agree to work with The Data Mine or not, it is OK to enter the information about all partnerships (past, present, potential, etc.)  Partnerships can be classified by their type, including "Prospect" (which means that they have not yet agreed to work with The Data Mine) or "Partner" (which means that they are a past or present partner, or have agreed to be a partner in the very near future).

A "project" describes an opportunity that The Data Mine will execute with one or more of its partners, typically during a 9-month credit-bearing, experiential project, but could also be during a sponsored research project.

