= Frequently Asked Questions about Partnership


== What is the time commitment?

During the academic year, from late August until the end of April, mentors meet with their students for 50 minutes per week. This meeting is usually online unless the mentor is local or visiting West Lafayette. In the summer, we meet to check in every other week for 25 minutes to plan for the academic year. 

== Does my project make sense for The Data Mine?
* Does it have a clear, aspirational, data-driven problem?
* Could it benefit from Purdue's computing resources?
* Do you have domain-specific analytical challenges where multiple approaches are viable?

== What are the key elements to a good Data Mine project?

The best Data Mine projects have these two elements:

1. *Data intensive project*: We seek projects with large data sets (an Excel spreadsheet doesn't count).
2. *Committed mentoring*: It is important to have a corporate employee who can meet and mentor the students.

== What resources do we get for partnering with The Data Mine?

* 1 paid team leader (student) per project 
* Team of undergraduate and graduate students of diverse backgrounds
* Data Scientist support 
* Corporate Partner Manager 
* Connections to campus partners 


