= `cd`

Navigating directories is one of the most used (and most basic) skill you will develop in Unix. `cd` provides an essential building block to navigation, and is easy to learn. 

`cd` is short for "change directory". The command allows for you to move into another directory (think of it as a folder) inside of the current directory. This is something that you have been doing your whole life (like when you are trying to find a file on your computer; you change directories a lot!).

If you were to attempt to navigate into a folder using a GUI, you would click on the folder with the name that you would like to navigate to. Using `cd`, it is almost as easy. Simply type `cd` into your terminal, followed by the name of the directory that you would like to navigate to. If you wanted to navigate into the `school` folder on your computer, you would do this:

----
cd school
----

This changes your working directory to the path of the `school` directory. Remember, if you want to find the your working directory, you can use the `pwd` command.

Sometimes, you navigate into a folder that you do not want to be in, or you want to go back to a parent directory. To go back to the directory that you were previously in, you can use the `..` file path. 

Say that you did mistakenly navigated into the `school` directory, and wanted to go back. You could run the following command:

----
cd ..
----

Note that there is a space between `cd` and `..`!

`cd` is a very powerful and simple tool, and soon you will find yourself using it without even knowing. 