= `ls`

While `pwd` allows for you to see the full system path of the current working directory, `ls` prints the files and sub-directories located in the current working directory. `ls` is incredibly useful for navigation. For example, if you are `cd`-ing between folders to find a certain file, you can use `ls` to show which files and directories you have access to in the current working directory. To show all of the files and sub-directories in the `school` folder, you can use `ls`, like this:

----
ls
----

This would result in an output that looks something like this:

----
schedule.pdf    code.py     STAT_190    MA_165 
----

Here you can see that there are two files, and two sub-directories located in the `school` directory. From here, you can `cd` into the `STAT_190` or the `MA_165` sub-directory.

`ls` and `cd` are often used hand-in-hand. This makes sense: it is unlikely that you will remember the files located in each directory and sub-directory when navigating in the terminal.

== options

There are many options that are used with `ls`. This is how an option would be used with `ls`:

----
ls -a
----

Here are a few, and what they do!

* `-a` : list all files, including hidden files.
* `-l` : outputs the files in the directory in a list format.
* `-S` : sorts the output by the size of each file (please note that this is a *capital* S)