= University Partners

Welcome to The Data Mine University Partners!


This overview of The Data Mine was created by Purdue's Marketing and Communication team. It has over 115,000 views! 

++++
<iframe  class="video" width="560" height="315" src="https://www.youtube.com/embed/R_kqpIMyhR4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

We have partnerships with link:https://datamine.purdue.edu/symposium/welcome.html[47 companies]

The Data Mine is a partnership of

•	Purdue University, West Lafayette, Indiana
•	Purdue University, Fort Wayne, Indiana
•	Purdue Polytechnic, Anderson, Indiana

We are ready to expand The Data Mine model to universities throughout the state of Indiana, with our new Indiana Data Mine program, supported by the Lilly Endowment.

We are also ready to offer The Data Mine experience to students throughout the United States, under the new National Data Mine Network program, supported by the National Science Foundation.

We warmly welcome you to The Data Mine!

++++
<iframe class="video" src="https://cdnapisec.kaltura.com/html5/html5lib/v2.79.1/mwEmbedFrame.php/p/983291/uiconf_id/29134031/entry_id/1_fcjd0ivp?wid=_983291"></iframe>
++++

