= Spring 2022 Announcements 


*Check this page frequently for announcements about the course. Announcements will also be emailed out to students*

== (February 2) Inclement Weather Procedures for The Data Mine

We want to make you aware of our plans *if* Purdue calls for an inclement weather day.

Team meetings will continue as normal since these are already scheduled for online. No changes needed. 
Labs will continue as scheduled with an *online* format only. Students should use the same MS Teams meeting link for lab as previously sent out for the 50-minute team meetings. The link will still work even if it is a different day. 
Should there be inclement weather, Data Mine students are still expected to attend team meetings and labs in an *online* format. 

Please let us know if you have any questions. We will keep you posted via email with any additional updates. Stay safe and warm!

== (January 11) COVID-19 Protocols

https://protect.purdue.edu/protect-purdue-health-center/quarantine-isolation-resources/

These protocols were recently updated, and we want to make sure you are aware of them. Please review these updated protocols for quarantine and isolation before attending any in-person classes. 

YOU SHOULD NOT BE ATTENDING IN-PERSON CLASS IF YOU HAVE *ANY* SYMPTOMS, EVEN IF YOU TEST NEGATIVE. 

You can call Protect Purdue Health Center for any questions about your specific situation. 


== (January 10) Lab locations & Meeting Times

All teams have in-person labs (1 hour 50 minutes) regardless of what your registration says on UniTime. 

Lab locations are either in MRGN or HILL. The complete list of times and locations are available in the xref:spring2022_locations.adoc[Team Meeting Locations] page.

== (January 3) Welcome to The Data Mine Corporate Partners!

Hello, and welcome to The Data Mine Corporate Partners! (STAT 190/290/390 The Data Mine & STAT 598 Data Science in Industry).

To get started, please click on "Sprint #1" on the left hand column. It includes the syllabus, where to go for your class time, and your first assignments. 

If you have questions, please email datamine@purdue.edu and include "Corporate Partners question: [your team name]" in the subject line to help you get the fastest response. 

We look forward to working with you this semester! 