= Workshop Outline

During the spring 2023 semester, we will offer a workshop series to equip you to start The Data Mine at your university. 

Dates: 
Link to join: 
RSVP: 

== The Basics

=== 0 - Callout / About The Data Mine 

_Data Science for All_ 

=== 1 - Stakeholders + Expectations


=== 2 - Seminar 

This 1 credit hour course is offered fall and spring to provide students experiential learning (no lectures or exams) with data science tools and large data sets on HPC clusters. Semester one covers R and SQL, semester two covers Python, and sessions three through eight cover advanced topics. View the link:https://the-examples-book.com/projects/current-projects/fall2022/syllabus[syllabus] and link:https://the-examples-book.com/projects/current-projects/10100-2022-projects[content for semester one]. 

=== 3 - Students

Topics include: 

* Recruiting
* Registration
* Learning Communities/Housing
* TAs
* Academic Advisors

== Extended sessions about Corporate Partnerships

=== 4 - TDM Corporate Partners Overview 

Stakeholders to involve

=== 5 - Business Partnerships & Recruiting Industry Sponsored Projects

Homework for participants: bring your university's business partnership rep if possible

=== 6 - Legal 

Topics include: 

* NDAs
* Sponsor Acknowledgments
* IP 

Homework for participants: bring your university's legal rep 

=== 7 - Technical support & reserach computing 

Topics include: 

* Research computing at your university 
* Student support 


Homework for participants: bring your university's reserach computing if possible

=== 8 - Course Management for Corporate Partners

Topics include:

* Agile Project Management 
* Syallbus 
* Course structure
* Communication for teams (email, MS Teams)
* TAs


=== 9 - Operations 

Topics include: 

* Finances
* Sponsor Acknowledgments 
* Guest speakers