= Workshop Outline

During the spring 2023 semester, we will offer a series of *60-min _bi-weekly_ sessions* to help you identify the steps needed to bring The Data Mine model to life at your university. 

*Dates:* January 25 - March 22

link:https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpurdue.ca1.qualtrics.com%2Fjfe%2Fform%2FSV_dpAJweMGBmxoRDw&data=05%7C01%7CPWHEATLEY%40CSBSJU.EDU%7C0299b1bfdfac4609b90008dafa5b3152%7Cf3a8b12ce0414209a57adb14d8738136%7C0%7C0%7C638097566992299822%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=%2BYPtoyDKY%2F52Cu7%2B0izDAs7Ij1ByxMuudcwZtKz52Lg%3D&reserved=0[Registration link]

*Questions?  Email* datamine@purdue.edu



== Session 1:  Wed, January 25th

=== Intro/Workshops overview

* Workshop schedule & topics
* Workshop objectives & outcomes
* Expectations and commitments of the workshops

=== Stakeholders

* How to get buy-in at your university 
* Identifying your allies & key stakeholders

=== Students 

* Recruiting
* Registration
* Academic Advisors
* Learning Communities / Housing

=== Workshop #1 Resources

* PowerPoint
++++
<iframe id="reading" style="border:1px solid #666CCC" title="PDF in an i-Frame" src="_attachments/AcademicPartnerWorkshop1.pdf" frameborder="1" scrolling="auto" height="1100" width="850" ></iframe>
++++

* Workshop Recording
++++
<iframe width="560" height="315" src="https://youtube.com/embed/p_HFCgvuTXI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

== Session 2:  Wed, February 8th

=== Seminar

_Seminar is a credit hour course is offered fall and spring to provide students experiential learning (no lectures or exams) with data science tools and large data sets on HPC clusters. Semester one covers R and SQL, semester two covers Python, and sessions three through eight cover advanced topics. View the link:https://the-examples-book.com/projects/current-projects/fall2022/syllabus[syllabus] and link:https://the-examples-book.com/projects/current-projects/10100-2022-projects[content for semester one]._

* Course Content
* Experiential learning
* R, Python, SQL
* Project Writing

=== Technical support & Research computing 

* Research computing at your university 
* Student support 
* Anvil
* Examples Book

=== Workshop #2 Resources

* PowerPoint
++++
<iframe id="reading" style="border:1px solid #666CCC" title="PDF in an i-Frame" src="_attachments/Academic Partner Workshop2.pdf" frameborder="1" scrolling="auto" height="1100" width="850" ></iframe>
++++

* Workshop Recording
++++
<iframe width="560" height="315" src="https://youtube.com/embed/WMiYrUEgt6E" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

== Session 3:  Wed, February 22nd

=== Business Partnerships & Recruiting Industry Sponsored Projects

* How to find potential industry partners
* Roadmap to the partnership process
* Building projects
* Building the right project teams (experience, skills, etc.)
* Mentor expectations for support
* Sponsored Research vs. Corporate Partners
* Feedback & Evaluation

link:https://the-examples-book.com/crp/mentors/partner[Roadmap to partnership] process 

=== Workshop #3 Resources

*PowerPoint
++++
<iframe id="reading" style="border:1px solid #666CCC" title="PDF in an i-Frame" src="_attachments/Academic_Partner_Workshop_3.pdf" frameborder="1" scrolling="auto" height="1100" width="850" ></iframe>
++++

*For a copy of the workshop recording, please email* jljud@purdue.edu


== Session 4: Wed, March 8th 

=== Corporate Partners: Course Management

* Agile Project Management
* Syllabus & Course Structure
* Communication Platforms
* TAs
* Team Building

=== Workshop #4 Resources

*PowerPoint
++++
<iframe id="reading" style="border:1px solid #666CCC" title="PDF in an i-Frame" src="_attachments/Academic Partner Workshop4.pdf" frameborder="1" scrolling="auto" height="1100" width="850" ></iframe>
++++

* Workshop Recording
++++
<iframe width="560" height="315" src="https://youtube.com/embed/U6K1w8rxpfo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++


== Session 5: Wed, March 22nd

=== Legal 

* NDAs
* Sponsor Acknowledgments
* IP 

=== Feedback & Final Questions

=== Workshop #5 Resources

*PowerPoint
++++
<iframe id="reading" style="border:1px solid #666CCC" title="PDF in an i-Frame" src="_attachments/Academic Partner Workshop5.pdf" frameborder="1" scrolling="auto" height="1100" width="850" ></iframe>
++++

*Workshop Recording
++++
<iframe width="560" height="315" src="https://youtube.com/embed/xcp2P4opEwU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++
