= TDM 10100: Python Project 4 -- 2024

**Motivation:** Being able to write Python to perform tasks and analyze data is one thing. Having other people (or you, in the future) read your code and be able to interpret what it does and means is another. Writing clean, organized code and learning about basic syntax and whitespace rules is an important part of data science. This project will be dedicated to exploring some syntactic and whitespace-related rules that we've glossed over in previous projects, along with exploring some industry standards that are good to keep in mind when working on your own projects - both for this class and in the rest of your life.

**Context:** We'll continue to use conditionals, lists, and looping as we move forward, but we won't be spending as much time on reviewing them individually. Feel free to review past weeks' projects and work for refreshers, as the groundwork we've laid up to this point will be the foundations we build on for the rest of this semester.

**Scope:** Syntax, whitespace, nesting/code blocks, styleguides

.Learning Objectives:
****
- Know what syntax is and why its important
- Understand the role whitespace plays in Python and how to use it
- Develop some basic ideas about how to make your code look cleaner and limit nesting/spaghetti code
- Read up on some basic industry standards regarding style
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about project submissions xref:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset(s):

- /anvil/projects/tdm/data/olympics/athlete_events.csv

== Questions

=== Question 1 (2 pts)

Firstly, let's explore _syntax_. Syntax is, simply put, a set of rules that are agreed upon to dictate how to structure a language. In the code world, _syntax_ often refers to the specific **keywords** that reside in each programming language, along with what symbols are used for things like operators, looping and conditionals, functions, and more! Additionally, syntax can refer to spacing. For example, while the below code is valid and will not produce errors if run by a _C_ compiler that is following _C syntax_, it would not work at all if run by a Python interpreter following _Python syntax_:

[source, C]
----
for (i=0;i<10;i++) {
    printf("We're on loop %d",i);
    }
----

Another good example would be operators. In `R`, for example, the modulus operator is `%%`. In `Python`, however, you (hopefully now) know that the modulus operator is just `%`. Below is some Python code using concepts we covered in previous projects. However, it has some syntax errors in it that make it error out. Your task in this question is to find the syntax errors, correct them, and run the code to figure out the secret sentence that is printed when the code is correct! (Hint: each line has one syntax error to fix, for a total of 7 syntax errors to fix! Running the code should give you hints as to what the errors are.)

[source, python]
----
secret == ["P", "i", "ur", "s", "du", " a", "e ", "ma", "Dat", "z", "a", "i", " M", "ng", "ine ", "!"]

for i in range(0, len(secret), 2)
    print(secret[i], end=""
for i in range(1, len(secret)) {
    if i % 2 = 1:
        print(secret(i), end="")
}    
----

.Deliverables
====
- The fixed version of the above code, and the secret sentence that results from running it
====

=== Question 2 (2 pts)

As we move from the idea of syntax onto style and code cleanliness, let's first discuss a unique feature of Python: `whitespace`. While many other languages like C, R, JavaScript, Java, C++, and Rust provide explicit characters that denote when code is "inside of" a loop or conditional (think brackets `{}`, parentheses `()`, etc.) Python does not. Instead, Python uses the amount of `whitespace` before the code on that line starts in order to determine whether or not it is within something else. We've been doing this automatically in previous projects, but now let's explore it more intentionally. Take a look at the two examples below:

[source, python]
----
# example 1
for i in range(5):
    print("Loop Number", i)
    print("Loop complete!")

# example 2
for i in range(5):
    print("Loop Number", i)
print("Loop complete!")
----

As you can see by running this code in a Jupyter notebook, the results of each example are drastically different based only on indentation.

[IMPORTANT]
====
The amount of space before an indented piece of code is important. While the author of this project is fond of using `tab`s for his indentation, using 2 spaces or 4 spaces for each level of indentation is also quite common. However, you **CAN NEVER MIX** different styles of indentation. If part of your code is indented using tabs, and part is indented using spaces, it will not run.
====

While often the Python interpreter will catch errors in your code in advance and stop the code from running, this is not always the case (as demonstrated in the above examples). Many times, when Python whitespacing is not done as intended, errors that don't stop your code from running will happen. These are often called 'runtime errors' and can be tricky to catch until they start causing unintended results in your code.

Below is some Python code to count the number of times the number "4" appears in a randomly generated list of 1000 numbers. However, this code contains 2 whitespace errors. Fix it so that it correctly counts the number of times "4" appears in our list.

[source, python]
----
import random

# generate a 1000 number list of random numbers from 1-100
number_list = random.choices(range(1,100), k=1000)
count = 0

for number in number_list:
    if number == 4:
        print("4 Detected!")
    count += 1

    print("Loop complete! Total number of 4's:", count)
----


.Deliverables
====
- Results of running the code above after correcting the two whitespace errors present
====

=== Question 3 (3 pts)

Great! We now have a more formal idea behind the indentation we've been doing throughout our projects so far. Now let's explore the concept of `nesting`. `Nesting` is when some code falls 'within' other code. For example, actions within a conditional or a for loop are nested. Generally, we try and keep nesting to a minimum, as tracking 10 levels of indentation in your code to see what falls within where can be quite difficult visually. Here is an important example to prove that being careful while nesting is necessary, using the Olympics data we used in a previous project:

[source, python]
----
import pandas as pd

# read in our olympics dataframe
olympics_df = pd.read_csv("/anvil/projects/tdm/data/olympics/athlete_events.csv")

# pick just the olympian from row 3 of our dataframe
my_olympian = olympics_df.iloc[3]

# what does any of this mean? Very unreadable, bad code
if my_olympian["Sex"] == "M":
    if my_olympian["Age"] > 20:
        print("Class 1 Athlete!")
        if my_olympian["Age"] < 30:
            print("Class 2 Athlete!")
        if my_olympian["Height"] > 180:
                if my_olympian["Weight"] > 60:
                    print("Class 3 Athlete!")
        print("Class 4 Athlete!")
----

If you think this code is unreadable and its hard to tell what it means to be a class 1 vs 2 vs 3 vs 4 athlete (classes entirely made up), you're correct. Nesting unnecessarily and in ways that don't make code easy to read can quickly render a decent project into unreadable spaghetti.

Take a good look at the above code. Are there any unnecessary classes that mean the same thing? How could you rewrite it using all that you've learned so far to make it more readable (for example, using _else-if_ and _else_)? For this question, copy this code into your Jupyter notebook and make changes to render it readable, reducing nesting as much as possible. Your final code should have the following features:

- 3 classes, with the one unnecessary class removed
- No more than a maximum level of nesting of 2 (aka, 3 indents on the most indented line)
- Should produce the same results as the messy code (minus the unnecessary class)

[NOTE]
====
One good way to test your work here would be to run your clean version and the messy version on a couple different olympians (by changing `X` in the `my_olympian = olympics_df.iloc[X]` line) and making sure both versions produce the same results.
====

.Deliverables
====
- A cleaned up version of the messy code provided
- The results of running both clean and messy versions of the code on the same athlete
====

=== Question 4 (3 pts)

For our last question on this project, we want you to explore some different style conventions suggested as standards for writing Python, and write about a few that sound interesting to you. Please visit https://peps.python.org/pep-0008/[this official Python Style Guide] and pick 3 different conventions discussed in the guide. For each convention, write a snippet of code that demonstrates the convention. At the end of the question, in a markdown cell, write at least a sentence or two about each convention describing what it is and why it is important.

.Deliverables
====
- 3 Python code snippets demonstrating three different style conventions
- a markdown cell with at least 3-6 sentences describing the conventions picked and their utility
====

== Submitting your Work

If you're at this point, you've successfully capped off our introduction to whitespace, nesting, and styling code in Python. Leaving this project, you should have a better understanding of a lot of the less straightforward elements of writing code and how more abstract concepts like style and indentation can drastically affect the quality of your code, even if it functions as intended. Remember that this was only an introduction to the topics, and throughout your career you'll always be picking up new tricks and style conventions as you gain more experience and meet new people.

Next week, we'll look more deeply at variables, variable types, and scope, and learn how profound the statement `x = 4` in Python really is!

.Items to submit
====
- firstname_lastname_project4.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/current-projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====