= GIS (Geographic Information System)

[quote,USGS]
A Geographic Information System (GIS) is a computer system that analyzes and displays geographically referenced information. It uses data that is attached to a unique location.


== Common Applications

Any organizations that heavily uses maps uses GIS. This includes energy, navigation, federal institutions, biology/ecology, construction, urban planning, geology, and many more. 

== Resources

All resources are chosen by Data Mine staff to be of decent quality, and most if not all content is free. 

=== Websites

https://www.in.gov/gis/[Indiana GIS Portal]

https://education.nationalgeographic.org/resource/geographic-information-system-gis/[GIS (National Geographic)]

https://www.cdc.gov/gis/what-is-gis.htm[What is GIS? (CDC)]

https://www.esri.com/en-us/what-is-gis/overview[What is GIS (Esri, makers of ArcGIS)]

=== Videos

https://www.youtube.com/watch?v=IRJC67zm6nk[GeoSpatial Analysis With Python For Beginners(~1 hour)]

https://www.youtube.com/watch?v=9V_Mz7NDy3o[Geographic Information Systems (GIS): Dan Scollon at TEDxRedding (~16 minutes)]

=== Books

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/ufs51j/alma99169166877001081[Applied Spatial Data Analysis with R (2013)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99169497768901081[Introduction to GIS programming and fundamentals with Python and ArcGIS (2017)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/ufs51j/alma99170383759801081[GIS fundamentals : a first text on geographic information systems (2019)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99170245248301081[Python for ArcGIS pro : automate cartography and data analysis using ArcPy, ArcGIS API for Python, notebooks, and pandas (2022)]

=== Articles

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_proquest_miscellaneous_1770316757[“FluvialCorridor”: A new ArcGIS toolbox package for multiscale riverscape exploration (2015)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_gale_infotracacademiconefile_A522699139[IG-Mapper: A new ArcGIS® toolbox for the geostatistics-based automated geochemical mapping of igneous rocks (2017)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_plos_journals_2125646584[Digital soil mapping in the Bara district of Nepal using kriging tool in ArcGIS (2018)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_crossref_primary_10_53550_EEC_2022_v28i04_082[Physical-Chemical Properties and Spatial Distribution of Heavy Metals in Agriculture Soil in Al-Qadisiyah City by using ArcGIS and Multivariate Analysis (2022)]