= Meeting Etiquette

== In-Person Meeting Etiquette

**RSVP Responsibility Reminder:** If you RSVP that you will attend a meeting or event, please make every effort to follow through and attend. If your plans change and you’re unable to attend, it is important to cancel your reservation, notify the host, and/or e-mail datamine@purdue.edu as soon as possible. This helps us plan effectively and shows respect for everyone’s time and effort.

**Dress Code:** Match the tone of the meeting (e.g. business casual)

**Be prepared:**

- Review bio and agenda (if applicable)
- Research the speaker and come with 1-2 questions to ask
- Be at least 5 minutes early to the meeting location to settle in your seat. Tardiness can disrupt the flow and shows a lack of respect for others' time.
- Take all needed supplies with you:  notebook, pens, etc.
- Turn off and put away all electronic devices.  If you need to take notes, it is less distracting to use paper/pen.
- Give the lecturer your full attention and practice active listening (occasional nodding, make eye contact).
- Ask questions at the appropriate time.  Introduce yourself and speak loudly and clearly.
- Do not eat while at the meeting unless it is stated in the invite that a meal is to be provided or to bring your own meal.
- Wait until the meeting is officially concluded to leave
- If you have any questions that were not answered, don’t hesitate to follow up and thank the meeting host.

== Online Meeting Etiquette

- Test your sound and video before joining the meeting to ensure it is connected properly.  Check your name is listed correctly on the screen and use first and last name if possible.
- Ensure you have a quiet and professional space to engage in the meeting.  Check your background is not distracting or use a virtual background.
- Ensure you have a charger set up for your computer, keyboard, mouse, etc. and necessary materials like notebook, pen, etc.
- Log on to the meeting a few minutes early
- Make sure your camera is on, and your mic is off when joining a meeting.  Keep your camera on during the meeting.  If you have a technical issue – make sure your default blank screen is a professional photo.
- Do not type on your keyboard unless you are using the chat feature for the meeting.  If you need to take notes, it is less distracting to use paper/pen
