= Scrum Team Roles

Considering the personnel and their strengths on every sprint team is crucial for team success. Designated individual roles will help teams stay organized and will establish clear, individual responsibilities. The three roles on a scrum team are product owner, scrum master, and development team. 

The *product owner* is connected directly to the product’s business application. This person provides detailed explanation of product applications and tells the development team what is important to deliver. They set clear directions for the team, balance stakeholder expectations, and understand customer needs. 

The *development team* is comprised of the team members that will do the work. These team members take ownership of tasks made by the product owner and establish these tasks as a part of their sprint. Great development teams have a broad background of experiences and use their strengths to swiftly complete tasks. Their main responsibilities include delivering work throughout the sprint and ensuring transparency in their development. 

The final role within a scrum team is the *scrum master*. This role ensures that scrum is running smoothly and effectively. They are the bridge between product owners and the development team by coordinating valuable product updates with product owners and ensuring work gets completed by the development team. Scrum masters ensure transparency between all team members, create defined sprint schedules, teach sprint values, and most importantly, serve the scrum team to allow for smooth development. 

== Scrum Team Roles in The Data Mine

The Data Mine has a natural definition of who takes on what roles within a scrum team. 

Corporate partner mentors take on the role of product owner because of their direct connection to the business. 

Purdue students make up the development team and perform the work necessary to complete the project. 

TAs work as scrum masters and are the bridge between CP mentors and Purdue students. They establish Agile management and teach scrum to the team. 

== Team Breakdown

A proper breakdown of a Data Mine Corporate Partners team can aid a team in creating a collaborative and efficient space. Depending on team size, often times a great approach is to break the team down into sub-teams focused on specific parts of the project. For example, with a team size of 15 people and a project focused on software development for a web app, a sub-team approach might include a data architecture group, data science group, data engineering group, front end development group, and back end development group with a few people on each team. 

[IMPORTANT]
====
These sub-teams should be tailored based on team member preferences and skills in order to prioritize development efficiency and team well-being. 
====

== How to Form Sub-Teams

The first step in forming the best sub-teams possible for a project is to get to know everyone on the team. Learning about each team member's skills and preferences will help when organizing the team and will ideally allow each team member feel passionately about the work they will be doing on the team. One strategy for collecting this information quickly is to use an online survey, asking about each team members prior experiences, learning preferences, and skills (technical and team focused).

[TIP]
====
Check out a sample survey here: https://purdue.ca1.qualtrics.com/jfe/form/SV_cCM5c0Glm7Qx8qx
====

After working with the team to collect this information, the next step is to form the sub teams. Use the information collected to form groups that are tailored towards team member strengths and learning goals. The goal when forming the sub teams is to create a balance of experience with learning preferences so sub-team members will merge and work well together. For example, pairing more experienced team members with new developers may be a good approach to allow for collaboration and menotorship between two individuals in different points of their professional and academic careers. 

Each sub-team will ultimately be dependent on team size and makeup so creating the best sub-teams will be a challenge to get right immediatley. Thus, after teams are formed, it is important to ask for feedback from your team to ensure each team member is comforatble with their placement. 

[TIP]
====
Do regular check-ins with your team to be confident that everyone on the team enjoys the work they are doing on their sub-team, and it is okay for team-members to move around between sub-teams if preferences do change.
====