WELCOME WELCOME WELCOME WELCOME WELCOME!


The lesson plan is structured in a gentle approach where anyone with any background is able to learn about data analysis and start building their skills in data science. 

If you feel so overwhelemed, that means we did a very poor job and any feedback is very welcomed! 

[NOTE]
====
This exercise assumes that you have a Purdue account and have the access to our depot. If not, please contact us datamine@purdue.edu. 
====

Get started by opening a Jupyter notebook in Brown. 

Please view the video for the instructions.
++++
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&playerId=kaltura_player&entry_id=1_rqcgh4rs&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_la6qsg5v" width="608" height="402" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="TDM-BrownAccess-ASL"></iframe>
++++
Open a Jupyter notebook in Brown using your Purdue account. 

Video with ASL and closed captions.

* xref:attachments$video-transcript-brown-access.txt[Video Transcript]

Sincerely, 

 Kevin 2.0