= Sprint #3

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 2/8
|Mon 2/5

|*Sprint End Date*
|Wed 2/21
|Sun 2/18

|*Due Date*
2+| Wed 2/21 by 11:59 PM ET

|===

== Sprint Tasks


=== &#10003; Purdue Data Classification and Handling Training (New Students Only)

As soon as possible, complete Purdue's Data Classification and Handling Training. This training is required for all students who will be working with data in The Data Mine. If you believe that data was incorrectly handled or shared, please notify datamine@purdue.edu immediately.

*When:* As soon as possible!

*What:*  Purdue students need to complete https://www.eventreg.purdue.edu/WebCert/CourseListing.aspx?master_id=5398&master_version=1&course_area=CERT&course_number=340&course_subtitle=00[Data Classification and Handling Training]. NDMN & IDMN students need to review https://the-examples-book.com/crp/students/_attachments/Data_Classification_and_Handling_Educational_Resources.pdf[Data Classification and Handling Powerpoint] There is nothing to submit.

*Where:* https://www.eventreg.purdue.edu/WebCert/CourseListing.aspx?master_id=5398&master_version=1&course_area=CERT&course_number=340&course_subtitle=00[Purdue Data Classification and Handling Training] or https://the-examples-book.com/crp/students/_attachments/Data_Classification_and_Handling_Educational_Resources.pdf[NDMN & IDMN students]. There is nothing to submit.

=== &#10003; Professional Development 

The Data Mine Corporate Partners program is a professional development program. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

In each sprint, you will complete one https://www.gradescope.com/[Gradescope Quiz] on this sprint's professional development topics.

++++
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}

.accordion:after {
  content: '\002B';
  color: #777;
  font-weight: bold;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2212";
}

.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>

<button class="accordion">Data Security</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, February 21, 2024 at 11:59 PM ET. Late work will not be accepted.	</p>
<br>
	</div>
	<div>
		<p><b>What: </b>Please <a href="https://the-examples-book.com/crp/students/datasecurity">read about data security in The Data Mine</a> and take the quiz in Gradescope.</b></p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 3: Professional Development".</p>
<br>
  	</div>
	<div>
<p><b>Why: </b> The Data Mine Corporate Partners students work with proprietary data from many company. It is important to understand the importance of data security and how to protect the data you are working with. </p>
<br>
  </div>
</div>
<button class="accordion">Teamwork</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, February 21, 2024 at 11:59 PM ET. Late work will not be accepted.
		</p>
<br>
	</div>
	<div>
		<p><b>What: </b>Watch <a href="https://www.youtube.com/watch?v=0t_XUUcM1ng">  Being a good Team member </a> (4 minutes).</p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 3: Professional Development".</p>
<br>
  	</div>
	<div>
		<p><b>Why: </b> These concepts may not be new to you, but learning how to be an effective team member is an important skill to have when working on data mine projects with companies. </p>
<br>
  </div>
</div>

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

</body>
</html>
++++

=== &#10003; Sprint #3 Report 

*When:* Due Wednesday, Febuary 21, 2024 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in the Sprint #3 Report accessed on Gradescope. You can draft your answers in a separate document then you will write your answers directly in the Gradescope assignment. 

*Where:* link:https://www.gradescope.com/[Gradescope] 
