= Sprint #2

// == Intro Video

// ++++
// <iframe width="560" height="315" src="https://www.youtube.com/embed/B9CIIUJWGlc?si=fjPQqSMoaPEvEYhX" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
// ++++

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 1/25
|Mon 1/22

|*Sprint End Date*
|Wed 2/7
|Sun 2/4

|*Due Date*
2+| Wed 2/7 by 11:59 PM ET

|===

== Sprint Tasks

=== &#10003; Github on Anvil (Setting up ssh keys)

As soon as possible, set up your ssh key for Github on Anvil. ssh key are the way for github to verify that you are who you say you are. This will allow you to push and pull code from your team's repository and collaborate with your team members on github.

*When:* As soon as possible!

*What:*  xref:github_set_up.adoc[Set up ssh key on Github for Anvil]. There is nothing to submit for this item.

*Where:* xref:github_set_up.adoc[Setup Github on Anvil]

=== &#10003; Starter Guides

Use these starter guides to up-skill during the first couple of sprints. You will be using these tools throughout the semester on your semester!

*When:* When you are ready to upskill!

*What:* Review the following xref:starter-guides:ROOT:index.adoc[Starter Guides] and work with your TA to see which topics are relevant for your project - there is nothing to submit for this item.

*Where:* xref:starter-guides:ROOT:index.adoc[Starter Guides]

=== &#10003; Professional Development 

The Data Mine Corporate Partners program is a professional development program. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

In each sprint you will complete a few professional development-related tasks.

[IMPORTANT]
====
*CONTENT STILL UNDER CONSTRUCTION FOR SPRING 2024.*
====



++++
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}

.accordion:after {
  content: '\002B';
  color: #777;
  font-weight: bold;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2212";
}

.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>

<button class="accordion">Net-etiquette</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, February 2, 2024 at 11:59 PM ET. Late work will not be accepted.
		</p>
	</div>
	<div>
		<p><b>What: </b>Review <a href="https://the-examples-book.com/crp/students/online_meeting">Agile in The Data Mine Training</a>, participate in the Lego lab activity (new teams), and take the quiz.</b></p>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 2: Professional Development".</p>
  </div>
</div>
<button class="accordion">Kanban board</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, February 2, 2024 at 11:59 PM ET. Late work will not be accepted.
		</p>
	</div>
	<div>
		<p><b>What: </b>Watch <a href="https://www.youtube.com/watch?v=R8dYLbJiTUE"> Intro to Kanban in Under 5 Minutes (What is Kanban, Learn Kanban) </a> (4 minutes).</p>
	</div>
	<div>
		<p><b>Where: </b>Upload a screenshot of your team Kanban board on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 1: Professional Development".</p>
  </div>
</div>

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

</body>
</html>
++++

=== &#10003; Sprint #2 Report 

*When:* Due Wednesday, Febuary 7, 2024 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in the Sprint #2 Report accessed on Gradescope. You can draft your answers in a separate document then you will write your answers directly in the Gradescope assignment. 

*Where:* link:https://www.gradescope.com/[Gradescope] 


