= Sprint #2

// == Intro Video

// ++++
// <iframe width="560" height="315" src="https://www.youtube.com/embed/B9CIIUJWGlc?si=fjPQqSMoaPEvEYhX" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
// ++++

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 1/25
|Mon 1/22

|*Sprint End Date*
|Wed 2/7
|Sun 2/4

|*Due Date*
2+| Wed 2/7 by 11:59 PM ET

|===

== Sprint Tasks

=== &#10003; Github on Anvil (Setting up ssh keys)

As soon as possible, set up your ssh key for Github on Anvil. ssh key are the way for github to verify that you are who you say you are. This will allow you to push and pull code from your team's repository and collaborate with your team members on github.

*When:* As soon as possible!

*What:*  https://the-examples-book.com/crp/students/github_set_up[Set up ssh key on Github for Anvil]. There is nothing to submit for this item.

*Where:* https://the-examples-book.com/crp/students/github_set_up[Set up ssh key on Github for Anvil]

=== &#10003; Professional Development 

The Data Mine Corporate Partners program is a professional development program. We want to help you develop the skills you need to be successful in your career. We will have a variety of professional development activities throughout the semester.

In each sprint, you will complete one https://www.gradescope.com/[Gradescope Quiz] on this sprint's professional development topics.

++++
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}

.accordion:after {
  content: '\002B';
  color: #777;
  font-weight: bold;
  float: right;
  margin-left: 5px;
}

.active:after {
  content: "\2212";
}

.panel {
  padding: 0 18px;
  background-color: white;
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}
</style>
</head>
<body>

<button class="accordion">Online Meeting Net-etiquette</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, February 7, 2024 at 11:59 PM ET. Late work will not be accepted.	</p>
<br>
	</div>
	<div>
		<p><b>What: </b>Please <a href="https://the-examples-book.com/crp/students/online_meeting">read and watch the video about how to effectively participate in a virtual meeting</a> and take the quiz in Gradescope.</b></p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 2: Professional Development".</p>
<br>
  	</div>
	<div>
		<p><b>Why: </b> The Data Mine Corporate Partners students meet with their Corporate Partner Mentors online via Microsoft Teams every week. Being able to conduct yourself professionally in a virtual setting is an important skill for students to develop in The Data Mine.</p>
<br>
  </div>
</div>
<button class="accordion">Problem Solving</button>
<div class="panel">
	<div>
		<p><b>When: </b>Due Wednesday, February 7, 2024 at 11:59 PM ET. Late work will not be accepted.
		</p>
<br>
	</div>
	<div>
		<p><b>What: </b>Watch <a href="https://www.youtube.com/watch?v=ehRNriENFic">  Problem Solving in the Workplace </a> (9 minutes).</p>
<br>
	</div>
	<div>
		<p><b>Where: </b>Complete the knowledge check for this professional development training on <a href="https://www.gradescope.com/">Gradescope</a> in the assignment "Sprint 2: Professional Development".</p>
<br>
  	</div>
	<div>
		<p><b>Why: </b>These may not be new concepts to you, however, they can be applied in a new way based on the work your approaching and situation you are currently in. Learning the fundamental steps to problem-solving is an important skill to have in The Data Mine, since you are working with companies to create novel solutions to problems. </p>
<br>
  </div>
</div>

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight) {
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>

</body>
</html>
++++

=== &#10003; Sprint #2 Report 

*When:* Due Wednesday, Febuary 7, 2024 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in the Sprint #2 Report accessed on Gradescope. You can draft your answers in a separate document then you will write your answers directly in the Gradescope assignment. 

*Where:* link:https://www.gradescope.com/[Gradescope] 




