= TDM 10100: R Project 8 -- 2024

**Motivation:** In the previous project, we cemented the formal concept of functions and wrote our first functions. We also learned about more complicated functions with multiple arguments, and developed some versatile functions that we can apply to real data. In this project, we're going to learn how to build functions that we can apply to entire datasets at once and more!

**Context:** The previous project on functions, along with the prior knowledge of data science we've covered so far in the course

**Scope:** Advanced functions, apply, sapply, lapply, and tapply

.Learning Objectives:
****
- Be able to develop versatile, powerful functions
- Learn to apply transform whole columns or dataframes at once
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about project submissions xref:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset(s):

- `/anvil/projects/tdm/data/craigslist/vehicles.csv`

[IMPORTANT]
====
You will likely need 3 cores for this project, but should not need more than 4.
====

== Questions

=== Question 1 (2 pts)

Let's start out by reading in the data at `/anvil/projects/tdm/data/craigslist/vehicles.csv` into a dataframe (name it whatever you'd like), and then print the head of that dataframe. Take a few minutes to explore and acquaint yourself with the data.

We're going to provide a bit less structure for this question so that you can use this as an opportunity to test what you've learned so far, but the previous projects outline all of the concepts necessary to complete it. If you are struggling, feel free to read the note down below that details the specific projects to look back at if you are struggling with developing an approach to this question.

For this question, do two main things:
. print the head of the dataframe
. get a sorted (in descending order) table of the top 10 vehicle models for the year 2018

[NOTE]
====
- For a reminder about with logical indexing, revisit Project 3, Question 4
- For a reminder about `table()`, visit this https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/table[docs page]
====

To validate your answers, refer to the below list to see the top 3 models for this year, and their frequency:

- f-150: 862
- silverado 1500: 450
- escape: 379

.Deliverables
====
- The head of your vehicles dataframe
- A descending-order sorted table of the top 10 vehicle models for the year 2018
====

=== Question 2 (2 pts)

Now that we have some logic to get us the most popular model of vehicle for the given year, let's make a function that uses this logic to tell us interesting information! Taking as input a year, your function should return a table of the 20 most popular vehicle models for that year.

Here is a basic function signature to get you started:

[source, r]
----
popular_models_for_year <- function(year) {
    # insert your function's logic here
}
----

To validate your function, print the results of running it on the year 2018. Is it the same as the results you got in the last question? If not, you should revisit your logic and see why.

Next, make a new function named `top_model_for_year()` that returns only the name of the most popular vehicle model for that year. If you aren't sure where to start with this, think about it this way: we can use the code from the function we just wrote, but now, instead of the top 10 models, we only want the top 1. We can use `names()` to retrieve the names in a table, like so: `names(mytable)` returns c(name1, name2, ...).

There are a few different ways you could do this (i.e. indexing, changing arguments to `head()`), and any are acceptable as long as they return the expected top model.
 
Again, test your function on 2018. Does it return 'f-150' as expected?

.Deliverables
====
- a function `popular_models_for_year()` that gets a table of the top 10 vehicle models for a given year
- a function `top_model_for_year()` that gets the name of the most popular vehicle for a given year.
====

=== Question 3 (2 pts)

Fantastic. Now that we've created a function that can easily get us the most popular vehicle for a given year, let's incorporate this information back into our dataframe and learn about a useful family of functions in the meantime. 

The 'apply' functions in R are super useful, and each provide some different version of applying a function over a whole dataframe. Give the below (non-exhaustive) list of apply-family functions a once-over, paying special attention to some of the provided examples, before attempting to complete the task for this question.

- apply: runs a function across every row (or column) of a dataframe, returning a list of results
- lapply/sapply: runs a function on a list/vector, returning a list/array/dataframe of results of the same length as the input list
- tapply: runs a given function on every value in a column, grouping by another specified column (this one is tough to understand without looking at an example)

[NOTE]
====
`lapply()` and `sapply()` are extremely similar, and largely differ in the type of object that they return. `lapply()` returns a list of values, where `sapply()` returns an array/dataframe of values. In many cases, they can be used relatively interchangeably.
====

[source, r]
----
# create an example dataframe with some playing cards
cards_df <- data.frame(card_name=c("Ace","King","Queen","Jack","3","2","1"),
                        card_suit=c("Clubs","Clubs","Hearts","Spades","Diamonds","Diamonds","Diamonds"),
                        lowest_card_cost=c(15,13,10,9,3,2,1),
                        highest_card_cost=c(500,200,100,90,30,20,10))
head(cards_df)

# apply example:
# gets mean card value across columns (mean lowest and highest card costs)
print("Average lowest and highest card cost:")
apply(cards_df[3:4], 2, mean)

# lapply example:
# converts all our costs from USD to CAD
usd_to_cad <- function(usd) {
    return (usd * 1.36)
}
print("Canadian lowest card value")
lapply(cards_df$lowest_card_cost, usd_to_cad)

# tapply example:
# show the mean highest cost of each suit type in our dataframe
print("Mean Highest Cost by Suit:")
tapply(cards_df$highest_card_cost, cards_df$card_suit, mean)
----

[NOTE]
====
For additional explanation on these functions, including more examples, please refer to https://www.geeksforgeeks.org/apply-lapply-sapply-and-tapply-in-r/[this wonderful GeeksforGeeks article].
====

Your task for this question is straightforward: Print the most commonly occurring value for each column of our data, using `apply()` in conjunction with a function that takes as input a column and returns as output the most commonly occurring value for that column. If you'd like to try and create this function on your own, [this stackoverflow post] is a fantastic resource. Otherwise, you can make some _slight_ changes to the function that you wrote previously during this project that gets the most common vehicle for a given year in order to get the most common value in a given column. (Hint: You don't have to consider the year, or any other factors, in this function. It is just the column as a whole that needs to be analyzed)

[NOTE]
====
If you're struggling with this question, take a look back at the previous question's work. Is there a way we can use a `sorted()` `table()` to figure out the most common value?
====

.Deliverables
====
- The most common value in each column of the vehicles dataframe
====

=== Question 4 (2 pts)

Let's continue on our journey with the 'apply' family with `lapply()`. To recap what was discussed previously, lapply takes a given column and applies a function to each element in that column, returning a vector of the same length as the original column, containing the results of the function for each element. Again, the example provided in the last question (and provided again below, for your convenience) is a great way to test this and see it in action.

[source, r]
----
# create an example dataframe with some playing cards
cards_df <- data.frame(card_name=c("Ace","King","Queen","Jack","3","2","1"),
                        card_suit=c("Clubs","Clubs","Hearts","Spades","Diamonds","Diamonds","Diamonds"),
                        lowest_card_cost=c(15,13,10,9,3,2,1),
                        highest_card_cost=c(500,200,100,90,30,20,10))
head(cards_df)

# lapply example:
# converts all our costs from USD to CAD
usd_to_cad <- function(usd) {
    return (usd * 1.36)
}
print("Canadian lowest card value")
lapply(cards_df$lowest_card_cost, usd_to_cad)
----

For this question, we want you to use lapply() to create a new column `popular_model_by_year` containing the most popular model and manufacturer, respectively, for the year of the given row. We've provided some basic instructions for the given task, along with some skeleton code for you to start from, below. 

. First, get a list of unique years in the data
. Then, use your `top_model_for_year()` function from earlier to create a list where the names are the `as.character(year)` and the values are the top model for the given year
. Define a mapping function, year_to_model, that takes as input a year and returns as output the model with that year as a name from the list you just created
. Define a new column, `year_top_model()`, in your dataframe, that is filled in by using lapply and your mapping function `year_to_model()`.
. Print two rows of the data to check your work

[source, r]
----
# HINT: You can use unique() to get a list of all the years
years <- # FILL THIS IN

# use your "top_model_for_year()" function to get the model for each year and add it to a named list
# you're aiming to get a list like c("2018": "f-150", "1900": "model T")
models_years <- setNames(as.vector('''use lapply here to get the top models for each year'''), as.character(years))

# map year to model using our models_years function
year_to_model <- function(year) {
    return # FILL THIS IN
}

# use lapply with your year_to_model function
vehicles$year_top_model <- # FILL THIS IN

# Check your answers!
print(vehicles[29, "year_top_model"]) # => This should print "f-150"
print(vehicles[30, "year_top_model"]) # => This should print "ranger supercab xl pickup"
----

.Deliverables
====
- Use lapply to create the `year_top_model` column as specified above
- Run the provided `Check your answers!` section and be sure they match the expected results
====

=== Question 5 (2 pts)

Let's finish this project out with one of the most useful functions in the `apply` family, and one of the more useful R functions as a whole (especially for data scientists): `tapply()`. `tapply()` is extremely powerful, as it allows us to run grouping functions like `mean()` on a specific column of a dataframe, grouping by another column in the dataframe. For example, `tapply(mydf$price, mydf$condition, median)` will return the median price for each condition in your dataframe. Take a look at the provided example below, and try running it on your own so that you understand tapply. Once you've done this, you can start the task for this question.

[source, r]
----
# create an example dataframe with some playing cards
cards_df <- data.frame(card_name=c("Ace","King","Queen","Jack","3","2","1"),
                        card_suit=c("Clubs","Clubs","Hearts","Spades","Diamonds","Diamonds","Diamonds"),
                        lowest_card_cost=c(15,13,10,9,3,2,1),
                        highest_card_cost=c(500,200,100,90,30,20,10))
head(cards_df)

# tapply example:
# show the mean highest cost of each suit type in our dataframe
print("Mean Highest Cost by Suit:")
tapply(cards_df$highest_card_cost, cards_df$card_suit, mean)
----

Using `tapply()`, calculate the average vehicle price in our dataframe for each given year and then again for each given state. Are there any results you found interesting or surprising? In a markdown cell, write 3-4 sentences about your results analyzing the trends in each result and noting any surprising features of the data you've discovered.

.Deliverables
====
- The average vehicle price for each year in our data
- The average vehicle price for each state in our data
- At least 3-4 sentences analyzing the results of your `tapply()` operations
====

== Submitting your Work

This project was quite complex, and it is okay to struggle and stop to finish your work later, or even to try and do the project again another day to review and continue to grow your understanding. The `apply()` family of functions, and the concept of a function in general, are extremely valuable tools to have in any field, and mastering the ability to write modular functions and apply them to entire dataframes at once to improve or extend on existing data analyses will take your skills to the next level.

Next week we will take a step back and start to look at packages in R, which are essentially collections of functions that others have written that can **DRASTICALLY** reduce your workload and make your code much faster. As you've likely come to learn, reducing repition is one of the key paradigms of good code, and packages are a fantastic method towards this end.

Take a break, drink some water, enjoy some fresh air, and I hope you all have a great rest of your week. I look forward to the opportunity to learn with you all on the next project.

.Items to submit
====
- firstname_lastname_project8.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====