= TDM 10100: R Project 12 -- 2024

**Motivation:** Up to this point, we've been hyperfocused on numbers and letters; we've learned how to handle, transform, store, and reformat data to do whatever we need. However, as important as data is, most people don't enjoy staring at spreadsheets and attempting to parse out patterns and meaning. That is why **visualization** is such a key aspect of data analysis. This project will be focused on using `ggplot2` to create clear plots of data trends, and prepare us for the more complex topics that we'll broach in project 13.

**Context:** A working understanding of piping, `dplyr`, and common `tidyverse` utilities will be helpful for this project.

**Scope:** Data visualization, `ggplot2`, `dplyr`, `tidyverse`, R

.Learning Objectives:
****
- Ipsum lorem
- Ipsum lorem
- Ipsum lorem
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about project submissions xref:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset(s):

- Ipsum lorem
- Ipsum lorem

== Questions

=== Question 1

Ipsum lorem dolor sit amet, consectetur adipiscing elit

.Deliverables
====
- Ipsum lorem
====

=== Question 2

Ipsum lorem dolor sit amet, consectetur adipiscing elit

.Deliverables
====
- Ipsum lorem
====

=== Question 3

Ipsum lorem dolor sit amet, consectetur adipiscing elit

.Deliverables
====
- Ipsum lorem
====

=== Question 4

Ipsum lorem dolor sit amet, consectetur adipiscing elit

.Deliverables
====
- Ipsum lorem
====

=== Question 5

Ipsum lorem dolor sit amet, consectetur adipiscing elit

.Deliverables
====
- Ipsum lorem
====

== Submitting your Work

This is where we're going to say how to submit your work. Probably a bit of copypasta.

.Items to submit
====
- Ipsum lorem
- Ipsum lorem
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====