= TDM 10100: R Project 12 -- 2024

**Motivation:**  Some files are too big to read into R.  We practice methods for extracting the portions of a file that we need.

**Context:**  The `fread` function allows us to read a portion of a file (either a small number of rows, and/or a small number of columns).

**Scope:**  We learn how to work with enormous files in R, if we only need a portion of the file in our analysis.

.Learning Objectives:
****
- Learn how to apply functions to large data sets and extract information.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about project submissions xref:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset(s):

- `/anvil/projects/tdm/data/iowa_liquor_sales/iowa_liquor_sales.csv` (Iowa liquor sales)

== Questions

[WARNING]
====
Please use 2 cores in your Jupyter Lab session for this project.
====

=== Question 1 (2 pts)

First load:  `library(data.table)` so that you have the `fread` function available, and also `options(repr.matrix.max.cols=50)` so that you can see 50 columns.

If you try to read the entire file `/anvil/projects/tdm/data/iowa_liquor_sales/iowa_liquor_sales.csv` then the `seminar-r` kernel will crash.

Instead, use `fread` with the option `nrows=1000` so that you can see (only) the first 1000 rows of the data frame.

a.  Which columns contain the `Store Number`, `Store Name`, `Address`, `City`, and `Zip Code`?

b.  Use the `select` option in `fread` to read the entire data set, but *only* those 5 columns of the data.  What is the dimension of the data set?  (Hint: it should now be 5 columns and more than 27 million rows.)

.Deliverables
====
- Which columns contain the `Store Number`, `Store Name`, `Address`, `City`, and `Zip Code`?
- What is the dimension of the data set?
====


=== Question 2 (2 pts)

Now let's find the most popular 10 stores in two different ways:

a.  Use the `table` command to find the 10 most popular values of the `"Store Number"`

b.  Use the `table` command to find the 10 most popular values of the `"Store Name"`

c.  Use the `table` command to find the 10 most popular values of these three columns pasted together: `Address`, `City`, `"Zip Code"`

d.  Do your answers to parts (a) and (b) seem to agree?  Do your answers to parts (a) and (c) seem to agree?


.Deliverables
====
- a.  A table with the 10 most popular values of the `"Store Number"` and the number of occurrences of each.
- b.  A table with the 10 most popular values of the `"Store Name"` and the number of occurrences of each.
- c.  A table with the 10 most popular values of these three columns pasted together: `Address`, `City`, `"Zip Code"` and the number of occurrences of each.
- d.  Do your answers to parts (a) and (b) seem to agree?  Do your answers to parts (a) and (c) seem to agree?

====


=== Question 3 (2 pts)

For this question, use `fread` to read in the data set again, but this time, only read in the columns `"Zip Code"`, `"Category Name"`, `"Sale (Dollars)"`.




a. Write a function called `myindycities` that takes a year as the input and uses `tapply` to make a table of length 10, containing the top 10 cities in Indiana according to the sum of the amount of donations (in dollars) given in each city.

b. Test your function individually, one at a time, on the years 1980, 1986, and 1992.  For instance, if you run `myindycities(1984)`, the output should be something like:  `FT WAYNE: 44665 TERRE HAUTE: 52650 CARMEL: 53200 EVANSVILLE: 65250 SOUTH BEND: 68387 INDPLS: 76520 FORT WAYNE: 80882 ELKHART: 93171 MUNCIE: 104260 INDIANAPOLIS: 511935`


.Deliverables
====
- Write a function called `myindycities` that takes a year as the input and uses `tapply` to make a table of length 10, containing the top 10 cities in Indiana according to the sum of the amount of donations (in dollars) given in each city.
- Show the output of `myindycities(1980)` and `myindycities(1986)` and `myindycities(1992)`.
====

=== Question 4 (2 pts)

a. Use the list apply function (`lapply`) to run the function `myindycities` on each of the even-numbered election years 1984 to 1994 as follows:

[source,r]
----
myresults <- lapply( seq(1984,1994,by=2), myindycities )
names(myresults) <- seq(1984,1994,by=2)
myresults
----

b. Now use `par(mfrow=c(3,2))` and the sapply function too, but this time, make a `dotchart` for each entry in `myresults`.

[TIP]
====
Do not worry about the pink warning that appears above the plots.
====


.Deliverables
====
- Use `lapply` to show the results of `myindycities` for each even-numbered year from 1984 to 1994.
- Make a dotchart for each of the 6 years in part a.
====

=== Question 5 (2 pts)

a. Find the average number of stars in each of these four files:

`/anvil/projects/tdm/data/icecream/bj/reviews.csv`

`/anvil/projects/tdm/data/icecream/breyers/reviews.csv`

`/anvil/projects/tdm/data/icecream/hd/reviews.csv`

`/anvil/projects/tdm/data/icecream/talenti/reviews.csv`

b. Write a function `myavgstars` that takes a company name (e.g., either "bj" or "breyers" or "hd" or "talenti") as input, and returns the average number of stars for that company.

c. Define a vector of length 4, with all 4 of these company names:

[source,r]
----
mycompanies <- c("bj", "breyers", "hd", "talenti")
----
and now use the `sapply` function to run the function from part b that re-computes the values from part a, all at once, like this:

[source,r]
----
sapply(mycompanies, myavgstars)
----

.Deliverables
====
- Print the average number of stars for each of the 4 ice cream companies.
- Write a function `myavgstars` that takes a company name (e.g., either "bj" or "breyers" or "hd" or "talenti") as input, and returns the average number of stars for that company.
- Use `sapply` to run the function from part b on the vector `mycompanies`, which should give the same values as in part a.
====

== Submitting your Work

This project further demonstrates how to use the powerful functions in R to perform data analysis.


.Items to submit
====
- firstname_lastname_project11.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, comments (in markdown or with hashtags), and code output, even though it may not. **Please** take the time to double check your work. See xref:submissions.adoc[the instructions on how to double check your submission].

You **will not** receive full credit if your `.ipynb` file submitted in Gradescope does not **show** all of the information you expect it to, including the output for each question result (i.e., the results of running your code), and also comments about your work on each question. Please ask a TA if you need help with this.  Please do not wait until Friday afternoon or evening to complete and submit your work.
====

