= TDM 10100: R Project 12 -- 2024

**Motivation:** Up to this point, we've been hyperfocused on numbers and letters; we've learned how to handle, transform, store, and reformat data to do whatever we need. However, as important as data is, most people don't enjoy staring at spreadsheets and attempting to parse out patterns and meaning. That is why **visualization** is such a key aspect of data analysis. This project will be focused on using `ggplot2` to create clear plots of data trends, and prepare us for the more complex topics that we'll broach in project 13.

**Context:** A working understanding of piping, `dplyr`, and common `tidyverse` utilities will be helpful for this project.

**Scope:** Data visualization, `ggplot2`, `dplyr`, `tidyverse`, R

.Learning Objectives:
****
- Ipsum lorem
- Ipsum lorem
- Ipsum lorem
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about project submissions xref:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset(s):

- `/anvil/projects/tdm/data/youtube/USvideos.csv`
- Ipsum lorem

== Questions

=== Question 1 (2 pts)

As a first step, let's talk about the general structure when using `ggplot2`. You can think of a plot created with `ggplot()` as a series of layers that we add that determine the structure, style, and type of plot. For an example structure, along with a more generic version, see below:

[source, R]
----
# working example using real data
library(tidyverse)
a <- read_csv("/anvil/projects/tdm/data/youtube/USvideos.csv")

# specify data to plot, with color coming from comment_count
ggplot(a, aes(x=views, y=comment_count, col=comment_count)) + 
    # create scatterplot
    geom_point() + 
    # add color scaling based on comment count
    scale_color_gradient2(low="yellow", mid="red", high="purple") + 
    ggtitle("Demonstration Plot")

# ---------------------------------------------------------------

# generic example using placeholder names
library(tidyverse)
df <- read_csv("/path/to/data.csv")

# specify data to plot
ggplot(df, aes(x=column1, y=column2)) + 
    # create scatterplot
    geom_point() + 
    # set x, y axis labels and Plot Title
    xlab("Column1 Data")
    ylab("Column2 Data")
    ggtitle("Fake Plot")
----

[NOTE]
==== 
For a more detailed and official description of how ggplot calls should be structured, check out this official https://ggplot2.tidyverse.org/articles/ggplot2.html["Getting Started" guide].
====

Try removing specific lines from the working example provided above, swapping around the order of certain lines, or adding your own lines after reading through the linked documentation and see what happens! As I've noted before, experimentation is a _huge_ part of working with code, so don't be afraid to experiment, break things, kill your kernel and more! It's all steps towards a well-made end product.

For this question, first read the data from `/anvil/projects/tdm/data/youtube/USvideos.csv` into a data structure called `US_vids`, and then use `ggplot2` to create a scatterplot of `likes` versus `comment_count` for the US videos data. You don't have to worry about specifying a color of any type, but you should be sure that your plot has appropriate axes and plot titles (Hint: Look at the above example!).

.Deliverables
====
- A new data structure called `US_vids`
- A scatterplot of `likes` vs. `comment_count` for the `US_vids` data
====

=== Question 2 (2 pts)

Make a box-and-whisker of likes or comments

Build on box-and-whisker of likes or comments by splitting based on category_id

.Deliverables
====
- Ipsum lorem
====

=== Question 3 (2 pts)

Explore faceting, basic usage, and contrast it against splitting like in Question 3

https://stackoverflow.com/questions/57457872/how-to-use-ggplot-faceting-with-data-from-different-dataframes 

.Deliverables
====
- Ipsum lorem
====

=== Question 4 (2 pts)

Read in data from a different country, explore `geom_raster()` and using faceting to compare the boxplots for different countries

.Deliverables
====
- Ipsum lorem
====

=== Question 5 (2 pts)

Open ended design question regarding a plot type used in this project, demonstrating either splitting by column or faceting or something.


.Deliverables
====
- Ipsum lorem
====

== Submitting your Work

This is where we're going to say how to submit your work. Probably a bit of copypasta.

.Items to submit
====
- Ipsum lorem
- Ipsum lorem
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====