= TDM 10100: R Project 8 -- 2024

**Motivation:** In the previous project, we cemented the formal concept of functions and wrote our first functions. We also learned about more complicated functions with multiple arguments, and developed some versatile functions that we can apply to real data. In this project, we're going to learn how to build functions that we can apply to entire datasets at once, how we can pass in functions as arguments to other functions, and more!

**Context:** The previous project on functions, along with the prior knowledge of data science we've covered so far in the course

**Scope:** Advanced functions, apply, sapply, lapply, and vapply

.Learning Objectives:
****
- Be able to develop versatile, powerful functions
- Learn to apply transform whole columns or dataframes at once
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about project submissions xref:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset(s):

- /anvil/projects/tdm/data/craigslist/vehicles.csv

[IMPORTANT]
====
You will likely need 3 cores for this project, but should not need more than 4.
====

== Questions

=== Question 1 (2 pts)

Let's start out by reading in the data at "/anvil/projects/tdm/data/craigslist/vehicles.csv" into a dataframe (name it whatever you'd like), and then print the head of that dataframe. Take a few minutes to explore and acquaint yourself with the data.

We're going to provide a bit less structure for this question so that you can use this as an opportunity to test what you've learned so far, but the previous projects outline all of the concepts necessary to complete it. If you are struggling, feel free to read the note down below that details the specific projects to look back at if you are struggling with developing an approach to this question.

For this question, do two main things:
. print the head of the dataframe
. get a sorted (in descending order) table of the top 10 vehicle models for the year 2018

[NOTE]
====
- For a reminder about with logical indexing, revisit Project 3, Question 4
- For a reminder about `table()`, visit this https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/table[docs page]
====

To validate your answers, refer to the below list to see the top 3 models for this year, and their frequency:

- f-150: 862
- silverado 1500: 450
- escape: 379

.Deliverables
====
- The head of your vehicles dataframe
- A descending-order sorted table of the top 10 vehicle models for the year 2018
====

=== Question 2 (2 pts)

Now that we have some logic to get us the most popular model of vehicle for the given year, let's make a function that uses this logic to tell us interesting information! Taking as input a year, your function should return a table of the 20 most popular vehicle models for that year.

Here is a basic function signature to get you started:

[source, r]
----
popular_models_for_year <- function(year) {
    # insert your function's logic here
}
----

To validate your function, print the results of running it on the year 2018. Is it the same as the results you got in the last question? If not, you should revisit your logic and see why.

Next, make a new function named `top_model_for_year()` that returns only the name of the most popular vehicle model for that year. If you aren't sure where to start with this, think about it this way: we can use the code from the function we just wrote, but now, instead of the top 10 models, we only want the top 1. We can use `names()` to retrieve the names in a table, like so: `names(mytable)` returns c(name1, name2, ...).

There are a few different ways you could do this (i.e. indexing, changing arguments to `head()`), and any are acceptable as long as they return the expected top model.
 
Again, test your function on 2018. Does it return 'f-150' as expected?

.Deliverables
====
- a function `popular_models_for_year()` that gets a table of the top 10 vehicle models for a given year
- a function `top_model_for_year()` that gets the name of the most popular vehicle for a given year.
====

=== Question 3 (2 pts)

Fantastic. Now that we've created a function that can easily get us the most popular vehicle for a given year, let's incorporate this information back into our dataframe and learn about a useful family of functions in the meantime. 

The 'apply' functions in R are super useful, and each provide some different version of applying a function over a whole dataframe. Give the below (non-exhaustive) list of apply-family functions a once-over, paying special attention to some of the provided examples, before attempting to complete the task for this question.

- apply: runs a function across every row (or column) of a dataframe, returning a list of results
- lapply/sapply: runs a function on a list/vector, returning a list/array/dataframe of results of the same length
- tapply: runs a given function on every value in a column, grouping by another specified column (this one is tough to understand without looking at an example)



[NOTE]
====
`lapply()` and `sapply()` are extremely similar, and largely differ in the type of object that they return. `lapply()` returns a list of values, where `sapply()` returns an array/dataframe of values. In many cases, they can be used relatively interchangeably.
====

.Deliverables
====
- Ipsum lorem
====

=== Question 4 (2 pts)

Ipsum lorem dolor sit amet, consectetur adipiscing elit

.Deliverables
====
- Ipsum lorem
====

=== Question 5 (2 pts)

Ipsum lorem dolor sit amet, consectetur adipiscing elit

.Deliverables
====
- Ipsum lorem
====

== Submitting your Work

This is where we're going to say how to submit your work. Probably a bit of copypasta.

.Items to submit
====
- firstname_lastname_project8.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/current-projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====