= TDM 10100: R Project 11 -- 2024

**Motivation:** Time is extremely important to humans and data analysis, and us humans have created a _lot_ of different ways to represent times and dates. In this project we'll look at `lubridate`, one of R's most popular packages for handling date-time data and a part of the aforementioned `tidyverse`. We'll combine it with utilities we've looked at in other libraries previously, along with some different datasets and data formats, in order to really polish our data ingestion skills. 

**Context:** Understanding of common `dplyr` and `tidyr` functions, along with knowledge of base R syntax, will be vital for this project. Prioritizing vectorized operations will also be important to ensure good performance in your code.

**Scope:** `lubridate`, `dplyr`, `tidyr`, `tidyverse`, data ingestion, R

.Learning Objectives:
****
- Learn a few basic date and time storage formats commonly used in data
- Learn how to process, manipulate, and analyze date-time data
- Apply basic visual analyses to processed date-time data.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about project submissions xref:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset(s):

- `/anvil/projects/tdm/data/flights/1999.csv`

== Questions

=== Question 1

Read in data from both files, learn about datetime objects and reading in different formats



Let's begin our exploration of handling dates and times with the most simple and fundamental step: reading them in and understanding their structure.

Start by reading the datasets for this project into a structures called `flights_dat` (for `/anvil/projects/tdm/data/flights/1999.csv`).

[NOTE]
====
At this point, we're really going to give you freedom on a lot of parts of these projects. For example, you can choose to either use `fread()` to store your data in a `data.table`, `read.csv()` to store your data into a data.frame, or even `read_csv()` to store your data into a `tibble` (even though we haven't learned about those yet!). Generally , if we don't explicitly limit or request you do things a certain way, you will have the freedom to design and build your own unique solutions to problems going forward.
====

Print the head of each dataset. `lubridate` has a ton of fantastic functions to process dates of various formats into their special `date` type that is much easier than regular character data to work with. Take a look at any information associated with dates and times in the data. In particular, notice that we have dates of the format "YYYY-MM-DD" along with individual day, month, and year data.

As a callback to concepts we learned early in the semester, index into the column with full date information and get just the first entry. Print the type of that data using `class()`.

Next, create an identical-_looking_ bit of data by combining the first entries in the `day`, `month`, and `year` columns. Don't use `lubridate` just yet. Print the type of this combination using `class`. Is it the same as the date column?

You can see that it is in fact not!


.Deliverables
====
- Ipsum lorem
====

=== Question 2

learn about reformatting/writing in different formats

.Deliverables
====
- Ipsum lorem
====

=== Question 3

Convert to different time zones

.Deliverables
====
- Ipsum lorem
====

=== Question 4

Do arithmetic with times, calculate timespans

.Deliverables
====
- Ipsum lorem
====

=== Question 5

Visualize results of datetime analysis and create a summary visual

.Deliverables
====
- Ipsum lorem
====

== Submitting your Work

This is where we're going to say how to submit your work. Probably a bit of copypasta.

.Items to submit
====
- Ipsum lorem
- Ipsum lorem
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/current-projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====