= TDM 10100: R Project 2 -- 2024

**Motivation:** R is one of the most popular programming languages in the world for statistical and scientific analysics. it is particularly handy for working with data. Indexing in R is very powerful.

**Context:** We will load several data frames in R and will practice indexing the data in several ways.

**Scope:** R, Operators, Conditionals

.Learning Objectives:
****
- Get comfortable with extracting data in R that satisfy various conditions
- Learning how to use indices in R
- Apply these techniques with real-world data
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about project submissions xref:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset(s):

- `/anvil/projects/tdm/data/olympics/athlete_events.csv`

== Questions

[IMPORTANT]
====
For this project (and moving forward, when you are using R), please use the `seminar-r` kernel (not the `seminar` kernel), unless otherwise specified. When you use the `seminar-r` kernel with R, you do not need to use the `%%R` cell magic.
====

=== Question 1 (2 pts)

Import the Olympics data from the file `/anvil/projects/tdm/data/olympics/athlete_events.csv` into a data frame called `myDF`.  Make a table from the values in the column `myDF$Year` and the plot this table.  (Your work will be simlar to Project 1, Questions 3, 4, 5.)  Does the resulting plot make sense?  In other words, does it make sense that the number of athletes is increasing over time?  Can you see the halt in the Olympics during the two World Wars?  Do you see the 2-year rotation between summer and winter Olympics began in the 1990s?

.Deliverables
====
- A table showing the number of athletes participating in the Olympics during each year.
- A plot showing the number of athletes participating in the Olympics during each year.
- As *always*, be sure to document your work from Question 1 (and from all of the questions!), using some comments and insights about your work.  We will stop adding this note to document your work.  Moving forward, we assume that you will *document every single question with your comments and your insights*.
====

=== Question 2 (2 pts)

While we'll cover control structures in greater detail in the next few weeks, let's introduce the basic concept so we can see the **power** of logical operators when used in conditionals!

Conditionals are exactly what they sound like: blocks of code that perform actions _if_ we satisfy certain conditions. Creatively, we call these _if statements_. In R, _if statements_ are structured like so:

[source, r]
----
# general structure
if (condition) {
    do this action
}

# specific example
if (x > 0) {
    print("X is a positive number!")
}
----

For this question, we want you to use the operators we just learned to perform the following:

- define a variable `myYear`
- write an `if statement` that prints "Divisible by 4!" if `myYear` is divisible by 4
- write an `if` statement that prints "Not divisible by 100!" if `myYear` is not divisible by 100
- write an `if` statement that prints "Leap Year!" if `myYear` is divisible by 4 **AND** myYear is not divisible by 100

Here is some skeleton code to get you started (the first if statement is already completed):

[source, r]
----
myYear <- 2000

if (myYear %% 4 == 0) {
    print("Divisible by 4!")
}
if # continue your code here...
----

[IMPORTANT]
====
The `&&` AND operator may be useful here when you want to check that two conditions are _both true_. For more information about the `&&` operator, please refer to the resources presented in the first question.
====

To check your work, here are the following test cases:

- Year 2000 is divisible by 4 and 100
- Year 2020 is divisible by 4, but not by 100 (meaning it is a _leap year_)
- Year 1010 is not divisible by 100 or 4

.Deliverables
====
- Three _if_ statements as described above.
====

=== Question 3 (2 pts)

Let's continue to build on the foundational concept of _if_ statements. Sometimes, when our first condition is not true, we want to do something else. Sometimes we only want to do something else if _another_ condition is true. In an astounding feat of creativity, these are called _if/else/else-if_ statements, and here is their general structure:

[source, r]
----
# general structure (we can have as many else ifs as we want!)
if (condition) {
    do this
} else if (other condition) {
    do this instead
} else if (third condition) {
    do this if we meet third condition
} else {
    this is our last option
}

# we can also have no else if statements if we want!
if (condition) {
    do this
} else {
    do this instead
}

# and finally, a concrete example
x <- 5 # you can change 5 to any value you'd like!
if (x > 100) {
    print("x is greater than 100!")
} else if (x > 0) {
    print("x is a positive number less than 100!")
} else if (x < -100) {
    print("x is less than -100!")
} else {
    print("x is a negative number greater than -100!")
}
----

Feel free to experiment with these examples, plugging in different values of `x` and seeing what happens. Learning to code is done with lots of experimentation, and exploring/making mistakes is a valuable part of that learning experience.

Let's build on your code from the last problem to create an _if/else/else-if_ statement that is able to identify any and all leap years! Below is the definition of a leap year. Your task for this question is to take the below definition and, defining a variable `myYear`, write an _if/else/else-if_ block that prints "Is a leap year!" if `myYear` is a leap year, and prints "Is not a leap year!" if `myYear` is not a leap year.

[IMPORTANT]
====
A year is a leap year if it is divisible by 4 and not 100, _or_ if it is divisible by 100 and 400. To put it in language that may make more sense in a conditional structure:

If a year is divisible by 4, but not divisible by 100, it is a leap year. Else if a year is divisible by 100 and is divisible by 400, it is a leap year. Else, it is not a leap year.
====

[source, r]
----
myYear <- 2000

if ( ... ) {
    print("Is a leap year!")
} else if ( ... ) {
    print("Is a leap year!")
}
else {
    print("Is not a leap year!")
}
----

[NOTE]
====
Here are some test cases for you to use to double-check that your code is working as expected.

- 2000, 2004, 2008, 2024 are all leap years
- 1700, 1896, 1900, and 2010 are all not leap years
====

.Deliverables
====
- A conditional structure to identify leap years, and the results of running it with at least one year.
====

=== Question 4 (2 pts)

Okay, we've learned a lot in this project already. Let's try and master the concepts we've been working on by making a more concise version of the conditional structure from the last problem. Here are the rules: you must create a conditional structure with only one _if_ and only one _else_. No _else ifs_ are allowed. It has to accomplish fundamentally the same task as in the previous question, and you may use the test cases provided in the previous question as a way to validate your work. Some basic skeleton code is provided below for you to build on:

[source, r]
----
myYear <- 2000

if ( ... ) {
    print("Is a leap year!")
} else {
    print("Is not a leap year!")
}
----

[IMPORTANT]
====
For this question, the `||` OR operator, which functions similarly to the `&&` AND operator mentioned in question 2, may be helpful.
====

.Deliverables
====
- The results of running your conditional on at least one leap year.
====

=== Question 5 (2 pts)

Great work so far. Let's summarize what we've learned. In this project, we learned about the different types of operators in R and how they are used, what conditional statements are and how they are structured, and how we can use logical and comparison operators in conditional statements to make decisions in our code!

For this last question, we'll use what operators and conditionals on real-world data and make observations based on our work! The below code has been provided to you, and contains a few new concepts we are going to cover in next week's project (namely, `for` loops and lists). For now, you don't have to understand fully what is going on. Just insert the conditions you wrote in the last problem where specified to complete the code (you only have to change lines with `===` in comments), run it, and write at least 2 sentences about the results of running your code and any observations you may have regarding that output. Include in those two sentences what percentage of the Olympics were held on leap years. (If you are interested in understanding the provided code, feel free to take some time to read the comments explaining what each line is doing.)

[IMPORTANT]
====
The Olympics data can be found at `/anvil/projects/tdm/data/olympics/athlete_events.csv`
====

[NOTE]
====
In the below code, you may have noticed the addition of `.unique()` when we're getting a list of years from our data. We'll refrain from covering this in detail until a future project, but what you can know is that here it takes our list of all years and removes all the duplicate years so we have only one of each year in our resulting `year_list`
====

[NOTE]
====
You will also notice the `cat()` function below, which you can think of as the same as the `print()` function we've been using, but printing everything on one line instead of having a whole bunch of messy output. Feel free to swap `cat()` and `print()` to see the difference between their outputs.
====

[source, r]
----
olympics_df <- # === read the dataset in here (see Project 1 for reminder!) ===

# get a list of each year in our olympics_df using c(), 
#   and use unique() to remove duplicate years
year_list <- unique(olympics_df$Year)
year_list <- year_list[!is.na(year_list)] # removes all NA values from our list

# create an empty list for our results
leap_list = c() 

# apply our conditional to each year in our list of years
for (year in year_list) {
    if # === add your condition for leap years here === {
        # add the year to our list of leap years 
        leap_list <- append(leap_list, year)
    }
}

# prints our list of leap years and number of leap years
cat("The Olympics were held on leap years in:", sort(leap_list), "\n")
cat(length(leap_list), "of the", length(year_list), "Olympics occurrences in our data were held on a leap year.\n")
----

.Deliverables
====
- The results of running the completed code
- At least two sentences containing observations about the results and what percentage of Olympics are held on leap years
====

== Submitting your Work

Great job, you've completed Project 2! This project was your first real foray into the world of R, and it is okay to feel a bit overwhelmed. R is likely a new language to you, and just like any other language, it will get much easier with time and practice. As we keep building on these fundamental concepts in the next few weeks, don't be afraid to come back and revisit your previous work. As always, please ask any questions you have during seminar, on Piazza, or in office hours. We hope you have a great rest of your week, and we're excited to keep learning about R with you in the next project!

.Items to submit
====
- firstname_lastname_project2.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, comments (in markdown or with hashtags), and code output, even though it may not. **Please** take the time to double check your work. See xref:submissions.adoc[the instructions on how to double check your submission].

You **will not** receive full credit if your `.ipynb` file submitted in Gradescope does not **show** all of the information you expect it to, including the output for each question result (i.e., the results of running your code), and also comments about your work on each question. Please ask a TA if you need help with this.  Please do not wait until Friday afternoon or evening to complete and submit your work.
====
