= TDM 10100: R Project 13 -- 2024

**Motivation:**  It is fun and straightforward to do mapping in R!

**Context:**  We will create several maps in R, including one with a Thanksgiving theme.

**Scope:**  Maps in R are large, so when you download your Jupyter Lab project to your computer and then upload it to Gradescope, you won't be able to easily view it in Gradescope, but that's OK.  The graders will still be able to see it.

.Learning Objectives:
****
- Learn how to make maps in R.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about project submissions xref:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset(s):

- `/anvil/projects/tdm/data/craigslist/vehicles.csv` (Craigslist vehicles)
- `/anvil/projects/tdm/data/taxi/yellow/yellow_tripdata_2015-11.csv` (New York City taxi cab data from November 2015)


== Questions

[WARNING]
====
Please use 3 cores in your Jupyter Lab session for this project.
====

=== Question 1 (2 pts)

First load:  `library(data.table)` so that you have the `fread` function available, and also `options(repr.matrix.max.cols=50)` so that you can see 50 columns.

Also load:  `options(jupyter.rich_display = T)` so that you can draw maps in Jupyter Lab.

For this project, we need two maps packages:  `library(leaflet)` and `library(sf)`

For this first question, we simply make a simple map, with three latitude and longitude values.

We call our data frame `testDF`, and it is important that we name the columns:

[source,r]
----
testDF <- data.frame(c(40.4259, 41.8781, 39.0792), c(-86.9081, -87.6298, -84.17704))
names(testDF) <- c("lat", "long")
----

The whole data frame looks like this, just three rows and two columns:

[source,r]
----
testDF
----

Now we can define the points that we want to plot on a map:

[source,r]
----
points <- st_as_sf( testDF, coords=c("long", "lat"), crs=4326)
----

and we can render the map.  We make each dot have radius 1, but you are welcome to change the radius if you want to:

[source,r]
----
addCircleMarkers(addTiles(leaflet( testDF )), radius=1)
----


.Deliverables
====
Show the map with the three points.
====


=== Question 2 (2 pts)

Now let's find the most popular 10 stores (from all 27 million rows, and only the 5 columns in question 1) in two different ways:

a.  Use the `table` command to find the 10 most popular values of the `"Store Number"`

b.  Use the `table` command to find the 10 most popular values of the `"Store Name"`

c.  Use the `table` command to find the 10 most popular values of these three columns pasted together: `Address`, `City`, `"Zip Code"`

d.  Do your answers to parts (a) and (b) seem to agree?  Do your answers to parts (a) and (c) seem to agree?


.Deliverables
====
- a.  A table with the 10 most popular values of the `"Store Number"` and the number of occurrences of each.
- b.  A table with the 10 most popular values of the `"Store Name"` and the number of occurrences of each.
- c.  A table with the 10 most popular values of these three columns pasted together: `Address`, `City`, `"Zip Code"` and the number of occurrences of each.
- d.  Do your answers to parts (a) and (b) seem to agree?  Do your answers to parts (a) and (c) seem to agree?

====


=== Question 3 (2 pts)

For this question, use `fread` to read all 27 million rows of the data set again, but this time, only read in the columns `"Zip Code"`, `"Category Name"`, `"Sale (Dollars)"`.

a. Use the tapply function to sum the values of `"Sale (Dollars)"` according to the `"Zip Code"`.  Find the 10 `"Zip Code"` values that have the largest sum of `"Sale (Dollars)"` altogether, and give those `"Zip Code"` values and each of their sums of `"Sale (Dollars)"`.


b. Now use the tapply function to sum the values of `"Sale (Dollars)"` according to the `"Category Name"`.  Find the 10 `"Category Name"` values that have the largest sum of `"Sale (Dollars)"` altogether, and give those `"Category Name"` values and each of their sums of `"Sale (Dollars)"`.


.Deliverables
====
- Find the 10 `"Zip Code"` values that have the largest sum of `"Sale (Dollars)"` altogether, and give those `"Zip Code"` values and each of their sums of `"Sale (Dollars)"`.
- Find the 10 `"Category Name"` values that have the largest sum of `"Sale (Dollars)"` altogether, and give those `"Category Name"` values and each of their sums of `"Sale (Dollars)"`.
====

=== Question 4 (2 pts)

Use `fread` to read only the 10th and 15th fields of this huge file:  `/anvil/projects/tdm/data/election/itcont2020.txt` (do not worry about the warning in a pink box that appears).

Sum the amount of the donations (from the 15th field) according to the state (from the 10th field).  List the top 10 states according to the sum of the donation amounts, and the sum of the donation amounts in each of these top 10 states.


.Deliverables
====
- List the top 10 states according to the sum of the donation amounts, and the sum of the donation amounts in each of these top 10 states.
====

=== Question 5 (2 pts)

Read the first 10 lines of `/anvil/projects/tdm/data/movies_and_tv/imdb2024/basics.tsv` and notice that the entries of the `genres` column are strings with several types of genres, separated by commas.  On the `genres` column (for only these 10 lines), run the following:

`myDF$genres`

`strsplit(myDF$genres, ',')`

`unlist(strsplit(myDF$genres, ','))`

`table(unlist(strsplit(myDF$genres, ',')))`

Notice that, in this way, using the `strsplit` function, we can find out how many times each of the individual `genres` occur.

Now read in *only* the `genres` column of the entire file (do not worry about the warning that results).  For each of the `genres`, list how many times it occurs.  For instance, `Action` occurs 462531 times.

.Deliverables
====
- For each of the `genres`, list how many times it occurs.
====

== Submitting your Work

This project enables students to select the relevant columns of a data frame for their analysis.


.Items to submit
====
- firstname_lastname_project12.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, comments (in markdown or with hashtags), and code output, even though it may not. **Please** take the time to double check your work. See xref:submissions.adoc[the instructions on how to double check your submission].

You **will not** receive full credit if your `.ipynb` file submitted in Gradescope does not **show** all of the information you expect it to, including the output for each question result (i.e., the results of running your code), and also comments about your work on each question. Please ask a TA if you need help with this.  Please do not wait until Friday afternoon or evening to complete and submit your work.
====

