= TDM 10100: R Project 10 -- 2024

**Motivation:** Using R enables us to applying functions to many data sets in an efficient way.  We can extract information in a straightforward way.

**Context:** There are several types of `apply` functions in R.  In this project, we learn about the `sapply` function, which is a "simplified" apply function.

**Scope:** Applying functions to data.

.Learning Objectives:
****
- Learn how to apply functions to large data sets and extract information.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about project submissions xref:submissions.adoc[here].

== Dataset(s)

This project will use the following dataset(s):

- `/anvil/projects/tdm/data/flights/subset/*` (flights data)
- `/anvil/projects/tdm/data/election/itcont/*` (election data)

We demonstrate the power of the apply family of functions.

In this project, we walk students through these powerful techniques.

== Questions

=== Question 1 (2 pts)

We can calculate the number of flights starting from Indianapolis airport in 1990 as follows:


[source, r]
----
library(data.table)
myDF <- fread(paste0("/anvil/projects/tdm/data/flights/subset/1990.csv"))
myvalue <- table(myDF$Origin)['IND']
myvalue
rm(myDF)
----

(We use the `rm` at the end, so that we do not keep this data frame in memory, during the remainder of the project.)

Now we can replicate this work, using a function, as follows:

[source, r]
----
myindyflights <- function(myyear) {
    myDF <- fread(paste0("/anvil/projects/tdm/data/flights/subset/", myyear, ".csv"))
    myvalue <- table(myDF$Origin)['IND']
    names(myvalue) <- myyear
    return(myvalue)
}
----

and we can test that we get the same results:

[source, r]
----
library(data.table)
myindyflights(1990)
----

Finally, we can use the `sapply` function to run this function on each year from 1987 to 2008.

[source, r]
----
library(data.table)
myresults <- sapply(1987:2008, myindyflights)
----

which yields the number of flights starting from Indianapolis airport in each year from 1987 to 2008.

The total number of flights starting from Indianapolis altogether, during 1987 to 2008, is:

[source, r]
----
sum(myresults)
----

and the number of flights per year is:

[source, r]
----
plot(myresults)
----


[NOTE]
====
The data sets cover October 1987 through April 2008.  So the data sets for 1987 and 2008 are smaller than you might expect, and that is OK.
====

.Deliverables
====
- Plot the total number of flights starting from the Indianapolis airport during 1987 to 2008.
====


=== Question 2 (2 pts)

We replicate the work from Question 1, but this time, we keep track of all of the flights originating at every airport in the data set.


We make a function, very much like Question 1, but this time, we keep track of the full table of the counts of `Origin` airports, for all airports (not just for Indianapolis):

[source, r]
----
myflights <- function(myyear) {
    myDF <- fread(paste0("/anvil/projects/tdm/data/flights/subset/", myyear, ".csv"))
    myvalue <- table(myDF$Origin)
    names(myvalue) <- myyear
    return(myvalue)
}
----

and we can test that this function works for the 1990 flights:

[source, r]
----
library(data.table)
myflights(1990)
----

Finally, we can use the `sapply` function to run this function on each year from 1987 to 2008.

[source, r]
----
library(data.table)
myresults <- sapply(1987:2008, myflights)
----

which yields the number of flights starting from each airport in each year, from 1987 to 2008.

Now we can add up the number of flights across all of the years, as follows:

[source, r]
----
v <- unlist(myresults)
tapply(v, names(v), sum)
----

and the number of flights starting at each of the top 10 airports during the years 1987 to 2008 is:

[source, r]
----
dotchart(tail(sort(tapply(v, names(v), sum)), n=10))
----



.Deliverables
====
- Plot the total number of flights starting from each of the top 10 airports during 1987 to 2008.
====


=== Question 3 (2 pts)

In Project 2, we learned about the `grep` and `grepl` functions.  Using either of these two functions, you can limit attention to ice cream products that have `"Chocolate"` in the title.  (There are 49 such ice cream products.)  Find the average number of stars for all 4831 of the reviews of these products that have `"Chocolate"` in the product name.


.Deliverables
====
- Print the average number of stars for all 4831 of the reviews of these products that have `"Chocolate"` in the product name.
====

=== Question 4 (2 pts)

Read in the information about airports, and also the flight data from 1990, into two separate data frames, as follows:

[source, r]
----
library(data.table)
airportsDF <- fread("/anvil/projects/tdm/data/flights/subset/airports.csv")
flightdataDF <- fread("/anvil/projects/tdm/data/flights/subset/1990.csv")
----

[IMPORTANT]
====
It is necessary to have 2 cores in your Jupyter Lab session for Question 4 and Question 5.
====

[IMPORTANT]
====
Do not worry about the warning message from the `fread` function when you read in the `airportsDF` data.
====

These two data frames do not have any columns in common!  Nonetheless, the `"iata"` values from the `airportsDF` are the three-letter codes corresponding to airports, which are also found in the `Origin` and `Dest` columns in the `flightdataDF`.  So when we merge the information from the two tables, if we want to study where the flights depart, then we only want to merge the data according to the `iata` value (from the `airportsDF`) merged with the `Origin` value (from the `flightdataDF`), as follows:


[source,r]
----
mybigDF <- merge(airportsDF, flightdataDF, by.x = "iata", by.y = "Origin")
----

Using this new data frame, find the average departure delay for all flights that have `Origin` airport in Indiana.


.Deliverables
====
- Print the average departure delay for all flights that have `Origin` airport in Indiana.
====

=== Question 5 (2 pts)

Using the same data frame from Question 4, find the average departure delay for all flights that have `Origin` airport in Houston, Texas.

.Deliverables
====
- Print the average departure delay for all flights that have `Origin` airport in Houston, Texas.
====

== Submitting your Work

Now you are familiar with the method of merging data from multiple data frames.


.Items to submit
====
- firstname_lastname_project9.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, comments (in markdown or with hashtags), and code output, even though it may not. **Please** take the time to double check your work. See xref:submissions.adoc[the instructions on how to double check your submission].

You **will not** receive full credit if your `.ipynb` file submitted in Gradescope does not **show** all of the information you expect it to, including the output for each question result (i.e., the results of running your code), and also comments about your work on each question. Please ask a TA if you need help with this.  Please do not wait until Friday afternoon or evening to complete and submit your work.
====
