= Mark Daniel Ward

== Publications

Good try and example

[%reversed]
. Student Experiences within a Data Science Learning Community: A Communities of Practice Perspective, by Aparajita Jaiswal, Alejandra Magana, Joseph A. Lyon, Ellen Gundlach, and Mark D. Ward, Learning Communities Research and Practice, Volume 9, Issue 1 (2021).
. Work-in-Progress: Evaluating Student Experiences in a Residential Learning Community: A Situated Learning Perspective, by Aparajita Jaiswal, Joseph A. Lyon, Viranga Perera, Alejandra J. Magana, Ellen Gundlach, Mark D. Ward, accepted for publication in the American Society for Engineering Education (ASEE) Annual Conference (2021).
. Characterizing the psychosocial effects of participating on a year-long residential research-oriented learning community, by Alejandra J. Magana, Aparajita Jaiswal, Aasakiran Madamanchi, Loran C. Parker, Ellen Gundlach, Mark D. Ward, accepted for publication in Current Psychology (2021).
. The number of distinct adjacent pairs ingeometrically distributed words, by Margaret Archibald, Aubrey Blecher, Charlotte Brennan, Arnold Knopfmacher, Stephan Wagner, Mark Daniel Ward, 18 pages, accepted for publication in Discrete Mathematics and Theoretical Computer Science (2021).
. Research Experiences in the Statistics Living Learning Community, by Maggie Betz, Peter Boyd, Emily Damone, Christina DeSantiago, Kent Gauen, Katie Lothrop, Mikaela Meyer, Kristen Mori, Ashley Peterson, Mark Daniel Ward, 12 pages, provisionally accepted pending minor revisions, for forthcoming book on the Future of Undergraduate Research in Math, to be published by the MAA in 2021.
. The Data Mine: Enabling Data Science Across the Curriculum, by E. Gundlach and M. D. Ward, Journal of Statistics and Data Science Education, Volume 29 (2021), supplement, S74-S82.
. The Periodicity of Nim-Sequences in Two-Element Subtraction Games, by B. Benesh, J. Carter, D. Crabill, D. Coleman, J. Good, M. Smith, J. Travis, and M. D. Ward, INTEGERS: Electronic Journal of Combinatorial Number Theory, Volume 20 (2020), 6 pages (xref:papers/paper044.pdf[pdf]).
. The Next Wave: We Will All Be Data Scientists, by M. Betz, E. Gundlach, E. Hillery, J. Rickus, and M. D. Ward, Statistical Analysis and Data Mining, volume 13 (2020), 544-547 (xref:papers/paper043.pdf[pdf]).
. Asymptotic Analysis of the kth Subword Complexity, by L. Ahmadi and M. D. Ward, Entropy, Volume 22, Issue 2 (2020), 34 pages (xref:papers/paper042.pdf[pdf]).
. Fostering Undergraduate Data Science, by F. Gokalp Yavuz and M. D. Ward, The American Statistician, volume 74 (2020), 8-16 (xref:papers/paper041.pdf[pdf]).

HELLO now

