= Frequently Asked Questions (FAQs)

== Registration

See the link:https://the-examples-book.com/registration/howtoregister[Registration Appendix here]. 

{sp}+

== Corporate Partners 

* Where is the syllabus? 

** The xref:fall2023/syllabus.adoc[Fall 2022 syllabus is here]. 

* How do I get started on my Corporate Partners project? 
** Start with reviewing xref:fall2022/sprint1.adoc[Sprint 1 page] for Fall 2023. 

* Where do I go for class?
** The meeting locations are listed on your course registration. You will receive a calendar invite for the synchronous online meeting before the first day of class. See the xref:fall2023/syllabus#classteam-meeting-times.adoc[Logistics section of the Syllabus] for more details including a map. 

* How do I access my new MS Team email group?
** Navigate to the xref:./fall2023/ms_teams.adoc[MS Teams] page to learn how to login and view past emails in your MS Team email group.

* I just switched my registration and don't have access to my new MS Team. 
** Our systems update every night at midnight, so please wait until the next day after you update your registration to be added to the new MS Team. If you switch your registration the same day as the first meeting, you can email us for the meeting link. Otherwise, please wait 24 hours before contacting us. 

* When are assignments due?

** Everything you need to submit is listed in the xref:fall2023/schedule.adoc[Course Schedule]. Check out the corresponding sprint pages for details. 

* Are there exams in Corporate Partners?

** Besides the open note syllabus quiz and agile training quiz at the beginning of the semester, there are no exams. There is not a final exam either; instead, students collaborate with their team on a final presentation.

* How do I know who my TA is?
** A list of Corporate Partner TAs and emails for Fall 2023 are xref:fall2023/syllabus#corporate-partner-tas.adoc[available in the syllabus here]. 

{sp}+

== Technical Resources 

* The research computing cluster isn't working. How do I get help?
** Check with your TA first. If you need more help email datamine-help@purdue.edu. 

{sp}+

== Seminar

* Q: I didn't understand Dr. Ward's lesson today. Where can I get more help?
** A: Ask your seminar TA's. If you need more help submit a question to Dr. Ward in Piazza. 

== General Questions from Students

* Q: Are there any overlapping concepts between TDM 111 and TDM 101?
** A: TDM 101 exists to equip students with foundational data science concepts and technical skills needed to contribute to TDM 111 projects. The utilization of TDM 101 concepts in TDM 111 will vary from project to project. It is possible for some TDM 111 projects to utilize concepts not covered in TDM 101. 

* Q: Can my experience in The Data Mine lead to an internship with Corporate Partners?
** A: Yes. There have been instances where TDM students have received internships through connections with Corporate Partners. Students are encourage to reach out to their Corporate Partner Mentor about possible internship opportunities. 

* Q: What future Corporate Partners are TDM looking to bring in?
** A: TDM is always continuing to pursue partnerships with companies from multiple sectors of industry. 
