= How to succeed in this course

If you want to be a *successful* student, we encourage you to:

•	TDM 11100/21100/31100/41100/51100 Data Mine Corporate Partners is a 3-credit hour course. It is generally recommended that you spend 3 hours per week per credit hour you are enrolled in. Therefore, we expect students to be able to commit to 8 to 10 hours per week this semester towards your Corporate Partners project. The general weekly breakdown of your time is as follows: 
** 50 minutes per week meeting with your team and your Corporate Partner Mentor 
** 1 hour and 50 minutes per week meeting with your team led by your Corporate Partner Peer Mentor (TA)
** 5 to 7 hours per week working on the project (individually or with teammates)
•	Communicate with your team about your share of the work.  
•	Read your @purdue.edu email daily and respond to emails (and group communications like MS Teams) in a timely manner. 
•	Be self-motivated and self-disciplined.
•	Accept critical thinking and decision making as part of the learning process. 
•	Be willing to “speak up” if problems arise. Your Corporate Partner Peer Mentor and The Data Mine staff are here to support you, but you have to communicate with us when you need help. Please do not wait until the end of the semester to bring issues to our attention or say you don’t understand a concept. The earlier that you let us know, the easier we can help you.  
•	Don’t be afraid to ask questions. Some of the projects focus on complicated topics and the teams are learning together. There are no bad questions in this type of environment!  
•	It is not ok to stop participating if the course content gets difficult.  Even if other students are more experienced, everyone should 1) make an effort to learn and get caught up and 2) find some way to contribute while trying to build up the necessary technical skills.  Your Corporate Partner Mentor and TA can provide suggestions of other resources to help learn content. Again, you have to “speak up” when you need help! 
•	Deadlines are an unavoidable part of being a professional, and this course is no exception. Course requirements must be completed and submitted on or before the specified due date and delivery time deadline. Late work will not be accepted. Due dates and delivery time deadlines are defined as Eastern Time (as used in West Lafayette, Indiana). 
•	Be respectful of your teammates, your Corporate Partner Mentor, your Corporate Partner Peer Mentor, and The Data Mine staff.
