= Student Playbook

Welcome to the student resource section for The Data Mine Corporate Partners program.

Students sign up for their level of participation in The Data Mine according to the number of years that they have participated (rather than the number of years they have been a student at Purdue).  E.g., a junior who is participating for the first time will still take TDM 11100 and TDM 11200.

If this is your first semester in our Corporate Partners program, then you register for TDM 11100 during the fall semester, and TDM 11200 in the spring semester.  Students who are returning to our Corporate Partners program for a second year of participation will take TDM 21100 in the fall and TDM 21200 in the spring.  Similarly, if you are in Corporate Partners for a third year in a row, you can take TDM 31100 and TDM 31200.  During your fourth year in our program, we have TDM 41100 and 41200 available.

Graduate students may participate in TDM 51100 as many times as desired.  This course is repeatable.

This is a "living" book about our Corporate Partners program, which is continuously being updated. If you have feedback, you can write to datamine@purdue.edu. 



