= Project Milestones

The project milestones are opportunities to present your project's progress and get feedback from The Data Mine teams. There are 4 milestones that will progress with the project throughout the academic year. 

The information for the different milestones is included below. 

== Due Dates

The TA for each team should be responseible for scheduling the milestone reviews using the link below. 

Due to the number of reviews, the timeframe for the review will be a window of time. Each team must make sure to complete the review before the end of the time window. 

If you have questions, email datamine-help@purdue.edu. 

Schedule: https://calendly.com/datamine/milestone-review 

**Milestone 1**: Review must be completed before the [.underline]#end of September#. 

**Milestone 2**: Review must be completed by [.underline]#December 8th#. 

**Milestone 3**: Review must be completed by the [.underline]#end of February#. 

**Milestone 4**: Review must be completed by [.underline]#April 15th#. 

== Format

Presentation Length: 20-30 minutes. 
Presentation Format: xref:attachment$Purdue-branded-powerpoint-template-reduced.pptx[Purdue PowerPoint Template]
Presentation Style: While business attire is not required, these are formal presentations and should be complete and ready for review and questions. 

== Content

**Milestone 1**: This should be an overview of all the planning and research at the start of your project. 

**Milestone 2**: This is an update on your initial research and model or application design. 

**Milestone 3**: This presentation is focused on how the model or application is progressing. 

**Milestone 4**: This presentation is focused on how the research is wrapping up toward the end of the academic year. 

**Core Content**: The questions below should be answered for every milestone. Feel free to add additional information that you feel is relevant to the project. 

