= Technical Specification Documentation (Tech Spec)

We have been discussing documentation for The Data Mine CRP projects off and on since the beginning of the fall semester. Why and what does it all mean? Documentation benefits more than just the project. It benefits the engineers and developers who work on the project, the teams that will utilize the work, and any project that could be developed after the project is finished. This process allows for the entire team to understand the end goal and what is involved in executing the project to its completion. Zara Cooper perfectly summarizes how this helps the development team in the “A Practical Guide to Writing Technical Specs” blog, April 6th, 2020.  

[quote,A Practical Guide to Writing Technical Specs” blog, April 6th, 2020]
____
A technical spec is a straightforward and efficient way to communicate project design ideas between a team and stakeholders. The whole team can collaboratively solve a problem and create a solution. As more teammates and stakeholders contribute to a spec, it makes them more invested in the project and encourages them to take ownership and responsibility. With everyone on the same page, it limits complications that may arise from overlapping work. Newer teammates unfamiliar with the project can onboard themselves and contribute to the implementation earlier.
____

While the sections below explain what a tech spec needs, not all sections will fit every project. However, each team should try to answer or summarize each section below. Every team is required to submit one tech spec on their project. 


++++
<iframe width= "800" height="400" title="Time Management Template and Examples"  scrolling="yes"
src="https://docs.google.com/document/d/e/2PACX-1vRAhOZJpCtxAgFl_MMQBE-E5iC0DDyOgjqtsIuIGqIEghLS6X95JiA_AkbbefEK9Kp4_Spzu_XHm36P/pub?embedded=true&amp;headers=false" &wdDownloadButton="True"></iframe>
++++

Make your own copy by navigating to the link:https://docs.google.com/document/d/1DigltIFOXIIpLDuw1mZVWk-R5YtBE87DGQADfeBkp24/edit?usp=sharing[Technical Specification Guide]. It is strongly recommended that this is shared with your entire team in a MS Teams Notebook or files.

== What should be included in technical specification?
In the technical specification guide provided, you will complete sections including:

Instructions
Table of Contents
Title Page
Introduction
Further Considerations
Success Evaluation
Work
Deliberation

