= TDM 20200: Systematically extracting data from the web:  Project 6 -- Spring 2025

**Motivation:** Now that we are familiar with web scraping, we also want to ensure that we can systematically extract data from the internet and analyze it.

**Context:** We will get familiar with techniques for reproducibly working with data from the web, using workflows that can be well-documented, rather than doing everything by hand.

**Scope:** Data from the web in workflows

.Learning Objectives:
****
- We learn how to systematically and reproducibly use data from the internet.
****

Make sure to read about, and use the template found xref:ROOT:templates.adoc[here], and the important information about project submissions xref:ROOT:submissions.adoc[here].

== Dataset(s)

In this project we will scrape data from the following websites:

- https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page

== Questions


=== Question 1 (2 pts)

Consider the Green Taxi Trip Records, stored in parquet format, on the New York City taxi website:

https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page

Use list comprehension to build a list (of length 11) with the data from January 2024 through November 2024.  Each element of the list will be a Pandas dataframe.

[HINT]
====
The `read.parquet` function from Pandas should be helpful.

It might also be helpful to know how to make a string with leading zeros; several examples are given here:  https://stackoverflow.com/questions/134934/display-number-with-leading-zeros
====

Use `pd.concat` as described here: https://pandas.pydata.org/docs/reference/api/pandas.concat.html (with the option `ignore_index=True`) to build a Pandas data frame from the list given above.  Your data frame should have 606224 rows and 20 columns.

.Deliverables
====
- Build a data frame containing the green taxi cab data from January 2024 through November 2024
====

=== Question 2 (2 pts)

Read about how to extract a month from a date in Pandas, for instance, here: https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html or here: https://www.geeksforgeeks.org/get-month-from-date-in-pandas-python/ or wherever you prefer.

Then extract the average `total_amount` (i.e., the average cost) of a taxi cab ride for each of the months (based on the `lpep_pickup_datetime`).  Display these average values of `total_amount` (by month) in a plot.

[NOTE]
====
Even though you only are extracting data from 11 months, there seem to be a very small number of taxicab rides from December.  There are 50000 to 60000 rides in each of the 11 months, and just 10 rides in December, and that is OK.
====

.Deliverables
====
- Plot the average values of `total_amount` (by month) in a plot.
====

=== Question 3 (2 pts)

Create an empty list called `mybiglist`.  Then use list comprehension to extend `mybiglist` for each element in the list from question 2.  As a result, `mybiglist` should have the URLs for all 1000 books at the Books To Scrape website.

.Deliverables
====
- Show the head and tail of `mybiglist`.
- Verify that `mybiglist` has 1000 URLs.
- Be sure to document your work from Question 3, using some comments and insights about your work.
====


=== Question 4 (2 pts)

Write a function that takes a category from Books To Scrape, and lists all of the individual prices of the books from that category.  Do not run a function on the individual book URLs!  Instead, modify the two occurrences of `mytemplist.extend` from Question 1, so that you extract all of the prices from the category pages.  To get the price of the books on a category page, search for a `p` tag with `@class="price_color"`.

For instance, when we run the function on:

`https://books.toscrape.com/catalogue/category/books/childrens_11/index.html`

it should print:


[source, python]
----
['£54.64',
 '£36.89',
 '£56.13',
 '£58.08',
 '£13.47',
 '£12.96',
 '£22.08',
 '£23.57',
 '£18.28',
 '£53.95',
 '£25.08',
 '£35.96',
 '£52.87',
 '£34.41',
 '£32.38',
 '£22.54',
 '£56.07',
 '£48.77',
 '£43.59',
 '£26.33',
 '£16.26',
 '£28.54',
 '£37.52',
 '£10.79',
 '£10.62',
 '£10.66',
 '£52.88',
 '£28.34',
 '£22.85']
----

or if you run it on:

`https://books.toscrape.com/catalogue/category/books/science_22/index.html`

it should print:

[source, python]
----
['£42.96',
 '£57.36',
 '£44.74',
 '£37.55',
 '£55.91',
 '£28.41',
 '£10.01',
 '£13.76',
 '£16.28',
 '£13.03',
 '£57.35',
 '£25.83',
 '£30.60',
 '£29.45']
----


.Deliverables
====
- Demonstrate that your function works, by testing it on the categories suggested above.
- Be sure to document your work from Question 4, using some comments and insights about your work.
====

=== Question 5 (2 pts)

Now add the prices of all 1000 books.  You will need to remove the British pound symbol from each (you can use the `replace` function for this).  Verify that the total amount of the costs of all of the books from the Books To Scrape website is 35070.35 British pounds altogether.

.Deliverables
====
- Verify that the total amount of the costs of all of the books from the Books To Scrape website is 35070.35 British pounds altogether.
- Be sure to document your work from Question 5, using some comments and insights about your work.
====





== Submitting your Work

Please make sure that you added comments for each question, which explain your thinking about your method of solving each question.  Please also make sure that your work is your own work, and that any outside sources (people, internet pages, generating AI, etc.) are cited properly in the project template.

Congratulations! Assuming you've completed all the above questions, you are learning to apply your web scraping knowledge effectively!

Prior to submitting your work, you need to put your work xref:ROOT:templates.adoc[into the project template], and re-run all of the code in your Jupyter notebook and make sure that the results of running that code is visible in your template.  Please check the xref:ROOT:submissions.adoc[detailed instructions on how to ensure that your submission is formatted correctly]. To download your completed project, you can right-click on the file in the file explorer and click 'download'.

Once you upload your submission to Gradescope, make sure that everything appears as you would expect to ensure that you don't lose any points. We hope your first project with us went well, and we look forward to continuing to learn with you on future projects!!

.Items to submit
====
- firstname_lastname_project5.ipynb
====

[WARNING]
====
It is necessary to document your work, with comments about each solution.  All of your work needs to be your own work, with citations to any source that you used.  Please make sure that your work is your own work, and that any outside sources (people, internet pages, generating AI, etc.) are cited properly in the project template.

You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not.

**Please** take the time to double check your work. See https://the-examples-book.com/projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====

