= TDM 20200: Web Scraping Project 1 -- Spring 2025

**Motivation:** Happy New Year! In this project, we will get comfortable scraping some data from the internet in Python.

**Context:** In this project, we will use BeautifulSoup, documented here:  https://pypi.org/project/beautifulsoup4/

**Scope:** Web Scraping in Python

.Learning Objectives:
****
- We learn the basics about web scraping using Beautiful Soup in Python
****

Make sure to read about, and use the template found xref:ROOT:templates.adoc[here], and the important information about project submissions xref:ROOT:submissions.adoc[here].

== Dataset(s)

In this project we will scrape data from the following websites:

- https://datamine.purdue.edu/about/about-welcome/
- https://www.nps.gov
- https://www.scrapethissite.com/pages/forms/

== Questions

=== Question 1 (2 pts)

When scraping data from websites using Beautiful Soup, we first import `requests` and `BeautifulSoup`:

[source, python]
----
import requests
from bs4 import BeautifulSoup
----

Afterwards, we can use `requests` to scrape the data from a website, such as (for instance) The Data Mine staff directory:

[source, python]
----
myresponse = requests.get("https://datamine.purdue.edu/about/about-welcome/")
----

and then we can parse this content using `BeautifulSoup`:

[source, python]
----
mysoup = BeautifulSoup(myresponse.content, 'html.parser')
----

Afterwards, we can use `select` statements to extract elements from the website.  For instance, the names of The Data Mine staff members are given as the text after the `p` tags with `class` attribute `purdue-home-cta-grid__card-name`.

We can extract the names of all 22 staff members at once, by selecting the data in these `p` tags with `class` attribute `purdue-home-cta-grid__card-name` from the page, as follows:

[source, python]
----
mysoup.select('p[class = "purdue-home-cta-grid__card-name"]')
----

With a list comprehension, we can get these 22 names into a list:

[source, python]
----
[element.text for element in mysoup.select('p[class = "purdue-home-cta-grid__card-name"]')]
----

Now that you have the 22 staff members' names in a list, *use a similar operation* to extract the 22 staff members' job titles.

Finally, make a Pandas data frame with 22 rows and 2 columns, namely, 1 row per staff member, with their name in the left column and their job title in the right column.


.Deliverables
====
- Use Python to make a Pandas data frame with 22 rows and 2 columns, namely, 1 row per staff member, with their name in the left column and their job title in the right column.
- Be sure to document your work from Question 1, using some comments and insights about your work.
====

=== Question 2 (2 pts)

The National Park Service homepage at https://www.nps.gov lists 56 states and territories.  Their names are given as the text after the `a` tags with `class` attribute `dropdown-item dropdown-state`.

Extract the 56 names of the states and territories, and remove the whitespace from the `text`, using the `strip()` function.

Now that you have these 56 names, we can get the locations of the webpages devoted to each state and territory, by extracting the `href` attribute from each tag.  If your data is stored in `element`, then the `href` attribute can be retrieved as `element['href']`.  Append the string `'https://www.nps.gov'` to the front of each string.

Finally, make a Pandas data frame with 56 rows and 2 columns, namely, 1 row per state or territory, with their name in the left column and a string displaying the URL for that state or territory in the right column.

For instance, the row for Indiana should have `'Indiana'` in the left column and `'https://www.nps.gov/state/in/index.htm'` in the right column.

.Deliverables
====
- Use Python to make a Pandas data frame with 56 rows and 2 columns, namely, 1 row per state or territory, with their name in the left column and a string displaying the URL for that state or territory in the right column.
- Be sure to document your work from Question 2, using some comments and insights about your work.
====

=== Question 3 (2 pts)

This website http://www.scrapethissite.com/pages/forms/ has data about hockey teams, which students can use to practice scraping tables.

We can view 100 rows of this data at a time, for instance, as follows:  http://www.scrapethissite.com/pages/forms/?page_num=4&per_page=100  which gives the 4th page of the data.  In other words, this page shows rows 301 through 400.

Indeed, there are only 582 rows altogether.  By asking for 582 or more rows at a time, in this particular website, we can actually get all 582 rows at once, like this:  https://www.scrapethissite.com/pages/forms/?per_page=600

(This is website dependent!  Not every website will allow you to do this.)

Now we can extract the entire table from this website.  First we need to import Pandas, and also `io` from `StringIO`:

[source, python]
----
import pandas as pd
from io import StringIO
----

Then, as in the previous two questions, we can extract the contents of the website as follows:

[source, python]
----
myresponse = requests.get("https://www.scrapethissite.com/pages/forms/?per_page=600")
mysoup = BeautifulSoup(myresponse.content, 'html.parser')
----

and then we can read the entire table, using `StringIO` and Pandas, as follows:

[source, python]
----
pd.read_html(StringIO(str(myresponse.text)))[0]
----

which will show rows 0 through 4 and also rows 577 through 581.

.Deliverables
====
- Extract all 582 rows and 9 columns of the hockey data into a Pandas data frame.  Display rows 0 through 4 and also rows 577 through 581.
- Be sure to document your work from Question 3, using some comments and insights about your work.
====

=== Question 4 (2 pts)

Now load the ice cream products data set, stored here:

`/anvil/projects/tdm/data/icecream/combined/products.csv`

Using the `value_counts` function with the `brand` column from the ice cream products data set, how many rows are associated with each `brand`?  In other words, how many times does each `brand` occur in the `brand` column?

Now solve the same question with a different data set.
First load the head of the ice cream reviews data set, and then find how many times each `brand` occurs in the ice cream reviews data set:

`/anvil/projects/tdm/data/icecream/combined/reviews.csv`

How many times does each brand occur in the `reviews.csv` data set?

You work will be similar to the work from Question 3.  Be sure to document each question with comments about your work.

.Deliverables
====
- Use the `value_counts` function to find the number of times that each `brand` occurs in the ice cream products data set.
- Then use the `value_counts` function again, to find the number of times that each `brand` occurs in the ice cream reviews data set.
- Be sure to document your work from Question 4, using some comments and insights about your work.
====

=== Question 5 (2 pts)

Now we use `matplotlib` to display the `value_counts` from Question 4.  To accomplish this, we first load `matplotlib` as follows:

[source, python]
----
import matplotlib.pyplot as plt
----

Then we can save our counts into a variable, which we choose to call `mycounts` like this:

[source, python]
----
mycounts = myDF['brand'].value_counts()
----

and finally we can plot the names of the brands (which are the `index` values in `mycounts`) on the x-axis, and the values on the y-axis, as follows:

[source, python]
----
plt.bar(mycounts.index, mycounts)
----

Give this a try yourself, with BOTH of the data sets from Question 4.

In other words, make one plot that shows the number of occurrences of the `brand` in the ice cream products data set, and then make another plot that shows the number of occurrences of the `brand` in the ice cream reviews data set.

.Deliverables
====
- Use the `value_counts` function to find the number of times that each `brand` occurs in the ice cream products data set.
- Then use the `value_counts` function again, to find the number of times that each `brand` occurs in the ice cream reviews data set.
- Be sure to document your work from Question 5, using some comments and insights about your work.
====

== Submitting your Work

Please make sure that you added comments for each question, which explain your thinking about your method of solving each question.  Please also make sure that your work is your own work, and that any outside sources (people, internet pages, generating AI, etc.) are cited properly in the project template.

Congratulations! Assuming you've completed all the above questions, you've just finished your first project for TDM 10200! If you have any questions or issues regarding this project, please feel free to ask in seminar, over Piazza, or during office hours.

Prior to submitting your work, you need to put your work xref:ROOT:templates.adoc[into the project template], and re-run all of the code in your Jupyter notebook and make sure that the results of running that code is visible in your template.  Please check the xref:ROOT:submissions.adoc[detailed instructions on how to ensure that your submission is formatted correctly]. To download your completed project, you can right-click on the file in the file explorer and click 'download'.

Once you upload your submission to Gradescope, make sure that everything appears as you would expect to ensure that you don't lose any points. We hope your first project with us went well, and we look forward to continuing to learn with you on future projects!!

.Items to submit
====
- firstname_lastname_project1.ipynb
====

[WARNING]
====
It is necessary to document your work, with comments about each solution.  All of your work needs to be your own work, with citations to any source that you used.  Please make sure that your work is your own work, and that any outside sources (people, internet pages, generating AI, etc.) are cited properly in the project template.

You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not.

**Please** take the time to double check your work. See https://the-examples-book.com/projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====

