= Gallaudet Training: Project 3 -- 2022

**Motivation:** As we learned breifly in the last project about dictonary and sets as a type of data structure in `python`. +
 A dictionary (`dict`) is one of the most useful data structures in Python. It is a data structure that uses _key_: _value_ pairs, essentially a data structure called a https://en.wikipedia.org/wiki/Hash_table[hash table] with a useful set of properties. No matter how large the hash table grows, inserting, searching or deleting data will remain the same. +
 There are two primary ways to get information out of a *`dict`*
 * use the `get` method
 * use square brackets *[]* and strings *""*

.Practice Makes Perfect
[%collapsible]
====
[source,python]
----
my_dict = {"fruits": ["apple", "orange", "pear"], "person": "John", "vegetables": ["carrots", "peas"]}
# If "person" is indeed a key, they will function the same way
my_dict["person"]
my_dict.get("person")
# If the key does not exist, like below, they will not 
# function the same way.
my_dict.get("height") # Returns None when key doesn't exist
print(my_dict.get("height")) # By printing, we can see None in this case
my_dict["height"] # Throws a KeyError exception because the key, "height" doesn't exist
----
====

**Context:**  In this project we will introduce some basic data types, demonstrate control flow concepts, all while digging right into a dataset. +
Throughout the course, we will slowly introduce concepts from `pandas`, and popular plotting packages.

**Scope:** dicts, sets, if/else statements, opening files, tuples, lists

.Learning Objectives
****
- Explain what is a `dict` is and why it is useful.
- Understand how a `set` works and when it could be useful.
- List the differences between lists & tuples and when to use each.
- Gain familiarity with string methods, list methods, and tuple methods.
- Gain familiarity with dict methods.
****

Make sure to read about, and use the template found xref:templates.adoc[here], and the important information about projects submissions xref:submissions.adoc[here].


== Dataset(s)

The following questions will use the dataset found in Anvil:

`/anvil/projects/tdm/data/craigslist/vehicles.csv`

== Questions

=== ONE
Read in the dataset `/anvil/projects/tdm/data/craigslist/vehicles.csv` into a `pandas` DataFrame called `myDF`. As we learned in `R` we could gain an understanding of the data by using the `head()` function. 

[source,r]
----
head(myDF)
----
[loweralpha]
.. Find the function in `pandas` that is similar to the `head()` function in `R`. 
.. How can we look at the first 20 rows?
.. What is the function we can use to look at row 346?

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answers to the questions above
====


=== TWO
[loweralpha]
..Looking at the dataset, create a dictonary called `my_dict` that contains key:value pairs. The keys will be years, and the values are a single integer that represents the number of vehicles from that year.
.. Use the `year` column, a loop, and a dictionary to do this. You can use the code in the *Helpful Hint* to extract the `year` column as a list. 
.. Print the dictionary 

.Helpful Hint
[%collapsible]
====
If you get a `KeyError`, remember, you must declare each key value pair just like any other variable. Use the following code to initialize each `year` key to the value 0.
[source, python]
----
myyears = myDF['year'].dropna().to_list()
# get a list containing each unique year
unique_years = list(set(myyears))
# for each year (key), initialize the value (value) to 0
my_dict = {}
for year in unique_years:
    my_dict[year] = 0
----
====

.Insider Knowledge
[%collapsible]
====
There is a special kind of `dict` called a `defaultdict`, that allows you to give default values to a `dict`. +
A common problem that happens is when you try to access or modify keys that dont exist in `dict` you will get a _KeyError_. Python provides a `defaultdict` which will automatically create a key and a default value for it. This is a option for handling missng keys in dictionaries. 
====


== THREE
After completing question (2) you can easily access the number of vehicles from a given year. For example, to get the number of vehicles on craigslist from 1912, you can run the code below
[source,python]
----
my_dict[1912]
# or
my_dict.get(1912)
----

.Insider Knowledge
[%collapsible]
====
A `dict` stores its data in key:value pairs. Identify a "key" from `my_dict`, as well as the associated "value". Having data in this format can be very beneficial. +
One benefit is the ability to easily create a graphic using `matplotlib`.  
====
[loweralpha]
.. Use `matplotlib` to create a bar graph with the year on the x-axis, and the number of vehicles from that year on the y-axis.

.Helpful Hint
[%collapsible]
====
If you end see something like `<BarContainer object of X artists>`. Make sure at the end of your code add `plt.show()`. +
What is happening is Python is trying to `print` the plot object. That text is the result. To instead display the plot you need to call `plt.show()`. +
To use `matplotlib`, first import it:

[source,python]
----
import matplotlib.pyplot as plt
# now you can use it, for example
plt.plot([1,2,3,1])
plt.show()
plt.close()
----
The `keys` method and `values` method from `dict` could be useful here.
====


.Items to submit
====
- Python code used to solve the problem.
- The resulting plot.
- A sentence giving an example of a "key" and associated "value" from `my_dict` (e.g., a sentence explaining the 1912 example above).
====

== FOUR
Previously we used a `set` to quickly get a list of unique years in a list. + 
Other common uses of a `set` include: +
* Wanting to get a list of values that are *not* in one list present in another. + 
* Getting a ist of values that are present in both lists. +

Examine the following code: +
Notice that we are looping over multiple values. 
[loweralpha]
.. Replace the code for each of the three examples below with a code that uses *no* loops whatsoever.

[source,python]
----
listA = [1, 2, 3, 4, 5, 6, 12, 12]
listB = [2, 1, 7, 7, 7, 2, 8, 9, 10, 11, 12, 13]
# 1. values in list A but not list B
# values in list A but not list B
onlyA = []
for valA in listA:
    if valA not in listB and valA not in onlyA:
        onlyA.append(valA)
print(onlyA) # [3, 4, 5, 6]
# 2. values in listB but not list A
onlyB = []
for valB in listB:
    if valB not in listA and valB not in onlyB:
        onlyB.append(valB)
print(onlyB) # [7, 8, 9, 10, 11, 13]
# 3. values in both lists
# values in both lists
in_both_lists = []
for valA in listA:
    if valA in listB and valA not in in_both_lists:
        in_both_lists.append(valA)
print(in_both_lists) # [1,2,12]
----

.Helpful Hint
[%collapsible]
====
Use a `set` to eliminate the need for a loop. Not only is it easier to read, but it also is much faster than using a loop. 
====

.Insider Knowledge
[%collapsible]
====
As refrenced in the previous project. A set is a group of values that are unordered, unchangeable with *no* duplicate values. +
While sets are not used often, they are useful for a few common tasks such as:
* Removing duplicate values efficiently
* Finding values in one group of values that are *not* in another group of values
====

.Items to submit
====
- Code used to solve this problem.
- Output from running the code.
- The answers to the questions above
====


== FIVE

A dictionary's value does not have to be a single value (like we've shown so far). It can be _ANYTHING_. +
Notice the latitude and longitude data that is avaiable for each row in our DataFrame (`lat` and `long`, respectively). 
It would be very useful to be able to quickly "get" pairs of latitude and longitude data for a given state+
[loweralpha]
..Run the the following code to get a list of tuples where the first value is the `state`, the second value is the `lat`, and the third value is the `long`. 

[source,python]
----
states_list = list(myDF.loc[:, ["state", "lat", "long"]].dropna().to_records(index=False))
states_list[0:3] # [('az', 34.4554, -114.269), ('or', 46.1837, -123.824), ('sc', 34.9352, -81.9654)]
# to get the first tuple
states_list[0] # ('az', 34.4554, -114.269)
# to get the first value in the first tuple
states_list[0][0] # az
# to get the second tuple
states_list[1] # ('or', 46.1837, -123.824)
# to get the first value in the second tuple
states_list[1][0] # or
----

.Helpful Hint
[%collapsible]
====
If you run across an issue that does not allow you to append values to a specific key.  Make sure to first initialize the specific key to an empty list so the append method is available to use.
====

["loweralpha", start=2] 
.. Organize the latitude and longitude data in a dictionary called `geoDict` such that each state from the `state` column is a key, and the respective value is a list of tuples, where the first value in each tuple is the latitude (`lat`) and the second value is the longitude (`long`). +
For example, the first 2 (lat,long) pairs in Indiana (`"in"`) are:
[source, python]
----
geoDict.get("in")[0:2] # [(39.0295, -86.8675), (38.8585, -86.4806)]
len(geoDict.get("in")) # 5687
----
["loweralpha", start=3]
.. Now that you are able to see the `lat` and `long` for each state, plot the points for Texas (the `state` value is `"tx"`). Include the the graphic produced below in your solution, but feel free to experiment with other states. 



.Helpful Hint
[%collapsible]
====
[source, python]
----
from shapely.geometry import Point
import geopandas as gpd
from geopandas import GeoDataFrame
usa = gpd.read_file('/class/datamine/data/craigslist/cb_2018_us_state_20m.shp')
usa.crs = {'init': 'epsg:4269'}
pts = [Point(y,x) for x, y in geoDict.get("tx")]
gdf = gpd.GeoDataFrame(geometry=pts, crs = 4269)
fig, gax = plt.subplots(1, figsize=(10,10))
base = usa[usa['NAME'].isin(['Hawaii', 'Alaska', 'Puerto Rico']) == False].plot(ax=gax, color='white', edgecolor='black')
gdf.plot(ax=base, color='darkred', marker="*", markersize=10)
plt.show()
plt.close()
# to save to jpg:
plt.savefig('q5.jpg')
----
====

.Items to submit
====
- Output from running the code.
- Python code used to solve the problem.
- Graphic file (`q5.jpg`) produced for the given state.
====


=== SIX
Use your new skills to extract some sort of information from our dataset and create a graphic. This can be as simple or complicated as you are comfortable with!

.Items to submit
====
- Output from running the code.
- Python code used to solve the problem.
- Graphic file (`q5.jpg`) produced for the given state.
====