= Spring 2022 Syllabus - The Data Mine Seminar

== Course Information 


[%header,format=csv,stripes=even]
|===
Course Number and Title, CRN
STAT 19000 – The Data Mine II, CRNs vary 
STAT 29000 – The Data Mine IV, CRNs vary 
STAT 39000 – The Data Mine VI, CRNs vary 
|===

*Course credit hours:* 1 credit hour, so you should expect to spend about 3 hours per week doing work
for the class

*Prerequisites:*
None for STAT 19000. All students, regardless of background are welcome. Typically, students new to The Data Mine sign up for STAT 19000, students in their second year of The Data Mine sign up for STAT 29000, and students in their third year of The Data Mine sign up for STAT 39000. However, during the first week of the semester only, if a student new to The Data Mine has several years of coding and/or data science experience and would prefer to switch to STAT 29000, we can make adjustments. A placement exam was offered before the semester started, too.

=== Course Web Pages

- link:https://the-examples-book.com/[*The Examples Book*] - All information will be posted within  
- link:https://www.gradescope.com/[*Gradescope*] - All projects and outside events will be submitted on Gradescope 
- link:https://purdue.brightspace.com/[*Brightspace*] - Grades will be posted in Brightspace. Stduents will also take the quizzes at the beginning of the semester on Brightspace 
-  link:https://datamine.purdue.edu[*The Data Mine’s website*] - helpful resource  
-  link:https://ondemand.brown.rcac.purdue.edu/[*Jupyter Lab via the On Demand Gateway on Brown*]

=== Meeting Times 
There are officially 4 Monday class times: 8:30 am, 9:30 am, 10:30 am (all in the Hillenbrand Dining Court atrium—no meal swipe required), and 4:30 pm (link:https://purdue.webex.com/meet/mdw[synchronous online], recorded and posted later). All the information you need to work on the projects each week will be provided online on the Thursday of the previous week, and we encourage you to get a head start on the projects before class time. Dr. Ward does not lecture during the class meetings, but this is a good time to ask questions and get help from Dr. Ward, the T.A.s, and your classmates. Attendance is not required. The T.A.s will have many daytime and evening office hours throughout the week.

=== Course Description

The Data Mine is a supportive environment for students in any major from any background who want to learn some data science skills. Students will have hands-on experience with computational tools for representing, extracting, manipulating, interpreting, transforming, and visualizing data, especially big data sets, and in effectively communicating insights about data. Topics include: the R environment, Python, visualizing data, UNIX, bash, regular expressions, SQL, XML and scraping data from the internet, as well as selected advanced topics, as time permits.

=== Learning Outcomes

By the end of the course, you will be able to:

1. Discover data science and professional development opportunities in order to prepare for a career.
2. Explain the difference between research computing and basic personal computing data science capabilities in order to know which system is appropriate for a data science project.
3. Design efficient search strategies in order to acquire new data science skills.
4. Devise the most appropriate data science strategy in order to answer a research question.
5. Apply data science techniques in order to answer a research question about a big data set.



=== Required Materials

• A laptop so that you can easily work with others. Having audio/video capabilities is useful.
• Brightspace course page.
• Access to Jupyter Lab at the On Demand Gateway on Brown:
https://ondemand.brown.rcac.purdue.edu/
• “The Examples Book”: https://the-examples-book.com
• Good internet connection.



=== Attendance Policy 

While everything we are doing in The Data Mine this semester can be done online, rather than in person, and no part of your seminar grade comes from attendance, we want to remind you of general campus attendance policies during COVID-19. Students should stay home and contact the Protect Purdue Health Center (496-INFO) if they feel ill, have any symptoms associated with COVID-19, or suspect they have been exposed to the virus. In the current context of COVID-19, in-person attendance will not be a factor in the final grades, but the student still needs to inform the instructor of any conflict that can be anticipated and will affect the submission of an assignment. Only the instructor can excuse a student from a course requirement or responsibility. When conflicts can be anticipated, such as for many University-sponsored activities and religious observations, the student should inform the instructor of the situation as far in advance as possible. For unanticipated or emergency conflict, when advance notification to an instructor is not possible, the student should contact the instructor as soon as possible by email or by phone. When the student is unable to make direct contact with the instructor and is unable to leave word with the instructor’s department because of circumstances beyond the student’s control, and in cases of bereavement, quarantine, or isolation, the student or the student’s representative should contact the Office of the Dean of Students via email or phone at 765-494-1747. Below are links on Attendance and Grief Absence policies under the University Policies menu.


== Information about the Instructors 

=== The Data Mine Staff

[%header,format=csv]
|===
Name, Title, Email
Shared email we all read, , datamine@purdue.edu
Kevin Amstutz, Senior Data Scientist and Instruction Specialist, kamstut@purdue.edu 
Jamie Baker, Senior Administrative Assistant, jcbaker@purdue.edu
Maggie Betz, Managing Director of Corporate Partnerships, betz@purdue.edu
Jarai Carter, Limited Term Lecturer, 
Shuennhau Chang, Corporate Partners Senior Manager, chang@purdue.edu
Nicole Finley, Operations Manager, kingman@purdue.edu
David Glass, Senior Data Scientist, dglass@purdue.edu
Heather Goodwin, Corporate Partners Senior Manager, hgoodwi@purdue.edu
Norma Grubb, Limited Term Lecturer, 
Dave Kotterman, Managing Director, dkotter@purdue.edu
Rebecca Sharples, Managing Director of Academic Programs & Outreach, rebecca@purdue.edu
Dr. Mark Daniel Ward, Director, mdw@purdue.edu

|===


*For the purposes of getting help with this 1-credit seminar class, your most important people are:*

• *T.A.s:* Visit their xref:officehours.adoc[office hours] and use the link:https://piazza.com/[Piazza site]
• *Mr. Kevin Amstutz*, Senior Data Scientist and Instruction Specialist - Piazza is preferred method of questions
• *Dr. Mark Daniel Ward*, Director: Dr. Ward responds to questions on Piazza faster than by email


=== Communication Guidance

• *For questions about how to do the homework, use Piazza or visit office hours*. You will receive the fastest email by using Piazza versus emailing us. 
• For general Data Mine questions, email datamine@purdue.edu
• For regrade requests, use Gradescope’s regrade feature within Brightspace. Regrades should be
requested within 1 week of the grade being posted.


=== Office Hours

The xref:officehours.adoc[office hours schedule is posted here.]

Office hours are held in person in Hillenbrand lobby and on WebEx. Check the schedule to see the available schedule.

Piazza is an online discussion board where students can post questions at any time, and Data Mine staff or T.A.s will respond. Piazza is available through Brightspace. There are private and public postings. Last year we had over 11,000 interactions on Piazza, and the typical response time was around 5-10 minutes.


== Assignments and Grades


=== Course Schedule & Due Dates

xref:s2022-schedule.adoc[Click here to view the Spring 2022 Course Schedule]

See the schedule and later parts of the syllabus for more details, but here is an overview of how the course works:

In the first week of the beginning of the semester, you will have some “housekeeping” tasks to do, which include taking the Syllabus quiz and Academic Integrity quiz.

Generally, every week from the very beginning of the semester, you will have your new projects released on a Thursday, and they are due 8 days later on the Friday at 11:55 pm Purdue West Lafayette (Eastern) time. You will need to do 3 Outside Event reflections.

We will have 14 weekly projects available, but we only count your best 10. This means you could miss up to 4 projects due to illness or other reasons, and it won’t hurt your grade. We suggest trying to do as many projects as possible so that you can keep up with the material. The projects are much less stressful if they aren’t done at the last minute, and it is possible that our systems will be stressed if you wait until Friday night causing unexpected behavior and long wait times. Try to start your projects on or before Monday each week to leave yourself time to ask questions. 

[cols="4,1"]
|===

|Projects (best 10 out of Projects #1-14) |86% 
|Outside event reflections (3 total) |12% 
|Academic Integrity Quiz |1% 
|Syllabus Quiz |1% 
|*Total* |*100%*

|===




=== Grading Scale
In this class grades reflect your achievement throughout the semester in the various course components listed above. Your grades will be maintained in Brightspace. This course will follow the 90-80-70-60 grading scale for A, B, C, D cut-offs. If you earn a 90.000 in the class, for example, that is a solid A. +/- grades will be given at the instructor’s discretion below these cut-offs. If you earn an 89.11 in the class, for example, this may be an A- or a B+.

* A: 100.000% – 90.000%
* B: 89.999% – 80.000%
* C: 79.999% – 70.000%
* D: 69.999% – 60.000%
* F: 59.999% – 0.000%


 
=== Late Policy 

We generally do NOT accept late work. For the projects, we count only your best 10 out of 14, so that gives you a lot of flexibility. We need to be able to post answer keys for the rest of the class in a timely manner, and we can’t do this if we are waiting for other students to turn their work in.


=== Projects 

• The projects will help you achieve Learning Outcomes #2-5.
• Each weekly programming project is worth 10 points.
• There will be 13 projects available over the semester, and your best 10 will count.
• The 3 project grades that are dropped could be from illnesses, absences, travel, family
emergencies, or simply low scores. No excuses necessary.
• No late work will be accepted, even if you are having technical difficulties, so do not work at the
last minute.
• There are many opportunities to get help throughout the week, either through Piazza or office
hours. We’re waiting for you! Ask questions!
• Follow the instructions for how to submit your projects properly through Gradescope in
Brightspace.
• It is ok to get help from others or online, although it is important to document this help in the
comment sections of your project submission. You need to say who helped you and how they
helped you.
• Each week, the project will be posted on the Thursday before the seminar, the project will be
the topic of the seminar and any office hours that week, and then the project will be due by
11:55 pm Eastern time on the following Friday. See the schedule for specific dates.
• If you need to request a regrade on any part of your project, use the regrade request feature
inside Gradescope. The regrade request needs to be submitted within one week of the grade being posted (we send an announcement about this).


=== Outside Event Reflections

• The Outside Event reflections will help you achieve Learning Outcome #1. They are an opportunity for you to learn more about data science applications, career development, and diversity.
• Throughout the semester, The Data Mine will have many special events and speakers, typically happening in person so you can interact with the presenter, but some may be online and possibly recorded.
• These eligible opportunities will be posted on The Data Mine’s website (https://datamine.purdue.edu/events/) and updated frequently. Feel free to suggest good events that you hear about, too.
• You are required to attend 3 of these over the semester, with 1 due each month. See the schedule for specific due dates.
• You are welcome to do all 3 reflections early. For example, you could submit all 3 reflections in September.
• You must submit your outside event reflection within 1 week of attending the event or watching the recording.
• Follow the instructions on Brightspace for writing and submitting these reflections.
• At least one of these events should be on the topic of Professional Development. These
events will be designated by “PD” next to the event on the schedule.
• For each of the 3 required events, write a minimum 1-page (double-spaced, 12-pt font) reflection that includes the name of the event and speaker, the time and date of the event, what was discussed at the event, what you learned from it, what new ideas you would like to explore as a result of what you learned at the event, and what question(s) you would like to ask the presenter if you met them at an after-presentation reception. This should not be just a list of notes you took from the event—it is a reflection. The header of your reflection should not take up more than 2 lines!
• We read every single reflection! We care about what you write! We have used these connections to provide new opportunities for you, to thank our speakers, and to learn more about what interests you.



== How to succeed in this course

If you would like to be a successful Data Mine student:

• Be excited to challenge yourself and learn impressive new skills. Don’t get discouraged if something is difficult—you’re here because you want to learn, not because you already know everything!
• Start on the weekly projects on or before Mondays so that you have plenty of time to get help from your classmates, TAs, and Data Mine staff. Don’t wait until the due date to start!
• Remember that Data Mine staff and TAs are excited to work with you! Take advantage of us as resources.
• Network! Get to know your classmates, even if you don’t see them in an actual classroom. You are all part of The Data Mine because you share interests and goals. You have over 800 potential new friends!
• Use “The Examples Book” with lots of explanations and examples to get you started. Google, Stack Overflow, etc. are all great, but “The Examples Book” has been carefully put together to be the most useful to you. https://the-examples-book.com
• Expect to spend approximately 3 hours per week on the projects. Some might take less time, and occasionally some might take more.
• Don’t forget about the syllabus quiz, academic integrity quiz, and outside event reflections. They all contribute to your grade and are part of the course for a reason.
• If you get behind or feel overwhelmed about this course or anything else, please talk to us!
• Stay on top of deadlines. Announcements will also be sent out every Monday morning, but you
should keep a copy of the course schedule where you see it easily.
• Read your emails!



== Purdue Policies & Resources 

=== Academic Guidance in the Event a Student is Quarantined/Isolated 

If you must miss class at any point in time during the semester, please reach out to me via email so that we can communicate about how you can maintain your academic progress. If you find yourself too sick to progress in the course, notify your adviser and notify me via email or Brightspace. We will make arrangements based on your particular situation. Please note that, according to link:https://protect.purdue.edu/updates/purdue-announces-additional-details-for-students-on-normal-operations-for-fall-2021/[Details for Students on Normal Operations for Fall 2021] announced on the Protect Purdue website, “individuals who test positive for COVID-19 are not guaranteed remote access to all course activities, materials, and assignments.”

=== Class Behavior

You are expected to behave in a way that promotes a welcoming, inclusive, productive learning environment.  You need to be prepared for your individual and group work each week, and you need to include everybody in your group in any discussions.  Respond promptly to all communications and show up for any appointments that are scheduled.  If your group is having trouble working well together, try hard to talk through the difficulties—this is an important skill to have for future professional experiences.  If you are still having difficulties, ask The Data Mine staff to meet with your group.

=== Academic Integrity 

Academic integrity is one of the highest values that Purdue University holds.  Individuals are encouraged to alert university officials to potential breaches of this value by either link:mailto:integrity@purdue.edu[emailing] or by calling 765-494-8778.  While information may be submitted anonymously, the more information that is submitted provides the greatest opportunity for the university to investigate the concern.

In STAT 19000/29000/39000, we encourage students to work together. However, there is a difference between good collaboration and academic misconduct. We expect you to read over this list, and you will be held responsible for violating these rules. We are serious about protecting the hard-working students in this course. We want a grade for STAT 19000/29000/39000 to have value for everyone and to represent what you truly know. We may punish both the student who cheats and the student who allows or enables another student to cheat. Punishment could include receiving a 0 on a project, receiving an F for the course, and/or being reported to the Office of The Dean of Students.

*Good Collaboration:*

• First try the project yourself, on your own.
• After trying the project yourself, then get together with a small group of other students who
have also tried the project themselves to discuss ideas for how to do the more difficult problems. Document in the comments section any suggestions you took from your classmates or your TA.
• Finish the project on your own so that what you turn in truly represents your own understanding of the material.
• Look up potential solutions for how to do part of the project online, but document in the comments section where you found the information.
• If the assignment involves writing a long, worded explanation, you may proofread somebody’s completed written work and allow them to proofread your work. Do this only after you have both completed your own assignments, though.

*Academic Misconduct:*

• Divide up the problems among a group. (You do #1, I’ll do #2, and he’ll do #3: then we’ll share our work to get the assignment done more quickly.)
• Attend a group work session without having first worked all of the problems yourself.
• Allowing your partners to do all of the work while you copy answers down, or allowing an
unprepared partner to copy your answers.
• Letting another student copy your work or doing the work for them.
• Sharing files or typing on somebody else’s computer or in their computing account.
• Getting help from a classmate or a TA without documenting that help in the comments section.
• Looking up a potential solution online without documenting that help in the comments section.
• Reading someone else’s answers before you have completed your work.
• Have a tutor or TA work though all (or some) of your problems for you.
• Uploading, downloading, or using old course materials from Course Hero, Chegg, or similar sites.
• Using the same outside event reflection (or parts of it) more than once. Using an outside event reflection from a previous semester.
• Using somebody else’s outside event reflection rather than attending the event yourself.

The link:https://www.purdue.edu/odos/osrr/honor-pledge/about.html[Purdue Honor Pledge] “As a boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together - we are Purdue"  

Please refer to the link:https://www.purdue.edu/odos/osrr/academic-integrity/index.html[student guide for academic integrity] for more details.


*Purdue’s Copyrighted Materials Policy:*

Among the materials that may be protected by copyright law are the lectures, notes, and other material presented in class or as part of the course. Always assume the materials presented by an instructor are protected by copyright unless the instructor has stated otherwise. Students enrolled in, and authorized visitors to, Purdue University courses are permitted to take notes, which they may use for individual/group study or for other non-commercial purposes reasonably arising from enrollment in the course or the University generally.
Notes taken in class are, however, generally considered to be “derivative works” of the instructor’s presentations and materials, and they are thus subject to the instructor’s copyright in such presentations and materials. No individual is permitted to sell or otherwise barter notes, either to other students or to any commercial concern, for a course without the express written permission of the course instructor. To obtain permission to sell or barter notes, the individual wishing to sell or barter the notes must be registered in the course or must be an approved visitor to the class. Course instructors may choose to grant or not grant such permission at their own discretion, and may require a review of the notes prior to their being sold or bartered. If they do grant such permission, they may revoke it at any time, if they so choose.

=== Nondiscrimination Statement
Purdue University is committed to maintaining a community which recognizes and values the inherent worth and dignity of every person; fosters tolerance, sensitivity, understanding, and mutual respect among its members; and encourages each individual to strive to reach his or her own potential.  In pursuit of its goal of academic excellence, the University seeks to develop and nurture diversity.  The University believes that diversity among its many members strengthens the institution, stimulates creativity, promotes the exchange of ideas, and enriches campus life. link:https://www.purdue.edu/purdue/ea_eou_statement.php[Link to Purdue’s nondiscrimination policy statement.]

=== Students with Disabilities
Purdue University strives to make learning experiences as accessible as possible. If you anticipate or experience physical or academic barriers based on disability, you are welcome to let me know so that we can discuss options. You are also encouraged to contact the Disability Resource Center at: link:mailto:drc@purdue.edu[drc@purdue.edu] or by phone: 765-494-1247.  

If you have been certified by the Office of the Dean of Students as someone needing a course adaptation or accommodation because of a disability OR if you need special arrangements in case the building must be evacuated, please contact The Data Mine staff during the first week of classes.  We are happy to help you.

=== Mental Health Resources

•	*If you find yourself beginning to feel some stress, anxiety and/or feeling slightly overwhelmed,* try link:https://purdue.welltrack.com/[WellTrack]. Sign in and find information and tools at your fingertips, available to you at any time. 
•	*If you need support and information about options and resources*, please contact or see the link:https://www.purdue.edu/odos/[Office of the Dean of Students]. Call 765-494-1747. Hours of operation are M-F, 8 am- 5 pm.
•	*If you find yourself struggling to find a healthy balance between academics, social life, stress*, etc. sign up for free one-on-one virtual or in-person sessions with a link:https://www.purdue.edu/recwell/fitness-wellness/wellness/one-on-one-coaching/wellness-coaching.php[Purdue Wellness Coach at RecWell]. Student coaches can help you navigate through barriers and challenges toward your goals throughout the semester. Sign up is completely free and can be done on BoilerConnect. If you have any questions, please contact Purdue Wellness at evans240@purdue.edu.
•	*If you’re struggling and need mental health services:* Purdue University is committed to advancing the mental health and well-being of its students. If you or someone you know is feeling overwhelmed, depressed, and/or in need of mental health support, services are available. For help, such individuals should contact link:https://www.purdue.edu/caps/[Counseling and Psychological Services (CAPS)] at 765-494-6995 during and after hours, on weekends and holidays, or by going to the CAPS office of the second floor of the Purdue University Student Health Center (PUSH) during business hours. 

=== Violent Behavior Policy 

Purdue University is committed to providing a safe and secure campus environment for members of the university community. Purdue strives to create an educational environment for students and a work environment for employees that promote educational and career goals. Violent Behavior impedes such goals. Therefore, Violent Behavior is prohibited in or on any University Facility or while participating in any university activity. See the link:https://www.purdue.edu/policies/facilities-safety/iva3.html[University’s full violent behavior policy] for more detail.

=== Diversity and Inclusion Statement

In our discussions, structured and unstructured, we will explore a variety of challenging issues, which can help us enhance our understanding of different experiences and perspectives. This can be challenging, but in overcoming these challenges we find the greatest rewards. While we will design guidelines as a group, everyone should remember the following points:

•	We are all in the process of learning about others and their experiences. Please speak with me, anonymously if needed, if something has made you uncomfortable.
•	Intention and impact are not always aligned, and we should respect the impact something may have on someone even if it was not the speaker’s intention.
•	We all come to the class with a variety of experiences and a range of expertise, we should respect these in others while critically examining them in ourselves.

=== Basic Needs Security Resources 

Any student who faces challenges securing their food or housing and believes this may affect their performance in the course is urged to contact the Dean of Students for support. There is no appointment needed and Student Support Services is available to serve students from 8:00 – 5:00, Monday through Friday. The link:https://www.purdue.edu/vpsl/leadership/About/ACE_Campus_Pantry.html[ACE Campus Food Pantry] is open to the entire Purdue community). 

Considering the significant disruptions caused by the current global crisis as it related to COVID-19, students may submit requests for emergency assistance from the link:https://www.purdue.edu/odos/resources/critical-need-fund.html[Critical Needs Fund]. 

=== Course Evaluation

During the last two weeks of the semester, you will be provided with an opportunity to give anonymous feedback on this course and your instructor. Purdue uses an online course evaluation system. You will receive an official email from evaluation administrators with a link to the online evaluation site. You will have up to 10 days to complete this evaluation. Your participation is an integral part of this course, and your feedback is vital to improving education at Purdue University. I strongly urge you to participate in the evaluation system. 

You may email feedback to us anytime at link:mailto:datamine@purdue.edu[datamine@purdue.edu]. We take feedback from our students seriously, as we want to create the best learning experience for you!  

=== General Classroom Guidance Regarding Protect Purdue 

Any student who has substantial reason to believe that another person is threatening the safety of others by not complying with Protect Purdue protocols is encouraged to report the behavior to and discuss the next steps with their instructor. Students also have the option of reporting the behavior to the link:purdue.edu/odos/osrr/[Office of the Student Rights and Responsibilities]. See also link:https://catalog.purdue.edu/content.php?catoid=7&navoid=2852#purdue-university-bill-of-student-rights[Purdue University Bill of Student Rights] and the Violent Behavior Policy under University Resources in Brightspace.  

=== Campus Emergencies

In the event of a major campus emergency, course requirements, deadlines and grading percentages are subject to changes that may be necessitated by a revised semester calendar or other circumstances. Here are ways to get information about changes in this course:  

•	Brightspace or by e-mail from Data Mine staff.  
•	General information about a campus emergency can be found on the Purdue website:  link:www.purdue.edu[]. 
  

=== Illness and other student emergencies

Students with *extended* illnesses should contact their instructor as soon as possible so that arrangements can be made for keeping up with the course. Extended absences/illnesses/emergencies should also go through the Office of the Dean of Students. 

=== Disclaimer 
This syllabus is subject to change. Changes will be made by an announcement in Brightspace and the corresponding course content will be updated. 

