= Templates

Our course project template can be found xref:book:projects:attachment$project_template.ipynb[here], or on Scholar:

`/depot/datamine/apps/templates/project_template.ipynb`

Students in STAT 19000, 29000, and 39000 can use and modify this as a template as needed, for all project submissions. This template is a starting point for all projects.

Most of the time, this template will be used with the f2021-s2022 or f2021-s2022-r kernel. By default, the f2021-s2022 kernel runs Python code and the f2021-s2022-r kernel runs R code. To run other types of code, see below. Any format or template related questions should be asked in Piazza.

== Running `R` code using the `f2021-s2022` kernel

. First, load the `rpy2.ipython` extension.
+
[source, ipython]
----
%load_ext rpy2.ipython
----
. Next, to run R code, in a new cell, run the following.
+
[source,ipython]
----
%%R

my_vec <- c(1,2,3)
my_vec
----

As you can see, any cell that begins with `%%R` will run the R code in that cell. If a cell does not begin with `%%R`, it will be assumed that the code is Python code, and run accordingly.

== Running SQL queries using the `f2021-s2022` kernel

. First, load the sql extension.
+
[source,ipython]
----
%load_ext sql
----
+
. Next, you need to establish a connection with the database. If this is a sqlite database, you can use the following command.
+
[source,ipython]
----
%sql sqlite:///my_db.db
# or
%sql sqlite:////home/class/datamine/path/to/my_db.db
----
+
Otherwise, if this is a mysql database, you can use the following command.
+
[source,ipython]
----
%sql mariadb+pymysql://username:password@my_url.com/my_database
----
+
. Next, to run SQL queries, in a new cell, run the following.
+
[source,ipython]
----
%%sql

SELECT * FROM my_table;
----

As you can see, any cell that begins with `%%sql` will run the SQL query in that cell. If a cell does not begin with `%%sql`, it will be assumed that the code is Python code, and run accordingly.

== Running `bash` code using the `f2021-s2022` kernel

To run `bash` code, in a new cell, run the following.

[source,bash]
----
%%bash

ls -la
----

As you can see, any cell that begins with `%%bash` will run the `bash` code in that cell. If a cell does not begin with `%%bash`, it will be assumed that the code is Python code, and run accordingly.

[TIP]
====
Code cells that start with `%` or `%%` are sometimes referred to as magic cells. To see a list of available magics, run `%lsmagic` in a cell. 

The commands listed in the "line" section are run with a single `%` and can be mixed with other code. For example, the following cell contains (in order) some Python code, uses a single line magic, followed by some more Python code.

[source,ipython]
----
import pandas as pd

%time myDF = pd.read_parquet("/class/datamine/data/whin/weather.parquet")

myDF.head()
----

The commands listed in the "cell" section are run with a double `%%` and apply to the entire cell, rather than just a single line. For example, `%%bash` is an example of a cell magic. 

You can read more about some of the available magics in the https://ipython.readthedocs.io/en/stable/interactive/magics.html#[official documentation].
====

== Including an image in your notebook

To include an image in your notebook, use the following Python code.

[source,python]
----
from IPython import display
display.Image("./cloud.png")
----

Here, `./cloud.png` is the path to the image you would like to include.

[IMPORTANT]
====
If you choose to include an image using a Markdown cell, and the `![](...)` syntax, please note that while the notebook will render properly in our https://ondemand.brown.rcac.purdue.edu environment, it will _not_ load properly in any other environment where that image is not available. For this reason it is critical to include images using the method shown here.
====
