= 301 Project 05 - Multiple Linear Regression  

== Project Objectives

Last project we went through the steps to build a Linear regression model. In this project let us build a simple Multiple Linear Regression Model


== Reading and Resources

- [An Introduction to Statistical Learning](https://www.statlearning.com/)

== Dataset
- `/anvil/projects/tdm/data/boston.csv`
Boston.csv contain 13 features( independent variables) and one median value (dependent variable)

Load the dataset
[source,python]
----
import pandas as pd
my_df = pd.read_csv("/anvil/projects/tdm/data/boston.csv")
----
== Questions


=== Question 1 (2 points)

Before start building model, you can check the dataset to familiar with it. like besides size, dimensions, you can also check if there are empty values
[NOTE]
====
`isnull` can be used to identify empty value and check for dataset's missing values, it returns true of false. You may get more information from https://www.w3schools.com/python/pandas/ref_df_isnull.asp[here]
====
.. Please check how many missing value 'my_df' contains
+
[TIP]
====
"sum" can be useful to do calculation
====
.. Please list the independent variables and what is dependent variable from 'my_df'

[TIP]
====
The following statement can help you to get the list 

[source,python]
----
# Independent variables
X = my_df.iloc[:,:-1].values

# Dependent variable
y = my_df.iloc[:,-1].values
----
====

We can visualize the dependent variable with the following statement

[source,python]
----
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
plt.hist(X, bins = 20)
plt.title("Housing Price")
plt.xlabel("Median Values")
plt.ylabel("Boston")
plt.show
----


[NOTE]
====
We will start build mode. As we mentioned in previous project, We will first split whole dataset into 2 sets: training and testing

[source,python]
---- 
from sklearn.model_selection import train_test_split

# Split to training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, y,
test_size=0.2, random_state=42)
----
====

==== Question 2 (2 points)

.. Please visualize the whole dataset and training set by the provide statement
.. Please compare if you observer anything by comparing 2 plots

[NOTE]
====
Next we will train a Multiple Linear Regression model using the training data.

[source,python]
----
from sklearn.linear_model import LinearRegression

model = LinearRegression()
# Train the model
model.fit(X_train, Y_train)
----
Intercept is the dependent variable's value if all independent variables values are zero
Coefficients can also be called weights, represent the change in related to dependant variable while 1 unit of independent variable change
====
.. Please find out what is the intercept and coefficients for the model

[NOTE]
====
Now let us make predictions on the test set with the model

[source, python]
----
Y_pred = model.predict(X_test)
----
====
=== Question 3 (2 points)

.. Please display the predict values as well as testing values
.. Observe the 2 sets, what is your finding?


[NOTE]
We can evaluate the model by examining the intercept, coefficients, and the R-squared value.

[source,python]
----
# Intercept of the model
print("Intercept:", model.intercept_)

# Coefficients of the model
print("Coefficients:", model.coef_)

# R-squared value
r_squared = model.score(X_test, Y_test)
print("R-squared value:", r_squared)
----
.. Please find out what is the R-squared value of your model? What does it signify?

[NOTE]
====
residuals are difference between testing value of dependent variable with predicted value of it

[source,python]
residuals = Y_test-Y_pred
====

=== Question 4 ( 2 points)

.. Please use matplotlib to create a residual plot to check the distribution of the residuals
.. Please explain if you have any finding

[NOTE]
====
You can also visualize the predicted values vs. actual values to find out how well the model works
====

=== Question 5 ( 2 points)
.. Please create a scatter plot to visualize the relationship between predicted values vs. actual values
.. Please explain if you have any finding


Project 05 Assignment Checklist
====
* Jupyter Lab notebook with your code, comments, and output for the assignment
    ** `firstname-lastname-project05.ipynb`

* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double-check that your submission is complete and contains all of your code and output before submitting. If you are on a spotty internet connection, it is recommended to download your submission after submitting it to make sure what you _think_ you submitted was what you _actually_ submitted.

In addition, please review our [submission guidelines](xref:projects:current-projects:submissions.adoc) before submitting your project.
====

