= 301 Project 03 - K-Nearest Neighbor Model Introduction II

== Project Objectives 

In this project, we will continue to understand the foundational knowledge of the K-Nearest Neighbors (KNN) algorithm using a regression approach.

== Reading and Resources 

- [An Introduction to Statistical Learning](http://www.statlearning.com/)
- [What is the k-nearest neighbors (KNN) algorithm](https://www.ibm.com/topics/knn)

== Dataset

`/anvil/projects/tdm/data/boston.csv`

This dataset contains various features of houses in Boston. The target variable is the median value of owner-occupied homes.

Let us load the data to a DataFrame

[source,python]
----
import pandas as pd

my_df = pd.read_csv('/anvil/projects/tdm/data/boston.csv')
----

== Questions

=== Question 1 (2 points) 

.. What are the mean, median, and standard deviation of the median value  (target variable)?


Next we will need to preprocess the data

== Question 2 (2 points) 

.. Complete the following code to get the features and target

[source,python]
----
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Prepare the data
X = # your code here 
y = # your code here 
----

=== Question 3 (2 points)

Next we will split the dataset to training and testing

.. Complete the following code to split the dataset using appropriate function and parameters

[source,python]
----
X_train, X_test, y_train, y_test = # your code here 
----

Then let us standardize the features

=== Question 4 (2 points)

.. Please complete the following code 
.. Please explain why we need to standardize the features

[source,python]
----
scaler = StandardScaler()
X_train = # Your code here #
X_test = # Your code here #
----


Now let us train a simple KNN regression model. 

=== Question 5 (2 points)

.. Please complete the following code

[source,ptyhon]
----
from sklearn.neighbors import KNeighborsRegressor

# Initialize the KNN regressor
knn = KNeighborsRegressor(n_neighbors=3)

# Train the model on the training set
# Your code here
---- 


Project 03 Assignment Checklist
====

* Jupyter Lab notebook with your code, comments, and output for the assignment
    ** `firstname-lastname-project03.ipynb` 

* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double-check that your submission is complete and contains all of your code and output before submitting. If you have a spotty internet connection, it is recommended to download your submission after submitting it to ensure what you _think_ you submitted is what you _actually_ submitted.

In addition, please review our xref:projects:submissions.adoc[submission guidelines] before submitting your project.
====