= 301 Project # - Intro to ML - Data Preprocessing

== Project Objectives

Learn how to preprocess data for machine learning models. This includes one-hot encoding, scaling, and train-validation-test splitting.

.Learning Objectives
****
- Learn how to one-hot encode categorical variables
- Learn why scaling data is important
- Learn how to split data into training, validation, and test sets
****


== Dataset

- `/anvil/projects/tdm/data/Iris.csv`

[NOTE]
====
make a note block
====

[source,language]
----
make a code cell in language
----
== Questions

=== Question 1 (2 points)

.Deliverables
====
- Question
====

=== Question 2 (2 points)

.Deliverables
====
- Question
====

=== Question 3 (2 points)

.Deliverables
====
- Question
====

=== Question 4 (2 points)

.Deliverables
====
- Question
====

=== Question 5 (2 points)

.Deliverables
====
- Question
====


== Submitting your Work

.Items to submit
====
- firstname_lastname_project3.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====