= 301 Project 03 - K-Nearest Neighbors II

== Project Objectives 

In this project, we will continue to understand the foundational ideas of the K-Nearest Neighbors (KNN) algorithm using a regressive approach.

== Reading and Resources 

- http://www.statlearning.com/[An Introduction to Statistical Learning]
- https://www.ibm.com/topics/knn[What is the k-nearest neighbors (KNN) algorithm]

== Dataset

`/anvil/projects/tdm/data/boston.csv`


== Questions

[NOTE]
====
This project will largely be based on concepts covered in the previous two projects. As a result, much of the code will be more on you to write. If you are struggling with these questions, feel free to refer back to the examples provided in Projects 1 and 2 for more substantive starting code to build off of.
====

=== Question 1 (2 points) 

This dataset contains various features of houses in Boston. The target variable is the median value of owner-occupied homes.

Let us load the data to a DataFrame

[source,python]
----
import pandas as pd

my_df = pd.read_csv('/anvil/projects/tdm/data/boston.csv')
----

.. What are the mean, median, and standard deviation of the median price of owner-occupied homes(our target variable)?

[TIP]
====
If you need a reminder on how to do this, take a glance at https://www.geeksforgeeks.org/create-the-mean-and-standard-deviation-of-the-data-of-a-pandas-series/[this article].
====

== Question 2 (2 points) 

Next we will need to pre-process the data

.. Complete the following code to get the features and target

[source,python]
----
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Prepare the data
X = # your code here 
y = # your code here 
----

=== Question 3 (2 points)

Next we will split the dataset to training and testing sets

.. Complete the following code to split the dataset using the appropriate function and parameters

[source,python]
----
X_train, X_test, y_train, y_test = # your code here 
----

=== Question 4 (2 points)

Then let's standardize the features

.. Please complete the following code 
.. Please explain the motivation behind standardizing the features

[source,python]
----
scaler = StandardScaler()
X_train = # Your code here #
X_test = # Your code here #
----
 

=== Question 5 (2 points)

Now let's train a simple KNN regression model.

.. Please complete the following code

[source,python]
----
from sklearn.neighbors import KNeighborsRegressor
# Initialize the KNN regressor
knn = KNeighborsRegressor(n_neighbors=3)

# Train the model on the training set
# Your code here
----


Project 03 Assignment Checklist
====

* Jupyter Lab notebook with your code, comments, and output for the assignment
    ** `firstname-lastname-project03.ipynb` 

* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double-check that your submission is complete and contains all of your code and output before submitting. If you have a spotty internet connection, it is recommended to download your submission after submitting it to ensure what you _think_ you submitted is what you _actually_ submitted.

In addition, please review our https://the-examples-book.com/projects/submissions[submission guidelines] before submitting your project.
====