= 301 Project 05 - Classifiers - K-Nearest Neighbors (KNN) I

== Project Objectives

In this project, we will go learn about the K-Nearest Neighbors (KNN) machine learning algorithm, develop it without the use of a library, and apply it to a small dataset.

.Learning Objectives
****
- Learn the mathematics behind a KNN
- Create a KNN
- Use KNN to classify data
****

== Supplemental Reading and Resources

- url[display name]

== Dataset

- `/anvil/projects/tdm/data/Iris.csv`

[NOTE]
====
make a note block
====

[source,language]
----
make a code cell in language
----
== Questions

=== Question 1 (2 points)

First, let's learn the basics of how a KNN works. A KNN operates by calculating the difference between input features to all samples in its existing database, and performing a majority vote between the k closest samples to classify the input features. If k=1, it simply chooses the closest class. If k=3, it takes chooses the majority between the 3 nearest. If there is ever a tie, it will randomly select a class.

[NOTE]
====
This random selection during a tie is not ideal, but it is a simple way to handle the case. In the next project, we will explore a way to handle ties in a more sophisticated manner.
====

To think about this simply, let's create an example dataset with 2 input features. This dataset uses a hue and size to identify fruit.

[cols=4*]
|===
|#|Hue | Size| Output Variable
|1|22|1|Banana
|2|27|.9|Banana
|3|87|.05|Grape
|4|84|.03|Grape
|===

Given this dataset, we want to identify a fruit with Hue=24, Size=0.95.

To find the distance between 2d points, you can use the formula
latexmath:[dist = sqrt((X-X_0)^2 + (Y-Y_0)^2)]

.Deliverables
====
- Which point is our unknown fruit closest to? (put the #)
- What fruit should our unknown fruit be classified as, assuming k=1?
- What would happen if we set k=4?
- Are there any problems with the way our data is currently formatted (think about scaling from Project 1)?
====

=== Question 2 (2 points)

Because the KNN simply calculates the distance between points, it is very important that the input features are scaled. If one feature has a significantly larger range than another, then it is significantly more important in the distance calculation. If we want each feature to have the same importance, they should all have the same range.
[NOTE]
====
Sometimes input features are scaled, but not uniformly. This allows the model creator to essentially manually assign importance to each feature. We will explore this in the next project.
====

.Deliverables
====
- Question
====

=== Question 3 (2 points)

.Deliverables
====
- Question
====

=== Question 4 (2 points)

.Deliverables
====
- Question
====

=== Question 5 (2 points)

.Deliverables
====
- Question
====


== Submitting your Work

.Items to submit
====
- firstname_lastname_project4.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====