= 301 Project 02 - K-Nearest Neighbor Model Introduction I

== Project Objectives

In this project, we will go through the following steps to train and evaluate a K-Nearest Neighbors (KNN) classifier:

- Load and Explore the Data
- Pre-process the Data
- Train the KNN Classifier

== Reading and Resources

- https://www.statlearning.com/[An Introduction to Statistical Learning]
- https://www.ibm.com/topics/knn[What is the k-nearest neighbors (KNN) algorithm]

== Dataset

- `/anvil/projects/tdm/data/Iris.csv`


== Questions

[NOTE]
====

First, let us Load and Explore the Data.

[source,python]
----
import pandas as pd

# Load the Iris dataset from the provided CSV file
my_df = pd.read_csv('/anvil/projects/tdm/data/Iris.csv')

# Display the first few rows of the dataset
print(my_df.head())
----
====

=== Question 1 (2 points)

.. How many features does the Iris dataset have?     
.. How many iris classes does the Iris dataset have? 

 
[TIP]
====

Classes are the outputs based on the input features, also called labels or categories.

Features are input variables used by models to make predictions.
====


[NOTE]
====

Next, let us Pre-process the Data and split the dataset into training and testing sets. 

The training set is the data used to train the model, and the testing set is used to evaluate the model.

[source,python]
----
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = my_df.iloc[:, :-1].values 
y = my_df['target'].values

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

----
====

=== Question 2 (2 points)

.. Please explain the meaning of the following statement, and what will be the values of X and y

[source,python]
----
X = my_df.iloc[:, :-1].values
y = my_df['target'].values
----

[NOTE]
====

The following code is used to standardize the data:

[source,python]
----
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
----
====

=== Question 3 (2 points)

.. Please state why we need to standardize the data and the difference between the original data and the standardized data using the code provided above.

[NOTE]
====

The next step is to `Initialize` and `Train` the KNN Classifier.

The parameter `k` in K-Nearest Neighbors (KNN) is the number of nearest neighbors. Changing `k` will impact the model's performance:

- k = 1: one neighbor, highly flexible (low bias) but can have high variance.
- k = 5: five neighbors, less sensitive to noise compared to k = 1.
- k = 10: ten neighbors, even less sensitive with lower variance.

https://blog.dataiku.com/bias-and-noise-in-machine-learning[This article] will give you more idea what are bias, variance or noise 

For small clean datasets like iris.csv, you possibly get perfect accuracy for different k values.

[source, python]
----
from sklearn.neighbors import KNeighborsClassifier

# Initialize the KNN classifier
knn = KNeighborsClassifier(n_neighbors=3)

# Train the classifier
knn.fit(X_train, y_train)
----
====

=== Question 4 (2 points)

.. Use your own words to state what impact changing the number of neighbors (k) has on the model's performance.

[NOTE]
====
We can then make a prediction using the following sample code:

[source,python]
----
predicted_class = knn.predict([X_test[0]])
----
====

=== Question 5 (2 points)

.. What is the predicted class for the first instance in the testing set using the KNN classifier with k=3?


Project 02 Assignment Checklist
====

* Jupyter Lab notebook with your code, comments, and output for the assignment
    ** `firstname-lastname-project02.ipynb` 

* Submit files through Gradescope
====

[WARNING]
====
_Please_ make sure to double-check that your submission is complete and contains all of your code and output before submitting. If you have a spotty internet connection, it is recommended to download your submission after submitting it to ensure what you _think_ you submitted is what you _actually_ submitted.

In addition, please review our https://the-examples-book.com/projects/submissions[submission guidelines] before submitting your project.
====