= TDM 20100: Project 8 -- Fall 2026

== Overview About Single Agent Models (Part 2)

== Project Objectives

Motivation: Large Language Models (LLMs) can generate text, but many tasks require them to interact with external systems, and to make decisions based on available information. AI agents extend what LLMs can do by allowing the model to use tools, follow workflows, and complete tasks on behalf of users.

Context: In this project, students will (continue to) build a single-agent system using LangGraph, LangChain, Ollama, and a customer order dataset. Students will create tools, design agent workflows, connect the agent to a dataset, and implement safeguards to ensure the agent follows set rules. 

Scope: AI agents, LangGraph, LangChain, tool calling

.Learning Objectives
****
- Understand the purpose and workflow of a single-agent system.
- Build agent workflows using LangGraph and state-based execution.
- Connect an agent to an external dataset.
- Set rules for agent behavior to ensure reliability.
****  

== Dataset
- /anvil/projects/tdm/data/orders/Superstore_modified.csv


[IMPORTANT]
====
Use 4 cores for this project!
====

=== Question 1

https://the-examples-book.com/projects/fall2026/20100/stateversion3

https://the-examples-book.com/projects/fall2026/20100/graphversion3

After setting up version 3 of the `state.py` and `graph.py` Python files (and remembering to use `graph = construct_graph()` to reconstruct the graph with these updates), run the tests in the file:

https://the-examples-book.com/projects/fall2026/20100/risks

and show the outputs.

(You can continue to use the same version of `tools.py` from Version 2 in the previous project, on Questions 1 and 2 of this project.  No changes are needed yet, for the `tools.py`.)

=== Question 2

Using version 3 of the three Python files, explain (using a few sentences in English) how the agent handles order cancellation requests.

=== Question 3

https://the-examples-book.com/projects/fall2026/20100/toolsversion2

https://the-examples-book.com/projects/fall2026/20100/graphversion2

After setting up version 4 of the `tools.py` and `graph.py` Python files (and remembering to use `graph = construct_graph()` to reconstruct the graph with these updates), run the tests in the file:

https://the-examples-book.com/projects/fall2026/20100/cannotsolverequest

and show the outputs.

(You can continue to use the same version of `state.py` from Version 3 that you used in the questions above, on Questions 1 and 2 of this project.  No changes are needed for Version 4, for the `state.py`.)

=== Question 4

Many companies are using agent-based models for customer service requests.  Write two paragraphs in English about your understanding about customer service requests that rely on prompts, rules, tools, and may have potential failures and hallucinations.  For instance, are such changes are automations good or bad, and why?  Please comment on your views related to the integration of such tools, your opinion about their potential to aid economic development and potentially to improve customer service?  What are your opinions of single agent-based models, now that you see how they work behind the scenes?

=== Question 5

Agent-based models need governance, checks, rules, appropriate handling of potential hallucinations and mistakes, etc.  Please comment on your opinion about ethics and compliance issues, related to the pervasive usage of such tools.  What strengths and weakness do you perceive?  What are your perceptions about the potential needs related to governance, guiderails, and ethical usage of such tools?






== Submitting your Work

Please make sure that you added comments for each question, which explain your thinking about your method of solving each question.  Please also make sure that your work is your own work, and that any outside sources (people, internet pages, generative AI, etc.) are cited properly in the project template.


Prior to submitting your work, you need to put your work xref:ROOT:templates.adoc[into the project template], and re-run all of the code in Jupyter Lab and make sure that the results of running that code is visible in your template.  Please check the xref:ROOT:submissions.adoc[detailed instructions on how to ensure that your submission is formatted correctly]. To download your completed project, you can right-click on the file in the file explorer and click 'download'.


.Items to submit
====
- firstname_lastname_project8.ipynb
====

[WARNING]
====
It is necessary to document your work, with comments about each solution.  All of your work needs to be your own work, with citations to any source that you used.  Please make sure that your work is your own work, and that any outside sources (people, internet pages, generative AI, etc.) are cited properly in the project template.

You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not.

**Please** take the time to double check your work. See xref:ROOT:submissions.adoc[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====


