= Assignments You can Work On

We always like to brainstorm for resource ideas could be helpful for current and future students. If you have any ideas, please feel free to reach out or bring them to our monthly check-ins.

In the very beginning of the project, there's a low demand for technical assistance as students are learning about TDM CRP model and expectations. Sometimes, you will find yourself with some free time, and if you do, those are items you can work on.

**Feel free to collaborate with other technical TAs on developing templates and guidelines.**

IMPORTANT: Remember no project confidential information is allowed to be discussed with other TAs (other than your co-TA).

== Develop some starting research questions
CRP projects usually have a project charter which often consists of major benchmarks and expectations. Please check with your CRP staff if you don't have the access to your project charter.

During the first mentor meeting, the mentor usually will explain high-level expectations and goals they have for the CRP project. This is when you should take notes and transform them into a somewhat actionable step-by-step plan for your students. You should seek some feedback/discussion with your co-TA as well.

Some research questions to get you started can be xref:./techskills.adoc[found here]. +
If you don't have the data yet, please visit https://the-examples-book.com/crp/TAs/trainingModules/ta_training_Q_and_A[this Q&A page] for some ideas.

The execution can vary. One example can be a list of major research questions with sub questions/details under them. Those questions can help your team build a stronger kanban/task board.

It'd be great if there's a template we can re-use for future projects as a starting place for developing research questions.

== Research Existing Solutions and Examples
Often, it can be helpful if you do research on similar or existing solutions to the problems addressed in the project, especially when you find examples that students can work through.

Once you have completed the student technical survey, it's a good time to start digging into some great resources for team upskilling. Are there sites/videos/code exercises that you have worked with that could help students on the team start to build their skills?

== How to Create Test Cases Guideline
Students who are new to coding typically realize the importance of creating their own test cases later on or maybe never do so if they are not in STEM. Sometimes, CRP mentors will provide test cases or validate the code themselves. However, this is not expected from all mentors. It'd be a large workload for a technical TA to test all code produced through the CRP project. Instead, it'd be great if there's a beginner-friendly document or guideline that discusses about test cases and how to create and use them.

== Git and Version Control Tutorial
We have a https://the-examples-book.com/starter-guides/tools-and-standards/git/github-anvil[short example how to use GitHub in Anvil], but it'd be helpful to have a tutorial on using Git for version control, which is essential for collaborative data science projects like your CRP project.

== Code Style and Best Practices
This is a good opportunity to consider the process you want for your CRP project. Do you want your students to have PR review conducted by you in beginning and then students learn how to pull review other students' code later this semester? How can you encourage students to review each other's code? How can you show them how to provide constructive feedback regarding their code quality? Are students confident in their code that they can merge the changes to the main without a pull review?

Helping your team's setup code comment guidelines and a code review process can be a good use of your free time. Code comments are a vital part of documentation and can make a big difference for projects that continue between semesters.

A guide on coding conventions and best practices for clean and readable code. Also emphasizes the importance of comments, documentation, and modular code design.

== Debugging Techniques
A guide on common debugging techniques, including how to use debugging tools, print statements, and error messages effectively.

Maybe it'd be helpful for you to lead a quick session to show students how to google for how-to's or debugging their code message. This is something we have never done before.

== Effective Communication of Results
Students only have 50 minutes with their mentor who is the product owner, so it's important to know how to use the time efficiently. Students know they need to provide updates to their mentor weekly, and they need to be prepared. Many often don't know how to present technical updates in the beginning.

A guide on communicating their findings through clear and compelling visualizations, reports, and presentations.
