= Technical TA Expectations

The idea of a technical TA is new to TDM, and thank you to all of the technical TAs this semester for being part of the pilot semester. We aim to learn from your experiences and hope this is a positive experience for you as well.

== Technical TA Responsibilities

Technical TAs will co-lead a CRP project with another TA who is more aligned with the role of a Scrum Master. It is expected that both TAs collaborate effectively to lead a team of students.

Technical TAs are positioned to guide student teams through questions that arise during the research project. They are not expected to do any grading or taking attendance (those are the other TA's responsibilities).

The ultimate goal of having a technical TA on a CRP project team is to offer more accessible technical support to the students. This support encompasses debugging technical issues and teaching professional technical skills. 

NOTE: Technical TAs are not expected to be experts in all aspects of their project. The crucial part is to empower team members to conduct research, test hypotheses, and strive to improve their results. Technical TAs will play a key role in helping students feel comfortable and finding resources for this methodology.

A few core areas of focus for the technical TA position are included below:

* Assisting when setting up technical environments.
* Guide students through building and testing different research hypothesis. 
* Help to troubleshoot technical questions. 
* Escalate questions to TDM team when additional assistance is required

== Actionable Items

* Attend your assigned lab and mentor meetings weekly. 
* Submit timesheet justification weekly in SuccessFactors. https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module5_4_time_sheets[(Time Sheet Info)]
* Submit technical report biweekly in Gradescope. (You don't need to do team reports)
* Attend monthly TA meeting with TDM with general TAs.
* Attend monthly check-in meeting with TDM data science team (only technical TAs).



[%header,format=csv,stripes=even,%autowidth.stretch]
|===      
Technical Report,Due date (at 11:59 Eastern Time)
1, Jan. 17
2, Jan. 24
3, Feb. 7
4, Feb. 21
5, Mar. 6
6, Mar. 27
7, Apr. 10
|===


== How to Ask For Help

* Weekly Labs
** Talk with your co-TA. You will work closely with your co-TA, and strong collaboration will most likely result in a strong team of students.
** You will have a staff either from TDM Corporate Partners team or data science team come to your lab weekly.
* Microsoft Teams
** There's a private channel under TDM_2023_CRP_TA for technical TAs. Staff from TDM data science team are in the private channel. You can use this to ask general and non-NDA-binding questions that can be useful for other technical TAs to know.
** You can direct message someone from TDM data science team if you have sensitive questions that are directly related to your project.
* datamine-help@purdue.edu
** For large asks, it's better to submit a ticket by emailing to datamine-help@purdue.edu. Building a database server is an example of a big request that can be submitted as a ticket, not a DM.
** You also can submit a ticket for any sensitive question instead of DM.
** Anyone including your students can submit a ticket to datamine-help@purdue.edu, but we encourage them to check with you first to see if you are able to help.