= Technical TA Guide

This guide is designed to give an overview of many of the systems that are core to The Data Mine (TDM). 

This guide can be leveraged by anyone, but many of the topics are directed toward technical TA's.

The idea of a technical TA is new to TDM, and thank you to all of the technical TAs this semester for being part of the pilot semester. We aim to learn from your experiences and hope this is a positive experience for you as well.

== Technical TA Responsibilities

Technical TAs will co-lead a CRP project with another TA who is more aligned with the role of a Scrum Master. It is expected that both TAs collaborate effectively to lead a team of students.

Technical TAs are positioned to guide student teams through questions that arise during the research project. They are not expected to do any grading or taking attendance (those are the other TA's responsibilities).

The ultimate goal of having a technical TA on a CRP project team is to offer more accessible technical support to the students. This support encompasses debugging technical issues and teaching professional technical skills.

A few core areas of focus for the technical TA position are included below:

* Assisting when setting up technical environments.
* Guide students through building and testing different research hypothesis. 
* Help to troubleshoot technical questions. 
* Escalate questions to TDM team when additional assistance is required.

== (Actionable) Expectations and Submissions

* Attend your assigned lab and mentor meetings weekly
* Submit timesheet justification weekly
* Submit technical report biweekly
* Attend monthly TA meeting with TDM with general TAs
* Attend monthly check-in meeting with TDM data science team (only technical TAs)