== Teachable Technical Skills

=== Team Research

One of the most important aspects of The Data Mine is that it gives teams a great chance to build and test hypothesis with very low consequence. 

As part of this, the technical TA should be a core driver of a team's research philosophy. 

When a team is researching a new technique, or stuck on a problem, think through:

* What is being done in industry?
* Publications that may show how similar problems were solved. 
* Can the problem be broken down into smaller parts?
* Are there any subject matter experts at Purdue or the mentor's company who could help?
* Would a team brainstorming session help to find potential solutions?

The Data Mine will always be here to help, but one of the most important things you can take away from these projects are the abilities to think critically, come up with solutions, and then test those solutions to see what works. 

Experiential learning projects are a great time to build these skills. Because the projects are focused on the team learning and growing together. 

When submitting a ticket to The Data Mine team, we'll want to know:

* What the problem is.
** Code examples are always amazing. 
* What research was done to try to fix the problem?
* What were the outcomes of those attempted fixes?
* Do you have any theories on what may be causing the problem?

It's always OK to ask for help, but we want to understand what steps you took to try and solve the problem as a team before you escalated to us. 

=== Documentation

Documentation is one of the most impactful and least popular tasks for a team. Many of The Data Mine's projects continue for multiple years but have new students. 

That means that if teams don't do a good job with documentation, a team may spend their first semester (or more) working through what was done previously. 

TA's should help the teams continually build their documentation. This can be done through a https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes[GitHub README]. 

[TIP]
====
It's often a good idea to hand over your documentation to someone who isn't directly in the project (mentor or mentor's colleague) and see if they can follow the steps. 
====

[TIP]
====
Treat documentation like any other work task. Make them deliverables and review them as a team. 

The more practice a person gets, the easier documentation gets. 
====

=== Test Cases and PR Review
Classes often provide test cases for students to use, ensuring their code works as expected. However, this is not always the case for a CRP project, and even less so for real-world scenarios. Developing the skill to create one's own test cases is valuable for building confidence in the presented code.

It can be risky if the same student creates and merges new changes into the repository. Therefore, it is encouraged for a student to review and test another student's pull request.

Technical TAs can guide students on creating test cases and reviewing another person's code for feedback and testing purposes. They aim to foster an environment where students feel encouraged and comfortable sharing their work and giving/receiving feedback from each other.