= Sprint #6

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 4/3
|Mon 3/31

|*Sprint End Date*
|Wed 4/16
|Sun 4/13

|*Due Date*
2+| Wed 4/16 by 11:59 PM ET

|===

== To Do

&#10003; Submit final symposium materials (poster and video) in Gradescope on behalf of your team due Wednesday 4/9 at 11:59 PM ET. 

&#10003; Upload your final poster and final video to your project team's MS teams channel.

&#10003; Complete Time Sheet

* Timesheet #11 due Sunday 4/6 at 11:59 PM ET.

* Timesheet #12 due Sunday 4/13 at 11:59 PM ET.

&#10003; See the xref:spring2025/schedule.adoc[Spring Schedule] for timesheet, grading, and report deadlines.

* Sprint Tasks for students: xref:students:spring2025/sprint6.adoc[Sprint 6 Tasks]

* Please review the following Guidelines for The Data Mine Corporate Partners Symposium: xref:students:spring2025/spring2025_symposium_expectations.adoc[Spring 2025 Symposium Details]. 

== Sprint Schedule

=== Team Meeting #1 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.

* Ensure students are assigned tasks to work on before meeting again in the next lab.


=== Lab Section #1 (1 hour and 50 Minutes):

* There will not be a professional development discussion this week. Instead, use this extra time to incorporate feedback from your draft poster and video to the team's Final Presentation and 3MT Video Presentation. 

=== Team Meeting #2 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles,roadblocks or barriers that they experienced while completing this weeks task?
** What do they plan on committing to completing by next mentor meeting?
* Time for questions from students to mentor.

* Ensure students are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #2 (1 hour and 50 Minutes):

* There will not be a professional development discussion this week. Instead, use this extra time to work on your Final Presentation Draft and Project objectives. See below for more information on the Final Presentation.

* Sprint Tasks for students: xref:students:spring2025/sprint6.adoc[Sprint 6 Tasks]

== Symposium Presentation

To recap the team's project work, your team will present a poster at The Data Mine Corporate Partners Symposium. Please review the following Guidelines for the Symposium: xref:students:spring2025/spring2025_symposium_expectations.adoc[Spring 2025 Symposium Details]. 

