= Sprint #5

// == Intro Video

// ++++
// <iframe width="560" height="315" src="https://www.youtube.com/embed/13g7l3zQPq4?si=dnseCld3iCECTpJk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
// ++++

== Sprint Dates

*_Monday, March 17 to Saturday March 22:  Spring Break (no Corporate Partner meetings/classes)_*

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 3/13
|Mon 3/10

|*Sprint End Date*
|Wed 4/2
|Sun 3/30

|*Due Date*
2+| Wed 4/2 by 11:59 PM ET

|===

== To Do

&#10003; Complete Time Sheet

* Timesheet #9 due Sunday 3/16 at 11:59 PM ET.

* Timesheet #10 due Sunday 3/30 at 11:59 PM ET.

&#10003; Grade Sprint #4 professional development assignment by Wed, 3/12 at 11:59 PM ET on https://www.gradescope.com/[Gradescope].

&#10003; Grade Sprint #4 Report assignment by Wed, 3/26 at 11:59 PM ET on https://www.gradescope.com/[Gradescope].

&#10003; Submit your symposium draft video on behalf of your team to https://www.gradescope.com/[Gradescope].

&#10003; Set-up a meeting with corporate partner mentor to complete mid-semester student feedback on https://www.gradescope.com/[Gradescope] by Wed 3/12 11:59 PM ET. Please make them aware and share the rubric with them early so they may begin preparing. link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module5_4_mentor_feedback[Mentor and TA Feedback Guide]

&#10003; Attend Monthly Meeting 3 on Wednesday, 4/2(See TA schedule for timings).

&#10003; See the xref:spring2025/schedule.adoc[Spring Schedule] for timesheet, grading, and report deadlines.

&#10003; Completed second required semester check-in with students! link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module4_9_check_ins[Semester Check-Ins with Students Guide]

&#10003; Create and share a technical specification document for your team to work on. Make sure to assign sections of the technical specification for students to complete during Sprint #5. link:https://the-examples-book.com/crp/students/technical_specification_documentation[Technical Specification Guide]

**https://the-examples-book.com/crp/students/spring2025/sprint4[Student Sprint Task]**

* Technical Specification

&#10003; Have a fantastic spring break!!!

== Sprint Schedule

[IMPORTANT]

=== Team Meeting #1 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
** Questions related to the company. (Internship, Full-Time Opportunities, and etc.)
* Ensure students are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #1 (1 hour and 50 Minutes):

* Start the meeting by taking attendance and having a weekly standup with your team.
** What did you work on last week?
** What are you currently working on?
** What are your blockers?
* Complete semester check-in with students. Review https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module4_9_check_ins[Check-In Guide] for more information.
* Assign sprint tasks and deadlines to team members on the Kanban board in MS Teams.
* A Data Mine staff member will stop by the lab sometime to provide support and answer any questions.

=== Team Meeting #2 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
** Questions related to the company. (Internship, Full-Time Opportunities, and etc.)
* Ensure students are assigned tasks to work on before meeting again in the next lab.
** Record tasks and deadlines on the Kanban board in MS Teams.s are assigned tasks to work on before meeting again in the next lab.

=== Lab Section #2 (1 hour and 50 Minutes):

* Start the meeting by taking attendance and having a daily standup with your team.

* Break students into pairs and have them review each others LinkedIN posts written in PD #4. Encourage students to post these at the end of the semester. 

* Assign sprint tasks and deadlines to team members on the Kanban board in MS Teams.
* Collaboration and work-time with team members.
* A Data Mine staff member will stop by the lab sometime to provide support and answer any questions.

* Sprint Tasks for students: xref:students:spring2025/sprint5.adoc[Sprint 5 Tasks]
