= Sprint #4

// == Intro Video

// ++++
// <iframe width="560" height="315" src="https://www.youtube.com/embed/8kzhUzJHZk4?si=DqQUVDAlCFDyV0Gq" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
// ++++

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 2/27
|Mon 2/24

|*Sprint End Date*
|Wed 3/12
|Sun 3/9

|*Due Date*
2+| Wed 3/12 by 11:59 PM ET

|===


== To Do


&#10003; Complete Time Sheet

* Timesheet #7 due Sunday 3/2 at 11:59 PM ET.

* Timesheet #8 due Sunday 3/9 at 11:59 PM ET.

&#10003; Attend Monthly Meeting #2 on 2/26.

&#10003; Draft poster and draft video due March 12, 2024, delegate tasks related to the draft poster and video to your team members. See https://the-examples-book.com/crp/students/spring2025/poster_guidelines[Poster Guidelines] and https://the-examples-book.com/crp/students/spring2025/video_guidelines[Video Guidelines] for more information.

&#10003; Set-up a meeting with your mentor to complete mid-semester feedback. You can begin this assignment during this sprint with your mentor. Please make them aware and share the rubric with them early so they may begin preparing. link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module5_4_mentor_feedback[Mentor and TA Feedback Guide]

&#10003; Complete TA and Student 1:1's. This task is flexible during Sprint 4. Please find time with each team member to check in with them individually.  link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module4_9_check_ins[Semester Check-Ins with Students]

&#10003; Set-up a meeting with corporate partner mentor to complete mid-semester student feedback on https://www.gradescope.com/[Gradescope] by Wed 3/12 11:59 PM ET. Please make them aware and share the rubric with them early so they may begin preparing. link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module5_4_mentor_feedback[Mentor and TA Feedback Guide]

&#10003; See the xref:spring2024/schedule.adoc[Spring Schedule] for timesheet, grading, and report deadlines.

**https://the-examples-book.com/crp/students/spring2025/sprint4[Student Sprint Task]**

* Review project documentation
* Three Minute Thesis

== Sprint Schedule

=== Team Meeting #1 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
** Questions related to the company. (Internship, Full-Time Opportunities, and etc.)
* Ensure students are assigned tasks to work on before meeting again in the next lab.


=== Lab Section #1 (1 hour and 50 Minutes):

* Start the meeting by taking attendance and having a weekly standup with your team.
** What did you work on last week?
** What are you currently working on?
** What are your blockers?
* Complete semester check-in with students. Review https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module4_9_check_ins[Check-In Guide] for more information.
* Assign sprint tasks and deadlines to team members on the Kanban board in MS Teams.
* A Data Mine staff member will stop by the lab sometime to provide support and answer any questions.

=== Team Meeting #2 (50 minutes):

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Project Updates from students:
** What have they been working on since the last sprint?
** Were there any hurdles, roadblocks or barriers that they experienced while completing this week's task?
** What do they plan on committing to completing by the next mentor meeting?
* Time for questions from students to mentor.
** Questions related to the project.
** Questions related to the company. (Internship, Full-Time Opportunities, and etc.)
* Ensure students are assigned tasks to work on before meeting again in the next lab.
** Record tasks and deadlines on the Kanban board in MS Teams.

=== Lab Section #2 (1 hour and 50 Minutes):

* Start the meeting by taking attendance and having a daily standup with your team.
* Begin lab by facilitating a discussion on the Sprint 4 Three Minute Thesis professional development assignment.
** Use this PowerPoint to facilitate the discussion: xref:attachment$3mt_facilitation_guide 2.pptx[3 minute thesis facilitation guide]
** Sprint Tasks for students: xref:students:spring2025/sprint4.adoc[Sprint 4 Tasks]
* Assign sprint tasks and deadlines to team members on the Kanban board in MS Teams.
* Collaboration and work-time with team members.
* A Data Mine staff member will stop by the lab sometime to provide support and answer any questions.
* Remind students to complete xref:students:spring2025/sprint4.adoc[Sprint 4 Tasks]