= Sprint #7

[IMPORTANT]
====
 *CONTENT STILL UNDER CONSTRUCTION FOR SPRING 2025!!!!*
====

== Sprint Dates

[cols="<.^1,^.^1,^.^1"]
|===

| |*Lab (Mon/Tues) then Meeting (Thurs/Fri)* |*Meeting (Mon/Tues) then Lab (Thurs/Fri)*

|*Sprint Start Date*
|Thurs 4/11
|Sun 4/8

|*Sprint End Date*
|Wed 4/24
|Sun 4/21

|*Due Date*
2+| Wed 4/24 by 11:59 PM ET

|*Symposium*
2+| Wed 4/24

|===

== To Do 

&#10003; Upload your final poster and final video to your project team's MS Teams channel.

&#10003; See the xref:spring2024/schedule.adoc[Spring Schedule] for timesheet, grading, and report deadlines.

&#10003; Attend Monthly Meeting 4 on Wednesday, April 17. 

&#10003; Print your project team's poster link:https://the-examples-book.com/crp/students/spring2024/poster_guidelines#print-your-poster[How to Print Team Poster]

* Do not print your team's poster before April 15. Corporate partner review needs to be completed by The Data Mine. 

* Print codes will be communicated via email to access printing funds. 

&#10003; Final Semester Feedback completed with mentor due Wednesday 4/24 
**Please share the link:https://the-examples-book.com/crp/TAs/trainingModules/ta_training_module5_4_mentor_feedback[Mentor and TA Feedback Guide] with your mentor ahead of time so they may prepare and set a time to meet. 

&#10003; Attend the Symposium Wednesday, April 24 from 4:00 - 6:30pm with your student project team.

* Please review the following Guidelines for The Data Mine Corporate Partners Symposium: xref:students:spring2024/spring2024_symposium_expectations.adoc[Spring 2024 Symposium Details]. 

* Track student attendance at the Symposium.

&#10003; Complete final survey via Qualtrics due Sunday 4/28

* Your feedback is very important to us. There are specific questions about your TA experience - we value your input!

&#10003; Complete Time Sheets

* Timesheet #13 due Sunday 4/7 at 11:59 PM ET.

* Timesheet #14 due Sunday 4/14 at 11:59 PM ET.

== Sprint Schedule

[NOTE]
====
*The semester is not over yet. Your team is still required to host labs and meetings to work on deliverables.*
====

=== Team Meeting #1 (50 minutes): 

* This is a credit-bearing class; take attendance and make sure students have their cameras turned on.

* Review the final draft of the poster with corporate partner mentor.
* Your CRP Liaison will be in touch with the mentor for their approval of the poster ahead of printing and public display.

=== Lab Section #1 (1 hour and 50 Minutes): 

* Final preparation for Symposium Poster Presentations including practice Q&A.
* Continue to build out the company product or create add-ons. 
* Clean up and organize documentation. 
* Establish symposium schedule with student team.

=== Team Meeting #2 (50 minutes):

* Offer this meeting time to share your project work with the broader corporate partner's company. The mentor can forward the meeting invitation to members of their organization who are not able to attend the symposium. 

=== Lab Section #2 (1 hour and 50 Minutes):

* Final preparation for Symposium Poster Presentations.
* Continue to build out the company product or create add-ons. 
* Clean up and organize documentation.

&#10003; Review Sprint Tasks for students: xref:students:fall2023/sprint7.adoc[Sprint 7 Tasks]. 
