= Spring 2023 Syllabus - The Data Mine Corporate Partners

== Purdue Policies & Resources 

=== Academic Guidance in the Event a Student is Quarantined/Isolated 

If you must miss class at any point in time during the semester, please reach out to me via email so that we can communicate about how you can maintain your academic progress. If you find yourself too sick to progress in the course, notify your adviser and notify me via email or Brightspace. We will make arrangements based on your particular situation. Please note that, according to link:https://protect.purdue.edu/updates/purdue-announces-additional-details-for-students-on-normal-operations-for-fall-2021/[Details for Students on Normal Operations for Fall 2021] announced on the Protect Purdue website, “individuals who test positive for COVID-19 are not guaranteed remote access to all course activities, materials, and assignments.”

=== Academic Integrity 

Academic integrity is one of the highest values that Purdue University holds.  Individuals are encouraged to alert university officials to potential breaches of this value by either link:mailto:integrity@purdue.edu[emailing] or by calling 765-494-8778.  While information may be submitted anonymously, the more information that is submitted provides the greatest opportunity for the university to investigate the concern.

The link:https://www.purdue.edu/odos/osrr/honor-pledge/about.html[Purdue Honor Pledge] “As a boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together - we are Purdue"  

Please refer to the link:https://www.purdue.edu/odos/osrr/academic-integrity/index.html[student guide for academic integrity] for more details.

=== Nondiscrimination Statement
link:https://www.purdue.edu/purdue/ea_eou_statement.php[Link to Purdue’s nondiscrimination policy statement.]

=== Students with Disabilities
Purdue University strives to make learning experiences as accessible as possible. If you anticipate or experience physical or academic barriers based on disability, you are welcome to let me know so that we can discuss options. You are also encouraged to contact the Disability Resource Center at: link:mailto:drc@purdue.edu[drc@purdue.edu] or by phone: 765-494-1247.  

If you have been certified by the Office of the Dean of Students as someone needing a course adaptation or accommodation because of a disability OR if you need special arrangements in case the building must be evacuated, please contact The Data Mine staff during the first week of classes.  We are happy to help you.

=== Mental Health Resources
•	*If you find yourself beginning to feel some stress, anxiety and/or feeling slightly overwhelmed,* try link:https://purdue.welltrack.com/[WellTrack]. Sign in and find information and tools at your fingertips, available to you at any time. 
•	*If you need support and information about options and resources*, please contact or see the link:https://www.purdue.edu/odos/[Office of the Dean of Students]. Call 765-494-1747. Hours of operation are M-F, 8 am- 5 pm.
•	*If you find yourself struggling to find a healthy balance between academics, social life, stress*, etc. sign up for free one-on-one virtual or in-person sessions with a link:https://www.purdue.edu/recwell/fitness-wellness/wellness/one-on-one-coaching/wellness-coaching.php[Purdue Wellness Coach at RecWell]. Student coaches can help you navigate through barriers and challenges toward your goals throughout the semester. Sign up is completely free and can be done on BoilerConnect. If you have any questions, please contact Purdue Wellness at evans240@purdue.edu.
•	*If you’re struggling and need mental health services:* Purdue University is committed to advancing the mental health and well-being of its students. If you or someone you know is feeling overwhelmed, depressed, and/or in need of mental health support, services are available. For help, such individuals should contact link:https://www.purdue.edu/caps/[Counseling and Psychological Services (CAPS)] at 765-494-6995 during and after hours, on weekends and holidays, or by going to the CAPS office of the second floor of the Purdue University Student Health Center (PUSH) during business hours. 

=== Violent Behavior Policy 

Purdue University is committed to providing a safe and secure campus environment for members of the university community. Purdue strives to create an educational environment for students and a work environment for employees that promote educational and career goals. Violent Behavior impedes such goals. Therefore, Violent Behavior is prohibited in or on any University Facility or while participating in any university activity. See the link:https://www.purdue.edu/policies/facilities-safety/iva3.html[University’s full violent behavior policy] for more detail.

=== Inclusion Statement

In our discussions, structured and unstructured, we will explore a variety of challenging issues, which can help us enhance our understanding of different experiences and perspectives. This can be challenging, but in overcoming these challenges we find the greatest rewards. While we will design guidelines as a group, everyone should remember the following points:

•	We are all in the process of learning about others and their experiences. Please speak with me, anonymously if needed, if something has made you uncomfortable.
•	Intention and impact are not always aligned, and we should respect the impact something may have on someone even if it was not the speaker’s intention.
•	We all come to the class with a variety of experiences and a range of expertise, we should respect these in others while critically examining them in ourselves.

=== Basic Needs Security Resources 

Any student who faces challenges securing their food or housing and believes this may affect their performance in the course is urged to contact the Dean of Students for support. There is no appointment needed and Student Support Services is available to serve students from 8:00 – 5:00, Monday through Friday. The link:https://www.purdue.edu/vpsl/leadership/About/ACE_Campus_Pantry.html[ACE Campus Food Pantry] is open to the entire Purdue community). 

Considering the significant disruptions caused by the current global crisis as it related to COVID-19, students may submit requests for emergency assistance from the link:https://www.purdue.edu/odos/resources/critical-need-fund.html[Critical Needs Fund]. 

=== Course Evaluation

During the last two weeks of the semester, you will be provided with an opportunity to give anonymous feedback on this course and your instructor. Purdue uses an online course evaluation system. You will receive an official email from evaluation administrators with a link to the online evaluation site. You will have up to 10 days to complete this evaluation. Your participation is an integral part of this course, and your feedback is vital to improving education at Purdue University. I strongly urge you to participate in the evaluation system. 

You may email feedback to us anytime at link:mailto:datamine@purdue.edu[datamine@purdue.edu]. We take feedback from our students seriously, as we want to create the best learning experience for you!  

=== General Classroom Guidance Regarding Protect Purdue 

Any student who has substantial reason to believe that another person is threatening the safety of others by not complying with Protect Purdue protocols is encouraged to report the behavior to and discuss the next steps with their instructor. Students also have the option of reporting the behavior to the link:purdue.edu/odos/osrr/[Office of the Student Rights and Responsibilities]. See also link:https://catalog.purdue.edu/content.php?catoid=7&navoid=2852#purdue-university-bill-of-student-rights[Purdue University Bill of Student Rights] and the Violent Behavior Policy under University Resources in Brightspace.  

=== Campus Emergencies

In the event of a major campus emergency, course requirements, deadlines and grading percentages are subject to changes that may be necessitated by a revised semester calendar or other circumstances. Here are ways to get information about changes in this course:  

•	Brightspace or by e-mail from Data Mine staff.  
•	General information about a campus emergency can be found on the Purdue website:  link:www.purdue.edu[]. 
  

=== Absences, Illness, and other student emergencies

Please see the link:https://catalog.purdue.edu/content.php?catoid=15&navoid=18634#a-attendance[official attendance policies of the Office of the Registrar].  

The University has established the following as reasons to be granted an excused absence from class:

* Grief/Bereavement
* Military Service
* Jury Duty
* Parenting Leave
* Medical Excuse

See the link above for details. 

=== Disclaimer 
This syllabus is subject to change. Changes will be made by an announcement in Brightspace and the corresponding course content will be updated. 
