--- 
title: "Example slides"
author: "John Smith" 
date: "Jan 1, 2020"
output: ioslides_presentation 
---

## Headers

All first level headers, or headers preceded by one `#`, like `# My header` will automatically create a new slide.

All second level headers, or headers preceded by two `#`, like `## My header` will automatically create a new slide.

## Manually create a new slide

To manually create a new slide, you can use `***`. This will create a new slide.

For example, I will create a new slide after this sentence.

***

And this is my new slide...

## Incremental lists

You can create slides that will automatically create enough slides to emulate a new bullet or numbered list item appearing. For example the following lists could appear incrementally as you are presenting:

**Ordered list:**

1. One
2. Two
3. Three

**Unordered list:**

- First
- Second
- Third

***

To do so, simply place the `>` character before each item in the list. For example:

**Ordered list:**

>1. One
>2. Two
>3. Three

**Unordered list:**

>- First
>- Second
>- Third

## The end
