= `mean`

== Basics

`mean` is a function that calculates the average of a vector of values.

You will often find yourself using the `na.rm` argument, short for *NA* value **r**e**m**oval. Most real-life data will contain missing values somewhere, and `na.rm = TRUE` will automatically remove those values from consideration during a function call or computation. `na.rm = FALSE` is the default, so make sure to include `na.rm = TRUE` if you're unsure of your data's composition.

[NOTE]
====
As mentioned https://www.statmethods.net/input/missingdata.html#:~:text=In%20R%2C%20missing%20values%20are,for%20character%20and%20numeric%20data[here], `NA` indicates a missing datum/value, while `NaN` indicates an impossible number (division by zero). We'll show in Example 2 that `na.rm` does not care about the difference.
====

{sp}+

=== Examples

==== How do I get the average of a vector of values?

.Click to see solution
[%collapsible]
====
[source,R]
----
mean(c(1,2,3,4))
----

----
[1] 2.5
----
====

==== How do I get the average of the values in a vector when some of the values are: `NA`, `NaN`? What happens if I want to include those values?

.Click to see solution
[%collapsible]
====
First, we show the implication of not including `na.rm = TRUE`:

[source,R]
----
mean(c(1,2,3,NaN))
----
----
[1] NaN
----

That's obviously not what we want. We would only ever want `na.rm = F` if we were checking for null values being present in the data.

Now, the rest of the examples, executed properly:

[source,R]
----
mean(c(1,2,3,NaN), na.rm=TRUE)
----
----
[1] 2
----

[source, R]
----
mean(c(1,2,3,NA), na.rm=TRUE)
----
----
[1] 2
----

[source, R]
----
mean(c(1,2,NA,NaN,4), na.rm=TRUE)
----
----
[1] 2.333333
----
====