= R Books

There are lots of books on R.

* The New S Language, by Richard A. Becker, John M. Chambers, and Allan R. Wilks (Chapman & Hall, 1988), a.k.a. the "Blue Book"; covers S version 2

* Statistical Models in S, by John M. Chambers and Trevor J. Hastie (Chapman & Hall, 1992), a.k.a. the "White Book"; covers S version 3

* Programming with Data, by John M. Chambers (Springer, 1998), a.k.a. the "Green Book"; covers S version 4

* Software for Data Analysis: Programming with R, by John M. Chambers (Springer, 2008), available from https://link.springer.com/book/10.1007/978-0-387-75936-4[Springer]

* Modern Applied Statistics with S, 4th Edition, by William N. Venables and Brian D. Ripley (Springer, 2002)

* S Programming, by William N. Venables and Brian D. Ripley (Springer, 2000)

* Data Analysis and Graphics Using R, 3rd Edition, by John Maindonald and John Braun (Cambridge, 2010)

* The R Book, by Michael J. Crawley (Wiley, 2007)

* Statistics: An Introduction using R, by Michael J. Crawley (Wiley, 2005)

* Using R for Introductory Statistics, Second Edition, by John Verzani (Chapman & Hall/CRC, 2014)




* Statistical Computing: An Introduction to Data Analysis using S-Plus, by Michael J. Crawley (Wiley, 2002)

* A Handbook of Statistical Analyses Using R, by Brian Everitt and Torsten Hothorn (Chapman & Hall/CRC, 2006)

* Statistical Computing with R, by Maria L. Rizzo (Chapman & Hall/CRC, 2008)

* A First Course in Statistical Programming with R, Second Edition, by W. John Braun and Duncan J. Murdoch (Cambridge, 2016)

* Data Manipulation with R, by Phil Spector (Springer, 2008), available from https://link.springer.com/book/10.1007/978-0-387-74731-6[Springer]

* The Basics of S-PLUS, 4th Edition, by Andreas Krause and Melvin Olson (Springer, 2005), available from https://link.springer.com/book/10.1007/0-387-28390-0[Springer]

* Introduction to Probability with R, by Kenneth Baclawski (Chapman & Hall/CRC, 2008)

* Probability and Statistics with R, by María Dolores Ugarte, Ana F. Militino, and Alan T. Arnholt (Chapman & Hall/CRC, 2008)

* R in a Nutshell, 2nd Edition, by Joseph Adler (O'Reilly, 2012)

* Learning R, by Richard Cotton (O'Reilly, 2013)

* A Beginner's Guide to R, by Alain F. Zuur, Elena N. Ieno, and Erik Meesters (Springer, 2009)







* Introduction to Scientific Programming and Simulation Using R, by Owen Jones, Robert Maillardet, and Andrew Robinson (CRC Press, 2009)

* Probability with Applications and R, by Robert P. Dobrow (Wiley, 2014)

* Statistics and Data with R, by Yosef Cohen and Jeremiah Y. Cohen (Wiley, 2008)

* R Cookbook, 2nd Edition, by J.D. Long and Paul Teetor (O'Reilly, 2019)

* The R Software, by Pierre Lafaye de Micheaux, Rémy Drouilhet, and Benoit Liquet (Springer, 2013)

* Understanding Statistics Using R, by Randall Schumacker and Sara Tomek (Springer, 2013)

* R by Example, by Jim Albert and Maria Rizzo (Springer, 2012)

* The Art of R Programming, by Norman Matloff (No Starch Press, 2011)

* R in Action, 2nd Edition, by Robert I. Kabacoff (Manning, 2014)

* R: A language for data analysis and graphics</a> by Ross Ihaka and Robert Gentleman, Journal of Computational and Graphical Statistics, 5(3):299-314, 1996, available from http://www.jstor.org.ezproxy.lib.purdue.edu/stable/1390807[JSTOR]

* Lexical scope and statistical computing</a> by Robert Gentleman and Ross Ihaka, Journal of Computational and Graphical Statistics, 9(3):491-508, 2000, available from http://www.jstor.org.ezproxy.lib.purdue.edu/stable/1390942[JSTOR]

* Data Analysts Captivated by R's Power</a> by Ashlee Vance, New York Times, January 6, 2009, available from http://www.nytimes.com/2009/01/07/technology/business-computing/07program.html[New York Times]

* R You Ready for R?</a> by Ashlee Vance, New York Times, January 8, 2009, available from http://bits.blogs.nytimes.com/2009/01/08/r-you-ready-for-r/[New York Times]

* R for SAS and SPSS Users, by Robert A. Muenchen (Springer, 2008)

* Advanced R by Hadley Wickham (CRC Press, 2015)

* Linear Models with R, Second Edition, by Julian J. Faraway (CRC Press, 2014)

* R Graphics Cookbook, Second Edition, by Winston Chang (O'Reilly, 2019)

* Extending the Linear Model with R, Second Edition, by Julian J. Faraway (O'Reilly, 2016)

* Behavioral Data Analysis with R and Python by Florent Buisson (O'Reilly, 2021)

* The Book of R by Tilman M. Davies (No Starch Press, 2016)

* R for Data Science by Hadley Wickham and Garrett Grolemund (O'Reilly, 2017)

* Text Mining with R by Julia Silge and David Robinson (O'Reilly, 2017)

* R Markdown: The Definitive Guide by Yihui Xie, Garrett Grolemund, and J.J. Allaire (CRC Press, 2019)

* Analyzing Baseball Data with R by Max Marchi and Jim Albert (CRC Press, 2014)

* Modern Data Science with R by Benjamin S. Baumer, Daniel T. Kaplan, and Nicholas J. Horton (CRC Press, 2017)

* Graphics for Statistics and Data Analysis with R by Kevin J. Keen (CRC Press, 2018)

* Statistical Methods for Environmental Epidemiology with R by Roger D. Peng and Francesca Dominici (Springer, 2008)

* Deep Learning with R by Francois Chollet with J.J. Allaire (Manning, 2018)

* Data Mining with R by Luís Torgo (CRC Press, 2011)

* Displaying Time Series, Spatial, and Space-Time Data with R by Oscar Perpiñán Lamigueiro (CRC Press, 2014)

* Linear Mixed-Effects Models Using R by Andrzej Gałecki and Tomasz Burzykowski (Springer, 2013)

* Practical Data Science with R by Nina Zumel and John Mount (Manning, 2014)

* Mastering Spark with R by Javier Luraschi, Kevin Kuo, and Edgar Ruiz (O'Reilly, 2020)

* Hands-On Programming with R by Garrett Grolemund (O'Reilly, 2014)

* Lattice: Multivariate Data Visualization with R by Deepayan Sarkar (Springer, 2008)

* The R Primer by Claus Thorn Ekstrom (CRC Press, 2016)

* R Graphics by Paul Murrell (CRC Press, 2011)

* Time Series Analysis, 2nd Edition, by Jonathan D. Cryer and Kung-Sik Chan (Springer, 2008)

* An Introduction to Applied Multivariate Analysis with R by Brian Everitt and Torsten Hothorn (Springer, 2011)

* Machine Learning with R by Brett Lantz (Packt, 2013)

* R Packages by Hadley Wickham (O'Reilly, 2015)

* Interactive and Dynamic Graphics for Data Analysis by Dianne Cook and Deborah F. Swayne (Springer, 2007)

* Extending R by John M. Chambers (Springer, 2016)

* Graphing Data with R by John Jay Hilfiger (O'Reilly, 2016)

* Reproducible Research with R and RStudio, Second Edition, by Christopher Gandrud (CRC Press, 2015)

* Introduction to Stochastic Processes with R by Robert P. Dobrow (Wiley, 2016)

* Automated Data Collection with R by Simon Munzert, Christian Rubba, Peter Meißner, and Dominic Nyhuis (Wiley, 2015)

* The Essentials of Data Science by Graham J. Williams (CRC Press, 2017)

* Mastering Shiny by Hadley Wickham (O'Reilly, 2021)

* Introduction to Scientific Programming and Simulation Using R, Second Edition, by Owen Jones, Robert Maillardet, and Andrew Robinson (CRC Press, 2014)

* A Guide to QTL Mapping with R/qtl by Karl W. Broman and Saunak Sen (Springer, 2009)

* Dynamic Documents with R and knitr, Second Edition, by Yihui Xie (CRC Press, 2015)

* ggplot2: Elegant Graphics for Data Analysis, Second Edition, by Hadley Wickham (Springer, 2016)

* Learning Base R, Second Edition, by Lawrence M. Leemis (2022)

* Using R and RStudio for Data Management, Statistical Analysis, and Graphics, Second Edition, by Nicholas J. Horton and Ken Kleinman (CRC Press, 2015)

* Efficient R Programming by Colin Gillespie and Robin Lovelace (O'Reilly, 2017)

* Parallel R by Q. Ethan McCallum and Stephen Weston (O'Reilly, 2012)

* Getting Started with RStudio by John Verzani (O'Reilly, 2011)

* Data Mining with Rattle and R by Graham Williams (Springer, 2011)


