= `str_extract` & `str_extract_all`

== Basics

`str_extract` and `str_extract_all` are useful functions from the `stringr` package. You can install the package by running the following (although they should be loaded into your Data Mine environment already):

[source,r]
----
install.packages("stringr")
----

`str_extract` extracts the text which matches the provided regular expression or pattern. Note that this differs from grep in a major way. `grep` simply returns the index in which a pattern match was found. `str_extract` returns the actual matching text. Note that `grep` typically returns the entire line where a match was found. `str_extract` returns only the part of the line or text that matches the pattern. For example:

[source,r]
----
text <- c("cat", "mat", "spat", "spatula", "gnat")

# All 5 "lines" of text were a match.
grep(".*at", text)
----
----
 [1] 1 2 3 4 5
----

[source,r]
----
text <- c("cat", "mat", "spat", "spatula", "gnat")
stringr::str_extract(text, ".*at") 
----
----
 [1] "cat"  "mat"  "spat" "spat" "gnat"
----

As you can see, although all 5 words match our pattern and would be returned by `grep`, `str_extract` only returns the actual text that matches the pattern. In this case "spatula" is not a "full" match -- the pattern `.\*at` only captures the "spat" part of "spatula". In order to capture the rest of the word you would need to add another `.*` to the end of the pattern:

[source,r]
----
text <- c("cat", "mat", "spat", "spatula", "gnat")
stringr::str_extract(text, ".*at.*") 
----
----
 [1] "cat"     "mat"     "spat"    "spatula" "gnat"
----

{sp}+

=== Examples

==== How can I extract the text between parenthesis in a vector of texts?

.Click to see solution
[%collapsible]
====
[source,r]
----
text <- c("this is easy for (you)", "there (are) challenging ones", "text is (really awesome) (ok?)")

# Search for a literal "(", followed by any amount of any text other than more parenthesis ([^()]*), followed by a literal ")".
stringr::str_extract(text, "\\([^()]*\\)")
----
----
 [1] "(you)"            "(are)"            "(really awesome)"
----

To get all matches, not just the first match:

[source,r]
----
text <- c("this is easy for (you)", "there (are) challenging ones", "text is (really awesome) more text (ok?)")

# Search for a literal "(", followed by any amount of any text (.*), followed by a literal ")".
stringr::str_extract_all(text, "\\([^()]*\\)")
----
----
 [[1]]
 [1] "(you)"
 
 [[2]]
 [1] "(are)"
 
 [[3]]
 [1] "(really awesome)" "(ok?)"
----
====