= `case_when`

`case_when` is a function, used mostly as a parameter, that allows you to vectorize multiple `if_else` statements. For example, let's say we want to create a new column in our `iris` dataset called `size`, where the value is `Large` if `Sepal.Length` is greater than 5, and `Not Large` otherwise?

[source,r]
----
new_iris <- iris %>%
    mutate(size = case_when(
        Sepal.Length > 5 ~ "Large",
        Sepal.Length <= 5 ~ "Not Large"
    ))

head(new_iris)
----
----
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species      size
 1          5.1         3.5          1.4         0.2  setosa     Large
 2          4.9         3.0          1.4         0.2  setosa Not Large
 3          4.7         3.2          1.3         0.2  setosa Not Large
 4          4.6         3.1          1.5         0.2  setosa Not Large
 5          5.0         3.6          1.4         0.2  setosa Not Large
 6          5.4         3.9          1.7         0.4  setosa     Large
----

Here, `mutate` is responsible for creating a new column called `size`, and `case_when` assigns the value `Large` when `Sepal.Length` is greater than 5 and `Not Large` when `Sepal.Length` is less than or equal to `Not Large`. In this case we have exhaustively gone through all of the possible values of our new column, `size`, because for each and every possible value of `Sepal.Length` we have an associated value (`Large` and `Not Large`). In reality, this is not always possible. For example, let's remove the second case:

[source,r]
----
new_iris <- iris %>%
    mutate(size = case_when(
        Sepal.Length > 5 ~ "Large"
    ))

head(new_iris)
----
----
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species  size
 1          5.1         3.5          1.4         0.2  setosa Large
 2          4.9         3.0          1.4         0.2  setosa  <NA>
 3          4.7         3.2          1.3         0.2  setosa  <NA>
 4          4.6         3.1          1.5         0.2  setosa  <NA>
 5          5.0         3.6          1.4         0.2  setosa  <NA>
 6          5.4         3.9          1.7         0.4  setosa Large
----

As you can see, by default, if no cases match, `NA` is the resulting value. One common technique to handle "all other cases" is the following:

[source,r]
----
new_iris <- iris %>%
    mutate(size = case_when(
        Sepal.Length > 5 ~ "Large",
        TRUE ~ "Not Large"
    ))

head(new_iris)
----
----
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species      size
 1          5.1         3.5          1.4         0.2  setosa     Large
 2          4.9         3.0          1.4         0.2  setosa Not Large
 3          4.7         3.2          1.3         0.2  setosa Not Large
 4          4.6         3.1          1.5         0.2  setosa Not Large
 5          5.0         3.6          1.4         0.2  setosa Not Large
 6          5.4         3.9          1.7         0.4  setosa     Large
----

Here, each case is evaluated. If at the end, there was no match, `TRUE` is always a match, and therefore the result will be `Not Large`.