= `filter`

`filter` is a function that comes from the `dplyr` package of `tidyverse`, and serves as a subsetting function applied to your dataset. 

To start, you can either include your dataset as the first parameter in `filter` OR xref:tidy-piping[pipe] your dataset into the filter function.

[NOTE]
====
The example `diamonds` tibble is taken from `ggplot2`, included when `library(tidyverse)` is executed. You can find a list of example datasets (and from which package they originate) by running the `data()` command.
====

[source,R]
----
# both lines provide the same output, listed below

diamonds %>% filter(cut == 'Ideal')
filter(diamonds, cut == 'Ideal')
----
----
# A tibble: 21,551 x 10
   carat cut   color clarity depth table price     x     y     z
   <dbl> <ord> <ord> <ord>   <dbl> <dbl> <int> <dbl> <dbl> <dbl>
 1  0.23 Ideal E     SI2      61.5    55   326  3.95  3.98  2.43
 2  0.23 Ideal J     VS1      62.8    56   340  3.93  3.9   2.46
 3  0.31 Ideal J     SI2      62.2    54   344  4.35  4.37  2.71
 4  0.3  Ideal I     SI2      62      54   348  4.31  4.34  2.68
 5  0.33 Ideal I     SI2      61.8    55   403  4.49  4.51  2.78
 6  0.33 Ideal I     SI2      61.2    56   403  4.49  4.5   2.75
 7  0.33 Ideal J     SI1      61.1    56   403  4.49  4.55  2.76
 8  0.23 Ideal G     VS1      61.9    54   404  3.93  3.95  2.44
 9  0.32 Ideal I     SI1      60.9    55   404  4.45  4.48  2.72
10  0.3  Ideal I     SI2      61      59   405  4.3   4.33  2.63
# ... with 21,541 more rows
----

You can use whichever method you prefer, but we'll use piping with future examples to both enhance your understanding of it and exposure to it.

Much like the subsetting described in our xref:data-frames.adoc[page on `Data.frames`], selecting your data is done using logical statements. This allows you to condense several `filter` statements into one. Additionally, `filter` combines statements separated by commas into the logical AND (`&`), such that the following two lines of code result in the same output:

[source,R]
----
diamonds %>% filter(cut == 'Ideal', color=='D')
diamonds %>% filter(cut == 'Ideal' & color=='D')
----
----
# A tibble: 2,834 x 10
   carat cut   color clarity depth table price     x     y     z
   <dbl> <ord> <ord> <ord>   <dbl> <dbl> <int> <dbl> <dbl> <dbl>
 1  0.3  Ideal D     SI1      62.5    57   552  4.29  4.32  2.69
 2  0.3  Ideal D     SI1      62.1    56   552  4.3   4.33  2.68
 3  0.71 Ideal D     SI2      62.3    56  2762  5.73  5.69  3.56
 4  0.71 Ideal D     SI1      61.9    59  2764  5.69  5.72  3.53
 5  0.71 Ideal D     SI2      61.6    55  2767  5.74  5.76  3.54
 6  0.76 Ideal D     SI2      62.4    57  2770  5.78  5.83  3.62
 7  0.73 Ideal D     SI2      59.9    57  2770  5.92  5.89  3.54
 8  0.75 Ideal D     SI2      61.3    56  2773  5.85  5.89  3.6 
 9  0.72 Ideal D     SI1      60.8    57  2782  5.76  5.75  3.5 
10  0.64 Ideal D     VS1      61.5    56  2787  5.54  5.55  3.41
# ... with 2,824 more rows
----