= FAQs

When searching for help in The Examples Book, we encourage you to check through the sections listed below. We've included a few additional common questions on this page for your reference. 

* xref:crp:students:introduction.adoc[Corporate Partners Student Resources]
** Any questions about the course, registration, TA's, due-dates, or the course in general. 
* xref:starter-guides:data-science:intro-to-ds:intro-to-data-science.adoc[Data Science]
** Topics related to algorithms, exploratory data analysis, or working with data. 
* xref:starter-guides:data-engineering:intro-to-data-engineering:introduction-data-engineering.adoc[Data Engineering]
** Questions related to containers, research computing, or data pipelines. 
* xref:programming-languages:python:introduction.adoc[Programming Languages]
** Information about writing code in Python, R, and SQL. 

If you have questions outside of this list, please feel free to contact us at datamine@purdue.edu. 

== Technical Questions

[qanda]
How do I start a Juypter Lab session?::
Connect to `ondemand.anvil.rcac.purdue.edu`. Under `My Interactive Sessions` select `Jupyter Notebook` from the menu on the left. If you have any issues check out the `Data Engineering` section above.

Where is my data stored?::
The data will be stored in project specific locations on Anvil. If you aren't sure of your team's location, please check with the TA. If they aren't sure, you can contact xref:crp:students:ds_team_support.adoc[the data science team.]

I tried to install a package, but I'm still getting an error. What's up?::
By design The Data Mine doesn't allow for students to install their own packages. If you need a package installed for your project please contact xref:crp:students:ds_team_support.adoc[the data science team.]

My code is running slowly. What should I do?::
Troubleshooting tips:

* Check out the https://python-tutorial.dev/201/[Python 201] training from Research Computing. 
* Work with https://www.rcac.purdue.edu/knowledge/weber/run/slurm[SLURM] to schedule your code. 
* Contact xref:crp:students:ds_team_support.adoc[the data science team.]

I'm getting an error with my code. Who can help me troubleshoot?::
Check with your TA and team members for help first. If you're still having issues contact xref:crp:students:ds_team_support.adoc[the data science team.]

Can I just SSH from an IDE on my computer to the research cluster?::
Yes! As long as there is no company data on your local computer you are ok to work locally via SSH. Students have used SSH with https://code.visualstudio.com/docs/remote/ssh-tutorial[VS Code] on past projects. 

== Project Questions
[qanda]
What should I do if a team member is quarantined?::
If a team member is sick but feels good enough to attend the meeting The Data Mine will provide an OWL for the meeting. OWL's are webcams that allow the remote person to see the full room and hear each person as they are talking. If you need an OWL, please contact datamine@purdue.edu. 

Who can I talk to about visiting a company or attending an event?::
Often during a project, a company will meet with their team(s) or invite them to an event. If you'd like to attend and need transportation, please contact datamine@purdue.edu. The Data Mine team will work with the company and student team to ensure that we provide safe, university approved transport.