= Neural Networks & Deep Learning

Neural networks are a type of modeling technique that was inspired by neuronal transmission in animal brains. Neural networks are often deployed when the suspected solution is nonlinear; that is to say, a line probably won't represent the expected answer. Deep learning is neural networks with two or more layers.

== Common Applications

=== Industries
- Healthcare
- Tech 
- Retail
- Cybersecurity
- Any industry with lots of data

=== Problem Types
- Computer Vision
- Classification Problems
- Speech & Natural Language Processing
- High Dimensional Data

=== A Brief History

One of the original inspirations for neural networks was classifying images, something that is relatively easy for humans to do, but turned out to be pretty hard for us to figure out how computers can do. Research on neural networks began in the 1950's, in forms very different from what we work with today; the so called "AI winter" soon began after, and other tools saw large usage and arguably were more powerful (and far simpler) at the time. Approximately in the late 80's, neural networks started to see renewed interest; this catapulted in the early 00's with tech companies like Google and Facebook (with incredible amounts of data) and reignited research that overcame some of the early hurdles. 

== Code Project

=====Make an example project that anyone using Python can do using a Notebook======

xref:attachment$mnist.ipynb[MNIST Notebook (Beginner)]

Need help implementing this code? Feel free to reach out to mailto:datamine@purdue.edu[datamine@purdue.edu] and we can help!

== Resources

All of the content below is free for Purdue students; most of it should be free for National Data Mine students as well (check your school's digital library resources for the books). 

=== Videos

https://developers.google.com/machine-learning/crash-course/introduction-to-neural-networks/video-lecture[Google (~3 minutes)]

https://www.youtube.com/watch?v=aircAruvnKk[3 Blue, 1 Brown (~20 minutes)]

https://www.youtube.com/watch?v=jmmW0F0biz0[IBM (~5 minutes)]

=== Books

==== https://www.statlearning.com[Introduction to Statistical Learning (ISL)]

Also known as the "machine learning bible", this book is very well known and highly recommended and very clear, *and has numerous code projects attached with each chapter*. Chapter 10 is the deep learning chapter.

==== https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/kov9gv/alma99169839657501081[Introduction to Deep Learning and Neural Networks with Python]

This book is a gentle introduction to neural networks with plenty of examples, and also includes documentation on how to get your coding environment set up too.

==== https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/kov9gv/alma99169573376001081[Neural Networks and Statistical Learning]

This book is great for people who have experience with neural networks, but want to get a better feel for the math/theory background. A calculus and linear algebra background is necessary to make sense of this book.

==== https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/kov9gv/alma99169793279001081[Neural Networks]

Gentle introduction; good for visual learners.

=== Articles

https://developers.google.com/machine-learning/crash-course/introduction-to-neural-networks/anatomy[Brief Google guide on the motivation for neural networks, with great visual representation]

https://pages.cs.wisc.edu/~bolo/shipyard/neural/local.html[Brief introduction from UW-Madison]

https://www.mathworks.com/discovery/neural-network.html[Mathworks (MATLAB) introduction to neural networks]