= TDM 32100: Project ## - SQL Introduction 4

== Project Objectives

In this project, we will be copying the lahman database to your local storage in anvil so that you are able to modify it, and learn core SQL concepts that involve writing and updating database tables.

.Learning Objectives
****
- Copy a database to your local storage in anvil
- Create a new table in a database
- Insert data into a table
- Alter an existing table
- Delete data from a table
- Remove all data from a table
- Drop a table from a database
****

== Dataset
- '/anvil/projects/tdm/data/lahman/lahman.db'
- Alternative: '/anvil/projects/tdm/data/chinook/chinook.db' (Chinook Music Database)

[NOTE]
====
This project primarily uses the https://the-examples-book.com/projects/data-sets/Lahman[Lahman baseball database], but students may also practice with the Chinook music database for additional examples. The Chinook database contains information about music artists, albums, tracks, customers, and sales - providing a different domain to practice the same SQL concepts. There is a dedicated page for Chinook database in the example book: https://the-examples-book.com/projects/data-sets/chinook
====

== Questions

=== Question 1 (2 points)

The first thing we need to do is to copy the Lahman database and save it in your local folder in anvil. We can do this buy first loading the database from the path above like normal, and then using the python sqlite3 library to create a new database file in your local folder and copy the contents of the Lahman database into it.

[source,python]
----
import sqlite3

# Load the Lahman database
read_only_lahman = sqlite3.connect('/anvil/projects/tdm/data/lahman/lahman.db')
local_lahman = sqlite3.connect('./lahman.db')

read_only_lahman.backup(local_lahman) # Backup the database to your local file
read_only_lahman.close()
local_lahman.close()
----

Now, connect to your local copy of the Lahman database and write a query that returns the first 5 rows of the "Teams" table. You can connect to your local version by using this command:

[source,python]
----
%sql sqlite:///./lahman.db
----

[source,sql]
----
SELECT * FROM Teams LIMIT 5;
----

.Deliverables
====
1.1. Lahman database copied to your local folder in anvil
1.2. Query that returns the first 5 rows of the "Teams" table from Lahman database
====

=== Question 2 (2 points)

Now that we have a modifyable lahman database, let's talk about creating a new table. The `CREATE TABLE` command is used to create a new table in the database. For example, if you wanted to create a new table called "MyPlayers" with columns for "playerID", "name", and "teamID", you would use the following command:

[source,sql]
----
CREATE TABLE MyPlayers (
    playerID TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    teamID TEXT NOT NULL
);
----

This will create a new table called "MyPlayers" with the specified columns. You should also notice that each column has a data type specified, such as `TEXT` or `INTEGER`. This is important because it tells the database what kind of data will be stored in each column. Additionally, the `PRIMARY KEY` constraint is used to ensure that each row in the table has a unique identifier. Finally, the `NOT NULL` constraint is used to ensure that a column cannot have a NULL value. There are many other constraints that can be used, such as `UNIQUE`, `FOREIGN KEY`, and `CHECK`, but we will not cover those in this project.

[NOTE]
====
SQLite doesn't have very many data types. The most common ones are `TEXT`, `INTEGER`, `REAL`, `BLOB`, and `NULL`. You can read more about SQLite data types https://www.sqlite.org/datatype3.html[here].

However, more robust databases like PostgreSQL can have a wide rang of data types, including Arrays, JSON, UUIDs, etc. You can read more about PostgreSQL data types https://www.postgresql.org/docs/current/datatype.html[here].
====

Now that we have this table, how do we insert data into it? The `INSERT INTO` command is used to insert data into a table. For example, if you wanted to insert a new player into the "MyPlayers" table, you would use the following command:

[source,sql]
----
INSERT INTO MyPlayers (playerID, name, teamID)
VALUES ('player1', 'John Doe', 'team1');
----

Now, if you query the "MyPlayers" table, you should see the new player that you just inserted:
[source,sql]
----
SELECT * FROM MyPlayers;
----

This is cool, but impractical to add thousands of players one by one. Instead, we can use the `INSERT INTO` command to insert multiple rows at once. For example, if you wanted to insert multiple players into the "MyPlayers" table, you would use the following command:

[source,sql]
----
INSERT INTO MyPlayers (playerID, name, teamID)
VALUES
('player2', 'Jane Smith', 'team1'),
('player3', 'Bob Johnson', 'team2'),
('player4', 'Alice Brown', 'team2');
----

Additionally, we can use the `INSERT INTO` command to insert data from another table. For example, if you wanted to insert all players from the "People" table into the "MyPlayers" table, you would use the following command:

[source,sql]
----
INSERT INTO MyPlayers (playerID, name, teamID)
SELECT p.playerID, p.nameFirst || ' ' || p.nameLast AS name, MIN(s.teamID) as teamID
FROM People p
JOIN Salaries s on s.playerID = p.playerID 
WHERE s.yearID = ( SELECT MAX(yearID) FROM Salaries s2 WHERE s2.playerID = s.playerID )
GROUP BY p.playerID;
----

[NOTE]
====
The above sql query is quite complex. This is because the Salaries table does not require playerID to be unique, as a player could be on different teams or have a different salary in different years, or even get traded mid-season. Therefore, we need to aggregate both the teamID and the yearID to ensure that we are only getting one row per player. We do this by using the `MIN` function on the teamID and a subquery to get the maximum yearID for each player. This ensures that we are getting the teamID for the most recent year that the player played in.
====

Once you've inserted the data, query the first 5 rows of the "MyPlayers" table to see the data you just inserted.

.Deliverables
====
2.1. Create a new table called "MyPlayers"
2.2. Insert a single new player into the "MyPlayers" table using the `INSERT INTO` command
2.3. Insert multiple players into the "MyPlayers" table using the `INSERT INTO` command
2.4. Insert all players from the "Master" table into the "MyPlayers" table using the `INSERT INTO`` command
2.5. Query the first 5 rows of the "MyPlayers" table
====

=== Question 3 (2 points)

Now that you know how to create a new table and insert data into it, let's talk about altering an existing table. The `ALTER` command is used to modify an existing table in the database. For example, if you wanted to add a new column called "age" to the "MyPlayers" table, you would use the following command:

[source,sql]
----
ALTER TABLE MyPlayers
ADD COLUMN age INTEGER;
----

Or, if you wanted to remove a column called "teamID" from the "MyPlayers" table, you would use the following command:

[source,sql]
----
ALTER TABLE MyPlayers
DROP COLUMN teamID;
----


Another common thing that `ALTER` can be used for is altering the data type of a column. While this is not supported in sqlite3, it is supported in other databases including PostgreSQL. The syntax for this is as follows:

[source,sql]
----
ALTER TABLE MyPlayers
ALTER COLUMN age TYPE TEXT;
----


Now, if you query the "MyPlayers" table, you should see the changes that you just made:
[source,sql]
----
SELECT * FROM MyPlayers LIMIT 5;
----


Now that you know how to alter an existing table, please modify your "MyPlayers" table to add a new column called "height" of type `REAL` and a new column called "weight" of type `REAL`. You can do this by using the `ALTER TABLE` command as shown above. After you have added the new columns, insert 5 fake players into the "MyPlayers" table, giving them each a name, unique playerID, height, weight and age. Then, query the table to return the 5 tallest players in the "MyPlayers" table, ordered by height in descending order. 

.Deliverables
====
3.1. Alter the "MyPlayers" table to add a new column called "height" of type `REAL`
3.2. Alter the "MyPlayers" table to add a new column called "weight" of type `REAL`
3.3. Insert a new player into the "MyPlayers" table with the specified data
3.4. Query the "MyPlayers" table to return the 5 tallest players, ordered by height in descending order
====

=== Question 4 (2 points)

Now that you know how to alter an existing table and insert data into it, let's talk about deleting data from a table. The `DELETE` command is used to delete data from a table. For example, if you wanted to delete a player from the "MyPlayers" table, you would use the following command:

[source,sql]
----
DELETE FROM MyPlayers
WHERE playerID = 'player1';
----

This will delete the player with the specified playerID from the "MyPlayers" table. If you query the "MyPlayers" table after running this command, you should see that the player has been deleted:
[source,sql]
----
SELECT * FROM MyPlayers WHERE playerID = 'player1' LIMIT 5;
----

In a similar manner, we could delete all players from the "MyPlayers" table that have a height less than 6 feet. For example, if you wanted to delete all players with a height less than 6 feet, you would use the following command:
[source,sql]
----
DELETE FROM MyPlayers
WHERE height < 6.0;
----

This will delete all players from the "MyPlayers" table that have a height less than 6 feet. If you query the "MyPlayers" table after running this command, you should see that the players with a height less than 6 feet have been deleted:
[source,sql]
----
SELECT * FROM MyPlayers WHERE height < 6.0 LIMIT 5;
----

[NOTE]
====
In SQLite, the `DELETE` command is used to delete data from a table. However, in PostgreSQL, there is a `TRUNCATE` command that is used to remove all data from a table. 
====

.Deliverables
====
4.1. Delete a player from the "MyPlayers" table using the `DELETE` command
4.2. Delete all players from the "MyPlayers" table that have a height less than 6 feet using the `DELETE` command
4.3. Query the "MyPlayers" table to verify that the players have been deleted
====

=== Question 5 (2 points)

Finally, let's talk about greatly removing data from a table or the table as a whole. If you want to remove all data from a table but keep the structure, column names and types, etc., you can use the `DELETE` command instead without a `WHERE` clause. This will remove all data from the table but keep the table itself intact. For example, if you wanted to truncate the "MyPlayers" table, you would use the following command:
[source,sql]
----
DELETE FROM MyPlayers;
----

[NOTE]
====
In PostgreSQL, there is a `TRUNCATE` command that is used to remove all data from a table. However, sqlite3 does not support this command, so we use `DELETE FROM` without a `WHERE` clause to achieve the same effect.
====

The `DROP TABLE` command is used to delete an entire table from the database. For example, if you wanted to drop the "MyPlayers" table, you would use the following command:

[source,sql]
----
DROP TABLE MyPlayers;
----

This will delete the entire "MyPlayers" table from the database. If you query the "MyPlayers" table after running this command, you should see that the table no longer exists:

[source,sql]
----
SELECT * FROM MyPlayers LIMIT 5;
----

[NOTE]
====
Now, dropping a table is a very destructive operation, so be careful when using this command. You should only use it when you are sure that you no longer need the table and its data. 
====

.Deliverables
====
5.1. Remove all data from the "MyPlayers" table using the `TRUNCATE` command
5.2. Drop the "MyPlayers" table using the `DROP TABLE` command
5.3. Verify that the "MyPlayers" table has been dropped by attempting to query it
====

== Alternative Examples with Chinook Database

For students who want to practice the same concepts with a different dataset, here are equivalent examples using the Chinook music database:



=== Question 2 Alternative: CREATE TABLE and INSERT
[source,sql]
----
CREATE TABLE MyPlaylists (
    playlistID TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    created_date TEXT
);
----

[source,sql]
----
INSERT INTO MyPlaylists (playlistID, name, description, created_date)
VALUES ('playlist1', 'My Favorites', 'Songs I love the most', '2025-01-01');
----

[source,sql]
----
INSERT INTO MyPlaylists (playlistID, name, description, created_date)
VALUES
('playlist2', 'Workout Music', 'High energy songs for exercise', '2025-01-02'),
('playlist3', 'Study Music', 'Calm instrumental music', '2025-01-03'),
('playlist4', 'Road Trip', 'Great songs for long drives', '2025-01-04');
----

[source,sql]
----
INSERT INTO MyPlaylists (playlistID, name, description, created_date)
SELECT 'playlist_' || CAST(AlbumId AS TEXT), Title, 'Album playlist', '2025-01-01'
FROM Album 
WHERE AlbumId IN (1, 2, 3, 4, 5);
----

=== Question 3 Alternative: ALTER TABLE
[source,sql]
----
ALTER TABLE MyPlaylists
ADD COLUMN track_count INTEGER;
----

[source,sql]
----
ALTER TABLE MyPlaylists
ADD COLUMN is_public INTEGER DEFAULT 0;
----

[source,sql]
----
INSERT INTO MyPlaylists (playlistID, name, description, created_date, track_count, is_public)
VALUES
('playlist5', 'Public Favorites', 'My public playlist', '2025-01-05', 25, 1),
('playlist6', 'Private Collection', 'My private songs', '2025-01-06', 15, 0),
('playlist7', 'Party Mix', 'Great party songs', '2025-01-07', 30, 1),
('playlist8', 'Chill Vibes', 'Relaxing music', '2025-01-08', 20, 1),
('playlist9', 'Old Classics', 'Timeless favorites', '2025-01-09', 40, 0);
----

[source,sql]
----
SELECT * FROM MyPlaylists 
ORDER BY track_count DESC 
LIMIT 5;
----

=== Question 4 Alternative: DELETE
[source,sql]
----
DELETE FROM MyPlaylists
WHERE playlistID = 'playlist1';
----

[source,sql]
----
DELETE FROM MyPlaylists
WHERE is_public = 0;
----

=== Question 5 Alternative: TRUNCATE and DROP
[source,sql]
----
DELETE FROM MyPlaylists;
----

[source,sql]
----
DROP TABLE MyPlaylists;
----

== Submitting your Work

Once you have completed the questions, save your Jupyter notebook. You can then download the notebook and submit it to Gradescope.

.Items to submit
====
- firstname_lastname_project1.ipynb
====

[WARNING]
====
You _must_ double check your `.ipynb` after submitting it in gradescope. A _very_ common mistake is to assume that your `.ipynb` file has been rendered properly and contains your code, markdown, and code output even though it may not. **Please** take the time to double check your work. See https://the-examples-book.com/projects/submissions[here] for instructions on how to double check this.

You **will not** receive full credit if your `.ipynb` file does not contain all of the information you expect it to, or if it does not render properly in Gradescope. Please ask a TA if you need help with this.
====