= Expectations
For this summer starting on Thursday, June 1st, you're expected to: +

=== Submissions
* Submit your timesheet justification weekly due Sunday at 11:59 PM Eastern Time + 
* Submit a check-in report weekly due Friday at 11:59 PM Eastern Time +
* Complete pre/post survey from our assessor, Stephanie, https://www.youtube.com/watch?v=wol_unqeHfg[see her 1-min introduction video here]

=== Meetings
* Meet with your mentor on regular basis
* Create slides consisting of your work updates and present to your mentor weekly during your mentor meeting
* Regular team collaboration work (~15 hours a week)

=== Communication
You're expected to contantly check your Purdue email and Microsoft Teams. xref:purdue-account-usage.adoc[Please visit this page for all accounts you have under Purdue.]

Communication will help to drive your team and keep everyone connected. Creating connections is relevant to supporting your project.

==== Working with The Data Mine (TDM) Staff
* Ask for help when you do not understand. 
* Reach out for help early.
* Check in with staff and data scientists, they want to help you succeed.
* Poor planning does not constitute an emergency on TDM staff.
* Email The Data Mine shared email at datamine-help@purdue.edu.

==== Working with Your Mentor
* Be in constant contact.
* Be direct about what you need.
* Ask questions, especially if you do not understand something.
* Do not rely on your mentor to lead meetings. This is YOUR job.

==== Working with Your Teammates
* Communicate with your team about your share of the work.
* Don’t be afraid to ask questions. Some of the projects focus on complicated topics and the teams are learning together. There are no bad questions in this type of environment!
* Be willing to “speak up” if problems arise. Your Corporate Partner Peer Mentor and The Data Mine staff are here to support you, but you have to communicate with us when you need help. Please do not wait until the end of the semester to bring issues to our attention or say you don’t understand a concept. The earlier that you let us know, the easier we can help you.
* It is not ok to stop participating if the content gets difficult. Even if other students are more experienced, everyone should 1) make an effort to learn and get caught up and 2) find some way to contribute while trying to build up the necessary technical skills. Your Corporate Partner Mentor and TA can provide suggestions of other resources to help learn content. Again, you have to “speak up” when you need help!
* Deadlines are an unavoidable part of being a professional, and this program is no exception. Program requirements must be completed and submitted on or before the specified due date and delivery time deadline. Late work will not be accepted. Due dates and delivery time deadlines are defined as Eastern Time (as used in West Lafayette, Indiana).

=== Confidentiality of The Data Mine Corporate Partner Projects 
It is important to note that you are working on real-world problems that your Corporate Partner is trying to solve. You have the opportunity to make a real impact with your Corporate Partner. Past work from Data Mine students has been put into production code!

With that being said, *the work you do and the data you have access to must be kept fully confidential!* Nearly all Corporate Partner students will be required to sign an NDA and/or IP agreement with the company. Even if you do not have to sign an NDA for your project, please keep the project details private. While each NDA will have unique terms, some basics include:

*	Do not move or copy the data from the original storage. Never email data, text it to your teammates, copy it to MS Teams, or put it in Google drive (or any other cloud storage system). For example, if the data lives on Anvil, do not move it off Anvil and _do not move it to a different folder._ including your home directory. 
*	Do not share any screenshots of the data or any findings (graphs, pictures, etc.) from the project with those who are not on your team. 
*	You cannot share things you learn from the data with anyone who is not working on the project. This includes your roommate, your parents, and your best friend. 
*	Do not disclose project specifics to anyone, including:
**	In an interview for an internship or job
**	On your LinkedIn profile
**	Your family/friends/roommate/boyfriend/girlfriend/professor 
*	Do not discuss the details of projects when you are in a public space. You should find a private place to join the weekly online team meetings. Also, be careful working on the project in a public space when others could walk by and see your screen. 
*	If you ever have questions about what you *can* talk about, always ask your Corporate Partner Mentor first. 
If you’re ever in doubt about what to share it’s often best to not share initially and check with your corporate partner. They can help clarify any confusion.