= Student Expectations

Welcome to the student resource section for individuals who participate in the Summer '23 Cohort. + 

This is a "living" book that is continuously being updated. If you have any feedback, please write to datamine@purdue.edu

== Expectations
For this summer starting on Thursday, June 1st, you're expected to: +

=== Submissions
* submit your timesheet justification weekly. + 
* submit a check-in report bi-weekly due Wednesday at 11:59 PM Eastern Time on Gradescope. +
* complete pre/post survey from Stephanie

=== Meetings
* meet with your mentor on regular basis
* create slides consisting of your work updates and present weekly in your mentor meeting
* regular team collaboration (~15 hours a week)


== Questions? Need Help?
* Check The Examples Book for course schedule with due dates
* Ask The Data Mine Staff
** Naomi and Kali are your go-to resource for questions specific to DEAF PODS
** Send us an email at datamine-help@purdue.edu for questions related to grades and techincal help [https://the-examples-book.com/crp/students/ds_team_support[see this page on asking for techincal help]]