= More Data Science Books

Here is a list of even more useful data science books.


* Programming Collective Intelligence by Toby Segaran (O'Reilly, 2007)

* Stat Labs: Mathematical Statistics Through Applications by Deborah Nolan and Terry Speed (Springer, 2000)

* Subversion, a version control system (here is an official, free version of the manual)

* Introduction to Data Technologies by Paul Murrell (CRC Press, 2009)

* Practical Data Science with R by Nina Zumel and John Mount (Manning, 2014)

* Computational Statistics by James E. Gentle (Springer, 2009)

* Statistical Methods for Environmental Epidemiology with R by Roger D. Peng and Francesca Dominici (Springer, 2008)

* Data Mining with Rattle and R by Graham Williams (Springer, 2011)

* Machine Learning with R by Brett Lantz (Packt, 2013)

* Hadoop: The Definitive Guide, 3rd Edition by Tom White (O'Reilly, 2012)

* Thinking with Data by Max Shron (O'Reilly, 2014)

* Parallel R by Q. Ethan McCallum and Stephen Weston (O'Reilly, 2011)

* Machine Learning for Hackers by Drew Conway and John Myles White (O'Reilly, 2012)

* Getting Started with RStudio by John Verzani (O'Reilly, 2011)

* Bad Data Handbook by Q. Ethan McCallum (O'Reilly, 2012)

* Agile Data Science by Russell Jurney (O'Reilly, 2013)

* Doing Data Science by Cathy O'Neil and Rachel Schutt (O'Reilly, 2013)

* Analyzing Baseball Data with R by Max Marchi and Jim Albert (CRC Press, 2014)

* Dynamic Documents with R and knitr by Yihui Xie (CRC Press, 2014)

* Reproducible Research with R and RStudio by Christopher Gandrud (CRC Press, 2014)

* Statistical Methods in Bioinformatics: An Introduction, 2nd Edition by Warren J. Ewens and Gregory R. Grant (Springer, 2005)

* A Guide to QTL Mapping with R/qtl by Karl W. Broman and Saunak Sen (Springer, 2009)

* The Elements of Statistical Learning by Trevor Hastie, Robert Tibshirani, and Jerome Friedman (Springer, 2009)

* Introductory Time Series with R by Andrew V. Metcalfe and Paul S.P. Cowpertwait (Springer, 2009)

* An Introduction to Applied Multivariate Analysis with R by Brian Everitt and Torsten Hothorn (Springer, 2011)

* Forest Analytics with R by Andrew P. Robinson and Jeff D. Hamann (Springer, 2011)

* Applied Spatial Data Analysis with R by Roger S. Bivand, Edzer Pebesma, and Virgilio Gómez-Rubio (Springer, 2013)

* An Introduction to Statistical Learning by Gareth James, Daniela Witten, Trevor Hastie, and Robert Tibshirani (Springer, 2013)

* Time Series Analysis and Its Applications, 3rd Edition by Robert H. Shumway and David S. Stoffer (Springer, 2011)

* Linear Mixed-Effects Models Using R by Andrzej Gałecki and Tomasz Burzykowski (Springer, 2013)

* Displaying Time Series, Spatial, and Space-Time Data with R by Oscar Perpiñán Lamigueiro (CRC Press, 2014)

* Time Series Analysis, 2nd Edition by Jonathan D. Cryer and Kung-Sik Chan (Springer, 2008)

