= Fall 2022 Course Schedule

== Assignment Schedule

Each project will have a project charter with project-specific goals and dates, but here is the schedule for ALL Corporate Partner students for the general due dates of assignments to be submitted to The Data Mine staff. 

Assignment due dates are listed in *BOLD*. Other dates are important notes.

++++
<iframe width = "800" height = "400" title="Student Schedule" scrolling="yes"
src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQliS8phyQqsJ5tQHILphF14-K9l6-Mpolj5xTKyWG2GMzKGn9uJBA4SLdnSstnMXXin6Tuxhf5AB6W/pubhtml?widget=true&amp;headers=false" & wdDownloadButton="True"></iframe>
++++

You can link:https://docs.google.com/spreadsheets/d/15hojxBfuEYYcJJjGf2mBcuVXVh-dfedd6FNW8lDXpg0/edit?usp=sharing[view the schedule as a spreadsheet here]. You can also make your own copy, however, changes to the schedule will not be reflected in your copy so always check back here. 

== Sprint Schedule

All sprints will have the same due dates, but you will see below that the sprint start and end dates are slightly shifted depending on when a team has their lab (2 hours) and lecture (50 minutes). 

This is so that sprints always start with a lec and follow the format lec-lab-lec-lab.

A visual of this schedule is available in the xref:agile:ceremonies.adoc#sprint-schedule[Agile training section on ceremonies]. 


// ++++
// <iframe width = "800" height = "400" title="Sprint Schedule" scrolling="yes" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSbWtPtssvYq7m98SqQ2k5vP7p1RtACXtlWHyg0OgxVjOV_XrF6hwhqAMsgxw1Z1iSuT3ZVgA7U9buj/pubhtml?widget=true&amp;headers=false" & wdDownloadButton="True"></iframe>
// ++++

