= Sprint #7: November 14 - December 4, 2022

_Wednesday, 11/23 – Friday, 11/25: Thanksgiving break – No Classes_

== Sprint Dates
If you have your lab earlier in the week than your meeting, then you follow the "lab-meeting" sprint schedule (Wednesday Cycle).

* Monday lab and Friday meeting
* Tuesday lab and Thursday meeting

Sprint 7 Dates: November 16, 2022 - November 30, 2022
Final Presentation & Loose Ends: December 1, 2022 - December 9, 2022

If you have your meeting earlier in the week than your lab, then you follow the "meeting-lab" sprint schedule (Sunday Cycle).

* Monday meeting and Friday lab
* Tuesday meeting and Thursday lab

Sprint 7 Dates: November 13, 2022 - December 4, 2022
Final Presentation & Loose Ends: December 5, 2022 - December 9, 2022

Sprint Retro Reports and Documentation are due December 7, 2022 at 11:59 PM for both sprint schedules.


== Sprint #7 Retro Report 

*When:* Due Wednesday, December 7 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in Sprint #7 Retro Report. 

*Where:* link:https://www.gradescope.com/[Gradescope] 