= Sprint #4: Due October 19, 2022

_Monday, 10/10 and Tuesday, 10/11: Fall Break – No Classes_

_Wednesday, 10/12 and Friday 10/14: All labs and meetings as usual. No changes on Wednesday, Thursday and Friday._

== Sprint Dates
If you have your lab earlier in the week than your meeting, then you follow the "lab-meeting" sprint schedule (Wednesday Cycle).

* Monday lab and Friday meeting
* Tuesday lab and Thursday meeting

Sprint 4 Dates: October 5, 2022 - October 19, 2022

If you have your meeting earlier in the week than your lab, then you follow the "meeting-lab" sprint schedule (Sunday Cycle).

* Monday meeting and Friday lab
* Tuesday meeting and Thursday lab

Sprint 4 Dates: October 2, 2022 - October 16, 2022

Sprint Retro Reports and Documentation are due October 19, 2022 at 11:59 PM for *both* sprint schedules.


== Sprint #4 Retro Report 

*When:* Due Wednesday, October 19, 2022 at 11:59 PM ET. Late work will not be accepted. 

*What:* Answer the questions in Sprint #4 Retro Report. 

*Where:* link:https://www.gradescope.com/[Gradescope] 