= Training Your Model
:page-mathjax: true

== Introduction

Training (sometimes called fitting) your model is when you build out the implementation of your modeling technique, connect data to it, and press start. Here we explore roughly what this process entails.

== Planning the Architecture

Here we plan the structure of our model. Often, this is where we determine the approximate shapes that $\hat{f}$ is likely to take on and plan our architecture in accordance- you will recall that shaping is heavily influenced by xref:data-modeling/choosing-model/parameterization.adoc[how we parameterize], if we choose to do so. For instance, in a regression model, this often takes the form of determining if a simple or curvilinear line is needed, detecting possible interaction effects, etc. 

If you have hyperparameters (also called tuning parameters), this is the place to list them out and consider possible ranges for them. Neural networks are a great example here because they often have so many hyperparameters, including the number of hidden layers, number of neurons in each layer, the activation functions used, what type of gradient descent algorithm and its associated optimization, and much more. We need to come up with a way to decide on how to the different tuning paramaters; sometimes this can amount to testing out numerous different models and seeing what works.

This step is where the planning in xref:data-modeling/process/think-output.adoc[thinking about the output] comes into play. If we are trying to imagine what the approximate structure for our model should be, how can we do that if we don't know what we want to see as output?

With relatively simple models, maybe going right ahead to code and see what works is a great idea. Other times, with more complex models and lots of data, writing out our model architecture is not a bad idea. Here's a rough template to give you an idea:

- What Do We Want To See As Output:
- Model(s) To Build:
- Parameters in the model(s):
- Hyperparameters (and optimization of those hyperparameters, if applicable):

== Code Implementation

== Training/Fitting

== Testing

