= TA Training Module 0: Introduction

TAs hold a large part in the success of a corporate partner team and in a student’s experience within The Data Mine. The TAs primary responsibilities include engaging with students and CRP mentors, leading projects, and being a resource for their team. 

The training modules are designed to help prepare you for your time as a TA. 

== Trainings

&#10003; Complete Training Modules 0-7 found under xref:trainingModules/introduction_trainings.adoc[TA Training].

&#10003; Navigate to link:https://www.gradescope.com/[Gradescope] to complete assessments and submit the following.

* Module 1 Quiz
* Module 2 Quiz
* Module 3 Quiz
* Module 4 Quiz
* Module 5 Quiz
* Salesforce Training: Atlassian Agile Basics
* Project Management Quiz
* Syllabus Quiz
* *FERPA Certification*

== Fall Preparation
These are steps you should take as a TA to prepare for the Fall semester in addtion to the required trainings.

&#10003; Set up an link:https://the-examples-book.com/starter-guides/anvil/access-setup[ACCESS account]

&#10003; Meet with my Corporate Mentor to discuss project expectations and communication methods. 

&#10003; Double checked I have access to my MS Teams Group. Reviewed xref:students:fall2025/MS_Teams.adoc[Microsoft Teams Email Groups]

&#10003; Send out a welcome chat in your Microsoft Teams channel to the team including the following:

    * Introducing yourself
        ** Your Year and Major
        ** Why are you excited to work on this project?
    * Welcoming the team to the project
    * Reminding the team about project meeting times
    * Reminding the team about link:https://the-examples-book.com/book/[The Examples Book]
    * Providing the team with the best way to reach you for the semester

&#10003; Check the xref:fall2025/schedule.adoc[TA schedule] to identify due dates for the semester and required TA meetings.

&#10003; Prepare an icebreaker for the first lab. Navigate to xref:trainingModules/ta_training_module4_3_warmups.adoc[TA Created Warm-Ups] to choose icebreakers, create, or find more. Most of your first lab will be completing the xref:projectmanagement:/agile-lego-activity.adoc[Lego Agile Activity].

&#10003; Plan your second lab! Remember to include an introduction, agile explanation, and reminders about the syllabus/quizzes and NDAs (if your company has provided them already). Navigate to the xref:trainingModules/ta_training_module5_8_labs.adoc[Lab Planning Guide] for an outline of how to create a lab.  

&#10003; (Optional, but highly recommended) Meet with my Mentor for more planning and/or reviewing information.

&#10003; (Optional) Meet with Data Mine Staff to discuss any concerns or get my questions answered.

== Useful Links
* link:https://datamine.purdue.edu[The Data Mine Website]

* link:https://the-examples-book.com/book/[The Examples Book Home Page]