= Documentation

Documentation is super important across a variety of industries. For Fall 2022, The Data Mine has decided to provide a documentation guide for teams to follow. It is strongly encouraged your team uses this guide if your mentor does not provide a preferred documentation guide for you. 

[NOTE]
====
Completion of documentation will play a role in student's retrospective sprint reports.
====

== Why is documentation so important?
Documentation provides a record of what has been completed in a project. It is extremely useful if you need to revisit a task you completed in the past. Documentation can also be passed to the next team for continuing projects. It helps to know what has already completed, how, and where to find it. 

Documentation can also help your team prepare for presentations, demonstrations, meetings, and more. 

== Who completes the documentation?
Corporate Partner Team Documentation is a team effort. 

Anyone who works on the project! Each time students or TAs work on the project they should be adding to the guide. It is much easier to add documentation as you go than to try and remember what happened in August when preparing for the May Symposium.

Because you are working as a team, make sure everyone has access to add to the Documentation Guide!

[IMPORTANT]
====
Documentation Guide will be added here for team download.
====

== What should be included in documentation?
In the documentation guide provided, you will complete sections including:

* Project Scope
* Process
** Overview
** ReadMe
* Background Information (Research)
* Tooling
* Who is involved?
** Contributors
* Exceptions to the Normal Process
* Risks
* Assumptions
* Review
* Testing
* Sources
