= TA Training Module 3: Classroom Policies

In this section we will review the TA policies to follow while acting as a TA and working under The Data Mine model. These tasks will repeat weekly throughout the semester. Please use this page as a checklist to ensure you have followed all TA responsibilities on any given week. 

== Weekly Team Reports
Please refer to xref:resources/team_report.adoc[Team Reports] for more information on TA expectations for team reports.

== How To Grade Biweekly Progress Reports
Please refer to xref:expectations/grading.adoc[Grading] for more information on TA expectations for grading.

== Time Sheets
Please refer to xref:resources/timesheet.adoc[Time Sheets] for more information on TA expectations for time sheets.

== Attendance and Participation Spreadsheets
Please refer to xref:expectations/attendance.adoc[Attendance] for more information on TA expectations for attendance and participation spreadsheets.

== Meeting Minutes
Please refer to xref:expectations/meeting_notes.adoc[Meeting Minutes] for more information on TA expectations for meeting minutes.

== Labs and Meetings
Please refer to xref:expectations/team_meetings.adoc[Team Meetings] and xref:expectations/team_labs.adoc[Labs] for more information on TA expectations for team meetings and labs