= TA Training Module 2: University Policies

== Policy You Need to Know
- FERPA
- Purdue amorous relationships and nepotism policy 
- Purdue statement of integrity and code of conduct 
- Purdue Nondiscrimination Policy
- Purdue Honor Pledge

== FERPA
• Family Education Rights and Privacy Act
• This is a federal law that protects student records.
• It is extremely important that you understand and obey this law.
• You must maintain confidentiality about student performance, grades, disability concerns, and personal issues.
• https://www.purdue.edu/registrar/FERPA/
• TODAY: Complete your FERPA certification and upload the proof to the designated spot in the TA training Blackboard site. This certification has to be renewed every year.
https://www.purdue.edu/registrar/FERPA/certification.html

== Amorous relationships and nepotism
• It is likely that you will have friends or relatives or romantic interests who are students in The Data Mine.
• Understanding what is and is not ok when combining your job with your personal life is important.
• Your supervisors need to know these situations immediately because we have to file action plans with the Office of the Provost to explain how we are avoiding conflicts of interest.
• Purdue amorous relationships and nepotism policy: https://www.purdue.edu/ethics/resources/faqs/amorous-nepotism-faqs.php

== Purdue statement of integrity and code of conduct
• https://www.purdue.edu/purdue/about/integrity_statement.php 
• Act with honesty, adhere to highest standards of public trust
• Words should be consistent with our actions and vice versa
• Champion freedom of expression, open inquiry, debate
• Embrace human and intellectual diversity and inclusiveness
• Treat all individuals with dignity
• Strong work ethic
• Treat all students equitably and impartially based on performance • Make wise use of resources

== Purdue Nondiscrimination Policy Statement
Purdue University is committed to maintaining a community which recognizes and values the inherent worth and dignity of every person; fosters tolerance, sensitivity, understanding, and mutual respect among its members; and encourages each individual to strive to reach his or her own potential. In pursuit of its goal of academic excellence, the University seeks to develop and nurture diversity. The University believes that diversity among its many members strengthens the institution, stimulates creativity, promotes the exchange of ideas, and enriches campus life. 

Purdue University views, evaluates, and treats all persons in any University related activity or circumstance in which they may be involved, solely as individuals on the basis of their own personal abilities, qualifications, and other relevant characteristics.


Purdue University prohibits discrimination against any member of the University community on the basis of race, religion, color, sex, age, national origin or ancestry, genetic information, marital status, parental status, sexual orientation, gender identity and expression, disability, or status as a veteran. The University will conduct its programs, services and activities consistent with applicable federal, state and local laws, regulations and orders and in conformance with the procedures and limitations as set forth in Purdue’s Equal Opportunity, Equal Access and Affirmative Action policy which provides specific and contractual rights and remedies. Additionally, the University promotes the full realization of equal employment opportunity for women, minorities, persons with disabilities and veterans through its affirmative action program.

== Purdue Nondiscrimination Policy in The Data Mine
• Although cultures may vary, T.A.s are expected to conform in this respect to U.S. standards.
• If you have any doubts about what behavior is considered appropriate, consult Data Mine staff.
• Whatever the interaction context is, always be polite and treat ALL students with equal respect. Sarcasm is generally not appreciated by students when they need help. Show respect always.
• No discrimination, jokes or disparaging remarks about individuals based on their sex, race, ethnicity, age, disability status, religion, sexual orientation, or national origin in the classroom or outside of it.


== Purdue Honor Pledge
“As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together—we are Purdue.”

++++
<iframe class="video" width="560" height="315" src="https://www.youtube.com/embed/Zq5CVTj7NTg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

== Purdue Universities Guide for Academic Integrity
https://www.purdue.edu/odos/osrr/academic-integrity/index.html 

== FERPA Training
Directions:

1. Click the Certification Link: https://www.purdue.edu/registrar/FERPA/certification.html

2. Click the FERPA certification training materials link and look over the PDF.

3. When you've completed reading the PDF, click the link under the certification heading.

4. Click the "Enterprise Certifications" heading.

5. Click "Family Educational Rights and Privacy Act / FERPA 2020" link.

Follow the instructions on the site.  You'll be able to read training material and take a quiz.  When you successfully pass the certification, you will get an email that shows you are certified for a year.  Paste the text of this email into the Brightspace assignment. 

