= Diversity, Equity, Inclusion, and Accessibility In Data Science

== Why Is It So Important to Increase Diversity and Inclusion in Data Science?

=== How Diversity Makes Us Smarter

- Decades of research by organizational scientists, psychologists, sociologists, economists and demographers show that socially diverse groups (that is, those with a diversity of race, ethnicity, gender and sexual orientation) are more innovative than homogeneous groups.
- It seems obvious that a group of people with diverse individual expertise would be better than a homogeneous group at solving complex, non-routine problems. It is less obvious that social diversity should work in the same way—yet the science shows that it does.
- This is not only because people with diverse backgrounds bring new information. Simply interacting with individuals who are different forces group members to prepare better, to anticipate alternative viewpoints and to expect that reaching consensus will take effort.
- Phillips, K.W. (2014, October 1). How Diversity Makes Us Smarter: Being around people who are different from us makes us more creative, more diligent and harder working. https://www.scientificamerican.com/article/how-diversity-makes-us-smarter/ 

{sp}+

=== Why Does Data Science Need Diversity?

- Diversity enables better representation of the broader population.

- Diversity improves the products and services we create.

- Diversity helps counteract algorithmic violence (the ways that algorithms or automated decision-making systems inflict harm by preventing people from meeting their needs).

- https://www.informationweek.com/big-data/big-data-analytics/why-data-scientists-should-make-a-commitment-to-diversity/a/d-id/1333403

{sp}+

=== Data Science Needs Different Perspectives

- “We like to have this idea that the data is the ultimate truth, but it really comes down to how you ask questions and the evidence you are looking for to support the question you have or to deny it.  

- “Remember that data is just a representation of something that happened. A lot of times it tells a portion of the story but not the full story…Any time you bring in someone who brings a different perspective and different experience, you will only add to being able to solve problems…

- “There should be a conscious awareness to make sure you go after building a diverse team…It's so easy to hire people in our own circle, and those people usually are most like us. That's where awareness needs to be.” - Sadie St. Lawrence, Founder and Executive Director of the non-profit Women in Data

- https://www.dataversity.net/building-future-women-data/

{sp}+

== First Impressions video
++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/9rdHHkUomzw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++