= Project Mapping Guide

Below you will find a guide to help you plan your project. The guide includes reflective questions as well as an area to breakdown major goals and sub-goals. Once you identify major steps and sub-steps you can also add assignees, due dates, and notes. 

In addition adding answers to this guide, you are also encouraged to use link:https://linear.app[Linear], a free tool used to streamline sprints and tasks, with your team. 

== Reflective Questions

These questions are to help you gain a deeper understanding of your project.

1. How would you describe your project? How would you summarize your project in two sentences?
2. How does this project contribute to the bigger picture of the company? 
3. Who will benefit from your project?
4. What is the difficulty of the task(s)?
5. Will you need special systems or equipment?
6. What risks should you plan to manage?
7. How can the project be broken down into stages? Goals and Objectives?
8. What is your strategy to get each stage complete? Deadlines?
9. How can students contribute to each stage?
10. Will you need to break into sub-teams? What does this look like for your project?



== Mapping Guide
++++
<iframe width="800" height="500" scrolling="yes" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQbpPGf9n-YVOUvuiORTlv6LfRVVcdrgJpOP8pYYwQRRUgdLQsHi9rMmnBbddQkWsfTJDYpR5uvkifz/pubhtml?widget=true&amp;headers=false"></iframe>
++++

Make a copy of the guide to edit by navigating to the link:https://docs.google.com/spreadsheets/d/1dnvVrPnDFQPrSoaf5x1FLzE8CA3iJgL1TQINn7NOFgY/edit?usp=sharing[project mapping guide].