= TA Training Module 2: University Policies

== Policy You Need to Know
•	FERPA
•	Purdue amorous relationships and nepotism policy
•	Purdue statement of integrity and code of conduct
•	Purdue Nondiscrimination Policy
•	Purdue Honor Pledge

== FERPA
•	Family Education Rights and Privacy Act
•	This is a federal law that protects student records.
•	It is extremely important that you understand and obey this law.
•	You must maintain confidentiality about student performance, grades, disability concerns, and personal issues.
• https://www.purdue.edu/registrar/FERPA/

[IMPORTANT]
====
TODAY: Complete your FERPA certification and upload the proof to the designated spot in the TA Gradescope site. This certification has to be renewed every year.
====

=== FERPA Training
Directions:

1. Click the Certification Link: https://www.purdue.edu/registrar/FERPA/certification.html

2. Review the FERPA certification training materials PDF

3. Review the FERPA certification training materials PDF.

4. Register for the certificate: www.eventreg.purdue.edu/webcert

5. Select "Family Educational Rights and Privacy Act / FERPA Annual Certification".

Follow the instructions on the site.  You'll be able to read training material and take a quiz.  When you successfully pass the certification, you will get an email that shows you are certified for a year.  Export the email as a PDF and upload it to the Gradescope assignment. 

This certification has to be renewed every year. 

== Amorous relationships and nepotism
•	It is likely that you will have friends or relatives or romantic interests who are students in The Data Mine.
•	Understanding what is and is not ok when combining your job with your personal life is important.
•	Your supervisors need to know these situations immediately because we have to file action plans with the Office of the Provost to explain how we are avoiding conflicts of interest.
•	Purdue amorous relationships and nepotism policy: www.purdue.edu/ethics/resources/faqs/amorous-nepotism-faqs.php

== Purdue statement of integrity and code of conduct
•	www.purdue.edu/purdue/about/integrity_statement.php
•	Act with honesty, adhere to highest standards of public trust
•	Words should be consistent with our actions and vice versa
•	Champion freedom of expression, open inquiry, debate
•	Treat all individuals with dignity
•	Strong work ethic
•	Treat all students impartially based on performance 
•	Make wise use of resources

== Purdue Nondiscrimination Policy Statement

Review link:https://www.purdue.edu/home/ea_eou_statement/[Purdue's Nondiscrimination Policy Statement]


== Purdue Nondiscrimination Policy in The Data Mine
•	Although cultures may vary, T.A.s are expected to conform in this respect to U.S. standards.
•	If you have any doubts about what behavior is considered appropriate, consult Data Mine staff.
•	Whatever the interaction context is, always be polite and treat ALL students with equal respect. Sarcasm is generally not appreciated by students when they need help. Show respect always.
•	No discrimination, jokes or disparaging remarks about individuals based on their sex, race, ethnicity, age, disability status, religion, sexual orientation, or national origin in the classroom or outside of it.

== Purdue Honor Pledge
https://www.purdue.edu/odos/osrr/honor-pledge/index.php 

“As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together—we are Purdue.”

== Purdue Universities Guide for Academic Integrity
www.purdue.edu/odos/osrr/academic-integrity/index.html

