= Communication

Communication will help to drive your team and keep everyone connected. Creating connections is relevant to supporting your project. Below is general expectations and advice from previous TAs on how to best communicate with the team.

Reminder: You are the captain of your ship. You are the leader in labs, meetings, office hours, and other discussions.

== Working with Staff
* Ask for help when you do not understand. 
* Reach out for help early.
* Check in with staff and data scientists, they want to help you succeed.
* Poor planning does not constitute an emergency on Data Mine staff.

== Working with Other TAs
* Meet other TAs. They want to meet you.
* Talk to the previous TA of the project.
* Work together to overcome challenges. Other TAs may be facing similar challenges or have valuable experiences or opinions on the topic.
* You can share resources and tips.

== Working with Your Mentor
* Establish a private meeting schedule and communication that works for the mentor and yourself to discuss any details or planning.
* Be in constant contact, you should be the main point of contact.
* Be direct about what you need.
* Ask questions, especially if you do not understand something.
* Yes! Set-up extra meetings if you would like to (check the time-zone).
* Do not rely on your mentor to lead meetings. This is the TAs job. 
* Plan meetings early to work on mid-semester and final feedback together.

== Working with Students
* Constant communication will help keep your students engaged.
* If a student misses 2 meetings or labs in a row follow-up with them until you get a response. Do not leave any students behind. 
* Trust your judgement, it is ok to say no. Give the students a reason, if applicable.
* Get to know your students professionally. This will reduce frustration and help the team run more smooth. You can do this through icebreakers, check-ins, or just asking.
    ** Understand their strengths and weaknesses. 
    ** Understand their personalities and what drives their work ethic. 
    ** Learn what their goals are for their project contributions.
* Check on your students regularly, especially around mid-term season. Balance out their work load.
* Be patient as students problem solve.
* Make students comfortable and feel like they can ask questions. 