= Valuing Student Perspectives and Experiences in Data Science Part Two

== Why Is It So Important to value every student’s perspective and experiences in Data Science?

=== How this Makes Us Smarter
•	Decades of research by organizational scientists, psychologists, sociologists, economists and demographers show that groups with varied perspective and experiences are more innovative than homogeneous groups.
•	It seems obvious that a group of people with different individual expertise would be better than a homogeneous group at solving complex, non-routine problems. It is less obvious that social variety should work in the same way—yet the science shows that it does.
•	This is not only because people with varied backgrounds bring new information. Simply interacting with individuals who are different forces group members to prepare better, to anticipate alternative viewpoints and to expect that reaching consensus will take effort.

{sp}+

=== Data Science Needs Different Perspectives
"We like to have this idea that the data is the ultimate truth, but it really comes down to how you ask questions and the evidence you are looking for to support the question you have or to deny it.

Remember that data is just a representation of something that happened. A lot of times it tells a portion of the story but not the full story. Any time you bring in someone who brings a different perspective and different experience, you will only add to being able to solve problem.

by Sadie St. Lawrence, Founder and Executive Director of the non-profit Women in Data

{sp}+
