= Diversity in The Data Mine

== What is the current status of diversity in data science?

*Purdue Undergraduate Demographics (Fall 2021)*

- *Gender*:  Male 58%, Female 42%

- *Residency*:  Indiana resident 45%, Out-of-state US resident 47%, International 8%

*The Data Mine Demographics (FALL 2022)*

These statistics are from August 2022. They do not include students from The National Data Mine Network, Indiana Data Mine, and Purdue West Lafayette Data Mine TAs. Percentages may not total 100% due to rounding.

- *Gender*:  Male 69%, Female 31%

- *Race/ethnicity*:  Asian 32%, International (other) 30%, White 27%, Hispanic/Latino(a) 4%, 2 or more races 3%, Unknown 2%, Black or African American <1%, 

- *Residency*: Out-of-state US resident 50%, International 30%, Indiana resident 20%

{sp}+

=== Data Mine Students -- College of Major (Fall 2022)

[cols="1,1,1"]
|===
|College | # | % of Total

|Science
|615
|55.01%

|Engineering
|191
|17.08%

|Polytechnic
|85
|7.60%

|Management
|80
|7.15%

|Health and Human Sciences
|56
|5.01%

|Liberal Arts
|40
|3.58%

|Agriculture
|16
|1.43%

|Exploratory Studies
|15
|1.34%

|Pharmacy
|13
|1.16%

|Interdisciplinary and Special Programs
|3
|0.27%

|College of Education
|3
|0.27%

|College of Veterinary Medicine
|1
|.09%

|*Total*
|*1118*
|*100%*
|===

{sp}+

=== National Data Mine Network Demographics (Fall 2022)

- *Gender*: Male: 52%, Female 43%, Non-Binary 2%, Genderfluid 1%

- *Race*: Hispanic/Latino(a): 52%, Black or African American: 42%, American Indian or Alaska Native: 3%, Asian 2% 

{sp}+

=== Data Science Professional Demographics

- Google's workforce, according to its own internal audit, is 70% male, 61% white. Facebook isn't much different. 

- 18% of computer science degrees go to women. 

- Women make up 11% of math faculty. 

- Nearly half of women who graduate with engineering degrees never enter the profession or leave soon after. 

- https://www.washingtonpost.com/local/women-flocking-to-statistics-the-new-hot-high-tech-field-of-data-science/2014/12/19/f3e2e486-62ed-11e4-9fdc-d43b053ecb4d_story.html?noredirect=on&utm_term=.695b6e0f193b

{sp}+