= Additional Tools

== Repository Set Up
If your team is interested in using a repository, please send a ticket to datamine-help@purdue.edu and Data Mine staff will set up a repository for you. Data Mine staff will set up the repository for you team and will provide your team access. 

It is also fine for your company to set up their own repository.

Why?

* This makes it easier to transition on-going projects between years. 
* Data Mine hosting will ensure confidentiality is protected. If students host their own repositories, this can cause issues. 

If you have more questions about setting up a repository, please let Data Mine Staff know. 

== Additional Resources

In addition to the resources in this section, there are many other resources located in The Examples Book. Below are some of the sections you could find useful on your project.

Navigate to: link:https://the-examples-book.com/starter-guides/data-science/intro-to-ds/intro-to-data-science[Introduction to Data Science]

// Navigate to: link:https://the-examples-book.com/starter-guides/ds-resources/[Supplementary Data Science Reading List]

 Navigate to: https://the-examples-book.com/starter-guides/data-science/data-analysis/nlp/prodigy[Prodigy Annotation]

 Navigate to: https://the-examples-book.com/starter-guides/data-science/data-analysis/gis/introduction-gis[Geospatial Analytics]

Navigate to: link:https://the-examples-book.com/starter-guides/data-science/data-visualization/introduction-data-visualization[Data Visualization]

Navigate to: link:https://the-examples-book.com/starter-guides/tools-and-standards/matlab/introduction-matlab[MATLAB]

Navigate to: link:https://the-examples-book.com/starter-guides/data-science/data-analysis/optimization.adoc[Optimization]

Navigate to: link:https://the-examples-book.com/starter-guides/data-science/data-analysis/nlp/introduction-nlp[Natural Language Processing]

**More specific resources(Git, CloudVM, ANVIL, Python Lib, SQL) will be added soon**

To find more resources in the appendices and resources on Data Types, UNIX, SQL, R, Python, Git, and past project please navigate to the home page of link:https://the-examples-book.com/[The Examples Book] and search through the appendices and left hand search bar. 

These resources can also be useful to refer students to throughout the semester.
