= TA Training Module 5: Weekly Rhythms 

In this section we will review the TA policies to follow while acting as a TA and working under The Data Mine model. These tasks will repeat throughout the semester and by following a steady sprint schedule, your team will find a consistent and continuous approach to the project.

Please work through the sub modules under this module.

== Sprint Tasks

*Each sprint, there will be tasks that both TAs and students have to complete.* To see the tasks that TAs have to complete for each sprint, navigate to the respective sprint page. For example, to see the tasks for Sprint 1, navigate to xref:fall2025/sprint1.adoc[Fall 2025 Sprint 1]. 

== Lab Location

To review where your lab will be meeting on campus, navigate to xref:students:fall2025/locations.adoc[Class Times & Locations]. 

== Your Data Mine Contact

Each project will have a Data Mine staff member as a liaison to the project. This staff member has worked with your corporate partner to define the project and will be available to answer questions and provide guidance throughout the semester. Please review the following table to see who your contact is:
**TO BE UPDATED**


[IMPORTANT]
====
If any changes are made, they will appear here. They will not appear in copies.
====

//++++
//<iframe width = "800" height = "400" title="CRP Liaison" scrolling="yes"
//src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSPPpx8rAZZZ_RaaOTdiLHGEVcTxKw5EVVse1Kpeq_GjigDSdg5yWpZYSdF5K3nQa288n3XZaCEhYuA/pubhtml?gid=0&amp;single=true&amp;widget=true&amp;headers=false"></iframe>
//++++
