= Peer Mentor Groups

== Overview

All TAs will be placed in peer mentor groups for the academic year. These groups are meant as a support system for new and continuing TDM TAs. 

Each group will have at least one experienced TA that will be well suited to answer any questions on the TA experience including best practices, weekly rhythms, and more. 

For more support, TAs can email the datamine-help@purdue.edu or stop by a team member's office in Convergence. 

== Requirements

- Teams are required to meet (in person or virtually) once every sprint to connect and engage with their peer group
- Each Team Report that TAs submit will have a question asking about their interactions with their peer groups

== Best Practices

- Grade sprint reports as a peer group (make sure not to violate any NDAs)
- Grab a meal as a group
- Stop by Convergence and meet with a TDM staff member
- Talk about common challenges you are facing
- Share your best practices for team engagement and bonding 
- Developing lab or meeting content (if applicable)
- Study sessions 
- Go to a club meeting together
- Go to an event like Purdue sports, music, art, theater, or dance event(s) 