= Team Report

Another responsibility as a TA in The Data Mine is writing Team Reports. These reports are a set of questions that are answered by TAs and serve as a written retrospective of the team. TAs will provide honest feedback on their team's progress and submit the report to The Data Mine staff for review. The Data Mine staff then reads the reports and offers any guidance and assistance that was requested or perceived. 

Report questions will be based on:

1. The teams progress including questions and concerns.
2. A summary of activities and tasks that were completed during meetings and labs.
3. Names of students who were absent or did not complete assignments.

Questions will vary on the reports as each Sprint Report is unique. 

== Sample Team Report Questions
The questions found on Team Reports are:

1. Review the tasks of this sprint.  Are any of these tasks incomplete?

2. What has the team accomplished during this sprint?

3. What are your highest priorities for the next sprint?

4. During this print you completed the presentation initation activity.  How did the activity go?  Do you have any suggestions to improve the activity?

5. What students were absent this sprint?  What students missed asssignments this sprint?

== FAQs
*How often do TAs write and submit team reports?*

TAs submit team reports every two weeks. They should be completed throughout the sprint. We recommend making several submissions.  For example, submit once after each team meeting to ensure up to date information.

*Are the team reports required?*

Yes, they are required. These reports are the primary source of updates for The Data Mine staff.

*How long does it take to write a team report on average?*

Team reports are not difficult to write or very time consuming. It will usually take TAs no longer than 30 to 45 minutes to complete their team report.

