<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Projects | The Examples Book</title>
  <meta name="description" content="A book of supplemental examples for The Data Mine at Purdue University." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Projects | The Examples Book" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A book of supplemental examples for The Data Mine at Purdue University." />
  <meta name="github-repo" content="kevinamstutz/the-examples-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Projects | The Examples Book" />
  
  <meta name="twitter:description" content="A book of supplemental examples for The Data Mine at Purdue University." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="images/touch-icon.png" />
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
<link rel="prev" href="faqs.html"/>
<link rel="next" href="contributors.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="book.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">The Data Mine</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#how-to-contribute"><i class="fa fa-check"></i>How to contribute</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#small-changes-and-additions"><i class="fa fa-check"></i>Small changes and additions</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#larger-changes-or-additions"><i class="fa fa-check"></i>Larger changes or additions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="scholar.html"><a href="scholar.html"><i class="fa fa-check"></i>Scholar</a><ul>
<li class="chapter" data-level="" data-path="scholar.html"><a href="scholar.html#connecting-to-scholar"><i class="fa fa-check"></i>Connecting to Scholar</a><ul>
<li class="chapter" data-level="" data-path="scholar.html"><a href="scholar.html#rstudio-server-pro"><i class="fa fa-check"></i>RStudio Server Pro</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="scholar.html"><a href="scholar.html#other-ways-to-connect"><i class="fa fa-check"></i>Other ways to connect</a><ul>
<li class="chapter" data-level="" data-path="scholar.html"><a href="scholar.html#connecting-with-thinlinc-webclient"><i class="fa fa-check"></i>ThinLinc web client</a></li>
<li class="chapter" data-level="" data-path="scholar.html"><a href="scholar.html#connecting-with-thinlinc-client"><i class="fa fa-check"></i>ThinLinc client</a></li>
<li class="chapter" data-level="" data-path="scholar.html"><a href="scholar.html#connecting-with-ssh"><i class="fa fa-check"></i>SSH</a></li>
<li class="chapter" data-level="" data-path="scholar.html"><a href="scholar.html#jupyterhub"><i class="fa fa-check"></i>JupyterHub</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="scholar.html"><a href="scholar.html#scholar-resources"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-formats.html"><a href="data-formats.html"><i class="fa fa-check"></i>Data Formats</a><ul>
<li class="chapter" data-level="" data-path="data-formats.html"><a href="data-formats.html#html"><i class="fa fa-check"></i>HTML</a></li>
<li class="chapter" data-level="" data-path="data-formats.html"><a href="data-formats.html#xml"><i class="fa fa-check"></i>XML</a><ul>
<li class="chapter" data-level="" data-path="data-formats.html"><a href="data-formats.html#xml-xpath"><i class="fa fa-check"></i>XPath Expressions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html"><i class="fa fa-check"></i>Unix</a><ul>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html#unix-getting-started"><i class="fa fa-check"></i>Getting started</a></li>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html#unix-utilities"><i class="fa fa-check"></i>Standard utilities</a><ul>
<li><a href="unix.html#man"><code>man</code></a></li>
<li><a href="unix.html#cat"><code>cat</code></a></li>
<li><a href="unix.html#head"><code>head</code></a></li>
<li><a href="unix.html#tail"><code>tail</code></a></li>
<li><a href="unix.html#ls"><code>ls</code></a></li>
<li><a href="unix.html#du"><code>du</code></a></li>
<li><a href="unix.html#cp"><code>cp</code></a></li>
<li><a href="unix.html#mv"><code>mv</code></a></li>
<li><a href="unix.html#touch"><code>touch</code></a></li>
<li><a href="unix.html#mkdir"><code>mkdir</code></a></li>
<li><a href="unix.html#rm"><code>rm</code></a></li>
<li><a href="unix.html#rmdir"><code>rmdir</code></a></li>
<li><a href="unix.html#pwd"><code>pwd</code></a></li>
<li><a href="unix.html#type"><code>type</code></a></li>
<li><a href="unix.html#uniq"><code>uniq</code></a></li>
<li><a href="unix.html#wc"><code>wc</code></a></li>
<li><a href="unix.html#ssh"><code>ssh</code></a></li>
<li><a href="unix.html#scp"><code>scp</code></a></li>
<li><a href="unix.html#cut"><code>cut</code></a></li>
<li><a href="unix.html#sed"><code>sed</code></a></li>
<li><a href="unix.html#grep"><code>grep</code></a></li>
<li><a href="unix.html#find"><code>find</code></a></li>
<li><a href="unix.html#less"><code>less</code></a></li>
<li><a href="unix.html#sort"><code>sort</code></a></li>
<li><a href="unix.html#git-ref-01"><code>git</code></a></li>
</ul></li>
<li><a href="unix.html#awk"><code>awk</code></a><ul>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html#unix-awk-built-in-variables"><i class="fa fa-check"></i>Built in variables</a></li>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html#examples-5"><i class="fa fa-check"></i>Examples</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html#dots"><i class="fa fa-check"></i>~ &amp; . &amp; ..</a><ul>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html#examples-6"><i class="fa fa-check"></i>Examples</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html#piping-and-redirection"><i class="fa fa-check"></i>Piping &amp; Redirection</a><ul>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html#redirection"><i class="fa fa-check"></i>Redirection</a></li>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html#piping"><i class="fa fa-check"></i>Piping</a></li>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html#piping-and-redirection-resources"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html#emacs"><i class="fa fa-check"></i>Emacs</a></li>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html#nano"><i class="fa fa-check"></i>Nano</a></li>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html#vim"><i class="fa fa-check"></i>Vim</a></li>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html#unix-writing-scripts"><i class="fa fa-check"></i>Writing scripts</a><ul>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html#unix-bash-arguments"><i class="fa fa-check"></i>Arguments</a></li>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html#unix-bash-script-examples"><i class="fa fa-check"></i>Examples</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html"><i class="fa fa-check"></i>SQL</a><ul>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#sql-joins"><i class="fa fa-check"></i>Joins</a><ul>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#sql-inner-join"><i class="fa fa-check"></i>INNER JOIN</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#sql-left-join"><i class="fa fa-check"></i>LEFT OUTER JOIN</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#aliasing"><i class="fa fa-check"></i>Aliasing</a><ul>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#sql-rdbms"><i class="fa fa-check"></i>RDBMS</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#sql-in-r"><i class="fa fa-check"></i>SQL in R</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#sql-in-python"><i class="fa fa-check"></i>SQL in Python</a></li>
<li class="chapter" data-level="" data-path="sql.html"><a href="sql.html#sql-examples"><i class="fa fa-check"></i>Examples</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html"><i class="fa fa-check"></i>R</a><ul>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#getting-started-with-r"><i class="fa fa-check"></i>Getting started</a><ul>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-8451-intro"><i class="fa fa-check"></i>Examples using the 84.51 data set.</a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-nyc-taxi-intro"><i class="fa fa-check"></i>Examples using the New York City yellow taxi cab data set.</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-variables"><i class="fa fa-check"></i>Variables</a><ul>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-na"><i class="fa fa-check"></i>NA</a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-nan"><i class="fa fa-check"></i>NaN</a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-null"><i class="fa fa-check"></i>NULL</a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-dates"><i class="fa fa-check"></i>Dates</a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-factors"><i class="fa fa-check"></i>Factors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-logical-operators"><i class="fa fa-check"></i>Logical operators</a><ul>
<li class="chapter" data-level="" data-path="data-formats.html"><a href="data-formats.html#examples"><i class="fa fa-check"></i>Examples</a></li>
<li class="chapter" data-level="" data-path="data-formats.html"><a href="data-formats.html#resources"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-lists-and-vectors"><i class="fa fa-check"></i>Lists &amp; Vectors</a><ul>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-indexing"><i class="fa fa-check"></i>Indexing</a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-recycling"><i class="fa fa-check"></i>Recycling</a></li>
<li class="chapter" data-level="" data-path="unix.html"><a href="unix.html#examples-2"><i class="fa fa-check"></i>Examples</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-basic-functions"><i class="fa fa-check"></i>Basic R functions</a><ul>
<li><a href="r.html#r-all"><code>all</code></a></li>
<li><a href="r.html#r-any"><code>any</code></a></li>
<li><a href="r.html#r-all.equal"><code>all.equal</code></a></li>
<li><a href="r.html#r-in"><code>%in%</code></a></li>
<li><a href="r.html#r-setdiff"><code>setdiff</code></a></li>
<li><a href="r.html#r-intersect"><code>intersect</code></a></li>
<li><a href="r.html#r-dim"><code>dim</code></a></li>
<li><a href="r.html#r-length"><code>length</code></a></li>
<li><a href="r.html#r-rep"><code>rep</code></a></li>
<li><a href="r.html#r-bind"><code>rbind</code> and <code>cbind</code></a></li>
<li><a href="r.html#r-which"><code>which</code>, <code>which.max</code>, <code>which.min</code></a></li>
<li><a href="r.html#r-grep"><code>grep</code>, <code>grepl</code>, etc.</a></li>
<li><a href="r.html#r-sum"><code>sum</code></a></li>
<li><a href="r.html#r-mean"><code>mean</code></a></li>
<li><a href="r.html#r-var"><code>var</code></a></li>
<li><a href="r.html#r-sums"><code>colSums</code> and <code>rowSums</code></a></li>
<li><a href="r.html#r-means"><code>colMeans</code> and <code>rowMeans</code></a></li>
<li><a href="r.html#r-unique"><code>unique</code></a></li>
<li><a href="r.html#r-summary"><code>summary</code></a></li>
<li><a href="r.html#r-order"><code>order</code> and <code>sort</code></a></li>
<li><a href="r.html#r-paste"><code>paste</code> and <code>paste0</code></a></li>
<li><a href="r.html#r-head"><code>head</code> and <code>tail</code></a></li>
<li><a href="r.html#r-str"><code>str</code></a></li>
<li><a href="r.html#r-strsplit"><code>strsplit</code></a></li>
<li><a href="r.html#r-names"><code>names</code></a></li>
<li><a href="r.html#r-colnames-and-rownames"><code>colnames</code> &amp; <code>rownames</code></a></li>
<li><a href="r.html#r-table"><code>table</code> &amp; <code>prop.table</code></a></li>
<li><a href="r.html#r-cut"><code>cut</code></a></li>
<li><a href="r.html#r-subset"><code>subset</code></a></li>
<li><a href="r.html#difftime-r-difftime"><code>difftime</code> {r#-difftime}</a></li>
<li><a href="r.html#r-merge"><code>merge</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-data-frames"><i class="fa fa-check"></i>Data.frames</a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-reading-and-writing-data"><i class="fa fa-check"></i>Reading &amp; Writing data</a><ul>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#examples-29"><i class="fa fa-check"></i>Examples</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-control-flow"><i class="fa fa-check"></i>Control flow</a><ul>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-if-else"><i class="fa fa-check"></i>If/else statements</a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-for-loops"><i class="fa fa-check"></i>For loops</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-apply-functions"><i class="fa fa-check"></i>Apply functions</a><ul>
<li><a href="r.html#r-apply"><code>apply</code></a></li>
<li><a href="r.html#r-lapply"><code>lapply</code></a></li>
<li><a href="r.html#r-sapply"><code>sapply</code></a></li>
<li><a href="r.html#r-tapply"><code>tapply</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-writing-functions"><i class="fa fa-check"></i>Writing functions</a><ul>
<li><a href="r.html#r-ellipsis"><code>...</code></a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#examples-34"><i class="fa fa-check"></i>Examples</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-plotting"><i class="fa fa-check"></i>Plotting</a><ul>
<li><a href="r.html#r-barplot"><code>barplot</code></a></li>
<li><a href="r.html#r-boxplot"><code>boxplot</code></a></li>
<li><a href="r.html#r-pie"><code>pie</code></a></li>
<li><a href="r.html#r-dotchart"><code>dotchart</code></a></li>
<li><a href="r.html#r-plot"><code>plot</code></a></li>
<li><a href="r.html#r-lines"><code>lines</code></a></li>
<li><a href="r.html#r-points"><code>points</code></a></li>
<li><a href="r.html#r-abline"><code>abline</code></a></li>
<li><a href="r.html#r-text"><code>text</code></a></li>
<li><a href="r.html#r-mtext"><code>mtext</code></a></li>
<li><a href="r.html#r-legend"><code>legend</code></a></li>
<li><a href="r.html#r-par"><code>par</code></a></li>
<li><a href="r.html#r-plot_usmap"><code>plot_usmap</code></a></li>
<li><a href="r.html#r-ggplot"><code>ggplot</code></a></li>
<li><a href="r.html#r-ggmap"><code>ggmap</code></a></li>
<li><a href="r.html#r-leaflet"><code>leaflet</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-rmarkdown"><i class="fa fa-check"></i>RMarkdown</a><ul>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#code-chunks"><i class="fa fa-check"></i>Code chunks</a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-markdown-resources"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-tidyverse"><i class="fa fa-check"></i>Tidyverse</a><ul>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-piping"><i class="fa fa-check"></i>piping</a></li>
<li><a href="r.html#r-glimpse"><code>glimpse</code></a></li>
<li><a href="r.html#r-filter"><code>filter</code></a></li>
<li><a href="r.html#r-arrange"><code>arrange</code></a></li>
<li><a href="r.html#r-mutate"><code>mutate</code></a></li>
<li><a href="r.html#r-group-by"><code>group_by</code></a></li>
<li><a href="r.html#r-str-extract"><code>str_extract</code> and <code>str_extract_all</code></a></li>
<li><a href="r.html#r-lubridate"><code>lubridate</code></a></li>
<li><a href="r.html#r-strrep"><code>strrep</code></a></li>
<li><a href="r.html#r-nchar"><code>nchar</code></a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-lubridate-resources"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-datatable"><i class="fa fa-check"></i>data.table</a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-sql"><i class="fa fa-check"></i>SQL in R</a></li>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-scraping"><i class="fa fa-check"></i>Scraping</a></li>
<li><a href="r.html#r-shiny"><code>shiny</code></a><ul>
<li class="chapter" data-level="" data-path="r.html"><a href="r.html#r-shiny-render-images"><i class="fa fa-check"></i>Rendering images</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html"><i class="fa fa-check"></i>Python</a><ul>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#getting-started-with-python"><i class="fa fa-check"></i>Getting started</a><ul>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#python-on-scholar"><i class="fa fa-check"></i>Python on Scholar</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-variables"><i class="fa fa-check"></i>Variables</a><ul>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-none"><i class="fa fa-check"></i>None</a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-bool"><i class="fa fa-check"></i>bool</a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-str"><i class="fa fa-check"></i>str</a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-int"><i class="fa fa-check"></i>int</a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-float"><i class="fa fa-check"></i>float</a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-complex"><i class="fa fa-check"></i>complex</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-printing"><i class="fa fa-check"></i>Printing</a><ul>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-f-strings"><i class="fa fa-check"></i>f-strings</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-logical-operators"><i class="fa fa-check"></i>Logical operators</a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-lists-and-tuples"><i class="fa fa-check"></i>Lists &amp; Tuples</a><ul>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-indexing"><i class="fa fa-check"></i>Indexing</a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-list-methods"><i class="fa fa-check"></i>List methods</a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#tuple-methods"><i class="fa fa-check"></i>Tuple methods</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-dicts"><i class="fa fa-check"></i>Dicts</a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-sets"><i class="fa fa-check"></i>Sets</a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-control-flow"><i class="fa fa-check"></i>Control flow</a><ul>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-if-else"><i class="fa fa-check"></i>If/else statements</a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-for-loops"><i class="fa fa-check"></i>For loops</a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-list-comprehensions"><i class="fa fa-check"></i>List comprehensions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-writing-functions"><i class="fa fa-check"></i>Writing functions</a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-reading-and-writing-data"><i class="fa fa-check"></i>Reading &amp; Writing data</a><ul>
<li><a href="python.html#read_csv"><code>read_csv</code></a></li>
<li><a href="python.html#p-csv-pkg"><code>csv</code></a></li>
</ul></li>
<li><a href="python.html#p-pathlib"><code>pathlib</code></a><ul>
<li><a href="python.html#p-pathlib-path"><code>Path</code></a></li>
</ul></li>
<li><a href="python.html#p-numpy"><code>numpy</code></a></li>
<li><a href="python.html#p-scipy"><code>scipy</code></a></li>
<li><a href="python.html#p-pandas"><code>pandas</code></a><ul>
<li><a href="python.html#p-pandas-read_csv"><code>read_csv</code></a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-pandas-dataframe"><i class="fa fa-check"></i>DataFrame</a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-pandas-series"><i class="fa fa-check"></i>Series</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-jupyter-notebooks"><i class="fa fa-check"></i>Jupyter notebooks</a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-writing-scripts"><i class="fa fa-check"></i>Writing scripts</a><ul>
<li><a href="python.html#p-argparse"><code>argparse</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-scraping"><i class="fa fa-check"></i>Scraping</a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-xml"><i class="fa fa-check"></i>XML</a><ul>
<li><a href="python.html#p-lxml"><code>lxml</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-plotting"><i class="fa fa-check"></i>Plotting</a><ul>
<li><a href="python.html#p-matplotlib"><code>matplotlib</code></a></li>
<li><a href="python.html#p-plotly"><code>plotly</code></a></li>
<li><a href="python.html#p-plotnine"><code>plotnine</code></a></li>
<li><a href="python.html#p-pygal"><code>pygal</code></a></li>
<li><a href="python.html#p-seaborn"><code>seaborn</code></a></li>
<li><a href="python.html#p-bokeh"><code>bokeh</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#p-classes"><i class="fa fa-check"></i>Classes</a><ul>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#attributes"><i class="fa fa-check"></i>Attributes</a></li>
<li class="chapter" data-level="" data-path="python.html"><a href="python.html#methods"><i class="fa fa-check"></i>Methods</a></li>
</ul></li>
<li><a href="python.html#tensorflow"><code>tensorflow</code></a></li>
<li><a href="python.html#pytorch"><code>pytorch</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tools.html"><a href="tools.html"><i class="fa fa-check"></i>Tools</a><ul>
<li class="chapter" data-level="" data-path="tools.html"><a href="tools.html#docker"><i class="fa fa-check"></i>Docker</a></li>
<li class="chapter" data-level="" data-path="tools.html"><a href="tools.html#tableau"><i class="fa fa-check"></i>Tableau</a></li>
<li class="chapter" data-level="" data-path="tools.html"><a href="tools.html#github"><i class="fa fa-check"></i>GitHub</a><ul>
<li class="chapter" data-level="" data-path="tools.html"><a href="tools.html#github-overview"><i class="fa fa-check"></i>Overview</a></li>
<li><a href="tools.html#git"><code>git</code></a></li>
<li class="chapter" data-level="" data-path="tools.html"><a href="tools.html#github-desktop"><i class="fa fa-check"></i>GitHub Desktop</a></li>
<li class="chapter" data-level="" data-path="tools.html"><a href="tools.html#git-resources"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tools.html"><a href="tools.html#vpns"><i class="fa fa-check"></i>VPNs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html"><i class="fa fa-check"></i>FAQs</a><ul>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-no-such-file-or-directory"><i class="fa fa-check"></i>Cannot open the connection. No such file or directory.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-how-do-i-connect-to-scholar-off-campus"><i class="fa fa-check"></i>How do I connect to Scholar from off-campus?</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-cursor-offset"><i class="fa fa-check"></i>In Scholar, on RStudio, my font size looks weird or my cursor is offset.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-unable-to-type-terminal"><i class="fa fa-check"></i>I'm unable to type into the terminal in RStudio.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-unable-to-connect-to-rstudio-server"><i class="fa fa-check"></i>I'm unable to connect to RStudio Server.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-rstudio-long-time-to-open"><i class="fa fa-check"></i>RStudio is taking a long time to open.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-deleting-file-in-RStudio"><i class="fa fa-check"></i>How do I delete a file from my RStudio directory? (asked by Karthik Uppuluri)</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-how-do-i-rename-file-rstudio"><i class="fa fa-check"></i>How do I rename a file from my RStudio directory?</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-running-R-code"><i class="fa fa-check"></i>How can you run a line of R code in RStudio without clicking the &quot;Run&quot; button?</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-r-session-freezes"><i class="fa fa-check"></i>My R session freezes.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-scholar-is-slow"><i class="fa fa-check"></i>Scholar is slow.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-how-to-transfer-files"><i class="fa fa-check"></i>How to transfer files between your computer and Scholar.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#password-wont-work"><i class="fa fa-check"></i>My password will not work.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-jupyter-notebook-download-error-ie"><i class="fa fa-check"></i>Jupyter Notebook download error with IE.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-jupyter-notebook-kernel-dying"><i class="fa fa-check"></i>Jupyter Notebook kernel dying.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-kernel-jupyter-wont-save"><i class="fa fa-check"></i>Python kernel not working, Jupyter Notebook won't save.</a></li>
<li><a href="faqs.html#faq-installing-python-package">Installing <code>my_package</code> for Python.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-displaying-multiple-images-jupyter"><i class="fa fa-check"></i>Displaying multiple images after a single Jupyter Notebook Python code cell.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-error-has-null-value"><i class="fa fa-check"></i>RMarkdown “Error: option error has NULL value” when knitting&quot;.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-creating-rmarkdown-file"><i class="fa fa-check"></i>How do you create an RMarkdown file?</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-problems-building-rmarkdown-scholar"><i class="fa fa-check"></i>Problems building an RMarkdown document on Scholar.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-how-to-use-sql-in-rmarkdown"><i class="fa fa-check"></i>How can I use SQL in RMarkdown?</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-copy-paste-from-terminal-inside-rstudio"><i class="fa fa-check"></i>Copy/paste from terminal (not a console) inside RStudio to RMarkdown.</a></li>
<li><a href="faqs.html#faq-how-to-render-image-in-shiny-app">How do I render an image in a <code>shiny</code> app?</a></li>
<li><a href="faqs.html#faq-package-not-found">The package <code>my_package</code> is not found.</a></li>
<li><a href="faqs.html#faq-problems-installing-ggmap">Problems installing <code>ggmap</code>.</a></li>
<li><a href="faqs.html#faq-object-name-not-found">Error: <code>object_name</code> is not found.</a></li>
<li><a href="faqs.html#faq-zoom-in-ggmap">Zoom in on <code>ggmap</code>.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-find-lat-long-of-loc"><i class="fa fa-check"></i>Find the latitude and longitude of a location.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-save-work-pdf-scholar"><i class="fa fa-check"></i>Problems saving work as a PDF in R on Scholar.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-resources-for-html"><i class="fa fa-check"></i>What is a good resource to better understand HTML?</a></li>
<li><a href="faqs.html#faq-style-guide-r">Is there a style guide for <code>R</code> code?</a></li>
<li><a href="faqs.html#faq-best-practices-r">Is there a guide for best practices using <code>R</code>?</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-tips-for-jupyter"><i class="fa fa-check"></i>Tips for using Jupyter notebooks.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-what-is-my-username"><i class="fa fa-check"></i>What is my username on Scholar?</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-escape-characters"><i class="fa fa-check"></i>How and why would I need to &quot;escape a character&quot;?</a><ul>
<li class="chapter" data-level="" data-path="data-formats.html"><a href="data-formats.html#resources"><i class="fa fa-check"></i>Resources</a></li>
</ul></li>
<li><a href="faqs.html#faq-fix-illegal-byte-sequence">How can I fix the error &quot;Illegal byte sequence&quot; when using a UNIX utility like <code>cut</code>?</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#faq-rmarkdown-unicode-error"><i class="fa fa-check"></i>Unicode character error when Knitting an RMarkdown file to PDF.</a></li>
<li class="chapter" data-level="" data-path="faqs.html"><a href="faqs.html#my-tab-key-will-not-auto-complete-anymore-in-rstudio.-how-can-i-fix-this"><i class="fa fa-check"></i>My tab key will not auto-complete anymore in RStudio. How can I fix this?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="projects.html"><a href="projects.html"><i class="fa fa-check"></i>Projects</a><ul>
<li class="chapter" data-level="" data-path="projects.html"><a href="projects.html#templates"><i class="fa fa-check"></i>Templates</a></li>
<li class="chapter" data-level="" data-path="projects.html"><a href="projects.html#submissions"><i class="fa fa-check"></i>Submissions</a></li>
<li class="chapter" data-level="" data-path="projects.html"><a href="projects.html#stat-19000"><i class="fa fa-check"></i>STAT 19000</a><ul>
<li class="chapter" data-level="" data-path="projects.html"><a href="projects.html#p01-190"><i class="fa fa-check"></i>Project 1</a></li>
<li class="chapter" data-level="" data-path="projects.html"><a href="projects.html#p02-190"><i class="fa fa-check"></i>Project 2</a></li>
<li class="chapter" data-level="" data-path="projects.html"><a href="projects.html#p03-190"><i class="fa fa-check"></i>Project 3</a></li>
<li class="chapter" data-level="" data-path="projects.html"><a href="projects.html#p04-190"><i class="fa fa-check"></i>Project 4</a></li>
<li class="chapter" data-level="" data-path="projects.html"><a href="projects.html#p05-190"><i class="fa fa-check"></i>Project 5</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="projects.html"><a href="projects.html#stat-29000"><i class="fa fa-check"></i>STAT 29000</a><ul>
<li class="chapter" data-level="" data-path="projects.html"><a href="projects.html#p01-290"><i class="fa fa-check"></i>Project 1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="projects.html"><a href="projects.html#stat-39000"><i class="fa fa-check"></i>STAT 39000</a><ul>
<li class="chapter" data-level="" data-path="projects.html"><a href="projects.html#p01-390"><i class="fa fa-check"></i>Project 1</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="contributors.html"><a href="contributors.html"><i class="fa fa-check"></i>Contributors</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The Examples Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="projects" class="section level1">
<h1>Projects</h1>
<div id="templates" class="section level2">
<h2>Templates</h2>
<p>Our course project template can be found <a href="https://raw.githubusercontent.com/TheDataMine/the-examples-book/master/files/project_template.Rmd">here</a>, or on Scholar:</p>
<p><code>/class/datamine/apps/templates/project_template.Rmd</code></p>
<p><strong>Important note:</strong> We've updated the template to allow a code chunk option that prevents content from running off the page. Simply add <code>linewidth=80</code> to any code chunk that creates output that runs off the page.</p>
<p>This video demonstrates:</p>
<ul>
<li>opening a browser (emphasizing Firefox as the best choice),</li>
<li>opening RStudio Server Pro (<a href="https://rstudio.scholar.rcac.purdue.edu" class="uri">https://rstudio.scholar.rcac.purdue.edu</a>),</li>
<li>introducing (basics) about what RStudio looks like,</li>
<li>checking to see that the students are using R 4.0,</li>
<li>running the initial (one-time) setup script,</li>
<li>opening the project template,</li>
<li>knitting the template into a PDF file, and</li>
<li>finally handling the popup blocker, which can potentially block the PDF.</li>
</ul>
<p><strong><a href="https://cdnapisec.kaltura.com/p/983291/sp/98329100/embedIframeJs/uiconf_id/29134031/partner_id/983291?iframeembed=true&amp;playerId=kaltura_player&amp;entry_id=1_444kq84l&amp;flashvars%5BstreamerType%5D=auto&amp;flashvars%5BlocalizationCode%5D=en&amp;flashvars%5BleadWithHTML5%5D=true&amp;flashvars%5BsideBarContainer.plugin%5D=true&amp;flashvars%5BsideBarContainer.position%5D=left&amp;flashvars%5BsideBarContainer.clickToClose%5D=true&amp;flashvars%5Bchapters.plugin%5D=true&amp;flashvars%5Bchapters.layout%5D=vertical&amp;flashvars%5Bchapters.thumbnailRotator%5D=false&amp;flashvars%5BstreamSelector.plugin%5D=true&amp;flashvars%5BEmbedPlayer.SpinnerTarget%5D=videoHolder&amp;flashvars%5BdualScreen.plugin%5D=true&amp;flashvars%5BKaltura.addCrossoriginToIframe%5D=true&amp;&amp;wid=1_5wx961lv">Click here for video</a></strong></p>
<p>Students in STAT 19000, 29000, and 39000 are to use this as a template for all project submissions. The template includes a code chunk that &quot;activates&quot; our Python environment, and adjusts some default settings. In addition, it provides examples on how to include solutions for Python, R, Bash, and SQL. Every question should be clearly marked with a third-level header (using 3 <code>#</code>s) followed by <code>Question 1</code>, <code>Question 2</code>, etc. Sections for solutions should be added or removed, based on the number of questions in the given project. All code chunks are to be run and solutions displayed for the compiled PDF submission.</p>
<p>Any format or template related questions should be asked in Piazza.</p>
</div>
<div id="submissions" class="section level2">
<h2>Submissions</h2>
<p>Unless otherwise specified, all projects will need 2-4 submitted files:</p>
<ol style="list-style-type: decimal">
<li>A compiled PDF file (built using the template), with all code and output.</li>
<li>The .Rmd file (based off of <a href="projects.html#templates">the template</a>), used to Knit the final PDF.</li>
<li>If it is a project containing R code, a .R file containing all of the R code with comments explaining what the code does. <em>Note: This is <strong>not</strong> an .Rmd file.</em></li>
<li>If it is a project containing Python code, a .py file containing all of the Python code.</li>
</ol>
</div>
<div id="stat-19000" class="section level2">
<h2>STAT 19000</h2>
<div id="p01-190" class="section level3">
<h3>Project 1</h3>
<hr />
<p><strong>Motivation:</strong> In this course we require the majority of project submissions to include a compiled PDF, a .Rmd file based off of <a href="https://raw.githubusercontent.com/TheDataMine/the-examples-book/master/files/project_template.Rmd">our template</a>, and a code file (a .R file if the project is in R, a .py file if the project is in Python). Although RStudio makes it easy to work with both Python and R, there are occasions where working out a Python problem in a Jupyter Notebook could be convenient. For that reason, we will introduce Jupyter Notebook in this project.</p>
<p><strong>Context:</strong> This is the first in a series of projects that will introduce Python and its tooling to students.</p>
<p><strong>Scope:</strong> jupyter notebooks, rstudio, python</p>
<p><strong>Learning objectives:</strong></p>
<div class="bbox">
<ul>
<li>
Use Jupyter Notebook to run Python code and create Markdown text.
</li>
<li>
Use RStudio to run Python code and compile your final PDF.
</li>
<li>
Gain exposure to Python control flow and reading external data.
</li>
</ul>
</div>
<p>Make sure to read about, and use the template found <a href="projects.html#templates">here</a>, and the important information about projects submissions <a href="projects.html#submissions">here</a>.</p>
<div id="dataset" class="section level4">
<h4>Dataset</h4>
<p>The following questions will use the dataset found in Scholar:</p>
<p><code>/class/datamine/data/open_food_facts/openfoodfacts.tsv</code></p>
</div>
<div id="questions" class="section level4">
<h4>Questions</h4>
<div id="navigate-to-httpsnotebook.scholar.rcac.purdue.edu-and-sign-in-with-your-purdue-credentials-without-boilerkey.-this-is-an-instance-of-jupyter-notebook.-the-main-screen-will-show-a-series-of-files-and-folders-that-are-in-your-home-directory.-create-a-new-notebook-by-clicking-on-new-f2020-s2021." class="section level5">
<h5>1. Navigate to <a href="https://notebook.scholar.rcac.purdue.edu/" class="uri">https://notebook.scholar.rcac.purdue.edu/</a> and sign in with your Purdue credentials (<em>without</em> BoilerKey). This is an instance of Jupyter Notebook. The main screen will show a series of files and folders that are in your <code>$HOME</code> directory. Create a new notebook by clicking on <code>New &gt; f2020-s2021</code>.</h5>
</div>
<div id="change-the-name-of-your-notebook-to-lastname_firstname_project01-where-lastname-is-your-family-name-and-firstname-is-your-given-name.-try-to-export-your-notebook-using-the-file-dropdown-menu-choosing-the-option-download-as-what-format-options-for-example-.pdf-are-available-to-you" class="section level5">
<h5>Change the name of your notebook to &quot;LASTNAME_FIRSTNAME_project01&quot; where &quot;LASTNAME&quot; is your family name, and &quot;FIRSTNAME&quot; is your given name. Try to export your notebook (using the <code>File</code> dropdown menu, choosing the option <code>Download as</code>), what format options (for example, <code>.pdf</code>) are available to you?</h5>
<p><strong>Important note:</strong> <code>f2020-s2021</code> is the name of our course notebook kernel. A notebook kernel is an engine that runs code in a notebook. ipython kernels run Python code. <code>f2020-s2021</code> is an ipython kernel that we've created for our course Python environment, which contains a variety of compatible, pre-installed packages for you to use. When you select <code>f2020-s2021</code> as your kernel, all of the packages in our course environment are automatically made available to you.</p>
<p><a href="https://mediaspace.itap.purdue.edu/id/1_4g2lwx5g">Click here for video</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
A list of export format options.
</li>
</ul>
</div>
</div>
<div id="each-box-in-a-jupyter-notebook-is-called-a-cell.-there-are-two-primary-types-of-cells-code-and-markdown.-by-default-a-cell-will-be-a-code-cell.-place-the-following-python-code-inside-the-first-cell-and-run-the-cell.-what-is-the-output" class="section level5">
<h5>2. Each &quot;box&quot; in a Jupyter Notebook is called a <em>cell</em>. There are two primary types of cells: code, and markdown. By default, a cell will be a code cell. Place the following Python code inside the first cell, and run the cell. What is the output?</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="im">from</span> thedatamine <span class="im">import</span> hello_datamine
hello_datamine()</code></pre></div>
<p><strong>Hint:</strong> You can run the code in the currently selected cell by using the GUI (the buttons), as well as by pressing <code>Ctrl+Return/Enter</code>.</p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Output from running the provided code.
</li>
</ul>
</div>
</div>
<div id="jupyter-notebooks-allow-you-to-easily-pull-up-documentation-similar-to-function-in-r.-to-do-so-use-the-help-function-like-this-helpmy_function.-what-is-the-output-from-running-the-help-function-on-hello_datamine-can-you-modify-the-code-from-question-2-to-print-a-customized-message-create-a-new-markdown-cell-and-explain-what-you-did-to-the-code-from-question-2-to-make-the-message-customized." class="section level5">
<h5>3. Jupyter Notebooks allow you to easily pull up documentation, similar to <code>?function</code> in R. To do so, use the <code>help</code> function, like this: <code>help(my_function)</code>. What is the output from running the help function on <code>hello_datamine</code>? Can you modify the code from question (2) to print a customized message? Create a new <em>markdown</em> cell and explain what you did to the code from question (2) to make the message customized.</h5>
<p><strong>Important note:</strong> Some Jupyter-only methods to do this are:</p>
<ul>
<li>Click on the function of interest and type <code>Shift+Tab</code> or <code>Shift+Tab+Tab</code>.</li>
<li>Run <code>function?</code>, for example, <code>print?</code>.</li>
</ul>
<p><strong>Important note:</strong> You can also see the source code of a function in a Jupyter Notebook by typing <code>function??</code>, for example, <code>print??</code>.</p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Output from running the <code>help</code> function on <code>hello_datamine</code>.
</li>
<li>
Modified code from question (2) that prints a customized message.
</li>
</ul>
</div>
</div>
<div id="at-this-point-in-time-youve-now-got-the-basics-of-running-python-code-in-jupyter-notebooks.-there-is-really-not-a-whole-lot-more-to-it.-for-this-class-however-we-will-continue-to-create-rmarkdown-documents-in-addition-to-the-compiled-pdfs.-you-are-welcome-to-use-jupyter-notebooks-for-personal-projects-or-for-testing-things-out-however-we-will-still-require-an-rmarkdown-file-.rmd-pdf-generated-from-the-rmarkdown-file-and-.py-file-containing-your-python-code.-for-example-please-move-your-solutions-from-questions-1-2-3-from-jupyter-notebooks-over-to-rmarkdown-we-discuss-rmarkdown-below.-lets-learn-how-to-run-python-code-chunks-in-rmarkdown." class="section level5">
<h5>4. At this point in time, you've now got the basics of running Python code in Jupyter Notebooks. There is really not a whole lot more to it. For this class, however, we will continue to create RMarkdown documents in addition to the compiled PDFs. You are welcome to use Jupyter Notebooks for personal projects or for testing things out, however, we will still require an RMarkdown file (.Rmd), PDF (generated from the RMarkdown file), and .py file (containing your python code). For example, please move your solutions from Questions 1, 2, 3 from Jupyter Notebooks over to RMarkdown (we discuss RMarkdown below). Let's learn how to run Python code chunks in RMarkdown.</h5>
</div>
<div id="sign-in-to-httpsrstudio.scholar.rcac.purdue.edu-with-boilerkey.-projects-in-the-data-mine-should-all-be-submitted-using-our-template-found-here-or-on-scholar-classdatamineappstemplatesproject_template.rmd." class="section level5">
<h5>Sign in to <a href="https://rstudio.scholar.rcac.purdue.edu" class="uri">https://rstudio.scholar.rcac.purdue.edu</a> (<em>with</em> BoilerKey). Projects in The Data Mine should all be submitted using our template found <a href="https://raw.githubusercontent.com/TheDataMine/the-examples-book/master/files/project_template.Rmd">here</a> or on Scholar (<code>/class/datamine/apps/templates/project_template.Rmd</code>).</h5>
</div>
<div id="open-the-project-template-and-save-it-into-your-home-directory-in-a-new-rmarkdown-file-named-project01.rmd.-prior-to-running-any-python-code-run-datamine_py-in-the-r-console-just-like-you-did-at-the-beginning-of-every-project-from-the-first-semester." class="section level5">
<h5>Open the project template and save it into your home directory, in a new RMarkdown file named <code>project01.Rmd</code>. Prior to running any Python code, run <code>datamine_py()</code> in the R console, just like you did at the beginning of every project from the first semester.</h5>
</div>
<div id="code-chunks-are-parts-of-the-rmarkdown-file-that-contains-code.-you-can-identify-what-type-of-code-a-code-chunk-contains-by-looking-at-the-engine-in-the-curly-braces-and-.-as-you-can-see-it-is-possible-to-mix-and-match-different-languages-just-by-changing-the-engine.-move-the-solutions-for-questions-1-3-to-your-project01.rmd.-make-sure-to-place-all-python-code-in-python-code-chunks.-run-the-python-code-chunks-to-ensure-you-get-the-same-results-as-you-got-when-running-the-python-code-in-a-jupyter-notebook." class="section level5">
<h5>Code chunks are parts of the RMarkdown file that contains code. You can identify what type of code a code chunk contains by looking at the <em>engine</em> in the curly braces &quot;{&quot; and &quot;}&quot;. As you can see, it is possible to mix and match different languages just by changing the engine. Move the solutions for questions 1-3 to your <code>project01.Rmd</code>. Make sure to place all Python code in <code>python</code> code chunks. Run the <code>python</code> code chunks to ensure you get the same results as you got when running the Python code in a Jupyter Notebook.</h5>
<p><strong>Important note:</strong> Make sure to run <code>datamine_py()</code> in the R console prior to attempting to run any Python code.</p>
<p><strong>Hint:</strong> The end result of the <code>project01.Rmd</code> should look <em>similar</em> to <a href="https://raw.githubusercontent.com/TheDataMine/the-examples-book/master/files/example02.Rmd">this</a>.</p>
<p><a href="https://mediaspace.itap.purdue.edu/id/1_nhkygxg9">Click here for video</a></p>
<p><a href="https://mediaspace.itap.purdue.edu/id/1_tdz3wmim">Click here for video</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
<code>project01.Rmd</code> with the solutions from questions 1-3 (including any Python code in <code>python</code> code chunks).
</li>
</ul>
</div>
</div>
<div id="it-is-not-a-data-mine-project-without-data-here-are-some-examples-of-reading-in-data-line-by-line-using-the-csv-package.-how-many-columns-are-in-the-following-dataset-classdataminedataopen_food_factsopenfoodfacts.tsv-print-the-first-row-the-number-of-columns-and-then-exit-the-loop-after-the-first-iteration-using-the-break-keyword." class="section level5">
<h5>5. It is not a Data Mine project without data! <a href="python.html#p-csv-pkg">Here</a> are some examples of reading in data line by line using the <code>csv</code> package. How many columns are in the following dataset: <code>/class/datamine/data/open_food_facts/openfoodfacts.tsv</code>? Print the first row, the number of columns, and then exit the loop after the first iteration using the <code>break</code> keyword.</h5>
<p><strong>Hint:</strong> You can get the number of elements in a list by using the <code>len</code> method. For example: <code>len(my_list)</code>.</p>
<p><strong>Hint:</strong> You can use the <code>break</code> keyword to exit a loop. As soon as <code>break</code> is executed, the loop is exited and the code immediately following the loop is run.</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="cf">for</span> my_row <span class="kw">in</span> my_csv_reader:
    <span class="bu">print</span>(my_row)
    <span class="cf">break</span>

<span class="bu">print</span>(<span class="st">&quot;Exited loop as soon as &#39;break&#39; was run.&quot;</span>)</code></pre></div>
<p><strong>Hint:</strong> <code>'\t'</code> represents a tab in Python.</p>
<p><a href="https://mediaspace.itap.purdue.edu/id/1_ck74xlzq">Click here for video</a></p>
<p><strong>Important note:</strong> If you get a Dtype warning, feel free to just ignore it.</p>
<p><strong>Relevant topics:</strong> <a href="python.html#p-for-loops">for loops</a>, <a href="python.html#p-break">break</a>, <a href="#p-print">print</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve this problem.
</li>
<li>
The first row printed, and the number of columns printed.
</li>
</ul>
</div>
</div>
<div id="optional.-unlike-in-r-where-many-of-the-tools-you-need-are-built-in-read.csv-data.frames-etc.-in-python-you-will-need-to-rely-on-packages-like-numpy-and-pandas-to-do-the-bulk-of-your-data-science-work." class="section level5">
<h5>6 (optional). Unlike in R, where many of the tools you need are built-in (<code>read.csv</code>, data.frames, etc.), in Python, you will need to rely on packages like <code>numpy</code> and <code>pandas</code> to do the bulk of your data science work.</h5>
</div>
<div id="in-r-it-would-be-really-easy-to-find-the-mean-of-the-151st-column-caffeine_100g" class="section level5">
<h5>In R it would be really easy to find the mean of the 151st column, <code>caffeine_100g</code>:</h5>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">myDF &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;/class/datamine/data/open_food_facts/openfoodfacts.tsv&quot;</span>, <span class="dt">sep=</span><span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>, <span class="dt">quote=</span><span class="st">&quot;&quot;</span>)
<span class="kw">mean</span>(myDF<span class="op">$</span>caffeine_100g, <span class="dt">na.rm=</span>T) <span class="co"># 2.075503</span></code></pre></div>
</div>
<div id="if-you-were-to-try-to-modify-our-loop-from-question-5-to-do-the-same-thing-you-will-run-into-a-myriad-of-issues-just-to-try-and-get-the-mean-of-a-column.-luckily-it-is-easy-to-do-using-pandas" class="section level5">
<h5>If you were to try to modify our loop from question (5) to do the same thing, you will run into a myriad of issues, just to try and get the mean of a column. Luckily, it is easy to do using <code>pandas</code>:</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="im">import</span> pandas <span class="im">as</span> pd
myDF <span class="op">=</span> pd.read_csv(<span class="st">&quot;/class/datamine/data/open_food_facts/openfoodfacts.tsv&quot;</span>, sep<span class="op">=</span><span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>)
myDF[<span class="st">&quot;caffeine_100g&quot;</span>].mean() <span class="co"># 2.0755028571428573</span></code></pre></div>
</div>
<div id="take-a-look-at-some-of-the-methods-you-can-perform-using-pandas-here.-perform-an-interesting-calculation-in-r-and-replicate-your-work-using-pandas.-which-did-you-prefer-python-or-r" class="section level5">
<h5>Take a look at some of the methods you can perform using pandas <a href="https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#computations-descriptive-stats">here</a>. Perform an interesting calculation in R, and replicate your work using <code>pandas</code>. Which did you prefer, Python or R?</h5>
<p><a href="https://mediaspace.itap.purdue.edu/id/1_ybx1iukd">Click here for video</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
R code used to solve the problem.
</li>
<li>
Python code used to solve the problem.
</li>
</ul>
</div>
<hr />
</div>
</div>
</div>
<div id="p02-190" class="section level3">
<h3>Project 2</h3>
<hr />
<p><strong>Motivation:</strong> In Python it is very important to understand some of the data types in a little bit more depth than you would in R. Many of the data types in Python will seem very familiar. A <code>character</code> in R is similar to a <code>str</code> in Python. An <code>integer</code> in R is an <code>int</code> in Python. A <code>numeric</code> in R is similar to a <code>float</code> in Python. A <code>logical</code> in R is similar to a <code>bool</code> in Python. In addition to all of that, there are some very popular classes that packages like <code>numpy</code> and <code>pandas</code> introduces. On the other hand, there are some data types in Python like <code>tuple</code>s, <code>list</code>s, <code>set</code>s, and <code>dict</code>s that diverge from R a little bit more. It is integral to understand some basic concepts before jumping too far into everything.</p>
<p><strong>Context:</strong> This is the second project introducing some basic data types, and demonstrating some familiar control flow concepts, all while digging right into a dataset.</p>
<p><strong>Scope:</strong> tuples, lists, if statements, opening files</p>
<p><strong>Learning objectives:</strong></p>
<div class="bbox">
<ul>
<li>
List the differences between lists &amp; tuples and when to use each.
</li>
<li>
Gain familiarity with string methods, list methods, and tuple methods.
</li>
<li>
Demonstrate the ability to read and write data of various formats using various packages.
</li>
</ul>
</div>
<p>Make sure to read about, and use the template found <a href="projects.html#templates">here</a>, and the important information about projects submissions <a href="projects.html#submissions">here</a>.</p>
<div id="dataset-1" class="section level4">
<h4>Dataset</h4>
<p>The following questions will use the dataset found in Scholar:</p>
<p><code>/class/datamine/data/craigslist/vehicles.csv</code></p>
</div>
<div id="questions-1" class="section level4">
<h4>Questions</h4>
<div id="read-in-the-dataset-classdataminedatacraigslistvehicles.csv-into-a-pandas-dataframe-called-mydf.-pandas-is-an-integral-tool-for-various-data-science-tasks-in-python.-you-can-read-a-quick-intro-here.-we-will-be-slowly-introducing-bits-and-pieces-of-this-package-throughout-the-semester.-similarly-we-will-try-to-introduce-byte-sized-ha-portions-of-plotting-packages-to-slowly-build-up-your-skills." class="section level5">
<h5>1. Read in the dataset <code>/class/datamine/data/craigslist/vehicles.csv</code> into a <code>pandas</code> DataFrame called <code>myDF</code>. <code>pandas</code> is an integral tool for various data science tasks in Python. You can read a quick intro <a href="https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html">here</a>. We will be slowly introducing bits and pieces of this package throughout the semester. Similarly, we will try to introduce byte-sized (ha!) portions of plotting packages to slowly build up your skills.</h5>
</div>
<div id="how-big-is-the-dataset-in-mb-or-gb" class="section level5">
<h5>How big is the dataset (in Mb or Gb)?</h5>
<p><strong>Hint:</strong> Remember to check out a question's <em>relevant topics</em>. We try very hard to link you to content and examples that will get you up and running as <em>quickly</em> as possible.</p>
<p><strong>Relevant topics:</strong> <a href="python.html#p-pandas-read_csv">pandas read_csv</a>, <a href="python.html#p-pathlib-path">get filesize in Python</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
</ul>
</div>
</div>
<div id="in-question-1-we-read-in-our-data-into-a-pandas-dataframe.-use-one-of-the-pandas-dataframe-attributes-to-get-the-number-of-columns-and-rows-of-our-dataset.-how-many-columns-and-rows-are-there-use-f-strings-to-print-a-message-for-example" class="section level5">
<h5>2. In question (1) we read in our data into a <code>pandas</code> DataFrame. Use one of the <code>pandas</code> DataFrame <a href="https://pandas.pydata.org/docs/reference/frame.html#attributes-and-underlying-data">attributes</a> to get the number of columns and rows of our dataset. How many columns and rows are there? Use f-strings to print a message, for example:</h5>
<pre><code>There are 123 columns in the DataFrame!
There are 321 rows in the DataFrame!</code></pre>
</div>
<div id="in-project-1-we-learned-how-to-read-a-csv-file-in-line-by-line-and-print-values.-use-the-csv-package-to-print-just-the-first-row-which-should-contain-the-names-of-the-columns.-repeat-this-process-but-instead-of-using-the-csv-package-use-one-of-the-attributes-from-mydf-to-print-the-column-names." class="section level5">
<h5>In project 1, we learned how to read a csv file in, line-by-line, and print values. Use the <code>csv</code> package to print <em>just</em> the first row, which should contain the names of the columns. Repeat this process, but instead of using the <code>csv</code> package, use one of the attributes from <code>myDF</code> (to print the column names).</h5>
<p><strong>Relevant topics:</strong> <a href="python.html#p-csv-pkg">csv read csv</a>, <a href="python.html#p-pandas-dataframe">pandas DataFrame</a>, <a href="https://realpython.com/python-f-strings/#f-strings-a-new-and-improved-way-to-format-strings-in-python">f-strings</a>, <a href="python.html#p-break">break</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
The output from printing the f-strings.
</li>
<li>
Python code used to solve the problem.
</li>
</ul>
</div>
</div>
<div id="use-the-csv-package-to-get-a-list-called-our_columns-that-contains-the-column-names.-add-a-string-extra-to-the-end-of-our_columns.-print-the-second-value-in-the-list.-without-using-a-loop-print-the-1st-3rd-5th-etc.-values-in-the-list.-state-lat-long-and-now-extra-should-be-the-last-values-in-the-list.-print-them-out-by-accessing-their-negative-index." class="section level5">
<h5>3. Use the <code>csv</code> package to get a <a href="python.html#p-lists-and-tuples">list</a> called <code>our_columns</code> that contains the column names. Add a string, &quot;extra&quot;, to the end of <code>our_columns</code>. Print the second value in the list. Without using a loop, print the 1st, 3rd, 5th, etc. values in the list. &quot;state&quot;, &quot;lat&quot;, &quot;long&quot;, and now &quot;extra&quot; should be the last values in the list. Print them out by accessing their negative index.</h5>
</div>
<div id="extra-doesnt-belong-in-our-list-you-can-easily-remove-this-value-from-our-list-by-doing-the-following" class="section level5">
<h5>&quot;extra&quot; doesn't belong in our list, you can easily remove this value from our list by doing the following:</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">our_columns.pop(<span class="dv">25</span>)

<span class="co"># or even this, as pop removes the last value by default</span>
our_columns.pop()</code></pre></div>
</div>
<div id="the-problem-with-this-solution-is-you-must-know-the-index-of-the-value-youd-like-to-remove.-this-isnt-always-ideal.-instead-use-a-list-method-to-remove-extra-by-value-rather-than-by-index." class="section level5">
<h5>The problem with this solution is you must know the index of the value you'd like to remove. This isn't always ideal. Instead, use a <a href="python.html#p-list-methods">list method</a> to remove &quot;extra&quot; by <em>value</em> rather than by <em>index</em>.</h5>
<p><strong>Relevant topics:</strong> <a href="python.html#p-csv-pkg">csv read csv</a>, <a href="python.html#p-break">break</a>, <a href="python.html#p-list-methods">append</a>, <a href="python.html#p-indexing">indexing</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
The output from running your code.
</li>
</ul>
</div>
</div>
<div id="matplotlib-is-one-of-the-primary-plotting-packages-in-python.-you-are-provided-with-the-following-code" class="section level5">
<h5>4. <code>matplotlib</code> is one of the primary plotting packages in Python. You are provided with the following code:</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">my_values <span class="op">=</span> <span class="bu">tuple</span>(myDF.loc[:, <span class="st">&#39;odometer&#39;</span>].dropna().to_list())</code></pre></div>
</div>
<div id="the-result-is-a-tuple-containing-the-odometer-readings-from-all-of-the-vehicles-in-our-dataset.-create-a-lineplot-of-the-odometer-readings." class="section level5">
<h5>The result is a <em>tuple</em> containing the odometer readings from all of the vehicles in our dataset. Create a lineplot of the odometer readings.</h5>
</div>
<div id="well-that-plot-doesnt-seem-too-informative.-lets-first-sort-the-values-in-our-tuple" class="section level5">
<h5>Well, that plot doesn't seem too informative. Let's first sort the values in our tuple:</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">my_values.sort()</code></pre></div>
</div>
<div id="what-happened-a-tuple-is-immutable.-what-this-means-is-that-once-the-contents-of-a-tuple-are-declared-they-cannot-be-modified.-for-example" class="section level5">
<h5>What happened? A tuple is immutable. What this means is that once the contents of a tuple are declared they cannot be modified. For example:</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co"># This will fail because tuples are immutable</span>
my_values[<span class="dv">0</span>] <span class="op">=</span> <span class="dv">100</span></code></pre></div>
</div>
<div id="you-can-read-a-good-article-about-this-here.-in-addition-here-is-a-great-post-that-gives-you-an-idea-when-using-a-tuple-might-be-a-good-idea.-okay-so-lets-go-back-to-our-problem.-we-know-that-lists-are-mutable-and-therefore-sortable-so-convert-my_values-to-a-list-and-then-sort-and-re-plot." class="section level5">
<h5>You can read a good article about this <a href="http://www.compciv.org/guides/python/fundamentals/tuples-immutable/">here</a>. In addition, <a href="https://stackoverflow.com/questions/1708510/list-vs-tuple-when-to-use-each">here</a> is a great post that gives you an idea when using a tuple might be a good idea. Okay, so let's go back to our problem. We know that lists <em>are</em> mutable (and therefore sortable), so convert <code>my_values</code> to a list and then sort, and re-plot.</h5>
</div>
<div id="it-looks-like-there-are-some-potential-outliers-that-are-making-our-plot-look-a-little-wonky.-for-the-sake-of-seeing-how-the-plot-would-look-use-negative-indexing-to-plot-the-sorted-values-minus-the-last-50-values-the-50-highest-values." class="section level5">
<h5>It looks like there are some (potential) outliers that are making our plot look a little wonky. For the sake of seeing how the plot would look, use negative indexing to plot the sorted values <em>minus</em> the last 50 values (the 50 highest values).</h5>
<p><strong>Hint:</strong> To prevent plotting values on the same plot, close your plot with the <code>close</code> method, for example:</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt
my_values <span class="op">=</span> [<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>]
plt.plot(my_values)
plt.show()
plt.close()</code></pre></div>
<p><strong>Relevant topics:</strong> <a href="python.html#p-list-methods">list methods</a>, <a href="python.html#p-indexing">indexing</a>, <a href="python.html#p-matplotlib">matplotlib</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
The output from running your code.
</li>
</ul>
</div>
</div>
<div id="weve-covered-a-lot-in-this-project-use-what-youve-learned-so-far-to-do-one-or-more-of-the-following-tasks" class="section level5">
<h5>5. We've covered a lot in this project! Use what you've learned so far to do one (or more) of the following tasks:</h5>
</div>
<div id="create-a-cool-graphic-using-matplotlib-that-summarizes-some-data-from-our-dataset." class="section level5">
<h5>- Create a cool graphic using <code>matplotlib</code>, that summarizes some data from our dataset.</h5>
</div>
<div id="use-pandas-and-your-investigative-skills-to-sift-through-the-dataset-and-glean-an-interesting-factoid." class="section level5">
<h5>- Use <code>pandas</code> and your investigative skills to sift through the dataset and glean an interesting factoid.</h5>
</div>
<div id="create-some-commented-coding-examples-that-highlight-the-differences-between-lists-and-tuples.-include-at-least-3-examples." class="section level5">
<h5>- Create some commented coding examples that highlight the differences between lists and tuples. Include at least 3 examples.</h5>
<p><strong>Relevant topics:</strong> <a href="python.html#p-pandas">pandas</a>, <a href="python.html#p-indexing">indexing</a>, <a href="python.html#p-matplotlib">matplotlib</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
The output from running your code.
</li>
</ul>
</div>
<hr />
</div>
</div>
</div>
<div id="p03-190" class="section level3">
<h3>Project 3</h3>
<hr />
<p><strong>Motivation:</strong> <code>dict</code>s or dictionaries, are one of the most useful data structures in Python. You can think about them as a data structure containing <em>key</em>: <em>value</em> pairs. Under the hood, <code>dict</code>s are essentially a data structure called a <em>hash table</em>. <a href="https://en.wikipedia.org/wiki/Hash_table">Hash tables</a> are a data structure with a useful set of properties. Searching, inserting, or removing a piece of data is usually constant, meaning that no matter how big your hash table grows to be, inserting, searching, or deleting a piece of data will <em>usually</em> take about the same amount of time, and in the worse case, increase linearly in time. <code>dict</code>s are used a lot, so it is worthwhile to understand them. Although not used quite as often, another important data type called <code>set</code>s, is also worthwhile learning about.</p>
<p><strong>Context:</strong> This is the third project introducing some basic data types, and demonstrating some familiar control flow concepts, all while digging right into a dataset. Throughout the course we will slowly introduce concepts from <code>pandas</code>, and popular plotting packages.</p>
<p><strong>Scope:</strong> dicts, sets, if/else statements, opening files, tuples, lists</p>
<p><strong>Learning objectives:</strong></p>
<div class="bbox">
<ul>
<li>
Explain what is a <code>dict</code> is and why it is useful.
</li>
<li>
Understand how a <code>set</code> works and when it could be useful.
</li>
<li>
List the differences between lists &amp; tuples and when to use each.
</li>
<li>
Gain familiarity with string methods, list methods, and tuple methods.
</li>
<li>
Gain familiarity with dict methods.
</li>
</ul>
</div>
<p>Make sure to read about, and use the template found <a href="projects.html#templates">here</a>, and the important information about projects submissions <a href="projects.html#submissions">here</a>.</p>
<div id="dataset-2" class="section level4">
<h4>Dataset</h4>
<p>The following questions will use the dataset found in Scholar:</p>
<p><code>/class/datamine/data/craigslist/vehicles.csv</code></p>
</div>
<div id="questions-2" class="section level4">
<h4>Questions</h4>
<div id="in-project-2-we-learned-how-to-read-in-data-using-pandas.-read-in-the-classdataminedatacraigslistvehicles.csv-dataset-into-a-dataframe-called-mydf-using-pandas.-in-r-we-can-get-a-sneak-peek-at-the-data-by-doing-something-like" class="section level5">
<h5>1. In project 2 we learned how to read in data using <code>pandas</code>. Read in the (<code>/class/datamine/data/craigslist/vehicles.csv</code>) dataset into a DataFrame called <code>myDF</code> using <code>pandas</code>. In R we can get a sneak peek at the data by doing something like:</h5>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(myDF) <span class="co"># where myDF is a data.frame</span></code></pre></div>
</div>
<div id="there-is-a-very-similar-and-aptly-named-method-that-allows-us-to-do-the-exact-same-thing-with-a-pandas-dataframe.-get-the-head-of-mydf-and-take-a-moment-to-consider-how-much-time-it-would-take-to-get-this-information-if-we-didnt-have-this-nice-method." class="section level5">
<h5>There is a very similar (and aptly named method) that allows us to do the exact same thing with a <code>pandas</code> DataFrame. Get the <code>head</code> of <code>myDF</code>, and take a moment to consider how much time it would take to get this information if we didn't have this nice method.</h5>
<p><strong>Relevant topics:</strong> <a href="python.html#p-pandas-read_csv">pandas read_csv</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
The <code>head</code> of the dataset.
</li>
</ul>
</div>
</div>
<div id="dictionaries-often-referred-to-as-dicts-are-really-powerful.-there-are-two-primary-ways-to-get-information-from-a-dict.-one-is-to-use-the-get-method-the-other-is-to-use-square-brackets-and-strings.-test-out-the-following-to-understand-the-differences-between-the-two" class="section level5">
<h5>2. Dictionaries, often referred to as dicts, are really powerful. There are two primary ways to &quot;get&quot; information from a dict. One is to use the <code>get</code> method, the other is to use square brackets and strings. Test out the following to understand the differences between the two:</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">my_dict <span class="op">=</span> {<span class="st">&quot;fruits&quot;</span>: [<span class="st">&quot;apple&quot;</span>, <span class="st">&quot;orange&quot;</span>, <span class="st">&quot;pear&quot;</span>], <span class="st">&quot;person&quot;</span>: <span class="st">&quot;John&quot;</span>, <span class="st">&quot;vegetables&quot;</span>: [<span class="st">&quot;carrots&quot;</span>, <span class="st">&quot;peas&quot;</span>]}

<span class="co"># If &quot;person&quot; is indeed a key, they will function the same way</span>
my_dict[<span class="st">&quot;person&quot;</span>]
my_dict.get(<span class="st">&quot;person&quot;</span>)

<span class="co"># If the key does not exist, like below, they will not </span>
<span class="co"># function the same way.</span>
my_dict.get(<span class="st">&quot;height&quot;</span>) <span class="co"># Returns None when key doesn&#39;t exist</span>
my_dict[<span class="st">&quot;height&quot;</span>] <span class="co"># Throws a KeyError exception because the key, &quot;height&quot; doesn&#39;t exist</span></code></pre></div>
</div>
<div id="look-at-the-dataset.-lets-say-that-we-want-to-prepare-a-subset-of-this-data-to-create-a-graphic.-specifically-lets-say-we-want-to-create-a-barplot-that-shows-the-number-of-vehicles-on-craigslist-by-year-of-make.-create-a-dict-called-my_dict-that-contains-keyvalue-pairs-where-the-keys-are-years-and-the-values-are-a-single-int-representing-the-number-of-vehicles-from-that-year-on-craigslist.-use-the-year-column-a-loop-and-a-dict-to-accomplish-this.-print-the-dictionary.-you-can-use-the-following-code-to-extract-the-year-column-as-a-list.-in-the-next-project-we-will-learn-how-to-loop-over-pandas-dataframes." class="section level5">
<h5>Look at the dataset. Let's say that we want to prepare a subset of this data to create a graphic. Specifically, let's say we want to create a barplot that shows the number of vehicles on craigslist by year of make. Create a dict called <code>my_dict</code> that contains key:value pairs where the keys are years, and the values are a single int representing the number of vehicles from that year on craigslist. Use the <code>year</code> column, a loop, and a dict to accomplish this. Print the dictionary. You can use the following code to extract the <code>year</code> column as a list. In the next project we will learn how to loop over <code>pandas</code> DataFrames.</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">years <span class="op">=</span> myDF[<span class="st">&#39;year&#39;</span>].dropna().to_list()</code></pre></div>
<p><strong>Hint:</strong> If you get a <code>KeyError</code>, remember, you must declare each key value pair just like any other variable. Use the following code to initialize each <code>year</code> key to the value 0.</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">years <span class="op">=</span> myDF[<span class="st">&#39;year&#39;</span>].dropna().to_list()

<span class="co"># get a list containing each unique year</span>
unique_years <span class="op">=</span> <span class="bu">list</span>(<span class="bu">set</span>(years))

<span class="co"># for each year (key), initialize the value (value) to 0</span>
my_dict <span class="op">=</span> {}
<span class="cf">for</span> year <span class="kw">in</span> unique_years:
    my_dict[year] <span class="op">=</span> <span class="dv">0</span></code></pre></div>
<p><strong>Hint:</strong> Here are some of the results you should get:</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="bu">print</span>(my_dict[<span class="dv">1912</span>]) <span class="co"># 5</span>
<span class="bu">print</span>(my_dict[<span class="dv">1982</span>]) <span class="co"># 185</span>
<span class="bu">print</span>(my_dict[<span class="dv">2014</span>]) <span class="co"># 31703</span></code></pre></div>
<p><strong>Note:</strong> There is a special kind of dict called a defaultdict, that allows you to give default values to a dict, giving you the ability to &quot;skip&quot; initialization. We will show you this when we release the solutions!</p>
<p><strong>Relevant topics:</strong> <a href="python.html#p-dicts">dicts</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
<code>my_dict</code> printed.
</li>
</ul>
</div>
</div>
<div id="after-completing-question-2-you-can-easily-access-the-number-of-vehicles-from-a-given-year.-for-example-to-get-the-number-of-vehicles-on-craigslist-from-1912-just-run" class="section level5">
<h5>3. After completing question (2) you can easily access the number of vehicles from a given year. For example, to get the number of vehicles on craigslist from 1912, just run:</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">my_dict[<span class="dv">1912</span>]

<span class="co"># or</span>

my_dict.get(<span class="dv">1912</span>)</code></pre></div>
</div>
<div id="dicts-store-data-in-keyvalue-pairs.-identify-a-key-from-my_dict-as-well-as-the-associated-value.-as-you-can-imagine-having-data-in-this-format-can-be-very-beneficial.-one-benefit-is-the-ability-to-easily-create-a-graphic-using-matplotlib.-use-matplotlib-to-create-a-bar-graph-with-the-year-on-the-x-axis-and-the-number-of-vehicles-from-that-year-on-the-y-axis." class="section level5">
<h5><code>dict</code>s store data in key:value pairs. Identify a &quot;key&quot; from <code>my_dict</code>, as well as the associated &quot;value&quot;. As you can imagine, having data in this format can be very beneficial. One benefit is the ability to easily create a graphic using <code>matplotlib</code>. Use <code>matplotlib</code> to create a bar graph with the year on the x-axis, and the number of vehicles from that year on the y-axis.</h5>
<p><strong>Hint:</strong> To use <code>matplotlib</code>, first import it:</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt

<span class="co"># now you can use it, for example</span>
plt.plot([<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">1</span>])
plt.show()</code></pre></div>
<p><strong>Hint:</strong> The <code>keys</code> method and <code>values</code> method from <code>dict</code> could be useful here.</p>
<p><strong>Relevant topics:</strong> <a href="python.html#p-dicts">dicts</a>, <a href="python.html#p-matplotlib">matplotlib</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
The resulting plot.
</li>
<li>
A sentence giving an example of a &quot;key&quot; and associated &quot;value&quot; from <code>my_dict</code>.
</li>
</ul>
</div>
</div>
<div id="in-the-hint-in-question-3-we-used-a-set-to-quickly-get-a-list-of-unique-years-in-a-list.-some-other-common-uses-of-sets-are-when-you-want-to-get-a-list-of-values-that-are-in-one-list-but-not-another-or-get-a-list-of-values-that-are-present-in-both-lists.-examine-the-following-code.-youll-notice-that-we-are-looping-over-many-values.-replace-the-code-with-code-that-uses-no-loops-whatsoever." class="section level5">
<h5>4. In the hint in question (3), we used a <code>set</code> to quickly get a list of unique years in a list. Some other common uses of <code>set</code>s are when you want to get a list of values that are in one list but not another, or get a list of values that are present in both lists. Examine the following code. You'll notice that we are looping over many values. Replace the code with code that uses <em>no</em> loops whatsoever.</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">listA <span class="op">=</span> [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">12</span>, <span class="dv">12</span>]
listB <span class="op">=</span> [<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">7</span>, <span class="dv">7</span>, <span class="dv">7</span>, <span class="dv">2</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">11</span>, <span class="dv">12</span>, <span class="dv">13</span>]

<span class="co"># values in list A but not list B</span>
onlyA <span class="op">=</span> []
<span class="cf">for</span> valA <span class="kw">in</span> listA:
    <span class="cf">if</span> valA <span class="kw">not</span> <span class="kw">in</span> listB <span class="kw">and</span> valA <span class="kw">not</span> <span class="kw">in</span> onlyA:
        onlyA.append(valA)

<span class="bu">print</span>(onlyA) <span class="co"># [3, 4, 5, 6]</span>

<span class="co"># values in listB but not list A</span>
onlyB <span class="op">=</span> []
<span class="cf">for</span> valB <span class="kw">in</span> listB:
    <span class="cf">if</span> valB <span class="kw">not</span> <span class="kw">in</span> listA <span class="kw">and</span> valB <span class="kw">not</span> <span class="kw">in</span> onlyB:
        onlyB.append(valB)

<span class="bu">print</span>(onlyB) <span class="co"># [7, 8, 9, 10, 11, 13]</span>

<span class="co"># values in both lists</span>
in_both_lists <span class="op">=</span> []
<span class="cf">for</span> valA <span class="kw">in</span> listA:
    <span class="cf">if</span> valA <span class="kw">in</span> listB <span class="kw">and</span> valA <span class="kw">not</span> <span class="kw">in</span> in_both_lists:
        in_both_lists.append(valA)

<span class="cf">for</span> valB <span class="kw">in</span> listB:
    <span class="cf">if</span> valB <span class="kw">in</span> listA <span class="kw">and</span> valB <span class="kw">not</span> <span class="kw">in</span> in_both_lists:
        in_both_lists.append(valB)

<span class="bu">print</span>(in_both_lists) <span class="co"># [1,2,12]</span></code></pre></div>
<p><strong>Hint:</strong> You should use <code>set</code>s.</p>
<p><strong>Note:</strong> In addition to being easier to read, <code>set</code>s are <em>much</em> faster than loops!</p>
<p><strong>Relevant topics:</strong> <a href="python.html#p-sets">sets</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
The output from running the code.
</li>
</ul>
</div>
</div>
<div id="the-value-of-a-dictionary-does-not-have-to-be-a-single-value-like-weve-shown-so-far.-it-can-be-anything.-observe-that-there-is-latitude-and-longitude-data-for-each-row-in-our-dataframe-lat-and-long-respectively.-wouldnt-it-be-useful-to-be-able-to-quickly-get-pairs-of-latitude-and-longitude-data-for-a-given-state" class="section level5">
<h5>5. The value of a dictionary does not have to be a single value (like we've shown so far). It can be <em>anything</em>. Observe that there is latitude and longitude data for each row in our DataFrame (<code>lat</code> and <code>long</code>, respectively). Wouldn't it be useful to be able to quickly &quot;get&quot; pairs of latitude and longitude data for a given state?</h5>
</div>
<div id="first-run-the-following-code-to-get-a-list-of-tuples-where-the-first-value-is-the-state-the-second-value-is-the-lat-and-the-third-value-is-the-long." class="section level5">
<h5>First, run the following code to get a list of tuples where the first value is the <code>state</code>, the second value is the <code>lat</code>, and the third value is the <code>long</code>.</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">states_list <span class="op">=</span> <span class="bu">list</span>(myDF.loc[:, [<span class="st">&quot;state&quot;</span>, <span class="st">&quot;lat&quot;</span>, <span class="st">&quot;long&quot;</span>]].dropna().to_records(index<span class="op">=</span><span class="va">False</span>))
states_list[<span class="dv">0</span>:<span class="dv">3</span>] <span class="co"># [(&#39;az&#39;, 34.4554, -114.269), (&#39;or&#39;, 46.1837, -123.824), (&#39;sc&#39;, 34.9352, -81.9654)]</span>

<span class="co"># to get the first tuple</span>
states_list[<span class="dv">0</span>] <span class="co"># (&#39;az&#39;, 34.4554, -114.269)</span>

<span class="co"># to get the first value in the first tuple</span>
states_list[<span class="dv">0</span>][<span class="dv">0</span>] <span class="co"># az</span>

<span class="co"># to get the second tuple</span>
states_list[<span class="dv">1</span>] <span class="co"># (&#39;or&#39;, 46.1837, -123.824)</span>

<span class="co"># to get the first value in the second tuple</span>
states_list[<span class="dv">1</span>][<span class="dv">0</span>] <span class="co"># or</span></code></pre></div>
</div>
<div id="now-organize-the-latitude-and-longitude-data-in-a-dictionary-called-geodict-such-that-each-state-from-the-state-column-is-a-key-and-the-respective-value-is-a-list-of-tuples-where-the-first-value-in-each-tuple-is-the-latitude-lat-and-the-second-value-is-the-longitude-long.-for-example" class="section level5">
<h5>Now, organize the latitude and longitude data in a dictionary called <code>geoDict</code> such that each state from the <code>state</code> column is a key, and the respective value is a list of tuples, where the first value in each tuple is the latitude (<code>lat</code>) and the second value is the longitude (<code>long</code>). For example:</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">geoDict.get(<span class="st">&quot;in&quot;</span>)[<span class="dv">0</span>:<span class="dv">2</span>] <span class="co"># [(39.0295, -86.8675), (38.8585, -86.4806)]</span>
<span class="bu">len</span>(geoDict.get(<span class="st">&quot;in&quot;</span>)) <span class="co"># 5687</span></code></pre></div>
</div>
<div id="now-that-you-can-easily-access-latitude-and-longitude-pairs-for-a-given-state-run-the-following-code-to-plot-the-points-for-texas-state-tx.-include-the-the-graphic-produced-below-in-your-solution-but-feel-free-to-experiment-with-other-states." class="section level5">
<h5>Now that you can easily access latitude and longitude pairs for a given state, run the following code to plot the points for Texas (<code>state</code> == tx). Include the the graphic produced below in your solution, but feel free to experiment with other states.</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="im">from</span> shapely.geometry <span class="im">import</span> Point
<span class="im">import</span> geopandas <span class="im">as</span> gpd
<span class="im">from</span> geopandas <span class="im">import</span> GeoDataFrame

usa <span class="op">=</span> gpd.read_file(<span class="st">&#39;/class/datamine/data/craigslist/cb_2018_us_state_20m.shp&#39;</span>)
usa.crs <span class="op">=</span> {<span class="st">&#39;init&#39;</span>: <span class="st">&#39;epsg:4269&#39;</span>}

pts <span class="op">=</span> [Point(y,x) <span class="cf">for</span> x, y <span class="kw">in</span> geoDict.get(<span class="st">&quot;tx&quot;</span>)]
gdf <span class="op">=</span> gpd.GeoDataFrame(geometry<span class="op">=</span>pts, crs <span class="op">=</span> <span class="dv">4269</span>)
fig, gax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">10</span>))
base <span class="op">=</span> usa[usa[<span class="st">&#39;NAME&#39;</span>].isin([<span class="st">&#39;Hawaii&#39;</span>, <span class="st">&#39;Alaska&#39;</span>, <span class="st">&#39;Puerto Rico&#39;</span>]) <span class="op">==</span> <span class="va">False</span>].plot(ax<span class="op">=</span>gax, color<span class="op">=</span><span class="st">&#39;white&#39;</span>, edgecolor<span class="op">=</span><span class="st">&#39;black&#39;</span>)
gdf.plot(ax<span class="op">=</span>base, color<span class="op">=</span><span class="st">&#39;darkred&#39;</span>, marker<span class="op">=</span><span class="st">&quot;*&quot;</span>, markersize<span class="op">=</span><span class="dv">10</span>)
plt.show()

<span class="co"># to save to jpg:</span>
plt.savefig(<span class="st">&#39;q5.jpg&#39;</span>)</code></pre></div>
<p><strong>Relevant topics:</strong> <a href="python.html#p-dicts">dicts</a>, <a href="python.html#p-lists-and-tuples">lists and tuples</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Graphic produced for the given state.
</li>
</ul>
</div>
</div>
<div id="use-your-new-skills-to-extract-some-sort-of-information-from-our-dataset-and-create-a-graphic.-this-can-be-an-simple-or-complicated-as-you-are-comfortable-with" class="section level5">
<h5>6. Use your new skills to extract some sort of information from our dataset and create a graphic. This can be an simple or complicated as you are comfortable with!</h5>
<p><strong>Relevant topics:</strong> <a href="python.html#p-dicts">dicts</a>, <a href="python.html#p-lists-and-tuples">lists and tuples</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
The graphic produced using the code.
</li>
</ul>
</div>
<hr />
</div>
</div>
</div>
<div id="p04-190" class="section level3">
<h3>Project 4</h3>
<hr />
<p><strong>Motivation:</strong> We've now been introduced to a variety of core Python data structures. Along the way we've touched on a bit of <code>pandas</code>, <code>matplotlib</code>, and have utilized some control flow features like for loops, if statements. We will continue to touch on <code>pandas</code> and <code>matplotlib</code>, but we will take a deeper dive in this project and learn more about control flow, all while digging into the data!</p>
<p><strong>Context:</strong> We just finished a project where we were able to see the power of dictionaries and sets. In this project we will take a step back and make sure we are able to really grasp control flow (if/else statements, loops, etc.) in Python.</p>
<p><strong>Scope:</strong> python, dicts, lists, if/else statements, for loops</p>
<p><strong>Learning objectives:</strong></p>
<div class="bbox">
<ul>
<li>
List the differences between lists &amp; tuples and when to use each.
</li>
<li>
Explain what is a dict and why it is useful.
</li>
<li>
Demonstrate a working knowledge of control flow in python: if/else statements, while loops, for loops, etc.
</li>
</ul>
</div>
<p>Make sure to read about, and use the template found <a href="projects.html#templates">here</a>, and the important information about projects submissions <a href="projects.html#submissions">here</a>.</p>
<div id="dataset-3" class="section level4">
<h4>Dataset</h4>
<p>The following questions will use the dataset found in Scholar:</p>
<p><code>/class/datamine/data/craigslist/vehicles.csv</code></p>
</div>
<div id="questions-3" class="section level4">
<h4>Questions</h4>
<div id="unlike-in-r-where-traditional-loops-are-rare-and-typically-accomplished-via-one-of-the-apply-functions-in-python-loops-are-extremely-common-and-important-to-understand.-in-python-any-iterator-can-be-looped-over.-some-common-iterators-are-tuples-lists-dicts-sets-pandas-series-and-pandas-dataframes.-in-the-previous-project-we-had-some-examples-of-looping-over-lists-lets-learn-how-to-loop-over-pandas-series-and-dataframes" class="section level5">
<h5>1. Unlike in R, where traditional loops are rare and typically accomplished via one of the apply functions, in Python, loops are extremely common and important to understand. In Python, any iterator can be looped over. Some common iterators are: tuples, lists, dicts, sets, <code>pandas</code> Series, and <code>pandas</code> DataFrames. In the previous project we had some examples of looping over lists, let's learn how to loop over <code>pandas</code> Series and Dataframes!</h5>
</div>
<div id="load-up-our-dataset-classdataminedatacraigslistvehicles.csv-into-a-dataframe-called-mydf.-in-project-3-we-organized-the-latitude-and-longitude-data-in-a-dictionary-called-geodict-such-that-each-state-from-the-state-column-is-a-key-and-the-respective-value-is-a-list-of-tuples-where-the-first-value-in-each-tuple-is-the-latitude-lat-and-the-second-value-is-the-longitude-long.-repeat-this-question-but-do-not-use-lists-instead-use-pandas-to-accomplish-this." class="section level5">
<h5>Load up our dataset <code>/class/datamine/data/craigslist/vehicles.csv</code> into a DataFrame called <code>myDF</code>. In project (3), we organized the latitude and longitude data in a dictionary called <code>geoDict</code> such that each state from the <code>state</code> column is a key, and the respective value is a list of tuples, where the first value in each tuple is the latitude (<code>lat</code>) and the second value is the longitude (<code>long</code>). Repeat this question, but <strong>do not</strong> use lists, instead use <code>pandas</code> to accomplish this.</h5>
<p><strong>Relevant topics:</strong></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
</ul>
</div>
</div>
<div id="wow-the-solution-to-question-1-was-slow.-in-general-youll-want-to-avoid-looping-over-large-dataframes.-here-is-a-pretty-good-explanation-of-why-as-well-as-a-good-system-on-what-to-try-when-computing-something.-in-this-case-we-could-have-used-indexing-to-get-latitude-and-longitude-values-for-each-state-and-would-have-no-need-to-build-this-dict." class="section level5">
<h5>2. Wow! The solution to question (1) was <em>slow</em>. In general, you'll want to avoid looping over large DataFrames. <a href="https://stackoverflow.com/questions/16476924/how-to-iterate-over-rows-in-a-dataframe-in-pandas/55557758#55557758">Here</a> is a pretty good explanation of why, as well as a good system on what to try when computing something. In this case, we could have used indexing to get latitude and longitude values for each state, and would have no need to build this dict.</h5>
</div>
<div id="regardless-we-now-have-an-opportunity-to-practice-iterating-over-a-dictionary-list-and-tuple-all-at-once-loop-through-geodict-and-use-f-strings-to-print-the-state-abbreviation.-print-the-first-latitude-and-longitude-pair-as-well-as-every-5000th-latitude-and-longitude-pair-for-each-state.-round-values-to-the-hundreths-place.-for-example-if-the-state-was-pu-and-it-had-12000-latitude-and-longitude-pairs-we-would-print-the-following" class="section level5">
<h5>Regardless, we now have an opportunity to practice iterating over a dictionary, list, <em>and</em> tuple, all at once! Loop through <code>geoDict</code> and use f-strings to print the state abbreviation. Print the first latitude and longitude pair, as well as every 5000th latitude and longitude pair for each state. Round values to the hundreths place. For example, if the state was &quot;pu&quot;, and it had 12000 latitude and longitude pairs, we would print the following:</h5>
<pre><code>pu:
Lat: 41.41, Long: 41.41
Lat: 22.21, Long: 21.21
Lat: 11.11, Long: 10.22</code></pre>
</div>
<div id="in-the-above-example-lat-41.41-long-41.41-would-be-the-first-pair-lat-22.21-long-21.21-would-be-the-5000th-pair-and-lat-11.11-long-10.22-would-be-the-10000th-pair.-make-sure-to-use-f-strings-to-round-the-latitude-and-longitude-values-to-two-decimal-places." class="section level5">
<h5>In the above example, <code>Lat: 41.41, Long: 41.41</code> would be the first pair, <code>Lat: 22.21, Long: 21.21</code> would be the 5000th pair, and <code>Lat: 11.11, Long: 10.22</code> would be the 10000th pair. Make sure to use f-strings to round the latitude and longitude values to two decimal places.</h5>
<p><strong>Hint:</strong> <a href="">Enumerate</a> is a useful function that adds an index to our loop.</p>
<p><strong>Hint:</strong> Using and if statement and the <a href="">modulo operator</a> could be useful.</p>
<p><strong>Note:</strong> Whenever we have a loop <em>within</em> another loop, the &quot;inner&quot; loop is called a &quot;nested&quot; loop, as it is &quot;nested&quot; inside of the other.</p>
<p><strong>Relevant topics:</strong></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
</ul>
</div>
</div>
<div id="we-are-curious-about-how-the-year-of-the-car-year-effects-the-price-price.-in-r-we-could-get-the-median-price-by-year-easily-using-tapply" class="section level5">
<h5>3. We are curious about how the year of the car (<code>year</code>) effects the price (<code>price</code>). In R, we could get the median price by year easily, using <code>tapply</code>:</h5>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tapply</span>(myDF<span class="op">$</span>price, myDF<span class="op">$</span>year, median, <span class="dt">na.rm=</span>T)</code></pre></div>
</div>
<div id="using-pandas-we-would-do-this" class="section level5">
<h5>Using <code>pandas</code>, we would do this:</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">res <span class="op">=</span> myDF.groupby([<span class="st">&#39;year&#39;</span>], dropna<span class="op">=</span><span class="va">True</span>).median()</code></pre></div>
</div>
<div id="these-are-very-convenient-functions-that-do-a-lot-of-work-for-you.-if-we-were-to-take-a-look-at-the-median-price-of-cars-by-year-it-would-look-like" class="section level5">
<h5>These are very convenient functions that do a lot of work for you. If we were to take a look at the median price of cars by year, it would look like:</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt

res <span class="op">=</span> myDF.groupby([<span class="st">&#39;year&#39;</span>], dropna<span class="op">=</span><span class="va">True</span>).median()[<span class="st">&quot;price&quot;</span>]
plt.bar(res.index, res.values)</code></pre></div>
</div>
<div id="using-just-the-pandas-code-provided-below-and-no-other-pandas-code-calculate-the-median-price-by-year.-replicate-the-plot-generated-by-running-the-code-above-using-your-calculated-median-values." class="section level5">
<h5>Using <em>just</em> the <code>pandas</code> code provided below, and no other <code>pandas</code> code, calculate the median <code>price</code> by <code>year</code>. Replicate the plot generated by running the code above, using your calculated median values.</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">my_list <span class="op">=</span> <span class="bu">list</span>(myDF.loc[:, [<span class="st">&quot;year&quot;</span>, <span class="st">&quot;price&quot;</span>,]].dropna().to_records(index<span class="op">=</span><span class="va">False</span>))</code></pre></div>
<p><strong>Relevant topics:</strong></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
<li>
The barplot.
</li>
</ul>
</div>
</div>
<div id="now-calculate-the-mean-price-by-year-and-create-a-barplot-with-the-price-on-the-y-axis-and-year-on-the-x-axis.-whoa-something-is-odd-here.-explain-what-is-happening.-modify-your-code-to-use-an-if-statement-to-weed-out-the-likely-erroneous-value.-re-plot-your-values." class="section level5">
<h5>4. Now, calculate the mean <code>price</code> by <code>year</code>, and create a barplot with the <code>price</code> on the y-axis and <code>year</code> on the x-axis. Whoa! Something is odd here. Explain what is happening. Modify your code to use an if statement to &quot;weed out&quot; the likely erroneous value. Re-plot your values.</h5>
<p><strong>Relevant topics:</strong></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
<li>
The barplot.
</li>
</ul>
</div>
</div>
<div id="list-comprehensions-are-a-neat-feature-of-python-that-allows-for-a-more-concise-syntax-for-smaller-loops.-while-at-first-they-may-seem-difficult-and-more-confusing-eventually-they-grow-on-you.-for-example-say-you-wanted-to-capitalize-every-state-in-a-list-full-of-states" class="section level5">
<h5>5. List comprehensions are a neat feature of Python that allows for a more concise syntax for smaller loops. While at first they may seem difficult and more confusing, eventually they grow on you. For example, say you wanted to capitalize every <code>state</code> in a list full of states:</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">my_states <span class="op">=</span> myDF[<span class="st">&#39;state&#39;</span>].to_list()
my_states <span class="op">=</span> [state.upper() <span class="cf">for</span> state <span class="kw">in</span> my_states]</code></pre></div>
</div>
<div id="or-maybe-you-wanted-to-find-the-average-price-of-cars-in-excellent-condition-without-pandas" class="section level5">
<h5>Or, maybe you wanted to find the average price of cars in &quot;excellent&quot; condition (without <code>pandas</code>):</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">my_list <span class="op">=</span> <span class="bu">list</span>(myDF.loc[:, [<span class="st">&quot;condition&quot;</span>, <span class="st">&quot;price&quot;</span>,]].dropna().to_records(index<span class="op">=</span><span class="va">False</span>))
my_list <span class="op">=</span> [price <span class="cf">for</span> (condition, price) <span class="kw">in</span> my_list <span class="cf">if</span> condition <span class="op">==</span> <span class="st">&quot;excellent&quot;</span>]
<span class="bu">sum</span>(my_list)<span class="op">/</span><span class="bu">len</span>(my_list)</code></pre></div>
</div>
<div id="do-the-following-using-list-comprehensions-and-the-provided-code" class="section level5">
<h5>Do the following using list comprehensions, and the provided code:</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">my_list <span class="op">=</span> <span class="bu">list</span>(myDF.loc[:, [<span class="st">&quot;state&quot;</span>, <span class="st">&quot;price&quot;</span>,]].dropna().to_records(index<span class="op">=</span><span class="va">False</span>))</code></pre></div>
<ul>
<li>Calculate the average price of vehicles from Indiana (<code>in</code>).</li>
<li>Calculate the average price of vehicles from Indiana (<code>in</code>), Michigan (<code>mi</code>), and Illinois (<code>il</code>) combined.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">my_list <span class="op">=</span> <span class="bu">list</span>(myDF.loc[:, [<span class="st">&quot;manufacturer&quot;</span>, <span class="st">&quot;year&quot;</span>, <span class="st">&quot;price&quot;</span>,]].dropna().to_records(index<span class="op">=</span><span class="va">False</span>))</code></pre></div>
<ul>
<li>Calculate the average price of a &quot;honda&quot; (<code>manufacturer</code>) that is 2010 or newer (<code>year</code>).</li>
</ul>
<p><strong>Relevant topics:</strong></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
</ul>
</div>
</div>
<div id="lets-use-a-package-called-spacy-to-try-and-parse-phone-numbers-out-of-the-description-column.-first-simply-loop-through-and-print-the-text-and-the-label.-what-is-the-label-of-the-majority-of-the-phone-numbers-you-can-see" class="section level5">
<h5>6. Let's use a package called <code>spacy</code> to try and parse phone numbers out of the <code>description</code> column. First, simply loop through and print the text and the label. What is the label of the majority of the phone numbers you can see?</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="im">import</span> spacy

<span class="co"># get list of descriptions</span>
my_list <span class="op">=</span> <span class="bu">list</span>(myDF.loc[:, [<span class="st">&quot;description&quot;</span>,]].dropna().to_records(index<span class="op">=</span><span class="va">False</span>))
my_list <span class="op">=</span> [m[<span class="dv">0</span>] <span class="cf">for</span> m <span class="kw">in</span> my_list]

<span class="co"># load the pre-built spacy model</span>
nlp <span class="op">=</span> spacy.load(<span class="st">&quot;en_core_web_lg&quot;</span>)

<span class="co"># apply the model to a description</span>
doc <span class="op">=</span> nlp(my_list[<span class="dv">0</span>])

<span class="co"># print the text and label of each &quot;entity&quot;</span>
<span class="cf">for</span> entity <span class="kw">in</span> doc.ents:
    <span class="bu">print</span>(entity.text, entity.label_)</code></pre></div>
</div>
<div id="use-an-if-statement-to-filter-out-all-entities-that-are-not-the-label-you-see.-loop-through-again-and-see-what-our-printed-data-looks-like.-there-is-still-a-lot-of-data-there-that-we-dont-want-to-capture-right-phone-numbers-in-the-us-are-usually-7-5555555-8-555-5555-10-5555555555-11-15555555555-12-555-555-5555-or-14-1-555-555-5555-digits.-in-addition-to-your-first-filter-add-another-filter-that-keeps-only-text-where-the-text-is-one-of-those-lengths." class="section level5">
<h5>Use an if statement to filter out all entities that are not the label you see. Loop through again and see what our printed data looks like. There is still a lot of data there that we <em>don't</em> want to capture, right? Phone numbers in the US are <em>usually</em> 7 (5555555), 8 (555-5555), 10 (5555555555), 11 (15555555555), 12 (555-555-5555), or 14 (1-555-555-5555) digits. In addition to your first &quot;filter&quot;, add another &quot;filter&quot; that keeps only text where the text is one of those lengths.</h5>
</div>
<div id="that-is-starting-to-look-better-but-there-are-still-some-erroneous-values.-come-up-with-another-filter-and-loop-through-our-data-again.-explain-what-your-filter-does-and-make-sure-that-it-does-a-better-job-on-the-first-10-documents-than-when-we-dont-use-your-filter." class="section level5">
<h5>That is starting to look better, but there are still some erroneous values. Come up with another &quot;filter&quot;, and loop through our data again. Explain what your filter does and make sure that it does a better job on the first 10 documents than when we don't use your filter.</h5>
<p><strong>Note:</strong> It can be fun to utilize machine learning and natural language processing, but that doesn't mean it is always the best solution! We could get rid of all of our filters and use regular expressions with much better results! We will demonstrate this in our solution.</p>
<p><strong>Relevant topics:</strong></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
<li>
1-2 sentences explaining what your filter does.
</li>
</ul>
</div>
<hr />
</div>
</div>
</div>
<div id="p05-190" class="section level3">
<h3>Project 5</h3>
<hr />
<p><strong>Motivation:</strong> Up until this point we've utilized bits and pieces of the <code>pandas</code> library to perform various tasks. In this project we will formally introduce <code>pandas</code> and <code>numpy</code>, and utilize their capabilities to solve data-driven problems.</p>
<p><strong>Context:</strong> By now you'll have had some limited exposure to <code>pandas</code>. This is the first in a three project series that covers some of the main components of both the <code>numpy</code> and <code>pandas</code> libraries. We will take a two project intermission to learn about functions, and then continue.</p>
<p><strong>Scope:</strong> python, pandas, numpy, DataFrames, Series, ndarrays, indexing</p>
<p><strong>Learning objectives:</strong></p>
<div class="bbox">
<ul>
<li>
Distinguish the differences between numpy, pandas, DataFrames, Series, and ndarrays.
</li>
<li>
Use numpy, scipy, and pandas to solve a variety of data-driven problems.
</li>
<li>
Demonstrate the ability to read and write data of various formats using various packages.
</li>
<li>
View and access data inside DataFrames, Series, and ndarrays.
</li>
</ul>
</div>
<p>Make sure to read about, and use the template found <a href="projects.html#templates">here</a>, and the important information about projects submissions <a href="projects.html#submissions">here</a>.</p>
<div id="dataset-4" class="section level4">
<h4>Dataset</h4>
<p>The following questions will use the dataset found in Scholar:</p>
<p><code>/class/datamine/data/stackoverflow/unprocessed/2018.csv</code></p>
</div>
<div id="questions-4" class="section level4">
<h4>Questions</h4>
<div id="take-a-look-at-the-pandas-docs.-there-are-a-lot-of-formats-that-pandas-has-the-ability-to-read.-the-most-popular-formats-in-this-course-are-csv-with-commas-or-some-other-separator-excel-json-or-some-database.-csv-is-very-prevalent-but-it-was-not-designed-to-work-well-with-large-amounts-of-data.-newer-formats-like-parquet-and-feather-are-designed-from-the-ground-up-to-be-efficient-and-take-advantage-of-special-processor-instruction-set-called-simd.-the-benefits-of-using-these-formats-can-be-significant.-lets-do-some-experiments" class="section level5">
<h5>1. Take a look at the <a href="https://pandas.pydata.org/docs/reference/io.html"><code>pandas</code> docs</a>. There are a <em>lot</em> of formats that <code>pandas</code> has the ability to read. The most popular formats in this course are: csv (with commas or some other separator), excel, json, or some database. CSV is very prevalent, but it was not designed to work well with large amounts of data. Newer formats like parquet and feather are designed from the ground up to be efficient, and take advantage of special processor instruction set called SIMD. The benefits of using these formats can be significant. Let's do some experiments!</h5>
</div>
<div id="how-much-space-do-each-of-the-following-files-take-up-on-scholar-2018.csv-2018.parquet-and-2018.feather-how-much-smaller-as-a-percentage-is-the-parquet-file-than-the-csv-how-much-smaller-as-a-percentage-is-the-feather-file-than-the-csv-use-f-strings-to-format-the-percentages." class="section level5">
<h5>How much space do each of the following files take up on Scholar: <code>2018.csv</code>, <code>2018.parquet</code>, and <code>2018.feather</code>? How much smaller (as a percentage) is the parquet file than the csv? How much smaller (as a percentage) is the feather file than the csv? Use f-strings to format the percentages.</h5>
</div>
<div id="time-reading-in-the-following-files-2018.csv-2018.parquet-and-2018.feather.-how-much-faster-as-a-percentage-is-reading-the-parquet-file-than-the-csv-how-much-faster-as-a-percentage-is-reading-the-feather-file-than-the-csv-use-f-strings-to-format-the-percentages." class="section level5">
<h5>Time reading in the following files: <code>2018.csv</code>, <code>2018.parquet</code>, and <code>2018.feather</code>. How much faster (as a percentage) is reading the parquet file than the csv? How much faster (as a percentage) is reading the feather file than the csv? Use f-strings to format the percentages.</h5>
</div>
<div id="to-time-a-piece-of-code-you-can-use-the-block-timer-package" class="section level5">
<h5>To time a piece of code, you can use the <code>block-timer</code> package:</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="im">from</span> block_timer.timer <span class="im">import</span> Timer

<span class="cf">with</span> Timer(title<span class="op">=</span><span class="st">&quot;Using dict to declare a dict&quot;</span>) <span class="im">as</span> t1:
    my_dict <span class="op">=</span> <span class="bu">dict</span>()

<span class="cf">with</span> Timer(title<span class="op">=</span><span class="st">&quot;Using </span><span class="sc">{}</span><span class="st"> to declare a dict&quot;</span>) <span class="im">as</span> t2:
    my_dict <span class="op">=</span> {}

<span class="co"># or if you need more fine-tuned values</span>
<span class="bu">print</span>(t1.elapsed)
<span class="bu">print</span>(t2.elapsed)</code></pre></div>
</div>
<div id="read-the-2018.csv-file-into-a-pandas-dataframe-called-my2018.-time-writing-the-contents-of-my2018-to-the-following-files-2018.csv-2018.parquet-and-2018.feather.-write-the-files-to-your-scratch-directory-scratchscholarusername-where-username-is-your-username.-how-much-faster-as-a-percentage-is-reading-the-parquet-file-than-the-csv-how-much-faster-as-a-percentage-is-reading-the-feather-file-than-the-csv-use-f-strings-to-format-the-percentages." class="section level5">
<h5>Read the <code>2018.csv</code> file into a <code>pandas</code> DataFrame called <code>my2018</code>. Time writing the contents of <code>my2018</code> to the following files: <code>2018.csv</code>, <code>2018.parquet</code>, and <code>2018.feather</code>. Write the files to your scratch directory: <code>/scratch/scholar/&lt;username&gt;</code>, where <code>&lt;username&gt;</code> is your username. How much faster (as a percentage) is reading the parquet file than the csv? How much faster (as a percentage) is reading the feather file than the csv? Use f-strings to format the percentages.</h5>
<p><strong>Relevant topics:</strong></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
</ul>
</div>
</div>
<div id="a-method-is-just-a-function-associated-with-an-object-or-class.-for-example-mean-is-just-a-method-of-the-pandas-dataframe" class="section level5">
<h5>2. A <em>method</em> is just a function associated with an object or class. For example, <code>mean</code> is just a method of the <code>pandas</code> DataFrame:</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co"># myDF is an object of class DataFrame</span>
<span class="co"># mean is a method of the DataFrame class</span>
myDF.mean()</code></pre></div>
<pre><code>## Series([], dtype: float64)</code></pre>
</div>
<div id="in-pandas-there-are-two-main-methods-used-for-indexing-loc-and-iloc.-use-the-column-student-and-indexing-in-pandas-to-calculate-what-percentage-of-respondents-are-students-and-not-students.-consider-the-respondent-to-be-a-student-if-the-student-column-is-anything-but-no.-create-a-new-dataframe-called-not_students-that-is-a-subset-of-the-original-dataset-without-students." class="section level5">
<h5>In <code>pandas</code> there are two main methods used for indexing: <a href="https://pandas.pydata.org/docs/user_guide/indexing.html#different-choices-for-indexing"><code>loc</code> and <code>iloc</code></a>. Use the column <code>Student</code> and indexing in <code>pandas</code> to calculate what percentage of respondents are students and not students. Consider the respondent to be a student if the <code>Student</code> column is anything but &quot;No&quot;. Create a new DataFrame called <code>not_students</code> that is a subset of the original dataset <em>without</em> students.</h5>
<p><strong>Relevant topics:</strong></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
</ul>
</div>
</div>
<div id="in-pandas-if-you-were-to-isolate-a-single-column-using-indexing-like-this" class="section level5">
<h5>3. In <code>pandas</code>, if you were to isolate a single column using indexing, like this:</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">myDF.loc[:, <span class="st">&quot;Student&quot;</span>]</code></pre></div>
</div>
<div id="the-result-would-be-a-pandas-series.-a-series-is-the-1-dimensional-equivalent-of-a-dataframe." class="section level5">
<h5>The result would be a <code>pandas</code> Series. A Series is the 1-dimensional equivalent of a DataFrame.</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="bu">type</span>(myDF.loc[:, <span class="st">&quot;Student&quot;</span>]) <span class="co"># pandas.core.series.Series</span></code></pre></div>
</div>
<div id="pandas-and-numpy-make-it-very-easy-to-convert-between-a-series-ndarray-and-list.-here-is-a-very-useful-graphic-to-highlight-how-to-do-this.-look-at-the-devtype-column-in-not_students.-as-you-can-see-a-single-value-may-contain-a-list-of-semi-colon-separated-professions.-create-a-list-with-a-unique-group-of-all-the-possible-professions.-consider-each-semi-colon-separated-value-a-profession.-how-many-professions-are-there" class="section level5">
<h5><code>pandas</code> and <code>numpy</code> make it very easy to convert between a Series, ndarray, and list. <a href="https://miro.medium.com/max/1400/1*rv1JADavAhDKN4-3iM7phQ.png">Here</a> is a very useful graphic to highlight how to do this. Look at the <code>DevType</code> column in <code>not_students</code>. As you can see, a single value may contain a list of semi-colon-separated professions. Create a list with a unique group of all the possible professions. Consider each semi-colon-separated value a profession. How many professions are there?</h5>
</div>
<div id="it-looks-like-somehow-the-profession-student-got-in-there-even-though-we-filtered-by-the-student-column.-use-mydf-to-get-a-subset-of-our-data-for-which-the-respondents-replied-no-to-student-yet-put-student-as-a-devtype.-how-many-respondents-are-in-that-subset" class="section level5">
<h5>It looks like somehow the profession &quot;Student&quot; got in there even though we filtered by the <code>Student</code> column. Use <code>myDF</code> to get a subset of our data for which the respondents replied &quot;No&quot; to <code>Student</code>, yet put &quot;Student&quot; as a <code>DevType</code>. How many respondents are in that subset?</h5>
<p><strong>Hint:</strong> See <a href="https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#boolean-indexing">here</a>.</p>
<p><strong>Relevant topics:</strong></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
<li>
The number of professions there are.
</li>
<li>
The number of respondents that replied &quot;No&quot; to <code>Student</code>, yet put &quot;Student&quot; as the <code>DevType</code>.
</li>
</ul>
</div>
</div>
<div id="as-you-can-see-while-perhaps-a-bit-more-strict-indexing-in-pandas-is-not-that-much-more-difficult-than-indexing-in-r.-while-not-always-necessary-remembering-to-put-to-indicate-all-columns-or-all-rows-makes-life-easier.-in-addition-remembering-to-put-parentheses-around-logical-groupings-is-also-a-good-thing.-practice-makes-perfect-randomly-select-100-males-and-100-females.-how-many-of-each-sample-is-in-each-age-category-do-not-use-the-sample-method-yet-but-instead-use-numeric-indexing-and-random" class="section level5">
<h5>4. As you can see, while perhaps a bit more strict, indexing in <code>pandas</code> is not that much more difficult than indexing in R. While not always necessary, remembering to put &quot;:&quot; to indicate &quot;all columns&quot; or &quot;all rows&quot; makes life easier. In addition, remembering to put parentheses around logical groupings is also a good thing. Practice makes perfect! Randomly select 100 males and 100 females. How many of each sample is in each <code>Age</code> category? (<em>Do not</em> use the <code>sample</code> method yet, but instead use numeric indexing and <code>random</code>)</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="im">import</span> random

<span class="bu">print</span>(<span class="ss">f&quot;A random integer between 1 and 100 is </span><span class="sc">{</span>random<span class="sc">.</span>randint(<span class="dv">1</span>, <span class="dv">101</span>)<span class="sc">}</span><span class="ss">&quot;</span>)</code></pre></div>
<pre><code>## A random integer between 1 and 100 is 47</code></pre>
</div>
<div id="it-would-be-nice-to-visualize-these-results.-pandas-series-have-some-built-in-methods-to-create-plots.-use-this-method-to-generate-a-bar-plot-for-both-males-and-females.-how-do-they-compare" class="section level5">
<h5>It would be nice to visualize these results. <code>pandas</code> Series have some built in methods to create plots. Use [this] method to generate a bar plot for both males and females. How do they compare?</h5>
<p><strong>Hint:</strong> You may need to import <code>matplotlib</code> in order to display the graphic:</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt 

<span class="co"># female barplot code here</span>
plt.show()

<span class="co"># male barplot code here</span>
plt.show()</code></pre></div>
<p><strong>Hint:</strong> Once you have your male and female DataFrames, the <code>value_counts</code> method found <a href="https://pandas.pydata.org/docs/reference/series.html#computations-descriptive-stats">here</a> may be particularly useful.</p>
<p><strong>Relevant topics:</strong></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
</ul>
</div>
</div>
<div id="pandas-really-helps-out-when-it-comes-to-working-with-data-in-python.-this-is-really-cool-dataset-use-your-newfound-skills-to-do-a-mini-analysis.-your-mini-analysis-should-include-1-or-more-graphics-along-with-some-interesting-observation-you-made-while-exploring-the-data." class="section level5">
<h5>5. <code>pandas</code> really helps out when it comes to working with data in Python. This is really cool dataset, use your newfound skills to do a mini-analysis. Your mini-analysis should include 1 or more graphics, along with some interesting observation you made while exploring the data.</h5>
<p><strong>Relevant topics:</strong></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
<li>
A graphic.
</li>
<li>
1-2 sentences explaining your interesting observation and graphic.
</li>
</ul>
</div>
<hr />
</div>
</div>
</div>
</div>
<div id="stat-29000" class="section level2">
<h2>STAT 29000</h2>
<div id="p01-290" class="section level3">
<h3>Project 1</h3>
<hr />
<p><strong>Motivation:</strong> Extensible Markup Language or XML is a very important file format for storing structured data. Even though formats like JSON, and csv tend to be more prevalent, many, many legacy systems still use XML, and it remains an appropriate format for storing complex data. In fact, JSON and csv are quickly becoming less relevant as new formats and serialization methods like <a href="https://arrow.apache.org/faq/">parquet</a> and <a href="https://developers.google.com/protocol-buffers">protobufs</a> are becoming more common.</p>
<p><strong>Context:</strong> In previous semesters we've explored XML. In this project we will refresh our skills and, rather than exploring XML in R, we will use the <code>lxml</code> package in Python. This is the first project in a series of 5 projects focused on web scraping in R and Python.</p>
<p><strong>Scope:</strong> python, XML</p>
<p><strong>Learning objectives:</strong></p>
<div class="bbox">
<ul>
<li>
Review and summarize the differences between XML and HTML/CSV.
</li>
<li>
Match XML terms to sections of XML demonstrating working knowledge.
</li>
</ul>
</div>
<p>Make sure to read about, and use the template found <a href="projects.html#templates">here</a>, and the important information about projects submissions <a href="projects.html#submissions">here</a>.</p>
<div id="dataset-5" class="section level4">
<h4>Dataset</h4>
<p>The following questions will use the dataset found in Scholar:</p>
<p><code>/class/datamine/data/apple/health/watch_dump.xml</code></p>
</div>
<div id="resources" class="section level4">
<h4>Resources</h4>
<p>We realize that for many of you this is a big &quot;jump&quot; right into Python. Don't worry! Python is a very intuitive language with a clean syntax. It is easy to read and write. We will do our very best to keep things as straightforward as possible, especially in the early learning stages of the class.</p>
<p>We will be actively updating the examples book with videos and more examples throughout the semester. Ask a question in Piazza and perhaps we will add an example straight to the book to help out.</p>
<p>Some potentially useful resources for the semester include:</p>
<ul>
<li>The STAT 19000 projects. We are easing 19000 students into Python and will post solutions each week. It would be well worth 10 minutes to look over the questions and solutions each week.</li>
<li><a href="https://towardsdatascience.com/cheat-sheet-for-python-dataframe-r-dataframe-syntax-conversions-450f656b44ca">Here</a> is a decent cheat sheet that helps you quickly get an idea of how to do something you know how to do in R, in Python.</li>
<li><a href="https://thedatamine.github.io/the-examples-book/">The Examples Book</a> -- updating daily with more examples and videos. Be sure to click on the &quot;relevant topics&quot; links as we try to point you to topics with examples that should be particularly useful to solve the problems we assign.</li>
</ul>
</div>
<div id="questions-5" class="section level4">
<h4>Questions</h4>
<p><strong>Important note:</strong> It would be well worth your time to read through the <a href="data-formats.html#xml">xml section</a> of the book, as well as take the time to work through <a href="https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html">pandas 10 minute intro</a>.</p>
<div id="a-good-first-step-when-working-with-xml-is-to-get-an-idea-how-your-document-is-structured.-normally-there-should-be-good-documentation-that-spells-this-out-for-you-but-it-is-good-to-know-what-to-do-when-you-dont-have-the-documentation.-start-by-finding-the-root-node.-what-is-the-name-of-the-root-node-of-the-provided-dataset" class="section level5">
<h5>1. A good first step when working with XML is to get an idea how your document is structured. Normally, there should be good documentation that spells this out for you, but it is good to know what to do when you <em>don't</em> have the documentation. Start by finding the &quot;root&quot; node. What is the name of the root node of the provided dataset?</h5>
<p><strong>Hint:</strong> Make sure to import the <code>lxml</code> package first:</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="im">from</span> lxml <span class="im">import</span> etree</code></pre></div>
<p><strong>Relevant topics:</strong> <a href="python.html#p-lxml">lxml</a>, <a href="data-formats.html#xml">xml</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
</ul>
</div>
</div>
<div id="remember-xml-can-be-nested.-in-question-1-we-figured-out-what-the-root-node-was-called.-what-are-the-names-of-the-next-tier-of-elements" class="section level5">
<h5>2. Remember, XML can be nested. In question (1) we figured out what the root node was called. What are the names of the next &quot;tier&quot; of elements?</h5>
<p><strong>Hint:</strong> Now that we know the root node, you could use the root node name as a part of your xpath expression.</p>
<p><strong>Hint:</strong> As you may have noticed in question (1) the <code>xpath</code> method returns a list. Sometimes this list can contain many repeated tag names. Since our goal is to see the names of the second &quot;tier&quot; elements, you could convert the resulting <code>list</code> to a <code>set</code> to quickly see the unique list as <code>set</code>'s only contain unique values.</p>
<p><strong>Relevant topics:</strong> <a href="python.html#p-for-loops">for loops</a>, <a href="python.html#p-lxml">lxml</a>, <a href="data-formats.html#xml">xml</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
</ul>
</div>
</div>
<div id="continue-to-explore-each-tier-of-data-until-there-isnt-any-left.-name-the-full-paths-of-all-of-the-last-tier-tags." class="section level5">
<h5>3. Continue to explore each &quot;tier&quot; of data until there isn't any left. Name the &quot;full paths&quot; of all of the &quot;last tier&quot; tags.</h5>
<p><strong>Hint:</strong> Let's say a &quot;last tier&quot; tag is just a path where there are no more nested elements. For example, <code>/HealthData/Workout/WorkoutRoute/FileReference</code> is a &quot;last tier&quot; tag. If you try and get the nested elements for it, they don't exist:</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">tree.xpath(<span class="st">&quot;/HealthData/Workout/WorkoutRoute/FileReference/*&quot;</span>)</code></pre></div>
<p><strong>Hint:</strong> Here are 3 of the 7 &quot;full paths&quot;:</p>
<pre><code>/HealthData/Workout/WorkoutRoute/FileReference
/HealthData/Record/MetadataEntry
/HealthData/ActivitySummary</code></pre>
<p><strong>Relevant topics:</strong> <a href="python.html#p-lxml">lxml</a>, <a href="data-formats.html#xml">xml</a>, <a href="python.html#p-for-loops">for loops</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
</ul>
</div>
</div>
<div id="at-this-point-in-time-you-may-be-asking-yourself-but-where-is-the-data-depending-on-the-structure-of-the-xml-file-the-data-could-either-be-between-tags-like" class="section level5">
<h5>4. At this point in time you may be asking yourself &quot;but where is the data&quot;? Depending on the structure of the XML file, the data could either be between tags like:</h5>
<div class="sourceCode"><pre class="sourceCode html"><code class="sourceCode html"><span class="kw">&lt;some_tag&gt;</span>mydata<span class="kw">&lt;/some_tag&gt;</span></code></pre></div>
</div>
<div id="or-it-could-be-in-an-attribute" class="section level5">
<h5>Or, it could be in an attribute:</h5>
<div class="sourceCode"><pre class="sourceCode html"><code class="sourceCode html"><span class="kw">&lt;question</span><span class="ot"> answer=</span><span class="st">&quot;tac&quot;</span><span class="kw">&gt;</span>What is cat spelled backwards?<span class="kw">&lt;/question&gt;</span></code></pre></div>
</div>
<div id="collect-the-activitysummary-data-and-convert-the-list-of-dicts-to-a-pandas-dataframe.-the-following-is-an-example-of-converting-a-list-of-dicts-to-a-pandas-dataframe-called-mydf" class="section level5">
<h5>Collect the &quot;ActivitySummary&quot; data, and convert the list of dicts to a <code>pandas</code> DataFrame. The following is an example of converting a list of dicts to a <code>pandas</code> DataFrame called <code>myDF</code>:</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="im">import</span> pandas <span class="im">as</span> pd

list_of_dicts <span class="op">=</span> []
list_of_dicts.append({<span class="st">&#39;columnA&#39;</span>: <span class="dv">1</span>, <span class="st">&#39;columnB&#39;</span>: <span class="dv">2</span>})
list_of_dicts.append({<span class="st">&#39;columnB&#39;</span>: <span class="dv">4</span>, <span class="st">&#39;columnA&#39;</span>: <span class="dv">1</span>}) 

myDF <span class="op">=</span> pd.DataFrame(list_of_dicts)</code></pre></div>
<p><strong>Hint:</strong> It is important to note that an element's &quot;attrib&quot; attribute looks and feels like a <code>dict</code>, but it is actually a <code>lxml.etree._Attrib</code>. If you try to convert a list of <code>lxml.etree._Attrib</code> to a <code>pandas</code> DataFrame, it will not work out as you planned. Make sure to first convert each <code>lxml.etree._Attrib</code> to a <code>dict</code> before converting to a DataFrame. You can do so like:</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co"># this will convert a single `lxml.etree._Attrib` to a dict</span>
my_dict <span class="op">=</span> <span class="bu">dict</span>(my_lxml_etree_attrib)</code></pre></div>
<p><strong>Relevant topics:</strong> <a href="python.html#p-dicts">dicts</a>, <a href="#p-lists">lists</a>, <a href="python.html#p-lxml">lxml</a>, <a href="data-formats.html#xml">xml</a>, <a href="python.html#p-for-loops">for loops</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
</ul>
</div>
</div>
<div id="pandas-is-a-python-package-that-provides-the-dataframe-and-series-classes.-a-dataframe-is-very-similar-to-a-data.frame-in-r-and-can-be-used-to-manipulate-the-data-within-very-easily.-a-series-is-the-class-that-handles-a-single-column-of-a-dataframe.-go-through-the-pandas-in-10-minutes-page-from-the-official-documentation.-sort-find-and-print-the-top-5-rows-of-data-based-on-the-activeenergyburned-column." class="section level5">
<h5>5. <code>pandas</code> is a Python package that provides the DataFrame and Series classes. A DataFrame is very similar to a data.frame in R and can be used to manipulate the data within very easily. A Series is the class that handles a single column of a DataFrame. Go through the <a href="https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html">pandas in 10 minutes</a> page from the official documentation. Sort, find, and print the top 5 rows of data based on the &quot;activeEnergyBurned&quot; column.</h5>
<p><strong>Relevant topics:</strong> <a href="python.html#p-pandas">pandas</a>, <a href="python.html#p-dicts">dicts</a>, <a href="#p-lists">lists</a>, <a href="python.html#p-lxml">lxml</a>, <a href="data-formats.html#xml">xml</a>, <a href="python.html#p-for-loops">for loops</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
</ul>
</div>
<hr />
</div>
</div>
</div>
</div>
<div id="stat-39000" class="section level2">
<h2>STAT 39000</h2>
<div id="p01-390" class="section level3">
<h3>Project 1</h3>
<hr />
<p><strong>Motivation:</strong> Extensible Markup Language or XML is a very important file format for storing structured data. Even though formats like JSON, and csv tend to be more prevalent, many, many legacy systems still use XML, and it remains an appropriate format for storing complex data. In fact, JSON and csv are quickly becoming less relevant as new formats and serialization methods like <a href="https://arrow.apache.org/faq/">parquet</a> and <a href="https://developers.google.com/protocol-buffers">protobufs</a> are becoming more common.</p>
<p><strong>Context:</strong> In previous semesters we've explored XML. In this project we will refresh our skills and, rather than exploring XML in R, we will use the <code>lxml</code> package in Python. This is the first project in a series of 5 projects focused on web scraping in R and Python.</p>
<p><strong>Scope:</strong> python, XML</p>
<p><strong>Learning objectives:</strong></p>
<div class="bbox">
<ul>
<li>
Review and summarize the differences between XML and HTML/CSV.
</li>
<li>
Match XML terms to sections of XML demonstrating working knowledge.
</li>
</ul>
</div>
<p>Make sure to read about, and use the template found <a href="projects.html#templates">here</a>, and the important information about projects submissions <a href="projects.html#submissions">here</a>.</p>
<div id="dataset-6" class="section level4">
<h4>Dataset</h4>
<p>The following questions will use the dataset found in Scholar:</p>
<p><code>/class/datamine/data/apple/health/watch_dump.xml</code></p>
</div>
<div id="resources-1" class="section level4">
<h4>Resources</h4>
<p>We realize that it may be a while since you've used Python. That's okay! We are going to be taking things at a much more reasonable pace than Spring 2020.</p>
<p>Some potentially useful resources for the semester include:</p>
<ul>
<li>The STAT 19000 projects. We are easing 19000 students into Python and will post solutions each week. It would be well worth 10 minutes to look over the questions and solutions each week.</li>
<li><a href="https://towardsdatascience.com/cheat-sheet-for-python-dataframe-r-dataframe-syntax-conversions-450f656b44ca">Here</a> is a decent cheat sheet that helps you quickly get an idea of how to do something you know how to do in R, in Python.</li>
<li><a href="https://thedatamine.github.io/the-examples-book/">The Examples Book</a> -- updating daily with more examples and videos. Be sure to click on the &quot;relevant topics&quot; links as we try to point you to topics with examples that should be particularly useful to solve the problems we assign.</li>
</ul>
</div>
<div id="questions-6" class="section level4">
<h4>Questions</h4>
<p><strong>Important note:</strong> It would be well worth your time to read through the <a href="data-formats.html#xml">xml section</a> of the book, as well as take the time to work through <a href="https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html">pandas 10 minute intro</a>.</p>
<div id="a-good-first-step-when-working-with-xml-is-to-get-an-idea-how-your-document-is-structured.-normally-there-should-be-good-documentation-that-spells-this-out-for-you-but-it-is-good-to-know-what-to-do-when-you-dont-have-the-documentation.-start-by-finding-the-root-node.-what-is-the-name-of-the-root-node-of-the-provided-dataset-1" class="section level5">
<h5>1. A good first step when working with XML is to get an idea how your document is structured. Normally, there should be good documentation that spells this out for you, but it is good to know what to do when you <em>don't</em> have the documentation. Start by finding the &quot;root&quot; node. What is the name of the root node of the provided dataset?</h5>
<p><strong>Hint:</strong> Make sure to import the <code>lxml</code> package first:</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="im">from</span> lxml <span class="im">import</span> etree</code></pre></div>
<p><strong>Relevant topics:</strong> <a href="python.html#p-lxml">lxml</a>, <a href="data-formats.html#xml">xml</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
</ul>
</div>
</div>
<div id="remember-xml-can-be-nested.-in-question-1-we-figured-out-what-the-root-node-was-called.-what-are-the-names-of-the-next-tier-of-elements-1" class="section level5">
<h5>2. Remember, XML can be nested. In question (1) we figured out what the root node was called. What are the names of the next &quot;tier&quot; of elements?</h5>
<p><strong>Hint:</strong> Now that we know the root node, you could use the root node name as a part of your xpath expression.</p>
<p><strong>Hint:</strong> As you may have noticed in question (1) the <code>xpath</code> method returns a list. Sometimes this list can contain many repeated tag names. Since our goal is to see the names of the second &quot;tier&quot; elements, you could convert the resulting <code>list</code> to a <code>set</code> to quickly see the unique list as <code>set</code>'s only contain unique values.</p>
<p><strong>Relevant topics:</strong> <a href="python.html#p-for-loops">for loops</a>, <a href="python.html#p-lxml">lxml</a>, <a href="data-formats.html#xml">xml</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
</ul>
</div>
</div>
<div id="continue-to-explore-each-tier-of-data-until-there-isnt-any-left.-name-the-full-paths-of-all-of-the-last-tier-tags.-1" class="section level5">
<h5>3. Continue to explore each &quot;tier&quot; of data until there isn't any left. Name the &quot;full paths&quot; of all of the &quot;last tier&quot; tags.</h5>
<p><strong>Hint:</strong> Let's say a &quot;last tier&quot; tag is just a path where there are no more nested elements. For example, <code>/HealthData/Workout/WorkoutRoute/FileReference</code> is a &quot;last tier&quot; tag. If you try and get the nested elements for it, they don't exist:</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python">tree.xpath(<span class="st">&quot;/HealthData/Workout/WorkoutRoute/FileReference/*&quot;</span>)</code></pre></div>
<p><strong>Hint:</strong> Here are 3 of the 7 &quot;full paths&quot;:</p>
<pre><code>/HealthData/Workout/WorkoutRoute/FileReference
/HealthData/Record/MetadataEntry
/HealthData/ActivitySummary</code></pre>
<p><strong>Relevant topics:</strong> <a href="python.html#p-lxml">lxml</a>, <a href="data-formats.html#xml">xml</a>, <a href="python.html#p-for-loops">for loops</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
</ul>
</div>
</div>
<div id="at-this-point-in-time-you-may-be-asking-yourself-but-where-is-the-data-depending-on-the-structure-of-the-xml-file-the-data-could-either-be-between-tags-like-1" class="section level5">
<h5>4. At this point in time you may be asking yourself &quot;but where is the data&quot;? Depending on the structure of the XML file, the data could either be between tags like:</h5>
<div class="sourceCode"><pre class="sourceCode html"><code class="sourceCode html"><span class="kw">&lt;some_tag&gt;</span>mydata<span class="kw">&lt;/some_tag&gt;</span></code></pre></div>
</div>
<div id="or-it-could-be-in-an-attribute-1" class="section level5">
<h5>Or, it could be in an attribute:</h5>
<div class="sourceCode"><pre class="sourceCode html"><code class="sourceCode html"><span class="kw">&lt;question</span><span class="ot"> answer=</span><span class="st">&quot;tac&quot;</span><span class="kw">&gt;</span>What is cat spelled backwards?<span class="kw">&lt;/question&gt;</span></code></pre></div>
</div>
<div id="collect-the-activitysummary-data-and-convert-the-list-of-dicts-to-a-pandas-dataframe.-the-following-is-an-example-of-converting-a-list-of-dicts-to-a-pandas-dataframe-called-mydf-1" class="section level5">
<h5>Collect the &quot;ActivitySummary&quot; data, and convert the list of dicts to a <code>pandas</code> DataFrame. The following is an example of converting a list of dicts to a <code>pandas</code> DataFrame called <code>myDF</code>:</h5>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="im">import</span> pandas <span class="im">as</span> pd

list_of_dicts <span class="op">=</span> []
list_of_dicts.append({<span class="st">&#39;columnA&#39;</span>: <span class="dv">1</span>, <span class="st">&#39;columnB&#39;</span>: <span class="dv">2</span>})
list_of_dicts.append({<span class="st">&#39;columnB&#39;</span>: <span class="dv">4</span>, <span class="st">&#39;columnA&#39;</span>: <span class="dv">1</span>}) 

myDF <span class="op">=</span> pd.DataFrame(list_of_dicts)</code></pre></div>
<p><strong>Hint:</strong> It is important to note that an element's &quot;attrib&quot; attribute looks and feels like a <code>dict</code>, but it is actually a <code>lxml.etree._Attrib</code>. If you try to convert a list of <code>lxml.etree._Attrib</code> to a <code>pandas</code> DataFrame, it will not work out as you planned. Make sure to first convert each <code>lxml.etree._Attrib</code> to a <code>dict</code> before converting to a DataFrame. You can do so like:</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co"># this will convert a single `lxml.etree._Attrib` to a dict</span>
my_dict <span class="op">=</span> <span class="bu">dict</span>(my_lxml_etree_attrib)</code></pre></div>
<p><strong>Relevant topics:</strong> <a href="python.html#p-dicts">dicts</a>, <a href="#p-lists">lists</a>, <a href="python.html#p-lxml">lxml</a>, <a href="data-formats.html#xml">xml</a>, <a href="python.html#p-for-loops">for loops</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
</ul>
</div>
</div>
<div id="pandas-is-a-python-package-that-provides-the-dataframe-and-series-classes.-a-dataframe-is-very-similar-to-a-data.frame-in-r-and-can-be-used-to-manipulate-the-data-within-very-easily.-a-series-is-the-class-that-handles-a-single-column-of-a-dataframe.-go-through-the-pandas-in-10-minutes-page-from-the-official-documentation.-sort-find-and-print-the-top-5-rows-of-data-based-on-the-activeenergyburned-column.-1" class="section level5">
<h5>5. <code>pandas</code> is a Python package that provides the DataFrame and Series classes. A DataFrame is very similar to a data.frame in R and can be used to manipulate the data within very easily. A Series is the class that handles a single column of a DataFrame. Go through the <a href="https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html">pandas in 10 minutes</a> page from the official documentation. Sort, find, and print the top 5 rows of data based on the &quot;activeEnergyBurned&quot; column.</h5>
<p><strong>Relevant topics:</strong> <a href="python.html#p-pandas">pandas</a>, <a href="python.html#p-dicts">dicts</a>, <a href="#p-lists">lists</a>, <a href="python.html#p-lxml">lxml</a>, <a href="data-formats.html#xml">xml</a>, <a href="python.html#p-for-loops">for loops</a></p>
<div class="bbox">
<p>
<strong>Item(s) to submit:</strong>
</p>
<ul>
<li>
Python code used to solve the problem.
</li>
<li>
Output from running your code.
</li>
</ul>
</div>
<hr />

</div>
</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="faqs.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="contributors.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/kevinamstutz/the-examples-book/edit/master/09-projects.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["the-datamine-examples.pdf", "the-datamine-examples.epub"],
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"info": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
