= `argparse`

If you recall from the "Writing Scripts" page, we mentioned that ordering arguments is the easiest way to write your scripts. Unfortunately, this is limited in its functionality -- other people might not know of your forced order and it can be complicated when many arguments are required.

`argparse` is a Python package that solves our problems by creating consistent command-line interfaces and handling the arguments necessary to make your script function.

{sp}+

== Coding Basics

We'll begin by showing `argparse` stripped down to its most basic level. The contents of this tutorial were inspired by xref:https://docs.python.org/3/howto/argparse.html[Python's `argparse` tutorial] and xref:https://docs.python.org/3/library/argparse.html[the `argparse` documentation].

{sp}+

[source,Python]
----
import argparse

def main():
    parser = argparse.ArgumentParser()
    args = parser.parse_args()

if __name__ == '__main__':
    main()
----

[NOTE]
====
Recall that the structure of `main` and the conditional are features of _scripts_ and are only necessary for running scripts, not for understanding `argparse`.
====

As with any package, the first step is importing `argparse`. Our `parser` variable is an `ArgumentParser` object, on which we add & parse arguments and ask for help. Assigning `parser.parse_args()` to `args` is the final step that checks for errors and converts our argument strings into objects. Declaring that variable is recommended to access the arguments for further use in the script.

If the above code was stored in a file called `test.py` and then executed in the terminal, it wouldn't yield anything. However, we have the `-h`/`--help` flag, we get some basic output:

[source,UNIX]
----
$ python test.py -h
----
----
usage: test.py [-h]

options:
  -h, --help  show this help message and exit
----

The help flag is intrinsic to any script and is very useful for deciphering any script you use or write.

Let's make our script more useful by adding some arguments before parsing:

[source,python]
----
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('say', help='outputs the given string')
parser.add_argument('boom', help='prints the string in uppercase')
args = parser.parse_args()
print(args.say)
print(args.boom.upper())
----

[source,UNIX]
----
$ python test.py hey ya
----
----
hey
YA
----