= Python

Python is a very popular programming language used in companies across the world. It's free to use and can be downloaded directly from https://www.python.org[python.org].

There are many resources online that show different methods for programming in python. In The Examples Book we hope to give applied examples of python functionality. 

If you find any corrections or would like to contribute directly please let us know (datamine@purdue.edu). 

== Setting up your local environment

Often setting up python on your own computer can be one of the trickiest steps when learning to code. Within The Data Mine we use our xref:data-engineering:rcac:introduction.adoc[research computing] resources to run python code. However, when setting up python locally some of the resources below can be helpful. 

* https://realpython.com/installing-python/[Python 3 Installation]
* https://code.visualstudio.com/docs/setup/setup-overview[VSCode Setup]
* https://realpython.com/python-virtual-environments-a-primer/[Virtual Environments]
* https://python-poetry.org/[Poetry Package Management]