= `pandas` Dates and Times

== Basics

Visualization is one of the crucial foundations of practicing data science, and analyzing information on a timeline can be vital to understanding its behavior. However, our understanding and structure of time is difficult to translate into raw computing -- we can recognize that the phrase "8/1/2022" is the day that follows "7/31/2022", but without help, a computer would just see those as two different strings.

To help, `pandas` introduced the `to_datetime` function to convert strings (like the ones above) to `Timestamp` objects, which have many attributes that help translate our human perception of dates and times for the computer's sake.

[CAUTION]
====
Python already has a `datetime` package with a `datetime` object -- `pandas Timestamp` is an adaptation of this object that works with `pandas` functions, though the two are often used interchangeably.
====

{sp}+

== `to_datetime`

Let's start with an example `DataFrame` that contains event types, attendance numbers, and the dates on which the events occur. We'll check the data types of our columns to see what `pandas` starts out with.

[source,python]
----
import pandas as pd

list_1 = ['7/1/2021', '7/4/2021', '8/20/2021', '9/2/2021', '4/1/2050']
list_2 = ['Presentation', 'Class', 'Presentation', 'Event', 'Class']
list_3 = [25, 0, 50, 48, 1000000]

myDF = pd.DataFrame(zip(list_1, list_2, list_3), columns=['date', 'type', 'attendance'])
print(myDF.dtypes)
----
----
date          object
type          object
attendance     int64
----

As we can see from the output, `date` is a general `object` -- this doesn't help us, as we need a `datetime` object and its host of useful functions and attributes. The simplest way to convert this only requires our `to_datetime` function, the column we want to change, and the format our dates come in:

[source, python]
----
myDF['date'] = pd.to_datetime(myDF['date'], format='%m/%d/%Y')
print(myDF.dtypes)
----

----
date          datetime64[ns]
type                  object
attendance             int64
----

Hold on -- what's with the `datetime64[ns]` object? In spite of this output, if we test the type of our individual dates (for example, `type(myDF.date[0])`)

{sp}+

=== `format` Argument

The date column is now saved with the data type that we want. `format` looks odd, but the idea is that we are telling `pandas` how to perceive the date: month first, then day, then year, separated by forward slashes. If the dates had dashes or some other separator, we could indicate this in `format` to ensure `pandas` is reading it correctly.

`datetime` formatting *does* pay attention to capitalization. For example, `%y` means the date excludes century, while `%Y` includes century (think 13 compared to 2013). There are lots of https://strftime.org[helpful tables] to explain the different formats, and we'll include the main ones here:

* Month:
** `%b` -- abbreviated month, "Oct"; `%B` -- full month name, "October"
** `%m` -- month number with leading zero, "04"; `%-m` -- month number, no leading zero, "4"
* Day:
** `%a` -- abbreviated weekday, "Mon"; `%A` -- full weekday name, "Monday"
** `%d` -- day number with leading zero, "07"; `%-d` -- day number, no leading zero, "7"
* Year: 
** `%y` -- last two numbers of year, "14"; `%Y` -- full year, "1914"

[WARNING]
====
`%M` corresponds to minute, while `%m` corresponds to month.
====

{sp}+

== Date Time Methods
Once you have the data in the correct data type there are lots of functions that can be beneficial when working with date time data. A few of the most common functions are included below: 

=== Examples

*What if I just wanted the month or year?*

[source, python]
----
myDF['month'] = myDF['date'].dt.month
myDF['year'] = myDF['date'].dt.year
print(myDF)
----

----
        date          type  attendance  month  year
0 2021-07-01  Presentation          25      7  2021
1 2021-07-04         Class           0      7  2021
2 2021-08-20  Presentation          50      8  2021
3 2021-09-02         Event          48      9  2021
4 2050-04-01         Class     1000000      4  2050
----

*What if I wanted to find the day of the week?*

[source, python]
----
myDF['day_of_the_week'] = myDF['date'].dt.day_name()
print(myDF)
----

----
        date          type  attendance day_of_the_week
0 2021-07-01  Presentation          25        Thursday
1 2021-07-04         Class           0          Sunday
2 2021-08-20  Presentation          50          Friday
3 2021-09-02         Event          48        Thursday
4 2050-04-01         Class     1000000          Friday
----

There is also a `month_name()` function that could be used!

*What if I wanted to shift all the days forward one week?*

[source, python]
----
myDF['one_week_later'] = myDF['date'] + pd.Timedelta("7 days")
print(myDF)
----

----
        date          type  attendance one_week_later
0 2021-07-01  Presentation          25     2021-07-08
1 2021-07-04         Class           0     2021-07-11
2 2021-08-20  Presentation          50     2021-08-27
3 2021-09-02         Event          48     2021-09-09
4 2050-04-01         Class     1000000     2050-04-08
----

==== How would I see the number of days until a specific date?

[source, python]
----
one_year_later = myDF['date'] + pd.offsets.DateOffset(years=1)
myDF['end_of_school'] = pd.to_datetime({'month': 5, 'day': 31, 'year':one_year_later.dt.year})
myDF['days_until_school_is_over'] = myDF['end_of_school'] - myDF['date']
print(myDF)
----

----
        date          type  attendance end_of_school days_until_school_is_over
0 2021-07-01  Presentation          25    2022-05-31                  334 days
1 2021-07-04         Class           0    2022-05-31                  331 days
2 2021-08-20  Presentation          50    2022-05-31                  284 days
3 2021-09-02         Event          48    2022-05-31                  271 days
4 2050-04-01         Class     1000000    2051-05-31                  425 days
----

== Resources
As you can see there is a ton of different functionality when working with date time objects in Pandas. As usual, Pandas has some great https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html[documentation] regarding date time functionality and all the different methods that are available. 