= Python Books

There are lots of different books that cover many different SQL variants.

* Introducing Python, 2nd Edition, by Bill Lubanovic (O'Reilly, 2020)

* Python for Data Analysis, 3rd Edition, by Wes McKinney (O'Reilly, 2022)

* Python for DevOps by Noah Gift, Kennedy Behrman, Alfredo Deza, and Grig Gheorghiu (O'Reilly, 2020)

* Foundations for Analytics with Python by Clinton W. Brownley (O'Reilly, 2016)

* Bioinformatics Programming Using Python by Mitchell L. Model (O'Reilly, 2010)

* Think Python by Allen Downey (O'Reilly, 2016)

* Robust Python by Patrick Viafore (O'Reilly, 2021)

* Data Wrangling with Python by Jacqueline Kazil and Katharine Jarmul (O'Reilly, 2016)

* Deep Learning with Python by Francois Chollet (Manning, 2018)

* The Hitchhiker's Guide to Python by Kenneth Reitz and Tanya Schlusser (O'Reilly, 2016)

* Programming with MicroPython by Nicholas H. Tollervey (O'Reilly, 2018)

* Natural Language Processing with Python by Steven Bird, Ewan Klein, and Edward Loper (O'Reilly, 2009)

* The Quick Python Book, 2nd Edition, by Naomi Ceder (Manning, 2010)

* Web Scraping with Python, 2nd Edition, by Ryan Mitchell (O'Reilly, 2018)

* Applied Text Analysis with Python by Benjamin Bengfort, Rebecca Bilbro, and Tony Ojeda (O'Reilly, 2018)

* Programming Python, 4th Edition, by Mark Lutz (O'Reilly, 2011)

* Python Cookbook, 3rd Edition, by David Beazley and Brian Jones (O'Reilly, 2013)

* Python Cookbook, 2nd Edition, by Alex Martelli, Anna Martelli Ravenscroft, and David Ascher (O'Reilly, 2005)

* Thoughtful Machine Learning with Python by Matthew Kirk (O'Reilly, 2017)

* Fluent Python, 2nd Edition, by Luciano Ramalho (O'Reilly, 2022)

