= Python Scripts

A script is a file that has code to be executed. Scripts can be scheduled or run on a user's computer. In Python, a script is a simple file with a `.py` extension. For example, `my_script.py`.

Scripts can range from very simple to very complicated. In this section we will review the basic framework for writing scripts in Python. This all starts with the first line in every script and it's known as the `shebang`.

== shebang

The first line that you find in most Python scripts is called the shebang. The shebang shows which Python environment will be used when the script is executed. 

For example, if you run with no shebang:

----
python ~/my_script.py
----

The script will try to run with the default Python on your computer. If you wanted to check with version that would be you can run:

----
which python
----

Building on the example above, if you try to run the Python script without `python` or `python3` in front of the script name it will fail. This is because the terminal doesn't know that the script should be run using Python. Adding a shebang to the script can tell it to use Python. After the shebang is added to the script you can call it without `python` or `python3` and it will run! 

For example, once the shebang is added the following will work:

----
$HOME/my_script.py
----

Most often in Python there are two common shebangs with scripts:

* `#!/usr/bin/python`
* `#!/usr/bin/env python`

The first will use the system's default Python located at `/usr/bin/python`. The second, will use the Python version that would be used if you ran `python` on the system. This is an important difference because virtual environments will change the `python` response and allow you to use different environments. 

Similarly, if you want Python to run with a set of packages you can use the shebang to point to the package location. For example, if you had a virtual environment you could add a shebang similar to `#!/class/datamine/apps/python/f2020-s2021/env/bin/python`. This would use all of the packages installed in this environment and would keep you from having to load the environment before running the script. 

== Arguments

Arguments are the values that you can pass to a script. For example, in the follow command, `-i`, `special word`, and `my_file.txt` are all arguments being passed to `grep`.

----
grep -i 'special_word' my_file.txt
----

We can also pass arguments to Python scripts:

----
$HOME/my_script.py -i 'okay, sounds good!'
----

To use these arguments within the script you can use the `sys` package. For example, if you were to run the code below:

[source, python]
----
import sys

def main():
    print(sys.argv)

if __name__ == '__main__':
    main()
----

With these arguments:

----
my_script.py -i 'okay, sounds good!'
----

The results would be:

----
['my_script.py', '-i', 'okay, sounds good!']
----

The `sys.argv` function returns a list of arguments where the first item is always the script name. You could then use the output from `sys.argv` to perform other tasks based on the output. 

Arguments can also be positional. This means that the order they are given to a script is very important. For example, if you switch the order of the arugents for the `grep` command it will fail:

----
grep my_file.txt 'my_pattern' #This won't work
----

Arguments can also be optional. Usually optional arguments include at least 1 `-`. They can also have short and long forms. For example, `-i` is the short form of `--ignore-case`. Both of these arguments do the same thing when used. 

Some argument options will have values passed to them. For example, the file name after `-f` in `grep -f my_file.txt` tells the script which file to use. If the option doesn't have input you can assume that including the option means TRUE and not including it means FALSE. For example, in the `my_script -i 'okay'` command we used above if we include `-i` it means it's TRUE that it should ignore the case of the letters. If we don't include `-i` it means ignore case is FALSE and the input will care about the letter's case. 

When using the short version `-i` input is separated with a space (`-i 'okay'`). If using the long form values are separated by an equals sign (`--ignore-case='okay'`).