= Baseball Examples Using the Lahman Database

These examples depend on this database:

`/anvil/projects/tdm/data/lahman/lahman.db`

== Parks in Indiana

Display the ballparks (from the `Parks` table) located in Indiana.

[source,SQL]
----
SELECT * FROM parks WHERE state = 'IN';
----




== Currently Active Teams

Find the names of all 30 active teams in 2023.

[source,SQL]
----
SELECT franchName FROM TeamsFranchises WHERE active=='Y';
----



== Strikeouts for Batters and Pitchers

Strikeouts are good for pitchers but bad for batters.  During the 2014 season, which pitcher had the most strikeouts, and how many strikeouts did they have?  Which batter had the most strikeouts, and how many strikeouts did they have?  (It is OK to just find the `playerID` for this pitcher and this batter.

[source,SQL]
----
SELECT playerID, SO FROM Pitching WHERE yearID = 2014 ORDER BY SO DESC LIMIT (1);

SELECT playerID, SO FROM Batting WHERE yearID = 2014 ORDER BY SO DESC LIMIT (1);
----






== Large Salaries

List the rows from the Salaries table in which a player made at least 30 million dollars in a single season.

[source,SQL]
----
SELECT * FROM Salaries WHERE salary >= 30000000 ORDER BY salary DESC;
----



== At Least One Complete Game In A Year

In recent years, it is rare for pitchers to throw a complete game.  For this question, in each year, consider only the pitchers (from the Pitching table) who pitched at least 1 complete game (in other words, who have `CG > 0`).  In each year, how many players achieved this feat, i.e., had at least one complete game?

[NOTE]
====
In 1871, there were 14 such pitchers, and in 2023, there were 25 such pitchers, but the number changed a lot over the years.
====

[source,SQL]
----
SELECT COUNT(*), yearID FROM Pitching WHERE CG > 0 GROUP BY yearID;
----




== Cy Young Award

Which pitcher has received the `Cy Young Award` the most times altogether?  How many times did he receive this award?  It suffices to just find this pitcher's `playerID`.

[source,SQL]
----
SELECT COUNT(*) as mycounts, playerID FROM awardsplayers WHERE awardID = 'Cy Young Award' GROUP BY playerID ORDER BY mycounts DESC LIMIT 1;
----


== Most World Series

Find the franchise that has won the World Series the most times.

[source,SQL]
----
SELECT COUNT(*) as mycounts, franchID FROM Teams WHERE WSWin = 'Y' GROUP BY franchID ORDER BY mycounts DESC LIMIT 1;
----




== Most Runs Batted In

In the 2023 season, find the batter with the most runs batted in.  It suffices to simply find their `playerID`.

[NOTE]
====
In the `Batting` table, the runs batted in are found in the `RBI` column.
====

[source,SQL]
----
SELECT playerID, SUM(RBI) as mysum FROM Batting WHERE yearID = 2023 GROUP BY playerID ORDER BY mysum DESC LIMIT 1;
----




== Journeymen

The term journeyman is one "who plays for numerous clubs during his career":

see https://en.wikipedia.org/wiki/Journeyman_(sports)

Make a list of all of the pitchers who have played for 12 or more teams during their careers.

[source,SQL]
----
SELECT COUNT(DISTINCT teamID) as mycounts, playerID FROM Pitching GROUP BY playerID ORDER BY mycounts DESC LIMIT 15;
----









