= Baseball Examples Using the Lahman Database

These examples depend on this database:

`/anvil/projects/tdm/data/lahman/lahman.db`


== Manager for the Cincinnati Reds

The Cincinnati Reds (`teamID = 'CIN'`) were very successful in the 1970s.  They were so successful that they were often called by the nickname the "Big Red Machine"!  Who was their manager in 1976?

[source,SQL]
----
SELECT p.nameFirst, p.nameLast FROM Managers as m JOIN People as p ON m.playerID = p.playerID WHERE m.teamID = 'CIN' and m.yearID = 1976;
----


== Tony LaRussa's Many Years as a Manager

Find the list of `teamID` and `yearID` values corresponding to the teams and years in which Tony LaRussa was a Manager

[source,SQL]
----
SELECT m.teamID, m.yearID FROM People as p JOIN Managers as m ON p.playerID = m.playerID WHERE p.nameFirst = 'Tony' AND p.nameLast = 'LaRussa';
----


== Wade Boggs Salary

Find the salaries for Wade Boggs (`playerID = boggswa01`) for each year of his career.

[source,SQL]
----
SELECT * FROM Salaries WHERE playerID = 'boggswa01';
----


== Characteristics of Cal Ripken Jr.

Cal Ripken Sr. and Cal Ripken Jr. both had long careers with the Baltimore Orioles:

`SELECT * FROM People WHERE nameFirst = 'Cal' AND nameLast = 'Ripken' LIMIT 5;`

Find Cal Ripken Jr.'s weight, height, and whether he bats left or right handed.

[source,SQL]
----
SELECT weight, height, bats FROM People WHERE playerID = 'ripkeca01' LIMIT 5;
----


== Roberto Clemente

Find the number of at-bats, home runs, and stolen bases for Roberto Clemente (`playerID = 'clemero01'`) by year, given in ascending order according to the year.

[source,SQL]
----
SELECT yearID, AB, HR, SB FROM Batting WHERE playerID = 'clemero01' ORDER BY yearID;
----






== Ichiro Suzuki

Ichiro Suzuki is regarded as one of the greatest hitters of all time because of his prowess in both American and Japanese professional baseball.  Find the number of hits (`H`) and home runs (`HR`) for Ichiro Suzuki (`playerID = suzukic01`) during each year of his career.

[source,SQL]
----
SELECT teamID, yearID, H, HR FROM batting WHERE playerID == 'suzukic01';
----

Notice that he was traded in 2012, so if we want his total number of hits (`H`) and home runs (`HR`) in each year, we need to group the values together, according to the yearID.  In such a case, it no longer makes sense to list the `teamID` because he has multiple `teamID` values in 2012.

[source,SQL]
----
SELECT yearID, SUM(H), SUM(HR) FROM batting WHERE playerID == 'suzukic01' GROUP BY yearID;
----

This story about Iris Skinner and Ichiro Suzuki is one of my favorite baseball stories:

https://x.com/Mariners/status/1563651247290195968



== Hall of Fame Veterans Committee

The Hall of Fame Veterans Committee nominates Hall of Fame players that are forgotten, so to say, in baseball history. The committee allows players to recognize and give justice to their underrated, underviewed, or undervalued peers.  Find all `playerID` and `yearID` values corresponding to players who were selectged for the Hall of Fame by the Veterans Committee between 1990 and 2000. Put the list in descending order.

[source,SQL]
----
SELECT playerID, yearID FROM halloffame WHERE votedBy = 'Veterans' AND inducted = 'Y' AND yearID BETWEEN 1990 AND 2000 ORDER BY yearID DESC;
----



== Strikeouts for Batters and Pitchers

Strikeouts are good for pitchers but bad for batters.  During the 2014 season, which pitcher had the most strikeouts, and how many strikeouts did they have?  Which batter had the most strikeouts, and how many strikeouts did they have?  Be sure to get their full names.

[source,SQL]
----
SELECT p.nameFirst, p.nameLast, t.SO FROM Pitching as t JOIN People as p ON p.playerID = t.playerID WHERE t.yearID = 2014 ORDER BY t.SO DESC LIMIT (1);

SELECT p.nameFirst, p.nameLast, b.SO FROM Batting as b JOIN People as p ON p.playerID = b.playerID WHERE b.yearID = 2014 ORDER BY b.SO DESC LIMIT (1);
----


== Most Runs Batted In

In the 2023 season, find the name of the batter with the most runs batted in.

[NOTE]
====
In the `Batting` table, the runs batted in are found in the `RBI` column.
====

[source,SQL]
----
SELECT p.nameFirst, p.nameLast, SUM(b.RBI) as mysum FROM Batting AS b JOIN People as p ON b.playerID = p.playerID WHERE b.yearID = 2023 GROUP BY b.playerID ORDER BY mysum DESC LIMIT 1;
----


== Most Shutouts

Which pitcher has thrown the most shutouts (`SHO`) in the National League since 2010?

[source,SQL]
----
SELECT playerID, SUM(SHO) as mycounts FROM pitching WHERE yearID >= 2010 AND lgID = 'NL' GROUP BY playerID ORDER BY mycounts DESC LIMIT 1;
----





== Florida teams

There are only two teams from Florida, namely, the Marlins (who have played as the Florida Marlins and now as the Miami Marlins, with `franchID = 'FLA'`) and the Rays (who have played as the Tampa Bay Devil Rays and now as the Tampa Bay Rays, with `franchID = 'TBD'`).  Considering only these two teams, find their attendance in each year, with all Marlins results given first (in ascending order by year) and then all Rays results given second (in ascending order by year).

[source,SQL]
----
SELECT yearID, franchID, attendance FROM teams WHERE franchID = 'TBD' OR franchID == 'FLA' ORDER BY franchID, yearID;
----


== Toronto Blue Jays Attendance

Sometimes a baseball team plays in different stadiums, for instance, due to a stadium renovation or due to the COVID pandemic.  Consider the Toronto Blue Jays (`teamkey = 'TOR'`) attendance, as described in the `Homegames` table.  Notice that there are multiple rows for the `yearkey` values 1989, 2001, 2021.  Now `SUM` the values for each `yearkey`, to get the total attendance in each year.  List your results according to the `yearkey`, in descreasing order.

[source,SQL]
----
SELECT yearkey, SUM(attendance) FROM homegames WHERE teamkey = 'TOR' GROUP BY yearkey ORDER BY yearkey DESC;
----





== Cy Young Award

Which pitcher has received the `Cy Young Award` the most times altogether?  How many times did he receive this award?  Find the name of this player.

[source,SQL]
----
SELECT COUNT(*) as mycounts, p.nameFirst, p.nameLast FROM awardsplayers as a JOIN People as p ON a.playerID = p.playerID WHERE a.awardID = 'Cy Young Award' GROUP BY p.playerID ORDER BY mycounts DESC LIMIT 1;
----


== The Most Errors in Baseball

Herman Long committed the most errors in the history of baseball.

[source,SQL]
----
SELECT playerID, SUM(E) as mycounts FROM fielding GROUP BY playerID ORDER BY mycounts DESC LIMIT 1;
----



== Managers Who Won At Least Seven World Series

Find the two managers who won at least seven World Series.

[source,SQL]
----
SELECT COUNT(*) as mycounts, m.playerID FROM Teams as t JOIN Managers as m ON (t.yearID = m.yearID) AND (t.teamID = m.teamID) WHERE t.WSWin = 'Y' GROUP BY m.playerID HAVING mycounts >= 7;
----



== Catchers Who Won the Gold Glove Award More Than Once In Their Careers

The Gold Glove award recognizes players with excellent fielding abilities.  Identify the catchers who have been recognized with this award more than once in their careers.

[source,SQL]
----
SELECT COUNT(*) as mycounts, playerID FROM AwardsPlayers WHERE awardID = 'Gold Glove' AND notes = 'C' GROUP BY playerID HAVING mycounts > 1 ORDER BY mycounts DESC;
----


== Very Successful Manager in the 1990s

For this question, consider only games player during the 1990s.
Find the `playerID` for each manager who won at least 60 percent of their games.  Because there are some managers who were involved in only a few games, include the criteria that the managers was in more than 100 games during this time period.

[NOTE]
====
There was only one such manager to achieve this feat in the 1990s.
====

[source,SQL]
----
SELECT CAST(SUM(W) AS FLOAT)/(SUM(W)+SUM(L)) as myrecord, playerID, SUM(W), SUM(L)
FROM managers
WHERE yearID BETWEEN 1990 AND 1999
GROUP BY playerID
HAVING myrecord > 0.6 AND SUM(W) + SUM(L) > 100
ORDER BY myrecord DESC;
----



== Mike Piazza Batting Average

Calculate Mike Piazza's batting average during each year of his career.

[TIP]
====
A player's batting average during a season is the number of hits (`H`) divided by the number of times at bat (`AB`).  In 1998, his batting average was 0.328.  It is necessary to group the player's statistics within the year (e.g., in case they were traded during the year).  It is also necessary to cast either the hits or the at-bats (or both) as a floating point number (or real number); otherwise, when dividing two integers, the result will be an integer.
====


[source,SQL]
----
SELECT CAST(SUM(b.H) AS FLOAT)/SUM(b.AB), b.yearID FROM People as p JOIN Batting as b ON p.playerID = b.playerID WHERE nameFirst = 'Mike' AND nameLast = 'Piazza' GROUP BY b.yearID;
----


