= Baseball Examples Using the Lahman Database

These examples depend on this database:

`/anvil/projects/tdm/data/lahman/lahman.db`

== Strikeouts for Batters and Pitchers

Strikeouts are good for pitchers but bad for batters.  During the 2014 season, which pitcher had the most strikeouts, and how many strikeouts did they have?  Which batter had the most strikeouts, and how many strikeouts did they have?  Be sure to get their full names.

[source,SQL]
----
SELECT p.nameFirst, p.nameLast, t.SO FROM Pitching as t JOIN People as p ON p.playerID = t.playerID WHERE t.yearID = 2014 ORDER BY t.SO DESC LIMIT (1);

SELECT p.nameFirst, p.nameLast, b.SO FROM Batting as b JOIN People as p ON p.playerID = b.playerID WHERE b.yearID = 2014 ORDER BY b.SO DESC LIMIT (1);
----









== Cy Young Award

Which pitcher has received the `Cy Young Award` the most times altogether?  How many times did he receive this award?  Find the name of this player.

[source,SQL]
----
SELECT COUNT(*) as mycounts, p.nameFirst, p.nameLast FROM awardsplayers as a JOIN People as p ON a.playerID = p.playerID WHERE a.awardID = 'Cy Young Award' GROUP BY p.playerID ORDER BY mycounts DESC LIMIT 1;
----






== Mike Piazza Batting Average

Calculate Mike Piazza's batting average during each year of his career.

[TIP]
====
A player's batting average during a season is the number of hits (`H`) divided by the number of times at bat (`AB`).  In 1998, his batting average was 0.328.  It is necessary to group the player's statistics within the year (e.g., in case they were traded during the year).  It is also necessary to cast either the hits or the at-bats (or both) as a floating point number (or real number); otherwise, when dividing two integers, the result will be an integer.
====


[source,SQL]
----
SELECT CAST(SUM(b.H) AS FLOAT)/SUM(b.AB), b.yearID FROM People as p JOIN Batting as b ON p.playerID = b.playerID WHERE nameFirst = 'Mike' AND nameLast = 'Piazza' GROUP BY b.yearID;
----


