

Question 5.

a. Find all players who stole 100 or more bases. For each such player, list the player's first name, last name, the number of bases stolen, and the year.

b. Same question, but now include the full name of the team that player played on, during the year of the achievement.

Solution:


a.  There have been 20 times when a player stole 100 or more bases in a season.

`SELECT p.nameFirst, p.nameLast, b.SB, b.yearID FROM People p INNER JOIN Batting b ON p.playerID = b.playerID WHERE b.SB >= 100;`

b.  Now we add the team names.

`SELECT p.nameFirst, p.nameLast, b.SB, b.yearID, t.name FROM People p INNER JOIN Batting b ON p.playerID = b.playerID INNER JOIN Teams t ON b.yearID=t.yearID AND b.teamID=t.teamID WHERE b.SB >= 100;`



Question 6.

a. Find the first and last names of all players inducted into the Hall of Fame since 2008 (including 2008 itself, and all years since then). Be sure to list the year of induction.

b. Same question, but now sort the results of the query by year.

c. Same question, but now give just the counts of the number of players inducted per year. Your results should have 1 column with the year and 1 column with the counts of how many players were inducted that year.

Solution:

a.  There are 13 players inducted into the Hall of Fame since 2008.

`SELECT p.nameFirst, p.nameLast, h.yearID FROM People p INNER JOIN HallOfFame h ON p.playerID=h.playerID WHERE h.yearID >= 2008 AND h.inducted = 'Y' AND h.category='player';`

b.  Now we sort the results by year.

`SELECT p.nameFirst, p.nameLast, h.yearID FROM People p INNER JOIN HallOfFame h ON p.playerID=h.playerID WHERE h.yearID >= 2008 AND h.inducted = 'Y' AND h.category='player' ORDER BY yearID;`

c.  Now we count the number of inducted players by year.

`SELECT h.yearID, COUNT(*) FROM HallOfFame h WHERE h.yearID >= 2008 AND h.inducted = 'Y' AND h.category='player' GROUP BY h.yearID;`


Question 7.

a. For each pitcher who had 20 or more wins, list the player's first name, last name, number of wins, and the relevant year.

b. Same question, but now give just the counts of the number of players per year. Your results should have 1 column with the year and 1 column with the counts of how many players had 20 of more wins that year.

Solution:

a.  Altogether, we see that a pitcher had 20 or more wins in a season 1183 times.

`SELECT p.nameFirst, p.nameLast, p.W, p.yearID FROM People p INNER JOIN Pitching p ON p.playerID = p.playerID WHERE p.W >= 20;`

b.  Here are the counts of the number of players, per year, to get this achievement.

`SELECT p.yearID, COUNT(*) FROM Pitching p WHERE p.W >= 20 GROUP BY p.yearID;`


Question 8.

a. The "40-40" club is a name commonly given to the group of all players who stole 40 or more bases and hit 40 or more home runs in the same year. For each member of the 40-40 club, list the player's first name, last name, the relevant year for the achievement, the number of bases stolen in that year, the number of home runs in that year, and the full name of the player's team.

b. Same question, but now for the 30-30 club.

c. Same question, for the 30-30 club, but now ignore the names of the players and their specific numbers of home runs and stolen bases, and ignore the years too. Instead, give the summary totals, by team, of how many times the team has had a 30-30 player (with possible repetitions). For example, the Chicago Cubs would have count "2", since Sammy Sosa achieved this feat twice in his career, but no other Chicago Cub achieved this feat.

Solution:

a.  There are 4 members of the 40-40 club

`SELECT p.nameFirst, p.nameLast, b.yearID, b.SB, b.HR, t.name FROM People p INNER JOIN Batting b ON p.playerID = b.playerID INNER JOIN Teams t ON b.yearID=t.yearID AND b.teamID=t.teamID WHERE b.SB >= 40 AND b.HR >= 40;`

b.  There are 58 members of the 30-30 club, BUT ONLY if we consider players' achievements on the same team within a year.  Therefore, the following code misses two players, each of whom were traded midseason, so their achievements were each split over two teams.

`SELECT p.nameFirst, p.nameLast, b.yearID, b.SB, b.HR, t.name FROM People p INNER JOIN Batting b ON p.playerID = b.playerID INNER JOIN Teams t ON b.yearID=t.yearID AND b.teamID=t.teamID WHERE b.SB >= 30 AND b.HR >= 30;`

There are different ways to get those extra two players.  One way is:

`SELECT p.nameFirst, p.nameLast, b.yearID, SUM(b.SB) mysb, SUM(b.HR) myhr FROM People p INNER JOIN Batting b ON p.playerID = b.playerID GROUP BY p.nameFirst, p.nameLast, b.yearID HAVING SUM(b.SB) >= 30 AND SUM(b.HR) >= 30;`

c.  Now we tabulate the number of players and years in the 30-30 club according to the team (using the first version of the code from 8b, i.e., just using the 58 players)

`SELECT t.name, COUNT(*) FROM Batting b INNER JOIN Teams t ON b.yearID=t.yearID AND b.teamID=t.teamID WHERE b.SB >= 30 AND b.HR >= 30 GROUP BY t.name;`


Question 9.

a. Find all players who earned 20 million dollars or more in a season. For each such occurrence, list the player's first name, last name, the year, the salary, the teamID, and the Team's full name.

b. Give a table that has a "Year" column, and a "Total Salary" column, and a "Team" column.

c. Sort the table in the previous question according to the total salary column.

Solution:

a.  Here are the players who earned 20 million dollars or more in a season.

`SELECT p.nameFirst, p.nameLast, s.yearID, s.salary, t.teamID, t.name FROM People p INNER JOIN Salaries s ON p.playerID = s.playerID INNER JOIN Teams t ON t.yearID = s.yearID AND t.teamID = s.teamID WHERE s.salary >= 20000000;`

b.  Here we give a table of the years, sums of salaries, and team names, but only restricting attention to the players with 20 million or more.

`SELECT s.yearID, SUM(s.salary), t.name FROM Salaries s INNER JOIN Teams t ON t.yearID = s.yearID AND t.teamID = s.teamID WHERE s.salary >= 20000000 GROUP BY t.name, s.yearID;`

same question, but now summing over all players (not just those with 20 million or more)

`SELECT s.yearID, SUM(s.salary), t.name FROM Salaries s INNER JOIN Teams t ON t.yearID = s.yearID AND t.teamID = s.teamID GROUP BY t.name, s.yearID;`

c.  Here we give a table of the years, sums of salaries, and team names, but only restricting attention to the players with 20 million or more.

`SELECT s.yearID, SUM(s.salary), t.name FROM Salaries s INNER JOIN Teams t ON t.yearID = s.yearID AND t.teamID = s.teamID WHERE s.salary >= 20000000 GROUP BY t.name, s.yearID ORDER BY SUM(s.salary);`

same question, but now summing over all players (not just those with 20 million or more)

`SELECT s.yearID, SUM(s.salary), t.name FROM Salaries s INNER JOIN Teams t ON t.yearID = s.yearID AND t.teamID = s.teamID GROUP BY t.name, s.yearID ORDER BY SUM(s.salary);`



Question 10.

a. Consider the total number of saves by pitchers during their entire careers. A few pitchers had 300 or more saves during their careers. Make a list of all such pitchers. For each such pitcher, give his first name, last name, and the total number of saves that the pitcher had during his career.

b. Same question, but instead of finding pitchers with 300 or more saves, find pitchers with 2000 or more strikeouts during their careers.

Solution:

a. There are 25 pitchers with 300 or more saves during their careers.

`SELECT p.nameFirst, p.nameLast, SUM(p.SV) FROM People p INNER JOIN Pitching p ON p.playerID = p.playerID GROUP BY p.playerID HAVING SUM(p.SV) >= 300;`

b. There are 69 pitchers with 2000 or more strikeouts during their careers.

`SELECT p.nameFirst, p.nameLast, SUM(p.SO) FROM People p INNER JOIN Pitching p ON p.playerID = p.playerID GROUP BY p.playerID HAVING SUM(p.SO) >= 2000;`




== Project 10

The code found in the `Week 13 examples` should be helpful in this problem set.

Please answer questions 1 to 3 in R, by making calls to your MySQL database.

Question 1.

a. Who are the 10 pitchers with the highest tallys of strikeouts throughout their careers?

b. Who are the 10 wildest pitchers, i.e., which pitchers have the highest tallys of wild pitches during their whole careers?

c. Who are the 10 pitchers with the most Outs Pitched (`IPOuts`) during their career?

Solution:

`library("RMySQL")`

`myconnection <- dbConnect(dbDriver("MySQL"), host="mydb.itap.purdue.edu", username="mdw", dbname="mdw")`

a.  One possibility is to load all pitchers, with any number of strikeouts, but there are a lot of these players, so we need to increase the number of results we fetch

[source,r]
----
myresult <- dbSendQuery(myconnection, "SELECT p.nameFirst, p.nameLast, SUM(p.SO) FROM People p INNER JOIN Pitching p ON p.playerID = p.playerID GROUP BY p.playerID;")
mydata <- fetch(myresult, n=10000)
names(mydata) <- c("first", "last", "strikeouts")
tail(mydata[ order(mydata$strikeouts), ], n=10)
----

A different method is to go ahead and restrict the mySQL query to only fetch pitchers with at least 300 wins, so that we don't have to fetch so many pitchers.

[source,r]
----
myresult <- dbSendQuery(myconnection, "SELECT p.nameFirst, p.nameLast, SUM(p.SO) FROM People p INNER JOIN Pitching p ON p.playerID = p.playerID GROUP BY p.playerID HAVING SUM(p.SO) >= 2000;")
mydata <- fetch(myresult)
names(mydata) <- c("first", "last", "strikeouts")
tail(mydata[ order(mydata$strikeouts), ], n=10)
----


b.  Again, we could either do this by loading all of the pitchers:

[source,r]
----
myresult <- dbSendQuery(myconnection, "SELECT p.nameFirst, p.nameLast, SUM(p.WP) FROM People p INNER JOIN Pitching p ON p.playerID = p.playerID GROUP BY p.playerID;")
mydata <- fetch(myresult, n=10000)
names(mydata) <- c("first", "last", "wildpitches")
tail(mydata[ order(mydata$wildpitches, na.last=FALSE), ], n=10)
----

Notice, in the last line above, we had to make sure that the `NA` values were not put at the end of the list.

A different method is to go ahead and restrict the mySQL query to (say) 150 or more wild pitches

[source,r]
----
myresult <- dbSendQuery(myconnection, "SELECT p.nameFirst, p.nameLast, SUM(p.WP) FROM People p INNER JOIN Pitching p ON p.playerID = p.playerID GROUP BY p.playerID HAVING SUM(p.WP) >= 150;")
mydata <- fetch(myresult)
names(mydata) <- c("first", "last", "wildpitches")
tail(mydata[ order(mydata$wildpitches), ], n=10)
----


c.  Again, we could either do this by loading all of the pitchers:

[source,r]
----
myresult <- dbSendQuery(myconnection, "SELECT p.nameFirst, p.nameLast, SUM(p.IPOuts) FROM People p INNER JOIN Pitching p ON p.playerID = p.playerID GROUP BY p.playerID;")
mydata <- fetch(myresult, n=10000)
names(mydata) <- c("first", "last", "IPOuts")
tail(mydata[ order(mydata$IPOuts), ], n=10)
----

or a different method is to go ahead and restrict the mySQL query to (say) 12000 or more IPOuts

[source,r]
----
myresult <- dbSendQuery(myconnection, "SELECT p.nameFirst, p.nameLast, SUM(p.IPOuts) FROM People p INNER JOIN Pitching p ON p.playerID = p.playerID GROUP BY p.playerID HAVING SUM(p.IPOuts) >= 12000;")
mydata <- fetch(myresult)
names(mydata) <- c("first", "last", "IPOuts")
tail(mydata[ order(mydata$IPOuts), ], n=10)
----


Question 2.

a. Which team has the most home runs of all time (summed over all years)?

b. Which team has the largest average number of home runs per year, where this is averaged over all years?

Solution:

a.  The New York Yankees have the most home runs altogether.

[source,r]
----
myresult <- dbSendQuery(myconnection, "SELECT t.name, SUM(b.HR), t.yearID FROM Batting b INNER JOIN Teams t ON b.yearID=t.yearID AND b.teamID=t.teamID GROUP BY t.name, t.yearID;")
mydata <- fetch(myresult, n=10000)
names(mydata) <- c("team", "homeruns", "year")
sort(tapply(mydata$homeruns, mydata$team, sum), decreasing=T)[1:1]
----

b.   We start with the same data from part a, and then we determine the number of active years for each team

[source,r]
----
years <- sapply(tapply(mydata$year, mydata$team, range), diff)+1
#       and the number of home runs per team
homeruns <- tapply(mydata$homeruns, mydata$team, sum)
#       and finally we divide, and then sort, and extract the largest:
sort(homeruns / years, decreasing=T)[1]
----


Question 3.

a. Rank the 50 states according to the number of baseball players who were born in the state.

b. What percent of players have a left batting hand? Right batting hand? Both?

Solution:

a.   California is the birthplace of 2133 players, the most of any State.

[source,r]
----
myresult <- dbSendQuery(myconnection, "SELECT p.birthState, COUNT(*) FROM People p GROUP BY p.birthState;")
mydata <- fetch(myresult)
names(mydata) <- c("state", "peoplecount")
tail(mydata[order(mydata$peoplecount), ], n=1)
----

b.   Altogether, 6.17 percent use both hands for batting; 25.87 percent use the left hand; 61.30 percent use the right hand.

[source,r]
----
myresult <- dbSendQuery(myconnection, "SELECT p.bats, COUNT(*) FROM People p GROUP BY p.bats;")
mydata <- fetch(myresult)
mydata
mydata[ ,2]/sum(mydata[ ,2])
----


