= ACCESS Email Update

If you have an ACCESS ID, but it is connected to the wrong email, follow the steps below to update the ID's information.

. Login to the https://registry.access-ci.org/[ACCESS registry] with your current ACCESS ID and password. 
. If you haven't accepted the "Terms of Service", they must be accepted before the steps below. 
. Select the "Profile" option from the "ACCESS User Identity Dashboard".
. In the middle of the page, under "Email Addresses" click the "Add" button.
. On the "Add a New Email Address" page, enter your "edu" email information.
. Be sure to select "Official" from the "Type" drop down. 
. Select "Add". 
. After the new email has been added, it will have an "Unverified" label in the ACCESS portal. 
. Select the gear icon to the right of the new email and select the "Verify" option. This will generate an email to verify the connection. 
. Once the email has been verified, select the gear icon next to the old email and select "Delete".
. Your ACCESS account should now be updated for your "edu" email! 

== Associating a Different Organization

Sometimes you may have an ACCESS ID that you want to connect to your Purdue account. 

To do that, follow the steps below.

. Login to the https://registry.access-ci.org/[ACCESS registry] with your current ACCESS ID and password. 
. Click on your name in the upper-right corner and a drop-down menu will appear. 
. In the middle of the drop-down menu, under "Available Enrollment Flows", select the "Link another account" option. 
. Click "Begin".
. After the page loads, select "Purdue University Main Campus" from the "Select an Identify Provider" section of the page and click "Log On".
. Authenticate with your Purdue ID and password. 
. Once this is successful, you should see ACCESS take a series of steps to connect the Purdue profile with your existing profile.