= Register for Seminar (1 credit) for Fall 2022

*Undergraduate students:* ALL undergraduate students in The Data Mine must take the 1 credit seminar course (see table below for available sections). 

*Graduate students:* This course is *optional* for graduate students but you are welcome to enroll.

[%header,format=csv]
|===
CRN FALL 2022,Old Course - DO NOT USE,Course,Course Title,Subtitle,Min / Week,Day,Time,Room,Level
12067,STAT 19000,TDM 10100,The Data Mine Seminar I,Lec 1,50,Mon,8:30am,HILL C141,UNDERGRADUATE ONLY - 1st YEAR IN DATA MINE
12072,STAT 19000,TDM 10100,The Data Mine Seminar I,Lec 2,50,Mon,9:30am,HILL C141,UNDERGRADUATE ONLY - 1st YEAR IN DATA MINE
12073,STAT 19000,TDM 10100,The Data Mine Seminar I,Lec 3,50,Mon,10:30am,HILL C141,UNDERGRADUATE ONLY - 1st YEAR IN DATA MINE
12071,STAT 19000,TDM 10100,The Data Mine Seminar I,Lec 4,50,Mon,4:30pm,SYNC ONLINE,UNDERGRADUATE ONLY - 1st YEAR IN DATA MINE
12117,STAT 29000,TDM 20100,The Data Mine Seminar III,Lec 1,50,Mon,8:30am,HILL C141,UNDERGRADUATE ONLY - 2nd YEAR IN DATA MINE
12106,STAT 29000,TDM 20100,The Data Mine Seminar III,Lec 2,50,Mon,9:30am,HILL C141,UNDERGRADUATE ONLY - 2nd YEAR IN DATA MINE
12113,STAT 29000,TDM 20100,The Data Mine Seminar III,Lec 3,50,Mon,10:30am,HILL C141,UNDERGRADUATE ONLY - 2nd YEAR IN DATA MINE
12118,STAT 29000,TDM 20100,The Data Mine Seminar III,Lec 4,50,Mon,4:30pm,SYNC ONLINE,UNDERGRADUATE ONLY - 2nd YEAR IN DATA MINE
12104,STAT 39000,TDM 30100,The Data Mine Seminar V,Lec 1,50,Mon,8:30am,HILL C141,UNDERGRADUATE ONLY - 3rd YEAR IN DATA MINE
12112,STAT 39000,TDM 30100,The Data Mine Seminar V,Lec 2,50,Mon,9:30am,HILL C141,UNDERGRADUATE ONLY - 3rd YEAR IN DATA MINE
12115,STAT 39000,TDM 30100,The Data Mine Seminar V,Lec 3,50,Mon,10:30am,HILL C141,UNDERGRADUATE ONLY - 3rd YEAR IN DATA MINE
12120,STAT 39000,TDM 30100,The Data Mine Seminar V,Lec 4,50,Mon,4:30pm,SYNC ONLINE,UNDERGRADUATE ONLY - 3rd YEAR IN DATA MINE
12103,STAT 49000,TDM 40100,The Data Mine Seminar VII,Lec 1,50,Mon,8:30am,HILL C141,UNDERGRADUATE ONLY - 4th YEAR IN DATA MINE
12111,STAT 49000,TDM 40100,The Data Mine Seminar VII,Lec 2,50,Mon,9:30am,HILL C141,UNDERGRADUATE ONLY - 4th YEAR IN DATA MINE
12114,STAT 49000,TDM 40100,The Data Mine Seminar VII,Lec 3,50,Mon,10:30am,HILL C141,UNDERGRADUATE ONLY - 4th YEAR IN DATA MINE
12119,STAT 49000,TDM 40100,The Data Mine Seminar VII,Lec 4,50,Mon,4:30pm,SYNC ONLINE,UNDERGRADUATE ONLY - 4th YEAR IN DATA MINE
15644,STAT 59800,TDM 50100,The Data Mine Seminar,Lec 1,50,Mon,4:30pm ,SYNC ONLINE,GRADUATE STUDENTS ONLY

|===


*TDM 10100 - UNDERGRADUATE ONLY - 1st YEAR IN DATA MINE*
_Formerly STAT 19000_
[%header,format=csv]
|===
CRN FALL 2022,Old Course - DO NOT USE,Course,Course Title,Subtitle,Min / Week,Day,Time,Room
12067,STAT 19000,TDM 10100,The Data Mine Seminar I,Lec 1,50,Mon,8:30am,HILL C141
12072,STAT 19000,TDM 10100,The Data Mine Seminar I,Lec 2,50,Mon,9:30am,HILL C141
12073,STAT 19000,TDM 10100,The Data Mine Seminar I,Lec 3,50,Mon,10:30am,HILL C141
12071,STAT 19000,TDM 10100,The Data Mine Seminar I,Lec 4,50,Mon,4:30pm,SYNC ONLINE
|===

*TDM 20100 - UNDERGRADUATE ONLY - 2nd YEAR IN DATA MINE*
_Formerly STAT 29000_
[%header,format=csv]
|===
CRN FALL 2022,Old Course - DO NOT USE,Course,Course Title,Subtitle,Min / Week,Day,Time,Room
12117,STAT 29000,TDM 20100,The Data Mine Seminar III,Lec 1,50,Mon,8:30am,HILL C141
12106,STAT 29000,TDM 20100,The Data Mine Seminar III,Lec 2,50,Mon,9:30am,HILL C141
12113,STAT 29000,TDM 20100,The Data Mine Seminar III,Lec 3,50,Mon,10:30am,HILL C141
12118,STAT 29000,TDM 20100,The Data Mine Seminar III,Lec 4,50,Mon,4:30pm,SYNC ONLINE
|===


*TDM 30100 - UNDERGRADUATE ONLY - 3rd YEAR IN DATA MINE*
_Formerly STAT 39000_
[%header,format=csv]
|===
CRN FALL 2022,Old Course - DO NOT USE,Course,Course Title,Subtitle,Min / Week,Day,Time,Room
12104,STAT 39000,TDM 30100,The Data Mine Seminar V,Lec 1,50,Mon,8:30am,HILL C141
12112,STAT 39000,TDM 30100,The Data Mine Seminar V,Lec 2,50,Mon,9:30am,HILL C141
12115,STAT 39000,TDM 30100,The Data Mine Seminar V,Lec 3,50,Mon,10:30am,HILL C141
12120,STAT 39000,TDM 30100,The Data Mine Seminar V,Lec 4,50,Mon,4:30pm,SYNC ONLINE

|===

*TDM 40100 - UNDERGRADUATE ONLY - 4th YEAR IN DATA MINE*
_Formerly STAT 49000_
[%header,format=csv]
|===
CRN FALL 2022,Old Course - DO NOT USE,Course,Course Title,Subtitle,Min / Week,Day,Time,Room
12103,STAT 49000,TDM 40100,The Data Mine Seminar VII,Lec 1,50,Mon,8:30am,HILL C141
12111,STAT 49000,TDM 40100,The Data Mine Seminar VII,Lec 2,50,Mon,9:30am,HILL C141
12114,STAT 49000,TDM 40100,The Data Mine Seminar VII,Lec 3,50,Mon,10:30am,HILL C141
12119,STAT 49000,TDM 40100,The Data Mine Seminar VII,Lec 4,50,Mon,4:30pm,SYNC ONLINE
|===

*GRADUATE STUDENTS ONLY*
_Formerly STAT 59800_
[%header,format=csv]
|===
CRN FALL 2022,Old Course - DO NOT USE,Course,Course Title,Subtitle,Min / Week,Day,Time,Room
15644,STAT 59800,TDM 50100,The Data Mine Seminar,Lec 1,50,Mon,4:30pm ,SYNC ONLINE

|===

