= How to Register for Seminar (1 credit) - Fall 2022



[IMPORTANT] 
==== 
*ALL undergraduate students in The Data Mine must take the 1-credit hour seminar course.* 
====

See the tables below to register for the seminar based on how many years you have been in The Data Mine. The seminar level is not based on how many years you have been at Purdue.  


== TDM 10100 - 1st YEAR IN DATA MINE 

* Formerly STAT 19000
* UNDERGRADUATE ONLY 

[%header,format=csv, stripes=odd, frame=ends]
|===
CRN FALL 2022,Course,Course Title,Subtitle,Min / Week,Day,Time,Room
12067,TDM 10100,The Data Mine Seminar I,Lec 1,50,Mon,8:30am,HILL C141
12072,TDM 10100,The Data Mine Seminar I,Lec 2,50,Mon,9:30am,HILL C141
12073,TDM 10100,The Data Mine Seminar I,Lec 3,50,Mon,10:30am,HILL C141
12071,TDM 10100,The Data Mine Seminar I,Lec 4,50,Mon,4:30pm,SYNC ONLINE
|===

== TDM 20100 - 2nd YEAR IN DATA MINE

* Formerly STAT 29000
* UNDERGRADUATE ONLY 

[%header,format=csv]
|===
CRN FALL 2022,Course,Course Title,Subtitle,Min / Week,Day,Time,Room
12117,TDM 20100,The Data Mine Seminar III,Lec 1,50,Mon,8:30am,HILL C141
12106,TDM 20100,The Data Mine Seminar III,Lec 2,50,Mon,9:30am,HILL C141
12113,TDM 20100,The Data Mine Seminar III,Lec 3,50,Mon,10:30am,HILL C141
12118,TDM 20100,The Data Mine Seminar III,Lec 4,50,Mon,4:30pm,SYNC ONLINE
|===


== TDM 30100 - 3rd YEAR IN DATA MINE

* Formerly STAT 39000
* UNDERGRADUATE ONLY

[%header,format=csv]
|===
CRN FALL 2022,Course,Course Title,Subtitle,Min / Week,Day,Time,Room
12104,TDM 30100,The Data Mine Seminar V,Lec 1,50,Mon,8:30am,HILL C141
12112,TDM 30100,The Data Mine Seminar V,Lec 2,50,Mon,9:30am,HILL C141
12115,TDM 30100,The Data Mine Seminar V,Lec 3,50,Mon,10:30am,HILL C141
12120,TDM 30100,The Data Mine Seminar V,Lec 4,50,Mon,4:30pm,SYNC ONLINE

|===

== TDM 40100 - 4th YEAR IN DATA MINE

* Formerly STAT 49000
* UNDERGRADUATE ONLY

[%header,format=csv]
|===
CRN FALL 2022,Course,Course Title,Subtitle,Min / Week,Day,Time,Room
12103,TDM 40100,The Data Mine Seminar VII,Lec 1,50,Mon,8:30am,HILL C141
12111,TDM 40100,The Data Mine Seminar VII,Lec 2,50,Mon,9:30am,HILL C141
12114,TDM 40100,The Data Mine Seminar VII,Lec 3,50,Mon,10:30am,HILL C141
12119,TDM 40100,The Data Mine Seminar VII,Lec 4,50,Mon,4:30pm,SYNC ONLINE
|===

== TDM 50100 - GRADUATE STUDENTS ONLY

* Formerly STAT 59800
* GRADUATE STUDENTS ONLY
* This course is *optional* for graduate students but you are welcome to enroll.

[%header,format=csv]
|===
CRN FALL 2022,Course,Course Title,Subtitle,Min / Week,Day,Time,Room
15644,TDM 50100,The Data Mine Seminar,Lec 1,50,Mon,4:30pm, SYNC ONLINE
|===

