= Website Links

== https://one.purdue.edu/task/all/successfactors-employee[SuccessFactors]
Login Info: Purdue username, BoilerKey pin +
SuccessFactors will allow you to access your paystubs and information about your position.

== https://one.purdue.edu/task/all/webmail[Purdue Outlook]
Login Info: Purdue username, Purdue career password (not BoilerKey) +
Outlook Email is how you can access and check your Purdue emails. +
You can forward your Purdue email to your academic email. 

[IMPORTANT]
====
Do not exchange any sensitive information through emails.
====

== Anvil
Login Info: ACCESS username, ACCESS password +
_Once you log into Anvil, it will do a Duo Push to your phone and you need to approve the request._ +
Anvil is the location where you will access your company data and run your code in collaboration.


Type this link in a browser: *ondemand.anvil.rcac.purdue.edu*

== https://www.gradescope.com/[Gradescope]
Login Info:  +
Gradescope is the location you will submit your assignments.

== https://www.itap.purdue.edu/services/microsoft-teams.html[Microsoft Teams]
Login Info: Purdue username, Purdue career password (not BoilerKey) + 
We will use Teams as primary conversation for anything related to your Corporate Partner project. You can share your updates/findings with your team members on Teams. Sensitive data is allowed to discuss on Teams platform *only*.