= Clustering

Clustering is an xref:data-modeling/choosing-model/supervision.adoc[unsupervised learning] approach that "clusters" data points based on the type of clustering technique. There are many varieties of clustering out there, such as hierarchical and k-means.

== Common Applications

=== Common Industries

- Agriscience
- Healthcare
- Marketing
- Tech/Social Media

=== Common Problem Types

- Anomaly Identification
- Market Segmentation
- Genetic/Biological Analysis
- Recommender Systems

== Code Examples

NOTE: All of the code examples are written in Python, unless otherwise noted.

=== Containers

TIP: These are code examples in the form of Jupyter notebooks running in a container that come with all the data, libraries, and code you'll need to run it. https://the-examples-book.com/starter-guides/data-engineering/containers/using-data-mine-containers[Click here to learn why you should be using containers, along with how to do so.]

TIP: Quickstart: https://docs.docker.com/get-docker/[Download Docker], then run the commands below in a terminal. 

[source,bash]
----
#pull container, only needs to be run once
docker pull ghcr.io/thedatamine/starter-guides:k-means-clustering

#run container
docker run -p 8888:8888 -it ghcr.io/thedatamine/starter-guides:k-means-clustering
----

Need help implementing any of this code? Feel free to reach out to mailto:datamine-help@purdue.edu[datamine-help@purdue.edu] and we can help!

== Resources

All resources are chosen by Data Mine staff to be of decent quality, and most if not all content is free. 

=== Websites

https://developers.google.com/machine-learning/clustering/overview[What is Clustering? (Google)]

https://www.w3schools.com/python/python_ml_hierarchial_clustering.asp[Hierarchical Clustering (W3 Schools)]

https://www.mathworks.com/discovery/cluster-analysis.html[What is Cluster Analysis (MathWorks)]

=== Videos

https://www.youtube.com/watch?v=Se28XHI2_xE[4 Basic Types of Cluster Analysis used in Data Analytics (~9 minutes)]

https://www.youtube.com/watch?v=KtRLF6rAkyo[Clustering (~16 minutes)]

https://www.youtube.com/watch?v=4b5d3muPQmA[K-means Clustering (~8 minutes)]

https://www.youtube.com/watch?v=7xHsRkOdVwo[Hierarchical Clustering (~16 minutes)]

=== Books

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/uc5e95/alma99169710328501081[An Introduction to Clustering With R (2020)]

https://www.statlearning.com[Introduction to Statistical Learning (using Python and R), see Chapter 12.4 (2022)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_askewsholts_vlebooks_9783030378264[Partitional Clustering Via Nonsmooth Optimization: Clustering Via Optimization (2020)]

=== Articles

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_doaj_primary_oai_doaj_org_article_67c6c86d62004c00a8a208caa849e110[Survey on Hierarchical Clustering for Machine Learning (2023)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_proquest_journals_2502878800[Classifying Patients Operated for Degenerative Lumbar Spondylolisthesis: A Machine-Learning Clustering Analysis to Identify Patterns of Clinical Presentation (2020)]

https://purdue.primo.exlibrisgroup.com/permalink/01PURDUE_PUWL/5imsd2/cdi_crossref_primary_10_1016_j_jbiotec_2020_12_002[Multi-assignment clustering: Machine learning from a biological perspective (2021)]