= Lego Agile Activity

== TA Resources
Download these resources to lead the Lego Agile Activity:

- xref:attachment$Agile-Lego-Activity-Facilitator-Guide.docx[Agile Lego Activity Facilitator Guide]
- xref:attachment$Agile-lego-activity-instructions.pptx[Agile lego activity instructions]

*Task: Design and build a new building for The Data Mine*

== Instructions
*Teams*

- Unless otherwise instructed, split your team evenly into 2 groups
-  There should be 3-9 people per group
- Each sub team should have a Lego set and project board.

Product owners have developed a backlog of tasks. Your sub team will be responsible for allocating work in an Agile methodology and executing the tasks.

However, there are a few caveats...

- Your team will need to identify and deliver the minimum viable product (MVP)
- You will need to work with the product owner to clarify requests tasks in the backlog.
- You may not be able to complete all of the tasks on the backlog with the time and materials 
provided (you will need to negotiate with the PO!). 
- Remember, product owners can also change their minds – you may need to be flexible if you 
build something and they don’t like it.
- Creativity is encouraged! A Lego can represent anything as long as it is explained (and communication is a key part of Agile!)

*Roles*

- A Data Mine staff member or your TA will act as the product owner for this activity.  
- All team members will act as developers

== Sprint Timeline
*Sprint Planning* (4 minutes)  

- Choosing what tasks to do during the sprint, estimating time/distributing work, and working with the 
product owner to clarify tasks.

*Sprint* (8 minutes) 

- Work time in which the product owner is not actively working with you.

*Sprint Review* (3 minutes)

- Present work from the sprint to the product owner and get feedback.

*Retrospective* (2 minutes)

- Discuss what went right, what went wrong, and how you can fix issues in the next sprint (e.g., how 
you collaborate, estimating time required for tasks, etc.)

*Repeat!* (3x)