= Dashboarding Tools

As analytics become more widespread many applications have been built to make visualization and analysis of data easier. 

Two of the most common of these applications are https://www.tableau.com/[Tableau] and https://powerbi.microsoft.com/en-us/[Power BI].

These tools often come up as Data Mine projects progress. As with any tools they have their pros and cons. 

The Data Mine team created a simple list below to help think through use cases when designing your TDM project. 

== Power BI
* Currently there is no Linux version of this application. 
** This isn't impactful on a Windows or Mac computer, but everything on https://www.rcac.purdue.edu/compute/anvil[Anvil] runs on Linux. 
** This means that if you'd like to use Power BI with secure data storage The Data Mine team will need to work with you in advance to setup a Windows server or VM solution. 
* Licensing:
** Power BI Desktop base license is free to anyone.
** Power BI Pro and Premium are paid licenses. These are required for users to publish dashboards or share Power BI workspaces. 
** For non-licensed users to access Power BI dashboards the organization has to have a PPC license. This is capacity based and is usually purchased at an organization level. 
** Microsoft has a helpful https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-how-to-collaborate-distribute-dashboards-reports[collaboration guide] when researching different alternatives.
** There is also a https://powerbi.microsoft.com/en-us/pricing/[product comparison] guide to help with the differences between the license levels. 
+
[IMPORTANT]
====
The Data Mine doesn't currently pay for software licenses for student teams. 

This means that the Power BI Desktop version would be available, but Pro and Premium would need to be part of the project costs for the company. 
====
+
* Security:
** Security for the Power BI dashboards depends on where and how they are published. 
** Shared workspaces have different permissions levels that can be granted to users. 
** Other options publish the dashboard with no security at all. 
* Data Mine Guidance:
** Power BI is an easy to access tool that can be used to build quick dashboards. 
** The Data Mine can setup Windows Server solutions to allow for students to use Power BI within a secure data environment like Anvil. 
** *NOTE:* the easiest way to share Power BI dashboards is to send the dashboard file to another Power BI user for them to open. Working on shared dashboards or allowing non-licensed users to see a dashboard all require additional paid licenses. 

== Tableau
* Like Power BI, this does not have a Linux alternative. 
** This isn't impactful on a Windows or Mac computer, but everything on https://www.rcac.purdue.edu/compute/anvil[Anvil] runs on Linux. 
** This means that if you'd like to use Tableau with secure data storage The Data Mine team will need to work with you in advance to setup a Windows server or VM solution. 
* Licensing:
** Tableau does have a https://www.tableau.com/university-students[student license] that can be used for initial development.
** Publishing Tableau dashboards does require a paid contributor license that is usually purchased at an organizational level. 
+
[IMPORTANT]
====
The Data Mine doesn't currently pay for software licenses for student teams. 

This means that any of the paid versions of Tableau required for publishing of the dashboards would need to be part of the project costs for the company. 
====
* Security:
** Purdue University has two Tableau environments that are open to users. One is public and the other is private. 
** The private Tableau server is only open to users with Purdue ID's. Anyone outside Purdue wouldn't be able to access the dashboard. These can also be secured further with AD groups to allow only specific users access.
** The public Tableau server is open to *anyone*. These cannot be secured further, but they don't allow access to the underlying data. Only the dashboard itself. 
** Published dashboards are also limited by server capacity. Smaller publications should not be an issue, but dashboards consuming large amounts of data may not be possible on Purdue's environment. 
* Data Mine Guidance:
** If a team would like to use Tableau the students can usually get a Tableau student license that can be renewed on a yearly basis. 
** Publishing the dashboard to a Purdue environment would require a member of The Data Mine to purchase a Tableau license and would also require the mentor to have a Purdue ID unless the dashboard was published to the public. 
** The Purdue environment is limited by capacity. Small dashboards are OK, but larger dashboards may run into problems. 

== Alternatives
* One of the big pros of using tools like Tableau and Power BI is that they make visualization and publication easy once the pieces are in place. 
* There are tools that are open source, but they trade high levels or customization for harder implementation. 
* A few of these potential alternatives are included below:
** https://www.djangoproject.com/[Python Django]
** https://plotly.com/dash/[Python Dash]
** https://shiny.rstudio.com/[R Shiny] 