= Scoping a Data Science Project

One of the hardest aspects of data science can be defining the project. Data is messy and outcomes often change as the projects progress. 

There isn't any perfect way to define a data science project. These are lessons that we've learned as The Data Mine has grown and that other mentors have shared with us from industry. 

If you have anything that should be added, please email us at datamine@purdue.edu. 

== Data Science Project Checklist
* What level of experience is needed for the project?
** Many of our students are early in their academic careers. If you need very specific skills, a sponsored research project may be the way to go. 
* What kind of technology is required?
** The Data Mine team is happy to work with you to accommodate different environments at Purdue, but it can take some extra time to get everything set up. 
* What data will the students use?
** Data is both the fuel and the biggest challenge to a project. Small amounts of data or incomplete data sets can lead to challenges that the students aren't able to address. 
* How will the students learn about the data and models?
** Often the students will join a project eager to learn, but early in their academic career. Providing examples of types or models, data dictionaries, and steps to learn different concepts can be very helpful. 
* Is the project more about student experience or developing new products?
** There is nothing wrong with projects focused on progressing and application or methodology. However, these often fit better as sponsored research. 
** These types of projects have more specific goals and allow us to match students with more experience to help progress the research. 
