= Sponsored Research Projects

The Data Mine's sponsored research projects offer a more targeted and focused analytics project where close collaboration between companies and skilled students drives research and experience-based learning. 

All projects are beneficial for the students. The biggest decision point is around the level of complexity of the topic and the expected results from the project. 

As always, we are happy to brainstorm and discuss further if you have any questions. 

How are sponsored research projects different?
* Sponsored research projects start with higher expectations to achieve complex project goals within the project timeframe. 
* Students are selected for their specific skills and are expected to have analytics experience when joining the project. 
* A member of The Data Mine team will often be more directly involved in the project as well to help provide data science expertise. 

When are sponsored research projects a good fit?
* If you're trying to develop new applications or algorithms that require advanced research and development. 
* If your project is highly specialized and may be difficult for students who are starting their analytics careers. 
* If you want to develop new applications from scratch that requires a high-level of hands-on design and testing. 

[TIP]
====
If you'd like to learn more about the sponsored research projects, please reach out to our team at datamine-help@purdue.edu
====
