= The Data Mine – Data Use Framework

v1.3 - Updated on March 17, 2025

== Overview
This Data Use Framework describes how your data will be transmitted, accessed, stored, used, and disposed of upon Project completion.  In the document below, "sponsor company" refers to the sponsor company that provides data or other resources to students for experiential learning projects (each, a “Project”) coordinated and facilitated by The Data Mine (“TDM”). 

== Data Transmission and Access Restrictions
When possible, the sponsor company should transfer the data directly to TDM's Anvil environment. The Anvil environment is a computing cluster that is part of the ACCESS platform maintained by the National Science Foundation.  Sponsor companies will need to set up an Anvil account and agree to comply with the ACCESS acceptable use policy (https://access-ci.org/acceptable-use/).

File transfer will occur using Purdue’s Globus file transfer tool (https://transfer.rcac.purdue.edu/).  The Anvil environment has team directories that are created automatically and secured to only students on the specific Project team, TDM staff, sponsor company mentors, and IT support team members from Rosen Center for Advanced Computing (“RCAC”). The Anvil system utilizes 2 factor-authentication for all accounts. 

If transfer by Anvil is not possible, the sponsor company should coordinate another method of transmission with TDM staff.

TDM guidelines on data sensitivity and types of accepted data can be found in the https://the-examples-book.com/crp/mentors/legal#sponsor-acknowledgement[sponsor acknowledgement document]. Please note that certain types of data cannot be accepted.

== Data Use
Provided data will only be used for the applicable Project(s). Data will not be shared with any other groups (internal or external to Purdue) without prior direct written consent from the sponsor company. 

== Data Environments
The Data Mine utilizes a high-performance computing environment (HPC) for use in the student Projects, but it can also be an option to utilize the sponsor company's computing environment at the sponsor company’s discretion. Security and setting up student use of the company's technical environment would be the sponsor company's responsibility.

While TDM reinforces the importance of data security, neither TDM nor Purdue University can be held responsible for a student’s failure to comply with directives or policy regarding data. 

== Data Retention and Disposition
TDM stores an archive of all Project files, including data, for legal retention and sponsor company reference in an archival tape system called Fortress. These archives are limited to TDM and RCAC (or Purdue IT) staff only and will not be shared with others. The archives can be deleted at any time upon request of the sponsor company. 
 
Data on Anvil will be removed at the end of the academic year unless otherwise requested by the sponsor company. Snapshots of the filesystem containing this data are made periodically by the RCAC team, and are retained for a number of months at their discression.  Visibility to these snapshots is governed by membership in the various corporate partner groups.  These groups are purged at the end of the academic year.  These means that even if the data still exists in these snapshots after the end of the year, the students will no longer be able to see them because they are no longer in the corresponding group.

== Breach Response and Notification
TDM follows Purdue's policies on security incidents. In the event of a breach of secure data, TDM team will work with Purdue Security to resolve the issue and notify any affected parties. Purdue security policies can be reviewed at: https://www.purdue.edu/securepurdue/services/report-security-incident.php
