= Frequently Asked Questions About Partnership
This section answers some frequently asked questions. Please email datamine@purdue.edu for any other questions.

// == content
== What is the time commitment?

During the academic year, from late August until the end of April, mentors meet with their students for 50 minutes per week. This meeting is usually online unless the mentor is local or visiting West Lafayette. In the summer, we meet to check in every other week for 25 minutes to plan for the academic year. 

[NOTE] 
==== 

From previous experiences, projects benefit the most when mentors contribute more than 50-minutes-a-week. In the past, mentors have scheduled weekly meetings with their TAs and have also attended some labs in person or virtually.

====

== Does my project make sense for The Data Mine?

The Data Mine has done a plethora of projects over the years covering many concepts and domains. 

Please see current/previous years' https://projects.the-examples-book.com/projects/by-year[project descriptions] and https://datamine.purdue.edu/symposium/[end-of-year symposium posters].

== What are the key elements to a good Data Mine project?

The best Data Mine projects have these two elements:

1. *Data intensive project*: We seek projects with large data sets (an Excel spreadsheet doesn't count).
2. *Committed mentoring*: It is important to have a corporate employee who can meet and mentor the students.

== What resources do we get for partnering with The Data Mine?

* 2 paid Teaching Assistance (TAs) per project 
* Team of undergraduate and graduate students of diverse backgrounds
* Data Scientist support 
* Corporate Partner Manager 
* Connections to campus partners 

== How many mentors can be on a project?

Typically, corporate partners provide 1 or 2 primary mentors per project.

== Can mentors bring in guests to help teach specialized topics that can further the development of the project?

Yes, mentors are more than welcome to bring in guests to the 50-minute mentor meeting. We ask that the mentors let their CRP Liaison know prior so the meeting invitation can be sent. 

== How many students per group?

A project can have between 5-12 students.

== How are projects organized throughout the academic year?

We use Agile to organize each semester into 7 two-week-sprints. At the end of each sprint, students are encouraged to present their work to their mentor for feedback. Students complete 7 sprint reports throughout the semester which are graded by their TA. 

== How much time does a student spend each week on the project?

Students receive 3-credits for each semester spent on the project. Students attend two organized meetings each week (50-minute online meeting & 2-hour lab). Students are expected to work approx. 7 additional hours outside of class. 

== Can a project carry over into the next academic year?

Certainly! Projects can span across multiple academic years. We recommend that students are thoroughly documenting their work for future students.

== Can a mentor visit labs in-person?

Yes. Mentors are welcome to join the in-person labs. Arrangements can be made with TDM staff.

== Can students visit corporate partner facilities?

Yes. If corporate partners are within driving distance, we can help organize a day and time to have the students visit the facilities.

== How are students selected for each project?

Students sign-up for a project similar to how they sign-up for their classes. Project availability is at a first-come-first basis. If the project requires more upperclassmen/graduate students, please let TDM staff know.

== How does data get shared to students?

There are multiple ways for the students to access the data. Below are a two common routes.

1. https://www.rcac.purdue.edu/compute/anvil[Anvil]: Purdue's On-campus High-Performance-Computing Cluster (HPC)
2. Company Internal Environment: Virtual Machines, Laptops, etc.

== Can The Data Mine guarantee deliverables?

We cannot guarantee deliverables for our 3-credit experiential learning projects. For deliverable-driven projects, The Data Mine and the corporate Partner can work together on a sponsor research contract (SPS).

