= Corporate Partner Mentor Resources 

== Summer 2023 Checklist
&#10003; *Project Descriptions* for academic year 2023-24 are required by May 15, 2023. Review xref:project_descriptions.adoc[Project Description Guidelines] for instructions, requirements, and examples.

&#10003; *Summer Planning Meetings* for academic year 2023-24 are required to begin by May 31, 2023. Schedule meeting series with your Data Mine contact using our link:https://calendly.com/datamine[Calendly Home Page].

&#10003; *Project Charters* for academic year 2023-24 are required by June 2, 2023. Review xref:projectcharter.adoc[Project Charter Guidelines] for instructions, requirements, and examples.

&#10003; *Sponsorship Acknowledgments, Addendums, NDAs, and IP Agreements* for academic year 2023-24 are required by July 21st, 2023. Review xref:legal.adoc[Legal and Funding] to download this year's sponsor acknowledgment and for sample NDA/IP Agreements.

&#10003; *Data Sharing* for academic year 2023-24 is required by July 31, 2023. Review xref:technicalresources.adoc[Technical Resources] for instructions on our three modes of sharing data: Purdue's Compute Resources (Anvil), Virtual Desktop, or sending Laptops.

&#10003; *Develop a Student Engagement Strategy* before term starts on August 21st, 2023. Review xref:mentoringbestpractices.adoc[Mentor Best Practices] for considerations on how to best work with students and young professionals.

&#10003; *Become familiar with The Data Mine Logistics* before term starts on August 21st, 2023. Review xref:semester_logistics.adoc[Fall 2023 Logistics] learn about Microsoft Team platforms, email lists, rosters, NDA signing, data sharing, meeting time blocking, and Anvil access.

//Welcome to the corporate partner mentor resource section for The Data Mine Corporate Partnership Program!

//If you are interested in *learning* more about The Data Mine, please refer here: https://datamine.purdue.edu/about/

//If you are interested in *partnering* with The Data Mine, please refer here: xref:partner.adoc[Roadmap To Partnership]

//If you are ready to *begin project planning*, please refer here: xref:summerchecklist.adoc[Summer Checklist]

[NOTE] 
==== 
The content in the "Mentor" section is for _you_ and we'd love if it was made with your help too. 

If you have content that you would like to contribute, please send it to datamine@purdue.edu or make link:https://the-examples-book.com/book/how-to-contribute[contributions directly via GitHub.] 
====

