= Legal & Funding 

== Sponsor Acknowledgement

*[New Partners]* Our industry partners sign this Sponsor Acknowledgment (SA) link:https://datamine.purdue.edu/corporate/docs/sponsoracknowledgment.docx[(click here to download full sponsor acknowledgment)]. The SA covers five years of partnership, but it does not obligate your company to five years of projects. 

*[Renewing]* After executing the full SA, please renew each year with this addendum for years two through five. link:https://datamine.purdue.edu/corporate/addendum.docx[(click here to download addendum)]


Return the signed sponsor acknowledgment or addendum via email to datamine@purdue.edu. The SA will be routed through Purdue's Legal Counsel. You will receive a fully executed SA. 


== NDA
• Most companies require the students and Data Mine staff to sign a NDA at
the start of the project.
• The NDA is provided by the company. If you do not have a NDA, here is a generic one provided by Purdue Legal Counsel. 
** xref:attachment$TEMPLATE_NDA_and_IP_Assignment_to_Sponsor_student_only.docx[Template for student only]
** xref:attachment$TEMPLATE_NDA_with_Sponsor_Student_and_Staff.docx[Template for student and staff]
• The NDA must be between an individual (student or staff) and the company. Purdue will not sign a NDA on behalf of the students. 
• To make it easy for you, Data Mine staff handle the logistics of getting the NDAs signed by students and staff. We return a zip file of all signed documents shortly after the fall semester starts. 

== IP
• At Purdue University, students retain their IP. Students can choose to license or assign it to the company at no cost.
• Purdue faculty and staff cannot sign any agreement regarding IP for projects running under the Sponsor Acknowledgement. Faculty and staff can only sign an IP agreement under sponsored research contracts. 

== Funding
There are two funding levels for our credit-bearing student experience: 

* $20,000 for 5 students and 1 project
* $40,000 for 25 students and multiple projects

An invoice will be sent electronically to your accounts payable department after your sponsor acknowledgment is fully executed.
