= Legal & Funding 

== Sponsor Acknowledgment

*[New Partners]* Our industry partners sign this Sponsor Acknowledgment (SA) xref:attachment$sponsoracknowledgment.docx[(click here to download the full sponsor acknowledgment)]. The SA covers five years of partnership, but it does not obligate your company to five years of projects. 

*[Renewing]* After executing the full SA, please renew each year with this addendum for years two through five. xref:attachment$addendum.docx[(click here to download the addendum)]

Return the signed sponsor acknowledgment or addendum via email to datamine@purdue.edu. The SA will be routed through Purdue's Legal Counsel. You will receive a fully executed SA. 

*Differences between Course-Based Experiential Projects versus Sponsored Research* The differences between these two types of projects are summarized in a document. xref:attachment$Contracting-And-IP-The-Data-Mine.docx[(click here to download a chart describing the differences)]  For ease of understanding, see this graphic as well.  xref:attachment$Exp-VS-SPS-Reference-Guide.png[(click here to download a graphic describing the differences)]


== NDA
• Most companies require the students and Data Mine staff to sign a NDA at
the start of the project.
• The NDA is provided by the company. If you do not have a NDA, here is a generic one provided by Purdue Legal Counsel. 
** xref:attachment$Purdue_Template_NDA.docx[Template for student and staff]
• The NDA must be between an individual (student or staff) and the company. Purdue will not sign a NDA on behalf of the students. 
• To make it easy for you, Data Mine staff handle the logistics of getting the NDAs signed by students and staff. We return a zip file of all signed documents shortly after the fall semester starts. 

== IP
• At Purdue University, students retain their IP. Students can choose to license or assign it to the company at no cost.
• The IP Assignment Agreement is provided by the company. If you do not have an IP Assignment Agreement, here is a generic one provided by Purdue Legal Counsel.
** xref:attachment$Student_NDA_with_ Sponsor_2023.docx[Template for student only]
• Purdue faculty and staff cannot sign any agreement regarding IP for projects running under the Sponsor Acknowledgment. Faculty and staff can only sign an IP agreement under sponsored research contracts. 

== Funding for our credit-bearing student experience
* $20,000 for 5-15 students and 1 project

An invoice will be sent electronically to your accounts payable department after your sponsor acknowledgment is fully executed.
