= Fall 2023 Mentor Syllabus - The Data Mine Corporate Partners

// [IMPORTANT]
// ====
// *CONTENT STILL UNDER CONSTRUCTION FOR FALL 2023!!!!*
// ====

= Fall 2023 Course Schedule

== Assignment Schedule

Each project will have a project charter with project-specific goals and dates, but here is the schedule for ALL Corporate Partner mentor for the general due dates of assignments and important notes. 

Assignment due dates are listed in *BOLD*. Other dates are important notes.

++++
<iframe width = "800" height = "400" title="Student Schedule" scrolling="yes"
src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQ3Ehd9W5ieG2Ke_S5lQM6P4iKBa5ao01H_KBzpd0LSv4Ei7UokFD-qzMwUA3vTD1zP5uDmYU2w6dpl/pubhtml" & wdDownloadButton="True"></iframe>
++++

== Sprint Schedule

All sprints will have the same due dates, but you will see below that the sprint start and end dates are slightly shifted depending on when a team has their lab (2 hours) and lecture (50 minutes). 

This is so that sprints always start with a lec and follow the format lec-lab-lec-lab.

A visual of this schedule is available in the xref:agile:ceremonies.adoc#sprint-schedule[Agile training section on ceremonies]. 

// ++++
// <iframe width = "800" height = "400" title="Sprint Schedule" scrolling="yes" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTK43pmMY_ZARkrKC_paSV8RhtymTBed6PBJjcr7RNIHHWh5ta1b-u-pVattmVUOw44DMjOmQTS6BXo/pubhtml" & wdDownloadButton="True"></iframe>
// ++++
===
