= Roadmap to Partnership & Renewal

== 1. Let's discuss - schedule a call

Whether this is your first introduction to The Data Mine or you are a dear friend. We look forward to talking in more detail with you during a 25-minute call. 

You are welcome to schedule a call with us on link:https://calendly.com/datamine[our Calendly page] or email us at datamine@purdue.edu


== 2. Project Description 

View our xref:project_descriptions.adoc[project description guidelines] to help you define your customized project. 

== 3. Legal & Funding

Our industry partners sign this Sponsor Acknowledgment link:https://datamine.purdue.edu/corporate/sponsoracknowledgment.docx[(click here to download)]. Most of our partners require students and staff to sign a NDA. As an additional option students can be required to sign an IP agreement. Funding levels are listed in the Sponsor Acknowledgment.  Partners who already signed a Sponsor Acknowledgment within the last 5 years can simplify things by just signing a new Addendum link:https://datamine.purdue.edu/corporate/addendum.docx[(click here to download)]

Visit the xref:legal.adoc[Legal & Funding] page for details.


== 4. Summer Planning 

We are excited to meet with you every other week for 25 minutes during the summer to plan the specifics of your project(s). Visit the xref:summerchecklist.adoc[Summer Checklist] page for a readiness checklist. 

== 5. Renewal

The renewal process for the next academic year (August - May) starts in January, but please note that we are delighted to discuss additional projects at any time. 

We look forward to building a lasting relationship with your company, developing a deep connection over the many years of partnering together. 

== Questions? 

Check out our xref:faq.adoc[FAQ page] or email us. 



