= Project Tips and Tricks

This section is to provide common tips and tricks when scoping your project for The Data Mine. If you have a tip that you've found helpful, please let us know! You can email us at datamine@purdue.edu or contribute to our GitHub directly. 

== Tips and Tricks

. Give the students an end goal and let them find the steps to get there. 
    * We totally understand that not every project is going to have an end goal, and that's ok! 
    * If you do have an end goal it gives the students something to work toward throughout the year. 
. If you're having trouble thinking of a research area ask yourself or your coworkers the questions below. These often generate great problem statements. 
    * What are major paint points that we deal with? 
    * What information do we wish we knew, but don't currently have?
    * Are there any things that we've always thought were true, but want to test with data?
. Once you have a project in mind, pressure test it with your team. Ask a few of the questions below:
    * What data will we use for the project?
    * Does this feel like a good scope for an academic year project?
    * Is there any 3rd party data that we could guide the students to incorporate in their research?
    * Are we clear on the work that we'd like the students to focus on?
    * Where will they start and how will the work progress?
. Remember:
    * Almost all of the projects will pivot in some way during the year. This is totally ok and good for the students to experience. 
    * It's good to challenge the students, but they often benefit from more guidance at the start of the project until they get familiar with the research. 
    * If you feel stuck our team is here to help! We love to ideate and are here to work through the project outlines and help to brainstorm. Contact us at datamine@purdue.edu.