= Project Charter Recommendations

This template is a guide to assist in providing a project charter for the students. Students need to know *what* they are working towards and *why* it is important. With clear guidance and motivation, the students will take ownership and use their creativity to work on the project. 

== About CRP

=== About the Company

* What does your company do?
* History

=== About the Specific Department/Team

* What is your team’s role in relation to the company?

=== About the Mentor

* Title
* Summary of job responsibilities
* Contact
* Availability

== Project Description

=== Summary

* A bit more detailed than the project description.
* What is the motivation?
* Who are the stakeholders?
* How is it going to be used?

=== Objectives

* Contexualize the project
* What are the main goals?
* What is the projected product?
* What are expected outcomes after students complete the AY?

=== About the Data

* What is the purpose of the data?
* How is/was it collected?
* Any preprocessing done prior to student receiving the data?
* How is it currently used?

== Tentative Schedule

== Getting Started

* Where should students start? 
* Reading list/resource list (domain specific and/or technical)

=== Goals/Milestones

=== Fall

* Sprints
* Ideally understanding the data, exploration, literature review, research on proposed methodology, initial building of the product (web app, ML model, data analysis, etc).

=== Spring

* Sprints
* Ideally moving forward with building the product and continual improvement for each sprint. 
* Deployment
* Outlook for a good stopping point prior to Symposium

== Expectations

=== Team Composition 
* Corporate Partner Mentor(s) (employees at the company)
* 1 TA (student, 10 hours per week)
* 5-10 undergraduate students 
* 2-5 graduate students 
* The Data Mine staff 
* Faculty 

=== Teams/Roles
Follow Agile methodology.

Roles:

* Mentor (Product Owner)
* TA (Scrum Master)
* Students (Developers)
** Graduate Students
** Undergraduate Students

Sub-teams/student roles
* Sketch of tasks, backgrounds, interests that would help with alignment for the subteams. 

=== Project Expectation
Per the Sponsorship Acknowledgment, this is intended to be a learning experience; there are no guaranteed deliverables, outcomes, or performance. With that being said, we encourage you to set expectations for the students as it allows them to work towards the project goals.

== Preparations

=== Reviewing Materials

==== Required

* What required materials should the students review to understand the project?
* Videos
* Literature
* Articles
* News
* Project examples

==== Optional

* What are other materials that may be interesting to some students if they want to explore deeper into the topic?

=== Tools and Software

==== Required

* What tools and softwares the students need to know to be successful in this project?
* Are there tiers of competency to be part of a sub-teams?
** E.g., at least beginner level in programming, machine learning, domain knowledge, etc. 

==== Optional

* What are tools and software available to the students that are not needed for the project but potentially help or serve as an alternative.

=== Hardware

* What are required hardware or computing?
* E.g., cloud, company’s machine, remote into the company’s environment
** Purdue’s HPC (https://www.rcac.purdue.edu/)
** Student will be using Brown in seminar.


=== Potential Preferences

* Project management tool (E.g. Linear)
* Code management (E.g. GitHub)
* Documentation format (E.g. Wiki)

== Project Tips and Tricks

This section is to provide common tips and tricks when scoping your project for The Data Mine. If you have a tip that you've found helpful, please let us know! You can email us at datamine@purdue.edu or contribute to our GitHub directly. 

=== Tips and Tricks

. Give the students an end goal and let them find the steps to get there. 
    * We totally understand that not every project is going to have an end goal, and that's ok! 
    * If you do have an end goal it gives the students something to work toward throughout the year. 
. If you're having trouble thinking of a research area ask yourself or your coworkers the questions below. These often generate great problem statements. 
    * What are major paint points that we deal with? 
    * What information do we wish we knew, but don't currently have?
    * Are there any things that we've always thought were true, but want to test with data?
. Once you have a project in mind, pressure test it with your team. Ask a few of the questions below:
    * What data will we use for the project?
    * Does this feel like a good scope for an academic year project?
    * Is there any 3rd party data that we could guide the students to incorporate in their research?
    * Are we clear on the work that we'd like the students to focus on?
    * Where will they start and how will the work progress?
. Remember:
    * Almost all of the projects will pivot in some way during the year. This is totally ok and good for the students to experience. 
    * It's good to challenge the students, but they often benefit from more guidance at the start of the project until they get familiar with the research. 
    * If you feel stuck our team is here to help! We love to ideate and are here to work through the project outlines and help to brainstorm. Contact us at datamine@purdue.edu.