= Mentor Expectations & Ideal Qualities


== Commitment
* One hour per week meeting
** Get updates from the team
** Provide feedbacks (Sprint Review)
** Provide domain knowledge, training, education
* Responsive to questions (email or other communication channel)
* Consistent throughout the year
** Regularly available for the team

== Preparation
* Technical and domain knowledge support (or connections to resources within your company)
* Project syllabus outlining fall and spring semester
** Content overview
*** Literatures, lectures, online resources, examples
** Outline the team's roles
*** Mentor(s)
*** TA
*** Students (undergraduate and graduate)
** Goals, milestones, brief timeline
*** Define goals, expectations, and outcomes
*** Use agile to achieve milestones
*** Project charter - students need to know what they are working towards and *why*
*** Frame the project in business needs
** Subgroups/sub-teams
*** Sketch of tasks, backgrounds, interests that would help with alignment for the sub-teams
*** Forming groups can foster more leadership opportunities
** Computing resources/environment
*** Data access, domain resources, etc.
* Guest from within corporate organization
** Students *love* when guests come to present or listen to student presentations

> *The task we had to accomplish felt purposeful and thus made finding the solution more satisfying. I love the way it was structured in sub-teams as it made our individual voices easier to be heard.* Even though I am a freshman and most of my teammates are seniors or graduate students, I felt like I was able to contribute well. I didn't come in with much experience, so that fact that I was able to work on research with [company] was enlightening and extremely fun. - student, AY 2020-21



== Support
* Colleagues within corporate partners
* The Data Mine
** Outreach to faculty
** Data Scientists
** Teaching Assistant

== Approachability
* Open communication 
** Email
** Communication platforms (Slack, Teams, email)
* Other suggestions
** Attend lab
** Office hours


== Accountability

> My favorite memory from The Data Mine is there was a time period where the mentors were very unhappy with the data architect team which was the team I'm in and we had a meeting where they conveyed how they felt. *After this meeting, our team worked really hard and well together to make sure we completed our tasks and do a really good job overall. After we presenter our work, the mentors were very happy with us and proud of the work we accomplished.* This was my favorite experience because it reminded me that it's always important to push through and work through problems no matter how hard so that eventually you will be able to succeed. - student, AY 2020-21


== Adaptability
* Different skill levels
** Team with Graduate/highly technical students
** Team with students just starting their data science experience
** Team with a mix of technical skills
* Challenge the students but understand that this is a learning environment for students   
** 3 credit hour course = 8-10 hours
*** 1 hour mentor meeting
*** 2 hour lab
*** 5 - 7 hours commitment on own

== Engaging
* Student focus
** Student life
*** Course schedule
*** Exams, Breaks
** Aware of student's development
*** Technical/Non-technical
**** Technical students can lead the more advance tasks
**** Non-technical can tackle the low-hanging fruits

> Best memory? Probably at the very beginning of the project where I just shared a simple graph in the general group chat. A day later [my Corporate Partner Mentor] messaged me and said it was being shared around the office! *It felt good to make a real impact.* - student, AY 2020-21

