= Semester Logistics and Guidelines

The Data Mine Corporate Partners Program has continued to grow thanks to wonderful partners!

As our program continues to grow, we continue to make changes to automate processes and complete work efficiently. Below you will find some of the changes for Fall 2025.

== Mentor Syllabus

[cols="1,1"]
|===
|Activity
|Date

|First day of Fall 2025 class
|Mon, 8/25

|Labor Day (No CRP meetings/classes)
|Mon, 9/1

|Fall Break (No CRP meetings/classes)
|Mon, 10/13 - Tue, 10/14

|*Mid-semester Feedback from Mentors and TAs*
|*Due Wed, 10/29 by 11:59 PM ET*

|*DRAFT Fall Presentation*
|*Due Wed, 11/5 by 11:59 PM ET*

|*FINAL Fall Presentation*
|*Due Wed, 11/19 by 11:59 PM ET*

| *Final Presentation Week*
| *Mon, 12/8 - Fri, 12/12

|Final exam week (No CRP meetings/classes)
|Mon, 12/15 - Sat, 12/19

|===

*Important Due Dates in BOLD*

link:https://the-examples-book.com/crp/students/fall2025/syllabus/[Fall 2025 Student Syllabus] / link:https://catalog.purdue.edu/preview_program.php?catoid=16&poid=31706[2025-26 Academic Calendar]

////

[cols="1,1"]
|===
|Activity
|Date

|First day of Spring 2024 class
|Mon, 1/8

|MLK Day (No CRP meetings/classes)
|Mon, 1/15

|*Mid-semester Feedback from Mentors and TAs*
|*Due Wed, 3/6 by 11:59 PM ET*

|*Symposium Draft Video and Poster*
|*Due Wed, 3/6 by 11:59 PM ET*

|Spring Break (No CRP meetings/classes)
|Mon, 3/11 - Fri, 3/15 

|*The Data Mine Symposium*
|*Wed, 4/24*

|*Final Feedback from Mentors and TAs*
|*Due Friday, 4/26 by 11:59 PM ET*

|Last day of Spring 2024 classes
|Fri, 4/27

|Final exam week (No CRP meetings/classes)
|Mon, 4/29 - Sat, 5/4

|===

*Important Due Dates in BOLD*

Student Syllabus: https://the-examples-book.com/crp/students/spring2024/syllabus[Spring 2024 syllabus]

Spring 2024 Academic Calendar : https://catalog.purdue.edu/preview_program.php?catoid=16&poid=27594&_ga=2.139246646.40359815.1702925274-1283552926.1696879208[2023-2024 Academic Calendar]

////

== Team Platform: Microsoft Teams
MS Teams can host meetings, files, a team calendar, notebooks, links to The Examples Book and assignments, task dashboard(s), and so many more features. 

Data Mine staff will handle member management of teams. If you have concerns about your team management, please speak to your Corporate Partner Liaison. 

== Email Lists
MS Teams automatically creates email lists which can be used to send things to an entire team. These will be shared as soon as each Team is created. 

You will not have to create your own list.

== Roster
You can see all members of your team in MS Teams; this list can act as your roster.

You can view members of your team by selecting the following: (i) clicking on your team (ii) selecting the 3 dots next to the team name (iii) selecting manage team (iv) clicking on the Members and guests drop down. Here you can see the student names, emails, and role on the team as "member." 

[NOTE]
====
Disclaimer: The roster may continue changing till registration closes, for the students. Movement should settle down during week 1.
====

== NDA Signing Process
The NDA signing process takes about 1-2 weeks. Please be patient with us as we make sure students have completed their NDA to access your data. 

== Data Sharing
We strongly encourage you to *NOT* share your data the first or second week of the semester. We want to make sure NDAs are signed.

=== What should I do instead of sharing data immediately?
We strongly encourage you to *DO* the following.

1. Get to know your team! It is really helpful to know each member on your team. Get to know what drives them, what kind of support they may need, learn about their experiences. Mentoring is a two way street; maybe you can learn something new from your team. 
2. Focus on the project scope and make sure everyone understands what is being asked. This will help keep the project on track. One way to make sure all student understand is by asking everyone to describe your team project in two sentences or less in their own words. This can help you, as a mentor, identify what students think is important about your project and areas that may be over looked. 
3. Domain/background. Students are of different ages with different experiences. Providing readings or topics of research will help the students better understand the project scope or process. This step is valuable when you publish as well. Students can document what they learn in their bi-weekly documentation assignment. 
4. Outline the processes or tools your team is interested in using. Then when the team dives into the data there is already a plan in place. The students should also add the process and tools to the documentation they complete. 

== Meeting Time Blocking
Please please please remember to block your meeting time with your team on your schedule weekly. 

Mentors have a 50 minute meeting with their team each week to complete Sprint Planning or a Sprint Review. These are great opportunities to learn about what the team has completed or cover anything with the team as a whole. We want to make sure our wonderful mentor, you, are there to provide guidance, domain expertise, and feedback on your project's progress. 
It is recommended to book a full hour for this meeting in case there are questions at the end or the meeting runs a little late. 

You can find your project time in your project description which can be found on our link:https://projects.the-examples-book.com/projects/[Projects Page]. 

== Anvil Access
If you are hosting your data on Purdue HPC Anvil and would like an account, please follow the link below to set up an account. 

Account on Purdue HPC Anvil
If you plan on hosting your data at Purdue, we will be using link:https://www.rcac.purdue.edu/compute/anvil[Anvil]. You can link:https://the-examples-book.com/starter-guides/anvil/access-setup[set up an account here].

== More questions?
Please check out the resource pages provided or contact your Corporate Partner Liaison. We are happy to help and answer any questions you may have!
