= Site Visits

Site visits are often the highlight of a student's interaction with corporate partners. Getting a trip off campus and exploring a new place is novel and give students a glimpse into a potential future.

The remainder of this page provides information about the planning of site visits and thing students would be interesting in seeing.

== Who
Students of a corporate partner project, their TA and supporting Data Mine staff members.

Mentors should consider inviting collogues from their company to meet and speak with students.

== What

Student Wishlist:

 - Internship / Career Opportunities
 - Data centers
 - Employees talk about things they're passionate
 - Office spaces
 - Manufacturing

== When
While trips can occur at any point in the work week it is useful to keep in-mind student's class schedule to minimize conflicts. Therefore it is often recommended to make use of the student's LAB period, as this is time they have already set aside for The Data Mine.

For example: if a team's LAB was 2-4pm then a trip might be planned from 1-5pm to maximize this time.

== Where
At your company office, manufacturing space, laboratory, farm field, wherever!

== Why
Great opportunity to show students what your company environment looks like.

== How
Data Mine staff members will provide transportation to your faculty. Purdue policy allows for 8 persons per vehicle (including the driver), so multiple vans may be rented.