= Summer Planning & Readiness Checklist 

== &#10003; Summer Meetings

link:https://calendly.com/datamine[Schedule a 25-minute biweekly meeting] so we can check in throughout the summer and plan the specifics of your project(s). We'll work through the checklist below. 

== &#10003; Project Description

Have we received your project description? If not, check out the xref:project_descriptions.adoc[Project Description Guidelines]. 


== &#10003; Legal

Have you finalized the Sponsorship Acknowledgment? This process might take some time thus we suggest our corporate partners start early in the summer.

Details are here on the xref:legal.adoc[Legal and Funding] page. 

== &#10003; Project Charter 

The project charter should serve as the go-to reference for the project; this will help the students understand the company, the purpose of the project, the timeline, and other expectations.

Visit the xref:projectcharter.adoc[Project Charter] page for an outline, details on the course schedule, grading, and Agile. 


== &#10003; Technical 

Visit the xref:technicalresources.adoc[Technical Resources] page for details on topics such as:

* data sharing
* computing environment

== &#10003; Team Environment & Mentoring 

* Have you identify a committed personnel within your company to serve as the product owner and oversee the project? 
* Have you thought about creating a welcoming team environment and team building?
* Are you prepared to work with your TA? Prepared for the various student roles?

Our students thrive with the help of an engaging mentor. This personnel does not have to be a data scientist, but we encourage this individual to be attentive and support the students the best they can. Past corporate partner mentors have served as the domain expert, technical expert, or both!

Check out the xref:mentoringbestpractices.adoc[Mentor Best Practices] page for tips. 







