= Summer Planning & Readiness Checklist 

== &#10003; Project Description

*Project Descriptions for Academic Year 2024-25 are required by April 15, 2024.*

Project descriptions are made available to students considering participation in The Data Mine. Submitting your project description early allows students first-to-register (typically upper-classmen) a chance to choose your project. 

Have we received your project description? If not, check out the xref:project_descriptions.adoc[Project Description Guidelines]. 

{sp}+

== &#10003; Summer Meetings

*Summer Meetings are required to begin by May 31, 2024*

Set up dedicated time to tackle the Summer Checklist with one of our Corporate Partner Team Members. link:https://calendly.com/datamine[Schedule a 25-minute biweekly meeting] so we can check in throughout the summer and plan the specifics of your project(s). During the meetings, we'll work through the checklist below. 

{sp}+

== &#10003; Project Charter 


*Project Charters for Academic Year 2024-25 are required by June 30, 2024.*

The project charter should serve as the go-to reference for the project; this will help the students understand the company, the purpose of the project, the timeline, and other expectations.

Visit the xref:projectcharter.adoc[Project Charter] page for an outline, details on the course schedule, grading, and Agile. 

{sp}+

== &#10003; Legal

*Sponsorship Acknowledgments, Addendums, NDAs, and IP Agreements for Academic Year 2024-25 are required by June 30, 2024.*

* Have you finalized the Sponsorship Acknowledgment or Addendum? 
* If students and staff need to sign a Non-Disclosure Agreement, have you shared it with us? 
* If applicable, have you shared the IP document? 

Details are on the xref:legal.adoc[Legal and Funding] page. 

{sp}+

== &#10003; Technical and Data Sharing Plan

*Data Sharing for Academic Year 2024-25 is required by July 31, 2024.*

Setting up systems and testing this environment before your project begins is key to getting your student project team off to a quick start when the semester begins. Visit the xref:technicalresources.adoc[Technical Resources] page for details on topics such as:

* data sharing
* computing environment
* technical resources

{sp}+

== &#10003; Team Environment & Mentoring 

Creating a welcoming and productive online environment takes a little extra preparation and is well worth the effort. A few questions you can reflect on...

* Have you identified a committed mentor within your company to serve as the product owner and oversee the project? 
* Have you considered the welcoming team environment you hope to create and team building with the students?
* Do you feel prepared to work with your (Teaching Assistant) TA? 
* Have you thought about the different roles students may have on the project team? 

We have compiled several resources related to these topics. Check out the xref:mentoringbestpractices.adoc[Mentor Best Practices] page for tips. 
  
{sp}+

== &#10003; xref:semester_logistics.adoc[Fall 2024 Logistics]
Navigate to the xref:semester_logistics.adoc[Fall 2024 Logistics] to get some of your logistical questions answered.


Find more about:

* Team Platforms
* Email Lists
* Roster 
* NDA Signing Process
* Data Sharing
* Meeting Time Blocking
* Anvil Access

{sp}+

//== &#10003; Mentor Community

//* Connect with other mentors by joining the link:https://join.slack.com/t/dmcrpmentors/shared_invite/zt-18synsjhd-0qTg~9rtWvrb7uLS9Wj7Fg[Mentor Slack group here].

//* Join us this summer 2023 for biweekly summer sessions during the lunch hour.

//** Who: All continuing and new mentors for fall 2023 - spring 2024

//** Where: Zoom (email us datamine@purdue.edu for the invite link)

//** What: Topics in table below

//** When: See table below

//[%header,format=csv]
//|===
//Date, 	Time, 	Location, 	Topic
//"Tuesday, May 30", 	12:00 – 1:30 PM ET, 	Online, 	Summer Planning Kickoff 
//"Monday, June 12", 	12:00 – 12:45 PM ET, 	Online, 	Technical resources & data sharing
//"Monday, June 26", 	12:00 – 12:45 PM ET, 	Online, 	Shared best practices: networking with other CRP mentors 
//"Monday, July 10", 	12:00 – 12:45 PM ET, 	Online, 	Engaging with your TA  
//"Monday, July 24",	12:00 – 12:45 PM ET, 	Online, 	Agile & project charter  
//"Monday, August 7",	12:00 – 12:45 PM ET, 	Online and in-person option for those local or able to travel, 	Open discussion and networking for the final weeks of summer planning
//"Monday, August 15", 	12:00 – 12:45 PM ET, 	Online, 	Transition from planning to action: semester starts in 1 week 
//|===
