= Summer Planning & Readiness Checklist 

== &#10003; Summer Meetings

link:https://calendly.com/datamine[Schedule a 25-minute biweekly meeting] so we can check in throughout the summer and plan the specifics of your project(s). We'll work through the checklist below. 

== &#10003; Project Description

Have we received your project description? If not, check out the xref:project_descriptions.adoc[Project Description Guidelines]. 


== &#10003; Legal

* Have you finalized the Sponsorship Acknowledgment? This process might take some time so we suggest starting early.
* If students and staff need to sign a Non-Disclosure Agreement, have you shared it with us? 
* If applicable, have you shared the IP document? 

Details are on the xref:legal.adoc[Legal and Funding] page. 

== &#10003; Project Charter 

The project charter should serve as the go-to reference for the project; this will help the students understand the company, the purpose of the project, the timeline, and other expectations.

Visit the xref:projectcharter.adoc[Project Charter] page for an outline, details on the course schedule, grading, and Agile. 


== &#10003; Technical 

Visit the xref:technicalresources.adoc[Technical Resources] page for details on topics such as:

* data sharing
* computing environment
* technical resources

== &#10003; Team Environment & Mentoring 

* Have you identify a committed mentor within your company to serve as the product owner and oversee the project? 
* Have you thought about creating a welcoming team environment and team building with the students?
* Are you prepared to work with your TA? 
* Have you thought about the different roles student will have? 



Check out the xref:mentoringbestpractices.adoc[Mentor Best Practices] page for tips. 



== &#10003; Mentor Community

* Connect with other mentors by joining the link:https://join.slack.com/t/dmcrpmentors/shared_invite/zt-18synsjhd-0qTg~9rtWvrb7uLS9Wj7Fg[Mentor Slack group here].

* Join us this summer 2022 for biweekly summer sessions via lunch.

** Who: All continuing and new mentors for fall 2022 - spring 2023

** Where: Zoom (email us for the invite link)

** What: Topics in table below

** When: See table below

+
--
[%header,format=csv]
|===
Date, 	Time, 	Location, 	Topic
"Monday, May 23", 	12:00 – 1:30 PM ET, 	Online link:https://youtu.be/XJAU19Qogdk[(recording)], 	Summer Planning Kickoff 
"Monday, June 6", 	12:00 – 12:45 PM ET, 	Online link:https://youtu.be/cduerMq_Ih4[(recording)],	Technical resources & data sharing
"Monday, June 20", 	12:00 – 12:45 PM ET, 	Online and in-person option for those local or able to travel, 	Shared best practices: networking with other CRP mentors 
"Tuesday, July 5", 	12:00 – 12:45 PM ET, 	Online, 	Engaging with your TA  
"Monday, July 18",	12:00 – 12:45 PM ET, 	Online, 	Agile & project charter  
"Monday, August 1",	12:00 – 12:45 PM ET, 	Online and in-person option for those local or able to travel, 	Open discussion and networking for the final weeks of summer planning
"Monday, August 15", 	12:00 – 12:45 PM ET, 	Online, 	Transition from planning to action: semester starts in 1 week 


|===

--
+



