= Technology Licensing

The Data Mine is continually striving to give students new experiences related to analytics. This includes new technologies and tools that are being launched every day. 

If you have a new technology that you would like the students to use, please let our team know as soon as possible. 

That way we can work with you to understand the technology's requirements and discuss how it could be potentially deployed for student use. 

[IMPORTANT]
====
The Data Mine does not have budget to support student technology licenses. 

We are happy to see if a free academic version of the software is available or to use your company's license if possible. 

Purdue University also has enterprise student licenses for applications like ArcGIS that can be used by anyone with a Purdue email.

Paid Solutions Include:

* Power BI / Tableau
** This is related to publishing the dashboard. PowerBI desktop is free to download.
* Social Media APIs 
** Many APIs, like Twitter/X, have a paid option with better features. 
* AWS or other cloud solutions
** There may be free options for students, but they need to be cautious to ensure that they aren't charged. 
* Other paid or subscription-based analytics platforms
====