= Technical Resources

== Data Sharing 

*How will the students acquired the data?*

One of the most important aspects of a data science project is, of course, the data! It is essential to understand how the students will obtain the data and plan for potential obstacles (account set up, data requests, transfer to RCAC data depot, etc.). We want the students can access to the data near the beginning of the semester!

=== Options
. Utilizing RCAC (Anvil)
. Students connecting to company's environment (VPN, cloud, etc.)
. Sending hardware to the students

*Is the data complex enough for the project?*

A data project will not be intense enough if the data only contains a few observations and a handful of variables. We can discuss this topic in more detail with one of our Senior Data Scientists.

== Hardware/Software
*What are some required software and hardware?*

To work on the projects, the students need to know what they will be using to accomplish the tasks. We will discuss specifics tools you may have and what students have access to in The Data Mine.

