= Words of advice from mentors

[NOTE] 
==== 
Have you mentored students in The Data Mine? Would you like to share your advice? Please send your tips to datamine@purdue.edu and we'll feature them here. 
====

== Mentor Panel - 2025 Symposium

Hosted by Bryce Castle, this panel highlights mentors of the program and gathered their perspective on scoping projects, managing flexibility, indicators of success, and mentor purpose. Featuring Toby Hendricks (Elevance Health), Timothy Olojede (Microsoft - Minecraft), Katelyn Brandt (BASF), and Raja Allmdar Tariq Ali (Student Teaching Assistant).

++++
<iframe  class="video" width="560" height="315" src="https://www.youtube.com/embed/R738TBylz60" title="YouTube video /player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

=== scoping projects
"Making sure students had the proper resources in place as well as a tangle outcome. They'll be much more effective with a tighter scope, but giving them a little bit of ability to grow is very important."
-- Toby

"You start with that big idea or big question and then you break things down into pieces to estimate level of effort or level of complexity. Try to use agile methodologies, like 2 week sprints, to remain flexible and address questions."
-- Timothy

"Students are looking for in-demand skills, as they are looking to gain experience for the job market. Student want to grow, they don't want to be hand-held during the project. Give students the resources they need to challenge and lead themselves."
-- Raja

=== managing flexibility
"I really try to coach students through that [how do we get there, side projects, milestones] so they get as much out of this experience as we get out as a corporate mentor."
-- Katelyn

"What I love about the The Data Mine is that its teaching me what I don't know right now. So much of our base code still happens in the academic setting, way before it hits industry. So I always leave it up to students, dedicating a sprint or two, to let them go explore. No direction from me; this is their project how do you want to solve it?"
-- Katelyn

"I like to think about it in these three questions: What are we trying to solve? Why is it importance? How do we solve it? I [as a mentor] focus on the 'what' and the 'why', allowing them to be creative on the 'how'. My way might be old, and [the students] ways are probably newer and probably better then what I have."
-- Timothy

"I never told the student that they were absolutely wrong in any sort of capacity. I wanted them to learn the better ways of doing things and navigate the trial and error of how to do things. Its important to establish those norms, understanding where they can't go and where they can't go based on what we can provide to them and how we can guide them moving forward."
-- Toby

=== indicators of success
"Students want to feel that what they've done is valuable, make sure that they can find that connection between what they've done and how it will be used."
-- Toby

"Sometimes students just come up with a great idea and they surprise me, they challenge me and they're like, well, if I can solve this, I can solve this, and that will answer your question."
-- Katelyn

"It was more about professional growth rather than the technical growth. You want to make sure you're getting the deliverables done, but at the same time you want to make sure you're establishing those relationships with the mentors, with the students, that will go beyond just the classroom once the project is done."
-- Raja

=== mentor purpose
"They set out clear deliverables at the start in the broader charter, and they also encouraged the students. And they also reminded the students frequently on why we were doing this in the first place; connecting the technical aspects to the business values. Encouraging the students as well is pretty useful, especially when moral is low, like when midterms are coming up."
-- Raja

"I don't necessarily assign the roles, I let them self-assign, but I help them break down the project and then rely on my excellent TAs and the students to self-define and manage it."
-- Katelyn

"When I see a challenge, maybe someone that's always very surprised for instance, I pay attention to that, and so I reach out to find what's going on. Just listening [to the student], sometimes it's all they need to be able to actually come back in and fully integrate it into the project."
-- Timothy

=== words of advice
"Put a lot of effort into your project charter. I continuously point that back to the students saying there are resources in there that you can make use of, the goals are in there, all the roles have been defined within there. The more that you can put into a charter that makes sense, the easier it will be for you and the students to move forward with things."
-- Toby

"What we do as mentors goes a long way with the lives of the students. We're shaping a career and we're shaping their whole lives."
-- Timothy

"I always know when a student is after their first year in The Data Mine, as there's so much growth in their first year in The Data Mine. And what it shows the most is how much they're willing to ask me questions, spur of the moment, without fear, and everything like that."
-- Katelyn

"From a team perspective, I would say doing one-on-ones with the TAs and the students really helps. Just talking about the project as well as their personal life."
-- Raja


== Alumni Panel - 2025 Symposium

Hosted by Virginia Vought, this panel highlights alumni of the program and the value it provided after graduation. Featuring Claudia Franchville (Cummins), Kristen Mori (Houston Astros), Jack Arnold (Capital One), and Haleigh Gronwold (MISO).

++++
<iframe  class="video" width="560" height="315" src="https://www.youtube.com/embed/eOiPzwsd4-s" title="YouTube video /player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

==== career path shaping
"I didn't realize all the opportunities the midwest had for data science."
-- Claudia

"I was ahead of the curve because Purdue was ahead of the curve since they had this learning community."
-- Kristen

"The Data Mine help validate my interests, allowing me to 'shadow' data scientists in industry."
-- Haleigh

"The Data Mine really made me a continuous learner, helping me find what I'm most passionate about."
-- Jack 

==== valuable skills
"Communication [of your work] is often just as important as the math and statistics."
-- Haleigh

"Its incredible that your students are talking to each other about their experiences [with your company] in their dorms."
-- Virginia

"I stepped in as a leader and influencer of that group. That definitely one of the most valuable skills I got, something I now use every day full-time."
-- Jack

"A lot of the projects we faced in The Data Mine gave us experience with those problems were you really have to get creative to find a solution. ... We got experience with real & messy data, and techniques on how to clean it up."
-- Kristen

"The students are jumping into these project "
-- Claudia

==== what should students know?
"Find what motivates you, you'll going to get exactly what you put into."
-- Jack
 
"Confidence comes from trying, have a willingness to learn and ask questions."
-- Haleigh

"Devote time to learning your soft-skills; time-management, communication, leadership."
-- Kristen

"My biggest regret was not joining The Data Mine sooner, I could have learn a lot sooner about the business value."
-- Claudia

==== advice for recent graduates
"Stay curious, adopt a continuous learning mindset."
-- Haleigh

"The stuff that really matter is how to articulate your ideas. How you can understand a large complex business problem, how to propose your solution and share with stakeholders. In other words, the exact stuff you learn in The Data Mine outside of the traditional classroom."
-- Jack

"Don't treat your degree like a fishline, but a foundation."
-- Claudia

"Be confident in yourself and trust in the education you have and the foundation you have made."
-- Kristen

====  favorite Data Mine projects
"Ford: Creating a training dataset based off car manuals, allowing the user to voice-prompt and get human-understandable answers about the vehicle."
-- Jack

"John Deere: Analyzing bio-physical weather parameters to predict corn yield in the midwest."
-- Haleigh

"Cummins: Sediment analysis to analyze warranty technician comments to determine what had failed."
-- Claudia

==== advice for mentors
"Make sure you are scoping project flexibility, have a broad idea but let the students drive using their interest."
-- Haleigh

"The program is a great talent pipeline, we have hired lots of former students that a super great."
-- Haleigh

"Great opportunity to see what students show leadership attributes and step in as the big-influencer that cones up with the design decisions. Keep it open for them because that is what makes it an amazing experience as a student."
-- Jack

"Treat this as a life-long networking opportunity. Don't underestimate your freshman, they might become your best employee in 5 years."
-- Kristen

"The Data Mine in general is a win-win for everyone. For corporate parnters, you get scout students (for talent pipeline) and while getting some analytic projects worked on. For students, they get real-life expsosue in the data science world."
-- Claudia

==== one word to describe Data Mine students
"Driven; impressive that even with their busy class schedules they add [The Data Mine] on top of it."
-- Kristen

"Creative; valuable to get that outside (objective) perspective."
-- Haleigh

"Friendly; interesting in creating life-long relationships"
-- Jack

"Adaptable; often times as mentors we provide feedback and the students are very receptive"
-- Claudia


"Distuptive; bring in a student team can shake things up in a good way"
-- Virginia

== Matthew Skirvin, Microsoft

Matthew Skirvin, Corporate Partner Mentor at Microsoft, shares mentoring best practices at the Monday Mentor Meetings series on June 20, 2022. 

++++
<iframe  class="video" width="560" height="315" src="https://www.youtube.com/embed/WyfJcAX_NiI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

== Mike Douglass, Raytheon

Mike Douglass, Corporate Partner Mentor at Raytheon, shares mentoring best practices at the Monday Mentor Meetings series on June 20, 2022. 
++++
<iframe  class="video" width="560" height="315" src="https://www.youtube.com/embed/NEZA_n_gBRI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

