= Think Summer: Project 3 -- 2024

=== Question 1

Consider only the flights that arrive to Indianapolis (airport code `IND`), i.e., for which Indianapolis is the destination.  What are the 10 most popular origin airports?

=== Question 2

Each airplane has a unique `TailNum`.  Which airplane flew the most flights in 2005?  Hint:  If you strictly look at the `TailNum` values, you will need to ignore the top two results, because they are missing data.

=== Question 3

What is the Distance (in miles) of any individual flight from Seattle (`SEA`) to Los Angeles (`LAX`)?  Hint:  You might paste together the origin and destination airports of the flights.

=== Question 4

How many flights departed from Seattle (`SEA`) and landed in Los Angelex (`LAX`)?

=== Question 5

Which airplane flew the most times from Seattle to Los Angeles?  Hint:  Again, if you strictly look at the `TailNum` values, you will need to ignore the top result, because it has missing data.

=== Question 6

How many flights occurred on Independence Day in 2005?  Hint:  You might paste together the month and day of the flights.

=== Question 7

In which month are the average departure delays the worst?  Hint:  You might use a tapply function.

=== Question 8

Make a `dotchart` that illustrates the data from the previous question (about the average flight delays in each month).

=== Question 9

Which airline carrier had the most flights from Cincinnati to Atlanta in 2005?  (The `UniqueCarrier` is the airline carrier for the flight.)

=== Question 10

Create your own interesting question about the 2005 flight data.  What insights can you find?


