= Think Summer: Project 3 -- 2024

=== Question 1

How many flights departed from Dallas and landed in Denver?  (Please lookup the airport codes for both airports.)  How many flights went the other way, from Denver back to Dallas?

=== Question 2

First consider only the flights that arrive to Cincinnati (airport code `CVG`), i.e., for which Cincinnati is the destination.  What are the 10 most popular origin airports, for travelers coming to Cincinnati from these other cities?  Consider a major airport that is near where you grew up, and answer the same question for that airport.

=== Question 3

Each airplane has a unique `TailNum`.  Which airplane flew the most flights in 2005?  Hint:  If you strictly look at the `TailNum` values, you will need to ignore the top two results, because they are missing data.  (Missing data is part of real life!  Almost every data set in the real world has a ton of missing data!)

=== Question 4

Which airplane flew the most times from Chicago to Indianapolis?  Hint:  Again, if you strictly look at the `TailNum` values, you may need to ignore the top result, because it has missing data.

=== Question 5

What is the Distance (in miles) of any individual flight from Seattle (`SEA`) to Los Angeles (`LAX`)?  Hint:  You might paste together the origin and destination airports of the flights.

=== Question 6

Which airline carrier had the most flights from Atlanta to New York City in 2005?  (The `UniqueCarrier` is the airline carrier for the flight.)  You can consider this question in several ways, since New York City has several airports, but it is recommended to focus on John F. Kennedy International Airport (JFK), LaGuardia Airport (LGA), and Newark International Airport (EWR).

=== Question 7

Pick 5 holidays from 2005 (government, religious, etc., whichever you want), and see how many flights departed on each of those days.  Hint:  You might paste together the month and day of the flights.

=== Question 8

What is the best month for traveling, i.e., the average departure delays are the best during that month?  Hint:  You might use a tapply function.

=== Question 9

Make a `dotchart` that illustrates the data from the previous question (about the average flight delays in each month).

=== Question 10

Create your own interesting question about the 2005 flight data.  What insights can you find?

=== Question 11

How much money was donated in the federal election campaigns (altogether) in 2000 from the state where you grew up?

=== Question 12

From which zip code was the most money donated?  (Where is the zip code in the USA?)  Hint:  Do not worry too much about the fact that people sometimes write 5-digit zip codes and sometimes write 9-digit zip codes.  We are just getting familiar with the data!

=== Question 13

Consider a profession that you are interested in (for instance, "professor" or "engineer" or "scientist").  Spend a little time analyzing how much money was donated by people from that profession, during the 2000 federal election campaigns.

=== Question 14

Create your own interesting question about the 2000 federal election campaign data.  What insights can you find?

