= RCAC

The Rosen Center for Advanced Computing (RCAC) at Purdue University is a resource to provide advanced computation resources and services that support Purdue University students, faculty, and staff. Additionally, RCAC conducts their own research and development to "enhance the capabilities of these resources". 

[NOTE]
====
RCAC's namesake is from Saul Rosen, the former director of Purdue's Computing Center from 1968 to 1987. You can read more about him https://www.rcac.purdue.edu/about/saul-rosen[here].
====

== Resources

https://www.rcac.purdue.edu/[RCAC Home Page]

Home page for the Rosen Center for Advanced Computing (RCAC) at Purdue University. RCAC is a collection of resources and services that support the research and education of students, faculty, and staff at Purdue University. RCAC is a member of the Purdue Research Foundation.

https://www.rcac.purdue.edu/account/myinfo[RCAC Account Information]

Web page displaying your RCAC account information, data depot spaces, and where you can change your default shell for RCAC resources.

https://www.rcac.purdue.edu/compute[RCAC Computing Resources]

Web page with a list of computing resources available to you at RCAC, including but not limited to: xref:scholar.adoc[Scholar], xref:brown.adoc[Brown], and xref:geddes.adoc[Geddes].

https://www.rcac.purdue.edu/storage/depot[RCAC Data Depot]

Web page with information about the data depot.

[quote, , Purdue RCAC]
____
The Data Depot is a high-capacity, fast, reliable and secure data storage service designed, configured and operated for the needs of Purdue researchers in any field and shareable with both on-campus and off-campus collaborators.
____

https://www.rcac.purdue.edu/storage/home[RCAC Home Storage]

Web page showing information about your `$HOME` directory.

https://www.rcac.purdue.edu/storage/scratch[RCAC Scratch Storage]

Web page showing information about the scratch directories on the various clusters.