= Sprint #5

// attributes
:sprint-no: 5
:previous-sprint-no: 4
:start-date: Oct 26
:end-date: Nov 6, 2026
:fall-year: 2026
:spring-year: 2027

// Tasks with due dates 
:pd-due: Wed, Nov 4, 2026 @ 11:59 PM ET
:pd-due-short: Wed, Nov 4, 2026
:report-due: Wed, Nov 11, 2026 @ 11:59 PM ET


//sites
:gradescope-link: link:https://www.gradescope.com/[Gradescope,window=_blank]
:syllabus: xref:spring2026/syllabus.adoc[Syllabus, window=_blank]
:schedule: xref:spring2026/schedule.adoc[Course Schedule, window=_blank]
// attributes
:networking-article: link:https://tmhdc.org/2025/01/28/why-professional-networking-is-so-important/[Why Professional Networking Is So Important,window=_blank]

== Sprint Timeline: **{start-date} - {end-date}**

[cols="3,4,2", options="header"]
|===
| Task | Due Date | Where

| ✓ <<professional-development, Professional Development>>
| **{pd-due}** 
.2+.^| {gradescope-link}

| ✓ <<sprint-report, Sprint #{sprint-no} Report>>
| **{report-due}**
|===

== Sprint Tasks

[[professional-development]]
=== Professional Development

During this sprint, we will take time to reflect on team dynamics and professional growth.  
First, you will explore the importance of *Professional Networking*. Then, you will revisit *Tuckman’s Model of Team Development* to evaluate how your team has progressed.

**When:** Professional Development Due on Gradescope by {pd-due}. Late work will not be accepted. 

.**1. Networking**
[%collapsible%open]
====
**Why:** Networking helps you build meaningful professional relationships that can lead to mentorship, collaboration, and future opportunities.
By learning how to connect authentically with others (peers, mentors, and professionals) you strengthen your communication, leadership, and teamwork skills.
Even while working under NDA, you can practice networking ethically by focusing on conversations about skills, processes, and insights (for example, teamwork or project organization) rather than company-specific information.

**What:** Before you reflect, take a few minutes to read the article {networking-article}. Use the ideas from this article to guide your responses below:

- Reflect on how you currently build and maintain professional connections (in class, The Data Mine, or outside Purdue).  
  If you're not currently building professional connections, think about why and identify small ways you could begin - such as reaching out for guidance, feedback, or advice.
- **Identify one networking action you plan to take** that moves you slightly outside your comfort zone - for example, connecting with a Data Mine staff member, peer from another team, or professional contact to gain new insight or perspective related to your project area.  
- **Explain why you chose this action and what you hope to learn or gain** when you carry it out before the end of Sprint 6.


*Note:* You'll revisit this plan in **Sprint 6** under the *Implementation Check* section, where you'll describe the action you took and what you learned from it.
====


.**2. Tuckman's Model Review**
[%collapsible%open]
====
*Why:* In Sprint 1, you learned about *Tuckman's Model of Team Development* (**Forming, Storming, Norming, Performing, and Adjourning**) a framework that describes how teams evolve as they collaborate over time.  
Now that you have been working together for several sprints, it's time to reflect on your team's current stage.  
Recognizing where your team stands helps you strengthen communication, improve collaboration, and maintain momentum as you prepare for the final presentation.

*What:* Based on your experience with your team, complete the “Sprint 5: Professional Development” assignment in Gradescope by:

- Reflecting on your current team experience and identifying which stage best describes your team now.  
- Providing examples from meetings, communication, or task progress that support your observation.  
- Describing one action step your team can take to move toward (or maintain) the *Performing* stage.

Note: During Sprint 6, the TA will conduct a brief follow-up discussion to compare perspectives, agree on the current stage, and identify one action step.
====

.**3. Team Values Reflection**
[%collapsible%open]
====
*Why:* Team Values (or Team Contract) should help your team maintain shared expectations, communication norms, and collaboration guidelines. Take a moment to revisit your document and reflect on how well your team is living up to these values.

*What:* Review your Team Values/Contract document and reflect on elements you can improve or reinforce as you head into the final sprints.
====


---
[[sprint-report]]
=== Sprint Report
*Why*: The Sprint Report is part of your grade and helps you reflect on your past work. It also gives you the chance to step back, recognize your impact, and track your growth as a teammate and professional. Each section is designed to help you think about your role, your progress, and how you are applying professional skills in a real project setting.

**What**: For Sprint #5, your report has three parts:

 - **Self-Evaluation** - evaluate your presence, contributions, and collaboration using the provided rubrics, and justify your choices.
- **Implementation Check** -shows how you put into action the ideas from Professional Development.
 - **Reflection** - shows how you connect your learning experiences to project practices and the program's broader goals.



**When:** Sprint Report #{sprint-no} Due on Gradescope by {report-due}. Late work will not be accepted. 
