= Team Breakdown

A proper breakdown of a Data Mine Corporate Partners team can aid a team in creating a collaborative and efficient space. Depending on team size, often times a great approach is to break the team down into sub-teams focused on specific parts of the project. For example, with a team size of 15 people and a project focused on software development for a web app, a sub-team approach might include a data architecture group, data science group, data engineering group, front end developmemnt group, and back end devlopment group with a few people on each team. 

[IMPORTANT]
====
These sub-teams should be tailored based on team member preferences and skills in order to prioritize development efficiancy and team well-being. 
====

== How to Form Sub-Teams

The first step in forming the best sub-teams possible for a project is to get to know everyone on the team. Learning about each team member's skills and preferences will help when organizing the team and will ideally allow each team member feel passionately about the work they will be doing on the team. One strategy for collecting this information quickly is to use an online survey, asking about each team members prior experiences, learning preferences, and skills (technical and team focused).

[TIP]
====
Check out a sample survey here: https://purdue.ca1.qualtrics.com/jfe/form/SV_cCM5c0Glm7Qx8qx
====

After working with the team to collect this information, the next step is to form the sub teams. Use the information collected to form groups that are tailored towards team member strengths and learning goals. The goal when forming the sub teams is to create a balance of experience with learning preferences so sub-team members will merge and work well together. For example, pairing more experienced team members with new developers may be a good approach to allow for collaboration and menotorship between two individuals in different points of their professional and academic careers. 

Each sub-team will ultimately be dependent on team size and makeup so creating the best sub-teams will be a challenge to get right immediatley. Thus, after teams are formed, it is important to ask for feedback from your team to ensure each team member is comforatble with their placement. 

[TIP]
====
Do regular check-ins with your team to be confident that everyone on the team enjoys the work they are doing on their sub-team, and it is okay for team-members to move around between sub-teams if preferences do change.
====