= Uploading Data to Purdue

After you've completed the steps to get xref:xsede-setup.adoc[access to Anvil] you're ready to upload data! 

Purdue has lots of https://www.rcac.purdue.edu/knowledge/anvil/storage?all=true[options to connect] to the high performance computing (HPC) systems and we've included the most popular below. 

== Globus

Globus is a file transfer tool that can be used with any OS. 

Globus also offers both online and desktop solutions for file uploading. 

The steps below work with the online version of Globus. 

. Follow the https://docs.globus.org/how-to/get-started/[Globus connection steps] to log-in for the first time.
+
[IMPORTANT]
====
If you don't have an associated organization ID be sure to select `ACCESS CI (formerly XSEDE)` from the dropdown list. 

This should allow you to log-in with your ACCESS ID.

Globus may prompt for additional permissions when connecting to Anvil with the steps below. 
====
+ 
. In the `Collections` line search for `XSEDE Anvil` and select the option that appears. 
** If prompted to authenticate select your XSEDE username and click `Continue`.
. Once you are connected update the `Path` field to `/anvil/projects/tdm/corporate`. 
. Find the folder for your team and double-click to open it. 
** You can navigate within these folders just like you would on your own computer. 
. Identify the location that you'd like to upload to. Once it's found select the `Upload` option from the right-hand menu. 
** You may be prompted to authenticate again. You can select `Continue`. 
. Select the file or folder that you'd like to upload. 
. Globus should automatically upload the data and update you on the status. 
. Once it's uploaded it should be ready for the team to use. 

[TIP]
====
If you have any questions or issues, please contact datamine-help@purdue.edu.
====