= MATLAB

https://www.mathworks.com/products/matlab.html?s_tid=srchtitle[MATLAB] is a programming and numeric computing platform used by millions of engineers and scientists to analyze data, develop algorithms, and create models.

Purdue now receives unlimited use of MATLAB and Simulink products for all students, faculty, staff, researchers, and visitors on and off campus, on any device.  Students, researchers, and faculty may access MATLAB here, https://www.mathworks.com/academia/tah-portal/purdue-university-31484706.html[click here to access Purdue University's MATLAB license].

MATLAB can be used in your research and education activities including:

* https://www.mathworks.com/solutions/data-science.html[Data analysis] and visualization of experiments
* Build
https://www.mathworks.com/products/matlab/app-designer.html[user-friendly apps] to allow simple and intuitive interaction with datasets
* Use advanced algorithms such as with https://www.mathworks.com/solutions/deep-learning.html[Deep Learning] with your research
* Share analysis and results to research colleagues and students with https://www.mathworks.com/products/matlab-drive.html[MATLAB Drive]
* https://www.mathworks.com/academia/courseware.html[Teaching] of engineering and science concepts

MATLAB and can be applied to most areas in science and engineering. Furthermore, MATLAB has an user-driven https://www.mathworks.com/matlabcentral/[active community] with https://www.mathworks.com/matlabcentral/fileexchange/[file contributions], https://www.mathworks.com/matlabcentral/answers/index/[answers] to your questions, insightful https://blogs.mathworks.com/[posts] from MathWorks
engineers, and https://www.mathworks.com/matlabcentral/content/communities.html[links] to external communities.

Being the world’s most natural way to express computational mathematics, MATLAB has wide ranging applications in science and engineering; user contributions from our File Exchange illustrate the various ways of accelerating your research and development in various areas such as:

* https://www.mathworks.com/matlabcentral/fileexchange/?category%5B%5D=support%2Fai-data-s1509[AI,
Data Science, and Statistics]
* https://www.mathworks.com/matlabcentral/fileexchange/?category%5B%5D=support%2Fmathemati212[Mathematics
and Optimization]
* https://www.mathworks.com/matlabcentral/fileexchange/?category%5B%5D=support%2Fimage-pro211[Image
Processing and Computer Vision]
* https://www.mathworks.com/matlabcentral/fileexchange/?category%5B%5D=support%2Fsignal-pr213[Signal
Processing]
* https://www.mathworks.com/matlabcentral/fileexchange/?category%5B%5D=support%2Frobotics-1508[Robotics
and Autonomous Systems]
* https://www.mathworks.com/matlabcentral/fileexchange/?category%5B%5D=support%2Fcontrol-s214[Control
systems]
* https://www.mathworks.com/matlabcentral/fileexchange/?category%5B%5D=support%2Fwireless-5343[Wireless
Communications]

Also available to Purdue is https://www.mathworks.com/products/simulink.html[Simulink], which is a block diagram environment for multidomain simulation and Model-Based Design. Simulink greatly simplifies the simulation and implementation of dynamic systems whose data is analyzed. It supports system-level design, simulation, automatic code generation, and continuous test and verification of embedded systems. Simulink provides a graphical editor, customizable block libraries, and solvers for modeling and  simulating dynamic systems.