= MATLAB Training

== MATLAB Fundamentals (https://www.mathworks.com/learn/online-courses/matlab-fundamentals.html[access here])

This course provides comprehensive training in the MATLAB® technical
computing environment that is geared to make users proficient and
confident in the tool. The course is self-paced and interactive, with
hands-on exercises in the MATLAB tool, short videos, and projects with
automated assessments and feedback. Over 21 hours of content are
provided and divided into short modules – all accessible via the
in-browser learning environment.

Themes of data analysis, visualization, modeling, and programming are
explored throughout the course.

=== Topics include:

* MATLAB user interface
* Working with data files
* Analyzing and visualizing vectors and matrices
* Working with data types
* Writing scripts and functions
* Creating and annotating plots
* Writing programs with branching and loops

A certificate is provided upon completion of the course.

=== Prerequisites

* Completion of https://www.mathworks.com/learn/tutorials/matlab-onramp.html[MATLAB Onramp].

== MATLAB Onramp (https://www.mathworks.com/learn/tutorials/matlab-onramp.html[access here])

Get a quick and high-level overview of MATLAB® basics. The 2-hour course
is self-paced and interactive, with hands-on exercises in the MATLAB
software, short videos, and projects with automated assessments and
feedback. You will learn commonly used features and workflows though an
in-browser learning environment, and work on projects with real-world
applications.

=== Topics include:

* MATLAB commands
* Importing and manipulating data
* Creating and annotating plots
* Scripts and basic programming constructs
* Working with arrays

A certificate is provided upon completion of the course.

=== Prerequisites

* None - No prior programming experience or knowledge of MATLAB is
assumed.


== Other Training Courses Available
Additional training modules are available to Purdue here:

https://www.mathworks.com/products/campus-wide-training.html[Campus-Wide MATLAB Training]

