= Grading

Every two weeks, TAs are required to complete Sprint Report Grading within Gradescope. 

To access Gradescope, navigate to https://www.purdue.edu/innovativelearning/supporting-instruction/instructional-technology/gradescope.aspx and click "Go To Gradescope". Upon log in, navigate to the appropriate course within Gradescope.

[IMPORTANT]
====
Watch this video for an example on how to grade a sprint report: *video missing - to be added*
====

== FAQ
*How often is grading is completed?*

Grading is required by TAs every two weeks. 

*What will TAs be grading?*

TAs will be reviewing and grading their team member's sprint reports. 

*Will a rubric be provided?*

Yes, GradeScope will have a built in rubric for each of the sprint reports. Grading participation is up to the discretion of the TA, however, and additional point deductions can be made on a case-by-case basis. 

*When is grading due?*

Grading is due every two weeks on Sunday nights at 11:59pm. You can find deadlines on the semester schedule.