= Team Labs

Along with  xref:rythms_team_meetings.adoc[Team Meetings], TAs are responsible for leading weekly lab meetings. These lab sessions are about 2 hours long and is the best time to get work done as a team. This time in lab can be used as best fit, but here are a few suggestions.

== Icebreakers
Because labs are about 2 hours long, there is extra time to build team moral and identity by keeping a loose and casual working environment. TAs can begin labs by chatting with the team to ease any stress of the course. Icebreakers are also a great way to create a relaxed environment and allowing the team to get comfortable with each other. 

[TIP]
====
Review team building information at xref:ta_welcoming_env.adoc[Creating a Welcoming Environment]
====

== Working Sessions and Live Coding
The lab session may be the only face to face time that team members get with each other so the majority of the time in lab should be devoted to working sessions where sub-teams can work together. Separating the team in to sub-teams during the lab will make organizing the lab easier as well. 

During the working sessions, TAs are meant to be a resource for the team. TAs should be prepared to problem solve and answer questions from team members. 

== Retrospectives
Labs are also a great time to conduct short sprint retrospectives. Because labs are in person and mentors are not present, team members may feel more comfortable sharing their feedback on the course and project. Devote lab time every two weeks, before starting a new sprint, to having a discussion on:

1. Things that are going well
2. Things that can be improved
3. Large red flags that call for immediate attention

[TIP]
====
Learn more about sprint retrospective at xref:agile-training.adoc[Agile Training]]
====

== FAQs
*How long do labs last?*

Labs are 1 hour and 50 minutes long every week (ex. 9:30am to 11:20am). 

*Is attendance at labs required?*

Yes, students and TAs are required to attend lab meetings. 

*What if during a lab session, a TA does not know how to answer a question?*

Use the support of The Data Mine staff to help answer any difficult questions. It is encouraged to schedule meetings with The Data Mine staff, but sometimes, their office doors may open and willing help right away. 

*Will corporate partner mentors be at labs?*

No, unless there is a special circumstance, corporate partners do not attend lab sessions.  