= Team Meetings

Along with xref:rythms_team_labs.adoc[Team Labs], TAs are responsible for leading weekly, virtual team meetings. Team meetings are 50 minutes long and these meetings are best spent using the time to plan with corporate partner mentors. This meeting is the only regularly scheduled time the team will have with corporate partner mentors so this time is very valuable. 

Use these team meetings to complete the following sprint ceremonies:

== Sprint Planning
Sprint planning should be conducted every two weeks at the start of each sprint. Having the assistance of corporate partner mentors is valuable during sprint planning because they can help keep the project moving in the right direction. Proceed by moving through all sub-teams and assigning tasks to each team member to be completed during the sprint. 

[TIP]
====
Learn more about sprint planning at xref:ROOT:agile-training.adoc[Agile Training]
====

== Sprint Review
Sprint reviews should be conducted every two week as well. These meetings are times for sub teams to present progress updates to corporate partner mentors as well as receive feedback on their work. 

This meeting allows for consistent, technical presentation practice, giving team members new presentation skills and confidence. Sprint reviews are also open and honest discussions between the team and corporate partner mentors. Using this time effectively will aid the project immensely.  

[TIP]
====
Learn more about sprint reviews at xref:ROOT:agile-training.adoc[Agile Training]
====

== FAQs
*How long are team meetings?*

Team Meetings are 50 minutes long (ex. 9:30am to 10:20am).

*Is attendance at team meetings required?*

Yes, students and TAs are required to attend team meetings. 

*Will corporate partner mentors be at team meetings?*

Yes, corporate partners will attend team meetings and are there to help guide the project.  