= Seminar TA Training

== Welcome to The Data Mine Seminar Course!

We are excited to have you on board as a Seminar TA for The Data Mine next year!

This is going to be a long read, so please try to find a bit of focused time to understand all this (fun!) information.

[IMPORTANT]
====
On *August 9, 2023*, you will be added to a Gradescope page to submit proof of your training. It will consist of a couple of short quizzes to ensure that you have read this training material course syllabus and are ready for next semester. 

All quizzes would be due in Gradescope on *August 16, 2023, at 11:59 PM.* 

Proof of FERPA training is also due in Gradescope on *August 16, 2023, at 11:59 PM.* (More about FERPA training in Module 2)
====

== TA Training - Readings

Please complete the readings in the following modules:

* xref:ta_training_module_1.adoc[Module 1]
* xref:ta_training_module_2.adoc[Module 2]
* xref:ta_training_module_3.adoc[Module 3]

== TA Responsibility Overview

TAs are a key part of success in The Data Mine. Your constant support in seminars, grading, and office hours keeps the courses running smoothly. 

The Seminar TA position comprises *three* roles: Student-facing, Grader, or Hybrid TAs.

=== Student-facing TAs
Student-facing TAs are responsible for holding office hours and helping students with their projects.

=== Grader TAs
Grader TAs are responsible for grading student projects and providing feedback.

=== Hybrid TAs
Hybrid TAs are responsible for both student-facing and grading responsibilities. Next semester, only 301 TAs are hybrid.


All TAs should review the upcoming week's projects and solutions to be best prepared to assist students.

You can find a detailed calendar for next semester's weekly project schedule link:https://app.box.com/s/njk0g47rjxmw5bzig0k2mmspnmmencnf[here].

== Set up your GitHub Account
Please ensure you have a GitHub account made with your @purdue.edu email address.

Please share your GitHub usernames *link:https://purdue0-my.sharepoint.com/:x:/g/personal/kabrap_purdue_edu/ERYYpC6A0W9Dld8A7QvZaxsBm37FfqO7QiwPLb1-T72HPw?e=rqd3lh[here]* to get access to TDM Project Repositories.*

// == Set Up ACCESS account
// We are very excited for you to work with us as TAs this year!
 
// During this year working with us, we will use Purdue’s Anvil computing cluster.
 
// **IMPORTANT** To make sure you are ready to go on the first day, please complete ALL of the steps described here; it only takes a few minutes:
// https://the-examples-book.com/data-engineering/rcac/purdue-user-setup

Seminar TAs must submit their hours to link:https://one.purdue.edu/launch-task/all/successfactors-employee?roles=[SuccessFactor] by *Sunday evenings at 11:59 PM.* 

== Monday Seminar

Each Monday, Dr. Ward hosts seminar sessions for all students in the Data Mine to attend. These sessions are held in Hillenbrand Dining Court's atrium. 

The seminar times for Fall 2023 are:

- 8:30-9:30 AM
- 9:30-10:30 AM
- 10:30 -11:30 AM
- 4:30-5:30 PM (Virtual)

For the first four weeks of the semester, we need a few TAs (at least *four* for 101, *two* for 201, and *one* for 301) in each seminar time.

[NOTE]
====
If you attend the seminar, you can log an extra hour in SuccessFactors. It would be in addition to your required office hours.
====

== Office Hours 

**Graders can skip over the office hours section and go to the xref:grading.adoc[Grading] section.**

TAs will choose their office hours times and will be expected to hold their scheduled office hours consistently each week.

We need lots of help on Thursday and Friday. Evenings are much appreciated because we have students all over the world who will need help. Friday evenings are prime time, and we permit more than one TA to work at a time.

Please keep track of how many students come to each of your office hours during the first three weeks of the semester. If needed, we will reshuffle a bit based on popular times after the first four weeks.

- **Office hours _before_ 5:00 PM EST:** Hillenbrand Hall Lobby C100 
- **Office hours _after_ 5:00 PM EST:** Online in Zoom +
- **Office hours on the _weekend_:** Online in Zoom

[IMPORTANT]
====
**Your online Zoom meeting room should always be ON during in-person office hours.**

**You need to have your camera ON in all your Zoom calls.**

The staff will randomly join office hour meetings to ensure this is followed.
====

=== Set up your Zoom meeting room
All TAs should use their official Purdue Zoom meeting room to hold their office hours. Go to https://purdue-edu.zoom.us/ and log in with your Purdue credentials to setup your account. 

Please share the link for your Personal Zoom meeting room *link:https://purdue0-my.sharepoint.com/:x:/g/personal/kabrap_purdue_edu/ERBOmLOevitBqUq6y2Ghx4gBxf3iFlXNyol2A6SNOhKgHQ?e=RkNxTL[here].*

=== Choose your time
When choosing your office hour time slot(s), please consider your schedule and conflicts such as classes.

We encourage all TAs to hold office hours that impact the most students - you should aim to help as many students as you can. 

*Your help during office hours could change a student's day, week, month, or semester!* 

On *August 17*, you will be sent another email in which you will find a link to a spreadsheet to choose your weekly office hours time.

=== Unable to host office hours
If, for a certain day, you are unable to hold office hours, message the Head TA on Teams with a valid conflict and get approval to skip office hours. *If approved*, please post an instructor note in Piazza at least *48 hours before* to all the students

If it is an *emergency* and you cannot do the above in time, message the Head TA on Teams and post an instructor note on Piazza as soon as possible.

== How to Get Paid

Seminar TAs can submit up to 10 hours a week. 

[CAUTION]
====
International students can work a maximum of 20 hours across all jobs.
====

== Look forward to

1. Complete the Syllabus and Academic Integrity Quizzes in Gradescope by *11:59 PM, Aug 16*.
2. Submit proof of FERPA training in Gradescope by *11:59 PM, Aug 16*.
3. Submit your Github username and Zoom meeting room link.
4. Confirm which *mandatory* orientation session you want to attend.
5. Verify you're a part of the TA Teams channel.
6. Look out for an email on *Aug 17* to schedule office hours.

Please send questions to your Head TA via Teams/Email, post in the Seminar TA Teams Channel, or email datamine-help@purdue.edu. 

We look forward to having you onboard as a TA with us this semester!
