# Project 5 Solutions

# Student Name: ........

# Peer Collaborators (if any) and nature of the collaboration ........
# TA help sought (if any) ........
# Online resources used (if any) and weblink for location of resources ........

# 1a (1 pt)
# Comment about method of solution: ........
Solution itself ........ (no hashtag needed; this should be raw R code on this line)
# Output from the solution ........

# 1b (1 pt)
# Comment about method of solution: ........
Solution itself ........ (no hashtag needed; this should be raw R code on this line)
# Output from the solution ........

# 2a (2 pts)
# Comment about method of solution: ........
Solution itself ........ (no hashtag needed; this should be raw R code on this line)
# Output from the solution ........

# 2b (2 pts)
# Comment about method of solution: ........
Solution itself ........ (no hashtag needed; this should be raw R code on this line)
# Output from the solution ........

# 3a (2 pts)
# Comment about method of solution: ........
Solution itself ........ (no hashtag needed; this should be raw R code on this line)
# Output from the solution ........

# 3b (2 pts)
# Comment about method of solution: ........
Solution itself ........ (no hashtag needed; this should be raw R code on this line)
# Output from the solution ........