---
title: "Project 11 Solutions"
output:
  html_document:
    df_print: paged
---

## Student Name: ...

## Peer Collaborators (if any) and nature of the collaboration ...
## TA help sought (if any) ...
## Online resources used (if any) and weblink for location of resources ...

### 1a *(.5 pts)*

```{mysql eval=F}
sql solutions here
```

- 
- 
- 

### 1b *(.5 pts)*
```{mysql eval=F}
# sql statement 1 below this line
# sql statement 2 below this line
```

### 1c *(1 pt)*
Explain the oddity here...

```{mysql eval=F}
sql statement here
```

### 1d *(1 pt)*
Explain what is going on with the oddity here...

```{mysql eval=F}
sql statement here
```

### 1e *(1 pt)*
In which decade were movies (on average) longer? ...

```{mysql eval=F}
sql statement here
```

### 2a *(1 pt)*
```{r eval=T}
r code here
```

### 2b *(1 pt)*
Name of your favorite show and it's id here ...

```{r eval=T}
r code here
```

### 2c *(1 pt)*
```{r eval=T}
r code here
```

### 2d *(1 pt)*
```{r eval=T}
r code here
```

### 2e *(2 pts)*
```{r eval=T}
r code here
```