= `head`

 `head` is a function that returns the first parts of a data set.

 == Examples
 https://www.geeksforgeeks.org/get-the-first-parts-of-a-data-set-in-r-programming-head-function/[Examples Source]

 === How do I display the first 10 lines of a dataset? 

 .Click to see solution
 [%collapsible]
 ====
 [source, R]
 ----
 # R program to illustrate
 # head function
   
 # Calling the head() function to 
 # get the iris demo dataset
 head(iris)
 ----
 [source, R]
 ----
 Sepal.Length Sepal.Width Petal.Length Petal.Width Species
 1          5.1         3.5          1.4         0.2  setosa
 2          4.9         3.0          1.4         0.2  setosa
 3          4.7         3.2          1.3         0.2  setosa
 4          4.6         3.1          1.5         0.2  setosa
 5          5.0         3.6          1.4         0.2  setosa
 6          5.4         3.9          1.7         0.4  setosa
 ----
 The default display for the head equation is 10 rows. However, as shown above, for datasets with less than 10 rows, it will simply display all the rows.
 ====

 === How do I display the first `n` lines of a dataset?

 .Click to see solution
 [%collapsible]
 ====
 [source, R]
 ----
 # R program to illustrate
 # head function
   
 # Calling the head() function to 
 # get the iris demo dataset in
 # 4 rows
 head(iris, 4)
 ----
 [source, R]
 ----
 Sepal.Length Sepal.Width Petal.Length Petal.Width Species
 1          5.1         3.5          1.4         0.2  setosa
 2          4.9         3.0          1.4         0.2  setosa
 3          4.7         3.2          1.3         0.2  setosa
 4          4.6         3.1          1.5         0.2  setosa
 ----
 In this case, the 4 can be replaced with any numerical value to display that number of rows from the dataset.
 ====